##### imports

In [32]:
import utils as ut
import pandas as pd
from datetime import datetime, timedelta
pd.__version__

'2.0.3'

In [33]:
paths = "F:\TFG\datasets\\raw_datasets\\"

#### CHECK DATALAKES

In [44]:
df_v2 = ut.read_data(paths+"datalake.csv")
df_v1 = ut.read_data(paths+"datalake_v1.csv")

In [35]:
df_v1.Date[0]

Timestamp('2000-08-11 00:00:00')

In [29]:
print(df_v1.dtypes['Date'], df_v2.dtypes['Date'])
assert df_v1.dtypes['Date'] == df_v2.dtypes['Date']

datetime64[ns] datetime64[ns]

In [30]:
keys = ['matchId','Div','season','id_H','id_A','HomeTeam','AwayTeam','Date']

In [31]:
df_join = df_v1.merge(df_v2,on=keys,how='outer',suffixes=("_v1","_v2")).set_index('matchId')
df_join

,Unnamed: 0,id_H,id_A,Div,div_order_v1,Date,season,HomeTeam,AwayTeam,FTHG_v1,...,AHW_v2,B365H_v2,B365D_v2,B365A_v2,MaxH_v2,MaxD_v2,MaxA_v2,AvgH_v2,AvgD_v2,AvgA_v2
matchId,,,,,,,,,,,,,,,,,,,,,
0,0.0,8,19,D1,0.0,2000-08-11,T00-01,Dortmund,Hansa Rostock,1,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,2,20,D1,1.0,2000-08-12,T00-01,Bayern Munich,Hertha,4,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,15,35,D1,2.0,2000-08-12,T00-01,Freiburg,Stuttgart,4,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,17,29,D1,3.0,2000-08-12,T00-01,Hamburg,Munich 1860,2,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,23,4,D1,4.0,2000-08-12,T00-01,Kaiserslautern,Bochum,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60000,NaN,258,243,SP2,NaN,2000-06-04,T99-00,Extremadura,Badajoz,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60001,NaN,271,274,SP2,NaN,2000-06-04,T99-00,Las Palmas,Levante,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60002,NaN,277,314,SP2,NaN,2000-06-04,T99-00,Logrones,Villarreal,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60003,NaN,288,297,SP2,NaN,2000-06-04,T99-00,Osasuna,Recreativo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60004,NaN,300,255,SP2,NaN,2000-06-04,T99-00,Salamanca,Eibar,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df_v1.season.unique()

array(['T00-01', 'T01-02', 'T02-03', 'T03-04', 'T04-05', 'T05-06',
       'T06-07', 'T07-08', 'T08-09', 'T09-10', 'T10-11', 'T11-12',
       'T12-13', 'T13-14', 'T14-15', 'T15-16', 'T16-17', 'T17-18',
       'T18-19', 'T19-20', 'T20-21', 'T93-94', 'T94-95', 'T95-96',
       'T96-97', 'T97-98', 'T98-99', 'T99-00'], dtype=object)

In [30]:
df_join.loc[30002]

,id_H,id_A,Div,div_order_v1,Date,season,HomeTeam,AwayTeam,FTHG_v1,FTAG_v1,...,AHW_v2,B365H_v2,B365D_v2,B365A_v2,MaxH_v2,MaxD_v2,MaxA_v2,AvgH_v2,AvgD_v2,AvgA_v2
matchId,,,,,,,,,,,,,,,,,,,,,
30002,150,172,I1,2593.0,2007-09-26,T08-09,Fiorentina,Roma,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30002,159,158,I1,NaN,2006-10-01,T06-07,Messina,Livorno,NaN,NaN,...,NaN,2.3,2.87,3.4,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df_join.index.value_counts()

matchId
30002    2
39023    2
39025    2
39026    2
39027    2
        ..
743      1
742      1
741      1
740      1
60004    1
Name: count, Length: 60005, dtype: int64

#### ADDING WEEKDAY to DATALAKE V1

In [45]:
df_v1.loc[:,'Weekday'] = -1
df_v1

,Unnamed: 0,matchId,id_H,id_A,Div,div_order,Date,season,HomeTeam,AwayTeam,...,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Weekday
0,0,0,8,19,D1,0,2000-08-11,T00-01,Dortmund,Hansa Rostock,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
1,1,1,2,20,D1,1,2000-08-12,T00-01,Bayern Munich,Hertha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
2,2,2,15,35,D1,2,2000-08-12,T00-01,Freiburg,Stuttgart,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
3,3,3,17,29,D1,3,2000-08-12,T00-01,Hamburg,Munich 1860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
4,4,4,23,4,D1,4,2000-08-12,T00-01,Kaiserslautern,Bochum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58541,58541,58541,258,243,SP2,10828,2000-06-04,T99-00,Extremadura,Badajoz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
58542,58542,58542,271,274,SP2,10829,2000-06-04,T99-00,Las Palmas,Levante,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
58543,58543,58543,277,314,SP2,10830,2000-06-04,T99-00,Logrones,Villarreal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
58544,58544,58544,288,297,SP2,10831,2000-06-04,T99-00,Osasuna,Recreativo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
58545,58545,58545,300,255,SP2,10832,2000-06-04,T99-00,Salamanca,Eibar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0

In [46]:
df_v1 = df_v1.drop(columns='Unnamed: 0')
df_v1

,matchId,id_H,id_A,Div,div_order,Date,season,HomeTeam,AwayTeam,FTHG,...,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Weekday
0,0,8,19,D1,0,2000-08-11,T00-01,Dortmund,Hansa Rostock,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
1,1,2,20,D1,1,2000-08-12,T00-01,Bayern Munich,Hertha,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
2,2,15,35,D1,2,2000-08-12,T00-01,Freiburg,Stuttgart,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
3,3,17,29,D1,3,2000-08-12,T00-01,Hamburg,Munich 1860,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
4,4,23,4,D1,4,2000-08-12,T00-01,Kaiserslautern,Bochum,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58541,58541,258,243,SP2,10828,2000-06-04,T99-00,Extremadura,Badajoz,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
58542,58542,271,274,SP2,10829,2000-06-04,T99-00,Las Palmas,Levante,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
58543,58543,277,314,SP2,10830,2000-06-04,T99-00,Logrones,Villarreal,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
58544,58544,288,297,SP2,10831,2000-06-04,T99-00,Osasuna,Recreativo,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
58545,58545,300,255,SP2,10832,2000-06-04,T99-00,Salamanca,Eibar,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0

In [47]:
df_v1.Weekday

0       -1.0
1       -1.0
2       -1.0
3       -1.0
4       -1.0
        ...
58541   -1.0
58542   -1.0
58543   -1.0
58544   -1.0
58545   -1.0
Name: Weekday, Length: 58546, dtype: float64

In [48]:
ut.save_dataframe(df_v1,paths,'datalake_v1.1',encoding='utf-8',date_format="%d/%m/%Y")

### COMPROBACION PAGE RANK

Concuerdan claves del datalake y pagerank?

In [14]:
pagerank = ut.read_data(paths+'page_rank_v2_metadata.csv',date_format="%Y-%m-%d")
pagerank

,matchId,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,pagerank_1_H,pagerank_1_A,pagerank_2_H,pagerank_2_A,pagerank_5_H,pagerank_5_A,pagerank_10_H,pagerank_10_A
0,19,D1,T00-01,2000-09-05,Kaiserslautern,Stuttgart,1,0,H,0.079648,0.753159,0.225720,0.468540,0.264095,0.763595,0.815628,0.649886
1,43,D1,T00-01,2000-09-17,Hertha,Stuttgart,2,0,H,1.000000,0.753159,0.607373,0.468540,0.248699,0.763595,0.758029,0.649886
2,62,D1,T00-01,2000-10-01,Wolfsburg,Stuttgart,2,2,D,0.446847,0.657950,0.453123,0.640639,0.736377,0.811538,0.670230,0.649886
3,113,D1,T00-01,2000-11-18,Kaiserslautern,Freiburg,0,2,A,0.439257,0.301209,0.483791,0.449609,0.636028,0.482604,0.815628,0.646375
4,93,D1,T00-01,2000-11-04,Hamburg,Freiburg,5,0,H,0.466636,0.301209,0.563521,0.449609,0.645970,0.482604,0.605170,0.646375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51762,59904,SP2,T99-00,2000-04-02,Salamanca,Compostela,0.0,0.0,D,0.523640,0.312117,0.625296,0.401977,0.719304,0.613496,0.827149,0.642391
51763,59984,SP2,T99-00,2000-05-28,Eibar,Lleida,2.0,0.0,H,0.464876,0.664487,0.546187,0.652133,0.695865,0.641336,0.682637,0.660066
51764,59962,SP2,T99-00,2000-05-13,Badajoz,Lleida,0.0,0.0,D,0.338101,0.664487,0.416022,0.652133,0.737959,0.641336,0.745584,0.660066
51765,59946,SP2,T99-00,2000-04-30,Salamanca,Lleida,2.0,1.0,H,0.578333,0.664487,0.656746,0.652133,0.719304,0.641336,0.827149,0.660066
51766,59906,SP2,T99-00,2000-04-08,Las Palmas,Lleida,1.0,0.0,H,0.617321,0.469723,0.781961,0.465997,0.881247,0.641336,0.822659,0.660066

In [10]:
keys = ['matchId', 'Div', 'season', 'HomeTeam', 'AwayTeam', 'Date']

In [11]:
print(pagerank.dtypes) 
print()
print(df_v2.dtypes)

matchId                   int64
Div                      object
season                   object
Date             datetime64[ns]
HomeTeam                 object
AwayTeam                 object
FTHG                     object
FTAG                     object
FTR                      object
pagerank_1_H            float64
pagerank_1_A            float64
pagerank_2_H            float64
pagerank_2_A            float64
pagerank_5_H            float64
pagerank_5_A            float64
pagerank_10_H           float64
pagerank_10_A           float64
dtype: object

matchId                int64
id_H                   int64
id_A                   int64
Div                   object
div_order              int64
Date          datetime64[ns]
Weekday                int64
season                object
HomeTeam              object
AwayTeam              object
FTHG                  object
FTAG                  object
FTR                   object
Attendance           float64
Referee               object
HS                    object
AS                    object
HST                   object
AST                   object
HF                    object
AF                    object
HC                    object
AC                    object
HY                    object
AY                    object
HR                    object
AR                    object
HO                   float64
AO                   float64
HHW                  float64
AHW                  float64
B365H                float64
B365D                float64
B365A                float64
MaxH                 float64
MaxD                 float64
MaxA                 float64
AvgH                 float64
AvgD                 float64
AvgA                 float64
dtype: object

In [12]:
df_join = df_v2.merge(pagerank,on=keys,how='outer',suffixes=("_d","_p"),indicator=True).set_index('matchId')
df_join

,id_H,id_A,Div,div_order,Date,Weekday,season,HomeTeam,AwayTeam,FTHG_d,...,FTR_p,pagerank_1_H,pagerank_1_A,pagerank_2_H,pagerank_2_A,pagerank_5_H,pagerank_5_A,pagerank_10_H,pagerank_10_A,_merge
matchId,,,,,,,,,,,,,,,,,,,,,
0,8,19,D1,0,2000-08-11,4,T00-01,Dortmund,Hansa Rostock,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,2,20,D1,1,2000-08-12,5,T00-01,Bayern Munich,Hertha,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,15,35,D1,2,2000-08-12,5,T00-01,Freiburg,Stuttgart,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,17,29,D1,3,2000-08-12,5,T00-01,Hamburg,Munich 1860,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,23,4,D1,4,2000-08-12,5,T00-01,Kaiserslautern,Bochum,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60000,258,243,SP2,11419,2000-06-04,6,T99-00,Extremadura,Badajoz,2.0,...,D,0.456281,0.490016,0.593264,0.531792,0.712466,0.578734,0.734918,0.745584,both
60001,271,274,SP2,11420,2000-06-04,6,T99-00,Las Palmas,Levante,2.0,...,H,0.721121,0.535611,0.735219,0.624106,0.799255,0.647171,0.822659,0.710924,both
60002,277,314,SP2,11421,2000-06-04,6,T99-00,Logrones,Villarreal,1.0,...,H,0.475716,0.616144,0.444662,0.674619,0.540642,0.726894,0.569462,0.760554,both
60003,288,297,SP2,11422,2000-06-04,6,T99-00,Osasuna,Recreativo,2.0,...,H,0.555957,0.401048,0.562026,0.514327,0.684894,0.571581,0.654110,0.674037,both
60004,300,255,SP2,11423,2000-06-04,6,T99-00,Salamanca,Eibar,2.0,...,H,0.625057,0.513373,0.716366,0.543613,0.826565,0.580260,0.827149,0.682637,both

In [30]:
df_join._merge.value_counts()

_merge
both          55671
left_only      4334
right_only        0
Name: count, dtype: int64

Comprobamos los datasets antiguos

In [16]:
pagerank = ut.read_data(paths+'page_rank.csv',date=[])
pagerank

       matchId  pagerank_H  pagerank_A
0            0    0.750032    0.576891
1           55    0.989830    0.576891
2           42    0.737751    0.576891
3          109    0.467613    0.576891
4          135    0.721474    0.576891
...        ...         ...         ...
49049    58092    0.436662    0.541080
49050    58166    0.682582    0.134527
49051    58085    0.535204    0.134527
49052    58017    0.318754    0.446656
49053    57972    0.520126    0.446656

[49054 rows x 3 columns]

In [19]:
df_join = df_v1.merge(pagerank,on='matchId',how='outer',suffixes=("_d","_p"),indicator=True).set_index('matchId')
df_join

,Unnamed: 0,id_H,id_A,Div,div_order,Date,season,HomeTeam,AwayTeam,FTHG,...,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Weekday,pagerank_H,pagerank_A,_merge
matchId,,,,,,,,,,,,,,,,,,,,,
0,0,8,19,D1,0,2000-08-11,T00-01,Dortmund,Hansa Rostock,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.750032,0.576891,both
1,1,2,20,D1,1,2000-08-12,T00-01,Bayern Munich,Hertha,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.989830,0.760343,both
2,2,15,35,D1,2,2000-08-12,T00-01,Freiburg,Stuttgart,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.552579,0.684564,both
3,3,17,29,D1,3,2000-08-12,T00-01,Hamburg,Munich 1860,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.578819,0.721474,both
4,4,23,4,D1,4,2000-08-12,T00-01,Kaiserslautern,Bochum,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.704180,0.518411,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58541,58541,258,243,SP2,10828,2000-06-04,T99-00,Extremadura,Badajoz,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.853941,0.486740,both
58542,58542,271,274,SP2,10829,2000-06-04,T99-00,Las Palmas,Levante,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.552449,0.540121,both
58543,58543,277,314,SP2,10830,2000-06-04,T99-00,Logrones,Villarreal,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.451025,1.000000,both
58544,58544,288,297,SP2,10831,2000-06-04,T99-00,Osasuna,Recreativo,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.678948,0.578648,both
58545,58545,300,255,SP2,10832,2000-06-04,T99-00,Salamanca,Eibar,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.761985,0.517532,both

In [20]:
df_join._merge.value_counts()

_merge
both          49054
left_only      9492
right_only        0
Name: count, dtype: int64

In [31]:
df_join[df_join._merge=='left_only'].groupby(['Div','season']).count()['_merge'].to_frame().reset_index().pivot_table(values='_merge',index='season',columns='Div')

Div        D1     E0     F1     I1    SP1    SP2
season
T00-01   19.0   43.0   22.0    NaN    NaN   79.0
T01-02    NaN   19.0    NaN   29.0    NaN   94.0
T02-03   25.0   37.0   35.0   51.0    NaN   22.0
T03-04    3.0   54.0   22.0   29.0    NaN   49.0
T04-05   24.0   15.0   54.0   60.0    NaN   40.0
T05-06    2.0   29.0    NaN   57.0    NaN   53.0
T06-07    NaN   58.0   28.0   30.0    NaN   61.0
T07-08   25.0    3.0    3.0    NaN    NaN   52.0
T08-09   24.0   54.0   27.0    3.0    NaN   77.0
T09-10    2.0   29.0   28.0    NaN    NaN   76.0
T10-11    NaN   25.0   48.0   25.0    NaN   53.0
T11-12   22.0   50.0   50.0   25.0    1.0   75.0
T12-13   45.0    5.0   28.0   23.0    NaN   54.0
T13-14   22.0   25.0    1.0   23.0    NaN    4.0
T14-15   21.0    NaN    NaN    1.0    NaN   24.0
T15-16   43.0   26.0   47.0   43.0    NaN   24.0
T16-17   21.0    1.0    1.0   21.0    NaN   45.0
T17-18    1.0   49.0   24.0   41.0    NaN   24.0
T18-19    NaN    3.0   23.0    2.0    NaN   22.0
T19-20   21.0    NaN    NaN    NaN    NaN   26.0
T20-21    NaN    NaN    NaN   28.0    NaN    2.0
T93-94  306.0  462.0    NaN  306.0  380.0    NaN
T94-95  306.0  462.0    NaN  306.0  380.0    NaN
T95-96  306.0  380.0    NaN  306.0  462.0    NaN
T96-97  281.0  350.0    NaN  288.0  438.0  358.0
T97-98   92.0  115.0  121.0   63.0   71.0   87.0
T98-99    3.0    3.0    5.0   27.0    NaN   40.0
T99-00   28.0    9.0    6.0    4.0    NaN    7.0