#### imports

In [1]:
import pandas as pd
import numpy as np
from utils import correct_csv, load_json

In [2]:
COLUMNS_TO_KEEP = [
    'Div','Date','Attendance','HomeTeam','AwayTeam','FTHG','FTAG','FTR','HTHG','HTAG','HTR','Referee',
    'HS','AS','HST','AST','HF','AF','HC','AC','HY','AY','HR','AR','HO','AO','HHW','AHW','B365H','B365D','B365A', 'MaxH','MaxD','MaxA','AvgH','AvgD','AvgA'
]

# DATALAKE V1

### constants definition (and testing)

In [23]:
list_leagues = ["D1","SP1","E0","I1","F1"]

dict_encodings = []

In [24]:
path_footdata   ='F:\\TFG\\datasets\\football-data\\'

In [25]:
df = pd.read_csv(path_footdata+'I1_1819.csv')
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

In [26]:
pd.read_csv(path_footdata+'E0_2021.csv').columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG',
       ...
       'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH',
       'MaxCAHA', 'AvgCAHH', 'AvgCAHA'],
      dtype='object', length=106)

In [27]:
pd.read_csv(path_footdata+'E0_2021.csv').columns.to_list()

['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA']

In [28]:
pd.read_csv(path_footdata+'SP1_1819.csv').columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD',
       'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA',
       'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh',
       'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [29]:
pd.read_csv(path_footdata+'D1_1819.csv').columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD',
       'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA',
       'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh',
       'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

## CODE

In [31]:
pd.read_csv(path_footdata+'SP2_0405.csv')

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,GB<2.5,GBAHH,GBAHA,GBAH,LBAHH,LBAHA,LBAH,B365AHH,B365AHA,B365AH
0,SP2,28/08/2004,Eibar,Cadiz,2,1,H,2.0,0.0,H,...,1.51,2.30,1.45,-0.5,NaN,NaN,NaN,NaN,NaN,NaN
1,SP2,28/08/2004,Lleida,Ferrol,1,2,A,0.0,1.0,A,...,1.51,2.25,1.47,-0.5,NaN,NaN,NaN,NaN,NaN,NaN
2,SP2,28/08/2004,Pontevedra,Poli Ejido,0,1,A,0.0,0.0,D,...,1.51,2.25,1.47,-0.5,NaN,NaN,NaN,NaN,NaN,NaN
3,SP2,28/08/2004,Tenerife,Elche,1,0,H,0.0,0.0,D,...,1.61,1.90,1.67,-0.5,NaN,NaN,NaN,NaN,NaN,NaN
4,SP2,29/08/2004,Alaves,Valladolid,2,4,A,0.0,2.0,A,...,1.56,2.30,1.45,-0.5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,SP2,18/06/2005,Pontevedra,Salamanca,4,1,H,2.0,1.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,1.85,0.00
458,SP2,18/06/2005,Tenerife,Cordoba,0,2,A,0.0,1.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.85,2.00,0.25
459,SP2,18/06/2005,Terrassa,Malaga B,1,0,H,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.95,1.90,-0.25
460,SP2,18/06/2005,Valladolid,Elche,1,2,A,1.0,1.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.85,2.00,-0.50
461,SP2,18/06/2005,Xerez,Cadiz,0,2,A,0.0,1.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.95,1.90,0.50

In [32]:
import os
data = pd.DataFrame(data=[],columns=COLUMNS_TO_KEEP)

for elem in os.listdir(path_footdata):
    if (".csv" in elem):
        # print(elem)
        df = pd.read_csv(path_footdata+elem,sep=',',on_bad_lines='error',encoding='latin-1')
        df = df.loc[:, df.columns.isin(COLUMNS_TO_KEEP)]

        season = f"T{elem[-8:-6]}-{elem[-6:-4]}"
        df["season"] = season
        print(df.Div[0],season,df.shape)
        
        data = pd.concat([data,df],axis=0,ignore_index=True)

D1 T00-01 (306, 29)
D1 T01-02 (306, 29)
D1 T02-03 (307, 14)
D1 T03-04 (306, 24)
D1 T04-05 (306, 24)
D1 T05-06 (306, 24)
D1 T06-07 (306, 26)
D1 T07-08 (306, 26)
D1 T08-09 (306, 26)
D1 T09-10 (306, 26)
D1 T10-11 (306, 26)
D1 T11-12 (306, 26)
D1 T12-13 (306, 26)
D1 T13-14 (306, 26)
D1 T14-15 (306, 26)
D1 T15-16 (306, 26)
D1 T16-17 (306, 26)
D1 T17-18 (306, 26)
D1 T18-19 (306, 26)
D1 T19-20 (306, 32)
D1 T20-21 (288, 32)
D1 T93-94 (552, 8)
D1 T94-95 (552, 8)
D1 T95-96 (552, 11)
D1 T96-97 (552, 11)
D1 T97-98 (306, 11)
D1 T98-99 (306, 11)
D1 T99-00 (552, 11)
E0 T00-01 (380, 29)
E0 T01-02 (380, 29)
E0 T02-03 (380, 27)
E0 T03-04 (380, 27)
E0 T04-05 (380, 27)
E0 T05-06 (380, 27)
E0 T06-07 (380, 27)
E0 T07-08 (380, 27)
E0 T08-09 (380, 27)
E0 T09-10 (380, 27)
E0 T10-11 (380, 27)
E0 T11-12 (380, 27)
E0 T12-13 (380, 27)
E0 T13-14 (380, 27)
E0 T14-15 (381, 27)
E0 T15-16 (380, 27)
E0 T16-17 (380, 27)
E0 T17-18 (380, 27)
E0 T18-19 (380, 27)
E0 T19-20 (380, 33)
E0 T20-21 (350, 33)
E0 T93-94 (552, 8)
E0 T94-95 (552, 8)
E0 T95-96 (552, 11)
E0 T96-97 (552, 11)
E0 T97-98 (380, 11)
E0 T98-99 (380, 11)
E0 T99-00 (552, 11)
F1 T00-01 (306, 11)
F1 T01-02 (306, 11)
F1 T02-03 (380, 14)
F1 T03-04 (380, 14)
F1 T04-05 (380, 14)
F1 T05-06 (380, 22)
F1 T06-07 (380, 24)
F1 T07-08 (380, 26)
F1 T08-09 (380, 26)
F1 T09-10 (380, 26)
F1 T10-11 (380, 26)
F1 T11-12 (380, 26)
F1 T12-13 (380, 26)
F1 T13-14 (381, 26)
F1 T14-15 (380, 26)
F1 T15-16 (381, 26)
F1 T16-17 (380, 26)
F1 T17-18 (380, 26)
F1 T18-19 (380, 26)
F1 T19-20 (279, 32)
F1 T20-21 (380, 32)
F1 T97-98 (306, 11)
F1 T98-99 (552, 11)
F1 T99-00 (552, 11)
I1 T00-01 (306, 11)
I1 T01-02 (306, 11)
I1 T02-03 (315, 14)
I1 T03-04 (306, 14)
I1 T04-05 (380, 14)
I1 T05-06 (380, 27)
I1 T06-07 (380, 27)
I1 T07-08 (380, 26)
I1 T08-09 (380, 26)
I1 T09-10 (380, 26)
I1 T10-11 (380, 26)
I1 T11-12 (380, 26)
I1 T12-13 (383, 26)
I1 T13-14 (380, 26)
I1 T14-15 (381, 26)
I1 T15-16 (381, 26)
I1 T16-17 (380, 26)
I1 T17-18 (380, 26)
I1 T18-19 (380, 26)
I1 T19-20 (380, 32)
I1 T20-21 (358, 32)
I1 T93-94 (552, 8)
I1 T94-95 (552, 8)
I1 T95-96 (552, 11)
I1 T96-97 (552, 11)
I1 T97-98 (306, 11)
I1 T98-99 (306, 11)
I1 T99-00 (552, 11)
SP1 T00-01 (380, 11)
SP1 T01-02 (380, 11)
SP1 T02-03 (380, 14)
SP1 T03-04 (380, 14)
SP1 T04-05 (380, 14)
SP1 T05-06 (380, 26)
SP1 T06-07 (380, 26)
SP1 T07-08 (380, 26)
SP1 T08-09 (380, 26)
SP1 T09-10 (380, 26)
SP1 T10-11 (380, 26)
SP1 T11-12 (380, 26)
SP1 T12-13 (380, 26)
SP1 T13-14 (380, 26)
SP1 T14-15 (380, 26)
SP1 T15-16 (380, 26)
SP1 T16-17 (380, 26)
SP1 T17-18 (380, 26)
SP1 T18-19 (380, 26)
SP1 T19-20 (380, 32)
SP1 T20-21 (380, 32)
SP1 T93-94 (552, 8)
SP1 T94-95 (552, 8)
SP1 T95-96 (552, 11)
SP1 T96-97 (552, 11)
SP1 T97-98 (380, 11)
SP1 T98-99 (380, 11)
SP1 T99-00 (552, 11)
SP2 T00-01 (462, 11)
SP2 T01-02 (462, 11)
SP2 T02-03 (462, 14)
SP2 T03-04 (462, 14)
SP2 T04-05 (462, 14)
SP2 T05-06 (462, 14)
SP2 T06-07 (462, 14)
SP2 T07-08 (462, 14)
SP2 T08-09 (462, 14)
SP2 T09-10 (462, 14)
SP2 T10-11 (462, 14)
SP2 T11-12 (462, 14)
SP2 T12-13 (464, 14)
SP2 T13-14 (463, 14)
SP2 T14-15 (462, 14)
SP2 T15-16 (462, 14)
SP2 T16-17 (462, 14)
SP2 T17-18 (462, 26)
SP2 T18-19 (462, 26)
SP2 T19-20 (462, 32)
SP2 T20-21 (418, 32)
SP2 T96-97 (552, 8)
SP2 T97-98 (462, 11)
SP2 T98-99 (462, 11)
SP2 T99-00 (552, 11)

In [45]:
data.Date.dt.weekday

0        4.0
1        5.0
2        5.0
3        5.0
4        5.0
        ...
64627    NaN
64628    NaN
64629    NaN
64630    NaN
64631    NaN
Name: Date, Length: 64632, dtype: float64

In [47]:
data
data['Date'] = pd.to_datetime(data['Date'],dayfirst=True)
data['Weekday'] = data.Date.dt.weekday
data = data[data.Date.isna()==False]
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64537,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6
64538,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6
64539,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6
64540,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6
64541,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6

In [48]:
data.query("Div=='SP1' and season=='T00-01' and (HomeTeam=='Sociedad' or AwayTeam=='Sociedad')").sort_values("Date")

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday
41446,SP1,2000-09-09,NaN,Sociedad,Santander,2,2,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41459,SP1,2000-09-17,NaN,Celta,Sociedad,4,1,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41466,SP1,2000-09-23,NaN,Sociedad,La Coruna,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41485,SP1,2000-10-14,NaN,Sociedad,Barcelona,0,6,A,0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41492,SP1,2000-10-18,NaN,Espanol,Sociedad,1,2,A,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,2
41500,SP1,2000-10-22,NaN,Vallecano,Sociedad,4,1,H,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41511,SP1,2000-10-29,NaN,Sociedad,Real Madrid,1,4,A,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41514,SP1,2000-11-01,NaN,Alaves,Sociedad,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,2
41530,SP1,2000-11-05,NaN,Sociedad,Mallorca,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41538,SP1,2000-11-12,NaN,Oviedo,Sociedad,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41550,SP1,2000-11-19,NaN,Sociedad,Numancia,4,1,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41561,SP1,2000-11-26,NaN,Valladolid,Sociedad,2,1,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41569,SP1,2000-12-03,NaN,Sociedad,Las Palmas,1,1,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41574,SP1,2000-12-09,NaN,Valencia,Sociedad,2,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41584,SP1,2000-12-16,NaN,Sociedad,Villarreal,0,2,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41597,SP1,2000-12-20,NaN,Malaga,Sociedad,3,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,2
41608,SP1,2001-01-07,NaN,Sociedad,Zaragoza,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41618,SP1,2001-01-14,NaN,Sociedad,Ath Bilbao,0,2,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41628,SP1,2001-01-21,NaN,Osasuna,Sociedad,1,1,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41640,SP1,2001-01-28,NaN,Santander,Sociedad,1,4,A,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41650,SP1,2001-02-04,NaN,Sociedad,Celta,2,2,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41654,SP1,2001-02-10,NaN,La Coruna,Sociedad,4,1,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41670,SP1,2001-02-18,NaN,Sociedad,Espanol,2,1,H,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41676,SP1,2001-02-25,NaN,Barcelona,Sociedad,3,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41685,SP1,2001-03-03,NaN,Sociedad,Vallecano,2,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41700,SP1,2001-03-11,NaN,Real Madrid,Sociedad,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41709,SP1,2001-03-18,NaN,Sociedad,Alaves,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41719,SP1,2001-04-01,NaN,Mallorca,Sociedad,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41730,SP1,2001-04-08,NaN,Sociedad,Oviedo,3,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41740,SP1,2001-04-15,NaN,Numancia,Sociedad,3,3,D,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41749,SP1,2001-04-22,NaN,Sociedad,Valladolid,3,1,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41758,SP1,2001-04-29,NaN,Las Palmas,Sociedad,2,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41765,SP1,2001-05-05,NaN,Sociedad,Valencia,1,2,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41774,SP1,2001-05-12,NaN,Villarreal,Sociedad,1,3,A,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5
41789,SP1,2001-05-20,NaN,Sociedad,Malaga,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41802,SP1,2001-05-27,NaN,Zaragoza,Sociedad,1,1,D,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41804,SP1,2001-06-10,NaN,Ath Bilbao,Sociedad,1,3,A,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6
41821,SP1,2001-06-17,NaN,Sociedad,Osasuna,0,1,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,6

In [49]:
data.sort_values("Date").groupby(["Div", "season"]).agg({
    "Date": [("min_date", "min"), ("max_date", "max")]
}).loc['F1']

             Date
         min_date   max_date
season
T00-01 2000-07-28 2001-05-19
T01-02 2001-07-27 2002-05-04
T02-03 2002-08-02 2003-05-24
T03-04 2003-08-01 2004-05-23
T04-05 2004-08-06 2005-05-28
T05-06 2005-07-29 2006-05-13
T06-07 2006-08-04 2007-05-26
T07-08 2007-08-04 2008-05-17
T08-09 2008-08-09 2009-05-30
T09-10 2009-08-08 2010-05-15
T10-11 2010-08-07 2011-05-29
T11-12 2011-08-06 2012-05-20
T12-13 2012-08-10 2013-05-26
T13-14 2013-08-09 2014-05-17
T14-15 2014-08-08 2015-05-23
T15-16 2015-08-07 2016-05-14
T16-17 2016-08-12 2017-05-20
T17-18 2017-08-04 2018-05-19
T18-19 2018-08-10 2019-05-24
T19-20 2019-08-09 2020-03-08
T20-21 2020-08-21 2021-05-23
T97-98 1997-08-01 1998-05-09
T98-99 1998-08-07 1999-05-29
T99-00 1999-07-30 2000-05-13

In [50]:
data['div_order'] = data.groupby(['Div']).cumcount()
data.groupby(['Div']).div_order.max()
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday,div_order
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4,0
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,1
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,2
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,3
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64537,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11419
64538,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11420
64539,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11421
64540,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11422
64541,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11423

In [51]:
# data['matchId'] = data.Div + data.div_order.astype(str).map(lambda x: x.zfill(5))
data['matchId'] = np.arange(len(data))
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday,div_order,matchId
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4,0,0
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,1,1
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,2,2
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,3,3
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64537,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11419,60000
64538,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11420,60001
64539,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11421,60002
64540,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11422,60003
64541,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11423,60004

In [52]:
data.groupby(['Div','season']).Date.count().reset_index(level=1).pivot_table(columns='Div',index='season')

         Date
Div        D1     E0     F1     I1    SP1    SP2
season
T00-01  306.0  380.0  306.0  306.0  380.0  462.0
T01-02  306.0  380.0  306.0  306.0  380.0  462.0
T02-03  306.0  380.0  380.0  306.0  380.0  462.0
T03-04  306.0  380.0  380.0  306.0  380.0  462.0
T04-05  306.0  380.0  380.0  380.0  380.0  462.0
T05-06  306.0  380.0  380.0  380.0  380.0  462.0
T06-07  306.0  380.0  380.0  380.0  380.0  462.0
T07-08  306.0  380.0  380.0  380.0  380.0  462.0
T08-09  306.0  380.0  380.0  380.0  380.0  462.0
T09-10  306.0  380.0  380.0  380.0  380.0  462.0
T10-11  306.0  380.0  380.0  380.0  380.0  462.0
T11-12  306.0  380.0  380.0  380.0  380.0  462.0
T12-13  306.0  380.0  380.0  380.0  380.0  462.0
T13-14  306.0  380.0  380.0  380.0  380.0  462.0
T14-15  306.0  380.0  380.0  380.0  380.0  462.0
T15-16  306.0  380.0  380.0  380.0  380.0  462.0
T16-17  306.0  380.0  380.0  380.0  380.0  462.0
T17-18  306.0  380.0  380.0  380.0  380.0  462.0
T18-19  306.0  380.0  380.0  380.0  380.0  462.0
T19-20  306.0  380.0  279.0  380.0  380.0  462.0
T20-21  288.0  350.0  380.0  358.0  380.0  418.0
T93-94  306.0  462.0    NaN  306.0  380.0    NaN
T94-95  306.0  462.0    NaN  306.0  380.0    NaN
T95-96  306.0  380.0    NaN  306.0  462.0    NaN
T96-97  306.0  380.0    NaN  306.0  462.0  380.0
T97-98  306.0  380.0  306.0  306.0  380.0  462.0
T98-99  306.0  380.0  306.0  306.0  380.0  462.0
T99-00  306.0  380.0  306.0  306.0  380.0  462.0

In [53]:
# data['matchId'] = data.index
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday,div_order,matchId
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4,0,0
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,1,1
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,2,2
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,3,3
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64537,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11419,60000
64538,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11420,60001
64539,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11421,60002
64540,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11422,60003
64541,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11423,60004

In [54]:
dict_teams = {
    "M'Gladbach":"M'gladbach",
    "Extremadura UD":"Extremadura",
    "Orense":"Ourense",
    "Villareal":"Villarreal"
}

data["HomeTeam"] = data["HomeTeam"].apply(lambda t: dict_teams.get(t,t))
data["AwayTeam"] = data["AwayTeam"].apply(lambda t: dict_teams.get(t,t))
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday,div_order,matchId
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4,0,0
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,1,1
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,2,2
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,3,3
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64537,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11419,60000
64538,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11420,60001
64539,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11421,60002
64540,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11422,60003
64541,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6,11423,60004

In [55]:
teams_id = data[['Div','HomeTeam']].drop_duplicates().sort_values(['Div','HomeTeam'])
teams_id["AwayTeam"] = teams_id.HomeTeam
teams_id['id'] = np.arange(len(teams_id))
# teams_id = teams_id.set_index(["Div","HomeTeam"])
# teams_id = teams_id.to_dict()['id']
teams_id

       Div       HomeTeam       AwayTeam   id
1847    D1         Aachen         Aachen    0
3368    D1       Augsburg       Augsburg    1
1       D1  Bayern Munich  Bayern Munich    2
618     D1      Bielefeld      Bielefeld    3
11      D1         Bochum         Bochum    4
...    ...            ...            ...  ...
55730  SP2     Vecindario     Vecindario  313
58489  SP2     Villarreal     Villarreal  314
57107  SP2   Villarreal B   Villarreal B  315
53415  SP2          Xerez          Xerez  316
53877  SP2       Zaragoza       Zaragoza  317

[318 rows x 4 columns]

In [56]:
teams_id[teams_id.id==288]
# teams_id[teams_id.HomeTeam=="Extremadura"]

       Div HomeTeam AwayTeam   id
59416  SP2  Osasuna  Osasuna  288

In [57]:
cols = ['Div','HomeTeam']
data["id_H"] = data.set_index(cols).merge(teams_id[[*cols,'id']],on=cols,how='left').id.to_list()
cols = ['Div','AwayTeam']
data["id_A"] = data.set_index(cols).merge(teams_id[[*cols,'id']],on=cols,how='left').id.to_list()

data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,MaxA,AvgH,AvgD,AvgA,season,Weekday,div_order,matchId,id_H,id_A
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,T00-01,4,0,0,8,19
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,T00-01,5,1,1,2,20
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,T00-01,5,2,2,15,35
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,T00-01,5,3,3,17,29
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,T00-01,5,4,4,23,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64537,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,T99-00,6,11419,60000,258,243
64538,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,T99-00,6,11420,60001,271,274
64539,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,T99-00,6,11421,60002,277,314
64540,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,T99-00,6,11422,60003,288,297
64541,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,T99-00,6,11423,60004,300,255

In [59]:
cols_metadata = ['matchId','id_H', 'id_A','Div','div_order','Date','Weekday','season','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR','Attendance','Referee']
cols_features = ['HS', 'AS', 'HST', 'AST', 'HF','AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR','HO','AO','HHW','AHW']
cols_bets     = ['B365H', 'B365D', 'B365A','MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA']

In [60]:
data = data[[*cols_metadata,*cols_features,*cols_bets]]

In [61]:
data

,matchId,id_H,id_A,Div,div_order,Date,Weekday,season,HomeTeam,AwayTeam,...,AHW,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,0,8,19,D1,0,2000-08-11,4,T00-01,Dortmund,Hansa Rostock,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,20,D1,1,2000-08-12,5,T00-01,Bayern Munich,Hertha,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15,35,D1,2,2000-08-12,5,T00-01,Freiburg,Stuttgart,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17,29,D1,3,2000-08-12,5,T00-01,Hamburg,Munich 1860,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23,4,D1,4,2000-08-12,5,T00-01,Kaiserslautern,Bochum,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64537,60000,258,243,SP2,11419,2000-06-04,6,T99-00,Extremadura,Badajoz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64538,60001,271,274,SP2,11420,2000-06-04,6,T99-00,Las Palmas,Levante,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64539,60002,277,314,SP2,11421,2000-06-04,6,T99-00,Logrones,Villarreal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64540,60003,288,297,SP2,11422,2000-06-04,6,T99-00,Osasuna,Recreativo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64541,60004,300,255,SP2,11423,2000-06-04,6,T99-00,Salamanca,Eibar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
data[["id_H","id_A","Date"]].drop_duplicates().shape, data.shape

((60005, 3), (60005, 40))

In [63]:
dup_matches = data[["matchId","id_H","id_A","Date"]].groupby(["id_H","id_A","Date"]).count()
dup_matches = dup_matches[dup_matches.matchId>1].drop("matchId",axis=1).reset_index()
dup_matches

Empty DataFrame
Columns: [id_H, id_A, Date]
Index: []

In [64]:
dup_matches.merge(data,on=["id_H","id_A","Date"],how='left').sort_values(["id_H","id_A","Date"])

Empty DataFrame
Columns: [matchId, id_H, id_A, Div, div_order, Date, Weekday, season, HomeTeam, AwayTeam, FTHG, FTAG, FTR, Attendance, Referee, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR, HO, AO, HHW, AHW, B365H, B365D, B365A, MaxH, MaxD, MaxA, AvgH, AvgD, AvgA]
Index: []

[0 rows x 40 columns]

In [65]:
data.to_csv('F:\\TFG\\datasets\\raw_datasets\\datalake.csv',sep=';',decimal=',',encoding='utf-8',date_format="%d/%m/%Y",index=False)

In [71]:
pd.read_csv('F:\\TFG\\datasets\\raw_datasets\\datalake.csv',sep=';',decimal=',')

<ipython-input-71-b50f7ac4607d>:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('F:\\TFG\\datasets\\raw_datasets\\datalake.csv',sep=';',decimal=',')

,matchId,id_H,id_A,Div,div_order,Date,Weekday,season,HomeTeam,AwayTeam,...,AHW,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,0,8,19,D1,0,11/08/2000,4,T00-01,Dortmund,Hansa Rostock,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,20,D1,1,12/08/2000,5,T00-01,Bayern Munich,Hertha,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15,35,D1,2,12/08/2000,5,T00-01,Freiburg,Stuttgart,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17,29,D1,3,12/08/2000,5,T00-01,Hamburg,Munich 1860,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23,4,D1,4,12/08/2000,5,T00-01,Kaiserslautern,Bochum,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60000,60000,258,243,SP2,11419,04/06/2000,6,T99-00,Extremadura,Badajoz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60001,60001,271,274,SP2,11420,04/06/2000,6,T99-00,Las Palmas,Levante,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60002,60002,277,314,SP2,11421,04/06/2000,6,T99-00,Logrones,Villarreal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60003,60003,288,297,SP2,11422,04/06/2000,6,T99-00,Osasuna,Recreativo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60004,60004,300,255,SP2,11423,04/06/2000,6,T99-00,Salamanca,Eibar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# DATALAKE V2

### constants definition (and testing)

In [3]:
path_footdata   ='F:\\TFG\\datasets\\football-data\\cache\\'

In [4]:
# excluimos la liga belga ('B1') por su extraña estructura de liga regular + play-offs

list_leagues = ["E1","T1","P1","N1","SP2"] + ["D1","SP1","E0","I1","F1"]

dict_encodings = []

## CODE

In [5]:
import os
data = pd.DataFrame(data=[],columns=COLUMNS_TO_KEEP)

for elem in os.listdir(path_footdata):
    # if (".csv" in elem) and (elem.split('_')[0] in list_leagues):
    if (".csv" in elem):
        # print(elem)
        try:
            df = pd.read_csv(path_footdata+elem,sep=',',on_bad_lines='error',encoding='latin-1')
        except Exception as e:
            print(print(elem,e))
            df = correct_csv(path_footdata+elem,path_footdata+'corrected\\'+elem)
        df = df.loc[:, df.columns.isin(COLUMNS_TO_KEEP)]

        season = f"T{elem[-8:-6]}-{elem[-6:-4]}"
        df["season"] = season
        print(df.Div[0],season,df.shape)
        
        data = pd.concat([data,df],axis=0,ignore_index=True)

B1 T00-01 (306, 11)
B1 T01-02 (306, 11)
B1_0203.csv Error tokenizing data. C error: Expected 27 fields in line 113, saw 28

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\B1_0203.csv
B1 T02-03 (274, 14)
B1 T03-04 (306, 14)
B1_0405.csv Error tokenizing data. C error: Expected 44 fields in line 49, saw 76

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\B1_0405.csv
B1 T04-05 (306, 14)
B1 T05-06 (306, 14)

B1 T06-07 (306, 14)
B1 T07-08 (306, 14)
B1 T08-09 (306, 14)
B1 T09-10 (210, 14)
B1 T10-11 (240, 14)
B1 T11-12 (240, 14)
B1 T12-13 (240, 14)
B1 T13-14 (240, 14)
B1 T14-15 (240, 14)
B1 T15-16 (240, 14)
B1 T16-17 (240, 14)
B1 T17-18 (240, 24)
B1 T18-19 (240, 24)
B1 T19-20 (232, 32)
B1 T20-21 (306, 32)
B1 T21-22 (306, 32)
B1 T22-23 (306, 32)
B1 T23-24 (312, 32)
B1 T95-96 (552, 11)
B1 T96-97 (552, 11)
B1 T97-98 (306, 11)
B1 T98-99 (552, 11)
B1 T99-00 (552, 11)
D1 T21-22 (306, 32)
D1 T22-23 (306, 32)
D1 T23-24 (306, 32)
E0 T21-22 (380, 33)
E0 T22-23 (380, 33)
E0 T23-24 (380, 33)
E1 T00-01 (552, 29)
E1 T01-02 (552, 29)
E1_0203.csv Error tokenizing data. C error: Expected 48 fields in line 369, saw 49

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_0203.csv
E1 T02-03 (552, 27)
E1 T03-04 (552, 27)
E1_0405.csv Error tokenizing data. C error: Expected 57 fields in line 97, saw 61

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_0405.csv
E1 T04-05 (552, 27)
E1 T05-06 (552, 27)
E1 T06-07 (552, 27)
E1 T07-08 (552, 27)
E1 T08-09 (552, 27)
E1 T09-10 (552, 27)
E1 T10-11 (552, 27)
E1 T11-12 (552, 27)
E1 T12-13 (552, 26)
E1 T13-14 (552, 27)
E1 T14-15 (553, 27)
E1 T15-16 (552, 27)
E1 T16-17 (552, 27)
E1 T17-18 (552, 27)
E1 T18-19 (552, 27)
E1 T19-20 (552, 33)
E1 T20-21 (552, 33)
E1 T21-22 (552, 33)
E1 T22-23 (552, 33)
E1 T23-24 (552, 33)
E1_9394.csv Error tokenizing data. C error: Expected 28 fields in line 17, saw 45

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_9394.csv
E1 T93-94 (552, 8)
E1_9495.csv Error tokenizing data. C error: Expected 28 fields in line 17, saw 45

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_9495.csv
E1 T94-95 (552, 8)
E1_9596.csv Error tokenizing data. C error: Expected 28 fields in line 17, saw 45

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_9596.csv
E1 T95-96 (552, 8)
E1_9697.csv Error tokenizing data. C error: Expected 28 fields in line 17, saw 45

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_9697.csv
E1 T96-97 (552, 8)
E1_9798.csv Error tokenizing data. C error: Expected 21 fields in line 17, saw 38

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_9798.csv
E1 T97-98 (552, 11)
E1_9899.csv Error tokenizing data. C error: Expected 21 fields in line 17, saw 38

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_9899.csv
E1 T98-99 (552, 11)
E1_9900.csv Error tokenizing data. C error: Expected 21 fields in line 17, saw 38

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\E1_9900.csv
E1 T99-00 (552, 11)
F1 T21-22 (380, 32)
F1 T22-23 (380, 32)
F1 T23-24 (306, 32)
I1 T21-22 (380, 32)
I1 T22-23 (380, 32)
I1 T23-24 (380, 32)
N1 T00-01 (306, 11)
N1 T01-02 (306, 11)
N1_0203.csv Error tokenizing data. C error: Expected 27 fields in line 97, saw 29

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\N1_0203.csv
N1 T02-03 (306, 14)
N1 T03-04 (306, 14)
N1_0405.csv Error tokenizing data. C error: Expected 47 fields in line 65, saw 49

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\N1_0405.csv
N1 T04-05 (306, 14)
N1 T05-06 (306, 14)
N1 T06-07 (306, 14)
N1_0708.csv Error tokenizing data. C error: Expected 58 fields in line 145, saw 61

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\N1_0708.csv
N1 T07-08 (306, 14)
N1 T08-09 (306, 14)
N1 T09-10 (306, 14)
N1 T10-11 (306, 14)
N1 T11-12 (306, 14)
N1 T12-13 (309, 14)
N1 T13-14 (306, 14)
N1 T14-15 (306, 14)
N1 T15-16 (306, 14)
N1 T16-17 (306, 14)
N1 T17-18 (306, 26)
N1 T18-19 (306, 26)
N1 T19-20 (232, 32)
N1 T20-21 (306, 32)
N1 T21-22 (306, 32)
N1 T22-23 (306, 32)
N1 T23-24 (306, 32)
N1 T93-94 (552, 8)
N1 T94-95 (552, 8)
N1 T95-96 (552, 8)
N1 T96-97 (552, 8)
N1 T97-98 (306, 11)
N1 T98-99 (552, 11)
N1 T99-00 (552, 11)
P1 T00-01 (306, 11)
P1 T01-02 (306, 11)
P1_0203.csv Error tokenizing data. C error: Expected 27 fields in line 97, saw 29

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\P1_0203.csv
P1 T02-03 (306, 14)
P1_0304.csv Error tokenizing data. C error: Expected 47 fields in line 177, saw 50

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\P1_0304.csv
P1 T03-04 (306, 14)
P1 T04-05 (306, 14)
P1 T05-06 (306, 14)
P1 T06-07 (240, 14)
P1_0708.csv Error tokenizing data. C error: Expected 58 fields in line 113, saw 61

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\P1_0708.csv
P1 T07-08 (240, 14)
P1 T08-09 (240, 14)
P1 T09-10 (240, 14)
P1 T10-11 (240, 14)
P1 T11-12 (240, 14)
P1 T12-13 (241, 14)
P1 T13-14 (240, 14)
P1 T14-15 (307, 14)
P1 T15-16 (307, 14)
P1 T16-17 (306, 14)
P1 T17-18 (306, 26)
P1 T18-19 (306, 26)
P1 T19-20 (306, 32)
P1 T20-21 (306, 32)
P1 T21-22 (306, 32)
P1 T22-23 (306, 32)
P1 T23-24 (306, 32)
P1 T94-95 (552, 8)
P1 T95-96 (552, 8)
P1 T96-97 (552, 8)
P1 T97-98 (306, 8)
P1 T98-99 (552, 11)
P1 T99-00 (552, 11)
SP1 T21-22 (380, 32)
SP1 T22-23 (380, 32)
SP1 T23-24 (380, 32)
SP2 T21-22 (462, 32)
SP2 T22-23 (462, 32)
SP2 T23-24 (462, 32)
T1 T00-01 (306, 11)
T1 T01-02 (306, 11)
T1_0203.csv Error tokenizing data. C error: Expected 30 fields in line 17, saw 32

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\T1_0203.csv
T1 T02-03 (306, 14)
T1 T03-04 (306, 14)
T1 T04-05 (306, 14)
T1 T05-06 (306, 14)
T1_0607.csv Error tokenizing data. C error: Expected 55 fields in line 209, saw 63

None
Corrected file saved to F:\TFG\datasets\football-data\cache\corrected\T1_0607.csv
T1 T06-07 (306, 14)
T1 T07-08 (306, 14)
T1 T08-09 (306, 14)
T1 T09-10 (272, 14)
T1 T10-11 (306, 14)
T1 T11-12 (306, 14)
T1 T12-13 (307, 14)
T1 T13-14 (308, 14)
T1 T14-15 (307, 14)
T1 T15-16 (311, 14)
T1 T16-17 (306, 14)
T1 T17-18 (306, 26)
T1 T18-19 (306, 26)
T1 T19-20 (306, 32)
T1 T20-21 (420, 32)
T1 T21-22 (380, 32)
T1 T22-23 (342, 32)
T1 T23-24 (380, 32)
T1 T94-95 (552, 8)
T1 T95-96 (552, 8)
T1 T96-97 (552, 8)
T1 T97-98 (306, 8)
T1 T98-99 (552, 8)
T1 T99-00 (552, 11)

In [6]:
data[data[["HomeTeam","AwayTeam","Date"]].duplicated()].sort_values(["HomeTeam","AwayTeam"])

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season
885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T02-03
6860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T95-96
6861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T95-96
6862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T95-96
6863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T95-96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00
64426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00
64427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00
64428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00
64429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00

In [7]:
# data.Date.dt.weekday

In [8]:
cols2check = ['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR','season']

data_count_perseasondiv = data[cols2check].dropna().groupby(['Div','season']).count()

# TODO OK

In [9]:
data['Date'] = pd.to_datetime(data['Date'],dayfirst=True)
data['Weekday'] = data.Date.dt.weekday
data = data[data.Date.isna()==False]
data

<ipython-input-9-b182cf1eabea>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Date'] = pd.to_datetime(data['Date'],dayfirst=True)

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday
0,B1,2000-08-12,NaN,Beveren,Charleroi,1,2,A,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5.0
1,B1,2000-08-12,NaN,Mechelen,Genk,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5.0
2,B1,2000-08-12,NaN,Louvieroise,Lokeren,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5.0
3,B1,2000-08-12,NaN,Mouscron,Germinal,3,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5.0
4,B1,2000-08-12,NaN,Westerlo,Antwerp,2,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64179,T1,2000-05-21,NaN,Ankaragucu,Trabzonspor,1.0,1.0,D,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0
64180,T1,2000-05-21,NaN,Antalyaspor,Altay,3.0,1.0,H,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0
64181,T1,2000-05-21,NaN,Bursaspor,Kocaelispor,2.0,0.0,H,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0
64182,T1,2000-05-21,NaN,Erzurumspor,Besiktas,1.0,4.0,A,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0
64183,T1,2000-05-21,NaN,Galatasaray,Istanbulspor,1.0,1.0,D,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0

In [10]:
# FILTER LEAGUES
data = data[data.Div.isin(list_leagues)]
data.shape

(51410, 39)

In [11]:
data.sort_values("Date").groupby(["Div", "season"]).agg({
    "Date": [("min_date", "min"), ("max_date", "max")]
}).loc['T1']

             Date
         min_date   max_date
season
T00-01 2000-08-11 2001-05-26
T01-02 2001-08-10 2002-05-04
T02-03 2002-08-09 2003-05-31
T03-04 2003-08-08 2004-05-15
T04-05 2004-08-06 2005-05-29
T05-06 2005-08-05 2006-05-14
T06-07 2006-08-04 2007-05-26
T07-08 2007-08-10 2008-05-10
T08-09 2008-08-23 2009-05-30
T09-10 2009-08-07 2010-05-16
T10-11 2010-08-14 2011-05-22
T11-12 2011-09-10 2012-04-08
T12-13 2012-08-17 2013-05-19
T13-14 2013-08-16 2014-05-18
T14-15 2014-08-29 2015-05-30
T15-16 2015-08-14 2016-05-19
T16-17 2016-08-19 2017-06-03
T17-18 2017-08-11 2018-05-19
T18-19 2018-08-10 2019-05-26
T19-20 2019-08-16 2020-07-26
T20-21 2020-09-11 2021-05-15
T21-22 2021-08-13 2022-05-22
T22-23 2022-08-05 2023-06-07
T23-24 2023-08-11 2024-05-26
T94-95 1994-08-13 1995-05-21
T95-96 1995-08-11 1996-05-19
T96-97 1996-08-11 1997-05-25
T97-98 1997-08-03 1998-05-10
T98-99 1998-08-07 1999-05-30
T99-00 1999-08-06 2000-05-21

### create match_id

In [12]:
def read_datalake(path='F:\\TFG\\datasets\\raw_datasets\\datalake.csv',dtypes=None):
    return pd.read_csv(path,sep=';',decimal=',',parse_dates=['Date'],
                       date_format="%d/%m/%Y",dtype=dtypes)

datalake_actual = read_datalake()
datalake_actual.shape

<ipython-input-12-84df70717ca0>:2: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path,sep=';',decimal=',',parse_dates=['Date'],

(60005, 40)

In [13]:
matchId_init = datalake_actual.matchId.max() + 1
print(matchId_init)

data['matchId'] = matchId_init + np.arange(len(data))
data

60005

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday,matchId
9068,D1,2021-08-13,NaN,M'gladbach,Bayern Munich,1,1,D,1,1,...,1.66,4.82,4.50,1.77,4.54,4.32,1.70,T21-22,4.0,60005
9069,D1,2021-08-14,NaN,Augsburg,Hoffenheim,0,4,A,0,1,...,2.10,3.34,3.89,2.25,3.19,3.68,2.17,T21-22,5.0,60006
9070,D1,2021-08-14,NaN,Bielefeld,Freiburg,0,0,D,0,0,...,2.50,3.07,3.49,2.65,2.92,3.27,2.52,T21-22,5.0,60007
9071,D1,2021-08-14,NaN,Stuttgart,Greuther Furth,5,1,H,2,0,...,4.00,1.91,4.12,4.32,1.86,3.90,3.98,T21-22,5.0,60008
9072,D1,2021-08-14,NaN,Union Berlin,Leverkusen,1,1,D,1,1,...,2.55,2.89,3.59,2.70,2.79,3.36,2.57,T21-22,5.0,60009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64179,T1,2000-05-21,NaN,Ankaragucu,Trabzonspor,1.0,1.0,D,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111410
64180,T1,2000-05-21,NaN,Antalyaspor,Altay,3.0,1.0,H,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111411
64181,T1,2000-05-21,NaN,Bursaspor,Kocaelispor,2.0,0.0,H,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111412
64182,T1,2000-05-21,NaN,Erzurumspor,Besiktas,1.0,4.0,A,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111413
64183,T1,2000-05-21,NaN,Galatasaray,Istanbulspor,1.0,1.0,D,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111414

In [14]:
data.groupby(['Div','season']).Date.count().reset_index(level=1).pivot_table(columns='Div',index='season')

         Date
Div        D1     E0     E1     F1     I1     N1     P1    SP1    SP2     T1
season
T00-01    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T01-02    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T02-03    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T03-04    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T04-05    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T05-06    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T06-07    NaN    NaN  552.0    NaN    NaN  306.0  240.0    NaN    NaN  306.0
T07-08    NaN    NaN  552.0    NaN    NaN  306.0  240.0    NaN    NaN  306.0
T08-09    NaN    NaN  552.0    NaN    NaN  306.0  240.0    NaN    NaN  306.0
T09-10    NaN    NaN  552.0    NaN    NaN  306.0  240.0    NaN    NaN  272.0
T10-11    NaN    NaN  552.0    NaN    NaN  306.0  240.0    NaN    NaN  306.0
T11-12    NaN    NaN  552.0    NaN    NaN  306.0  240.0    NaN    NaN  306.0
T12-13    NaN    NaN  552.0    NaN    NaN  306.0  240.0    NaN    NaN  306.0
T13-14    NaN    NaN  552.0    NaN    NaN  306.0  240.0    NaN    NaN  306.0
T14-15    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T15-16    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T16-17    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T17-18    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T18-19    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T19-20    NaN    NaN  552.0    NaN    NaN  232.0  306.0    NaN    NaN  306.0
T20-21    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  420.0
T21-22  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  380.0
T22-23  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  342.0
T23-24  306.0  380.0  552.0  306.0  380.0  306.0  306.0  380.0  462.0  380.0
T93-94    NaN    NaN  552.0    NaN    NaN  306.0    NaN    NaN    NaN    NaN
T94-95    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T95-96    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T96-97    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T97-98    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T98-99    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0
T99-00    NaN    NaN  552.0    NaN    NaN  306.0  306.0    NaN    NaN  306.0

In [15]:
# data['matchId'] = data.index
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,Weekday,matchId
9068,D1,2021-08-13,NaN,M'gladbach,Bayern Munich,1,1,D,1,1,...,1.66,4.82,4.50,1.77,4.54,4.32,1.70,T21-22,4.0,60005
9069,D1,2021-08-14,NaN,Augsburg,Hoffenheim,0,4,A,0,1,...,2.10,3.34,3.89,2.25,3.19,3.68,2.17,T21-22,5.0,60006
9070,D1,2021-08-14,NaN,Bielefeld,Freiburg,0,0,D,0,0,...,2.50,3.07,3.49,2.65,2.92,3.27,2.52,T21-22,5.0,60007
9071,D1,2021-08-14,NaN,Stuttgart,Greuther Furth,5,1,H,2,0,...,4.00,1.91,4.12,4.32,1.86,3.90,3.98,T21-22,5.0,60008
9072,D1,2021-08-14,NaN,Union Berlin,Leverkusen,1,1,D,1,1,...,2.55,2.89,3.59,2.70,2.79,3.36,2.57,T21-22,5.0,60009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64179,T1,2000-05-21,NaN,Ankaragucu,Trabzonspor,1.0,1.0,D,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111410
64180,T1,2000-05-21,NaN,Antalyaspor,Altay,3.0,1.0,H,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111411
64181,T1,2000-05-21,NaN,Bursaspor,Kocaelispor,2.0,0.0,H,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111412
64182,T1,2000-05-21,NaN,Erzurumspor,Besiktas,1.0,4.0,A,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111413
64183,T1,2000-05-21,NaN,Galatasaray,Istanbulspor,1.0,1.0,D,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,6.0,111414

### Concat data

In [16]:
assert(data.columns.shape==datalake_actual.columns.shape)

# for col1,col2 in zip(data.columns.sort_values(),datalake_actual.columns.sort_values()):
#     print(col1,col2)


# CHECK MISSING COLS
for col in datalake_actual.columns:
    if col not in data.columns: print(col)

id_H
id_A
div_order

In [17]:
datalake = pd.concat([datalake_actual,data])
datalake

,matchId,id_H,id_A,Div,div_order,Date,Weekday,season,HomeTeam,AwayTeam,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,HTHG,HTAG,HTR
0,0,8.0,19.0,D1,0.0,2000-08-11,4.0,T00-01,Dortmund,Hansa Rostock,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.0,20.0,D1,1.0,2000-08-12,5.0,T00-01,Bayern Munich,Hertha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15.0,35.0,D1,2.0,2000-08-12,5.0,T00-01,Freiburg,Stuttgart,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17.0,29.0,D1,3.0,2000-08-12,5.0,T00-01,Hamburg,Munich 1860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23.0,4.0,D1,4.0,2000-08-12,5.0,T00-01,Kaiserslautern,Bochum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64179,111410,NaN,NaN,T1,NaN,2000-05-21,6.0,T99-00,Ankaragucu,Trabzonspor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,H
64180,111411,NaN,NaN,T1,NaN,2000-05-21,6.0,T99-00,Antalyaspor,Altay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,H
64181,111412,NaN,NaN,T1,NaN,2000-05-21,6.0,T99-00,Bursaspor,Kocaelispor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,D
64182,111413,NaN,NaN,T1,NaN,2000-05-21,6.0,T99-00,Erzurumspor,Besiktas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,A
64183,111414,NaN,NaN,T1,NaN,2000-05-21,6.0,T99-00,Galatasaray,Istanbulspor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,A

In [18]:
datalake.groupby(['Div','season']).Date.count().reset_index(level=1).pivot_table(columns='Div',index='season')

         Date
Div        D1     E0     E1     F1     I1     N1     P1    SP1    SP2     T1
season
T00-01  306.0  380.0  552.0  306.0  306.0  306.0  306.0  380.0  462.0  306.0
T01-02  306.0  380.0  552.0  306.0  306.0  306.0  306.0  380.0  462.0  306.0
T02-03  306.0  380.0  552.0  380.0  306.0  306.0  306.0  380.0  462.0  306.0
T03-04  306.0  380.0  552.0  380.0  306.0  306.0  306.0  380.0  462.0  306.0
T04-05  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  306.0
T05-06  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  306.0
T06-07  306.0  380.0  552.0  380.0  380.0  306.0  240.0  380.0  462.0  306.0
T07-08  306.0  380.0  552.0  380.0  380.0  306.0  240.0  380.0  462.0  306.0
T08-09  306.0  380.0  552.0  380.0  380.0  306.0  240.0  380.0  462.0  306.0
T09-10  306.0  380.0  552.0  380.0  380.0  306.0  240.0  380.0  462.0  272.0
T10-11  306.0  380.0  552.0  380.0  380.0  306.0  240.0  380.0  462.0  306.0
T11-12  306.0  380.0  552.0  380.0  380.0  306.0  240.0  380.0  462.0  306.0
T12-13  306.0  380.0  552.0  380.0  380.0  306.0  240.0  380.0  462.0  306.0
T13-14  306.0  380.0  552.0  380.0  380.0  306.0  240.0  380.0  462.0  306.0
T14-15  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  306.0
T15-16  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  306.0
T16-17  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  306.0
T17-18  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  306.0
T18-19  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  306.0
T19-20  306.0  380.0  552.0  279.0  380.0  232.0  306.0  380.0  462.0  306.0
T20-21  288.0  350.0  552.0  380.0  358.0  306.0  306.0  380.0  418.0  420.0
T21-22  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  380.0
T22-23  306.0  380.0  552.0  380.0  380.0  306.0  306.0  380.0  462.0  342.0
T23-24  306.0  380.0  552.0  306.0  380.0  306.0  306.0  380.0  462.0  380.0
T93-94  306.0  462.0  552.0    NaN  306.0  306.0    NaN  380.0    NaN    NaN
T94-95  306.0  462.0  552.0    NaN  306.0  306.0  306.0  380.0    NaN  306.0
T95-96  306.0  380.0  552.0    NaN  306.0  306.0  306.0  462.0    NaN  306.0
T96-97  306.0  380.0  552.0    NaN  306.0  306.0  306.0  462.0  380.0  306.0
T97-98  306.0  380.0  552.0  306.0  306.0  306.0  306.0  380.0  462.0  306.0
T98-99  306.0  380.0  552.0  306.0  306.0  306.0  306.0  380.0  462.0  306.0
T99-00  306.0  380.0  552.0  306.0  306.0  306.0  306.0  380.0  462.0  306.0

### create div_order 

Para el final

In [19]:
datalake['div_order'] = datalake.groupby(['Div']).cumcount()
datalake.groupby(['Div']).div_order.max()
datalake

,matchId,id_H,id_A,Div,div_order,Date,Weekday,season,HomeTeam,AwayTeam,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,HTHG,HTAG,HTR
0,0,8.0,19.0,D1,0,2000-08-11,4.0,T00-01,Dortmund,Hansa Rostock,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.0,20.0,D1,1,2000-08-12,5.0,T00-01,Bayern Munich,Hertha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15.0,35.0,D1,2,2000-08-12,5.0,T00-01,Freiburg,Stuttgart,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17.0,29.0,D1,3,2000-08-12,5.0,T00-01,Hamburg,Munich 1860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23.0,4.0,D1,4,2000-08-12,5.0,T00-01,Kaiserslautern,Bochum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64179,111410,NaN,NaN,T1,9439,2000-05-21,6.0,T99-00,Ankaragucu,Trabzonspor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,H
64180,111411,NaN,NaN,T1,9440,2000-05-21,6.0,T99-00,Antalyaspor,Altay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,H
64181,111412,NaN,NaN,T1,9441,2000-05-21,6.0,T99-00,Bursaspor,Kocaelispor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,D
64182,111413,NaN,NaN,T1,9442,2000-05-21,6.0,T99-00,Erzurumspor,Besiktas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,A
64183,111414,NaN,NaN,T1,9443,2000-05-21,6.0,T99-00,Galatasaray,Istanbulspor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,A

In [20]:
# ¿HAY DUPLICADOS?

pk_columns = ["Div","season","HomeTeam","AwayTeam"]

assert datalake[datalake[pk_columns].duplicated()].sort_values(["Div","season","HomeTeam","AwayTeam"]).shape[0] == 0

### Teams IDs

In [21]:
dict_teams = {
    "M'Gladbach":"M'gladbach",
    "Extremadura UD":"Extremadura",
    "Orense":"Ourense",
    "Villareal":"Villarreal",
    "Mouscron-Peruwelz":"Mouscron",
    "Desp. Chaves":"Chaves",
    "Erzurum BB":"Erzurumspor",
    "Erzurum":"Erzurumspor",
    "Dusseldorf":"Fortuna Dusseldorf",
    "Fairense":"Farense"
}

datalake["HomeTeam"] = datalake["HomeTeam"].apply(lambda t: dict_teams.get(t,t).strip())
datalake["AwayTeam"] = datalake["AwayTeam"].apply(lambda t: dict_teams.get(t,t).strip())
datalake

,matchId,id_H,id_A,Div,div_order,Date,Weekday,season,HomeTeam,AwayTeam,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,HTHG,HTAG,HTR
0,0,8.0,19.0,D1,0,2000-08-11,4.0,T00-01,Dortmund,Hansa Rostock,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.0,20.0,D1,1,2000-08-12,5.0,T00-01,Bayern Munich,Hertha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15.0,35.0,D1,2,2000-08-12,5.0,T00-01,Freiburg,Stuttgart,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17.0,29.0,D1,3,2000-08-12,5.0,T00-01,Hamburg,Munich 1860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23.0,4.0,D1,4,2000-08-12,5.0,T00-01,Kaiserslautern,Bochum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64179,111410,NaN,NaN,T1,9439,2000-05-21,6.0,T99-00,Ankaragucu,Trabzonspor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,H
64180,111411,NaN,NaN,T1,9440,2000-05-21,6.0,T99-00,Antalyaspor,Altay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,H
64181,111412,NaN,NaN,T1,9441,2000-05-21,6.0,T99-00,Bursaspor,Kocaelispor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,D
64182,111413,NaN,NaN,T1,9442,2000-05-21,6.0,T99-00,Erzurumspor,Besiktas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,A
64183,111414,NaN,NaN,T1,9443,2000-05-21,6.0,T99-00,Galatasaray,Istanbulspor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,A

In [22]:
teams_id = datalake[['Div','HomeTeam']].drop_duplicates().sort_values(['Div','HomeTeam'])
teams_id

      Div          HomeTeam
1846   D1            Aachen
3367   D1          Augsburg
1      D1     Bayern Munich
618    D1         Bielefeld
11     D1            Bochum
...    ..               ...
60656  T1      Umraniyespor
61372  T1           Vanspor
58931  T1  Yeni Malatyaspor
53760  T1        Yozgatspor
61364  T1       Zeytinburnu

[537 rows x 2 columns]

In [23]:
datalake[(datalake.HomeTeam=="Feirense") | (datalake.HomeTeam=="Farense")].groupby(['HomeTeam','Div','season']).matchId.count()

HomeTeam  Div  season
Farense   P1   T00-01    17
               T01-02    17
               T20-21    17
               T23-24    17
               T94-95    17
               T95-96    17
               T96-97    17
               T97-98    17
               T98-99    17
               T99-00    17
Feirense  P1   T11-12    15
               T16-17    17
               T17-18    17
               T18-19    17
Name: matchId, dtype: int64

In [24]:
teams_id = datalake[['Div','HomeTeam']].drop_duplicates().sort_values(['Div','HomeTeam'])
# teams_id["AwayTeam"] = teams_id.HomeTeam
# teams_id['id'] = np.arange(len(teams_id)).astype(int)
teams_id = teams_id.rename(columns={'HomeTeam':'team'})
# teams_id = teams_id.set_index(["Div","HomeTeam"])
# teams_id = teams_id.to_dict()['id']
teams_id

      Div              team
1846   D1            Aachen
3367   D1          Augsburg
1      D1     Bayern Munich
618    D1         Bielefeld
11     D1            Bochum
...    ..               ...
60656  T1      Umraniyespor
61372  T1           Vanspor
58931  T1  Yeni Malatyaspor
53760  T1        Yozgatspor
61364  T1       Zeytinburnu

[537 rows x 2 columns]

In [25]:
id_actual = datalake_actual[['Div','HomeTeam','id_H']].rename(columns={'id_H':'id','HomeTeam':'team'}).set_index(['Div','team']).drop_duplicates()
id_actual.shape

(318, 1)

In [26]:
teams_id.set_index(['Div','team']).join(id_actual)

                       id
Div team
D1  Aachen            0.0
    Augsburg          1.0
    Bayern Munich     2.0
    Bielefeld         3.0
    Bochum            4.0
...                   ...
T1  Umraniyespor      NaN
    Vanspor           NaN
    Yeni Malatyaspor  NaN
    Yozgatspor        NaN
    Zeytinburnu       NaN

[537 rows x 1 columns]

In [27]:
# añadimos ID a los equipos nuevos

teams_id = teams_id.set_index(['Div','team']).join(id_actual)
# cogemos el id maximo del datalake anterior
max_id_actual = id_actual.id.max()
print(max_id_actual)
# filtramos los equipos nuevos que no tienen ID
nan_ids = teams_id.id.isna()
print(nan_ids.sum())
# le añadimos un ID automatico a partir del valor maximo del datalake anterior para mantener los IDs anteriores
teams_id.loc[nan_ids,'id'] = np.arange(nan_ids.sum()) + max_id_actual + 1
# teams_id = teams_id['id'].bfill(axis=1).reset_index()
teams_id = teams_id.reset_index()
teams_id

317
220

    Div              team     id
0    D1            Aachen    0.0
1    D1          Augsburg    1.0
2    D1     Bayern Munich    2.0
3    D1         Bielefeld    3.0
4    D1            Bochum    4.0
..   ..               ...    ...
532  T1      Umraniyespor  533.0
533  T1           Vanspor  534.0
534  T1  Yeni Malatyaspor  535.0
535  T1        Yozgatspor  536.0
536  T1       Zeytinburnu  537.0

[537 rows x 3 columns]

In [28]:
teams_id["AwayTeam"] = teams_id.team
teams_id["HomeTeam"] = teams_id.team
teams_id

    Div              team     id          AwayTeam          HomeTeam
0    D1            Aachen    0.0            Aachen            Aachen
1    D1          Augsburg    1.0          Augsburg          Augsburg
2    D1     Bayern Munich    2.0     Bayern Munich     Bayern Munich
3    D1         Bielefeld    3.0         Bielefeld         Bielefeld
4    D1            Bochum    4.0            Bochum            Bochum
..   ..               ...    ...               ...               ...
532  T1      Umraniyespor  533.0      Umraniyespor      Umraniyespor
533  T1           Vanspor  534.0           Vanspor           Vanspor
534  T1  Yeni Malatyaspor  535.0  Yeni Malatyaspor  Yeni Malatyaspor
535  T1        Yozgatspor  536.0        Yozgatspor        Yozgatspor
536  T1       Zeytinburnu  537.0       Zeytinburnu       Zeytinburnu

[537 rows x 5 columns]

In [29]:
# cols = ['Div','HomeTeam']
# datalake["id_H"] = datalake.set_index(cols).merge(teams_id[[*cols,'id']],on=cols,how='left').id.astype(int)#.to_list()
# cols = ['Div','AwayTeam']
# datalake["id_A"] = datalake.set_index(cols).merge(teams_id[[*cols,'id']],on=cols,how='left').id.astype(int)#.to_list()

# datalake

cols = ['Div','HomeTeam']
datalake = datalake.set_index(cols).merge(teams_id[[*cols,'id']],on=cols,how='left').drop(columns='id_H').rename(columns={'id':'id_H'})
cols = ['Div','AwayTeam']
datalake = datalake.set_index(cols).merge(teams_id[[*cols,'id']],on=cols,how='left').drop(columns='id_A').rename(columns={'id':'id_A'})
datalake

,Div,AwayTeam,HomeTeam,matchId,div_order,Date,Weekday,season,FTHG,FTAG,...,MaxD,MaxA,AvgH,AvgD,AvgA,HTHG,HTAG,HTR,id_H,id_A
0,D1,Hansa Rostock,Dortmund,0,0,2000-08-11,4.0,T00-01,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,19.0
1,D1,Hertha,Bayern Munich,1,1,2000-08-12,5.0,T00-01,4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,20.0
2,D1,Stuttgart,Freiburg,2,2,2000-08-12,5.0,T00-01,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,35.0
3,D1,Munich 1860,Hamburg,3,3,2000-08-12,5.0,T00-01,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,29.0
4,D1,Bochum,Kaiserslautern,4,4,2000-08-12,5.0,T00-01,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111410,T1,Trabzonspor,Ankaragucu,111410,9439,2000-05-21,6.0,T99-00,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,H,483.0,532.0
111411,T1,Altay,Antalyaspor,111411,9440,2000-05-21,6.0,T99-00,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,2.0,1.0,H,486.0,482.0
111412,T1,Kocaelispor,Bursaspor,111412,9441,2000-05-21,6.0,T99-00,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,D,490.0,515.0
111413,T1,Besiktas,Erzurumspor,111413,9442,2000-05-21,6.0,T99-00,1.0,4.0,...,NaN,NaN,NaN,NaN,NaN,0.0,3.0,A,497.0,488.0
111414,T1,Istanbulspor,Galatasaray,111414,9443,2000-05-21,6.0,T99-00,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,0.0,1.0,A,500.0,508.0

In [30]:
datalake.columns

Index(['Div', 'AwayTeam', 'HomeTeam', 'matchId', 'div_order', 'Date',
       'Weekday', 'season', 'FTHG', 'FTAG', 'FTR', 'Attendance', 'Referee',
       'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR',
       'AR', 'HO', 'AO', 'HHW', 'AHW', 'B365H', 'B365D', 'B365A', 'MaxH',
       'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'HTHG', 'HTAG', 'HTR', 'id_H',
       'id_A'],
      dtype='object')

### Set Columns

In [31]:
cols_metadata = ['matchId','id_H', 'id_A','Div','div_order','Date','Weekday','season','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR','Attendance','Referee']
cols_features = ['HS', 'AS', 'HST', 'AST', 'HF','AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR','HO','AO','HHW','AHW']
cols_bets     = ['B365H', 'B365D', 'B365A','MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA']

In [32]:
datalake = datalake[[*cols_metadata,*cols_features,*cols_bets]]

In [33]:
datalake

,matchId,id_H,id_A,Div,div_order,Date,Weekday,season,HomeTeam,AwayTeam,...,AHW,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,0,8.0,19.0,D1,0,2000-08-11,4.0,T00-01,Dortmund,Hansa Rostock,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.0,20.0,D1,1,2000-08-12,5.0,T00-01,Bayern Munich,Hertha,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15.0,35.0,D1,2,2000-08-12,5.0,T00-01,Freiburg,Stuttgart,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17.0,29.0,D1,3,2000-08-12,5.0,T00-01,Hamburg,Munich 1860,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23.0,4.0,D1,4,2000-08-12,5.0,T00-01,Kaiserslautern,Bochum,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111410,111410,483.0,532.0,T1,9439,2000-05-21,6.0,T99-00,Ankaragucu,Trabzonspor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111411,111411,486.0,482.0,T1,9440,2000-05-21,6.0,T99-00,Antalyaspor,Altay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111412,111412,490.0,515.0,T1,9441,2000-05-21,6.0,T99-00,Bursaspor,Kocaelispor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111413,111413,497.0,488.0,T1,9442,2000-05-21,6.0,T99-00,Erzurumspor,Besiktas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111414,111414,500.0,508.0,T1,9443,2000-05-21,6.0,T99-00,Galatasaray,Istanbulspor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
datalake[datalake[["id_H","id_A","Date"]].duplicated()].sort_values(["id_H","id_A"])

# datalake[datalake.duplicated()]

Empty DataFrame
Columns: [matchId, id_H, id_A, Div, div_order, Date, Weekday, season, HomeTeam, AwayTeam, FTHG, FTAG, FTR, Attendance, Referee, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR, HO, AO, HHW, AHW, B365H, B365D, B365A, MaxH, MaxD, MaxA, AvgH, AvgD, AvgA]
Index: []

[0 rows x 40 columns]

In [35]:
datalake[(datalake.id_H==322.0) & (datalake.id_A==323.0)]

# datalake_actual[(datalake_actual.id_H==43) & (datalake_actual.id_A==47)]

,matchId,id_H,id_A,Div,div_order,Date,Weekday,season,HomeTeam,AwayTeam,...,AHW,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
62377,62377,322.0,323.0,E1,314,2001-01-13,5.0,T00-01,Barnsley,Birmingham,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62742,62742,322.0,323.0,E1,679,2001-10-13,5.0,T01-02,Barnsley,Birmingham,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65865,65865,322.0,323.0,E1,3802,2007-04-09,0.0,T06-07,Barnsley,Birmingham,...,NaN,3.60,3.25,1.90,NaN,NaN,NaN,NaN,NaN,NaN
66911,66911,322.0,323.0,E1,4848,2009-03-10,1.0,T08-09,Barnsley,Birmingham,...,NaN,2.90,3.30,2.40,NaN,NaN,NaN,NaN,NaN,NaN
68508,68508,322.0,323.0,E1,6445,2012-02-21,1.0,T11-12,Barnsley,Birmingham,...,NaN,3.50,3.30,2.10,NaN,NaN,NaN,NaN,NaN,NaN
68963,68963,322.0,323.0,E1,6900,2012-12-26,2.0,T12-13,Barnsley,Birmingham,...,NaN,2.40,3.30,2.88,NaN,NaN,NaN,NaN,NaN,NaN
69431,69431,322.0,323.0,E1,7368,2013-11-30,5.0,T13-14,Barnsley,Birmingham,...,NaN,2.60,3.50,2.80,NaN,NaN,NaN,NaN,NaN,NaN
71175,71175,322.0,323.0,E1,9112,2016-12-31,5.0,T16-17,Barnsley,Birmingham,...,NaN,2.30,3.50,3.25,NaN,NaN,NaN,NaN,NaN,NaN
71627,71627,322.0,323.0,E1,9564,2017-11-04,5.0,T17-18,Barnsley,Birmingham,...,NaN,2.39,3.50,3.10,NaN,NaN,NaN,NaN,NaN,NaN
72923,72923,322.0,323.0,E1,10860,2020-02-11,1.0,T19-20,Barnsley,Birmingham,...,NaN,2.55,3.40,2.75,2.70,3.5,2.84,2.57,3.41,2.69
73507,73507,322.0,323.0,E1,11444,2021-03-06,5.0,T20-21,Barnsley,Birmingham,...,NaN,1.80,3.60,4.50,1.88,3.6,5.00,1.83,3.44,4.62
73705,73705,322.0,323.0,E1,11642,2021-08-28,5.0,T21-22,Barnsley,Birmingham,...,NaN,2.25,3.30,3.30,2.40,3.3,3.50,2.29,3.19,3.34
75343,75343,322.0,323.0,E1,13280,1993-08-28,5.0,T93-94,Barnsley,Birmingham,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76464,76464,322.0,323.0,E1,14401,1995-09-02,5.0,T95-96,Barnsley,Birmingham,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77447,77447,322.0,323.0,E1,15384,1997-04-05,5.0,T96-97,Barnsley,Birmingham,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78393,78393,322.0,323.0,E1,16330,1999-01-16,5.0,T98-99,Barnsley,Birmingham,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78827,78827,322.0,323.0,E1,16764,1999-11-20,5.0,T99-00,Barnsley,Birmingham,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
datalake[["id_H","id_A","Date"]].drop_duplicates().shape, datalake.shape

((111415, 3), (111415, 40))

In [37]:
dup_matches = datalake[["matchId","id_H","id_A","Date"]].groupby(["id_H","id_A","Date"]).count()
dup_matches = dup_matches[dup_matches.matchId>1].drop("matchId",axis=1).reset_index()
dup_matches

Empty DataFrame
Columns: [id_H, id_A, Date]
Index: []

In [38]:
dup_matches.merge(datalake,on=["id_H","id_A","Date"],how='left').sort_values(["id_H","id_A","Date"])

Empty DataFrame
Columns: [matchId, id_H, id_A, Div, div_order, Date, Weekday, season, HomeTeam, AwayTeam, FTHG, FTAG, FTR, Attendance, Referee, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR, HO, AO, HHW, AHW, B365H, B365D, B365A, MaxH, MaxD, MaxA, AvgH, AvgD, AvgA]
Index: []

[0 rows x 40 columns]

In [60]:
dtypes = load_json('F:\TFG\datasets\\raw_datasets\dtypes.json')
dtypes

{'matchId': 'Int64',
 'id_H': 'Int64',
 'id_A': 'Int64',
 'Div': 'str',
 'season': 'str',
 'HomeTeam': 'str',
 'AwayTeam': 'str',
 'div_order': 'Int64',
 'FTHG': 'Int64',
 'FTAG': 'Int64',
 'FTR': 'str',
 'Attendance': 'float',
 'Referee': 'str',
 'Weekday': 'Int64'}

In [61]:
for _k,_v in dtypes.items():
    try:
        if _k in datalake.columns:
            datalake[_k] = datalake[_k].astype(_v)
        else: print('Este campo no aparece en los datos: ',_k)
    except Exception as e: print(_k,_v,e)

datalake.dtypes

FTHG Int64 invalid literal for int() with base 10: '2.0'
FTAG Int64 invalid literal for int() with base 10: '2.0'

matchId                Int64
id_H                   Int64
id_A                   Int64
Div                   object
div_order              Int64
Date          datetime64[ns]
Weekday                Int64
season                object
HomeTeam              object
AwayTeam              object
FTHG                  object
FTAG                  object
FTR                   object
Attendance           float64
Referee               object
HS                    object
AS                    object
HST                   object
AST                   object
HF                    object
AF                    object
HC                    object
AC                    object
HY                    object
AY                    object
HR                    object
AR                    object
HO                    object
AO                    object
HHW                   object
AHW                   object
B365H                float64
B365D                float64
B365A                float64
MaxH                 float64
MaxD                 float64
MaxA                 float64
AvgH                 float64
AvgD                 float64
AvgA                 float64
dtype: object

In [62]:
datalake.to_csv('F:\\TFG\\datasets\\raw_datasets\\datalake_v3.csv',sep=';',decimal=',',encoding='utf-8',date_format="%d/%m/%Y",index=False)

In [41]:
pd.read_csv('F:\\TFG\\datasets\\raw_datasets\\datalake_v3.csv',sep=';',decimal=',').columns

<ipython-input-41-3e6f031dcaab>:1: DtypeWarning: Columns (13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('F:\\TFG\\datasets\\raw_datasets\\datalake_v3.csv',sep=';',decimal=',').columns

Index(['matchId', 'id_H', 'id_A', 'Div', 'div_order', 'Date', 'Weekday',
       'season', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'Attendance',
       'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY',
       'HR', 'AR', 'HO', 'AO', 'HHW', 'AHW', 'B365H', 'B365D', 'B365A', 'MaxH',
       'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA'],
      dtype='object')