In [47]:
import pandas as pd
import numpy as np
import datetime

In [48]:
list_leagues = ["D1","SP1","E0","I1","F1"]

dict_encodings = []

In [49]:
path_footdata   ='F:\\TFG\\datasets\\football-data\\'

In [50]:
df = pd.read_csv(path_footdata+'I1_1819.csv')
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

In [51]:
pd.read_csv(path_footdata+'E0_2021.csv').columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG',
       ...
       'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH',
       'MaxCAHA', 'AvgCAHH', 'AvgCAHA'],
      dtype='object', length=106)

In [52]:
pd.read_csv(path_footdata+'E0_2021.csv').columns.to_list()

['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA']

In [53]:
pd.read_csv(path_footdata+'SP1_1819.csv').columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD',
       'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA',
       'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh',
       'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [54]:
pd.read_csv(path_footdata+'D1_1819.csv').columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD',
       'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA',
       'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh',
       'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [55]:
columns_to_keep = [
    'Div','Date','Attendance','HomeTeam','AwayTeam','FTHG','FTAG','FTR','HTHG','HTAG','HTR','Referee',
    'HS','AS','HST','AST','HF','AF','HC','AC','HY','AY','HR','AR','HO','AO','HHW','AHW','B365H','B365D','B365A', 'MaxH','MaxD','MaxA','AvgH','AvgD','AvgA'
]

In [56]:
import os
data = pd.DataFrame(data=[],columns=columns_to_keep)

for elem in os.listdir(path_footdata):
    if (".csv" in elem):
        # print(elem)
        df = pd.read_csv(path_footdata+elem,sep=',',on_bad_lines='skip',encoding='latin-1')
        df = df.loc[:, df.columns.isin(columns_to_keep)]

        season = f"T{elem[-8:-6]}-{elem[-6:-4]}"
        df["season"] = season
        print(df.Div[0],season,df.shape)
        
        data = pd.concat([data,df],axis=0,ignore_index=True)

D1 T00-01 (306, 29)
D1 T01-02 (306, 29)
D1 T02-03 (291, 14)
D1 T03-04 (194, 24)
D1 T04-05 (306, 24)
D1 T05-06 (306, 24)
D1 T06-07 (306, 26)
D1 T07-08 (306, 26)
D1 T08-09 (306, 26)
D1 T09-10 (306, 26)
D1 T10-11 (306, 26)
D1 T11-12 (306, 26)
D1 T12-13 (306, 26)
D1 T13-14 (306, 26)
D1 T14-15 (306, 26)
D1 T15-16 (306, 26)
D1 T16-17 (306, 26)
D1 T17-18 (306, 26)
D1 T18-19 (306, 26)
D1 T19-20 (306, 32)
D1 T20-21 (288, 32)
D1 T93-94 (552, 8)
D1 T94-95 (552, 8)
D1 T95-96 (552, 11)
D1 T96-97 (552, 11)
D1 T97-98 (306, 11)
D1 T98-99 (306, 11)
D1 T99-00 (552, 11)
E0 T00-01 (380, 29)
E0 T01-02 (380, 29)
E0 T02-03 (380, 27)
E0 T03-04 (335, 27)
E0 T04-05 (380, 27)
E0 T05-06 (335, 27)
E0 T06-07 (380, 27)
E0 T07-08 (380, 27)
E0 T08-09 (380, 27)
E0 T09-10 (380, 27)
E0 T10-11 (380, 27)
E0 T11-12 (380, 27)
E0 T12-13 (380, 27)
E0 T13-14 (380, 27)
E0 T14-15 (381, 27)
E0 T15-16 (380, 27)
E0 T16-17 (380, 27)
E0 T17-18 (380, 27)
E0 T18-19 (380, 27)
E0 T19-20 (380, 33)
E0 T20-21 (350, 33)
E0 T93-94 (552, 8)
E0 T94-95 (552, 8)
E0 T95-96 (552, 11)
E0 T96-97 (552, 11)
E0 T97-98 (380, 11)
E0 T98-99 (380, 11)
E0 T99-00 (552, 11)
F1 T00-01 (306, 11)
F1 T01-02 (306, 11)
F1 T02-03 (191, 14)
F1 T03-04 (223, 14)
F1 T04-05 (380, 14)
F1 T05-06 (380, 22)
F1 T06-07 (380, 24)
F1 T07-08 (380, 26)
F1 T08-09 (380, 26)
F1 T09-10 (380, 26)
F1 T10-11 (380, 26)
F1 T11-12 (380, 26)
F1 T12-13 (380, 26)
F1 T13-14 (381, 26)
F1 T14-15 (380, 26)
F1 T15-16 (381, 26)
F1 T16-17 (380, 26)
F1 T17-18 (380, 26)
F1 T18-19 (380, 26)
F1 T19-20 (279, 32)
F1 T20-21 (380, 32)
F1 T97-98 (306, 11)
F1 T98-99 (552, 11)
F1 T99-00 (552, 11)
I1 T00-01 (306, 11)
I1 T01-02 (306, 11)
I1 T02-03 (315, 14)
I1 T03-04 (194, 14)
I1 T04-05 (300, 14)
I1 T05-06 (380, 27)
I1 T06-07 (380, 27)
I1 T07-08 (380, 26)
I1 T08-09 (380, 26)
I1 T09-10 (380, 26)
I1 T10-11 (380, 26)
I1 T11-12 (380, 26)
I1 T12-13 (383, 26)
I1 T13-14 (380, 26)
I1 T14-15 (381, 26)
I1 T15-16 (381, 26)
I1 T16-17 (380, 26)
I1 T17-18 (380, 26)
I1 T18-19 (380, 26)
I1 T19-20 (380, 32)
I1 T20-21 (358, 32)
I1 T93-94 (552, 8)
I1 T94-95 (552, 8)
I1 T95-96 (552, 11)
I1 T96-97 (552, 11)
I1 T97-98 (306, 11)
I1 T98-99 (306, 11)
I1 T99-00 (552, 11)
SP1 T00-01 (380, 11)
SP1 T01-02 (380, 11)
SP1 T02-03 (380, 14)
SP1 T03-04 (380, 14)
SP1 T04-05 (268, 14)
SP1 T05-06 (380, 26)
SP1 T06-07 (380, 26)
SP1 T07-08 (380, 26)
SP1 T08-09 (380, 26)
SP1 T09-10 (380, 26)
SP1 T10-11 (380, 26)
SP1 T11-12 (380, 26)
SP1 T12-13 (380, 26)
SP1 T13-14 (380, 26)
SP1 T14-15 (380, 26)
SP1 T15-16 (380, 26)
SP1 T16-17 (380, 26)
SP1 T17-18 (380, 26)
SP1 T18-19 (380, 26)
SP1 T19-20 (380, 32)
SP1 T20-21 (380, 32)
SP1 T93-94 (552, 8)
SP1 T94-95 (552, 8)
SP1 T95-96 (552, 11)
SP1 T96-97 (552, 11)
SP1 T97-98 (380, 11)
SP1 T98-99 (380, 11)
SP1 T99-00 (552, 11)
SP2 T00-01 (462, 11)
SP2 T01-02 (414, 11)
SP2 T02-03 (239, 14)
SP2 T03-04 (158, 14)
SP2 T04-05 (462, 14)
SP2 T05-06 (462, 14)
SP2 T06-07 (462, 14)
SP2 T07-08 (446, 14)
SP2 T08-09 (462, 14)
SP2 T09-10 (462, 14)
SP2 T10-11 (462, 14)
SP2 T11-12 (462, 14)
SP2 T12-13 (464, 14)
SP2 T13-14 (463, 14)
SP2 T14-15 (462, 14)
SP2 T15-16 (462, 14)
SP2 T16-17 (462, 14)
SP2 T17-18 (462, 26)
SP2 T18-19 (462, 26)
SP2 T19-20 (462, 32)
SP2 T20-21 (418, 32)
SP2 T96-97 (552, 8)
SP2 T97-98 (462, 11)
SP2 T98-99 (462, 11)
SP2 T99-00 (552, 11)

In [57]:
data
data['Date'] = pd.to_datetime(data['Date'],dayfirst=True)
data = data[data.Date.isna()==False]
data

<ipython-input-57-fcfde43974bc>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Date'] = pd.to_datetime(data['Date'],dayfirst=True)

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63078,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00
63079,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00
63080,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00
63081,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00
63082,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00

In [58]:
data.query("Div=='SP1' and season=='T00-01' and (HomeTeam=='Sociedad' or AwayTeam=='Sociedad')").sort_values("Date")

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season
40690,SP1,2000-09-09,NaN,Sociedad,Santander,2,2,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40703,SP1,2000-09-17,NaN,Celta,Sociedad,4,1,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40710,SP1,2000-09-23,NaN,Sociedad,La Coruna,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40729,SP1,2000-10-14,NaN,Sociedad,Barcelona,0,6,A,0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40736,SP1,2000-10-18,NaN,Espanol,Sociedad,1,2,A,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40744,SP1,2000-10-22,NaN,Vallecano,Sociedad,4,1,H,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40755,SP1,2000-10-29,NaN,Sociedad,Real Madrid,1,4,A,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40758,SP1,2000-11-01,NaN,Alaves,Sociedad,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40774,SP1,2000-11-05,NaN,Sociedad,Mallorca,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40782,SP1,2000-11-12,NaN,Oviedo,Sociedad,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40794,SP1,2000-11-19,NaN,Sociedad,Numancia,4,1,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40805,SP1,2000-11-26,NaN,Valladolid,Sociedad,2,1,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40813,SP1,2000-12-03,NaN,Sociedad,Las Palmas,1,1,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40818,SP1,2000-12-09,NaN,Valencia,Sociedad,2,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40828,SP1,2000-12-16,NaN,Sociedad,Villarreal,0,2,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40841,SP1,2000-12-20,NaN,Malaga,Sociedad,3,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40852,SP1,2001-01-07,NaN,Sociedad,Zaragoza,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40862,SP1,2001-01-14,NaN,Sociedad,Ath Bilbao,0,2,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40872,SP1,2001-01-21,NaN,Osasuna,Sociedad,1,1,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40884,SP1,2001-01-28,NaN,Santander,Sociedad,1,4,A,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40894,SP1,2001-02-04,NaN,Sociedad,Celta,2,2,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40898,SP1,2001-02-10,NaN,La Coruna,Sociedad,4,1,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40914,SP1,2001-02-18,NaN,Sociedad,Espanol,2,1,H,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40920,SP1,2001-02-25,NaN,Barcelona,Sociedad,3,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40929,SP1,2001-03-03,NaN,Sociedad,Vallecano,2,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40944,SP1,2001-03-11,NaN,Real Madrid,Sociedad,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40953,SP1,2001-03-18,NaN,Sociedad,Alaves,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40963,SP1,2001-04-01,NaN,Mallorca,Sociedad,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40974,SP1,2001-04-08,NaN,Sociedad,Oviedo,3,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40984,SP1,2001-04-15,NaN,Numancia,Sociedad,3,3,D,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
40993,SP1,2001-04-22,NaN,Sociedad,Valladolid,3,1,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
41002,SP1,2001-04-29,NaN,Las Palmas,Sociedad,2,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
41009,SP1,2001-05-05,NaN,Sociedad,Valencia,1,2,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
41018,SP1,2001-05-12,NaN,Villarreal,Sociedad,1,3,A,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
41033,SP1,2001-05-20,NaN,Sociedad,Malaga,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
41046,SP1,2001-05-27,NaN,Zaragoza,Sociedad,1,1,D,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
41048,SP1,2001-06-10,NaN,Ath Bilbao,Sociedad,1,3,A,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01
41065,SP1,2001-06-17,NaN,Sociedad,Osasuna,0,1,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01

In [59]:
data.sort_values("Date").groupby(["Div", "season"]).agg({
    "Date": [("min_date", "min"), ("max_date", "max")]
}).loc['F1']

             Date
         min_date   max_date
season
T00-01 2000-07-28 2001-05-19
T01-02 2001-07-27 2002-05-04
T02-03 2002-08-02 2003-04-06
T03-04 2003-08-01 2004-05-15
T04-05 2004-08-06 2005-05-28
T05-06 2005-07-29 2006-05-13
T06-07 2006-08-04 2007-05-26
T07-08 2007-08-04 2008-05-17
T08-09 2008-08-09 2009-05-30
T09-10 2009-08-08 2010-05-15
T10-11 2010-08-07 2011-05-29
T11-12 2011-08-06 2012-05-20
T12-13 2012-08-10 2013-05-26
T13-14 2013-08-09 2014-05-17
T14-15 2014-08-08 2015-05-23
T15-16 2015-08-07 2016-05-14
T16-17 2016-08-12 2017-05-20
T17-18 2017-08-04 2018-05-19
T18-19 2018-08-10 2019-05-24
T19-20 2019-08-09 2020-03-08
T20-21 2020-08-21 2021-05-23
T97-98 1997-08-01 1998-05-09
T98-99 1998-08-07 1999-05-29
T99-00 1999-07-30 2000-05-13

In [60]:
data['div_order'] = data.groupby(['Div']).cumcount()
data.groupby(['Div']).div_order.max()
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,div_order
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,0
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,1
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,2
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,3
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63078,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10828
63079,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10829
63080,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10830
63081,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10831
63082,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10832

In [61]:
# data['matchId'] = data.Div + data.div_order.astype(str).map(lambda x: x.zfill(5))
data['matchId'] = np.arange(len(data))
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,div_order,matchId
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,0,0
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,1,1
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,2,2
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,3,3
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63078,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10828,58541
63079,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10829,58542
63080,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10830,58543
63081,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10831,58544
63082,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10832,58545

In [62]:
data.groupby(['Div','season']).Date.count().reset_index(level=1).pivot_table(columns='Div',index='season')

         Date
Div        D1     E0     F1     I1    SP1    SP2
season
T00-01  306.0  380.0  306.0  306.0  380.0  462.0
T01-02  306.0  380.0  306.0  306.0  380.0  414.0
T02-03  290.0  380.0  191.0  306.0  380.0  239.0
T03-04  194.0  335.0  223.0  194.0  380.0  158.0
T04-05  306.0  380.0  380.0  300.0  268.0  462.0
T05-06  306.0  335.0  380.0  380.0  380.0  462.0
T06-07  306.0  380.0  380.0  380.0  380.0  462.0
T07-08  306.0  380.0  380.0  380.0  380.0  446.0
T08-09  306.0  380.0  380.0  380.0  380.0  462.0
T09-10  306.0  380.0  380.0  380.0  380.0  462.0
T10-11  306.0  380.0  380.0  380.0  380.0  462.0
T11-12  306.0  380.0  380.0  380.0  380.0  462.0
T12-13  306.0  380.0  380.0  380.0  380.0  462.0
T13-14  306.0  380.0  380.0  380.0  380.0  462.0
T14-15  306.0  380.0  380.0  380.0  380.0  462.0
T15-16  306.0  380.0  380.0  380.0  380.0  462.0
T16-17  306.0  380.0  380.0  380.0  380.0  462.0
T17-18  306.0  380.0  380.0  380.0  380.0  462.0
T18-19  306.0  380.0  380.0  380.0  380.0  462.0
T19-20  306.0  380.0  279.0  380.0  380.0  462.0
T20-21  288.0  350.0  380.0  358.0  380.0  418.0
T93-94  306.0  462.0    NaN  306.0  380.0    NaN
T94-95  306.0  462.0    NaN  306.0  380.0    NaN
T95-96  306.0  380.0    NaN  306.0  462.0    NaN
T96-97  306.0  380.0    NaN  306.0  462.0  380.0
T97-98  306.0  380.0  306.0  306.0  380.0  462.0
T98-99  306.0  380.0  306.0  306.0  380.0  462.0
T99-00  306.0  380.0  306.0  306.0  380.0  462.0

In [63]:
# data['matchId'] = data.index
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,div_order,matchId
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,0,0
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,1,1
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,2,2
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,3,3
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63078,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10828,58541
63079,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10829,58542
63080,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10830,58543
63081,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10831,58544
63082,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10832,58545

In [64]:
dict_teams = {
    "M'Gladbach":"M'gladbach",
    "Extremadura UD":"Extremadura",
    "Orense":"Ourense",
    "Villareal":"Villarreal"
}

data["HomeTeam"] = data["HomeTeam"].apply(lambda t: dict_teams.get(t,t))
data["AwayTeam"] = data["AwayTeam"].apply(lambda t: dict_teams.get(t,t))
data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,season,div_order,matchId
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,0,0
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,1,1
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,2,2
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,3,3
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T00-01,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63078,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10828,58541
63079,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10829,58542
63080,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10830,58543
63081,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10831,58544
63082,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T99-00,10832,58545

In [65]:
teams_id = data[['Div','HomeTeam']].drop_duplicates().sort_values(['Div','HomeTeam'])
teams_id["AwayTeam"] = teams_id.HomeTeam
teams_id['id'] = np.arange(len(teams_id))
# teams_id = teams_id.set_index(["Div","HomeTeam"])
# teams_id = teams_id.to_dict()['id']
teams_id

       Div       HomeTeam       AwayTeam   id
1719    D1         Aachen         Aachen    0
3240    D1       Augsburg       Augsburg    1
1       D1  Bayern Munich  Bayern Munich    2
618     D1      Bielefeld      Bielefeld    3
11      D1         Bochum         Bochum    4
...    ...            ...            ...  ...
54287  SP2     Vecindario     Vecindario  313
57030  SP2     Villarreal     Villarreal  314
55648  SP2   Villarreal B   Villarreal B  315
52547  SP2          Xerez          Xerez  316
52961  SP2       Zaragoza       Zaragoza  317

[318 rows x 4 columns]

In [66]:
teams_id[teams_id.id==288]
# teams_id[teams_id.HomeTeam=="Extremadura"]

       Div HomeTeam AwayTeam   id
57957  SP2  Osasuna  Osasuna  288

In [67]:
cols = ['Div','HomeTeam']
data["id_H"] = data.set_index(cols).merge(teams_id[[*cols,'id']],on=cols,how='left').id.to_list()
cols = ['Div','AwayTeam']
data["id_A"] = data.set_index(cols).merge(teams_id[[*cols,'id']],on=cols,how='left').id.to_list()

data

,Div,Date,Attendance,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,MaxD,MaxA,AvgH,AvgD,AvgA,season,div_order,matchId,id_H,id_A
0,D1,2000-08-11,61000.0,Dortmund,Hansa Rostock,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,T00-01,0,0,8,19
1,D1,2000-08-12,57000.0,Bayern Munich,Hertha,4,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,T00-01,1,1,2,20
2,D1,2000-08-12,22500.0,Freiburg,Stuttgart,4,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,T00-01,2,2,15,35
3,D1,2000-08-12,35000.0,Hamburg,Munich 1860,2,2,D,2,2,...,NaN,NaN,NaN,NaN,NaN,T00-01,3,3,17,29
4,D1,2000-08-12,38000.0,Kaiserslautern,Bochum,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,T00-01,4,4,23,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63078,SP2,2000-06-04,NaN,Extremadura,Badajoz,2.0,2.0,D,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,T99-00,10828,58541,258,243
63079,SP2,2000-06-04,NaN,Las Palmas,Levante,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,T99-00,10829,58542,271,274
63080,SP2,2000-06-04,NaN,Logrones,Villarreal,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,T99-00,10830,58543,277,314
63081,SP2,2000-06-04,NaN,Osasuna,Recreativo,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,T99-00,10831,58544,288,297
63082,SP2,2000-06-04,NaN,Salamanca,Eibar,2.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,T99-00,10832,58545,300,255

In [68]:
cols_metadata = ['matchId','id_H', 'id_A','Div','div_order','Date','season','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR','Attendance','Referee']
cols_features = ['HS', 'AS', 'HST', 'AST', 'HF','AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR','HO','AO','HHW','AHW']
cols_bets     = ['B365H', 'B365D', 'B365A','MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA']

In [69]:
data = data[[*cols_metadata,*cols_features,*cols_bets]]

In [70]:
data

,matchId,id_H,id_A,Div,div_order,Date,season,HomeTeam,AwayTeam,FTHG,...,AHW,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,0,8,19,D1,0,2000-08-11,T00-01,Dortmund,Hansa Rostock,1,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,20,D1,1,2000-08-12,T00-01,Bayern Munich,Hertha,4,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15,35,D1,2,2000-08-12,T00-01,Freiburg,Stuttgart,4,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17,29,D1,3,2000-08-12,T00-01,Hamburg,Munich 1860,2,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23,4,D1,4,2000-08-12,T00-01,Kaiserslautern,Bochum,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63078,58541,258,243,SP2,10828,2000-06-04,T99-00,Extremadura,Badajoz,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63079,58542,271,274,SP2,10829,2000-06-04,T99-00,Las Palmas,Levante,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63080,58543,277,314,SP2,10830,2000-06-04,T99-00,Logrones,Villarreal,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63081,58544,288,297,SP2,10831,2000-06-04,T99-00,Osasuna,Recreativo,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63082,58545,300,255,SP2,10832,2000-06-04,T99-00,Salamanca,Eibar,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
data[["id_H","id_A","Date"]].drop_duplicates().shape, data.shape

((58546, 3), (58546, 39))

In [72]:
dup_matches = data[["matchId","id_H","id_A","Date"]].groupby(["id_H","id_A","Date"]).count()
dup_matches = dup_matches[dup_matches.matchId>1].drop("matchId",axis=1).reset_index()
dup_matches

Empty DataFrame
Columns: [id_H, id_A, Date]
Index: []

In [73]:
dup_matches.merge(data,on=["id_H","id_A","Date"],how='left').sort_values(["id_H","id_A","Date"])

Empty DataFrame
Columns: [matchId, id_H, id_A, Div, div_order, Date, season, HomeTeam, AwayTeam, FTHG, FTAG, FTR, Attendance, Referee, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR, HO, AO, HHW, AHW, B365H, B365D, B365A, MaxH, MaxD, MaxA, AvgH, AvgD, AvgA]
Index: []

[0 rows x 39 columns]

In [74]:
data.to_csv('F:\\TFG\\datasets\\raw_datasets\\datalake.csv',sep=';',decimal=',',encoding='utf-8',date_format="%d/%m/%Y",index=False)

In [75]:
pd.read_csv('F:\\TFG\\datasets\\raw_datasets\\datalake.csv',sep=';',decimal=',')

<ipython-input-75-b50f7ac4607d>:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('F:\\TFG\\datasets\\raw_datasets\\datalake.csv',sep=';',decimal=',')

,matchId,id_H,id_A,Div,div_order,Date,season,HomeTeam,AwayTeam,FTHG,...,AHW,B365H,B365D,B365A,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,0,8,19,D1,0,11/08/2000,T00-01,Dortmund,Hansa Rostock,1,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,20,D1,1,12/08/2000,T00-01,Bayern Munich,Hertha,4,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,15,35,D1,2,12/08/2000,T00-01,Freiburg,Stuttgart,4,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,17,29,D1,3,12/08/2000,T00-01,Hamburg,Munich 1860,2,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,23,4,D1,4,12/08/2000,T00-01,Kaiserslautern,Bochum,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58541,58541,258,243,SP2,10828,04/06/2000,T99-00,Extremadura,Badajoz,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58542,58542,271,274,SP2,10829,04/06/2000,T99-00,Las Palmas,Levante,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58543,58543,277,314,SP2,10830,04/06/2000,T99-00,Logrones,Villarreal,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58544,58544,288,297,SP2,10831,04/06/2000,T99-00,Osasuna,Recreativo,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58545,58545,300,255,SP2,10832,04/06/2000,T99-00,Salamanca,Eibar,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN