In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains 
import pandas as pd

In [6]:
# Ruta al controlador del navegador (especifica la ruta correcta)
driver_path = 'C:\\Users\\GuillemUPV\\chromedriver-win64\\chromedriver.exe'
# Inicializar el navegador
driver = webdriver.Chrome()

# URL de la página web
# url = 'https://www.whoscored.com/Matches/1079642/Live/Netherlands-Eredivisie-2016-2017-Go-Ahead-Eagles-Sparta-Rotterdam'
url = 'https://www.whoscored.com/Matches/738817/Live/Spain-LaLiga-2013-2014-Malaga-Levante'
# Acceder a la página web
driver.get(url)

# Esperar a que la página cargue completamente (puedes ajustar este tiempo según sea necesario)
driver.implicitly_wait(10)

players = {"team_id": [], "field": [], "player_id": [], "nombre": [], "titular": [], "rating": [], "minutes_played": []}

for tipo in ['.pitch-field','.bench']:
    # Encontrar todos los elementos de jugador banquillo
    equipos = driver.find_elements(By.CSS_SELECTOR, tipo)
    for equipo in equipos:
        equipo_id = equipo.get_attribute("data-team-id")
        field = equipo.get_attribute('data-field')
        jugadores = equipo.find_elements(By.CSS_SELECTOR, f'.player[data-field="{field}"]')

        # Iterar sobre los jugadores titulares e imprimir sus datos
        for jugador in jugadores:
            player_id = jugador.get_attribute("data-player-id")
            nombre = jugador.find_element(By.CSS_SELECTOR, '.player-name').text
            numero_camiseta = jugador.find_element(By.CSS_SELECTOR, '.shirt-number').text
            puntaje = jugador.find_element(By.CSS_SELECTOR, '.player-stat-value').text

            minutes_played = 90 if tipo=='.pitch-field' else 0

            players["team_id"].append(equipo_id), players["field"].append(field), players["player_id"].append(player_id)
            players["nombre"].append(nombre), players["titular"].append(int(tipo=='.pitch-field'))
            players["rating"].append(puntaje), players["minutes_played"].append(minutes_played)

# Cerrar el navegador
driver.quit()


df_players = pd.DataFrame(players)

In [7]:
df_players

   team_id field player_id      nombre  titular rating  minutes_played
0       69  home     34749   Caballero        1    6.7              90
1       69  home     23309      Eliseu        1    7.5              90
2       69  home     13289    Weligton        1    7.0              90
3       69  home     35199     Camacho        1    7.9              90
4       69  home     23621     Antunes        1    7.1              90
5       69  home    125509       Pérez        1    8.2              90
6       69  home    106596      Darder        1    7.3              90
7       69  home    135233      García        1    6.8              90
8       69  home     83360    Portillo        1    8.4              90
9       69  home     22932     Amrabat        1    7.5              90
10      69  home    125299  Rescaldani        1    6.9              90
11     832  away     65901       Navas        1    7.8              90
12     832  away    141281      Nagore        1    6.3              90
13     832  away     10687      Vyntra        1    6.7              90
14     832  away      5999     Navarro        1    6.8              90
15     832  away      1324    Juanfran        1    7.0              90
16     832  away      9576     Sissoko        1    6.7              90
17     832  away     27384        Diop        1    6.0              90
18     832  away      5628       Pinto        1    6.0              90
19     832  away     14077   Casadesús        1    6.6              90
20     832  away     23541        Ríos        1    6.4              90
21     832  away     19391      Barral        1    6.3              90
22      69  home     83080      Juanmi        0    7.2               0
23      69  home     31124      Casado        0    5.4               0
24      69  home     87647   Pawlowski        0    6.2               0
25      69  home      3515      Kameni        0                      0
26      69  home       954        Cruz        0                      0
27      69  home     18659   Iakovenko        0                      0
28     832  away     22325   Rodríguez        0    5.9               0
29     832  away     44282     Xumetra        0    6.1               0
30     832  away     23167        Zhar        0    6.0               0
31     832  away      5206  Ivanschitz        0                      0
32     832  away     35209  Karámpelas        0                      0
33     832  away     14104    Pallardó        0                      0
34     832  away      4601     Jiménez        0                      0

In [4]:
# Ruta al controlador del navegador (especifica la ruta correcta)
driver_path = 'C:\\Users\\GuillemUPV\\chromedriver-win64\\chromedriver.exe'
# Inicializar el navegador
driver = webdriver.Chrome()

# URL de la página web
url = 'https://www.whoscored.com/Matches/738817/Live/Spain-LaLiga-2013-2014-Malaga-Levante'
# Acceder a la página web
driver.get(url)

print("Running...")
# Esperar a que la página cargue completamente (puedes ajustar este tiempo según sea necesario)
driver.implicitly_wait(10)

events = {"team_id": [], "player_id": [], "incident_type": [], "incident_minute": [], "title": []}

scrollable = driver.find_element(By.CSS_SELECTOR,'.scrollable')
incidents = scrollable.find_elements(By.CSS_SELECTOR,'.timeline-event')
for incident in incidents:
    incident_type = incident.get_attribute('data-type')
    incident_minute = incident.get_attribute('data-minute')
    title = incident.get_attribute('title')
    equipo_id = incident.get_attribute("data-team-id")
    player_id = incident.get_attribute("data-player-id")
    if title=='Sub out': minutes_played = int(incident_minute)
    if title=='Sub in': minutes_played = 90-int(incident_minute)

    print(f"team_id: {equipo_id}, player_id: {player_id}, type: {incident_type}, minute: {incident_minute}, title: {title}")

    events["team_id"].append(equipo_id), events["player_id"].append(player_id)
    events["incident_type"].append(incident_type), events["incident_minute"].append(incident_minute), events["title"].append(title)

# Cerrar el navegador
driver.quit()

df_events = pd.DataFrame(events)

Running...
team_id: 69, player_id: 83080, type: 19, minute: 76, title: Sub in
team_id: 69, player_id: 31124, type: 19, minute: 82, title: Sub in
team_id: 69, player_id: 31124, type: 13, minute: 90, title: Penalty missed
team_id: 69, player_id: 87647, type: 19, minute: 69, title: Sub in
team_id: 69, player_id: 23621, type: 7, minute: 19, title: Last man tackle
team_id: 69, player_id: 125509, type: 18, minute: 82, title: Sub out
team_id: 69, player_id: 135233, type: 18, minute: 69, title: Sub out
team_id: 69, player_id: 83360, type: 16, minute: 59, title: Goal
team_id: 69, player_id: 125299, type: 18, minute: 76, title: Sub out
team_id: 832, player_id: 65901, type: 51, minute: 59, title: Error lead to goal
team_id: 832, player_id: 5999, type: 17, minute: 56, title: Yellow Card
team_id: 832, player_id: 27384, type: 17, minute: 28, title:
team_id: 832, player_id: 27384, type: 17, minute: 79, title: Red Card
team_id: 832, player_id: 5628, type: 18, minute: 64, title: Sub out
team_id: 832, player_id: 23541, type: 18, minute: 68, title: Sub out
team_id: 832, player_id: 19391, type: 18, minute: 45, title: Sub out
team_id: 832, player_id: 22325, type: 19, minute: 45, title: Sub in
team_id: 832, player_id: 44282, type: 19, minute: 64, title: Sub in
team_id: 832, player_id: 23167, type: 19, minute: 68, title: Sub in

In [5]:
df_events

   team_id player_id incident_type incident_minute               title
0       69     83080            19              76              Sub in
1       69     31124            19              82              Sub in
2       69     31124            13              90      Penalty missed
3       69     87647            19              69              Sub in
4       69     23621             7              19     Last man tackle
5       69    125509            18              82             Sub out
6       69    135233            18              69             Sub out
7       69     83360            16              59                Goal
8       69    125299            18              76             Sub out
9      832     65901            51              59  Error lead to goal
10     832      5999            17              56         Yellow Card
11     832     27384            17              28
12     832     27384            17              79            Red Card
13     832      5628            18              64             Sub out
14     832     23541            18              68             Sub out
15     832     19391            18              45             Sub out
16     832     22325            19              45              Sub in
17     832     44282            19              64              Sub in
18     832     23167            19              68              Sub in

In [7]:
from collections import defaultdict
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

# Ruta al controlador del navegador (especifica la ruta correcta)
driver_path = 'C:\\Users\\GuillemUPV\\chromedriver-win64\\chromedriver.exe'
# Inicializar el navegador
driver = webdriver.Chrome()

# URL de la página web
url = 'https://www.whoscored.com/Matches/738817/Live/Spain-LaLiga-2013-2014-Malaga-Levante'
# Acceder a la página web
driver.get(url)

# Esperar a que la página cargue completamente (puedes ajustar este tiempo según sea necesario)
driver.implicitly_wait(2)

players = defaultdict(lambda: defaultdict(dict))

for tipo in ['.pitch-field', '.bench']:
    # Encontrar todos los elementos de jugador o banquillo
    equipo_H, equipo_A = driver.find_elements(By.CSS_SELECTOR, tipo)

    equipo_id_H = equipo_H.get_attribute("data-team-id")
    equipo_id_A = equipo_A.get_attribute("data-team-id")
    field_H = equipo_H.get_attribute('data-field')
    field_A = equipo_A.get_attribute('data-field')
    
    jugadores_H = equipo_H.find_elements(By.CSS_SELECTOR, f'.player[data-field="{field_H}"]')
    jugadores_A = equipo_A.find_elements(By.CSS_SELECTOR, f'.player[data-field="{field_A}"]')

    # Iterar sobre los jugadores titulares e imprimir sus datos
    for jugador_H,jugador_A in zip(jugadores_H,jugadores_A):

        ActionChains(driver).click(jugador_H).perform()
        ActionChains(driver).click(jugador_A).perform()
        
        # Esperar a que aparezca la ventana emergente (puedes ajustar este tiempo según sea necesario)
        driver.implicitly_wait(2)

        for jugador in [jugador_H,jugador_A]:
            player_id = jugador.get_attribute("data-player-id")
            field = jugador.get_attribute("data-field")

            # Obtener datos de la ventana emergente
            player_info = driver.find_element(By.CSS_SELECTOR, f'.compared[data-mode="player"][data-field={field}]')
            position = player_info.find_element(By.CSS_SELECTOR, '.player-position').text
            age = player_info.find_element(By.CSS_SELECTOR, '.player-age').text
            height = player_info.find_element(By.CSS_SELECTOR, '.player-height').text
            weight = player_info.find_element(By.CSS_SELECTOR, '.player-weight').text

            # Cerrar la ventana emergente
            # driver.find_element(By.CSS_SELECTOR, '.close-comparison').click()

            # Obtener otros datos del jugador
            nombre = jugador.find_element(By.CSS_SELECTOR, '.player-name').text
            numero_camiseta = jugador.find_element(By.CSS_SELECTOR, '.shirt-number').text
            puntaje = jugador.find_element(By.CSS_SELECTOR, '.player-stat-value').text

            minutes_played = 90 if tipo == '.pitch-field' else 0

            # Agregar datos a la estructura
            players[player_id]["team_id"] = equipo_id
            players[player_id]["field"] = field
            players[player_id]["player_id"] = player_id
            players[player_id]["nombre"] = nombre
            players[player_id]["titular"] = int(tipo == '.pitch-field')
            players[player_id]["rating"] = puntaje
            players[player_id]["minutes_played"] = minutes_played
            players[player_id]["position"] = position
            players[player_id]["age"] = age
            players[player_id]["height"] = height
            players[player_id]["weight"] = weight

            # Obtener datos de estadísticas
            stats_container = driver.find_element(By.CSS_SELECTOR, '.match-centre-stats[data-mode="player"]')
            stats = stats_container.find_elements(By.CSS_SELECTOR, 'li[class="match-centre-stat match-centre-sub-stat"]')

            for stat in stats:
                stat_name = stat.get_attribute('data-for')
                stat_value = stat.find_element(By.CSS_SELECTOR,f'.match-centre-stat-value[data-field="{field}"]').get_attribute('data-value')
                players[player_id][stat_name] = stat_value
                print(field,nombre,stat_name,stat_value)

# Cerrar el navegador
driver.quit()

df_players = pd.DataFrame(players).T

home Caballero shotsTotal 0
home Caballero shotsOnPost 0
home Caballero shotsOnTarget 0
home Caballero shotsOffTarget 0
home Caballero shotsBlocked 0
home Caballero possession 0
home Caballero touches 38
home Caballero passSuccess 76
home Caballero passesTotal 17
home Caballero passesAccurate 13
home Caballero passesKey 0
home Caballero dribblesWon 0
home Caballero dribblesAttempted 0
home Caballero dribbledPast 0
home Caballero dribbleSuccess 0
home Caballero aerialsWon 1
home Caballero aerialSuccess 100
home Caballero offensiveAerials 0
home Caballero defensiveAerials 1
home Caballero tackleSuccessful 0
home Caballero tacklesTotal 0
home Caballero tackleUnsuccesful 0
home Caballero tackleSuccess 0
home Caballero clearances 1
home Caballero interceptions 0
home Caballero cornersTotal 0
home Caballero cornerAccuracy 0
home Caballero dispossessed 0
home Caballero errors 0
home Caballero foulsCommited 0
home Caballero offsidesCaught 0
home Caballero totalSaves 0
home Caballero collected 0
home Caballero parriedSafe 0
home Caballero parriedDanger 0
home Caballero goalsConceded 0
away Navas shotsTotal 0
away Navas shotsOnPost 0
away Navas shotsOnTarget 0
away Navas shotsOffTarget 0
away Navas shotsBlocked 0
away Navas possession 0
away Navas touches 70
away Navas passSuccess 52
away Navas passesTotal 42
away Navas passesAccurate 22
away Navas passesKey 0
away Navas dribblesWon 0
away Navas dribblesAttempted 0
away Navas dribbledPast 0
away Navas dribbleSuccess 0
away Navas aerialsWon 0
away Navas aerialSuccess 0
away Navas offensiveAerials 0
away Navas defensiveAerials 0
away Navas tackleSuccessful 0
away Navas tacklesTotal 0
away Navas tackleUnsuccesful 0
away Navas tackleSuccess 0
away Navas clearances 1
away Navas interceptions 0
away Navas cornersTotal 0
away Navas cornerAccuracy 0
away Navas dispossessed 0
away Navas errors 1
away Navas foulsCommited 0
away Navas offsidesCaught 0
away Navas totalSaves 10
away Navas collected 3
away Navas parriedSafe 3
away Navas parriedDanger 3
away Navas goalsConceded 0
home Eliseu shotsTotal 3
home Eliseu shotsOnPost 0
home Eliseu shotsOnTarget 0
home Eliseu shotsOffTarget 3
home Eliseu shotsBlocked 0
home Eliseu possession 0
home Eliseu touches 65
home Eliseu passSuccess 88
home Eliseu passesTotal 52
home Eliseu passesAccurate 46
home Eliseu passesKey 2
home Eliseu dribblesWon 2
home Eliseu dribblesAttempted 2
home Eliseu dribbledPast 0
home Eliseu dribbleSuccess 100
home Eliseu aerialsWon 2
home Eliseu aerialSuccess 33
home Eliseu offensiveAerials 1
home Eliseu defensiveAerials 5
home Eliseu tackleSuccessful 2
home Eliseu tacklesTotal 2
home Eliseu tackleUnsuccesful 0
home Eliseu tackleSuccess 100
home Eliseu clearances 1
home Eliseu interceptions 0
home Eliseu cornersTotal 0
home Eliseu cornerAccuracy 0
home Eliseu dispossessed 0
home Eliseu errors 0
home Eliseu foulsCommited 2
home Eliseu offsidesCaught 0
home Eliseu totalSaves 0
home Eliseu collected 0
home Eliseu parriedSafe 0
home Eliseu parriedDanger 0
home Eliseu goalsConceded 0
away Nagore shotsTotal 0
away Nagore shotsOnPost 0
away Nagore shotsOnTarget 0
away Nagore shotsOffTarget 0
away Nagore shotsBlocked 0
away Nagore possession 0
away Nagore touches 47
away Nagore passSuccess 71
away Nagore passesTotal 31
away Nagore passesAccurate 22
away Nagore passesKey 0
away Nagore dribblesWon 0
away Nagore dribblesAttempted 3
away Nagore dribbledPast 1
away Nagore dribbleSuccess 0
away Nagore aerialsWon 0
away Nagore aerialSuccess 0
away Nagore offensiveAerials 0
away Nagore defensiveAerials 0
away Nagore tackleSuccessful 3
away Nagore tacklesTotal 4
away Nagore tackleUnsuccesful 1
away Nagore tackleSuccess 75
away Nagore clearances 1
away Nagore interceptions 4
away Nagore cornersTotal 0
away Nagore cornerAccuracy 0
away Nagore dispossessed 1
away Nagore errors 0
away Nagore foulsCommited 2
away Nagore offsidesCaught 0
away Nagore totalSaves 0
away Nagore collected 0
away Nagore parriedSafe 0
away Nagore parriedDanger 0
away Nagore goalsConceded 0
home Weligton shotsTotal 0
home Weligton shotsOnPost 0
home Weligton shotsOnTarget 0
home Weligton shotsOffTarget 0
home Weligton shotsBlocked 0
home Weligton possession 0
home Weligton touches 42
home Weligton passSuccess 86
home Weligton passesTotal 37
home Weligton passesAccurate 32
home Weligton passesKey 0
home Weligton dribblesWon 0
home Weligton dribblesAttempted 0
home Weligton dribbledPast 1
home Weligton dribbleSuccess 0
home Weligton aerialsWon 3
home Weligton aerialSuccess 60
home Weligton offensiveAerials 0
home Weligton defensiveAerials 5
home Weligton tackleSuccessful 0
home Weligton tacklesTotal 1
home Weligton tackleUnsuccesful 1
home Weligton tackleSuccess 0
home Weligton clearances 2
home Weligton interceptions 2
home Weligton cornersTotal 0
home Weligton cornerAccuracy 0
home Weligton dispossessed 0
home Weligton errors 0
home Weligton foulsCommited 0
home Weligton offsidesCaught 0
home Weligton totalSaves 0
home Weligton collected 0
home Weligton parriedSafe 0
home Weligton parriedDanger 0
home Weligton goalsConceded 0
away Vyntra shotsTotal 0
away Vyntra shotsOnPost 0
away Vyntra shotsOnTarget 0
away Vyntra shotsOffTarget 0
away Vyntra shotsBlocked 0
away Vyntra possession 0
away Vyntra touches 38
away Vyntra passSuccess 93
away Vyntra passesTotal 29
away Vyntra passesAccurate 27
away Vyntra passesKey 1
away Vyntra dribblesWon 0
away Vyntra dribblesAttempted 0
away Vyntra dribbledPast 1
away Vyntra dribbleSuccess 0
away Vyntra aerialsWon 1
away Vyntra aerialSuccess 50
away Vyntra offensiveAerials 0
away Vyntra defensiveAerials 2
away Vyntra tackleSuccessful 0
away Vyntra tacklesTotal 1
away Vyntra tackleUnsuccesful 1
away Vyntra tackleSuccess 0
away Vyntra clearances 6
away Vyntra interceptions 2
away Vyntra cornersTotal 0
away Vyntra cornerAccuracy 0
away Vyntra dispossessed 0
away Vyntra errors 0
away Vyntra foulsCommited 1
away Vyntra offsidesCaught 0
away Vyntra totalSaves 0
away Vyntra collected 0
away Vyntra parriedSafe 0
away Vyntra parriedDanger 0
away Vyntra goalsConceded 0
home Camacho shotsTotal 1
home Camacho shotsOnPost 0
home Camacho shotsOnTarget 0
home Camacho shotsOffTarget 1
home Camacho shotsBlocked 0
home Camacho possession 0
home Camacho touches 71
home Camacho passSuccess 87
home Camacho passesTotal 53
home Camacho passesAccurate 46
home Camacho passesKey 0
home Camacho dribblesWon 0
home Camacho dribblesAttempted 0
home Camacho dribbledPast 0
home Camacho dribbleSuccess 0
home Camacho aerialsWon 7
home Camacho aerialSuccess 100
home Camacho offensiveAerials 0
home Camacho defensiveAerials 7
home Camacho tackleSuccessful 1
home Camacho tacklesTotal 1
home Camacho tackleUnsuccesful 0
home Camacho tackleSuccess 100
home Camacho clearances 10
home Camacho interceptions 2
home Camacho cornersTotal 1
home Camacho cornerAccuracy 0
home Camacho dispossessed 0
home Camacho errors 0
home Camacho foulsCommited 0
home Camacho offsidesCaught 0
home Camacho totalSaves 0
home Camacho collected 0
home Camacho parriedSafe 0
home Camacho parriedDanger 0
home Camacho goalsConceded 0
away Navarro shotsTotal 0
away Navarro shotsOnPost 0
away Navarro shotsOnTarget 0
away Navarro shotsOffTarget 0
away Navarro shotsBlocked 0
away Navarro possession 0
away Navarro touches 50
away Navarro passSuccess 84
away Navarro passesTotal 38
away Navarro passesAccurate 32
away Navarro passesKey 0
away Navarro dribblesWon 0
away Navarro dribblesAttempted 0
away Navarro dribbledPast 0
away Navarro dribbleSuccess 0
away Navarro aerialsWon 1
away Navarro aerialSuccess 33
away Navarro offensiveAerials 0
away Navarro defensiveAerials 3
away Navarro tackleSuccessful 3
away Navarro tacklesTotal 3
away Navarro tackleUnsuccesful 0
away Navarro tackleSuccess 100
away Navarro clearances 5
away Navarro interceptions 1
away Navarro cornersTotal 0
away Navarro cornerAccuracy 0
away Navarro dispossessed 1
away Navarro errors 0
away Navarro foulsCommited 1
away Navarro offsidesCaught 0
away Navarro totalSaves 0
away Navarro collected 0
away Navarro parriedSafe 0
away Navarro parriedDanger 0
away Navarro goalsConceded 0
home Antunes shotsTotal 0
home Antunes shotsOnPost 0
home Antunes shotsOnTarget 0
home Antunes shotsOffTarget 0
home Antunes shotsBlocked 0
home Antunes possession 0
home Antunes touches 55
home Antunes passSuccess 79
home Antunes passesTotal 47
home Antunes passesAccurate 37
home Antunes passesKey 1
home Antunes dribblesWon 0
home Antunes dribblesAttempted 0
home Antunes dribbledPast 0
home Antunes dribbleSuccess 0
home Antunes aerialsWon 0
home Antunes aerialSuccess 0
home Antunes offensiveAerials 0
home Antunes defensiveAerials 2
home Antunes tackleSuccessful 2
home Antunes tacklesTotal 2
home Antunes tackleUnsuccesful 0
home Antunes tackleSuccess 100
home Antunes clearances 1
home Antunes interceptions 0
home Antunes cornersTotal 1
home Antunes cornerAccuracy 0
home Antunes dispossessed 0
home Antunes errors 0
home Antunes foulsCommited 1
home Antunes offsidesCaught 0
home Antunes totalSaves 0
home Antunes collected 0
home Antunes parriedSafe 0
home Antunes parriedDanger 0
home Antunes goalsConceded 0
away Juanfran shotsTotal 0
away Juanfran shotsOnPost 0
away Juanfran shotsOnTarget 0
away Juanfran shotsOffTarget 0
away Juanfran shotsBlocked 0
away Juanfran possession 0
away Juanfran touches 46
away Juanfran passSuccess 72
away Juanfran passesTotal 32
away Juanfran passesAccurate 23
away Juanfran passesKey 0
away Juanfran dribblesWon 0
away Juanfran dribblesAttempted 0
away Juanfran dribbledPast 1
away Juanfran dribbleSuccess 0
away Juanfran aerialsWon 3
away Juanfran aerialSuccess 75
away Juanfran offensiveAerials 2
away Juanfran defensiveAerials 2
away Juanfran tackleSuccessful 1
away Juanfran tacklesTotal 2
away Juanfran tackleUnsuccesful 1
away Juanfran tackleSuccess 50
away Juanfran clearances 3
away Juanfran interceptions 7
away Juanfran cornersTotal 0
away Juanfran cornerAccuracy 0
away Juanfran dispossessed 1
away Juanfran errors 0
away Juanfran foulsCommited 0
away Juanfran offsidesCaught 0
away Juanfran totalSaves 0
away Juanfran collected 0
away Juanfran parriedSafe 0
away Juanfran parriedDanger 0
away Juanfran goalsConceded 0
home Pérez shotsTotal 4
home Pérez shotsOnPost 0
home Pérez shotsOnTarget 2
home Pérez shotsOffTarget 2
home Pérez shotsBlocked 0
home Pérez possession 0
home Pérez touches 72
home Pérez passSuccess 90
home Pérez passesTotal 52
home Pérez passesAccurate 47
home Pérez passesKey 6
home Pérez dribblesWon 0
home Pérez dribblesAttempted 0
home Pérez dribbledPast 0
home Pérez dribbleSuccess 0
home Pérez aerialsWon 1
home Pérez aerialSuccess 33
home Pérez offensiveAerials 2
home Pérez defensiveAerials 1
home Pérez tackleSuccessful 3
home Pérez tacklesTotal 3
home Pérez tackleUnsuccesful 0
home Pérez tackleSuccess 100
home Pérez clearances 0
home Pérez interceptions 2
home Pérez cornersTotal 1
home Pérez cornerAccuracy 200
home Pérez dispossessed 0
home Pérez errors 0
home Pérez foulsCommited 1
home Pérez offsidesCaught 0
home Pérez totalSaves 0
home Pérez collected 0
home Pérez parriedSafe 0
home Pérez parriedDanger 0
home Pérez goalsConceded 0
away Sissoko shotsTotal 0
away Sissoko shotsOnPost 0
away Sissoko shotsOnTarget 0
away Sissoko shotsOffTarget 0
away Sissoko shotsBlocked 0
away Sissoko possession 0
away Sissoko touches 53
away Sissoko passSuccess 86
away Sissoko passesTotal 37
away Sissoko passesAccurate 32
away Sissoko passesKey 0
away Sissoko dribblesWon 1
away Sissoko dribblesAttempted 2
away Sissoko dribbledPast 3
away Sissoko dribbleSuccess 50
away Sissoko aerialsWon 2
away Sissoko aerialSuccess 50
away Sissoko offensiveAerials 2
away Sissoko defensiveAerials 2
away Sissoko tackleSuccessful 3
away Sissoko tacklesTotal 6
away Sissoko tackleUnsuccesful 3
away Sissoko tackleSuccess 50
away Sissoko clearances 0
away Sissoko interceptions 3
away Sissoko cornersTotal 0
away Sissoko cornerAccuracy 0
away Sissoko dispossessed 0
away Sissoko errors 0
away Sissoko foulsCommited 3
away Sissoko offsidesCaught 0
away Sissoko totalSaves 0
away Sissoko collected 0
away Sissoko parriedSafe 0
away Sissoko parriedDanger 0
away Sissoko goalsConceded 0
home Darder shotsTotal 2
home Darder shotsOnPost 0
home Darder shotsOnTarget 0
home Darder shotsOffTarget 1
home Darder shotsBlocked 1
home Darder possession 0
home Darder touches 70
home Darder passSuccess 92
home Darder passesTotal 59
home Darder passesAccurate 54
home Darder passesKey 1
home Darder dribblesWon 2
home Darder dribblesAttempted 3
home Darder dribbledPast 1
home Darder dribbleSuccess 67
home Darder aerialsWon 0
home Darder aerialSuccess 0
home Darder offensiveAerials 2
home Darder defensiveAerials 0
home Darder tackleSuccessful 3
home Darder tacklesTotal 4
home Darder tackleUnsuccesful 1
home Darder tackleSuccess 75
home Darder clearances 0
home Darder interceptions 2
home Darder cornersTotal 1
home Darder cornerAccuracy 0
home Darder dispossessed 1
home Darder errors 0
home Darder foulsCommited 1
home Darder offsidesCaught 1
home Darder totalSaves 0
home Darder collected 0
home Darder parriedSafe 0
home Darder parriedDanger 0
home Darder goalsConceded 0
away Diop shotsTotal 0
away Diop shotsOnPost 0
away Diop shotsOnTarget 0
away Diop shotsOffTarget 0
away Diop shotsBlocked 0
away Diop possession 0
away Diop touches 52
away Diop passSuccess 75
away Diop passesTotal 40
away Diop passesAccurate 30
away Diop passesKey 0
away Diop dribblesWon 1
away Diop dribblesAttempted 1
away Diop dribbledPast 4
away Diop dribbleSuccess 100
away Diop aerialsWon 2
away Diop aerialSuccess 67
away Diop offensiveAerials 1
away Diop defensiveAerials 2
away Diop tackleSuccessful 3
away Diop tacklesTotal 7
away Diop tackleUnsuccesful 4
away Diop tackleSuccess 43
away Diop clearances 3
away Diop interceptions 2
away Diop cornersTotal 0
away Diop cornerAccuracy 0
away Diop dispossessed 0
away Diop errors 0
away Diop foulsCommited 3
away Diop offsidesCaught 0
away Diop totalSaves 0
away Diop collected 0
away Diop parriedSafe 0
away Diop parriedDanger 0
away Diop goalsConceded 0
home García shotsTotal 0
home García shotsOnPost 0
home García shotsOnTarget 0
home García shotsOffTarget 0
home García shotsBlocked 0
home García possession 0
home García touches 38
home García passSuccess 76
home García passesTotal 25
home García passesAccurate 19
home García passesKey 1
home García dribblesWon 2
home García dribblesAttempted 4
home García dribbledPast 1
home García dribbleSuccess 50
home García aerialsWon 1
home García aerialSuccess 33
home García offensiveAerials 2
home García defensiveAerials 1
home García tackleSuccessful 2
home García tacklesTotal 3
home García tackleUnsuccesful 1
home García tackleSuccess 67
home García clearances 0
home García interceptions 0
home García cornersTotal 1
home García cornerAccuracy 0
home García dispossessed 2
home García errors 0
home García foulsCommited 1
home García offsidesCaught 1
home García totalSaves 0
home García collected 0
home García parriedSafe 0
home García parriedDanger 0
home García goalsConceded 0
away Pinto shotsTotal 1
away Pinto shotsOnPost 0
away Pinto shotsOnTarget 0
away Pinto shotsOffTarget 0
away Pinto shotsBlocked 1
away Pinto possession 0
away Pinto touches 39
away Pinto passSuccess 86
away Pinto passesTotal 29
away Pinto passesAccurate 25
away Pinto passesKey 0
away Pinto dribblesWon 0
away Pinto dribblesAttempted 1
away Pinto dribbledPast 2
away Pinto dribbleSuccess 0
away Pinto aerialsWon 0
away Pinto aerialSuccess 0
away Pinto offensiveAerials 0
away Pinto defensiveAerials 0
away Pinto tackleSuccessful 1
away Pinto tacklesTotal 3
away Pinto tackleUnsuccesful 2
away Pinto tackleSuccess 33
away Pinto clearances 0
away Pinto interceptions 1
away Pinto cornersTotal 0
away Pinto cornerAccuracy 0
away Pinto dispossessed 1
away Pinto errors 0
away Pinto foulsCommited 2
away Pinto offsidesCaught 0
away Pinto totalSaves 0
away Pinto collected 0
away Pinto parriedSafe 0
away Pinto parriedDanger 0
away Pinto goalsConceded 0
home Portillo shotsTotal 3
home Portillo shotsOnPost 0
home Portillo shotsOnTarget 1
home Portillo shotsOffTarget 2
home Portillo shotsBlocked 0
home Portillo possession 0
home Portillo touches 90
home Portillo passSuccess 93
home Portillo passesTotal 68
home Portillo passesAccurate 63
home Portillo passesKey 4
home Portillo dribblesWon 3
home Portillo dribblesAttempted 7
home Portillo dribbledPast 2
home Portillo dribbleSuccess 43
home Portillo aerialsWon 0
home Portillo aerialSuccess 0
home Portillo offensiveAerials 0
home Portillo defensiveAerials 0
home Portillo tackleSuccessful 3
home Portillo tacklesTotal 5
home Portillo tackleUnsuccesful 2
home Portillo tackleSuccess 60
home Portillo clearances 0
home Portillo interceptions 0
home Portillo cornersTotal 2
home Portillo cornerAccuracy 50
home Portillo dispossessed 1
home Portillo errors 0
home Portillo foulsCommited 0
home Portillo offsidesCaught 0
home Portillo totalSaves 0
home Portillo collected 0
home Portillo parriedSafe 0
home Portillo parriedDanger 0
home Portillo goalsConceded 0
away Casadesús shotsTotal 0
away Casadesús shotsOnPost 0
away Casadesús shotsOnTarget 0
away Casadesús shotsOffTarget 0
away Casadesús shotsBlocked 0
away Casadesús possession 0
away Casadesús touches 36
away Casadesús passSuccess 79
away Casadesús passesTotal 28
away Casadesús passesAccurate 22
away Casadesús passesKey 0
away Casadesús dribblesWon 2
away Casadesús dribblesAttempted 3
away Casadesús dribbledPast 0
away Casadesús dribbleSuccess 67
away Casadesús aerialsWon 3
away Casadesús aerialSuccess 33
away Casadesús offensiveAerials 9
away Casadesús defensiveAerials 0
away Casadesús tackleSuccessful 0
away Casadesús tacklesTotal 0
away Casadesús tackleUnsuccesful 0
away Casadesús tackleSuccess 0
away Casadesús clearances 1
away Casadesús interceptions 2
away Casadesús cornersTotal 0
away Casadesús cornerAccuracy 0
away Casadesús dispossessed 1
away Casadesús errors 0
away Casadesús foulsCommited 0
away Casadesús offsidesCaught 0
away Casadesús totalSaves 0
away Casadesús collected 0
away Casadesús parriedSafe 0
away Casadesús parriedDanger 0
away Casadesús goalsConceded 0
home Amrabat shotsTotal 4
home Amrabat shotsOnPost 0
home Amrabat shotsOnTarget 3
home Amrabat shotsOffTarget 1
home Amrabat shotsBlocked 0
home Amrabat possession 0
home Amrabat touches 46
home Amrabat passSuccess 77
home Amrabat passesTotal 26
home Amrabat passesAccurate 20
home Amrabat passesKey 3
home Amrabat dribblesWon 3
home Amrabat dribblesAttempted 5
home Amrabat dribbledPast 0
home Amrabat dribbleSuccess 60
home Amrabat aerialsWon 0
home Amrabat aerialSuccess 0
home Amrabat offensiveAerials 0
home Amrabat defensiveAerials 0
home Amrabat tackleSuccessful 1
home Amrabat tacklesTotal 1
home Amrabat tackleUnsuccesful 0
home Amrabat tackleSuccess 100
home Amrabat clearances 0
home Amrabat interceptions 0
home Amrabat cornersTotal 1
home Amrabat cornerAccuracy 0
home Amrabat dispossessed 0
home Amrabat errors 0
home Amrabat foulsCommited 3
home Amrabat offsidesCaught 3
home Amrabat totalSaves 0
home Amrabat collected 0
home Amrabat parriedSafe 0
home Amrabat parriedDanger 0
home Amrabat goalsConceded 0
away Ríos shotsTotal 0
away Ríos shotsOnPost 0
away Ríos shotsOnTarget 0
away Ríos shotsOffTarget 0
away Ríos shotsBlocked 0
away Ríos possession 0
away Ríos touches 25
away Ríos passSuccess 77
away Ríos passesTotal 13
away Ríos passesAccurate 10
away Ríos passesKey 0
away Ríos dribblesWon 0
away Ríos dribblesAttempted 1
away Ríos dribbledPast 2
away Ríos dribbleSuccess 0
away Ríos aerialsWon 2
away Ríos aerialSuccess 33
away Ríos offensiveAerials 6
away Ríos defensiveAerials 0
away Ríos tackleSuccessful 2
away Ríos tacklesTotal 4
away Ríos tackleUnsuccesful 2
away Ríos tackleSuccess 50
away Ríos clearances 0
away Ríos interceptions 2
away Ríos cornersTotal 0
away Ríos cornerAccuracy 0
away Ríos dispossessed 3
away Ríos errors 0
away Ríos foulsCommited 2
away Ríos offsidesCaught 0
away Ríos totalSaves 0
away Ríos collected 0

In [8]:
df_players

,team_id,field,player_id,nombre,titular,rating,minutes_played,position,age,height,...,cornerAccuracy,dispossessed,errors,foulsCommited,offsidesCaught,totalSaves,collected,parriedSafe,parriedDanger,goalsConceded
34749,832,home,34749,Caballero,1,6.7,90,GK,42,186,...,0,0,0,0,0,0,0,0,0,0
65901,832,away,65901,Navas,1,7.8,90,GK,37,185,...,0,0,1,0,0,10,3,3,3,0
23309,832,home,23309,Eliseu,1,7.5,90,DR,40,175,...,0,0,0,2,0,0,0,0,0,0
141281,832,away,141281,Nagore,1,6.3,90,DR,43,182,...,0,1,0,2,0,0,0,0,0,0
13289,832,home,13289,Weligton,1,7.0,90,DC,44,186,...,0,0,0,0,0,0,0,0,0,0
10687,832,away,10687,Vyntra,1,6.7,90,DC,42,184,...,0,0,0,1,0,0,0,0,0,0
35199,832,home,35199,Camacho,1,7.9,90,DC,33,182,...,0,0,0,0,0,0,0,0,0,0
5999,832,away,5999,Navarro,1,6.8,90,DC,43,188,...,0,1,0,1,0,0,0,0,0,0
23621,832,home,23621,Antunes,1,7.1,90,DL,36,175,...,0,0,0,1,0,0,0,0,0,0
1324,832,away,1324,Juanfran,1,7.0,90,DL,47,183,...,0,1,0,0,0,0,0,0,0,0
125509,832,home,125509,Pérez,1,8.2,90,DMC,38,175,...,200,0,0,1,0,0,0,0,0,0
9576,832,away,9576,Sissoko,1,6.7,90,DMC,39,191,...,0,0,0,3,0,0,0,0,0,0
106596,832,home,106596,Darder,1,7.3,90,DMC,30,180,...,0,1,0,1,1,0,0,0,0,0
27384,832,away,27384,Diop,1,6.0,90,DMC,37,180,...,0,0,0,3,0,0,0,0,0,0
135233,832,home,135233,García,1,6.8,90,AMR,33,179,...,0,2,0,1,1,0,0,0,0,0
5628,832,away,5628,Pinto,1,6.0,90,AMR,43,176,...,0,1,0,2,0,0,0,0,0,0
83360,832,home,83360,Portillo,1,8.4,90,AMC,33,169,...,50,1,0,0,0,0,0,0,0,0
14077,832,away,14077,Casadesús,1,6.6,90,AMC,38,180,...,0,1,0,0,0,0,0,0,0,0
22932,832,home,22932,Amrabat,1,7.5,90,AML,36,179,...,0,0,0,3,3,0,0,0,0,0
23541,832,away,23541,Ríos,1,6.4,90,AML,42,175,...,0,3,0,2,0,0,0,0,0,0
125299,832,home,125299,Rescaldani,1,6.9,90,FW,31,191,...,0,0,0,2,0,0,0,0,0,0
19391,832,away,19391,Barral,1,6.3,90,FW,40,183,...,0,2,0,1,0,0,0,0,0,0
83080,832,home,83080,Juanmi,0,7.2,0,Sub,30,172,...,0,0,0,0,0,0,0,0,0,0
22325,832,away,22325,Rodríguez,0,5.9,0,Sub,36,172,...,0,0,0,1,2,0,0,0,0,0
31124,832,home,31124,Casado,0,5.4,0,Sub,37,173,...,0,1,0,0,0,0,0,0,0,0
44282,832,away,44282,Xumetra,0,6.1,0,Sub,38,172,...,0,0,0,0,0,0,0,0,0,0
87647,832,home,87647,Pawlowski,0,6.2,0,Sub,31,178,...,0,0,0,1,0,0,0,0,0,0
23167,832,away,23167,Zhar,0,6.0,0,Sub,37,171,...,0,1,0,0,0,0,0,0,0,0
3515,832,home,3515,Kameni,0,,0,Sub,39,186,...,0,0,0,0,0,0,0,0,0,0
5206,832,away,5206,Ivanschitz,0,,0,Sub,40,184,...,0,0,0,0,0,0,0,0,0,0
954,832,home,954,Cruz,0,,0,Sub,42,191,...,0,0,0,0,0,0,0,0,0,0
35209,832,away,35209,Karámpelas,0,,0,Sub,39,180,...,0,0,0,0,0,0,0,0,0,0
18659,832,home,18659,Iakovenko,0,,0,Sub,42,191,...,0,0,0,0,0,0,0,0,0,0
14104,832,away,14104,Pallardó,0,,0,Sub,39,180,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df_players.columns

Index(['team_id', 'field', 'player_id', 'nombre', 'titular', 'rating',
       'minutes_played', 'position', 'age', 'height', 'weight', 'shotsTotal',
       'shotsOnPost', 'shotsOnTarget', 'shotsOffTarget', 'shotsBlocked',
       'possession', 'touches', 'passSuccess', 'passesTotal', 'passesAccurate',
       'passesKey', 'dribblesWon', 'dribblesAttempted', 'dribbledPast',
       'dribbleSuccess', 'aerialsWon', 'aerialSuccess', 'offensiveAerials',
       'defensiveAerials', 'tackleSuccessful', 'tacklesTotal',
       'tackleUnsuccesful', 'tackleSuccess', 'clearances', 'interceptions',
       'cornersTotal', 'cornerAccuracy', 'dispossessed', 'errors',
       'foulsCommited', 'offsidesCaught', 'totalSaves', 'collected',
       'parriedSafe', 'parriedDanger', 'goalsConceded'],
      dtype='object')

#### STEP BY STEP

In [20]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
import undetected_chromedriver as uc
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
proxy = "socks5://127.0.0.1:9050"
resolver_rules = "MAP * 0.0.0.0 , EXCLUDE 127.0.0.1"
# chrome_options.add_argument("--headless")  # maybe try without this line too
# chrome_options.add_argument("--proxy-server=" + proxy)
# chrome_options.add_argument("--host-resolver-rules=" + resolver_rules)
driver = uc.Chrome(options=chrome_options)

# Ruta al controlador del navegador (especifica la ruta correcta)

# URL de la página web
url = 'https://www.whoscored.com/Matches/738817/Live/Spain-LaLiga-2013-2014-Malaga-Levante'
# Acceder a la página web
driver.get(url)

# Esperar a que la página cargue completamente (puedes ajustar este tiempo según sea necesario)
driver.implicitly_wait(20)

players = {"team_id": [], "field": [], "player_id": [], "nombre": [], "titular": [], "rating": [], "minutes_played": [],
           "position": [], "age": [], "height": [], "weight": []}

In [22]:
tipo = '.pitch-field'
field = 'home'

teams = driver.find_elements(By.CSS_SELECTOR,'.pitch-field')
driver.implicitly_wait(20)

teams[0]
teams_id = list(map(lambda x: x.get_attribute("data-team-id"),teams))
teams_field = list(map(lambda x: x.get_attribute("data-field"),teams))

teams_id,teams_field

(['69', '832'], ['home', 'away'])

In [23]:
jugadores = driver.find_elements(By.CSS_SELECTOR, f'.player')

jugador = jugadores[12]

player_id = jugador.get_attribute("data-player-id")
team_field = jugador.get_attribute("data-field")

nombre = jugador.find_element(By.CSS_SELECTOR, '.player-name').text
numero_camiseta = jugador.find_element(By.CSS_SELECTOR, '.shirt-number').text
puntaje = jugador.find_element(By.CSS_SELECTOR, '.player-stat-value').text

ActionChains(driver).click(jugador).perform()
driver.implicitly_wait(2)

player_info = driver.find_element(By.CSS_SELECTOR, f'.compared[data-mode="player"][data-field="{team_field}"]')
position = player_info.find_element(By.CSS_SELECTOR, '.player-position').text
age = player_info.find_element(By.CSS_SELECTOR, '.player-age').text
height = player_info.find_element(By.CSS_SELECTOR, '.player-height').text
weight = player_info.find_element(By.CSS_SELECTOR, '.player-weight').text

player_id, team_field, nombre, numero_camiseta, puntaje, position, age, height, weight

('106596', 'home', 'Darder', '30.', '7.3', '', '', '', '')

In [125]:
stats_container = driver.find_element(By.CSS_SELECTOR, '.match-centre-stats[data-mode="player"]')
stats = stats_container.find_elements(By.CSS_SELECTOR, 'li[class="match-centre-stat match-centre-sub-stat"]')

stats

[<selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1132")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1133")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1134")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1135")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1136")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1137")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1138")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1139")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1140")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1141")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1142")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1143")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1144")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1145")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1146")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1147")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1148")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1149")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1150")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1151")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1152")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1153")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1154")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1155")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1156")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1157")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1158")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1159")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1160")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1161")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1162")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1163")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1164")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1165")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1166")>,
 <selenium.webdriver.remote.webelement.WebElement (session="70e44b536c1652a1f6d8257ab5a523d6", element="905D27E0D62CF5ED03EEB4AE26B6574D_element_1167")>]

In [140]:
def get_feat(stat,field):
    value = stat.find_element(By.CSS_SELECTOR,f'.match-centre-stat-value[data-field="{field}"]').get_attribute('data-value')
    key = stat.get_attribute('data-for')
    return key,value

In [141]:
value = stats[10].find_element(By.CSS_SELECTOR,f'.match-centre-stat-value[data-field="{team_field}"]').get_attribute('data-value')
key = stats[10].get_attribute('data-for')

key,value
get_feat_field = lambda stat: get_feat(stat,team_field)
list(map(get_feat_field,stats))

[('shotsTotal', '2'),
 ('shotsOnPost', '0'),
 ('shotsOnTarget', '0'),
 ('shotsOffTarget', '1'),
 ('shotsBlocked', '1'),
 ('possession', '0'),
 ('touches', '70'),
 ('passSuccess', '92'),
 ('passesTotal', '59'),
 ('passesAccurate', '54'),
 ('passesKey', '1'),
 ('dribblesWon', '2'),
 ('dribblesAttempted', '3'),
 ('dribbledPast', '1'),
 ('dribbleSuccess', '67'),
 ('aerialsWon', '0'),
 ('aerialSuccess', '0'),
 ('offensiveAerials', '2'),
 ('defensiveAerials', '0'),
 ('tackleSuccessful', '3'),
 ('tacklesTotal', '4'),
 ('tackleUnsuccesful', '1'),
 ('tackleSuccess', '75'),
 ('clearances', '0'),
 ('interceptions', '2'),
 ('cornersTotal', '1'),
 ('cornerAccuracy', '0'),
 ('dispossessed', '1'),
 ('errors', '0'),
 ('foulsCommited', '1'),
 ('offsidesCaught', '1'),
 ('totalSaves', '0'),
 ('collected', '0'),
 ('parriedSafe', '0'),
 ('parriedDanger', '0'),
 ('goalsConceded', '0')]

### NEXT STEPS:

1. Extraer datos de Posicion, Altura, Edad, Disparos, Acierto pase, regates, duelos aereos, paradas, ratings
2. Navegar por diferentes partidos, temporadas y ligas

#### ¿Como nevagar y seleccionar interactivamente?