In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
%env SOCCERDATA_LOGLEVEL=ERROR
#%env SOCCERDATA_NOCACHE=True
#%env SOCCERDATA_NOSTORE=True
%env SOCCERDATA_DIR=/cw/dtaijupiter/NoCsBack/dtai/pieterr/Projects/soccerdata

env: SOCCERDATA_LOGLEVEL=ERROR
env: SOCCERDATA_DIR=/cw/dtaijupiter/NoCsBack/dtai/pieterr/Projects/soccerdata

In [3]:
import soccerdata as sd
import socceraction as sa
import os

# WhoScored

In [7]:
from pathlib import Path, PosixPath

data_dir = Path("F:\TFG\code\scrapping\cache")
data_dir

WindowsPath('F:/TFG/code/scrapping/cache')

In [77]:
proxy={
     "http": "socks5://127.0.0.1:9050",
     "https": "socks5://127.0.0.1:9050",
     'connection_timeout': 50
}

chrome = Path('C:\Program Files\Google\Chrome\Application\chrome.exe')
# chrome = Path("C:\\Users\GuillemUPV\chromedriver-win64\chromedriver.exe")

In [91]:
ws = sd.WhoScored(leagues="ESP-La Liga", seasons='0203', data_dir=data_dir, headless=False)
print(ws.__doc__)

Provides pd.DataFrames from data available at http://whoscored.com.

    Data will be downloaded as necessary and cached locally in
    ``~/soccerdata/data/WhoScored``.

    Parameters
    ----------
    leagues : string or iterable, optional
        IDs of Leagues to include.
    seasons : string, int or list, optional
        Seasons to include. Supports multiple formats.
        Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
    proxy : 'tor' or dict or list(dict) or callable, optional
        Use a proxy to hide your IP address. Valid options are:
            - "tor": Uses the Tor network. Tor should be running in
              the background on port 9050.
            - dict: A dictionary with the proxy to use. The dict should be
              a mapping of supported protocols to proxy addresses. For example::

                  {
                      'http': 'http://10.10.1.10:3128',
                      'https': 'http://10.10.1.10:1080',
                  }

            - list(dict): A list of proxies to choose from. A different proxy will
              be selected from this list after failed requests, allowing rotating
              proxies.
            - callable: A function that returns a valid proxy. This function will
              be called after failed requests, allowing rotating proxies.
    no_cache : bool
        If True, will not use cached data.
    no_store : bool
        If True, will not store downloaded data.
    data_dir : Path
        Path to directory where data will be cached.
    path_to_browser : Path, optional
        Path to the Chrome executable.
    headless : bool, default: True
        If True, will run Chrome in headless mode. Setting this to False might
        help to avoid getting blocked.

## Game schedule

In [92]:
epl_schedule = ws.read_schedule()
epl_schedule.head()

KeyboardInterrupt:

## Injured and suspended players

In [14]:
missing_players = ws.read_missing_players(match_id=1485184)
missing_players

                                                                                                    game_id  \
league             season game                                 team              player
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United Burnley           Charlie Taylor     1485184
                                                                                 Dwight McNeil      1485184
                                                                                 Jay RodrÃ­guez     1485184
                                                                                 Jimmy Dunne        1485184
                                                               Manchester United Eric Bailly        1485184
                                                                                 Facundo Pellistri  1485184
                                                                                 Luke Shaw          1485184
                                                                                 Marcos Rojo        1485184
                                                                                 Paul Pogba         1485184
                                                                                 Phil Jones         1485184
                                                                                 Victor LindelÃ¶f   1485184

                                                                                                    player_id  \
league             season game                                 team              player
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United Burnley           Charlie Taylor        107462
                                                                                 Dwight McNeil         357427
                                                                                 Jay RodrÃ­guez         33891
                                                                                 Jimmy Dunne           366743
                                                               Manchester United Eric Bailly           243814
                                                                                 Facundo Pellistri     404086
                                                                                 Luke Shaw             118244
                                                                                 Marcos Rojo            70050
                                                                                 Paul Pogba             97752
                                                                                 Phil Jones             81726
                                                                                 Victor LindelÃ¶f      100008

                                                                                                              reason  \
league             season game                                 team              player
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United Burnley           Charlie Taylor     injured doubtful
                                                                                 Dwight McNeil      injured doubtful
                                                                                 Jay RodrÃ­guez     injured doubtful
                                                                                 Jimmy Dunne        injured doubtful
                                                               Manchester United Eric Bailly        injured doubtful
                                                                                 Facundo Pellistri             other
                                                                                 Luke Shaw          injured doubtful
                                                                                 Marcos Rojo                 injured
                                                                                 Paul Pogba         injured doubtful
                                                                                 Phil Jones                  injured
                                                                                 Victor LindelÃ¶f   injured doubtful

                                                                                                      status
league             season game                                 team              player
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United Burnley           Charlie Taylor     Doubtful
                                                                                 Dwight McNeil      Doubtful
                                                                                 Jay RodrÃ­guez     Doubtful
                                                                                 Jimmy Dunne        Doubtful
                                                               Manchester United Eric Bailly        Doubtful
                                                                                 Facundo Pellistri       Out
                                                                                 Luke Shaw          Doubtful
                                                                                 Marcos Rojo             Out
                                                                                 Paul Pogba         Doubtful
                                                                                 Phil Jones              Out
                                                                                 Victor LindelÃ¶f   Doubtful

## Match event stream data

In [15]:
events = ws.read_events(match_id=1485184)
events.head()

                                                                           game_id  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317  1485184
                                                               2253458375  1485184
                                                               2253487469  1485184
                                                               2253487473  1485184
                                                               2253487625  1485184

                                                                              period  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317   PreMatch
                                                               2253458375   PreMatch
                                                               2253487469  FirstHalf
                                                               2253487473  FirstHalf
                                                               2253487625  FirstHalf

                                                                           minute  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317       0
                                                               2253458375       0
                                                               2253487469       0
                                                               2253487473       0
                                                               2253487625       0

                                                                           second  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317     0.0
                                                               2253458375     0.0
                                                               2253487469     0.0
                                                               2253487473     0.0
                                                               2253487625     0.0

                                                                           expanded_minute  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317                0
                                                               2253458375                0
                                                               2253487469                0
                                                               2253487473                0
                                                               2253487625                0

                                                                                   type  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317  FormationSet
                                                               2253458375  FormationSet
                                                               2253487469         Start
                                                               2253487473         Start
                                                               2253487625          Pass

                                                                          outcome_type  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317   Successful
                                                               2253458375   Successful
                                                               2253487469   Successful
                                                               2253487473   Successful
                                                               2253487625   Successful

                                                                           team_id  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317      184
                                                               2253458375       32
                                                               2253487469      184
                                                               2253487473       32
                                                               2253487625      184

                                                                              team  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317  Burnley
                                                               2253458375  Man Utd
                                                               2253487469  Burnley
                                                               2253487473  Man Utd
                                                               2253487625  Burnley

                                                                           player_id  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317        NaN
                                                               2253458375        NaN
                                                               2253487469        NaN
                                                               2253487473        NaN
                                                               2253487625    79050.0

                                                                                    player  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317              NaN
                                                               2253458375              NaN
                                                               2253487469              NaN
                                                               2253487473              NaN
                                                               2253487625  Ashley Westwood

                                                                              x  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317   0.0
                                                               2253458375   0.0
                                                               2253487469   0.0
                                                               2253487473   0.0
                                                               2253487625  50.3

                                                                              y  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317   0.0
                                                               2253458375   0.0
                                                               2253487469   0.0
                                                               2253487473   0.0
                                                               2253487625  50.3

                                                                           end_x  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317    NaN
                                                               2253458375    NaN
                                                               2253487469    NaN
                                                               2253487473    NaN
                                                               2253487625   30.5

                                                                           end_y  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317    NaN
                                                               2253458375    NaN
                                                               2253487469    NaN
                                                               2253487473    NaN
                                                               2253487625   50.3

                                                                           goal_mouth_y  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317           NaN
                                                               2253458375           NaN
                                                               2253487469           NaN
                                                               2253487473           NaN
                                                               2253487625           NaN

                                                                           goal_mouth_z  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317           NaN
                                                               2253458375           NaN
                                                               2253487469           NaN
                                                               2253487473           NaN
                                                               2253487625           NaN

                                                                           blocked_x  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317        NaN
                                                               2253458375        NaN
                                                               2253487469        NaN
                                                               2253487473        NaN
                                                               2253487625        NaN

                                                                           blocked_y  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317        NaN
                                                               2253458375        NaN
                                                               2253487469        NaN
                                                               2253487473        NaN
                                                               2253487625        NaN

                                                                                                                  qualifiers  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317  [{'type': {'displayName': 'TeamPlayerFormation...
                                                               2253458375  [{'type': {'displayName': 'CaptainPlayerId', '...
                                                               2253487469                                                 []
                                                               2253487473                                                 []
                                                               2253487625  [{'type': {'displayName': 'Angle', 'value': 21...

                                                                           is_touch  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317     False
                                                               2253458375     False
                                                               2253487469     False
                                                               2253487473     False
                                                               2253487625      True

                                                                          is_shot  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317     NaN
                                                               2253458375     NaN
                                                               2253487469     NaN
                                                               2253487473     NaN
                                                               2253487625     NaN

                                                                          is_goal  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317     NaN
                                                               2253458375     NaN
                                                               2253487469     NaN
                                                               2253487473     NaN
                                                               2253487625     NaN

                                                                          card_type  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317       NaN
                                                               2253458375       NaN
                                                               2253487469       NaN
                                                               2253487473       NaN
                                                               2253487625       NaN

                                                                           related_event_id  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317               NaN
                                                               2253458375               NaN
                                                               2253487469               NaN
                                                               2253487473               NaN
                                                               2253487625               NaN

                                                                           related_player_id
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317                NaN
                                                               2253458375                NaN
                                                               2253487469                NaN
                                                               2253487473                NaN
                                                               2253487625                NaN

In [16]:
events

                                                                           game_id  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317  1485184
                                                               2253458375  1485184
                                                               2253487469  1485184
                                                               2253487473  1485184
                                                               2253487625  1485184
...                                                                            ...
                                                               2253548043  1485184
                                                               2253548053  1485184
                                                               2253548057  1485184
                                                               2253548097  1485184
                                                               2253548101  1485184

                                                                              period  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317   PreMatch
                                                               2253458375   PreMatch
                                                               2253487469  FirstHalf
                                                               2253487473  FirstHalf
                                                               2253487625  FirstHalf
...                                                                              ...
                                                               2253548043  FirstHalf
                                                               2253548053  FirstHalf
                                                               2253548057  FirstHalf
                                                               2253548097  FirstHalf
                                                               2253548101  FirstHalf

                                                                           minute  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317       0
                                                               2253458375       0
                                                               2253487469       0
                                                               2253487473       0
                                                               2253487625       0
...                                                                           ...
                                                               2253548043      36
                                                               2253548053      36
                                                               2253548057      36
                                                               2253548097      42
                                                               2253548101      42

                                                                           second  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317     0.0
                                                               2253458375     0.0
                                                               2253487469     0.0
                                                               2253487473     0.0
                                                               2253487625     0.0
...                                                                           ...
                                                               2253548043    53.0
                                                               2253548053    54.0
                                                               2253548057    56.0
                                                               2253548097    21.0
                                                               2253548101    22.0

                                                                           expanded_minute  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317                0
                                                               2253458375                0
                                                               2253487469                0
                                                               2253487473                0
                                                               2253487625                0
...                                                                                    ...
                                                               2253548043               36
                                                               2253548053               36
                                                               2253548057               36
                                                               2253548097               42
                                                               2253548101               42

                                                                                   type  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317  FormationSet
                                                               2253458375  FormationSet
                                                               2253487469         Start
                                                               2253487473         Start
                                                               2253487625          Pass
...                                                                                 ...
                                                               2253548043          Pass
                                                               2253548053          Pass
                                                               2253548057          Pass
                                                               2253548097          Pass
                                                               2253548101          Pass

                                                                          outcome_type  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317   Successful
                                                               2253458375   Successful
                                                               2253487469   Successful
                                                               2253487473   Successful
                                                               2253487625   Successful
...                                                                                ...
                                                               2253548043   Successful
                                                               2253548053   Successful
                                                               2253548057   Successful
                                                               2253548097   Successful
                                                               2253548101   Successful

                                                                           team_id  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317      184
                                                               2253458375       32
                                                               2253487469      184
                                                               2253487473       32
                                                               2253487625      184
...                                                                            ...
                                                               2253548043       32
                                                               2253548053       32
                                                               2253548057       32
                                                               2253548097       32
                                                               2253548101       32

                                                                              team  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317  Burnley
                                                               2253458375  Man Utd
                                                               2253487469  Burnley
                                                               2253487473  Man Utd
                                                               2253487625  Burnley
...                                                                            ...
                                                               2253548043  Man Utd
                                                               2253548053  Man Utd
                                                               2253548057  Man Utd
                                                               2253548097  Man Utd
                                                               2253548101  Man Utd

                                                                           player_id  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317        NaN
                                                               2253458375        NaN
                                                               2253487469        NaN
                                                               2253487473        NaN
                                                               2253487625    79050.0
...                                                                              ...
                                                               2253548043    38128.0
                                                               2253548053   331924.0
                                                               2253548057   123761.0
                                                               2253548097    38128.0
                                                               2253548101    97752.0

                                                                                      player  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317                NaN
                                                               2253458375                NaN
                                                               2253487469                NaN
                                                               2253487473                NaN
                                                               2253487625    Ashley Westwood
...                                                                                      ...
                                                               2253548043      Nemanja Matic
                                                               2253548053  Aaron Wan-Bissaka
                                                               2253548057    Bruno Fernandes
                                                               2253548097      Nemanja Matic
                                                               2253548101         Paul Pogba

                                                                              x  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317   0.0
                                                               2253458375   0.0
                                                               2253487469   0.0
                                                               2253487473   0.0
                                                               2253487625  50.3
...                                                                         ...
                                                               2253548043  37.4
                                                               2253548053  43.8
                                                               2253548057  38.6
                                                               2253548097  27.9
                                                               2253548101  29.3

                                                                              y  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317   0.0
                                                               2253458375   0.0
                                                               2253487469   0.0
                                                               2253487473   0.0
                                                               2253487625  50.3
...                                                                         ...
                                                               2253548043   6.6
                                                               2253548053   3.8
                                                               2253548057  35.2
                                                               2253548097  48.7
                                                               2253548101  28.0

                                                                           end_x  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317    NaN
                                                               2253458375    NaN
                                                               2253487469    NaN
                                                               2253487473    NaN
                                                               2253487625   30.5
...                                                                          ...
                                                               2253548043   43.8
                                                               2253548053   39.6
                                                               2253548057   36.5
                                                               2253548097   29.3
                                                               2253548101   28.7

                                                                           end_y  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317    NaN
                                                               2253458375    NaN
                                                               2253487469    NaN
                                                               2253487473    NaN
                                                               2253487625   50.3
...                                                                          ...
                                                               2253548043    3.8
                                                               2253548053   34.0
                                                               2253548057   68.0
                                                               2253548097   24.8
                                                               2253548101   42.7

                                                                           goal_mouth_y  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317           NaN
                                                               2253458375           NaN
                                                               2253487469           NaN
                                                               2253487473           NaN
                                                               2253487625           NaN
...                                                                                 ...
                                                               2253548043           NaN
                                                               2253548053           NaN
                                                               2253548057           NaN
                                                               2253548097           NaN
                                                               2253548101           NaN

                                                                           goal_mouth_z  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317           NaN
                                                               2253458375           NaN
                                                               2253487469           NaN
                                                               2253487473           NaN
                                                               2253487625           NaN
...                                                                                 ...
                                                               2253548043           NaN
                                                               2253548053           NaN
                                                               2253548057           NaN
                                                               2253548097           NaN
                                                               2253548101           NaN

                                                                           blocked_x  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317        NaN
                                                               2253458375        NaN
                                                               2253487469        NaN
                                                               2253487473        NaN
                                                               2253487625        NaN
...                                                                              ...
                                                               2253548043        NaN
                                                               2253548053        NaN
                                                               2253548057        NaN
                                                               2253548097        NaN
                                                               2253548101        NaN

                                                                           blocked_y  \
league             season game                                 id
ENG-Premier League 2021   2021-01-12 Burnley-Manchester United 2253458317        NaN
                                                               2253458375        NaN
                                                               2253487469        NaN

In [17]:
events.columns

Index(['game_id', 'period', 'minute', 'second', 'expanded_minute', 'type',
       'outcome_type', 'team_id', 'team', 'player_id', 'player', 'x', 'y',
       'end_x', 'end_y', 'goal_mouth_y', 'goal_mouth_z', 'blocked_x',
       'blocked_y', 'qualifiers', 'is_touch', 'is_shot', 'is_goal',
       'card_type', 'related_event_id', 'related_player_id'],
      dtype='object')

Match event stream data can be returned in various formats, which can be selected with the "output_fmt" parameter.

- `events` (default): Returns a dataframe with all events.
- `raw`: Returns the original unformatted WhoScored JSON.
- `spadl`: Returns a dataframe with the [SPADL representation](https://socceraction.readthedocs.io/en/latest/documentation/SPADL.html#spadl)
  of the original events.
- `atomic-spadl`: Returns a dataframe with the [Atomic-SPADL representation](https://socceraction.readthedocs.io/en/latest/documentation/SPADL.html#atomic-spadl)
  of the original events.
- `loader`: Returns a ``socceration.data.opta.OptaLoader`` instance

In [18]:
events = ws.read_events(match_id=1485184, output_fmt="raw")

import json
print(json.dumps(events[1485184][0], indent=2))

{
  "eventId": 2,
  "expandedMinute": 0,
  "id": 2253487473,
  "isTouch": false,
  "minute": 0,
  "outcomeType": {
    "displayName": "Successful",
    "value": 1
  },
  "period": {
    "displayName": "FirstHalf",
    "value": 1
  },
  "qualifiers": [],
  "satisfiedEventsTypes": [],
  "second": 0,
  "teamId": 32,
  "type": {
    "displayName": "Start",
    "value": 32
  },
  "x": 0,
  "y": 0
}

In [19]:
actions = ws.read_events(match_id=1485184, output_fmt='spadl')
actions.head()

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,end_x,start_y,end_y,type_id,result_id,bodypart_id,action_id,player,team
0,1485184,2253487625,1,0.0,184,79050.0,52.815,32.025,34.204,34.204,0,1,0,0,Ashley Westwood,Burnley
1,1485184,2253487639,1,2.0,184,131464.0,31.080,38.220,36.312,15.844,0,1,0,1,James Tarkowski,Burnley
2,1485184,NaN,1,4.5,184,80067.0,38.220,43.365,15.844,12.512,21,1,0,2,Matthew Lowton,Burnley
3,1485184,2253487685,1,7.0,184,80067.0,43.365,90.300,12.512,49.708,0,1,0,3,Matthew Lowton,Burnley
4,1485184,2253487689,1,11.0,184,93473.0,90.300,105.000,49.708,38.828,11,0,4,4,Robert Brady,Burnley

In [20]:
atomic_actions = ws.read_events(match_id=1485184, output_fmt='atomic-spadl')
atomic_actions.head()

,game_id,original_event_id,action_id,period_id,time_seconds,team_id,player_id,x,y,dx,dy,type_id,bodypart_id,player,team
0,1485184,2253487625,0,1,0.00,184,79050.0,52.815,34.204,-20.790,0.000,0,0,Ashley Westwood,Burnley
1,1485184,2253487625,1,1,1.00,184,131464.0,32.025,34.204,0.000,0.000,23,0,James Tarkowski,Burnley
2,1485184,2253487639,2,1,2.00,184,131464.0,31.080,36.312,7.140,-20.468,0,0,James Tarkowski,Burnley
3,1485184,2253487639,3,1,3.25,184,80067.0,38.220,15.844,0.000,0.000,23,0,Matthew Lowton,Burnley
4,1485184,NaN,4,1,4.50,184,80067.0,38.220,15.844,5.145,-3.332,21,0,Matthew Lowton,Burnley

In [21]:
# Scrape all games and return a socceration.data.opta.OptaLoader
loader = ws.read_events(output_fmt='loader')

# Now use this loader to load the data
print("Games:")
df_games = loader.games(competition_id="ENG-Premier League", season_id="2021")
display(df_games.head())

print("Teams:")
df_teams = loader.teams(game_id=1485184)
display(df_teams.head())

print("Players:")
df_players = loader.players(game_id=1485184)
display(df_players.head())

print("Events:")
df_events = loader.events(game_id=1485184)
display(df_events.head())

# You can use the socceraction package to convert the events
# to SPADL and to compute xT or VAEP action values

Games:

,game_id,season_id,competition_id,game_day,game_date,home_team_id,away_team_id,home_score,away_score,duration,referee,venue,attendance,home_manager,away_manager
0,1485184,2021,ENG-Premier League,None,2021-01-12 20:15:00,184,32,0,1,102,Kevin Friend,Turf Moor,0,Sean Dyche,Ole Gunnar Solskjær
1,1485185,2021,ENG-Premier League,None,2021-01-20 18:00:00,167,24,2,0,95,Jonathan Moss,Etihad Stadium,0,Josep Guardiola,Dean Smith
2,1485186,2021,ENG-Premier League,None,2020-09-12 15:00:00,162,18,1,0,99,Jonathan Moss,Selhurst Park,0,Roy Hodgson,Ralph Hasenhüttl
3,1485187,2021,ENG-Premier League,None,2020-09-12 12:30:00,170,13,0,3,94,Chris Kavanagh,Craven Cottage,0,Scott Parker,Mikel Arteta
4,1485188,2021,ENG-Premier League,None,2020-09-12 17:30:00,26,19,4,3,97,Michael Oliver,Anfield,0,Jürgen Klopp,Marcelo Bielsa

Teams:

   team_id team_name
0      184   Burnley
1       32   Man Utd

Players:

,game_id,team_id,player_id,player_name,is_starter,minutes_played,jersey_number,starting_position
0,1485184,184,105720,Nick Pope,True,102,1,GK
1,1485184,184,80067,Matthew Lowton,True,102,2,DR
2,1485184,184,94935,Ben Mee,True,102,6,DC
3,1485184,184,131464,James Tarkowski,True,102,5,DC
4,1485184,184,24148,Erik Pieters,True,102,23,DL

Events:

,game_id,event_id,period_id,team_id,player_id,type_id,timestamp,minute,second,outcome,start_x,start_y,end_x,end_y,qualifiers,related_player_id,touch,goal,shot,type_name
0,1485184,2253487473,1,32,NaN,32,2021-01-12 20:15:00,0,0,True,0.0,0.0,0.0,0.0,{},NaN,False,False,False,start
1,1485184,2253487469,1,184,NaN,32,2021-01-12 20:15:00,0,0,True,0.0,0.0,0.0,0.0,{},NaN,False,False,False,start
2,1485184,2253487625,1,184,79050.0,1,2021-01-12 20:15:00,0,0,True,50.3,50.3,30.5,50.3,"{213: '3.1', 178: True, 141: '50.3', 212: '20....",NaN,True,False,False,pass
3,1485184,2253487639,1,184,131464.0,1,2021-01-12 20:15:02,0,2,True,29.6,53.4,36.4,23.3,"{178: True, 213: '5.0', 212: '21.7', 141: '23....",NaN,True,False,False,pass
4,1485184,2253487685,1,184,80067.0,1,2021-01-12 20:15:07,0,7,True,41.3,18.4,86.0,73.1,"{1: True, 213: '0.7', 56: 'Center', 178: True,...",NaN,True,False,False,pass

## PRUEBA

In [4]:
LEAGUES = {
    'eng': 'ENG-Premier League',
    'ing': 'ENG-Premier League',
    'esp': 'ESP-La Liga',
    'fra': 'FRA-Ligue 1',
    'ger': 'GER-Bundesliga',
    'ale': 'GER-Bundesliga',
    'ita': 'ITA-Serie A',
    'wworldcup': "INT-Women's World Cup",
    'mworldcup': "INT-World Cup"
}

list(set(LEAGUES.values()))

['GER-Bundesliga',
 "INT-Women's World Cup",
 'ENG-Premier League',
 'FRA-Ligue 1',
 'ITA-Serie A',
 'ESP-La Liga',
 'INT-World Cup']

In [5]:
sd.WhoScored.available_leagues()

['ENG-Premier League',
 'ESP-La Liga',
 'FRA-Ligue 1',
 'GER-Bundesliga',
 "INT-Women's World Cup",
 'INT-World Cup',
 'ITA-Serie A']

In [6]:
proxy={
     "http": "socks5://195.201.173.249:17965/",
     "https": "socks5://195.201.173.249:17965/",
     'connection_timeout': 50
}

chrome = Path('C:\Program Files\Google\Chrome\Application\chrome.exe')

In [33]:
import requests
from itertools import cycle
import time

# Assume you've collected a list of proxies in the format 'http://ip:port'
proxies = [
    'socks5://98.162.25.4:31654',
]
proxy_pool = cycle(proxies)

# The URL you're trying to scrape
url = 'https://www.whoscored.com'

for _ in range(len(proxies)):
    proxy = next(proxy_pool)
    print(f"Attempting with proxy: {proxy}")
    try:
        response = requests.get(url, proxies={"http": proxy, "https": proxy}, timeout=5)
        if response.status_code == 200:
            # Proxy works, process response
            print("Success")
            break  # or continue to use the proxy for more requests
        else:
            print(f"Proxy failed with status code: {response.status_code}")
    except requests.exceptions.ProxyError:
        print("Proxy connection error.")
    except requests.exceptions.ConnectTimeout:
        print("Proxy connection timed out.")
    except requests.exceptions.RequestException as e:
        print(f"Request failed: {e}")
    time.sleep(1)  # Be respectful in your scraping: add delays between requests

Attempting with proxy: socks5://98.162.25.4:31654
Request failed: SOCKSHTTPSConnectionPool(host='www.whoscored.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))

In [9]:
leagues = [
    'GER-Bundesliga',
    'ENG-Premier League',
    'FRA-Ligue 1',
    'ITA-Serie A',
    'ESP-La Liga',
    ]

ws = sd.WhoScored(leagues=leagues,seasons=1718, data_dir=data_dir, headless=False)

epl_schedule = ws.read_schedule()
epl_schedule.head()

                                                                                date  \
league             season game
ENG-Premier League 1718   2017-08-11 Arsenal-Leicester           2017-08-11 19:45:00
                          2017-08-12 Brighton-Manchester City    2017-08-12 17:30:00
                          2017-08-12 Chelsea-Burnley             2017-08-12 15:00:00
                          2017-08-12 Crystal Palace-Huddersfield 2017-08-12 15:00:00
                          2017-08-12 Everton-Stoke               2017-08-12 15:00:00

                                                                       home_team  \
league             season game
ENG-Premier League 1718   2017-08-11 Arsenal-Leicester                   Arsenal
                          2017-08-12 Brighton-Manchester City           Brighton
                          2017-08-12 Chelsea-Burnley                     Chelsea
                          2017-08-12 Crystal Palace-Huddersfield  Crystal Palace
                          2017-08-12 Everton-Stoke                       Everton

                                                                        away_team  \
league             season game
ENG-Premier League 1718   2017-08-11 Arsenal-Leicester                  Leicester
                          2017-08-12 Brighton-Manchester City     Manchester City
                          2017-08-12 Chelsea-Burnley                      Burnley
                          2017-08-12 Crystal Palace-Huddersfield     Huddersfield
                          2017-08-12 Everton-Stoke                          Stoke

                                                                  game_id  \
league             season game
ENG-Premier League 1718   2017-08-11 Arsenal-Leicester            1190174
                          2017-08-12 Brighton-Manchester City     1190175
                          2017-08-12 Chelsea-Burnley              1190176
                          2017-08-12 Crystal Palace-Huddersfield  1190177
                          2017-08-12 Everton-Stoke                1190178

                                                                                                                url  \
league             season game
ENG-Premier League 1718   2017-08-11 Arsenal-Leicester            https://www.whoscored.com/Matches/1190174/Live...
                          2017-08-12 Brighton-Manchester City     https://www.whoscored.com/Matches/1190175/Live...
                          2017-08-12 Chelsea-Burnley              https://www.whoscored.com/Matches/1190176/Live...
                          2017-08-12 Crystal Palace-Huddersfield  https://www.whoscored.com/Matches/1190177/Live...
                          2017-08-12 Everton-Stoke                https://www.whoscored.com/Matches/1190178/Live...

                                                                  stage
league             season game
ENG-Premier League 1718   2017-08-11 Arsenal-Leicester              NaN
                          2017-08-12 Brighton-Manchester City       NaN
                          2017-08-12 Chelsea-Burnley                NaN
                          2017-08-12 Crystal Palace-Huddersfield    NaN
                          2017-08-12 Everton-Stoke                  NaN

In [10]:
loader_1316348 = ws.read_events(output_fmt='loader')

In [16]:
# Now use this loader to load the data
print("Games:")
df_games = loader_1316348.games(competition_id="ENG-Premier League", season_id="1718")
df_games

Games:

,game_id,season_id,competition_id,game_day,game_date,home_team_id,away_team_id,home_score,away_score,duration,referee,venue,attendance,home_manager,away_manager
0,1190174,1718,ENG-Premier League,None,2017-08-11 19:45:00,13,14,4,3,98,Mike Dean,Emirates Stadium,59387,Arsène Wenger,Craig Shakespeare
1,1190175,1718,ENG-Premier League,None,2017-08-12 17:30:00,211,167,0,2,97,Michael Oliver,Amex Stadium,30415,Chris Hughton,Josep Guardiola
2,1190176,1718,ENG-Premier League,None,2017-08-12 15:00:00,15,184,2,3,98,Craig Pawson,Stamford Bridge,41616,Antonio Conte,Sean Dyche
3,1190177,1718,ENG-Premier League,None,2017-08-12 15:00:00,162,166,0,3,96,Jonathan Moss,Selhurst Park,25448,Frank de Boer,David Wagner
4,1190178,1718,ENG-Premier League,None,2017-08-12 15:00:00,31,96,1,0,96,Neil Swarbrick,Goodison Park,39045,Ronald Koeman,Mark Hughes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,1190549,1718,ENG-Premier League,None,2017-12-18 20:00:00,31,259,3,1,96,Jonathan Moss,Goodison Park,37580,Sam Allardyce,Paul Clement
376,1190550,1718,ENG-Premier League,None,2018-03-31 12:30:00,162,26,1,2,97,Neil Swarbrick,Selhurst Park,25807,Roy Hodgson,Jürgen Klopp
377,1190551,1718,ENG-Premier League,None,2018-03-31 17:30:00,31,167,1,3,95,Paul Tierney,Goodison Park,39221,Sam Allardyce,Josep Guardiola
378,1190552,1718,ENG-Premier League,None,2018-05-06 16:30:00,13,184,5,0,95,Andre Marriner,Emirates Stadium,59540,Arsène Wenger,Sean Dyche
379,1190553,1718,ENG-Premier League,None,2018-05-05 15:00:00,183,259,1,0,97,Kevin Friend,Vitality Stadium,10820,Eddie Howe,Carlos Carvalhal

In [14]:
print("Teams:")
df_teams = loader_1316348.teams(game_id=1221940)
display(df_teams.head())

print("Players:")
df_players = loader_1316348.players(game_id=1221940)
display(df_players.head())

print("Events:")
df_events = loader_1316348.events(game_id=1221940)
display(df_events.head())

Teams:

   team_id         team_name
0      825           Leganes
1       60  Deportivo Alaves

Players:

,game_id,team_id,player_id,player_name,is_starter,minutes_played,jersey_number,starting_position
0,1221940,825,11188,Iván Cuéllar,True,94,1,GK
1,1221940,825,135911,Joseba Zaldúa,True,80,20,DR
2,1221940,825,70733,Ezequiel Muñoz,True,94,19,DC
3,1221940,825,88311,Martín Mantovani,True,94,5,DC
4,1221940,825,323352,Diego Rico,True,94,15,DL

Events:

,game_id,event_id,period_id,team_id,player_id,type_id,timestamp,minute,second,outcome,start_x,start_y,end_x,end_y,qualifiers,related_player_id,touch,goal,shot,type_name
0,1221940,1787883674,1,60,NaN,32,2017-08-18 19:15:00,0,0,True,0.0,0.0,0.0,0.0,{},NaN,False,False,False,start
1,1221940,1187133896,1,825,NaN,32,2017-08-18 19:15:00,0,0,True,0.0,0.0,0.0,0.0,{},NaN,False,False,False,start
2,1221940,1800868097,1,60,323250.0,1,2017-08-18 19:15:01,0,1,True,50.0,50.0,33.0,47.3,"{213: '3.2', 140: '33.0', 141: '47.3', 56: 'Ba...",NaN,True,False,False,pass
3,1221940,2104308215,1,60,9255.0,1,2017-08-18 19:15:03,0,3,False,33.0,47.3,64.1,83.6,"{213: '0.6', 56: 'Left', 155: True, 212: '40.9...",NaN,True,False,False,pass
4,1221940,1491580685,1,60,107243.0,44,2017-08-18 19:15:05,0,5,False,68.6,85.8,68.6,85.8,"{286: True, 233: '3', 56: 'Left'}",NaN,False,False,False,aerial

### PRUEBA PROXY

In [36]:
# chrome = Path('C:\Program Files\Google\Chrome\Application\chrome.exe')
chrome = Path("C:\\Users\GuillemUPV\chromedriver-win64\chromedriver.exe")

In [37]:
# ws = sd.WhoScored(leagues="ENG-Premier League", seasons=2122, data_dir=data_dir, headless=False)

In [67]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

chrome_options = Options()
chromedriver = "C:\\Users\GuillemUPV\chromedriver-win64\chromedriver.exe"
proxy = "socks5://127.0.0.1:9050"
resolver_rules = "MAP * 0.0.0.0 , EXCLUDE 127.0.0.1"
# chrome_options.add_argument("--headless")  # maybe try without this line too
chrome_options.add_argument("--proxy-server=" + proxy)
chrome_options.add_argument("--host-resolver-rules=" + resolver_rules)
driver = webdriver.Chrome(chromedriver,options=chrome_options)
driver.get("https://check.torproject.org/api/ip")
print(driver.page_source)

url = 'https://www.whoscored.com/Matches/738817/Live/Spain-LaLiga-2013-2014-Malaga-Levante'
# Acceder a la página web
driver.get(url)
driver.implicitly_wait(100)

teams = driver.find_elements(By.CSS_SELECTOR,'.pitch-field')

TypeError: __init__() got multiple values for argument 'options'

In [69]:
import undetected_chromedriver as uc
from selenium.webdriver.chrome.options import Options
chrome_options = Options()
proxy = "socks5://127.0.0.1:9050"
resolver_rules = "MAP * 0.0.0.0 , EXCLUDE 127.0.0.1"
chrome_options.add_argument("--headless")  # maybe try without this line too
chrome_options.add_argument("--proxy-server=" + proxy)
chrome_options.add_argument("--host-resolver-rules=" + resolver_rules)
driver = uc.Chrome(options=chrome_options)
driver.get("https://check.torproject.org/api/ip") ## worked
driver.page_source
# driver.get('https://www.whoscored.com/Matches/1485477/Live/England-Premier-League-2020-2021-Crystal-Palace-Manchester-City')
# element = driver.find_element(by='xpath',value='//*[@id="layout-wrapper"]/script[1]')

could not detect version_main.therefore, we are assuming it is chrome 108 or higher

'<html><head><meta name="color-scheme" content="light dark"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"IsTor":true,"IP":"109.70.100.68"}</pre></body></html>'

In [55]:
import json
driver.get('https://www.whoscored.com/Matches/1485477/Live/England-Premier-League-2020-2021-Crystal-Palace-Manchester-City')
element = driver.find_element(by='xpath',value='//*[@id="layout-wrapper"]/script[1]')
script_content = element.get_attribute('innerHTML')
script_ls = script_content.split(sep="  ")
script_ls = list(filter(None, script_ls))
script_ls = [name for name in script_ls if name.strip()]
dictstring = script_ls[2][17:-2]
matchdict = json.loads(dictstring)
matchdict['score']

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="layout-wrapper"]/script[1]"}
  (Session info: chrome-headless-shell=121.0.6167.140); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7F0AC5E42+3538674]
	(No symbol) [0x00007FF7F06E4C02]
	(No symbol) [0x00007FF7F0595AEB]
	(No symbol) [0x00007FF7F05DBF4E]
	(No symbol) [0x00007FF7F05DC0CC]
	(No symbol) [0x00007FF7F061E477]
	(No symbol) [0x00007FF7F05FF0EF]
	(No symbol) [0x00007FF7F061BDE3]
	(No symbol) [0x00007FF7F05FEE53]
	(No symbol) [0x00007FF7F05CF514]
	(No symbol) [0x00007FF7F05D0631]
	GetHandleVerifier [0x00007FF7F0AF6CAD+3738973]
	GetHandleVerifier [0x00007FF7F0B4C506+4089270]
	GetHandleVerifier [0x00007FF7F0B44823+4057299]
	GetHandleVerifier [0x00007FF7F0815C49+720121]
	(No symbol) [0x00007FF7F06F126F]
	(No symbol) [0x00007FF7F06EC304]
	(No symbol) [0x00007FF7F06EC432]
	(No symbol) [0x00007FF7F06DBD04]
	BaseThreadInitThunk [0x00007FFFFBD253E0+16]
	RtlUserThreadStart [0x00007FFFFCB4485B+43]