In [1]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
ligas = {}
lista_temporadas = []


lista_temporadas = []

for i in range(93,99):
    t = str(i)+''+str(i+1)
    lista_temporadas = [t] + lista_temporadas
    
t = '9900'
lista_temporadas = [t] + lista_temporadas
    
for i in range(0,21):
        j = str(i+1)
        i = str(i)
        x = (2) if len(i) == 1 else (1)
        i = i.zfill(x)
        x = (2) if len(j) == 1 else (1)
        j = j.zfill(x)
        t = i+''+j
        lista_temporadas = [t] + lista_temporadas

print(lista_temporadas)

['2021', '1920', '1819', '1718', '1617', '1516', '1415', '1314', '1213', '1112', '1011', '0910', '0809', '0708', '0607', '0506', '0405', '0304', '0203', '0102', '0001', '9900', '9899', '9798', '9697', '9596', '9495', '9394']

In [3]:
#LALIGA
for temp, num in zip(lista_temporadas,range(0,25)):
    for file in os.listdir(os.getcwd()):
        aux = '(' + str(num) + ')'
        if file.find('SP1 ' + aux) == False:
            os.rename('SP1 ' + aux + '.csv','SP1_' + temp + '.csv')

ligas['LaLiga'] = {}

for temp in lista_temporadas:
    try:
        ligas['LaLiga'][temp] = pd.read_csv(os.getcwd()+'\\SP1_'+ temp +'.csv')
    except Exception:
        print(temp + ' da error')
        continue

0405 da error

In [4]:
ejemplo = ligas['LaLiga']['1920']

In [5]:
ejemplo

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,16/08/2019,20:00,Ath Bilbao,Barcelona,1,0,H,0,0,...,1.97,0.75,1.93,2.00,1.91,2.01,2.02,2.03,1.91,1.98
1,SP1,17/08/2019,16:00,Celta,Real Madrid,1,3,A,0,1,...,2.63,1.00,1.82,1.97,1.85,2.07,2.00,2.20,1.82,2.06
2,SP1,17/08/2019,18:00,Valencia,Sociedad,1,1,D,0,0,...,1.82,-0.75,1.94,1.99,1.92,2.00,1.96,2.12,1.89,2.00
3,SP1,17/08/2019,19:00,Mallorca,Eibar,2,1,H,1,0,...,1.66,0.00,2.11,1.82,2.09,1.83,2.12,1.88,2.07,1.83
4,SP1,17/08/2019,20:00,Leganes,Osasuna,0,1,A,0,0,...,1.46,-0.50,1.89,2.04,1.90,2.01,1.95,2.06,1.90,1.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,19/07/2020,20:00,Granada,Ath Bilbao,4,0,H,1,0,...,1.78,-0.75,1.96,1.97,1.93,1.98,2.04,1.99,1.93,1.94
376,SP1,19/07/2020,20:00,Leganes,Real Madrid,2,2,D,1,1,...,2.06,0.25,2.03,1.90,2.05,1.87,2.06,1.93,2.00,1.88
377,SP1,19/07/2020,20:00,Levante,Getafe,1,0,H,0,0,...,2.17,1.25,1.88,2.05,1.86,2.05,1.91,2.08,1.86,2.01
378,SP1,19/07/2020,20:00,Osasuna,Mallorca,2,2,D,1,1,...,2.30,-0.75,1.85,2.08,1.85,2.07,1.89,2.11,1.84,2.04
379,SP1,19/07/2020,20:00,Sevilla,Valencia,1,0,H,0,0,...,2.35,-0.75,1.94,1.99,1.93,1.99,1.96,2.00,1.92,1.95

In [6]:
ligas['LaLiga']['1617'][['FTR','B365H','B365A']]

    FTR  B365H  B365A
0     H   1.95   4.20
1     D   1.62   6.00
2     H   1.08  29.00
3     D   2.50   3.00
4     H   1.67   5.00
..   ..    ...    ...
375   H   2.00   3.80
376   H   1.05  34.00
377   D   4.75   1.75
378   A  11.00   1.22
379   A   3.10   2.30

[380 rows x 3 columns]

In [7]:
lista_ligas = list(ligas['LaLiga'].values())

In [8]:
lista_ligas[1]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,16/08/2019,20:00,Ath Bilbao,Barcelona,1,0,H,0,0,...,1.97,0.75,1.93,2.00,1.91,2.01,2.02,2.03,1.91,1.98
1,SP1,17/08/2019,16:00,Celta,Real Madrid,1,3,A,0,1,...,2.63,1.00,1.82,1.97,1.85,2.07,2.00,2.20,1.82,2.06
2,SP1,17/08/2019,18:00,Valencia,Sociedad,1,1,D,0,0,...,1.82,-0.75,1.94,1.99,1.92,2.00,1.96,2.12,1.89,2.00
3,SP1,17/08/2019,19:00,Mallorca,Eibar,2,1,H,1,0,...,1.66,0.00,2.11,1.82,2.09,1.83,2.12,1.88,2.07,1.83
4,SP1,17/08/2019,20:00,Leganes,Osasuna,0,1,A,0,0,...,1.46,-0.50,1.89,2.04,1.90,2.01,1.95,2.06,1.90,1.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,19/07/2020,20:00,Granada,Ath Bilbao,4,0,H,1,0,...,1.78,-0.75,1.96,1.97,1.93,1.98,2.04,1.99,1.93,1.94
376,SP1,19/07/2020,20:00,Leganes,Real Madrid,2,2,D,1,1,...,2.06,0.25,2.03,1.90,2.05,1.87,2.06,1.93,2.00,1.88
377,SP1,19/07/2020,20:00,Levante,Getafe,1,0,H,0,0,...,2.17,1.25,1.88,2.05,1.86,2.05,1.91,2.08,1.86,2.01
378,SP1,19/07/2020,20:00,Osasuna,Mallorca,2,2,D,1,1,...,2.30,-0.75,1.85,2.08,1.85,2.07,1.89,2.11,1.84,2.04
379,SP1,19/07/2020,20:00,Sevilla,Valencia,1,0,H,0,0,...,2.35,-0.75,1.94,1.99,1.93,1.99,1.96,2.00,1.92,1.95

In [9]:
dataframe1 = pd.concat(lista_ligas[:10], axis=0, ignore_index=True)
dataframe1

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA
0,SP1,12/09/2020,15:00,Eibar,Celta,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,13/09/2020,13:00,Alaves,Betis,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,SP1,13/05/12,NaN,Malaga,Sp Gijon,1,0,H,0,0,...,9.00,1.30,5.25,8.50,1.29,5.0,9.00,1.300,5.50,8.500
3796,SP1,13/05/12,NaN,Real Madrid,Mallorca,4,1,H,2,0,...,13.00,1.20,6.50,11.00,1.20,6.5,10.00,1.181,7.00,12.000
3797,SP1,13/05/12,NaN,Santander,Osasuna,2,4,A,1,0,...,1.57,5.25,4.00,1.57,5.00,4.0,1.57,5.500,3.75,1.600
3798,SP1,13/05/12,NaN,Vallecano,Granada,1,0,H,0,0,...,4.33,1.83,3.40,4.25,1.83,3.3,4.20,1.800,3.50,4.333
3799,SP1,13/05/12,NaN,Villarreal,Ath Madrid,0,1,A,0,0,...,2.88,2.30,3.40,2.85,2.38,3.3,2.80,2.300,3.40,2.900

In [10]:
d1 = dataframe1[['FTR','B365H','B365A']]

In [11]:
np.array(d1['FTR'])

array(['D', 'H', 'A', ..., 'A', 'H', 'A'], dtype=object)

In [12]:
ftr = np.array(d1['FTR'])
ftr[ftr!='H'] = 'no'
ftr[ftr=='H'] = 'yes'

cuotas_h = (1/d1['B365H'])
cuotas_a = (1/d1['B365A'])

In [13]:
set(ftr)

{'no', 'yes'}

<b>DATASET BET365 CON RESULTADO BINARIO (GANA LOCAL O NO GANA)</b>

In [14]:
d1.loc[3067]

FTR         H
B365H    1.08
B365A    23.0
Name: 3067, dtype: object

In [15]:
dataset1 = pd.DataFrame({'CuotaLocal':cuotas_h, 'CuotaVisitante':cuotas_a,'Resultado':ftr})
dataset1

dataset1 = dataset1.sample(frac=1,axis=0, random_state=1)
dataset1

      CuotaLocal  CuotaVisitante Resultado
3177    0.476190        0.294118        no
2130    0.555556        0.210526        no
909     0.512821        0.250000       yes
1010    0.444444        0.312500        no
1021    0.344828        0.392157        no
...          ...             ...       ...
2763    0.847458        0.076923       yes
905     0.653595        0.166667       yes
1096    0.400000        0.344828       yes
235     0.408163        0.333333        no
1061    0.400000        0.333333        no

[3800 rows x 3 columns]

In [16]:
dataset1.shape

(3800, 3)

In [17]:
dataset1.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\dataset1.csv',index=False)

<b>DATASET BET365 CON RESULTADO BINARIO (GANA LOCAL O NO GANA) Y CUOTAS NORMALIZADAS ESTANDAR</b>

https://empresas.blogthinkbig.com/precauciones-la-hora-de-normalizar/

In [18]:
len(ftr[ftr==0])

0

In [19]:
cuotalocal_norm=(dataset1['CuotaLocal']-dataset1['CuotaLocal'].mean())/dataset1['CuotaLocal'].std()
cuotavisit_norm=(dataset1['CuotaVisitante']-dataset1['CuotaVisitante'].mean())/dataset1['CuotaVisitante'].std()

d_norm = pd.DataFrame({'CuotaLocal':cuotalocal_norm, 'CuotaVisitante':cuotavisit_norm,'Resultado':ftr})

In [20]:
d_norm

      CuotaLocal  CuotaVisitante Resultado
3177   -0.036667       -0.088646        no
2130    0.352616       -0.543075       yes
909     0.143002       -0.328483        no
1010   -0.192380        0.011287        no
1021   -0.680998        0.444327        no
...          ...             ...       ...
2763    1.784386       -1.269385       yes
905     0.833495       -0.781510       yes
1096   -0.410379        0.187030        no
235    -0.370338        0.124543       yes
1061   -0.410379        0.124543        no

[3800 rows x 3 columns]

In [21]:
os.getcwd()

'F:\\2020-21\\Beca VRAIN\\datasets\\football-data'

In [22]:
# d_norm.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_stand.csv',index=False)

<b>DATASET BET365 CON RESULTADO BINARIO (GANA LOCAL O NO GANA) Y CUOTAS NORMALIZADAS MIN-MAX</b>

https://empresas.blogthinkbig.com/precauciones-la-hora-de-normalizar/

In [23]:
cuotalocal_norm=(dataset1['CuotaLocal']-dataset1['CuotaLocal'].min())/(dataset1['CuotaLocal'].max()-dataset1['CuotaLocal'].min())
cuotavisit_norm=(dataset1['CuotaVisitante']-dataset1['CuotaVisitante'].min())/(dataset1['CuotaVisitante'].max()-dataset1['CuotaVisitante'].min())

d_minmax = pd.DataFrame({'CuotaLocal':cuotalocal_norm, 'CuotaVisitante':cuotavisit_norm,'Resultado':ftr})
(d_minmax['CuotaLocal']).max()

1.0

In [24]:
# d_minmax.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\d_minmax.csv',index=False)

<b>DATASET BET365 CON RESULTADO H-D-A</b>

https://empresas.blogthinkbig.com/precauciones-la-hora-de-normalizar/

In [25]:
ftr = np.array(d1['FTR'])
data_hda = pd.DataFrame({'CuotaLocal':cuotas_h, 'CuotaVisitante':cuotas_a,'Resultado':ftr})

h = data_hda[data_hda['Resultado']=='H']
d = data_hda[data_hda['Resultado']=='D']
a = data_hda[data_hda['Resultado']=='A']

data_hda = pd.concat([h[:900],d[:900],a[:900]], axis=0, ignore_index=True)

data_hda = data_hda.sample(frac=1,axis=0,random_state=1)
data_hda

data_hda.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_hda.csv',index=False)

In [26]:
data_hda

      CuotaLocal  CuotaVisitante Resultado
1577    0.454545        0.285714         D
1783    0.540541        0.230947         D
429     0.877193        0.066667         H
1201    0.416667        0.312500         D
1027    0.348432        0.370370         D
...          ...             ...       ...
960     0.416667        0.322581         D
905     0.500000        0.250000         D
1096    0.421941        0.303030         D
235     0.602410        0.166667         H
1061    0.153846        0.689655         D

[2700 rows x 3 columns]

<b>DATASET CON MÁS CUOTAS CON RESULTADO H-D-A</b>

In [27]:
dataframe1

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA
0,SP1,12/09/2020,15:00,Eibar,Celta,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,13/09/2020,13:00,Alaves,Betis,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,SP1,13/05/12,NaN,Malaga,Sp Gijon,1,0,H,0,0,...,9.00,1.30,5.25,8.50,1.29,5.0,9.00,1.300,5.50,8.500
3796,SP1,13/05/12,NaN,Real Madrid,Mallorca,4,1,H,2,0,...,13.00,1.20,6.50,11.00,1.20,6.5,10.00,1.181,7.00,12.000
3797,SP1,13/05/12,NaN,Santander,Osasuna,2,4,A,1,0,...,1.57,5.25,4.00,1.57,5.00,4.0,1.57,5.500,3.75,1.600
3798,SP1,13/05/12,NaN,Vallecano,Granada,1,0,H,0,0,...,4.33,1.83,3.40,4.25,1.83,3.3,4.20,1.800,3.50,4.333
3799,SP1,13/05/12,NaN,Villarreal,Ath Madrid,0,1,A,0,0,...,2.88,2.30,3.40,2.85,2.38,3.3,2.80,2.300,3.40,2.900

In [28]:
ftr = np.array(dataframe1['FTR'])
ftr[ftr!='H'] = 'no'
ftr[ftr=='H'] = 'yes'

In [29]:
ftr

array(['no', 'yes', 'no', ..., 'no', 'yes', 'no'], dtype=object)

In [32]:
odd = False
cuotas = {}
for col in dataframe1.columns:
    if col=='B365H' or odd == True or re.match(r"[\s\S]*(draw)+[\s\S]*",col) == False:
        odd = True
        cuotas[col] = (1/dataframe1[col])
        if col == 'WHA':
            odd = False
            
for c in cuotas:
    assert len(cuotas[c]) == 3800
    
cuotas['ResultadosBin'] = ftr
cuotas['ResultadosTer'] = np.array(dataframe1['FTR'])

In [33]:
type(cuotas.values())

x = np.array(list(cuotas.values()))
x = np.reshape(x,(17,3770))
x

ValueError: cannot reshape array of size 64600 into shape (17,3770)

In [34]:
cuotas.keys()

dict_keys(['B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'ResultadosBin', 'ResultadosTer'])

In [35]:
data_cuotas = pd.DataFrame(x,index=cuotas.keys())
data_cuotas = data_cuotas.transpose()
print(data_cuotas.shape)
data_cuotas = data_cuotas.drop(['PSH','PSD','PSA'],axis=1) # PSH - PSD - PSA tienen valores nulos
print(data_cuotas.shape)
# data_cuotas = pd.DataFrame(data_cuotas,ftr)

(3800, 17)
(3800, 14)

In [36]:
data_cuotas

,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,WHH,WHD,WHA,ResultadosBin,ResultadosTer
0,0.4,0.307692,0.344828,0.408163,0.3125,0.333333,0.392157,0.344828,0.338983,0.392157,0.322581,0.333333,no,D
1,0.363636,0.322581,0.363636,0.350877,0.322581,0.377358,0.350877,0.37037,0.363636,0.357143,0.333333,0.363636,yes,H
2,0.357143,0.333333,0.363636,0.363636,0.333333,0.357143,0.357143,0.37037,0.357143,0.357143,0.344828,0.347222,no,A
3,0.357143,0.3125,0.384615,0.338983,0.333333,0.377358,0.350877,0.338983,0.384615,0.357143,0.3125,0.381679,no,A
4,0.357143,0.3125,0.384615,0.357143,0.3125,0.384615,0.344828,0.338983,0.392157,0.344828,0.3125,0.392157,no,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,0.769231,0.181818,0.111111,0.769231,0.181818,0.117647,0.769231,0.181818,0.142857,0.75188,0.2,0.111111,yes,H
3796,0.833333,0.142857,0.090909,0.833333,0.153846,0.083333,0.833333,0.181818,0.083333,0.819672,0.166667,0.083333,yes,H
3797,0.166667,0.25,0.653595,0.2,0.243902,0.625,0.188679,0.25,0.666667,0.181818,0.266667,0.617284,no,A
3798,0.546448,0.285714,0.230947,0.555556,0.289855,0.227273,0.526316,0.30303,0.27027,0.546448,0.294118,0.222222,yes,H
3799,0.434783,0.294118,0.333333,0.434783,0.294118,0.338983,0.454545,0.294118,0.357143,0.434783,0.30303,0.322581,no,A

In [37]:
data_cuotas = data_cuotas.sample(frac=1,axis=0,random_state=1)
data_cuotas

,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,WHH,WHD,WHA,ResultadosBin,ResultadosTer
3177,0.47619,0.294118,0.294118,0.47619,0.30303,0.294118,0.465116,0.30303,0.3125,0.454545,0.30303,0.307692,no,A
2130,0.555556,0.285714,0.210526,0.555556,0.294118,0.222222,0.526316,0.289855,0.263158,0.540541,0.294118,0.222222,no,D
909,0.512821,0.294118,0.25,0.5,0.30303,0.25,0.512821,0.294118,0.246914,0.512821,0.285714,0.25,yes,H
1010,0.444444,0.294118,0.3125,0.444444,0.30303,0.30303,0.434783,0.298507,0.3125,0.454545,0.30303,0.294118,no,A
1021,0.344828,0.3125,0.392157,0.344828,0.333333,0.37037,0.338983,0.327869,0.384615,0.347222,0.322581,0.381679,no,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2763,0.847458,0.142857,0.076923,0.840336,0.153846,0.074074,0.833333,0.166667,0.08,0.819672,0.166667,0.076923,yes,H
905,0.653595,0.230947,0.166667,0.653595,0.227273,0.166667,0.636943,0.229885,0.181818,0.653595,0.227273,0.172414,yes,H
1096,0.4,0.30303,0.344828,0.392157,0.285714,0.37037,0.408163,0.273973,0.37037,0.392157,0.285714,0.37037,yes,H
235,0.408163,0.3125,0.333333,0.392157,0.3125,0.344828,0.392157,0.327869,0.327869,0.392157,0.322581,0.333333,no,D
1061,0.4,0.3125,0.333333,0.392157,0.322581,0.333333,0.4,0.31746,0.338983,0.408163,0.3125,0.333333,no,A

In [38]:
data_cuotas.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_cuotas.csv',index=False)

In [39]:
data_cuotas.drop('ResultadosTer',axis=1).to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_cuotas_bin.csv',index=False)

In [40]:
data_cuotas.drop('ResultadosBin',axis=1).to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_cuotas_ter.csv',index=False)

<b>DATASET CON HANDICAP ASIATICO</b>

In [ ]:
dataframe1

In [ ]:
set(dataframe1['GBA'].isna())

In [ ]:
dataframe1.columns

In [ ]:
for i in dataframe1.columns:
    print(i)

In [ ]:
ex = dataframe1[
['Date','HomeTeam','AwayTeam','B365H','B365A','B365AHH','B365AHA','AHh','BbAHh','BbAvAHH','BbAvAHA']
].loc[[0,10,100,500,750,1000,2000]]

ex

# C -> significa Closing odds, y son lás últimas cuotas antes del inicio del partido

In [ ]:
ex['B365AHH'] = ex['B365AHH'].fillna(ex['BbAvAHH'])
ex['B365AHA'] = ex['B365AHA'].fillna(ex['BbAvAHA'])
ex['AHh'] = ex['AHh'].fillna(ex['BbAHh'])

ex.drop(['BbAHh','BbAvAHH','BbAvAHA'],axis=1)

In [ ]:
ftr = np.array(dataframe1['FTR'])
ftr[ftr!='H'] = 'no'
ftr[ftr=='H'] = 'yes'
ftr

In [ ]:
aux = {}
aux['B365H'] = (1/dataframe1['B365H'])
aux['B365A'] = (1/dataframe1['B365A'])
aux['B365AHH'] = (1/dataframe1['B365AHH'].fillna(dataframe1['BbAvAHH']))
aux['B365AHA'] = (1/dataframe1['B365AHA'].fillna(dataframe1['BbAvAHA']))
aux['AHh'] = dataframe1['AHh'].fillna(dataframe1['BbAHh'])
aux['ResultadoBin'] = ftr
aux['ResultadoTer'] = np.array(dataframe1['FTR'])

data_handicap = pd.DataFrame(aux)
data_handicap

In [ ]:
len(data_handicap['B365AHA'][data_handicap['B365AHA'].isna()])

In [ ]:
data_handicap = data_handicap.sample(frac=1,axis=0,random_state=1)
data_handicap

In [ ]:
# data_handicap.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_handicap_prob.csv',index=False)

In [ ]:
# data_handicap = pd.read_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_handicap_prob.csv')
# data_handicap

In [ ]:
test_handicap = data_handicap[(3770-900):]

borrar = list(range((3770-900),3770))
data_handicap = data_handicap.drop(borrar)

In [ ]:
data_handicap

In [ ]:
test_handicap.sample(frac=1,axis=0,random_state=1)

In [ ]:
data_handicap.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_handicap_prob.csv',index=False)
data_handicap.drop('ResultadoTer',axis=1).to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_handicap_bin.csv',index=False)
data_handicap.drop('ResultadoBin',axis=1).to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_handicap_ter.csv',index=False)
test_handicap.drop('ResultadoTer',axis=1).to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\test_handicap_prob_bin.csv',index=False)
test_handicap.drop('ResultadoBin',axis=1).to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\test_handicap_prob_ter.csv',index=False)

<h3>DATASET CON ATRIBUTOS DE ESTADÍSTICAS HISTÓRICAS</h3>

In [41]:
dataframe1

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA
0,SP1,12/09/2020,15:00,Eibar,Celta,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,13/09/2020,13:00,Alaves,Betis,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,SP1,13/05/12,NaN,Malaga,Sp Gijon,1,0,H,0,0,...,9.00,1.30,5.25,8.50,1.29,5.0,9.00,1.300,5.50,8.500
3796,SP1,13/05/12,NaN,Real Madrid,Mallorca,4,1,H,2,0,...,13.00,1.20,6.50,11.00,1.20,6.5,10.00,1.181,7.00,12.000
3797,SP1,13/05/12,NaN,Santander,Osasuna,2,4,A,1,0,...,1.57,5.25,4.00,1.57,5.00,4.0,1.57,5.500,3.75,1.600
3798,SP1,13/05/12,NaN,Vallecano,Granada,1,0,H,0,0,...,4.33,1.83,3.40,4.25,1.83,3.3,4.20,1.800,3.50,4.333
3799,SP1,13/05/12,NaN,Villarreal,Ath Madrid,0,1,A,0,0,...,2.88,2.30,3.40,2.85,2.38,3.3,2.80,2.300,3.40,2.900

In [42]:
ej = dataframe1.loc[:379]
ej = ej.sort_index(ascending=False,ignore_index=True)
ej

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA
0,SP1,23/05/2021,20:00,Sevilla,Alaves,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,23/05/2021,17:30,Granada,Getafe,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,22/05/2021,17:00,Valladolid,Ath Madrid,1,2,A,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,22/05/2021,17:00,Real Madrid,Villarreal,2,1,H,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,22/05/2021,17:00,Osasuna,Sociedad,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,SP1,13/09/2020,13:00,Alaves,Betis,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,SP1,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,SP1,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,SP1,12/09/2020,15:00,Eibar,Celta,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
assert len(rend_local) == len(rend_visit) == len(ej) == 380

In [3]:
#LALIGA
for temp, num in zip(lista_temporadas,range(0,25)):
    for file in os.listdir(os.getcwd()):
        aux = '(' + str(num) + ')'
        if file.find('SP1 ' + aux) == False:
            os.rename('SP1 ' + aux + '.csv','SP1_' + temp + '.csv')

ligas['LaLiga'] = {}

for temp in lista_temporadas:
    try:
        ligas['LaLiga'][temp] = pd.read_csv(os.getcwd()+'\\SP1_'+ temp +'.csv')
        ligas['LaLiga'][temp] = ligas['LaLiga'][temp].sort_index(ascending=False,ignore_index=True)
    except Exception:
        print(temp + ' da error')
        continue

0405 da error

In [39]:
def getPoints(lista, local):
    if local:
        l = 0
    else:
        l = 1
        
    lista[lista == 'D'] = 1
    lista[lista == 'H'] = 3 + (l * -3)
    lista[lista == 'A'] = 0 + (l *  3)
    
    print(lista)
    
    try:
            avg = sum(lista)/len(lista)
    except ZeroDivisionError:
            avg = 0.0
            pass
    
    print(avg)
    
    return avg

In [58]:
def calculoRendimiento(data,n=5):
    
    rend_local = []
    rend_visit = []
    encajados_h = []
    marcados_h = []
    encajados_a = []
    marcados_a = []
    shots_h = []
    shots_a = []

    for index in range(len(data)):
        local = data.loc[index]['HomeTeam']
        visitante = data.loc[index]['AwayTeam']

    #     LOCAL:
        indices = []
        indices = [i for i, x in enumerate(data['HomeTeam']) if x == local and i > index and len(indices) < 5]
        print(local + ' - local')
        indices = indices[:n]
        
#       Puntos
        pts = data['FTR'][indices]
        avg_pts = getPoints(pts,local=True)
        rend_local.append(avg_pts)
        
#       Goles Marcados y Recibidos
        marc = data['FTHG'][indices]
        marc = sum(marc)
        print(marc)
        marcados_h.append(marc)
        recib = data['FTAG'][indices]
        recib = sum(recib)
        encajados_h.append(recib)
        
        # Disparos
        shots = data['HS'][indices]
        
        try:
            shots = sum(shots)/len(shots)
        except ZeroDivisionError:
            shots = 0.0
            pass
        
        print(shots)
        shots_h.append(shots)

    #     VISITANTE:
        indices = []
        indices = [i for i, x in enumerate(data['AwayTeam']) if x == visitante and i > index]
        print(visitante + ' - visitante')
        indices = indices[:n]

        res = data['FTR'][indices]
        avg = getPoints(res,local=False)
        rend_visit.append(avg)
#       Goles Marcados y Recibidos
        marc = data['FTAG'][indices]
        marc = sum(marc)
        marcados_a.append(marc)
        recib = data['FTHG'][indices]
        recib = sum(recib)
        encajados_a.append(recib)

        # Disparos
        shots = data['AS'][indices]
        try:
            shots = sum(shots)/len(shots)
        except ZeroDivisionError:
            shots = 0.0
            pass        
        shots_a.append(shots)
    
    return [rend_local,rend_visit,marcados_h,encajados_h,marcados_a,encajados_a,shots_h,shots_a]

In [59]:
partidos = 10

In [60]:
lista_ligas = list(ligas['LaLiga'].values())
data = pd.concat(lista_ligas[:10], axis=0, ignore_index=True)
data
rend = calculoRendimiento(data,n=partidos)

Sevilla - local
26     3
40     0
54     3
92     3
110    3
112    3
139    0
161    3
170    3
192    3
Name: FTR, dtype: object
2.4
14
12.8
Alaves - visitante
28     3
48     0
59     1
87     1
101    0
122    0
146    0
159    0
179    1
208    0
Name: FTR, dtype: object
0.6
Granada - local
20     0
42     0
64     3
98     0
114    3
134    3
162    0
177    1
204    3
211    0
Name: FTR, dtype: object
1.3
11
8.6
Getafe - visitante
25     0
43     0
57     3
62     0
96     1
130    0
152    0
164    0
170    0
185    0
Name: FTR, dtype: object
0.4
Valladolid - local
22     0
44     1
60     1
82     0
105    1
130    3
148    0
184    0
201    1
207    0
Name: FTR, dtype: object
0.7
9
9.5
Ath Madrid - visitante
37     1
47     3
53     0
81     1
92     0
116    1
133    3
153    1
162    3
178    3
Name: FTR, dtype: object
1.6
Real Madrid - local
31     1
45     3
58     1
85     3
97     3
118    3
132    1
157    3
164    3
182    0
Name: FTR, dtype: object
2.1
16
16.6
Villarreal - visitante
22     3
68     0
72     3
98     3
113    3
131    0
144    1
171    1
193    1
213    3
Name: FTR, dtype: object
1.8
Osasuna - local
29     3
70     3
79     3
96     1
117    1
127    0
143    0
167    3
189    3
210    1
Name: FTR, dtype: object
1.8
13
10.2
Sociedad - visitante
23     0
46     0
52     3
83     1
114    0
132    1
158    3
180    1
212    0
226    3
Name: FTR, dtype: object
1.2
Huesca - local
24     3
46     3
57     0
89     3
106    1
126    0
145    3
172    0
193    1
205    0
Name: FTR, dtype: object
1.4
12
12.1
Valencia - visitante
26     0
70     0
75     1
93     0
120    0
137    0
157    0
168    1
186    0
207    3
Name: FTR, dtype: object
0.5
Elche - local
28     0
47     0
61     3
67     1
94     1
129    3
151    3
171    1
188    0
206    0
Name: FTR, dtype: object
1.2
9
7.2
Ath Bilbao - visitante
24     0
40     3
69     1
90     1
115    1
121    0
141    1
154    3
176    0
239    1
Name: FTR, dtype: object
1.1
Eibar - local
21     1
48     3
52     0
86     0
113    0
140    1
160    1
183    0
195    0
218    3
Name: FTR, dtype: object
0.9
10
14.4
Barcelona - visitante
27     1
41     3
56     3
85     0
100    3
127    3
139    3
166    3
188    3
211    3
Name: FTR, dtype: object
2.5
Celta - local
25     3
49     3
55     3
80     0
107    0
115    1
136    1
163    3
187    1
213    0
Name: FTR, dtype: object
1.5
14
8.7
Betis - visitante
21     1
44     1
58     1
94     1
112    0
135    3
155    3
191    1
205    3
231    0
Name: FTR, dtype: object
1.4
Levante - local
27     1
71     0
72     0
99     0
120    3
141    1
153    1
156    0
173    1
194    1
Name: FTR, dtype: object
0.8
11
11.0
Cadiz - visitante
29     0
42     3
60     1
88     3
102    0
119    1
147    1
169    0
192    0
215    1
Name: FTR, dtype: object
1.0
Villarreal - local
32     0
43     3
56     0
84     0
102    3
133    0
155    0
180    1
197    1
224    3
Name: FTR, dtype: object
1.1
13
11.1
Sevilla - visitante
31     1
71     3
78     3
80     3
105    1
129    0
143    3
183    3
200    3
203    0
Name: FTR, dtype: object
2.0
Valencia - local
33     3
41     0
59     1
83     1
103    3
131    3
149    3
181    3
196    1
215    1
Name: FTR, dtype: object
1.9
17
12.1
Eibar - visitante
34     3
64     0
76     0
97     0
108    1
128    0
151    0
167    0
187    1
209    0
Name: FTR, dtype: object
0.5
Sociedad - local
39     3
63     3
78     0
90     1
100    0
124    3
146    3
169    3
191    1
217    1
Name: FTR, dtype: object
1.8
19
12.0
Valladolid - visitante
33     0
51     1
67     1
91     0
117    1
136    1
160    1
174    0
194    1
222    3
Name: FTR, dtype: object
0.9
Getafe - local
34     0
73     1
88     0
104    1
116    1
137    3
158    0
179    1
199    3
222    0
Name: FTR, dtype: object
1.0
5
11.8
Levante - visitante
38     1
49     0
61     0
86     3
109    0
124    0
150    3
182    3
202    1
224    0
Name: FTR, dtype: object
1.1
Cadiz - local
36     3
66     0
74     1
93     3
128    3
135    0
154    0
178    0
202    1
208    3
Name: FTR, dtype: object
1.4
12
8.7
Elche - visitante
39     0
79     0
89     0
104    1
110    0
118    0
134    0
142    0
163    0
181    0
Name: FTR, dtype: object
0.1
Betis - local
30     3
69     1
75     1
81     1
109    3
122    3
152    3
166    0
175    3
198    3
Name: FTR, dtype: object
2.1
16
11.5
Huesca - visitante
36     0
65     0
77     0
99     3
111    0
140    1
161    0
184    3
199    0
228    0
Name: FTR, dtype: object
0.7
Barcelona - local
37     1
50     0
62     3
91     3
111    3
142    3
147    1
159    3
176    3
233    1
Name: FTR, dtype: object
2.1
23
14.8
Celta - visitante
32     3
63     0
74     1
95     3
126    3
149    0
165    1
177    1
198    0
221    0
Name: FTR, dtype: object
1.2
Ath Madrid - local
23     3
65     3
76     3
101    3
121    3
125    1
150    0
165    1
186    3
203    3
Name: FTR, dtype: object
2.3
20
12.6
Osasuna - visitante
35     1
45     0
55     0
84     3
106    1
138    3
156    3
175    0
196    1
204    0
Name: FTR, dtype: object
1.2
Ath Bilbao - local
35     1
51     1
53     3
87     1
108    1
123    3
144    1
168    1
185    3
214    0
Name: FTR, dtype: object
1.5
18
12.1
Real Madrid - visitante
20     3
66     3
73     1
107    3
125    1
148    3
172    3
190    3
210    1
227    1
Name: FTR, dtype: object
2.2
Alaves - local
38     1
68     3
77     3
95     0
119    1
138    0
174    3
190    0
200    0
219    0
Name: FTR, dtype: object
1.1
11
11.4
Granada - visitante
30     0
50     3
54     0
82     3
103    0
123    0
145    0
173    1
189    0
197    1
Name: FTR, dtype: object
0.8
Granada - local
42     0
64     3
98     0
114    3
134    3
162    0
177    1
204    3
211    0
230    3
Name: FTR, dtype: object
1.6
12
10.0
Real Madrid - visitante
66     3
73     1
107    3
125    1
148    3
172    3
190    3
210    1
227    1
245    3
Name: FTR, dtype: object
2.2
Eibar - local
48     3
52     0
86     0
113    0
140    1
160    1
183    0
195    0
218    3
245    0
Name: FTR, dtype: object
0.8
10
14.0
Betis - visitante
44     1
58     1
94     1
112    0
135    3
155    3
191    1
205    3
231    0
247    0
Name: FTR, dtype: object
1.3
Valladolid - local
44     1
60     1
82     0
105    1
130    3
148    0
184    0
201    1
207    0
240    0
Name: FTR, dtype: object
0.7
9
9.6
Villarreal - visitante
68     0
72     3
98     3
113    3
131    0
144    1
171    1
193    1
213    3
234    0
Name: FTR, dtype: object
1.5
Ath Madrid - local
65     3
76     3
101    3
121    3
125    1
150    0
165    1
186    3
203    3
229    3
Name: FTR, dtype: object
2.3
19
12.4
Sociedad - visitante
46     0
52     3
83     1
114    0
132    1
158    3
180    1
212    0
226    3
251    0
Name: FTR, dtype: object
1.2
Huesca - local
46     3
57     0
89     3
106    1
126    0
145    3
172    0
193    1
205    0
216    0
Name: FTR, dtype: object
1.1
11
10.7
Ath Bilbao - visitante
40     3
69     1
90     1
115    1
121    0
141    1
154    3
176    0
239    1
256    0
Name: FTR, dtype: object
1.1
Celta - local
49     3
55     3
80     0
107    0
115    1
136    1
163    3
187    1
213    0
228    3
Name: FTR, dtype: object
1.5
15
9.8
Getafe - visitante
43     0
57     3
62     0
96     1
130    0
152    0
164    0
170    0
185    0
206    3
Name: FTR, dtype: object
0.7
Sevilla - local
40     0
54     3
92     3
110    3
112    3
139    0
161    3
170    3
192    3
212    3
Name: FTR, dtype: object
2.4
16
13.0
Valencia - visitante
70     0
75     1
93     0
120    0
137    0
157    0
168    1
186    0
207    3
230    0
Name: FTR, dtype: object
0.5
Levante - local
71     0
72     0
99     0
120    3
141    1
153    1
156    0
173    1
194    1
209    3
Name: FTR, dtype: object
1.0
10
9.8
Barcelona - visitante
41     3
56     3
85     0
100    3
127    3
139    3
166    3
188    3
211    3
214    3
Name: FTR, dtype: object
2.7
Elche - local
47     0
61     3
67     1
94     1
129    3
151    3
171    1
188    0
206    0
227    1
Name: FTR, dtype: object
1.3
10
6.7
Alaves - visitante
48     0
59     1
87     1
101    0
122    0
146    0
159    0
179    1
208    0
225    1
Name: FTR, dtype: object
0.4
Osasuna - local
70     3
79     3
96     1
117    1
127    0
143    0
167    3
189    3
210    1
225    1
Name: FTR, dtype: object
1.6
11
9.6
Cadiz - visitante
42     3
60     1
88     3
102    0
119    1
147    1
169    0
192    0
215    1
235    0
Name: FTR, dtype: object
1.0
Betis - local
69     1
75     1
81     1
109    3
122    3
152    3
166    0
175    3
198    3
223    1
Name: FTR, dtype: object
1.9
15
11.7
Granada - visitante
50     3
54     0
82     3
103    0
123    0
145    0
173    1
189    0
197    1
218    0
Name: FTR, dtype: object
0.8
Real Madrid - local
45     3
58     1
85     3
97     3
118    3
132    1
157    3
164    3
182    0
221    3
Name: FTR, dtype: object
2.3
16
15.9
Sevilla - visitante
71     3
78     3
80     3
105    1
129    0
143    3
183    3
200    3
203    0
223    1
Name: FTR, dtype: object
2.0
Villarreal - local
43     3
56     0
84     0
102    3
133    0
155    0
180    1
197    1
224    3
239    1
Name: FTR, dtype: object
1.2
12
11.2
Celta - visitante
63     0
74     1
95     3
126    3
149    0
165    1
177    1
198    0
221    0
238    1
Name: FTR, dtype: object
1.0
Valencia - local
41     0
59     1
83     1
103    3
131    3
149    3
181    3
196    1
215    1
243    0
Name: FTR, dtype: object
1.6
14
12.5
Valladolid - visitante
51     1
67     1
91     0
117    1
136    1
160    1
174    0
194    1
222    3
232    1
Name: FTR, dtype: object
1.0
Getafe - local
73     1
88     0
104    1
116    1
137    3
158    0
179    1
199    3
222    0
238    1
Name: FTR, dtype: object
1.1
6
11.4
Eibar - visitante
64     0
76     0
97     0
108    1
128    0
151    0
167    0
187    1
209    0
233    1
Name: FTR, dtype: object
0.3
Ath Bilbao - local
51     1
53     3
87     1
108    1
123    3
144    1
168    1
185    3
214    0
220    3
Name: FTR, dtype: object
1.7
17
12.1
Osasuna - visitante
45     0
55     0
84     3
106    1
138    3
156    3
175    0
196    1
204    0
217    1
Name: FTR, dtype: object
1.2
Cadiz - local
66     0
74     1
93     3
128    3
135    0
154    0
178    0
202    1
208    3
232    1
Name: FTR, dtype: object
1.2
10
8.4
Huesca - visitante
65     0
77     0
99     3
111    0
140    1
161    0
184    3
199    0
228    0
254    0
Name: FTR, dtype: object
0.7
Barcelona - local
50     0
62     3
91     3
111    3
142    3
147    1
159    3
176    3
233    1
252    1
Name: FTR, dtype: object
2.1
25
16.1
Ath Madrid - visitante
47     3
53     0
81     1
92     0
116    1
133    3
153    1
162    3
178    3
195    3
Name: FTR, dtype: object
1.8
Alaves - local
68     3
77     3
95     0
119    1
138    0
174    3
190    0
200    0
219    0
236    3
Name: FTR, dtype: object
1.3
11
11.2
Levante - visitante
49     0
61     0
86     3
109    0
124    0
150    3
182    3
202    1
224    0
242    1
Name: FTR, dtype: object
1.1
Sociedad - local
63     3
78     0
90     1
100    0
124    3
146    3
169    3
191    1
217    1
241    0
Name: FTR, dtype: object
1.5
17
11.0
Elche - visitante
79     0
89     0
104    1
110    0
118    0
134    0
142    0
163    0
181    0
201    1
Name: FTR, dtype: object
0.2
Sevilla - local
54     3
92     3
110    3
112    3
139    0
161    3
170    3
192    3
212    3
234    3
Name: FTR, dtype: object
2.7
18
12.2
Ath Bilbao - visitante
69     1
90     1
115    1
121    0
141    1
154    3
176    0
239    1
256    0
265    1
Name: FTR, dtype: object
0.9
Valencia - local
59     1
83     1
103    3
131    3
149    3
181    3
196    1
215    1
243    0
265    1
Name: FTR, dtype: object
1.7
14
12.7
Barcelona - visitante
56     3
85     0
100    3
127    3
139    3
166    3
188    3
211    3
214    3
216    3

Name: FTR, dtype: object
2.7
Granada - local
64     3
98     0
114    3
134    3
162    0
177    1
204    3
211    0
230    3
247    3
Name: FTR, dtype: object
1.9
14
9.9
Cadiz - visitante
60     1
88     3
102    0
119    1
147    1
169    0
192    0
215    1
235    0
257    0
Name: FTR, dtype: object
0.7
Villarreal - local
56     0
84     0
102    3
133    0
155    0
180    1
197    1
224    3
239    1
269    1
Name: FTR, dtype: object
1.0
11
12.0
Getafe - visitante
57     3
62     0
96     1
130    0
152    0
164    0
170    0
185    0
206    3
229    0
Name: FTR, dtype: object
0.7
Valladolid - local
60     1
82     0
105    1
130    3
148    0
184    0
201    1
207    0
240    0
266    3
Name: FTR, dtype: object
0.9
11
9.7
Betis - visitante
58     1
94     1
112    0
135    3
155    3
191    1
205    3
231    0
247    0
270    3
Name: FTR, dtype: object
1.5
Real Madrid - local
58     1
85     3
97     3
118    3
132    1
157    3
164    3
182    0
221    3
237    3
Name: FTR, dtype: object
2.3
16
16.0
Osasuna - visitante
55     0
84     3
106    1
138    3
156    3
175    0
196    1
204    0
217    1
244    1
Name: FTR, dtype: object
1.3
Huesca - local
57     0
89     3
106    1
126    0
145    3
172    0
193    1
205    0
216    0
242    1
Name: FTR, dtype: object
0.9
11
10.8
Sociedad - visitante
52     3
83     1
114    0
132    1
158    3
180    1
212    0
226    3
251    0
255    0
Name: FTR, dtype: object
1.2
Elche - local
61     3
67     1
94     1
129    3
151    3
171    1
188    0
206    0
227    1
244    1
Name: FTR, dtype: object
1.4
12
6.8
Ath Madrid - visitante
53     0
81     1
92     0
116    1
133    3
153    1
162    3
178    3
195    3
219    3
Name: FTR, dtype: object
1.8
Eibar - local
52     0
86     0
113    0
140    1
160    1
183    0
195    0
218    3
245    0
267    1
Name: FTR, dtype: object
0.6
7
14.4
Alaves - visitante
59     1
87     1
101    0
122    0
146    0
159    0
179    1
208    0
225    1
248    0
Name: FTR, dtype: object
0.4
Celta - local
55     3
80     0
107    0
115    1
136    1
163    3
187    1
213    0
228    3
248    3
Name: FTR, dtype: object
1.5
15
10.1
Levante - visitante
61     0
86     3
109    0
124    0
150    3
182    3
202    1
224    0
242    1
258    0
Name: FTR, dtype: object
1.1
Barcelona - local
62     3
91     3
111    3
142    3
147    1
159    3
176    3
233    1
252    1
255    3
Name: FTR, dtype: object
2.4
26
15.9
Granada - visitante
54     0
82     3
103    0
123    0
145    0
173    1
189    0
197    1
218    0
237    0
Name: FTR, dtype: object
0.5
Ath Bilbao - local
53     3
87     1
108    1
123    3
144    1
168    1
185    3
214    0
220    3
226    0
Name: FTR, dtype: object
1.6
15
11.2
Valladolid - visitante
67     1
91     0
117    1
136    1
160    1
174    0
194    1
222    3
232    1
249    1
Name: FTR, dtype: object
1.0
Eibar - local
86     0
113    0
140    1
160    1
183    0
195    0
218    3
245    0
267    1
291    1
Name: FTR, dtype: object
0.7
7
14.5
Sociedad - visitante
83     1
114    0
132    1
158    3
180    1
212    0
226    3
251    0
255    0
268    1
Name: FTR, dtype: object
1.0
Ath Bilbao - local
87     1
108    1
123    3
144    1
168    1
185    3
214    0
220    3
226    0
254    3
Name: FTR, dtype: object
1.6
15
11.1
Ath Madrid - visitante
81     1
92     0
116    1
133    3
153    1
162    3
178    3
195    3
219    3
241    3
Name: FTR, dtype: object
2.1
Sevilla - local
92     3
110    3
112    3
139    0
161    3
170    3
192    3
212    3
234    3
249    1
Name: FTR, dtype: object
2.5
17
12.6
Granada - visitante
82     3
103    0
123    0
145    0
173    1
189    0
197    1
218    0
237    0
259    3
Name: FTR, dtype: object
0.8
Celta - local
80     0
107    0
115    1
136    1
163    3
187    1
213    0
228    3
248    3
257    3
Name: FTR, dtype: object
1.5
17
10.2
Osasuna - visitante
84     3
106    1
138    3
156    3
175    0
196    1
204    0
217    1
244    1
266    0
Name: FTR, dtype: object
1.3
Villarreal - local
84     0
102    3
133    0
155    0
180    1
197    1
224    3
239    1
269    1
294    1
Name: FTR, dtype: object
1.1
11
12.3
Barcelona - visitante
85     0
100    3
127    3
139    3
166    3
188    3
211    3
214    3
216    3
240    3
Name: FTR, dtype: object
2.7
Huesca - local
89     3
106    1
126    0
145    3
172    0
193    1
205    0
216    0
242    1
263    3
Name: FTR, dtype: object
1.2
12
11.1
Getafe - visitante
62     0
96     1
130    0
152    0
164    0
170    0
185    0
206    3
229    0
246    3
Name: FTR, dtype: object
0.7
Real Madrid - local
85     3
97     3
118    3
132    1
157    3
164    3
182    0
221    3
237    3
256    3
Name: FTR, dtype: object
2.5
19
16.1
Betis - visitante
94     1
112    0
135    3
155    3
191    1
205    3
231    0
247    0
270    3
287    0
Name: FTR, dtype: object
1.4
Valencia - local
83     1
103    3
131    3
149    3
181    3
196    1
215    1
243    0
265    1
284    0
Name: FTR, dtype: object
1.6
13
12.3
Alaves - visitante
87     1
101    0
122    0
146    0
159    0
179    1
208    0
225    1
248    0
263    0
Name: FTR, dtype: object
0.3
Valladolid - local
82     0
105    1
130    3
148    0
184    0
201    1
207    0
240    0
266    3
286    1
Name: FTR, dtype: object
0.9
11
9.4
Cadiz - visitante
88     3
102    0
119    1
147    1
169    0
192    0
215    1
235    0
257    0
285    1
Name: FTR, dtype: object
0.7
Elche - local
67     1
94     1
129    3
151    3
171    1
188    0
206    0
227    1
244    1
259    0
Name: FTR, dtype: object
1.1
11
6.9
Levante - visitante
86     3
109    0
124    0
150    3
182    3
202    1
224    0
242    1
258    0
286    1
Name: FTR, dtype: object
1.2
Barcelona - local
91     3
111    3
142    3
147    1
159    3
176    3
233    1
252    1
255    3
258    3
Name: FTR, dtype: object
2.4
22
17.4
Getafe - visitante
96     1
130    0
152    0
164    0
170    0
185    0
206    3
229    0
246    3
275    0
Name: FTR, dtype: object
0.7
Sociedad - local
78     0
90     1
100    0
124    3
146    3
169    3
191    1
217    1
241    0
261    1
Name: FTR, dtype: object
1.3
16
11.1
Celta - visitante
74     1
95     3
126    3
149    0
165    1
177    1
198    0
221    0
238    1
276    3
Name: FTR, dtype: object
1.3
Granada - local
98     0
114    3
134    3
162    0
177    1
204    3
211    0
230    3
247    3
271    1
Name: FTR, dtype: object
1.7
13
10.6
Eibar - visitante
76     0
97     0
108    1
128    0
151    0
167    0
187    1
209    0
233    1
236    0
Name: FTR, dtype: object
0.3
Ath Madrid - local
76     3
101    3
121    3
125    1
150    0
165    1
186    3
203    3
229    3
253    3
Name: FTR, dtype: object
2.3
20
11.8
Huesca - visitante
77     0
99     3
111    0
140    1
161    0
184    3
199    0
228    0
254    0
271    1
Name: FTR, dtype: object
0.8
Cadiz - local
74     1
93     3
128    3
135    0
154    0
178    0
202    1
208    3
232    1
246    0
Name: FTR, dtype: object
1.2
10
7.8
Real Madrid - visitante
73     1
107    3
125    1
148    3
172    3
190    3
210    1
227    1
245    3
274    3
Name: FTR, dtype: object
2.2
Elche - local
94     1
129    3
151    3
171    1
188    0
206    0
227    1
244    1
259    0
285    1
Name: FTR, dtype: object
1.1
11
6.4
Valladolid - visitante
91     0
117    1
136    1
160    1
174    0
194    1
222    3
232    1
249    1
273    0
Name: FTR, dtype: object
0.9
Alaves - local
77     3
95     0
119    1
138    0
174    3
190    0
200    0
219    0
236    3
268    1
Name: FTR, dtype: object
1.1
9
10.8
Villarreal - visitante
72     3
98     3
113    3
131    0
144    1
171    1
193    1
213    3
234    0
250    3
Name: FTR, dtype: object
1.8
Betis - local
75     1
81     1
109    3
122    3
152    3
166    0
175    3
198    3
223    1
235    3
Name: FTR, dtype: object
2.1
16
11.7
Ath Bilbao - visitante
90     1
115    1
121    0
141    1
154    3
176    0
239    1
256    0
265    1
280    1
Name: FTR, dtype: object
0.9
Osasuna - local
79     3
96     1
117    1
127    0
143    0
167    3
189    3
210    1
225    1
250    0
Name: FTR, dtype: object
1.3
9
8.4
Valencia - visitante
75     1
93     0
120    0
137    0
157    0
168    1
186    0
207    3
230    0
252    1
Name: FTR, dtype: object
0.6
Levante - local
72     0
99     0
120    3
141    1
153    1
156    0
173    1
194    1
209    3
231    3
Name: FTR, dtype: object
1.3
14
10.2
Sevilla - visitante
78     3
80     3
105    1
129    0
143    3
183    3
200    3
203    0
223    1
243    3
Name: FTR, dtype: object
2.0
Levante - local
99     0
120    3
141    1
153    1
156    0
173    1
194    1
209    3
231    3
251    3
Name: FTR, dtype: object
1.6
15
10.3
Villarreal - visitante
98     3
113    3
131    0
144    1
171    1
193    1
213    3
234    0
250    3
260    1
Name: FTR, dtype: object
1.6
Getafe - local
88     0
104    1
116    1
137    3
158    0
179    1
199    3
222    0
238    1
264    0
Name: FTR, dtype: object
1.0
6
10.3
Real Madrid - visitante
107    3
125    1
148    3
172    3
190    3
210    1
227    1
245    3
274    3
294    1
Name: FTR, dtype: object
2.2
Cadiz - local
93     3
128    3
135    0
154    0
178    0
202    1
208    3
232    1
246    0
272    3
Name: FTR, dtype: object
1.4
12
8.0
Celta - visitante
95     3
126    3
149    0
165    1
177    1
198    0
221    0
238    1
276    3
293    0
Name: FTR, dtype: object
1.2
Betis - local
81     1
109    3
122    3
152    3
166    0
175    3
198    3
223    1
235    3
260    1
Name: FTR, dtype: object
2.1
15
11.9
Valencia - visitante
93     0
120    0
137    0
157    0
168    1
186    0
207    3
230    0
252    1
267    1
Name: FTR, dtype: object
0.6
Ath Madrid - local
101    3
121    3
125    1
150    0
165    1
186    3
203    3
229    3
253    3
273    3
Name: FTR, dtype: object
2.3
17
12.3
Eibar - visitante
97     0
108    1
128    0
151    0
167    0
187    1
209    0
233    1
236    0
261    1
Name: FTR, dtype: object
0.4
Alaves - local
95     0
119    1
138    0
174    3
190    0
200    0
219    0
236    3
268    1
288    1
Name: FTR, dtype: object
0.9
10
11.1
Huesca - visitante
99     3
111    0
140    1
161    0
184    3
199    0
228    0
254    0
271    1
296    1
Name: FTR, dtype: object
0.9
Sociedad - local
90     1
100    0
124    3
146    3
169    3
191    1
217    1
241    0
261    1
278    1
Name: FTR, dtype: object
1.4
16
11.4
Sevilla - visitante
80     3
105    1
129    0
143    3
183    3
200    3
203    0
223    1
243    3
264    3
Name: FTR, dtype: object
2.0
Osasuna - local
96     1
117    1
127    0
143    0
167    3
189    3
210    1
225    1
250    0
270    0
Name: FTR, dtype: object
1.0
7
8.5
Elche - visitante
89     0
104    1
110    0
118    0
134    0
142    0
163    0
181    0
201    1
220    0
Name: FTR, dtype: object
0.2
Celta - local
107    0
115    1
136    1
163    3
187    1
213    0
228    3
248    3
257    3
279    3
Name: FTR, dtype: object
1.8
17
10.7
Sevilla - visitante
105    1
129    0
143    3
183    3
200    3
203    0
223    1
243    3
264    3
283    3
Name: FTR, dtype: object
2.0
Betis - local
109    3
122    3
152    3
166    0
175    3
198    3
223    1
235    3
260    1
277    0
Name: FTR, dtype: object
2.0
14
11.8
Ath Madrid - visitante
92     0
116    1
133    3
153    1
162    3
178    3
195    3
219    3
241    3
262    0
Name: FTR, dtype: object
2.0
Valladolid - local
105    1
130    3
148    0
184    0
201    1
207    0
240    0
266    3
286    1
298    3
Name: FTR, dtype: object
1.2
12
9.4
Granada - visitante
103    0
123    0
145    0
173    1
189    0
197    1
218    0
237    0
259    3
279    0
Name: FTR, dtype: object
0.5
Valencia - local
103    3
131    3
149    3
181    3
196    1
215    1
243    0
265    1
284    0
297    3
Name: FTR, dtype: object
1.8
15
12.1
Sociedad - visitante
114    0
132    1
158    3
180    1
212    0
226    3
251    0
255    0
268    1
290    3
Name: FTR, dtype: object
1.2
Villarreal - local
102    3
133    0
155    0
180    1
197    1
224    3
239    1
269    1
294    1
307    3
Name: FTR, dtype: object
1.4
12
11.9
Osasuna - visitante
106    1
138    3
156    3
175    0
196    1
204    0
217    1
244    1
266    0
281    0
Name: FTR, dtype: object
1.0
Real Madrid - local
97     3
118    3
132    1
157    3
164    3
182    0
221    3
237    3
256    3
262    3
Name: FTR, dtype: object
2.5
19
15.8
Barcelona - visitante
100    3
127    3
139    3
166    3
188    3
211    3
214    3
216    3
240    3
272    0
Name: FTR, dtype: object
2.7
Eibar - local
113    0
140    1
160    1
183    0
195    0
218    3
245    0
267    1
291    1
316    0
Name: FTR, dtype: object
0.7
7
14.4
Levante - visitante
109    0
124    0
150    3
182    3
202    1
224    0
242    1
258    0
286    1
309    1

Name: FTR, dtype: object
1.0
Ath Bilbao - local
108    1
123    3
144    1
168    1
185    3
214    0
220    3
226    0
254    3
276    0
Name: FTR, dtype: object
1.5
15
11.0
Alaves - visitante
101    0
122    0
146    0
159    0
179    1
208    0
225    1
248    0
263    0
282    3
Name: FTR, dtype: object
0.5
Getafe - local
104    1
116    1
137    3
158    0
179    1
199    3
222    0
238    1
264    0
280    1
Name: FTR, dtype: object
1.1
7
9.5
Cadiz - visitante
102    0
119    1
147    1
169    0
192    0
215    1
235    0
257    0
285    1
302    0
Name: FTR, dtype: object
0.4
Huesca - local
106    1
126    0
145    3
172    0
193    1
205    0
216    0
242    1
263    3
283    0
Name: FTR, dtype: object
0.9
9
10.8
Elche - visitante
104    1
110    0
118    0
134    0
142    0
163    0
181    0
201    1
220    0
253    0
Name: FTR, dtype: object
0.2
Sociedad - local
100    0
124    3
146    3
169    3
191    1
217    1
241    0
261    1
278    1
300    3
Name: FTR, dtype: object
1.6
17
12.4
Ath Bilbao - visitante
115    1
121    0
141    1
154    3
176    0
239    1
256    0
265    1
280    1
298    0
Name: FTR, dtype: object
0.8
Barcelona - local
111    3
142    3
147    1
159    3
176    3
233    1
252    1
255    3
258    3
281    3
Name: FTR, dtype: object
2.4
25
16.9
Valladolid - visitante
117    1
136    1
160    1
174    0
194    1
222    3
232    1
249    1
273    0
289    3
Name: FTR, dtype: object
1.2
Sevilla - local
110    3
112    3
139    0
161    3
170    3
192    3
212    3
234    3
249    1
274    0
Name: FTR, dtype: object
2.2
16
12.0
Ath Madrid - visitante
116    1
133    3
153    1
162    3
178    3
195    3
219    3
241    3
262    0
284    3
Name: FTR, dtype: object
2.3
Cadiz - local
128    3
135    0
154    0
178    0
202    1
208    3
232    1
246    0
272    3
290    0
Name: FTR, dtype: object
1.1
10
7.6
Valencia - visitante
120    0
137    0
157    0
168    1
186    0
207    3
230    0
252    1
267    1
288    1
Name: FTR, dtype: object
0.7
Elche - local
129    3
151    3
171    1
188    0
206    0
227    1
244    1
259    0
285    1
306    1
Name: FTR, dtype: object
1.1
11
6.5
Betis - visitante
112    0
135    3
155    3
191    1
205    3
231    0
247    0
270    3
287    0
304    0
Name: FTR, dtype: object
1.3
Alaves - local
119    1
138    0
174    3
190    0
200    0
219    0
236    3
268    1
288    1
312    1
Name: FTR, dtype: object
1.0
10
9.8
Celta - visitante
126    3
149    0
165    1
177    1
198    0
221    0
238    1
276    3
293    0
306    1
Name: FTR, dtype: object
1.0
Osasuna - local
117    1
127    0
143    0
167    3
189    3
210    1
225    1
250    0
270    0
296    1
Name: FTR, dtype: object
1.0
8
9.9
Getafe - visitante
130    0
152    0
164    0
170    0
185    0
206    3
229    0
246    3
275    0
291    1
Name: FTR, dtype: object
0.7
Real Madrid - local
118    3
132    1
157    3
164    3
182    0
221    3
237    3
256    3
262    3
282    0
Name: FTR, dtype: object
2.2
18
15.7
Eibar - visitante
108    1
128    0
151    0
167    0
187    1
209    0
233    1
236    0
261    1
277    3
Name: FTR, dtype: object
0.7
Granada - local
114    3
134    3
162    0
177    1
204    3
211    0
230    3
247    3
271    1
289    0
Name: FTR, dtype: object
1.7
14
11.6
Villarreal - visitante
113    3
131    0
144    1
171    1
193    1
213    3
234    0
250    3
260    1
278    1
Name: FTR, dtype: object
1.4
Levante - local
120    3
141    1
153    1
156    0
173    1
194    1
209    3
231    3
251    3
275    3
Name: FTR, dtype: object
1.9
18
10.2
Huesca - visitante
111    0
140    1
161    0
184    3
199    0
228    0
254    0
271    1
296    1
315    0
Name: FTR, dtype: object
0.6
Sociedad - local
124    3
146    3
169    3
191    1
217    1
241    0
261    1
278    1
300    3
318    3
Name: FTR, dtype: object
1.9
20
12.7
Barcelona - visitante
127    3
139    3
166    3
188    3
211    3
214    3
216    3
240    3
272    0
292    0
Name: FTR, dtype: object
2.4
Ath Madrid - local
121    3
125    1
150    0
165    1
186    3
203    3
229    3
253    3
273    3
292    3
Name: FTR, dtype: object
2.3
17
12.4
Alaves - visitante
122    0
146    0
159    0
179    1
208    0
225    1
248    0
263    0
282    3
299    1
Name: FTR, dtype: object
0.6
Villarreal - local
133    0
155    0
180    1
197    1
224    3
239    1
269    1
294    1
307    3
330    3
Name: FTR, dtype: object
1.4
12
12.2
Cadiz - visitante
119    1
147    1
169    0
192    0
215    1
235    0
257    0
285    1
302    0
316    3
Name: FTR, dtype: object
0.7
Valencia - local
131    3
149    3
181    3
196    1
215    1
243    0
265    1
284    0
297    3
308    1
Name: FTR, dtype: object
1.6
15
11.4
Granada - visitante
123    0
145    0
173    1
189    0
197    1
218    0
237    0
259    3
279    0
300    0
Name: FTR, dtype: object
0.5
Getafe - local
116    1
137    3
158    0
179    1
199    3
222    0
238    1
264    0
280    1
301    0
Name: FTR, dtype: object
1.0
7
9.6
Elche - visitante
110    0
118    0
134    0
142    0
163    0
181    0
201    1
220    0
253    0
269    1
Name: FTR, dtype: object
0.2
Valladolid - local
130    3
148    0
184    0
201    1
207    0
240    0
266    3
286    1
298    3
321    0
Name: FTR, dtype: object
1.1
11
9.6
Sevilla - visitante
129    0
143    3
183    3
200    3
203    0
223    1
243    3
264    3
283    3
314    0
Name: FTR, dtype: object
1.9
Huesca - local
126    0
145    3
172    0
193    1
205    0
216    0
242    1
263    3
283    0
305    1
Name: FTR, dtype: object
0.9
10
10.7
Osasuna - visitante
138    3
156    3
175    0
196    1
204    0
217    1
244    1
266    0
281    0
303    0
Name: FTR, dtype: object
0.9
Celta - local
115    1
136    1
163    3
187    1
213    0
228    3
248    3
257    3
279    3
310    0
Name: FTR, dtype: object
1.8
17
10.8
Real Madrid - visitante
125    1
148    3
172    3
190    3
210    1
227    1
245    3
274    3
294    1
297    0
Name: FTR, dtype: object
1.9
Ath Bilbao - local
123    3
144    1
168    1
185    3
214    0
220    3
226    0
254    3
276    0
287    3
Name: FTR, dtype: object
1.7
18
10.6
Eibar - visitante
128    0
151    0
167    0
187    1
209    0
233    1
236    0
261    1
277    3
305    1
Name: FTR, dtype: object
0.7
Betis - local
122    3
152    3
166    0
175    3
198    3
223    1
235    3
260    1
277    0
311    3
Name: FTR, dtype: object
2.0
15
12.0
Levante - visitante
124    0
150    3
182    3
202    1
224    0
242    1
258    0
286    1
309    1
331    0
Name: FTR, dtype: object
1.0
Sevilla - local
112    3
139    0
161    3
170    3
192    3
212    3
234    3
249    1
274    0
293    3
Name: FTR, dtype: object
2.2
18
12.2
Elche - visitante
118    0
134    0
142    0
163    0
181    0
201    1
220    0
253    0
269    1
295    1
Name: FTR, dtype: object
0.3
Barcelona - local
142    3
147    1
159    3
176    3
233    1
252    1
255    3
258    3
281    3
304    3
Name: FTR, dtype: object
2.4
26
17.5
Huesca - visitante
140    1
161    0
184    3
199    0
228    0
254    0
271    1
296    1
315    0
318    0
Name: FTR, dtype: object
0.6
Sevilla - local
139    0
161    3
170    3
192    3
212    3
234    3
249    1
274    0
293    3
303    3
Name: FTR, dtype: object
2.2
18
12.2
Betis - visitante
135    3
155    3
191    1
205    3
231    0
247    0
270    3
287    0
304    0
322    0
Name: FTR, dtype: object
1.3
Eibar - local
140    1
160    1
183    0
195    0
218    3
245    0
267    1
291    1
316    0
332    1
Name: FTR, dtype: object
0.8
6
13.8
Villarreal - visitante
131    0
144    1
171    1
193    1
213    3
234    0
250    3
260    1
278    1
301    3
Name: FTR, dtype: object
1.4
Granada - local
134    3
162    0
177    1
204    3
211    0
230    3
247    3
271    1
289    0
309    1
Name: FTR, dtype: object
1.5
14
11.4
Sociedad - visitante
132    1
158    3
180    1
212    0
226    3
251    0
255    0
268    1
290    3
310    3
Name: FTR, dtype: object
1.5
Celta - local
136    1
163    3
187    1
213    0
228    3
248    3
257    3
279    3
310    0
335    0
Name: FTR, dtype: object
1.7
17
11.0
Ath Bilbao - visitante
121    0
141    1
154    3
176    0
239    1
256    0
265    1
280    1
298    0
324    0
Name: FTR, dtype: object
0.7
Getafe - local
137    3
158    0
179    1
199    3
222    0
238    1
264    0
280    1
301    0
319    0
Name: FTR, dtype: object
0.9
7
9.5
Ath Madrid - visitante
133    3
153    1
162    3
178    3
195    3
219    3
241    3
262    0
284    3
313    3
Name: FTR, dtype: object
2.5
Osasuna - local
127    0
143    0
167    3
189    3
210    1
225    1
250    0
270    0
296    1
313    0
Name: FTR, dtype: object
0.9
9
9.3
Valladolid - visitante
136    1
160    1
174    0
194    1
222    3
232    1
249    1
273    0
289    3
307    0
Name: FTR, dtype: object
1.1
Real Madrid - local
132    1
157    3
164    3
182    0
221    3
237    3
256    3
262    3
282    0
315    3
Name: FTR, dtype: object
2.2
20
15.3
Elche - visitante
134    0
142    0
163    0
181    0
201    1
220    0
253    0
269    1
295    1
311    0
Name: FTR, dtype: object
0.3
Alaves - local
138    0
174    3
190    0
200    0
219    0
236    3
268    1
288    1
312    1
329    0
Name: FTR, dtype: object
0.9
9
10.2
Cadiz - visitante
147    1
169    0
192    0
215    1
235    0
257    0
285    1
302    0
316    3
334    3
Name: FTR, dtype: object
0.9
Levante - local
141    1
153    1
156    0
173    1
194    1
209    3
231    3
251    3
275    3
295    1
Name: FTR, dtype: object
1.7
18
10.4
Valencia - visitante
137    0
157    0
168    1
186    0
207    3
230    0
252    1
267    1
288    1
326    0
Name: FTR, dtype: object
0.7
Ath Madrid - local
125    1
150    0
165    1
186    3
203    3
229    3
253    3
273    3
292    3
302    3
Name: FTR, dtype: object
2.3
19
13.0
Ath Bilbao - visitante
141    1
154    3
176    0
239    1
256    0
265    1
280    1
298    0
324    0
340    0
Name: FTR, dtype: object
0.7
Betis - local
152    3
166    0
175    3
198    3
223    1
235    3
260    1
277    0
311    3
327    0
Name: FTR, dtype: object
1.7
12
10.4
Alaves - visitante
146    0
159    0
179    1
208    0
225    1
248    0
263    0
282    3
299    1
321    3
Name: FTR, dtype: object
0.9
Ath Bilbao - local
144    1
168    1
185    3
214    0
220    3
226    0
254    3
276    0
287    3
314    3
Name: FTR, dtype: object
1.7
18
11.5
Granada - visitante
145    0
173    1
189    0
197    1
218    0
237    0
259    3
279    0
300    0
319    3
Name: FTR, dtype: object
0.8
Sociedad - local
146    3
169    3
191    1
217    1
241    0
261    1
278    1
300    3
318    3
343    3
Name: FTR, dtype: object
1.9
22
11.3
Levante - visitante
150    3
182    3
202    1
224    0
242    1
258    0
286    1
309    1
331    0
348    0
Name: FTR, dtype: object
1.0
Ath Madrid - local
150    0
165    1
186    3
203    3
229    3
253    3
273    3
292    3
302    3
322    3
Name: FTR, dtype: object
2.5
20
13.2
Real Madrid - visitante
148    3
172    3
190    3
210    1
227    1
245    3
274    3
294    1
297    0
325    3
Name: FTR, dtype: object
2.1
Huesca - local
145    3
172    0
193    1
205    0
216    0
242    1
263    3
283    0
305    1
328    1
Name: FTR, dtype: object
1.0
9
10.0
Celta - visitante
149    0
165    1
177    1
198    0
221    0
238    1
276    3
293    0
306    1
317    1
Name: FTR, dtype: object
0.8
Osasuna - local
143    0
167    3
189    3
210    1
225    1
250    0
270    0
296    1
313    0
324    3
Name: FTR, dtype: object
1.2
10
9.0
Barcelona - visitante
139    3
166    3
188    3
211    3
214    3
216    3
240    3
272    0
292    0
312    1

Name: FTR, dtype: object
2.2
Cadiz - local
135    0
154    0
178    0
202    1
208    3
232    1
246    0
272    3
290    0
320    1
Name: FTR, dtype: object
0.9
9
7.5
Eibar - visitante
151    0
167    0
187    1
209    0
233    1
236    0
261    1
277    3
305    1
323    3
Name: FTR, dtype: object
1.0
Elche - local
151    3
171    1
188    0
206    0
227    1
244    1
259    0
285    1
306    1
326    3
Name: FTR, dtype: object
1.1
11
6.2
Sevilla - visitante
143    3
183    3
200    3
203    0
223    1
243    3
264    3
283    3
314    0
336    0
Name: FTR, dtype: object
1.9
Valladolid - local
148    0
184    0
201    1
207    0
240    0
266    3
286    1
298    3
321    0
346    0
Name: FTR, dtype: object
0.8
10
10.1
Getafe - visitante
152    0
164    0
170    0
185    0
206    3
229    0
246    3
275    0
291    1
308    1
Name: FTR, dtype: object
0.8
Valencia - local
149    3
181    3
196    1
215    1
243    0
265    1
284    0
297    3
308    1
342    0
Name: FTR, dtype: object
1.3
13
9.4
Villarreal - visitante
144    1
171    1
193    1
213    3
234    0
250    3
260    1
278    1
301    3
320    1
Name: FTR, dtype: object
1.5
Real Madrid - local
157    3
164    3
182    0
221    3
237    3
256    3
262    3
282    0
315    3
334    0
Name: FTR, dtype: object
2.1
19
14.6
Sociedad - visitante
158    3
180    1
212    0
226    3
251    0
255    0
268    1
290    3
310    3
327    3
Name: FTR, dtype: object
1.7
Villarreal - local
155    0
180    1
197    1
224    3
239    1
269    1
294    1
307    3
330    3
352    3
Name: FTR, dtype: object
1.7
15
11.3
Ath Madrid - visitante
153    1
162    3
178    3
195    3
219    3
241    3
262    0
284    3
313    3
335    3
Name: FTR, dtype: object
2.5
Granada - local
162    0
177    1
204    3
211    0
230    3
247    3
271    1
289    0
309    1
336    3
Name: FTR, dtype: object
1.5
13
11.4
Elche - visitante
142    0
163    0
181    0
201    1
220    0
253    0
269    1
295    1
311    0
329    3
Name: FTR, dtype: object
0.6
Cadiz - local
154    0
178    0
202    1
208    3
232    1
246    0
272    3
290    0
320    1
338    1
Name: FTR, dtype: object
1.0
10
8.4
Betis - visitante
155    3
191    1
205    3
231    0
247    0
270    3
287    0
304    0
322    0
342    3
Name: FTR, dtype: object
1.3
Celta - local
163    3
187    1
213    0
228    3
248    3
257    3
279    3
310    0
335    0
347    0
Name: FTR, dtype: object
1.6
16
10.9
Valladolid - visitante
160    1
174    0
194    1
222    3
232    1
249    1
273    0
289    3
307    0
328    1
Name: FTR, dtype: object
1.1
Getafe - local
158    0
179    1
199    3
222    0
238    1
264    0
280    1
301    0
319    0
333    3
Name: FTR, dtype: object
0.9
5
8.9
Valencia - visitante
157    0
168    1
186    0
207    3
230    0
252    1
267    1
288    1
326    0
330    0
Name: FTR, dtype: object
0.7
Alaves - local
174    3
190    0
200    0
219    0
236    3
268    1
288    1
312    1
329    0
340    3
Name: FTR, dtype: object
1.2
10
10.6
Osasuna - visitante
156    3
175    0
196    1
204    0
217    1
244    1
266    0
281    0
303    0
332    1
Name: FTR, dtype: object
0.7
Sevilla - local
161    3
170    3
192    3
212    3
234    3
249    1
274    0
293    3
303    3
323    0
Name: FTR, dtype: object
2.2
18
13.9
Barcelona - visitante
166    3
188    3
211    3
214    3
216    3
240    3
272    0
292    0
312    1
333    0
Name: FTR, dtype: object
1.9
Eibar - local
160    1
183    0
195    0
218    3
245    0
267    1
291    1
316    0
332    1
351    0
Name: FTR, dtype: object
0.7
5
13.3
Huesca - visitante
161    0
184    3
199    0
228    0
254    0
271    1
296    1
315    0
318    0
344    1
Name: FTR, dtype: object
0.6
Levante - local
153    1
156    0
173    1
194    1
209    3
231    3
251    3
275    3
295    1
299    1
Name: FTR, dtype: object
1.7
18
11.2
Ath Bilbao - visitante
154    3
176    0
239    1
256    0
265    1
280    1
298    0
324    0
340    0
360    3
Name: FTR, dtype: object
0.9
Barcelona - local
147    1
159    3
176    3
233    1
252    1
255    3
258    3
281    3
304    3
325    0
Name: FTR, dtype: object
2.1
24
17.6
Elche - visitante
163    0
181    0
201    1
220    0
253    0
269    1
295    1
311    0
329    3
351    3
Name: FTR, dtype: object
0.9
Osasuna - local
167    3
189    3
210    1
225    1
250    0
270    0
296    1
313    0
324    3
341    3
Name: FTR, dtype: object
1.5
12
9.8
Sevilla - visitante
183    3
200    3
203    0
223    1
243    3
264    3
283    3
314    0
336    0
337    1
Name: FTR, dtype: object
1.7
Ath Bilbao - local
168    1
185    3
214    0
220    3
226    0
254    3
276    0
287    3
314    3
331    3
Name: FTR, dtype: object
1.9
19
11.1
Villarreal - visitante
171    1
193    1
213    3
234    0
250    3
260    1
278    1
301    3
320    1
345    1
Name: FTR, dtype: object
1.5
Huesca - local
172    0
193    1
205    0
216    0
242    1
263    3
283    0
305    1
328    1
353    1
Name: FTR, dtype: object
0.8
6
9.4
Granada - visitante
173    1
189    0
197    1
218    0
237    0
259    3
279    0
300    0
319    3
338    1
Name: FTR, dtype: object
0.9
Sociedad - local
169    3
191    1
217    1
241    0
261    1
278    1
300    3
318    3
343    3
355    0
Name: FTR, dtype: object
1.6
18
11.6
Alaves - visitante
159    0
179    1
208    0
225    1
248    0
263    0
282    3
299    1
321    3
352    0
Name: FTR, dtype: object
0.9
Barcelona - local
159    3
176    3
233    1
252    1
255    3
258    3
281    3
304    3
325    0
337    1
Name: FTR, dtype: object
2.1
24
16.8
Cadiz - visitante
169    0
192    0
215    1
235    0
257    0
285    1
302    0
316    3
334    3
349    3
Name: FTR, dtype: object
1.1
Valladolid - local
184    0
201    1
207    0
240    0
266    3
286    1
298    3
321    0
346    0
357    1
Name: FTR, dtype: object
0.9
11
10.2
Real Madrid - visitante
172    3
190    3
210    1
227    1
245    3
274    3
294    1
297    0
325    3
339    3
Name: FTR, dtype: object
2.1
Valencia - local
181    3
196    1
215    1
243    0
265    1
284    0
297    3
308    1
342    0
364    1
Name: FTR, dtype: object
1.1
12
8.9
Celta - visitante
165    1
177    1
198    0
221    0
238    1
276    3
293    0
306    1
317    1
341    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
165    1
186    3
203    3
229    3
253    3
273    3
292    3
302    3
322    3
345    1
Name: FTR, dtype: object
2.6
20
11.8
Levante - visitante
182    3
202    1
224    0
242    1
258    0
286    1
309    1
331    0
348    0
361    3
Name: FTR, dtype: object
1.0
Elche - local
171    1
188    0
206    0
227    1
244    1
259    0
285    1
306    1
326    3
344    1
Name: FTR, dtype: object
0.9
10
5.8
Eibar - visitante
167    0
187    1
209    0
233    1
236    0
261    1
277    3
305    1
323    3
346    3
Name: FTR, dtype: object
1.3
Betis - local
166    0
175    3
198    3
223    1
235    3
260    1
277    0
311    3
327    0
362    0
Name: FTR, dtype: object
1.4
13
10.7
Getafe - visitante
164    0
170    0
185    0
206    3
229    0
246    3
275    0
291    1
308    1
343    0
Name: FTR, dtype: object
0.8
Levante - local
156    0
173    1
194    1
209    3
231    3
251    3
275    3
295    1
299    1
317    1
Name: FTR, dtype: object
1.7
18
11.5
Ath Madrid - visitante
162    3
178    3
195    3
219    3
241    3
262    0
284    3
313    3
335    3
353    1
Name: FTR, dtype: object
2.5
Cadiz - local
178    0
202    1
208    3
232    1
246    0
272    3
290    0
320    1
338    1
358    0
Name: FTR, dtype: object
1.0
11
8.5
Ath Bilbao - visitante
176    0
239    1
256    0
265    1
280    1
298    0
324    0
340    0
360    3
378    0
Name: FTR, dtype: object
0.6
Villarreal - local
180    1
197    1
224    3
239    1
269    1
294    1
307    3
330    3
352    3
372    3
Name: FTR, dtype: object
2.0
16
11.8
Betis - visitante
191    1
205    3
231    0
247    0
270    3
287    0
304    0
322    0
342    3
354    0
Name: FTR, dtype: object
1.0
Levante - local
173    1
194    1
209    3
231    3
251    3
275    3
295    1
299    1
317    1
339    0
Name: FTR, dtype: object
1.7
18
11.3
Osasuna - visitante
175    0
196    1
204    0
217    1
244    1
266    0
281    0
303    0
332    1
371    0
Name: FTR, dtype: object
0.4
Real Madrid - local
164    3
182    0
221    3
237    3
256    3
262    3
282    0
315    3
334    0
350    3
Name: FTR, dtype: object
2.1
18
14.5
Valencia - visitante
168    1
186    0
207    3
230    0
252    1
267    1
288    1
326    0
330    0
355    3
Name: FTR, dtype: object
1.0
Getafe - local
179    1
199    3
222    0
238    1
264    0
280    1
301    0
319    0
333    3
354    3
Name: FTR, dtype: object
1.2
8
9.3
Sociedad - visitante
180    1
212    0
226    3
251    0
255    0
268    1
290    3
310    3
327    3
363    3
Name: FTR, dtype: object
1.7
Barcelona - local
176    3
233    1
252    1
255    3
258    3
281    3
304    3
325    0
337    1
356    3
Name: FTR, dtype: object
2.1
23
16.8
Alaves - visitante
179    1
208    0
225    1
248    0
263    0
282    3
299    1
321    3
352    0
367    0
Name: FTR, dtype: object
0.9
Eibar - local
183    0
195    0
218    3
245    0
267    1
291    1
316    0
332    1
351    0
360    0
Name: FTR, dtype: object
0.6
5
12.6
Valladolid - visitante
174    0
194    1
222    3
232    1
249    1
273    0
289    3
307    0
328    1
350    0
Name: FTR, dtype: object
1.0
Sevilla - local
170    3
192    3
212    3
234    3
249    1
274    0
293    3
303    3
323    0
348    3
Name: FTR, dtype: object
2.2
18
14.1
Huesca - visitante
184    3
199    0
228    0
254    0
271    1
296    1
315    0
318    0
344    1
364    1
Name: FTR, dtype: object
0.7
Granada - local
177    1
204    3
211    0
230    3
247    3
271    1
289    0
309    1
336    3
367    3
Name: FTR, dtype: object
1.8
14
11.8
Ath Madrid - visitante
178    3
195    3
219    3
241    3
262    0
284    3
313    3
335    3
353    1
394    3
Name: FTR, dtype: object
2.5
Celta - local
187    1
213    0
228    3
248    3
257    3
279    3
310    0
335    0
347    0
370    3
Name: FTR, dtype: object
1.6
15
12.3
Elche - visitante
181     0
201     1
220     0
253     0
269     1
295     1
311     0
329     3
351     3
2283    1
Name: FTR, dtype: object
1.0
Real Madrid - local
182    0
221    3
237    3
256    3
262    3
282    0
315    3
334    0
350    3
392    3
Name: FTR, dtype: object
2.1
18
14.3
Getafe - visitante
170    0
185    0
206    3
229    0
246    3
275    0
291    1
308    1
343    0
365    1
Name: FTR, dtype: object
0.9
Ath Madrid - local
186    3
203    3
229    3
253    3
273    3
292    3
302    3
322    3
345    1
359    3
Name: FTR, dtype: object
2.8
24
12.6
Celta - visitante
177    1
198    0
221    0
238    1
276    3
293    0
306    1
317    1
341    0
357    1
Name: FTR, dtype: object
0.8
Betis - local
175    3
198    3
223    1
235    3
260    1
277    0
311    3
327    0
362    0
368    3
Name: FTR, dtype: object
1.7
13
11.5
Barcelona - visitante
188    3
211    3
214    3
216    3
240    3
272    0
292    0
312    1
333    0
347    3
Name: FTR, dtype: object
1.9
Osasuna - local
189    3
210    1
225    1
250    0
270    0
296    1
313    0
324    3
341    3
361    0
Name: FTR, dtype: object
1.2
11
9.5
Eibar - visitante
187    1
209    0
233    1
236    0
261    1
277    3
305    1
323    3
346    3
372    0
Name: FTR, dtype: object
1.3
Ath Bilbao - local
185    3
214    0
220    3
226    0
254    3
276    0
287    3
314    3
331    3
349    0
Name: FTR, dtype: object
1.8
18
11.3

Valencia - visitante
186    0
207    3
230    0
252    1
267    1
288    1
326    0
330    0
355    3
370    0
Name: FTR, dtype: object
0.9
Sociedad - local
191    1
217    1
241    0
261    1
278    1
300    3
318    3
343    3
355    0
366    1
Name: FTR, dtype: object
1.4
14
10.5
Cadiz - visitante
192    0
215    1
235    0
257    0
285    1
302    0
316    3
334    3
349    3
369    3
Name: FTR, dtype: object
1.4
Sevilla - local
192    3
212    3
234    3
249    1
274    0
293    3
303    3
323    0
348    3
380    3
Name: FTR, dtype: object
2.2
16
14.0
Getafe - visitante
185    0
206    3
229    0
246    3
275    0
291    1
308    1
343    0
365    1
382    0
Name: FTR, dtype: object
0.9
Elche - local
188    0
206    0
227    1
244    1
259    0
285    1
306    1
326    3
344    1
363    0
Name: FTR, dtype: object
0.8
8
5.5
Villarreal - visitante
193    1
213    3
234    0
250    3
260    1
278    1
301    3
320    1
345    1
356    0
Name: FTR, dtype: object
1.4
Huesca - local
193    1
205    0
216    0
242    1
263    3
283    0
305    1
328    1
353    1
369    0
Name: FTR, dtype: object
0.8
5
8.5
Real Madrid - visitante
190    3
210    1
227    1
245    3
274    3
294    1
297    0
325    3
339    3
362    3
Name: FTR, dtype: object
2.1
Levante - local
194    1
209    3
231    3
251    3
275    3
295    1
299    1
317    1
339    0
382    3
Name: FTR, dtype: object
1.9
17
11.5
Granada - visitante
189    0
197    1
218    0
237    0
259    3
279    0
300    0
319    3
338    1
359    0
Name: FTR, dtype: object
0.8
Alaves - local
190    0
200    0
219    0
236    3
268    1
288    1
312    1
329    0
340    3
365    1
Name: FTR, dtype: object
1.0
9
9.5
Valladolid - visitante
194    1
222    3
232    1
249    1
273    0
289    3
307    0
328    1
350    0
368    0
Name: FTR, dtype: object
1.0
Betis - local
198    3
223    1
235    3
260    1
277    0
311    3
327    0
362    0
368    3
396    0
Name: FTR, dtype: object
1.4
13
12.1
Osasuna - visitante
196    1
204    0
217    1
244    1
266    0
281    0
303    0
332    1
371    0
377    3
Name: FTR, dtype: object
0.7
Barcelona - local
233    1
252    1
255    3
258    3
281    3
304    3
325    0
337    1
356    3
397    0
Name: FTR, dtype: object
1.8
22
17.5
Ath Bilbao - visitante
239    1
256    0
265    1
280    1
298    0
324    0
340    0
360    3
378    0
384    0
Name: FTR, dtype: object
0.6
Granada - local
204    3
211    0
230    3
247    3
271    1
289    0
309    1
336    3
367    3
378    3
Name: FTR, dtype: object
2.0
16
11.2
Celta - visitante
198    0
221    0
238    1
276    3
293    0
306    1
317    1
341    0
357    1
379    1
Name: FTR, dtype: object
0.8
Cadiz - local
202    1
208    3
232    1
246    0
272    3
290    0
320    1
338    1
358    0
377    0
Name: FTR, dtype: object
1.0
9
8.6
Ath Madrid - visitante
195    3
219    3
241    3
262    0
284    3
313    3
335    3
353    1
394    3
418    1
Name: FTR, dtype: object
2.3
Getafe - local
199    3
222    0
238    1
264    0
280    1
301    0
319    0
333    3
354    3
371    3
Name: FTR, dtype: object
1.4
9
9.5
Alaves - visitante
208    0
225    1
248    0
263    0
282    3
299    1
321    3
352    0
367    0
396    3
Name: FTR, dtype: object
1.1
Villarreal - local
197    1
224    3
239    1
269    1
294    1
307    3
330    3
352    3
372    3
374    1
Name: FTR, dtype: object
2.0
16
12.9
Sociedad - visitante
212    0
226    3
251    0
255    0
268    1
290    3
310    3
327    3
363    3
375    1
Name: FTR, dtype: object
1.7
Valencia - local
196    1
215    1
243    0
265    1
284    0
297    3
308    1
342    0
364    1
373    3
Name: FTR, dtype: object
1.1
15
8.9
Elche - visitante
201     1
220     0
253     0
269     1
295     1
311     0
329     3
351     3
2283    1
2301    0
Name: FTR, dtype: object
1.0
Real Madrid - local
221    3
237    3
256    3
262    3
282    0
315    3
334    0
350    3
392    3
410    3
Name: FTR, dtype: object
2.4
19
15.3
Levante - visitante
202    1
224    0
242    1
258    0
286    1
309    1
331    0
348    0
361    3
373    0
Name: FTR, dtype: object
0.7
Eibar - local
195    0
218    3
245    0
267    1
291    1
316    0
332    1
351    0
360    0
379    1
Name: FTR, dtype: object
0.7
5
11.7
Sevilla - visitante
200    3
203    0
223    1
243    3
264    3
283    3
314    0
336    0
337    1
358    3
Name: FTR, dtype: object
1.7
Valladolid - local
201    1
207    0
240    0
266    3
286    1
298    3
321    0
346    0
357    1
375    1
Name: FTR, dtype: object
1.0
11
9.6
Huesca - visitante
199    0
228    0
254    0
271    1
296    1
315    0
318    0
344    1
364    1
374    1
Name: FTR, dtype: object
0.5
Ath Bilbao - local
214    0
220    3
226    0
254    3
276    0
287    3
314    3
331    3
349    0
398    0
Name: FTR, dtype: object
1.5
13
11.2
Getafe - visitante
206    3
229    0
246    3
275    0
291    1
308    1
343    0
365    1
382    0
402    1
Name: FTR, dtype: object
1.0
Ath Madrid - local
203    3
229    3
253    3
273    3
292    3
302    3
322    3
345    1
359    3
386    1
Name: FTR, dtype: object
2.6
22
11.8
Valencia - visitante
207    3
230    0
252    1
267    1
288    1
326    0
330    0
355    3
370    0
380    0
Name: FTR, dtype: object
0.9
Celta - local
213    0
228    3
248    3
257    3
279    3
310    0
335    0
347    0
370    3
395    0
Name: FTR, dtype: object
1.5
16
13.2
Eibar - visitante
209    0
233    1
236    0
261    1
277    3
305    1
323    3
346    3
372    0
387    0
Name: FTR, dtype: object
1.2
Elche - local
206     0
227     1
244     1
259     0
285     1
306     1
326     3
344     1
363     0
2297    0
Name: FTR, dtype: object
0.8
10
6.1
Barcelona - visitante
211    3
214    3
216    3
240    3
272    0
292    0
312    1
333    0
347    3
389    3
Name: FTR, dtype: object
1.9
Osasuna - local
210    1
225    1
250    0
270    0
296    1
313    0
324    3
341    3
361    0
381    1
Name: FTR, dtype: object
1.0
10
10.0
Granada - visitante
197    1
218    0
237    0
259    3
279    0
300    0
319    3
338    1
359    0
393    3
Name: FTR, dtype: object
1.1
Alaves - local
200    0
219    0
236    3
268    1
288    1
312    1
329    0
340    3
365    1
376    0
Name: FTR, dtype: object
1.0
8
8.8
Real Madrid - visitante
210    1
227    1
245    3
274    3
294    1
297    0
325    3
339    3
362    3
366    1
Name: FTR, dtype: object
1.9
Sociedad - local
217    1
241    0
261    1
278    1
300    3
318    3
343    3
355    0
366    1
391    1
Name: FTR, dtype: object
1.4
12
10.4
Betis - visitante
205    3
231    0
247    0
270    3
287    0
304    0
322    0
342    3
354    0
376    3
Name: FTR, dtype: object
1.2
Sevilla - local
212    3
234    3
249    1
274    0
293    3
303    3
323    0
348    3
380    3
403    3
Name: FTR, dtype: object
2.2
15
13.9
Cadiz - visitante
215    1
235    0
257    0
285    1
302    0
316    3
334    3
349    3
369    3
Name: FTR, dtype: object
1.5555555555555556
Huesca - local
205    0
216    0
242    1
263    3
283    0
305    1
328    1
353    1
369    0
765    3
Name: FTR, dtype: object
1.0
7
9.5
Villarreal - visitante
213    3
234    0
250    3
260    1
278    1
301    3
320    1
345    1
356    0
392    0
Name: FTR, dtype: object
1.3
Levante - local
209    3
231    3
251    3
275    3
295    1
299    1
317    1
339    0
382    3
405    0
Name: FTR, dtype: object
1.8
16
10.9
Valladolid - visitante
222    3
232    1
249    1
273    0
289    3
307    0
328    1
350    0
368    0
399    0
Name: FTR, dtype: object
0.9
Eibar - local
218    3
245    0
267    1
291    1
316    0
332    1
351    0
360    0
379    1
399    3
Name: FTR, dtype: object
1.0
7
11.8
Ath Madrid - visitante
219    3
241    3
262    0
284    3
313    3
335    3
353    1
394    3
418    1
437    1
Name: FTR, dtype: object
2.1
Valencia - local
215    1
243    0
265    1
284    0
297    3
308    1
342    0
364    1
373    3
390    3
Name: FTR, dtype: object
1.3
15
8.8
Osasuna - visitante
204    0
217    1
244    1
266    0
281    0
303    0
332    1
371    0
377    3
397    3
Name: FTR, dtype: object
0.9
Villarreal - local
224    3
239    1
269    1
294    1
307    3
330    3
352    3
372    3
374    1
387    3
Name: FTR, dtype: object
2.2
18
13.2
Granada - visitante
218    0
237    0
259    3
279    0
300    0
319    3
338    1
359    0
393    3
411    3
Name: FTR, dtype: object
1.3
Betis - local
223    1
235    3
260    1
277    0
311    3
327    0
362    0
368    3
396    0
417    3
Name: FTR, dtype: object
1.4
14
12.3
Celta - visitante
221    0
238    1
276    3
293    0
306    1
317    1
341    0
357    1
379    1
385    1
Name: FTR, dtype: object
0.9
Getafe - local
222    0
238    1
264    0
280    1
301    0
319    0
333    3
354    3
371    3
394    0
Name: FTR, dtype: object
1.1
8
9.8
Huesca - visitante
228    0
254    0
271    1
296    1
315    0
318    0
344    1
364    1
374    1
776    0
Name: FTR, dtype: object
0.5
Alaves - local
219    0
236    3
268    1
288    1
312    1
329    0
340    3
365    1
376    0
389    0
Name: FTR, dtype: object
1.0
7
8.4
Sevilla - visitante
203    0
223    1
243    3
264    3
283    3
314    0
336    0
337    1
358    3
391    1
Name: FTR, dtype: object
1.5
Valladolid - local
207    0
240    0
266    3
286    1
298    3
321    0
346    0
357    1
375    1
388    3
Name: FTR, dtype: object
1.2
11
9.6
Elche - visitante
220     0
253     0
269     1
295     1
311     0
329     3
351     3
2283    1
2301    0
2312    3
Name: FTR, dtype: object
1.2
Cadiz - local
208    3
232    1
246    0
272    3
290    0
320    1
338    1
358    0
377    0
Name: FTR, dtype: object
1.0
7
8.666666666666666
Levante - visitante
224    0
242    1
258    0
286    1
309    1
331    0
348    0
361    3
373    0
395    3
Name: FTR, dtype: object
0.9
Ath Madrid - local
229    3
253    3
273    3
292    3
302    3
322    3
345    1
359    3
386    1
407    3
Name: FTR, dtype: object
2.6
21
12.2
Sevilla - visitante
223    1
243    3
264    3
283    3
314    0
336    0
337    1
358    3
391    1
412    3
Name: FTR, dtype: object
1.8
Granada - local
211    0
230    3
247    3
271    1
289    0
309    1
336    3
367    3
378    3
384    3
Name: FTR, dtype: object
2.0
18
11.4
Osasuna - visitante
217    1
244    1
266    0
281    0
303    0
332    1
371    0
377    3
397    3
417    0
Name: FTR, dtype: object
0.9
Huesca - local
216    0
242    1
263    3
283    0
305    1
328    1
353    1
369    0
765    3
782    0
Name: FTR, dtype: object
1.0
9
10.9
Betis - visitante
231    0
247    0
270    3
287    0
304    0
322    0
342    3
354    0
376    3
388    0
Name: FTR, dtype: object
0.9
Elche - local
227     1
244     1
259     0
285     1
306     1
326     3
344     1
363     0
2297    0
2324    3
Name: FTR, dtype: object
1.1
13
6.6
Getafe - visitante
229    0
246    3
275    0
291    1
308    1
343    0
365    1
382    0
402    1
423    1
Name: FTR, dtype: object
0.8
Valladolid - local
240    0
266    3
286    1
298    3
321    0
346    0
357    1
375    1
388    3
408    0
Name: FTR, dtype: object
1.2
11
9.8
Valencia - visitante
230    0
252    1
267    1
288    1
326    0
330    0
355    3
370    0
380    0
404    0
Name: FTR, dtype: object
0.6
Cadiz - local
232    1
246    0
272    3
290    0
320    1
338    1
358    0
377    0
Name: FTR, dtype: object
0.75
4
8.5
Alaves - visitante
225    1
248    0
263    0
282    3
299    1
321    3
352    0
367    0
396    3
410    0
Name: FTR, dtype: object
1.1
Levante - local
231    3
251    3
275    3
295    1
299    1
317    1
339    0
382    3
405    0
421    1
Name: FTR, dtype: object
1.6
15
11.4
Eibar - visitante
233    1
236    0
261    1
277    3
305    1
323    3
346    3
372    0
387    0
406    3
Name: FTR, dtype: object
1.5
Osasuna - local

225    1
250    0
270    0
296    1
313    0
324    3
341    3
361    0
381    1
409    3
Name: FTR, dtype: object
1.2
12
10.7
Real Madrid - visitante
227    1
245    3
274    3
294    1
297    0
325    3
339    3
362    3
366    1
383    1
Name: FTR, dtype: object
1.9
Granada - local
230    3
247    3
271    1
289    0
309    1
336    3
367    3
378    3
384    3
400    0
Name: FTR, dtype: object
2.0
19
11.9
Barcelona - visitante
214    3
216    3
240    3
272    0
292    0
312    1
333    0
347    3
389    3
408    3
Name: FTR, dtype: object
1.9
Sevilla - local
234    3
249    1
274    0
293    3
303    3
323    0
348    3
380    3
403    3
420    3
Name: FTR, dtype: object
2.2
13
13.5
Sociedad - visitante
226    3
251    0
255    0
268    1
290    3
310    3
327    3
363    3
375    1
386    1
Name: FTR, dtype: object
1.8
Celta - local
228    3
248    3
257    3
279    3
310    0
335    0
347    0
370    3
395    0
418    1
Name: FTR, dtype: object
1.6
17
13.3
Villarreal - visitante
234    0
250    3
260    1
278    1
301    3
320    1
345    1
356    0
392    0
416    3
Name: FTR, dtype: object
1.3
Ath Bilbao - local
220    3
226    0
254    3
276    0
287    3
314    3
331    3
349    0
398    0
412    0
Name: FTR, dtype: object
1.5
12
11.7
Barcelona - visitante
216    3
240    3
272    0
292    0
312    1
333    0
347    3
389    3
408    3
422    3
Name: FTR, dtype: object
1.9
Valencia - local
243    0
265    1
284    0
297    3
308    1
342    0
364    1
373    3
390    3
419    3
Name: FTR, dtype: object
1.5
16
8.7
Cadiz - visitante
235    0
257    0
285    1
302    0
316    3
334    3
349    3
369    3
Name: FTR, dtype: object
1.625
Huesca - local
242    1
263    3
283    0
305    1
328    1
353    1
369    0
765    3
782    0
808    3
Name: FTR, dtype: object
1.3
11
11.7
Barcelona - visitante
240    3
272    0
292    0
312    1
333    0
347    3
389    3
408    3
422    3
447    1
Name: FTR, dtype: object
1.7
Sociedad - local
241    0
261    1
278    1
300    3
318    3
343    3
355    0
366    1
391    1
411    0
Name: FTR, dtype: object
1.3
13
11.5
Osasuna - visitante
244    1
266    0
281    0
303    0
332    1
371    0
377    3
397    3
417    0
432    3
Name: FTR, dtype: object
1.1
Eibar - local
245    0
267    1
291    1
316    0
332    1
351    0
360    0
379    1
399    3
414    1
Name: FTR, dtype: object
0.8
5
10.7
Granada - visitante
237    0
259    3
279    0
300    0
319    3
338    1
359    0
393    3
411    3
436    3
Name: FTR, dtype: object
1.6
Alaves - local
236    3
268    1
288    1
312    1
329    0
340    3
365    1
376    0
389    0
402    1
Name: FTR, dtype: object
1.1
6
8.3
Ath Madrid - visitante
241    3
262    0
284    3
313    3
335    3
353    1
394    3
418    1
437    1
457    3
Name: FTR, dtype: object
2.1
Ath Bilbao - local
226    0
254    3
276    0
287    3
314    3
331    3
349    0
398    0
412    0
425    0
Name: FTR, dtype: object
1.2
11
11.1
Elche - visitante
253     0
269     1
295     1
311     0
329     3
351     3
2283    1
2301    0
2312    3
2338    0
Name: FTR, dtype: object
1.2
Real Madrid - local
237    3
256    3
262    3
282    0
315    3
334    0
350    3
392    3
410    3
430    3
Name: FTR, dtype: object
2.4
18
15.2
Celta - visitante
238    1
276    3
293    0
306    1
317    1
341    0
357    1
379    1
385    1
409    0
Name: FTR, dtype: object
0.9
Getafe - local
238    1
264    0
280    1
301    0
319    0
333    3
354    3
371    3
394    0
416    0
Name: FTR, dtype: object
1.1
9
9.2
Valladolid - visitante
232    1
249    1
273    0
289    3
307    0
328    1
350    0
368    0
399    0
419    0
Name: FTR, dtype: object
0.6
Betis - local
235    3
260    1
277    0
311    3
327    0
362    0
368    3
396    0
417    3
434    0
Name: FTR, dtype: object
1.3
13
11.6
Sevilla - visitante
243    3
264    3
283    3
314    0
336    0
337    1
358    3
391    1
412    3
438    3
Name: FTR, dtype: object
2.0
Villarreal - local
239    1
269    1
294    1
307    3
330    3
352    3
372    3
374    1
387    3
401    0
Name: FTR, dtype: object
1.9
17
12.9
Levante - visitante
242    1
258    0
286    1
309    1
331    0
348    0
361    3
373    0
395    3
413    0
Name: FTR, dtype: object
0.9
Osasuna - local
250    0
270    0
296    1
313    0
324    3
341    3
361    0
381    1
409    3
423    1
Name: FTR, dtype: object
1.2
11
10.5
Alaves - visitante
248    0
263    0
282    3
299    1
321    3
352    0
367    0
396    3
410    0
427    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
254    3
276    0
287    3
314    3
331    3
349    0
398    0
412    0
425    0
448    3
Name: FTR, dtype: object
1.5
14
11.9
Sociedad - visitante
251    0
255    0
268    1
290    3
310    3
327    3
363    3
375    1
386    1
401    3
Name: FTR, dtype: object
1.8
Elche - local
244     1
259     0
285     1
306     1
326     3
344     1
363     0
2297    0
2324    3
2340    3
Name: FTR, dtype: object
1.3
13
6.9
Real Madrid - visitante
245    3
274    3
294    1
297    0
325    3
339    3
362    3
366    1
383    1
400    3
Name: FTR, dtype: object
2.1
Celta - local
248    3
257    3
279    3
310    0
335    0
347    0
370    3
395    0
418    1
428    1
Name: FTR, dtype: object
1.4
16
12.3
Huesca - visitante
254    0
271    1
296    1
315    0
318    0
344    1
364    1
374    1
776    0
791    1
Name: FTR, dtype: object
0.6
Ath Madrid - local
253    3
273    3
292    3
302    3
322    3
345    1
359    3
386    1
407    3
429    3
Name: FTR, dtype: object
2.6
23
12.7
Getafe - visitante
246    3
275    0
291    1
308    1
343    0
365    1
382    0
402    1
423    1
430    0
Name: FTR, dtype: object
0.8
Granada - local
247    3
271    1
289    0
309    1
336    3
367    3
378    3
384    3
400    0
426    1
Name: FTR, dtype: object
1.8
19
11.2
Valencia - visitante
252    1
267    1
288    1
326    0
330    0
355    3
370    0
380    0
404    0
426    1
Name: FTR, dtype: object
0.7
Levante - local
251    3
275    3
295    1
299    1
317    1
339    0
382    3
405    0
421    1
444    3
Name: FTR, dtype: object
1.6
15
11.3
Betis - visitante
247    0
270    3
287    0
304    0
322    0
342    3
354    0
376    3
388    0
407    0
Name: FTR, dtype: object
0.9
Cadiz - local
246    0
272    3
290    0
320    1
338    1
358    0
377    0
Name: FTR, dtype: object
0.7142857142857143
4
8.571428571428571
Valladolid - visitante
249    1
273    0
289    3
307    0
328    1
350    0
368    0
399    0
419    0
449    1
Name: FTR, dtype: object
0.6
Barcelona - local
252    1
255    3
258    3
281    3
304    3
325    0
337    1
356    3
397    0
415    3
Name: FTR, dtype: object
2.0
22
16.8
Eibar - visitante
236    0
261    1
277    3
305    1
323    3
346    3
372    0
387    0
406    3
420    0
Name: FTR, dtype: object
1.4
Sevilla - local
249    1
274    0
293    3
303    3
323    0
348    3
380    3
403    3
420    3
449    1
Name: FTR, dtype: object
2.0
12
14.0
Villarreal - visitante
250    3
260    1
278    1
301    3
320    1
345    1
356    0
392    0
416    3
434    3
Name: FTR, dtype: object
1.6
Betis - local
260    1
277    0
311    3
327    0
362    0
368    3
396    0
417    3
434    0
450    3
Name: FTR, dtype: object
1.3
13
12.3
Cadiz - visitante
257    0
285    1
302    0
316    3
334    3
349    3
369    3
Name: FTR, dtype: object
1.8571428571428572
Alaves - local
268    1
288    1
312    1
329    0
340    3
365    1
376    0
389    0
402    1
436    0
Name: FTR, dtype: object
0.8
4
8.1
Eibar - visitante
261    1
277    3
305    1
323    3
346    3
372    0
387    0
406    3
420    0
442    3
Name: FTR, dtype: object
1.7
Real Madrid - local
256    3
262    3
282    0
315    3
334    0
350    3
392    3
410    3
430    3
452    3
Name: FTR, dtype: object
2.4
18
14.3
Granada - visitante
259    3
279    0
300    0
319    3
338    1
359    0
393    3
411    3
436    3
458    1
Name: FTR, dtype: object
1.7
Getafe - local
264    0
280    1
301    0
319    0
333    3
354    3
371    3
394    0
416    0
440    3
Name: FTR, dtype: object
1.3
10
9.7
Celta - visitante
276    3
293    0
306    1
317    1
341    0
357    1
379    1
385    1
409    0
439    0
Name: FTR, dtype: object
0.8
Villarreal - local
269    1
294    1
307    3
330    3
352    3
372    3
374    1
387    3
401    0
422    0
Name: FTR, dtype: object
1.8
17
12.3
Ath Bilbao - visitante
256    0
265    1
280    1
298    0
324    0
340    0
360    3
378    0
384    0
405    3
Name: FTR, dtype: object
0.8
Valladolid - local
266    3
286    1
298    3
321    0
346    0
357    1
375    1
388    3
408    0
427    3
Name: FTR, dtype: object
1.5
12
9.1
Barcelona - visitante
272    0
292    0
312    1
333    0
347    3
389    3
408    3
422    3
447    1
467    1
Name: FTR, dtype: object
1.5
Sociedad - local
261    1
278    1
300    3
318    3
343    3
355    0
366    1
391    1
411    0
431    3
Name: FTR, dtype: object
1.6
15
12.1
Ath Madrid - visitante
262    0
284    3
313    3
335    3
353    1
394    3
418    1
437    1
457    3
472    3
Name: FTR, dtype: object
2.1
Huesca - local
263    3
283    0
305    1
328    1
353    1
369    0
765    3
782    0
808    3
827    1
Name: FTR, dtype: object
1.3
10
11.2
Levante - visitante
258    0
286    1
309    1
331    0
348    0
361    3
373    0
395    3
413    0
433    1
Name: FTR, dtype: object
0.9
Valencia - local
265    1
284    0
297    3
308    1
342    0
364    1
373    3
390    3
419    3
435    0
Name: FTR, dtype: object
1.5
16
8.7
Sevilla - visitante
264    3
283    3
314    0
336    0
337    1
358    3
391    1
412    3
438    3
459    1
Name: FTR, dtype: object
1.8
Elche - local
259     0
285     1
306     1
326     3
344     1
363     0
2297    0
2324    3
2340    3
2361    0
Name: FTR, dtype: object
1.2
11
7.8
Osasuna - visitante
266    0
281    0
303    0
332    1
371    0
377    3
397    3
417    0
432    3
454    3
Name: FTR, dtype: object
1.3
Eibar - local
267    1
291    1
316    0
332    1
351    0
360    0
379    1
399    3
414    1
432    0
Name: FTR, dtype: object
0.8
4
10.8
Real Madrid - visitante
274    3
294    1
297    0
325    3
339    3
362    3
366    1
383    1
400    3
425    3
Name: FTR, dtype: object
2.1
Cadiz - local
272    3
290    0
320    1
338    1
358    0
377    0
Name: FTR, dtype: object
0.8333333333333334
4
8.666666666666666
Getafe - visitante
275    0
291    1
308    1
343    0
365    1
382    0
402    1
423    1
430    0
456    1
Name: FTR, dtype: object
0.6
Granada - local
271    1
289    0
309    1
336    3
367    3
378    3
384    3
400    0
426    1
442    0
Name: FTR, dtype: object
1.5
18
11.8
Betis - visitante
270    3
287    0
304    0
322    0
342    3
354    0
376    3
388    0
407    0
428    1
Name: FTR, dtype: object
1.0
Celta - local
257    3
279    3
310    0
335    0
347    0
370    3
395    0
418    1
428    1
447    1
Name: FTR, dtype: object
1.2
16
12.2
Alaves - visitante
263    0
282    3
299    1
321    3
352    0
367    0
396    3
410    0
427    0
445    0
Name: FTR, dtype: object
1.0
Sevilla - local
274    0
293    3
303    3
323    0
348    3
380    3
403    3
420    3
449    1
467    1
Name: FTR, dtype: object
2.0
11
13.4
Valladolid - visitante
273    0
289    3
307    0
328    1
350    0
368    0
399    0
419    0
449    1
463    0
Name: FTR, dtype: object
0.5
Osasuna - local
270    0
296    1
313    0
324    3
341    3
361    0
381    1
409    3
423    1
446    3
Name: FTR, dtype: object
1.5
12
10.5
Villarreal - visitante
260    1
278    1
301    3
320    1
345    1
356    0
392    0
416    3
434    3
469    3
Name: FTR, dtype: object
1.6
Levante - local
275    3
295    1
299    1
317    1
339    0
382    3
405    0
421    1
444    3
457    0
Name: FTR, dtype: object
1.3
13
11.2
Sociedad - visitante
255    0
268    1
290    3
310    3
327    3
363    3
375    1
386    1
401    3
421    1
Name: FTR, dtype: object
1.9

Barcelona - local
255    3
258    3
281    3
304    3
325    0
337    1
356    3
397    0
415    3
437    1
Name: FTR, dtype: object
2.0
22
15.5
Valencia - visitante
267    1
288    1
326    0
330    0
355    3
370    0
380    0
404    0
426    1
443    0
Name: FTR, dtype: object
0.6
Ath Madrid - local
273    3
292    3
302    3
322    3
345    1
359    3
386    1
407    3
429    3
445    3
Name: FTR, dtype: object
2.6
22
12.9
Elche - visitante
269     1
295     1
311     0
329     3
351     3
2283    1
2301    0
2312    3
2338    0
2354    3
Name: FTR, dtype: object
1.5
Ath Bilbao - local
276    0
287    3
314    3
331    3
349    0
398    0
412    0
425    0
448    3
465    3
Name: FTR, dtype: object
1.5
13
12.1
Huesca - visitante
271    1
296    1
315    0
318    0
344    1
364    1
374    1
776    0
791    1
815    1
Name: FTR, dtype: object
0.7
Barcelona - local
258    3
281    3
304    3
325    0
337    1
356    3
397    0
415    3
437    1
455    3
Name: FTR, dtype: object
2.0
21
15.9
Sociedad - visitante
268    1
290    3
310    3
327    3
363    3
375    1
386    1
401    3
421    1
440    0
Name: FTR, dtype: object
1.9
Real Madrid - local
262    3
282    0
315    3
334    0
350    3
392    3
410    3
430    3
452    3
470    3
Name: FTR, dtype: object
2.4
18
14.4
Ath Bilbao - visitante
265    1
280    1
298    0
324    0
340    0
360    3
378    0
384    0
405    3
435    3
Name: FTR, dtype: object
1.1
Celta - local
279    3
310    0
335    0
347    0
370    3
395    0
418    1
428    1
447    1
462    3
Name: FTR, dtype: object
1.2
18
12.9
Cadiz - visitante
285    1
302    0
316    3
334    3
349    3
369    3
Name: FTR, dtype: object
2.1666666666666665
Barcelona - local
281    3
304    3
325    0
337    1
356    3
397    0
415    3
437    1
455    3
475    3
Name: FTR, dtype: object
2.0
22
14.5
Levante - visitante
286    1
309    1
331    0
348    0
361    3
373    0
395    3
413    0
433    1
466    3
Name: FTR, dtype: object
1.2
Elche - local
285     1
306     1
326     3
344     1
363     0
2297    0
2324    3
2340    3
2361    0
2389    0
Name: FTR, dtype: object
1.2
11
7.6
Granada - visitante
279    0
300    0
319    3
338    1
359    0
393    3
411    3
436    3
458    1
478    1
Name: FTR, dtype: object
1.5
Betis - local
277    0
311    3
327    0
362    0
368    3
396    0
417    3
434    0
450    3
478    1
Name: FTR, dtype: object
1.3
14
13.0
Villarreal - visitante
278    1
301    3
320    1
345    1
356    0
392    0
416    3
434    3
469    3
485    3
Name: FTR, dtype: object
1.8
Sociedad - local
278    1
300    3
318    3
343    3
355    0
366    1
391    1
411    0
431    3
453    0
Name: FTR, dtype: object
1.5
14
12.6
Eibar - visitante
277    3
305    1
323    3
346    3
372    0
387    0
406    3
420    0
442    3
464    1
Name: FTR, dtype: object
1.7
Real Madrid - local
282    0
315    3
334    0
350    3
392    3
410    3
430    3
452    3
470    3
481    3
Name: FTR, dtype: object
2.4
19
13.9
Ath Madrid - visitante
284    3
313    3
335    3
353    1
394    3
418    1
437    1
457    3
472    3
482    1
Name: FTR, dtype: object
2.2
Huesca - local
283    0
305    1
328    1
353    1
369    0
765    3
782    0
808    3
827    1
844    1
Name: FTR, dtype: object
1.1
12
12.4
Alaves - visitante
282    3
299    1
321    3
352    0
367    0
396    3
410    0
427    0
445    0
462    0
Name: FTR, dtype: object
1.0
Getafe - local
280    1
301    0
319    0
333    3
354    3
371    3
394    0
416    0
440    3
464    1
Name: FTR, dtype: object
1.4
11
9.8
Sevilla - visitante
283    3
314    0
336    0
337    1
358    3
391    1
412    3
438    3
459    1
479    1
Name: FTR, dtype: object
1.6
Valencia - local
284    0
297    3
308    1
342    0
364    1
373    3
390    3
419    3
435    0
461    3
Name: FTR, dtype: object
1.7
16
8.3
Ath Bilbao - visitante
280    1
298    0
324    0
340    0
360    3
378    0
384    0
405    3
435    3
455    0
Name: FTR, dtype: object
1.0
Valladolid - local
286    1
298    3
321    0
346    0
357    1
375    1
388    3
408    0
427    3
433    1
Name: FTR, dtype: object
1.3
9
9.5
Osasuna - visitante
281    0
303    0
332    1
371    0
377    3
397    3
417    0
432    3
454    3
461    0
Name: FTR, dtype: object
1.3
Eibar - local
291    1
316    0
332    1
351    0
360    0
379    1
399    3
414    1
432    0
451    3
Name: FTR, dtype: object
1.0
5
10.3
Valencia - visitante
288    1
326    0
330    0
355    3
370    0
380    0
404    0
426    1
443    0
451    0
Name: FTR, dtype: object
0.5
Alaves - local
288    1
312    1
329    0
340    3
365    1
376    0
389    0
402    1
436    0
454    0
Name: FTR, dtype: object
0.7
4
8.1
Sociedad - visitante
290    3
310    3
327    3
363    3
375    1
386    1
401    3
421    1
440    0
471    0
Name: FTR, dtype: object
1.8
Villarreal - local
294    1
307    3
330    3
352    3
372    3
374    1
387    3
401    0
422    0
443    3
Name: FTR, dtype: object
2.0
19
12.8
Elche - visitante
295     1
311     0
329     3
351     3
2283    1
2301    0
2312    3
2338    0
2354    3
2370    1
Name: FTR, dtype: object
1.5
Osasuna - local
296    1
313    0
324    3
341    3
361    0
381    1
409    3
423    1
446    3
472    0
Name: FTR, dtype: object
1.5
12
10.8
Betis - visitante
287    0
304    0
322    0
342    3
354    0
376    3
388    0
407    0
428    1
444    0
Name: FTR, dtype: object
0.7
Granada - local
289    0
309    1
336    3
367    3
378    3
384    3
400    0
426    1
442    0
469    0
Name: FTR, dtype: object
1.4
15
11.7
Huesca - visitante
296    1
315    0
318    0
344    1
364    1
374    1
776    0
791    1
815    1
831    1
Name: FTR, dtype: object
0.7
Cadiz - local
290    0
320    1
338    1
358    0
377    0
Name: FTR, dtype: object
0.4
2
9.0
Barcelona - visitante
292    0
312    1
333    0
347    3
389    3
408    3
422    3
447    1
467    1
483    3
Name: FTR, dtype: object
1.8
Ath Madrid - local
292    3
302    3
322    3
345    1
359    3
386    1
407    3
429    3
445    3
463    3
Name: FTR, dtype: object
2.6
21
12.9
Valladolid - visitante
289    3
307    0
328    1
350    0
368    0
399    0
419    0
449    1
463    0
484    3
Name: FTR, dtype: object
0.8
Sevilla - local
293    3
303    3
323    0
348    3
380    3
403    3
420    3
449    1
467    1
489    3
Name: FTR, dtype: object
2.3
13
13.5
Real Madrid - visitante
294    1
297    0
325    3
339    3
362    3
366    1
383    1
400    3
425    3
441    3
Name: FTR, dtype: object
2.1
Levante - local
295    1
299    1
317    1
339    0
382    3
405    0
421    1
444    3
457    0
479    1
Name: FTR, dtype: object
1.1
11
11.1
Getafe - visitante
291    1
308    1
343    0
365    1
382    0
402    1
423    1
430    0
456    1
488    0
Name: FTR, dtype: object
0.6
Ath Bilbao - local
287    3
314    3
331    3
349    0
398    0
412    0
425    0
448    3
465    3
482    1
Name: FTR, dtype: object
1.6
14
12.1
Celta - visitante
293    0
306    1
317    1
341    0
357    1
379    1
385    1
409    0
439    0
453    3
Name: FTR, dtype: object
0.8
Betis - local
311    3
327    0
362    0
368    3
396    0
417    3
434    0
450    3
478    1
491    3
Name: FTR, dtype: object
1.6
16
13.7
Eibar - visitante
305    1
323    3
346    3
372    0
387    0
406    3
420    0
442    3
464    1
481    0
Name: FTR, dtype: object
1.4
Sociedad - local
300    3
318    3
343    3
355    0
366    1
391    1
411    0
431    3
453    0
460    0
Name: FTR, dtype: object
1.4
14
12.8
Villarreal - visitante
301    3
320    1
345    1
356    0
392    0
416    3
434    3
469    3
485    3
504    0
Name: FTR, dtype: object
1.7
Celta - local
310    0
335    0
347    0
370    3
395    0
418    1
428    1
447    1
462    3
485    0
Name: FTR, dtype: object
0.9
15
11.6
Granada - visitante
300    0
319    3
338    1
359    0
393    3
411    3
436    3
458    1
478    1
493    1
Name: FTR, dtype: object
1.6
Getafe - local
301    0
319    0
333    3
354    3
371    3
394    0
416    0
440    3
464    1
477    1
Name: FTR, dtype: object
1.4
10
10.8
Ath Bilbao - visitante
298    0
324    0
340    0
360    3
378    0
384    0
405    3
435    3
455    0
474    1
Name: FTR, dtype: object
1.0
Barcelona - local
304    3
325    0
337    1
356    3
397    0
415    3
437    1
455    3
475    3
497    3
Name: FTR, dtype: object
2.0
19
13.8
Osasuna - visitante
303    0
332    1
371    0
377    3
397    3
417    0
432    3
454    3
461    0
480    1
Name: FTR, dtype: object
1.4
Real Madrid - local
315    3
334    0
350    3
392    3
410    3
430    3
452    3
470    3
481    3
501    3
Name: FTR, dtype: object
2.7
20
13.2
Alaves - visitante
299    1
321    3
352    0
367    0
396    3
410    0
427    0
445    0
462    0
486    0
Name: FTR, dtype: object
0.7
Huesca - local
305    1
328    1
353    1
369    0
765    3
782    0
808    3
827    1
844    1
867    0
Name: FTR, dtype: object
1.1
13
12.6
Sevilla - visitante
314    0
336    0
337    1
358    3
391    1
412    3
438    3
459    1
479    1
498    1
Name: FTR, dtype: object
1.4
Valencia - local
297    3
308    1
342    0
364    1
373    3
390    3
419    3
435    0
461    3
487    1
Name: FTR, dtype: object
1.8
17
9.0
Ath Madrid - visitante
313    3
335    3
353    1
394    3
418    1
437    1
457    3
472    3
482    1
503    1
Name: FTR, dtype: object
2.0
Elche - local
306     1
326     3
344     1
363     0
2297    0
2324    3
2340    3
2361    0
2389    0
2407    3
Name: FTR, dtype: object
1.4
11
8.7
Cadiz - visitante
302    0
316    3
334    3
349    3
369    3
Name: FTR, dtype: object
2.4
Valladolid - local
298    3
321    0
346    0
357    1
375    1
388    3
408    0
427    3
433    1
456    1
Name: FTR, dtype: object
1.3
9
9.1
Levante - visitante
309    1
331    0
348    0
361    3
373    0
395    3
413    0
433    1
466    3
487    1
Name: FTR, dtype: object
1.2
Ath Bilbao - local
314    3
331    3
349    0
398    0
412    0
425    0
448    3
465    3
482    1
504    3
Name: FTR, dtype: object
1.6
11
12.5
Betis - visitante
304    0
322    0
342    3
354    0
376    3
388    0
407    0
428    1
444    0
465    0
Name: FTR, dtype: object
0.7
Alaves - local
312    1
329    0
340    3
365    1
376    0
389    0
402    1
436    0
454    0
471    3
Name: FTR, dtype: object
0.9
4
8.3
Valencia - visitante
326    0
330    0
355    3
370    0
380    0
404    0
426    1
443    0
451    0
470    0
Name: FTR, dtype: object
0.4
Granada - local
309    1
336    3
367    3
378    3
384    3
400    0
426    1
442    0
469    0
488    3
Name: FTR, dtype: object
1.7
16
11.1
Valladolid - visitante
307    0
328    1
350    0
368    0
399    0
419    0
449    1
463    0
484    3
510    0
Name: FTR, dtype: object
0.5
Cadiz - local
320    1
338    1
358    0
377    0
Name: FTR, dtype: object
0.5
2
10.75
Sociedad - visitante
310    3
327    3
363    3
375    1
386    1
401    3
421    1
440    0
471    0
490    3
Name: FTR, dtype: object
1.8
Eibar - local
316    0
332    1
351    0
360    0
379    1
399    3
414    1
432    0
451    3
474    1
Name: FTR, dtype: object
1.0
7
10.0
Getafe - visitante
308    1
343    0
365    1
382    0
402    1
423    1
430    0
456    1
488    0
502    3
Name: FTR, dtype: object
0.8
Ath Madrid - local
302    3
322    3
345    1
359    3
386    1
407    3
429    3
445    3
463    3
498    1
Name: FTR, dtype: object
2.4
22
14.1
Barcelona - visitante
312    1
333    0
347    3
389    3
408    3
422    3
447    1
467    1
483    3
501    0
Name: FTR, dtype: object
1.8
Sevilla - local
303    3
323    0
348    3
380    3
403    3
420    3
449    1
467    1
489    3
505    3
Name: FTR, dtype: object
2.3
12
13.2
Celta - visitante
306    1
317    1
341    0
357    1
379    1
385    1
409    0
439    0
453    3
473    1
Name: FTR, dtype: object
0.9
Villarreal - local
307    3
330    3
352    3
372    3
374    1
387    3
401    0
422    0
443    3
459    1

Name: FTR, dtype: object
2.0
20
12.2
Real Madrid - visitante
297    0
325    3
339    3
362    3
366    1
383    1
400    3
425    3
441    3
460    3
Name: FTR, dtype: object
2.3
Levante - local
299    1
317    1
339    0
382    3
405    0
421    1
444    3
457    0
479    1
493    1
Name: FTR, dtype: object
1.1
11
10.9
Elche - visitante
311     0
329     3
351     3
2283    1
2301    0
2312    3
2338    0
2354    3
2370    1
2391    0
Name: FTR, dtype: object
1.4
Osasuna - local
313    0
324    3
341    3
361    0
381    1
409    3
423    1
446    3
472    0
495    3
Name: FTR, dtype: object
1.7
12
10.7
Huesca - visitante
315    0
318    0
344    1
364    1
374    1
776    0
791    1
815    1
831    1
853    0
Name: FTR, dtype: object
0.6
Valencia - local
308    1
342    0
364    1
373    3
390    3
419    3
435    0
461    3
487    1
508    3
Name: FTR, dtype: object
1.8
15
9.3
Real Madrid - visitante
325    3
339    3
362    3
366    1
383    1
400    3
425    3
441    3
460    3
491    0
Name: FTR, dtype: object
2.3
Valladolid - local
321    0
346    0
357    1
375    1
388    3
408    0
427    3
433    1
456    1
473    1
Name: FTR, dtype: object
1.1
7
9.0
Ath Bilbao - visitante
324    0
340    0
360    3
378    0
384    0
405    3
435    3
455    0
474    1
494    3
Name: FTR, dtype: object
1.3
Levante - local
317    1
339    0
382    3
405    0
421    1
444    3
457    0
479    1
493    1
516    3
Name: FTR, dtype: object
1.3
11
9.9
Alaves - visitante
321    3
352    0
367    0
396    3
410    0
427    0
445    0
462    0
486    0
507    1
Name: FTR, dtype: object
0.7
Sociedad - local
318    3
343    3
355    0
366    1
391    1
411    0
431    3
453    0
460    0
480    1
Name: FTR, dtype: object
1.2
13
11.5
Granada - visitante
319    3
338    1
359    0
393    3
411    3
436    3
458    1
478    1
493    1
515    3
Name: FTR, dtype: object
1.9
Getafe - local
319    0
333    3
354    3
371    3
394    0
416    0
440    3
464    1
477    1
496    1
Name: FTR, dtype: object
1.5
9
11.4
Villarreal - visitante
320    1
345    1
356    0
392    0
416    3
434    3
469    3
485    3
504    0
511    0
Name: FTR, dtype: object
1.4
Ath Madrid - local
322    3
345    1
359    3
386    1
407    3
429    3
445    3
463    3
498    1
511    3
Name: FTR, dtype: object
2.4
21
14.0
Cadiz - visitante
316    3
334    3
349    3
369    3
Name: FTR, dtype: object
3.0
Sevilla - local
323    0
348    3
380    3
403    3
420    3
449    1
467    1
489    3
505    3
524    1
Name: FTR, dtype: object
2.1
13
14.1
Osasuna - visitante
332    1
371    0
377    3
397    3
417    0
432    3
454    3
461    0
480    1
505    0
Name: FTR, dtype: object
1.4
Barcelona - local
325    0
337    1
356    3
397    0
415    3
437    1
455    3
475    3
497    3
518    3
Name: FTR, dtype: object
2.0
19
13.3
Betis - visitante
322    0
342    3
354    0
376    3
388    0
407    0
428    1
444    0
465    0
489    0
Name: FTR, dtype: object
0.7
Huesca - local
328    1
353    1
369    0
765    3
782    0
808    3
827    1
844    1
867    0
887    3
Name: FTR, dtype: object
1.3
14
11.9
Eibar - visitante
323    3
346    3
372    0
387    0
406    3
420    0
442    3
464    1
481    0
518    0
Name: FTR, dtype: object
1.3
Elche - local
326     3
344     1
363     0
2297    0
2324    3
2340    3
2361    0
2389    0
2407    3
2423    0
Name: FTR, dtype: object
1.3
10
8.3
Celta - visitante
317    1
341    0
357    1
379    1
385    1
409    0
439    0
453    3
473    1
496    1
Name: FTR, dtype: object
0.9
Villarreal - local
330    3
352    3
372    3
374    1
387    3
401    0
422    0
443    3
459    1
476    3
Name: FTR, dtype: object
2.0
19
12.1
Valladolid - visitante
328    1
350    0
368    0
399    0
419    0
449    1
463    0
484    3
510    0
525    0
Name: FTR, dtype: object
0.5
Valencia - local
342    0
364    1
373    3
390    3
419    3
435    0
461    3
487    1
508    3
529    1
Name: FTR, dtype: object
1.8
15
9.1
Getafe - visitante
343    0
365    1
382    0
402    1
423    1
430    0
456    1
488    0
502    3
527    0
Name: FTR, dtype: object
0.7
Granada - local
336    3
367    3
378    3
384    3
400    0
426    1
442    0
469    0
488    3
506    1
Name: FTR, dtype: object
1.7
15
12.0
Levante - visitante
331    0
348    0
361    3
373    0
395    3
413    0
433    1
466    3
487    1
509    0
Name: FTR, dtype: object
1.1
Celta - local
335    0
347    0
370    3
395    0
418    1
428    1
447    1
462    3
485    0
519    3
Name: FTR, dtype: object
1.2
15
11.0
Sociedad - visitante
327    3
363    3
375    1
386    1
401    3
421    1
440    0
471    0
490    3
497    0
Name: FTR, dtype: object
1.5
Betis - local
327    0
362    0
368    3
396    0
417    3
434    0
450    3
478    1
491    3
520    1
Name: FTR, dtype: object
1.4
16
13.9
Elche - visitante
329     3
351     3
2283    1
2301    0
2312    3
2338    0
2354    3
2370    1
2391    0
2410    1
Name: FTR, dtype: object
1.5
Alaves - local
329    0
340    3
365    1
376    0
389    0
402    1
436    0
454    0
471    3
500    1
Name: FTR, dtype: object
0.9
4
9.2
Barcelona - visitante
333    0
347    3
389    3
408    3
422    3
447    1
467    1
483    3
501    0
530    3
Name: FTR, dtype: object
2.0
Osasuna - local
324    3
341    3
361    0
381    1
409    3
423    1
446    3
472    0
495    3
515    0
Name: FTR, dtype: object
1.7
11
11.3
Ath Madrid - visitante
335    3
353    1
394    3
418    1
437    1
457    3
472    3
482    1
503    1
529    1
Name: FTR, dtype: object
1.8
Ath Bilbao - local
331    3
349    0
398    0
412    0
425    0
448    3
465    3
482    1
504    3
522    0
Name: FTR, dtype: object
1.3
9
12.1
Sevilla - visitante
336    0
337    1
358    3
391    1
412    3
438    3
459    1
479    1
498    1
512    3
Name: FTR, dtype: object
1.7
Real Madrid - local
334    0
350    3
392    3
410    3
430    3
452    3
470    3
481    3
501    3
521    1
Name: FTR, dtype: object
2.5
18
13.4
Huesca - visitante
318    0
344    1
364    1
374    1
776    0
791    1
815    1
831    1
853    0
875    0
Name: FTR, dtype: object
0.6
Eibar - local
332    1
351    0
360    0
379    1
399    3
414    1
432    0
451    3
474    1
490    0
Name: FTR, dtype: object
1.0
8
10.4
Cadiz - visitante
334    3
349    3
369    3
Name: FTR, dtype: object
3.0
Levante - local
339    0
382    3
405    0
421    1
444    3
457    0
479    1
493    1
516    3
538    3
Name: FTR, dtype: object
1.5
12
9.8
Celta - visitante
341    0
357    1
379    1
385    1
409    0
439    0
453    3
473    1
496    1
506    1
Name: FTR, dtype: object
0.9
Sociedad - local
343    3
355    0
366    1
391    1
411    0
431    3
453    0
460    0
480    1
510    3
Name: FTR, dtype: object
1.2
10
11.5
Huesca - visitante
344    1
364    1
374    1
776    0
791    1
815    1
831    1
853    0
875    0
899    1
Name: FTR, dtype: object
0.7
Getafe - local
333    3
354    3
371    3
394    0
416    0
440    3
464    1
477    1
496    1
512    0
Name: FTR, dtype: object
1.5
9
11.4
Granada - visitante
338    1
359    0
393    3
411    3
436    3
458    1
478    1
493    1
515    3
535    0
Name: FTR, dtype: object
1.6
Cadiz - local
338    1
358    0
377    0
Name: FTR, dtype: object
0.3333333333333333
2
12.666666666666666
Villarreal - visitante
345    1
356    0
392    0
416    3
434    3
469    3
485    3
504    0
511    0
536    1
Name: FTR, dtype: object
1.4
Valladolid - local
346    0
357    1
375    1
388    3
408    0
427    3
433    1
456    1
473    1
494    0
Name: FTR, dtype: object
1.1
8
10.4
Alaves - visitante
352    0
367    0
396    3
410    0
427    0
445    0
462    0
486    0
507    1
528    0
Name: FTR, dtype: object
0.4
Ath Madrid - local
345    1
359    3
386    1
407    3
429    3
445    3
463    3
498    1
511    3
535    3
Name: FTR, dtype: object
2.4
20
13.3
Betis - visitante
342    3
354    0
376    3
388    0
407    0
428    1
444    0
465    0
489    0
508    0
Name: FTR, dtype: object
0.7
Sevilla - local
348    3
380    3
403    3
420    3
449    1
467    1
489    3
505    3
524    1
542    1
Name: FTR, dtype: object
2.2
14
13.4
Eibar - visitante
346    3
372    0
387    0
406    3
420    0
442    3
464    1
481    0
518    0
539    0
Name: FTR, dtype: object
1.0
Osasuna - local
341    3
361    0
381    1
409    3
423    1
446    3
472    0
495    3
515    0
532    0
Name: FTR, dtype: object
1.4
11
12.0
Ath Bilbao - visitante
340    0
360    3
378    0
384    0
405    3
435    3
455    0
474    1
494    3
514    0
Name: FTR, dtype: object
1.3
Barcelona - local
337    1
356    3
397    0
415    3
437    1
455    3
475    3
497    3
518    3
527    3
Name: FTR, dtype: object
2.3
20
13.5
Real Madrid - visitante
339    3
362    3
366    1
383    1
400    3
425    3
441    3
460    3
491    0
516    0
Name: FTR, dtype: object
2.0
Elche - local
344     1
363     0
2297    0
2324    3
2340    3
2361    0
2389    0
2407    3
2423    0
2440    3
Name: FTR, dtype: object
1.3
10
9.8
Valencia - visitante
330    0
355    3
370    0
380    0
404    0
426    1
443    0
451    0
470    0
500    1
Name: FTR, dtype: object
0.5
Betis - local
362    0
368    3
396    0
417    3
434    0
450    3
478    1
491    3
520    1
530    0
Name: FTR, dtype: object
1.4
18
13.9
Sociedad - visitante
363    3
375    1
386    1
401    3
421    1
440    0
471    0
490    3
497    0
545    0
Name: FTR, dtype: object
1.2
Huesca - local
353    1
369    0
765    3
782    0
808    3
827    1
844    1
867    0
887    3
900    0
Name: FTR, dtype: object
1.2
12
11.9
Valladolid - visitante
350    0
368    0
399    0
419    0
449    1
463    0
484    3
510    0
525    0
547    3
Name: FTR, dtype: object
0.7
Alaves - local
340    3
365    1
376    0
389    0
402    1
436    0
454    0
471    3
500    1
514    3
Name: FTR, dtype: object
1.2
6
8.3
Elche - visitante
351     3
2283    1
2301    0
2312    3
2338    0
2354    3
2370    1
2391    0
2410    1
2430    3
Name: FTR, dtype: object
1.5
Villarreal - local
352    3
372    3
374    1
387    3
401    0
422    0
443    3
459    1
476    3
492    0
Name: FTR, dtype: object
1.7
18
12.0
Valencia - visitante
355    3
370    0
380    0
404    0
426    1
443    0
451    0
470    0
500    1
517    0
Name: FTR, dtype: object
0.5
Ath Bilbao - local
349    0
398    0
412    0
425    0
448    3
465    3
482    1
504    3
522    0
543    0
Name: FTR, dtype: object
1.0
7
11.5
Levante - visitante
348    0
361    3
373    0
395    3
413    0
433    1
466    3
487    1
509    0
526    0
Name: FTR, dtype: object
1.1
Eibar - local
351    0
360    0
379    1
399    3
414    1
432    0
451    3
474    1
490    0
499    0
Name: FTR, dtype: object
0.9
9
10.7
Osasuna - visitante
371    0
377    3
397    3
417    0
432    3
454    3
461    0
480    1
505    0
522    3
Name: FTR, dtype: object
1.6
Getafe - local
354    3
371    3
394    0
416    0
440    3
464    1
477    1
496    1
512    0
537    3
Name: FTR, dtype: object
1.5
11
12.7
Barcelona - visitante
347    3
389    3
408    3
422    3
447    1
467    1
483    3
501    0
530    3
557    0
Name: FTR, dtype: object
2.0
Real Madrid - local
350    3
392    3
410    3
430    3
452    3
470    3
481    3
501    3
521    1
548    3
Name: FTR, dtype: object
2.8
19
13.6
Cadiz - visitante
349    3
369    3
Name: FTR, dtype: object
3.0
Celta - local
347    0
370    3
395    0
418    1
428    1
447    1
462    3
485    0
519    3
531    3
Name: FTR, dtype: object
1.5
17
10.8
Ath Madrid - visitante
353    1
394    3
418    1
437    1
457    3
472    3
482    1
503    1
529    1
548    0
Name: FTR, dtype: object
1.5
Granada - local
367    3
378    3
384    3
400    0
426    1
442    0
469    0
488    3
506    1
525    3
Name: FTR, dtype: object
1.7
16
11.8
Sevilla - visitante
337    1
358    3
391    1
412    3
438    3
459    1
479    1
498    1
512    3
531    0
Name: FTR, dtype: object
1.7
Barcelona - local
356    3
397    0
415    3
437    1
455    3
475    3
497    3
518    3
527    3
540    3
Name: FTR, dtype: object
2.5
21
14.6
Sevilla - visitante
358    3
391    1
412    3
438    3
459    1
479    1
498    1
512    3
531    0
567    0
Name: FTR, dtype: object
1.6
Cadiz - local
358    0
377    0
Name: FTR, dtype: object
0.0
1
12.0
Granada - visitante
359    0
393    3
411    3
436    3
458    1
478    1
493    1
515    3
535    0
555    0

Name: FTR, dtype: object
1.5
Levante - local
382    3
405    0
421    1
444    3
457    0
479    1
493    1
516    3
538    3
568    0
Name: FTR, dtype: object
1.5
12
10.7
Real Madrid - visitante
362    3
366    1
383    1
400    3
425    3
441    3
460    3
491    0
516    0
532    3
Name: FTR, dtype: object
2.0
Alaves - local
365    1
376    0
389    0
402    1
436    0
454    0
471    3
500    1
514    3
539    3
Name: FTR, dtype: object
1.2
7
8.4
Ath Bilbao - visitante
360    3
378    0
384    0
405    3
435    3
455    0
474    1
494    3
514    0
533    0
Name: FTR, dtype: object
1.3
Osasuna - local
361    0
381    1
409    3
423    1
446    3
472    0
495    3
515    0
532    0
559    3
Name: FTR, dtype: object
1.4
11
12.1
Celta - visitante
357    1
379    1
385    1
409    0
439    0
453    3
473    1
496    1
506    1
521    1
Name: FTR, dtype: object
1.0
Valencia - local
364    1
373    3
390    3
419    3
435    0
461    3
487    1
508    3
529    1
546    3
Name: FTR, dtype: object
2.1
16
9.5
Betis - visitante
354    0
376    3
388    0
407    0
428    1
444    0
465    0
489    0
508    0
523    1
Name: FTR, dtype: object
0.5
Sociedad - local
355    0
366    1
391    1
411    0
431    3
453    0
460    0
480    1
510    3
517    3
Name: FTR, dtype: object
1.2
10
12.3
Getafe - visitante
365    1
382    0
402    1
423    1
430    0
456    1
488    0
502    3
527    0
543    3
Name: FTR, dtype: object
1.0
Elche - local
363     0
2297    0
2324    3
2340    3
2361    0
2389    0
2407    3
2423    0
2440    3
2468    0
Name: FTR, dtype: object
1.2
10
10.2
Huesca - visitante
364    1
374    1
776    0
791    1
815    1
831    1
853    0
875    0
899    1
915    3
Name: FTR, dtype: object
0.9
Ath Madrid - local
359    3
386    1
407    3
429    3
445    3
463    3
498    1
511    3
535    3
554    1
Name: FTR, dtype: object
2.4
20
13.3
Villarreal - visitante
356    0
392    0
416    3
434    3
469    3
485    3
504    0
511    0
536    1
556    3
Name: FTR, dtype: object
1.6
Valladolid - local
357    1
375    1
388    3
408    0
427    3
433    1
456    1
473    1
494    0
513    3
Name: FTR, dtype: object
1.4
9
11.6
Eibar - visitante
372    0
387    0
406    3
420    0
442    3
464    1
481    0
518    0
539    0
553    1
Name: FTR, dtype: object
0.8
Celta - local
370    3
395    0
418    1
428    1
447    1
462    3
485    0
519    3
531    3
553    1
Name: FTR, dtype: object
1.6
17
11.6
Barcelona - visitante
389    3
408    3
422    3
447    1
467    1
483    3
501    0
530    3
557    0
574    1
Name: FTR, dtype: object
1.8
Sevilla - local
380    3
403    3
420    3
449    1
467    1
489    3
505    3
524    1
542    1
555    3
Name: FTR, dtype: object
2.2
15
13.0
Levante - visitante
361    3
373    0
395    3
413    0
433    1
466    3
487    1
509    0
526    0
540    0
Name: FTR, dtype: object
1.1
Ath Bilbao - local
398    0
412    0
425    0
448    3
465    3
482    1
504    3
522    0
543    0
561    1
Name: FTR, dtype: object
1.1
8
12.4
Cadiz - visitante
369    3
Name: FTR, dtype: object
3.0
Real Madrid - local
392    3
410    3
430    3
452    3
470    3
481    3
501    3
521    1
548    3
567    3
Name: FTR, dtype: object
2.8
20
13.4
Valladolid - visitante
368    0
399    0
419    0
449    1
463    0
484    3
510    0
525    0
547    3
566    1
Name: FTR, dtype: object
0.8
Eibar - local
360    0
379    1
399    3
414    1
432    0
451    3
474    1
490    0
499    0
509    3
Name: FTR, dtype: object
1.2
12
10.8
Elche - visitante
2283    1
2301    0
2312    3
2338    0
2354    3
2370    1
2391    0
2410    1
2430    3
2457    0
Name: FTR, dtype: object
1.2
Villarreal - local
372    3
374    1
387    3
401    0
422    0
443    3
459    1
476    3
492    0
526    3
Name: FTR, dtype: object
1.7
17
12.4
Alaves - visitante
367    0
396    3
410    0
427    0
445    0
462    0
486    0
507    1
528    0
542    1
Name: FTR, dtype: object
0.5
Huesca - local
369    0
765    3
782    0
808    3
827    1
844    1
867    0
887    3
900    0
929    3
Name: FTR, dtype: object
1.4
16
12.1
Ath Madrid - visitante
394    3
418    1
437    1
457    3
472    3
482    1
503    1
529    1
548    0
565    0
Name: FTR, dtype: object
1.4
Getafe - local
371    3
394    0
416    0
440    3
464    1
477    1
496    1
512    0
537    3
552    3
Name: FTR, dtype: object
1.5
9
12.6
Betis - visitante
376    3
388    0
407    0
428    1
444    0
465    0
489    0
508    0
523    1
544    1
Name: FTR, dtype: object
0.6
Sociedad - local
366    1
391    1
411    0
431    3
453    0
460    0
480    1
510    3
517    3
533    3
Name: FTR, dtype: object
1.5
12
12.6
Valencia - visitante
370    0
380    0
404    0
426    1
443    0
451    0
470    0
500    1
517    0
537    0
Name: FTR, dtype: object
0.2
Barcelona - local
397    0
415    3
437    1
455    3
475    3
497    3
518    3
527    3
540    3
560    3
Name: FTR, dtype: object
2.5
18
14.7
Villarreal - visitante
392    0
416    3
434    3
469    3
485    3
504    0
511    0
536    1
556    3
572    3
Name: FTR, dtype: object
1.9
Valladolid - local
375    1
388    3
408    0
427    3
433    1
456    1
473    1
494    0
513    3
536    1
Name: FTR, dtype: object
1.4
9
11.4
Celta - visitante
379    1
385    1
409    0
439    0
453    3
473    1
496    1
506    1
521    1
546    0
Name: FTR, dtype: object
0.9
Cadiz - local
377    0
Name: FTR, dtype: object
0.0
0
12.0
Sevilla - visitante
391    1
412    3
438    3
459    1
479    1
498    1
512    3
531    0
567    0
588    3
Name: FTR, dtype: object
1.6
Ath Madrid - local
386    1
407    3
429    3
445    3
463    3
498    1
511    3
535    3
554    1
575    3
Name: FTR, dtype: object
2.4
16
13.3
Granada - visitante
393    3
411    3
436    3
458    1
478    1
493    1
515    3
535    0
555    0
560    0
Name: FTR, dtype: object
1.5
Eibar - local
379    1
399    3
414    1
432    0
451    3
474    1
490    0
499    0
509    3
544    1
Name: FTR, dtype: object
1.3
12
10.9
Ath Bilbao - visitante
378    0
384    0
405    3
435    3
455    0
474    1
494    3
514    0
533    0
558    1
Name: FTR, dtype: object
1.1
Osasuna - local
381    1
409    3
423    1
446    3
472    0
495    3
515    0
532    0
559    3
566    1
Name: FTR, dtype: object
1.5
10
13.3
Levante - visitante
373    0
395    3
413    0
433    1
466    3
487    1
509    0
526    0
540    0
559    0
Name: FTR, dtype: object
0.8
Betis - local
368    3
396    0
417    3
434    0
450    3
478    1
491    3
520    1
530    0
563    3
Name: FTR, dtype: object
1.7
19
13.8
Real Madrid - visitante
366    1
383    1
400    3
425    3
441    3
460    3
491    0
516    0
532    3
550    3
Name: FTR, dtype: object
2.0
Elche - local
2297    0
2324    3
2340    3
2361    0
2389    0
2407    3
2423    0
2440    3
2468    0
2474    3
Name: FTR, dtype: object
1.5
11
11.2
Sociedad - visitante
375    1
386    1
401    3
421    1
440    0
471    0
490    3
497    0
545    0
563    0
Name: FTR, dtype: object
0.9
Valencia - local
373    3
390    3
419    3
435    0
461    3
487    1
508    3
529    1
546    3
557    3
Name: FTR, dtype: object
2.3
17
9.8
Huesca - visitante
374    1
776    0
791    1
815    1
831    1
853    0
875    0
899    1
915    3
932    1
Name: FTR, dtype: object
0.9
Alaves - local
376    0
389    0
402    1
436    0
454    0
471    3
500    1
514    3
539    3
556    0
Name: FTR, dtype: object
1.1
8
8.7
Getafe - visitante
382    0
402    1
423    1
430    0
456    1
488    0
502    3
527    0
543    3
569    3
Name: FTR, dtype: object
1.2
Sociedad - local
391    1
411    0
431    3
453    0
460    0
480    1
510    3
517    3
533    3
551    3
Name: FTR, dtype: object
1.7
15
13.4
Real Madrid - visitante
383    1
400    3
425    3
441    3
460    3
491    0
516    0
532    3
550    3
576    3
Name: FTR, dtype: object
2.2
Granada - local
378    3
384    3
400    0
426    1
442    0
469    0
488    3
506    1
525    3
549    3
Name: FTR, dtype: object
1.7
16
11.6
Alaves - visitante
396    3
410    0
427    0
445    0
462    0
486    0
507    1
528    0
542    1
568    3
Name: FTR, dtype: object
0.8
Betis - local
396    0
417    3
434    0
450    3
478    1
491    3
520    1
530    0
563    3
582    0
Name: FTR, dtype: object
1.4
18
13.7
Valladolid - visitante
399    0
419    0
449    1
463    0
484    3
510    0
525    0
547    3
566    1
595    0
Name: FTR, dtype: object
0.8
Huesca - local
765    3
782    0
808    3
827    1
844    1
867    0
887    3
900    0
929    3
947    0
Name: FTR, dtype: object
1.4
16
13.1
Cadiz - visitante
Series([], Name: FTR, dtype: object)
0.0
Celta - local
395    0
418    1
428    1
447    1
462    3
485    0
519    3
531    3
553    1
570    1
Name: FTR, dtype: object
1.4
16
11.3
Valencia - visitante
380    0
404    0
426    1
443    0
451    0
470    0
500    1
517    0
537    0
564    0
Name: FTR, dtype: object
0.2
Getafe - local
394    0
416    0
440    3
464    1
477    1
496    1
512    0
537    3
552    3
576    0
Name: FTR, dtype: object
1.2
8
13.4
Osasuna - visitante
377    3
397    3
417    0
432    3
454    3
461    0
480    1
505    0
522    3
541    0
Name: FTR, dtype: object
1.6
Villarreal - local
374    1
387    3
401    0
422    0
443    3
459    1
476    3
492    0
526    3
541    3
Name: FTR, dtype: object
1.7
18
11.9
Eibar - visitante
387    0
406    3
420    0
442    3
464    1
481    0
518    0
539    0
553    1
577    0
Name: FTR, dtype: object
0.8
Valencia - local
390    3
419    3
435    0
461    3
487    1
508    3
529    1
546    3
557    3
577    3
Name: FTR, dtype: object
2.3
14
9.3
Levante - visitante
395    3
413    0
433    1
466    3
487    1
509    0
526    0
540    0
559    0
575    0
Name: FTR, dtype: object
0.8
Villarreal - local
387    3
401    0
422    0
443    3
459    1
476    3
492    0
526    3
541    3
562    0
Name: FTR, dtype: object
1.6
18
12.5
Huesca - visitante
776    0
791    1
815    1
831    1
853    0
875    0
899    1
915    3
932    1
957    0
Name: FTR, dtype: object
0.8
Valladolid - local
388    3
408    0
427    3
433    1
456    1
473    1
494    0
513    3
536    1
550    0
Name: FTR, dtype: object
1.3
8
11.0
Sociedad - visitante
386    1
401    3
421    1
440    0
471    0
490    3
497    0
545    0
563    0
583    3
Name: FTR, dtype: object
1.1
Alaves - local
389    0
402    1
436    0
454    0
471    3
500    1
514    3
539    3
556    0
571    1
Name: FTR, dtype: object
1.2
9
8.6
Betis - visitante
388    0
407    0
428    1
444    0
465    0
489    0
508    0
523    1
544    1
552    0
Name: FTR, dtype: object
0.3
Cadiz - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Osasuna - visitante
397    3
417    0
432    3
454    3
461    0
480    1
505    0
522    3
541    0
570    1
Name: FTR, dtype: object
1.4
Granada - local
384    3
400    0
426    1
442    0
469    0
488    3
506    1
525    3
549    3
573    3
Name: FTR, dtype: object
1.7
15
11.9
Ath Bilbao - visitante
384    0
405    3
435    3
455    0
474    1
494    3
514    0
533    0
558    1
578    1
Name: FTR, dtype: object
1.2
Eibar - local
399    3
414    1
432    0
451    3
474    1
490    0
499    0
509    3
544    1
565    3
Name: FTR, dtype: object
1.5
14
11.0
Celta - visitante
385    1
409    0
439    0
453    3
473    1
496    1
506    1
521    1
546    0
561    1
Name: FTR, dtype: object
0.9
Sevilla - local
403    3
420    3
449    1
467    1
489    3
505    3
524    1
542    1
555    3
578    1
Name: FTR, dtype: object
2.0
15
12.3
Valencia - visitante
404    0
426    1
443    0
451    0
470    0
500    1
517    0
537    0
564    0
585    1
Name: FTR, dtype: object
0.3
Osasuna - local
409    3
423    1
446    3
472    0
495    3
515    0
532    0
559    3
566    1
583    0
Name: FTR, dtype: object
1.4
11
14.0
Mallorca - visitante
403    0
429    0
448    0
452    0
476    0
499    3
520    1
534    0
551    0
573    0
Name: FTR, dtype: object
0.4

Levante - local
405    0
421    1
444    3
457    0
479    1
493    1
516    3
538    3
568    0
581    3
Name: FTR, dtype: object
1.5
14
10.7
Getafe - visitante
402    1
423    1
430    0
456    1
488    0
502    3
527    0
543    3
569    3
586    0
Name: FTR, dtype: object
1.2
Leganes - local
404    3
438    0
458    1
484    0
507    1
523    1
545    3
569    0
584    3
602    3
Name: FTR, dtype: object
1.5
10
11.5
Real Madrid - visitante
400    3
425    3
441    3
460    3
491    0
516    0
532    3
550    3
576    3
590    1
Name: FTR, dtype: object
2.2
Granada - local
400    0
426    1
442    0
469    0
488    3
506    1
525    3
549    3
573    3
599    0
Name: FTR, dtype: object
1.4
12
12.6
Ath Bilbao - visitante
405    3
435    3
455    0
474    1
494    3
514    0
533    0
558    1
578    1
580    1
Name: FTR, dtype: object
1.3
Espanol - local
406    0
424    0
441    0
466    0
486    3
503    1
534    3
558    1
574    1
593    1
Name: FTR, dtype: object
1.0
10
11.2
Celta - visitante
409    0
439    0
453    3
473    1
496    1
506    1
521    1
546    0
561    1
581    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
407    3
429    3
445    3
463    3
498    1
511    3
535    3
554    1
575    3
596    3
Name: FTR, dtype: object
2.6
17
14.6
Sociedad - visitante
401    3
421    1
440    0
471    0
490    3
497    0
545    0
563    0
583    3
603    1
Name: FTR, dtype: object
1.1
Villarreal - local
401    0
422    0
443    3
459    1
476    3
492    0
526    3
541    3
562    0
586    3
Name: FTR, dtype: object
1.6
15
12.4
Eibar - visitante
406    3
420    0
442    3
464    1
481    0
518    0
539    0
553    1
577    0
597    1
Name: FTR, dtype: object
0.9
Valladolid - local
408    0
427    3
433    1
456    1
473    1
494    0
513    3
536    1
550    0
579    1
Name: FTR, dtype: object
1.1
8
11.1
Betis - visitante
407    0
428    1
444    0
465    0
489    0
508    0
523    1
544    1
552    0
571    1
Name: FTR, dtype: object
0.4
Alaves - local
402    1
436    0
454    0
471    3
500    1
514    3
539    3
556    0
571    1
600    1
Name: FTR, dtype: object
1.3
10
8.8
Barcelona - visitante
408    3
422    3
447    1
467    1
483    3
501    0
530    3
557    0
574    1
598    1
Name: FTR, dtype: object
1.6
Valencia - local
419    3
435    0
461    3
487    1
508    3
529    1
546    3
557    3
577    3
591    1
Name: FTR, dtype: object
2.1
14
9.3
Espanol - visitante
415    0
431    0
450    0
477    1
495    0
513    0
524    1
549    0
562    3
584    0
Name: FTR, dtype: object
0.5
Sociedad - local
411    0
431    3
453    0
460    0
480    1
510    3
517    3
533    3
551    3
572    0
Name: FTR, dtype: object
1.6
16
13.3
Sevilla - visitante
412    3
438    3
459    1
479    1
498    1
512    3
531    0
567    0
588    3
601    1
Name: FTR, dtype: object
1.6
Real Madrid - local
410    3
430    3
452    3
470    3
481    3
501    3
521    1
548    3
567    3
580    1
Name: FTR, dtype: object
2.6
18
14.2
Villarreal - visitante
416    3
434    3
469    3
485    3
504    0
511    0
536    1
556    3
572    3
592    3
Name: FTR, dtype: object
2.2
Mallorca - local
413    3
439    3
468    1
483    0
502    0
528    3
547    0
564    3
588    0
617    0
Name: FTR, dtype: object
1.3
14
11.5
Granada - visitante
411    3
436    3
458    1
478    1
493    1
515    3
535    0
555    0
560    0
589    0
Name: FTR, dtype: object
1.2
Getafe - local
416    0
440    3
464    1
477    1
496    1
512    0
537    3
552    3
576    0
595    3
Name: FTR, dtype: object
1.5
10
12.6
Ath Madrid - visitante
418    1
437    1
457    3
472    3
482    1
503    1
529    1
548    0
565    0
582    3
Name: FTR, dtype: object
1.4
Celta - local
418    1
428    1
447    1
462    3
485    0
519    3
531    3
553    1
570    1
594    1
Name: FTR, dtype: object
1.5
16
11.5
Levante - visitante
413    0
433    1
466    3
487    1
509    0
526    0
540    0
559    0
575    0
599    3
Name: FTR, dtype: object
0.8
Betis - local
417    3
434    0
450    3
478    1
491    3
520    1
530    0
563    3
582    0
604    3
Name: FTR, dtype: object
1.7
20
13.3
Alaves - visitante
410    0
427    0
445    0
462    0
486    0
507    1
528    0
542    1
568    3
587    0
Name: FTR, dtype: object
0.5
Barcelona - local
415    3
437    1
455    3
475    3
497    3
518    3
527    3
540    3
560    3
587    3
Name: FTR, dtype: object
2.8
21
13.6
Osasuna - visitante
417    0
432    3
454    3
461    0
480    1
505    0
522    3
541    0
570    1
596    0
Name: FTR, dtype: object
1.1
Ath Bilbao - local
412    0
425    0
448    3
465    3
482    1
504    3
522    0
543    0
561    1
597    1
Name: FTR, dtype: object
1.2
8
12.2
Leganes - visitante
414    1
424    3
446    0
468    1
475    0
492    3
519    0
538    0
554    1
579    1
Name: FTR, dtype: object
1.0
Eibar - local
414    1
432    0
451    3
474    1
490    0
499    0
509    3
544    1
565    3
589    3
Name: FTR, dtype: object
1.5
14
11.8
Valladolid - visitante
419    0
449    1
463    0
484    3
510    0
525    0
547    3
566    1
595    0
620    1
Name: FTR, dtype: object
0.9
Granada - local
426    1
442    0
469    0
488    3
506    1
525    3
549    3
573    3
599    0
608    3
Name: FTR, dtype: object
1.7
14
12.6
Real Madrid - visitante
425    3
441    3
460    3
491    0
516    0
532    3
550    3
576    3
590    1
591    1
Name: FTR, dtype: object
2.0
Villarreal - local
422    0
443    3
459    1
476    3
492    0
526    3
541    3
562    0
586    3
610    1
Name: FTR, dtype: object
1.7
14
13.8
Sociedad - visitante
421    1
440    0
471    0
490    3
497    0
545    0
563    0
583    3
603    1
626    0
Name: FTR, dtype: object
0.8
Alaves - local
436    0
454    0
471    3
500    1
514    3
539    3
556    0
571    1
600    1
619    0
Name: FTR, dtype: object
1.2
11
9.3
Getafe - visitante
423    1
430    0
456    1
488    0
502    3
527    0
543    3
569    3
586    0
605    3
Name: FTR, dtype: object
1.4
Sevilla - local
420    3
449    1
467    1
489    3
505    3
524    1
542    1
555    3
578    1
592    0
Name: FTR, dtype: object
1.7
14
13.3
Mallorca - visitante
429    0
448    0
452    0
476    0
499    3
520    1
534    0
551    0
573    0
594    1
Name: FTR, dtype: object
0.5
Leganes - local
438    0
458    1
484    0
507    1
523    1
545    3
569    0
584    3
602    3
629    0
Name: FTR, dtype: object
1.2
10
11.4
Valencia - visitante
426    1
443    0
451    0
470    0
500    1
517    0
537    0
564    0
585    1
607    3
Name: FTR, dtype: object
0.6
Levante - local
421    1
444    3
457    0
479    1
493    1
516    3
538    3
568    0
581    3
607    0
Name: FTR, dtype: object
1.5
15
11.9
Ath Bilbao - visitante
435    3
455    0
474    1
494    3
514    0
533    0
558    1
578    1
580    1
604    0
Name: FTR, dtype: object
1.0
Espanol - local
424    0
441    0
466    0
486    3
503    1
534    3
558    1
574    1
593    1
613    0
Name: FTR, dtype: object
1.0
12
11.0
Eibar - visitante
420    0
442    3
464    1
481    0
518    0
539    0
553    1
577    0
597    1
618    0
Name: FTR, dtype: object
0.6
Ath Madrid - local
429    3
445    3
463    3
498    1
511    3
535    3
554    1
575    3
596    3
611    0
Name: FTR, dtype: object
2.3
16
15.4
Betis - visitante
428    1
444    0
465    0
489    0
508    0
523    1
544    1
552    0
571    1
593    1
Name: FTR, dtype: object
0.5
Valladolid - local
427    3
433    1
456    1
473    1
494    0
513    3
536    1
550    0
579    1
585    1
Name: FTR, dtype: object
1.2
9
11.2
Barcelona - visitante
422    3
447    1
467    1
483    3
501    0
530    3
557    0
574    1
598    1
611    3
Name: FTR, dtype: object
1.6
Osasuna - local
423    1
446    3
472    0
495    3
515    0
532    0
559    3
566    1
583    0
601    1
Name: FTR, dtype: object
1.2
10
13.5
Celta - visitante
439    0
453    3
473    1
496    1
506    1
521    1
546    0
561    1
581    0
602    0
Name: FTR, dtype: object
0.8
Real Madrid - local
430    3
452    3
470    3
481    3
501    3
521    1
548    3
567    3
580    1
609    3
Name: FTR, dtype: object
2.6
18
14.2
Alaves - visitante
427    0
445    0
462    0
486    0
507    1
528    0
542    1
568    3
587    0
608    0
Name: FTR, dtype: object
0.5
Sociedad - local
431    3
453    0
460    0
480    1
510    3
517    3
533    3
551    3
572    0
598    1
Name: FTR, dtype: object
1.7
16
13.3
Granada - visitante
436    3
458    1
478    1
493    1
515    3
535    0
555    0
560    0
589    0
614    0
Name: FTR, dtype: object
0.9
Ath Bilbao - local
425    0
448    3
465    3
482    1
504    3
522    0
543    0
561    1
597    1
614    3
Name: FTR, dtype: object
1.5
9
12.3
Sevilla - visitante
438    3
459    1
479    1
498    1
512    3
531    0
567    0
588    3
601    1
621    3
Name: FTR, dtype: object
1.6
Mallorca - local
439    3
468    1
483    0
502    0
528    3
547    0
564    3
588    0
617    0
635    3
Name: FTR, dtype: object
1.3
15
10.5
Levante - visitante
433    1
466    3
487    1
509    0
526    0
540    0
559    0
575    0
599    3
612    0
Name: FTR, dtype: object
0.8
Eibar - local
432    0
451    3
474    1
490    0
499    0
509    3
544    1
565    3
589    3
605    0
Name: FTR, dtype: object
1.4
14
12.0
Leganes - visitante
424    3
446    0
468    1
475    0
492    3
519    0
538    0
554    1
579    1
600    1
Name: FTR, dtype: object
1.0
Barcelona - local
437    1
455    3
475    3
497    3
518    3
527    3
540    3
560    3
587    3
590    1
Name: FTR, dtype: object
2.6
20
13.6
Espanol - visitante
431    0
450    0
477    1
495    0
513    0
524    1
549    0
562    3
584    0
609    0
Name: FTR, dtype: object
0.5
Getafe - local
440    3
464    1
477    1
496    1
512    0
537    3
552    3
576    0
595    3
612    3
Name: FTR, dtype: object
1.8
13
13.4
Villarreal - visitante
434    3
469    3
485    3
504    0
511    0
536    1
556    3
572    3
592    3
616    0
Name: FTR, dtype: object
1.9
Betis - local
434    0
450    3
478    1
491    3
520    1
530    0
563    3
582    0
604    3
628    3
Name: FTR, dtype: object
1.7
19
14.4
Osasuna - visitante
432    3
454    3
461    0
480    1
505    0
522    3
541    0
570    1
596    0
613    3
Name: FTR, dtype: object
1.4
Celta - local
428    1
447    1
462    3
485    0
519    3
531    3
553    1
570    1
594    1
620    1
Name: FTR, dtype: object
1.5
15
11.9
Ath Madrid - visitante
437    1
457    3
472    3
482    1
503    1
529    1
548    0
565    0
582    3
610    1
Name: FTR, dtype: object
1.4
Valencia - local
435    0
461    3
487    1
508    3
529    1
546    3
557    3
577    3
591    1
616    3
Name: FTR, dtype: object
2.1
14
9.6
Valladolid - visitante
449    1
463    0
484    3
510    0
525    0
547    3
566    1
595    0
620    1
639    0
Name: FTR, dtype: object
0.9
Sevilla - local
449    1
467    1
489    3
505    3
524    1
542    1
555    3
578    1
592    0
615    3
Name: FTR, dtype: object
1.7
14
14.1
Eibar - visitante
442    3
464    1
481    0
518    0
539    0
553    1
577    0
597    1
618    0
642    3
Name: FTR, dtype: object
0.9
Levante - local
444    3
457    0
479    1
493    1
516    3
538    3
568    0
581    3
607    0
630    3
Name: FTR, dtype: object
1.7
16
12.3
Sociedad - visitante
440    0
471    0
490    3
497    0
545    0
563    0
583    3
603    1
626    0
641    3
Name: FTR, dtype: object
1.0
Villarreal - local
443    3
459    1
476    3
492    0
526    3
541    3
562    0
586    3
610    1
622    0
Name: FTR, dtype: object
1.7
14
14.2
Barcelona - visitante
447    1
467    1
483    3
501    0
530    3
557    0
574    1
598    1
611    3
629    3
Name: FTR, dtype: object
1.6
Osasuna - local
446    3
472    0
495    3
515    0
532    0
559    3
566    1
583    0
601    1
624    0
Name: FTR, dtype: object
1.1
11
14.1
Getafe - visitante
430    0
456    1
488    0
502    3
527    0
543    3
569    3
586    0
605    3
625    1
Name: FTR, dtype: object
1.4
Espanol - local
441    0
466    0
486    3
503    1
534    3
558    1
574    1
593    1
613    0
625    1
Name: FTR, dtype: object
1.1
13
10.9
Leganes - visitante
446    0
468    1
475    0
492    3
519    0
538    0
554    1
579    1
600    1
615    0

Name: FTR, dtype: object
0.7
Ath Bilbao - local
448    3
465    3
482    1
504    3
522    0
543    0
561    1
597    1
614    3
634    3
Name: FTR, dtype: object
1.8
11
13.9
Real Madrid - visitante
441    3
460    3
491    0
516    0
532    3
550    3
576    3
590    1
591    1
619    3
Name: FTR, dtype: object
2.0
Granada - local
442    0
469    0
488    3
506    1
525    3
549    3
573    3
599    0
608    3
627    1
Name: FTR, dtype: object
1.7
13
11.8
Valencia - visitante
443    0
451    0
470    0
500    1
517    0
537    0
564    0
585    1
607    3
628    0
Name: FTR, dtype: object
0.5
Valladolid - local
433    1
456    1
473    1
494    0
513    3
536    1
550    0
579    1
585    1
603    1
Name: FTR, dtype: object
1.0
8
11.1
Alaves - visitante
445    0
462    0
486    0
507    1
528    0
542    1
568    3
587    0
608    0
623    3
Name: FTR, dtype: object
0.8
Celta - local
447    1
462    3
485    0
519    3
531    3
553    1
570    1
594    1
620    1
643    0
Name: FTR, dtype: object
1.4
14
12.0
Betis - visitante
444    0
465    0
489    0
508    0
523    1
544    1
552    0
571    1
593    1
617    3
Name: FTR, dtype: object
0.7
Ath Madrid - local
445    3
463    3
498    1
511    3
535    3
554    1
575    3
596    3
611    0
633    3
Name: FTR, dtype: object
2.3
16
15.7
Mallorca - visitante
448    0
452    0
476    0
499    3
520    1
534    0
551    0
573    0
594    1
606    0
Name: FTR, dtype: object
0.5
Real Madrid - local
452    3
470    3
481    3
501    3
521    1
548    3
567    3
580    1
609    3
626    3
Name: FTR, dtype: object
2.6
20
15.2
Getafe - visitante
456    1
488    0
502    3
527    0
543    3
569    3
586    0
605    3
625    1
643    3
Name: FTR, dtype: object
1.7
Sociedad - local
453    0
460    0
480    1
510    3
517    3
533    3
551    3
572    0
598    1
618    3
Name: FTR, dtype: object
1.7
18
13.6
Espanol - visitante
450    0
477    1
495    0
513    0
524    1
549    0
562    3
584    0
609    0
633    0
Name: FTR, dtype: object
0.5
Eibar - local
451    3
474    1
490    0
499    0
509    3
544    1
565    3
589    3
605    0
623    0
Name: FTR, dtype: object
1.4
14
12.7
Osasuna - visitante
454    3
461    0
480    1
505    0
522    3
541    0
570    1
596    0
613    3
632    1
Name: FTR, dtype: object
1.2
Valladolid - local
456    1
473    1
494    0
513    3
536    1
550    0
579    1
585    1
603    1
621    0
Name: FTR, dtype: object
0.9
8
10.3
Levante - visitante
466    3
487    1
509    0
526    0
540    0
559    0
575    0
599    3
612    0
634    0
Name: FTR, dtype: object
0.7
Betis - local
450    3
478    1
491    3
520    1
530    0
563    3
582    0
604    3
628    3
631    0
Name: FTR, dtype: object
1.7
20
15.3
Villarreal - visitante
469    3
485    3
504    0
511    0
536    1
556    3
572    3
592    3
616    0
635    0
Name: FTR, dtype: object
1.6
Valencia - local
461    3
487    1
508    3
529    1
546    3
557    3
577    3
591    1
616    3
638    3
Name: FTR, dtype: object
2.4
16
9.8
Ath Bilbao - visitante
455    0
474    1
494    3
514    0
533    0
558    1
578    1
580    1
604    0
624    3
Name: FTR, dtype: object
1.0
Alaves - local
454    0
471    3
500    1
514    3
539    3
556    0
571    1
600    1
619    0
639    3
Name: FTR, dtype: object
1.5
14
9.6
Granada - visitante
458    1
478    1
493    1
515    3
535    0
555    0
560    0
589    0
614    0
638    0
Name: FTR, dtype: object
0.6
Barcelona - local
455    3
475    3
497    3
518    3
527    3
540    3
560    3
587    3
590    1
606    3
Name: FTR, dtype: object
2.8
23
14.9
Ath Madrid - visitante
457    3
472    3
482    1
503    1
529    1
548    0
565    0
582    3
610    1
627    1
Name: FTR, dtype: object
1.4
Leganes - local
458    1
484    0
507    1
523    1
545    3
569    0
584    3
602    3
629    0
642    0
Name: FTR, dtype: object
1.2
11
11.7
Sevilla - visitante
459    1
479    1
498    1
512    3
531    0
567    0
588    3
601    1
621    3
631    3
Name: FTR, dtype: object
1.6
Mallorca - local
468    1
483    0
502    0
528    3
547    0
564    3
588    0
617    0
635    3
652    1
Name: FTR, dtype: object
1.1
12
10.7
Celta - visitante
453    3
473    1
496    1
506    1
521    1
546    0
561    1
581    0
602    0
622    3
Name: FTR, dtype: object
1.1
Getafe - local
464    1
477    1
496    1
512    0
537    3
552    3
576    0
595    3
612    3
632    1
Name: FTR, dtype: object
1.6
11
13.7
Sociedad - visitante
471    0
490    3
497    0
545    0
563    0
583    3
603    1
626    0
641    3
665    3
Name: FTR, dtype: object
1.3
Espanol - local
466    0
486    3
503    1
534    3
558    1
574    1
593    1
613    0
625    1
650    0
Name: FTR, dtype: object
1.1
14
11.4
Real Madrid - visitante
460    3
491    0
516    0
532    3
550    3
576    3
590    1
591    1
619    3
637    3
Name: FTR, dtype: object
2.0
Granada - local
469    0
488    3
506    1
525    3
549    3
573    3
599    0
608    3
627    1
641    0
Name: FTR, dtype: object
1.7
13
10.9
Eibar - visitante
464    1
481    0
518    0
539    0
553    1
577    0
597    1
618    0
642    3
667    0
Name: FTR, dtype: object
0.6
Villarreal - local
459    1
476    3
492    0
526    3
541    3
562    0
586    3
610    1
622    0
645    1
Name: FTR, dtype: object
1.5
12
13.6
Valencia - visitante
451    0
470    0
500    1
517    0
537    0
564    0
585    1
607    3
628    0
650    3
Name: FTR, dtype: object
0.8
Levante - local
457    0
479    1
493    1
516    3
538    3
568    0
581    3
607    0
630    3
649    3
Name: FTR, dtype: object
1.7
15
12.3
Betis - visitante
465    0
489    0
508    0
523    1
544    1
552    0
571    1
593    1
617    3
647    1
Name: FTR, dtype: object
0.8
Ath Madrid - local
463    3
498    1
511    3
535    3
554    1
575    3
596    3
611    0
633    3
666    3
Name: FTR, dtype: object
2.3
16
15.2
Alaves - visitante
462    0
486    0
507    1
528    0
542    1
568    3
587    0
608    0
623    3
644    0
Name: FTR, dtype: object
0.8
Osasuna - local
472    0
495    3
515    0
532    0
559    3
566    1
583    0
601    1
624    0
644    3
Name: FTR, dtype: object
1.1
13
15.4
Leganes - visitante
468    1
475    0
492    3
519    0
538    0
554    1
579    1
600    1
615    0
640    1
Name: FTR, dtype: object
0.8
Celta - local
462    3
485    0
519    3
531    3
553    1
570    1
594    1
620    1
643    0
665    0
Name: FTR, dtype: object
1.3
12
11.9
Barcelona - visitante
467    1
483    3
501    0
530    3
557    0
574    1
598    1
611    3
629    3
649    0
Name: FTR, dtype: object
1.5
Ath Bilbao - local
465    3
482    1
504    3
522    0
543    0
561    1
597    1
614    3
634    3
656    3
Name: FTR, dtype: object
1.8
11
13.4
Mallorca - visitante
452    0
476    0
499    3
520    1
534    0
551    0
573    0
594    1
606    0
630    0
Name: FTR, dtype: object
0.5
Sevilla - local
467    1
489    3
505    3
524    1
542    1
555    3
578    1
592    0
615    3
648    1
Name: FTR, dtype: object
1.7
14
13.7
Valladolid - visitante
463    0
484    3
510    0
525    0
547    3
566    1
595    0
620    1
639    0
659    0
Name: FTR, dtype: object
0.8
Betis - local
478    1
491    3
520    1
530    0
563    3
582    0
604    3
628    3
631    0
655    3
Name: FTR, dtype: object
1.7
21
15.1
Espanol - visitante
477    1
495    0
513    0
524    1
549    0
562    3
584    0
609    0
633    0
656    0
Name: FTR, dtype: object
0.5
Eibar - local
474    1
490    0
499    0
509    3
544    1
565    3
589    3
605    0
623    0
637    0
Name: FTR, dtype: object
1.1
13
12.7
Valencia - visitante
470    0
500    1
517    0
537    0
564    0
585    1
607    3
628    0
650    3
661    0
Name: FTR, dtype: object
0.8
Real Madrid - local
470    3
481    3
501    3
521    1
548    3
567    3
580    1
609    3
626    3
647    1
Name: FTR, dtype: object
2.4
18
16.0
Mallorca - visitante
476    0
499    3
520    1
534    0
551    0
573    0
594    1
606    0
630    0
646    0
Name: FTR, dtype: object
0.5
Sociedad - local
460    0
480    1
510    3
517    3
533    3
551    3
572    0
598    1
618    3
640    1
Name: FTR, dtype: object
1.8
19
13.4
Celta - visitante
473    1
496    1
506    1
521    1
546    0
561    1
581    0
602    0
622    3
636    0
Name: FTR, dtype: object
0.8
Alaves - local
471    3
500    1
514    3
539    3
556    0
571    1
600    1
619    0
639    3
660    1
Name: FTR, dtype: object
1.6
15
10.2
Osasuna - visitante
461    0
480    1
505    0
522    3
541    0
570    1
596    0
613    3
632    1
652    1
Name: FTR, dtype: object
1.0
Barcelona - local
475    3
497    3
518    3
527    3
540    3
560    3
587    3
590    1
606    3
636    3
Name: FTR, dtype: object
2.8
26
14.1
Ath Bilbao - visitante
474    1
494    3
514    0
533    0
558    1
578    1
580    1
604    0
624    3
645    1
Name: FTR, dtype: object
1.1
Valladolid - local
473    1
494    0
513    3
536    1
550    0
579    1
585    1
603    1
621    0
646    3
Name: FTR, dtype: object
1.1
10
10.9
Getafe - visitante
488    0
502    3
527    0
543    3
569    3
586    0
605    3
625    1
643    3
662    0
Name: FTR, dtype: object
1.6
Levante - local
479    1
493    1
516    3
538    3
568    0
581    3
607    0
630    3
649    3
663    0
Name: FTR, dtype: object
1.7
15
11.8
Ath Madrid - visitante
472    3
482    1
503    1
529    1
548    0
565    0
582    3
610    1
627    1
648    1
Name: FTR, dtype: object
1.2
Leganes - local
484    0
507    1
523    1
545    3
569    0
584    3
602    3
629    0
642    0
668    3
Name: FTR, dtype: object
1.4
12
11.7
Granada - visitante
478    1
493    1
515    3
535    0
555    0
560    0
589    0
614    0
638    0
651    0
Name: FTR, dtype: object
0.5
Villarreal - local
476    3
492    0
526    3
541    3
562    0
586    3
610    1
622    0
645    1
669    3
Name: FTR, dtype: object
1.7
14
14.8
Sevilla - visitante
479    1
498    1
512    3
531    0
567    0
588    3
601    1
621    3
631    3
657    1
Name: FTR, dtype: object
1.6
Sociedad - local
480    1
510    3
517    3
533    3
551    3
572    0
598    1
618    3
640    1
658    0
Name: FTR, dtype: object
1.8
19
14.1
Real Madrid - visitante
491    0
516    0
532    3
550    3
576    3
590    1
591    1
619    3
637    3
675    0
Name: FTR, dtype: object
1.7
Valencia - local
487    1
508    3
529    1
546    3
557    3
577    3
591    1
616    3
638    3
657    1
Name: FTR, dtype: object
2.2
15
10.1
Osasuna - visitante
480    1
505    0
522    3
541    0
570    1
596    0
613    3
632    1
652    1
679    0
Name: FTR, dtype: object
1.0
Celta - local
485    0
519    3
531    3
553    1
570    1
594    1
620    1
643    0
665    0
683    3
Name: FTR, dtype: object
1.3
7
11.7
Alaves - visitante
486    0
507    1
528    0
542    1
568    3
587    0
608    0
623    3
644    0
669    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
498    1
511    3
535    3
554    1
575    3
596    3
611    0
633    3
666    3
677    1
Name: FTR, dtype: object
2.1
16
15.2
Valladolid - visitante
484    3
510    0
525    0
547    3
566    1
595    0
620    1
639    0
659    0
671    1
Name: FTR, dtype: object
0.9
Getafe - local
477    1
496    1
512    0
537    3
552    3
576    0
595    3
612    3
632    1
651    3
Name: FTR, dtype: object
1.8
13
13.6
Eibar - visitante
481    0
518    0
539    0
553    1
577    0
597    1
618    0
642    3
667    0
689    1
Name: FTR, dtype: object
0.6
Ath Bilbao - local
482    1
504    3
522    0
543    0
561    1
597    1
614    3
634    3
656    3
671    1
Name: FTR, dtype: object
1.6
11
14.1
Betis - visitante
489    0
508    0
523    1
544    1
552    0
571    1
593    1
617    3
647    1
664    0
Name: FTR, dtype: object
0.8
Espanol - local
486    3
503    1
534    3
558    1
574    1
593    1
613    0
625    1
650    0
672    0
Name: FTR, dtype: object
1.1
13
12.2
Levante - visitante
487    1
509    0
526    0
540    0
559    0
575    0
599    3
612    0
634    0
658    3
Name: FTR, dtype: object
0.7
Sevilla - local
489    3
505    3
524    1
542    1
555    3
578    1
592    0
615    3
648    1
662    3
Name: FTR, dtype: object
1.9
16
14.4
Barcelona - visitante
483    3
501    0
530    3
557    0
574    1
598    1
611    3
629    3
649    0
678    3

Name: FTR, dtype: object
1.7
Mallorca - local
483    0
502    0
528    3
547    0
564    3
588    0
617    0
635    3
652    1
675    3
Name: FTR, dtype: object
1.3
12
10.5
Leganes - visitante
475    0
492    3
519    0
538    0
554    1
579    1
600    1
615    0
640    1
654    0
Name: FTR, dtype: object
0.7
Granada - local
488    3
506    1
525    3
549    3
573    3
599    0
608    3
627    1
641    0
664    3
Name: FTR, dtype: object
2.0
14
10.8
Villarreal - visitante
485    3
504    0
511    0
536    1
556    3
572    3
592    3
616    0
635    0
653    0
Name: FTR, dtype: object
1.3
Real Madrid - local
481    3
501    3
521    1
548    3
567    3
580    1
609    3
626    3
647    1
654    3
Name: FTR, dtype: object
2.4
20
16.3
Valencia - visitante
500    1
517    0
537    0
564    0
585    1
607    3
628    0
650    3
661    0
677    1
Name: FTR, dtype: object
0.9
Alaves - local
500    1
514    3
539    3
556    0
571    1
600    1
619    0
639    3
660    1
674    3
Name: FTR, dtype: object
1.6
15
9.9
Sociedad - visitante
490    3
497    0
545    0
563    0
583    3
603    1
626    0
641    3
665    3
690    0
Name: FTR, dtype: object
1.3
Osasuna - local
495    3
515    0
532    0
559    3
566    1
583    0
601    1
624    0
644    3
661    3
Name: FTR, dtype: object
1.4
16
16.2
Ath Madrid - visitante
482    1
503    1
529    1
548    0
565    0
582    3
610    1
627    1
648    1
660    1
Name: FTR, dtype: object
1.0
Valladolid - local
494    0
513    3
536    1
550    0
579    1
585    1
603    1
621    0
646    3
667    3
Name: FTR, dtype: object
1.3
12
11.1
Celta - visitante
496    1
506    1
521    1
546    0
561    1
581    0
602    0
622    3
636    0
655    0
Name: FTR, dtype: object
0.7
Eibar - local
490    0
499    0
509    3
544    1
565    3
589    3
605    0
623    0
637    0
653    3
Name: FTR, dtype: object
1.3
13
14.0
Ath Bilbao - visitante
494    3
514    0
533    0
558    1
578    1
580    1
604    0
624    3
645    1
666    0
Name: FTR, dtype: object
1.0
Barcelona - local
497    3
518    3
527    3
540    3
560    3
587    3
590    1
606    3
636    3
659    3
Name: FTR, dtype: object
2.8
29
14.9
Leganes - visitante
492    3
519    0
538    0
554    1
579    1
600    1
615    0
640    1
654    0
676    0
Name: FTR, dtype: object
0.7
Villarreal - local
492    0
526    3
541    3
562    0
586    3
610    1
622    0
645    1
669    3
699    3
Name: FTR, dtype: object
1.7
18
15.5
Mallorca - visitante
499    3
520    1
534    0
551    0
573    0
594    1
606    0
630    0
646    0
668    0
Name: FTR, dtype: object
0.5
Getafe - local
496    1
512    0
537    3
552    3
576    0
595    3
612    3
632    1
651    3
676    3
Name: FTR, dtype: object
2.0
15
12.0
Espanol - visitante
495    0
513    0
524    1
549    0
562    3
584    0
609    0
633    0
656    0
663    3
Name: FTR, dtype: object
0.7
Betis - local
491    3
520    1
530    0
563    3
582    0
604    3
628    3
631    0
655    3
689    1
Name: FTR, dtype: object
1.7
20
14.5
Granada - visitante
493    1
515    3
535    0
555    0
560    0
589    0
614    0
638    0
651    0
687    0
Name: FTR, dtype: object
0.4
Levante - local
493    1
516    3
538    3
568    0
581    3
607    0
630    3
649    3
663    0
691    1
Name: FTR, dtype: object
1.7
15
11.7
Sevilla - visitante
498    1
512    3
531    0
567    0
588    3
601    1
621    3
631    3
657    1
680    0
Name: FTR, dtype: object
1.5
Sociedad - local
510    3
517    3
533    3
551    3
572    0
598    1
618    3
640    1
658    0
673    3
Name: FTR, dtype: object
2.0
21
15.0
Osasuna - visitante
505    0
522    3
541    0
570    1
596    0
613    3
632    1
652    1
679    0
691    1
Name: FTR, dtype: object
1.0
Real Madrid - local
501    3
521    1
548    3
567    3
580    1
609    3
626    3
647    1
654    3
687    3
Name: FTR, dtype: object
2.4
21
17.4
Eibar - visitante
518    0
539    0
553    1
577    0
597    1
618    0
642    3
667    0
689    1
717    1
Name: FTR, dtype: object
0.7
Ath Bilbao - local
504    3
522    0
543    0
561    1
597    1
614    3
634    3
656    3
671    1
698    0
Name: FTR, dtype: object
1.5
10
14.5
Ath Madrid - visitante
503    1
529    1
548    0
565    0
582    3
610    1
627    1
648    1
660    1
682    1
Name: FTR, dtype: object
1.0
Mallorca - local
502    0
528    3
547    0
564    3
588    0
617    0
635    3
652    1
675    3
684    3
Name: FTR, dtype: object
1.6
14
10.1
Barcelona - visitante
501    0
530    3
557    0
574    1
598    1
611    3
629    3
649    0
678    3
697    3
Name: FTR, dtype: object
1.7
Leganes - local
507    1
523    1
545    3
569    0
584    3
602    3
629    0
642    0
668    3
688    0
Name: FTR, dtype: object
1.4
12
13.1
Valladolid - visitante
510    0
525    0
547    3
566    1
595    0
620    1
639    0
659    0
671    1
694    3
Name: FTR, dtype: object
0.9
Celta - local
519    3
531    3
553    1
570    1
594    1
620    1
643    0
665    0
683    3
701    1
Name: FTR, dtype: object
1.4
8
12.7
Villarreal - visitante
504    0
511    0
536    1
556    3
572    3
592    3
616    0
635    0
653    0
672    3
Name: FTR, dtype: object
1.3
Espanol - local
503    1
534    3
558    1
574    1
593    1
613    0
625    1
650    0
672    0
694    0
Name: FTR, dtype: object
0.8
11
11.9
Alaves - visitante
507    1
528    0
542    1
568    3
587    0
608    0
623    3
644    0
669    0
686    0
Name: FTR, dtype: object
0.8
Valencia - local
508    3
529    1
546    3
557    3
577    3
591    1
616    3
638    3
657    1
686    3
Name: FTR, dtype: object
2.4
16
10.0
Levante - visitante
509    0
526    0
540    0
559    0
575    0
599    3
612    0
634    0
658    3
670    0
Name: FTR, dtype: object
0.6
Granada - local
506    1
525    3
549    3
573    3
599    0
608    3
627    1
641    0
664    3
679    3
Name: FTR, dtype: object
2.0
13
10.4
Getafe - visitante
502    3
527    0
543    3
569    3
586    0
605    3
625    1
643    3
662    0
681    3
Name: FTR, dtype: object
1.9
Sevilla - local
505    3
524    1
542    1
555    3
578    1
592    0
615    3
648    1
662    3
670    3
Name: FTR, dtype: object
1.9
15
15.0
Betis - visitante
508    0
523    1
544    1
552    0
571    1
593    1
617    3
647    1
664    0
673    0
Name: FTR, dtype: object
0.8
Eibar - local
499    0
509    3
544    1
565    3
589    3
605    0
623    0
637    0
653    3
678    0
Name: FTR, dtype: object
1.3
12
13.2
Sociedad - visitante
497    0
545    0
563    0
583    3
603    1
626    0
641    3
665    3
690    0
713    3
Name: FTR, dtype: object
1.3
Betis - local
520    1
530    0
563    3
582    0
604    3
628    3
631    0
655    3
689    1
708    3
Name: FTR, dtype: object
1.7
21
14.8
Real Madrid - visitante
516    0
532    3
550    3
576    3
590    1
591    1
619    3
637    3
675    0
695    1
Name: FTR, dtype: object
1.8
Villarreal - local
526    3
541    3
562    0
586    3
610    1
622    0
645    1
669    3
699    3
718    3
Name: FTR, dtype: object
2.0
19
15.8
Leganes - visitante
519    0
538    0
554    1
579    1
600    1
615    0
640    1
654    0
676    0
696    0
Name: FTR, dtype: object
0.4
Levante - local
516    3
538    3
568    0
581    3
607    0
630    3
649    3
663    0
691    1
717    1
Name: FTR, dtype: object
1.7
14
11.9
Granada - visitante
515    3
535    0
555    0
560    0
589    0
614    0
638    0
651    0
687    0
709    1
Name: FTR, dtype: object
0.4
Valladolid - local
513    3
536    1
550    0
579    1
585    1
603    1
621    0
646    3
667    3
682    1
Name: FTR, dtype: object
1.4
11
9.7
Ath Bilbao - visitante
514    0
533    0
558    1
578    1
580    1
604    0
624    3
645    1
666    0
683    0
Name: FTR, dtype: object
0.7
Osasuna - local
515    0
532    0
559    3
566    1
583    0
601    1
624    0
644    3
661    3
685    3
Name: FTR, dtype: object
1.4
17
16.1
Espanol - visitante
513    0
524    1
549    0
562    3
584    0
609    0
633    0
656    0
663    3
684    0
Name: FTR, dtype: object
0.7
Getafe - local
512    0
537    3
552    3
576    0
595    3
612    3
632    1
651    3
676    3
697    0
Name: FTR, dtype: object
1.9
15
10.9
Celta - visitante
506    1
521    1
546    0
561    1
581    0
602    0
622    3
636    0
655    0
674    0
Name: FTR, dtype: object
0.6
Barcelona - local
518    3
527    3
540    3
560    3
587    3
590    1
606    3
636    3
659    3
680    3
Name: FTR, dtype: object
2.8
32
15.1
Sociedad - visitante
545    0
563    0
583    3
603    1
626    0
641    3
665    3
690    0
713    3
738    0
Name: FTR, dtype: object
1.3
Ath Madrid - local
511    3
535    3
554    1
575    3
596    3
611    0
633    3
666    3
677    1
695    1
Name: FTR, dtype: object
2.1
14
13.8
Sevilla - visitante
512    3
531    0
567    0
588    3
601    1
621    3
631    3
657    1
680    0
702    0
Name: FTR, dtype: object
1.4
Eibar - local
509    3
544    1
565    3
589    3
605    0
623    0
637    0
653    3
678    0
693    3
Name: FTR, dtype: object
1.6
13
12.6
Mallorca - visitante
520    1
534    0
551    0
573    0
594    1
606    0
630    0
646    0
668    0
692    0
Name: FTR, dtype: object
0.2
Alaves - local
514    3
539    3
556    0
571    1
600    1
619    0
639    3
660    1
674    3
692    3
Name: FTR, dtype: object
1.8
16
9.7
Valencia - visitante
517    0
537    0
564    0
585    1
607    3
628    0
650    3
661    0
677    1
698    3
Name: FTR, dtype: object
1.1
Real Madrid - local
521    1
548    3
567    3
580    1
609    3
626    3
647    1
654    3
687    3
703    3
Name: FTR, dtype: object
2.4
21
17.6
Barcelona - visitante
530    3
557    0
574    1
598    1
611    3
629    3
649    0
678    3
697    3
715    0
Name: FTR, dtype: object
1.7
Mallorca - local
528    3
547    0
564    3
588    0
617    0
635    3
652    1
675    3
684    3
705    0
Name: FTR, dtype: object
1.6
14
10.6
Getafe - visitante
527    0
543    3
569    3
586    0
605    3
625    1
643    3
662    0
681    3
704    1
Name: FTR, dtype: object
1.7
Espanol - local
534    3
558    1
574    1
593    1
613    0
625    1
650    0
672    0
694    0
713    0
Name: FTR, dtype: object
0.7
11
12.7
Ath Madrid - visitante
529    1
548    0
565    0
582    3
610    1
627    1
648    1
660    1
682    1
705    3
Name: FTR, dtype: object
1.2
Ath Bilbao - local
522    0
543    0
561    1
597    1
614    3
634    3
656    3
671    1
698    0
711    3
Name: FTR, dtype: object
1.5
11
14.0
Villarreal - visitante
511    0
536    1
556    3
572    3
592    3
616    0
635    0
653    0
672    3
685    0
Name: FTR, dtype: object
1.3
Sevilla - local
524    1
542    1
555    3
578    1
592    0
615    3
648    1
662    3
670    3
690    3
Name: FTR, dtype: object
1.9
15
15.9
Osasuna - visitante
522    3
541    0
570    1
596    0
613    3
632    1
652    1
679    0
691    1
703    0
Name: FTR, dtype: object
1.0
Granada - local
525    3
549    3
573    3
599    0
608    3
627    1
641    0
664    3
679    3
696    3
Name: FTR, dtype: object
2.2
14
10.1
Celta - visitante
521    1
546    0
561    1
581    0
602    0
622    3
636    0
655    0
674    0
693    0
Name: FTR, dtype: object
0.5
Leganes - local
523    1
545    3
569    0
584    3
602    3
629    0
642    0
668    3
688    0
706    1
Name: FTR, dtype: object
1.4
12
11.9
Alaves - visitante
528    0
542    1
568    3
587    0
608    0
623    3
644    0
669    0
686    0
700    0
Name: FTR, dtype: object
0.7
Valencia - local
529    1
546    3
557    3
577    3
591    1
616    3
638    3
657    1
686    3
704    1
Name: FTR, dtype: object
2.2
17
9.8
Betis - visitante
523    1
544    1
552    0
571    1
593    1
617    3
647    1
664    0
673    0
699    0
Name: FTR, dtype: object
0.8
Eibar - local
544    1
565    3
589    3
605    0
623    0
637    0
653    3
678    0
693    3
702    3
Name: FTR, dtype: object
1.6
13
12.4
Levante - visitante
526    0
540    0
559    0
575    0
599    3
612    0
634    0
658    3
670    0
688    3
Name: FTR, dtype: object
0.9
Sociedad - local
517    3
533    3
551    3
572    0
598    1
618    3
640    1
658    0
673    3
681    0
Name: FTR, dtype: object
1.7
21
14.3
Valladolid - visitante
525    0
547    3
566    1
595    0
620    1
639    0
659    0
671    1
694    3
718    0
Name: FTR, dtype: object
0.9
Ath Madrid - local
535    3
554    1
575    3
596    3
611    0
633    3
666    3
677    1
695    1
716    1
Name: FTR, dtype: object
1.9
11
14.2
Villarreal - visitante
536    1
556    3
572    3
592    3
616    0
635    0
653    0
672    3
685    0
707    0

Name: FTR, dtype: object
1.3
Getafe - local
537    3
552    3
576    0
595    3
612    3
632    1
651    3
676    3
697    0
714    3
Name: FTR, dtype: object
2.2
19
11.3
Sevilla - visitante
531    0
567    0
588    3
601    1
621    3
631    3
657    1
680    0
702    0
723    3
Name: FTR, dtype: object
1.4
Valladolid - local
536    1
550    0
579    1
585    1
603    1
621    0
646    3
667    3
682    1
709    1
Name: FTR, dtype: object
1.2
10
8.5
Espanol - visitante
524    1
549    0
562    3
584    0
609    0
633    0
656    0
663    3
684    0
701    1
Name: FTR, dtype: object
0.8
Alaves - local
539    3
556    0
571    1
600    1
619    0
639    3
660    1
674    3
692    3
723    0
Name: FTR, dtype: object
1.5
14
10.0
Ath Bilbao - visitante
533    0
558    1
578    1
580    1
604    0
624    3
645    1
666    0
683    0
706    1
Name: FTR, dtype: object
0.8
Osasuna - local
532    0
559    3
566    1
583    0
601    1
624    0
644    3
661    3
685    3
719    1
Name: FTR, dtype: object
1.5
17
15.9
Granada - visitante
535    0
555    0
560    0
589    0
614    0
638    0
651    0
687    0
709    1
722    3
Name: FTR, dtype: object
0.4
Levante - local
538    3
568    0
581    3
607    0
630    3
649    3
663    0
691    1
717    1
735    3
Name: FTR, dtype: object
1.7
15
12.7
Real Madrid - visitante
532    3
550    3
576    3
590    1
591    1
619    3
637    3
675    0
695    1
710    3
Name: FTR, dtype: object
2.1
Sociedad - local
533    3
551    3
572    0
598    1
618    3
640    1
658    0
673    3
681    0
700    3
Name: FTR, dtype: object
1.7
21
14.5
Valencia - visitante
537    0
564    0
585    1
607    3
628    0
650    3
661    0
677    1
698    3
725    0
Name: FTR, dtype: object
1.1
Barcelona - local
527    3
540    3
560    3
587    3
590    1
606    3
636    3
659    3
680    3
707    3
Name: FTR, dtype: object
2.8
29
14.6
Eibar - visitante
539    0
553    1
577    0
597    1
618    0
642    3
667    0
689    1
717    1
732    0
Name: FTR, dtype: object
0.7
Celta - local
531    3
553    1
570    1
594    1
620    1
643    0
665    0
683    3
701    1
722    0
Name: FTR, dtype: object
1.1
7
12.8
Leganes - visitante
538    0
554    1
579    1
600    1
615    0
640    1
654    0
676    0
696    0
712    1
Name: FTR, dtype: object
0.5
Betis - local
530    0
563    3
582    0
604    3
628    3
631    0
655    3
689    1
708    3
720    1
Name: FTR, dtype: object
1.7
19
13.6
Mallorca - visitante
534    0
551    0
573    0
594    1
606    0
630    0
646    0
668    0
692    0
714    0
Name: FTR, dtype: object
0.1
Real Madrid - local
548    3
567    3
580    1
609    3
626    3
647    1
654    3
687    3
703    3
728    3
Name: FTR, dtype: object
2.6
22
18.6
Celta - visitante
546    0
561    1
581    0
602    0
622    3
636    0
655    0
674    0
693    0
716    1
Name: FTR, dtype: object
0.5
Ath Bilbao - local
543    0
561    1
597    1
614    3
634    3
656    3
671    1
698    0
711    3
738    3
Name: FTR, dtype: object
1.8
13
14.3
Osasuna - visitante
541    0
570    1
596    0
613    3
632    1
652    1
679    0
691    1
703    0
721    1
Name: FTR, dtype: object
0.8
Leganes - local
545    3
569    0
584    3
602    3
629    0
642    0
668    3
688    0
706    1
727    0
Name: FTR, dtype: object
1.3
12
11.8
Betis - visitante
544    1
552    0
571    1
593    1
617    3
647    1
664    0
673    0
699    0
719    1
Name: FTR, dtype: object
0.8
Sevilla - local
542    1
555    3
578    1
592    0
615    3
648    1
662    3
670    3
690    3
710    0
Name: FTR, dtype: object
1.8
13
15.0
Espanol - visitante
549    0
562    3
584    0
609    0
633    0
656    0
663    3
684    0
701    1
724    3
Name: FTR, dtype: object
1.0
Granada - local
549    3
573    3
599    0
608    3
627    1
641    0
664    3
679    3
696    3
715    3
Name: FTR, dtype: object
2.2
14
9.9
Valladolid - visitante
547    3
566    1
595    0
620    1
639    0
659    0
671    1
694    3
718    0
735    0
Name: FTR, dtype: object
0.9
Villarreal - local
541    3
562    0
586    3
610    1
622    0
645    1
669    3
699    3
718    3
730    1
Name: FTR, dtype: object
1.8
19
15.4
Levante - visitante
540    0
559    0
575    0
599    3
612    0
634    0
658    3
670    0
688    3
708    0
Name: FTR, dtype: object
0.9
Barcelona - local
540    3
560    3
587    3
590    1
606    3
636    3
659    3
680    3
707    3
725    3
Name: FTR, dtype: object
2.8
32
15.1
Getafe - visitante
543    3
569    3
586    0
605    3
625    1
643    3
662    0
681    3
704    1
720    1
Name: FTR, dtype: object
1.8
Mallorca - local
547    0
564    3
588    0
617    0
635    3
652    1
675    3
684    3
705    0
729    1
Name: FTR, dtype: object
1.4
13
10.2
Alaves - visitante
542    1
568    3
587    0
608    0
623    3
644    0
669    0
686    0
700    0
711    0
Name: FTR, dtype: object
0.7
Valencia - local
546    3
557    3
577    3
591    1
616    3
638    3
657    1
686    3
704    1
712    1
Name: FTR, dtype: object
2.2
16
10.2
Ath Madrid - visitante
548    0
565    0
582    3
610    1
627    1
648    1
660    1
682    1
705    3
726    0
Name: FTR, dtype: object
1.1
Betis - local
563    3
582    0
604    3
628    3
631    0
655    3
689    1
708    3
720    1
734    3
Name: FTR, dtype: object
2.0
19
14.6
Barcelona - visitante
557    0
574    1
598    1
611    3
629    3
649    0
678    3
697    3
715    0
737    1
Name: FTR, dtype: object
1.5
Celta - local
553    1
570    1
594    1
620    1
643    0
665    0
683    3
701    1
722    0
745    3
Name: FTR, dtype: object
1.1
6
12.6
Sevilla - visitante
567    0
588    3
601    1
621    3
631    3
657    1
680    0
702    0
723    3
749    3
Name: FTR, dtype: object
1.7
Osasuna - local
559    3
566    1
583    0
601    1
624    0
644    3
661    3
685    3
719    1
737    1
Name: FTR, dtype: object
1.6
18
16.0
Real Madrid - visitante
550    3
576    3
590    1
591    1
619    3
637    3
675    0
695    1
710    3
730    1
Name: FTR, dtype: object
1.9
Sociedad - local
551    3
572    0
598    1
618    3
640    1
658    0
673    3
681    0
700    3
726    3
Name: FTR, dtype: object
1.7
21
14.5
Ath Bilbao - visitante
558    1
578    1
580    1
604    0
624    3
645    1
666    0
683    0
706    1
729    1
Name: FTR, dtype: object
0.9
Espanol - local
558    1
574    1
593    1
613    0
625    1
650    0
672    0
694    0
713    0
731    0
Name: FTR, dtype: object
0.4
10
13.0
Mallorca - visitante
551    0
573    0
594    1
606    0
630    0
646    0
668    0
692    0
714    0
733    0
Name: FTR, dtype: object
0.1
Ath Madrid - local
554    1
575    3
596    3
611    0
633    3
666    3
677    1
695    1
716    1
732    3
Name: FTR, dtype: object
1.9
13
14.3
Granada - visitante
555    0
560    0
589    0
614    0
638    0
651    0
687    0
709    1
722    3
731    3
Name: FTR, dtype: object
0.7
Valladolid - local
550    0
579    1
585    1
603    1
621    0
646    3
667    3
682    1
709    1
721    1
Name: FTR, dtype: object
1.2
10
8.8
Villarreal - visitante
556    3
572    3
592    3
616    0
635    0
653    0
672    3
685    0
707    0
727    3
Name: FTR, dtype: object
1.5
Getafe - local
552    3
576    0
595    3
612    3
632    1
651    3
676    3
697    0
714    3
736    1
Name: FTR, dtype: object
2.0
17
10.6
Valencia - visitante
564    0
585    1
607    3
628    0
650    3
661    0
677    1
698    3
725    0
745    0
Name: FTR, dtype: object
1.1
Levante - local
568    0
581    3
607    0
630    3
649    3
663    0
691    1
717    1
735    3
748    3
Name: FTR, dtype: object
1.7
15
13.4
Leganes - visitante
554    1
579    1
600    1
615    0
640    1
654    0
676    0
696    0
712    1
734    0
Name: FTR, dtype: object
0.5
Alaves - local
556    0
571    1
600    1
619    0
639    3
660    1
674    3
692    3
723    0
743    1
Name: FTR, dtype: object
1.3
12
10.1
Eibar - visitante
553    1
577    0
597    1
618    0
642    3
667    0
689    1
717    1
732    0
747    1
Name: FTR, dtype: object
0.8
Barcelona - local
560    3
587    3
590    1
606    3
636    3
659    3
680    3
707    3
725    3
740    3
Name: FTR, dtype: object
2.8
35
14.8
Levante - visitante
559    0
575    0
599    3
612    0
634    0
658    3
670    0
688    3
708    0
728    0
Name: FTR, dtype: object
0.9
Villarreal - local
562    0
586    3
610    1
622    0
645    1
669    3
699    3
718    3
730    1
754    1
Name: FTR, dtype: object
1.6
20
15.7
Osasuna - visitante
570    1
596    0
613    3
632    1
652    1
679    0
691    1
703    0
721    1
755    3
Name: FTR, dtype: object
1.1
Sevilla - local
555    3
578    1
592    0
615    3
648    1
662    3
670    3
690    3
710    0
739    1
Name: FTR, dtype: object
1.8
13
15.5
Alaves - visitante
568    3
587    0
608    0
623    3
644    0
669    0
686    0
700    0
711    0
736    1
Name: FTR, dtype: object
0.7
Ath Bilbao - local
561    1
597    1
614    3
634    3
656    3
671    1
698    0
711    3
738    3
759    3
Name: FTR, dtype: object
2.1
14
14.6
Getafe - visitante
569    3
586    0
605    3
625    1
643    3
662    0
681    3
704    1
720    1
750    0
Name: FTR, dtype: object
1.5
Eibar - local
565    3
589    3
605    0
623    0
637    0
653    3
678    0
693    3
702    3
724    0
Name: FTR, dtype: object
1.5
13
12.7
Betis - visitante
552    0
571    1
593    1
617    3
647    1
664    0
673    0
699    0
719    1
740    0
Name: FTR, dtype: object
0.7
Leganes - local
569    0
584    3
602    3
629    0
642    0
668    3
688    0
706    1
727    0
741    0
Name: FTR, dtype: object
1.0
10
11.6
Sociedad - visitante
563    0
583    3
603    1
626    0
641    3
665    3
690    0
713    3
738    0
742    3
Name: FTR, dtype: object
1.6
Valencia - local
557    3
577    3
591    1
616    3
638    3
657    1
686    3
704    1
712    1
733    3
Name: FTR, dtype: object
2.2
17
10.2
Celta - visitante
561    1
581    0
602    0
622    3
636    0
655    0
674    0
693    0
716    1
739    1
Name: FTR, dtype: object
0.6
Mallorca - local
564    3
588    0
617    0
635    3
652    1
675    3
684    3
705    0
729    1
742    0
Name: FTR, dtype: object
1.4
13
9.8
Valladolid - visitante
566    1
595    0
620    1
639    0
659    0
671    1
694    3
718    0
735    0
746    1
Name: FTR, dtype: object
0.7
Real Madrid - local
567    3
580    1
609    3
626    3
647    1
654    3
687    3
703    3
728    3
746    1
Name: FTR, dtype: object
2.4
22
19.2
Ath Madrid - visitante
565    0
582    3
610    1
627    1
648    1
660    1
682    1
705    3
726    0
741    3
Name: FTR, dtype: object
1.4
Granada - local
573    3
599    0
608    3
627    1
641    0
664    3
679    3
696    3
715    3
749    0
Name: FTR, dtype: object
1.9
12
10.3
Espanol - visitante
562    3
584    0
609    0
633    0
656    0
663    3
684    0
701    1
724    3
743    1
Name: FTR, dtype: object
1.1
Valladolid - local
579    1
585    1
603    1
621    0
646    3
667    3
682    1
709    1
721    1
762    0
Name: FTR, dtype: object
1.2
10
10.3
Real Madrid - visitante
576    3
590    1
591    1
619    3
637    3
675    0
695    1
710    3
730    1
758    3
Name: FTR, dtype: object
1.9
Sociedad - local
572    0
598    1
618    3
640    1
658    0
673    3
681    0
700    3
726    3
773    3
Name: FTR, dtype: object
1.7
21
15.0
Mallorca - visitante
573     0
594     1
606     0
630     0
646     0
668     0
692     0
714     0
733     0
3058    1
Name: FTR, dtype: object
0.2
Getafe - local
576    0
595    3
612    3
632    1
651    3
676    3
697    0
714    3
736    1
744    1
Name: FTR, dtype: object
1.8
17
10.5
Betis - visitante
571    1
593    1
617    3
647    1
664    0
673    0
699    0
719    1
740    0
760    3
Name: FTR, dtype: object
1.0
Celta - local
570    1
594    1
620    1
643    0
665    0
683    3
701    1
722    0
745    3
758    0
Name: FTR, dtype: object
1.0
7
11.5
Eibar - visitante
577    0
597    1
618    0
642    3
667    0
689    1
717    1
732    0
747    1
756    0
Name: FTR, dtype: object
0.7
Ath Madrid - local
575    3
596    3
611    0
633    3
666    3
677    1
695    1
716    1
732    3
750    3
Name: FTR, dtype: object
2.1
14
13.4
Leganes - visitante
579    1
600    1
615    0
640    1
654    0
676    0
696    0
712    1
734    0
765    0
Name: FTR, dtype: object
0.4
Sevilla - local
578    1
592    0
615    3
648    1
662    3
670    3
690    3
710    0
739    1
763    3
Name: FTR, dtype: object
1.8
13
15.2
Granada - visitante
560    0
589    0
614    0
638    0
651    0
687    0
709    1
722    3
731    3
754    1
Name: FTR, dtype: object
0.8

Alaves - local
571    1
600    1
619    0
639    3
660    1
674    3
692    3
723    0
743    1
753    3
Name: FTR, dtype: object
1.6
12
9.8
Villarreal - visitante
572    3
592    3
616    0
635    0
653    0
672    3
685    0
707    0
727    3
748    0
Name: FTR, dtype: object
1.2
Valencia - local
577    3
591    1
616    3
638    3
657    1
686    3
704    1
712    1
733    3
757    1
Name: FTR, dtype: object
2.0
16
10.8
Barcelona - visitante
574    1
598    1
611    3
629    3
649    0
678    3
697    3
715    0
737    1
759    0
Name: FTR, dtype: object
1.5
Espanol - local
574    1
593    1
613    0
625    1
650    0
672    0
694    0
713    0
731    0
752    0
Name: FTR, dtype: object
0.3
9
12.8
Ath Bilbao - visitante
578    1
580    1
604    0
624    3
645    1
666    0
683    0
706    1
729    1
744    1
Name: FTR, dtype: object
0.9
Osasuna - local
566    1
583    0
601    1
624    0
644    3
661    3
685    3
719    1
737    1
747    1
Name: FTR, dtype: object
1.4
16
15.1
Levante - visitante
575    0
599    3
612    0
634    0
658    3
670    0
688    3
708    0
728    0
753    0
Name: FTR, dtype: object
0.9
Barcelona - local
587    3
590    1
606    3
636    3
659    3
680    3
707    3
725    3
740    3
777    3
Name: FTR, dtype: object
2.8
36
14.3
Granada - visitante
589     0
614     0
638     0
651     0
687     0
709     1
722     3
731     3
754     1
1539    0
Name: FTR, dtype: object
0.8
Ath Bilbao - local
597    1
614    3
634    3
656    3
671    1
698    0
711    3
738    3
759    3
779    3
Name: FTR, dtype: object
2.3
16
13.2
Celta - visitante
581    0
602    0
622    3
636    0
655    0
674    0
693    0
716    1
739    1
779    0
Name: FTR, dtype: object
0.5
Villarreal - local
586    3
610    1
622    0
645    1
669    3
699    3
718    3
730    1
754    1
770    3
Name: FTR, dtype: object
1.9
20
14.7
Espanol - visitante
584    0
609    0
633    0
656    0
663    3
684    0
701    1
724    3
743    1
774    3
Name: FTR, dtype: object
1.1
Betis - local
582    0
604    3
628    3
631    0
655    3
689    1
708    3
720    1
734    3
751    0
Name: FTR, dtype: object
1.7
17
14.5
Sociedad - visitante
583    3
603    1
626    0
641    3
665    3
690    0
713    3
738    0
742    3
757    1
Name: FTR, dtype: object
1.7
Mallorca - local
588    0
617    0
635    3
652    1
675    3
684    3
705    0
729    1
742    0
756    3
Name: FTR, dtype: object
1.4
11
10.1
Valencia - visitante
585    1
607    3
628    0
650    3
661    0
677    1
698    3
725    0
745    0
762    3
Name: FTR, dtype: object
1.4
Eibar - local
589    3
605    0
623    0
637    0
653    3
678    0
693    3
702    3
724    0
761    1
Name: FTR, dtype: object
1.3
13
13.3
Ath Madrid - visitante
582    3
610    1
627    1
648    1
660    1
682    1
705    3
726    0
741    3
764    1
Name: FTR, dtype: object
1.5
Osasuna - local
583     0
601     1
624     0
644     3
661     3
685     3
719     1
737     1
747     1
1539    3
Name: FTR, dtype: object
1.6
18
14.9
Valladolid - visitante
595    0
620    1
639    0
659    0
671    1
694    3
718    0
735    0
746    1
751    3
Name: FTR, dtype: object
0.9
Real Madrid - local
580    1
609    3
626    3
647    1
654    3
687    3
703    3
728    3
746    1
760    0
Name: FTR, dtype: object
2.1
20
18.8
Sevilla - visitante
588    3
601    1
621    3
631    3
657    1
680    0
702    0
723    3
749    3
752    3
Name: FTR, dtype: object
2.0
Levante - local
581    3
607    0
630    3
649    3
663    0
691    1
717    1
735    3
748    3
764    1
Name: FTR, dtype: object
1.8
17
13.1
Alaves - visitante
587    0
608    0
623    3
644    0
669    0
686    0
700    0
711    0
736    1
772    0
Name: FTR, dtype: object
0.4
Leganes - local
584    3
602    3
629    0
642    0
668    3
688    0
706    1
727    0
741    0
755    0
Name: FTR, dtype: object
1.0
10
12.1
Getafe - visitante
586    0
605    3
625    1
643    3
662    0
681    3
704    1
720    1
750    0
777    0
Name: FTR, dtype: object
1.2
Celta - local
594    1
620    1
643    0
665    0
683    3
701    1
722    0
745    3
758    0
768    1
Name: FTR, dtype: object
1.0
8
10.9
Osasuna - visitante
596     0
613     3
632     1
652     1
679     0
691     1
703     0
721     1
755     3
1526    0
Name: FTR, dtype: object
1.0
Alaves - local
600    1
619    0
639    3
660    1
674    3
692    3
723    0
743    1
753    3
769    3
Name: FTR, dtype: object
1.8
13
10.6
Betis - visitante
593    1
617    3
647    1
664    0
673    0
699    0
719    1
740    0
760    3
784    0
Name: FTR, dtype: object
0.9
Sociedad - local
598    1
618    3
640    1
658    0
673    3
681    0
700    3
726    3
773    3
794    3
Name: FTR, dtype: object
2.0
22
15.1
Villarreal - visitante
592    3
616    0
635    0
653    0
672    3
685    0
707    0
727    3
748    0
766    1
Name: FTR, dtype: object
1.0
Granada - local
599     0
608     3
627     1
641     0
664     3
679     3
696     3
715     3
749     0
1529    0
Name: FTR, dtype: object
1.6
12
11.2
Mallorca - visitante
594     1
606     0
630     0
646     0
668     0
692     0
714     0
733     0
3058    1
3076    0
Name: FTR, dtype: object
0.2
Espanol - local
593    1
613    0
625    1
650    0
672    0
694    0
713    0
731    0
752    0
767    3
Name: FTR, dtype: object
0.5
9
12.9
Barcelona - visitante
598    1
611    3
629    3
649    0
678    3
697    3
715    0
737    1
759    0
761    1
Name: FTR, dtype: object
1.5
Ath Madrid - local
596    3
611    0
633    3
666    3
677    1
695    1
716    1
732    3
750    3
778    1
Name: FTR, dtype: object
1.9
13
12.8
Levante - visitante
599    3
612    0
634    0
658    3
670    0
688    3
708    0
728    0
753    0
775    3
Name: FTR, dtype: object
1.2
Getafe - local
595    3
612    3
632    1
651    3
676    3
697    0
714    3
736    1
744    1
766    1
Name: FTR, dtype: object
1.9
19
10.7
Real Madrid - visitante
590    1
591    1
619    3
637    3
675    0
695    1
710    3
730    1
758    3
773    0
Name: FTR, dtype: object
1.6
Valencia - local
591    1
616    3
638    3
657    1
686    3
704    1
712    1
733    3
757    1
772    3
Name: FTR, dtype: object
2.0
18
10.9
Eibar - visitante
597    1
618    0
642    3
667    0
689    1
717    1
732    0
747    1
756    0
770    0
Name: FTR, dtype: object
0.7
Sevilla - local
592    0
615    3
648    1
662    3
670    3
690    3
710    0
739    1
763    3
789    0
Name: FTR, dtype: object
1.7
12
15.0
Ath Bilbao - visitante
580    1
604    0
624    3
645    1
666    0
683    0
706    1
729    1
744    1
763    0
Name: FTR, dtype: object
0.8
Valladolid - local
585    1
603    1
621    0
646    3
667    3
682    1
709    1
721    1
762    0
780    3
Name: FTR, dtype: object
1.4
9
9.9
Leganes - visitante
600    1
615    0
640    1
654    0
676    0
696    0
712    1
734    0
765    0
789    3
Name: FTR, dtype: object
0.6
Real Madrid - local
609    3
626    3
647    1
654    3
687    3
703    3
728    3
746    1
760    0
781    3
Name: FTR, dtype: object
2.3
23
19.2
Ath Bilbao - visitante
604    0
624    3
645    1
666    0
683    0
706    1
729    1
744    1
763    0
780    0
Name: FTR, dtype: object
0.7
Levante - local
607    0
630    3
649    3
663    0
691    1
717    1
735    3
748    3
764    1
785    3
Name: FTR, dtype: object
1.8
18
13.0
Celta - visitante
602    0
622    3
636    0
655    0
674    0
693    0
716    1
739    1
779    0
796    1
Name: FTR, dtype: object
0.6
Betis - local
604    3
628    3
631    0
655    3
689    1
708    3
720    1
734    3
751    0
776    3
Name: FTR, dtype: object
2.0
18
14.7
Ath Madrid - visitante
610    1
627    1
648    1
660    1
682    1
705    3
726    0
741    3
764    1
786    0
Name: FTR, dtype: object
1.2
Osasuna - local
601     1
624     0
644     3
661     3
685     3
719     1
737     1
747     1
1539    3
1552    1
Name: FTR, dtype: object
1.7
17
14.6
Sociedad - visitante
603    1
626    0
641    3
665    3
690    0
713    3
738    0
742    3
757    1
767    0
Name: FTR, dtype: object
1.4
Leganes - local
602    3
629    0
642    0
668    3
688    0
706    1
727    0
741    0
755    0
774    0
Name: FTR, dtype: object
0.7
8
12.1
Espanol - visitante
609    0
633    0
656    0
663    3
684    0
701    1
724    3
743    1
774    3
790    1
Name: FTR, dtype: object
1.2
Valladolid - local
603    1
621    0
646    3
667    3
682    1
709    1
721    1
762    0
780    3
807    3
Name: FTR, dtype: object
1.6
9
9.8
Valencia - visitante
607    3
628    0
650    3
661    0
677    1
698    3
725    0
745    0
762    3
782    3
Name: FTR, dtype: object
1.6
Villarreal - local
610    1
622    0
645    1
669    3
699    3
718    3
730    1
754    1
770    3
791    1
Name: FTR, dtype: object
1.7
20
15.4
Getafe - visitante
605    3
625    1
643    3
662    0
681    3
704    1
720    1
750    0
777    0
794    0
Name: FTR, dtype: object
1.2
Barcelona - local
590    1
606    3
636    3
659    3
680    3
707    3
725    3
740    3
777    3
797    3
Name: FTR, dtype: object
2.8
33
15.8
Alaves - visitante
608    0
623    3
644    0
669    0
686    0
700    0
711    0
736    1
772    0
799    1
Name: FTR, dtype: object
0.5
Mallorca - local
617     0
635     3
652     1
675     3
684     3
705     0
729     1
742     0
756     3
3044    3
Name: FTR, dtype: object
1.7
15
11.3
Sevilla - visitante
601    1
621    3
631    3
657    1
680    0
702    0
723    3
749    3
752    3
778    1
Name: FTR, dtype: object
1.8
Eibar - local
605    0
623    0
637    0
653    3
678    0
693    3
702    3
724    0
761    1
784    3
Name: FTR, dtype: object
1.3
11
12.6
Granada - visitante
614     0
638     0
651     0
687     0
709     1
722     3
731     3
754     1
1539    0
1556    0
Name: FTR, dtype: object
0.8
Barcelona - local
606    3
636    3
659    3
680    3
707    3
725    3
740    3
777    3
797    3
818    3
Name: FTR, dtype: object
3.0
35
16.0
Real Madrid - visitante
591    1
619    3
637    3
675    0
695    1
710    3
730    1
758    3
773    0
792    0
Name: FTR, dtype: object
1.5
Valencia - local
616    3
638    3
657    1
686    3
704    1
712    1
733    3
757    1
772    3
793    0
Name: FTR, dtype: object
1.9
17
10.7
Real Madrid - visitante
619    3
637    3
675    0
695    1
710    3
730    1
758    3
773    0
792    0
802    1
Name: FTR, dtype: object
1.5
Sevilla - local
615    3
648    1
662    3
670    3
690    3
710    0
739    1
763    3
789    0
801    3
Name: FTR, dtype: object
2.0
16
14.6
Villarreal - visitante
616    0
635    0
653    0
672    3
685    0
707    0
727    3
748    0
766    1
781    0
Name: FTR, dtype: object
0.7
Espanol - local
613    0
625    1
650    0
672    0
694    0
713    0
731    0
752    0
767    3
786    3
Name: FTR, dtype: object
0.7
10
12.4
Betis - visitante
617    3
647    1
664    0
673    0
699    0
719    1
740    0
760    3
784    0
803    0
Name: FTR, dtype: object
0.8
Celta - local
620    1
643    0
665    0
683    3
701    1
722    0
745    3
758    0
768    1
787    3
Name: FTR, dtype: object
1.2
8
10.5
Mallorca - visitante
606     0
630     0
646     0
668     0
692     0
714     0
733     0
3058    1
3076    0
3095    0
Name: FTR, dtype: object
0.1
Getafe - local
612    3
632    1
651    3
676    3
697    0
714    3
736    1
744    1
766    1
783    3
Name: FTR, dtype: object
1.9
19
11.3
Valladolid - visitante
620    1
639    0
659    0
671    1
694    3
718    0
735    0
746    1
751    3
771    3
Name: FTR, dtype: object
1.2
Ath Madrid - local
611    0
633    3
666    3
677    1
695    1
716    1
732    3
750    3
778    1
798    3
Name: FTR, dtype: object
1.9
12
12.2
Osasuna - visitante
613     3
632     1
652     1
679     0
691     1
703     0
721     1
755     3
1526    0
1542    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
614    3
634    3
656    3
671    1
698    0
711    3
738    3
759    3
779    3
799    1
Name: FTR, dtype: object
2.3
17
13.8
Eibar - visitante
618    0
642    3
667    0
689    1
717    1
732    0
747    1
756    0
770    0
793    3
Name: FTR, dtype: object
0.9
Sociedad - local
618    3
640    1
658    0
673    3
681    0
700    3
726    3
773    3
794    3
800    0
Name: FTR, dtype: object
1.9
20
14.5
Barcelona - visitante
611    3
629    3
649    0
678    3
697    3
715    0
737    1
759    0
761    1
787    0
Name: FTR, dtype: object
1.4
Granada - local
608     3
627     1
641     0
664     3
679     3
696     3
715     3
749     0
1529    0
1547    0
Name: FTR, dtype: object
1.6
11
10.7
Levante - visitante
612    0
634    0
658    3
670    0
688    3
708    0
728    0
753    0
775    3
797    0

Name: FTR, dtype: object
0.9
Alaves - local
619    0
639    3
660    1
674    3
692    3
723    0
743    1
753    3
769    3
788    0
Name: FTR, dtype: object
1.7
12
11.3
Leganes - visitante
615    0
640    1
654    0
676    0
696    0
712    1
734    0
765    0
789    3
810    0
Name: FTR, dtype: object
0.5
Osasuna - local
624     0
644     3
661     3
685     3
719     1
737     1
747     1
1539    3
1552    1
1577    1
Name: FTR, dtype: object
1.7
18
14.3
Sevilla - visitante
621    3
631    3
657    1
680    0
702    0
723    3
749    3
752    3
778    1
795    0
Name: FTR, dtype: object
1.7
Leganes - local
629    0
642    0
668    3
688    0
706    1
727    0
741    0
755    0
774    0
796    1
Name: FTR, dtype: object
0.5
5
11.6
Celta - visitante
622    3
636    0
655    0
674    0
693    0
716    1
739    1
779    0
796    1
805    1
Name: FTR, dtype: object
0.7
Valladolid - local
621    0
646    3
667    3
682    1
709    1
721    1
762    0
780    3
807    3
821    1
Name: FTR, dtype: object
1.6
11
10.2
Sociedad - visitante
626    0
641    3
665    3
690    0
713    3
738    0
742    3
757    1
767    0
788    3
Name: FTR, dtype: object
1.6
Betis - local
628    3
631    0
655    3
689    1
708    3
720    1
734    3
751    0
776    3
790    1
Name: FTR, dtype: object
1.8
16
15.5
Ath Bilbao - visitante
624    3
645    1
666    0
683    0
706    1
729    1
744    1
763    0
780    0
804    3
Name: FTR, dtype: object
1.0
Eibar - local
623    0
637    0
653    3
678    0
693    3
702    3
724    0
761    1
784    3
816    0
Name: FTR, dtype: object
1.3
11
13.0
Getafe - visitante
625    1
643    3
662    0
681    3
704    1
720    1
750    0
777    0
794    0
821    1
Name: FTR, dtype: object
1.0
Barcelona - local
636    3
659    3
680    3
707    3
725    3
740    3
777    3
797    3
818    3
839    3
Name: FTR, dtype: object
3.0
32
15.6
Mallorca - visitante
630     0
646     0
668     0
692     0
714     0
733     0
3058    1
3076    0
3095    0
3128    0
Name: FTR, dtype: object
0.1
Levante - local
630    3
649    3
663    0
691    1
717    1
735    3
748    3
764    1
785    3
803    3
Name: FTR, dtype: object
2.1
20
11.9
Valencia - visitante
628    0
650    3
661    0
677    1
698    3
725    0
745    0
762    3
782    3
806    0
Name: FTR, dtype: object
1.3
Granada - local
627     1
641     0
664     3
679     3
696     3
715     3
749     0
1529    0
1547    0
1569    0
Name: FTR, dtype: object
1.3
8
9.7
Alaves - visitante
623    3
644    0
669    0
686    0
700    0
711    0
736    1
772    0
799    1
828    0
Name: FTR, dtype: object
0.5
Real Madrid - local
626    3
647    1
654    3
687    3
703    3
728    3
746    1
760    0
781    3
811    3
Name: FTR, dtype: object
2.3
24
18.5
Espanol - visitante
633    0
656    0
663    3
684    0
701    1
724    3
743    1
774    3
790    1
812    1
Name: FTR, dtype: object
1.3
Villarreal - local
622    0
645    1
669    3
699    3
718    3
730    1
754    1
770    3
791    1
810    3
Name: FTR, dtype: object
1.9
22
14.2
Ath Madrid - visitante
627    1
648    1
660    1
682    1
705    3
726    0
741    3
764    1
786    0
816    3
Name: FTR, dtype: object
1.4
Ath Madrid - local
633    3
666    3
677    1
695    1
716    1
732    3
750    3
778    1
798    3
806    3
Name: FTR, dtype: object
2.2
15
11.9
Barcelona - visitante
629    3
649    0
678    3
697    3
715    0
737    1
759    0
761    1
787    0
809    3
Name: FTR, dtype: object
1.4
Getafe - local
632    1
651    3
676    3
697    0
714    3
736    1
744    1
766    1
783    3
802    1
Name: FTR, dtype: object
1.7
15
10.9
Levante - visitante
634    0
658    3
670    0
688    3
708    0
728    0
753    0
775    3
797    0
822    0
Name: FTR, dtype: object
0.9
Espanol - local
625    1
650    0
672    0
694    0
713    0
731    0
752    0
767    3
786    3
805    1
Name: FTR, dtype: object
0.8
9
12.1
Osasuna - visitante
632     1
652     1
679     0
691     1
703     0
721     1
755     3
1526    0
1542    0
1567    0
Name: FTR, dtype: object
0.7
Ath Bilbao - local
634    3
656    3
671    1
698    0
711    3
738    3
759    3
779    3
799    1
825    3
Name: FTR, dtype: object
2.3
18
13.9
Granada - visitante
638     0
651     0
687     0
709     1
722     3
731     3
754     1
1539    0
1556    0
1580    0
Name: FTR, dtype: object
0.8
Sevilla - local
648    1
662    3
670    3
690    3
710    0
739    1
763    3
789    0
801    3
826    3
Name: FTR, dtype: object
2.0
18
14.1
Leganes - visitante
640    1
654    0
676    0
696    0
712    1
734    0
765    0
789    3
810    0
835    1
Name: FTR, dtype: object
0.6
Valencia - local
638    3
657    1
686    3
704    1
712    1
733    3
757    1
772    3
793    0
822    3
Name: FTR, dtype: object
1.9
18
11.7
Villarreal - visitante
635    0
653    0
672    3
685    0
707    0
727    3
748    0
766    1
781    0
800    3
Name: FTR, dtype: object
1.0
Mallorca - local
635     3
652     1
675     3
684     3
705     0
729     1
742     0
756     3
3044    3
3060    3
Name: FTR, dtype: object
2.0
15
11.2
Betis - visitante
647    1
664    0
673    0
699    0
719    1
740    0
760    3
784    0
803    0
826    0
Name: FTR, dtype: object
0.5
Sociedad - local
640    1
658    0
673    3
681    0
700    3
726    3
773    3
794    3
800    0
823    1
Name: FTR, dtype: object
1.7
17
13.3
Eibar - visitante
642    3
667    0
689    1
717    1
732    0
747    1
756    0
770    0
793    3
808    0
Name: FTR, dtype: object
0.9
Alaves - local
639    3
660    1
674    3
692    3
723    0
743    1
753    3
769    3
788    0
809    0
Name: FTR, dtype: object
1.7
11
11.1
Real Madrid - visitante
637    3
675    0
695    1
710    3
730    1
758    3
773    0
792    0
802    1
820    1
Name: FTR, dtype: object
1.3
Celta - local
643    0
665    0
683    3
701    1
722    0
745    3
758    0
768    1
787    3
817    3
Name: FTR, dtype: object
1.4
10
10.5
Valladolid - visitante
639    0
659    0
671    1
694    3
718    0
735    0
746    1
751    3
771    3
798    0
Name: FTR, dtype: object
1.1
Valladolid - local
646    3
667    3
682    1
709    1
721    1
762    0
780    3
807    3
821    1
830    0
Name: FTR, dtype: object
1.6
11
10.5
Sevilla - visitante
631    3
657    1
680    0
702    0
723    3
749    3
752    3
778    1
795    0
813    0
Name: FTR, dtype: object
1.4
Villarreal - local
645    1
669    3
699    3
718    3
730    1
754    1
770    3
791    1
810    3
847    1
Name: FTR, dtype: object
2.0
25
14.3
Celta - visitante
636    0
655    0
674    0
693    0
716    1
739    1
779    0
796    1
805    1
829    0
Name: FTR, dtype: object
0.4
Eibar - local
637    0
653    3
678    0
693    3
702    3
724    0
761    1
784    3
816    0
845    3
Name: FTR, dtype: object
1.6
13
12.4
Alaves - visitante
644    0
669    0
686    0
700    0
711    0
736    1
772    0
799    1
828    0
841    0
Name: FTR, dtype: object
0.2
Osasuna - local
644     3
661     3
685     3
719     1
737     1
747     1
1539    3
1552    1
1577    1
1592    3
Name: FTR, dtype: object
2.0
19
14.2
Ath Bilbao - visitante
645    1
666    0
683    0
706    1
729    1
744    1
763    0
780    0
804    3
811    0
Name: FTR, dtype: object
0.7
Espanol - local
650    0
672    0
694    0
713    0
731    0
752    0
767    3
786    3
805    1
828    3
Name: FTR, dtype: object
1.0
10
12.1
Getafe - visitante
643    3
662    0
681    3
704    1
720    1
750    0
777    0
794    0
821    1
848    1
Name: FTR, dtype: object
1.0
Real Madrid - local
647    1
654    3
687    3
703    3
728    3
746    1
760    0
781    3
811    3
837    3
Name: FTR, dtype: object
2.3
23
18.0
Sociedad - visitante
641    3
665    3
690    0
713    3
738    0
742    3
757    1
767    0
788    3
818    0
Name: FTR, dtype: object
1.6
Granada - local
641     0
664     3
679     3
696     3
715     3
749     0
1529    0
1547    0
1569    0
1584    0
Name: FTR, dtype: object
1.2
7
10.5
Ath Madrid - visitante
648    1
660    1
682    1
705    3
726    0
741    3
764    1
786    0
816    3
839    0
Name: FTR, dtype: object
1.3
Betis - local
631    0
655    3
689    1
708    3
720    1
734    3
751    0
776    3
790    1
814    0
Name: FTR, dtype: object
1.5
15
15.3
Valencia - visitante
650    3
661    0
677    1
698    3
725    0
745    0
762    3
782    3
806    0
814    3
Name: FTR, dtype: object
1.6
Leganes - local
642    0
668    3
688    0
706    1
727    0
741    0
755    0
774    0
796    1
804    0
Name: FTR, dtype: object
0.5
4
12.1
Barcelona - visitante
649    0
678    3
697    3
715    0
737    1
759    0
761    1
787    0
809    3
827    1
Name: FTR, dtype: object
1.2
Levante - local
649    3
663    0
691    1
717    1
735    3
748    3
764    1
785    3
803    3
812    1
Name: FTR, dtype: object
1.9
20
12.5
Mallorca - visitante
646     0
668     0
692     0
714     0
733     0
3058    1
3076    0
3095    0
3128    0
3147    0
Name: FTR, dtype: object
0.1
Betis - local
655    3
689    1
708    3
720    1
734    3
751    0
776    3
790    1
814    0
834    3
Name: FTR, dtype: object
1.8
16
15.2
Sevilla - visitante
657    1
680    0
702    0
723    3
749    3
752    3
778    1
795    0
813    0
830    3
Name: FTR, dtype: object
1.4
Getafe - local
651    3
676    3
697    0
714    3
736    1
744    1
766    1
783    3
802    1
813    3
Name: FTR, dtype: object
1.9
18
10.5
Osasuna - visitante
652     1
679     0
691     1
703     0
721     1
755     3
1526    0
1542    0
1567    0
1589    0
Name: FTR, dtype: object
0.6
Ath Madrid - local
666    3
677    1
695    1
716    1
732    3
750    3
778    1
798    3
806    3
829    3
Name: FTR, dtype: object
2.2
14
11.2
Espanol - visitante
656    0
663    3
684    0
701    1
724    3
743    1
774    3
790    1
812    1
838    3
Name: FTR, dtype: object
1.6
Ath Bilbao - local
656    3
671    1
698    0
711    3
738    3
759    3
779    3
799    1
825    3
846    3
Name: FTR, dtype: object
2.3
19
13.0
Levante - visitante
658    3
670    0
688    3
708    0
728    0
753    0
775    3
797    0
822    0
846    0
Name: FTR, dtype: object
0.9
Mallorca - local
652     1
675     3
684     3
705     0
729     1
742     0
756     3
3044    3
3060    3
3083    1
Name: FTR, dtype: object
1.8
13
12.8
Villarreal - visitante
653    0
672    3
685    0
707    0
727    3
748    0
766    1
781    0
800    3
824    3
Name: FTR, dtype: object
1.3
Barcelona - local
659    3
680    3
707    3
725    3
740    3
777    3
797    3
818    3
839    3
857    3
Name: FTR, dtype: object
3.0
30
15.9
Celta - visitante
655    0
674    0
693    0
716    1
739    1
779    0
796    1
805    1
829    0
844    1
Name: FTR, dtype: object
0.5
Eibar - local
653    3
678    0
693    3
702    3
724    0
761    1
784    3
816    0
845    3
863    0
Name: FTR, dtype: object
1.6
14
12.5
Real Madrid - visitante
675    0
695    1
710    3
730    1
758    3
773    0
792    0
802    1
820    1
843    0
Name: FTR, dtype: object
1.0
Valencia - local
657    1
686    3
704    1
712    1
733    3
757    1
772    3
793    0
822    3
843    3
Name: FTR, dtype: object
1.9
18
11.6
Granada - visitante
651     0
687     0
709     1
722     3
731     3
754     1
1539    0
1556    0
1580    0
1605    1
Name: FTR, dtype: object
0.9
Alaves - local
660    1
674    3
692    3
723    0
743    1
753    3
769    3
788    0
809    0
819    1
Name: FTR, dtype: object
1.5
10
10.7
Valladolid - visitante
659    0
671    1
694    3
718    0
735    0
746    1
751    3
771    3
798    0
819    1
Name: FTR, dtype: object
1.2
Sociedad - local
658    0
673    3
681    0
700    3
726    3
773    3
794    3
800    0
823    1
840    3
Name: FTR, dtype: object
1.9
18
13.7
Leganes - visitante
654    0
676    0
696    0
712    1
734    0
765    0
789    3
810    0
835    1
855    3
Name: FTR, dtype: object
0.8
Granada - local
664     3
679     3
696     3
715     3
749     0
1529    0
1547    0
1569    0
1584    0
1594    0
Name: FTR, dtype: object
1.2
7
12.1
Sociedad - visitante
665    3
690    0
713    3
738    0
742    3
757    1
767    0
788    3
818    0
833    0
Name: FTR, dtype: object
1.3
Leganes - local
668    3
688    0
706    1
727    0
741    0
755    0
774    0
796    1
804    0
820    1
Name: FTR, dtype: object
0.6
4
11.4
Eibar - visitante
667    0
689    1
717    1
732    0
747    1
756    0
770    0
793    3
808    0
823    1
Name: FTR, dtype: object
0.7
Celta - local
665    0
683    3
701    1
722    0
745    3
758    0
768    1
787    3
817    3
833    3

Name: FTR, dtype: object
1.7
13
11.0
Getafe - visitante
662    0
681    3
704    1
720    1
750    0
777    0
794    0
821    1
848    1
861    1
Name: FTR, dtype: object
0.8
Osasuna - local
661     3
685     3
719     1
737     1
747     1
1539    3
1552    1
1577    1
1592    3
1618    0
Name: FTR, dtype: object
1.7
16
13.1
Alaves - visitante
669    0
686    0
700    0
711    0
736    1
772    0
799    1
828    0
841    0
867    3
Name: FTR, dtype: object
0.5
Villarreal - local
669    3
699    3
718    3
730    1
754    1
770    3
791    1
810    3
847    1
860    3
Name: FTR, dtype: object
2.2
28
14.4
Ath Bilbao - visitante
666    0
683    0
706    1
729    1
744    1
763    0
780    0
804    3
811    0
832    0
Name: FTR, dtype: object
0.6
Valladolid - local
667    3
682    1
709    1
721    1
762    0
780    3
807    3
821    1
830    0
851    1
Name: FTR, dtype: object
1.4
9
10.3
Mallorca - visitante
668     0
692     0
714     0
733     0
3058    1
3076    0
3095    0
3128    0
3147    0
3163    3
Name: FTR, dtype: object
0.4
Real Madrid - local
654    3
687    3
703    3
728    3
746    1
760    0
781    3
811    3
837    3
853    3
Name: FTR, dtype: object
2.5
26
17.4
Betis - visitante
664    0
673    0
699    0
719    1
740    0
760    3
784    0
803    0
826    0
840    0
Name: FTR, dtype: object
0.4
Sevilla - local
662    3
670    3
690    3
710    0
739    1
763    3
789    0
801    3
826    3
841    3
Name: FTR, dtype: object
2.2
19
14.8
Ath Madrid - visitante
660    1
682    1
705    3
726    0
741    3
764    1
786    0
816    3
839    0
858    3
Name: FTR, dtype: object
1.5
Levante - local
663    0
691    1
717    1
735    3
748    3
764    1
785    3
803    3
812    1
831    1
Name: FTR, dtype: object
1.7
19
13.0
Barcelona - visitante
678    3
697    3
715    0
737    1
759    0
761    1
787    0
809    3
827    1
847    1
Name: FTR, dtype: object
1.3
Espanol - local
672    0
694    0
713    0
731    0
752    0
767    3
786    3
805    1
828    3
848    1
Name: FTR, dtype: object
1.1
10
11.7
Valencia - visitante
661    0
677    1
698    3
725    0
745    0
762    3
782    3
806    0
814    3
836    0
Name: FTR, dtype: object
1.3
Getafe - local
676    3
697    0
714    3
736    1
744    1
766    1
783    3
802    1
813    3
832    3
Name: FTR, dtype: object
1.9
16
10.3
Granada - visitante
687     0
709     1
722     3
731     3
754     1
1539    0
1556    0
1580    0
1605    1
1621    0
Name: FTR, dtype: object
0.9
Mallorca - local
675     3
684     3
705     0
729     1
742     0
756     3
3044    3
3060    3
3083    1
3109    1
Name: FTR, dtype: object
1.8
12
12.8
Osasuna - visitante
679     0
691     1
703     0
721     1
755     3
1526    0
1542    0
1567    0
1589    0
1607    3
Name: FTR, dtype: object
0.8
Eibar - local
678    0
693    3
702    3
724    0
761    1
784    3
816    0
845    3
863    0
883    3
Name: FTR, dtype: object
1.6
13
11.5
Villarreal - visitante
672    3
685    0
707    0
727    3
748    0
766    1
781    0
800    3
824    3
834    0
Name: FTR, dtype: object
1.3
Real Madrid - local
687    3
703    3
728    3
746    1
760    0
781    3
811    3
837    3
853    3
865    3
Name: FTR, dtype: object
2.5
23
17.4
Leganes - visitante
676    0
696    0
712    1
734    0
765    0
789    3
810    0
835    1
855    3
877    0
Name: FTR, dtype: object
0.8
Betis - local
689    1
708    3
720    1
734    3
751    0
776    3
790    1
814    0
834    3
864    0
Name: FTR, dtype: object
1.5
15
15.4
Celta - visitante
674    0
693    0
716    1
739    1
779    0
796    1
805    1
829    0
844    1
865    0
Name: FTR, dtype: object
0.5
Ath Bilbao - local
671    1
698    0
711    3
738    3
759    3
779    3
799    1
825    3
846    3
868    3
Name: FTR, dtype: object
2.3
18
13.2
Espanol - visitante
663    3
684    0
701    1
724    3
743    1
774    3
790    1
812    1
838    3
857    0
Name: FTR, dtype: object
1.6
Valencia - local
686    3
704    1
712    1
733    3
757    1
772    3
793    0
822    3
843    3
861    1
Name: FTR, dtype: object
1.9
17
11.4
Sevilla - visitante
680    0
702    0
723    3
749    3
752    3
778    1
795    0
813    0
830    3
862    3
Name: FTR, dtype: object
1.6
Sociedad - local
673    3
681    0
700    3
726    3
773    3
794    3
800    0
823    1
840    3
869    1
Name: FTR, dtype: object
2.0
18
14.2
Levante - visitante
670    0
688    3
708    0
728    0
753    0
775    3
797    0
822    0
846    0
869    1
Name: FTR, dtype: object
0.7
Barcelona - local
680    3
707    3
725    3
740    3
777    3
797    3
818    3
839    3
857    3
876    3
Name: FTR, dtype: object
3.0
28
15.3
Valladolid - visitante
671    1
694    3
718    0
735    0
746    1
751    3
771    3
798    0
819    1
842    0
Name: FTR, dtype: object
1.2
Alaves - local
674    3
692    3
723    0
743    1
753    3
769    3
788    0
809    0
819    1
835    1
Name: FTR, dtype: object
1.5
10
10.2
Ath Madrid - visitante
682    1
705    3
726    0
741    3
764    1
786    0
816    3
839    0
858    3
868    0
Name: FTR, dtype: object
1.4
Osasuna - local
685     3
719     1
737     1
747     1
1539    3
1552    1
1577    1
1592    3
1618    0
1631    1
Name: FTR, dtype: object
1.5
14
12.0
Valencia - visitante
677    1
698    3
725    0
745    0
762    3
782    3
806    0
814    3
836    0
852    3
Name: FTR, dtype: object
1.6
Sevilla - local
670    3
690    3
710    0
739    1
763    3
789    0
801    3
826    3
841    3
852    0
Name: FTR, dtype: object
1.9
17
15.0
Getafe - visitante
681    3
704    1
720    1
750    0
777    0
794    0
821    1
848    1
861    1
884    3
Name: FTR, dtype: object
1.1
Levante - local
691    1
717    1
735    3
748    3
764    1
785    3
803    3
812    1
831    1
854    1
Name: FTR, dtype: object
1.8
21
13.0
Espanol - visitante
684    0
701    1
724    3
743    1
774    3
790    1
812    1
838    3
857    0
879    1
Name: FTR, dtype: object
1.4
Granada - local
679     3
696     3
715     3
749     0
1529    0
1547    0
1569    0
1584    0
1594    0
1615    0
Name: FTR, dtype: object
0.9
7
11.5
Betis - visitante
673    0
699    0
719    1
740    0
760    3
784    0
803    0
826    0
840    0
850    1
Name: FTR, dtype: object
0.5
Celta - local
683    3
701    1
722    0
745    3
758    0
768    1
787    3
817    3
833    3
856    3
Name: FTR, dtype: object
2.0
16
11.6
Sociedad - visitante
690    0
713    3
738    0
742    3
757    1
767    0
788    3
818    0
833    0
851    1
Name: FTR, dtype: object
1.1
Ath Madrid - local
677    1
695    1
716    1
732    3
750    3
778    1
798    3
806    3
829    3
849    3
Name: FTR, dtype: object
2.2
14
12.0
Ath Bilbao - visitante
683    0
706    1
729    1
744    1
763    0
780    0
804    3
811    0
832    0
859    3
Name: FTR, dtype: object
0.9
Valladolid - local
682    1
709    1
721    1
762    0
780    3
807    3
821    1
830    0
851    1
870    0
Name: FTR, dtype: object
1.1
8
10.5
Eibar - visitante
689    1
717    1
732    0
747    1
756    0
770    0
793    3
808    0
823    1
837    0
Name: FTR, dtype: object
0.7
Leganes - local
688    0
706    1
727    0
741    0
755    0
774    0
796    1
804    0
820    1
842    3
Name: FTR, dtype: object
0.6
4
12.3
Mallorca - visitante
692     0
714     0
733     0
3058    1
3076    0
3095    0
3128    0
3147    0
3163    3
3181    0
Name: FTR, dtype: object
0.4
Villarreal - local
699    3
718    3
730    1
754    1
770    3
791    1
810    3
847    1
860    3
885    0
Name: FTR, dtype: object
1.9
25
13.4
Alaves - visitante
686    0
700    0
711    0
736    1
772    0
799    1
828    0
841    0
867    3
885    3
Name: FTR, dtype: object
0.8
Sevilla - local
690    3
710    0
739    1
763    3
789    0
801    3
826    3
841    3
852    0
871    3
Name: FTR, dtype: object
1.9
21
15.3
Levante - visitante
688    3
708    0
728    0
753    0
775    3
797    0
822    0
846    0
869    1
880    0
Name: FTR, dtype: object
0.7
Ath Bilbao - local
698    0
711    3
738    3
759    3
779    3
799    1
825    3
846    3
868    3
879    1
Name: FTR, dtype: object
2.3
18
12.8
Valladolid - visitante
694    3
718    0
735    0
746    1
751    3
771    3
798    0
819    1
842    0
863    3
Name: FTR, dtype: object
1.4
Espanol - local
694    0
713    0
731    0
752    0
767    3
786    3
805    1
828    3
848    1
862    0
Name: FTR, dtype: object
1.1
10
11.2
Villarreal - visitante
685    0
707    0
727    3
748    0
766    1
781    0
800    3
824    3
834    0
856    0
Name: FTR, dtype: object
1.0
Sociedad - local
681    0
700    3
726    3
773    3
794    3
800    0
823    1
840    3
869    1
882    0
Name: FTR, dtype: object
1.7
15
14.3
Betis - visitante
699    0
719    1
740    0
760    3
784    0
803    0
826    0
840    0
850    1
874    3
Name: FTR, dtype: object
0.8
Alaves - local
692    3
723    0
743    1
753    3
769    3
788    0
809    0
819    1
835    1
858    0
Name: FTR, dtype: object
1.2
8
10.4
Celta - visitante
693    0
716    1
739    1
779    0
796    1
805    1
829    0
844    1
865    0
883    0
Name: FTR, dtype: object
0.5
Mallorca - local
684     3
705     0
729     1
742     0
756     3
3044    3
3060    3
3083    1
3109    1
3110    3
Name: FTR, dtype: object
1.8
12
13.7
Real Madrid - visitante
695    1
710    3
730    1
758    3
773    0
792    0
802    1
820    1
843    0
870    3
Name: FTR, dtype: object
1.3
Getafe - local
697    0
714    3
736    1
744    1
766    1
783    3
802    1
813    3
832    3
855    0
Name: FTR, dtype: object
1.6
14
10.7
Leganes - visitante
696    0
712    1
734    0
765    0
789    3
810    0
835    1
855    3
877    0
906    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
695    1
716    1
732    3
750    3
778    1
798    3
806    3
829    3
849    3
877    3
Name: FTR, dtype: object
2.4
14
11.8
Valencia - visitante
698    3
725    0
745    0
762    3
782    3
806    0
814    3
836    0
852    3
873    3
Name: FTR, dtype: object
1.8
Eibar - local
693    3
702    3
724    0
761    1
784    3
816    0
845    3
863    0
883    3
909    1
Name: FTR, dtype: object
1.7
15
12.1
Barcelona - visitante
697    3
715    0
737    1
759    0
761    1
787    0
809    3
827    1
847    1
864    3
Name: FTR, dtype: object
1.3
Granada - local
696     3
715     3
749     0
1529    0
1547    0
1569    0
1584    0
1594    0
1615    0
1639    0
Name: FTR, dtype: object
0.6
6
12.1
Osasuna - visitante
691     1
703     0
721     1
755     3
1526    0
1542    0
1567    0
1589    0
1607    3
1627    0
Name: FTR, dtype: object
0.8
Barcelona - local
707    3
725    3
740    3
777    3
797    3
818    3
839    3
857    3
876    3
908    3
Name: FTR, dtype: object
3.0
25
15.8
Sevilla - visitante
702    0
723    3
749    3
752    3
778    1
795    0
813    0
830    3
862    3
887    0
Name: FTR, dtype: object
1.6
Sociedad - local
700    3
726    3
773    3
794    3
800    0
823    1
840    3
869    1
882    0
906    3
Name: FTR, dtype: object
2.0
17
15.2
Getafe - visitante
704    1
720    1
750    0
777    0
794    0
821    1
848    1
861    1
884    3
909    1
Name: FTR, dtype: object
0.9
Valladolid - local
709    1
721    1
762    0
780    3
807    3
821    1
830    0
851    1
870    0
891    0
Name: FTR, dtype: object
1.0
8
11.0
Ath Madrid - visitante
705    3
726    0
741    3
764    1
786    0
816    3
839    0
858    3
868    0
882    3
Name: FTR, dtype: object
1.6
Celta - local
701    1
722    0
745    3
758    0
768    1
787    3
817    3
833    3
856    3
874    0
Name: FTR, dtype: object
1.7
15
11.0
Ath Bilbao - visitante
706    1
729    1
744    1
763    0
780    0
804    3
811    0
832    0
859    3
881    0
Name: FTR, dtype: object
0.9
Mallorca - local
705     0
729     1
742     0
756     3
3044    3
3060    3
3083    1
3109    1
3110    3
3133    0
Name: FTR, dtype: object
1.5
12
14.8
Espanol - visitante
701    1
724    3
743    1
774    3
790    1
812    1
838    3
857    0
879    1
902    1
Name: FTR, dtype: object
1.5
Osasuna - local
719     1
737     1
747     1
1539    3
1552    1
1577    1
1592    3
1618    0
1631    1
1655    0
Name: FTR, dtype: object
1.2
13
12.1
Villarreal - visitante
707    0
727    3
748    0
766    1
781    0
800    3
824    3
834    0
856    0
872    3
Name: FTR, dtype: object
1.3
Valencia - local
704    1
712    1
733    3
757    1
772    3
793    0
822    3
843    3
861    1
881    3
Name: FTR, dtype: object
1.9
17
11.4
Alaves - visitante
700    0
711    0
736    1
772    0
799    1
828    0
841    0
867    3
885    3
904    1
Name: FTR, dtype: object
0.9

Real Madrid - local
703    3
728    3
746    1
760    0
781    3
811    3
837    3
853    3
865    3
886    0
Name: FTR, dtype: object
2.2
19
17.4
Granada - visitante
709     1
722     3
731     3
754     1
1539    0
1556    0
1580    0
1605    1
1621    0
1648    0
Name: FTR, dtype: object
0.9
Leganes - local
706    1
727    0
741    0
755    0
774    0
796    1
804    0
820    1
842    3
866    0
Name: FTR, dtype: object
0.6
3
11.0
Levante - visitante
708    0
728    0
753    0
775    3
797    0
822    0
846    0
869    1
880    0
907    3
Name: FTR, dtype: object
0.7
Betis - local
708    3
720    1
734    3
751    0
776    3
790    1
814    0
834    3
864    0
884    0
Name: FTR, dtype: object
1.4
15
14.8
Eibar - visitante
717    1
732    0
747    1
756    0
770    0
793    3
808    0
823    1
837    0
854    1
Name: FTR, dtype: object
0.7
Sevilla - local
710    0
739    1
763    3
789    0
801    3
826    3
841    3
852    0
871    3
895    0
Name: FTR, dtype: object
1.6
20
14.5
Sociedad - visitante
713    3
738    0
742    3
757    1
767    0
788    3
818    0
833    0
851    1
871    0
Name: FTR, dtype: object
1.1
Levante - local
717    1
735    3
748    3
764    1
785    3
803    3
812    1
831    1
854    1
872    0
Name: FTR, dtype: object
1.7
20
13.1
Osasuna - visitante
703     0
721     1
755     3
1526    0
1542    0
1567    0
1589    0
1607    3
1627    0
1644    0
Name: FTR, dtype: object
0.7
Alaves - local
723    0
743    1
753    3
769    3
788    0
809    0
819    1
835    1
858    0
878    1
Name: FTR, dtype: object
1.0
7
10.9
Mallorca - visitante
714     0
733     0
3058    1
3076    0
3095    0
3128    0
3147    0
3163    3
3181    0
3201    0
Name: FTR, dtype: object
0.4
Eibar - local
702    3
724    0
761    1
784    3
816    0
845    3
863    0
883    3
909    1
923    3
Name: FTR, dtype: object
1.7
16
13.1
Celta - visitante
716    1
739    1
779    0
796    1
805    1
829    0
844    1
865    0
883    0
898    1
Name: FTR, dtype: object
0.6
Espanol - local
713    0
731    0
752    0
767    3
786    3
805    1
828    3
848    1
862    0
888    3
Name: FTR, dtype: object
1.4
13
11.1
Valladolid - visitante
718    0
735    0
746    1
751    3
771    3
798    0
819    1
842    0
863    3
888    0
Name: FTR, dtype: object
1.1
Ath Madrid - local
716    1
732    3
750    3
778    1
798    3
806    3
829    3
849    3
877    3
894    3
Name: FTR, dtype: object
2.6
16
12.6
Real Madrid - visitante
710    3
730    1
758    3
773    0
792    0
802    1
820    1
843    0
870    3
892    3
Name: FTR, dtype: object
1.5
Granada - local
715     3
749     0
1529    0
1547    0
1569    0
1584    0
1594    0
1615    0
1639    0
1656    3
Name: FTR, dtype: object
0.6
7
12.3
Leganes - visitante
712    1
734    0
765    0
789    3
810    0
835    1
855    3
877    0
906    0
920    3
Name: FTR, dtype: object
1.1
Getafe - local
714    3
736    1
744    1
766    1
783    3
802    1
813    3
832    3
855    0
875    3
Name: FTR, dtype: object
1.9
16
11.3
Barcelona - visitante
715    0
737    1
759    0
761    1
787    0
809    3
827    1
847    1
864    3
886    3
Name: FTR, dtype: object
1.3
Ath Bilbao - local
711    3
738    3
759    3
779    3
799    1
825    3
846    3
868    3
879    1
897    3
Name: FTR, dtype: object
2.6
19
12.3
Valencia - visitante
725    0
745    0
762    3
782    3
806    0
814    3
836    0
852    3
873    3
893    1
Name: FTR, dtype: object
1.6
Villarreal - local
718    3
730    1
754    1
770    3
791    1
810    3
847    1
860    3
885    0
901    3
Name: FTR, dtype: object
1.9
23
12.9
Betis - visitante
719    1
740    0
760    3
784    0
803    0
826    0
840    0
850    1
874    3
891    3
Name: FTR, dtype: object
1.1
Sociedad - local
726    3
773    3
794    3
800    0
823    1
840    3
869    1
882    0
906    3
925    3
Name: FTR, dtype: object
2.0
16
13.7
Alaves - visitante
711    0
736    1
772    0
799    1
828    0
841    0
867    3
885    3
904    1
922    0
Name: FTR, dtype: object
0.9
Celta - local
722    0
745    3
758    0
768    1
787    3
817    3
833    3
856    3
874    0
907    0
Name: FTR, dtype: object
1.6
15
11.0
Espanol - visitante
724    3
743    1
774    3
790    1
812    1
838    3
857    0
879    1
902    1
921    1
Name: FTR, dtype: object
1.5
Eibar - local
724    0
761    1
784    3
816    0
845    3
863    0
883    3
909    1
923    3
940    3
Name: FTR, dtype: object
1.7
16
13.6
Sevilla - visitante
723    3
749    3
752    3
778    1
795    0
813    0
830    3
862    3
887    0
901    0
Name: FTR, dtype: object
1.6
Real Madrid - local
728    3
746    1
760    0
781    3
811    3
837    3
853    3
865    3
886    0
903    0
Name: FTR, dtype: object
1.9
18
17.8
Osasuna - visitante
721     1
755     3
1526    0
1542    0
1567    0
1589    0
1607    3
1627    0
1644    0
1664    0
Name: FTR, dtype: object
0.7
Valencia - local
712    1
733    3
757    1
772    3
793    0
822    3
843    3
861    1
881    3
902    1
Name: FTR, dtype: object
1.9
14
12.7
Getafe - visitante
720    1
750    0
777    0
794    0
821    1
848    1
861    1
884    3
909    1
926    1
Name: FTR, dtype: object
0.9
Mallorca - local
729     1
742     0
756     3
3044    3
3060    3
3083    1
3109    1
3110    3
3133    0
3157    3
Name: FTR, dtype: object
1.8
14
14.9
Ath Madrid - visitante
726    0
741    3
764    1
786    0
816    3
839    0
858    3
868    0
882    3
905    3
Name: FTR, dtype: object
1.6
Leganes - local
727    0
741    0
755    0
774    0
796    1
804    0
820    1
842    3
866    0
880    3
Name: FTR, dtype: object
0.8
3
11.7
Ath Bilbao - visitante
729    1
744    1
763    0
780    0
804    3
811    0
832    0
859    3
881    0
900    3
Name: FTR, dtype: object
1.1
Barcelona - local
725    3
740    3
777    3
797    3
818    3
839    3
857    3
876    3
908    3
928    1
Name: FTR, dtype: object
2.8
25
17.0
Villarreal - visitante
727    3
748    0
766    1
781    0
800    3
824    3
834    0
856    0
872    3
894    0
Name: FTR, dtype: object
1.3
Betis - local
720    1
734    3
751    0
776    3
790    1
814    0
834    3
864    0
884    0
904    1
Name: FTR, dtype: object
1.2
13
15.0
Levante - visitante
728    0
753    0
775    3
797    0
822    0
846    0
869    1
880    0
907    3
910    0
Name: FTR, dtype: object
0.7
Valladolid - local
721    1
762    0
780    3
807    3
821    1
830    0
851    1
870    0
891    0
919    1
Name: FTR, dtype: object
1.0
7
11.0
Granada - visitante
722     3
731     3
754     1
1539    0
1556    0
1580    0
1605    1
1621    0
1648    0
1666    0
Name: FTR, dtype: object
0.8
Sevilla - local
739    1
763    3
789    0
801    3
826    3
841    3
852    0
871    3
895    0
912    1
Name: FTR, dtype: object
1.7
22
14.9
Real Madrid - visitante
730    1
758    3
773    0
792    0
802    1
820    1
843    0
870    3
892    3
918    3
Name: FTR, dtype: object
1.5
Ath Bilbao - local
738    3
759    3
779    3
799    1
825    3
846    3
868    3
879    1
897    3
914    1
Name: FTR, dtype: object
2.4
17
12.3
Alaves - visitante
736    1
772    0
799    1
828    0
841    0
867    3
885    3
904    1
922    0
949    0
Name: FTR, dtype: object
0.9
Valencia - local
733    3
757    1
772    3
793    0
822    3
843    3
861    1
881    3
902    1
911    1
Name: FTR, dtype: object
1.9
13
12.4
Leganes - visitante
734    0
765    0
789    3
810    0
835    1
855    3
877    0
906    0
920    3
945    0
Name: FTR, dtype: object
1.0
Espanol - local
731    0
752    0
767    3
786    3
805    1
828    3
848    1
862    0
888    3
899    1
Name: FTR, dtype: object
1.5
13
10.7
Sociedad - visitante
738    0
742    3
757    1
767    0
788    3
818    0
833    0
851    1
871    0
890    1
Name: FTR, dtype: object
0.9
Getafe - local
736    1
744    1
766    1
783    3
802    1
813    3
832    3
855    0
875    3
896    3
Name: FTR, dtype: object
1.9
14
11.0
Mallorca - visitante
733     0
3058    1
3076    0
3095    0
3128    0
3147    0
3163    3
3181    0
3201    0
3229    0
Name: FTR, dtype: object
0.4
Granada - local
749     0
1529    0
1547    0
1569    0
1584    0
1594    0
1615    0
1639    0
1656    3
1682    3
Name: FTR, dtype: object
0.6
9
12.4
Barcelona - visitante
737    1
759    0
761    1
787    0
809    3
827    1
847    1
864    3
886    3
895    3
Name: FTR, dtype: object
1.6
Ath Madrid - local
732    3
750    3
778    1
798    3
806    3
829    3
849    3
877    3
894    3
918    0
Name: FTR, dtype: object
2.5
17
11.7
Celta - visitante
739    1
779    0
796    1
805    1
829    0
844    1
865    0
883    0
898    1
916    0
Name: FTR, dtype: object
0.5
Levante - local
735    3
748    3
764    1
785    3
803    3
812    1
831    1
854    1
872    0
892    0
Name: FTR, dtype: object
1.6
21
12.9
Eibar - visitante
732    0
747    1
756    0
770    0
793    3
808    0
823    1
837    0
854    1
878    1
Name: FTR, dtype: object
0.7
Villarreal - local
730    1
754    1
770    3
791    1
810    3
847    1
860    3
885    0
901    3
921    1
Name: FTR, dtype: object
1.7
23
12.5
Valladolid - visitante
735    0
746    1
751    3
771    3
798    0
819    1
842    0
863    3
888    0
908    0
Name: FTR, dtype: object
1.1
Osasuna - local
737     1
747     1
1539    3
1552    1
1577    1
1592    3
1618    0
1631    1
1655    0
1688    0
Name: FTR, dtype: object
1.1
14
12.0
Betis - visitante
740    0
760    3
784    0
803    0
826    0
840    0
850    1
874    3
891    3
913    0
Name: FTR, dtype: object
1.0
Betis - local
734    3
751    0
776    3
790    1
814    0
834    3
864    0
884    0
904    1
924    3
Name: FTR, dtype: object
1.4
13
15.0
Getafe - visitante
750    0
777    0
794    0
821    1
848    1
861    1
884    3
909    1
926    1
939    0
Name: FTR, dtype: object
0.8
Valladolid - local
762    0
780    3
807    3
821    1
830    0
851    1
870    0
891    0
919    1
931    3
Name: FTR, dtype: object
1.2
8
11.8
Osasuna - visitante
755     3
1526    0
1542    0
1567    0
1589    0
1607    3
1627    0
1644    0
1664    0
1676    0
Name: FTR, dtype: object
0.6
Celta - local
745    3
758    0
768    1
787    3
817    3
833    3
856    3
874    0
907    0
927    3
Name: FTR, dtype: object
1.9
16
11.6
Granada - visitante
731     3
754     1
1539    0
1556    0
1580    0
1605    1
1621    0
1648    0
1666    0
1683    0
Name: FTR, dtype: object
0.5
Alaves - local
743    1
753    3
769    3
788    0
809    0
819    1
835    1
858    0
878    1
898    1
Name: FTR, dtype: object
1.1
7
11.9
Sevilla - visitante
749    3
752    3
778    1
795    0
813    0
830    3
862    3
887    0
901    0
927    0
Name: FTR, dtype: object
1.3
Eibar - local
761    1
784    3
816    0
845    3
863    0
883    3
909    1
923    3
940    3
964    1
Name: FTR, dtype: object
1.8
15
14.9
Espanol - visitante
743    1
774    3
790    1
812    1
838    3
857    0
879    1
902    1
921    1
940    0
Name: FTR, dtype: object
1.2
Barcelona - local
740    3
777    3
797    3
818    3
839    3
857    3
876    3
908    3
928    1
945    3
Name: FTR, dtype: object
2.8
23
16.8
Valencia - visitante
745    0
762    3
782    3
806    0
814    3
836    0
852    3
873    3
893    1
928    1
Name: FTR, dtype: object
1.7
Sociedad - local
773    3
794    3
800    0
823    1
840    3
869    1
882    0
906    3
925    3
932    1
Name: FTR, dtype: object
1.8
14
13.1
Ath Madrid - visitante
741    3
764    1
786    0
816    3
839    0
858    3
868    0
882    3
905    3
924    0
Name: FTR, dtype: object
1.6
Leganes - local
741    0
755    0
774    0
796    1
804    0
820    1
842    3
866    0
880    3
893    1
Name: FTR, dtype: object
0.9
4
12.4
Villarreal - visitante
748    0
766    1
781    0
800    3
824    3
834    0
856    0
872    3
894    0
919    1
Name: FTR, dtype: object
1.1
Real Madrid - local
746    1
760    0
781    3
811    3
837    3
853    3
865    3
886    0
903    0
922    3
Name: FTR, dtype: object
1.9
18
17.5
Levante - visitante
753    0
775    3
797    0
822    0
846    0
869    1
880    0
907    3
910    0
937    0
Name: FTR, dtype: object
0.7
Mallorca - local
742     0
756     3
3044    3
3060    3
3083    1
3109    1
3110    3
3133    0
3157    3
3176    0
Name: FTR, dtype: object
1.7
15
15.4
Ath Bilbao - visitante
744    1
763    0
780    0
804    3
811    0
832    0
859    3
881    0
900    3
925    0
Name: FTR, dtype: object
1.0
Villarreal - local
754    1
770    3
791    1
810    3
847    1
860    3
885    0
901    3
921    1
941    1
Name: FTR, dtype: object
1.7
22
11.8
Real Madrid - visitante
758    3
773    0
792    0
802    1
820    1
843    0
870    3
892    3
918    3
934    3

Name: FTR, dtype: object
1.7
Espanol - local
752    0
767    3
786    3
805    1
828    3
848    1
862    0
888    3
899    1
917    3
Name: FTR, dtype: object
1.8
15
10.7
Granada - visitante
754     1
1539    0
1556    0
1580    0
1605    1
1621    0
1648    0
1666    0
1683    0
1706    0
Name: FTR, dtype: object
0.2
Ath Madrid - local
750    3
778    1
798    3
806    3
829    3
849    3
877    3
894    3
918    0
939    3
Name: FTR, dtype: object
2.5
16
12.0
Eibar - visitante
747    1
756    0
770    0
793    3
808    0
823    1
837    0
854    1
878    1
897    0
Name: FTR, dtype: object
0.7
Valencia - local
757    1
772    3
793    0
822    3
843    3
861    1
881    3
902    1
911    1
936    3
Name: FTR, dtype: object
1.9
14
13.3
Mallorca - visitante
3058    1
3076    0
3095    0
3128    0
3147    0
3163    3
3181    0
3201    0
3229    0
3235    0
Name: FTR, dtype: object
0.4
Betis - local
751    0
776    3
790    1
814    0
834    3
864    0
884    0
904    1
924    3
944    3
Name: FTR, dtype: object
1.4
14
14.5
Leganes - visitante
765    0
789    3
810    0
835    1
855    3
877    0
906    0
920    3
945    0
969    0
Name: FTR, dtype: object
1.0
Levante - local
748    3
764    1
785    3
803    3
812    1
831    1
854    1
872    0
892    0
926    1
Name: FTR, dtype: object
1.4
19
12.1
Valladolid - visitante
746    1
751    3
771    3
798    0
819    1
842    0
863    3
888    0
908    0
929    0
Name: FTR, dtype: object
1.1
Getafe - local
744    1
766    1
783    3
802    1
813    3
832    3
855    0
875    3
896    3
916    3
Name: FTR, dtype: object
2.1
16
10.7
Alaves - visitante
772    0
799    1
828    0
841    0
867    3
885    3
904    1
922    0
949    0
958    1
Name: FTR, dtype: object
0.9
Osasuna - local
747     1
1539    3
1552    1
1577    1
1592    3
1618    0
1631    1
1655    0
1688    0
1710    1
Name: FTR, dtype: object
1.1
13
11.9
Barcelona - visitante
759    0
761    1
787    0
809    3
827    1
847    1
864    3
886    3
895    3
914    1
Name: FTR, dtype: object
1.6
Ath Bilbao - local
759    3
779    3
799    1
825    3
846    3
868    3
879    1
897    3
914    1
935    3
Name: FTR, dtype: object
2.4
16
11.9
Sociedad - visitante
742    3
757    1
767    0
788    3
818    0
833    0
851    1
871    0
890    1
911    1
Name: FTR, dtype: object
1.0
Sevilla - local
763    3
789    0
801    3
826    3
841    3
852    0
871    3
895    0
912    1
937    3
Name: FTR, dtype: object
1.9
26
15.3
Celta - visitante
779    0
796    1
805    1
829    0
844    1
865    0
883    0
898    1
916    0
931    0
Name: FTR, dtype: object
0.4
Barcelona - local
777    3
797    3
818    3
839    3
857    3
876    3
908    3
928    1
945    3
952    3
Name: FTR, dtype: object
2.8
21
15.5
Betis - visitante
760    3
784    0
803    0
826    0
840    0
850    1
874    3
891    3
913    0
935    0
Name: FTR, dtype: object
1.0
Leganes - local
755    0
774    0
796    1
804    0
820    1
842    3
866    0
880    3
893    1
913    3
Name: FTR, dtype: object
1.2
7
13.0
Ath Madrid - visitante
764    1
786    0
816    3
839    0
858    3
868    0
882    3
905    3
924    0
947    3
Name: FTR, dtype: object
1.6
Mallorca - local
756     3
3044    3
3060    3
3083    1
3109    1
3110    3
3133    0
3157    3
3176    0
3196    1
Name: FTR, dtype: object
1.8
16
15.4
Sociedad - visitante
757    1
767    0
788    3
818    0
833    0
851    1
871    0
890    1
911    1
942    1
Name: FTR, dtype: object
0.8
Alaves - local
753    3
769    3
788    0
809    0
819    1
835    1
858    0
878    1
898    1
910    3
Name: FTR, dtype: object
1.3
9
12.5
Espanol - visitante
774    3
790    1
812    1
838    3
857    0
879    1
902    1
921    1
940    0
950    0
Name: FTR, dtype: object
1.1
Getafe - local
766    1
783    3
802    1
813    3
832    3
855    0
875    3
896    3
916    3
949    3
Name: FTR, dtype: object
2.3
19
11.3
Ath Bilbao - visitante
763    0
780    0
804    3
811    0
832    0
859    3
881    0
900    3
925    0
941    1
Name: FTR, dtype: object
1.0
Celta - local
758    0
768    1
787    3
817    3
833    3
856    3
874    0
907    0
927    3
948    0
Name: FTR, dtype: object
1.6
16
11.7
Valencia - visitante
762    3
782    3
806    0
814    3
836    0
852    3
873    3
893    1
928    1
948    3
Name: FTR, dtype: object
2.0
Real Madrid - local
760    0
781    3
811    3
837    3
853    3
865    3
886    0
903    0
922    3
946    3
Name: FTR, dtype: object
2.1
19
17.6
Valladolid - visitante
751    3
771    3
798    0
819    1
842    0
863    3
888    0
908    0
929    0
943    0
Name: FTR, dtype: object
1.0
Osasuna - local
1539    3
1552    1
1577    1
1592    3
1618    0
1631    1
1655    0
1688    0
1710    1
1712    0
Name: FTR, dtype: object
1.0
16
12.7
Eibar - visitante
756    0
770    0
793    3
808    0
823    1
837    0
854    1
878    1
897    0
912    1
Name: FTR, dtype: object
0.7
Levante - local
764    1
785    3
803    3
812    1
831    1
854    1
872    0
892    0
926    1
943    3
Name: FTR, dtype: object
1.4
19
11.8
Villarreal - visitante
766    1
781    0
800    3
824    3
834    0
856    0
872    3
894    0
919    1
936    0
Name: FTR, dtype: object
1.1
Granada - local
1529    0
1547    0
1569    0
1584    0
1594    0
1615    0
1639    0
1656    3
1682    3
1693    3
Name: FTR, dtype: object
0.9
10
12.4
Sevilla - visitante
752    3
778    1
795    0
813    0
830    3
862    3
887    0
901    0
927    0
946    0
Name: FTR, dtype: object
1.0
Ath Madrid - local
778    1
798    3
806    3
829    3
849    3
877    3
894    3
918    0
939    3
953    3
Name: FTR, dtype: object
2.5
16
13.4
Getafe - visitante
777    0
794    0
821    1
848    1
861    1
884    3
909    1
926    1
939    0
955    3
Name: FTR, dtype: object
1.1
Betis - local
776    3
790    1
814    0
834    3
864    0
884    0
904    1
924    3
944    3
951    0
Name: FTR, dtype: object
1.4
14
14.1
Valladolid - visitante
771    3
798    0
819    1
842    0
863    3
888    0
908    0
929    0
943    0
956    1
Name: FTR, dtype: object
0.8
Espanol - local
767    3
786    3
805    1
828    3
848    1
862    0
888    3
899    1
917    3
934    0
Name: FTR, dtype: object
1.8
17
11.3
Sevilla - visitante
778    1
795    0
813    0
830    3
862    3
887    0
901    0
927    0
946    0
954    0
Name: FTR, dtype: object
0.7
Alaves - local
769    3
788    0
809    0
819    1
835    1
858    0
878    1
898    1
910    3
930    0
Name: FTR, dtype: object
1.0
8
13.2
Levante - visitante
775    3
797    0
822    0
846    0
869    1
880    0
907    3
910    0
937    0
953    0
Name: FTR, dtype: object
0.7
Villarreal - local
770    3
791    1
810    3
847    1
860    3
885    0
901    3
921    1
941    1
955    0
Name: FTR, dtype: object
1.6
19
12.3
Granada - visitante
1539    0
1556    0
1580    0
1605    1
1621    0
1648    0
1666    0
1683    0
1706    0
1718    0
Name: FTR, dtype: object
0.1
Leganes - local
774    0
796    1
804    0
820    1
842    3
866    0
880    3
893    1
913    3
938    1
Name: FTR, dtype: object
1.3
9
12.6
Osasuna - visitante
1526    0
1542    0
1567    0
1589    0
1607    3
1627    0
1644    0
1664    0
1676    0
1695    0
Name: FTR, dtype: object
0.3
Mallorca - local
3044    3
3060    3
3083    1
3109    1
3110    3
3133    0
3157    3
3176    0
3196    1
3213    0
Name: FTR, dtype: object
1.5
16
16.1
Eibar - visitante
770    0
793    3
808    0
823    1
837    0
854    1
878    1
897    0
912    1
938    1
Name: FTR, dtype: object
0.8
Valencia - local
772    3
793    0
822    3
843    3
861    1
881    3
902    1
911    1
936    3
956    1
Name: FTR, dtype: object
1.9
14
13.6
Sociedad - visitante
767    0
788    3
818    0
833    0
851    1
871    0
890    1
911    1
942    1
962    3
Name: FTR, dtype: object
1.0
Celta - local
768    1
787    3
817    3
833    3
856    3
874    0
907    0
927    3
948    0
960    0
Name: FTR, dtype: object
1.6
16
12.7
Real Madrid - visitante
773    0
792    0
802    1
820    1
843    0
870    3
892    3
918    3
934    3
951    3
Name: FTR, dtype: object
1.7
Ath Bilbao - local
779    3
799    1
825    3
846    3
868    3
879    1
897    3
914    1
935    3
954    3
Name: FTR, dtype: object
2.4
17
11.8
Barcelona - visitante
761    1
787    0
809    3
827    1
847    1
864    3
886    3
895    3
914    1
933    3
Name: FTR, dtype: object
1.9
Real Madrid - local
781    3
811    3
837    3
853    3
865    3
886    0
903    0
922    3
946    3
962    0
Name: FTR, dtype: object
2.1
19
19.5
Betis - visitante
784    0
803    0
826    0
840    0
850    1
874    3
891    3
913    0
935    0
966    0
Name: FTR, dtype: object
0.7
Eibar - local
784    3
816    0
845    3
863    0
883    3
909    1
923    3
940    3
964    1
988    1
Name: FTR, dtype: object
1.8
14
15.2
Barcelona - visitante
787    0
809    3
827    1
847    1
864    3
886    3
895    3
914    1
933    3
963    3
Name: FTR, dtype: object
2.1
Valladolid - local
780    3
807    3
821    1
830    0
851    1
870    0
891    0
919    1
931    3
965    0
Name: FTR, dtype: object
1.2
8
11.1
Valencia - visitante
782    3
806    0
814    3
836    0
852    3
873    3
893    1
928    1
948    3
967    0
Name: FTR, dtype: object
1.7
Sevilla - local
789    0
801    3
826    3
841    3
852    0
871    3
895    0
912    1
937    3
961    1
Name: FTR, dtype: object
1.7
25
15.9
Ath Bilbao - visitante
780    0
804    3
811    0
832    0
859    3
881    0
900    3
925    0
941    1
960    3
Name: FTR, dtype: object
1.3
Levante - local
785    3
803    3
812    1
831    1
854    1
872    0
892    0
926    1
943    3
968    1
Name: FTR, dtype: object
1.4
19
12.0
Ath Madrid - visitante
786    0
816    3
839    0
858    3
868    0
882    3
905    3
924    0
947    3
961    1
Name: FTR, dtype: object
1.6
Huesca - local
782    0
808    3
827    1
844    1
867    0
887    3
900    0
929    3
947    0
966    3
Name: FTR, dtype: object
1.4
16
12.7
Leganes - visitante
789    3
810    0
835    1
855    3
877    0
906    0
920    3
945    0
969    0
989    1
Name: FTR, dtype: object
1.1
Getafe - local
783    3
802    1
813    3
832    3
855    0
875    3
896    3
916    3
949    3
963    0
Name: FTR, dtype: object
2.2
18
10.6
Villarreal - visitante
781    0
800    3
824    3
834    0
856    0
872    3
894    0
919    1
936    0
964    1
Name: FTR, dtype: object
1.1
Espanol - local
786    3
805    1
828    3
848    1
862    0
888    3
899    1
917    3
934    0
969    3
Name: FTR, dtype: object
1.8
16
11.6
Sociedad - visitante
788    3
818    0
833    0
851    1
871    0
890    1
911    1
942    1
962    3
987    0
Name: FTR, dtype: object
1.0
Celta - local
787    3
817    3
833    3
856    3
874    0
907    0
927    3
948    0
960    0
989    1
Name: FTR, dtype: object
1.6
14
12.8
Vallecano - visitante
785    0
801    0
825    0
845    0
860    0
876    0
896    0
917    0
930    3
965    3
Name: FTR, dtype: object
0.6
Alaves - local
788    0
809    0
819    1
835    1
858    0
878    1
898    1
910    3
930    0
967    3
Name: FTR, dtype: object
1.0
8
13.2
Girona - visitante
783    0
807    0
817    0
849    0
866    3
889    3
903    3
923    0
944    0
968    1
Name: FTR, dtype: object
1.0
Villarreal - local
791    1
810    3
847    1
860    3
885    0
901    3
921    1
941    1
955    0
970    1
Name: FTR, dtype: object
1.4
20
12.4
Eibar - visitante
793    3
808    0
823    1
837    0
854    1
878    1
897    0
912    1
938    1
952    0
Name: FTR, dtype: object
0.8
Vallecano - local
792    3
815    1
836    3
850    1
889    0
905    0
920    0
942    1
959    3
971    3
Name: FTR, dtype: object
1.5
13
13.8
Valladolid - visitante
798    0
819    1
842    0
863    3
888    0
908    0
929    0
943    0
956    1
977    1
Name: FTR, dtype: object
0.6
Valencia - local
793    0
822    3
843    3
861    1
881    3
902    1
911    1
936    3
956    1
972    3
Name: FTR, dtype: object
1.9
13
14.5
Alaves - visitante
799    1
828    0
841    0
867    3
885    3
904    1
922    0
949    0
958    1
978    3
Name: FTR, dtype: object
1.2
Sociedad - local
794    3
800    0
823    1
840    3
869    1
882    0
906    3
925    3
932    1
950    3
Name: FTR, dtype: object
1.8
14
12.1
Real Madrid - visitante
792    0
802    1
820    1
843    0
870    3
892    3
918    3
934    3
951    3
970    1
Name: FTR, dtype: object
1.8
Leganes - local
796    1
804    0
820    1
842    3
866    0
880    3
893    1
913    3
938    1
957    3
Name: FTR, dtype: object
1.6
10
12.9
Espanol - visitante
790    1
812    1
838    3
857    0
879    1
902    1
921    1
940    0
950    0
976    0
Name: FTR, dtype: object
0.8

Girona - local
795    3
824    0
838    0
859    0
873    0
890    1
915    0
933    0
958    1
979    1
Name: FTR, dtype: object
0.6
7
12.4
Levante - visitante
797    0
822    0
846    0
869    1
880    0
907    3
910    0
937    0
953    0
971    0
Name: FTR, dtype: object
0.4
Betis - local
790    1
814    0
834    3
864    0
884    0
904    1
924    3
944    3
951    0
974    1
Name: FTR, dtype: object
1.2
13
12.8
Huesca - visitante
791    1
815    1
831    1
853    0
875    0
899    1
915    3
932    1
957    0
972    0
Name: FTR, dtype: object
0.8
Barcelona - local
797    3
818    3
839    3
857    3
876    3
908    3
928    1
945    3
952    3
975    3
Name: FTR, dtype: object
2.8
21
15.1
Getafe - visitante
794    0
821    1
848    1
861    1
884    3
909    1
926    1
939    0
955    3
979    1
Name: FTR, dtype: object
1.2
Ath Madrid - local
798    3
806    3
829    3
849    3
877    3
894    3
918    0
939    3
953    3
976    3
Name: FTR, dtype: object
2.7
16
13.1
Sevilla - visitante
795    0
813    0
830    3
862    3
887    0
901    0
927    0
946    0
954    0
973    1
Name: FTR, dtype: object
0.7
Ath Bilbao - local
799    1
825    3
846    3
868    3
879    1
897    3
914    1
935    3
954    3
977    1
Name: FTR, dtype: object
2.2
15
11.8
Celta - visitante
796    1
805    1
829    0
844    1
865    0
883    0
898    1
916    0
931    0
959    0
Name: FTR, dtype: object
0.4
Valladolid - local
807    3
821    1
830    0
851    1
870    0
891    0
919    1
931    3
965    0
985    0
Name: FTR, dtype: object
0.9
9
10.9
Ath Bilbao - visitante
804    3
811    0
832    0
859    3
881    0
900    3
925    0
941    1
960    3
980    1
Name: FTR, dtype: object
1.4
Real Madrid - local
811    3
837    3
853    3
865    3
886    0
903    0
922    3
946    3
962    0
986    3
Name: FTR, dtype: object
2.1
17
18.0
Villarreal - visitante
800    3
824    3
834    0
856    0
872    3
894    0
919    1
936    0
964    1
983    1
Name: FTR, dtype: object
1.2
Huesca - local
808    3
827    1
844    1
867    0
887    3
900    0
929    3
947    0
966    3
983    1
Name: FTR, dtype: object
1.5
16
13.3
Valencia - visitante
806    0
814    3
836    0
852    3
873    3
893    1
928    1
948    3
967    0
988    1
Name: FTR, dtype: object
1.5
Getafe - local
802    1
813    3
832    3
855    0
875    3
896    3
916    3
949    3
963    0
987    3
Name: FTR, dtype: object
2.2
17
10.2
Girona - visitante
807    0
817    0
849    0
866    3
889    3
903    3
923    0
944    0
968    1
981    0
Name: FTR, dtype: object
1.0
Eibar - local
816    0
845    3
863    0
883    3
909    1
923    3
940    3
964    1
988    1
993    1
Name: FTR, dtype: object
1.6
17
17.0
Betis - visitante
803    0
826    0
840    0
850    1
874    3
891    3
913    0
935    0
966    0
984    3
Name: FTR, dtype: object
1.0
Levante - local
803    3
812    1
831    1
854    1
872    0
892    0
926    1
943    3
968    1
982    0
Name: FTR, dtype: object
1.1
15
12.8
Vallecano - visitante
801    0
825    0
845    0
860    0
876    0
896    0
917    0
930    3
965    3
986    0
Name: FTR, dtype: object
0.6
Espanol - local
805    1
828    3
848    1
862    0
888    3
899    1
917    3
934    0
969    3
984    0
Name: FTR, dtype: object
1.5
14
11.5
Ath Madrid - visitante
816    3
839    0
858    3
868    0
882    3
905    3
924    0
947    3
961    1
985    3
Name: FTR, dtype: object
1.9
Celta - local
817     3
833     3
856     3
874     0
907     0
927     3
948     0
960     0
989     1
1008    3
Name: FTR, dtype: object
1.6
14
12.6
Barcelona - visitante
809    3
827    1
847    1
864    3
886    3
895    3
914    1
933    3
963    3
982    3
Name: FTR, dtype: object
2.4
Alaves - local
809    0
819    1
835    1
858    0
878    1
898    1
910    3
930    0
967    3
980    1
Name: FTR, dtype: object
1.1
8
12.6
Sociedad - visitante
818     0
833     0
851     1
871     0
890     1
911     1
942     1
962     3
987     0
1002    0
Name: FTR, dtype: object
0.7
Sevilla - local
801    3
826    3
841    3
852    0
871    3
895    0
912    1
937    3
961    1
981    3
Name: FTR, dtype: object
2.0
27
16.9
Leganes - visitante
810     0
835     1
855     3
877     0
906     0
920     3
945     0
969     0
989     1
1005    3
Name: FTR, dtype: object
1.1
Betis - local
814    0
834    3
864    0
884    0
904    1
924    3
944    3
951    0
974    1
994    3
Name: FTR, dtype: object
1.4
14
11.8
Espanol - visitante
812     1
838     3
857     0
879     1
902     1
921     1
940     0
950     0
976     0
1007    0
Name: FTR, dtype: object
0.7
Villarreal - local
810    3
847    1
860    3
885    0
901    3
921    1
941    1
955    0
970    1
995    0
Name: FTR, dtype: object
1.3
21
11.9
Huesca - visitante
815     1
831     1
853     0
875     0
899     1
915     3
932     1
957     0
972     0
1008    0
Name: FTR, dtype: object
0.7
Vallecano - local
815     1
836     3
850     1
889     0
905     0
920     0
942     1
959     3
971     3
1009    3
Name: FTR, dtype: object
1.5
13
13.2
Real Madrid - visitante
802    1
820    1
843    0
870    3
892    3
918    3
934    3
951    3
970    1
992    3
Name: FTR, dtype: object
2.1
Valencia - local
822    3
843    3
861    1
881    3
902    1
911    1
936    3
956    1
972    3
996    1
Name: FTR, dtype: object
2.0
14
15.4
Eibar - visitante
808    0
823    1
837    0
854    1
878    1
897    0
912    1
938    1
952    0
974    1
Name: FTR, dtype: object
0.6
Sociedad - local
800    0
823    1
840    3
869    1
882    0
906    3
925    3
932    1
950    3
978    0
Name: FTR, dtype: object
1.5
12
12.8
Getafe - visitante
821    1
848    1
861    1
884    3
909    1
926    1
939    0
955    3
979    1
999    1
Name: FTR, dtype: object
1.3
Girona - local
824     0
838     0
859     0
873     0
890     1
915     0
933     0
958     1
979     1
1001    1
Name: FTR, dtype: object
0.4
7
12.2
Sevilla - visitante
813    0
830    3
862    3
887    0
901    0
927    0
946    0
954    0
973    1
996    1
Name: FTR, dtype: object
0.8
Leganes - local
804    0
820    1
842    3
866    0
880    3
893    1
913    3
938    1
957    3
973    1
Name: FTR, dtype: object
1.6
11
13.2
Celta - visitante
805    1
829    0
844    1
865    0
883    0
898    1
916    0
931    0
959    0
975    0
Name: FTR, dtype: object
0.3
Barcelona - local
818     3
839     3
857     3
876     3
908     3
928     1
945     3
952     3
975     3
1003    3
Name: FTR, dtype: object
2.8
22
14.4
Levante - visitante
822    0
846    0
869    1
880    0
907    3
910    0
937    0
953    0
971    0
993    1
Name: FTR, dtype: object
0.5
Ath Madrid - local
806    3
829    3
849    3
877    3
894    3
918    0
939    3
953    3
976    3
998    3
Name: FTR, dtype: object
2.7
18
13.0
Valladolid - visitante
819    1
842    0
863    3
888    0
908    0
929    0
943    0
956    1
977    1
991    3
Name: FTR, dtype: object
0.9
Ath Bilbao - local
825    3
846    3
868    3
879    1
897    3
914    1
935    3
954    3
977    1
990    3
Name: FTR, dtype: object
2.4
15
12.9
Alaves - visitante
828    0
841    0
867    3
885    3
904    1
922    0
949    0
958    1
978    3
998    0
Name: FTR, dtype: object
1.1
Sociedad - local
823    1
840    3
869    1
882    0
906    3
925    3
932    1
950    3
978    0
991    0
Name: FTR, dtype: object
1.5
13
13.8
Villarreal - visitante
824     3
834     0
856     0
872     3
894     0
919     1
936     0
964     1
983     1
1003    0
Name: FTR, dtype: object
0.9
Sevilla - local
826     3
841     3
852     0
871     3
895     0
912     1
937     3
961     1
981     3
1012    3
Name: FTR, dtype: object
2.0
23
16.6
Vallecano - visitante
825    0
845    0
860    0
876    0
896    0
917    0
930    3
965    3
986    0
994    0
Name: FTR, dtype: object
0.6
Getafe - local
813     3
832     3
855     0
875     3
896     3
916     3
949     3
963     0
987     3
1007    3
Name: FTR, dtype: object
2.4
20
10.7
Real Madrid - visitante
820     1
843     0
870     3
892     3
918     3
934     3
951     3
970     1
992     3
1017    0
Name: FTR, dtype: object
2.0
Levante - local
812     1
831     1
854     1
872     0
892     0
926     1
943     3
968     1
982     0
1000    3
Name: FTR, dtype: object
1.1
14
13.9
Betis - visitante
826     0
840     0
850     1
874     3
891     3
913     0
935     0
966     0
984     3
1011    0
Name: FTR, dtype: object
1.0
Leganes - local
820    1
842    3
866    0
880    3
893    1
913    3
938    1
957    3
973    1
999    1
Name: FTR, dtype: object
1.7
12
13.5
Ath Bilbao - visitante
811     0
832     0
859     3
881     0
900     3
925     0
941     1
960     3
980     1
1000    0
Name: FTR, dtype: object
1.1
Espanol - local
828    3
848    1
862    0
888    3
899    1
917    3
934    0
969    3
984    0
997    0
Name: FTR, dtype: object
1.4
13
12.1
Celta - visitante
829    0
844    1
865    0
883    0
898    1
916    0
931    0
959    0
975    0
995    3
Name: FTR, dtype: object
0.5
Ath Madrid - local
829     3
849     3
877     3
894     3
918     0
939     3
953     3
976     3
998     3
1018    1
Name: FTR, dtype: object
2.5
16
11.9
Valencia - visitante
814     3
836     0
852     3
873     3
893     1
928     1
948     3
967     0
988     1
1006    0
Name: FTR, dtype: object
1.5
Valladolid - local
821     1
830     0
851     1
870     0
891     0
919     1
931     3
965     0
985     0
1005    0
Name: FTR, dtype: object
0.6
10
11.6
Girona - visitante
817    0
849    0
866    3
889    3
903    3
923    0
944    0
968    1
981    0
990    0
Name: FTR, dtype: object
1.0
Huesca - local
827    1
844    1
867    0
887    3
900    0
929    3
947    0
966    3
983    1
992    0
Name: FTR, dtype: object
1.2
14
13.2
Eibar - visitante
823     1
837     0
854     1
878     1
897     0
912     1
938     1
952     0
974     1
1009    0
Name: FTR, dtype: object
0.6
Alaves - local
819     1
835     1
858     0
878     1
898     1
910     3
930     0
967     3
980     1
1004    1
Name: FTR, dtype: object
1.2
9
13.1
Barcelona - visitante
827    1
847    1
864    3
886    3
895    3
914    1
933    3
963    3
982    3
997    3
Name: FTR, dtype: object
2.4
Villarreal - local
847     1
860     3
885     0
901     3
921     1
941     1
955     0
970     1
995     0
1011    3
Name: FTR, dtype: object
1.3
21
12.1
Leganes - visitante
835     1
855     3
877     0
906     0
920     3
945     0
969     0
989     1
1005    3
1026    1
Name: FTR, dtype: object
1.2
Real Madrid - local
837     3
853     3
865     3
886     0
903     0
922     3
946     3
962     0
986     3
1006    3
Name: FTR, dtype: object
2.1
16
18.2
Ath Bilbao - visitante
832     0
859     3
881     0
900     3
925     0
941     1
960     3
980     1
1000    0
1028    0
Name: FTR, dtype: object
1.1
Levante - local
831     1
854     1
872     0
892     0
926     1
943     3
968     1
982     0
1000    3
1029    0
Name: FTR, dtype: object
1.0
13
13.7
Espanol - visitante
838     3
857     0
879     1
902     1
921     1
940     0
950     0
976     0
1007    0
1021    0
Name: FTR, dtype: object
0.6
Getafe - local
832     3
855     0
875     3
896     3
916     3
949     3
963     0
987     3
1007    3
1027    0
Name: FTR, dtype: object
2.1
17
11.4
Sevilla - visitante
830     3
862     3
887     0
901     0
927     0
946     0
954     0
973     1
996     1
1004    1
Name: FTR, dtype: object
0.9
Betis - local
834     3
864     0
884     0
904     1
924     3
944     3
951     0
974     1
994     3
1002    3
Name: FTR, dtype: object
1.7
14
10.1
Valencia - visitante
836     0
852     3
873     3
893     1
928     1
948     3
967     0
988     1
1006    0
1027    3
Name: FTR, dtype: object
1.5
Vallecano - local
836     3
850     1
889     0
905     0
920     0
942     1
959     3
971     3
1009    3
1020    1
Name: FTR, dtype: object
1.5
15
13.1
Huesca - visitante
831     1
853     0
875     0
899     1
915     3
932     1
957     0
972     0
1008    0
1024    0
Name: FTR, dtype: object
0.6
Eibar - local
845     3
863     0
883     3
909     1
923     3
940     3
964     1
988     1
993     1
1017    3
Name: FTR, dtype: object
1.9
20
17.4
Ath Madrid - visitante
839     0
858     3
868     0
882     3
905     3
924     0
947     3
961     1
985     3
1001    1
Name: FTR, dtype: object
1.7
Celta - local
833     3
856     3
874     0
907     0
927     3
948     0
960     0
989     1
1008    3
1022    0
Name: FTR, dtype: object
1.3
14
12.8
Girona - visitante
849     0
866     3
889     3
903     3
923     0
944     0
968     1
981     0
990     0
1013    3
Name: FTR, dtype: object
1.3
Barcelona - local
839     3
857     3
876     3
908     3
928     1
945     3
952     3
975     3
1003    3
1023    0
Name: FTR, dtype: object
2.5
23
15.3
Sociedad - visitante
833     0
851     1
871     0
890     1
911     1
942     1
962     3
987     0
1002    0
1029    3
Name: FTR, dtype: object
1.0
Alaves - local
835     1
858     0
878     1
898     1
910     3
930     0
967     3
980     1
1004    1
1024    3
Name: FTR, dtype: object
1.4
9
13.4

Valladolid - visitante
842     0
863     3
888     0
908     0
929     0
943     0
956     1
977     1
991     3
1012    0
Name: FTR, dtype: object
0.8
Leganes - local
842     3
866     0
880     3
893     1
913     3
938     1
957     3
973     1
999     1
1019    3
Name: FTR, dtype: object
1.9
12
14.3
Real Madrid - visitante
843     0
870     3
892     3
918     3
934     3
951     3
970     1
992     3
1017    0
1022    3
Name: FTR, dtype: object
2.2
Valladolid - local
830     0
851     1
870     0
891     0
919     1
931     3
965     0
985     0
1005    0
1025    1
Name: FTR, dtype: object
0.6
8
11.7
Getafe - visitante
848     1
861     1
884     3
909     1
926     1
939     0
955     3
979     1
999     1
1014    1
Name: FTR, dtype: object
1.3
Valencia - local
843     3
861     1
881     3
902     1
911     1
936     3
956     1
972     3
996     1
1015    3
Name: FTR, dtype: object
2.0
14
14.4
Levante - visitante
846     0
869     1
880     0
907     3
910     0
937     0
953     0
971     0
993     1
1016    1
Name: FTR, dtype: object
0.6
Sociedad - local
840     3
869     1
882     0
906     3
925     3
932     1
950     3
978     0
991     0
1010    3
Name: FTR, dtype: object
1.7
14
15.0
Eibar - visitante
837     0
854     1
878     1
897     0
912     1
938     1
952     0
974     1
1009    0
1025    1
Name: FTR, dtype: object
0.6
Girona - local
838     0
859     0
873     0
890     1
915     0
933     0
958     1
979     1
1001    1
1026    1
Name: FTR, dtype: object
0.5
7
11.3
Villarreal - visitante
834     0
856     0
872     3
894     0
919     1
936     0
964     1
983     1
1003    0
1020    1
Name: FTR, dtype: object
0.7
Ath Bilbao - local
846     3
868     3
879     1
897     3
914     1
935     3
954     3
977     1
990     3
1014    1
Name: FTR, dtype: object
2.2
13
12.2
Vallecano - visitante
845     0
860     0
876     0
896     0
917     0
930     3
965     3
986     0
994     0
1015    0
Name: FTR, dtype: object
0.6
Sevilla - local
841     3
852     0
871     3
895     0
912     1
937     3
961     1
981     3
1012    3
1021    3
Name: FTR, dtype: object
2.0
22
17.8
Betis - visitante
840     0
850     1
874     3
891     3
913     0
935     0
966     0
984     3
1011    0
1023    3
Name: FTR, dtype: object
1.3
Huesca - local
844     1
867     0
887     3
900     0
929     3
947     0
966     3
983     1
992     0
1016    1
Name: FTR, dtype: object
1.2
16
15.8
Barcelona - visitante
847     1
864     3
886     3
895     3
914     1
933     3
963     3
982     3
997     3
1018    1
Name: FTR, dtype: object
2.4
Espanol - local
848     1
862     0
888     3
899     1
917     3
934     0
969     3
984     0
997     0
1013    0
Name: FTR, dtype: object
1.1
12
13.3
Alaves - visitante
841     0
867     3
885     3
904     1
922     0
949     0
958     1
978     3
998     0
1019    0
Name: FTR, dtype: object
1.1
Ath Madrid - local
849     3
877     3
894     3
918     0
939     3
953     3
976     3
998     3
1018    1
1028    3
Name: FTR, dtype: object
2.5
17
11.7
Celta - visitante
844     1
865     0
883     0
898     1
916     0
931     0
959     0
975     0
995     3
1010    0
Name: FTR, dtype: object
0.5
Valladolid - local
851     1
870     0
891     0
919     1
931     3
965     0
985     0
1005    0
1025    1
1049    1
Name: FTR, dtype: object
0.7
9
12.2
Sevilla - visitante
862     3
887     0
901     0
927     0
946     0
954     0
973     1
996     1
1004    1
1032    1
Name: FTR, dtype: object
0.7
Levante - local
854     1
872     0
892     0
926     1
943     3
968     1
982     0
1000    3
1029    0
1044    3
Name: FTR, dtype: object
1.2
13
13.2
Huesca - visitante
853     0
875     0
899     1
915     3
932     1
957     0
972     0
1008    0
1024    0
1040    0
Name: FTR, dtype: object
0.5
Getafe - local
855     0
875     3
896     3
916     3
949     3
963     0
987     3
1007    3
1027    0
1041    3
Name: FTR, dtype: object
2.1
18
12.4
Ath Bilbao - visitante
859     3
881     0
900     3
925     0
941     1
960     3
980     1
1000    0
1028    0
1030    0
Name: FTR, dtype: object
1.1
Celta - local
856     3
874     0
907     0
927     3
948     0
960     0
989     1
1008    3
1022    0
1046    3
Name: FTR, dtype: object
1.3
15
12.7
Sociedad - visitante
851     1
871     0
890     1
911     1
942     1
962     3
987     0
1002    0
1029    3
1047    0
Name: FTR, dtype: object
1.0
Betis - local
864     0
884     0
904     1
924     3
944     3
951     0
974     1
994     3
1002    3
1035    1
Name: FTR, dtype: object
1.5
15
9.8
Villarreal - visitante
856     0
872     3
894     0
919     1
936     0
964     1
983     1
1003    0
1020    1
1043    0
Name: FTR, dtype: object
0.7
Alaves - local
858     0
878     1
898     1
910     3
930     0
967     3
980     1
1004    1
1024    3
1043    3
Name: FTR, dtype: object
1.6
10
14.7
Leganes - visitante
855     3
877     0
906     0
920     3
945     0
969     0
989     1
1005    3
1026    1
1044    0
Name: FTR, dtype: object
1.1
Vallecano - local
850     1
889     0
905     0
920     0
942     1
959     3
971     3
1009    3
1020    1
1036    0
Name: FTR, dtype: object
1.2
15
12.7
Valencia - visitante
852     3
873     3
893     1
928     1
948     3
967     0
988     1
1006    0
1027    3
1048    1
Name: FTR, dtype: object
1.6
Real Madrid - local
853     3
865     3
886     0
903     0
922     3
946     3
962     0
986     3
1006    3
1038    3
Name: FTR, dtype: object
2.1
16
18.5
Eibar - visitante
854     1
878     1
897     0
912     1
938     1
952     0
974     1
1009    0
1025    1
1046    0
Name: FTR, dtype: object
0.6
Girona - local
859     0
873     0
890     1
915     0
933     0
958     1
979     1
1001    1
1026    1
1045    3
Name: FTR, dtype: object
0.8
8
11.3
Espanol - visitante
857     0
879     1
902     1
921     1
940     0
950     0
976     0
1007    0
1021    0
1049    1
Name: FTR, dtype: object
0.4
Barcelona - local
857     3
876     3
908     3
928     1
945     3
952     3
975     3
1003    3
1023    0
1042    3
Name: FTR, dtype: object
2.5
26
14.5
Ath Madrid - visitante
858     3
868     0
882     3
905     3
924     0
947     3
961     1
985     3
1001    1
1039    1
Name: FTR, dtype: object
1.8
Sociedad - local
869     1
882     0
906     3
925     3
932     1
950     3
978     0
991     0
1010    3
1032    1
Name: FTR, dtype: object
1.5
12
14.5
Betis - visitante
850     1
874     3
891     3
913     0
935     0
966     0
984     3
1011    0
1023    3
1041    0
Name: FTR, dtype: object
1.3
Sevilla - local
852     0
871     3
895     0
912     1
937     3
961     1
981     3
1012    3
1021    3
1040    3
Name: FTR, dtype: object
2.0
22
17.5
Alaves - visitante
867     3
885     3
904     1
922     0
949     0
958     1
978     3
998     0
1019    0
1034    0
Name: FTR, dtype: object
1.1
Leganes - local
866     0
880     3
893     1
913     3
938     1
957     3
973     1
999     1
1019    3
1039    1
Name: FTR, dtype: object
1.7
12
13.3
Valladolid - visitante
863     3
888     0
908     0
929     0
943     0
956     1
977     1
991     3
1012    0
1038    0
Name: FTR, dtype: object
0.8
Valencia - local
861     1
881     3
902     1
911     1
936     3
956     1
972     3
996     1
1015    3
1037    0
Name: FTR, dtype: object
1.7
12
16.0
Real Madrid - visitante
870     3
892     3
918     3
934     3
951     3
970     1
992     3
1017    0
1022    3
1042    0
Name: FTR, dtype: object
2.2
Huesca - local
867     0
887     3
900     0
929     3
947     0
966     3
983     1
992     0
1016    1
1033    1
Name: FTR, dtype: object
1.2
14
15.3
Celta - visitante
865     0
883     0
898     1
916     0
931     0
959     0
975     0
995     3
1010    0
1035    1
Name: FTR, dtype: object
0.5
Eibar - local
863     0
883     3
909     1
923     3
940     3
964     1
988     1
993     1
1017    3
1034    3
Name: FTR, dtype: object
1.9
20
18.5
Vallecano - visitante
860     0
876     0
896     0
917     0
930     3
965     3
986     0
994     0
1015    0
1045    0
Name: FTR, dtype: object
0.6
Ath Bilbao - local
868     3
879     1
897     3
914     1
935     3
954     3
977     1
990     3
1014    1
1048    1
Name: FTR, dtype: object
2.0
10
12.1
Levante - visitante
869     1
880     0
907     3
910     0
937     0
953     0
971     0
993     1
1016    1
1031    1
Name: FTR, dtype: object
0.7
Villarreal - local
860     3
885     0
901     3
921     1
941     1
955     0
970     1
995     0
1011    3
1031    1
Name: FTR, dtype: object
1.3
18
12.8
Barcelona - visitante
864     3
886     3
895     3
914     1
933     3
963     3
982     3
997     3
1018    1
1036    3
Name: FTR, dtype: object
2.6
Espanol - local
862     0
888     3
899     1
917     3
934     0
969     3
984     0
997     0
1013    0
1030    3
Name: FTR, dtype: object
1.3
12
13.2
Getafe - visitante
861     1
884     3
909     1
926     1
939     0
955     3
979     1
999     1
1014    1
1033    1
Name: FTR, dtype: object
1.3
Ath Madrid - local
877     3
894     3
918     0
939     3
953     3
976     3
998     3
1018    1
1028    3
1047    3
Name: FTR, dtype: object
2.5
17
11.4
Girona - visitante
866     3
889     3
903     3
923     0
944     0
968     1
981     0
990     0
1013    3
1037    3
Name: FTR, dtype: object
1.6
Vallecano - local
889     0
905     0
920     0
942     1
959     3
971     3
1009    3
1020    1
1036    0
1050    1
Name: FTR, dtype: object
1.2
15
11.8
Betis - visitante
874     3
891     3
913     0
935     0
966     0
984     3
1011    0
1023    3
1041    0
1065    0
Name: FTR, dtype: object
1.2
Valladolid - local
870     0
891     0
919     1
931     3
965     0
985     0
1005    0
1025    1
1049    1
1061    3
Name: FTR, dtype: object
0.9
9
12.1
Sociedad - visitante
871     0
890     1
911     1
942     1
962     3
987     0
1002    0
1029    3
1047    0
1070    3
Name: FTR, dtype: object
1.2
Sevilla - local
871     3
895     0
912     1
937     3
961     1
981     3
1012    3
1021    3
1040    3
1063    3
Name: FTR, dtype: object
2.3
24
17.0
Valencia - visitante
873     3
893     1
928     1
948     3
967     0
988     1
1006    0
1027    3
1048    1
1076    3
Name: FTR, dtype: object
1.6
Real Madrid - local
865     3
886     0
903     0
922     3
946     3
962     0
986     3
1006    3
1038    3
1058    0
Name: FTR, dtype: object
1.8
14
20.3
Huesca - visitante
875     0
899     1
915     3
932     1
957     0
972     0
1008    0
1024    0
1040    0
1061    0
Name: FTR, dtype: object
0.5
Levante - local
872     0
892     0
926     1
943     3
968     1
982     0
1000    3
1029    0
1044    3
1073    3
Name: FTR, dtype: object
1.4
13
13.9
Eibar - visitante
878     1
897     0
912     1
938     1
952     0
974     1
1009    0
1025    1
1046    0
1067    3
Name: FTR, dtype: object
0.8
Getafe - local
875     3
896     3
916     3
949     3
963     0
987     3
1007    3
1027    0
1041    3
1068    0
Name: FTR, dtype: object
2.1
18
13.0
Leganes - visitante
877     0
906     0
920     3
945     0
969     0
989     1
1005    3
1026    1
1044    0
1057    1
Name: FTR, dtype: object
0.9
Celta - local
874     0
907     0
927     3
948     0
960     0
989     1
1008    3
1022    0
1046    3
1060    0
Name: FTR, dtype: object
1.0
12
13.1
Villarreal - visitante
872     3
894     0
919     1
936     0
964     1
983     1
1003    0
1020    1
1043    0
1064    0
Name: FTR, dtype: object
0.7
Barcelona - local
876     3
908     3
928     1
945     3
952     3
975     3
1003    3
1023    0
1042    3
1059    3
Name: FTR, dtype: object
2.5
28
15.5
Espanol - visitante
879     1
902     1
921     1
940     0
950     0
976     0
1007    0
1021    0
1049    1
1053    3
Name: FTR, dtype: object
0.7
Alaves - local
878     1
898     1
910     3
930     0
967     3
980     1
1004    1
1024    3
1043    3
1069    3
Name: FTR, dtype: object
1.9
11
14.1
Ath Madrid - visitante
868     0
882     3
905     3
924     0
947     3
961     1
985     3
1001    1
1039    1
1056    1
Name: FTR, dtype: object
1.6
Girona - local
873     0
890     1
915     0
933     0
958     1
979     1
1001    1
1026    1
1045    3
1067    0
Name: FTR, dtype: object
0.8
9
11.7
Ath Bilbao - visitante
881     0
900     3
925     0
941     1
960     3
980     1
1000    0
1028    0
1030    0
1050    1
Name: FTR, dtype: object
0.9
Villarreal - local
885     0
901     3
921     1
941     1
955     0
970     1
995     0
1011    3
1031    1
1056    1
Name: FTR, dtype: object
1.1
16
13.4
Vallecano - visitante
876     0
896     0
917     0
930     3
965     3
986     0
994     0
1015    0
1045    0
1066    0
Name: FTR, dtype: object
0.6
Valencia - local
881     3
902     1
911     1
936     3
956     1
972     3
996     1
1015    3
1037    0
1057    1
Name: FTR, dtype: object
1.7
13
17.0
Getafe - visitante
884     3
909     1
926     1
939     0
955     3
979     1
999     1
1014    1
1033    1
1052    3
Name: FTR, dtype: object
1.5
Espanol - local
888     3
899     1
917     3
934     0
969     3
984     0
997     0
1013    0
1030    3
1064    3
Name: FTR, dtype: object
1.6
15
14.7
Sevilla - visitante
887     0
901     0
927     0
946     0
954     0
973     1
996     1
1004    1
1032    1
1059    0

Name: FTR, dtype: object
0.4
Eibar - local
883     3
909     1
923     3
940     3
964     1
988     1
993     1
1017    3
1034    3
1054    1
Name: FTR, dtype: object
2.0
20
18.8
Valladolid - visitante
888     0
908     0
929     0
943     0
956     1
977     1
991     3
1012    0
1038    0
1055    3
Name: FTR, dtype: object
0.8
Betis - local
884     0
904     1
924     3
944     3
951     0
974     1
994     3
1002    3
1035    1
1055    0
Name: FTR, dtype: object
1.5
14
10.5
Barcelona - visitante
886     3
895     3
914     1
933     3
963     3
982     3
997     3
1018    1
1036    3
1062    1
Name: FTR, dtype: object
2.4
Real Madrid - local
886     0
903     0
922     3
946     3
962     0
986     3
1006    3
1038    3
1058    0
1077    1
Name: FTR, dtype: object
1.6
12
19.6
Celta - visitante
883     0
898     1
916     0
931     0
959     0
975     0
995     3
1010    0
1035    1
1063    0
Name: FTR, dtype: object
0.5
Leganes - local
880     3
893     1
913     3
938     1
957     3
973     1
999     1
1019    3
1039    1
1066    3
Name: FTR, dtype: object
2.0
13
13.4
Girona - visitante
889     3
903     3
923     0
944     0
968     1
981     0
990     0
1013    3
1037    3
1051    1
Name: FTR, dtype: object
1.4
Huesca - local
887     3
900     0
929     3
947     0
966     3
983     1
992     0
1016    1
1033    1
1053    0
Name: FTR, dtype: object
1.2
13
15.6
Alaves - visitante
885     3
904     1
922     0
949     0
958     1
978     3
998     0
1019    0
1034    0
1060    3
Name: FTR, dtype: object
1.1
Ath Bilbao - local
879     1
897     3
914     1
935     3
954     3
977     1
990     3
1014    1
1048    1
1070    0
Name: FTR, dtype: object
1.7
9
12.5
Ath Madrid - visitante
882     3
905     3
924     0
947     3
961     1
985     3
1001    1
1039    1
1056    1
1077    1
Name: FTR, dtype: object
1.7
Sociedad - local
882     0
906     3
925     3
932     1
950     3
978     0
991     0
1010    3
1032    1
1051    1
Name: FTR, dtype: object
1.5
11
13.7
Levante - visitante
880     0
907     3
910     0
937     0
953     0
971     0
993     1
1016    1
1031    1
1058    3
Name: FTR, dtype: object
0.9
Valladolid - local
891     0
919     1
931     3
965     0
985     0
1005    0
1025    1
1049    1
1061    3
1081    3
Name: FTR, dtype: object
1.2
10
13.1
Real Madrid - visitante
892     3
918     3
934     3
951     3
970     1
992     3
1017    0
1022    3
1042    0
1069    0
Name: FTR, dtype: object
1.9
Sevilla - local
895     0
912     1
937     3
961     1
981     3
1012    3
1021    3
1040    3
1063    3
1085    3
Name: FTR, dtype: object
2.3
22
16.4
Sociedad - visitante
890     1
911     1
942     1
962     3
987     0
1002    0
1029    3
1047    0
1070    3
1100    3
Name: FTR, dtype: object
1.5
Levante - local
892     0
926     1
943     3
968     1
982     0
1000    3
1029    0
1044    3
1073    3
1092    0
Name: FTR, dtype: object
1.4
15
14.7
Villarreal - visitante
894     0
919     1
936     0
964     1
983     1
1003    0
1020    1
1043    0
1064    0
1087    3
Name: FTR, dtype: object
0.7
Girona - local
890     1
915     0
933     0
958     1
979     1
1001    1
1026    1
1045    3
1067    0
1082    0
Name: FTR, dtype: object
0.8
7
10.7
Valencia - visitante
893     1
928     1
948     3
967     0
988     1
1006    0
1027    3
1048    1
1076    3
1091    1
Name: FTR, dtype: object
1.4
Celta - local
907     0
927     3
948     0
960     0
989     1
1008    3
1022    0
1046    3
1060    0
1071    1
Name: FTR, dtype: object
1.1
13
13.2
Betis - visitante
891     3
913     0
935     0
966     0
984     3
1011    0
1023    3
1041    0
1065    0
1082    3
Name: FTR, dtype: object
1.2
Getafe - local
896     3
916     3
949     3
963     0
987     3
1007    3
1027    0
1041    3
1068    0
1097    0
Name: FTR, dtype: object
1.8
16
12.7
Huesca - visitante
899     1
915     3
932     1
957     0
972     0
1008    0
1024    0
1040    0
1061    0
1090    0
Name: FTR, dtype: object
0.5
Barcelona - local
908     3
928     1
945     3
952     3
975     3
1003    3
1023    0
1042    3
1059    3
1079    1
Name: FTR, dtype: object
2.3
26
16.3
Vallecano - visitante
896     0
917     0
930     3
965     3
986     0
994     0
1015    0
1045    0
1066    0
1088    1
Name: FTR, dtype: object
0.7
Ath Madrid - local
894     3
918     0
939     3
953     3
976     3
998     3
1018    1
1028    3
1047    3
1065    3
Name: FTR, dtype: object
2.5
17
11.4
Leganes - visitante
906     0
920     3
945     0
969     0
989     1
1005    3
1026    1
1044    0
1057    1
1075    0
Name: FTR, dtype: object
0.9
Alaves - local
898     1
910     3
930     0
967     3
980     1
1004    1
1024    3
1043    3
1069    3
1083    1
Name: FTR, dtype: object
1.9
11
14.0
Eibar - visitante
897     0
912     1
938     1
952     0
974     1
1009    0
1025    1
1046    0
1067    3
1089    0
Name: FTR, dtype: object
0.7
Ath Bilbao - local
897     3
914     1
935     3
954     3
977     1
990     3
1014    1
1048    1
1070    0
1087    0
Name: FTR, dtype: object
1.6
8
12.2
Espanol - visitante
902     1
921     1
940     0
950     0
976     0
1007    0
1021    0
1049    1
1053    3
1080    1
Name: FTR, dtype: object
0.7
Leganes - local
893     1
913     3
938     1
957     3
973     1
999     1
1019    3
1039    1
1066    3
1086    3
Name: FTR, dtype: object
2.0
14
13.0
Levante - visitante
907     3
910     0
937     0
953     0
971     0
993     1
1016    1
1031    1
1058    3
1068    3
Name: FTR, dtype: object
1.2
Valencia - local
902     1
911     1
936     3
956     1
972     3
996     1
1015    3
1037    0
1057    1
1062    1
Name: FTR, dtype: object
1.5
12
16.9
Ath Bilbao - visitante
900     3
925     0
941     1
960     3
980     1
1000    0
1028    0
1030    0
1050    1
1054    1
Name: FTR, dtype: object
1.0
Sociedad - local
906     3
925     3
932     1
950     3
978     0
991     0
1010    3
1032    1
1051    1
1076    0
Name: FTR, dtype: object
1.5
11
12.8
Ath Madrid - visitante
905     3
924     0
947     3
961     1
985     3
1001    1
1039    1
1056    1
1077    1
1097    3
Name: FTR, dtype: object
1.7
Eibar - local
909     1
923     3
940     3
964     1
988     1
993     1
1017    3
1034    3
1054    1
1078    0
Name: FTR, dtype: object
1.7
20
18.8
Celta - visitante
898     1
916     0
931     0
959     0
975     0
995     3
1010    0
1035    1
1063    0
1084    1
Name: FTR, dtype: object
0.6
Betis - local
904     1
924     3
944     3
951     0
974     1
994     3
1002    3
1035    1
1055    0
1075    3
Name: FTR, dtype: object
1.8
14
11.6
Getafe - visitante
909     1
926     1
939     0
955     3
979     1
999     1
1014    1
1033    1
1052    3
1071    1
Name: FTR, dtype: object
1.3
Villarreal - local
901     3
921     1
941     1
955     0
970     1
995     0
1011    3
1031    1
1056    1
1072    0
Name: FTR, dtype: object
1.1
15
15.2
Alaves - visitante
904     1
922     0
949     0
958     1
978     3
998     0
1019    0
1034    0
1060    3
1073    0
Name: FTR, dtype: object
0.8
Real Madrid - local
903     0
922     3
946     3
962     0
986     3
1006    3
1038    3
1058    0
1077    1
1096    3
Name: FTR, dtype: object
1.9
13
19.8
Barcelona - visitante
895     3
914     1
933     3
963     3
982     3
997     3
1018    1
1036    3
1062    1
1086    0
Name: FTR, dtype: object
2.1
Huesca - local
900     0
929     3
947     0
966     3
983     1
992     0
1016    1
1033    1
1053    0
1074    1
Name: FTR, dtype: object
1.0
12
16.2
Sevilla - visitante
901     0
927     0
946     0
954     0
973     1
996     1
1004    1
1032    1
1059    0
1078    3
Name: FTR, dtype: object
0.7
Espanol - local
899     1
917     3
934     0
969     3
984     0
997     0
1013    0
1030    3
1064    3
1089    3
Name: FTR, dtype: object
1.6
13
14.1
Valladolid - visitante
908     0
929     0
943     0
956     1
977     1
991     3
1012    0
1038    0
1055    3
1072    3
Name: FTR, dtype: object
1.1
Vallecano - local
905     0
920     0
942     1
959     3
971     3
1009    3
1020    1
1036    0
1050    1
1052    0
Name: FTR, dtype: object
1.2
16
11.9
Girona - visitante
903     3
923     0
944     0
968     1
981     0
990     0
1013    3
1037    3
1051    1
1074    1
Name: FTR, dtype: object
1.2
Girona - local
915     0
933     0
958     1
979     1
1001    1
1026    1
1045    3
1067    0
1082    0
1101    3
Name: FTR, dtype: object
1.0
10
10.8
Sociedad - visitante
911     1
942     1
962     3
987     0
1002    0
1029    3
1047    0
1070    3
1100    3
1119    0
Name: FTR, dtype: object
1.4
Valladolid - local
919     1
931     3
965     0
985     0
1005    0
1025    1
1049    1
1061    3
1081    3
1102    0
Name: FTR, dtype: object
1.2
10
13.6
Betis - visitante
913     0
935     0
966     0
984     3
1011    0
1023    3
1041    0
1065    0
1082    3
1106    1
Name: FTR, dtype: object
1.0
Levante - local
926     1
943     3
968     1
982     0
1000    3
1029    0
1044    3
1073    3
1092    0
1111    1
Name: FTR, dtype: object
1.5
16
14.9
Real Madrid - visitante
918     3
934     3
951     3
970     1
992     3
1017    0
1022    3
1042    0
1069    0
1085    0
Name: FTR, dtype: object
1.6
Leganes - local
913     3
938     1
957     3
973     1
999     1
1019    3
1039    1
1066    3
1086    3
1104    0
Name: FTR, dtype: object
1.9
13
12.9
Valencia - visitante
928     1
948     3
967     0
988     1
1006    0
1027    3
1048    1
1076    3
1091    1
1111    1
Name: FTR, dtype: object
1.4
Ath Madrid - local
918     0
939     3
953     3
976     3
998     3
1018    1
1028    3
1047    3
1065    3
1090    3
Name: FTR, dtype: object
2.5
18
11.6
Villarreal - visitante
919     1
936     0
964     1
983     1
1003    0
1020    1
1043    0
1064    0
1087    3
1104    3
Name: FTR, dtype: object
1.0
Sevilla - local
912     1
937     3
961     1
981     3
1012    3
1021    3
1040    3
1063    3
1085    3
1103    0
Name: FTR, dtype: object
2.3
20
16.6
Barcelona - visitante
914     1
933     3
963     3
982     3
997     3
1018    1
1036    3
1062    1
1086    0
1107    3
Name: FTR, dtype: object
2.1
Getafe - local
916     3
949     3
963     0
987     3
1007    3
1027    0
1041    3
1068    0
1097    0
1118    1
Name: FTR, dtype: object
1.6
14
12.8
Vallecano - visitante
917     0
930     3
965     3
986     0
994     0
1015    0
1045    0
1066    0
1088    1
1110    3
Name: FTR, dtype: object
1.0
Ath Bilbao - local
914     1
935     3
954     3
977     1
990     3
1014    1
1048    1
1070    0
1087    0
1109    1
Name: FTR, dtype: object
1.4
8
12.4
Eibar - visitante
912     1
938     1
952     0
974     1
1009    0
1025    1
1046    0
1067    3
1089    0
1108    1
Name: FTR, dtype: object
0.8
Alaves - local
910     3
930     0
967     3
980     1
1004    1
1024    3
1043    3
1069    3
1083    1
1114    3
Name: FTR, dtype: object
2.1
13
13.1
Celta - visitante
916     0
931     0
959     0
975     0
995     3
1010    0
1035    1
1063    0
1084    1
1101    0
Name: FTR, dtype: object
0.5
Espanol - local
917     3
934     0
969     3
984     0
997     0
1013    0
1030    3
1064    3
1089    3
1105    3
Name: FTR, dtype: object
1.8
13
15.0
Huesca - visitante
915     3
932     1
957     0
972     0
1008    0
1024    0
1040    0
1061    0
1090    0
1113    0
Name: FTR, dtype: object
0.4
Huesca - local
929     3
947     0
966     3
983     1
992     0
1016    1
1033    1
1053    0
1074    1
1100    0
Name: FTR, dtype: object
1.0
12
16.3
Ath Bilbao - visitante
925     0
941     1
960     3
980     1
1000    0
1028    0
1030    0
1050    1
1054    1
1079    1
Name: FTR, dtype: object
0.8
Villarreal - local
921     1
941     1
955     0
970     1
995     0
1011    3
1031    1
1056    1
1072    0
1091    1
Name: FTR, dtype: object
0.9
12
15.1
Sevilla - visitante
927     0
946     0
954     0
973     1
996     1
1004    1
1032    1
1059    0
1078    3
1092    3
Name: FTR, dtype: object
1.0
Valencia - local
911     1
936     3
956     1
972     3
996     1
1015    3
1037    0
1057    1
1062    1
1084    1
Name: FTR, dtype: object
1.5
13
16.2
Espanol - visitante
921     1
940     0
950     0
976     0
1007    0
1021    0
1049    1
1053    3
1080    1
1096    0
Name: FTR, dtype: object
0.6
Real Madrid - local
922     3
946     3
962     0
986     3
1006    3
1038    3
1058    0
1077    1
1096    3
1115    3
Name: FTR, dtype: object
2.2
16
19.6
Girona - visitante
923     0
944     0
968     1
981     0
990     0
1013    3
1037    3
1051    1
1074    1
1094    1

Name: FTR, dtype: object
1.0
Betis - local
924     3
944     3
951     0
974     1
994     3
1002    3
1035    1
1055    0
1075    3
1093    1
Name: FTR, dtype: object
1.8
15
11.2
Alaves - visitante
922     0
949     0
958     1
978     3
998     0
1019    0
1034    0
1060    3
1073    0
1095    3
Name: FTR, dtype: object
1.0
Vallecano - local
920     0
942     1
959     3
971     3
1009    3
1020    1
1036    0
1050    1
1052    0
1080    1
Name: FTR, dtype: object
1.3
18
11.8
Ath Madrid - visitante
924     0
947     3
961     1
985     3
1001    1
1039    1
1056    1
1077    1
1097    3
1116    0
Name: FTR, dtype: object
1.4
Sociedad - local
925     3
932     1
950     3
978     0
991     0
1010    3
1032    1
1051    1
1076    0
1088    1
Name: FTR, dtype: object
1.3
10
12.9
Leganes - visitante
920     3
945     0
969     0
989     1
1005    3
1026    1
1044    0
1057    1
1075    0
1098    0
Name: FTR, dtype: object
0.9
Celta - local
927     3
948     0
960     0
989     1
1008    3
1022    0
1046    3
1060    0
1071    1
1099    1
Name: FTR, dtype: object
1.2
15
13.0
Levante - visitante
910     0
937     0
953     0
971     0
993     1
1016    1
1031    1
1058    3
1068    3
1081    0
Name: FTR, dtype: object
0.9
Barcelona - local
928     1
945     3
952     3
975     3
1003    3
1023    0
1042    3
1059    3
1079    1
1094    1
Name: FTR, dtype: object
2.1
27
16.5
Valladolid - visitante
929     0
943     0
956     1
977     1
991     3
1012    0
1038    0
1055    3
1072    3
1099    1
Name: FTR, dtype: object
1.2
Eibar - local
923     3
940     3
964     1
988     1
993     1
1017    3
1034    3
1054    1
1078    0
1098    3
Name: FTR, dtype: object
1.9
19
19.1
Getafe - visitante
926     1
939     0
955     3
979     1
999     1
1014    1
1033    1
1052    3
1071    1
1083    1
Name: FTR, dtype: object
1.3
Alaves - local
930     0
967     3
980     1
1004    1
1024    3
1043    3
1069    3
1083    1
1114    3
1127    1
Name: FTR, dtype: object
1.9
11
13.1
Levante - visitante
937     0
953     0
971     0
993     1
1016    1
1031    1
1058    3
1068    3
1081    0
1105    0
Name: FTR, dtype: object
0.9
Valencia - local
936     3
956     1
972     3
996     1
1015    3
1037    0
1057    1
1062    1
1084    1
1106    1
Name: FTR, dtype: object
1.5
13
16.4
Sociedad - visitante
942     1
962     3
987     0
1002    0
1029    3
1047    0
1070    3
1100    3
1119    0
1128    1
Name: FTR, dtype: object
1.4
Sevilla - local
937     3
961     1
981     3
1012    3
1021    3
1040    3
1063    3
1085    3
1103    0
1122    1
Name: FTR, dtype: object
2.3
18
17.2
Eibar - visitante
938     1
952     0
974     1
1009    0
1025    1
1046    0
1067    3
1089    0
1108    1
1129    0
Name: FTR, dtype: object
0.7
Leganes - local
938     1
957     3
973     1
999     1
1019    3
1039    1
1066    3
1086    3
1104    0
1128    1
Name: FTR, dtype: object
1.7
12
13.1
Betis - visitante
935     0
966     0
984     3
1011    0
1023    3
1041    0
1065    0
1082    3
1106    1
1127    1
Name: FTR, dtype: object
1.1
Ath Bilbao - local
935     3
954     3
977     1
990     3
1014    1
1048    1
1070    0
1087    0
1109    1
1121    1
Name: FTR, dtype: object
1.4
10
12.5
Barcelona - visitante
933     3
963     3
982     3
997     3
1018    1
1036    3
1062    1
1086    0
1107    3
1125    3
Name: FTR, dtype: object
2.3
Girona - local
933     0
958     1
979     1
1001    1
1026    1
1045    3
1067    0
1082    0
1101    3
1123    0
Name: FTR, dtype: object
1.0
11
10.5
Huesca - visitante
932     1
957     0
972     0
1008    0
1024    0
1040    0
1061    0
1090    0
1113    0
1121    1
Name: FTR, dtype: object
0.2
Getafe - local
949     3
963     0
987     3
1007    3
1027    0
1041    3
1068    0
1097    0
1118    1
1129    3
Name: FTR, dtype: object
1.6
13
12.3
Celta - visitante
931     0
959     0
975     0
995     3
1010    0
1035    1
1063    0
1084    1
1101    0
1120    3
Name: FTR, dtype: object
0.8
Espanol - local
934     0
969     3
984     0
997     0
1013    0
1030    3
1064    3
1089    3
1105    3
1124    3
Name: FTR, dtype: object
1.8
13
15.4
Vallecano - visitante
930     3
965     3
986     0
994     0
1015    0
1045    0
1066    0
1088    1
1110    3
1126    0
Name: FTR, dtype: object
1.0
Ath Madrid - local
939     3
953     3
976     3
998     3
1018    1
1028    3
1047    3
1065    3
1090    3
1108    1
Name: FTR, dtype: object
2.6
18
12.3
Real Madrid - visitante
934     3
951     3
970     1
992     3
1017    0
1022    3
1042    0
1069    0
1085    0
1109    1
Name: FTR, dtype: object
1.4
Valladolid - local
931     3
965     0
985     0
1005    0
1025    1
1049    1
1061    3
1081    3
1102    0
1125    0
Name: FTR, dtype: object
1.1
10
13.4
Villarreal - visitante
936     0
964     1
983     1
1003    0
1020    1
1043    0
1064    0
1087    3
1104    3
1122    1
Name: FTR, dtype: object
1.0
Vallecano - local
942     1
959     3
971     3
1009    3
1020    1
1036    0
1050    1
1052    0
1080    1
1095    0
Name: FTR, dtype: object
1.3
18
11.6
Leganes - visitante
945     0
969     0
989     1
1005    3
1026    1
1044    0
1057    1
1075    0
1098    0
1115    0
Name: FTR, dtype: object
0.6
Villarreal - local
941     1
955     0
970     1
995     0
1011    3
1031    1
1056    1
1072    0
1091    1
1117    0
Name: FTR, dtype: object
0.8
10
15.0
Espanol - visitante
940     0
950     0
976     0
1007    0
1021    0
1049    1
1053    3
1080    1
1096    0
1114    0
Name: FTR, dtype: object
0.5
Real Madrid - local
946     3
962     0
986     3
1006    3
1038    3
1058    0
1077    1
1096    3
1115    3
1133    3
Name: FTR, dtype: object
2.2
15
18.4
Alaves - visitante
949     0
958     1
978     3
998     0
1019    0
1034    0
1060    3
1073    0
1095    3
1102    3
Name: FTR, dtype: object
1.3
Eibar - local
940     3
964     1
988     1
993     1
1017    3
1034    3
1054    1
1078    0
1098    3
1119    3
Name: FTR, dtype: object
1.9
18
18.2
Girona - visitante
944     0
968     1
981     0
990     0
1013    3
1037    3
1051    1
1074    1
1094    1
1117    3
Name: FTR, dtype: object
1.3
Betis - local
944     3
951     0
974     1
994     3
1002    3
1035    1
1055    0
1075    3
1093    1
1112    3
Name: FTR, dtype: object
1.8
15
11.6
Ath Madrid - visitante
947     3
961     1
985     3
1001    1
1039    1
1056    1
1077    1
1097    3
1116    0
1130    1
Name: FTR, dtype: object
1.5
Sociedad - local
932     1
950     3
978     0
991     0
1010    3
1032    1
1051    1
1076    0
1088    1
1107    0
Name: FTR, dtype: object
1.0
9
13.1
Ath Bilbao - visitante
941     1
960     3
980     1
1000    0
1028    0
1030    0
1050    1
1054    1
1079    1
1093    1
Name: FTR, dtype: object
0.9
Levante - local
943     3
968     1
982     0
1000    3
1029    0
1044    3
1073    3
1092    0
1111    1
1120    0
Name: FTR, dtype: object
1.4
17
15.6
Getafe - visitante
939     0
955     3
979     1
999     1
1014    1
1033    1
1052    3
1071    1
1083    1
1103    3
Name: FTR, dtype: object
1.5
Celta - local
948     0
960     0
989     1
1008    3
1022    0
1046    3
1060    0
1071    1
1099    1
1116    3
Name: FTR, dtype: object
1.2
16
13.0
Sevilla - visitante
946     0
954     0
973     1
996     1
1004    1
1032    1
1059    0
1078    3
1092    3
1112    0
Name: FTR, dtype: object
1.0
Barcelona - local
945     3
952     3
975     3
1003    3
1023    0
1042    3
1059    3
1079    1
1094    1
1113    3
Name: FTR, dtype: object
2.3
33
17.6
Valencia - visitante
948     3
967     0
988     1
1006    0
1027    3
1048    1
1076    3
1091    1
1111    1
1124    0
Name: FTR, dtype: object
1.3
Huesca - local
947     0
966     3
983     1
992     0
1016    1
1033    1
1053    0
1074    1
1100    0
1110    0
Name: FTR, dtype: object
0.7
8
16.6
Valladolid - visitante
943     0
956     1
977     1
991     3
1012    0
1038    0
1055    3
1072    3
1099    1
1118    1
Name: FTR, dtype: object
1.3
Alaves - local
967     3
980     1
1004    1
1024    3
1043    3
1069    3
1083    1
1114    3
1127    1
1159    3
Name: FTR, dtype: object
2.2
14
11.9
Vallecano - visitante
965     3
986     0
994     0
1015    0
1045    0
1066    0
1088    1
1110    3
1126    0
1911    0
Name: FTR, dtype: object
0.7
Valladolid - local
965     0
985     0
1005    0
1025    1
1049    1
1061    3
1081    3
1102    0
1125    0
2661    0
Name: FTR, dtype: object
0.8
8
12.5
Celta - visitante
959     0
975     0
995     3
1010    0
1035    1
1063    0
1084    1
1101    0
1120    3
1153    0
Name: FTR, dtype: object
0.8
Sociedad - local
950     3
978     0
991     0
1010    3
1032    1
1051    1
1076    0
1088    1
1107    0
1152    3
Name: FTR, dtype: object
1.2
12
13.4
Huesca - visitante
957     0
972     0
1008    0
1024    0
1040    0
1061    0
1090    0
1113    0
1121    1
1134    3
Name: FTR, dtype: object
0.4
Girona - local
958     1
979     1
1001    1
1026    1
1045    3
1067    0
1082    0
1101    3
1123    0
1138    1
Name: FTR, dtype: object
1.1
11
10.5
Barcelona - visitante
963     3
982     3
997     3
1018    1
1036    3
1062    1
1086    0
1107    3
1125    3
1150    0
Name: FTR, dtype: object
2.0
Espanol - local
969     3
984     0
997     0
1013    0
1030    3
1064    3
1089    3
1105    3
1124    3
1151    3
Name: FTR, dtype: object
2.1
15
16.0
Real Madrid - visitante
951     3
970     1
992     3
1017    0
1022    3
1042    0
1069    0
1085    0
1109    1
1123    3
Name: FTR, dtype: object
1.4
Ath Bilbao - local
954     3
977     1
990     3
1014    1
1048    1
1070    0
1087    0
1109    1
1121    1
1131    3
Name: FTR, dtype: object
1.4
11
13.1
Betis - visitante
966     0
984     3
1011    0
1023    3
1041    0
1065    0
1082    3
1106    1
1127    1
1147    0
Name: FTR, dtype: object
1.1
Valencia - local
956     1
972     3
996     1
1015    3
1037    0
1057    1
1062    1
1084    1
1106    1
1130    1
Name: FTR, dtype: object
1.3
11
15.9
Villarreal - visitante
964     1
983     1
1003    0
1020    1
1043    0
1064    0
1087    3
1104    3
1122    1
1154    3
Name: FTR, dtype: object
1.3
Sevilla - local
961     1
981     3
1012    3
1021    3
1040    3
1063    3
1085    3
1103    0
1122    1
1145    3
Name: FTR, dtype: object
2.3
14
16.9
Levante - visitante
953     0
971     0
993     1
1016    1
1031    1
1058    3
1068    3
1081    0
1105    0
1139    3
Name: FTR, dtype: object
1.2
Leganes - local
957     3
973     1
999     1
1019    3
1039    1
1066    3
1086    3
1104    0
1128    1
1147    3
Name: FTR, dtype: object
1.9
13
13.0
Eibar - visitante
952     0
974     1
1009    0
1025    1
1046    0
1067    3
1089    0
1108    1
1129    0
1142    1
Name: FTR, dtype: object
0.7
Ath Madrid - local
953     3
976     3
998     3
1018    1
1028    3
1047    3
1065    3
1090    3
1108    1
1126    3
Name: FTR, dtype: object
2.6
17
12.2
Getafe - visitante
955     3
979     1
999     1
1014    1
1033    1
1052    3
1071    1
1083    1
1103    3
1133    0
Name: FTR, dtype: object
1.5
Eibar - local
964     1
988     1
993     1
1017    3
1034    3
1054    1
1078    0
1098    3
1119    3
1134    0
Name: FTR, dtype: object
1.6
16
18.4
Espanol - visitante
950     0
976     0
1007    0
1021    0
1049    1
1053    3
1080    1
1096    0
1114    0
1136    1
Name: FTR, dtype: object
0.6
Villarreal - local
955     0
970     1
995     0
1011    3
1031    1
1056    1
1072    0
1091    1
1117    0
1135    0
Name: FTR, dtype: object
0.7
10
16.3
Ath Bilbao - visitante
960     3
980     1
1000    0
1028    0
1030    0
1050    1
1054    1
1079    1
1093    1
1159    0
Name: FTR, dtype: object
0.8
Vallecano - local
959     3
971     3
1009    3
1020    1
1036    0
1050    1
1052    0
1080    1
1095    0
1132    0
Name: FTR, dtype: object
1.2
17
11.8
Sociedad - visitante
962     3
987     0
1002    0
1029    3
1047    0
1070    3
1100    3
1119    0
1128    1
1135    3
Name: FTR, dtype: object
1.6
Levante - local
968     1
982     0
1000    3
1029    0
1044    3
1073    3
1092    0
1111    1
1120    0
1150    3
Name: FTR, dtype: object
1.4
20
15.5
Valladolid - visitante
956     1
977     1
991     3
1012    0
1038    0
1055    3
1072    3
1099    1
1118    1
1138    1
Name: FTR, dtype: object
1.4
Betis - local
951     0
974     1
994     3
1002    3
1035    1
1055    0
1075    3
1093    1
1112    3
1139    0
Name: FTR, dtype: object
1.5
12
12.6
Girona - visitante
968     1
981     0
990     0
1013    3
1037    3
1051    1
1074    1
1094    1
1117    3
1148    3
Name: FTR, dtype: object
1.6
Barcelona - local
952     3
975     3
1003    3
1023    0
1042    3
1059    3
1079    1
1094    1
1113    3
1137    3
Name: FTR, dtype: object
2.3
33
18.6
Leganes - visitante
969     0
989     1
1005    3
1026    1
1044    0
1057    1
1075    0
1098    0
1115    0
1131    0
Name: FTR, dtype: object
0.6
Real Madrid - local
962     0
986     3
1006    3
1038    3
1058    0
1077    1
1096    3
1115    3
1133    3
1153    3
Name: FTR, dtype: object
2.2
19
17.6
Sevilla - visitante
954     0
973     1
996     1
1004    1
1032    1
1059    0
1078    3
1092    3
1112    0
1132    3
Name: FTR, dtype: object
1.3
Huesca - local
966     3
983     1
992     0
1016    1
1033    1
1053    0
1074    1
1100    0
1110    0
Name: FTR, dtype: object
0.7777777777777778
8
16.88888888888889
Ath Madrid - visitante
961     1
985     3
1001    1
1039    1
1056    1
1077    1
1097    3
1116    0
1130    1
1156    3
Name: FTR, dtype: object
1.5

Celta - local
960     0
989     1
1008    3
1022    0
1046    3
1060    0
1071    1
1099    1
1116    3
1136    1
Name: FTR, dtype: object
1.3
16
13.0
Valencia - visitante
967     0
988     1
1006    0
1027    3
1048    1
1076    3
1091    1
1111    1
1124    0
1155    3
Name: FTR, dtype: object
1.3
Getafe - local
963     0
987     3
1007    3
1027    0
1041    3
1068    0
1097    0
1118    1
1129    3
1156    0
Name: FTR, dtype: object
1.3
9
12.2
Alaves - visitante
958     1
978     3
998     0
1019    0
1034    0
1060    3
1073    0
1095    3
1102    3
1137    0
Name: FTR, dtype: object
1.3
Sociedad - local
978     0
991     0
1010    3
1032    1
1051    1
1076    0
1088    1
1107    0
1152    3
1178    3
Name: FTR, dtype: object
1.2
12
14.2
Espanol - visitante
976     0
1007    0
1021    0
1049    1
1053    3
1080    1
1096    0
1114    0
1136    1
1143    3
Name: FTR, dtype: object
0.9
Betis - local
974     1
994     3
1002    3
1035    1
1055    0
1075    3
1093    1
1112    3
1139    0
1158    1
Name: FTR, dtype: object
1.6
13
12.6
Real Madrid - visitante
970     1
992     3
1017    0
1022    3
1042    0
1069    0
1085    0
1109    1
1123    3
1144    1
Name: FTR, dtype: object
1.2
Barcelona - local
975     3
1003    3
1023    0
1042    3
1059    3
1079    1
1094    1
1113    3
1137    3
1141    3
Name: FTR, dtype: object
2.3
31
19.1
Eibar - visitante
974     1
1009    0
1025    1
1046    0
1067    3
1089    0
1108    1
1129    0
1142    1
1168    3
Name: FTR, dtype: object
1.0
Ath Madrid - local
976     3
998     3
1018    1
1028    3
1047    3
1065    3
1090    3
1108    1
1126    3
1142    1
Name: FTR, dtype: object
2.4
18
11.1
Levante - visitante
971     0
993     1
1016    1
1031    1
1058    3
1068    3
1081    0
1105    0
1139    3
1149    0
Name: FTR, dtype: object
1.2
Ath Bilbao - local
977     1
990     3
1014    1
1048    1
1070    0
1087    0
1109    1
1121    1
1131    3
1143    0
Name: FTR, dtype: object
1.1
9
13.3
Sevilla - visitante
973     1
996     1
1004    1
1032    1
1059    0
1078    3
1092    3
1112    0
1132    3
1158    1
Name: FTR, dtype: object
1.4
Villarreal - local
970     1
995     0
1011    3
1031    1
1056    1
1072    0
1091    1
1117    0
1135    0
1144    1
Name: FTR, dtype: object
0.8
11
16.0
Getafe - visitante
979     1
999     1
1014    1
1033    1
1052    3
1071    1
1083    1
1103    3
1133    0
1146    3
Name: FTR, dtype: object
1.5
Valencia - local
972     3
996     1
1015    3
1037    0
1057    1
1062    1
1084    1
1106    1
1130    1
1140    3
Name: FTR, dtype: object
1.5
12
16.4
Valladolid - visitante
977     1
991     3
1012    0
1038    0
1055    3
1072    3
1099    1
1118    1
1138    1
2675    0
Name: FTR, dtype: object
1.3
Leganes - local
973     1
999     1
1019    3
1039    1
1066    3
1086    3
1104    0
1128    1
1147    3
1162    0
Name: FTR, dtype: object
1.6
12
12.9
Huesca - visitante
972     0
1008    0
1024    0
1040    0
1061    0
1090    0
1113    0
1121    1
1134    3
Name: FTR, dtype: object
0.4444444444444444
Girona - local
979     1
1001    1
1026    1
1045    3
1067    0
1082    0
1101    3
1123    0
1138    1
1155    0
Name: FTR, dtype: object
1.0
10
11.2
Alaves - visitante
978     3
998     0
1019    0
1034    0
1060    3
1073    0
1095    3
1102    3
1137    0
1145    0
Name: FTR, dtype: object
1.2
Vallecano - local
971     3
1009    3
1020    1
1036    0
1050    1
1052    0
1080    1
1095    0
1132    0
1900    3
Name: FTR, dtype: object
1.2
16
12.8
Celta - visitante
975     0
995     3
1010    0
1035    1
1063    0
1084    1
1101    0
1120    3
1153    0
1177    0
Name: FTR, dtype: object
0.8
Celta - local
989     1
1008    3
1022    0
1046    3
1060    0
1071    1
1099    1
1116    3
1136    1
1149    3
Name: FTR, dtype: object
1.6
19
13.3
Ath Bilbao - visitante
980     1
1000    0
1028    0
1030    0
1050    1
1054    1
1079    1
1093    1
1159    0
1178    0
Name: FTR, dtype: object
0.5
Sevilla - local
981     3
1012    3
1021    3
1040    3
1063    3
1085    3
1103    0
1122    1
1145    3
1160    3
Name: FTR, dtype: object
2.5
16
16.8
Ath Madrid - visitante
985     3
1001    1
1039    1
1056    1
1077    1
1097    3
1116    0
1130    1
1156    3
1176    3
Name: FTR, dtype: object
1.7
Real Madrid - local
986     3
1006    3
1038    3
1058    0
1077    1
1096    3
1115    3
1133    3
1153    3
1179    3
Name: FTR, dtype: object
2.5
21
16.0
Sociedad - visitante
987     0
1002    0
1029    3
1047    0
1070    3
1100    3
1119    0
1128    1
1135    3
1141    0
Name: FTR, dtype: object
1.3
Getafe - local
987     3
1007    3
1027    0
1041    3
1068    0
1097    0
1118    1
1129    3
1156    0
1175    1
Name: FTR, dtype: object
1.4
9
12.2
Barcelona - visitante
982     3
997     3
1018    1
1036    3
1062    1
1086    0
1107    3
1125    3
1150    0
1174    3
Name: FTR, dtype: object
2.0
Eibar - local
988     1
993     1
1017    3
1034    3
1054    1
1078    0
1098    3
1119    3
1134    0
1157    3
Name: FTR, dtype: object
1.8
17
17.0
Villarreal - visitante
983     1
1003    0
1020    1
1043    0
1064    0
1087    3
1104    3
1122    1
1154    3
1161    0
Name: FTR, dtype: object
1.2
Valladolid - local
985     0
1005    0
1025    1
1049    1
1061    3
1081    3
1102    0
1125    0
2661    0
2680    1
Name: FTR, dtype: object
0.9
9
11.9
Vallecano - visitante
986     0
994     0
1015    0
1045    0
1066    0
1088    1
1110    3
1126    0
1911    0
1928    0
Name: FTR, dtype: object
0.4
Huesca - local
983     1
992     0
1016    1
1033    1
1053    0
1074    1
1100    0
1110    0
Name: FTR, dtype: object
0.5
6
17.625
Betis - visitante
984     3
1011    0
1023    3
1041    0
1065    0
1082    3
1106    1
1127    1
1147    0
1170    0
Name: FTR, dtype: object
1.1
Alaves - local
980     1
1004    1
1024    3
1043    3
1069    3
1083    1
1114    3
1127    1
1159    3
1176    0
Name: FTR, dtype: object
1.9
12
11.2
Valencia - visitante
988     1
1006    0
1027    3
1048    1
1076    3
1091    1
1111    1
1124    0
1155    3
1167    0
Name: FTR, dtype: object
1.3
Levante - local
982     0
1000    3
1029    0
1044    3
1073    3
1092    0
1111    1
1120    0
1150    3
1181    3
Name: FTR, dtype: object
1.6
20
15.1
Girona - visitante
981     0
990     0
1013    3
1037    3
1051    1
1074    1
1094    1
1117    3
1148    3
1175    1
Name: FTR, dtype: object
1.6
Espanol - local
984     0
997     0
1013    0
1030    3
1064    3
1089    3
1105    3
1124    3
1151    3
1180    1
Name: FTR, dtype: object
1.9
15
16.4
Leganes - visitante
989     1
1005    3
1026    1
1044    0
1057    1
1075    0
1098    0
1115    0
1131    0
1152    0
Name: FTR, dtype: object
0.6
Villarreal - local
995     0
1011    3
1031    1
1056    1
1072    0
1091    1
1117    0
1135    0
1144    1
1167    3
Name: FTR, dtype: object
1.0
10
16.1
Real Madrid - visitante
992     3
1017    0
1022    3
1042    0
1069    0
1085    0
1109    1
1123    3
1144    1
1160    0
Name: FTR, dtype: object
1.1
Vallecano - local
1009    3
1020    1
1036    0
1050    1
1052    0
1080    1
1095    0
1132    0
1900    3
1935    0
Name: FTR, dtype: object
0.9
16
12.1
Levante - visitante
993     1
1016    1
1031    1
1058    3
1068    3
1081    0
1105    0
1139    3
1149    0
1162    3
Name: FTR, dtype: object
1.5
Valencia - local
996     1
1015    3
1037    0
1057    1
1062    1
1084    1
1106    1
1130    1
1140    3
1173    1
Name: FTR, dtype: object
1.3
10
16.1
Huesca - visitante
1008    0
1024    0
1040    0
1061    0
1090    0
1113    0
1121    1
1134    3
Name: FTR, dtype: object
0.5
Leganes - local
999     1
1019    3
1039    1
1066    3
1086    3
1104    0
1128    1
1147    3
1162    0
1189    1
Name: FTR, dtype: object
1.6
11
12.9
Sevilla - visitante
996     1
1004    1
1032    1
1059    0
1078    3
1092    3
1112    0
1132    3
1158    1
1181    0
Name: FTR, dtype: object
1.3
Betis - local
994     3
1002    3
1035    1
1055    0
1075    3
1093    1
1112    3
1139    0
1158    1
1172    3
Name: FTR, dtype: object
1.8
14
13.4
Eibar - visitante
1009    0
1025    1
1046    0
1067    3
1089    0
1108    1
1129    0
1142    1
1168    3
1173    1
Name: FTR, dtype: object
1.0
Barcelona - local
1003    3
1023    0
1042    3
1059    3
1079    1
1094    1
1113    3
1137    3
1141    3
1161    3
Name: FTR, dtype: object
2.3
34
19.4
Celta - visitante
995     3
1010    0
1035    1
1063    0
1084    1
1101    0
1120    3
1153    0
1177    0
1205    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
998     3
1018    1
1028    3
1047    3
1065    3
1090    3
1108    1
1126    3
1142    1
1166    0
Name: FTR, dtype: object
2.1
17
11.2
Espanol - visitante
1007    0
1021    0
1049    1
1053    3
1080    1
1096    0
1114    0
1136    1
1143    3
1166    3
Name: FTR, dtype: object
1.2
Ath Bilbao - local
990     3
1014    1
1048    1
1070    0
1087    0
1109    1
1121    1
1131    3
1143    0
1170    3
Name: FTR, dtype: object
1.3
10
13.9
Valladolid - visitante
991     3
1012    0
1038    0
1055    3
1072    3
1099    1
1118    1
1138    1
2675    0
2691    0
Name: FTR, dtype: object
1.2
Sociedad - local
991     0
1010    3
1032    1
1051    1
1076    0
1088    1
1107    0
1152    3
1178    3
1190    3
Name: FTR, dtype: object
1.5
15
13.6
Alaves - visitante
998     0
1019    0
1034    0
1060    3
1073    0
1095    3
1102    3
1137    0
1145    0
1163    3
Name: FTR, dtype: object
1.2
Girona - local
1001    1
1026    1
1045    3
1067    0
1082    0
1101    3
1123    0
1138    1
1155    0
1168    0
Name: FTR, dtype: object
0.9
10
11.6
Getafe - visitante
999     1
1014    1
1033    1
1052    3
1071    1
1083    1
1103    3
1133    0
1146    3
1164    3
Name: FTR, dtype: object
1.7
Alaves - local
1004    1
1024    3
1043    3
1069    3
1083    1
1114    3
1127    1
1159    3
1176    0
1193    0
Name: FTR, dtype: object
1.8
13
11.2
Ath Bilbao - visitante
1000    0
1028    0
1030    0
1050    1
1054    1
1079    1
1093    1
1159    0
1178    0
1195    1
Name: FTR, dtype: object
0.5
Sevilla - local
1012    3
1021    3
1040    3
1063    3
1085    3
1103    0
1122    1
1145    3
1160    3
1171    3
Name: FTR, dtype: object
2.5
15
16.7
Girona - visitante
990     0
1013    3
1037    3
1051    1
1074    1
1094    1
1117    3
1148    3
1175    1
1193    3
Name: FTR, dtype: object
1.9
Levante - local
1000    3
1029    0
1044    3
1073    3
1092    0
1111    1
1120    0
1150    3
1181    3
1191    3
Name: FTR, dtype: object
1.9
21
14.2
Barcelona - visitante
997     3
1018    1
1036    3
1062    1
1086    0
1107    3
1125    3
1150    0
1174    3
1199    1
Name: FTR, dtype: object
1.8
Huesca - local
992     0
1016    1
1033    1
1053    0
1074    1
1100    0
1110    0
Name: FTR, dtype: object
0.42857142857142855
4
15.857142857142858
Villarreal - visitante
1003    0
1020    1
1043    0
1064    0
1087    3
1104    3
1122    1
1154    3
1161    0
1204    1
Name: FTR, dtype: object
1.2
Espanol - local
997     0
1013    0
1030    3
1064    3
1089    3
1105    3
1124    3
1151    3
1180    1
1196    0
Name: FTR, dtype: object
1.9
14
16.4
Betis - visitante
1011    0
1023    3
1041    0
1065    0
1082    3
1106    1
1127    1
1147    0
1170    0
1186    1
Name: FTR, dtype: object
0.9
Valladolid - local
1005    0
1025    1
1049    1
1061    3
1081    3
1102    0
1125    0
2661    0
2680    1
2686    3
Name: FTR, dtype: object
1.2
8
12.1
Ath Madrid - visitante
1001    1
1039    1
1056    1
1077    1
1097    3
1116    0
1130    1
1156    3
1176    3
1190    0
Name: FTR, dtype: object
1.4
Real Madrid - local
1006    3
1038    3
1058    0
1077    1
1096    3
1115    3
1133    3
1153    3
1179    3
1195    1
Name: FTR, dtype: object
2.3
21
18.0
Vallecano - visitante
994     0
1015    0
1045    0
1066    0
1088    1
1110    3
1126    0
1911    0
1928    0
1945    1
Name: FTR, dtype: object
0.5
Getafe - local
1007    3
1027    0
1041    3
1068    0
1097    0
1118    1
1129    3
1156    0
1175    1
1201    3
Name: FTR, dtype: object
1.4
9
12.6
Sociedad - visitante
1002    0
1029    3
1047    0
1070    3
1100    3
1119    0
1128    1
1135    3
1141    0
1171    0
Name: FTR, dtype: object
1.3
Eibar - local
993     1
1017    3
1034    3
1054    1
1078    0
1098    3
1119    3
1134    0
1157    3
1187    0
Name: FTR, dtype: object
1.7
16
16.4
Valencia - visitante
1006    0
1027    3
1048    1
1076    3
1091    1
1111    1
1124    0
1155    3
1167    0
1188    1
Name: FTR, dtype: object
1.3
Celta - local
1008    3
1022    0
1046    3
1060    0
1071    1
1099    1
1116    3
1136    1
1149    3
1169    1

Name: FTR, dtype: object
1.6
20
13.1
Leganes - visitante
1005    3
1026    1
1044    0
1057    1
1075    0
1098    0
1115    0
1131    0
1152    0
1179    0
Name: FTR, dtype: object
0.5
Ath Bilbao - local
1014    1
1048    1
1070    0
1087    0
1109    1
1121    1
1131    3
1143    0
1170    3
1182    0
Name: FTR, dtype: object
1.0
10
13.2
Girona - visitante
1013    3
1037    3
1051    1
1074    1
1094    1
1117    3
1148    3
1175    1
1193    3
1212    0
Name: FTR, dtype: object
1.9
Sociedad - local
1010    3
1032    1
1051    1
1076    0
1088    1
1107    0
1152    3
1178    3
1190    3
1212    3
Name: FTR, dtype: object
1.8
19
12.6
Valladolid - visitante
1012    0
1038    0
1055    3
1072    3
1099    1
1118    1
1138    1
2675    0
2691    0
2719    1
Name: FTR, dtype: object
1.0
Huesca - local
1016    1
1033    1
1053    0
1074    1
1100    0
1110    0
Name: FTR, dtype: object
0.5
4
16.666666666666668
Real Madrid - visitante
1017    0
1022    3
1042    0
1069    0
1085    0
1109    1
1123    3
1144    1
1160    0
1165    1
Name: FTR, dtype: object
0.9
Eibar - local
1017    3
1034    3
1054    1
1078    0
1098    3
1119    3
1134    0
1157    3
1187    0
1202    0
Name: FTR, dtype: object
1.6
12
15.3
Levante - visitante
1016    1
1031    1
1058    3
1068    3
1081    0
1105    0
1139    3
1149    0
1162    3
1182    3
Name: FTR, dtype: object
1.7
Betis - local
1002    3
1035    1
1055    0
1075    3
1093    1
1112    3
1139    0
1158    1
1172    3
1192    3
Name: FTR, dtype: object
1.8
13
14.3
Vallecano - visitante
1015    0
1045    0
1066    0
1088    1
1110    3
1126    0
1911    0
1928    0
1945    1
1964    0
Name: FTR, dtype: object
0.5
Villarreal - local
1011    3
1031    1
1056    1
1072    0
1091    1
1117    0
1135    0
1144    1
1167    3
1177    3
Name: FTR, dtype: object
1.3
12
16.1
Celta - visitante
1010    0
1035    1
1063    0
1084    1
1101    0
1120    3
1153    0
1177    0
1205    0
1229    1
Name: FTR, dtype: object
0.6
Valencia - local
1015    3
1037    0
1057    1
1062    1
1084    1
1106    1
1130    1
1140    3
1173    1
1194    0
Name: FTR, dtype: object
1.2
10
15.5
Sevilla - visitante
1004    1
1032    1
1059    0
1078    3
1092    3
1112    0
1132    3
1158    1
1181    0
1198    1
Name: FTR, dtype: object
1.3
Espanol - local
1013    0
1030    3
1064    3
1089    3
1105    3
1124    3
1151    3
1180    1
1196    0
1223    1
Name: FTR, dtype: object
2.0
14
16.1
Barcelona - visitante
1018    1
1036    3
1062    1
1086    0
1107    3
1125    3
1150    0
1174    3
1199    1
1226    1
Name: FTR, dtype: object
1.6
Ath Madrid - local
1018    1
1028    3
1047    3
1065    3
1090    3
1108    1
1126    3
1142    1
1166    0
1186    1
Name: FTR, dtype: object
1.9
14
11.0
Alaves - visitante
1019    0
1034    0
1060    3
1073    0
1095    3
1102    3
1137    0
1145    0
1163    3
1184    3
Name: FTR, dtype: object
1.5
Leganes - local
1019    3
1039    1
1066    3
1086    3
1104    0
1128    1
1147    3
1162    0
1189    1
1205    3
Name: FTR, dtype: object
1.8
11
13.1
Getafe - visitante
1014    1
1033    1
1052    3
1071    1
1083    1
1103    3
1133    0
1146    3
1164    3
1187    3
Name: FTR, dtype: object
1.9
Levante - local
1029    0
1044    3
1073    3
1092    0
1111    1
1120    0
1150    3
1181    3
1191    3
1214    3
Name: FTR, dtype: object
1.9
20
13.6
Ath Bilbao - visitante
1028    0
1030    0
1050    1
1054    1
1079    1
1093    1
1159    0
1178    0
1195    1
1210    3
Name: FTR, dtype: object
0.8
Girona - local
1026    1
1045    3
1067    0
1082    0
1101    3
1123    0
1138    1
1155    0
1168    0
1185    0
Name: FTR, dtype: object
0.8
9
12.3
Ath Madrid - visitante
1039    1
1056    1
1077    1
1097    3
1116    0
1130    1
1156    3
1176    3
1190    0
1213    1
Name: FTR, dtype: object
1.4
Betis - local
1035    1
1055    0
1075    3
1093    1
1112    3
1139    0
1158    1
1172    3
1192    3
1216    3
Name: FTR, dtype: object
1.8
14
15.0
Sociedad - visitante
1029    3
1047    0
1070    3
1100    3
1119    0
1128    1
1135    3
1141    0
1171    0
1183    0
Name: FTR, dtype: object
1.3
Barcelona - local
1023    0
1042    3
1059    3
1079    1
1094    1
1113    3
1137    3
1141    3
1161    3
1165    1
Name: FTR, dtype: object
2.1
34
18.9
Villarreal - visitante
1020    1
1043    0
1064    0
1087    3
1104    3
1122    1
1154    3
1161    0
1204    1
1221    0
Name: FTR, dtype: object
1.2
Alaves - local
1024    3
1043    3
1069    3
1083    1
1114    3
1127    1
1159    3
1176    0
1193    0
1218    3
Name: FTR, dtype: object
2.0
14
11.2
Sevilla - visitante
1032    1
1059    0
1078    3
1092    3
1112    0
1132    3
1158    1
1181    0
1198    1
1215    0
Name: FTR, dtype: object
1.2
Valladolid - local
1025    1
1049    1
1061    3
1081    3
1102    0
1125    0
2661    0
2680    1
2686    3
2721    1
Name: FTR, dtype: object
1.3
6
11.2
Leganes - visitante
1026    1
1044    0
1057    1
1075    0
1098    0
1115    0
1131    0
1152    0
1179    0
1197    0
Name: FTR, dtype: object
0.2
Real Madrid - local
1038    3
1058    0
1077    1
1096    3
1115    3
1133    3
1153    3
1179    3
1195    1
1213    1
Name: FTR, dtype: object
2.1
20
19.7
Valencia - visitante
1027    3
1048    1
1076    3
1091    1
1111    1
1124    0
1155    3
1167    0
1188    1
1207    0
Name: FTR, dtype: object
1.3
Getafe - local
1027    0
1041    3
1068    0
1097    0
1118    1
1129    3
1156    0
1175    1
1201    3
1220    0
Name: FTR, dtype: object
1.1
6
12.0
Espanol - visitante
1021    0
1049    1
1053    3
1080    1
1096    0
1114    0
1136    1
1143    3
1166    3
1185    3
Name: FTR, dtype: object
1.5
Celta - local
1022    0
1046    3
1060    0
1071    1
1099    1
1116    3
1136    1
1149    3
1169    1
1188    1
Name: FTR, dtype: object
1.4
19
12.9
Huesca - visitante
1024    0
1040    0
1061    0
1090    0
1113    0
1121    1
1134    3
Name: FTR, dtype: object
0.5714285714285714
Vallecano - local
1020    1
1036    0
1050    1
1052    0
1080    1
1095    0
1132    0
1900    3
1935    0
1950    3
Name: FTR, dtype: object
0.9
17
13.0
Eibar - visitante
1025    1
1046    0
1067    3
1089    0
1108    1
1129    0
1142    1
1168    3
1173    1
1196    3
Name: FTR, dtype: object
1.3
Sociedad - local
1032    1
1051    1
1076    0
1088    1
1107    0
1152    3
1178    3
1190    3
1212    3
1236    0
Name: FTR, dtype: object
1.5
18
11.9
Celta - visitante
1035    1
1063    0
1084    1
1101    0
1120    3
1153    0
1177    0
1205    0
1229    1
1243    0
Name: FTR, dtype: object
0.6
Villarreal - local
1031    1
1056    1
1072    0
1091    1
1117    0
1135    0
1144    1
1167    3
1177    3
1197    3
Name: FTR, dtype: object
1.3
12
16.5
Betis - visitante
1023    3
1041    0
1065    0
1082    3
1106    1
1127    1
1147    0
1170    0
1186    1
1209    3
Name: FTR, dtype: object
1.2
Sevilla - local
1021    3
1040    3
1063    3
1085    3
1103    0
1122    1
1145    3
1160    3
1171    3
1204    1
Name: FTR, dtype: object
2.3
16
16.8
Valladolid - visitante
1038    0
1055    3
1072    3
1099    1
1118    1
1138    1
2675    0
2691    0
2719    1
2740    0
Name: FTR, dtype: object
1.0
Espanol - local
1030    3
1064    3
1089    3
1105    3
1124    3
1151    3
1180    1
1196    0
1223    1
1242    3
Name: FTR, dtype: object
2.3
15
16.1
Girona - visitante
1037    3
1051    1
1074    1
1094    1
1117    3
1148    3
1175    1
1193    3
1212    0
1231    0
Name: FTR, dtype: object
1.6
Ath Bilbao - local
1048    1
1070    0
1087    0
1109    1
1121    1
1131    3
1143    0
1170    3
1182    0
1208    0
Name: FTR, dtype: object
0.9
11
13.7
Getafe - visitante
1033    1
1052    3
1071    1
1083    1
1103    3
1133    0
1146    3
1164    3
1187    3
1194    3
Name: FTR, dtype: object
2.1
Valencia - local
1037    0
1057    1
1062    1
1084    1
1106    1
1130    1
1140    3
1173    1
1194    0
1211    3
Name: FTR, dtype: object
1.2
8
15.6
Vallecano - visitante
1045    0
1066    0
1088    1
1110    3
1126    0
1911    0
1928    0
1945    1
1964    0
1987    1
Name: FTR, dtype: object
0.6
Huesca - local
1033    1
1053    0
1074    1
1100    0
1110    0
Name: FTR, dtype: object
0.4
2
13.6
Levante - visitante
1031    1
1058    3
1068    3
1081    0
1105    0
1139    3
1149    0
1162    3
1182    3
1203    0
Name: FTR, dtype: object
1.6
Eibar - local
1034    3
1054    1
1078    0
1098    3
1119    3
1134    0
1157    3
1187    0
1202    0
1224    1
Name: FTR, dtype: object
1.4
9
15.4
Real Madrid - visitante
1022    3
1042    0
1069    0
1085    0
1109    1
1123    3
1144    1
1160    0
1165    1
1200    3
Name: FTR, dtype: object
1.2
Ath Madrid - local
1028    3
1047    3
1065    3
1090    3
1108    1
1126    3
1142    1
1166    0
1186    1
1203    3
Name: FTR, dtype: object
2.1
16
12.0
Barcelona - visitante
1036    3
1062    1
1086    0
1107    3
1125    3
1150    0
1174    3
1199    1
1226    1
1246    3
Name: FTR, dtype: object
1.8
Leganes - local
1039    1
1066    3
1086    3
1104    0
1128    1
1147    3
1162    0
1189    1
1205    3
1222    0
Name: FTR, dtype: object
1.5
10
12.6
Alaves - visitante
1034    0
1060    3
1073    0
1095    3
1102    3
1137    0
1145    0
1163    3
1184    3
1202    3
Name: FTR, dtype: object
1.8
Vallecano - local
1036    0
1050    1
1052    0
1080    1
1095    0
1132    0
1900    3
1935    0
1950    3
1979    3
Name: FTR, dtype: object
1.1
17
13.1
Villarreal - visitante
1043    0
1064    0
1087    3
1104    3
1122    1
1154    3
1161    0
1204    1
1221    0
1241    3
Name: FTR, dtype: object
1.4
Sevilla - local
1040    3
1063    3
1085    3
1103    0
1122    1
1145    3
1160    3
1171    3
1204    1
1226    1
Name: FTR, dtype: object
2.1
16
16.6
Espanol - visitante
1049    1
1053    3
1080    1
1096    0
1114    0
1136    1
1143    3
1166    3
1185    3
1201    0
Name: FTR, dtype: object
1.5
Celta - local
1046    3
1060    0
1071    1
1099    1
1116    3
1136    1
1149    3
1169    1
1188    1
1199    1
Name: FTR, dtype: object
1.5
19
13.2
Real Madrid - visitante
1042    0
1069    0
1085    0
1109    1
1123    3
1144    1
1160    0
1165    1
1200    3
1227    3
Name: FTR, dtype: object
1.2
Barcelona - local
1042    3
1059    3
1079    1
1094    1
1113    3
1137    3
1141    3
1161    3
1165    1
1207    3
Name: FTR, dtype: object
2.4
33
18.1
Betis - visitante
1041    0
1065    0
1082    3
1106    1
1127    1
1147    0
1170    0
1186    1
1209    3
1220    3
Name: FTR, dtype: object
1.2
Alaves - local
1043    3
1069    3
1083    1
1114    3
1127    1
1159    3
1176    0
1193    0
1218    3
1240    0
Name: FTR, dtype: object
1.7
13
10.8
Huesca - visitante
1040    0
1061    0
1090    0
1113    0
1121    1
1134    3
Name: FTR, dtype: object
0.6666666666666666
Valladolid - local
1049    1
1061    3
1081    3
1102    0
1125    0
2661    0
2680    1
2686    3
2721    1
2733    3
Name: FTR, dtype: object
1.5
7
12.3
Eibar - visitante
1046    0
1067    3
1089    0
1108    1
1129    0
1142    1
1168    3
1173    1
1196    3
1216    0
Name: FTR, dtype: object
1.2
Girona - local
1045    3
1067    0
1082    0
1101    3
1123    0
1138    1
1155    0
1168    0
1185    0
1209    0
Name: FTR, dtype: object
0.7
9
12.7
Leganes - visitante
1044    0
1057    1
1075    0
1098    0
1115    0
1131    0
1152    0
1179    0
1197    0
1217    0
Name: FTR, dtype: object
0.1
Getafe - local
1041    3
1068    0
1097    0
1118    1
1129    3
1156    0
1175    1
1201    3
1220    0
1247    0
Name: FTR, dtype: object
1.1
6
11.4
Valencia - visitante
1048    1
1076    3
1091    1
1111    1
1124    0
1155    3
1167    0
1188    1
1207    0
1222    3
Name: FTR, dtype: object
1.3
Ath Madrid - local
1047    3
1065    3
1090    3
1108    1
1126    3
1142    1
1166    0
1186    1
1203    3
1225    3

Name: FTR, dtype: object
2.1
14
12.6
Ath Bilbao - visitante
1030    0
1050    1
1054    1
1079    1
1093    1
1159    0
1178    0
1195    1
1210    3
1234    0
Name: FTR, dtype: object
0.8
Levante - local
1044    3
1073    3
1092    0
1111    1
1120    0
1150    3
1181    3
1191    3
1214    3
1239    3
Name: FTR, dtype: object
2.2
21
12.5
Sociedad - visitante
1047    0
1070    3
1100    3
1119    0
1128    1
1135    3
1141    0
1171    0
1183    0
1206    3
Name: FTR, dtype: object
1.3
Espanol - local
1064    3
1089    3
1105    3
1124    3
1151    3
1180    1
1196    0
1223    1
1242    3
1269    3
Name: FTR, dtype: object
2.3
15
16.9
Ath Bilbao - visitante
1050    1
1054    1
1079    1
1093    1
1159    0
1178    0
1195    1
1210    3
1234    0
1256    0
Name: FTR, dtype: object
0.8
Villarreal - local
1056    1
1072    0
1091    1
1117    0
1135    0
1144    1
1167    3
1177    3
1197    3
1210    0
Name: FTR, dtype: object
1.2
12
14.9
Levante - visitante
1058    3
1068    3
1081    0
1105    0
1139    3
1149    0
1162    3
1182    3
1203    0
1228    1
Name: FTR, dtype: object
1.6
Sociedad - local
1051    1
1076    0
1088    1
1107    0
1152    3
1178    3
1190    3
1212    3
1236    0
1252    3
Name: FTR, dtype: object
1.7
20
12.3
Sevilla - visitante
1059    0
1078    3
1092    3
1112    0
1132    3
1158    1
1181    0
1198    1
1215    0
1232    0
Name: FTR, dtype: object
1.1
Huesca - local
1053    0
1074    1
1100    0
1110    0
Name: FTR, dtype: object
0.25
1
12.5
Getafe - visitante
1052    3
1071    1
1083    1
1103    3
1133    0
1146    3
1164    3
1187    3
1194    3
1218    0
Name: FTR, dtype: object
2.0
Eibar - local
1054    1
1078    0
1098    3
1119    3
1134    0
1157    3
1187    0
1202    0
1224    1
1248    0
Name: FTR, dtype: object
1.1
8
14.3
Alaves - visitante
1060    3
1073    0
1095    3
1102    3
1137    0
1145    0
1163    3
1184    3
1202    3
1223    1
Name: FTR, dtype: object
1.9
Betis - local
1055    0
1075    3
1093    1
1112    3
1139    0
1158    1
1172    3
1192    3
1216    3
1238    3
Name: FTR, dtype: object
2.0
14
14.5
Celta - visitante
1063    0
1084    1
1101    0
1120    3
1153    0
1177    0
1205    0
1229    1
1243    0
1268    0
Name: FTR, dtype: object
0.5
Vallecano - local
1050    1
1052    0
1080    1
1095    0
1132    0
1900    3
1935    0
1950    3
1979    3
1995    1
Name: FTR, dtype: object
1.2
16
13.2
Barcelona - visitante
1062    1
1086    0
1107    3
1125    3
1150    0
1174    3
1199    1
1226    1
1246    3
1260    1
Name: FTR, dtype: object
1.6
Valencia - local
1057    1
1062    1
1084    1
1106    1
1130    1
1140    3
1173    1
1194    0
1211    3
1235    3
Name: FTR, dtype: object
1.5
11
15.3
Girona - visitante
1051    1
1074    1
1094    1
1117    3
1148    3
1175    1
1193    3
1212    0
1231    0
1255    3
Name: FTR, dtype: object
1.6
Real Madrid - local
1058    0
1077    1
1096    3
1115    3
1133    3
1153    3
1179    3
1195    1
1213    1
1231    3
Name: FTR, dtype: object
2.1
24
20.1
Valladolid - visitante
1055    3
1072    3
1099    1
1118    1
1138    1
2675    0
2691    0
2719    1
2740    0
2762    0
Name: FTR, dtype: object
1.0
Leganes - local
1066    3
1086    3
1104    0
1128    1
1147    3
1162    0
1189    1
1205    3
1222    0
1232    3
Name: FTR, dtype: object
1.7
11
13.0
Ath Madrid - visitante
1056    1
1077    1
1097    3
1116    0
1130    1
1156    3
1176    3
1190    0
1213    1
1230    0
Name: FTR, dtype: object
1.3
Sevilla - local
1063    3
1085    3
1103    0
1122    1
1145    3
1160    3
1171    3
1204    1
1226    1
1245    0
Name: FTR, dtype: object
1.8
14
17.2
Huesca - visitante
1061    0
1090    0
1113    0
1121    1
1134    3
Name: FTR, dtype: object
0.8
Getafe - local
1068    0
1097    0
1118    1
1129    3
1156    0
1175    1
1201    3
1220    0
1247    0
1264    3
Name: FTR, dtype: object
1.1
7
11.2
Betis - visitante
1065    0
1082    3
1106    1
1127    1
1147    0
1170    0
1186    1
1209    3
1220    3
1240    3
Name: FTR, dtype: object
1.5
Barcelona - local
1059    3
1079    1
1094    1
1113    3
1137    3
1141    3
1161    3
1165    1
1207    3
1217    3
Name: FTR, dtype: object
2.4
31
18.0
Real Madrid - visitante
1069    0
1085    0
1109    1
1123    3
1144    1
1160    0
1165    1
1200    3
1227    3
1248    3
Name: FTR, dtype: object
1.5
Alaves - local
1069    3
1083    1
1114    3
1127    1
1159    3
1176    0
1193    0
1218    3
1240    0
1262    3
Name: FTR, dtype: object
1.7
12
10.4
Villarreal - visitante
1064    0
1087    3
1104    3
1122    1
1154    3
1161    0
1204    1
1221    0
1241    3
1265    0
Name: FTR, dtype: object
1.4
Levante - local
1073    3
1092    0
1111    1
1120    0
1150    3
1181    3
1191    3
1214    3
1239    3
1253    1
Name: FTR, dtype: object
2.0
20
12.9
Leganes - visitante
1057    1
1075    0
1098    0
1115    0
1131    0
1152    0
1179    0
1197    0
1217    0
1244    0
Name: FTR, dtype: object
0.1
Girona - local
1067    0
1082    0
1101    3
1123    0
1138    1
1155    0
1168    0
1185    0
1209    0
1228    1
Name: FTR, dtype: object
0.5
8
12.5
Vallecano - visitante
1066    0
1088    1
1110    3
1126    0
1911    0
1928    0
1945    1
1964    0
1987    1
2000    0
Name: FTR, dtype: object
0.6
Celta - local
1060    0
1071    1
1099    1
1116    3
1136    1
1149    3
1169    1
1188    1
1199    1
1215    3
Name: FTR, dtype: object
1.5
19
13.4
Eibar - visitante
1067    3
1089    0
1108    1
1129    0
1142    1
1168    3
1173    1
1196    3
1216    0
1239    0
Name: FTR, dtype: object
1.2
Ath Madrid - local
1065    3
1090    3
1108    1
1126    3
1142    1
1166    0
1186    1
1203    3
1225    3
1243    3
Name: FTR, dtype: object
2.1
15
11.9
Sociedad - visitante
1070    3
1100    3
1119    0
1128    1
1135    3
1141    0
1171    0
1183    0
1206    3
1224    1
Name: FTR, dtype: object
1.4
Ath Bilbao - local
1070    0
1087    0
1109    1
1121    1
1131    3
1143    0
1170    3
1182    0
1208    0
1229    1
Name: FTR, dtype: object
0.9
12
13.5
Valencia - visitante
1076    3
1091    1
1111    1
1124    0
1155    3
1167    0
1188    1
1207    0
1222    3
1245    3
Name: FTR, dtype: object
1.5
Valladolid - local
1061    3
1081    3
1102    0
1125    0
2661    0
2680    1
2686    3
2721    1
2733    3
2755    1
Name: FTR, dtype: object
1.5
7
11.7
Espanol - visitante
1053    3
1080    1
1096    0
1114    0
1136    1
1143    3
1166    3
1185    3
1201    0
1211    0
Name: FTR, dtype: object
1.4
Vallecano - local
1052    0
1080    1
1095    0
1132    0
1900    3
1935    0
1950    3
1979    3
1995    1
2010    0
Name: FTR, dtype: object
1.1
16
12.9
Ath Bilbao - visitante
1054    1
1079    1
1093    1
1159    0
1178    0
1195    1
1210    3
1234    0
1256    0
1285    0
Name: FTR, dtype: object
0.7
Sociedad - local
1076    0
1088    1
1107    0
1152    3
1178    3
1190    3
1212    3
1236    0
1252    3
1282    3
Name: FTR, dtype: object
1.9
23
12.2
Girona - visitante
1074    1
1094    1
1117    3
1148    3
1175    1
1193    3
1212    0
1231    0
1255    3
1278    0
Name: FTR, dtype: object
1.5
Vallecano - local
1080    1
1095    0
1132    0
1900    3
1935    0
1950    3
1979    3
1995    1
2010    0
2030    1
Name: FTR, dtype: object
1.2
17
13.2
Getafe - visitante
1071    1
1083    1
1103    3
1133    0
1146    3
1164    3
1187    3
1194    3
1218    0
1236    3
Name: FTR, dtype: object
2.0
Huesca - local
1074    1
1100    0
1110    0
Name: FTR, dtype: object
0.3333333333333333
1
13.333333333333334
Espanol - visitante
1080    1
1096    0
1114    0
1136    1
1143    3
1166    3
1185    3
1201    0
1211    0
1238    0
Name: FTR, dtype: object
1.1
Eibar - local
1078    0
1098    3
1119    3
1134    0
1157    3
1187    0
1202    0
1224    1
1248    0
1265    3
Name: FTR, dtype: object
1.3
8
13.8
Ath Bilbao - visitante
1079    1
1093    1
1159    0
1178    0
1195    1
1210    3
1234    0
1256    0
1285    0
1302    0
Name: FTR, dtype: object
0.6
Betis - local
1075    3
1093    1
1112    3
1139    0
1158    1
1172    3
1192    3
1216    3
1238    3
1261    1
Name: FTR, dtype: object
2.1
14
13.3
Valladolid - visitante
1072    3
1099    1
1118    1
1138    1
2675    0
2691    0
2719    1
2740    0
2762    0
2785    1
Name: FTR, dtype: object
0.8
Villarreal - local
1072    0
1091    1
1117    0
1135    0
1144    1
1167    3
1177    3
1197    3
1210    0
1230    3
Name: FTR, dtype: object
1.4
13
14.8
Ath Madrid - visitante
1077    1
1097    3
1116    0
1130    1
1156    3
1176    3
1190    0
1213    1
1230    0
1254    0
Name: FTR, dtype: object
1.2
Valencia - local
1062    1
1084    1
1106    1
1130    1
1140    3
1173    1
1194    0
1211    3
1235    3
1251    3
Name: FTR, dtype: object
1.7
12
14.7
Leganes - visitante
1075    0
1098    0
1115    0
1131    0
1152    0
1179    0
1197    0
1217    0
1244    0
1266    0
Name: FTR, dtype: object
0.0
Real Madrid - local
1077    1
1096    3
1115    3
1133    3
1153    3
1179    3
1195    1
1213    1
1231    3
1257    3
Name: FTR, dtype: object
2.4
26
18.1
Levante - visitante
1068    3
1081    0
1105    0
1139    3
1149    0
1162    3
1182    3
1203    0
1228    1
1247    3
Name: FTR, dtype: object
1.6
Barcelona - local
1079    1
1094    1
1113    3
1137    3
1141    3
1161    3
1165    1
1207    3
1217    3
1234    3
Name: FTR, dtype: object
2.4
29
17.5
Sevilla - visitante
1078    3
1092    3
1112    0
1132    3
1158    1
1181    0
1198    1
1215    0
1232    0
1263    3
Name: FTR, dtype: object
1.4
Celta - local
1071    1
1099    1
1116    3
1136    1
1149    3
1169    1
1188    1
1199    1
1215    3
1233    1
Name: FTR, dtype: object
1.6
19
12.4
Alaves - visitante
1073    0
1095    3
1102    3
1137    0
1145    0
1163    3
1184    3
1202    3
1223    1
1235    0
Name: FTR, dtype: object
1.6
Valladolid - local
1081    3
1102    0
1125    0
2661    0
2680    1
2686    3
2721    1
2733    3
2755    1
2776    3
Name: FTR, dtype: object
1.5
7
11.5
Huesca - visitante
1090    0
1113    0
1121    1
1134    3
Name: FTR, dtype: object
1.0
Valencia - local
1084    1
1106    1
1130    1
1140    3
1173    1
1194    0
1211    3
1235    3
1251    3
1272    3
Name: FTR, dtype: object
1.9
13
14.4
Barcelona - visitante
1086    0
1107    3
1125    3
1150    0
1174    3
1199    1
1226    1
1246    3
1260    1
1288    3
Name: FTR, dtype: object
1.8
Sevilla - local
1085    3
1103    0
1122    1
1145    3
1160    3
1171    3
1204    1
1226    1
1245    0
1256    3
Name: FTR, dtype: object
1.8
14
17.8
Celta - visitante
1084    1
1101    0
1120    3
1153    0
1177    0
1205    0
1229    1
1243    0
1268    0
1281    0
Name: FTR, dtype: object
0.5
Espanol - local
1089    3
1105    3
1124    3
1151    3
1180    1
1196    0
1223    1
1242    3
1269    3
1283    1
Name: FTR, dtype: object
2.1
13
15.6
Villarreal - visitante
1087    3
1104    3
1122    1
1154    3
1161    0
1204    1
1221    0
1241    3
1265    0
1283    1
Name: FTR, dtype: object
1.5
Ath Madrid - local
1090    3
1108    1
1126    3
1142    1
1166    0
1186    1
1203    3
1225    3
1243    3
1266    3
Name: FTR, dtype: object
2.1
18
12.1
Betis - visitante
1082    3
1106    1
1127    1
1147    0
1170    0
1186    1
1209    3
1220    3
1240    3
1251    0
Name: FTR, dtype: object
1.5
Leganes - local
1086    3
1104    0
1128    1
1147    3
1162    0
1189    1
1205    3
1222    0
1232    3
1258    3
Name: FTR, dtype: object
1.7
12
12.7
Vallecano - visitante
1088    1
1110    3
1126    0
1911    0
1928    0
1945    1
1964    0
1987    1
2000    0
2028    1
Name: FTR, dtype: object
0.7
Girona - local
1082    0
1101    3
1123    0
1138    1
1155    0
1168    0
1185    0
1209    0
1228    1
1249    3
Name: FTR, dtype: object
0.8
8
12.4
Eibar - visitante
1089    0
1108    1
1129    0
1142    1
1168    3
1173    1
1196    3
1216    0
1239    0
1259    1
Name: FTR, dtype: object
1.0
Getafe - local
1097    0
1118    1
1129    3
1156    0
1175    1
1201    3
1220    0
1247    0
1264    3
1281    3
Name: FTR, dtype: object
1.4
10
10.6
Levante - visitante
1081    0
1105    0
1139    3
1149    0
1162    3
1182    3
1203    0
1228    1
1247    3
1262    0
Name: FTR, dtype: object
1.3
Alaves - local
1083    1
1114    3
1127    1
1159    3
1176    0
1193    0
1218    3
1240    0
1262    3
1289    3
Name: FTR, dtype: object
1.7
12
11.0
Real Madrid - visitante
1085    0
1109    1
1123    3
1144    1
1160    0
1165    1
1200    3
1227    3
1248    3
1269    0
Name: FTR, dtype: object
1.5
Ath Bilbao - local
1087    0
1109    1
1121    1
1131    3
1143    0
1170    3
1182    0
1208    0
1229    1
1244    3
Name: FTR, dtype: object
1.2
13
13.5
Sociedad - visitante
1100    3
1119    0
1128    1
1135    3
1141    0
1171    0
1183    0
1206    3
1224    1
1242    0
Name: FTR, dtype: object
1.1
Celta - local
1099    1
1116    3
1136    1
1149    3
1169    1
1188    1
1199    1
1215    3
1233    1
1250    3
Name: FTR, dtype: object
1.8
20
13.0
Getafe - visitante
1083    1
1103    3
1133    0
1146    3
1164    3
1187    3
1194    3
1218    0
1236    3
1257    0
Name: FTR, dtype: object
1.9

Villarreal - local
1091    1
1117    0
1135    0
1144    1
1167    3
1177    3
1197    3
1210    0
1230    3
1255    0
Name: FTR, dtype: object
1.4
13
13.5
Valladolid - visitante
1099    1
1118    1
1138    1
2675    0
2691    0
2719    1
2740    0
2762    0
2785    1
2808    0
Name: FTR, dtype: object
0.5
Levante - local
1092    0
1111    1
1120    0
1150    3
1181    3
1191    3
1214    3
1239    3
1253    1
1270    0
Name: FTR, dtype: object
1.7
18
12.7
Alaves - visitante
1095    3
1102    3
1137    0
1145    0
1163    3
1184    3
1202    3
1223    1
1235    0
1252    0
Name: FTR, dtype: object
1.6
Huesca - local
1100    0
1110    0
Name: FTR, dtype: object
0.0
0
13.5
Girona - visitante
1094    1
1117    3
1148    3
1175    1
1193    3
1212    0
1231    0
1255    3
1278    0
1293    0
Name: FTR, dtype: object
1.4
Betis - local
1093    1
1112    3
1139    0
1158    1
1172    3
1192    3
1216    3
1238    3
1261    1
1284    0
Name: FTR, dtype: object
1.8
16
13.6
Leganes - visitante
1098    0
1115    0
1131    0
1152    0
1179    0
1197    0
1217    0
1244    0
1266    0
1290    0
Name: FTR, dtype: object
0.0
Sociedad - local
1088    1
1107    0
1152    3
1178    3
1190    3
1212    3
1236    0
1252    3
1282    3
1310    3
Name: FTR, dtype: object
2.2
28
13.1
Valencia - visitante
1091    1
1111    1
1124    0
1155    3
1167    0
1188    1
1207    0
1222    3
1245    3
1267    1
Name: FTR, dtype: object
1.3
Real Madrid - local
1096    3
1115    3
1133    3
1153    3
1179    3
1195    1
1213    1
1231    3
1257    3
1275    3
Name: FTR, dtype: object
2.6
30
19.1
Ath Madrid - visitante
1097    3
1116    0
1130    1
1156    3
1176    3
1190    0
1213    1
1230    0
1254    0
1273    3
Name: FTR, dtype: object
1.4
Eibar - local
1098    3
1119    3
1134    0
1157    3
1187    0
1202    0
1224    1
1248    0
1265    3
1288    0
Name: FTR, dtype: object
1.3
7
13.6
Sevilla - visitante
1092    3
1112    0
1132    3
1158    1
1181    0
1198    1
1215    0
1232    0
1263    3
1287    3
Name: FTR, dtype: object
1.4
Barcelona - local
1094    1
1113    3
1137    3
1141    3
1161    3
1165    1
1207    3
1217    3
1234    3
1254    3
Name: FTR, dtype: object
2.6
29
17.1
Ath Bilbao - visitante
1093    1
1159    0
1178    0
1195    1
1210    3
1234    0
1256    0
1285    0
1302    0
1330    1
Name: FTR, dtype: object
0.6
Vallecano - local
1095    0
1132    0
1900    3
1935    0
1950    3
1979    3
1995    1
2010    0
2030    1
2056    3
Name: FTR, dtype: object
1.4
17
13.9
Espanol - visitante
1096    0
1114    0
1136    1
1143    3
1166    3
1185    3
1201    0
1211    0
1238    0
1253    1
Name: FTR, dtype: object
1.1
Valladolid - local
1102    0
1125    0
2661    0
2680    1
2686    3
2721    1
2733    3
2755    1
2776    3
2799    1
Name: FTR, dtype: object
1.3
6
10.6
Levante - visitante
1105    0
1139    3
1149    0
1162    3
1182    3
1203    0
1228    1
1247    3
1262    0
1282    0
Name: FTR, dtype: object
1.3
Girona - local
1101    3
1123    0
1138    1
1155    0
1168    0
1185    0
1209    0
1228    1
1249    3
1268    3
Name: FTR, dtype: object
1.1
9
12.7
Betis - visitante
1106    1
1127    1
1147    0
1170    0
1186    1
1209    3
1220    3
1240    3
1251    0
1270    3
Name: FTR, dtype: object
1.5
Alaves - local
1114    3
1127    1
1159    3
1176    0
1193    0
1218    3
1240    0
1262    3
1289    3
1309    3
Name: FTR, dtype: object
1.9
13
10.4
Getafe - visitante
1103    3
1133    0
1146    3
1164    3
1187    3
1194    3
1218    0
1236    3
1257    0
1271    0
Name: FTR, dtype: object
1.8
Valencia - local
1106    1
1130    1
1140    3
1173    1
1194    0
1211    3
1235    3
1251    3
1272    3
1292    3
Name: FTR, dtype: object
2.1
15
14.8
Celta - visitante
1101    0
1120    3
1153    0
1177    0
1205    0
1229    1
1243    0
1268    0
1281    0
1309    0
Name: FTR, dtype: object
0.4
Sevilla - local
1103    0
1122    1
1145    3
1160    3
1171    3
1204    1
1226    1
1245    0
1256    3
1273    0
Name: FTR, dtype: object
1.5
13
17.2
Real Madrid - visitante
1109    1
1123    3
1144    1
1160    0
1165    1
1200    3
1227    3
1248    3
1269    0
1280    3
Name: FTR, dtype: object
1.8
Leganes - local
1104    0
1128    1
1147    3
1162    0
1189    1
1205    3
1222    0
1232    3
1258    3
1276    1
Name: FTR, dtype: object
1.5
10
12.8
Barcelona - visitante
1107    3
1125    3
1150    0
1174    3
1199    1
1226    1
1246    3
1260    1
1288    3
1304    1
Name: FTR, dtype: object
1.9
Ath Bilbao - local
1109    1
1121    1
1131    3
1143    0
1170    3
1182    0
1208    0
1229    1
1244    3
1267    1
Name: FTR, dtype: object
1.3
14
13.4
Villarreal - visitante
1104    3
1122    1
1154    3
1161    0
1204    1
1221    0
1241    3
1265    0
1283    1
1308    0
Name: FTR, dtype: object
1.2
Sociedad - local
1107    0
1152    3
1178    3
1190    3
1212    3
1236    0
1252    3
1282    3
1310    3
1322    0
Name: FTR, dtype: object
2.1
27
13.1
Vallecano - visitante
1110    3
1126    0
1911    0
1928    0
1945    1
1964    0
1987    1
2000    0
2028    1
2050    1
Name: FTR, dtype: object
0.7
Espanol - local
1105    3
1124    3
1151    3
1180    1
1196    0
1223    1
1242    3
1269    3
1283    1
1304    1
Name: FTR, dtype: object
1.9
13
15.4
Eibar - visitante
1108    1
1129    0
1142    1
1168    3
1173    1
1196    3
1216    0
1239    0
1259    1
1277    0
Name: FTR, dtype: object
1.0
Ath Madrid - local
1108    1
1126    3
1142    1
1166    0
1186    1
1203    3
1225    3
1243    3
1266    3
1285    3
Name: FTR, dtype: object
2.1
17
11.8
Huesca - visitante
1113    0
1121    1
1134    3
Name: FTR, dtype: object
1.3333333333333333
Villarreal - local
1117    0
1135    0
1144    1
1167    3
1177    3
1197    3
1210    0
1230    3
1255    0
1271    3
Name: FTR, dtype: object
1.6
14
13.4
Valencia - visitante
1111    1
1124    0
1155    3
1167    0
1188    1
1207    0
1222    3
1245    3
1267    1
1286    3
Name: FTR, dtype: object
1.5
Levante - local
1111    1
1120    0
1150    3
1181    3
1191    3
1214    3
1239    3
1253    1
1270    0
1306    1
Name: FTR, dtype: object
1.8
18
12.0
Sevilla - visitante
1112    0
1132    3
1158    1
1181    0
1198    1
1215    0
1232    0
1263    3
1287    3
1307    0
Name: FTR, dtype: object
1.1
Betis - local
1112    3
1139    0
1158    1
1172    3
1192    3
1216    3
1238    3
1261    1
1284    0
1308    3
Name: FTR, dtype: object
2.0
16
13.4
Ath Bilbao - visitante
1159    0
1178    0
1195    1
1210    3
1234    0
1256    0
1285    0
1302    0
1330    1
1334    1
Name: FTR, dtype: object
0.6
Barcelona - local
1113    3
1137    3
1141    3
1161    3
1165    1
1207    3
1217    3
1234    3
1254    3
1278    3
Name: FTR, dtype: object
2.8
33
17.0
Girona - visitante
1117    3
1148    3
1175    1
1193    3
1212    0
1231    0
1255    3
1278    0
1293    0
1318    1
Name: FTR, dtype: object
1.4
Vallecano - local
1132    0
1900    3
1935    0
1950    3
1979    3
1995    1
2010    0
2030    1
2056    3
2076    3
Name: FTR, dtype: object
1.7
19
15.2
Alaves - visitante
1102    3
1137    0
1145    0
1163    3
1184    3
1202    3
1223    1
1235    0
1252    0
1275    0
Name: FTR, dtype: object
1.3
Real Madrid - local
1115    3
1133    3
1153    3
1179    3
1195    1
1213    1
1231    3
1257    3
1275    3
1297    3
Name: FTR, dtype: object
2.6
34
19.0
Espanol - visitante
1114    0
1136    1
1143    3
1166    3
1185    3
1201    0
1211    0
1238    0
1253    1
1279    1
Name: FTR, dtype: object
1.2
Getafe - local
1118    1
1129    3
1156    0
1175    1
1201    3
1220    0
1247    0
1264    3
1281    3
1303    1
Name: FTR, dtype: object
1.5
10
10.6
Ath Madrid - visitante
1116    0
1130    1
1156    3
1176    3
1190    0
1213    1
1230    0
1254    0
1273    3
1298    3
Name: FTR, dtype: object
1.4
Eibar - local
1119    3
1134    0
1157    3
1187    0
1202    0
1224    1
1248    0
1265    3
1288    0
1307    3
Name: FTR, dtype: object
1.3
11
13.9
Leganes - visitante
1115    0
1131    0
1152    0
1179    0
1197    0
1217    0
1244    0
1266    0
1290    0
1303    1
Name: FTR, dtype: object
0.1
Celta - local
1116    3
1136    1
1149    3
1169    1
1188    1
1199    1
1215    3
1233    1
1250    3
1277    3
Name: FTR, dtype: object
2.0
19
12.6
Valladolid - visitante
1118    1
1138    1
2675    0
2691    0
2719    1
2740    0
2762    0
2785    1
2808    0
2827    1
Name: FTR, dtype: object
0.5
Huesca - local
1110    0
Name: FTR, dtype: object
0.0
0
14.0
Sociedad - visitante
1119    0
1128    1
1135    3
1141    0
1171    0
1183    0
1206    3
1224    1
1242    0
1261    1
Name: FTR, dtype: object
0.9
Girona - local
1123    0
1138    1
1155    0
1168    0
1185    0
1209    0
1228    1
1249    3
1268    3
1290    3
Name: FTR, dtype: object
1.1
9
12.6
Celta - visitante
1120    3
1153    0
1177    0
1205    0
1229    1
1243    0
1268    0
1281    0
1309    0
1322    3
Name: FTR, dtype: object
0.7
Valladolid - local
1125    0
2661    0
2680    1
2686    3
2721    1
2733    3
2755    1
2776    3
2799    1
2811    1
Name: FTR, dtype: object
1.4
8
10.4
Alaves - visitante
1137    0
1145    0
1163    3
1184    3
1202    3
1223    1
1235    0
1252    0
1275    0
1296    3
Name: FTR, dtype: object
1.3
Sevilla - local
1122    1
1145    3
1160    3
1171    3
1204    1
1226    1
1245    0
1256    3
1273    0
1293    3
Name: FTR, dtype: object
1.8
14
17.0
Getafe - visitante
1133    0
1146    3
1164    3
1187    3
1194    3
1218    0
1236    3
1257    0
1271    0
1295    1
Name: FTR, dtype: object
1.6
Leganes - local
1128    1
1147    3
1162    0
1189    1
1205    3
1222    0
1232    3
1258    3
1276    1
1280    0
Name: FTR, dtype: object
1.5
11
11.9
Villarreal - visitante
1122    1
1154    3
1161    0
1204    1
1221    0
1241    3
1265    0
1283    1
1308    0
1336    3
Name: FTR, dtype: object
1.2
Espanol - local
1124    3
1151    3
1180    1
1196    0
1223    1
1242    3
1269    3
1283    1
1304    1
1328    0
Name: FTR, dtype: object
1.6
12
14.1
Levante - visitante
1139    3
1149    0
1162    3
1182    3
1203    0
1228    1
1247    3
1262    0
1282    0
1292    0
Name: FTR, dtype: object
1.3
Valencia - local
1130    1
1140    3
1173    1
1194    0
1211    3
1235    3
1251    3
1272    3
1292    3
1317    0
Name: FTR, dtype: object
2.0
16
14.7
Betis - visitante
1127    1
1147    0
1170    0
1186    1
1209    3
1220    3
1240    3
1251    0
1270    3
1291    3
Name: FTR, dtype: object
1.7
Sociedad - local
1152    3
1178    3
1190    3
1212    3
1236    0
1252    3
1282    3
1310    3
1322    0
1332    0
Name: FTR, dtype: object
2.1
28
13.8
Barcelona - visitante
1125    3
1150    0
1174    3
1199    1
1226    1
1246    3
1260    1
1288    3
1304    1
1324    3
Name: FTR, dtype: object
1.9
Ath Madrid - local
1126    3
1142    1
1166    0
1186    1
1203    3
1225    3
1243    3
1266    3
1285    3
1305    3
Name: FTR, dtype: object
2.3
17
11.4
Eibar - visitante
1129    0
1142    1
1168    3
1173    1
1196    3
1216    0
1239    0
1259    1
1277    0
1299    3
Name: FTR, dtype: object
1.2
Ath Bilbao - local
1121    1
1131    3
1143    0
1170    3
1182    0
1208    0
1229    1
1244    3
1267    1
1274    3
Name: FTR, dtype: object
1.5
15
13.1
Real Madrid - visitante
1123    3
1144    1
1160    0
1165    1
1200    3
1227    3
1248    3
1269    0
1280    3
1284    3
Name: FTR, dtype: object
2.0
Huesca - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Vallecano - visitante
1126    0
1911    0
1928    0
1945    1
1964    0
1987    1
2000    0
2028    1
2050    1
2061    1
Name: FTR, dtype: object
0.5
Levante - local
1120    0
1150    3
1181    3
1191    3
1214    3
1239    3
1253    1
1270    0
1306    1
1333    0
Name: FTR, dtype: object
1.7
16
12.2
Valencia - visitante
1124    0
1155    3
1167    0
1188    1
1207    0
1222    3
1245    3
1267    1
1286    3
1305    0
Name: FTR, dtype: object
1.4
Betis - local
1139    0
1158    1
1172    3
1192    3
1216    3
1238    3
1261    1
1284    0
1308    3
1324    0
Name: FTR, dtype: object
1.7
15
13.0
Sevilla - visitante
1132    3
1158    1
1181    0
1198    1
1215    0
1232    0
1263    3
1287    3
1307    0
1328    3
Name: FTR, dtype: object
1.4
Barcelona - local
1137    3
1141    3
1161    3
1165    1
1207    3
1217    3
1234    3
1254    3
1278    3
1295    1
Name: FTR, dtype: object
2.6
25
15.1
Huesca - visitante
1121    1
1134    3
Name: FTR, dtype: object
2.0
Alaves - local
1127    1
1159    3
1176    0
1193    0
1218    3
1240    0
1262    3
1289    3
1309    3
1325    1
Name: FTR, dtype: object
1.7
13
11.0
Espanol - visitante
1136    1
1143    3
1166    3
1185    3
1201    0
1211    0
1238    0
1253    1
1279    1
1294    1
Name: FTR, dtype: object
1.3
Real Madrid - local
1133    3
1153    3
1179    3
1195    1
1213    1
1231    3
1257    3
1275    3
1297    3
1323    3
Name: FTR, dtype: object
2.6
37
19.7
Leganes - visitante
1131    0
1152    0
1179    0
1197    0
1217    0
1244    0
1266    0
1290    0
1303    1
1325    1
Name: FTR, dtype: object
0.2
Celta - local
1136    1
1149    3
1169    1
1188    1
1199    1
1215    3
1233    1
1250    3
1277    3
1294    1
Name: FTR, dtype: object
1.8
19
13.4
Ath Madrid - visitante
1130    1
1156    3
1176    3
1190    0
1213    1
1230    0
1254    0
1273    3
1298    3
1339    3
Name: FTR, dtype: object
1.7
Villarreal - local
1135    0
1144    1
1167    3
1177    3
1197    3
1210    0
1230    3
1255    0
1271    3
1296    0
Name: FTR, dtype: object
1.6
15
14.8

Girona - visitante
1148    3
1175    1
1193    3
1212    0
1231    0
1255    3
1278    0
1293    0
1318    1
1329    1
Name: FTR, dtype: object
1.2
Getafe - local
1129    3
1156    0
1175    1
1201    3
1220    0
1247    0
1264    3
1281    3
1303    1
1330    1
Name: FTR, dtype: object
1.5
12
11.1
Valladolid - visitante
1138    1
2675    0
2691    0
2719    1
2740    0
2762    0
2785    1
2808    0
2827    1
2840    0
Name: FTR, dtype: object
0.4
Eibar - local
1134    0
1157    3
1187    0
1202    0
1224    1
1248    0
1265    3
1288    0
1307    3
1321    1
Name: FTR, dtype: object
1.1
10
14.6
Sociedad - visitante
1128    1
1135    3
1141    0
1171    0
1183    0
1206    3
1224    1
1242    0
1261    1
1272    0
Name: FTR, dtype: object
0.9
Levante - local
1150    3
1181    3
1191    3
1214    3
1239    3
1253    1
1270    0
1306    1
1333    0
1360    1
Name: FTR, dtype: object
1.8
15
11.7
Celta - visitante
1153    0
1177    0
1205    0
1229    1
1243    0
1268    0
1281    0
1309    0
1322    3
1333    3
Name: FTR, dtype: object
0.7
Ath Bilbao - local
1131    3
1143    0
1170    3
1182    0
1208    0
1229    1
1244    3
1267    1
1274    3
1300    1
Name: FTR, dtype: object
1.5
13
12.8
Huesca - visitante
1134    3
Name: FTR, dtype: object
3.0
Sevilla - local
1145    3
1160    3
1171    3
1204    1
1226    1
1245    0
1256    3
1273    0
1293    3
1312    1
Name: FTR, dtype: object
1.8
15
16.6
Villarreal - visitante
1154    3
1161    0
1204    1
1221    0
1241    3
1265    0
1283    1
1308    0
1336    3
1351    3
Name: FTR, dtype: object
1.4
Girona - local
1138    1
1155    0
1168    0
1185    0
1209    0
1228    1
1249    3
1268    3
1290    3
1302    3
Name: FTR, dtype: object
1.4
10
12.4
Real Madrid - visitante
1144    1
1160    0
1165    1
1200    3
1227    3
1248    3
1269    0
1280    3
1284    3
1306    1
Name: FTR, dtype: object
1.8
Espanol - local
1151    3
1180    1
1196    0
1223    1
1242    3
1269    3
1283    1
1304    1
1328    0
1334    1
Name: FTR, dtype: object
1.4
11
13.3
Valencia - visitante
1155    3
1167    0
1188    1
1207    0
1222    3
1245    3
1267    1
1286    3
1305    0
1327    0
Name: FTR, dtype: object
1.4
Valladolid - local
2661    0
2680    1
2686    3
2721    1
2733    3
2755    1
2776    3
2799    1
2811    1
2835    3
Name: FTR, dtype: object
1.7
9
10.5
Barcelona - visitante
1150    0
1174    3
1199    1
1226    1
1246    3
1260    1
1288    3
1304    1
1324    3
1332    3
Name: FTR, dtype: object
1.9
Ath Madrid - local
1142    1
1166    0
1186    1
1203    3
1225    3
1243    3
1266    3
1285    3
1305    3
1315    3
Name: FTR, dtype: object
2.3
19
12.3
Vallecano - visitante
1911    0
1928    0
1945    1
1964    0
1987    1
2000    0
2028    1
2050    1
2061    1
2082    1
Name: FTR, dtype: object
0.6
Alaves - local
1159    3
1176    0
1193    0
1218    3
1240    0
1262    3
1289    3
1309    3
1325    1
1335    3
Name: FTR, dtype: object
1.9
14
10.6
Betis - visitante
1147    0
1170    0
1186    1
1209    3
1220    3
1240    3
1251    0
1270    3
1291    3
1311    0
Name: FTR, dtype: object
1.6
Leganes - local
1147    3
1162    0
1189    1
1205    3
1222    0
1232    3
1258    3
1276    1
1280    0
1299    0
Name: FTR, dtype: object
1.4
9
10.3
Sociedad - visitante
1135    3
1141    0
1171    0
1183    0
1206    3
1224    1
1242    0
1261    1
1272    0
1297    0
Name: FTR, dtype: object
0.8
Getafe - local
1156    0
1175    1
1201    3
1220    0
1247    0
1264    3
1281    3
1303    1
1330    1
1340    3
Name: FTR, dtype: object
1.5
11
11.1
Eibar - visitante
1142    1
1168    3
1173    1
1196    3
1216    0
1239    0
1259    1
1277    0
1299    3
1320    1
Name: FTR, dtype: object
1.3
Valencia - local
1140    3
1173    1
1194    0
1211    3
1235    3
1251    3
1272    3
1292    3
1317    0
1347    3
Name: FTR, dtype: object
2.2
17
15.1
Ath Madrid - visitante
1156    3
1176    3
1190    0
1213    1
1230    0
1254    0
1273    3
1298    3
1339    3
1354    0
Name: FTR, dtype: object
1.6
Ath Bilbao - local
1143    0
1170    3
1182    0
1208    0
1229    1
1244    3
1267    1
1274    3
1300    1
1320    1
Name: FTR, dtype: object
1.3
12
11.8
Leganes - visitante
1152    0
1179    0
1197    0
1217    0
1244    0
1266    0
1290    0
1303    1
1325    1
1331    0
Name: FTR, dtype: object
0.2
Vallecano - local
1900    3
1935    0
1950    3
1979    3
1995    1
2010    0
2030    1
2056    3
2076    3
2102    1
Name: FTR, dtype: object
1.8
20
15.1
Sevilla - visitante
1158    1
1181    0
1198    1
1215    0
1232    0
1263    3
1287    3
1307    0
1328    3
1335    0
Name: FTR, dtype: object
1.1
Real Madrid - local
1153    3
1179    3
1195    1
1213    1
1231    3
1257    3
1275    3
1297    3
1323    3
1336    0
Name: FTR, dtype: object
2.3
35
21.5
Getafe - visitante
1146    3
1164    3
1187    3
1194    3
1218    0
1236    3
1257    0
1271    0
1295    1
1312    1
Name: FTR, dtype: object
1.7
Eibar - local
1157    3
1187    0
1202    0
1224    1
1248    0
1265    3
1288    0
1307    3
1321    1
1339    0
Name: FTR, dtype: object
1.1
9
13.9
Huesca - visitante
Series([], Name: FTR, dtype: object)
0.0
Villarreal - local
1144    1
1167    3
1177    3
1197    3
1210    0
1230    3
1255    0
1271    3
1296    0
1316    3
Name: FTR, dtype: object
1.9
18
14.3
Sociedad - visitante
1141    0
1171    0
1183    0
1206    3
1224    1
1242    0
1261    1
1272    0
1297    0
1316    0
Name: FTR, dtype: object
0.5
Celta - local
1149    3
1169    1
1188    1
1199    1
1215    3
1233    1
1250    3
1277    3
1294    1
1311    3
Name: FTR, dtype: object
2.0
21
13.5
Espanol - visitante
1143    3
1166    3
1185    3
1201    0
1211    0
1238    0
1253    1
1279    1
1294    1
1313    0
Name: FTR, dtype: object
1.2
Barcelona - local
1141    3
1161    3
1165    1
1207    3
1217    3
1234    3
1254    3
1278    3
1295    1
1314    3
Name: FTR, dtype: object
2.6
24
14.4
Alaves - visitante
1145    0
1163    3
1184    3
1202    3
1223    1
1235    0
1252    0
1275    0
1296    3
1314    0
Name: FTR, dtype: object
1.3
Girona - local
1155    0
1168    0
1185    0
1209    0
1228    1
1249    3
1268    3
1290    3
1302    3
1338    3
Name: FTR, dtype: object
1.6
16
12.6
Valladolid - visitante
2675    0
2691    0
2719    1
2740    0
2762    0
2785    1
2808    0
2827    1
2840    0
2859    0
Name: FTR, dtype: object
0.3
Betis - local
1158    1
1172    3
1192    3
1216    3
1238    3
1261    1
1284    0
1308    3
1324    0
1331    3
Name: FTR, dtype: object
2.0
18
12.4
Levante - visitante
1149    0
1162    3
1182    3
1203    0
1228    1
1247    3
1262    0
1282    0
1292    0
1319    1
Name: FTR, dtype: object
1.1
Valencia - local
1173    1
1194    0
1211    3
1235    3
1251    3
1272    3
1292    3
1317    0
1347    3
1351    0
Name: FTR, dtype: object
1.9
15
15.1
La Coruna - visitante
1169    1
1189    1
1208    3
1225    0
1249    0
1264    0
1289    0
1310    0
1323    0
1342    1
Name: FTR, dtype: object
0.6
Barcelona - local
1161    3
1165    1
1207    3
1217    3
1234    3
1254    3
1278    3
1295    1
1314    3
1345    3
Name: FTR, dtype: object
2.6
26
14.8
Sociedad - visitante
1171    0
1183    0
1206    3
1224    1
1242    0
1261    1
1272    0
1297    0
1316    0
1343    0
Name: FTR, dtype: object
0.5
Ath Madrid - local
1166    0
1186    1
1203    3
1225    3
1243    3
1266    3
1285    3
1305    3
1315    3
1329    1
Name: FTR, dtype: object
2.3
18
12.4
Eibar - visitante
1168    3
1173    1
1196    3
1216    0
1239    0
1259    1
1277    0
1299    3
1320    1
1349    3
Name: FTR, dtype: object
1.5
Ath Bilbao - local
1170    3
1182    0
1208    0
1229    1
1244    3
1267    1
1274    3
1300    1
1320    1
1346    3
Name: FTR, dtype: object
1.6
14
12.0
Espanol - visitante
1166    3
1185    3
1201    0
1211    0
1238    0
1253    1
1279    1
1294    1
1313    0
1341    3
Name: FTR, dtype: object
1.2
Villarreal - local
1167    3
1177    3
1197    3
1210    0
1230    3
1255    0
1271    3
1296    0
1316    3
1326    3
Name: FTR, dtype: object
2.1
18
14.7
Real Madrid - visitante
1160    0
1165    1
1200    3
1227    3
1248    3
1269    0
1280    3
1284    3
1306    1
1317    3
Name: FTR, dtype: object
2.0
Sevilla - local
1160    3
1171    3
1204    1
1226    1
1245    0
1256    3
1273    0
1293    3
1312    1
1348    0
Name: FTR, dtype: object
1.5
17
16.0
Alaves - visitante
1163    3
1184    3
1202    3
1223    1
1235    0
1252    0
1275    0
1296    3
1314    0
1346    0
Name: FTR, dtype: object
1.3
Malaga - local
1163    0
1183    3
1200    0
1221    3
1246    0
1263    0
1286    0
1298    0
1318    1
1341    0
Name: FTR, dtype: object
0.7
5
10.6
Getafe - visitante
1164    3
1187    3
1194    3
1218    0
1236    3
1257    0
1271    0
1295    1
1312    1
1350    0
Name: FTR, dtype: object
1.4
Leganes - local
1162    0
1189    1
1205    3
1222    0
1232    3
1258    3
1276    1
1280    0
1299    0
1313    3
Name: FTR, dtype: object
1.4
9
10.6
Betis - visitante
1170    0
1186    1
1209    3
1220    3
1240    3
1251    0
1270    3
1291    3
1311    0
1348    3
Name: FTR, dtype: object
1.9
Las Palmas - local
1164    0
1184    0
1206    0
1227    0
1241    0
1260    1
1287    0
1301    3
1327    3
1349    0
Name: FTR, dtype: object
0.7
6
12.4
Girona - visitante
1175    1
1193    3
1212    0
1231    0
1255    3
1278    0
1293    0
1318    1
1329    1
1347    0
Name: FTR, dtype: object
0.9
Celta - local
1169    1
1188    1
1199    1
1215    3
1233    1
1250    3
1277    3
1294    1
1311    3
1344    1
Name: FTR, dtype: object
1.8
19
12.5
Levante - visitante
1162    3
1182    3
1203    0
1228    1
1247    3
1262    0
1282    0
1292    0
1319    1
1326    0
Name: FTR, dtype: object
1.1
Levante - local
1181    3
1191    3
1214    3
1239    3
1253    1
1270    0
1306    1
1333    0
1360    1
1373    0
Name: FTR, dtype: object
1.5
11
11.7
Barcelona - visitante
1174    3
1199    1
1226    1
1246    3
1260    1
1288    3
1304    1
1324    3
1332    3
1352    3
Name: FTR, dtype: object
2.2
Espanol - local
1180    1
1196    0
1223    1
1242    3
1269    3
1283    1
1304    1
1328    0
1334    1
1354    3
Name: FTR, dtype: object
1.4
8
12.1
Malaga - visitante
1172    0
1191    0
1219    0
1233    1
1258    0
1274    0
1301    0
1321    1
1340    0
1357    0
Name: FTR, dtype: object
0.2
Sociedad - local
1178    3
1190    3
1212    3
1236    0
1252    3
1282    3
1310    3
1322    0
1332    0
1358    3
Name: FTR, dtype: object
2.1
28
14.1
Leganes - visitante
1179    0
1197    0
1217    0
1244    0
1266    0
1290    0
1303    1
1325    1
1331    0
1360    1
Name: FTR, dtype: object
0.3
Real Madrid - local
1179    3
1195    1
1213    1
1231    3
1257    3
1275    3
1297    3
1323    3
1336    0
1352    0
Name: FTR, dtype: object
2.0
29
21.4
Celta - visitante
1177    0
1205    0
1229    1
1243    0
1268    0
1281    0
1309    0
1322    3
1333    3
1353    3
Name: FTR, dtype: object
1.0
La Coruna - local
1174    0
1198    1
1219    3
1237    1
1259    1
1279    1
1291    0
1319    1
1337    0
1353    0
Name: FTR, dtype: object
0.8
11
14.1
Villarreal - visitante
1161    0
1204    1
1221    0
1241    3
1265    0
1283    1
1308    0
1336    3
1351    3
1364    3
Name: FTR, dtype: object
1.4
Girona - local
1168    0
1185    0
1209    0
1228    1
1249    3
1268    3
1290    3
1302    3
1338    3
1363    3
Name: FTR, dtype: object
1.9
17
11.9
Valencia - visitante
1167    0
1188    1
1207    0
1222    3
1245    3
1267    1
1286    3
1305    0
1327    0
1337    3
Name: FTR, dtype: object
1.4
Getafe - local
1175    1
1201    3
1220    0
1247    0
1264    3
1281    3
1303    1
1330    1
1340    3
1359    3
Name: FTR, dtype: object
1.8
13
11.3
Ath Madrid - visitante
1176    3
1190    0
1213    1
1230    0
1254    0
1273    3
1298    3
1339    3
1354    0
1374    3
Name: FTR, dtype: object
1.6
Eibar - local
1187    0
1202    0
1224    1
1248    0
1265    3
1288    0
1307    3
1321    1
1339    0
1356    3
Name: FTR, dtype: object
1.1
12
14.5
Las Palmas - visitante
1180    1
1192    0
1214    0
1237    1
1250    0
1276    1
1300    1
1315    0
1338    0
1359    0
Name: FTR, dtype: object
0.4
Betis - local
1172    3
1192    3
1216    3
1238    3
1261    1
1284    0
1308    3
1324    0
1331    3
1355    0
Name: FTR, dtype: object
1.9
16
13.1
Sevilla - visitante
1181    0
1198    1
1215    0
1232    0
1263    3
1287    3
1307    0
1328    3
1335    0
1358    0
Name: FTR, dtype: object
1.0
Alaves - local
1176    0
1193    0
1218    3
1240    0
1262    3
1289    3
1309    3
1325    1
1335    3
1357    3
Name: FTR, dtype: object
1.9
12
11.2
Ath Bilbao - visitante
1178    0
1195    1
1210    3
1234    0
1256    0
1285    0
1302    0
1330    1
1334    1
1355    3
Name: FTR, dtype: object
0.9
Sevilla - local
1171    3
1204    1
1226    1
1245    0
1256    3
1273    0
1293    3
1312    1
1348    0
1369    1
Name: FTR, dtype: object
1.3
14
16.2
Real Madrid - visitante
1165    1
1200    3
1227    3
1248    3
1269    0
1280    3
1284    3
1306    1
1317    3
1344    1
Name: FTR, dtype: object
2.1
Barcelona - local
1165    1
1207    3
1217    3
1234    3
1254    3
1278    3
1295    1
1314    3
1345    3
1365    3
Name: FTR, dtype: object
2.6
25
15.9
Villarreal - visitante
1204    1
1221    0
1241    3
1265    0
1283    1
1308    0
1336    3
1351    3
1364    3
1381    0
Name: FTR, dtype: object
1.4
Leganes - local
1189    1
1205    3
1222    0
1232    3
1258    3
1276    1
1280    0
1299    0
1313    3
1343    3

Name: FTR, dtype: object
1.7
10
10.1
Levante - visitante
1182    3
1203    0
1228    1
1247    3
1262    0
1282    0
1292    0
1319    1
1326    0
1345    0
Name: FTR, dtype: object
0.8
Malaga - local
1183    3
1200    0
1221    3
1246    0
1263    0
1286    0
1298    0
1318    1
1341    0
1361    0
Name: FTR, dtype: object
0.7
5
10.8
Alaves - visitante
1184    3
1202    3
1223    1
1235    0
1252    0
1275    0
1296    3
1314    0
1346    0
1367    0
Name: FTR, dtype: object
1.0
Las Palmas - local
1184    0
1206    0
1227    0
1241    0
1260    1
1287    0
1301    3
1327    3
1349    0
1362    1
Name: FTR, dtype: object
0.8
8
11.7
Getafe - visitante
1187    3
1194    3
1218    0
1236    3
1257    0
1271    0
1295    1
1312    1
1350    0
1363    0
Name: FTR, dtype: object
1.1
Barcelona - local
1207    3
1217    3
1234    3
1254    3
1278    3
1295    1
1314    3
1345    3
1365    3
1386    1
Name: FTR, dtype: object
2.6
25
16.9
Real Madrid - visitante
1200    3
1227    3
1248    3
1269    0
1280    3
1284    3
1306    1
1317    3
1344    1
1388    1
Name: FTR, dtype: object
2.1
Ath Madrid - local
1186    1
1203    3
1225    3
1243    3
1266    3
1285    3
1305    3
1315    3
1329    1
1350    3
Name: FTR, dtype: object
2.6
20
12.4
Espanol - visitante
1185    3
1201    0
1211    0
1238    0
1253    1
1279    1
1294    1
1313    0
1341    3
1362    1
Name: FTR, dtype: object
1.0
Villarreal - local
1177    3
1197    3
1210    0
1230    3
1255    0
1271    3
1296    0
1316    3
1326    3
1342    1
Name: FTR, dtype: object
1.9
18
14.5
Valencia - visitante
1188    1
1207    0
1222    3
1245    3
1267    1
1286    3
1305    0
1327    0
1337    3
1366    0
Name: FTR, dtype: object
1.4
Girona - local
1185    0
1209    0
1228    1
1249    3
1268    3
1290    3
1302    3
1338    3
1363    3
1380    0
Name: FTR, dtype: object
1.9
18
11.4
Eibar - visitante
1173    1
1196    3
1216    0
1239    0
1259    1
1277    0
1299    3
1320    1
1349    3
1378    1
Name: FTR, dtype: object
1.3
Celta - local
1188    1
1199    1
1215    3
1233    1
1250    3
1277    3
1294    1
1311    3
1344    1
1364    0
Name: FTR, dtype: object
1.7
18
12.2
La Coruna - visitante
1189    1
1208    3
1225    0
1249    0
1264    0
1289    0
1310    0
1323    0
1342    1
1365    0
Name: FTR, dtype: object
0.5
Ath Bilbao - local
1182    0
1208    0
1229    1
1244    3
1267    1
1274    3
1300    1
1320    1
1346    3
1368    1
Name: FTR, dtype: object
1.4
12
11.3
Betis - visitante
1186    1
1209    3
1220    3
1240    3
1251    0
1270    3
1291    3
1311    0
1348    3
1361    3
Name: FTR, dtype: object
2.2
Sevilla - local
1204    1
1226    1
1245    0
1256    3
1273    0
1293    3
1312    1
1348    0
1369    1
1385    3
Name: FTR, dtype: object
1.3
15
15.6
Sociedad - visitante
1183    0
1206    3
1224    1
1242    0
1261    1
1272    0
1297    0
1316    0
1343    0
1368    1
Name: FTR, dtype: object
0.6
Betis - local
1192    3
1216    3
1238    3
1261    1
1284    0
1308    3
1324    0
1331    3
1355    0
1374    0
Name: FTR, dtype: object
1.6
14
12.8
Malaga - visitante
1191    0
1219    0
1233    1
1258    0
1274    0
1301    0
1321    1
1340    0
1357    0
1372    3
Name: FTR, dtype: object
0.5
Valencia - local
1194    0
1211    3
1235    3
1251    3
1272    3
1292    3
1317    0
1347    3
1351    0
1375    3
Name: FTR, dtype: object
2.1
17
14.8
Eibar - visitante
1196    3
1216    0
1239    0
1259    1
1277    0
1299    3
1320    1
1349    3
1378    1
1398    3
Name: FTR, dtype: object
1.5
La Coruna - local
1198    1
1219    3
1237    1
1259    1
1279    1
1291    0
1319    1
1337    0
1353    0
1377    3
Name: FTR, dtype: object
1.1
10
13.9
Barcelona - visitante
1199    1
1226    1
1246    3
1260    1
1288    3
1304    1
1324    3
1332    3
1352    3
1371    3
Name: FTR, dtype: object
2.2
Getafe - local
1201    3
1220    0
1247    0
1264    3
1281    3
1303    1
1330    1
1340    3
1359    3
1378    1
Name: FTR, dtype: object
1.8
12
10.9
Girona - visitante
1193    3
1212    0
1231    0
1255    3
1278    0
1293    0
1318    1
1329    1
1347    0
1356    0
Name: FTR, dtype: object
0.8
Alaves - local
1193    0
1218    3
1240    0
1262    3
1289    3
1309    3
1325    1
1335    3
1357    3
1379    3
Name: FTR, dtype: object
2.2
14
12.7
Ath Madrid - visitante
1190    0
1213    1
1230    0
1254    0
1273    3
1298    3
1339    3
1354    0
1374    3
1396    3
Name: FTR, dtype: object
1.6
Villarreal - local
1197    3
1210    0
1230    3
1255    0
1271    3
1296    0
1316    3
1326    3
1342    1
1371    0
Name: FTR, dtype: object
1.6
14
14.1
Celta - visitante
1205    0
1229    1
1243    0
1268    0
1281    0
1309    0
1322    3
1333    3
1353    3
1375    0
Name: FTR, dtype: object
1.0
Sociedad - local
1190    3
1212    3
1236    0
1252    3
1282    3
1310    3
1322    0
1332    0
1358    3
1372    0
Name: FTR, dtype: object
1.8
25
14.2
Ath Bilbao - visitante
1195    1
1210    3
1234    0
1256    0
1285    0
1302    0
1330    1
1334    1
1355    3
1373    3
Name: FTR, dtype: object
1.2
Real Madrid - local
1195    1
1213    1
1231    3
1257    3
1275    3
1297    3
1323    3
1336    0
1352    0
1376    3
Name: FTR, dtype: object
2.0
32
22.2
Leganes - visitante
1197    0
1217    0
1244    0
1266    0
1290    0
1303    1
1325    1
1331    0
1360    1
1377    0
Name: FTR, dtype: object
0.3
Espanol - local
1196    0
1223    1
1242    3
1269    3
1283    1
1304    1
1328    0
1334    1
1354    3
1370    0
Name: FTR, dtype: object
1.3
7
11.3
Las Palmas - visitante
1192    0
1214    0
1237    1
1250    0
1276    1
1300    1
1315    0
1338    0
1359    0
1379    0
Name: FTR, dtype: object
0.3
Levante - local
1191    3
1214    3
1239    3
1253    1
1270    0
1306    1
1333    0
1360    1
1373    0
1396    0
Name: FTR, dtype: object
1.2
9
11.9
Sevilla - visitante
1198    1
1215    0
1232    0
1263    3
1287    3
1307    0
1328    3
1335    0
1358    0
1376    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
1208    0
1229    1
1244    3
1267    1
1274    3
1300    1
1320    1
1346    3
1368    1
1388    1
Name: FTR, dtype: object
1.5
11
10.6
Levante - visitante
1203    0
1228    1
1247    3
1262    0
1282    0
1292    0
1319    1
1326    0
1345    0
1369    1
Name: FTR, dtype: object
0.6
Malaga - local
1200    0
1221    3
1246    0
1263    0
1286    0
1298    0
1318    1
1341    0
1361    0
1389    1
Name: FTR, dtype: object
0.5
3
12.2
Sociedad - visitante
1206    3
1224    1
1242    0
1261    1
1272    0
1297    0
1316    0
1343    0
1368    1
1387    0
Name: FTR, dtype: object
0.6
Las Palmas - local
1206    0
1227    0
1241    0
1260    1
1287    0
1301    3
1327    3
1349    0
1362    1
1382    3
Name: FTR, dtype: object
1.1
9
12.6
Alaves - visitante
1202    3
1223    1
1235    0
1252    0
1275    0
1296    3
1314    0
1346    0
1367    0
1380    3
Name: FTR, dtype: object
1.0
Girona - local
1209    0
1228    1
1249    3
1268    3
1290    3
1302    3
1338    3
1363    3
1380    0
1409    1
Name: FTR, dtype: object
2.0
19
10.8
Espanol - visitante
1201    0
1211    0
1238    0
1253    1
1279    1
1294    1
1313    0
1341    3
1362    1
1384    0
Name: FTR, dtype: object
0.7
Ath Madrid - local
1203    3
1225    3
1243    3
1266    3
1285    3
1305    3
1315    3
1329    1
1350    3
1367    3
Name: FTR, dtype: object
2.8
21
12.4
Betis - visitante
1209    3
1220    3
1240    3
1251    0
1270    3
1291    3
1311    0
1348    3
1361    3
1382    0
Name: FTR, dtype: object
2.1
Eibar - local
1202    0
1224    1
1248    0
1265    3
1288    0
1307    3
1321    1
1339    0
1356    3
1366    3
Name: FTR, dtype: object
1.4
14
14.8
Getafe - visitante
1194    3
1218    0
1236    3
1257    0
1271    0
1295    1
1312    1
1350    0
1363    0
1390    0
Name: FTR, dtype: object
0.8
Celta - local
1199    1
1215    3
1233    1
1250    3
1277    3
1294    1
1311    3
1344    1
1364    0
1399    3
Name: FTR, dtype: object
1.9
18
12.6
Valencia - visitante
1207    0
1222    3
1245    3
1267    1
1286    3
1305    0
1327    0
1337    3
1366    0
1383    0
Name: FTR, dtype: object
1.3
Leganes - local
1205    3
1222    0
1232    3
1258    3
1276    1
1280    0
1299    0
1313    3
1343    3
1381    3
Name: FTR, dtype: object
1.9
13
10.0
La Coruna - visitante
1208    3
1225    0
1249    0
1264    0
1289    0
1310    0
1323    0
1342    1
1365    0
1385    0
Name: FTR, dtype: object
0.4
Sociedad - local
1212    3
1236    0
1252    3
1282    3
1310    3
1322    0
1332    0
1358    3
1372    0
1393    1
Name: FTR, dtype: object
1.6
24
14.6
Ath Madrid - visitante
1213    1
1230    0
1254    0
1273    3
1298    3
1339    3
1354    0
1374    3
1396    3
1416    3
Name: FTR, dtype: object
1.9
Levante - local
1214    3
1239    3
1253    1
1270    0
1306    1
1333    0
1360    1
1373    0
1396    0
1413    0
Name: FTR, dtype: object
0.9
9
11.5
Malaga - visitante
1219    0
1233    1
1258    0
1274    0
1301    0
1321    1
1340    0
1357    0
1372    3
1395    0
Name: FTR, dtype: object
0.5
Betis - local
1216    3
1238    3
1261    1
1284    0
1308    3
1324    0
1331    3
1355    0
1374    0
1397    1
Name: FTR, dtype: object
1.4
15
12.3
Las Palmas - visitante
1214    0
1237    1
1250    0
1276    1
1300    1
1315    0
1338    0
1359    0
1379    0
1393    1
Name: FTR, dtype: object
0.4
Alaves - local
1218    3
1240    0
1262    3
1289    3
1309    3
1325    1
1335    3
1357    3
1379    3
1398    0
Name: FTR, dtype: object
2.2
14
12.2
Girona - visitante
1212    0
1231    0
1255    3
1278    0
1293    0
1318    1
1329    1
1347    0
1356    0
1370    3
Name: FTR, dtype: object
0.8
Valencia - local
1211    3
1235    3
1251    3
1272    3
1292    3
1317    0
1347    3
1351    0
1375    3
1392    1
Name: FTR, dtype: object
2.2
17
14.6
Getafe - visitante
1218    0
1236    3
1257    0
1271    0
1295    1
1312    1
1350    0
1363    0
1390    0
1419    1
Name: FTR, dtype: object
0.6
Real Madrid - local
1213    1
1231    3
1257    3
1275    3
1297    3
1323    3
1336    0
1352    0
1376    3
1395    3
Name: FTR, dtype: object
2.2
34
20.9
Ath Bilbao - visitante
1210    3
1234    0
1256    0
1285    0
1302    0
1330    1
1334    1
1355    3
1373    3
1394    1
Name: FTR, dtype: object
1.2
Espanol - local
1223    1
1242    3
1269    3
1283    1
1304    1
1328    0
1334    1
1354    3
1370    0
1390    3
Name: FTR, dtype: object
1.6
8
11.3
Eibar - visitante
1216    0
1239    0
1259    1
1277    0
1299    3
1320    1
1349    3
1378    1
1398    3
1411    0
Name: FTR, dtype: object
1.2
Villarreal - local
1210    0
1230    3
1255    0
1271    3
1296    0
1316    3
1326    3
1342    1
1371    0
1391    0
Name: FTR, dtype: object
1.3
14
14.3
Leganes - visitante
1217    0
1244    0
1266    0
1290    0
1303    1
1325    1
1331    0
1360    1
1377    0
1399    0
Name: FTR, dtype: object
0.3
La Coruna - local
1219    3
1237    1
1259    1
1279    1
1291    0
1319    1
1337    0
1353    0
1377    3
1394    1
Name: FTR, dtype: object
1.1
12
13.1
Sevilla - visitante
1215    0
1232    0
1263    3
1287    3
1307    0
1328    3
1335    0
1358    0
1376    0
1391    3
Name: FTR, dtype: object
1.2
Celta - local
1215    3
1233    1
1250    3
1277    3
1294    1
1311    3
1344    1
1364    0
1399    3
1414    3
Name: FTR, dtype: object
2.1
19
11.9
Barcelona - visitante
1226    1
1246    3
1260    1
1288    3
1304    1
1324    3
1332    3
1352    3
1371    3
1392    1
Name: FTR, dtype: object
2.2
Malaga - local
1221    3
1246    0
1263    0
1286    0
1298    0
1318    1
1341    0
1361    0
1389    1
1401    3
Name: FTR, dtype: object
0.8
5
12.3
Real Madrid - visitante
1227    3
1248    3
1269    0
1280    3
1284    3
1306    1
1317    3
1344    1
1388    1
1408    1
Name: FTR, dtype: object
1.9
Getafe - local
1220    0
1247    0
1264    3
1281    3
1303    1
1330    1
1340    3
1359    3
1378    1
1383    3
Name: FTR, dtype: object
1.8
12
10.7
Espanol - visitante
1211    0
1238    0
1253    1
1279    1
1294    1
1313    0
1341    3
1362    1
1384    0
1418    0
Name: FTR, dtype: object
0.7
Eibar - local
1224    1
1248    0
1265    3
1288    0
1307    3
1321    1
1339    0
1356    3
1366    3
1384    3
Name: FTR, dtype: object
1.7
17
13.7
Alaves - visitante
1223    1
1235    0
1252    0
1275    0
1296    3
1314    0
1346    0
1367    0
1380    3
1407    0
Name: FTR, dtype: object
0.7
Ath Madrid - local
1225    3
1243    3
1266    3
1285    3
1305    3
1315    3
1329    1
1350    3
1367    3
1387    3
Name: FTR, dtype: object
2.8
20
12.7
Levante - visitante
1228    1
1247    3
1262    0
1282    0
1292    0
1319    1
1326    0
1345    0
1369    1
1389    1
Name: FTR, dtype: object
0.7
Sevilla - local
1226    1
1245    0
1256    3
1273    0
1293    3
1312    1
1348    0
1369    1
1385    3
1405    3
Name: FTR, dtype: object
1.5
15
15.0
Villarreal - visitante
1221    0
1241    3
1265    0
1283    1
1308    0
1336    3
1351    3
1364    3
1381    0
1404    1
Name: FTR, dtype: object
1.4
Leganes - local
1222    0
1232    3
1258    3
1276    1
1280    0
1299    0
1313    3
1343    3
1381    3
1406    0
Name: FTR, dtype: object
1.6
12
9.9

Celta - visitante
1229    1
1243    0
1268    0
1281    0
1309    0
1322    3
1333    3
1353    3
1375    0
1386    1
Name: FTR, dtype: object
1.1
Las Palmas - local
1227    0
1241    0
1260    1
1287    0
1301    3
1327    3
1349    0
1362    1
1382    3
1402    0
Name: FTR, dtype: object
1.1
9
12.9
Sociedad - visitante
1224    1
1242    0
1261    1
1272    0
1297    0
1316    0
1343    0
1368    1
1387    0
1409    1
Name: FTR, dtype: object
0.4
Barcelona - local
1217    3
1234    3
1254    3
1278    3
1295    1
1314    3
1345    3
1365    3
1386    1
1417    3
Name: FTR, dtype: object
2.6
25
17.5
Valencia - visitante
1222    3
1245    3
1267    1
1286    3
1305    0
1327    0
1337    3
1366    0
1383    0
1403    3
Name: FTR, dtype: object
1.6
Ath Bilbao - local
1229    1
1244    3
1267    1
1274    3
1300    1
1320    1
1346    3
1368    1
1388    1
1404    1
Name: FTR, dtype: object
1.6
10
10.8
La Coruna - visitante
1225    0
1249    0
1264    0
1289    0
1310    0
1323    0
1342    1
1365    0
1385    0
1401    0
Name: FTR, dtype: object
0.1
Girona - local
1228    1
1249    3
1268    3
1290    3
1302    3
1338    3
1363    3
1380    0
1409    1
1423    3
Name: FTR, dtype: object
2.3
21
11.4
Betis - visitante
1220    3
1240    3
1251    0
1270    3
1291    3
1311    0
1348    3
1361    3
1382    0
1400    0
Name: FTR, dtype: object
1.8
Villarreal - local
1230    3
1255    0
1271    3
1296    0
1316    3
1326    3
1342    1
1371    0
1391    0
1410    3
Name: FTR, dtype: object
1.6
15
15.0
Ath Bilbao - visitante
1234    0
1256    0
1285    0
1302    0
1330    1
1334    1
1355    3
1373    3
1394    1
1414    0
Name: FTR, dtype: object
0.9
Valencia - local
1235    3
1251    3
1272    3
1292    3
1317    0
1347    3
1351    0
1375    3
1392    1
1415    3
Name: FTR, dtype: object
2.2
19
14.5
Espanol - visitante
1238    0
1253    1
1279    1
1294    1
1313    0
1341    3
1362    1
1384    0
1418    0
1430    1
Name: FTR, dtype: object
0.8
Sociedad - local
1236    0
1252    3
1282    3
1310    3
1322    0
1332    0
1358    3
1372    0
1393    1
1411    3
Name: FTR, dtype: object
1.6
22
14.3
Girona - visitante
1231    0
1255    3
1278    0
1293    0
1318    1
1329    1
1347    0
1356    0
1370    3
1397    1
Name: FTR, dtype: object
0.9
Real Madrid - local
1231    3
1257    3
1275    3
1297    3
1323    3
1336    0
1352    0
1376    3
1395    3
1412    3
Name: FTR, dtype: object
2.4
36
20.6
Ath Madrid - visitante
1230    0
1254    0
1273    3
1298    3
1339    3
1354    0
1374    3
1396    3
1416    3
1435    3
Name: FTR, dtype: object
2.1
Levante - local
1239    3
1253    1
1270    0
1306    1
1333    0
1360    1
1373    0
1396    0
1413    0
1437    1
Name: FTR, dtype: object
0.7
8
10.9
Las Palmas - visitante
1237    1
1250    0
1276    1
1300    1
1315    0
1338    0
1359    0
1379    0
1393    1
1412    0
Name: FTR, dtype: object
0.4
Celta - local
1233    1
1250    3
1277    3
1294    1
1311    3
1344    1
1364    0
1399    3
1414    3
1435    0
Name: FTR, dtype: object
1.8
15
12.6
Sevilla - visitante
1232    0
1263    3
1287    3
1307    0
1328    3
1335    0
1358    0
1376    0
1391    3
1417    0
Name: FTR, dtype: object
1.2
Betis - local
1238    3
1261    1
1284    0
1308    3
1324    0
1331    3
1355    0
1374    0
1397    1
1419    1
Name: FTR, dtype: object
1.2
15
12.5
Eibar - visitante
1239    0
1259    1
1277    0
1299    3
1320    1
1349    3
1378    1
1398    3
1411    0
1433    0
Name: FTR, dtype: object
1.2
Barcelona - local
1234    3
1254    3
1278    3
1295    1
1314    3
1345    3
1365    3
1386    1
1417    3
1439    3
Name: FTR, dtype: object
2.6
24
17.5
Leganes - visitante
1244    0
1266    0
1290    0
1303    1
1325    1
1331    0
1360    1
1377    0
1399    0
1415    0
Name: FTR, dtype: object
0.3
Alaves - local
1240    0
1262    3
1289    3
1309    3
1325    1
1335    3
1357    3
1379    3
1398    0
1418    3
Name: FTR, dtype: object
2.2
13
12.8
Getafe - visitante
1236    3
1257    0
1271    0
1295    1
1312    1
1350    0
1363    0
1390    0
1419    1
1437    1
Name: FTR, dtype: object
0.7
La Coruna - local
1237    1
1259    1
1279    1
1291    0
1319    1
1337    0
1353    0
1377    3
1394    1
1416    0
Name: FTR, dtype: object
0.8
9
13.1
Malaga - visitante
1233    1
1258    0
1274    0
1301    0
1321    1
1340    0
1357    0
1372    3
1395    0
1410    0
Name: FTR, dtype: object
0.5
Getafe - local
1247    0
1264    3
1281    3
1303    1
1330    1
1340    3
1359    3
1378    1
1383    3
1407    3
Name: FTR, dtype: object
2.1
16
11.2
Betis - visitante
1240    3
1251    0
1270    3
1291    3
1311    0
1348    3
1361    3
1382    0
1400    0
1421    0
Name: FTR, dtype: object
1.5
Malaga - local
1246    0
1263    0
1286    0
1298    0
1318    1
1341    0
1361    0
1389    1
1401    3
1422    3
Name: FTR, dtype: object
0.8
6
12.5
Villarreal - visitante
1241    3
1265    0
1283    1
1308    0
1336    3
1351    3
1364    3
1381    0
1404    1
1427    1
Name: FTR, dtype: object
1.5
Leganes - local
1232    3
1258    3
1276    1
1280    0
1299    0
1313    3
1343    3
1381    3
1406    0
1434    3
Name: FTR, dtype: object
1.9
13
10.6
Valencia - visitante
1245    3
1267    1
1286    3
1305    0
1327    0
1337    3
1366    0
1383    0
1403    3
1429    3
Name: FTR, dtype: object
1.6
Espanol - local
1242    3
1269    3
1283    1
1304    1
1328    0
1334    1
1354    3
1370    0
1390    3
1403    0
Name: FTR, dtype: object
1.5
8
11.3
Alaves - visitante
1235    0
1252    0
1275    0
1296    3
1314    0
1346    0
1367    0
1380    3
1407    0
1438    0
Name: FTR, dtype: object
0.6
Eibar - local
1248    0
1265    3
1288    0
1307    3
1321    1
1339    0
1356    3
1366    3
1384    3
1400    3
Name: FTR, dtype: object
1.9
22
13.9
Sociedad - visitante
1242    0
1261    1
1272    0
1297    0
1316    0
1343    0
1368    1
1387    0
1409    1
1424    0
Name: FTR, dtype: object
0.3
Ath Madrid - local
1243    3
1266    3
1285    3
1305    3
1315    3
1329    1
1350    3
1367    3
1387    3
1408    1
Name: FTR, dtype: object
2.6
19
11.9
La Coruna - visitante
1249    0
1264    0
1289    0
1310    0
1323    0
1342    1
1365    0
1385    0
1401    0
1420    3
Name: FTR, dtype: object
0.4
Sevilla - local
1245    0
1256    3
1273    0
1293    3
1312    1
1348    0
1369    1
1385    3
1405    3
1426    3
Name: FTR, dtype: object
1.7
15
13.8
Barcelona - visitante
1246    3
1260    1
1288    3
1304    1
1324    3
1332    3
1352    3
1371    3
1392    1
1406    3
Name: FTR, dtype: object
2.4
Las Palmas - local
1241    0
1260    1
1287    0
1301    3
1327    3
1349    0
1362    1
1382    3
1402    0
1420    0
Name: FTR, dtype: object
1.1
10
12.5
Real Madrid - visitante
1248    3
1269    0
1280    3
1284    3
1306    1
1317    3
1344    1
1388    1
1408    1
1423    0
Name: FTR, dtype: object
1.6
Girona - local
1249    3
1268    3
1290    3
1302    3
1338    3
1363    3
1380    0
1409    1
1423    3
1442    0
Name: FTR, dtype: object
2.2
21
11.6
Levante - visitante
1247    3
1262    0
1282    0
1292    0
1319    1
1326    0
1345    0
1369    1
1389    1
1402    3
Name: FTR, dtype: object
0.9
Ath Bilbao - local
1244    3
1267    1
1274    3
1300    1
1320    1
1346    3
1368    1
1388    1
1404    1
1428    0
Name: FTR, dtype: object
1.5
9
11.4
Celta - visitante
1243    0
1268    0
1281    0
1309    0
1322    3
1333    3
1353    3
1375    0
1386    1
1405    0
Name: FTR, dtype: object
1.0
Villarreal - local
1255    0
1271    3
1296    0
1316    3
1326    3
1342    1
1371    0
1391    0
1410    3
1432    3
Name: FTR, dtype: object
1.6
17
15.8
Ath Madrid - visitante
1254    0
1273    3
1298    3
1339    3
1354    0
1374    3
1396    3
1416    3
1435    3
1457    1
Name: FTR, dtype: object
2.2
Real Madrid - local
1257    3
1275    3
1297    3
1323    3
1336    0
1352    0
1376    3
1395    3
1412    3
1433    3
Name: FTR, dtype: object
2.4
33
20.1
Girona - visitante
1255    3
1278    0
1293    0
1318    1
1329    1
1347    0
1356    0
1370    3
1397    1
1413    3
Name: FTR, dtype: object
1.2
Leganes - local
1258    3
1276    1
1280    0
1299    0
1313    3
1343    3
1381    3
1406    0
1434    3
1457    1
Name: FTR, dtype: object
1.7
11
10.1
Sevilla - visitante
1263    3
1287    3
1307    0
1328    3
1335    0
1358    0
1376    0
1391    3
1417    0
1436    0
Name: FTR, dtype: object
1.2
Celta - local
1250    3
1277    3
1294    1
1311    3
1344    1
1364    0
1399    3
1414    3
1435    0
1459    1
Name: FTR, dtype: object
1.8
18
13.3
Malaga - visitante
1258    0
1274    0
1301    0
1321    1
1340    0
1357    0
1372    3
1395    0
1410    0
1439    0
Name: FTR, dtype: object
0.4
Barcelona - local
1254    3
1278    3
1295    1
1314    3
1345    3
1365    3
1386    1
1417    3
1439    3
1454    3
Name: FTR, dtype: object
2.6
25
17.9
Ath Bilbao - visitante
1256    0
1285    0
1302    0
1330    1
1334    1
1355    3
1373    3
1394    1
1414    0
1434    0
Name: FTR, dtype: object
0.9
Valencia - local
1251    3
1272    3
1292    3
1317    0
1347    3
1351    0
1375    3
1392    1
1415    3
1436    3
Name: FTR, dtype: object
2.2
20
13.9
Alaves - visitante
1252    0
1275    0
1296    3
1314    0
1346    0
1367    0
1380    3
1407    0
1438    0
1456    3
Name: FTR, dtype: object
0.9
Sociedad - local
1252    3
1282    3
1310    3
1322    0
1332    0
1358    3
1372    0
1393    1
1411    3
1430    1
Name: FTR, dtype: object
1.7
22
15.4
Getafe - visitante
1257    0
1271    0
1295    1
1312    1
1350    0
1363    0
1390    0
1419    1
1437    1
1458    0
Name: FTR, dtype: object
0.4
La Coruna - local
1259    1
1279    1
1291    0
1319    1
1337    0
1353    0
1377    3
1394    1
1416    0
1431    0
Name: FTR, dtype: object
0.7
9
13.3
Las Palmas - visitante
1250    0
1276    1
1300    1
1315    0
1338    0
1359    0
1379    0
1393    1
1412    0
1432    0
Name: FTR, dtype: object
0.3
Betis - local
1261    1
1284    0
1308    3
1324    0
1331    3
1355    0
1374    0
1397    1
1419    1
1438    3
Name: FTR, dtype: object
1.2
14
12.8
Espanol - visitante
1253    1
1279    1
1294    1
1313    0
1341    3
1362    1
1384    0
1418    0
1430    1
1453    0
Name: FTR, dtype: object
0.8
Levante - local
1253    1
1270    0
1306    1
1333    0
1360    1
1373    0
1396    0
1413    0
1437    1
1456    0
Name: FTR, dtype: object
0.4
6
11.6
Eibar - visitante
1259    1
1277    0
1299    3
1320    1
1349    3
1378    1
1398    3
1411    0
1433    0
1450    0
Name: FTR, dtype: object
1.2
Alaves - local
1262    3
1289    3
1309    3
1325    1
1335    3
1357    3
1379    3
1398    0
1418    3
1429    0
Name: FTR, dtype: object
2.2
13
13.5
Betis - visitante
1251    0
1270    3
1291    3
1311    0
1348    3
1361    3
1382    0
1400    0
1421    0
1452    1
Name: FTR, dtype: object
1.3
Las Palmas - local
1260    1
1287    0
1301    3
1327    3
1349    0
1362    1
1382    3
1402    0
1420    0
1440    0
Name: FTR, dtype: object
1.1
12
14.0
Villarreal - visitante
1265    0
1283    1
1308    0
1336    3
1351    3
1364    3
1381    0
1404    1
1427    1
1442    3
Name: FTR, dtype: object
1.5
Espanol - local
1269    3
1283    1
1304    1
1328    0
1334    1
1354    3
1370    0
1390    3
1403    0
1421    3
Name: FTR, dtype: object
1.5
7
10.5
Sociedad - visitante
1261    1
1272    0
1297    0
1316    0
1343    0
1368    1
1387    0
1409    1
1424    0
1448    3
Name: FTR, dtype: object
0.6
Ath Madrid - local
1266    3
1285    3
1305    3
1315    3
1329    1
1350    3
1367    3
1387    3
1408    1
1427    1
Name: FTR, dtype: object
2.4
17
13.0
Celta - visitante
1268    0
1281    0
1309    0
1322    3
1333    3
1353    3
1375    0
1386    1
1405    0
1422    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
1267    1
1274    3
1300    1
1320    1
1346    3
1368    1
1388    1
1404    1
1428    0
1447    3
Name: FTR, dtype: object
1.5
8
11.6
Leganes - visitante
1266    0
1290    0
1303    1
1325    1
1331    0
1360    1
1377    0
1399    0
1415    0
1426    0
Name: FTR, dtype: object
0.3
Sevilla - local
1256    3
1273    0
1293    3
1312    1
1348    0
1369    1
1385    3
1405    3
1426    3
1455    3
Name: FTR, dtype: object
2.0
17
12.9
Valencia - visitante
1267    1
1286    3
1305    0
1327    0
1337    3
1366    0
1383    0
1403    3
1429    3
1444    3
Name: FTR, dtype: object
1.6
Malaga - local
1263    0
1286    0
1298    0
1318    1
1341    0
1361    0
1389    1
1401    3
1422    3
1441    0
Name: FTR, dtype: object
0.8
6
13.2
Barcelona - visitante
1260    1
1288    3
1304    1
1324    3
1332    3
1352    3
1371    3
1392    1
1406    3
1428    3
Name: FTR, dtype: object
2.4
Getafe - local
1264    3
1281    3
1303    1
1330    1
1340    3
1359    3
1378    1
1383    3
1407    3
1424    3
Name: FTR, dtype: object
2.4
18
11.1
Levante - visitante
1262    0
1282    0
1292    0
1319    1
1326    0
1345    0
1369    1
1389    1
1402    3
1425    1
Name: FTR, dtype: object
0.7
Eibar - local
1265    3
1288    0
1307    3
1321    1
1339    0
1356    3
1366    3
1384    3
1400    3
1425    1
Name: FTR, dtype: object
2.0
23
14.3
Real Madrid - visitante
1269    0
1280    3
1284    3
1306    1
1317    3
1344    1
1388    1
1408    1
1423    0
1445    3
Name: FTR, dtype: object
1.6
Girona - local
1268    3
1290    3
1302    3
1338    3
1363    3
1380    0
1409    1
1423    3
1442    0
1467    0
Name: FTR, dtype: object
1.9
19
12.0
La Coruna - visitante
1264    0
1289    0
1310    0
1323    0
1342    1
1365    0
1385    0
1401    0
1420    3
1443    1

Name: FTR, dtype: object
0.5
Celta - local
1277    3
1294    1
1311    3
1344    1
1364    0
1399    3
1414    3
1435    0
1459    1
1472    1
Name: FTR, dtype: object
1.6
17
12.7
Las Palmas - visitante
1276    1
1300    1
1315    0
1338    0
1359    0
1379    0
1393    1
1412    0
1432    0
1454    0
Name: FTR, dtype: object
0.3
Valencia - local
1272    3
1292    3
1317    0
1347    3
1351    0
1375    3
1392    1
1415    3
1436    3
1451    3
Name: FTR, dtype: object
2.2
21
13.7
Betis - visitante
1270    3
1291    3
1311    0
1348    3
1361    3
1382    0
1400    0
1421    0
1452    1
1474    3
Name: FTR, dtype: object
1.6
Sociedad - local
1282    3
1310    3
1322    0
1332    0
1358    3
1372    0
1393    1
1411    3
1430    1
1452    1
Name: FTR, dtype: object
1.5
24
15.7
Alaves - visitante
1275    0
1296    3
1314    0
1346    0
1367    0
1380    3
1407    0
1438    0
1456    3
1476    0
Name: FTR, dtype: object
0.9
Levante - local
1270    0
1306    1
1333    0
1360    1
1373    0
1396    0
1413    0
1437    1
1456    0
1471    3
Name: FTR, dtype: object
0.6
8
11.6
Espanol - visitante
1279    1
1294    1
1313    0
1341    3
1362    1
1384    0
1418    0
1430    1
1453    0
1470    1
Name: FTR, dtype: object
0.8
Barcelona - local
1278    3
1295    1
1314    3
1345    3
1365    3
1386    1
1417    3
1439    3
1454    3
1479    3
Name: FTR, dtype: object
2.6
30
17.4
Ath Madrid - visitante
1273    3
1298    3
1339    3
1354    0
1374    3
1396    3
1416    3
1435    3
1457    1
1477    3
Name: FTR, dtype: object
2.5
Villarreal - local
1271    3
1296    0
1316    3
1326    3
1342    1
1371    0
1391    0
1410    3
1432    3
1450    3
Name: FTR, dtype: object
1.9
20
15.6
Girona - visitante
1278    0
1293    0
1318    1
1329    1
1347    0
1356    0
1370    3
1397    1
1413    3
1431    3
Name: FTR, dtype: object
1.2
Sevilla - local
1273    0
1293    3
1312    1
1348    0
1369    1
1385    3
1405    3
1426    3
1455    3
1473    3
Name: FTR, dtype: object
2.0
16
12.5
Ath Bilbao - visitante
1285    0
1302    0
1330    1
1334    1
1355    3
1373    3
1394    1
1414    0
1434    0
1451    0
Name: FTR, dtype: object
0.9
Real Madrid - local
1275    3
1297    3
1323    3
1336    0
1352    0
1376    3
1395    3
1412    3
1433    3
1453    3
Name: FTR, dtype: object
2.4
32
20.9
Getafe - visitante
1271    0
1295    1
1312    1
1350    0
1363    0
1390    0
1419    1
1437    1
1458    0
1472    1
Name: FTR, dtype: object
0.5
Leganes - local
1276    1
1280    0
1299    0
1313    3
1343    3
1381    3
1406    0
1434    3
1457    1
1475    1
Name: FTR, dtype: object
1.5
9
10.3
Malaga - visitante
1274    0
1301    0
1321    1
1340    0
1357    0
1372    3
1395    0
1410    0
1439    0
1455    0
Name: FTR, dtype: object
0.4
La Coruna - local
1279    1
1291    0
1319    1
1337    0
1353    0
1377    3
1394    1
1416    0
1431    0
1458    3
Name: FTR, dtype: object
0.9
10
14.1
Eibar - visitante
1277    0
1299    3
1320    1
1349    3
1378    1
1398    3
1411    0
1433    0
1450    0
1479    0
Name: FTR, dtype: object
1.1
Las Palmas - local
1287    0
1301    3
1327    3
1349    0
1362    1
1382    3
1402    0
1420    0
1440    0
1462    0
Name: FTR, dtype: object
1.0
11
13.6
Barcelona - visitante
1288    3
1304    1
1324    3
1332    3
1352    3
1371    3
1392    1
1406    3
1428    3
1446    1
Name: FTR, dtype: object
2.4
Betis - local
1284    0
1308    3
1324    0
1331    3
1355    0
1374    0
1397    1
1419    1
1438    3
1444    0
Name: FTR, dtype: object
1.1
17
13.3
Sociedad - visitante
1272    0
1297    0
1316    0
1343    0
1368    1
1387    0
1409    1
1424    0
1448    3
1471    0
Name: FTR, dtype: object
0.5
Alaves - local
1289    3
1309    3
1325    1
1335    3
1357    3
1379    3
1398    0
1418    3
1429    0
1448    0
Name: FTR, dtype: object
1.9
12
12.8
Levante - visitante
1282    0
1292    0
1319    1
1326    0
1345    0
1369    1
1389    1
1402    3
1425    1
1449    1
Name: FTR, dtype: object
0.8
Malaga - local
1286    0
1298    0
1318    1
1341    0
1361    0
1389    1
1401    3
1422    3
1441    0
1466    1
Name: FTR, dtype: object
0.9
9
13.9
Sevilla - visitante
1287    3
1307    0
1328    3
1335    0
1358    0
1376    0
1391    3
1417    0
1436    0
1447    0
Name: FTR, dtype: object
0.9
Getafe - local
1281    3
1303    1
1330    1
1340    3
1359    3
1378    1
1383    3
1407    3
1424    3
1445    0
Name: FTR, dtype: object
2.1
16
10.5
La Coruna - visitante
1289    0
1310    0
1323    0
1342    1
1365    0
1385    0
1401    0
1420    3
1443    1
1464    0
Name: FTR, dtype: object
0.5
Eibar - local
1288    0
1307    3
1321    1
1339    0
1356    3
1366    3
1384    3
1400    3
1425    1
1443    1
Name: FTR, dtype: object
1.8
22
14.5
Villarreal - visitante
1283    1
1308    0
1336    3
1351    3
1364    3
1381    0
1404    1
1427    1
1442    3
1463    0
Name: FTR, dtype: object
1.5
Ath Madrid - local
1285    3
1305    3
1315    3
1329    1
1350    3
1367    3
1387    3
1408    1
1427    1
1446    1
Name: FTR, dtype: object
2.2
14
12.0
Leganes - visitante
1290    0
1303    1
1325    1
1331    0
1360    1
1377    0
1399    0
1415    0
1426    0
1441    3
Name: FTR, dtype: object
0.6
Ath Bilbao - local
1274    3
1300    1
1320    1
1346    3
1368    1
1388    1
1404    1
1428    0
1447    3
1477    0
Name: FTR, dtype: object
1.4
8
11.7
Valencia - visitante
1286    3
1305    0
1327    0
1337    3
1366    0
1383    0
1403    3
1429    3
1444    3
1461    3
Name: FTR, dtype: object
1.8
Girona - local
1290    3
1302    3
1338    3
1363    3
1380    0
1409    1
1423    3
1442    0
1467    0
1483    0
Name: FTR, dtype: object
1.6
18
12.2
Celta - visitante
1281    0
1309    0
1322    3
1333    3
1353    3
1375    0
1386    1
1405    0
1422    0
1440    3
Name: FTR, dtype: object
1.3
Espanol - local
1283    1
1304    1
1328    0
1334    1
1354    3
1370    0
1390    3
1403    0
1421    3
1449    1
Name: FTR, dtype: object
1.3
6
10.9
Real Madrid - visitante
1280    3
1284    3
1306    1
1317    3
1344    1
1388    1
1408    1
1423    0
1445    3
1469    3
Name: FTR, dtype: object
1.9
Levante - local
1306    1
1333    0
1360    1
1373    0
1396    0
1413    0
1437    1
1456    0
1471    3
1485    1
Name: FTR, dtype: object
0.7
9
11.3
Betis - visitante
1291    3
1311    0
1348    3
1361    3
1382    0
1400    0
1421    0
1452    1
1474    3
1491    0
Name: FTR, dtype: object
1.3
Villarreal - local
1296    0
1316    3
1326    3
1342    1
1371    0
1391    0
1410    3
1432    3
1450    3
1470    1
Name: FTR, dtype: object
1.7
19
16.0
Getafe - visitante
1295    1
1312    1
1350    0
1363    0
1390    0
1419    1
1437    1
1458    0
1472    1
1499    3
Name: FTR, dtype: object
0.8
Valencia - local
1292    3
1317    0
1347    3
1351    0
1375    3
1392    1
1415    3
1436    3
1451    3
1478    3
Name: FTR, dtype: object
2.2
24
14.6
Sociedad - visitante
1297    0
1316    0
1343    0
1368    1
1387    0
1409    1
1424    0
1448    3
1471    0
1492    3
Name: FTR, dtype: object
0.8
Sevilla - local
1293    3
1312    1
1348    0
1369    1
1385    3
1405    3
1426    3
1455    3
1473    3
1496    3
Name: FTR, dtype: object
2.3
17
12.7
Ath Madrid - visitante
1298    3
1339    3
1354    0
1374    3
1396    3
1416    3
1435    3
1457    1
1477    3
1495    1
Name: FTR, dtype: object
2.3
Ath Bilbao - local
1300    1
1320    1
1346    3
1368    1
1388    1
1404    1
1428    0
1447    3
1477    0
1494    3
Name: FTR, dtype: object
1.4
8
11.6
Malaga - visitante
1301    0
1321    1
1340    0
1357    0
1372    3
1395    0
1410    0
1439    0
1455    0
1478    0
Name: FTR, dtype: object
0.4
Real Madrid - local
1297    3
1323    3
1336    0
1352    0
1376    3
1395    3
1412    3
1433    3
1453    3
1474    0
Name: FTR, dtype: object
2.1
28
21.1
Alaves - visitante
1296    3
1314    0
1346    0
1367    0
1380    3
1407    0
1438    0
1456    3
1476    0
1493    0
Name: FTR, dtype: object
0.9
Leganes - local
1280    0
1299    0
1313    3
1343    3
1381    3
1406    0
1434    3
1457    1
1475    1
1499    0
Name: FTR, dtype: object
1.4
10
10.3
Las Palmas - visitante
1300    1
1315    0
1338    0
1359    0
1379    0
1393    1
1412    0
1432    0
1454    0
1473    0
Name: FTR, dtype: object
0.2
Celta - local
1294    1
1311    3
1344    1
1364    0
1399    3
1414    3
1435    0
1459    1
1472    1
1493    3
Name: FTR, dtype: object
1.6
16
13.9
Eibar - visitante
1299    3
1320    1
1349    3
1378    1
1398    3
1411    0
1433    0
1450    0
1479    0
1496    0
Name: FTR, dtype: object
1.1
Barcelona - local
1295    1
1314    3
1345    3
1365    3
1386    1
1417    3
1439    3
1454    3
1479    3
1498    3
Name: FTR, dtype: object
2.6
29
17.3
Girona - visitante
1293    0
1318    1
1329    1
1347    0
1356    0
1370    3
1397    1
1413    3
1431    3
1459    1
Name: FTR, dtype: object
1.3
La Coruna - local
1291    0
1319    1
1337    0
1353    0
1377    3
1394    1
1416    0
1431    0
1458    3
1476    3
Name: FTR, dtype: object
1.1
11
13.9
Espanol - visitante
1294    1
1313    0
1341    3
1362    1
1384    0
1418    0
1430    1
1453    0
1470    1
1498    0
Name: FTR, dtype: object
0.7
Leganes - local
1299    0
1313    3
1343    3
1381    3
1406    0
1434    3
1457    1
1475    1
1499    0
1519    3
Name: FTR, dtype: object
1.7
10
11.2
Real Madrid - visitante
1284    3
1306    1
1317    3
1344    1
1388    1
1408    1
1423    0
1445    3
1469    3
1481    3
Name: FTR, dtype: object
1.9
Getafe - local
1303    1
1330    1
1340    3
1359    3
1378    1
1383    3
1407    3
1424    3
1445    0
1463    3
Name: FTR, dtype: object
2.1
17
11.3
Celta - visitante
1309    0
1322    3
1333    3
1353    3
1375    0
1386    1
1405    0
1422    0
1440    3
1465    3
Name: FTR, dtype: object
1.6
Sociedad - local
1310    3
1322    0
1332    0
1358    3
1372    0
1393    1
1411    3
1430    1
1452    1
1461    0
Name: FTR, dtype: object
1.2
23
16.2
Levante - visitante
1292    0
1319    1
1326    0
1345    0
1369    1
1389    1
1402    3
1425    1
1449    1
1460    0
Name: FTR, dtype: object
0.8
Espanol - local
1304    1
1328    0
1334    1
1354    3
1370    0
1390    3
1403    0
1421    3
1449    1
1464    3
Name: FTR, dtype: object
1.5
9
11.1
Villarreal - visitante
1308    0
1336    3
1351    3
1364    3
1381    0
1404    1
1427    1
1442    3
1463    0
1484    3
Name: FTR, dtype: object
1.7
Betis - local
1308    3
1324    0
1331    3
1355    0
1374    0
1397    1
1419    1
1438    3
1444    0
1460    3
Name: FTR, dtype: object
1.4
18
12.7
Real Madrid - visitante
1306    1
1317    3
1344    1
1388    1
1408    1
1423    0
1445    3
1469    3
1481    3
1512    3
Name: FTR, dtype: object
1.9
Ath Madrid - local
1305    3
1315    3
1329    1
1350    3
1367    3
1387    3
1408    1
1427    1
1446    1
1468    3
Name: FTR, dtype: object
2.2
14
11.9
Ath Bilbao - visitante
1302    0
1330    1
1334    1
1355    3
1373    3
1394    1
1414    0
1434    0
1451    0
1466    1
Name: FTR, dtype: object
1.0
Malaga - local
1298    0
1318    1
1341    0
1361    0
1389    1
1401    3
1422    3
1441    0
1466    1
1490    0
Name: FTR, dtype: object
0.9
9
14.4
Valencia - visitante
1305    0
1327    0
1337    3
1366    0
1383    0
1403    3
1429    3
1444    3
1461    3
1485    1
Name: FTR, dtype: object
1.6
Las Palmas - local
1301    3
1327    3
1349    0
1362    1
1382    3
1402    0
1420    0
1440    0
1462    0
1482    3
Name: FTR, dtype: object
1.3
11
13.7
Sevilla - visitante
1307    0
1328    3
1335    0
1358    0
1376    0
1391    3
1417    0
1436    0
1447    0
1468    0
Name: FTR, dtype: object
0.6
Eibar - local
1307    3
1321    1
1339    0
1356    3
1366    3
1384    3
1400    3
1425    1
1443    1
1465    0
Name: FTR, dtype: object
1.8
22
14.1
Barcelona - visitante
1304    1
1324    3
1332    3
1352    3
1371    3
1392    1
1406    3
1428    3
1446    1
1467    3
Name: FTR, dtype: object
2.4
Alaves - local
1309    3
1325    1
1335    3
1357    3
1379    3
1398    0
1418    3
1429    0
1448    0
1469    0
Name: FTR, dtype: object
1.6
12
12.2
La Coruna - visitante
1310    0
1323    0
1342    1
1365    0
1385    0
1401    0
1420    3
1443    1
1464    0
1487    0
Name: FTR, dtype: object
0.5
Girona - local
1302    3
1338    3
1363    3
1380    0
1409    1
1423    3
1442    0
1467    0
1483    0
1506    3
Name: FTR, dtype: object
1.6
16
12.7
Leganes - visitante
1303    1
1325    1
1331    0
1360    1
1377    0
1399    0
1415    0
1426    0
1441    3
1462    3
Name: FTR, dtype: object
0.9
La Coruna - local
1319    1
1337    0
1353    0
1377    3
1394    1
1416    0
1431    0
1458    3
1476    3
1492    0
Name: FTR, dtype: object
1.1
13
13.4
Betis - visitante
1311    0
1348    3
1361    3
1382    0
1400    0
1421    0
1452    1
1474    3
1491    0
1513    0
Name: FTR, dtype: object
1.0
Valencia - local
1317    0
1347    3
1351    0
1375    3
1392    1
1415    3
1436    3
1451    3
1478    3
1495    1
Name: FTR, dtype: object
2.0
21
13.9
Levante - visitante
1319    1
1326    0
1345    0
1369    1
1389    1
1402    3
1425    1
1449    1
1460    0
1497    1
Name: FTR, dtype: object
0.9
Sevilla - local
1312    1
1348    0
1369    1
1385    3
1405    3
1426    3
1455    3
1473    3
1496    3
1515    1
Name: FTR, dtype: object
2.1
17
12.3
Girona - visitante
1318    1
1329    1
1347    0
1356    0
1370    3
1397    1
1413    3
1431    3
1459    1
1475    1
Name: FTR, dtype: object
1.4
Celta - local
1311    3
1344    1
1364    0
1399    3
1414    3
1435    0
1459    1
1472    1
1493    3
1517    0
Name: FTR, dtype: object
1.5
16
13.7
Espanol - visitante
1313    0
1341    3
1362    1
1384    0
1418    0
1430    1
1453    0
1470    1
1498    0
1515    1

Name: FTR, dtype: object
0.7
Barcelona - local
1314    3
1345    3
1365    3
1386    1
1417    3
1439    3
1454    3
1479    3
1498    3
1513    3
Name: FTR, dtype: object
2.8
31
17.6
Getafe - visitante
1312    1
1350    0
1363    0
1390    0
1419    1
1437    1
1458    0
1472    1
1499    3
1514    1
Name: FTR, dtype: object
0.8
Villarreal - local
1316    3
1326    3
1342    1
1371    0
1391    0
1410    3
1432    3
1450    3
1470    1
1491    3
Name: FTR, dtype: object
2.0
21
14.7
Alaves - visitante
1314    0
1346    0
1367    0
1380    3
1407    0
1438    0
1456    3
1476    0
1493    0
1519    0
Name: FTR, dtype: object
0.6
Real Madrid - local
1323    3
1336    0
1352    0
1376    3
1395    3
1412    3
1433    3
1453    3
1474    0
1497    1
Name: FTR, dtype: object
1.9
24
21.1
Sociedad - visitante
1316    0
1343    0
1368    1
1387    0
1409    1
1424    0
1448    3
1471    0
1492    3
1517    3
Name: FTR, dtype: object
1.1
Malaga - local
1318    1
1341    0
1361    0
1389    1
1401    3
1422    3
1441    0
1466    1
1490    0
1510    0
Name: FTR, dtype: object
0.9
9
14.1
Ath Madrid - visitante
1339    3
1354    0
1374    3
1396    3
1416    3
1435    3
1457    1
1477    3
1495    1
1505    3
Name: FTR, dtype: object
2.3
Leganes - local
1313    3
1343    3
1381    3
1406    0
1434    3
1457    1
1475    1
1499    0
1519    3
1527    1
Name: FTR, dtype: object
1.8
11
12.5
Eibar - visitante
1320    1
1349    3
1378    1
1398    3
1411    0
1433    0
1450    0
1479    0
1496    0
1510    3
Name: FTR, dtype: object
1.1
Ath Bilbao - local
1320    1
1346    3
1368    1
1388    1
1404    1
1428    0
1447    3
1477    0
1494    3
1514    1
Name: FTR, dtype: object
1.4
8
11.7
Las Palmas - visitante
1315    0
1338    0
1359    0
1379    0
1393    1
1412    0
1432    0
1454    0
1473    0
1490    3
Name: FTR, dtype: object
0.4
Las Palmas - local
1327    3
1349    0
1362    1
1382    3
1402    0
1420    0
1440    0
1462    0
1482    3
1505    0
Name: FTR, dtype: object
1.0
11
13.6
Malaga - visitante
1321    1
1340    0
1357    0
1372    3
1395    0
1410    0
1439    0
1455    0
1478    0
1488    0
Name: FTR, dtype: object
0.4
Girona - local
1338    3
1363    3
1380    0
1409    1
1423    3
1442    0
1467    0
1483    0
1506    3
1516    1
Name: FTR, dtype: object
1.4
16
13.2
Ath Bilbao - visitante
1330    1
1334    1
1355    3
1373    3
1394    1
1414    0
1434    0
1451    0
1466    1
1482    0
Name: FTR, dtype: object
1.0
Getafe - local
1330    1
1340    3
1359    3
1378    1
1383    3
1407    3
1424    3
1445    0
1463    3
1486    0
Name: FTR, dtype: object
2.0
18
11.5
Leganes - visitante
1325    1
1331    0
1360    1
1377    0
1399    0
1415    0
1426    0
1441    3
1462    3
1489    0
Name: FTR, dtype: object
0.8
Espanol - local
1328    0
1334    1
1354    3
1370    0
1390    3
1403    0
1421    3
1449    1
1464    3
1480    3
Name: FTR, dtype: object
1.7
10
11.3
Barcelona - visitante
1324    3
1332    3
1352    3
1371    3
1392    1
1406    3
1428    3
1446    1
1467    3
1486    3
Name: FTR, dtype: object
2.6
Ath Madrid - local
1315    3
1329    1
1350    3
1367    3
1387    3
1408    1
1427    1
1446    1
1468    3
1488    3
Name: FTR, dtype: object
2.2
14
12.2
Valencia - visitante
1327    0
1337    3
1366    0
1383    0
1403    3
1429    3
1444    3
1461    3
1485    1
1500    1
Name: FTR, dtype: object
1.7
Levante - local
1333    0
1360    1
1373    0
1396    0
1413    0
1437    1
1456    0
1471    3
1485    1
1504    1
Name: FTR, dtype: object
0.7
9
12.5
Real Madrid - visitante
1317    3
1344    1
1388    1
1408    1
1423    0
1445    3
1469    3
1481    3
1512    3
1521    3
Name: FTR, dtype: object
2.1
Eibar - local
1321    1
1339    0
1356    3
1366    3
1384    3
1400    3
1425    1
1443    1
1465    0
1489    3
Name: FTR, dtype: object
1.8
18
13.4
Sevilla - visitante
1328    3
1335    0
1358    0
1376    0
1391    3
1417    0
1436    0
1447    0
1468    0
1483    3
Name: FTR, dtype: object
0.9
Betis - local
1324    0
1331    3
1355    0
1374    0
1397    1
1419    1
1438    3
1444    0
1460    3
1487    3
Name: FTR, dtype: object
1.4
18
13.1
Villarreal - visitante
1336    3
1351    3
1364    3
1381    0
1404    1
1427    1
1442    3
1463    0
1484    3
1508    0
Name: FTR, dtype: object
1.7
Alaves - local
1325    1
1335    3
1357    3
1379    3
1398    0
1418    3
1429    0
1448    0
1469    0
1484    0
Name: FTR, dtype: object
1.3
10
12.9
Celta - visitante
1322    3
1333    3
1353    3
1375    0
1386    1
1405    0
1422    0
1440    3
1465    3
1480    0
Name: FTR, dtype: object
1.6
Sociedad - local
1322    0
1332    0
1358    3
1372    0
1393    1
1411    3
1430    1
1452    1
1461    0
1481    0
Name: FTR, dtype: object
0.9
19
15.3
La Coruna - visitante
1323    0
1342    1
1365    0
1385    0
1401    0
1420    3
1443    1
1464    0
1487    0
1504    1
Name: FTR, dtype: object
0.6
Celta - local
1344    1
1364    0
1399    3
1414    3
1435    0
1459    1
1472    1
1493    3
1517    0
1522    1
Name: FTR, dtype: object
1.3
15
13.7
Betis - visitante
1348    3
1361    3
1382    0
1400    0
1421    0
1452    1
1474    3
1491    0
1513    0
1525    1
Name: FTR, dtype: object
1.1
Sevilla - local
1348    0
1369    1
1385    3
1405    3
1426    3
1455    3
1473    3
1496    3
1515    1
1526    3
Name: FTR, dtype: object
2.3
21
12.5
Getafe - visitante
1350    0
1363    0
1390    0
1419    1
1437    1
1458    0
1472    1
1499    3
1514    1
1904    0
Name: FTR, dtype: object
0.7
Leganes - local
1343    3
1381    3
1406    0
1434    3
1457    1
1475    1
1499    0
1519    3
1527    1
1541    3
Name: FTR, dtype: object
1.8
12
12.0
Espanol - visitante
1341    3
1362    1
1384    0
1418    0
1430    1
1453    0
1470    1
1498    0
1515    1
1529    3
Name: FTR, dtype: object
1.0
Barcelona - local
1345    3
1365    3
1386    1
1417    3
1439    3
1454    3
1479    3
1498    3
1513    3
1523    3
Name: FTR, dtype: object
2.8
33
17.6
Alaves - visitante
1346    0
1367    0
1380    3
1407    0
1438    0
1456    3
1476    0
1493    0
1519    0
1527    1
Name: FTR, dtype: object
0.7
Ath Madrid - local
1329    1
1350    3
1367    3
1387    3
1408    1
1427    1
1446    1
1468    3
1488    3
1524    3
Name: FTR, dtype: object
2.2
14
11.6
Las Palmas - visitante
1338    0
1359    0
1379    0
1393    1
1412    0
1432    0
1454    0
1473    0
1490    3
1518    0
Name: FTR, dtype: object
0.4
Villarreal - local
1326    3
1342    1
1371    0
1391    0
1410    3
1432    3
1450    3
1470    1
1491    3
1531    1
Name: FTR, dtype: object
1.8
17
15.7
Sociedad - visitante
1343    0
1368    1
1387    0
1409    1
1424    0
1448    3
1471    0
1492    3
1517    3
1522    1
Name: FTR, dtype: object
1.2
Valencia - local
1347    3
1351    0
1375    3
1392    1
1415    3
1436    3
1451    3
1478    3
1495    1
1518    3
Name: FTR, dtype: object
2.3
21
15.0
Real Madrid - visitante
1344    1
1388    1
1408    1
1423    0
1445    3
1469    3
1481    3
1512    3
1521    3
1530    3
Name: FTR, dtype: object
2.1
Malaga - local
1341    0
1361    0
1389    1
1401    3
1422    3
1441    0
1466    1
1490    0
1510    0
1521    0
Name: FTR, dtype: object
0.8
9
15.6
Girona - visitante
1329    1
1347    0
1356    0
1370    3
1397    1
1413    3
1431    3
1459    1
1475    1
1494    0
Name: FTR, dtype: object
1.3
La Coruna - local
1337    0
1353    0
1377    3
1394    1
1416    0
1431    0
1458    3
1476    3
1492    0
1512    0
Name: FTR, dtype: object
1.0
11
13.8
Levante - visitante
1326    0
1345    0
1369    1
1389    1
1402    3
1425    1
1449    1
1460    0
1497    1
1900    0
Name: FTR, dtype: object
0.8
Ath Bilbao - local
1346    3
1368    1
1388    1
1404    1
1428    0
1447    3
1477    0
1494    3
1514    1
1537    1
Name: FTR, dtype: object
1.4
8
12.5
Eibar - visitante
1349    3
1378    1
1398    3
1411    0
1433    0
1450    0
1479    0
1496    0
1510    3
1523    0
Name: FTR, dtype: object
1.0
Eibar - local
1339    0
1356    3
1366    3
1384    3
1400    3
1425    1
1443    1
1465    0
1489    3
1503    0
Name: FTR, dtype: object
1.7
17
13.3
Malaga - visitante
1340    0
1357    0
1372    3
1395    0
1410    0
1439    0
1455    0
1478    0
1488    0
1506    0
Name: FTR, dtype: object
0.3
Sociedad - local
1332    0
1358    3
1372    0
1393    1
1411    3
1430    1
1452    1
1461    0
1481    0
1508    3
Name: FTR, dtype: object
1.2
21
15.2
Celta - visitante
1333    3
1353    3
1375    0
1386    1
1405    0
1422    0
1440    3
1465    3
1480    0
1509    0
Name: FTR, dtype: object
1.3
Real Madrid - local
1336    0
1352    0
1376    3
1395    3
1412    3
1433    3
1453    3
1474    0
1497    1
1500    1
Name: FTR, dtype: object
1.7
19
20.9
La Coruna - visitante
1342    1
1365    0
1385    0
1401    0
1420    3
1443    1
1464    0
1487    0
1504    1
1531    1
Name: FTR, dtype: object
0.7
Betis - local
1331    3
1355    0
1374    0
1397    1
1419    1
1438    3
1444    0
1460    3
1487    3
1509    3
Name: FTR, dtype: object
1.7
20
13.4
Barcelona - visitante
1332    3
1352    3
1371    3
1392    1
1406    3
1428    3
1446    1
1467    3
1486    3
1507    3
Name: FTR, dtype: object
2.6
Alaves - local
1335    3
1357    3
1379    3
1398    0
1418    3
1429    0
1448    0
1469    0
1484    0
1507    0
Name: FTR, dtype: object
1.2
8
12.6
Leganes - visitante
1331    0
1360    1
1377    0
1399    0
1415    0
1426    0
1441    3
1462    3
1489    0
1502    3
Name: FTR, dtype: object
1.0
Villarreal - local
1342    1
1371    0
1391    0
1410    3
1432    3
1450    3
1470    1
1491    3
1531    1
1560    3
Name: FTR, dtype: object
1.8
18
15.7
Levante - visitante
1345    0
1369    1
1389    1
1402    3
1425    1
1449    1
1460    0
1497    1
1900    0
1920    0
Name: FTR, dtype: object
0.8
Las Palmas - local
1349    0
1362    1
1382    3
1402    0
1420    0
1440    0
1462    0
1482    3
1505    0
1534    0
Name: FTR, dtype: object
0.7
10
12.7
Valencia - visitante
1337    3
1366    0
1383    0
1403    3
1429    3
1444    3
1461    3
1485    1
1500    1
1540    3
Name: FTR, dtype: object
2.0
Espanol - local
1334    1
1354    3
1370    0
1390    3
1403    0
1421    3
1449    1
1464    3
1480    3
1502    0
Name: FTR, dtype: object
1.7
10
12.1
Sevilla - visitante
1335    0
1358    0
1376    0
1391    3
1417    0
1436    0
1447    0
1468    0
1483    3
1501    3
Name: FTR, dtype: object
0.9
Ath Madrid - local
1350    3
1367    3
1387    3
1408    1
1427    1
1446    1
1468    3
1488    3
1524    3
1549    3
Name: FTR, dtype: object
2.4
14
12.1
Girona - visitante
1347    0
1356    0
1370    3
1397    1
1413    3
1431    3
1459    1
1475    1
1494    0
Name: FTR, dtype: object
1.3333333333333333
Getafe - local
1340    3
1359    3
1378    1
1383    3
1407    3
1424    3
1445    0
1463    3
1486    0
1501    0
Name: FTR, dtype: object
1.9
16
11.3
Ath Bilbao - visitante
1334    1
1355    3
1373    3
1394    1
1414    0
1434    0
1451    0
1466    1
1482    0
1503    3
Name: FTR, dtype: object
1.2
Betis - local
1355    0
1374    0
1397    1
1419    1
1438    3
1444    0
1460    3
1487    3
1509    3
1536    1
Name: FTR, dtype: object
1.5
18
13.1
Leganes - visitante
1360    1
1377    0
1399    0
1415    0
1426    0
1441    3
1462    3
1489    0
1502    3
1537    1
Name: FTR, dtype: object
1.1
Sociedad - local
1358    3
1372    0
1393    1
1411    3
1430    1
1452    1
1461    0
1481    0
1508    3
1532    1
Name: FTR, dtype: object
1.3
21
15.2
Barcelona - visitante
1352    3
1371    3
1392    1
1406    3
1428    3
1446    1
1467    3
1486    3
1507    3
1534    3
Name: FTR, dtype: object
2.6
Levante - local
1360    1
1373    0
1396    0
1413    0
1437    1
1456    0
1471    3
1485    1
1504    1
1511    3
Name: FTR, dtype: object
1.0
10
12.4
Celta - visitante
1353    3
1375    0
1386    1
1405    0
1422    0
1440    3
1465    3
1480    0
1509    0
1538    0
Name: FTR, dtype: object
1.0
Espanol - local
1354    3
1370    0
1390    3
1403    0
1421    3
1449    1
1464    3
1480    3
1502    0
1540    0
Name: FTR, dtype: object
1.6
9
12.5
Ath Bilbao - visitante
1355    3
1373    3
1394    1
1414    0
1434    0
1451    0
1466    1
1482    0
1503    3
1524    0
Name: FTR, dtype: object
1.1
Alaves - local
1357    3
1379    3
1398    0
1418    3
1429    0
1448    0
1469    0
1484    0
1507    0
1538    3
Name: FTR, dtype: object
1.2
10
12.5
Sevilla - visitante
1358    0
1376    0
1391    3
1417    0
1436    0
1447    0
1468    0
1483    3
1501    3
1533    0
Name: FTR, dtype: object
0.9
Real Madrid - local
1352    0
1376    3
1395    3
1412    3
1433    3
1453    3
1474    0
1497    1
1500    1
1533    3
Name: FTR, dtype: object
2.0
23
19.5
Villarreal - visitante
1351    3
1364    3
1381    0
1404    1
1427    1
1442    3
1463    0
1484    3
1508    0
1511    0
Name: FTR, dtype: object
1.4
La Coruna - local
1353    0
1377    3
1394    1
1416    0
1431    0
1458    3
1476    3
1492    0
1512    0
1528    3
Name: FTR, dtype: object
1.3
13
13.5
Valencia - visitante
1366    0
1383    0
1403    3
1429    3
1444    3
1461    3
1485    1
1500    1
1540    3
1557    0
Name: FTR, dtype: object
1.7

Girona - local
1363    3
1380    0
1409    1
1423    3
1442    0
1467    0
1483    0
1506    3
1516    1
Name: FTR, dtype: object
1.2222222222222223
10
13.0
Las Palmas - visitante
1359    0
1379    0
1393    1
1412    0
1432    0
1454    0
1473    0
1490    3
1518    0
1528    0
Name: FTR, dtype: object
0.4
Eibar - local
1356    3
1366    3
1384    3
1400    3
1425    1
1443    1
1465    0
1489    3
1503    0
1535    0
Name: FTR, dtype: object
1.7
17
13.2
Ath Madrid - visitante
1354    0
1374    3
1396    3
1416    3
1435    3
1457    1
1477    3
1495    1
1505    3
1516    1
Name: FTR, dtype: object
2.1
Getafe - local
1359    3
1378    1
1383    3
1407    3
1424    3
1445    0
1463    3
1486    0
1501    0
1916    1
Name: FTR, dtype: object
1.7
16
12.5
Malaga - visitante
1357    0
1372    3
1395    0
1410    0
1439    0
1455    0
1478    0
1488    0
1506    0
1532    1
Name: FTR, dtype: object
0.4
Malaga - local
1361    0
1389    1
1401    3
1422    3
1441    0
1466    1
1490    0
1510    0
1521    0
1543    3
Name: FTR, dtype: object
1.1
12
15.3
Espanol - visitante
1362    1
1384    0
1418    0
1430    1
1453    0
1470    1
1498    0
1515    1
1529    3
1544    3
Name: FTR, dtype: object
1.0
Villarreal - local
1371    0
1391    0
1410    3
1432    3
1450    3
1470    1
1491    3
1531    1
1560    3
1576    3
Name: FTR, dtype: object
2.0
19
15.7
La Coruna - visitante
1365    0
1385    0
1401    0
1420    3
1443    1
1464    0
1487    0
1504    1
1531    1
1552    1
Name: FTR, dtype: object
0.7
Leganes - local
1381    3
1406    0
1434    3
1457    1
1475    1
1499    0
1519    3
1527    1
1541    3
1565    3
Name: FTR, dtype: object
1.8
14
12.8
Sociedad - visitante
1368    1
1387    0
1409    1
1424    0
1448    3
1471    0
1492    3
1517    3
1522    1
1550    1
Name: FTR, dtype: object
1.3
Celta - local
1364    0
1399    3
1414    3
1435    0
1459    1
1472    1
1493    3
1517    0
1522    1
1530    0
Name: FTR, dtype: object
1.2
14
14.4
Real Madrid - visitante
1388    1
1408    1
1423    0
1445    3
1469    3
1481    3
1512    3
1521    3
1530    3
1547    3
Name: FTR, dtype: object
2.3
Barcelona - local
1365    3
1386    1
1417    3
1439    3
1454    3
1479    3
1498    3
1513    3
1523    3
1548    3
Name: FTR, dtype: object
2.8
34
18.0
Levante - visitante
1369    1
1389    1
1402    3
1425    1
1449    1
1460    0
1497    1
1900    0
1920    0
1941    0
Name: FTR, dtype: object
0.8
Ath Bilbao - local
1368    1
1388    1
1404    1
1428    0
1447    3
1477    0
1494    3
1514    1
1537    1
1562    3
Name: FTR, dtype: object
1.4
8
12.9
Alaves - visitante
1367    0
1380    3
1407    0
1438    0
1456    3
1476    0
1493    0
1519    0
1527    1
1555    3
Name: FTR, dtype: object
1.0
Valencia - local
1351    0
1375    3
1392    1
1415    3
1436    3
1451    3
1478    3
1495    1
1518    3
1520    0
Name: FTR, dtype: object
2.0
20
14.9
Girona - visitante
1356    0
1370    3
1397    1
1413    3
1431    3
1459    1
1475    1
1494    0
Name: FTR, dtype: object
1.5
Sevilla - local
1369    1
1385    3
1405    3
1426    3
1455    3
1473    3
1496    3
1515    1
1526    3
1550    1
Name: FTR, dtype: object
2.4
19
12.2
Betis - visitante
1361    3
1382    0
1400    0
1421    0
1452    1
1474    3
1491    0
1513    0
1525    1
1541    0
Name: FTR, dtype: object
0.8
Las Palmas - local
1362    1
1382    3
1402    0
1420    0
1440    0
1462    0
1482    3
1505    0
1534    0
1558    0
Name: FTR, dtype: object
0.7
9
13.8
Eibar - visitante
1378    1
1398    3
1411    0
1433    0
1450    0
1479    0
1496    0
1510    3
1523    0
1549    0
Name: FTR, dtype: object
0.7
Ath Madrid - local
1367    3
1387    3
1408    1
1427    1
1446    1
1468    3
1488    3
1524    3
1549    3
1570    0
Name: FTR, dtype: object
2.1
12
13.5
Getafe - visitante
1363    0
1390    0
1419    1
1437    1
1458    0
1472    1
1499    3
1514    1
1904    0
1922    3
Name: FTR, dtype: object
1.0
Valencia - local
1375    3
1392    1
1415    3
1436    3
1451    3
1478    3
1495    1
1518    3
1520    0
1542    3
Name: FTR, dtype: object
2.3
24
14.6
Villarreal - visitante
1364    3
1381    0
1404    1
1427    1
1442    3
1463    0
1484    3
1508    0
1511    0
1520    3
Name: FTR, dtype: object
1.4
Real Madrid - local
1376    3
1395    3
1412    3
1433    3
1453    3
1474    0
1497    1
1500    1
1533    3
1557    3
Name: FTR, dtype: object
2.3
25
20.1
Barcelona - visitante
1371    3
1392    1
1406    3
1428    3
1446    1
1467    3
1486    3
1507    3
1534    3
1559    3
Name: FTR, dtype: object
2.6
La Coruna - local
1377    3
1394    1
1416    0
1431    0
1458    3
1476    3
1492    0
1512    0
1528    3
1544    0
Name: FTR, dtype: object
1.3
13
14.1
Celta - visitante
1375    0
1386    1
1405    0
1422    0
1440    3
1465    3
1480    0
1509    0
1538    0
1543    0
Name: FTR, dtype: object
0.7
Espanol - local
1370    0
1390    3
1403    0
1421    3
1449    1
1464    3
1480    3
1502    0
1540    0
1559    0
Name: FTR, dtype: object
1.3
8
12.4
Ath Madrid - visitante
1374    3
1396    3
1416    3
1435    3
1457    1
1477    3
1495    1
1505    3
1516    1
1536    1
Name: FTR, dtype: object
2.2
Betis - local
1374    0
1397    1
1419    1
1438    3
1444    0
1460    3
1487    3
1509    3
1536    1
1555    0
Name: FTR, dtype: object
1.5
19
12.6
Ath Bilbao - visitante
1373    3
1394    1
1414    0
1434    0
1451    0
1466    1
1482    0
1503    3
1524    0
1545    0
Name: FTR, dtype: object
0.8
Eibar - local
1366    3
1384    3
1400    3
1425    1
1443    1
1465    0
1489    3
1503    0
1535    0
1553    3
Name: FTR, dtype: object
1.7
15
12.5
Girona - visitante
1370    3
1397    1
1413    3
1431    3
1459    1
1475    1
1494    0
Name: FTR, dtype: object
1.7142857142857142
Alaves - local
1379    3
1398    0
1418    3
1429    0
1448    0
1469    0
1484    0
1507    0
1538    3
1545    3
Name: FTR, dtype: object
1.2
10
12.4
Malaga - visitante
1372    3
1395    0
1410    0
1439    0
1455    0
1478    0
1488    0
1506    0
1532    1
1569    3
Name: FTR, dtype: object
0.7
Sociedad - local
1372    0
1393    1
1411    3
1430    1
1452    1
1461    0
1481    0
1508    3
1532    1
1556    3
Name: FTR, dtype: object
1.3
20
15.1
Sevilla - visitante
1376    0
1391    3
1417    0
1436    0
1447    0
1468    0
1483    3
1501    3
1533    0
1551    0
Name: FTR, dtype: object
0.9
Getafe - local
1378    1
1383    3
1407    3
1424    3
1445    0
1463    3
1486    0
1501    0
1916    1
1934    1
Name: FTR, dtype: object
1.5
16
13.0
Las Palmas - visitante
1379    0
1393    1
1412    0
1432    0
1454    0
1473    0
1490    3
1518    0
1528    0
1546    0
Name: FTR, dtype: object
0.4
Levante - local
1373    0
1396    0
1413    0
1437    1
1456    0
1471    3
1485    1
1504    1
1511    3
1914    3
Name: FTR, dtype: object
1.2
12
12.6
Leganes - visitante
1377    0
1399    0
1415    0
1426    0
1441    3
1462    3
1489    0
1502    3
1537    1
1553    0
Name: FTR, dtype: object
1.0
Malaga - local
1389    1
1401    3
1422    3
1441    0
1466    1
1490    0
1510    0
1521    0
1543    3
1551    3
Name: FTR, dtype: object
1.4
16
14.6
Betis - visitante
1382    0
1400    0
1421    0
1452    1
1474    3
1491    0
1513    0
1525    1
1541    0
1562    0
Name: FTR, dtype: object
0.5
Las Palmas - local
1382    3
1402    0
1420    0
1440    0
1462    0
1482    3
1505    0
1534    0
1558    0
1574    1
Name: FTR, dtype: object
0.7
8
13.8
Espanol - visitante
1384    0
1418    0
1430    1
1453    0
1470    1
1498    0
1515    1
1529    3
1544    3
1568    1
Name: FTR, dtype: object
1.0
Girona - local
1380    0
1409    1
1423    3
1442    0
1467    0
1483    0
1506    3
1516    1
Name: FTR, dtype: object
1.0
9
13.5
Getafe - visitante
1390    0
1419    1
1437    1
1458    0
1472    1
1499    3
1514    1
1904    0
1922    3
1940    3
Name: FTR, dtype: object
1.3
Celta - local
1399    3
1414    3
1435    0
1459    1
1472    1
1493    3
1517    0
1522    1
1530    0
1554    0
Name: FTR, dtype: object
1.2
14
13.9
Villarreal - visitante
1381    0
1404    1
1427    1
1442    3
1463    0
1484    3
1508    0
1511    0
1520    3
1548    0
Name: FTR, dtype: object
1.1
Barcelona - local
1386    1
1417    3
1439    3
1454    3
1479    3
1498    3
1513    3
1523    3
1548    3
1567    3
Name: FTR, dtype: object
2.8
37
17.6
La Coruna - visitante
1385    0
1401    0
1420    3
1443    1
1464    0
1487    0
1504    1
1531    1
1552    1
1572    0
Name: FTR, dtype: object
0.7
Eibar - local
1384    3
1400    3
1425    1
1443    1
1465    0
1489    3
1503    0
1535    0
1553    3
1571    0
Name: FTR, dtype: object
1.4
13
11.7
Valencia - visitante
1383    0
1403    3
1429    3
1444    3
1461    3
1485    1
1500    1
1540    3
1557    0
1578    0
Name: FTR, dtype: object
1.7
Ath Madrid - local
1387    3
1408    1
1427    1
1446    1
1468    3
1488    3
1524    3
1549    3
1570    0
1589    3
Name: FTR, dtype: object
2.1
14
14.4
Alaves - visitante
1380    3
1407    0
1438    0
1456    3
1476    0
1493    0
1519    0
1527    1
1555    3
1574    1
Name: FTR, dtype: object
1.1
Ath Bilbao - local
1388    1
1404    1
1428    0
1447    3
1477    0
1494    3
1514    1
1537    1
1562    3
1590    3
Name: FTR, dtype: object
1.6
13
14.0
Sociedad - visitante
1387    0
1409    1
1424    0
1448    3
1471    0
1492    3
1517    3
1522    1
1550    1
1564    3
Name: FTR, dtype: object
1.5
Sevilla - local
1385    3
1405    3
1426    3
1455    3
1473    3
1496    3
1515    1
1526    3
1550    1
1561    3
Name: FTR, dtype: object
2.6
21
12.2
Levante - visitante
1389    1
1402    3
1425    1
1449    1
1460    0
1497    1
1900    0
1920    0
1941    0
1968    0
Name: FTR, dtype: object
0.7
Espanol - local
1390    3
1403    0
1421    3
1449    1
1464    3
1480    3
1502    0
1540    0
1559    0
1579    0
Name: FTR, dtype: object
1.3
8
12.6
Girona - visitante
1397    1
1413    3
1431    3
1459    1
1475    1
1494    0
Name: FTR, dtype: object
1.5
Villarreal - local
1391    0
1410    3
1432    3
1450    3
1470    1
1491    3
1531    1
1560    3
1576    3
1600    3
Name: FTR, dtype: object
2.3
22
15.8
Barcelona - visitante
1392    1
1406    3
1428    3
1446    1
1467    3
1486    3
1507    3
1534    3
1559    3
1573    3
Name: FTR, dtype: object
2.6
Sociedad - local
1393    1
1411    3
1430    1
1452    1
1461    0
1481    0
1508    3
1532    1
1556    3
1572    3
Name: FTR, dtype: object
1.6
21
15.0
Malaga - visitante
1395    0
1410    0
1439    0
1455    0
1478    0
1488    0
1506    0
1532    1
1569    3
1587    0
Name: FTR, dtype: object
0.4
Levante - local
1396    0
1413    0
1437    1
1456    0
1471    3
1485    1
1504    1
1511    3
1914    3
1933    1
Name: FTR, dtype: object
1.3
13
12.4
Ath Bilbao - visitante
1394    1
1414    0
1434    0
1451    0
1466    1
1482    0
1503    3
1524    0
1545    0
1554    3
Name: FTR, dtype: object
0.8
Betis - local
1397    1
1419    1
1438    3
1444    0
1460    3
1487    3
1509    3
1536    1
1555    0
1585    3
Name: FTR, dtype: object
1.8
21
12.3

Ath Madrid - visitante
1396    3
1416    3
1435    3
1457    1
1477    3
1495    1
1505    3
1516    1
1536    1
1558    3
Name: FTR, dtype: object
2.2
Valencia - local
1392    1
1415    3
1436    3
1451    3
1478    3
1495    1
1518    3
1520    0
1542    3
1564    0
Name: FTR, dtype: object
2.0
24
14.7
Celta - visitante
1386    1
1405    0
1422    0
1440    3
1465    3
1480    0
1509    0
1538    0
1543    0
1561    0
Name: FTR, dtype: object
0.7
Real Madrid - local
1395    3
1412    3
1433    3
1453    3
1474    0
1497    1
1500    1
1533    3
1557    3
1573    0
Name: FTR, dtype: object
2.0
22
20.3
Sevilla - visitante
1391    3
1417    0
1436    0
1447    0
1468    0
1483    3
1501    3
1533    0
1551    0
1582    1
Name: FTR, dtype: object
1.0
La Coruna - local
1394    1
1416    0
1431    0
1458    3
1476    3
1492    0
1512    0
1528    3
1544    0
1566    0
Name: FTR, dtype: object
1.0
14
14.5
Leganes - visitante
1399    0
1415    0
1426    0
1441    3
1462    3
1489    0
1502    3
1537    1
1553    0
1576    0
Name: FTR, dtype: object
1.0
Getafe - local
1383    3
1407    3
1424    3
1445    0
1463    3
1486    0
1501    0
1916    1
1934    1
1956    0
Name: FTR, dtype: object
1.4
17
13.6
Eibar - visitante
1398    3
1411    0
1433    0
1450    0
1479    0
1496    0
1510    3
1523    0
1549    0
1563    1
Name: FTR, dtype: object
0.7
Alaves - local
1398    0
1418    3
1429    0
1448    0
1469    0
1484    0
1507    0
1538    3
1545    3
1563    1
Name: FTR, dtype: object
1.0
8
11.6
Las Palmas - visitante
1393    1
1412    0
1432    0
1454    0
1473    0
1490    3
1518    0
1528    0
1546    0
1565    0
Name: FTR, dtype: object
0.4
Girona - local
1409    1
1423    3
1442    0
1467    0
1483    0
1506    3
1516    1
Name: FTR, dtype: object
1.1428571428571428
7
13.857142857142858
Alaves - visitante
1407    0
1438    0
1456    3
1476    0
1493    0
1519    0
1527    1
1555    3
1574    1
1599    0
Name: FTR, dtype: object
0.8
Leganes - local
1406    0
1434    3
1457    1
1475    1
1499    0
1519    3
1527    1
1541    3
1565    3
1583    0
Name: FTR, dtype: object
1.5
11
13.1
Villarreal - visitante
1404    1
1427    1
1442    3
1463    0
1484    3
1508    0
1511    0
1520    3
1548    0
1570    3
Name: FTR, dtype: object
1.4
Las Palmas - local
1402    0
1420    0
1440    0
1462    0
1482    3
1505    0
1534    0
1558    0
1574    1
1593    3
Name: FTR, dtype: object
0.7
11
12.6
Betis - visitante
1400    0
1421    0
1452    1
1474    3
1491    0
1513    0
1525    1
1541    0
1562    0
1575    3
Name: FTR, dtype: object
0.8
Getafe - local
1407    3
1424    3
1445    0
1463    3
1486    0
1501    0
1916    1
1934    1
1956    0
1989    1
Name: FTR, dtype: object
1.2
17
13.3
Valencia - visitante
1403    3
1429    3
1444    3
1461    3
1485    1
1500    1
1540    3
1557    0
1578    0
1594    3
Name: FTR, dtype: object
2.0
Eibar - local
1400    3
1425    1
1443    1
1465    0
1489    3
1503    0
1535    0
1553    3
1571    0
1602    3
Name: FTR, dtype: object
1.4
13
11.8
Espanol - visitante
1418    0
1430    1
1453    0
1470    1
1498    0
1515    1
1529    3
1544    3
1568    1
1583    3
Name: FTR, dtype: object
1.3
Sevilla - local
1405    3
1426    3
1455    3
1473    3
1496    3
1515    1
1526    3
1550    1
1561    3
1580    3
Name: FTR, dtype: object
2.6
21
14.0
La Coruna - visitante
1401    0
1420    3
1443    1
1464    0
1487    0
1504    1
1531    1
1552    1
1572    0
1596    0
Name: FTR, dtype: object
0.7
Barcelona - local
1417    3
1439    3
1454    3
1479    3
1498    3
1513    3
1523    3
1548    3
1567    3
1588    3
Name: FTR, dtype: object
3.0
38
17.1
Celta - visitante
1405    0
1422    0
1440    3
1465    3
1480    0
1509    0
1538    0
1543    0
1561    0
1584    3
Name: FTR, dtype: object
0.9
Ath Madrid - local
1408    1
1427    1
1446    1
1468    3
1488    3
1524    3
1549    3
1570    0
1589    3
1609    3
Name: FTR, dtype: object
2.1
13
14.8
Sociedad - visitante
1409    1
1424    0
1448    3
1471    0
1492    3
1517    3
1522    1
1550    1
1564    3
1588    0
Name: FTR, dtype: object
1.5
Ath Bilbao - local
1404    1
1428    0
1447    3
1477    0
1494    3
1514    1
1537    1
1562    3
1590    3
1610    3
Name: FTR, dtype: object
1.8
15
14.2
Real Madrid - visitante
1408    1
1423    0
1445    3
1469    3
1481    3
1512    3
1521    3
1530    3
1547    3
1566    3
Name: FTR, dtype: object
2.5
Malaga - local
1401    3
1422    3
1441    0
1466    1
1490    0
1510    0
1521    0
1543    3
1551    3
1578    3
Name: FTR, dtype: object
1.6
18
13.8
Levante - visitante
1402    3
1425    1
1449    1
1460    0
1497    1
1900    0
1920    0
1941    0
1968    0
1986    0
Name: FTR, dtype: object
0.6
Espanol - local
1403    0
1421    3
1449    1
1464    3
1480    3
1502    0
1540    0
1559    0
1579    0
1599    3
Name: FTR, dtype: object
1.3
8
13.1
Getafe - visitante
1419    1
1437    1
1458    0
1472    1
1499    3
1514    1
1904    0
1922    3
1940    3
1961    0
Name: FTR, dtype: object
1.3
Villarreal - local
1410    3
1432    3
1450    3
1470    1
1491    3
1531    1
1560    3
1576    3
1600    3
1616    0
Name: FTR, dtype: object
2.3
22
15.4
Sevilla - visitante
1417    0
1436    0
1447    0
1468    0
1483    3
1501    3
1533    0
1551    0
1582    1
1606    0
Name: FTR, dtype: object
0.7
Valencia - local
1415    3
1436    3
1451    3
1478    3
1495    1
1518    3
1520    0
1542    3
1564    0
1582    1
Name: FTR, dtype: object
2.0
23
15.3
Barcelona - visitante
1406    3
1428    3
1446    1
1467    3
1486    3
1507    3
1534    3
1559    3
1573    3
1598    0
Name: FTR, dtype: object
2.5
Sociedad - local
1411    3
1430    1
1452    1
1461    0
1481    0
1508    3
1532    1
1556    3
1572    3
1591    3
Name: FTR, dtype: object
1.8
22
15.4
Las Palmas - visitante
1412    0
1432    0
1454    0
1473    0
1490    3
1518    0
1528    0
1546    0
1565    0
1590    0
Name: FTR, dtype: object
0.3
La Coruna - local
1416    0
1431    0
1458    3
1476    3
1492    0
1512    0
1528    3
1544    0
1566    0
1587    3
Name: FTR, dtype: object
1.2
14
14.2
Ath Bilbao - visitante
1414    0
1434    0
1451    0
1466    1
1482    0
1503    3
1524    0
1545    0
1554    3
1571    3
Name: FTR, dtype: object
1.0
Real Madrid - local
1412    3
1433    3
1453    3
1474    0
1497    1
1500    1
1533    3
1557    3
1573    0
1597    1
Name: FTR, dtype: object
1.8
20
20.7
Malaga - visitante
1410    0
1439    0
1455    0
1478    0
1488    0
1506    0
1532    1
1569    3
1587    0
1603    3
Name: FTR, dtype: object
0.7
Levante - local
1413    0
1437    1
1456    0
1471    3
1485    1
1504    1
1511    3
1914    3
1933    1
1959    3
Name: FTR, dtype: object
1.6
15
11.9
Ath Madrid - visitante
1416    3
1435    3
1457    1
1477    3
1495    1
1505    3
1516    1
1536    1
1558    3
1579    3
Name: FTR, dtype: object
2.2
Betis - local
1419    1
1438    3
1444    0
1460    3
1487    3
1509    3
1536    1
1555    0
1585    3
1608    0
Name: FTR, dtype: object
1.7
19
12.6
Girona - visitante
1413    3
1431    3
1459    1
1475    1
1494    0
Name: FTR, dtype: object
1.6
Alaves - local
1418    3
1429    0
1448    0
1469    0
1484    0
1507    0
1538    3
1545    3
1563    1
1581    3
Name: FTR, dtype: object
1.3
9
12.1
Eibar - visitante
1411    0
1433    0
1450    0
1479    0
1496    0
1510    3
1523    0
1549    0
1563    1
1585    0
Name: FTR, dtype: object
0.4
Celta - local
1414    3
1435    0
1459    1
1472    1
1493    3
1517    0
1522    1
1530    0
1554    0
1575    0
Name: FTR, dtype: object
0.9
13
13.3
Leganes - visitante
1415    0
1426    0
1441    3
1462    3
1489    0
1502    3
1537    1
1553    0
1576    0
1592    0
Name: FTR, dtype: object
1.0
Eibar - local
1425    1
1443    1
1465    0
1489    3
1503    0
1535    0
1553    3
1571    0
1602    3
1626    1
Name: FTR, dtype: object
1.2
9
11.7
Betis - visitante
1421    0
1452    1
1474    3
1491    0
1513    0
1525    1
1541    0
1562    0
1575    3
1593    0
Name: FTR, dtype: object
0.8
Malaga - local
1422    3
1441    0
1466    1
1490    0
1510    0
1521    0
1543    3
1551    3
1578    3
1598    3
Name: FTR, dtype: object
1.6
17
13.2
La Coruna - visitante
1420    3
1443    1
1464    0
1487    0
1504    1
1531    1
1552    1
1572    0
1596    0
1612    0
Name: FTR, dtype: object
0.7
Las Palmas - local
1420    0
1440    0
1462    0
1482    3
1505    0
1534    0
1558    0
1574    1
1593    3
1630    3
Name: FTR, dtype: object
1.0
12
13.5
Levante - visitante
1425    1
1449    1
1460    0
1497    1
1900    0
1920    0
1941    0
1968    0
1986    0
2003    1
Name: FTR, dtype: object
0.4
Espanol - local
1421    3
1449    1
1464    3
1480    3
1502    0
1540    0
1559    0
1579    0
1599    3
1620    3
Name: FTR, dtype: object
1.6
10
12.7
Valencia - visitante
1429    3
1444    3
1461    3
1485    1
1500    1
1540    3
1557    0
1578    0
1594    3
1624    0
Name: FTR, dtype: object
1.7
Ath Bilbao - local
1428    0
1447    3
1477    0
1494    3
1514    1
1537    1
1562    3
1590    3
1610    3
1628    0
Name: FTR, dtype: object
1.7
15
13.9
Villarreal - visitante
1427    1
1442    3
1463    0
1484    3
1508    0
1511    0
1520    3
1548    0
1570    3
1581    0
Name: FTR, dtype: object
1.3
Sevilla - local
1426    3
1455    3
1473    3
1496    3
1515    1
1526    3
1550    1
1561    3
1580    3
1596    3
Name: FTR, dtype: object
2.6
23
14.7
Celta - visitante
1422    0
1440    3
1465    3
1480    0
1509    0
1538    0
1543    0
1561    0
1584    3
1601    0
Name: FTR, dtype: object
0.9
Leganes - local
1434    3
1457    1
1475    1
1499    0
1519    3
1527    1
1541    3
1565    3
1583    0
1604    0
Name: FTR, dtype: object
1.5
13
12.7
Barcelona - visitante
1428    3
1446    1
1467    3
1486    3
1507    3
1534    3
1559    3
1573    3
1598    0
1615    3
Name: FTR, dtype: object
2.5
Getafe - local
1424    3
1445    0
1463    3
1486    0
1501    0
1916    1
1934    1
1956    0
1989    1
2009    1
Name: FTR, dtype: object
1.0
14
13.3
Alaves - visitante
1438    0
1456    3
1476    0
1493    0
1519    0
1527    1
1555    3
1574    1
1599    0
1614    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
1427    1
1446    1
1468    3
1488    3
1524    3
1549    3
1570    0
1589    3
1609    3
1625    3
Name: FTR, dtype: object
2.3
16
15.6
Real Madrid - visitante
1423    0
1445    3
1469    3
1481    3
1512    3
1521    3
1530    3
1547    3
1566    3
1586    3
Name: FTR, dtype: object
2.7
Girona - local
1423    3
1442    0
1467    0
1483    0
1506    3
1516    1
Name: FTR, dtype: object
1.1666666666666667
6
13.833333333333334
Sociedad - visitante
1424    0
1448    3
1471    0
1492    3
1517    3
1522    1
1550    1
1564    3
1588    0
1609    0
Name: FTR, dtype: object
1.4
Villarreal - local
1432    3
1450    3
1470    1
1491    3
1531    1
1560    3
1576    3
1600    3
1616    0
1647    3

Name: FTR, dtype: object
2.3
22
15.1
Malaga - visitante
1439    0
1455    0
1478    0
1488    0
1506    0
1532    1
1569    3
1587    0
1603    3
1622    1
Name: FTR, dtype: object
0.8
Sociedad - local
1430    1
1452    1
1461    0
1481    0
1508    3
1532    1
1556    3
1572    3
1591    3
1617    1
Name: FTR, dtype: object
1.6
20
15.8
Eibar - visitante
1433    0
1450    0
1479    0
1496    0
1510    3
1523    0
1549    0
1563    1
1585    0
1595    3
Name: FTR, dtype: object
0.7
Real Madrid - local
1433    3
1453    3
1474    0
1497    1
1500    1
1533    3
1557    3
1573    0
1597    1
1614    3
Name: FTR, dtype: object
1.8
20
19.8
Las Palmas - visitante
1432    0
1454    0
1473    0
1490    3
1518    0
1528    0
1546    0
1565    0
1590    0
1602    0
Name: FTR, dtype: object
0.3
Levante - local
1437    1
1456    0
1471    3
1485    1
1504    1
1511    3
1914    3
1933    1
1959    3
1970    1
Name: FTR, dtype: object
1.7
14
12.8
Girona - visitante
1431    3
1459    1
1475    1
1494    0
Name: FTR, dtype: object
1.25
Celta - local
1435    0
1459    1
1472    1
1493    3
1517    0
1522    1
1530    0
1554    0
1575    0
1595    0
Name: FTR, dtype: object
0.6
10
13.4
Ath Bilbao - visitante
1434    0
1451    0
1466    1
1482    0
1503    3
1524    0
1545    0
1554    3
1571    3
1600    0
Name: FTR, dtype: object
1.0
Valencia - local
1436    3
1451    3
1478    3
1495    1
1518    3
1520    0
1542    3
1564    0
1582    1
1601    3
Name: FTR, dtype: object
2.0
23
15.5
Leganes - visitante
1426    0
1441    3
1462    3
1489    0
1502    3
1537    1
1553    0
1576    0
1592    0
1617    1
Name: FTR, dtype: object
1.1
La Coruna - local
1431    0
1458    3
1476    3
1492    0
1512    0
1528    3
1544    0
1566    0
1587    3
1605    1
Name: FTR, dtype: object
1.3
14
14.0
Ath Madrid - visitante
1435    3
1457    1
1477    3
1495    1
1505    3
1516    1
1536    1
1558    3
1579    3
1597    1
Name: FTR, dtype: object
2.0
Barcelona - local
1439    3
1454    3
1479    3
1498    3
1513    3
1523    3
1548    3
1567    3
1588    3
1606    3
Name: FTR, dtype: object
3.0
39
16.8
Sevilla - visitante
1436    0
1447    0
1468    0
1483    3
1501    3
1533    0
1551    0
1582    1
1606    0
1625    0
Name: FTR, dtype: object
0.7
Alaves - local
1429    0
1448    0
1469    0
1484    0
1507    0
1538    3
1545    3
1563    1
1581    3
1607    0
Name: FTR, dtype: object
1.0
8
11.9
Espanol - visitante
1430    1
1453    0
1470    1
1498    0
1515    1
1529    3
1544    3
1568    1
1583    3
1610    0
Name: FTR, dtype: object
1.3
Betis - local
1438    3
1444    0
1460    3
1487    3
1509    3
1536    1
1555    0
1585    3
1608    0
1627    3
Name: FTR, dtype: object
1.9
19
12.0
Getafe - visitante
1437    1
1458    0
1472    1
1499    3
1514    1
1904    0
1922    3
1940    3
1961    0
1979    0
Name: FTR, dtype: object
1.2
Las Palmas - local
1440    0
1462    0
1482    3
1505    0
1534    0
1558    0
1574    1
1593    3
1630    3
1644    3
Name: FTR, dtype: object
1.3
16
13.8
La Coruna - visitante
1443    1
1464    0
1487    0
1504    1
1531    1
1552    1
1572    0
1596    0
1612    0
1643    3
Name: FTR, dtype: object
0.7
Espanol - local
1449    1
1464    3
1480    3
1502    0
1540    0
1559    0
1579    0
1599    3
1620    3
1640    3
Name: FTR, dtype: object
1.6
13
12.9
Betis - visitante
1452    1
1474    3
1491    0
1513    0
1525    1
1541    0
1562    0
1575    3
1593    0
1620    0
Name: FTR, dtype: object
0.8
Malaga - local
1441    0
1466    1
1490    0
1510    0
1521    0
1543    3
1551    3
1578    3
1598    3
1619    0
Name: FTR, dtype: object
1.3
15
13.8
Celta - visitante
1440    3
1465    3
1480    0
1509    0
1538    0
1543    0
1561    0
1584    3
1601    0
1623    3
Name: FTR, dtype: object
1.2
Girona - local
1442    0
1467    0
1483    0
1506    3
1516    1
Name: FTR, dtype: object
0.8
4
13.6
Real Madrid - visitante
1445    3
1469    3
1481    3
1512    3
1521    3
1530    3
1547    3
1566    3
1586    3
1604    3
Name: FTR, dtype: object
3.0
Getafe - local
1445    0
1463    3
1486    0
1501    0
1916    1
1934    1
1956    0
1989    1
2009    1
2027    0
Name: FTR, dtype: object
0.7
12
13.7
Sociedad - visitante
1448    3
1471    0
1492    3
1517    3
1522    1
1550    1
1564    3
1588    0
1609    0
1629    0
Name: FTR, dtype: object
1.4
Eibar - local
1443    1
1465    0
1489    3
1503    0
1535    0
1553    3
1571    0
1602    3
1626    1
1649    0
Name: FTR, dtype: object
1.1
8
11.3
Levante - visitante
1449    1
1460    0
1497    1
1900    0
1920    0
1941    0
1968    0
1986    0
2003    1
2020    0
Name: FTR, dtype: object
0.3
Sevilla - local
1455    3
1473    3
1496    3
1515    1
1526    3
1550    1
1561    3
1580    3
1596    3
1613    1
Name: FTR, dtype: object
2.4
21
15.6
Leganes - visitante
1441    3
1462    3
1489    0
1502    3
1537    1
1553    0
1576    0
1592    0
1617    1
1637    1
Name: FTR, dtype: object
1.2
Ath Madrid - local
1446    1
1468    3
1488    3
1524    3
1549    3
1570    0
1589    3
1609    3
1625    3
1645    3
Name: FTR, dtype: object
2.5
18
15.6
Villarreal - visitante
1442    3
1463    0
1484    3
1508    0
1511    0
1520    3
1548    0
1570    3
1581    0
1608    3
Name: FTR, dtype: object
1.5
Ath Bilbao - local
1447    3
1477    0
1494    3
1514    1
1537    1
1562    3
1590    3
1610    3
1628    0
1646    3
Name: FTR, dtype: object
2.0
16
13.7
Barcelona - visitante
1446    1
1467    3
1486    3
1507    3
1534    3
1559    3
1573    3
1598    0
1615    3
1634    0
Name: FTR, dtype: object
2.2
Alaves - local
1448    0
1469    0
1484    0
1507    0
1538    3
1545    3
1563    1
1581    3
1607    0
1629    3
Name: FTR, dtype: object
1.3
8
11.3
Valencia - visitante
1444    3
1461    3
1485    1
1500    1
1540    3
1557    0
1578    0
1594    3
1624    0
1645    0
Name: FTR, dtype: object
1.4
Sociedad - local
1452    1
1461    0
1481    0
1508    3
1532    1
1556    3
1572    3
1591    3
1617    1
1632    0
Name: FTR, dtype: object
1.5
19
15.5
Espanol - visitante
1453    0
1470    1
1498    0
1515    1
1529    3
1544    3
1568    1
1583    3
1610    0
1626    1
Name: FTR, dtype: object
1.3
La Coruna - local
1458    3
1476    3
1492    0
1512    0
1528    3
1544    0
1566    0
1587    3
1605    1
1623    0
Name: FTR, dtype: object
1.3
13
13.4
Girona - visitante
1459    1
1475    1
1494    0
Name: FTR, dtype: object
0.6666666666666666
Villarreal - local
1450    3
1470    1
1491    3
1531    1
1560    3
1576    3
1600    3
1616    0
1647    3
1662    0
Name: FTR, dtype: object
2.0
20
13.7
Las Palmas - visitante
1454    0
1473    0
1490    3
1518    0
1528    0
1546    0
1565    0
1590    0
1602    0
1611    0
Name: FTR, dtype: object
0.3
Real Madrid - local
1453    3
1474    0
1497    1
1500    1
1533    3
1557    3
1573    0
1597    1
1614    3
1633    3
Name: FTR, dtype: object
1.8
19
19.7
Eibar - visitante
1450    0
1479    0
1496    0
1510    3
1523    0
1549    0
1563    1
1585    0
1595    3
1616    3
Name: FTR, dtype: object
1.0
Leganes - local
1457    1
1475    1
1499    0
1519    3
1527    1
1541    3
1565    3
1583    0
1604    0
1622    1
Name: FTR, dtype: object
1.3
12
12.6
Ath Bilbao - visitante
1451    0
1466    1
1482    0
1503    3
1524    0
1545    0
1554    3
1571    3
1600    0
1618    3
Name: FTR, dtype: object
1.3
Celta - local
1459    1
1472    1
1493    3
1517    0
1522    1
1530    0
1554    0
1575    0
1595    0
1611    3
Name: FTR, dtype: object
0.9
13
12.8
Ath Madrid - visitante
1457    1
1477    3
1495    1
1505    3
1516    1
1536    1
1558    3
1579    3
1597    1
1619    3
Name: FTR, dtype: object
2.0
Valencia - local
1451    3
1478    3
1495    1
1518    3
1520    0
1542    3
1564    0
1582    1
1601    3
1612    3
Name: FTR, dtype: object
2.0
22
15.1
Sevilla - visitante
1447    0
1468    0
1483    3
1501    3
1533    0
1551    0
1582    1
1606    0
1625    0
1642    1
Name: FTR, dtype: object
0.8
Levante - local
1456    0
1471    3
1485    1
1504    1
1511    3
1914    3
1933    1
1959    3
1970    1
1992    3
Name: FTR, dtype: object
1.9
14
13.6
Getafe - visitante
1458    0
1472    1
1499    3
1514    1
1904    0
1922    3
1940    3
1961    0
1979    0
1997    0
Name: FTR, dtype: object
1.1
Betis - local
1444    0
1460    3
1487    3
1509    3
1536    1
1555    0
1585    3
1608    0
1627    3
1651    0
Name: FTR, dtype: object
1.6
19
12.0
Alaves - visitante
1456    3
1476    0
1493    0
1519    0
1527    1
1555    3
1574    1
1599    0
1614    0
1638    3
Name: FTR, dtype: object
1.1
Barcelona - local
1454    3
1479    3
1498    3
1513    3
1523    3
1548    3
1567    3
1588    3
1606    3
1624    3
Name: FTR, dtype: object
3.0
41
18.4
Malaga - visitante
1455    0
1478    0
1488    0
1506    0
1532    1
1569    3
1587    0
1603    3
1622    1
1646    0
Name: FTR, dtype: object
0.8
Las Palmas - local
1462    0
1482    3
1505    0
1534    0
1558    0
1574    1
1593    3
1630    3
1644    3
1671    0
Name: FTR, dtype: object
1.3
14
13.2
Celta - visitante
1465    3
1480    0
1509    0
1538    0
1543    0
1561    0
1584    3
1601    0
1623    3
1650    0
Name: FTR, dtype: object
0.9
Malaga - local
1466    1
1490    0
1510    0
1521    0
1543    3
1551    3
1578    3
1598    3
1619    0
1638    0
Name: FTR, dtype: object
1.3
16
14.0
Leganes - visitante
1462    3
1489    0
1502    3
1537    1
1553    0
1576    0
1592    0
1617    1
1637    1
1659    0
Name: FTR, dtype: object
0.9
Girona - local
1467    0
1483    0
1506    3
1516    1
Name: FTR, dtype: object
1.0
3
13.5
Villarreal - visitante
1463    0
1484    3
1508    0
1511    0
1520    3
1548    0
1570    3
1581    0
1608    3
1630    0
Name: FTR, dtype: object
1.2
Eibar - local
1465    0
1489    3
1503    0
1535    0
1553    3
1571    0
1602    3
1626    1
1649    0
1668    3
Name: FTR, dtype: object
1.3
11
10.6
La Coruna - visitante
1464    0
1487    0
1504    1
1531    1
1552    1
1572    0
1596    0
1612    0
1643    3
1667    0
Name: FTR, dtype: object
0.6
Betis - local
1460    3
1487    3
1509    3
1536    1
1555    0
1585    3
1608    0
1627    3
1651    0
1669    0

Name: FTR, dtype: object
1.6
17
12.2
Valencia - visitante
1461    3
1485    1
1500    1
1540    3
1557    0
1578    0
1594    3
1624    0
1645    0
1670    0
Name: FTR, dtype: object
1.1
Getafe - local
1463    3
1486    0
1501    0
1916    1
1934    1
1956    0
1989    1
2009    1
2027    0
2043    0
Name: FTR, dtype: object
0.7
11
14.0
Real Madrid - visitante
1469    3
1481    3
1512    3
1521    3
1530    3
1547    3
1566    3
1586    3
1604    3
1628    3
Name: FTR, dtype: object
3.0
Ath Madrid - local
1468    3
1488    3
1524    3
1549    3
1570    0
1589    3
1609    3
1625    3
1645    3
1665    0
Name: FTR, dtype: object
2.4
18
16.3
Barcelona - visitante
1467    3
1486    3
1507    3
1534    3
1559    3
1573    3
1598    0
1615    3
1634    0
1665    3
Name: FTR, dtype: object
2.4
Ath Bilbao - local
1477    0
1494    3
1514    1
1537    1
1562    3
1590    3
1610    3
1628    0
1646    3
1666    3
Name: FTR, dtype: object
2.0
18
13.6
Sevilla - visitante
1468    0
1483    3
1501    3
1533    0
1551    0
1582    1
1606    0
1625    0
1642    1
1669    3
Name: FTR, dtype: object
1.1
Alaves - local
1469    0
1484    0
1507    0
1538    3
1545    3
1563    1
1581    3
1607    0
1629    3
1642    1
Name: FTR, dtype: object
1.4
9
12.3
Sociedad - visitante
1471    0
1492    3
1517    3
1522    1
1550    1
1564    3
1588    0
1609    0
1629    0
1651    3
Name: FTR, dtype: object
1.4
Espanol - local
1464    3
1480    3
1502    0
1540    0
1559    0
1579    0
1599    3
1620    3
1640    3
1664    3
Name: FTR, dtype: object
1.8
16
12.7
Levante - visitante
1460    0
1497    1
1900    0
1920    0
1941    0
1968    0
1986    0
2003    1
2020    0
2044    0
Name: FTR, dtype: object
0.2
Villarreal - local
1470    1
1491    3
1531    1
1560    3
1576    3
1600    3
1616    0
1647    3
1662    0
1684    1
Name: FTR, dtype: object
1.8
18
13.7
Eibar - visitante
1479    0
1496    0
1510    3
1523    0
1549    0
1563    1
1585    0
1595    3
1616    3
1631    1
Name: FTR, dtype: object
1.1
Valencia - local
1478    3
1495    1
1518    3
1520    0
1542    3
1564    0
1582    1
1601    3
1612    3
1636    1
Name: FTR, dtype: object
1.8
20
16.1
Ath Bilbao - visitante
1466    1
1482    0
1503    3
1524    0
1545    0
1554    3
1571    3
1600    0
1618    3
1632    3
Name: FTR, dtype: object
1.6
Sociedad - local
1461    0
1481    0
1508    3
1532    1
1556    3
1572    3
1591    3
1617    1
1632    0
1660    1
Name: FTR, dtype: object
1.5
17
15.2
Betis - visitante
1474    3
1491    0
1513    0
1525    1
1541    0
1562    0
1575    3
1593    0
1620    0
1633    0
Name: FTR, dtype: object
0.7
Real Madrid - local
1474    0
1497    1
1500    1
1533    3
1557    3
1573    0
1597    1
1614    3
1633    3
1654    1
Name: FTR, dtype: object
1.6
20
19.5
Espanol - visitante
1470    1
1498    0
1515    1
1529    3
1544    3
1568    1
1583    3
1610    0
1626    1
1647    0
Name: FTR, dtype: object
1.3
Barcelona - local
1479    3
1498    3
1513    3
1523    3
1548    3
1567    3
1588    3
1606    3
1624    3
1650    3
Name: FTR, dtype: object
3.0
43
18.1
Las Palmas - visitante
1473    0
1490    3
1518    0
1528    0
1546    0
1565    0
1590    0
1602    0
1611    0
1640    0
Name: FTR, dtype: object
0.3
Sevilla - local
1473    3
1496    3
1515    1
1526    3
1550    1
1561    3
1580    3
1596    3
1613    1
1637    1
Name: FTR, dtype: object
2.2
20
15.6
Malaga - visitante
1478    0
1488    0
1506    0
1532    1
1569    3
1587    0
1603    3
1622    1
1646    0
1668    0
Name: FTR, dtype: object
0.8
Levante - local
1471    3
1485    1
1504    1
1511    3
1914    3
1933    1
1959    3
1970    1
1992    3
2015    0
Name: FTR, dtype: object
1.9
15
13.4
Alaves - visitante
1476    0
1493    0
1519    0
1527    1
1555    3
1574    1
1599    0
1614    0
1638    3
1656    0
Name: FTR, dtype: object
0.8
Leganes - local
1475    1
1499    0
1519    3
1527    1
1541    3
1565    3
1583    0
1604    0
1622    1
1648    3
Name: FTR, dtype: object
1.5
13
13.5
Ath Madrid - visitante
1477    3
1495    1
1505    3
1516    1
1536    1
1558    3
1579    3
1597    1
1619    3
1639    3
Name: FTR, dtype: object
2.2
La Coruna - local
1476    3
1492    0
1512    0
1528    3
1544    0
1566    0
1587    3
1605    1
1623    0
1634    3
Name: FTR, dtype: object
1.3
13
13.3
Getafe - visitante
1472    1
1499    3
1514    1
1904    0
1922    3
1940    3
1961    0
1979    0
1997    0
2018    0
Name: FTR, dtype: object
1.1
Celta - local
1472    1
1493    3
1517    0
1522    1
1530    0
1554    0
1575    0
1595    0
1611    3
1635    0
Name: FTR, dtype: object
0.8
10
12.4
Girona - visitante
1475    1
1494    0
Name: FTR, dtype: object
0.5
Betis - local
1487    3
1509    3
1536    1
1555    0
1585    3
1608    0
1627    3
1651    0
1669    0
1689    1
Name: FTR, dtype: object
1.4
13
12.4
Levante - visitante
1497    1
1900    0
1920    0
1941    0
1968    0
1986    0
2003    1
2020    0
2044    0
2063    0
Name: FTR, dtype: object
0.2
Sociedad - local
1481    0
1508    3
1532    1
1556    3
1572    3
1591    3
1617    1
1632    0
1660    1
1675    0
Name: FTR, dtype: object
1.5
15
15.0
Valencia - visitante
1485    1
1500    1
1540    3
1557    0
1578    0
1594    3
1624    0
1645    0
1670    0
1689    1
Name: FTR, dtype: object
0.9
Las Palmas - local
1482    3
1505    0
1534    0
1558    0
1574    1
1593    3
1630    3
1644    3
1671    0
1686    0
Name: FTR, dtype: object
1.3
14
13.9
Leganes - visitante
1489    0
1502    3
1537    1
1553    0
1576    0
1592    0
1617    1
1637    1
1659    0
1677    0
Name: FTR, dtype: object
0.6
Getafe - local
1486    0
1501    0
1916    1
1934    1
1956    0
1989    1
2009    1
2027    0
2043    0
2068    0
Name: FTR, dtype: object
0.4
7
13.4
Villarreal - visitante
1484    3
1508    0
1511    0
1520    3
1548    0
1570    3
1581    0
1608    3
1630    0
1635    3
Name: FTR, dtype: object
1.5
Espanol - local
1480    3
1502    0
1540    0
1559    0
1579    0
1599    3
1620    3
1640    3
1664    3
1692    0
Name: FTR, dtype: object
1.5
13
11.7
La Coruna - visitante
1487    0
1504    1
1531    1
1552    1
1572    0
1596    0
1612    0
1643    3
1667    0
1690    0
Name: FTR, dtype: object
0.6
Eibar - local
1489    3
1503    0
1535    0
1553    3
1571    0
1602    3
1626    1
1649    0
1668    3
1683    3
Name: FTR, dtype: object
1.6
15
12.2
Celta - visitante
1480    0
1509    0
1538    0
1543    0
1561    0
1584    3
1601    0
1623    3
1650    0
1663    1
Name: FTR, dtype: object
0.7
Malaga - local
1490    0
1510    0
1521    0
1543    3
1551    3
1578    3
1598    3
1619    0
1638    0
1661    0
Name: FTR, dtype: object
1.2
14
14.0
Ath Bilbao - visitante
1482    0
1503    3
1524    0
1545    0
1554    3
1571    3
1600    0
1618    3
1632    3
1652    0
Name: FTR, dtype: object
1.5
Girona - local
1483    0
1506    3
1516    1
Name: FTR, dtype: object
1.3333333333333333
3
13.666666666666666
Barcelona - visitante
1486    3
1507    3
1534    3
1559    3
1573    3
1598    0
1615    3
1634    0
1665    3
1691    3
Name: FTR, dtype: object
2.4
Ath Madrid - local
1488    3
1524    3
1549    3
1570    0
1589    3
1609    3
1625    3
1645    3
1665    0
1687    3
Name: FTR, dtype: object
2.4
19
16.6
Sevilla - visitante
1483    3
1501    3
1533    0
1551    0
1582    1
1606    0
1625    0
1642    1
1669    3
1686    3
Name: FTR, dtype: object
1.4
Alaves - local
1484    0
1507    0
1538    3
1545    3
1563    1
1581    3
1607    0
1629    3
1642    1
1670    3
Name: FTR, dtype: object
1.7
10
12.8
Real Madrid - visitante
1481    3
1512    3
1521    3
1530    3
1547    3
1566    3
1586    3
1604    3
1628    3
1649    3
Name: FTR, dtype: object
3.0
Villarreal - local
1491    3
1531    1
1560    3
1576    3
1600    3
1616    0
1647    3
1662    0
1684    1
1706    3
Name: FTR, dtype: object
2.0
20
14.1
Espanol - visitante
1498    0
1515    1
1529    3
1544    3
1568    1
1583    3
1610    0
1626    1
1647    0
1657    1
Name: FTR, dtype: object
1.3
Levante - local
1485    1
1504    1
1511    3
1914    3
1933    1
1959    3
1970    1
1992    3
2015    0
2039    3
Name: FTR, dtype: object
1.9
15
13.3
Sociedad - visitante
1492    3
1517    3
1522    1
1550    1
1564    3
1588    0
1609    0
1629    0
1651    3
1671    3
Name: FTR, dtype: object
1.7
Celta - local
1493    3
1517    0
1522    1
1530    0
1554    0
1575    0
1595    0
1611    3
1635    0
1657    1
Name: FTR, dtype: object
0.8
11
12.4
Getafe - visitante
1499    3
1514    1
1904    0
1922    3
1940    3
1961    0
1979    0
1997    0
2018    0
2039    0
Name: FTR, dtype: object
1.0
Sevilla - local
1496    3
1515    1
1526    3
1550    1
1561    3
1580    3
1596    3
1613    1
1637    1
1652    3
Name: FTR, dtype: object
2.2
20
15.6
Las Palmas - visitante
1490    3
1518    0
1528    0
1546    0
1565    0
1590    0
1602    0
1611    0
1640    0
1654    1
Name: FTR, dtype: object
0.4
Real Madrid - local
1497    1
1500    1
1533    3
1557    3
1573    0
1597    1
1614    3
1633    3
1654    1
1680    3
Name: FTR, dtype: object
1.9
22
18.0
Betis - visitante
1491    0
1513    0
1525    1
1541    0
1562    0
1575    3
1593    0
1620    0
1633    0
1641    1
Name: FTR, dtype: object
0.5
Leganes - local
1499    0
1519    3
1527    1
1541    3
1565    3
1583    0
1604    0
1622    1
1648    3
1667    3
Name: FTR, dtype: object
1.7
17
13.0
Girona - visitante
1494    0
Name: FTR, dtype: object
0.0
La Coruna - local
1492    0
1512    0
1528    3
1544    0
1566    0
1587    3
1605    1
1623    0
1634    3
1641    1
Name: FTR, dtype: object
1.1
13
13.3
Alaves - visitante
1493    0
1519    0
1527    1
1555    3
1574    1
1599    0
1614    0
1638    3
1656    0
1681    3
Name: FTR, dtype: object
1.1
Ath Bilbao - local
1494    3
1514    1
1537    1
1562    3
1590    3
1610    3
1628    0
1646    3
1666    3
1690    3
Name: FTR, dtype: object
2.3
19
13.7
Ath Madrid - visitante
1495    1
1505    3
1516    1
1536    1
1558    3
1579    3
1597    1
1619    3
1639    3
1653    1
Name: FTR, dtype: object
2.0
Valencia - local
1495    1
1518    3
1520    0
1542    3
1564    0
1582    1
1601    3
1612    3
1636    1
1659    3

Name: FTR, dtype: object
1.8
16
16.1
Malaga - visitante
1488    0
1506    0
1532    1
1569    3
1587    0
1603    3
1622    1
1646    0
1668    0
1684    1
Name: FTR, dtype: object
0.9
Barcelona - local
1498    3
1513    3
1523    3
1548    3
1567    3
1588    3
1606    3
1624    3
1650    3
1658    3
Name: FTR, dtype: object
3.0
43
19.5
Eibar - visitante
1496    0
1510    3
1523    0
1549    0
1563    1
1585    0
1595    3
1616    3
1631    1
1660    1
Name: FTR, dtype: object
1.2
Espanol - local
1502    0
1540    0
1559    0
1579    0
1599    3
1620    3
1640    3
1664    3
1692    0
1703    3
Name: FTR, dtype: object
1.5
14
12.4
Celta - visitante
1509    0
1538    0
1543    0
1561    0
1584    3
1601    0
1623    3
1650    0
1663    1
1687    0
Name: FTR, dtype: object
0.7
Sociedad - local
1508    3
1532    1
1556    3
1572    3
1591    3
1617    1
1632    0
1660    1
1675    0
1695    3
Name: FTR, dtype: object
1.8
17
15.3
Real Madrid - visitante
1512    3
1521    3
1530    3
1547    3
1566    3
1586    3
1604    3
1628    3
1649    3
1662    3
Name: FTR, dtype: object
3.0
Las Palmas - local
1505    0
1534    0
1558    0
1574    1
1593    3
1630    3
1644    3
1671    0
1686    0
1701    3
Name: FTR, dtype: object
1.3
16
13.6
Ath Bilbao - visitante
1503    3
1524    0
1545    0
1554    3
1571    3
1600    0
1618    3
1632    3
1652    0
1674    0
Name: FTR, dtype: object
1.5
Girona - local
1506    3
1516    1
Name: FTR, dtype: object
2.0
3
14.0
Sevilla - visitante
1501    3
1533    0
1551    0
1582    1
1606    0
1625    0
1642    1
1669    3
1686    3
1703    0
Name: FTR, dtype: object
1.1
Alaves - local
1507    0
1538    3
1545    3
1563    1
1581    3
1607    0
1629    3
1642    1
1670    3
1691    0
Name: FTR, dtype: object
1.7
10
12.1
Villarreal - visitante
1508    0
1511    0
1520    3
1548    0
1570    3
1581    0
1608    3
1630    0
1635    3
1655    3
Name: FTR, dtype: object
1.5
Levante - local
1504    1
1511    3
1914    3
1933    1
1959    3
1970    1
1992    3
2015    0
2039    3
2052    0
Name: FTR, dtype: object
1.8
14
13.5
Valencia - visitante
1500    1
1540    3
1557    0
1578    0
1594    3
1624    0
1645    0
1670    0
1689    1
1701    0
Name: FTR, dtype: object
0.8
Getafe - local
1501    0
1916    1
1934    1
1956    0
1989    1
2009    1
2027    0
2043    0
2068    0
2085    3
Name: FTR, dtype: object
0.7
9
13.9
Barcelona - visitante
1507    3
1534    3
1559    3
1573    3
1598    0
1615    3
1634    0
1665    3
1691    3
1704    1
Name: FTR, dtype: object
2.2
Betis - local
1509    3
1536    1
1555    0
1585    3
1608    0
1627    3
1651    0
1669    0
1689    1
1704    1
Name: FTR, dtype: object
1.2
12
12.4
La Coruna - visitante
1504    1
1531    1
1552    1
1572    0
1596    0
1612    0
1643    3
1667    0
1690    0
1708    0
Name: FTR, dtype: object
0.6
Ath Madrid - local
1524    3
1549    3
1570    0
1589    3
1609    3
1625    3
1645    3
1665    0
1687    3
1700    3
Name: FTR, dtype: object
2.4
20
16.1
Malaga - visitante
1506    0
1532    1
1569    3
1587    0
1603    3
1622    1
1646    0
1668    0
1684    1
1710    1
Name: FTR, dtype: object
1.0
Eibar - local
1503    0
1535    0
1553    3
1571    0
1602    3
1626    1
1649    0
1668    3
1683    3
1708    3
Name: FTR, dtype: object
1.6
17
12.4
Leganes - visitante
1502    3
1537    1
1553    0
1576    0
1592    0
1617    1
1637    1
1659    0
1677    0
1700    0
Name: FTR, dtype: object
0.6
Malaga - local
1510    0
1521    0
1543    3
1551    3
1578    3
1598    3
1619    0
1638    0
1661    0
1673    3
Name: FTR, dtype: object
1.5
15
13.9
Las Palmas - visitante
1518    0
1528    0
1546    0
1565    0
1590    0
1602    0
1611    0
1640    0
1654    1
1673    0
Name: FTR, dtype: object
0.1
Villarreal - local
1531    1
1560    3
1576    3
1600    3
1616    0
1647    3
1662    0
1684    1
1706    3
1716    0
Name: FTR, dtype: object
1.7
17
14.7
Betis - visitante
1513    0
1525    1
1541    0
1562    0
1575    3
1593    0
1620    0
1633    0
1641    1
1661    3
Name: FTR, dtype: object
0.8
La Coruna - local
1512    0
1528    3
1544    0
1566    0
1587    3
1605    1
1623    0
1634    3
1641    1
1653    1
Name: FTR, dtype: object
1.2
12
13.5
Sociedad - visitante
1517    3
1522    1
1550    1
1564    3
1588    0
1609    0
1629    0
1651    3
1671    3
1692    3
Name: FTR, dtype: object
1.7
Celta - local
1517    0
1522    1
1530    0
1554    0
1575    0
1595    0
1611    3
1635    0
1657    1
1676    3
Name: FTR, dtype: object
0.8
13
11.5
Alaves - visitante
1519    0
1527    1
1555    3
1574    1
1599    0
1614    0
1638    3
1656    0
1681    3
1694    3
Name: FTR, dtype: object
1.4
Ath Bilbao - local
1514    1
1537    1
1562    3
1590    3
1610    3
1628    0
1646    3
1666    3
1690    3
1705    3
Name: FTR, dtype: object
2.3
19
14.1
Girona - visitante
Series([], Name: FTR, dtype: object)
0.0
Valencia - local
1518    3
1520    0
1542    3
1564    0
1582    1
1601    3
1612    3
1636    1
1659    3
1672    3
Name: FTR, dtype: object
2.0
18
15.8
Ath Madrid - visitante
1505    3
1516    1
1536    1
1558    3
1579    3
1597    1
1619    3
1639    3
1653    1
1678    3
Name: FTR, dtype: object
2.2
Sevilla - local
1515    1
1526    3
1550    1
1561    3
1580    3
1596    3
1613    1
1637    1
1652    3
1679    3
Name: FTR, dtype: object
2.2
19
15.5
Eibar - visitante
1510    3
1523    0
1549    0
1563    1
1585    0
1595    3
1616    3
1631    1
1660    1
1679    0
Name: FTR, dtype: object
1.2
Real Madrid - local
1500    1
1533    3
1557    3
1573    0
1597    1
1614    3
1633    3
1654    1
1680    3
1702    3
Name: FTR, dtype: object
2.1
24
16.9
Levante - visitante
1900    0
1920    0
1941    0
1968    0
1986    0
2003    1
2020    0
2044    0
2063    0
2090    0
Name: FTR, dtype: object
0.1
Barcelona - local
1513    3
1523    3
1548    3
1567    3
1588    3
1606    3
1624    3
1650    3
1658    3
1677    3
Name: FTR, dtype: object
3.0
40
18.8
Espanol - visitante
1515    1
1529    3
1544    3
1568    1
1583    3
1610    0
1626    1
1647    0
1657    1
1680    0
Name: FTR, dtype: object
1.3
Leganes - local
1519    3
1527    1
1541    3
1565    3
1583    0
1604    0
1622    1
1648    3
1667    3
1685    0
Name: FTR, dtype: object
1.7
16
12.8
Getafe - visitante
1514    1
1904    0
1922    3
1940    3
1961    0
1979    0
1997    0
2018    0
2039    0
2060    0
Name: FTR, dtype: object
0.7
Real Madrid - local
1533    3
1557    3
1573    0
1597    1
1614    3
1633    3
1654    1
1680    3
1702    3
1717    3
Name: FTR, dtype: object
2.3
24
16.1
Valencia - visitante
1540    3
1557    0
1578    0
1594    3
1624    0
1645    0
1670    0
1689    1
1701    0
1716    3
Name: FTR, dtype: object
1.0
Getafe - local
1916    1
1934    1
1956    0
1989    1
2009    1
2027    0
2043    0
2068    0
2085    3
2099    3
Name: FTR, dtype: object
1.0
10
13.2
Sevilla - visitante
1533    0
1551    0
1582    1
1606    0
1625    0
1642    1
1669    3
1686    3
1703    0
1712    3
Name: FTR, dtype: object
1.1
Espanol - local
1540    0
1559    0
1579    0
1599    3
1620    3
1640    3
1664    3
1692    0
1703    3
1718    3
Name: FTR, dtype: object
1.8
17
12.4
Leganes - visitante
1537    1
1553    0
1576    0
1592    0
1617    1
1637    1
1659    0
1677    0
1700    0
1719    1
Name: FTR, dtype: object
0.4
Eibar - local
1535    0
1553    3
1571    0
1602    3
1626    1
1649    0
1668    3
1683    3
1708    3
1713    0
Name: FTR, dtype: object
1.6
17
12.4
Ath Bilbao - visitante
1524    0
1545    0
1554    3
1571    3
1600    0
1618    3
1632    3
1652    0
1674    0
1699    0
Name: FTR, dtype: object
1.2
Levante - local
1511    3
1914    3
1933    1
1959    3
1970    1
1992    3
2015    0
2039    3
2052    0
2071    3
Name: FTR, dtype: object
2.0
15
12.3
La Coruna - visitante
1531    1
1552    1
1572    0
1596    0
1612    0
1643    3
1667    0
1690    0
1708    0
1720    1
Name: FTR, dtype: object
0.6
Las Palmas - local
1534    0
1558    0
1574    1
1593    3
1630    3
1644    3
1671    0
1686    0
1701    3
1720    1
Name: FTR, dtype: object
1.4
16
13.5
Ath Madrid - visitante
1516    1
1536    1
1558    3
1579    3
1597    1
1619    3
1639    3
1653    1
1678    3
1709    1
Name: FTR, dtype: object
2.0
Girona - local
1516    1
Name: FTR, dtype: object
1.0
2
13.0
Malaga - visitante
1532    1
1569    3
1587    0
1603    3
1622    1
1646    0
1668    0
1684    1
1710    1
1717    0
Name: FTR, dtype: object
1.0
Alaves - local
1538    3
1545    3
1563    1
1581    3
1607    0
1629    3
1642    1
1670    3
1691    0
1709    1
Name: FTR, dtype: object
1.8
10
12.9
Barcelona - visitante
1534    3
1559    3
1573    3
1598    0
1615    3
1634    0
1665    3
1691    3
1704    1
1713    3
Name: FTR, dtype: object
2.2
Sociedad - local
1532    1
1556    3
1572    3
1591    3
1617    1
1632    0
1660    1
1675    0
1695    3
1711    3
Name: FTR, dtype: object
1.8
15
15.5
Villarreal - visitante
1511    0
1520    3
1548    0
1570    3
1581    0
1608    3
1630    0
1635    3
1655    3
1675    3
Name: FTR, dtype: object
1.8
Betis - local
1536    1
1555    0
1585    3
1608    0
1627    3
1651    0
1669    0
1689    1
1704    1
1714    1
Name: FTR, dtype: object
1.0
10
13.0
Celta - visitante
1538    0
1543    0
1561    0
1584    3
1601    0
1623    3
1650    0
1663    1
1687    0
1707    3
Name: FTR, dtype: object
1.0
Malaga - local
1521    0
1543    3
1551    3
1578    3
1598    3
1619    0
1638    0
1661    0
1673    3
1698    0

Name: FTR, dtype: object
1.5
15
14.8
Eibar - visitante
1523    0
1549    0
1563    1
1585    0
1595    3
1616    3
1631    1
1660    1
1679    0
1697    3
Name: FTR, dtype: object
1.2
Levante - local
1914    3
1933    1
1959    3
1970    1
1992    3
2015    0
2039    3
2052    0
2071    3
2098    3
Name: FTR, dtype: object
2.0
16
11.9
Villarreal - visitante
1520    3
1548    0
1570    3
1581    0
1608    3
1630    0
1635    3
1655    3
1675    3
1696    1
Name: FTR, dtype: object
1.9
La Coruna - local
1528    3
1544    0
1566    0
1587    3
1605    1
1623    0
1634    3
1641    1
1653    1
1681    0
Name: FTR, dtype: object
1.2
12
13.9
Real Madrid - visitante
1521    3
1530    3
1547    3
1566    3
1586    3
1604    3
1628    3
1649    3
1662    3
1672    0
Name: FTR, dtype: object
2.7
Barcelona - local
1523    3
1548    3
1567    3
1588    3
1606    3
1624    3
1650    3
1658    3
1677    3
1699    3
Name: FTR, dtype: object
3.0
41
18.9
Betis - visitante
1525    1
1541    0
1562    0
1575    3
1593    0
1620    0
1633    0
1641    1
1661    3
1682    0
Name: FTR, dtype: object
0.8
Ath Bilbao - local
1537    1
1562    3
1590    3
1610    3
1628    0
1646    3
1666    3
1690    3
1705    3
1715    1
Name: FTR, dtype: object
2.3
21
13.7
Getafe - visitante
1904    0
1922    3
1940    3
1961    0
1979    0
1997    0
2018    0
2039    0
2060    0
2078    0
Name: FTR, dtype: object
0.6
Sevilla - local
1526    3
1550    1
1561    3
1580    3
1596    3
1613    1
1637    1
1652    3
1679    3
1696    1
Name: FTR, dtype: object
2.2
18
16.0
Espanol - visitante
1529    3
1544    3
1568    1
1583    3
1610    0
1626    1
1647    0
1657    1
1680    0
1698    3
Name: FTR, dtype: object
1.5
Girona - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Ath Madrid - visitante
1536    1
1558    3
1579    3
1597    1
1619    3
1639    3
1653    1
1678    3
1709    1
1715    1
Name: FTR, dtype: object
2.0
Celta - local
1522    1
1530    0
1554    0
1575    0
1595    0
1611    3
1635    0
1657    1
1676    3
1726    3
Name: FTR, dtype: object
1.1
12
11.2
Sociedad - visitante
1522    1
1550    1
1564    3
1588    0
1609    0
1629    0
1651    3
1671    3
1692    3
1702    0
Name: FTR, dtype: object
1.4
Valencia - local
1520    0
1542    3
1564    0
1582    1
1601    3
1612    3
1636    1
1659    3
1672    3
1674    3
Name: FTR, dtype: object
2.0
19
15.1
Las Palmas - visitante
1528    0
1546    0
1565    0
1590    0
1602    0
1611    0
1640    0
1654    1
1673    0
1693    0
Name: FTR, dtype: object
0.1
Leganes - local
1527    1
1541    3
1565    3
1583    0
1604    0
1622    1
1648    3
1667    3
1685    0
1707    0
Name: FTR, dtype: object
1.4
15
11.8
Alaves - visitante
1527    1
1555    3
1574    1
1599    0
1614    0
1638    3
1656    0
1681    3
1694    3
1726    0
Name: FTR, dtype: object
1.4
Valencia - local
1542    3
1564    0
1582    1
1601    3
1612    3
1636    1
1659    3
1672    3
1674    3
1697    0
Name: FTR, dtype: object
2.0
18
14.3
Villarreal - visitante
1548    0
1570    3
1581    0
1608    3
1630    0
1635    3
1655    3
1675    3
1696    1
1728    1
Name: FTR, dtype: object
1.7
Malaga - local
1543    3
1551    3
1578    3
1598    3
1619    0
1638    0
1661    0
1673    3
1698    0
1721    0
Name: FTR, dtype: object
1.5
15
13.1
Real Madrid - visitante
1530    3
1547    3
1566    3
1586    3
1604    3
1628    3
1649    3
1662    3
1672    0
1688    3
Name: FTR, dtype: object
2.7
Celta - local
1530    0
1554    0
1575    0
1595    0
1611    3
1635    0
1657    1
1676    3
1726    3
1733    3
Name: FTR, dtype: object
1.3
13
10.5
Sociedad - visitante
1550    1
1564    3
1588    0
1609    0
1629    0
1651    3
1671    3
1692    3
1702    0
1721    3
Name: FTR, dtype: object
1.6
Barcelona - local
1548    3
1567    3
1588    3
1606    3
1624    3
1650    3
1658    3
1677    3
1699    3
1729    3
Name: FTR, dtype: object
3.0
42
19.3
Eibar - visitante
1549    0
1563    1
1585    0
1595    3
1616    3
1631    1
1660    1
1679    0
1697    3
1723    3
Name: FTR, dtype: object
1.5
Ath Madrid - local
1549    3
1570    0
1589    3
1609    3
1625    3
1645    3
1665    0
1687    3
1700    3
1730    3
Name: FTR, dtype: object
2.4
18
15.5
Ath Bilbao - visitante
1545    0
1554    3
1571    3
1600    0
1618    3
1632    3
1652    0
1674    0
1699    0
1727    1
Name: FTR, dtype: object
1.3
Sp Gijon - local
1546    3
1568    1
1586    0
1603    0
1621    3
1643    0
1663    1
1678    0
1694    0
1723    0
Name: FTR, dtype: object
0.8
13
13.1
Betis - visitante
1541    0
1562    0
1575    3
1593    0
1620    0
1633    0
1641    1
1661    3
1682    0
1730    0
Name: FTR, dtype: object
0.7
Sevilla - local
1550    1
1561    3
1580    3
1596    3
1613    1
1637    1
1652    3
1679    3
1696    1
1724    3
Name: FTR, dtype: object
2.2
15
15.2
Osasuna - visitante
1542    0
1567    0
1589    0
1607    3
1627    0
1644    0
1664    0
1676    0
1695    0
1725    1
Name: FTR, dtype: object
0.4
Leganes - local
1541    3
1565    3
1583    0
1604    0
1622    1
1648    3
1667    3
1685    0
1707    0
1727    1
Name: FTR, dtype: object
1.4
14
11.8
Alaves - visitante
1555    3
1574    1
1599    0
1614    0
1638    3
1656    0
1681    3
1694    3
1726    0
1735    1
Name: FTR, dtype: object
1.4
La Coruna - local
1544    0
1566    0
1587    3
1605    1
1623    0
1634    3
1641    1
1653    1
1681    0
1728    1
Name: FTR, dtype: object
1.0
9
14.3
Las Palmas - visitante
1546    0
1565    0
1590    0
1602    0
1611    0
1640    0
1654    1
1673    0
1693    0
1729    0
Name: FTR, dtype: object
0.1
Granada - local
1547    0
1569    0
1584    0
1594    0
1615    0
1639    0
1656    3
1682    3
1693    3
1725    1
Name: FTR, dtype: object
1.0
10
11.6
Espanol - visitante
1544    3
1568    1
1583    3
1610    0
1626    1
1647    0
1657    1
1680    0
1698    3
1722    0
Name: FTR, dtype: object
1.2
Celta - local
1554    0
1575    0
1595    0
1611    3
1635    0
1657    1
1676    3
1726    3
1733    3
1753    0
Name: FTR, dtype: object
1.3
12
10.2
Real Madrid - visitante
1547    3
1566    3
1586    3
1604    3
1628    3
1649    3
1662    3
1672    0
1688    3
1724    0
Name: FTR, dtype: object
2.4
Villarreal - local
1560    3
1576    3
1600    3
1616    0
1647    3
1662    0
1684    1
1706    3
1716    0
1732    1
Name: FTR, dtype: object
1.7
18
13.2
La Coruna - visitante
1552    1
1572    0
1596    0
1612    0
1643    3
1667    0
1690    0
1708    0
1720    1
1740    1
Name: FTR, dtype: object
0.6
Sociedad - local
1556    3
1572    3
1591    3
1617    1
1632    0
1660    1
1675    0
1695    3
1711    3
1736    0
Name: FTR, dtype: object
1.7
13
15.1
Malaga - visitante
1569    3
1587    0
1603    3
1622    1
1646    0
1668    0
1684    1
1710    1
1717    0
1733    0
Name: FTR, dtype: object
0.9
Real Madrid - local
1557    3
1573    0
1597    1
1614    3
1633    3
1654    1
1680    3
1702    3
1717    3
1737    3
Name: FTR, dtype: object
2.3
25
17.0
Sevilla - visitante
1551    0
1582    1
1606    0
1625    0
1642    1
1669    3
1686    3
1703    0
1712    3
1736    3
Name: FTR, dtype: object
1.4
Las Palmas - local
1558    0
1574    1
1593    3
1630    3
1644    3
1671    0
1686    0
1701    3
1720    1
1738    3
Name: FTR, dtype: object
1.7
16
14.0
Barcelona - visitante
1559    3
1573    3
1598    0
1615    3
1634    0
1665    3
1691    3
1704    1
1713    3
1732    1
Name: FTR, dtype: object
2.0
Eibar - local
1553    3
1571    0
1602    3
1626    1
1649    0
1668    3
1683    3
1708    3
1713    0
1739    0
Name: FTR, dtype: object
1.6
17
12.9
Sp Gijon - visitante
1560    0
1577    1
1591    0
1613    1
1636    1
1658    0
1685    3
1705    0
1714    1
1738    0
Name: FTR, dtype: object
0.7
Betis - local
1555    0
1585    3
1608    0
1627    3
1651    0
1669    0
1689    1
1704    1
1714    1
1734    3
Name: FTR, dtype: object
1.2
11
13.3
Ath Madrid - visitante
1558    3
1579    3
1597    1
1619    3
1639    3
1653    1
1678    3
1709    1
1715    1
1739    3
Name: FTR, dtype: object
2.2
Ath Bilbao - local
1562    3
1590    3
1610    3
1628    0
1646    3
1666    3
1690    3
1705    3
1715    1
1735    1
Name: FTR, dtype: object
2.3
20
13.7
Leganes - visitante
1553    0
1576    0
1592    0
1617    1
1637    1
1659    0
1677    0
1700    0
1719    1
1734    0
Name: FTR, dtype: object
0.3
Alaves - local
1545    3
1563    1
1581    3
1607    0
1629    3
1642    1
1670    3
1691    0
1709    1
1719    1
Name: FTR, dtype: object
1.6
9
12.6
Celta - visitante
1543    0
1561    0
1584    3
1601    0
1623    3
1650    0
1663    1
1687    0
1707    3
1711    0
Name: FTR, dtype: object
1.0
Osasuna - local
1552    1
1577    1
1592    3
1618    0
1631    1
1655    0
1688    0
1710    1
1712    0
1731    1
Name: FTR, dtype: object
0.8
17
13.0
Granada - visitante
1556    0
1580    0
1605    1
1621    0
1648    0
1666    0
1683    0
1706    0
1718    0
1737    0
Name: FTR, dtype: object
0.1
Espanol - local
1559    0
1579    0
1599    3
1620    3
1640    3
1664    3
1692    0
1703    3
1718    3
1740    1
Name: FTR, dtype: object
1.9
18
12.3
Valencia - visitante
1557    0
1578    0
1594    3
1624    0
1645    0
1670    0
1689    1
1701    0
1716    3
1731    1
Name: FTR, dtype: object
0.8

Leganes - local
1565    3
1583    0
1604    0
1622    1
1648    3
1667    3
1685    0
1707    0
1727    1
1742    1
Name: FTR, dtype: object
1.2
11
12.0
Betis - visitante
1562    0
1575    3
1593    0
1620    0
1633    0
1641    1
1661    3
1682    0
1730    0
1749    0
Name: FTR, dtype: object
0.7
Valencia - local
1564    0
1582    1
1601    3
1612    3
1636    1
1659    3
1672    3
1674    3
1697    0
1722    3
Name: FTR, dtype: object
2.0
16
13.4
Osasuna - visitante
1567    0
1589    0
1607    3
1627    0
1644    0
1664    0
1676    0
1695    0
1725    1
1743    0
Name: FTR, dtype: object
0.4
Malaga - local
1551    3
1578    3
1598    3
1619    0
1638    0
1661    0
1673    3
1698    0
1721    0
1759    1
Name: FTR, dtype: object
1.3
13
13.3
Celta - visitante
1561    0
1584    3
1601    0
1623    3
1650    0
1663    1
1687    0
1707    3
1711    0
1741    0
Name: FTR, dtype: object
1.0
La Coruna - local
1566    0
1587    3
1605    1
1623    0
1634    3
1641    1
1653    1
1681    0
1728    1
1743    3
Name: FTR, dtype: object
1.3
10
13.0
Espanol - visitante
1568    1
1583    3
1610    0
1626    1
1647    0
1657    1
1680    0
1698    3
1722    0
1744    0
Name: FTR, dtype: object
0.9
Alaves - local
1563    1
1581    3
1607    0
1629    3
1642    1
1670    3
1691    0
1709    1
1719    1
1749    3
Name: FTR, dtype: object
1.6
9
12.7
Ath Bilbao - visitante
1554    3
1571    3
1600    0
1618    3
1632    3
1652    0
1674    0
1699    0
1727    1
1754    0
Name: FTR, dtype: object
1.3
Sp Gijon - local
1568    1
1586    0
1603    0
1621    3
1643    0
1663    1
1678    0
1694    0
1723    0
1745    0
Name: FTR, dtype: object
0.5
13
13.1
Las Palmas - visitante
1565    0
1590    0
1602    0
1611    0
1640    0
1654    1
1673    0
1693    0
1729    0
1748    0
Name: FTR, dtype: object
0.1
Granada - local
1569    0
1584    0
1594    0
1615    0
1639    0
1656    3
1682    3
1693    3
1725    1
1747    0
Name: FTR, dtype: object
1.0
10
11.3
Real Madrid - visitante
1566    3
1586    3
1604    3
1628    3
1649    3
1662    3
1672    0
1688    3
1724    0
1768    1
Name: FTR, dtype: object
2.2
Barcelona - local
1567    3
1588    3
1606    3
1624    3
1650    3
1658    3
1677    3
1699    3
1729    3
1744    3
Name: FTR, dtype: object
3.0
42
18.7
Villarreal - visitante
1570    3
1581    0
1608    3
1630    0
1635    3
1655    3
1675    3
1696    1
1728    1
1745    3
Name: FTR, dtype: object
2.0
Ath Madrid - local
1570    0
1589    3
1609    3
1625    3
1645    3
1665    0
1687    3
1700    3
1730    3
1748    3
Name: FTR, dtype: object
2.4
18
15.7
Eibar - visitante
1563    1
1585    0
1595    3
1616    3
1631    1
1660    1
1679    0
1697    3
1723    3
1742    1
Name: FTR, dtype: object
1.6
Sevilla - local
1561    3
1580    3
1596    3
1613    1
1637    1
1652    3
1679    3
1696    1
1724    3
1746    3
Name: FTR, dtype: object
2.4
18
15.0
Sociedad - visitante
1564    3
1588    0
1609    0
1629    0
1651    3
1671    3
1692    3
1702    0
1721    3
1747    3
Name: FTR, dtype: object
1.8
Malaga - local
1578    3
1598    3
1619    0
1638    0
1661    0
1673    3
1698    0
1721    0
1759    1
1777    3
Name: FTR, dtype: object
1.3
13
13.2
Sevilla - visitante
1582    1
1606    0
1625    0
1642    1
1669    3
1686    3
1703    0
1712    3
1736    3
1753    3
Name: FTR, dtype: object
1.7
Osasuna - local
1577    1
1592    3
1618    0
1631    1
1655    0
1688    0
1710    1
1712    0
1731    1
1757    0
Name: FTR, dtype: object
0.7
15
11.8
La Coruna - visitante
1572    0
1596    0
1612    0
1643    3
1667    0
1690    0
1708    0
1720    1
1740    1
1756    0
Name: FTR, dtype: object
0.5
Eibar - local
1571    0
1602    3
1626    1
1649    0
1668    3
1683    3
1708    3
1713    0
1739    0
1752    1
Name: FTR, dtype: object
1.4
15
12.8
Leganes - visitante
1576    0
1592    0
1617    1
1637    1
1659    0
1677    0
1700    0
1719    1
1734    0
1758    1
Name: FTR, dtype: object
0.4
Celta - local
1575    0
1595    0
1611    3
1635    0
1657    1
1676    3
1726    3
1733    3
1753    0
1774    3
Name: FTR, dtype: object
1.6
15
11.3
Ath Bilbao - visitante
1571    3
1600    0
1618    3
1632    3
1652    0
1674    0
1699    0
1727    1
1754    0
1770    0
Name: FTR, dtype: object
1.0
Betis - local
1585    3
1608    0
1627    3
1651    0
1669    0
1689    1
1704    1
1714    1
1734    3
1754    3
Name: FTR, dtype: object
1.5
11
12.8
Alaves - visitante
1574    1
1599    0
1614    0
1638    3
1656    0
1681    3
1694    3
1726    0
1735    1
1752    1
Name: FTR, dtype: object
1.2
Sociedad - local
1572    3
1591    3
1617    1
1632    0
1660    1
1675    0
1695    3
1711    3
1736    0
1755    3
Name: FTR, dtype: object
1.7
14
15.2
Granada - visitante
1580    0
1605    1
1621    0
1648    0
1666    0
1683    0
1706    0
1718    0
1737    0
1759    1
Name: FTR, dtype: object
0.2
Real Madrid - local
1573    0
1597    1
1614    3
1633    3
1654    1
1680    3
1702    3
1717    3
1737    3
1756    3
Name: FTR, dtype: object
2.3
26
16.7
Valencia - visitante
1578    0
1594    3
1624    0
1645    0
1670    0
1689    1
1701    0
1716    3
1731    1
1755    0
Name: FTR, dtype: object
0.8
Las Palmas - local
1574    1
1593    3
1630    3
1644    3
1671    0
1686    0
1701    3
1720    1
1738    3
1758    1
Name: FTR, dtype: object
1.8
17
13.0
Ath Madrid - visitante
1579    3
1597    1
1619    3
1639    3
1653    1
1678    3
1709    1
1715    1
1739    3
1750    0
Name: FTR, dtype: object
1.9
Espanol - local
1579    0
1599    3
1620    3
1640    3
1664    3
1692    0
1703    3
1718    3
1740    1
1751    3
Name: FTR, dtype: object
2.2
20
12.9
Barcelona - visitante
1573    3
1598    0
1615    3
1634    0
1665    3
1691    3
1704    1
1713    3
1732    1
1757    3
Name: FTR, dtype: object
2.0
Villarreal - local
1576    3
1600    3
1616    0
1647    3
1662    0
1684    1
1706    3
1716    0
1732    1
1750    3
Name: FTR, dtype: object
1.7
18
12.3
Sp Gijon - visitante
1577    1
1591    0
1613    1
1636    1
1658    0
1685    3
1705    0
1714    1
1738    0
1751    0
Name: FTR, dtype: object
0.7
Sevilla - local
1580    3
1596    3
1613    1
1637    1
1652    3
1679    3
1696    1
1724    3
1746    3
1775    3
Name: FTR, dtype: object
2.4
18
14.0
Celta - visitante
1584    3
1601    0
1623    3
1650    0
1663    1
1687    0
1707    3
1711    0
1741    0
1763    1
Name: FTR, dtype: object
1.1
Ath Bilbao - local
1590    3
1610    3
1628    0
1646    3
1666    3
1690    3
1705    3
1715    1
1735    1
1741    3
Name: FTR, dtype: object
2.3
20
12.9
Betis - visitante
1575    3
1593    0
1620    0
1633    0
1641    1
1661    3
1682    0
1730    0
1749    0
1779    0
Name: FTR, dtype: object
0.7
Alaves - local
1581    3
1607    0
1629    3
1642    1
1670    3
1691    0
1709    1
1719    1
1749    3
1765    1
Name: FTR, dtype: object
1.6
10
12.2
Eibar - visitante
1585    0
1595    3
1616    3
1631    1
1660    1
1679    0
1697    3
1723    3
1742    1
1764    0
Name: FTR, dtype: object
1.5
Valencia - local
1582    1
1601    3
1612    3
1636    1
1659    3
1672    3
1674    3
1697    0
1722    3
1761    1
Name: FTR, dtype: object
2.1
16
12.8
Sociedad - visitante
1588    0
1609    0
1629    0
1651    3
1671    3
1692    3
1702    0
1721    3
1747    3
1760    0
Name: FTR, dtype: object
1.5
Leganes - local
1583    0
1604    0
1622    1
1648    3
1667    3
1685    0
1707    0
1727    1
1742    1
1766    1
Name: FTR, dtype: object
1.0
8
11.5
Las Palmas - visitante
1590    0
1602    0
1611    0
1640    0
1654    1
1673    0
1693    0
1729    0
1748    0
1765    1
Name: FTR, dtype: object
0.2
La Coruna - local
1587    3
1605    1
1623    0
1634    3
1641    1
1653    1
1681    0
1728    1
1743    3
1760    3
Name: FTR, dtype: object
1.6
13
12.6
Real Madrid - visitante
1586    3
1604    3
1628    3
1649    3
1662    3
1672    0
1688    3
1724    0
1768    1
1788    3
Name: FTR, dtype: object
2.2
Barcelona - local
1588    3
1606    3
1624    3
1650    3
1658    3
1677    3
1699    3
1729    3
1744    3
1768    1
Name: FTR, dtype: object
2.8
36
17.9
Osasuna - visitante
1589    0
1607    3
1627    0
1644    0
1664    0
1676    0
1695    0
1725    1
1743    0
1762    0
Name: FTR, dtype: object
0.4
Sp Gijon - local
1586    0
1603    0
1621    3
1643    0
1663    1
1678    0
1694    0
1723    0
1745    0
1762    3
Name: FTR, dtype: object
0.7
15
12.4
Espanol - visitante
1583    3
1610    0
1626    1
1647    0
1657    1
1680    0
1698    3
1722    0
1744    0
1769    1
Name: FTR, dtype: object
0.9
Granada - local
1584    0
1594    0
1615    0
1639    0
1656    3
1682    3
1693    3
1725    1
1747    0
1767    3
Name: FTR, dtype: object
1.3
12
12.1
Malaga - visitante
1587    0
1603    3
1622    1
1646    0
1668    0
1684    1
1710    1
1717    0
1733    0
1746    0
Name: FTR, dtype: object
0.6
Ath Madrid - local
1589    3
1609    3
1625    3
1645    3
1665    0
1687    3
1700    3
1730    3
1748    3
1769    1
Name: FTR, dtype: object
2.5
18
14.5
Villarreal - visitante
1581    0
1608    3
1630    0
1635    3
1655    3
1675    3
1696    1
1728    1
1745    3
1766    1
Name: FTR, dtype: object
1.8
Eibar - local
1602    3
1626    1
1649    0
1668    3
1683    3
1708    3
1713    0
1739    0
1752    1
1779    3
Name: FTR, dtype: object
1.7
18
13.7
Ath Bilbao - visitante
1600    0
1618    3
1632    3
1652    0
1674    0
1699    0
1727    1
1754    0
1770    0
1793    1
Name: FTR, dtype: object
0.8
Sociedad - local
1591    3
1617    1
1632    0
1660    1
1675    0
1695    3
1711    3
1736    0
1755    3
1772    1
Name: FTR, dtype: object
1.5
14
15.2
La Coruna - visitante
1596    0
1612    0
1643    3
1667    0
1690    0
1708    0
1720    1
1740    1
1756    0
1777    0
Name: FTR, dtype: object
0.5
Real Madrid - local
1597    1
1614    3
1633    3
1654    1
1680    3
1702    3
1717    3
1737    3
1756    3
1776    3
Name: FTR, dtype: object
2.6
26
16.4
Barcelona - visitante
1598    0
1615    3
1634    0
1665    3
1691    3
1704    1
1713    3
1732    1
1757    3
1772    1

Name: FTR, dtype: object
1.8
Las Palmas - local
1593    3
1630    3
1644    3
1671    0
1686    0
1701    3
1720    1
1738    3
1758    1
1770    3
Name: FTR, dtype: object
2.0
19
12.6
Alaves - visitante
1599    0
1614    0
1638    3
1656    0
1681    3
1694    3
1726    0
1735    1
1752    1
1771    3
Name: FTR, dtype: object
1.4
Celta - local
1595    0
1611    3
1635    0
1657    1
1676    3
1726    3
1733    3
1753    0
1774    3
1794    3
Name: FTR, dtype: object
1.9
17
11.2
Betis - visitante
1593    0
1620    0
1633    0
1641    1
1661    3
1682    0
1730    0
1749    0
1779    0
1790    0
Name: FTR, dtype: object
0.4
Villarreal - local
1600    3
1616    0
1647    3
1662    0
1684    1
1706    3
1716    0
1732    1
1750    3
1771    0
Name: FTR, dtype: object
1.4
16
13.5
Leganes - visitante
1592    0
1617    1
1637    1
1659    0
1677    0
1700    0
1719    1
1734    0
1758    1
1778    0
Name: FTR, dtype: object
0.4
Osasuna - local
1592    3
1618    0
1631    1
1655    0
1688    0
1710    1
1712    0
1731    1
1757    0
1773    0
Name: FTR, dtype: object
0.6
13
12.2
Sp Gijon - visitante
1591    0
1613    1
1636    1
1658    0
1685    3
1705    0
1714    1
1738    0
1751    0
1776    0
Name: FTR, dtype: object
0.6
Malaga - local
1598    3
1619    0
1638    0
1661    0
1673    3
1698    0
1721    0
1759    1
1777    3
1799    3
Name: FTR, dtype: object
1.3
14
14.4
Valencia - visitante
1594    3
1624    0
1645    0
1670    0
1689    1
1701    0
1716    3
1731    1
1755    0
1775    0
Name: FTR, dtype: object
0.8
Espanol - local
1599    3
1620    3
1640    3
1664    3
1692    0
1703    3
1718    3
1740    1
1751    3
1778    3
Name: FTR, dtype: object
2.5
23
12.7
Ath Madrid - visitante
1597    1
1619    3
1639    3
1653    1
1678    3
1709    1
1715    1
1739    3
1750    0
1773    3
Name: FTR, dtype: object
1.9
Sevilla - local
1596    3
1613    1
1637    1
1652    3
1679    3
1696    1
1724    3
1746    3
1775    3
1791    0
Name: FTR, dtype: object
2.1
17
12.7
Granada - visitante
1605    1
1621    0
1648    0
1666    0
1683    0
1706    0
1718    0
1737    0
1759    1
1774    0
Name: FTR, dtype: object
0.2
Alaves - local
1607    0
1629    3
1642    1
1670    3
1691    0
1709    1
1719    1
1749    3
1765    1
1784    0
Name: FTR, dtype: object
1.3
8
12.1
Villarreal - visitante
1608    3
1630    0
1635    3
1655    3
1675    3
1696    1
1728    1
1745    3
1766    1
1783    0
Name: FTR, dtype: object
1.8
Valencia - local
1601    3
1612    3
1636    1
1659    3
1672    3
1674    3
1697    0
1722    3
1761    1
1781    1
Name: FTR, dtype: object
2.1
17
12.8
Sevilla - visitante
1606    0
1625    0
1642    1
1669    3
1686    3
1703    0
1712    3
1736    3
1753    3
1767    0
Name: FTR, dtype: object
1.6
Leganes - local
1604    0
1622    1
1648    3
1667    3
1685    0
1707    0
1727    1
1742    1
1766    1
1780    3
Name: FTR, dtype: object
1.3
10
11.5
Espanol - visitante
1610    0
1626    1
1647    0
1657    1
1680    0
1698    3
1722    0
1744    0
1769    1
1784    3
Name: FTR, dtype: object
0.9
Granada - local
1594    0
1615    0
1639    0
1656    3
1682    3
1693    3
1725    1
1747    0
1767    3
1798    1
Name: FTR, dtype: object
1.4
13
11.8
Celta - visitante
1601    0
1623    3
1650    0
1663    1
1687    0
1707    3
1711    0
1741    0
1763    1
1786    0
Name: FTR, dtype: object
0.8
Betis - local
1608    0
1627    3
1651    0
1669    0
1689    1
1704    1
1714    1
1734    3
1754    3
1763    1
Name: FTR, dtype: object
1.3
12
13.8
Eibar - visitante
1595    3
1616    3
1631    1
1660    1
1679    0
1697    3
1723    3
1742    1
1764    0
1797    0
Name: FTR, dtype: object
1.5
Sp Gijon - local
1603    0
1621    3
1643    0
1663    1
1678    0
1694    0
1723    0
1745    0
1762    3
1782    0
Name: FTR, dtype: object
0.7
14
12.4
Real Madrid - visitante
1604    3
1628    3
1649    3
1662    3
1672    0
1688    3
1724    0
1768    1
1788    3
1808    3
Name: FTR, dtype: object
2.2
La Coruna - local
1605    1
1623    0
1634    3
1641    1
1653    1
1681    0
1728    1
1743    3
1760    3
1785    0
Name: FTR, dtype: object
1.3
13
11.9
Malaga - visitante
1603    3
1622    1
1646    0
1668    0
1684    1
1710    1
1717    0
1733    0
1746    0
1761    1
Name: FTR, dtype: object
0.7
Barcelona - local
1606    3
1624    3
1650    3
1658    3
1677    3
1699    3
1729    3
1744    3
1768    1
1787    1
Name: FTR, dtype: object
2.6
33
19.1
Sociedad - visitante
1609    0
1629    0
1651    3
1671    3
1692    3
1702    0
1721    3
1747    3
1760    0
1782    3
Name: FTR, dtype: object
1.8
Ath Madrid - local
1609    3
1625    3
1645    3
1665    0
1687    3
1700    3
1730    3
1748    3
1769    1
1788    0
Name: FTR, dtype: object
2.2
15
14.2
Osasuna - visitante
1607    3
1627    0
1644    0
1664    0
1676    0
1695    0
1725    1
1743    0
1762    0
1780    0
Name: FTR, dtype: object
0.4
Ath Bilbao - local
1610    3
1628    0
1646    3
1666    3
1690    3
1705    3
1715    1
1735    1
1741    3
1764    3
Name: FTR, dtype: object
2.3
18
12.3
Las Palmas - visitante
1602    0
1611    0
1640    0
1654    1
1673    0
1693    0
1729    0
1748    0
1765    1
1789    0
Name: FTR, dtype: object
0.2
Sociedad - local
1617    1
1632    0
1660    1
1675    0
1695    3
1711    3
1736    0
1755    3
1772    1
1795    3
Name: FTR, dtype: object
1.5
13
14.4
Sp Gijon - visitante
1613    1
1636    1
1658    0
1685    3
1705    0
1714    1
1738    0
1751    0
1776    0
1799    0
Name: FTR, dtype: object
0.6
Osasuna - local
1618    0
1631    1
1655    0
1688    0
1710    1
1712    0
1731    1
1757    0
1773    0
1796    0
Name: FTR, dtype: object
0.3
11
12.1
Leganes - visitante
1617    1
1637    1
1659    0
1677    0
1700    0
1719    1
1734    0
1758    1
1778    0
1792    0
Name: FTR, dtype: object
0.4
Las Palmas - local
1630    3
1644    3
1671    0
1686    0
1701    3
1720    1
1738    3
1758    1
1770    3
1797    3
Name: FTR, dtype: object
2.0
16
13.3
Betis - visitante
1620    0
1633    0
1641    1
1661    3
1682    0
1730    0
1749    0
1779    0
1790    0
1819    3
Name: FTR, dtype: object
0.7
Granada - local
1615    0
1639    0
1656    3
1682    3
1693    3
1725    1
1747    0
1767    3
1798    1
1817    1
Name: FTR, dtype: object
1.5
12
10.9
Valencia - visitante
1624    0
1645    0
1670    0
1689    1
1701    0
1716    3
1731    1
1755    0
1775    0
1794    0
Name: FTR, dtype: object
0.5
Celta - local
1611    3
1635    0
1657    1
1676    3
1726    3
1733    3
1753    0
1774    3
1794    3
1814    3
Name: FTR, dtype: object
2.2
21
10.9
Eibar - visitante
1616    3
1631    1
1660    1
1679    0
1697    3
1723    3
1742    1
1764    0
1797    0
1818    1
Name: FTR, dtype: object
1.3
Sevilla - local
1613    1
1637    1
1652    3
1679    3
1696    1
1724    3
1746    3
1775    3
1791    0
1811    3
Name: FTR, dtype: object
2.1
14
12.0
La Coruna - visitante
1612    0
1643    3
1667    0
1690    0
1708    0
1720    1
1740    1
1756    0
1777    0
1798    1
Name: FTR, dtype: object
0.6
Real Madrid - local
1614    3
1633    3
1654    1
1680    3
1702    3
1717    3
1737    3
1756    3
1776    3
1792    3
Name: FTR, dtype: object
2.8
28
16.1
Ath Madrid - visitante
1619    3
1639    3
1653    1
1678    3
1709    1
1715    1
1739    3
1750    0
1773    3
1795    0
Name: FTR, dtype: object
1.8
Malaga - local
1619    0
1638    0
1661    0
1673    3
1698    0
1721    0
1759    1
1777    3
1799    3
1813    3
Name: FTR, dtype: object
1.3
16
16.0
Barcelona - visitante
1615    3
1634    0
1665    3
1691    3
1704    1
1713    3
1732    1
1757    3
1772    1
1791    3
Name: FTR, dtype: object
2.1
Espanol - local
1620    3
1640    3
1664    3
1692    0
1703    3
1718    3
1740    1
1751    3
1778    3
1793    1
Name: FTR, dtype: object
2.3
22
11.8
Alaves - visitante
1614    0
1638    3
1656    0
1681    3
1694    3
1726    0
1735    1
1752    1
1771    3
1796    3
Name: FTR, dtype: object
1.7
Villarreal - local
1616    0
1647    3
1662    0
1684    1
1706    3
1716    0
1732    1
1750    3
1771    0
1790    3
Name: FTR, dtype: object
1.4
15
14.0
Ath Bilbao - visitante
1618    3
1632    3
1652    0
1674    0
1699    0
1727    1
1754    0
1770    0
1793    1
1812    0
Name: FTR, dtype: object
0.8
Valencia - local
1612    3
1636    1
1659    3
1672    3
1674    3
1697    0
1722    3
1761    1
1781    1
1815    0
Name: FTR, dtype: object
1.8
16
12.0
Celta - visitante
1623    3
1650    0
1663    1
1687    0
1707    3
1711    0
1741    0
1763    1
1786    0
1801    1
Name: FTR, dtype: object
0.9
Eibar - local
1626    1
1649    0
1668    3
1683    3
1708    3
1713    0
1739    0
1752    1
1779    3
1786    3
Name: FTR, dtype: object
1.7
16
13.8
Las Palmas - visitante
1611    0
1640    0
1654    1
1673    0
1693    0
1729    0
1748    0
1765    1
1789    0
1810    0
Name: FTR, dtype: object
0.2
Sp Gijon - local
1621    3
1643    0
1663    1
1678    0
1694    0
1723    0
1745    0
1762    3
1782    0
1805    1
Name: FTR, dtype: object
0.8
15
11.9
Malaga - visitante
1622    1
1646    0
1668    0
1684    1
1710    1
1717    0
1733    0
1746    0
1761    1
1787    1
Name: FTR, dtype: object
0.5
Leganes - local
1622    1
1648    3
1667    3
1685    0
1707    0
1727    1
1742    1
1766    1
1780    3
1809    0
Name: FTR, dtype: object
1.3
8
10.8
Real Madrid - visitante
1628    3
1649    3
1662    3
1672    0
1688    3
1724    0
1768    1
1788    3
1808    3
1826    3
Name: FTR, dtype: object
2.2
La Coruna - local
1623    0
1634    3
1641    1
1653    1
1681    0
1728    1
1743    3
1760    3
1785    0
1800    1
Name: FTR, dtype: object
1.3
14
12.3
Granada - visitante
1621    0
1648    0
1666    0
1683    0
1706    0
1718    0
1737    0
1759    1
1774    0
1781    1
Name: FTR, dtype: object
0.2
Barcelona - local
1624    3
1650    3
1658    3
1677    3
1699    3
1729    3
1744    3
1768    1
1787    1
1806    3
Name: FTR, dtype: object
2.6
31
19.1
Sevilla - visitante
1625    0
1642    1
1669    3
1686    3
1703    0
1712    3
1736    3
1753    3
1767    0
1785    3
Name: FTR, dtype: object
1.9
Alaves - local
1629    3
1642    1
1670    3
1691    0
1709    1
1719    1
1749    3
1765    1
1784    0
1808    0
Name: FTR, dtype: object
1.3
9
11.4
Osasuna - visitante
1627    0
1644    0
1664    0
1676    0
1695    0
1725    1
1743    0
1762    0
1780    0
1804    1
Name: FTR, dtype: object
0.2
Betis - local
1627    3
1651    0
1669    0
1689    1
1704    1
1714    1
1734    3
1754    3
1763    1
1789    3
Name: FTR, dtype: object
1.6
14
13.3
Villarreal - visitante
1630    0
1635    3
1655    3
1675    3
1696    1
1728    1
1745    3
1766    1
1783    0
1802    0

Name: FTR, dtype: object
1.5
Ath Madrid - local
1625    3
1645    3
1665    0
1687    3
1700    3
1730    3
1748    3
1769    1
1788    0
1807    3
Name: FTR, dtype: object
2.2
18
13.8
Sociedad - visitante
1629    0
1651    3
1671    3
1692    3
1702    0
1721    3
1747    3
1760    0
1782    3
1809    3
Name: FTR, dtype: object
2.1
Ath Bilbao - local
1628    0
1646    3
1666    3
1690    3
1705    3
1715    1
1735    1
1741    3
1764    3
1783    3
Name: FTR, dtype: object
2.3
17
12.2
Espanol - visitante
1626    1
1647    0
1657    1
1680    0
1698    3
1722    0
1744    0
1769    1
1784    3
1803    3
Name: FTR, dtype: object
1.2
Celta - local
1635    0
1657    1
1676    3
1726    3
1733    3
1753    0
1774    3
1794    3
1814    3
1834    3
Name: FTR, dtype: object
2.2
22
11.0
Las Palmas - visitante
1640    0
1654    1
1673    0
1693    0
1729    0
1748    0
1765    1
1789    0
1810    0
1836    1
Name: FTR, dtype: object
0.3
Valencia - local
1636    1
1659    3
1672    3
1674    3
1697    0
1722    3
1761    1
1781    1
1815    0
1830    0
Name: FTR, dtype: object
1.5
13
12.0
La Coruna - visitante
1643    3
1667    0
1690    0
1708    0
1720    1
1740    1
1756    0
1777    0
1798    1
1814    0
Name: FTR, dtype: object
0.6
Sevilla - local
1637    1
1652    3
1679    3
1696    1
1724    3
1746    3
1775    3
1791    0
1811    3
1835    3
Name: FTR, dtype: object
2.3
16
12.2
Sp Gijon - visitante
1636    1
1658    0
1685    3
1705    0
1714    1
1738    0
1751    0
1776    0
1799    0
1817    1
Name: FTR, dtype: object
0.6
Real Madrid - local
1633    3
1654    1
1680    3
1702    3
1717    3
1737    3
1756    3
1776    3
1792    3
1812    3
Name: FTR, dtype: object
2.8
27
16.7
Alaves - visitante
1638    3
1656    0
1681    3
1694    3
1726    0
1735    1
1752    1
1771    3
1796    3
1816    0
Name: FTR, dtype: object
1.7
Granada - local
1639    0
1656    3
1682    3
1693    3
1725    1
1747    0
1767    3
1798    1
1817    1
1838    0
Name: FTR, dtype: object
1.5
11
11.0
Barcelona - visitante
1634    0
1665    3
1691    3
1704    1
1713    3
1732    1
1757    3
1772    1
1791    3
1815    3
Name: FTR, dtype: object
2.1
Villarreal - local
1647    3
1662    0
1684    1
1706    3
1716    0
1732    1
1750    3
1771    0
1790    3
1810    3
Name: FTR, dtype: object
1.7
15
13.9
Eibar - visitante
1631    1
1660    1
1679    0
1697    3
1723    3
1742    1
1764    0
1797    0
1818    1
1831    1
Name: FTR, dtype: object
1.1
Sociedad - local
1632    0
1660    1
1675    0
1695    3
1711    3
1736    0
1755    3
1772    1
1795    3
1816    3
Name: FTR, dtype: object
1.7
15
14.6
Leganes - visitante
1637    1
1659    0
1677    0
1700    0
1719    1
1734    0
1758    1
1778    0
1792    0
1813    0
Name: FTR, dtype: object
0.3
Osasuna - local
1631    1
1655    0
1688    0
1710    1
1712    0
1731    1
1757    0
1773    0
1796    0
1819    0
Name: FTR, dtype: object
0.3
11
12.6
Ath Bilbao - visitante
1632    3
1652    0
1674    0
1699    0
1727    1
1754    0
1770    0
1793    1
1812    0
1832    0
Name: FTR, dtype: object
0.5
Malaga - local
1638    0
1661    0
1673    3
1698    0
1721    0
1759    1
1777    3
1799    3
1813    3
1832    3
Name: FTR, dtype: object
1.6
18
15.4
Ath Madrid - visitante
1639    3
1653    1
1678    3
1709    1
1715    1
1739    3
1750    0
1773    3
1795    0
1811    0
Name: FTR, dtype: object
1.5
Espanol - local
1640    3
1664    3
1692    0
1703    3
1718    3
1740    1
1751    3
1778    3
1793    1
1818    1
Name: FTR, dtype: object
2.1
23
12.1
Betis - visitante
1633    0
1641    1
1661    3
1682    0
1730    0
1749    0
1779    0
1790    0
1819    3
1839    0
Name: FTR, dtype: object
0.7
Sp Gijon - local
1643    0
1663    1
1678    0
1694    0
1723    0
1745    0
1762    3
1782    0
1805    1
1822    0
Name: FTR, dtype: object
0.5
13
11.4
Granada - visitante
1648    0
1666    0
1683    0
1706    0
1718    0
1737    0
1759    1
1774    0
1781    1
1806    0
Name: FTR, dtype: object
0.2
Leganes - local
1648    3
1667    3
1685    0
1707    0
1727    1
1742    1
1766    1
1780    3
1809    0
1825    0
Name: FTR, dtype: object
1.2
10
11.3
Malaga - visitante
1646    0
1668    0
1684    1
1710    1
1717    0
1733    0
1746    0
1761    1
1787    1
1807    0
Name: FTR, dtype: object
0.4
La Coruna - local
1634    3
1641    1
1653    1
1681    0
1728    1
1743    3
1760    3
1785    0
1800    1
1837    3
Name: FTR, dtype: object
1.6
16
13.5
Celta - visitante
1650    0
1663    1
1687    0
1707    3
1711    0
1741    0
1763    1
1786    0
1801    1
1821    0
Name: FTR, dtype: object
0.6
Barcelona - local
1650    3
1658    3
1677    3
1699    3
1729    3
1744    3
1768    1
1787    1
1806    3
1827    3
Name: FTR, dtype: object
2.6
31
18.8
Valencia - visitante
1645    0
1670    0
1689    1
1701    0
1716    3
1731    1
1755    0
1775    0
1794    0
1800    1
Name: FTR, dtype: object
0.6
Ath Madrid - local
1645    3
1665    0
1687    3
1700    3
1730    3
1748    3
1769    1
1788    0
1807    3
1828    3
Name: FTR, dtype: object
2.2
22
14.0
Sevilla - visitante
1642    1
1669    3
1686    3
1703    0
1712    3
1736    3
1753    3
1767    0
1785    3
1805    1
Name: FTR, dtype: object
2.0
Eibar - local
1649    0
1668    3
1683    3
1708    3
1713    0
1739    0
1752    1
1779    3
1786    3
1802    3
Name: FTR, dtype: object
1.9
17
13.5
Espanol - visitante
1647    0
1657    1
1680    0
1698    3
1722    0
1744    0
1769    1
1784    3
1803    3
1829    1
Name: FTR, dtype: object
1.2
Betis - local
1651    0
1669    0
1689    1
1704    1
1714    1
1734    3
1754    3
1763    1
1789    3
1803    0
Name: FTR, dtype: object
1.3
12
13.7
Osasuna - visitante
1644    0
1664    0
1676    0
1695    0
1725    1
1743    0
1762    0
1780    0
1804    1
1820    3
Name: FTR, dtype: object
0.5
Ath Bilbao - local
1646    3
1666    3
1690    3
1705    3
1715    1
1735    1
1741    3
1764    3
1783    3
1804    1
Name: FTR, dtype: object
2.4
17
12.8
Real Madrid - visitante
1649    3
1662    3
1672    0
1688    3
1724    0
1768    1
1788    3
1808    3
1826    3
1846    1
Name: FTR, dtype: object
2.0
Alaves - local
1642    1
1670    3
1691    0
1709    1
1719    1
1749    3
1765    1
1784    0
1808    0
1824    1
Name: FTR, dtype: object
1.1
9
11.2
Sociedad - visitante
1651    3
1671    3
1692    3
1702    0
1721    3
1747    3
1760    0
1782    3
1809    3
1823    0
Name: FTR, dtype: object
2.1
Las Palmas - local
1644    3
1671    0
1686    0
1701    3
1720    1
1738    3
1758    1
1770    3
1797    3
1801    1
Name: FTR, dtype: object
1.8
18
13.1
Villarreal - visitante
1635    3
1655    3
1675    3
1696    1
1728    1
1745    3
1766    1
1783    0
1802    0
1833    1
Name: FTR, dtype: object
1.6
Osasuna - local
1655    0
1688    0
1710    1
1712    0
1731    1
1757    0
1773    0
1796    0
1819    0
1836    1
Name: FTR, dtype: object
0.3
12
12.1
Eibar - visitante
1660    1
1679    0
1697    3
1723    3
1742    1
1764    0
1797    0
1818    1
1831    1
1859    0
Name: FTR, dtype: object
1.0
Sociedad - local
1660    1
1675    0
1695    3
1711    3
1736    0
1755    3
1772    1
1795    3
1816    3
1839    3
Name: FTR, dtype: object
2.0
16
14.6
Ath Bilbao - visitante
1652    0
1674    0
1699    0
1727    1
1754    0
1770    0
1793    1
1812    0
1832    0
1855    3
Name: FTR, dtype: object
0.5
Real Madrid - local
1654    1
1680    3
1702    3
1717    3
1737    3
1756    3
1776    3
1792    3
1812    3
1831    1
Name: FTR, dtype: object
2.6
26
16.8
Betis - visitante
1641    1
1661    3
1682    0
1730    0
1749    0
1779    0
1790    0
1819    3
1839    0
1858    0
Name: FTR, dtype: object
0.7
La Coruna - local
1641    1
1653    1
1681    0
1728    1
1743    3
1760    3
1785    0
1800    1
1837    3
1852    0
Name: FTR, dtype: object
1.3
15
13.3
Barcelona - visitante
1665    3
1691    3
1704    1
1713    3
1732    1
1757    3
1772    1
1791    3
1815    3
1834    0
Name: FTR, dtype: object
2.1
Celta - local
1657    1
1676    3
1726    3
1733    3
1753    0
1774    3
1794    3
1814    3
1834    3
1856    3
Name: FTR, dtype: object
2.5
24
11.4
Villarreal - visitante
1655    3
1675    3
1696    1
1728    1
1745    3
1766    1
1783    0
1802    0
1833    1
1854    1
Name: FTR, dtype: object
1.4
Valencia - local
1659    3
1672    3
1674    3
1697    0
1722    3
1761    1
1781    1
1815    0
1830    0
1850    3
Name: FTR, dtype: object
1.7
14
11.2
Sp Gijon - visitante
1658    0
1685    3
1705    0
1714    1
1738    0
1751    0
1776    0
1799    0
1817    1
1837    0
Name: FTR, dtype: object
0.5
Sevilla - local
1652    3
1679    3
1696    1
1724    3
1746    3
1775    3
1791    0
1811    3
1835    3
1858    3
Name: FTR, dtype: object
2.5
16
12.2
Leganes - visitante
1659    0
1677    0
1700    0
1719    1
1734    0
1758    1
1778    0
1792    0
1813    0
1838    3
Name: FTR, dtype: object
0.5
Malaga - local
1661    0
1673    3
1698    0
1721    0
1759    1
1777    3
1799    3
1813    3
1832    3
1859    3
Name: FTR, dtype: object
1.9
19
15.3
Alaves - visitante
1656    0
1681    3
1694    3
1726    0
1735    1
1752    1
1771    3
1796    3
1816    0
1835    0
Name: FTR, dtype: object
1.4
Granada - local
1656    3
1682    3
1693    3
1725    1
1747    0
1767    3
1798    1
1817    1
1838    0
1855    0
Name: FTR, dtype: object
1.5
12
11.1
Ath Madrid - visitante
1653    1
1678    3
1709    1
1715    1
1739    3
1750    0
1773    3
1795    0
1811    0
1830    3
Name: FTR, dtype: object
1.5
Espanol - local
1664    3
1692    0
1703    3
1718    3
1740    1
1751    3
1778    3
1793    1
1818    1
1833    1
Name: FTR, dtype: object
1.9
19
11.8
Las Palmas - visitante
1654    1
1673    0
1693    0
1729    0
1748    0
1765    1
1789    0
1810    0
1836    1
1853    0
Name: FTR, dtype: object
0.3
La Coruna - local
1653    1
1681    0
1728    1
1743    3
1760    3
1785    0
1800    1
1837    3
1852    0
1872    0
Name: FTR, dtype: object
1.2
14
13.4
Betis - visitante
1661    3
1682    0
1730    0
1749    0
1779    0
1790    0
1819    3
1839    0
1858    0
1870    3
Name: FTR, dtype: object
0.9
Alaves - local
1670    3
1691    0
1709    1
1719    1
1749    3
1765    1
1784    0
1808    0
1824    1
1840    3
Name: FTR, dtype: object
1.3
11
11.0
Sevilla - visitante
1669    3
1686    3
1703    0
1712    3
1736    3
1753    3
1767    0
1785    3
1805    1
1825    3
Name: FTR, dtype: object
2.2
Sp Gijon - local
1663    1
1678    0
1694    0
1723    0
1745    0
1762    3
1782    0
1805    1
1822    0
1845    0
Name: FTR, dtype: object
0.5
13
11.5
La Coruna - visitante
1667    0
1690    0
1708    0
1720    1
1740    1
1756    0
1777    0
1798    1
1814    0
1827    0
Name: FTR, dtype: object
0.3
Las Palmas - local
1671    0
1686    0
1701    3
1720    1
1738    3
1758    1
1770    3
1797    3
1801    1
1829    1
Name: FTR, dtype: object
1.6
13
12.8
Osasuna - visitante
1664    0
1676    0
1695    0
1725    1
1743    0
1762    0
1780    0
1804    1
1820    3
1841    0
Name: FTR, dtype: object
0.5

Ath Madrid - local
1665    0
1687    3
1700    3
1730    3
1748    3
1769    1
1788    0
1807    3
1828    3
1844    3
Name: FTR, dtype: object
2.2
20
14.3
Valencia - visitante
1670    0
1689    1
1701    0
1716    3
1731    1
1755    0
1775    0
1794    0
1800    1
1822    3
Name: FTR, dtype: object
0.9
Ath Bilbao - local
1666    3
1690    3
1705    3
1715    1
1735    1
1741    3
1764    3
1783    3
1804    1
1823    3
Name: FTR, dtype: object
2.4
19
12.8
Malaga - visitante
1668    0
1684    1
1710    1
1717    0
1733    0
1746    0
1761    1
1787    1
1807    0
1824    1
Name: FTR, dtype: object
0.5
Villarreal - local
1662    0
1684    1
1706    3
1716    0
1732    1
1750    3
1771    0
1790    3
1810    3
1821    3
Name: FTR, dtype: object
1.7
18
13.9
Espanol - visitante
1657    1
1680    0
1698    3
1722    0
1744    0
1769    1
1784    3
1803    3
1829    1
1851    3
Name: FTR, dtype: object
1.5
Leganes - local
1667    3
1685    0
1707    0
1727    1
1742    1
1766    1
1780    3
1809    0
1825    0
1842    0
Name: FTR, dtype: object
0.9
10
10.4
Granada - visitante
1666    0
1683    0
1706    0
1718    0
1737    0
1759    1
1774    0
1781    1
1806    0
1828    0
Name: FTR, dtype: object
0.2
Eibar - local
1668    3
1683    3
1708    3
1713    0
1739    0
1752    1
1779    3
1786    3
1802    3
1820    0
Name: FTR, dtype: object
1.9
18
13.6
Real Madrid - visitante
1662    3
1672    0
1688    3
1724    0
1768    1
1788    3
1808    3
1826    3
1846    1
1863    3
Name: FTR, dtype: object
2.0
Barcelona - local
1658    3
1677    3
1699    3
1729    3
1744    3
1768    1
1787    1
1806    3
1827    3
1857    1
Name: FTR, dtype: object
2.4
27
18.8
Celta - visitante
1663    1
1687    0
1707    3
1711    0
1741    0
1763    1
1786    0
1801    1
1821    0
1843    3
Name: FTR, dtype: object
0.9
Betis - local
1669    0
1689    1
1704    1
1714    1
1734    3
1754    3
1763    1
1789    3
1803    0
1826    0
Name: FTR, dtype: object
1.3
11
13.8
Sociedad - visitante
1671    3
1692    3
1702    0
1721    3
1747    3
1760    0
1782    3
1809    3
1823    0
1847    0
Name: FTR, dtype: object
1.8
Sevilla - local
1679    3
1696    1
1724    3
1746    3
1775    3
1791    0
1811    3
1835    3
1858    3
1874    3
Name: FTR, dtype: object
2.5
17
12.4
Ath Bilbao - visitante
1674    0
1699    0
1727    1
1754    0
1770    0
1793    1
1812    0
1832    0
1855    3
1872    3
Name: FTR, dtype: object
0.8
La Coruna - local
1681    0
1728    1
1743    3
1760    3
1785    0
1800    1
1837    3
1852    0
1872    0
1899    3
Name: FTR, dtype: object
1.4
15
13.2
Ath Madrid - visitante
1678    3
1709    1
1715    1
1739    3
1750    0
1773    3
1795    0
1811    0
1830    3
1857    1
Name: FTR, dtype: object
1.5
Real Madrid - local
1680    3
1702    3
1717    3
1737    3
1756    3
1776    3
1792    3
1812    3
1831    1
1854    1
Name: FTR, dtype: object
2.6
24
17.0
Las Palmas - visitante
1673    0
1693    0
1729    0
1748    0
1765    1
1789    0
1810    0
1836    1
1853    0
1874    0
Name: FTR, dtype: object
0.2
Osasuna - local
1688    0
1710    1
1712    0
1731    1
1757    0
1773    0
1796    0
1819    0
1836    1
1851    0
Name: FTR, dtype: object
0.3
12
12.1
Villarreal - visitante
1675    3
1696    1
1728    1
1745    3
1766    1
1783    0
1802    0
1833    1
1854    1
1876    3
Name: FTR, dtype: object
1.4
Granada - local
1682    3
1693    3
1725    1
1747    0
1767    3
1798    1
1817    1
1838    0
1855    0
1873    0
Name: FTR, dtype: object
1.2
11
11.3
Alaves - visitante
1681    3
1694    3
1726    0
1735    1
1752    1
1771    3
1796    3
1816    0
1835    0
1850    0
Name: FTR, dtype: object
1.4
Celta - local
1676    3
1726    3
1733    3
1753    0
1774    3
1794    3
1814    3
1834    3
1856    3
1877    0
Name: FTR, dtype: object
2.4
22
11.5
Espanol - visitante
1680    0
1698    3
1722    0
1744    0
1769    1
1784    3
1803    3
1829    1
1851    3
1879    1
Name: FTR, dtype: object
1.5
Barcelona - local
1677    3
1699    3
1729    3
1744    3
1768    1
1787    1
1806    3
1827    3
1857    1
1878    0
Name: FTR, dtype: object
2.1
22
17.9
Sp Gijon - visitante
1685    3
1705    0
1714    1
1738    0
1751    0
1776    0
1799    0
1817    1
1837    0
1856    0
Name: FTR, dtype: object
0.5
Valencia - local
1672    3
1674    3
1697    0
1722    3
1761    1
1781    1
1815    0
1830    0
1850    3
1870    0
Name: FTR, dtype: object
1.4
15
11.9
Leganes - visitante
1677    0
1700    0
1719    1
1734    0
1758    1
1778    0
1792    0
1813    0
1838    3
1852    3
Name: FTR, dtype: object
0.8
Sociedad - local
1675    0
1695    3
1711    3
1736    0
1755    3
1772    1
1795    3
1816    3
1839    3
1853    3
Name: FTR, dtype: object
2.2
18
14.9
Eibar - visitante
1679    0
1697    3
1723    3
1742    1
1764    0
1797    0
1818    1
1831    1
1859    0
1873    3
Name: FTR, dtype: object
1.2
Malaga - local
1673    3
1698    0
1721    0
1759    1
1777    3
1799    3
1813    3
1832    3
1859    3
1876    0
Name: FTR, dtype: object
1.9
18
15.3
Betis - visitante
1682    0
1730    0
1749    0
1779    0
1790    0
1819    3
1839    0
1858    0
1870    3
1897    0
Name: FTR, dtype: object
0.6
Villarreal - local
1684    1
1706    3
1716    0
1732    1
1750    3
1771    0
1790    3
1810    3
1821    3
1841    3
Name: FTR, dtype: object
2.0
19
14.0
Real Madrid - visitante
1672    0
1688    3
1724    0
1768    1
1788    3
1808    3
1826    3
1846    1
1863    3
1893    3
Name: FTR, dtype: object
2.0
Sp Gijon - local
1678    0
1694    0
1723    0
1745    0
1762    3
1782    0
1805    1
1822    0
1845    0
1871    3
Name: FTR, dtype: object
0.7
14
10.2
Celta - visitante
1687    0
1707    3
1711    0
1741    0
1763    1
1786    0
1801    1
1821    0
1843    3
1862    1
Name: FTR, dtype: object
0.9
Espanol - local
1692    0
1703    3
1718    3
1740    1
1751    3
1778    3
1793    1
1818    1
1833    1
1843    0
Name: FTR, dtype: object
1.6
16
11.0
Osasuna - visitante
1676    0
1695    0
1725    1
1743    0
1762    0
1780    0
1804    1
1820    3
1841    0
1875    0
Name: FTR, dtype: object
0.5
Ath Madrid - local
1687    3
1700    3
1730    3
1748    3
1769    1
1788    0
1807    3
1828    3
1844    3
1868    3
Name: FTR, dtype: object
2.5
24
14.9
Barcelona - visitante
1691    3
1704    1
1713    3
1732    1
1757    3
1772    1
1791    3
1815    3
1834    0
1845    3
Name: FTR, dtype: object
2.1
Ath Bilbao - local
1690    3
1705    3
1715    1
1735    1
1741    3
1764    3
1783    3
1804    1
1823    3
1848    3
Name: FTR, dtype: object
2.4
19
12.8
Granada - visitante
1683    0
1706    0
1718    0
1737    0
1759    1
1774    0
1781    1
1806    0
1828    0
1840    0
Name: FTR, dtype: object
0.2
Leganes - local
1685    0
1707    0
1727    1
1742    1
1766    1
1780    3
1809    0
1825    0
1842    0
1865    0
Name: FTR, dtype: object
0.6
7
11.2
La Coruna - visitante
1690    0
1708    0
1720    1
1740    1
1756    0
1777    0
1798    1
1814    0
1827    0
1844    0
Name: FTR, dtype: object
0.3
Eibar - local
1683    3
1708    3
1713    0
1739    0
1752    1
1779    3
1786    3
1802    3
1820    0
1847    3
Name: FTR, dtype: object
1.9
17
14.5
Malaga - visitante
1684    1
1710    1
1717    0
1733    0
1746    0
1761    1
1787    1
1807    0
1824    1
1849    0
Name: FTR, dtype: object
0.5
Betis - local
1689    1
1704    1
1714    1
1734    3
1754    3
1763    1
1789    3
1803    0
1826    0
1849    3
Name: FTR, dtype: object
1.6
11
13.4
Sevilla - visitante
1686    3
1703    0
1712    3
1736    3
1753    3
1767    0
1785    3
1805    1
1825    3
1848    0
Name: FTR, dtype: object
1.9
Alaves - local
1691    0
1709    1
1719    1
1749    3
1765    1
1784    0
1808    0
1824    1
1840    3
1860    1
Name: FTR, dtype: object
1.1
9
10.6
Valencia - visitante
1689    1
1701    0
1716    3
1731    1
1755    0
1775    0
1794    0
1800    1
1822    3
1842    3
Name: FTR, dtype: object
1.2
Las Palmas - local
1686    0
1701    3
1720    1
1738    3
1758    1
1770    3
1797    3
1801    1
1829    1
1846    1
Name: FTR, dtype: object
1.7
15
11.8
Sociedad - visitante
1692    3
1702    0
1721    3
1747    3
1760    0
1782    3
1809    3
1823    0
1847    0
1861    0
Name: FTR, dtype: object
1.5
Valencia - local
1674    3
1697    0
1722    3
1761    1
1781    1
1815    0
1830    0
1850    3
1870    0
1890    0
Name: FTR, dtype: object
1.1
15
12.8
Real Madrid - visitante
1688    3
1724    0
1768    1
1788    3
1808    3
1826    3
1846    1
1863    3
1893    3
1905    3
Name: FTR, dtype: object
2.3
Malaga - local
1698    0
1721    0
1759    1
1777    3
1799    3
1813    3
1832    3
1859    3
1876    0
1898    1
Name: FTR, dtype: object
1.7
17
15.4
Las Palmas - visitante
1693    0
1729    0
1748    0
1765    1
1789    0
1810    0
1836    1
1853    0
1874    0
1890    3
Name: FTR, dtype: object
0.5
Valencia - local
1697    0
1722    3
1761    1
1781    1
1815    0
1830    0
1850    3
1870    0
1890    0
1909    0
Name: FTR, dtype: object
0.8
13
12.1
Ath Bilbao - visitante
1699    0
1727    1
1754    0
1770    0
1793    1
1812    0
1832    0
1855    3
1872    3
1892    0
Name: FTR, dtype: object
0.8
Sociedad - local
1695    3
1711    3
1736    0
1755    3
1772    1
1795    3
1816    3
1839    3
1853    3
1879    1
Name: FTR, dtype: object
2.3
19
14.2
Villarreal - visitante
1696    1
1728    1
1745    3
1766    1
1783    0
1802    0
1833    1
1854    1
1876    3
1896    1
Name: FTR, dtype: object
1.2
Celta - local
1726    3
1733    3
1753    0
1774    3
1794    3
1814    3
1834    3
1856    3
1877    0
1891    0
Name: FTR, dtype: object
2.1
19
11.4
Osasuna - visitante
1695    0
1725    1
1743    0
1762    0
1780    0
1804    1
1820    3
1841    0
1875    0
1898    1
Name: FTR, dtype: object
0.6
Barcelona - local
1699    3
1729    3
1744    3
1768    1
1787    1
1806    3
1827    3
1857    1
1878    0
1897    3
Name: FTR, dtype: object
2.1
26
19.6
Leganes - visitante
1700    0
1719    1
1734    0
1758    1
1778    0
1792    0
1813    0
1838    3
1852    3
1871    0
Name: FTR, dtype: object
0.8
Sp Gijon - local
1694    0
1723    0
1745    0
1762    3
1782    0
1805    1
1822    0
1845    0
1871    3
1892    3
Name: FTR, dtype: object
1.0
15
9.9
Ath Madrid - visitante
1709    1
1715    1
1739    3
1750    0
1773    3
1795    0
1811    0
1830    3
1857    1
1877    3
Name: FTR, dtype: object
1.5
Sevilla - local
1696    1
1724    3
1746    3
1775    3
1791    0
1811    3
1835    3
1858    3
1874    3
1895    3
Name: FTR, dtype: object
2.5
21
12.9

Eibar - visitante
1697    3
1723    3
1742    1
1764    0
1797    0
1818    1
1831    1
1859    0
1873    3
1899    0
Name: FTR, dtype: object
1.2
Real Madrid - local
1702    3
1717    3
1737    3
1756    3
1776    3
1792    3
1812    3
1831    1
1854    1
1875    3
Name: FTR, dtype: object
2.6
27
18.3
Espanol - visitante
1698    3
1722    0
1744    0
1769    1
1784    3
1803    3
1829    1
1851    3
1879    1
1895    0
Name: FTR, dtype: object
1.5
La Coruna - local
1728    1
1743    3
1760    3
1785    0
1800    1
1837    3
1852    0
1872    0
1899    3
1905    0
Name: FTR, dtype: object
1.4
15
12.6
Alaves - visitante
1694    3
1726    0
1735    1
1752    1
1771    3
1796    3
1816    0
1835    0
1850    0
1878    3
Name: FTR, dtype: object
1.4
Granada - local
1693    3
1725    1
1747    0
1767    3
1798    1
1817    1
1838    0
1855    0
1873    0
1896    1
Name: FTR, dtype: object
1.0
8
11.0
Betis - visitante
1730    0
1749    0
1779    0
1790    0
1819    3
1839    0
1858    0
1870    3
1897    0
1917    1
Name: FTR, dtype: object
0.7
Eibar - local
1708    3
1713    0
1739    0
1752    1
1779    3
1786    3
1802    3
1820    0
1847    3
1867    1
Name: FTR, dtype: object
1.7
14
13.0
Granada - visitante
1706    0
1718    0
1737    0
1759    1
1774    0
1781    1
1806    0
1828    0
1840    0
1869    1
Name: FTR, dtype: object
0.3
Villarreal - local
1706    3
1716    0
1732    1
1750    3
1771    0
1790    3
1810    3
1821    3
1841    3
1861    3
Name: FTR, dtype: object
2.2
20
13.7
Malaga - visitante
1710    1
1717    0
1733    0
1746    0
1761    1
1787    1
1807    0
1824    1
1849    0
1866    0
Name: FTR, dtype: object
0.4
Leganes - local
1707    0
1727    1
1742    1
1766    1
1780    3
1809    0
1825    0
1842    0
1865    0
1886    1
Name: FTR, dtype: object
0.7
7
10.9
Sp Gijon - visitante
1705    0
1714    1
1738    0
1751    0
1776    0
1799    0
1817    1
1837    0
1856    0
1868    0
Name: FTR, dtype: object
0.2
Las Palmas - local
1701    3
1720    1
1738    3
1758    1
1770    3
1797    3
1801    1
1829    1
1846    1
1866    3
Name: FTR, dtype: object
2.0
16
10.9
Sevilla - visitante
1703    0
1712    3
1736    3
1753    3
1767    0
1785    3
1805    1
1825    3
1848    0
1867    1
Name: FTR, dtype: object
1.7
Ath Madrid - local
1700    3
1730    3
1748    3
1769    1
1788    0
1807    3
1828    3
1844    3
1868    3
1894    1
Name: FTR, dtype: object
2.3
22
16.0
Celta - visitante
1707    3
1711    0
1741    0
1763    1
1786    0
1801    1
1821    0
1843    3
1862    1
1884    0
Name: FTR, dtype: object
0.9
Osasuna - local
1710    1
1712    0
1731    1
1757    0
1773    0
1796    0
1819    0
1836    1
1851    0
1862    1
Name: FTR, dtype: object
0.4
11
11.9
Real Madrid - visitante
1724    0
1768    1
1788    3
1808    3
1826    3
1846    1
1863    3
1893    3
1905    3
1925    3
Name: FTR, dtype: object
2.3
Betis - local
1704    1
1714    1
1734    3
1754    3
1763    1
1789    3
1803    0
1826    0
1849    3
1869    1
Name: FTR, dtype: object
1.6
13
14.1
Valencia - visitante
1701    0
1716    3
1731    1
1755    0
1775    0
1794    0
1800    1
1822    3
1842    3
1864    0
Name: FTR, dtype: object
1.1
Ath Bilbao - local
1705    3
1715    1
1735    1
1741    3
1764    3
1783    3
1804    1
1823    3
1848    3
1864    3
Name: FTR, dtype: object
2.4
19
12.8
La Coruna - visitante
1708    0
1720    1
1740    1
1756    0
1777    0
1798    1
1814    0
1827    0
1844    0
1860    1
Name: FTR, dtype: object
0.4
Alaves - local
1709    1
1719    1
1749    3
1765    1
1784    0
1808    0
1824    1
1840    3
1860    1
1883    1
Name: FTR, dtype: object
1.2
9
11.0
Barcelona - visitante
1704    1
1713    3
1732    1
1757    3
1772    1
1791    3
1815    3
1834    0
1845    3
1865    3
Name: FTR, dtype: object
2.1
Espanol - local
1703    3
1718    3
1740    1
1751    3
1778    3
1793    1
1818    1
1833    1
1843    0
1863    0
Name: FTR, dtype: object
1.6
15
11.4
Sociedad - visitante
1702    0
1721    3
1747    3
1760    0
1782    3
1809    3
1823    0
1847    0
1861    0
1885    3
Name: FTR, dtype: object
1.5
Granada - local
1725    1
1747    0
1767    3
1798    1
1817    1
1838    0
1855    0
1873    0
1896    1
1906    0
Name: FTR, dtype: object
0.7
7
10.6
Las Palmas - visitante
1729    0
1748    0
1765    1
1789    0
1810    0
1836    1
1853    0
1874    0
1890    3
1902    0
Name: FTR, dtype: object
0.5
Sp Gijon - local
1723    0
1745    0
1762    3
1782    0
1805    1
1822    0
1845    0
1871    3
1892    3
1901    3
Name: FTR, dtype: object
1.3
15
10.3
Alaves - visitante
1726    0
1735    1
1752    1
1771    3
1796    3
1816    0
1835    0
1850    0
1878    3
1894    1
Name: FTR, dtype: object
1.2
Sociedad - local
1711    3
1736    0
1755    3
1772    1
1795    3
1816    3
1839    3
1853    3
1879    1
1893    0
Name: FTR, dtype: object
2.0
16
13.7
Osasuna - visitante
1725    1
1743    0
1762    0
1780    0
1804    1
1820    3
1841    0
1875    0
1898    1
2672    1
Name: FTR, dtype: object
0.7
Sevilla - local
1724    3
1746    3
1775    3
1791    0
1811    3
1835    3
1858    3
1874    3
1895    3
1912    0
Name: FTR, dtype: object
2.4
22
12.7
Villarreal - visitante
1728    1
1745    3
1766    1
1783    0
1802    0
1833    1
1854    1
1876    3
1896    1
1901    0
Name: FTR, dtype: object
1.1
Valencia - local
1722    3
1761    1
1781    1
1815    0
1830    0
1850    3
1870    0
1890    0
1909    0
1921    0
Name: FTR, dtype: object
0.8
13
12.0
Eibar - visitante
1723    3
1742    1
1764    0
1797    0
1818    1
1831    1
1859    0
1873    3
1899    0
1903    0
Name: FTR, dtype: object
0.9
Malaga - local
1721    0
1759    1
1777    3
1799    3
1813    3
1832    3
1859    3
1876    0
1898    1
1902    3
Name: FTR, dtype: object
2.0
21
14.9
Espanol - visitante
1722    0
1744    0
1769    1
1784    3
1803    3
1829    1
1851    3
1879    1
1895    0
1919    0
Name: FTR, dtype: object
1.2
Barcelona - local
1729    3
1744    3
1768    1
1787    1
1806    3
1827    3
1857    1
1878    0
1897    3
1919    3
Name: FTR, dtype: object
2.1
28
19.3
Ath Bilbao - visitante
1727    1
1754    0
1770    0
1793    1
1812    0
1832    0
1855    3
1872    3
1892    0
1915    1
Name: FTR, dtype: object
0.9
Ath Madrid - local
1730    3
1748    3
1769    1
1788    0
1807    3
1828    3
1844    3
1868    3
1894    1
1907    3
Name: FTR, dtype: object
2.3
22
16.0
Leganes - visitante
1719    1
1734    0
1758    1
1778    0
1792    0
1813    0
1838    3
1852    3
1871    0
1891    3
Name: FTR, dtype: object
1.1
Las Palmas - local
1720    1
1738    3
1758    1
1770    3
1797    3
1801    1
1829    1
1846    1
1866    3
1881    3
Name: FTR, dtype: object
2.0
18
11.5
Valencia - visitante
1716    3
1731    1
1755    0
1775    0
1794    0
1800    1
1822    3
1842    3
1864    0
1887    0
Name: FTR, dtype: object
1.1
Real Madrid - local
1717    3
1737    3
1756    3
1776    3
1792    3
1812    3
1831    1
1854    1
1875    3
1884    3
Name: FTR, dtype: object
2.6
26
20.0
Sociedad - visitante
1721    3
1747    3
1760    0
1782    3
1809    3
1823    0
1847    0
1861    0
1885    3
1909    3
Name: FTR, dtype: object
1.8
Espanol - local
1718    3
1740    1
1751    3
1778    3
1793    1
1818    1
1833    1
1843    0
1863    0
1888    1
Name: FTR, dtype: object
1.4
14
10.5
Sevilla - visitante
1712    3
1736    3
1753    3
1767    0
1785    3
1805    1
1825    3
1848    0
1867    1
1880    1
Name: FTR, dtype: object
1.8
Betis - local
1714    1
1734    3
1754    3
1763    1
1789    3
1803    0
1826    0
1849    3
1869    1
1889    1
Name: FTR, dtype: object
1.6
12
13.9
Barcelona - visitante
1713    3
1732    1
1757    3
1772    1
1791    3
1815    3
1834    0
1845    3
1865    3
1882    3
Name: FTR, dtype: object
2.3
Ath Bilbao - local
1715    1
1735    1
1741    3
1764    3
1783    3
1804    1
1823    3
1848    3
1864    3
1882    0
Name: FTR, dtype: object
2.1
17
12.6
Sp Gijon - visitante
1714    1
1738    0
1751    0
1776    0
1799    0
1817    1
1837    0
1856    0
1868    0
1883    1
Name: FTR, dtype: object
0.3
Villarreal - local
1716    0
1732    1
1750    3
1771    0
1790    3
1810    3
1821    3
1841    3
1861    3
1880    1
Name: FTR, dtype: object
2.0
18
13.1
Granada - visitante
1718    0
1737    0
1759    1
1774    0
1781    1
1806    0
1828    0
1840    0
1869    1
1881    0
Name: FTR, dtype: object
0.3
Leganes - local
1727    1
1742    1
1766    1
1780    3
1809    0
1825    0
1842    0
1865    0
1886    1
Name: FTR, dtype: object
0.7777777777777778
7
11.444444444444445
Celta - visitante
1711    0
1741    0
1763    1
1786    0
1801    1
1821    0
1843    3
1862    1
1884    0
1907    0
Name: FTR, dtype: object
0.6
Eibar - local
1713    0
1739    0
1752    1
1779    3
1786    3
1802    3
1820    0
1847    3
1867    1
1887    3
Name: FTR, dtype: object
1.7
12
13.1
La Coruna - visitante
1720    1
1740    1
1756    0
1777    0
1798    1
1814    0
1827    0
1844    0
1860    1
1889    1
Name: FTR, dtype: object
0.5
Alaves - local
1719    1
1749    3
1765    1
1784    0
1808    0
1824    1
1840    3
1860    1
1883    1
Name: FTR, dtype: object
1.2222222222222223
9
10.11111111111111
Ath Madrid - visitante
1715    1
1739    3
1750    0
1773    3
1795    0
1811    0
1830    3
1857    1
1877    3
1886    1
Name: FTR, dtype: object
1.5
Osasuna - local
1712    0
1731    1
1757    0
1773    0
1796    0
1819    0
1836    1
1851    0
1862    1
1885    0
Name: FTR, dtype: object
0.3
10
11.3
Malaga - visitante
1717    0
1733    0
1746    0
1761    1
1787    1
1807    0
1824    1
1849    0
1866    0
1888    1
Name: FTR, dtype: object
0.4
Sociedad - local
1736    0
1755    3
1772    1
1795    3
1816    3
1839    3
1853    3
1879    1
1893    0
1911    3
Name: FTR, dtype: object
2.0
17
13.2
Celta - visitante
1741    0
1763    1
1786    0
1801    1
1821    0
1843    3
1862    1
1884    0
1907    0
1924    0
Name: FTR, dtype: object
0.6
Osasuna - local
1731    1
1757    0
1773    0
1796    0
1819    0
1836    1
1851    0
1862    1
1885    0
2664    3
Name: FTR, dtype: object
0.6
9
11.3
Sevilla - visitante
1736    3
1753    3
1767    0
1785    3
1805    1
1825    3
1848    0
1867    1
1880    1
1908    0
Name: FTR, dtype: object
1.5
Eibar - local
1739    0
1752    1
1779    3
1786    3
1802    3
1820    0
1847    3
1867    1
1887    3
1917    1

Name: FTR, dtype: object
1.8
13
13.8
Barcelona - visitante
1732    1
1757    3
1772    1
1791    3
1815    3
1834    0
1845    3
1865    3
1882    3
1906    3
Name: FTR, dtype: object
2.3
Betis - local
1734    3
1754    3
1763    1
1789    3
1803    0
1826    0
1849    3
1869    1
1889    1
1904    3
Name: FTR, dtype: object
1.8
14
13.0
Sp Gijon - visitante
1738    0
1751    0
1776    0
1799    0
1817    1
1837    0
1856    0
1868    0
1883    1
1916    1
Name: FTR, dtype: object
0.3
Ath Bilbao - local
1735    1
1741    3
1764    3
1783    3
1804    1
1823    3
1848    3
1864    3
1882    0
1908    3
Name: FTR, dtype: object
2.3
18
13.1
Ath Madrid - visitante
1739    3
1750    0
1773    3
1795    0
1811    0
1830    3
1857    1
1877    3
1886    1
1914    0
Name: FTR, dtype: object
1.4
Villarreal - local
1732    1
1750    3
1771    0
1790    3
1810    3
1821    3
1841    3
1861    3
1880    1
1910    0
Name: FTR, dtype: object
2.0
18
12.2
Valencia - visitante
1731    1
1755    0
1775    0
1794    0
1800    1
1822    3
1842    3
1864    0
1887    0
1913    0
Name: FTR, dtype: object
0.8
Real Madrid - local
1737    3
1756    3
1776    3
1792    3
1812    3
1831    1
1854    1
1875    3
1884    3
1913    3
Name: FTR, dtype: object
2.6
27
20.1
Malaga - visitante
1733    0
1746    0
1761    1
1787    1
1807    0
1824    1
1849    0
1866    0
1888    1
1918    0
Name: FTR, dtype: object
0.4
Espanol - local
1740    1
1751    3
1778    3
1793    1
1818    1
1833    1
1843    0
1863    0
1888    1
1903    3
Name: FTR, dtype: object
1.4
15
9.9
Granada - visitante
1737    0
1759    1
1774    0
1781    1
1806    0
1828    0
1840    0
1869    1
1881    0
1912    3
Name: FTR, dtype: object
0.6
Alaves - local
1749    3
1765    1
1784    0
1808    0
1824    1
1840    3
1860    1
1883    1
Name: FTR, dtype: object
1.25
7
10.375
Leganes - visitante
1734    0
1758    1
1778    0
1792    0
1813    0
1838    3
1852    3
1871    0
1891    3
Name: FTR, dtype: object
1.1111111111111112
Las Palmas - local
1738    3
1758    1
1770    3
1797    3
1801    1
1829    1
1846    1
1866    3
1881    3
1915    1
Name: FTR, dtype: object
2.0
17
11.0
La Coruna - visitante
1740    1
1756    0
1777    0
1798    1
1814    0
1827    0
1844    0
1860    1
1889    1
1910    3
Name: FTR, dtype: object
0.7
Malaga - local
1759    1
1777    3
1799    3
1813    3
1832    3
1859    3
1876    0
1898    1
1902    3
1920    3
Name: FTR, dtype: object
2.3
24
16.5
Sociedad - visitante
1747    3
1760    0
1782    3
1809    3
1823    0
1847    0
1861    0
1885    3
1909    3
1931    1
Name: FTR, dtype: object
1.6
Valencia - local
1761    1
1781    1
1815    0
1830    0
1850    3
1870    0
1890    0
1909    0
1921    0
1942    3
Name: FTR, dtype: object
0.8
15
11.9
Espanol - visitante
1744    0
1769    1
1784    3
1803    3
1829    1
1851    3
1879    1
1895    0
1919    0
1939    0
Name: FTR, dtype: object
1.2
Sp Gijon - local
1745    0
1762    3
1782    0
1805    1
1822    0
1845    0
1871    3
1892    3
1901    3
1929    3
Name: FTR, dtype: object
1.6
15
9.6
Eibar - visitante
1742    1
1764    0
1797    0
1818    1
1831    1
1859    0
1873    3
1899    0
1903    0
1929    0
Name: FTR, dtype: object
0.6
Sevilla - local
1746    3
1775    3
1791    0
1811    3
1835    3
1858    3
1874    3
1895    3
1912    0
1932    3
Name: FTR, dtype: object
2.4
22
13.1
Real Madrid - visitante
1768    1
1788    3
1808    3
1826    3
1846    1
1863    3
1893    3
1905    3
1925    3
1935    3
Name: FTR, dtype: object
2.6
Granada - local
1747    0
1767    3
1798    1
1817    1
1838    0
1855    0
1873    0
1896    1
1906    0
1926    3
Name: FTR, dtype: object
0.9
9
11.2
Osasuna - visitante
1743    0
1762    0
1780    0
1804    1
1820    3
1841    0
1875    0
1898    1
2672    1
2696    0
Name: FTR, dtype: object
0.6
Celta - local
1733    3
1753    0
1774    3
1794    3
1814    3
1834    3
1856    3
1877    0
1891    0
1918    3
Name: FTR, dtype: object
2.1
19
11.3
Alaves - visitante
1735    1
1752    1
1771    3
1796    3
1816    0
1835    0
1850    0
1878    3
1894    1
Name: FTR, dtype: object
1.3333333333333333
Leganes - local
1742    1
1766    1
1780    3
1809    0
1825    0
1842    0
1865    0
1886    1
Name: FTR, dtype: object
0.75
7
11.0
Ath Bilbao - visitante
1754    0
1770    0
1793    1
1812    0
1832    0
1855    3
1872    3
1892    0
1915    1
1933    1
Name: FTR, dtype: object
0.9
La Coruna - local
1743    3
1760    3
1785    0
1800    1
1837    3
1852    0
1872    0
1899    3
1905    0
1922    0
Name: FTR, dtype: object
1.3
15
12.8
Villarreal - visitante
1745    3
1766    1
1783    0
1802    0
1833    1
1854    1
1876    3
1896    1
1901    0
1921    3
Name: FTR, dtype: object
1.3
Barcelona - local
1744    3
1768    1
1787    1
1806    3
1827    3
1857    1
1878    0
1897    3
1919    3
1937    3
Name: FTR, dtype: object
2.1
29
19.5
Las Palmas - visitante
1748    0
1765    1
1789    0
1810    0
1836    1
1853    0
1874    0
1890    3
1902    0
1926    0
Name: FTR, dtype: object
0.5
Ath Madrid - local
1748    3
1769    1
1788    0
1807    3
1828    3
1844    3
1868    3
1894    1
1907    3
1928    3
Name: FTR, dtype: object
2.3
22
16.6
Betis - visitante
1749    0
1779    0
1790    0
1819    3
1839    0
1858    0
1870    3
1897    0
1917    1
1932    0
Name: FTR, dtype: object
0.7
Osasuna - local
1757    0
1773    0
1796    0
1819    0
1836    1
1851    0
1862    1
1885    0
2664    3
2687    0
Name: FTR, dtype: object
0.5
6
11.4
Valencia - visitante
1755    0
1775    0
1794    0
1800    1
1822    3
1842    3
1864    0
1887    0
1913    0
1934    1
Name: FTR, dtype: object
0.8
Villarreal - local
1750    3
1771    0
1790    3
1810    3
1821    3
1841    3
1861    3
1880    1
1910    0
1931    1
Name: FTR, dtype: object
2.0
17
12.4
Barcelona - visitante
1757    3
1772    1
1791    3
1815    3
1834    0
1845    3
1865    3
1882    3
1906    3
1927    3
Name: FTR, dtype: object
2.5
Celta - local
1753    0
1774    3
1794    3
1814    3
1834    3
1856    3
1877    0
1891    0
1918    3
1930    3
Name: FTR, dtype: object
2.1
18
12.2
Malaga - visitante
1746    0
1761    1
1787    1
1807    0
1824    1
1849    0
1866    0
1888    1
1918    0
1938    0
Name: FTR, dtype: object
0.4
Betis - local
1754    3
1763    1
1789    3
1803    0
1826    0
1849    3
1869    1
1889    1
1904    3
1927    0
Name: FTR, dtype: object
1.5
12
11.6
Leganes - visitante
1758    1
1778    0
1792    0
1813    0
1838    3
1852    3
1871    0
1891    3
Name: FTR, dtype: object
1.25
Ath Bilbao - local
1741    3
1764    3
1783    3
1804    1
1823    3
1848    3
1864    3
1882    0
1908    3
1924    3
Name: FTR, dtype: object
2.5
20
12.6
Alaves - visitante
1752    1
1771    3
1796    3
1816    0
1835    0
1850    0
1878    3
1894    1
Name: FTR, dtype: object
1.375
Sociedad - local
1755    3
1772    1
1795    3
1816    3
1839    3
1853    3
1879    1
1893    0
1911    3
1925    0
Name: FTR, dtype: object
2.0
17
13.2
Sevilla - visitante
1753    3
1767    0
1785    3
1805    1
1825    3
1848    0
1867    1
1880    1
1908    0
1923    0
Name: FTR, dtype: object
1.2
Real Madrid - local
1756    3
1776    3
1792    3
1812    3
1831    1
1854    1
1875    3
1884    3
1913    3
1944    3
Name: FTR, dtype: object
2.6
25
19.8
Granada - visitante
1759    1
1774    0
1781    1
1806    0
1828    0
1840    0
1869    1
1881    0
1912    3
1930    0
Name: FTR, dtype: object
0.6
Las Palmas - local
1758    1
1770    3
1797    3
1801    1
1829    1
1846    1
1866    3
1881    3
1915    1
1939    3
Name: FTR, dtype: object
2.0
20
10.8
Sp Gijon - visitante
1751    0
1776    0
1799    0
1817    1
1837    0
1856    0
1868    0
1883    1
1916    1
1937    0
Name: FTR, dtype: object
0.3
Eibar - local
1752    1
1779    3
1786    3
1802    3
1820    0
1847    3
1867    1
1887    3
1917    1
1936    1
Name: FTR, dtype: object
1.9
14
13.2
Ath Madrid - visitante
1750    0
1773    3
1795    0
1811    0
1830    3
1857    1
1877    3
1886    1
1914    0
1947    3
Name: FTR, dtype: object
1.4
Espanol - local
1751    3
1778    3
1793    1
1818    1
1833    1
1843    0
1863    0
1888    1
1903    3
1923    3
Name: FTR, dtype: object
1.6
15
9.6
La Coruna - visitante
1756    0
1777    0
1798    1
1814    0
1827    0
1844    0
1860    1
1889    1
1910    3
1936    1
Name: FTR, dtype: object
0.7
Ath Bilbao - local
1764    3
1783    3
1804    1
1823    3
1848    3
1864    3
1882    0
1908    3
1924    3
1947    0
Name: FTR, dtype: object
2.2
18
12.8
Celta - visitante
1763    1
1786    0
1801    1
1821    0
1843    3
1862    1
1884    0
1907    0
1924    0
1948    1
Name: FTR, dtype: object
0.7
Leganes - local
1766    1
1780    3
1809    0
1825    0
1842    0
1865    0
1886    1
Name: FTR, dtype: object
0.7142857142857143
6
11.428571428571429
Eibar - visitante
1764    0
1797    0
1818    1
1831    1
1859    0
1873    3
1899    0
1903    0
1929    0
1942    0
Name: FTR, dtype: object
0.5
La Coruna - local
1760    3
1785    0
1800    1
1837    3
1852    0
1872    0
1899    3
1905    0
1922    0
1946    0
Name: FTR, dtype: object
1.0
13
13.6
Osasuna - visitante
1762    0
1780    0
1804    1
1820    3
1841    0
1875    0
1898    1
2672    1
2696    0
2729    3
Name: FTR, dtype: object
0.9
Barcelona - local
1768    1
1787    1
1806    3
1827    3
1857    1
1878    0
1897    3
1919    3
1937    3
1953    0
Name: FTR, dtype: object
1.8
26
20.3
Espanol - visitante
1769    1
1784    3
1803    3
1829    1
1851    3
1879    1
1895    0
1919    0
1939    0
1959    0
Name: FTR, dtype: object
1.2
Sp Gijon - local
1762    3
1782    0
1805    1
1822    0
1845    0
1871    3
1892    3
1901    3
1929    3
1943    3
Name: FTR, dtype: object
1.9
16
9.4
Villarreal - visitante
1766    1
1783    0
1802    0
1833    1
1854    1
1876    3
1896    1
1901    0
1921    3
1944    0
Name: FTR, dtype: object
1.0
Sevilla - local
1775    3
1791    0
1811    3
1835    3
1858    3
1874    3
1895    3
1912    0
1932    3
1951    1
Name: FTR, dtype: object
2.2
19
13.4
Malaga - visitante
1761    1
1787    1
1807    0
1824    1
1849    0
1866    0
1888    1
1918    0
1938    0
1969    1
Name: FTR, dtype: object
0.5
Granada - local
1767    3
1798    1
1817    1
1838    0
1855    0
1873    0
1896    1
1906    0
1926    3
1941    3
Name: FTR, dtype: object
1.2
14
11.5
Sociedad - visitante
1760    0
1782    3
1809    3
1823    0
1847    0
1861    0
1885    3
1909    3
1931    1
1957    0
Name: FTR, dtype: object
1.3
Ath Madrid - local
1769    1
1788    0
1807    3
1828    3
1844    3
1868    3
1894    1
1907    3
1928    3
1938    3
Name: FTR, dtype: object
2.3
22
16.4
Las Palmas - visitante
1765    1
1789    0
1810    0
1836    1
1853    0
1874    0
1890    3
1902    0
1926    0
1949    0

Name: FTR, dtype: object
0.5
Alaves - local
1765    1
1784    0
1808    0
1824    1
1840    3
1860    1
1883    1
Name: FTR, dtype: object
1.0
6
10.428571428571429
Betis - visitante
1779    0
1790    0
1819    3
1839    0
1858    0
1870    3
1897    0
1917    1
1932    0
1958    1
Name: FTR, dtype: object
0.8
Villarreal - local
1771    0
1790    3
1810    3
1821    3
1841    3
1861    3
1880    1
1910    0
1931    1
1961    3
Name: FTR, dtype: object
2.0
16
12.8
Ath Madrid - visitante
1773    3
1795    0
1811    0
1830    3
1857    1
1877    3
1886    1
1914    0
1947    3
1967    3
Name: FTR, dtype: object
1.7
Espanol - local
1778    3
1793    1
1818    1
1833    1
1843    0
1863    0
1888    1
1903    3
1923    3
1948    1
Name: FTR, dtype: object
1.4
14
9.2
Sp Gijon - visitante
1776    0
1799    0
1817    1
1837    0
1856    0
1868    0
1883    1
1916    1
1937    0
1955    1
Name: FTR, dtype: object
0.4
Eibar - local
1779    3
1786    3
1802    3
1820    0
1847    3
1867    1
1887    3
1917    1
1936    1
1957    3
Name: FTR, dtype: object
2.1
16
13.3
Alaves - visitante
1771    3
1796    3
1816    0
1835    0
1850    0
1878    3
1894    1
Name: FTR, dtype: object
1.4285714285714286
Celta - local
1774    3
1794    3
1814    3
1834    3
1856    3
1877    0
1891    0
1918    3
1930    3
1958    1
Name: FTR, dtype: object
2.2
19
12.6
Sevilla - visitante
1767    0
1785    3
1805    1
1825    3
1848    0
1867    1
1880    1
1908    0
1923    0
1943    0
Name: FTR, dtype: object
0.9
Betis - local
1763    1
1789    3
1803    0
1826    0
1849    3
1869    1
1889    1
1904    3
1927    0
1949    3
Name: FTR, dtype: object
1.5
12
13.0
Ath Bilbao - visitante
1770    0
1793    1
1812    0
1832    0
1855    3
1872    3
1892    0
1915    1
1933    1
1952    3
Name: FTR, dtype: object
1.2
Sociedad - local
1772    1
1795    3
1816    3
1839    3
1853    3
1879    1
1893    0
1911    3
1925    0
1940    0
Name: FTR, dtype: object
1.7
15
13.2
Valencia - visitante
1775    0
1794    0
1800    1
1822    3
1842    3
1864    0
1887    0
1913    0
1934    1
1953    3
Name: FTR, dtype: object
1.1
Real Madrid - local
1776    3
1792    3
1812    3
1831    1
1854    1
1875    3
1884    3
1913    3
1944    3
1966    3
Name: FTR, dtype: object
2.6
26
19.4
La Coruna - visitante
1777    0
1798    1
1814    0
1827    0
1844    0
1860    1
1889    1
1910    3
1936    1
1951    1
Name: FTR, dtype: object
0.8
Osasuna - local
1773    0
1796    0
1819    0
1836    1
1851    0
1862    1
1885    0
2664    3
2687    0
2707    1
Name: FTR, dtype: object
0.6
7
11.9
Barcelona - visitante
1772    1
1791    3
1815    3
1834    0
1845    3
1865    3
1882    3
1906    3
1927    3
1946    3
Name: FTR, dtype: object
2.5
Las Palmas - local
1770    3
1797    3
1801    1
1829    1
1846    1
1866    3
1881    3
1915    1
1939    3
1955    1
Name: FTR, dtype: object
2.0
20
11.3
Leganes - visitante
1778    0
1792    0
1813    0
1838    3
1852    3
1871    0
1891    3
Name: FTR, dtype: object
1.2857142857142858
Malaga - local
1777    3
1799    3
1813    3
1832    3
1859    3
1876    0
1898    1
1902    3
1920    3
1945    1
Name: FTR, dtype: object
2.3
24
16.1
Granada - visitante
1774    0
1781    1
1806    0
1828    0
1840    0
1869    1
1881    0
1912    3
1930    0
1954    0
Name: FTR, dtype: object
0.5
La Coruna - local
1785    0
1800    1
1837    3
1852    0
1872    0
1899    3
1905    0
1922    0
1946    0
1960    0
Name: FTR, dtype: object
0.7
9
14.0
Sociedad - visitante
1782    3
1809    3
1823    0
1847    0
1861    0
1885    3
1909    3
1931    1
1957    0
1971    3
Name: FTR, dtype: object
1.6
Valencia - local
1781    1
1815    0
1830    0
1850    3
1870    0
1890    0
1909    0
1921    0
1942    3
1962    3
Name: FTR, dtype: object
1.0
15
13.4
Malaga - visitante
1787    1
1807    0
1824    1
1849    0
1866    0
1888    1
1918    0
1938    0
1969    1
1988    3
Name: FTR, dtype: object
0.7
Sp Gijon - local
1782    0
1805    1
1822    0
1845    0
1871    3
1892    3
1901    3
1929    3
1943    3
1963    0
Name: FTR, dtype: object
1.6
13
9.4
Osasuna - visitante
1780    0
1804    1
1820    3
1841    0
1875    0
1898    1
2672    1
2696    0
2729    3
2744    0
Name: FTR, dtype: object
0.9
Betis - local
1789    3
1803    0
1826    0
1849    3
1869    1
1889    1
1904    3
1927    0
1949    3
1968    3
Name: FTR, dtype: object
1.7
10
12.1
Celta - visitante
1786    0
1801    1
1821    0
1843    3
1862    1
1884    0
1907    0
1924    0
1948    1
1963    3
Name: FTR, dtype: object
0.9
Ath Bilbao - local
1783    3
1804    1
1823    3
1848    3
1864    3
1882    0
1908    3
1924    3
1947    0
1964    3
Name: FTR, dtype: object
2.2
16
13.0
Eibar - visitante
1797    0
1818    1
1831    1
1859    0
1873    3
1899    0
1903    0
1929    0
1942    0
1966    0
Name: FTR, dtype: object
0.5
Alaves - local
1784    0
1808    0
1824    1
1840    3
1860    1
1883    1
Name: FTR, dtype: object
1.0
5
10.666666666666666
Las Palmas - visitante
1789    0
1810    0
1836    1
1853    0
1874    0
1890    3
1902    0
1926    0
1949    0
1960    3
Name: FTR, dtype: object
0.7
Leganes - local
1780    3
1809    0
1825    0
1842    0
1865    0
1886    1
Name: FTR, dtype: object
0.6666666666666666
6
11.5
Villarreal - visitante
1783    0
1802    0
1833    1
1854    1
1876    3
1896    1
1901    0
1921    3
1944    0
1950    0
Name: FTR, dtype: object
0.9
Granada - local
1798    1
1817    1
1838    0
1855    0
1873    0
1896    1
1906    0
1926    3
1941    3
1969    1
Name: FTR, dtype: object
1.0
12
11.3
Sevilla - visitante
1785    3
1805    1
1825    3
1848    0
1867    1
1880    1
1908    0
1923    0
1943    0
1962    0
Name: FTR, dtype: object
0.9
Barcelona - local
1787    1
1806    3
1827    3
1857    1
1878    0
1897    3
1919    3
1937    3
1953    0
1977    0
Name: FTR, dtype: object
1.7
26
20.6
Real Madrid - visitante
1788    3
1808    3
1826    3
1846    1
1863    3
1893    3
1905    3
1925    3
1935    3
1956    3
Name: FTR, dtype: object
2.8
Ath Madrid - local
1788    0
1807    3
1828    3
1844    3
1868    3
1894    1
1907    3
1928    3
1938    3
1954    3
Name: FTR, dtype: object
2.5
25
16.1
Espanol - visitante
1784    3
1803    3
1829    1
1851    3
1879    1
1895    0
1919    0
1939    0
1959    0
1972    1
Name: FTR, dtype: object
1.2
Las Palmas - local
1797    3
1801    1
1829    1
1846    1
1866    3
1881    3
1915    1
1939    3
1955    1
1975    3
Name: FTR, dtype: object
2.0
19
11.6
Ath Bilbao - visitante
1793    1
1812    0
1832    0
1855    3
1872    3
1892    0
1915    1
1933    1
1952    3
1983    0
Name: FTR, dtype: object
1.2
Villarreal - local
1790    3
1810    3
1821    3
1841    3
1861    3
1880    1
1910    0
1931    1
1961    3
1980    1
Name: FTR, dtype: object
2.1
18
12.0
Alaves - visitante
1796    3
1816    0
1835    0
1850    0
1878    3
1894    1
Name: FTR, dtype: object
1.1666666666666667
Sociedad - local
1795    3
1816    3
1839    3
1853    3
1879    1
1893    0
1911    3
1925    0
1940    0
1965    3
Name: FTR, dtype: object
1.9
15
12.0
Barcelona - visitante
1791    3
1815    3
1834    0
1845    3
1865    3
1882    3
1906    3
1927    3
1946    3
1965    0
Name: FTR, dtype: object
2.4
Osasuna - local
1796    0
1819    0
1836    1
1851    0
1862    1
1885    0
2664    3
2687    0
2707    1
2719    1
Name: FTR, dtype: object
0.7
7
12.3
Ath Madrid - visitante
1795    0
1811    0
1830    3
1857    1
1877    3
1886    1
1914    0
1947    3
1967    3
1984    0
Name: FTR, dtype: object
1.4
Celta - local
1794    3
1814    3
1834    3
1856    3
1877    0
1891    0
1918    3
1930    3
1958    1
1976    1
Name: FTR, dtype: object
2.0
17
11.9
Granada - visitante
1781    1
1806    0
1828    0
1840    0
1869    1
1881    0
1912    3
1930    0
1954    0
1974    1
Name: FTR, dtype: object
0.6
Sevilla - local
1791    0
1811    3
1835    3
1858    3
1874    3
1895    3
1912    0
1932    3
1951    1
1971    0
Name: FTR, dtype: object
1.9
18
14.3
Valencia - visitante
1794    0
1800    1
1822    3
1842    3
1864    0
1887    0
1913    0
1934    1
1953    3
1975    0
Name: FTR, dtype: object
1.1
Real Madrid - local
1792    3
1812    3
1831    1
1854    1
1875    3
1884    3
1913    3
1944    3
1966    3
1982    3
Name: FTR, dtype: object
2.6
28
20.1
Sp Gijon - visitante
1799    0
1817    1
1837    0
1856    0
1868    0
1883    1
1916    1
1937    0
1955    1
1970    1
Name: FTR, dtype: object
0.5
Malaga - local
1799    3
1813    3
1832    3
1859    3
1876    0
1898    1
1902    3
1920    3
1945    1
1952    0
Name: FTR, dtype: object
2.0
20
16.8
La Coruna - visitante
1798    1
1814    0
1827    0
1844    0
1860    1
1889    1
1910    3
1936    1
1951    1
1976    1
Name: FTR, dtype: object
0.9
Espanol - local
1793    1
1818    1
1833    1
1843    0
1863    0
1888    1
1903    3
1923    3
1948    1
1967    0
Name: FTR, dtype: object
1.1
12
9.4
Leganes - visitante
1792    0
1813    0
1838    3
1852    3
1871    0
1891    3
Name: FTR, dtype: object
1.5
Eibar - local
1786    3
1802    3
1820    0
1847    3
1867    1
1887    3
1917    1
1936    1
1957    3
1973    0
Name: FTR, dtype: object
1.8
14
12.7
Betis - visitante
1790    0
1819    3
1839    0
1858    0
1870    3
1897    0
1917    1
1932    0
1958    1
1978    0
Name: FTR, dtype: object
0.8
Leganes - local
1809    0
1825    0
1842    0
1865    0
1886    1
Name: FTR, dtype: object
0.2
4
10.8
Osasuna - visitante
1804    1
1820    3
1841    0
1875    0
1898    1
2672    1
2696    0
2729    3
2744    0
2764    0
Name: FTR, dtype: object
0.9
Valencia - local
1815    0
1830    0
1850    3
1870    0
1890    0
1909    0
1921    0
1942    3
1962    3
1981    0
Name: FTR, dtype: object
0.9
14
13.4
Granada - visitante
1806    0
1828    0
1840    0
1869    1
1881    0
1912    3
1930    0
1954    0
1974    1
2005    0
Name: FTR, dtype: object
0.5
Sp Gijon - local
1805    1
1822    0
1845    0
1871    3
1892    3
1901    3
1929    3
1943    3
1963    0
1984    3
Name: FTR, dtype: object
1.9
14
10.2
Sociedad - visitante
1809    3
1823    0
1847    0
1861    0
1885    3
1909    3
1931    1
1957    0
1971    3
1996    0

Name: FTR, dtype: object
1.3
Ath Bilbao - local
1804    1
1823    3
1848    3
1864    3
1882    0
1908    3
1924    3
1947    0
1964    3
1974    1
Name: FTR, dtype: object
2.0
16
12.6
Villarreal - visitante
1802    0
1833    1
1854    1
1876    3
1896    1
1901    0
1921    3
1944    0
1950    0
1973    3
Name: FTR, dtype: object
1.2
Alaves - local
1808    0
1824    1
1840    3
1860    1
1883    1
Name: FTR, dtype: object
1.2
5
10.8
Espanol - visitante
1803    3
1829    1
1851    3
1879    1
1895    0
1919    0
1939    0
1959    0
1972    1
1990    1
Name: FTR, dtype: object
1.0
La Coruna - local
1800    1
1837    3
1852    0
1872    0
1899    3
1905    0
1922    0
1946    0
1960    0
1986    3
Name: FTR, dtype: object
1.0
9
15.1
Sevilla - visitante
1805    1
1825    3
1848    0
1867    1
1880    1
1908    0
1923    0
1943    0
1962    0
1982    0
Name: FTR, dtype: object
0.6
Eibar - local
1802    3
1820    0
1847    3
1867    1
1887    3
1917    1
1936    1
1957    3
1973    0
2004    0
Name: FTR, dtype: object
1.5
13
12.2
Celta - visitante
1801    1
1821    0
1843    3
1862    1
1884    0
1907    0
1924    0
1948    1
1963    3
1981    3
Name: FTR, dtype: object
1.2
Barcelona - local
1806    3
1827    3
1857    1
1878    0
1897    3
1919    3
1937    3
1953    0
1977    0
1997    3
Name: FTR, dtype: object
1.9
32
19.4
Malaga - visitante
1807    0
1824    1
1849    0
1866    0
1888    1
1918    0
1938    0
1969    1
1988    3
2008    1
Name: FTR, dtype: object
0.7
Ath Madrid - local
1807    3
1828    3
1844    3
1868    3
1894    1
1907    3
1928    3
1938    3
1954    3
1978    3
Name: FTR, dtype: object
2.8
30
16.4
Real Madrid - visitante
1808    3
1826    3
1846    1
1863    3
1893    3
1905    3
1925    3
1935    3
1956    3
1977    3
Name: FTR, dtype: object
2.8
Betis - local
1803    0
1826    0
1849    3
1869    1
1889    1
1904    3
1927    0
1949    3
1968    3
1988    0
Name: FTR, dtype: object
1.4
8
12.7
Las Palmas - visitante
1810    0
1836    1
1853    0
1874    0
1890    3
1902    0
1926    0
1949    0
1960    3
1985    3
Name: FTR, dtype: object
1.0
Villarreal - local
1810    3
1821    3
1841    3
1861    3
1880    1
1910    0
1931    1
1961    3
1980    1
2006    0
Name: FTR, dtype: object
1.8
16
11.8
Betis - visitante
1819    3
1839    0
1858    0
1870    3
1897    0
1917    1
1932    0
1958    1
1978    0
1994    0
Name: FTR, dtype: object
0.8
Sevilla - local
1811    3
1835    3
1858    3
1874    3
1895    3
1912    0
1932    3
1951    1
1971    0
1991    3
Name: FTR, dtype: object
2.2
21
14.2
Barcelona - visitante
1815    3
1834    0
1845    3
1865    3
1882    3
1906    3
1927    3
1946    3
1965    0
1980    1
Name: FTR, dtype: object
2.2
Real Madrid - local
1812    3
1831    1
1854    1
1875    3
1884    3
1913    3
1944    3
1966    3
1982    3
2007    3
Name: FTR, dtype: object
2.6
32
20.4
Leganes - visitante
1813    0
1838    3
1852    3
1871    0
1891    3
Name: FTR, dtype: object
1.8
Espanol - local
1818    1
1833    1
1843    0
1863    0
1888    1
1903    3
1923    3
1948    1
1967    0
1983    3
Name: FTR, dtype: object
1.3
14
10.4
Ath Bilbao - visitante
1812    0
1832    0
1855    3
1872    3
1892    0
1915    1
1933    1
1952    3
1983    0
2002    3
Name: FTR, dtype: object
1.4
Celta - local
1814    3
1834    3
1856    3
1877    0
1891    0
1918    3
1930    3
1958    1
1976    1
1996    3
Name: FTR, dtype: object
2.0
16
11.9
Valencia - visitante
1800    1
1822    3
1842    3
1864    0
1887    0
1913    0
1934    1
1953    3
1975    0
1992    0
Name: FTR, dtype: object
1.1
Sociedad - local
1816    3
1839    3
1853    3
1879    1
1893    0
1911    3
1925    0
1940    0
1965    3
1985    0
Name: FTR, dtype: object
1.6
13
12.1
Ath Madrid - visitante
1811    0
1830    3
1857    1
1877    3
1886    1
1914    0
1947    3
1967    3
1984    0
2001    3
Name: FTR, dtype: object
1.7
Osasuna - local
1819    0
1836    1
1851    0
1862    1
1885    0
2664    3
2687    0
2707    1
2719    1
2735    1
Name: FTR, dtype: object
0.8
8
12.8
Alaves - visitante
1816    0
1835    0
1850    0
1878    3
1894    1
Name: FTR, dtype: object
0.8
Las Palmas - local
1801    1
1829    1
1846    1
1866    3
1881    3
1915    1
1939    3
1955    1
1975    3
1993    0
Name: FTR, dtype: object
1.7
19
11.5
Eibar - visitante
1818    1
1831    1
1859    0
1873    3
1899    0
1903    0
1929    0
1942    0
1966    0
1989    1
Name: FTR, dtype: object
0.6
Granada - local
1817    1
1838    0
1855    0
1873    0
1896    1
1906    0
1926    3
1941    3
1969    1
1987    1
Name: FTR, dtype: object
1.0
13
11.0
La Coruna - visitante
1814    0
1827    0
1844    0
1860    1
1889    1
1910    3
1936    1
1951    1
1976    1
1998    0
Name: FTR, dtype: object
0.8
Malaga - local
1813    3
1832    3
1859    3
1876    0
1898    1
1902    3
1920    3
1945    1
1952    0
1972    1
Name: FTR, dtype: object
1.8
18
15.7
Sp Gijon - visitante
1817    1
1837    0
1856    0
1868    0
1883    1
1916    1
1937    0
1955    1
1970    1
1999    0
Name: FTR, dtype: object
0.5
La Coruna - local
1837    3
1852    0
1872    0
1899    3
1905    0
1922    0
1946    0
1960    0
1986    3
2008    1
Name: FTR, dtype: object
1.0
11
14.9
Valencia - visitante
1822    3
1842    3
1864    0
1887    0
1913    0
1934    1
1953    3
1975    0
1992    0
2014    3
Name: FTR, dtype: object
1.3
Las Palmas - local
1829    1
1846    1
1866    3
1881    3
1915    1
1939    3
1955    1
1975    3
1993    0
2018    3
Name: FTR, dtype: object
1.9
20
10.9
Celta - visitante
1821    0
1843    3
1862    1
1884    0
1907    0
1924    0
1948    1
1963    3
1981    3
2007    0
Name: FTR, dtype: object
1.1
Eibar - local
1820    0
1847    3
1867    1
1887    3
1917    1
1936    1
1957    3
1973    0
2004    0
2029    0
Name: FTR, dtype: object
1.2
11
11.9
Villarreal - visitante
1833    1
1854    1
1876    3
1896    1
1901    0
1921    3
1944    0
1950    0
1973    3
1991    0
Name: FTR, dtype: object
1.2
Betis - local
1826    0
1849    3
1869    1
1889    1
1904    3
1927    0
1949    3
1968    3
1988    0
2005    3
Name: FTR, dtype: object
1.7
10
12.4
Espanol - visitante
1829    1
1851    3
1879    1
1895    0
1919    0
1939    0
1959    0
1972    1
1990    1
2024    3
Name: FTR, dtype: object
1.0
Ath Bilbao - local
1823    3
1848    3
1864    3
1882    0
1908    3
1924    3
1947    0
1964    3
1974    1
1994    3
Name: FTR, dtype: object
2.2
18
12.6
Osasuna - visitante
1820    3
1841    0
1875    0
1898    1
2672    1
2696    0
2729    3
2744    0
2764    0
2786    0
Name: FTR, dtype: object
0.8
Sp Gijon - local
1822    0
1845    0
1871    3
1892    3
1901    3
1929    3
1943    3
1963    0
1984    3
2002    0
Name: FTR, dtype: object
1.8
13
9.8
Sevilla - visitante
1825    3
1848    0
1867    1
1880    1
1908    0
1923    0
1943    0
1962    0
1982    0
2009    1
Name: FTR, dtype: object
0.6
Barcelona - local
1827    3
1857    1
1878    0
1897    3
1919    3
1937    3
1953    0
1977    0
1997    3
2023    3
Name: FTR, dtype: object
1.9
33
19.6
Granada - visitante
1828    0
1840    0
1869    1
1881    0
1912    3
1930    0
1954    0
1974    1
2005    0
2022    3
Name: FTR, dtype: object
0.8
Ath Madrid - local
1828    3
1844    3
1868    3
1894    1
1907    3
1928    3
1938    3
1954    3
1978    3
1998    3
Name: FTR, dtype: object
2.8
29
16.3
Malaga - visitante
1824    1
1849    0
1866    0
1888    1
1918    0
1938    0
1969    1
1988    3
2008    1
2025    1
Name: FTR, dtype: object
0.8
Alaves - local
1824    1
1840    3
1860    1
1883    1
Name: FTR, dtype: object
1.5
4
11.5
Real Madrid - visitante
1826    3
1846    1
1863    3
1893    3
1905    3
1925    3
1935    3
1956    3
1977    3
1993    3
Name: FTR, dtype: object
2.8
Leganes - local
1825    0
1842    0
1865    0
1886    1
Name: FTR, dtype: object
0.25
4
11.75
Sociedad - visitante
1823    0
1847    0
1861    0
1885    3
1909    3
1931    1
1957    0
1971    3
1996    0
2019    0
Name: FTR, dtype: object
1.0
Villarreal - local
1821    3
1841    3
1861    3
1880    1
1910    0
1931    1
1961    3
1980    1
2006    0
2020    3
Name: FTR, dtype: object
1.8
17
11.3
Las Palmas - visitante
1836    1
1853    0
1874    0
1890    3
1902    0
1926    0
1949    0
1960    3
1985    3
2006    3
Name: FTR, dtype: object
1.3
Sevilla - local
1835    3
1858    3
1874    3
1895    3
1912    0
1932    3
1951    1
1971    0
1991    3
2013    3
Name: FTR, dtype: object
2.2
21
14.4
Ath Madrid - visitante
1830    3
1857    1
1877    3
1886    1
1914    0
1947    3
1967    3
1984    0
2001    3
2026    3
Name: FTR, dtype: object
2.0
Real Madrid - local
1831    1
1854    1
1875    3
1884    3
1913    3
1944    3
1966    3
1982    3
2007    3
2026    0
Name: FTR, dtype: object
2.3
30
19.5
Ath Bilbao - visitante
1832    0
1855    3
1872    3
1892    0
1915    1
1933    1
1952    3
1983    0
2002    3
2021    3
Name: FTR, dtype: object
1.7
Malaga - local
1832    3
1859    3
1876    0
1898    1
1902    3
1920    3
1945    1
1952    0
1972    1
1999    3
Name: FTR, dtype: object
1.8
15
14.6
Leganes - visitante
1838    3
1852    3
1871    0
1891    3
Name: FTR, dtype: object
2.25
Celta - local
1834    3
1856    3
1877    0
1891    0
1918    3
1930    3
1958    1
1976    1
1996    3
2016    1
Name: FTR, dtype: object
1.8
12
12.1
La Coruna - visitante
1827    0
1844    0
1860    1
1889    1
1910    3
1936    1
1951    1
1976    1
1998    0
2017    0
Name: FTR, dtype: object
0.8
Valencia - local
1830    0
1850    3
1870    0
1890    0
1909    0
1921    0
1942    3
1962    3
1981    0
2001    0
Name: FTR, dtype: object
0.9
13
13.7
Barcelona - visitante
1834    0
1845    3
1865    3
1882    3
1906    3
1927    3
1946    3
1965    0
1980    1
2004    3
Name: FTR, dtype: object
2.2
Sociedad - local
1839    3
1853    3
1879    1
1893    0
1911    3
1925    0
1940    0
1965    3
1985    0
2003    1
Name: FTR, dtype: object
1.4
11
12.0
Alaves - visitante
1835    0
1850    0
1878    3
1894    1
Name: FTR, dtype: object
1.0
Granada - local
1838    0
1855    0
1873    0
1896    1
1906    0
1926    3
1941    3
1969    1
1987    1
1990    1
Name: FTR, dtype: object
1.0
14
10.6
Sp Gijon - visitante
1837    0
1856    0
1868    0
1883    1
1916    1
1937    0
1955    1
1970    1
1999    0
2011    0

Name: FTR, dtype: object
0.4
Espanol - local
1833    1
1843    0
1863    0
1888    1
1903    3
1923    3
1948    1
1967    0
1983    3
2000    3
Name: FTR, dtype: object
1.5
13
10.2
Eibar - visitante
1831    1
1859    0
1873    3
1899    0
1903    0
1929    0
1942    0
1966    0
1989    1
1995    1
Name: FTR, dtype: object
0.6
Osasuna - local
1836    1
1851    0
1862    1
1885    0
2664    3
2687    0
2707    1
2719    1
2735    1
2753    0
Name: FTR, dtype: object
0.8
8
13.3
Betis - visitante
1839    0
1858    0
1870    3
1897    0
1917    1
1932    0
1958    1
1978    0
1994    0
2012    3
Name: FTR, dtype: object
0.8
Eibar - local
1847    3
1867    1
1887    3
1917    1
1936    1
1957    3
1973    0
2004    0
2029    0
2044    3
Name: FTR, dtype: object
1.5
11
12.1
Osasuna - visitante
1841    0
1875    0
1898    1
2672    1
2696    0
2729    3
2744    0
2764    0
2786    0
2809    1
Name: FTR, dtype: object
0.6
Villarreal - local
1841    3
1861    3
1880    1
1910    0
1931    1
1961    3
1980    1
2006    0
2020    3
2046    3
Name: FTR, dtype: object
1.8
13
11.4
Celta - visitante
1843    3
1862    1
1884    0
1907    0
1924    0
1948    1
1963    3
1981    3
2007    0
2027    3
Name: FTR, dtype: object
1.4
Sp Gijon - local
1845    0
1871    3
1892    3
1901    3
1929    3
1943    3
1963    0
1984    3
2002    0
2024    0
Name: FTR, dtype: object
1.8
14
10.1
Valencia - visitante
1842    3
1864    0
1887    0
1913    0
1934    1
1953    3
1975    0
1992    0
2014    3
2032    3
Name: FTR, dtype: object
1.3
Ath Bilbao - local
1848    3
1864    3
1882    0
1908    3
1924    3
1947    0
1964    3
1974    1
1994    3
2017    3
Name: FTR, dtype: object
2.2
19
12.3
Sociedad - visitante
1847    0
1861    0
1885    3
1909    3
1931    1
1957    0
1971    3
1996    0
2019    0
2034    3
Name: FTR, dtype: object
1.3
Alaves - local
1840    3
1860    1
1883    1
Name: FTR, dtype: object
1.6666666666666667
3
12.666666666666666
Malaga - visitante
1849    0
1866    0
1888    1
1918    0
1938    0
1969    1
1988    3
2008    1
2025    1
2046    0
Name: FTR, dtype: object
0.7
Leganes - local
1842    0
1865    0
1886    1
Name: FTR, dtype: object
0.3333333333333333
2
9.333333333333334
Sevilla - visitante
1848    0
1867    1
1880    1
1908    0
1923    0
1943    0
1962    0
1982    0
2009    1
2023    0
Name: FTR, dtype: object
0.3
Betis - local
1849    3
1869    1
1889    1
1904    3
1927    0
1949    3
1968    3
1988    0
2005    3
2028    1
Name: FTR, dtype: object
1.8
11
13.1
Real Madrid - visitante
1846    1
1863    3
1893    3
1905    3
1925    3
1935    3
1956    3
1977    3
1993    3
2015    3
Name: FTR, dtype: object
2.8
Barcelona - local
1857    1
1878    0
1897    3
1919    3
1937    3
1953    0
1977    0
1997    3
2023    3
2045    3
Name: FTR, dtype: object
1.9
35
19.0
La Coruna - visitante
1844    0
1860    1
1889    1
1910    3
1936    1
1951    1
1976    1
1998    0
2017    0
2036    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
1844    3
1868    3
1894    1
1907    3
1928    3
1938    3
1954    3
1978    3
1998    3
2019    3
Name: FTR, dtype: object
2.8
25
15.8
Granada - visitante
1840    0
1869    1
1881    0
1912    3
1930    0
1954    0
1974    1
2005    0
2022    3
2041    0
Name: FTR, dtype: object
0.8
Las Palmas - local
1846    1
1866    3
1881    3
1915    1
1939    3
1955    1
1975    3
1993    0
2018    3
2035    0
Name: FTR, dtype: object
1.8
21
11.2
Espanol - visitante
1851    3
1879    1
1895    0
1919    0
1939    0
1959    0
1972    1
1990    1
2024    3
2047    0
Name: FTR, dtype: object
0.9
Valencia - local
1850    3
1870    0
1890    0
1909    0
1921    0
1942    3
1962    3
1981    0
2001    0
2021    0
Name: FTR, dtype: object
0.9
13
13.2
Ath Madrid - visitante
1857    1
1877    3
1886    1
1914    0
1947    3
1967    3
1984    0
2001    3
2026    3
2043    3
Name: FTR, dtype: object
2.0
Real Madrid - local
1854    1
1875    3
1884    3
1913    3
1944    3
1966    3
1982    3
2007    3
2026    0
2048    3
Name: FTR, dtype: object
2.5
33
19.9
Eibar - visitante
1859    0
1873    3
1899    0
1903    0
1929    0
1942    0
1966    0
1989    1
1995    1
2013    0
Name: FTR, dtype: object
0.5
Malaga - local
1859    3
1876    0
1898    1
1902    3
1920    3
1945    1
1952    0
1972    1
1999    3
2014    0
Name: FTR, dtype: object
1.5
14
14.1
Ath Bilbao - visitante
1855    3
1872    3
1892    0
1915    1
1933    1
1952    3
1983    0
2002    3
2021    3
2048    0
Name: FTR, dtype: object
1.7
Espanol - local
1843    0
1863    0
1888    1
1903    3
1923    3
1948    1
1967    0
1983    3
2000    3
2012    0
Name: FTR, dtype: object
1.4
13
10.9
Villarreal - visitante
1854    1
1876    3
1896    1
1901    0
1921    3
1944    0
1950    0
1973    3
1991    0
2016    1
Name: FTR, dtype: object
1.2
Celta - local
1856    3
1877    0
1891    0
1918    3
1930    3
1958    1
1976    1
1996    3
2016    1
2037    3
Name: FTR, dtype: object
1.8
11
12.1
Barcelona - visitante
1845    3
1865    3
1882    3
1906    3
1927    3
1946    3
1965    0
1980    1
2004    3
2010    3
Name: FTR, dtype: object
2.5
Sevilla - local
1858    3
1874    3
1895    3
1912    0
1932    3
1951    1
1971    0
1991    3
2013    3
2042    3
Name: FTR, dtype: object
2.2
21
13.3
Alaves - visitante
1850    0
1878    3
1894    1
Name: FTR, dtype: object
1.3333333333333333
Osasuna - local
1851    0
1862    1
1885    0
2664    3
2687    0
2707    1
2719    1
2735    1
2753    0
2771    0
Name: FTR, dtype: object
0.7
6
14.7
Las Palmas - visitante
1853    0
1874    0
1890    3
1902    0
1926    0
1949    0
1960    3
1985    3
2006    3
2029    3
Name: FTR, dtype: object
1.5
La Coruna - local
1852    0
1872    0
1899    3
1905    0
1922    0
1946    0
1960    0
1986    3
2008    1
2022    0
Name: FTR, dtype: object
0.7
9
14.1
Sp Gijon - visitante
1856    0
1868    0
1883    1
1916    1
1937    0
1955    1
1970    1
1999    0
2011    0
2038    1
Name: FTR, dtype: object
0.5
Granada - local
1855    0
1873    0
1896    1
1906    0
1926    3
1941    3
1969    1
1987    1
1990    1
2011    3
Name: FTR, dtype: object
1.3
16
11.1
Leganes - visitante
1852    3
1871    0
1891    3
Name: FTR, dtype: object
2.0
Sociedad - local
1853    3
1879    1
1893    0
1911    3
1925    0
1940    0
1965    3
1985    0
2003    1
2025    1
Name: FTR, dtype: object
1.2
11
11.5
Betis - visitante
1858    0
1870    3
1897    0
1917    1
1932    0
1958    1
1978    0
1994    0
2012    3
2049    1
Name: FTR, dtype: object
0.9
Alaves - local
1860    1
1883    1
Name: FTR, dtype: object
1.0
0
11.0
Granada - visitante
1869    1
1881    0
1912    3
1930    0
1954    0
1974    1
2005    0
2022    3
2041    0
2066    0
Name: FTR, dtype: object
0.8
Villarreal - local
1861    3
1880    1
1910    0
1931    1
1961    3
1980    1
2006    0
2020    3
2046    3
2066    3
Name: FTR, dtype: object
1.8
11
11.4
Osasuna - visitante
1875    0
1898    1
2672    1
2696    0
2729    3
2744    0
2764    0
2786    0
2809    1
2820    0
Name: FTR, dtype: object
0.6
Leganes - local
1865    0
1886    1
Name: FTR, dtype: object
0.5
1
10.5
Valencia - visitante
1864    0
1887    0
1913    0
1934    1
1953    3
1975    0
1992    0
2014    3
2032    3
2055    0
Name: FTR, dtype: object
1.0
Espanol - local
1863    0
1888    1
1903    3
1923    3
1948    1
1967    0
1983    3
2000    3
2012    0
2036    3
Name: FTR, dtype: object
1.7
14
11.5
Celta - visitante
1862    1
1884    0
1907    0
1924    0
1948    1
1963    3
1981    3
2007    0
2027    3
2045    0
Name: FTR, dtype: object
1.1
Ath Madrid - local
1868    3
1894    1
1907    3
1928    3
1938    3
1954    3
1978    3
1998    3
2019    3
2033    1
Name: FTR, dtype: object
2.6
24
14.9
La Coruna - visitante
1860    1
1889    1
1910    3
1936    1
1951    1
1976    1
1998    0
2017    0
2036    0
2057    1
Name: FTR, dtype: object
0.9
Sp Gijon - local
1871    3
1892    3
1901    3
1929    3
1943    3
1963    0
1984    3
2002    0
2024    0
2040    0
Name: FTR, dtype: object
1.8
15
9.7
Barcelona - visitante
1865    3
1882    3
1906    3
1927    3
1946    3
1965    0
1980    1
2004    3
2010    3
2035    3
Name: FTR, dtype: object
2.5
Las Palmas - local
1866    3
1881    3
1915    1
1939    3
1955    1
1975    3
1993    0
2018    3
2035    0
2065    3
Name: FTR, dtype: object
2.0
21
11.7
Real Madrid - visitante
1863    3
1893    3
1905    3
1925    3
1935    3
1956    3
1977    3
1993    3
2015    3
2031    1
Name: FTR, dtype: object
2.8
Eibar - local
1867    1
1887    3
1917    1
1936    1
1957    3
1973    0
2004    0
2029    0
2044    3
2069    0
Name: FTR, dtype: object
1.2
10
11.5
Sociedad - visitante
1861    0
1885    3
1909    3
1931    1
1957    0
1971    3
1996    0
2019    0
2034    3
2051    3
Name: FTR, dtype: object
1.6
Ath Bilbao - local
1864    3
1882    0
1908    3
1924    3
1947    0
1964    3
1974    1
1994    3
2017    3
2034    0
Name: FTR, dtype: object
1.9
16
11.8
Sevilla - visitante
1867    1
1880    1
1908    0
1923    0
1943    0
1962    0
1982    0
2009    1
2023    0
2030    1
Name: FTR, dtype: object
0.4
Betis - local
1869    1
1889    1
1904    3
1927    0
1949    3
1968    3
1988    0
2005    3
2028    1
2038    1
Name: FTR, dtype: object
1.6
11
13.7
Malaga - visitante
1866    0
1888    1
1918    0
1938    0
1969    1
1988    3
2008    1
2025    1
2046    0
2069    3
Name: FTR, dtype: object
1.0
Valencia - local
1870    0
1890    0
1909    0
1921    0
1942    3
1962    3
1981    0
2001    0
2021    0
2047    3
Name: FTR, dtype: object
0.9
13
13.7
Alaves - visitante
1878    3
1894    1
Name: FTR, dtype: object
2.0
Osasuna - local
1862    1
1885    0
2664    3
2687    0
2707    1
2719    1
2735    1
2753    0
2771    0
2793    3
Name: FTR, dtype: object
1.0
8
14.0
Espanol - visitante
1879    1
1895    0
1919    0
1939    0
1959    0
1972    1
1990    1
2024    3
2047    0
2064    0

Name: FTR, dtype: object
0.6
La Coruna - local
1872    0
1899    3
1905    0
1922    0
1946    0
1960    0
1986    3
2008    1
2022    0
2049    1
Name: FTR, dtype: object
0.8
10
15.4
Leganes - visitante
1871    0
1891    3
Name: FTR, dtype: object
1.5
Sociedad - local
1879    1
1893    0
1911    3
1925    0
1940    0
1965    3
1985    0
2003    1
2025    1
2041    3
Name: FTR, dtype: object
1.2
10
11.0
Las Palmas - visitante
1874    0
1890    3
1902    0
1926    0
1949    0
1960    3
1985    3
2006    3
2029    3
2042    0
Name: FTR, dtype: object
1.5
Real Madrid - local
1875    3
1884    3
1913    3
1944    3
1966    3
1982    3
2007    3
2026    0
2048    3
2064    3
Name: FTR, dtype: object
2.7
38
19.5
Villarreal - visitante
1876    3
1896    1
1901    0
1921    3
1944    0
1950    0
1973    3
1991    0
2016    1
2033    1
Name: FTR, dtype: object
1.2
Granada - local
1873    0
1896    1
1906    0
1926    3
1941    3
1969    1
1987    1
1990    1
2011    3
2032    0
Name: FTR, dtype: object
1.3
16
11.3
Ath Bilbao - visitante
1872    3
1892    0
1915    1
1933    1
1952    3
1983    0
2002    3
2021    3
2048    0
2068    3
Name: FTR, dtype: object
1.7
Celta - local
1877    0
1891    0
1918    3
1930    3
1958    1
1976    1
1996    3
2016    1
2037    3
2054    1
Name: FTR, dtype: object
1.6
10
13.0
Sp Gijon - visitante
1868    0
1883    1
1916    1
1937    0
1955    1
1970    1
1999    0
2011    0
2038    1
2062    3
Name: FTR, dtype: object
0.8
Barcelona - local
1878    0
1897    3
1919    3
1937    3
1953    0
1977    0
1997    3
2023    3
2045    3
2070    3
Name: FTR, dtype: object
2.1
36
18.1
Ath Madrid - visitante
1877    3
1886    1
1914    0
1947    3
1967    3
1984    0
2001    3
2026    3
2043    3
2070    0
Name: FTR, dtype: object
1.9
Sevilla - local
1874    3
1895    3
1912    0
1932    3
1951    1
1971    0
1991    3
2013    3
2042    3
2063    3
Name: FTR, dtype: object
2.2
23
13.5
Betis - visitante
1870    3
1897    0
1917    1
1932    0
1958    1
1978    0
1994    0
2012    3
2049    1
2067    0
Name: FTR, dtype: object
0.9
Malaga - local
1876    0
1898    1
1902    3
1920    3
1945    1
1952    0
1972    1
1999    3
2014    0
2031    1
Name: FTR, dtype: object
1.3
13
13.8
Eibar - visitante
1873    3
1899    0
1903    0
1929    0
1942    0
1966    0
1989    1
1995    1
2013    0
2037    0
Name: FTR, dtype: object
0.5
Alaves - local
1883    1
Name: FTR, dtype: object
1.0
0
13.0
La Coruna - visitante
1889    1
1910    3
1936    1
1951    1
1976    1
1998    0
2017    0
2036    0
2057    1
2088    1
Name: FTR, dtype: object
0.9
Villarreal - local
1880    1
1910    0
1931    1
1961    3
1980    1
2006    0
2020    3
2046    3
2066    3
2087    1
Name: FTR, dtype: object
1.6
9
11.4
Sociedad - visitante
1885    3
1909    3
1931    1
1957    0
1971    3
1996    0
2019    0
2034    3
2051    3
2080    0
Name: FTR, dtype: object
1.6
Osasuna - local
1885    0
2664    3
2687    0
2707    1
2719    1
2735    1
2753    0
2771    0
2793    3
2814    3
Name: FTR, dtype: object
1.2
10
14.5
Celta - visitante
1884    0
1907    0
1924    0
1948    1
1963    3
1981    3
2007    0
2027    3
2045    0
2065    0
Name: FTR, dtype: object
1.0
Espanol - local
1888    1
1903    3
1923    3
1948    1
1967    0
1983    3
2000    3
2012    0
2036    3
2051    0
Name: FTR, dtype: object
1.7
14
10.9
Real Madrid - visitante
1893    3
1905    3
1925    3
1935    3
1956    3
1977    3
1993    3
2015    3
2031    1
2053    3
Name: FTR, dtype: object
2.8
Ath Bilbao - local
1882    0
1908    3
1924    3
1947    0
1964    3
1974    1
1994    3
2017    3
2034    0
2059    1
Name: FTR, dtype: object
1.7
14
11.5
Valencia - visitante
1887    0
1913    0
1934    1
1953    3
1975    0
1992    0
2014    3
2032    3
2055    0
2072    1
Name: FTR, dtype: object
1.1
Leganes - local
1886    1
Name: FTR, dtype: object
1.0
0
6.0
Barcelona - visitante
1882    3
1906    3
1927    3
1946    3
1965    0
1980    1
2004    3
2010    3
2035    3
2040    3
Name: FTR, dtype: object
2.5
Las Palmas - local
1881    3
1915    1
1939    3
1955    1
1975    3
1993    0
2018    3
2035    0
2065    3
2084    0
Name: FTR, dtype: object
1.7
20
12.2
Malaga - visitante
1888    1
1918    0
1938    0
1969    1
1988    3
2008    1
2025    1
2046    0
2069    3
2089    0
Name: FTR, dtype: object
1.0
Eibar - local
1887    3
1917    1
1936    1
1957    3
1973    0
2004    0
2029    0
2044    3
2069    0
2081    3
Name: FTR, dtype: object
1.4
14
11.7
Sevilla - visitante
1880    1
1908    0
1923    0
1943    0
1962    0
1982    0
2009    1
2023    0
2030    1
2054    1
Name: FTR, dtype: object
0.4
Ath Madrid - local
1894    1
1907    3
1928    3
1938    3
1954    3
1978    3
1998    3
2019    3
2033    1
2058    3
Name: FTR, dtype: object
2.6
22
14.4
Sp Gijon - visitante
1883    1
1916    1
1937    0
1955    1
1970    1
1999    0
2011    0
2038    1
2062    3
2083    0
Name: FTR, dtype: object
0.8
Betis - local
1889    1
1904    3
1927    0
1949    3
1968    3
1988    0
2005    3
2028    1
2038    1
2055    3
Name: FTR, dtype: object
1.8
10
12.0
Granada - visitante
1881    0
1912    3
1930    0
1954    0
1974    1
2005    0
2022    3
2041    0
2066    0
2081    0
Name: FTR, dtype: object
0.7
Valencia - local
1890    0
1909    0
1921    0
1942    3
1962    3
1981    0
2001    0
2021    0
2047    3
2062    0
Name: FTR, dtype: object
0.9
11
13.0
Betis - visitante
1897    0
1917    1
1932    0
1958    1
1978    0
1994    0
2012    3
2049    1
2067    0
2087    1
Name: FTR, dtype: object
0.7
Sp Gijon - local
1892    3
1901    3
1929    3
1943    3
1963    0
1984    3
2002    0
2024    0
2040    0
2050    1
Name: FTR, dtype: object
1.6
15
10.1
Leganes - visitante
1891    3
Name: FTR, dtype: object
3.0
La Coruna - local
1899    3
1905    0
1922    0
1946    0
1960    0
1986    3
2008    1
2022    0
2049    1
2061    1
Name: FTR, dtype: object
0.9
12
15.5
Ath Bilbao - visitante
1892    0
1915    1
1933    1
1952    3
1983    0
2002    3
2021    3
2048    0
2068    3
2086    0
Name: FTR, dtype: object
1.4
Granada - local
1896    1
1906    0
1926    3
1941    3
1969    1
1987    1
1990    1
2011    3
2032    0
2053    0
Name: FTR, dtype: object
1.3
16
11.2
Eibar - visitante
1899    0
1903    0
1929    0
1942    0
1966    0
1989    1
1995    1
2013    0
2037    0
2058    0
Name: FTR, dtype: object
0.2
Sevilla - local
1895    3
1912    0
1932    3
1951    1
1971    0
1991    3
2013    3
2042    3
2063    3
2089    3
Name: FTR, dtype: object
2.2
23
12.7
Las Palmas - visitante
1890    3
1902    0
1926    0
1949    0
1960    3
1985    3
2006    3
2029    3
2042    0
2056    0
Name: FTR, dtype: object
1.5
Real Madrid - local
1884    3
1913    3
1944    3
1966    3
1982    3
2007    3
2026    0
2048    3
2064    3
2083    3
Name: FTR, dtype: object
2.7
38
18.7
Osasuna - visitante
1898    1
2672    1
2696    0
2729    3
2744    0
2764    0
2786    0
2809    1
2820    0
2845    1
Name: FTR, dtype: object
0.7
Malaga - local
1898    1
1902    3
1920    3
1945    1
1952    0
1972    1
1999    3
2014    0
2031    1
2060    3
Name: FTR, dtype: object
1.6
16
13.1
Villarreal - visitante
1896    1
1901    0
1921    3
1944    0
1950    0
1973    3
1991    0
2016    1
2033    1
2059    1
Name: FTR, dtype: object
1.0
Celta - local
1891    0
1918    3
1930    3
1958    1
1976    1
1996    3
2016    1
2037    3
2054    1
2090    3
Name: FTR, dtype: object
1.9
14
13.5
Ath Madrid - visitante
1886    1
1914    0
1947    3
1967    3
1984    0
2001    3
2026    3
2043    3
2070    0
2084    3
Name: FTR, dtype: object
1.9
Barcelona - local
1897    3
1919    3
1937    3
1953    0
1977    0
1997    3
2023    3
2045    3
2070    3
2086    3
Name: FTR, dtype: object
2.4
41
18.5
Alaves - visitante
1894    1
Name: FTR, dtype: object
1.0
Sociedad - local
1893    0
1911    3
1925    0
1940    0
1965    3
1985    0
2003    1
2025    1
2041    3
2067    3
Name: FTR, dtype: object
1.4
11
11.2
Espanol - visitante
1895    0
1919    0
1939    0
1959    0
1972    1
1990    1
2024    3
2047    0
2064    0
2085    0
Name: FTR, dtype: object
0.5
Villarreal - local
1910    0
1931    1
1961    3
1980    1
2006    0
2020    3
2046    3
2066    3
2087    1
2091    3
Name: FTR, dtype: object
1.8
11
10.9
Sevilla - visitante
1908    0
1923    0
1943    0
1962    0
1982    0
2009    1
2023    0
2030    1
2054    1
2074    1
Name: FTR, dtype: object
0.4
Las Palmas - local
1915    1
1939    3
1955    1
1975    3
1993    0
2018    3
2035    0
2065    3
2084    0
2093    1
Name: FTR, dtype: object
1.5
16
11.2
Granada - visitante
1912    3
1930    0
1954    0
1974    1
2005    0
2022    3
2041    0
2066    0
2081    0
2100    0
Name: FTR, dtype: object
0.7
Ath Bilbao - local
1908    3
1924    3
1947    0
1964    3
1974    1
1994    3
2017    3
2034    0
2059    1
2075    3
Name: FTR, dtype: object
2.0
19
11.6
Barcelona - visitante
1906    3
1927    3
1946    3
1965    0
1980    1
2004    3
2010    3
2035    3
2040    3
2052    3
Name: FTR, dtype: object
2.5
Alaves - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Sp Gijon - visitante
1916    1
1937    0
1955    1
1970    1
1999    0
2011    0
2038    1
2062    3
2083    0
2091    0
Name: FTR, dtype: object
0.7
Real Madrid - local
1913    3
1944    3
1966    3
1982    3
2007    3
2026    0
2048    3
2064    3
2083    3
2097    3
Name: FTR, dtype: object
2.7
41
18.6
Celta - visitante
1907    0
1924    0
1948    1
1963    3
1981    3
2007    0
2027    3
2045    0
2065    0
2076    0
Name: FTR, dtype: object
1.0
Osasuna - local
2664    3
2687    0
2707    1
2719    1
2735    1
2753    0
2771    0
2793    3
2814    3
2832    0
Name: FTR, dtype: object
1.2
11
14.8
Sociedad - visitante
1909    3
1931    1
1957    0
1971    3
1996    0
2019    0
2034    3
2051    3
2080    0
2102    1
Name: FTR, dtype: object
1.4
Leganes - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Ath Madrid - visitante
1914    0
1947    3
1967    3
1984    0
2001    3
2026    3
2043    3
2070    0
2084    3
2095    3
Name: FTR, dtype: object
2.1
Eibar - local
1917    1
1936    1
1957    3
1973    0
2004    0
2029    0
2044    3
2069    0
2081    3
2094    3
Name: FTR, dtype: object
1.4
15
12.4
Valencia - visitante
1913    0
1934    1
1953    3
1975    0
1992    0
2014    3
2032    3
2055    0
2072    1
2092    0

Name: FTR, dtype: object
1.1
Espanol - local
1903    3
1923    3
1948    1
1967    0
1983    3
2000    3
2012    0
2036    3
2051    0
2079    1
Name: FTR, dtype: object
1.7
14
11.3
Malaga - visitante
1918    0
1938    0
1969    1
1988    3
2008    1
2025    1
2046    0
2069    3
2089    0
2093    1
Name: FTR, dtype: object
1.0
Betis - local
1904    3
1927    0
1949    3
1968    3
1988    0
2005    3
2028    1
2038    1
2055    3
2073    1
Name: FTR, dtype: object
1.8
11
10.9
La Coruna - visitante
1910    3
1936    1
1951    1
1976    1
1998    0
2017    0
2036    0
2057    1
2088    1
2097    0
Name: FTR, dtype: object
0.8
Valencia - local
1909    0
1921    0
1942    3
1962    3
1981    0
2001    0
2021    0
2047    3
2062    0
2082    1
Name: FTR, dtype: object
1.0
11
12.6
Las Palmas - visitante
1902    0
1926    0
1949    0
1960    3
1985    3
2006    3
2029    3
2042    0
2056    0
2071    0
Name: FTR, dtype: object
1.2
Celta - local
1918    3
1930    3
1958    1
1976    1
1996    3
2016    1
2037    3
2054    1
2090    3
2095    0
Name: FTR, dtype: object
1.9
14
13.1
Leganes - visitante
Series([], Name: FTR, dtype: object)
0.0
Sp Gijon - local
1901    3
1929    3
1943    3
1963    0
1984    3
2002    0
2024    0
2040    0
2050    1
2057    1
Name: FTR, dtype: object
1.4
14
10.0
Ath Bilbao - visitante
1915    1
1933    1
1952    3
1983    0
2002    3
2021    3
2048    0
2068    3
2086    0
2096    0
Name: FTR, dtype: object
1.4
Sociedad - local
1911    3
1925    0
1940    0
1965    3
1985    0
2003    1
2025    1
2041    3
2067    3
2088    1
Name: FTR, dtype: object
1.5
12
12.0
Real Madrid - visitante
1905    3
1925    3
1935    3
1956    3
1977    3
1993    3
2015    3
2031    1
2053    3
2073    1
Name: FTR, dtype: object
2.6
Ath Madrid - local
1907    3
1928    3
1938    3
1954    3
1978    3
1998    3
2019    3
2033    1
2058    3
2074    1
Name: FTR, dtype: object
2.6
21
13.8
Alaves - visitante
Series([], Name: FTR, dtype: object)
0.0
Sevilla - local
1912    0
1932    3
1951    1
1971    0
1991    3
2013    3
2042    3
2063    3
2089    3
2096    3
Name: FTR, dtype: object
2.2
19
11.5
Espanol - visitante
1919    0
1939    0
1959    0
1972    1
1990    1
2024    3
2047    0
2064    0
2085    0
2094    0
Name: FTR, dtype: object
0.5
Granada - local
1906    0
1926    3
1941    3
1969    1
1987    1
1990    1
2011    3
2032    0
2053    0
2078    3
Name: FTR, dtype: object
1.5
18
12.5
Villarreal - visitante
1901    0
1921    3
1944    0
1950    0
1973    3
1991    0
2016    1
2033    1
2059    1
2079    1
Name: FTR, dtype: object
1.0
Barcelona - local
1919    3
1937    3
1953    0
1977    0
1997    3
2023    3
2045    3
2070    3
2086    3
2100    3
Name: FTR, dtype: object
2.4
39
17.2
Betis - visitante
1917    1
1932    0
1958    1
1978    0
1994    0
2012    3
2049    1
2067    0
2087    1
2099    0
Name: FTR, dtype: object
0.7
Malaga - local
1902    3
1920    3
1945    1
1952    0
1972    1
1999    3
2014    0
2031    1
2060    3
2077    0
Name: FTR, dtype: object
1.5
16
13.2
Osasuna - visitante
2672    1
2696    0
2729    3
2744    0
2764    0
2786    0
2809    1
2820    0
2845    1
2854    3
Name: FTR, dtype: object
0.9
La Coruna - local
1905    0
1922    0
1946    0
1960    0
1986    3
2008    1
2022    0
2049    1
2061    1
2072    1
Name: FTR, dtype: object
0.7
11
15.4
Eibar - visitante
1903    0
1929    0
1942    0
1966    0
1989    1
1995    1
2013    0
2037    0
2058    0
2075    0
Name: FTR, dtype: object
0.2
Vallecano - local
1935    0
1950    3
1979    3
1995    1
2010    0
2030    1
2056    3
2076    3
2102    1
2112    0
Name: FTR, dtype: object
1.5
17
14.0
Levante - visitante
1920    0
1941    0
1968    0
1986    0
2003    1
2020    0
2044    0
2063    0
2090    0
2110    0
Name: FTR, dtype: object
0.1
Sp Gijon - local
1929    3
1943    3
1963    0
1984    3
2002    0
2024    0
2040    0
2050    1
2057    1
2080    3
Name: FTR, dtype: object
1.4
17
9.5
Villarreal - visitante
1921    3
1944    0
1950    0
1973    3
1991    0
2016    1
2033    1
2059    1
2079    1
2104    3
Name: FTR, dtype: object
1.3
Malaga - local
1920    3
1945    1
1952    0
1972    1
1999    3
2014    0
2031    1
2060    3
2077    0
2108    3
Name: FTR, dtype: object
1.5
14
13.2
Las Palmas - visitante
1926    0
1949    0
1960    3
1985    3
2006    3
2029    3
2042    0
2056    0
2071    0
2107    1
Name: FTR, dtype: object
1.3
Espanol - local
1923    3
1948    1
1967    0
1983    3
2000    3
2012    0
2036    3
2051    0
2079    1
2109    1
Name: FTR, dtype: object
1.5
10
10.6
Eibar - visitante
1929    0
1942    0
1966    0
1989    1
1995    1
2013    0
2037    0
2058    0
2075    0
2106    3
Name: FTR, dtype: object
0.5
Betis - local
1927    0
1949    3
1968    3
1988    0
2005    3
2028    1
2038    1
2055    3
2073    1
2106    0
Name: FTR, dtype: object
1.5
9
11.1
Getafe - visitante
1922    3
1940    3
1961    0
1979    0
1997    0
2018    0
2039    0
2060    0
2078    0
2101    3
Name: FTR, dtype: object
0.9
La Coruna - local
1922    0
1946    0
1960    0
1986    3
2008    1
2022    0
2049    1
2061    1
2072    1
2104    0
Name: FTR, dtype: object
0.7
12
15.5
Real Madrid - visitante
1925    3
1935    3
1956    3
1977    3
1993    3
2015    3
2031    1
2053    3
2073    1
2103    1
Name: FTR, dtype: object
2.4
Granada - local
1926    3
1941    3
1969    1
1987    1
1990    1
2011    3
2032    0
2053    0
2078    3
2105    3
Name: FTR, dtype: object
1.8
20
12.6
Barcelona - visitante
1927    3
1946    3
1965    0
1980    1
2004    3
2010    3
2035    3
2040    3
2052    3
2077    3
Name: FTR, dtype: object
2.5
Ath Madrid - local
1928    3
1938    3
1954    3
1978    3
1998    3
2019    3
2033    1
2058    3
2074    1
2110    3
Name: FTR, dtype: object
2.6
20
14.2
Celta - visitante
1924    0
1948    1
1963    3
1981    3
2007    0
2027    3
2045    0
2065    0
2076    0
2108    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
1924    3
1947    0
1964    3
1974    1
1994    3
2017    3
2034    0
2059    1
2075    3
2107    1
Name: FTR, dtype: object
1.8
18
11.9
Sevilla - visitante
1923    0
1943    0
1962    0
1982    0
2009    1
2023    0
2030    1
2054    1
2074    1
2105    0
Name: FTR, dtype: object
0.4
Valencia - local
1921    0
1942    3
1962    3
1981    0
2001    0
2021    0
2047    3
2062    0
2082    1
2103    1
Name: FTR, dtype: object
1.1
13
12.9
Sociedad - visitante
1931    1
1957    0
1971    3
1996    0
2019    0
2034    3
2051    3
2080    0
2102    1
2114    0
Name: FTR, dtype: object
1.1
Villarreal - local
1931    1
1961    3
1980    1
2006    0
2020    3
2046    3
2066    3
2087    1
2091    3
2111    3
Name: FTR, dtype: object
2.1
12
10.7
La Coruna - visitante
1936    1
1951    1
1976    1
1998    0
2017    0
2036    0
2057    1
2088    1
2097    0
2117    1
Name: FTR, dtype: object
0.6
Sociedad - local
1925    0
1940    0
1965    3
1985    0
2003    1
2025    1
2041    3
2067    3
2088    1
2092    3
Name: FTR, dtype: object
1.5
12
13.2
Vallecano - visitante
1928    0
1945    1
1964    0
1987    1
2000    0
2028    1
2050    1
2061    1
2082    1
2098    0
Name: FTR, dtype: object
0.6
Sevilla - local
1932    3
1951    1
1971    0
1991    3
2013    3
2042    3
2063    3
2089    3
2096    3
2113    3
Name: FTR, dtype: object
2.5
20
11.8
Granada - visitante
1930    0
1954    0
1974    1
2005    0
2022    3
2041    0
2066    0
2081    0
2100    0
2116    0
Name: FTR, dtype: object
0.4
Real Madrid - local
1944    3
1966    3
1982    3
2007    3
2026    0
2048    3
2064    3
2083    3
2097    3
2114    3
Name: FTR, dtype: object
2.7
41
19.4
Valencia - visitante
1934    1
1953    3
1975    0
1992    0
2014    3
2032    3
2055    0
2072    1
2092    0
2111    0
Name: FTR, dtype: object
1.1
Levante - local
1933    1
1959    3
1970    1
1992    3
2015    0
2039    3
2052    0
2071    3
2098    3
2115    0
Name: FTR, dtype: object
1.7
14
11.4
Ath Madrid - visitante
1947    3
1967    3
1984    0
2001    3
2026    3
2043    3
2070    0
2084    3
2095    3
2112    3
Name: FTR, dtype: object
2.4
Las Palmas - local
1939    3
1955    1
1975    3
1993    0
2018    3
2035    0
2065    3
2084    0
2093    1
2116    3
Name: FTR, dtype: object
1.7
20
11.5
Ath Bilbao - visitante
1933    1
1952    3
1983    0
2002    3
2021    3
2048    0
2068    3
2086    0
2096    0
2119    3
Name: FTR, dtype: object
1.6
Getafe - local
1934    1
1956    0
1989    1
2009    1
2027    0
2043    0
2068    0
2085    3
2099    3
2117    1
Name: FTR, dtype: object
1.0
9
12.8
Sp Gijon - visitante
1937    0
1955    1
1970    1
1999    0
2011    0
2038    1
2062    3
2083    0
2091    0
2118    0
Name: FTR, dtype: object
0.6
Eibar - local
1936    1
1957    3
1973    0
2004    0
2029    0
2044    3
2069    0
2081    3
2094    3
2118    3
Name: FTR, dtype: object
1.6
16
11.9
Betis - visitante
1932    0
1958    1
1978    0
1994    0
2012    3
2049    1
2067    0
2087    1
2099    0
2120    0
Name: FTR, dtype: object
0.6
Celta - local
1930    3
1958    1
1976    1
1996    3
2016    1
2037    3
2054    1
2090    3
2095    0
2119    0
Name: FTR, dtype: object
1.6
13
12.6
Malaga - visitante
1938    0
1969    1
1988    3
2008    1
2025    1
2046    0
2069    3
2089    0
2093    1
2115    3
Name: FTR, dtype: object
1.3
Barcelona - local
1937    3
1953    0
1977    0
1997    3
2023    3
2045    3
2070    3
2086    3
2100    3
2120    3
Name: FTR, dtype: object
2.4
38
17.5
Espanol - visitante
1939    0
1959    0
1972    1
1990    1
2024    3
2047    0
2064    0
2085    0
2094    0
2113    0
Name: FTR, dtype: object
0.5
Malaga - local
1945    1
1952    0
1972    1
1999    3
2014    0
2031    1
2060    3
2077    0
2108    3
2123    3
Name: FTR, dtype: object
1.5
12
12.8
Levante - visitante
1941    0
1968    0
1986    0
2003    1
2020    0
2044    0
2063    0
2090    0
2110    0
2125    0
Name: FTR, dtype: object
0.1
Valencia - local
1942    3
1962    3
1981    0
2001    0
2021    0
2047    3
2062    0
2082    1
2103    1
2126    1
Name: FTR, dtype: object
1.2
15
13.4
Villarreal - visitante
1944    0
1950    0
1973    3
1991    0
2016    1
2033    1
2059    1
2079    1
2104    3
2121    3
Name: FTR, dtype: object
1.3
La Coruna - local
1946    0
1960    0
1986    3
2008    1
2022    0
2049    1
2061    1
2072    1
2104    0
2127    3

Name: FTR, dtype: object
1.0
14
15.3
Getafe - visitante
1940    3
1961    0
1979    0
1997    0
2018    0
2039    0
2060    0
2078    0
2101    3
2126    1
Name: FTR, dtype: object
0.7
Espanol - local
1948    1
1967    0
1983    3
2000    3
2012    0
2036    3
2051    0
2079    1
2109    1
2128    3
Name: FTR, dtype: object
1.5
10
10.7
Sevilla - visitante
1943    0
1962    0
1982    0
2009    1
2023    0
2030    1
2054    1
2074    1
2105    0
2129    1
Name: FTR, dtype: object
0.5
Ath Bilbao - local
1947    0
1964    3
1974    1
1994    3
2017    3
2034    0
2059    1
2075    3
2107    1
2125    3
Name: FTR, dtype: object
1.8
18
12.7
Celta - visitante
1948    1
1963    3
1981    3
2007    0
2027    3
2045    0
2065    0
2076    0
2108    0
2124    3
Name: FTR, dtype: object
1.3
Sociedad - local
1940    0
1965    3
1985    0
2003    1
2025    1
2041    3
2067    3
2088    1
2092    3
2121    0
Name: FTR, dtype: object
1.5
12
13.7
Real Madrid - visitante
1935    3
1956    3
1977    3
1993    3
2015    3
2031    1
2053    3
2073    1
2103    1
2130    0
Name: FTR, dtype: object
2.1
Granada - local
1941    3
1969    1
1987    1
1990    1
2011    3
2032    0
2053    0
2078    3
2105    3
2124    0
Name: FTR, dtype: object
1.5
17
12.3
Las Palmas - visitante
1949    0
1960    3
1985    3
2006    3
2029    3
2042    0
2056    0
2071    0
2107    1
2128    0
Name: FTR, dtype: object
1.3
Betis - local
1949    3
1968    3
1988    0
2005    3
2028    1
2038    1
2055    3
2073    1
2106    0
2129    1
Name: FTR, dtype: object
1.6
9
12.1
Barcelona - visitante
1946    3
1965    0
1980    1
2004    3
2010    3
2035    3
2040    3
2052    3
2077    3
2109    1
Name: FTR, dtype: object
2.3
Ath Madrid - local
1938    3
1954    3
1978    3
1998    3
2019    3
2033    1
2058    3
2074    1
2110    3
2133    3
Name: FTR, dtype: object
2.6
21
13.8
Vallecano - visitante
1945    1
1964    0
1987    1
2000    0
2028    1
2050    1
2061    1
2082    1
2098    0
2122    0
Name: FTR, dtype: object
0.6
Sp Gijon - local
1943    3
1963    0
1984    3
2002    0
2024    0
2040    0
2050    1
2057    1
2080    3
2101    0
Name: FTR, dtype: object
1.1
16
10.9
Eibar - visitante
1942    0
1966    0
1989    1
1995    1
2013    0
2037    0
2058    0
2075    0
2106    3
2127    0
Name: FTR, dtype: object
0.5
Celta - local
1958    1
1976    1
1996    3
2016    1
2037    3
2054    1
2090    3
2095    0
2119    0
2137    3
Name: FTR, dtype: object
1.6
12
12.7
Granada - visitante
1954    0
1974    1
2005    0
2022    3
2041    0
2066    0
2081    0
2100    0
2116    0
2135    3
Name: FTR, dtype: object
0.7
Villarreal - local
1961    3
1980    1
2006    0
2020    3
2046    3
2066    3
2087    1
2091    3
2111    3
2130    3
Name: FTR, dtype: object
2.3
13
10.6
Sociedad - visitante
1957    0
1971    3
1996    0
2019    0
2034    3
2051    3
2080    0
2102    1
2114    0
2139    1
Name: FTR, dtype: object
1.1
Sevilla - local
1951    1
1971    0
1991    3
2013    3
2042    3
2063    3
2089    3
2096    3
2113    3
2134    3
Name: FTR, dtype: object
2.5
20
12.3
Betis - visitante
1958    1
1978    0
1994    0
2012    3
2049    1
2067    0
2087    1
2099    0
2120    0
2136    0
Name: FTR, dtype: object
0.6
Levante - local
1959    3
1970    1
1992    3
2015    0
2039    3
2052    0
2071    3
2098    3
2115    0
2135    0
Name: FTR, dtype: object
1.6
13
11.1
Ath Bilbao - visitante
1952    3
1983    0
2002    3
2021    3
2048    0
2068    3
2086    0
2096    0
2119    3
2133    0
Name: FTR, dtype: object
1.5
Getafe - local
1956    0
1989    1
2009    1
2027    0
2043    0
2068    0
2085    3
2099    3
2117    1
2139    1
Name: FTR, dtype: object
1.0
8
11.9
Valencia - visitante
1953    3
1975    0
1992    0
2014    3
2032    3
2055    0
2072    1
2092    0
2111    0
2132    1
Name: FTR, dtype: object
1.1
Vallecano - local
1950    3
1979    3
1995    1
2010    0
2030    1
2056    3
2076    3
2102    1
2112    0
2131    0
Name: FTR, dtype: object
1.5
16
14.2
Real Madrid - visitante
1956    3
1977    3
1993    3
2015    3
2031    1
2053    3
2073    1
2103    1
2130    0
2153    3
Name: FTR, dtype: object
2.1
Eibar - local
1957    3
1973    0
2004    0
2029    0
2044    3
2069    0
2081    3
2094    3
2118    3
2132    1
Name: FTR, dtype: object
1.6
16
12.4
La Coruna - visitante
1951    1
1976    1
1998    0
2017    0
2036    0
2057    1
2088    1
2097    0
2117    1
2138    1
Name: FTR, dtype: object
0.6
Barcelona - local
1953    0
1977    0
1997    3
2023    3
2045    3
2070    3
2086    3
2100    3
2120    3
2138    1
Name: FTR, dtype: object
2.2
34
16.8
Sp Gijon - visitante
1955    1
1970    1
1999    0
2011    0
2038    1
2062    3
2083    0
2091    0
2118    0
2134    0
Name: FTR, dtype: object
0.6
Ath Madrid - local
1954    3
1978    3
1998    3
2019    3
2033    1
2058    3
2074    1
2110    3
2133    3
2158    3
Name: FTR, dtype: object
2.6
21
14.5
Malaga - visitante
1969    1
1988    3
2008    1
2025    1
2046    0
2069    3
2089    0
2093    1
2115    3
2131    3
Name: FTR, dtype: object
1.6
Las Palmas - local
1955    1
1975    3
1993    0
2018    3
2035    0
2065    3
2084    0
2093    1
2116    3
2136    3
Name: FTR, dtype: object
1.7
17
11.7
Espanol - visitante
1959    0
1972    1
1990    1
2024    3
2047    0
2064    0
2085    0
2094    0
2113    0
2137    0
Name: FTR, dtype: object
0.5
Sociedad - local
1965    3
1985    0
2003    1
2025    1
2041    3
2067    3
2088    1
2092    3
2121    0
2143    3
Name: FTR, dtype: object
1.8
13
13.3
Getafe - visitante
1961    0
1979    0
1997    0
2018    0
2039    0
2060    0
2078    0
2101    3
2126    1
2146    0
Name: FTR, dtype: object
0.4
Granada - local
1969    1
1987    1
1990    1
2011    3
2032    0
2053    0
2078    3
2105    3
2124    0
2148    0
Name: FTR, dtype: object
1.2
12
12.8
Levante - visitante
1968    0
1986    0
2003    1
2020    0
2044    0
2063    0
2090    0
2110    0
2125    0
2140    1
Name: FTR, dtype: object
0.2
Valencia - local
1962    3
1981    0
2001    0
2021    0
2047    3
2062    0
2082    1
2103    1
2126    1
2145    1
Name: FTR, dtype: object
1.0
12
13.5
Eibar - visitante
1966    0
1989    1
1995    1
2013    0
2037    0
2058    0
2075    0
2106    3
2127    0
2143    0
Name: FTR, dtype: object
0.5
Sp Gijon - local
1963    0
1984    3
2002    0
2024    0
2040    0
2050    1
2057    1
2080    3
2101    0
2142    3
Name: FTR, dtype: object
1.1
17
11.6
Sevilla - visitante
1962    0
1982    0
2009    1
2023    0
2030    1
2054    1
2074    1
2105    0
2129    1
2147    1
Name: FTR, dtype: object
0.6
Real Madrid - local
1966    3
1982    3
2007    3
2026    0
2048    3
2064    3
2083    3
2097    3
2114    3
2122    3
Name: FTR, dtype: object
2.7
48
20.4
Villarreal - visitante
1950    0
1973    3
1991    0
2016    1
2033    1
2059    1
2079    1
2104    3
2121    3
2152    0
Name: FTR, dtype: object
1.3
Malaga - local
1952    0
1972    1
1999    3
2014    0
2031    1
2060    3
2077    0
2108    3
2123    3
2154    1
Name: FTR, dtype: object
1.5
13
12.8
Vallecano - visitante
1964    0
1987    1
2000    0
2028    1
2050    1
2061    1
2082    1
2098    0
2122    0
2141    0
Name: FTR, dtype: object
0.5
La Coruna - local
1960    0
1986    3
2008    1
2022    0
2049    1
2061    1
2072    1
2104    0
2127    3
2147    1
Name: FTR, dtype: object
1.1
15
14.5
Barcelona - visitante
1965    0
1980    1
2004    3
2010    3
2035    3
2040    3
2052    3
2077    3
2109    1
2145    1
Name: FTR, dtype: object
2.1
Ath Bilbao - local
1964    3
1974    1
1994    3
2017    3
2034    0
2059    1
2075    3
2107    1
2125    3
2144    1
Name: FTR, dtype: object
1.9
18
12.6
Ath Madrid - visitante
1967    3
1984    0
2001    3
2026    3
2043    3
2070    0
2084    3
2095    3
2112    3
2123    0
Name: FTR, dtype: object
2.1
Espanol - local
1967    0
1983    3
2000    3
2012    0
2036    3
2051    0
2079    1
2109    1
2128    3
2140    1
Name: FTR, dtype: object
1.5
10
10.8
Celta - visitante
1963    3
1981    3
2007    0
2027    3
2045    0
2065    0
2076    0
2108    0
2124    3
2149    1
Name: FTR, dtype: object
1.3
Betis - local
1968    3
1988    0
2005    3
2028    1
2038    1
2055    3
2073    1
2106    0
2129    1
2149    1
Name: FTR, dtype: object
1.4
9
12.8
Las Palmas - visitante
1960    3
1985    3
2006    3
2029    3
2042    0
2056    0
2071    0
2107    1
2128    0
2142    0
Name: FTR, dtype: object
1.3
Vallecano - local
1979    3
1995    1
2010    0
2030    1
2056    3
2076    3
2102    1
2112    0
2131    0
2150    0
Name: FTR, dtype: object
1.2
14
14.3
Villarreal - visitante
1973    3
1991    0
2016    1
2033    1
2059    1
2079    1
2104    3
2121    3
2152    0
2171    0
Name: FTR, dtype: object
1.3
Sevilla - local
1971    0
1991    3
2013    3
2042    3
2063    3
2089    3
2096    3
2113    3
2134    3
2151    3
Name: FTR, dtype: object
2.7
20
12.6
La Coruna - visitante
1976    1
1998    0
2017    0
2036    0
2057    1
2088    1
2097    0
2117    1
2138    1
2155    3
Name: FTR, dtype: object
0.8
Malaga - local
1972    1
1999    3
2014    0
2031    1
2060    3
2077    0
2108    3
2123    3
2154    1
2175    0
Name: FTR, dtype: object
1.5
13
12.3
Ath Bilbao - visitante
1983    0
2002    3
2021    3
2048    0
2068    3
2086    0
2096    0
2119    3
2133    0
2150    3
Name: FTR, dtype: object
1.5
Barcelona - local
1977    0
1997    3
2023    3
2045    3
2070    3
2086    3
2100    3
2120    3
2138    1
2157    3
Name: FTR, dtype: object
2.5
37
15.7
Valencia - visitante
1975    0
1992    0
2014    3
2032    3
2055    0
2072    1
2092    0
2111    0
2132    1
2151    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
1978    3
1998    3
2019    3
2033    1
2058    3
2074    1
2110    3
2133    3
2158    3
2172    3
Name: FTR, dtype: object
2.6
19
15.2
Granada - visitante
1974    1
2005    0
2022    3
2041    0
2066    0
2081    0
2100    0
2116    0
2135    3
2154    1
Name: FTR, dtype: object
0.8
Las Palmas - local
1975    3
1993    0
2018    3
2035    0
2065    3
2084    0
2093    1
2116    3
2136    3
2155    0
Name: FTR, dtype: object
1.6
16
11.5
Sp Gijon - visitante
1970    1
1999    0
2011    0
2038    1
2062    3
2083    0
2091    0
2118    0
2134    0
2156    0
Name: FTR, dtype: object
0.5
Getafe - local
1989    1
2009    1
2027    0
2043    0
2068    0
2085    3
2099    3
2117    1
2139    1
2152    3
Name: FTR, dtype: object
1.3
9
11.8
Real Madrid - visitante
1977    3
1993    3
2015    3
2031    1
2053    3
2073    1
2103    1
2130    0
2153    3
2170    0

Name: FTR, dtype: object
1.8
Eibar - local
1973    0
2004    0
2029    0
2044    3
2069    0
2081    3
2094    3
2118    3
2132    1
2153    0
Name: FTR, dtype: object
1.3
14
12.3
Sociedad - visitante
1971    3
1996    0
2019    0
2034    3
2051    3
2080    0
2102    1
2114    0
2139    1
2157    0
Name: FTR, dtype: object
1.1
Celta - local
1976    1
1996    3
2016    1
2037    3
2054    1
2090    3
2095    0
2119    0
2137    3
2156    3
Name: FTR, dtype: object
1.8
13
11.5
Betis - visitante
1978    0
1994    0
2012    3
2049    1
2067    0
2087    1
2099    0
2120    0
2136    0
2159    3
Name: FTR, dtype: object
0.8
Levante - local
1970    1
1992    3
2015    0
2039    3
2052    0
2071    3
2098    3
2115    0
2135    0
2159    0
Name: FTR, dtype: object
1.3
11
11.3
Espanol - visitante
1972    1
1990    1
2024    3
2047    0
2064    0
2085    0
2094    0
2113    0
2137    0
2158    0
Name: FTR, dtype: object
0.5
La Coruna - local
1986    3
2008    1
2022    0
2049    1
2061    1
2072    1
2104    0
2127    3
2147    1
2168    3
Name: FTR, dtype: object
1.4
16
13.1
Las Palmas - visitante
1985    3
2006    3
2029    3
2042    0
2056    0
2071    0
2107    1
2128    0
2142    0
2165    1
Name: FTR, dtype: object
1.1
Villarreal - local
1980    1
2006    0
2020    3
2046    3
2066    3
2087    1
2091    3
2111    3
2130    3
2141    3
Name: FTR, dtype: object
2.3
13
10.7
Getafe - visitante
1979    0
1997    0
2018    0
2039    0
2060    0
2078    0
2101    3
2126    1
2146    0
2177    0
Name: FTR, dtype: object
0.4
Valencia - local
1981    0
2001    0
2021    0
2047    3
2062    0
2082    1
2103    1
2126    1
2145    1
2165    1
Name: FTR, dtype: object
0.8
11
12.1
Sevilla - visitante
1982    0
2009    1
2023    0
2030    1
2054    1
2074    1
2105    0
2129    1
2147    1
2166    0
Name: FTR, dtype: object
0.6
Sp Gijon - local
1984    3
2002    0
2024    0
2040    0
2050    1
2057    1
2080    3
2101    0
2142    3
2162    0
Name: FTR, dtype: object
1.1
17
12.0
Celta - visitante
1981    3
2007    0
2027    3
2045    0
2065    0
2076    0
2108    0
2124    3
2149    1
2168    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
1974    1
1994    3
2017    3
2034    0
2059    1
2075    3
2107    1
2125    3
2144    1
2173    3
Name: FTR, dtype: object
1.9
19
12.0
Vallecano - visitante
1987    1
2000    0
2028    1
2050    1
2061    1
2082    1
2098    0
2122    0
2141    0
2160    1
Name: FTR, dtype: object
0.6
Sociedad - local
1985    0
2003    1
2025    1
2041    3
2067    3
2088    1
2092    3
2121    0
2143    3
2166    3
Name: FTR, dtype: object
1.8
14
14.2
Barcelona - visitante
1980    1
2004    3
2010    3
2035    3
2040    3
2052    3
2077    3
2109    1
2145    1
2167    3
Name: FTR, dtype: object
2.4
Real Madrid - local
1982    3
2007    3
2026    0
2048    3
2064    3
2083    3
2097    3
2114    3
2122    3
2146    3
Name: FTR, dtype: object
2.7
48
20.7
Eibar - visitante
1989    1
1995    1
2013    0
2037    0
2058    0
2075    0
2106    3
2127    0
2143    0
2161    1
Name: FTR, dtype: object
0.6
Espanol - local
1983    3
2000    3
2012    0
2036    3
2051    0
2079    1
2109    1
2128    3
2140    1
2169    3
Name: FTR, dtype: object
1.8
11
10.5
Ath Madrid - visitante
1984    0
2001    3
2026    3
2043    3
2070    0
2084    3
2095    3
2112    3
2123    0
2148    3
Name: FTR, dtype: object
2.1
Betis - local
1988    0
2005    3
2028    1
2038    1
2055    3
2073    1
2106    0
2129    1
2149    1
2164    0
Name: FTR, dtype: object
1.1
8
12.7
Levante - visitante
1986    0
2003    1
2020    0
2044    0
2063    0
2090    0
2110    0
2125    0
2140    1
2162    3
Name: FTR, dtype: object
0.5
Granada - local
1987    1
1990    1
2011    3
2032    0
2053    0
2078    3
2105    3
2124    0
2148    0
2163    3
Name: FTR, dtype: object
1.4
14
12.7
Malaga - visitante
1988    3
2008    1
2025    1
2046    0
2069    3
2089    0
2093    1
2115    3
2131    3
2144    1
Name: FTR, dtype: object
1.6
Levante - local
1992    3
2015    0
2039    3
2052    0
2071    3
2098    3
2115    0
2135    0
2159    0
2176    1
Name: FTR, dtype: object
1.3
12
11.2
Sp Gijon - visitante
1999    0
2011    0
2038    1
2062    3
2083    0
2091    0
2118    0
2134    0
2156    0
2172    0
Name: FTR, dtype: object
0.4
Sevilla - local
1991    3
2013    3
2042    3
2063    3
2089    3
2096    3
2113    3
2134    3
2151    3
2170    3
Name: FTR, dtype: object
3.0
22
12.5
Sociedad - visitante
1996    0
2019    0
2034    3
2051    3
2080    0
2102    1
2114    0
2139    1
2157    0
2179    0
Name: FTR, dtype: object
0.8
Malaga - local
1999    3
2014    0
2031    1
2060    3
2077    0
2108    3
2123    3
2154    1
2175    0
2196    3
Name: FTR, dtype: object
1.7
14
12.1
Espanol - visitante
1990    1
2024    3
2047    0
2064    0
2085    0
2094    0
2113    0
2137    0
2158    0
2173    0
Name: FTR, dtype: object
0.4
Eibar - local
2004    0
2029    0
2044    3
2069    0
2081    3
2094    3
2118    3
2132    1
2153    0
2177    3
Name: FTR, dtype: object
1.6
16
12.9
Villarreal - visitante
1991    0
2016    1
2033    1
2059    1
2079    1
2104    3
2121    3
2152    0
2171    0
2192    1
Name: FTR, dtype: object
1.1
Ath Bilbao - local
1994    3
2017    3
2034    0
2059    1
2075    3
2107    1
2125    3
2144    1
2173    3
2190    3
Name: FTR, dtype: object
2.1
21
13.2
Granada - visitante
2005    0
2022    3
2041    0
2066    0
2081    0
2100    0
2116    0
2135    3
2154    1
2174    0
Name: FTR, dtype: object
0.7
Las Palmas - local
1993    0
2018    3
2035    0
2065    3
2084    0
2093    1
2116    3
2136    3
2155    0
2179    3
Name: FTR, dtype: object
1.6
16
11.0
Valencia - visitante
1992    0
2014    3
2032    3
2055    0
2072    1
2092    0
2111    0
2132    1
2151    0
2178    3
Name: FTR, dtype: object
1.1
Celta - local
1996    3
2016    1
2037    3
2054    1
2090    3
2095    0
2119    0
2137    3
2156    3
2178    0
Name: FTR, dtype: object
1.7
13
12.3
La Coruna - visitante
1998    0
2017    0
2036    0
2057    1
2088    1
2097    0
2117    1
2138    1
2155    3
2176    1
Name: FTR, dtype: object
0.8
Barcelona - local
1997    3
2023    3
2045    3
2070    3
2086    3
2100    3
2120    3
2138    1
2157    3
2171    3
Name: FTR, dtype: object
2.8
39
16.3
Real Madrid - visitante
1993    3
2015    3
2031    1
2053    3
2073    1
2103    1
2130    0
2153    3
2170    0
2198    3
Name: FTR, dtype: object
1.8
Ath Madrid - local
1998    3
2019    3
2033    1
2058    3
2074    1
2110    3
2133    3
2158    3
2172    3
2194    3
Name: FTR, dtype: object
2.6
16
14.9
Betis - visitante
1994    0
2012    3
2049    1
2067    0
2087    1
2099    0
2120    0
2136    0
2159    3
2175    3
Name: FTR, dtype: object
1.1
Vallecano - local
1995    1
2010    0
2030    1
2056    3
2076    3
2102    1
2112    0
2131    0
2150    0
2174    3
Name: FTR, dtype: object
1.2
14
13.4
Getafe - visitante
1997    0
2018    0
2039    0
2060    0
2078    0
2101    3
2126    1
2146    0
2177    0
2195    0
Name: FTR, dtype: object
0.4
Villarreal - local
2006    0
2020    3
2046    3
2066    3
2087    1
2091    3
2111    3
2130    3
2141    3
2161    1
Name: FTR, dtype: object
2.3
12
10.4
Barcelona - visitante
2004    3
2010    3
2035    3
2040    3
2052    3
2077    3
2109    1
2145    1
2167    3
2188    3
Name: FTR, dtype: object
2.6
Valencia - local
2001    0
2021    0
2047    3
2062    0
2082    1
2103    1
2126    1
2145    1
2165    1
2185    3
Name: FTR, dtype: object
1.1
14
12.0
Celta - visitante
2007    0
2027    3
2045    0
2065    0
2076    0
2108    0
2124    3
2149    1
2168    0
2186    3
Name: FTR, dtype: object
1.0
Real Madrid - local
2007    3
2026    0
2048    3
2064    3
2083    3
2097    3
2114    3
2122    3
2146    3
2167    0
Name: FTR, dtype: object
2.4
44
19.4
Sevilla - visitante
2009    1
2023    0
2030    1
2054    1
2074    1
2105    0
2129    1
2147    1
2166    0
2184    0
Name: FTR, dtype: object
0.6
Espanol - local
2000    3
2012    0
2036    3
2051    0
2079    1
2109    1
2128    3
2140    1
2169    3
2181    1
Name: FTR, dtype: object
1.6
10
9.9
Ath Bilbao - visitante
2002    3
2021    3
2048    0
2068    3
2086    0
2096    0
2119    3
2133    0
2150    3
2163    0
Name: FTR, dtype: object
1.5
Sp Gijon - local
2002    0
2024    0
2040    0
2050    1
2057    1
2080    3
2101    0
2142    3
2162    0
2180    3
Name: FTR, dtype: object
1.1
16
11.6
Ath Madrid - visitante
2001    3
2026    3
2043    3
2070    0
2084    3
2095    3
2112    3
2123    0
2148    3
2164    3
Name: FTR, dtype: object
2.4
Sociedad - local
2003    1
2025    1
2041    3
2067    3
2088    1
2092    3
2121    0
2143    3
2166    3
2186    0
Name: FTR, dtype: object
1.8
16
14.9
Las Palmas - visitante
2006    3
2029    3
2042    0
2056    0
2071    0
2107    1
2128    0
2142    0
2165    1
2187    0
Name: FTR, dtype: object
0.8
La Coruna - local
2008    1
2022    0
2049    1
2061    1
2072    1
2104    0
2127    3
2147    1
2168    3
2189    1
Name: FTR, dtype: object
1.2
15
12.3
Levante - visitante
2003    1
2020    0
2044    0
2063    0
2090    0
2110    0
2125    0
2140    1
2162    3
2185    0
Name: FTR, dtype: object
0.5
Granada - local
1990    1
2011    3
2032    0
2053    0
2078    3
2105    3
2124    0
2148    0
2163    3
2197    1
Name: FTR, dtype: object
1.4
13
13.3
Vallecano - visitante
2000    0
2028    1
2050    1
2061    1
2082    1
2098    0
2122    0
2141    0
2160    1
2182    0
Name: FTR, dtype: object
0.5
Betis - local
2005    3
2028    1
2038    1
2055    3
2073    1
2106    0
2129    1
2149    1
2164    0
2183    0
Name: FTR, dtype: object
1.1
9
12.2
Malaga - visitante
2008    1
2025    1
2046    0
2069    3
2089    0
2093    1
2115    3
2131    3
2144    1
2169    0
Name: FTR, dtype: object
1.3
Getafe - local
2009    1
2027    0
2043    0
2068    0
2085    3
2099    3
2117    1
2139    1
2152    3
2160    1
Name: FTR, dtype: object
1.3
9
12.5
Eibar - visitante
1995    1
2013    0
2037    0
2058    0
2075    0
2106    3
2127    0
2143    0
2161    1
2193    0
Name: FTR, dtype: object
0.5
Granada - local
2011    3
2032    0
2053    0
2078    3
2105    3
2124    0
2148    0
2163    3
2197    1
2217    1
Name: FTR, dtype: object
1.4
13
13.5
Espanol - visitante
2024    3
2047    0
2064    0
2085    0
2094    0
2113    0
2137    0
2158    0
2173    0
2199    0
Name: FTR, dtype: object
0.3
Sevilla - local
2013    3
2042    3
2063    3
2089    3
2096    3
2113    3
2134    3
2151    3
2170    3
2195    3
Name: FTR, dtype: object
3.0
23
13.3
Villarreal - visitante
2016    1
2033    1
2059    1
2079    1
2104    3
2121    3
2152    0
2171    0
2192    1
2211    0
Name: FTR, dtype: object
1.1

Levante - local
2015    0
2039    3
2052    0
2071    3
2098    3
2115    0
2135    0
2159    0
2176    1
2191    0
Name: FTR, dtype: object
1.0
11
11.2
Valencia - visitante
2014    3
2032    3
2055    0
2072    1
2092    0
2111    0
2132    1
2151    0
2178    3
2194    0
Name: FTR, dtype: object
1.1
Las Palmas - local
2018    3
2035    0
2065    3
2084    0
2093    1
2116    3
2136    3
2155    0
2179    3
2192    1
Name: FTR, dtype: object
1.7
15
10.1
Real Madrid - visitante
2015    3
2031    1
2053    3
2073    1
2103    1
2130    0
2153    3
2170    0
2198    3
2212    1
Name: FTR, dtype: object
1.6
Ath Bilbao - local
2017    3
2034    0
2059    1
2075    3
2107    1
2125    3
2144    1
2173    3
2190    3
2213    3
Name: FTR, dtype: object
2.1
21
13.0
Betis - visitante
2012    3
2049    1
2067    0
2087    1
2099    0
2120    0
2136    0
2159    3
2175    3
2197    1
Name: FTR, dtype: object
1.2
Vallecano - local
2010    0
2030    1
2056    3
2076    3
2102    1
2112    0
2131    0
2150    0
2174    3
2199    3
Name: FTR, dtype: object
1.4
16
13.5
Eibar - visitante
2013    0
2037    0
2058    0
2075    0
2106    3
2127    0
2143    0
2161    1
2193    0
2216    3
Name: FTR, dtype: object
0.7
Celta - local
2016    1
2037    3
2054    1
2090    3
2095    0
2119    0
2137    3
2156    3
2178    0
2198    0
Name: FTR, dtype: object
1.4
13
13.3
Sociedad - visitante
2019    0
2034    3
2051    3
2080    0
2102    1
2114    0
2139    1
2157    0
2179    0
2191    3
Name: FTR, dtype: object
1.1
Barcelona - local
2023    3
2045    3
2070    3
2086    3
2100    3
2120    3
2138    1
2157    3
2171    3
2193    3
Name: FTR, dtype: object
2.8
36
16.1
Getafe - visitante
2018    0
2039    0
2060    0
2078    0
2101    3
2126    1
2146    0
2177    0
2195    0
2219    1
Name: FTR, dtype: object
0.5
Ath Madrid - local
2019    3
2033    1
2058    3
2074    1
2110    3
2133    3
2158    3
2172    3
2194    3
2212    1
Name: FTR, dtype: object
2.4
14
15.2
La Coruna - visitante
2017    0
2036    0
2057    1
2088    1
2097    0
2117    1
2138    1
2155    3
2176    1
2196    0
Name: FTR, dtype: object
0.8
Malaga - local
2014    0
2031    1
2060    3
2077    0
2108    3
2123    3
2154    1
2175    0
2196    3
2215    3
Name: FTR, dtype: object
1.7
16
11.9
Sp Gijon - visitante
2011    0
2038    1
2062    3
2083    0
2091    0
2118    0
2134    0
2156    0
2172    0
2190    0
Name: FTR, dtype: object
0.4
Espanol - local
2012    0
2036    3
2051    0
2079    1
2109    1
2128    3
2140    1
2169    3
2181    1
2218    0
Name: FTR, dtype: object
1.3
9
10.3
Vallecano - visitante
2028    1
2050    1
2061    1
2082    1
2098    0
2122    0
2141    0
2160    1
2182    0
2209    0
Name: FTR, dtype: object
0.5
Valencia - local
2021    0
2047    3
2062    0
2082    1
2103    1
2126    1
2145    1
2165    1
2185    3
2205    3
Name: FTR, dtype: object
1.4
16
11.6
Ath Madrid - visitante
2026    3
2043    3
2070    0
2084    3
2095    3
2112    3
2123    0
2148    3
2164    3
2189    1
Name: FTR, dtype: object
2.2
Sp Gijon - local
2024    0
2040    0
2050    1
2057    1
2080    3
2101    0
2142    3
2162    0
2180    3
2200    1
Name: FTR, dtype: object
1.2
19
12.7
Ath Bilbao - visitante
2021    3
2048    0
2068    3
2086    0
2096    0
2119    3
2133    0
2150    3
2163    0
2183    3
Name: FTR, dtype: object
1.5
Sociedad - local
2025    1
2041    3
2067    3
2088    1
2092    3
2121    0
2143    3
2166    3
2186    0
2202    0
Name: FTR, dtype: object
1.7
15
14.5
Levante - visitante
2020    0
2044    0
2063    0
2090    0
2110    0
2125    0
2140    1
2162    3
2185    0
2206    0
Name: FTR, dtype: object
0.4
Eibar - local
2029    0
2044    3
2069    0
2081    3
2094    3
2118    3
2132    1
2153    0
2177    3
2182    3
Name: FTR, dtype: object
1.9
17
13.4
Barcelona - visitante
2010    3
2035    3
2040    3
2052    3
2077    3
2109    1
2145    1
2167    3
2188    3
2214    0
Name: FTR, dtype: object
2.3
Betis - local
2028    1
2038    1
2055    3
2073    1
2106    0
2129    1
2149    1
2164    0
2183    0
2208    0
Name: FTR, dtype: object
0.8
8
13.3
Granada - visitante
2022    3
2041    0
2066    0
2081    0
2100    0
2116    0
2135    3
2154    1
2174    0
2181    1
Name: FTR, dtype: object
0.8
Villarreal - local
2020    3
2046    3
2066    3
2087    1
2091    3
2111    3
2130    3
2141    3
2161    1
2184    3
Name: FTR, dtype: object
2.6
14
10.2
Las Palmas - visitante
2029    3
2042    0
2056    0
2071    0
2107    1
2128    0
2142    0
2165    1
2187    0
2204    0
Name: FTR, dtype: object
0.5
Real Madrid - local
2026    0
2048    3
2064    3
2083    3
2097    3
2114    3
2122    3
2146    3
2167    0
2187    3
Name: FTR, dtype: object
2.4
40
19.1
Celta - visitante
2027    3
2045    0
2065    0
2076    0
2108    0
2124    3
2149    1
2168    0
2186    3
2201    3
Name: FTR, dtype: object
1.3
La Coruna - local
2022    0
2049    1
2061    1
2072    1
2104    0
2127    3
2147    1
2168    3
2189    1
2203    1
Name: FTR, dtype: object
1.2
14
12.5
Malaga - visitante
2025    1
2046    0
2069    3
2089    0
2093    1
2115    3
2131    3
2144    1
2169    0
2180    0
Name: FTR, dtype: object
1.2
Getafe - local
2027    0
2043    0
2068    0
2085    3
2099    3
2117    1
2139    1
2152    3
2160    1
2188    0
Name: FTR, dtype: object
1.2
8
11.8
Sevilla - visitante
2023    0
2030    1
2054    1
2074    1
2105    0
2129    1
2147    1
2166    0
2184    0
2207    1
Name: FTR, dtype: object
0.6
Vallecano - local
2030    1
2056    3
2076    3
2102    1
2112    0
2131    0
2150    0
2174    3
2199    3
2210    0
Name: FTR, dtype: object
1.4
15
15.0
Barcelona - visitante
2035    3
2040    3
2052    3
2077    3
2109    1
2145    1
2167    3
2188    3
2214    0
2235    0
Name: FTR, dtype: object
2.0
Granada - local
2032    0
2053    0
2078    3
2105    3
2124    0
2148    0
2163    3
2197    1
2217    1
2237    0
Name: FTR, dtype: object
1.1
11
13.3
Sp Gijon - visitante
2038    1
2062    3
2083    0
2091    0
2118    0
2134    0
2156    0
2172    0
2190    0
2218    3
Name: FTR, dtype: object
0.7
Espanol - local
2036    3
2051    0
2079    1
2109    1
2128    3
2140    1
2169    3
2181    1
2218    0
2238    3
Name: FTR, dtype: object
1.6
10
10.4
Betis - visitante
2049    1
2067    0
2087    1
2099    0
2120    0
2136    0
2159    3
2175    3
2197    1
2210    3
Name: FTR, dtype: object
1.2
Sevilla - local
2042    3
2063    3
2089    3
2096    3
2113    3
2134    3
2151    3
2170    3
2195    3
2214    3
Name: FTR, dtype: object
3.0
24
13.1
Eibar - visitante
2037    0
2058    0
2075    0
2106    3
2127    0
2143    0
2161    1
2193    0
2216    3
2233    1
Name: FTR, dtype: object
0.8
Malaga - local
2031    1
2060    3
2077    0
2108    3
2123    3
2154    1
2175    0
2196    3
2215    3
2232    0
Name: FTR, dtype: object
1.7
15
12.4
Valencia - visitante
2032    3
2055    0
2072    1
2092    0
2111    0
2132    1
2151    0
2178    3
2194    0
2213    0
Name: FTR, dtype: object
0.8
Levante - local
2039    3
2052    0
2071    3
2098    3
2115    0
2135    0
2159    0
2176    1
2191    0
2211    3
Name: FTR, dtype: object
1.3
11
11.6
Real Madrid - visitante
2031    1
2053    3
2073    1
2103    1
2130    0
2153    3
2170    0
2198    3
2212    1
2236    3
Name: FTR, dtype: object
1.6
Celta - local
2037    3
2054    1
2090    3
2095    0
2119    0
2137    3
2156    3
2178    0
2198    0
2219    1
Name: FTR, dtype: object
1.4
13
14.0
Villarreal - visitante
2033    1
2059    1
2079    1
2104    3
2121    3
2152    0
2171    0
2192    1
2211    0
2232    3
Name: FTR, dtype: object
1.3
Ath Bilbao - local
2034    0
2059    1
2075    3
2107    1
2125    3
2144    1
2173    3
2190    3
2213    3
2236    0
Name: FTR, dtype: object
1.8
18
12.9
La Coruna - visitante
2036    0
2057    1
2088    1
2097    0
2117    1
2138    1
2155    3
2176    1
2196    0
2217    1
Name: FTR, dtype: object
0.9
Las Palmas - local
2035    0
2065    3
2084    0
2093    1
2116    3
2136    3
2155    0
2179    3
2192    1
2216    0
Name: FTR, dtype: object
1.4
11
10.8
Getafe - visitante
2039    0
2060    0
2078    0
2101    3
2126    1
2146    0
2177    0
2195    0
2219    1
2239    0
Name: FTR, dtype: object
0.5
Ath Madrid - local
2033    1
2058    3
2074    1
2110    3
2133    3
2158    3
2172    3
2194    3
2212    1
2239    3
Name: FTR, dtype: object
2.4
13
15.2
Sociedad - visitante
2034    3
2051    3
2080    0
2102    1
2114    0
2139    1
2157    0
2179    0
2191    3
2215    0
Name: FTR, dtype: object
1.1
Villarreal - local
2046    3
2066    3
2087    1
2091    3
2111    3
2130    3
2141    3
2161    1
2184    3
2201    0
Name: FTR, dtype: object
2.3
12
10.5
Levante - visitante
2044    0
2063    0
2090    0
2110    0
2125    0
2140    1
2162    3
2185    0
2206    0
2223    0
Name: FTR, dtype: object
0.4
Valencia - local
2047    3
2062    0
2082    1
2103    1
2126    1
2145    1
2165    1
2185    3
2205    3
2229    3
Name: FTR, dtype: object
1.7
17
11.9
Ath Bilbao - visitante
2048    0
2068    3
2086    0
2096    0
2119    3
2133    0
2150    3
2163    0
2183    3
2203    1
Name: FTR, dtype: object
1.3
La Coruna - local
2049    1
2061    1
2072    1
2104    0
2127    3
2147    1
2168    3
2189    1
2203    1
2222    3
Name: FTR, dtype: object
1.5
17
12.6
Granada - visitante
2041    0
2066    0
2081    0
2100    0
2116    0
2135    3
2154    1
2174    0
2181    1
2200    1
Name: FTR, dtype: object
0.6
Barcelona - local
2045    3
2070    3
2086    3
2100    3
2120    3
2138    1
2157    3
2171    3
2193    3
2209    3
Name: FTR, dtype: object
2.8
39
15.8
Sevilla - visitante
2030    1
2054    1
2074    1
2105    0
2129    1
2147    1
2166    0
2184    0
2207    1
2234    0
Name: FTR, dtype: object
0.6
Sp Gijon - local
2040    0
2050    1
2057    1
2080    3
2101    0
2142    3
2162    0
2180    3
2200    1
2220    0
Name: FTR, dtype: object
1.2
18
13.3
Espanol - visitante
2047    0
2064    0
2085    0
2094    0
2113    0
2137    0
2158    0
2173    0
2199    0
2208    3
Name: FTR, dtype: object
0.3
Sociedad - local
2041    3
2067    3
2088    1
2092    3
2121    0
2143    3
2166    3
2186    0
2202    0
2221    1
Name: FTR, dtype: object
1.7
14
14.8
Malaga - visitante
2046    0
2069    3
2089    0
2093    1
2115    3
2131    3
2144    1
2169    0
2180    0
2205    0
Name: FTR, dtype: object
1.1
Real Madrid - local
2048    3
2064    3
2083    3
2097    3
2114    3
2122    3
2146    3
2167    0
2187    3
2206    3
Name: FTR, dtype: object
2.7
43
19.6
Ath Madrid - visitante
2043    3
2070    0
2084    3
2095    3
2112    3
2123    0
2148    3
2164    3
2189    1
2202    3
Name: FTR, dtype: object
2.2
Getafe - local
2043    0
2068    0
2085    3
2099    3
2117    1
2139    1
2152    3
2160    1
2188    0
2204    3
Name: FTR, dtype: object
1.5
12
11.8
Celta - visitante
2045    0
2065    0
2076    0
2108    0
2124    3
2149    1
2168    0
2186    3
2201    3
2227    1
Name: FTR, dtype: object
1.1
Betis - local
2038    1
2055    3
2073    1
2106    0
2129    1
2149    1
2164    0
2183    0
2208    0
2230    0
Name: FTR, dtype: object
0.7
7
12.2

Vallecano - visitante
2050    1
2061    1
2082    1
2098    0
2122    0
2141    0
2160    1
2182    0
2209    0
2225    0
Name: FTR, dtype: object
0.4
Eibar - local
2044    3
2069    0
2081    3
2094    3
2118    3
2132    1
2153    0
2177    3
2182    3
2207    1
Name: FTR, dtype: object
2.0
18
13.8
Las Palmas - visitante
2042    0
2056    0
2071    0
2107    1
2128    0
2142    0
2165    1
2187    0
2204    0
2228    0
Name: FTR, dtype: object
0.2
Vallecano - local
2056    3
2076    3
2102    1
2112    0
2131    0
2150    0
2174    3
2199    3
2210    0
2231    3
Name: FTR, dtype: object
1.6
15
15.5
Sevilla - visitante
2054    1
2074    1
2105    0
2129    1
2147    1
2166    0
2184    0
2207    1
2234    0
2259    1
Name: FTR, dtype: object
0.6
Malaga - local
2060    3
2077    0
2108    3
2123    3
2154    1
2175    0
2196    3
2215    3
2232    0
2251    1
Name: FTR, dtype: object
1.7
14
12.3
Real Madrid - visitante
2053    3
2073    1
2103    1
2130    0
2153    3
2170    0
2198    3
2212    1
2236    3
2256    3
Name: FTR, dtype: object
1.8
Granada - local
2053    0
2078    3
2105    3
2124    0
2148    0
2163    3
2197    1
2217    1
2237    0
2252    0
Name: FTR, dtype: object
1.1
11
13.1
Valencia - visitante
2055    0
2072    1
2092    0
2111    0
2132    1
2151    0
2178    3
2194    0
2213    0
2238    0
Name: FTR, dtype: object
0.5
Ath Madrid - local
2058    3
2074    1
2110    3
2133    3
2158    3
2172    3
2194    3
2212    1
2239    3
2258    0
Name: FTR, dtype: object
2.3
14
15.1
Villarreal - visitante
2059    1
2079    1
2104    3
2121    3
2152    0
2171    0
2192    1
2211    0
2232    3
2252    3
Name: FTR, dtype: object
1.5
Ath Bilbao - local
2059    1
2075    3
2107    1
2125    3
2144    1
2173    3
2190    3
2213    3
2236    0
2254    3
Name: FTR, dtype: object
2.1
21
13.4
Sociedad - visitante
2051    3
2080    0
2102    1
2114    0
2139    1
2157    0
2179    0
2191    3
2215    0
2237    3
Name: FTR, dtype: object
1.1
Las Palmas - local
2065    3
2084    0
2093    1
2116    3
2136    3
2155    0
2179    3
2192    1
2216    0
2234    3
Name: FTR, dtype: object
1.7
12
10.4
Barcelona - visitante
2040    3
2052    3
2077    3
2109    1
2145    1
2167    3
2188    3
2214    0
2235    0
2258    3
Name: FTR, dtype: object
2.0
Espanol - local
2051    0
2079    1
2109    1
2128    3
2140    1
2169    3
2181    1
2218    0
2238    3
2256    0
Name: FTR, dtype: object
1.3
9
10.2
La Coruna - visitante
2057    1
2088    1
2097    0
2117    1
2138    1
2155    3
2176    1
2196    0
2217    1
2230    3
Name: FTR, dtype: object
1.2
Celta - local
2054    1
2090    3
2095    0
2119    0
2137    3
2156    3
2178    0
2198    0
2219    1
2235    3
Name: FTR, dtype: object
1.4
14
14.4
Eibar - visitante
2058    0
2075    0
2106    3
2127    0
2143    0
2161    1
2193    0
2216    3
2233    1
2251    1
Name: FTR, dtype: object
0.9
Betis - local
2055    3
2073    1
2106    0
2129    1
2149    1
2164    0
2183    0
2208    0
2230    0
2257    3
Name: FTR, dtype: object
0.9
7
11.4
Sp Gijon - visitante
2062    3
2083    0
2091    0
2118    0
2134    0
2156    0
2172    0
2190    0
2218    3
2231    0
Name: FTR, dtype: object
0.6
Levante - local
2052    0
2071    3
2098    3
2115    0
2135    0
2159    0
2176    1
2191    0
2211    3
2233    1
Name: FTR, dtype: object
1.1
10
11.6
Getafe - visitante
2060    0
2078    0
2101    3
2126    1
2146    0
2177    0
2195    0
2219    1
2239    0
2254    0
Name: FTR, dtype: object
0.5
Sp Gijon - local
2050    1
2057    1
2080    3
2101    0
2142    3
2162    0
2180    3
2200    1
2220    0
2255    0
Name: FTR, dtype: object
1.2
17
14.3
Barcelona - visitante
2052    3
2077    3
2109    1
2145    1
2167    3
2188    3
2214    0
2235    0
2258    3
2274    3
Name: FTR, dtype: object
2.0
Sociedad - local
2067    3
2088    1
2092    3
2121    0
2143    3
2166    3
2186    0
2202    0
2221    1
2246    0
Name: FTR, dtype: object
1.4
13
14.6
Granada - visitante
2066    0
2081    0
2100    0
2116    0
2135    3
2154    1
2174    0
2181    1
2200    1
2229    0
Name: FTR, dtype: object
0.6
Sevilla - local
2063    3
2089    3
2096    3
2113    3
2134    3
2151    3
2170    3
2195    3
2214    3
2225    3
Name: FTR, dtype: object
3.0
25
13.9
Las Palmas - visitante
2056    0
2071    0
2107    1
2128    0
2142    0
2165    1
2187    0
2204    0
2228    0
2253    1
Name: FTR, dtype: object
0.3
Getafe - local
2068    0
2085    3
2099    3
2117    1
2139    1
2152    3
2160    1
2188    0
2204    3
2223    3
Name: FTR, dtype: object
1.8
15
12.2
Ath Madrid - visitante
2070    0
2084    3
2095    3
2112    3
2123    0
2148    3
2164    3
2189    1
2202    3
2224    0
Name: FTR, dtype: object
1.9
Eibar - local
2069    0
2081    3
2094    3
2118    3
2132    1
2153    0
2177    3
2182    3
2207    1
2227    1
Name: FTR, dtype: object
1.8
17
13.3
Levante - visitante
2063    0
2090    0
2110    0
2125    0
2140    1
2162    3
2185    0
2206    0
2223    0
2244    0
Name: FTR, dtype: object
0.4
Barcelona - local
2070    3
2086    3
2100    3
2120    3
2138    1
2157    3
2171    3
2193    3
2209    3
2228    3
Name: FTR, dtype: object
2.8
35
15.7
Celta - visitante
2065    0
2076    0
2108    0
2124    3
2149    1
2168    0
2186    3
2201    3
2227    1
2241    3
Name: FTR, dtype: object
1.4
Villarreal - local
2066    3
2087    1
2091    3
2111    3
2130    3
2141    3
2161    1
2184    3
2201    0
2224    3
Name: FTR, dtype: object
2.3
12
9.8
Malaga - visitante
2069    3
2089    0
2093    1
2115    3
2131    3
2144    1
2169    0
2180    0
2205    0
2226    1
Name: FTR, dtype: object
1.2
Valencia - local
2062    0
2082    1
2103    1
2126    1
2145    1
2165    1
2185    3
2205    3
2229    3
2245    1
Name: FTR, dtype: object
1.5
15
12.4
Espanol - visitante
2064    0
2085    0
2094    0
2113    0
2137    0
2158    0
2173    0
2199    0
2208    3
2222    0
Name: FTR, dtype: object
0.3
Real Madrid - local
2064    3
2083    3
2097    3
2114    3
2122    3
2146    3
2167    0
2187    3
2206    3
2226    1
Name: FTR, dtype: object
2.5
39
20.8
Ath Bilbao - visitante
2068    3
2086    0
2096    0
2119    3
2133    0
2150    3
2163    0
2183    3
2203    1
2221    1
Name: FTR, dtype: object
1.4
La Coruna - local
2061    1
2072    1
2104    0
2127    3
2147    1
2168    3
2189    1
2203    1
2222    3
2243    0
Name: FTR, dtype: object
1.4
17
12.0
Betis - visitante
2067    0
2087    1
2099    0
2120    0
2136    0
2159    3
2175    3
2197    1
2210    3
2220    3
Name: FTR, dtype: object
1.4
Sp Gijon - local
2057    1
2080    3
2101    0
2142    3
2162    0
2180    3
2200    1
2220    0
2255    0
2271    1
Name: FTR, dtype: object
1.2
15
13.8
Vallecano - visitante
2061    1
2082    1
2098    0
2122    0
2141    0
2160    1
2182    0
2209    0
2225    0
2242    3
Name: FTR, dtype: object
0.6
Espanol - local
2079    1
2109    1
2128    3
2140    1
2169    3
2181    1
2218    0
2238    3
2256    0
2277    3
Name: FTR, dtype: object
1.6
10
10.1
Sociedad - visitante
2080    0
2102    1
2114    0
2139    1
2157    0
2179    0
2191    3
2215    0
2237    3
2257    0
Name: FTR, dtype: object
0.8
Levante - local
2071    3
2098    3
2115    0
2135    0
2159    0
2176    1
2191    0
2211    3
2233    1
2259    1
Name: FTR, dtype: object
1.2
11
11.9
Barcelona - visitante
2077    3
2109    1
2145    1
2167    3
2188    3
2214    0
2235    0
2258    3
2274    3
2299    3
Name: FTR, dtype: object
2.0
Granada - local
2078    3
2105    3
2124    0
2148    0
2163    3
2197    1
2217    1
2237    0
2252    0
2270    0
Name: FTR, dtype: object
1.1
11
12.9
Real Madrid - visitante
2073    1
2103    1
2130    0
2153    3
2170    0
2198    3
2212    1
2236    3
2256    3
2271    1
Name: FTR, dtype: object
1.6
Celta - local
2090    3
2095    0
2119    0
2137    3
2156    3
2178    0
2198    0
2219    1
2235    3
2253    1
Name: FTR, dtype: object
1.4
16
14.5
Sevilla - visitante
2074    1
2105    0
2129    1
2147    1
2166    0
2184    0
2207    1
2234    0
2259    1
2279    1
Name: FTR, dtype: object
0.6
Betis - local
2073    1
2106    0
2129    1
2149    1
2164    0
2183    0
2208    0
2230    0
2257    3
2273    1
Name: FTR, dtype: object
0.7
7
13.0
Valencia - visitante
2072    1
2092    0
2111    0
2132    1
2151    0
2178    3
2194    0
2213    0
2238    0
2255    3
Name: FTR, dtype: object
0.8
Vallecano - local
2076    3
2102    1
2112    0
2131    0
2150    0
2174    3
2199    3
2210    0
2231    3
2250    0
Name: FTR, dtype: object
1.3
14
14.5
Las Palmas - visitante
2071    0
2107    1
2128    0
2142    0
2165    1
2187    0
2204    0
2228    0
2253    1
2278    0
Name: FTR, dtype: object
0.3
Sp Gijon - local
2080    3
2101    0
2142    3
2162    0
2180    3
2200    1
2220    0
2255    0
2271    1
3432    3
Name: FTR, dtype: object
1.4
16
13.9
La Coruna - visitante
2088    1
2097    0
2117    1
2138    1
2155    3
2176    1
2196    0
2217    1
2230    3
2250    3
Name: FTR, dtype: object
1.4
Ath Madrid - local
2074    1
2110    3
2133    3
2158    3
2172    3
2194    3
2212    1
2239    3
2258    0
2278    3
Name: FTR, dtype: object
2.3
12
15.2
Eibar - visitante
2075    0
2106    3
2127    0
2143    0
2161    1
2193    0
2216    3
2233    1
2251    1
2270    3
Name: FTR, dtype: object
1.2
Ath Bilbao - local
2075    3
2107    1
2125    3
2144    1
2173    3
2190    3
2213    3
2236    0
2254    3
2274    0
Name: FTR, dtype: object
2.0
21
13.2
Villarreal - visitante
2079    1
2104    3
2121    3
2152    0
2171    0
2192    1
2211    0
2232    3
2252    3
2273    1
Name: FTR, dtype: object
1.5
Malaga - local
2077    0
2108    3
2123    3
2154    1
2175    0
2196    3
2215    3
2232    0
2251    1
2279    1
Name: FTR, dtype: object
1.5
11
14.0
Getafe - visitante
2078    0
2101    3
2126    1
2146    0
2177    0
2195    0
2219    1
2239    0
2254    0
2277    0
Name: FTR, dtype: object
0.5
La Coruna - local
2072    1
2104    0
2127    3
2147    1
2168    3
2189    1
2203    1
2222    3
2243    0
2276    1
Name: FTR, dtype: object
1.4
15
11.8
Vallecano - visitante
2082    1
2098    0
2122    0
2141    0
2160    1
2182    0
2209    0
2225    0
2242    3
2267    0
Name: FTR, dtype: object
0.5
Valencia - local
2082    1
2103    1
2126    1
2145    1
2165    1
2185    3
2205    3
2229    3
2245    1
2260    1
Name: FTR, dtype: object
1.6
16
12.0
Sp Gijon - visitante
2083    0
2091    0
2118    0
2134    0
2156    0
2172    0
2190    0
2218    3
2231    0
2243    3
Name: FTR, dtype: object
0.6
Sevilla - local
2089    3
2096    3
2113    3
2134    3
2151    3
2170    3
2195    3
2214    3
2225    3
2241    0
Name: FTR, dtype: object
2.7
23
13.8
Levante - visitante
2090    0
2110    0
2125    0
2140    1
2162    3
2185    0
2206    0
2223    0
2244    0
2262    1

Name: FTR, dtype: object
0.5
Real Madrid - local
2083    3
2097    3
2114    3
2122    3
2146    3
2167    0
2187    3
2206    3
2226    1
2247    3
Name: FTR, dtype: object
2.5
34
21.0
Espanol - visitante
2085    0
2094    0
2113    0
2137    0
2158    0
2173    0
2199    0
2208    3
2222    0
2246    3
Name: FTR, dtype: object
0.6
Las Palmas - local
2084    0
2093    1
2116    3
2136    3
2155    0
2179    3
2192    1
2216    0
2234    3
2242    0
Name: FTR, dtype: object
1.4
10
9.9
Celta - visitante
2076    0
2108    0
2124    3
2149    1
2168    0
2186    3
2201    3
2227    1
2241    3
2272    3
Name: FTR, dtype: object
1.7
Villarreal - local
2087    1
2091    3
2111    3
2130    3
2141    3
2161    1
2184    3
2201    0
2224    3
2240    3
Name: FTR, dtype: object
2.3
14
10.0
Granada - visitante
2081    0
2100    0
2116    0
2135    3
2154    1
2174    0
2181    1
2200    1
2229    0
2247    0
Name: FTR, dtype: object
0.6
Sociedad - local
2088    1
2092    3
2121    0
2143    3
2166    3
2186    0
2202    0
2221    1
2246    0
2265    1
Name: FTR, dtype: object
1.2
11
14.7
Betis - visitante
2087    1
2099    0
2120    0
2136    0
2159    3
2175    3
2197    1
2210    3
2220    3
2245    1
Name: FTR, dtype: object
1.5
Getafe - local
2085    3
2099    3
2117    1
2139    1
2152    3
2160    1
2188    0
2204    3
2223    3
2249    3
Name: FTR, dtype: object
2.1
16
12.1
Ath Bilbao - visitante
2086    0
2096    0
2119    3
2133    0
2150    3
2163    0
2183    3
2203    1
2221    1
2240    0
Name: FTR, dtype: object
1.1
Eibar - local
2081    3
2094    3
2118    3
2132    1
2153    0
2177    3
2182    3
2207    1
2227    1
2248    0
Name: FTR, dtype: object
1.8
16
13.1
Malaga - visitante
2089    0
2093    1
2115    3
2131    3
2144    1
2169    0
2180    0
2205    0
2226    1
2249    0
Name: FTR, dtype: object
0.9
Barcelona - local
2086    3
2100    3
2120    3
2138    1
2157    3
2171    3
2193    3
2209    3
2228    3
2244    3
Name: FTR, dtype: object
2.8
37
16.8
Ath Madrid - visitante
2084    3
2095    3
2112    3
2123    0
2148    3
2164    3
2189    1
2202    3
2224    0
2248    3
Name: FTR, dtype: object
2.2
Levante - local
2098    3
2115    0
2135    0
2159    0
2176    1
2191    0
2211    3
2233    1
2259    1
2272    0
Name: FTR, dtype: object
0.9
9
11.8
Las Palmas - visitante
2107    1
2128    0
2142    0
2165    1
2187    0
2204    0
2228    0
2253    1
2278    0
Name: FTR, dtype: object
0.3333333333333333
La Coruna - local
2104    0
2127    3
2147    1
2168    3
2189    1
2203    1
2222    3
2243    0
2276    1
2294    3
Name: FTR, dtype: object
1.6
16
11.8
Valencia - visitante
2092    0
2111    0
2132    1
2151    0
2178    3
2194    0
2213    0
2238    0
2255    3
2275    1
Name: FTR, dtype: object
0.8
Betis - local
2106    0
2129    1
2149    1
2164    0
2183    0
2208    0
2230    0
2257    3
2273    1
2675    3
Name: FTR, dtype: object
0.9
10
14.7
Real Madrid - visitante
2103    1
2130    0
2153    3
2170    0
2198    3
2212    1
2236    3
2256    3
2271    1
2296    3
Name: FTR, dtype: object
1.8
Ath Madrid - local
2110    3
2133    3
2158    3
2172    3
2194    3
2212    1
2239    3
2258    0
2278    3
2299    0
Name: FTR, dtype: object
2.2
12
14.1
Sevilla - visitante
2105    0
2129    1
2147    1
2166    0
2184    0
2207    1
2234    0
2259    1
2279    1
2282    3
Name: FTR, dtype: object
0.8
Ath Bilbao - local
2107    1
2125    3
2144    1
2173    3
2190    3
2213    3
2236    0
2254    3
2274    0
2288    3
Name: FTR, dtype: object
2.0
20
13.9
Eibar - visitante
2106    3
2127    0
2143    0
2161    1
2193    0
2216    3
2233    1
2251    1
2270    3
2295    1
Name: FTR, dtype: object
1.3
Vallecano - local
2102    1
2112    0
2131    0
2150    0
2174    3
2199    3
2210    0
2231    3
2250    0
2275    1
Name: FTR, dtype: object
1.1
11
12.7
Celta - visitante
2108    0
2124    3
2149    1
2168    0
2186    3
2201    3
2227    1
2241    3
2272    3
2291    1
Name: FTR, dtype: object
1.8
Malaga - local
2108    3
2123    3
2154    1
2175    0
2196    3
2215    3
2232    0
2251    1
2279    1
2282    0
Name: FTR, dtype: object
1.5
12
14.1
Barcelona - visitante
2109    1
2145    1
2167    3
2188    3
2214    0
2235    0
2258    3
2274    3
2299    3
2317    3
Name: FTR, dtype: object
2.0
Granada - local
2105    3
2124    0
2148    0
2163    3
2197    1
2217    1
2237    0
2252    0
2270    0
2284    1
Name: FTR, dtype: object
0.9
8
11.1
Getafe - visitante
2101    3
2126    1
2146    0
2177    0
2195    0
2219    1
2239    0
2254    0
2277    0
2281    0
Name: FTR, dtype: object
0.5
Espanol - local
2109    1
2128    3
2140    1
2169    3
2181    1
2218    0
2238    3
2256    0
2277    3
2296    0
Name: FTR, dtype: object
1.5
9
10.5
Villarreal - visitante
2104    3
2121    3
2152    0
2171    0
2192    1
2211    0
2232    3
2252    3
2273    1
2288    0
Name: FTR, dtype: object
1.4
Sp Gijon - local
2101    0
2142    3
2162    0
2180    3
2200    1
2220    0
2255    0
2271    1
3432    3
3447    0
Name: FTR, dtype: object
1.1
13
15.0
Sociedad - visitante
2102    1
2114    0
2139    1
2157    0
2179    0
2191    3
2215    0
2237    3
2257    0
2276    1
Name: FTR, dtype: object
0.9
Eibar - local
2094    3
2118    3
2132    1
2153    0
2177    3
2182    3
2207    1
2227    1
2248    0
2264    3
Name: FTR, dtype: object
1.8
13
12.8
Granada - visitante
2100    0
2116    0
2135    3
2154    1
2174    0
2181    1
2200    1
2229    0
2247    0
2263    3
Name: FTR, dtype: object
0.9
Valencia - local
2103    1
2126    1
2145    1
2165    1
2185    3
2205    3
2229    3
2245    1
2260    1
2291    1
Name: FTR, dtype: object
1.6
15
12.8
Vallecano - visitante
2098    0
2122    0
2141    0
2160    1
2182    0
2209    0
2225    0
2242    3
2267    0
2298    3
Name: FTR, dtype: object
0.7
Real Madrid - local
2097    3
2114    3
2122    3
2146    3
2167    0
2187    3
2206    3
2226    1
2247    3
2266    3
Name: FTR, dtype: object
2.5
34
21.4
Sp Gijon - visitante
2091    0
2118    0
2134    0
2156    0
2172    0
2190    0
2218    3
2231    0
2243    3
2265    1
Name: FTR, dtype: object
0.7
Las Palmas - local
2093    1
2116    3
2136    3
2155    0
2179    3
2192    1
2216    0
2234    3
2242    0
2262    1
Name: FTR, dtype: object
1.5
10
10.4
Ath Madrid - visitante
2095    3
2112    3
2123    0
2148    3
2164    3
2189    1
2202    3
2224    0
2248    3
2261    3
Name: FTR, dtype: object
2.2
Getafe - local
2099    3
2117    1
2139    1
2152    3
2160    1
2188    0
2204    3
2223    3
2249    3
2263    0
Name: FTR, dtype: object
1.8
14
11.9
Espanol - visitante
2094    0
2113    0
2137    0
2158    0
2173    0
2199    0
2208    3
2222    0
2246    3
2269    0
Name: FTR, dtype: object
0.6
Barcelona - local
2100    3
2120    3
2138    1
2157    3
2171    3
2193    3
2209    3
2228    3
2244    3
2268    3
Name: FTR, dtype: object
2.8
32
17.0
Ath Bilbao - visitante
2096    0
2119    3
2133    0
2150    3
2163    0
2183    3
2203    1
2221    1
2240    0
2264    0
Name: FTR, dtype: object
1.1
Villarreal - local
2091    3
2111    3
2130    3
2141    3
2161    1
2184    3
2201    0
2224    3
2240    3
2269    3
Name: FTR, dtype: object
2.5
17
10.5
Betis - visitante
2099    0
2120    0
2136    0
2159    3
2175    3
2197    1
2210    3
2220    3
2245    1
2266    0
Name: FTR, dtype: object
1.4
Sociedad - local
2092    3
2121    0
2143    3
2166    3
2186    0
2202    0
2221    1
2246    0
2265    1
2292    0
Name: FTR, dtype: object
1.1
10
13.8
La Coruna - visitante
2097    0
2117    1
2138    1
2155    3
2176    1
2196    0
2217    1
2230    3
2250    3
2260    1
Name: FTR, dtype: object
1.4
Sevilla - local
2096    3
2113    3
2134    3
2151    3
2170    3
2195    3
2214    3
2225    3
2241    0
2261    0
Name: FTR, dtype: object
2.4
21
15.5
Malaga - visitante
2093    1
2115    3
2131    3
2144    1
2169    0
2180    0
2205    0
2226    1
2249    0
2268    0
Name: FTR, dtype: object
0.9
Celta - local
2095    0
2119    0
2137    3
2156    3
2178    0
2198    0
2219    1
2235    3
2253    1
2267    3
Name: FTR, dtype: object
1.4
15
14.2
Levante - visitante
2110    0
2125    0
2140    1
2162    3
2185    0
2206    0
2223    0
2244    0
2262    1
2294    0
Name: FTR, dtype: object
0.5
Villarreal - local
2111    3
2130    3
2141    3
2161    1
2184    3
2201    0
2224    3
2240    3
2269    3
2290    3
Name: FTR, dtype: object
2.5
17
10.6
Sp Gijon - visitante
2118    0
2134    0
2156    0
2172    0
2190    0
2218    3
2231    0
2243    3
2265    1
3424    0
Name: FTR, dtype: object
0.7
Sociedad - local
2121    0
2143    3
2166    3
2186    0
2202    0
2221    1
2246    0
2265    1
2292    0
2319    3
Name: FTR, dtype: object
1.1
11
12.3
Valencia - visitante
2111    0
2132    1
2151    0
2178    3
2194    0
2213    0
2238    0
2255    3
2275    1
2289    3
Name: FTR, dtype: object
1.1
Las Palmas - local
2116    3
2136    3
2155    0
2179    3
2192    1
2216    0
2234    3
2242    0
2262    1
Name: FTR, dtype: object
1.5555555555555556
9
11.0
Malaga - visitante
2115    3
2131    3
2144    1
2169    0
2180    0
2205    0
2226    1
2249    0
2268    0
2290    0
Name: FTR, dtype: object
0.8
Eibar - local
2118    3
2132    1
2153    0
2177    3
2182    3
2207    1
2227    1
2248    0
2264    3
2285    3
Name: FTR, dtype: object
1.8
14
12.0
Espanol - visitante
2113    0
2137    0
2158    0
2173    0
2199    0
2208    3
2222    0
2246    3
2269    0
2286    0
Name: FTR, dtype: object
0.6
Celta - local
2119    0
2137    3
2156    3
2178    0
2198    0
2219    1
2235    3
2253    1
2267    3
2286    3
Name: FTR, dtype: object
1.7
18
14.6
Ath Madrid - visitante
2112    3
2123    0
2148    3
2164    3
2189    1
2202    3
2224    0
2248    3
2261    3
2284    1
Name: FTR, dtype: object
2.0
Sevilla - local
2113    3
2134    3
2151    3
2170    3
2195    3
2214    3
2225    3
2241    0
2261    0
2293    3
Name: FTR, dtype: object
2.4
21
16.6
Ath Bilbao - visitante
2119    3
2133    0
2150    3
2163    0
2183    3
2203    1
2221    1
2240    0
2264    0
2297    3
Name: FTR, dtype: object
1.4
Real Madrid - local
2114    3
2122    3
2146    3
2167    0
2187    3
2206    3
2226    1
2247    3
2266    3
2281    3
Name: FTR, dtype: object
2.5
36
20.9
La Coruna - visitante
2117    1
2138    1
2155    3
2176    1
2196    0
2217    1
2230    3
2250    3
2260    1
2287    1
Name: FTR, dtype: object
1.5
Levante - local
2115    0
2135    0
2159    0
2176    1
2191    0
2211    3
2233    1
2259    1
2272    0
2283    1
Name: FTR, dtype: object
0.7
7
11.6
Vallecano - visitante
2122    0
2141    0
2160    1
2182    0
2209    0
2225    0
2242    3
2267    0
2298    3
2314    1

Name: FTR, dtype: object
0.8
Getafe - local
2117    1
2139    1
2152    3
2160    1
2188    0
2204    3
2223    3
2249    3
2263    0
2295    1
Name: FTR, dtype: object
1.6
14
12.4
Betis - visitante
2120    0
2136    0
2159    3
2175    3
2197    1
2210    3
2220    3
2245    1
2266    0
2664    0
Name: FTR, dtype: object
1.4
Barcelona - local
2120    3
2138    1
2157    3
2171    3
2193    3
2209    3
2228    3
2244    3
2268    3
2287    1
Name: FTR, dtype: object
2.6
30
17.1
Granada - visitante
2116    0
2135    3
2154    1
2174    0
2181    1
2200    1
2229    0
2247    0
2263    3
2292    3
Name: FTR, dtype: object
1.2
Sp Gijon - local
2142    3
2162    0
2180    3
2200    1
2220    0
2255    0
2271    1
3432    3
3447    0
3466    3
Name: FTR, dtype: object
1.4
14
14.9
Getafe - visitante
2126    1
2146    0
2177    0
2195    0
2219    1
2239    0
2254    0
2277    0
2281    0
2300    0
Name: FTR, dtype: object
0.2
Vallecano - local
2112    0
2131    0
2150    0
2174    3
2199    3
2210    0
2231    3
2250    0
2275    1
2280    0
Name: FTR, dtype: object
1.0
11
12.8
Sociedad - visitante
2114    0
2139    1
2157    0
2179    0
2191    3
2215    0
2237    3
2257    0
2276    1
2280    3
Name: FTR, dtype: object
1.1
Valencia - local
2126    1
2145    1
2165    1
2185    3
2205    3
2229    3
2245    1
2260    1
2291    1
2311    3
Name: FTR, dtype: object
1.8
16
13.0
Real Madrid - visitante
2130    0
2153    3
2170    0
2198    3
2212    1
2236    3
2256    3
2271    1
2296    3
2315    3
Name: FTR, dtype: object
2.0
La Coruna - local
2127    3
2147    1
2168    3
2189    1
2203    1
2222    3
2243    0
2276    1
2294    3
2316    1
Name: FTR, dtype: object
1.7
16
11.6
Villarreal - visitante
2121    3
2152    0
2171    0
2192    1
2211    0
2232    3
2252    3
2273    1
2288    0
2316    1
Name: FTR, dtype: object
1.2
Granada - local
2124    0
2148    0
2163    3
2197    1
2217    1
2237    0
2252    0
2270    0
2284    1
2306    3
Name: FTR, dtype: object
0.9
8
12.3
Sevilla - visitante
2129    1
2147    1
2166    0
2184    0
2207    1
2234    0
2259    1
2279    1
2282    3
2303    1
Name: FTR, dtype: object
0.9
Betis - local
2129    1
2149    1
2164    0
2183    0
2208    0
2230    0
2257    3
2273    1
2675    3
2699    0
Name: FTR, dtype: object
0.9
10
15.2
Eibar - visitante
2127    0
2143    0
2161    1
2193    0
2216    3
2233    1
2251    1
2270    3
2295    1
2311    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
2125    3
2144    1
2173    3
2190    3
2213    3
2236    0
2254    3
2274    0
2288    3
2308    1
Name: FTR, dtype: object
2.0
19
13.4
Las Palmas - visitante
2128    0
2142    0
2165    1
2187    0
2204    0
2228    0
2253    1
2278    0
Name: FTR, dtype: object
0.25
Malaga - local
2123    3
2154    1
2175    0
2196    3
2215    3
2232    0
2251    1
2279    1
2282    0
2312    0
Name: FTR, dtype: object
1.2
11
14.8
Celta - visitante
2124    3
2149    1
2168    0
2186    3
2201    3
2227    1
2241    3
2272    3
2291    1
2310    1
Name: FTR, dtype: object
1.9
Espanol - local
2128    3
2140    1
2169    3
2181    1
2218    0
2238    3
2256    0
2277    3
2296    0
2314    1
Name: FTR, dtype: object
1.5
10
11.3
Barcelona - visitante
2145    1
2167    3
2188    3
2214    0
2235    0
2258    3
2274    3
2299    3
2317    3
2337    3
Name: FTR, dtype: object
2.2
Ath Madrid - local
2133    3
2158    3
2172    3
2194    3
2212    1
2239    3
2258    0
2278    3
2299    0
2318    1
Name: FTR, dtype: object
2.0
11
13.5
Levante - visitante
2125    0
2140    1
2162    3
2185    0
2206    0
2223    0
2244    0
2262    1
2294    0
2319    0
Name: FTR, dtype: object
0.5
Villarreal - local
2130    3
2141    3
2161    1
2184    3
2201    0
2224    3
2240    3
2269    3
2290    3
2301    3
Name: FTR, dtype: object
2.5
17
10.9
Valencia - visitante
2132    1
2151    0
2178    3
2194    0
2213    0
2238    0
2255    3
2275    1
2289    3
2305    1
Name: FTR, dtype: object
1.2
Vallecano - local
2131    0
2150    0
2174    3
2199    3
2210    0
2231    3
2250    0
2275    1
2280    0
2300    3
Name: FTR, dtype: object
1.3
13
13.3
Ath Madrid - visitante
2123    0
2148    3
2164    3
2189    1
2202    3
2224    0
2248    3
2261    3
2284    1
2302    1
Name: FTR, dtype: object
1.8
Sevilla - local
2134    3
2151    3
2170    3
2195    3
2214    3
2225    3
2241    0
2261    0
2293    3
2315    0
Name: FTR, dtype: object
2.1
21
16.9
Espanol - visitante
2137    0
2158    0
2173    0
2199    0
2208    3
2222    0
2246    3
2269    0
2286    0
2309    3
Name: FTR, dtype: object
0.9
Real Madrid - local
2122    3
2146    3
2167    0
2187    3
2206    3
2226    1
2247    3
2266    3
2281    3
2305    1
Name: FTR, dtype: object
2.3
35
21.5
Sociedad - visitante
2139    1
2157    0
2179    0
2191    3
2215    0
2237    3
2257    0
2276    1
2280    3
2307    0
Name: FTR, dtype: object
1.1
Levante - local
2135    0
2159    0
2176    1
2191    0
2211    3
2233    1
2259    1
2272    0
2283    1
2302    1
Name: FTR, dtype: object
0.8
9
11.7
Malaga - visitante
2131    3
2144    1
2169    0
2180    0
2205    0
2226    1
2249    0
2268    0
2290    0
2304    3
Name: FTR, dtype: object
0.8
Las Palmas - local
2136    3
2155    0
2179    3
2192    1
2216    0
2234    3
2242    0
2262    1
Name: FTR, dtype: object
1.375
5
11.5
Granada - visitante
2135    3
2154    1
2174    0
2181    1
2200    1
2229    0
2247    0
2263    3
2292    3
2313    3
Name: FTR, dtype: object
1.5
Getafe - local
2139    1
2152    3
2160    1
2188    0
2204    3
2223    3
2249    3
2263    0
2295    1
2313    0
Name: FTR, dtype: object
1.5
15
12.6
La Coruna - visitante
2138    1
2155    3
2176    1
2196    0
2217    1
2230    3
2250    3
2260    1
2287    1
2308    1
Name: FTR, dtype: object
1.5
Eibar - local
2132    1
2153    0
2177    3
2182    3
2207    1
2227    1
2248    0
2264    3
2285    3
2309    0
Name: FTR, dtype: object
1.5
12
11.2
Sp Gijon - visitante
2134    0
2156    0
2172    0
2190    0
2218    3
2231    0
2243    3
2265    1
3424    0
3459    3
Name: FTR, dtype: object
1.0
Celta - local
2137    3
2156    3
2178    0
2198    0
2219    1
2235    3
2253    1
2267    3
2286    3
2303    1
Name: FTR, dtype: object
1.8
19
15.2
Ath Bilbao - visitante
2133    0
2150    3
2163    0
2183    3
2203    1
2221    1
2240    0
2264    0
2297    3
2318    1
Name: FTR, dtype: object
1.2
Barcelona - local
2138    1
2157    3
2171    3
2193    3
2209    3
2228    3
2244    3
2268    3
2287    1
2307    3
Name: FTR, dtype: object
2.6
28
17.0
Betis - visitante
2136    0
2159    3
2175    3
2197    1
2210    3
2220    3
2245    1
2266    0
2664    0
2685    0
Name: FTR, dtype: object
1.4
Sociedad - local
2143    3
2166    3
2186    0
2202    0
2221    1
2246    0
2265    1
2292    0
2319    3
2335    1
Name: FTR, dtype: object
1.2
11
12.0
Villarreal - visitante
2152    0
2171    0
2192    1
2211    0
2232    3
2252    3
2273    1
2288    0
2316    1
2335    1
Name: FTR, dtype: object
1.0
Real Madrid - local
2146    3
2167    0
2187    3
2206    3
2226    1
2247    3
2266    3
2281    3
2305    1
2323    3
Name: FTR, dtype: object
2.3
28
20.3
Vallecano - visitante
2141    0
2160    1
2182    0
2209    0
2225    0
2242    3
2267    0
2298    3
2314    1
2331    0
Name: FTR, dtype: object
0.8
Malaga - local
2154    1
2175    0
2196    3
2215    3
2232    0
2251    1
2279    1
2282    0
2312    0
2332    1
Name: FTR, dtype: object
1.0
11
14.5
Ath Madrid - visitante
2148    3
2164    3
2189    1
2202    3
2224    0
2248    3
2261    3
2284    1
2302    1
2322    3
Name: FTR, dtype: object
2.1
Granada - local
2148    0
2163    3
2197    1
2217    1
2237    0
2252    0
2270    0
2284    1
2306    3
2321    0
Name: FTR, dtype: object
0.9
9
12.8
Celta - visitante
2149    1
2168    0
2186    3
2201    3
2227    1
2241    3
2272    3
2291    1
2310    1
2344    3
Name: FTR, dtype: object
1.9
Ath Bilbao - local
2144    1
2173    3
2190    3
2213    3
2236    0
2254    3
2274    0
2288    3
2308    1
2329    1
Name: FTR, dtype: object
1.8
18
12.7
Levante - visitante
2140    1
2162    3
2185    0
2206    0
2223    0
2244    0
2262    1
2294    0
2319    0
2336    3
Name: FTR, dtype: object
0.8
Valencia - local
2145    1
2165    1
2185    3
2205    3
2229    3
2245    1
2260    1
2291    1
2311    3
2330    3
Name: FTR, dtype: object
2.0
18
13.1
Getafe - visitante
2146    0
2177    0
2195    0
2219    1
2239    0
2254    0
2277    0
2281    0
2300    0
2328    0
Name: FTR, dtype: object
0.1
La Coruna - local
2147    1
2168    3
2189    1
2203    1
2222    3
2243    0
2276    1
2294    3
2316    1
2346    0
Name: FTR, dtype: object
1.4
15
11.2
Eibar - visitante
2143    0
2161    1
2193    0
2216    3
2233    1
2251    1
2270    3
2295    1
2311    0
2334    0
Name: FTR, dtype: object
1.0
Espanol - local
2140    1
2169    3
2181    1
2218    0
2238    3
2256    0
2277    3
2296    0
2314    1
2337    0
Name: FTR, dtype: object
1.2
9
10.8
Las Palmas - visitante
2142    0
2165    1
2187    0
2204    0
2228    0
2253    1
2278    0
Name: FTR, dtype: object
0.2857142857142857
Betis - local
2149    1
2164    0
2183    0
2208    0
2230    0
2257    3
2273    1
2675    3
2699    0
2714    0
Name: FTR, dtype: object
0.8
10
15.7
Sevilla - visitante
2147    1
2166    0
2184    0
2207    1
2234    0
2259    1
2279    1
2282    3
2303    1
2325    3
Name: FTR, dtype: object
1.1
Villarreal - local
2141    3
2161    1
2184    3
2201    0
2224    3
2240    3
2269    3
2290    3
2301    3
2322    0
Name: FTR, dtype: object
2.2
16
11.5
Real Madrid - visitante
2153    3
2170    0
2198    3
2212    1
2236    3
2256    3
2271    1
2296    3
2315    3
2333    3
Name: FTR, dtype: object
2.3
Vallecano - local
2150    0
2174    3
2199    3
2210    0
2231    3
2250    0
2275    1
2280    0
2300    3
2320    1
Name: FTR, dtype: object
1.4
13
12.9
Malaga - visitante
2144    1
2169    0
2180    0
2205    0
2226    1
2249    0
2268    0
2290    0
2304    3
2326    0
Name: FTR, dtype: object
0.5
Eibar - local
2153    0
2177    3
2182    3
2207    1
2227    1
2248    0
2264    3
2285    3
2309    0
2325    0
Name: FTR, dtype: object
1.4
12
11.3
Valencia - visitante
2151    0
2178    3
2194    0
2213    0
2238    0
2255    3
2275    1
2289    3
2305    1
2320    1
Name: FTR, dtype: object
1.2
Ath Madrid - local
2158    3
2172    3
2194    3
2212    1
2239    3
2258    0
2278    3
2299    0
2318    1
2338    3
Name: FTR, dtype: object
2.0
12
14.5
Ath Bilbao - visitante
2150    3
2163    0
2183    3
2203    1
2221    1
2240    0
2264    0
2297    3
2318    1
2339    3
Name: FTR, dtype: object
1.5
Sevilla - local
2151    3
2170    3
2195    3
2214    3
2225    3
2241    0
2261    0
2293    3
2315    0
2331    3
Name: FTR, dtype: object
2.1
21
16.3
Sp Gijon - visitante
2156    0
2172    0
2190    0
2218    3
2231    0
2243    3
2265    1
3424    0
3459    3
3478    0

Name: FTR, dtype: object
1.0
Levante - local
2159    0
2176    1
2191    0
2211    3
2233    1
2259    1
2272    0
2283    1
2302    1
2327    3
Name: FTR, dtype: object
1.1
9
12.3
Granada - visitante
2154    1
2174    0
2181    1
2200    1
2229    0
2247    0
2263    3
2292    3
2313    3
2330    0
Name: FTR, dtype: object
1.2
Las Palmas - local
2155    0
2179    3
2192    1
2216    0
2234    3
2242    0
2262    1
Name: FTR, dtype: object
1.1428571428571428
4
10.857142857142858
Betis - visitante
2159    3
2175    3
2197    1
2210    3
2220    3
2245    1
2266    0
2664    0
2685    0
2702    0
Name: FTR, dtype: object
1.4
Celta - local
2156    3
2178    0
2198    0
2219    1
2235    3
2253    1
2267    3
2286    3
2303    1
2326    3
Name: FTR, dtype: object
1.8
19
15.0
Espanol - visitante
2158    0
2173    0
2199    0
2208    3
2222    0
2246    3
2269    0
2286    0
2309    3
2321    3
Name: FTR, dtype: object
1.2
Barcelona - local
2157    3
2171    3
2193    3
2209    3
2228    3
2244    3
2268    3
2287    1
2307    3
2328    3
Name: FTR, dtype: object
2.8
32
17.4
La Coruna - visitante
2155    3
2176    1
2196    0
2217    1
2230    3
2250    3
2260    1
2287    1
2308    1
2324    0
Name: FTR, dtype: object
1.4
Getafe - local
2152    3
2160    1
2188    0
2204    3
2223    3
2249    3
2263    0
2295    1
2313    0
2336    0
Name: FTR, dtype: object
1.4
14
12.7
Sociedad - visitante
2157    0
2179    0
2191    3
2215    0
2237    3
2257    0
2276    1
2280    3
2307    0
2329    1
Name: FTR, dtype: object
1.1
Espanol - local
2169    3
2181    1
2218    0
2238    3
2256    0
2277    3
2296    0
2314    1
2337    0
2353    3
Name: FTR, dtype: object
1.4
9
10.4
Levante - visitante
2162    3
2185    0
2206    0
2223    0
2244    0
2262    1
2294    0
2319    0
2336    3
2350    0
Name: FTR, dtype: object
0.7
Villarreal - local
2161    1
2184    3
2201    0
2224    3
2240    3
2269    3
2290    3
2301    3
2322    0
2341    1
Name: FTR, dtype: object
2.0
14
12.9
Vallecano - visitante
2160    1
2182    0
2209    0
2225    0
2242    3
2267    0
2298    3
2314    1
2331    0
2358    0
Name: FTR, dtype: object
0.8
Sp Gijon - local
2162    0
2180    3
2200    1
2220    0
2255    0
2271    1
3432    3
3447    0
3466    3
3484    3
Name: FTR, dtype: object
1.4
14
15.2
Las Palmas - visitante
2165    1
2187    0
2204    0
2228    0
2253    1
2278    0
Name: FTR, dtype: object
0.3333333333333333
Sociedad - local
2166    3
2186    0
2202    0
2221    1
2246    0
2265    1
2292    0
2319    3
2335    1
2351    1
Name: FTR, dtype: object
1.0
11
11.9
Eibar - visitante
2161    1
2193    0
2216    3
2233    1
2251    1
2270    3
2295    1
2311    0
2334    0
2356    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
2173    3
2190    3
2213    3
2236    0
2254    3
2274    0
2288    3
2308    1
2329    1
2348    3
Name: FTR, dtype: object
2.0
22
14.3
Malaga - visitante
2169    0
2180    0
2205    0
2226    1
2249    0
2268    0
2290    0
2304    3
2326    0
2345    0
Name: FTR, dtype: object
0.4
Valencia - local
2165    1
2185    3
2205    3
2229    3
2245    1
2260    1
2291    1
2311    3
2330    3
2350    3
Name: FTR, dtype: object
2.2
20
13.4
Barcelona - visitante
2167    3
2188    3
2214    0
2235    0
2258    3
2274    3
2299    3
2317    3
2337    3
2355    1
Name: FTR, dtype: object
2.2
Real Madrid - local
2167    0
2187    3
2206    3
2226    1
2247    3
2266    3
2281    3
2305    1
2323    3
2345    3
Name: FTR, dtype: object
2.3
27
19.9
Getafe - visitante
2177    0
2195    0
2219    1
2239    0
2254    0
2277    0
2281    0
2300    0
2328    0
2348    0
Name: FTR, dtype: object
0.1
La Coruna - local
2168    3
2189    1
2203    1
2222    3
2243    0
2276    1
2294    3
2316    1
2346    0
2364    1
Name: FTR, dtype: object
1.4
15
11.2
Sevilla - visitante
2166    0
2184    0
2207    1
2234    0
2259    1
2279    1
2282    3
2303    1
2325    3
2343    1
Name: FTR, dtype: object
1.1
Granada - local
2163    3
2197    1
2217    1
2237    0
2252    0
2270    0
2284    1
2306    3
2321    0
2343    1
Name: FTR, dtype: object
1.0
10
11.6
Ath Madrid - visitante
2164    3
2189    1
2202    3
2224    0
2248    3
2261    3
2284    1
2302    1
2322    3
2346    3
Name: FTR, dtype: object
2.1
Betis - local
2164    0
2183    0
2208    0
2230    0
2257    3
2273    1
2675    3
2699    0
2714    0
2731    0
Name: FTR, dtype: object
0.7
10
14.1
Celta - visitante
2168    0
2186    3
2201    3
2227    1
2241    3
2272    3
2291    1
2310    1
2344    3
2365    1
Name: FTR, dtype: object
1.9
Vallecano - local
2174    3
2199    3
2210    0
2231    3
2250    0
2275    1
2280    0
2300    3
2320    1
2342    3
Name: FTR, dtype: object
1.7
15
12.7
Ath Bilbao - visitante
2163    0
2183    3
2203    1
2221    1
2240    0
2264    0
2297    3
2318    1
2339    3
2353    0
Name: FTR, dtype: object
1.2
Sevilla - local
2170    3
2195    3
2214    3
2225    3
2241    0
2261    0
2293    3
2315    0
2331    3
2355    1
Name: FTR, dtype: object
1.9
22
15.9
Valencia - visitante
2178    3
2194    0
2213    0
2238    0
2255    3
2275    1
2289    3
2305    1
2320    1
2347    0
Name: FTR, dtype: object
1.2
Getafe - local
2160    1
2188    0
2204    3
2223    3
2249    3
2263    0
2295    1
2313    0
2336    0
2352    1
Name: FTR, dtype: object
1.2
13
12.8
Villarreal - visitante
2171    0
2192    1
2211    0
2232    3
2252    3
2273    1
2288    0
2316    1
2335    1
2352    1
Name: FTR, dtype: object
1.1
Eibar - local
2177    3
2182    3
2207    1
2227    1
2248    0
2264    3
2285    3
2309    0
2325    0
2344    0
Name: FTR, dtype: object
1.4
12
11.6
Real Madrid - visitante
2170    0
2198    3
2212    1
2236    3
2256    3
2271    1
2296    3
2315    3
2333    3
2363    3
Name: FTR, dtype: object
2.3
Malaga - local
2175    0
2196    3
2215    3
2232    0
2251    1
2279    1
2282    0
2312    0
2332    1
2357    1
Name: FTR, dtype: object
1.0
11
14.4
Granada - visitante
2174    0
2181    1
2200    1
2229    0
2247    0
2263    3
2292    3
2313    3
2330    0
2359    0
Name: FTR, dtype: object
1.1
Las Palmas - local
2179    3
2192    1
2216    0
2234    3
2242    0
2262    1
Name: FTR, dtype: object
1.3333333333333333
4
11.333333333333334
La Coruna - visitante
2176    1
2196    0
2217    1
2230    3
2250    3
2260    1
2287    1
2308    1
2324    0
2332    1
Name: FTR, dtype: object
1.2
Celta - local
2178    0
2198    0
2219    1
2235    3
2253    1
2267    3
2286    3
2303    1
2326    3
2333    0
Name: FTR, dtype: object
1.5
19
16.4
Sp Gijon - visitante
2172    0
2190    0
2218    3
2231    0
2243    3
2265    1
3424    0
3459    3
3478    0
3497    0
Name: FTR, dtype: object
1.0
Barcelona - local
2171    3
2193    3
2209    3
2228    3
2244    3
2268    3
2287    1
2307    3
2328    3
2347    3
Name: FTR, dtype: object
2.8
30
17.4
Sociedad - visitante
2179    0
2191    3
2215    0
2237    3
2257    0
2276    1
2280    3
2307    0
2329    1
2340    0
Name: FTR, dtype: object
1.1
Ath Madrid - local
2172    3
2194    3
2212    1
2239    3
2258    0
2278    3
2299    0
2318    1
2338    3
2369    3
Name: FTR, dtype: object
2.0
13
13.6
Espanol - visitante
2173    0
2199    0
2208    3
2222    0
2246    3
2269    0
2286    0
2309    3
2321    3
2349    1
Name: FTR, dtype: object
1.3
Levante - local
2176    1
2191    0
2211    3
2233    1
2259    1
2272    0
2283    1
2302    1
2327    3
2349    1
Name: FTR, dtype: object
1.2
11
12.2
Betis - visitante
2175    3
2197    1
2210    3
2220    3
2245    1
2266    0
2664    0
2685    0
2702    0
2727    0
Name: FTR, dtype: object
1.1
Getafe - local
2188    0
2204    3
2223    3
2249    3
2263    0
2295    1
2313    0
2336    0
2352    1
2373    3
Name: FTR, dtype: object
1.4
14
12.4
Vallecano - visitante
2182    0
2209    0
2225    0
2242    3
2267    0
2298    3
2314    1
2331    0
2358    0
2379    3
Name: FTR, dtype: object
1.0
Villarreal - local
2184    3
2201    0
2224    3
2240    3
2269    3
2290    3
2301    3
2322    0
2341    1
2360    0
Name: FTR, dtype: object
1.9
13
12.4
Eibar - visitante
2193    0
2216    3
2233    1
2251    1
2270    3
2295    1
2311    0
2334    0
2356    0
2386    1
Name: FTR, dtype: object
1.0
Sp Gijon - local
2180    3
2200    1
2220    0
2255    0
2271    1
3432    3
3447    0
3466    3
3484    3
3505    0
Name: FTR, dtype: object
1.4
15
15.3
Levante - visitante
2185    0
2206    0
2223    0
2244    0
2262    1
2294    0
2319    0
2336    3
2350    0
2378    3
Name: FTR, dtype: object
0.7
Granada - local
2197    1
2217    1
2237    0
2252    0
2270    0
2284    1
2306    3
2321    0
2343    1
2365    1
Name: FTR, dtype: object
0.8
9
11.6
Ath Bilbao - visitante
2183    3
2203    1
2221    1
2240    0
2264    0
2297    3
2318    1
2339    3
2353    0
2375    0
Name: FTR, dtype: object
1.2
Betis - local
2183    0
2208    0
2230    0
2257    3
2273    1
2675    3
2699    0
2714    0
2731    0
2754    0
Name: FTR, dtype: object
0.7
10
14.0
Ath Madrid - visitante
2189    1
2202    3
2224    0
2248    3
2261    3
2284    1
2302    1
2322    3
2346    3
2357    1
Name: FTR, dtype: object
1.9
Valencia - local
2185    3
2205    3
2229    3
2245    1
2260    1
2291    1
2311    3
2330    3
2350    3
2371    1
Name: FTR, dtype: object
2.2
19
13.8
Las Palmas - visitante
2187    0
2204    0
2228    0
2253    1
2278    0
Name: FTR, dtype: object
0.2
Sociedad - local
2186    0
2202    0
2221    1
2246    0
2265    1
2292    0
2319    3
2335    1
2351    1
2381    3
Name: FTR, dtype: object
1.0
12
12.4
Sevilla - visitante
2184    0
2207    1
2234    0
2259    1
2279    1
2282    3
2303    1
2325    3
2343    1
2367    3
Name: FTR, dtype: object
1.4
Real Madrid - local
2187    3
2206    3
2226    1
2247    3
2266    3
2281    3
2305    1
2323    3
2345    3
2356    3
Name: FTR, dtype: object
2.6
30
21.0
Barcelona - visitante
2188    3
2214    0
2235    0
2258    3
2274    3
2299    3
2317    3
2337    3
2355    1
2374    3
Name: FTR, dtype: object
2.2
La Coruna - local
2189    1
2203    1
2222    3
2243    0
2276    1
2294    3
2316    1
2346    0
2364    1
2382    1
Name: FTR, dtype: object
1.2
13
12.1
Celta - visitante
2186    3
2201    3
2227    1
2241    3
2272    3
2291    1
2310    1
2344    3
2365    1
2385    3
Name: FTR, dtype: object
2.2
Espanol - local
2181    1
2218    0
2238    3
2256    0
2277    3
2296    0
2314    1
2337    0
2353    3
2370    1
Name: FTR, dtype: object
1.2
8
10.2
Malaga - visitante
2180    0
2205    0
2226    1
2249    0
2268    0
2290    0
2304    3
2326    0
2345    0
2368    0
Name: FTR, dtype: object
0.4
Sevilla - local
2195    3
2214    3
2225    3
2241    0
2261    0
2293    3
2315    0
2331    3
2355    1
2375    3
Name: FTR, dtype: object
1.9
21
15.4

Real Madrid - visitante
2198    3
2212    1
2236    3
2256    3
2271    1
2296    3
2315    3
2333    3
2363    3
2383    0
Name: FTR, dtype: object
2.3
Barcelona - local
2193    3
2209    3
2228    3
2244    3
2268    3
2287    1
2307    3
2328    3
2347    3
2366    3
Name: FTR, dtype: object
2.8
31
17.3
Villarreal - visitante
2192    1
2211    0
2232    3
2252    3
2273    1
2288    0
2316    1
2335    1
2352    1
2371    1
Name: FTR, dtype: object
1.2
Ath Madrid - local
2194    3
2212    1
2239    3
2258    0
2278    3
2299    0
2318    1
2338    3
2369    3
2387    3
Name: FTR, dtype: object
2.0
14
13.6
Sp Gijon - visitante
2190    0
2218    3
2231    0
2243    3
2265    1
3424    0
3459    3
3478    0
3497    0
3516    1
Name: FTR, dtype: object
1.1
Ath Bilbao - local
2190    3
2213    3
2236    0
2254    3
2274    0
2288    3
2308    1
2329    1
2348    3
2362    1
Name: FTR, dtype: object
1.8
21
14.7
Espanol - visitante
2199    0
2208    3
2222    0
2246    3
2269    0
2286    0
2309    3
2321    3
2349    1
2360    3
Name: FTR, dtype: object
1.6
Vallecano - local
2199    3
2210    0
2231    3
2250    0
2275    1
2280    0
2300    3
2320    1
2342    3
2363    0
Name: FTR, dtype: object
1.4
13
14.0
Granada - visitante
2181    1
2200    1
2229    0
2247    0
2263    3
2292    3
2313    3
2330    0
2359    0
2372    0
Name: FTR, dtype: object
1.1
Malaga - local
2196    3
2215    3
2232    0
2251    1
2279    1
2282    0
2312    0
2332    1
2357    1
2376    1
Name: FTR, dtype: object
1.1
12
14.5
Betis - visitante
2197    1
2210    3
2220    3
2245    1
2266    0
2664    0
2685    0
2702    0
2727    0
2741    3
Name: FTR, dtype: object
1.1
Levante - local
2191    0
2211    3
2233    1
2259    1
2272    0
2283    1
2302    1
2327    3
2349    1
2367    0
Name: FTR, dtype: object
1.1
11
12.6
La Coruna - visitante
2196    0
2217    1
2230    3
2250    3
2260    1
2287    1
2308    1
2324    0
2332    1
2351    1
Name: FTR, dtype: object
1.2
Eibar - local
2182    3
2207    1
2227    1
2248    0
2264    3
2285    3
2309    0
2325    0
2344    0
2368    3
Name: FTR, dtype: object
1.4
10
10.8
Getafe - visitante
2195    0
2219    1
2239    0
2254    0
2277    0
2281    0
2300    0
2328    0
2348    0
2361    3
Name: FTR, dtype: object
0.4
Celta - local
2198    0
2219    1
2235    3
2253    1
2267    3
2286    3
2303    1
2326    3
2333    0
2358    3
Name: FTR, dtype: object
1.8
24
16.4
Valencia - visitante
2194    0
2213    0
2238    0
2255    3
2275    1
2289    3
2305    1
2320    1
2347    0
2362    1
Name: FTR, dtype: object
1.0
Las Palmas - local
2192    1
2216    0
2234    3
2242    0
2262    1
Name: FTR, dtype: object
1.0
2
12.0
Sociedad - visitante
2191    3
2215    0
2237    3
2257    0
2276    1
2280    3
2307    0
2329    1
2340    0
2369    0
Name: FTR, dtype: object
1.1
Sp Gijon - local
2200    1
2220    0
2255    0
2271    1
3432    3
3447    0
3466    3
3484    3
3505    0
3525    0
Name: FTR, dtype: object
1.1
16
16.7
Malaga - visitante
2205    0
2226    1
2249    0
2268    0
2290    0
2304    3
2326    0
2345    0
2368    0
2384    0
Name: FTR, dtype: object
0.4
Espanol - local
2218    0
2238    3
2256    0
2277    3
2296    0
2314    1
2337    0
2353    3
2370    1
2396    1
Name: FTR, dtype: object
1.2
7
9.9
Granada - visitante
2200    1
2229    0
2247    0
2263    3
2292    3
2313    3
2330    0
2359    0
2372    0
2395    0
Name: FTR, dtype: object
1.0
Eibar - local
2207    1
2227    1
2248    0
2264    3
2285    3
2309    0
2325    0
2344    0
2368    3
2379    0
Name: FTR, dtype: object
1.1
10
10.8
Vallecano - visitante
2209    0
2225    0
2242    3
2267    0
2298    3
2314    1
2331    0
2358    0
2379    3
2403    0
Name: FTR, dtype: object
1.0
Betis - local
2208    0
2230    0
2257    3
2273    1
2675    3
2699    0
2714    0
2731    0
2754    0
2779    3
Name: FTR, dtype: object
1.0
11
14.6
Ath Bilbao - visitante
2203    1
2221    1
2240    0
2264    0
2297    3
2318    1
2339    3
2353    0
2375    0
2398    3
Name: FTR, dtype: object
1.2
Villarreal - local
2201    0
2224    3
2240    3
2269    3
2290    3
2301    3
2322    0
2341    1
2360    0
2380    0
Name: FTR, dtype: object
1.6
11
13.6
Sevilla - visitante
2207    1
2234    0
2259    1
2279    1
2282    3
2303    1
2325    3
2343    1
2367    3
2380    3
Name: FTR, dtype: object
1.7
Valencia - local
2205    3
2229    3
2245    1
2260    1
2291    1
2311    3
2330    3
2350    3
2371    1
2399    3
Name: FTR, dtype: object
2.2
18
14.1
Levante - visitante
2206    0
2223    0
2244    0
2262    1
2294    0
2319    0
2336    3
2350    0
2378    3
2392    0
Name: FTR, dtype: object
0.7
Sociedad - local
2202    0
2221    1
2246    0
2265    1
2292    0
2319    3
2335    1
2351    1
2381    3
2402    3
Name: FTR, dtype: object
1.3
11
11.4
Celta - visitante
2201    3
2227    1
2241    3
2272    3
2291    1
2310    1
2344    3
2365    1
2385    3
2401    0
Name: FTR, dtype: object
1.9
Real Madrid - local
2206    3
2226    1
2247    3
2266    3
2281    3
2305    1
2323    3
2345    3
2356    3
2372    3
Name: FTR, dtype: object
2.6
36
22.2
Las Palmas - visitante
2204    0
2228    0
2253    1
2278    0
Name: FTR, dtype: object
0.25
Getafe - local
2204    3
2223    3
2249    3
2263    0
2295    1
2313    0
2336    0
2352    1
2373    3
2390    0
Name: FTR, dtype: object
1.4
14
13.2
Barcelona - visitante
2214    0
2235    0
2258    3
2274    3
2299    3
2317    3
2337    3
2355    1
2374    3
2397    3
Name: FTR, dtype: object
2.2
La Coruna - local
2203    1
2222    3
2243    0
2276    1
2294    3
2316    1
2346    0
2364    1
2382    1
2405    0
Name: FTR, dtype: object
1.1
15
12.9
Ath Madrid - visitante
2202    3
2224    0
2248    3
2261    3
2284    1
2302    1
2322    3
2346    3
2357    1
2377    3
Name: FTR, dtype: object
2.1
Ath Bilbao - local
2213    3
2236    0
2254    3
2274    0
2288    3
2308    1
2329    1
2348    3
2362    1
2388    3
Name: FTR, dtype: object
1.8
20
14.6
Sp Gijon - visitante
2218    3
2231    0
2243    3
2265    1
3424    0
3459    3
3478    0
3497    0
3516    1
3538    0
Name: FTR, dtype: object
1.1
Levante - local
2211    3
2233    1
2259    1
2272    0
2283    1
2302    1
2327    3
2349    1
2367    0
2385    0
Name: FTR, dtype: object
1.1
11
12.2
Sociedad - visitante
2215    0
2237    3
2257    0
2276    1
2280    3
2307    0
2329    1
2340    0
2369    0
2376    1
Name: FTR, dtype: object
0.9
Las Palmas - local
2216    0
2234    3
2242    0
2262    1
Name: FTR, dtype: object
1.0
2
13.5
Villarreal - visitante
2211    0
2232    3
2252    3
2273    1
2288    0
2316    1
2335    1
2352    1
2371    1
2394    1
Name: FTR, dtype: object
1.2
Barcelona - local
2209    3
2228    3
2244    3
2268    3
2287    1
2307    3
2328    3
2347    3
2366    3
2383    3
Name: FTR, dtype: object
2.8
30
17.6
Eibar - visitante
2216    3
2233    1
2251    1
2270    3
2295    1
2311    0
2334    0
2356    0
2386    1
2409    0
Name: FTR, dtype: object
1.0
Ath Madrid - local
2212    1
2239    3
2258    0
2278    3
2299    0
2318    1
2338    3
2369    3
2387    3
2404    1
Name: FTR, dtype: object
1.8
13
12.8
Valencia - visitante
2213    0
2238    0
2255    3
2275    1
2289    3
2305    1
2320    1
2347    0
2362    1
2389    3
Name: FTR, dtype: object
1.3
Sevilla - local
2214    3
2225    3
2241    0
2261    0
2293    3
2315    0
2331    3
2355    1
2375    3
2391    3
Name: FTR, dtype: object
1.9
19
14.4
Getafe - visitante
2219    1
2239    0
2254    0
2277    0
2281    0
2300    0
2328    0
2348    0
2361    3
2387    0
Name: FTR, dtype: object
0.4
Malaga - local
2215    3
2232    0
2251    1
2279    1
2282    0
2312    0
2332    1
2357    1
2376    1
2393    3
Name: FTR, dtype: object
1.1
12
15.5
La Coruna - visitante
2217    1
2230    3
2250    3
2260    1
2287    1
2308    1
2324    0
2332    1
2351    1
2373    0
Name: FTR, dtype: object
1.2
Granada - local
2217    1
2237    0
2252    0
2270    0
2284    1
2306    3
2321    0
2343    1
2365    1
2386    1
Name: FTR, dtype: object
0.8
8
11.6
Betis - visitante
2210    3
2220    3
2245    1
2266    0
2664    0
2685    0
2702    0
2727    0
2741    3
2763    1
Name: FTR, dtype: object
1.1
Celta - local
2219    1
2235    3
2253    1
2267    3
2286    3
2303    1
2326    3
2333    0
2358    3
2374    0
Name: FTR, dtype: object
1.8
23
15.4
Real Madrid - visitante
2212    1
2236    3
2256    3
2271    1
2296    3
2315    3
2333    3
2363    3
2383    0
2408    0
Name: FTR, dtype: object
2.0
Vallecano - local
2210    0
2231    3
2250    0
2275    1
2280    0
2300    3
2320    1
2342    3
2363    0
2384    3
Name: FTR, dtype: object
1.4
11
13.8
Espanol - visitante
2208    3
2222    0
2246    3
2269    0
2286    0
2309    3
2321    3
2349    1
2360    3
2382    1
Name: FTR, dtype: object
1.7
Sp Gijon - local
2220    0
2255    0
2271    1
3432    3
3447    0
3466    3
3484    3
3505    0
3525    0
3546    3
Name: FTR, dtype: object
1.3
14
16.6
Granada - visitante
2229    0
2247    0
2263    3
2292    3
2313    3
2330    0
2359    0
2372    0
2395    0
2420    0
Name: FTR, dtype: object
0.9
Villarreal - local
2224    3
2240    3
2269    3
2290    3
2301    3
2322    0
2341    1
2360    0
2380    0
2401    3
Name: FTR, dtype: object
1.9
14
13.6
Celta - visitante
2227    1
2241    3
2272    3
2291    1
2310    1
2344    3
2365    1
2385    3
2401    0
2425    3
Name: FTR, dtype: object
1.9
Sociedad - local
2221    1
2246    0
2265    1
2292    0
2319    3
2335    1
2351    1
2381    3
2402    3
2422    3
Name: FTR, dtype: object
1.6
15
12.0
Ath Madrid - visitante
2224    0
2248    3
2261    3
2284    1
2302    1
2322    3
2346    3
2357    1
2377    3
2396    1
Name: FTR, dtype: object
1.9
La Coruna - local
2222    3
2243    0
2276    1
2294    3
2316    1
2346    0
2364    1
2382    1
2405    0
2425    0
Name: FTR, dtype: object
1.0
13
12.7
Ath Bilbao - visitante
2221    1
2240    0
2264    0
2297    3
2318    1
2339    3
2353    0
2375    0
2398    3
2414    3
Name: FTR, dtype: object
1.4
Getafe - local
2223    3
2249    3
2263    0
2295    1
2313    0
2336    0
2352    1
2373    3
2390    0
2429    3
Name: FTR, dtype: object
1.4
12
12.8
Las Palmas - visitante
2228    0
2253    1
2278    0
Name: FTR, dtype: object
0.3333333333333333
Valencia - local
2229    3
2245    1
2260    1
2291    1
2311    3
2330    3
2350    3
2371    1
2399    3
2411    3
Name: FTR, dtype: object
2.2
17
15.4
Malaga - visitante
2226    1
2249    0
2268    0
2290    0
2304    3
2326    0
2345    0
2368    0
2384    0
2406    0
Name: FTR, dtype: object
0.4

Real Madrid - local
2226    1
2247    3
2266    3
2281    3
2305    1
2323    3
2345    3
2356    3
2372    3
2392    3
Name: FTR, dtype: object
2.6
35
22.4
Levante - visitante
2223    0
2244    0
2262    1
2294    0
2319    0
2336    3
2350    0
2378    3
2392    0
2415    0
Name: FTR, dtype: object
0.7
Eibar - local
2227    1
2248    0
2264    3
2285    3
2309    0
2325    0
2344    0
2368    3
2379    0
2397    0
Name: FTR, dtype: object
1.0
9
10.7
Sevilla - visitante
2234    0
2259    1
2279    1
2282    3
2303    1
2325    3
2343    1
2367    3
2380    3
2405    3
Name: FTR, dtype: object
1.9
Betis - local
2230    0
2257    3
2273    1
2675    3
2699    0
2714    0
2731    0
2754    0
2779    3
2794    0
Name: FTR, dtype: object
1.0
10
13.6
Espanol - visitante
2222    0
2246    3
2269    0
2286    0
2309    3
2321    3
2349    1
2360    3
2382    1
2402    0
Name: FTR, dtype: object
1.4
Barcelona - local
2228    3
2244    3
2268    3
2287    1
2307    3
2328    3
2347    3
2366    3
2383    3
2403    3
Name: FTR, dtype: object
2.8
31
18.1
Vallecano - visitante
2225    0
2242    3
2267    0
2298    3
2314    1
2331    0
2358    0
2379    3
2403    0
2424    0
Name: FTR, dtype: object
1.0
Vallecano - local
2231    3
2250    0
2275    1
2280    0
2300    3
2320    1
2342    3
2363    0
2384    3
2395    3
Name: FTR, dtype: object
1.7
14
13.1
Betis - visitante
2220    3
2245    1
2266    0
2664    0
2685    0
2702    0
2727    0
2741    3
2763    1
2780    1
Name: FTR, dtype: object
0.9
Levante - local
2233    1
2259    1
2272    0
2283    1
2302    1
2327    3
2349    1
2367    0
2385    0
2409    3
Name: FTR, dtype: object
1.1
12
11.9
Villarreal - visitante
2232    3
2252    3
2273    1
2288    0
2316    1
2335    1
2352    1
2371    1
2394    1
2413    1
Name: FTR, dtype: object
1.3
Ath Madrid - local
2239    3
2258    0
2278    3
2299    0
2318    1
2338    3
2369    3
2387    3
2404    1
2428    3
Name: FTR, dtype: object
2.0
15
11.9
Real Madrid - visitante
2236    3
2256    3
2271    1
2296    3
2315    3
2333    3
2363    3
2383    0
2408    0
2423    3
Name: FTR, dtype: object
2.2
Ath Bilbao - local
2236    0
2254    3
2274    0
2288    3
2308    1
2329    1
2348    3
2362    1
2388    3
2408    3
Name: FTR, dtype: object
1.8
18
13.6
Valencia - visitante
2238    0
2255    3
2275    1
2289    3
2305    1
2320    1
2347    0
2362    1
2389    3
2404    1
Name: FTR, dtype: object
1.4
Sevilla - local
2225    3
2241    0
2261    0
2293    3
2315    0
2331    3
2355    1
2375    3
2391    3
2412    1
Name: FTR, dtype: object
1.7
17
14.5
Barcelona - visitante
2235    0
2258    3
2274    3
2299    3
2317    3
2337    3
2355    1
2374    3
2397    3
2417    3
Name: FTR, dtype: object
2.5
Malaga - local
2232    0
2251    1
2279    1
2282    0
2312    0
2332    1
2357    1
2376    1
2393    3
2416    3
Name: FTR, dtype: object
1.1
12
16.0
Sociedad - visitante
2237    3
2257    0
2276    1
2280    3
2307    0
2329    1
2340    0
2369    0
2376    1
2390    3
Name: FTR, dtype: object
1.2
Las Palmas - local
2234    3
2242    0
2262    1
Name: FTR, dtype: object
1.3333333333333333
2
12.0
Eibar - visitante
2233    1
2251    1
2270    3
2295    1
2311    0
2334    0
2356    0
2386    1
2409    0
2421    0
Name: FTR, dtype: object
0.7
Granada - local
2237    0
2252    0
2270    0
2284    1
2306    3
2321    0
2343    1
2365    1
2386    1
2406    3
Name: FTR, dtype: object
1.0
8
12.0
La Coruna - visitante
2230    3
2250    3
2260    1
2287    1
2308    1
2324    0
2332    1
2351    1
2373    0
2399    0
Name: FTR, dtype: object
1.1
Espanol - local
2238    3
2256    0
2277    3
2296    0
2314    1
2337    0
2353    3
2370    1
2396    1
2419    3
Name: FTR, dtype: object
1.5
7
9.8
Sp Gijon - visitante
2231    0
2243    3
2265    1
3424    0
3459    3
3478    0
3497    0
3516    1
3538    0
3559    0
Name: FTR, dtype: object
0.8
Celta - local
2235    3
2253    1
2267    3
2286    3
2303    1
2326    3
2333    0
2358    3
2374    0
2398    0
Name: FTR, dtype: object
1.7
24
15.2
Getafe - visitante
2239    0
2254    0
2277    0
2281    0
2300    0
2328    0
2348    0
2361    3
2387    0
2400    3
Name: FTR, dtype: object
0.6
Sp Gijon - local
2255    0
2271    1
3432    3
3447    0
3466    3
3484    3
3505    0
3525    0
3546    3
3571    1
Name: FTR, dtype: object
1.4
14
15.7
Betis - visitante
2245    1
2266    0
2664    0
2685    0
2702    0
2727    0
2741    3
2763    1
2780    1
2802    0
Name: FTR, dtype: object
0.6
Sociedad - local
2246    0
2265    1
2292    0
2319    3
2335    1
2351    1
2381    3
2402    3
2422    3
2446    1
Name: FTR, dtype: object
1.6
16
11.3
Ath Bilbao - visitante
2240    0
2264    0
2297    3
2318    1
2339    3
2353    0
2375    0
2398    3
2414    3
2438    1
Name: FTR, dtype: object
1.4
La Coruna - local
2243    0
2276    1
2294    3
2316    1
2346    0
2364    1
2382    1
2405    0
2425    0
2449    3
Name: FTR, dtype: object
1.0
12
12.8
Espanol - visitante
2246    3
2269    0
2286    0
2309    3
2321    3
2349    1
2360    3
2382    1
2402    0
2429    0
Name: FTR, dtype: object
1.4
Getafe - local
2249    3
2263    0
2295    1
2313    0
2336    0
2352    1
2373    3
2390    0
2429    3
2441    3
Name: FTR, dtype: object
1.4
11
13.1
Levante - visitante
2244    0
2262    1
2294    0
2319    0
2336    3
2350    0
2378    3
2392    0
2415    0
2434    0
Name: FTR, dtype: object
0.7
Villarreal - local
2240    3
2269    3
2290    3
2301    3
2322    0
2341    1
2360    0
2380    0
2401    3
2421    3
Name: FTR, dtype: object
1.9
14
15.2
Ath Madrid - visitante
2248    3
2261    3
2284    1
2302    1
2322    3
2346    3
2357    1
2377    3
2396    1
2412    1
Name: FTR, dtype: object
2.0
Sevilla - local
2241    0
2261    0
2293    3
2315    0
2331    3
2355    1
2375    3
2391    3
2412    1
2435    3
Name: FTR, dtype: object
1.7
17
14.6
Vallecano - visitante
2242    3
2267    0
2298    3
2314    1
2331    0
2358    0
2379    3
2403    0
2424    0
2440    0
Name: FTR, dtype: object
1.0
Real Madrid - local
2247    3
2266    3
2281    3
2305    1
2323    3
2345    3
2356    3
2372    3
2392    3
2413    1
Name: FTR, dtype: object
2.6
36
21.8
Malaga - visitante
2249    0
2268    0
2290    0
2304    3
2326    0
2345    0
2368    0
2384    0
2406    0
2427    3
Name: FTR, dtype: object
0.6
Eibar - local
2248    0
2264    3
2285    3
2309    0
2325    0
2344    0
2368    3
2379    0
2397    0
2414    0
Name: FTR, dtype: object
0.9
8
10.3
Celta - visitante
2241    3
2272    3
2291    1
2310    1
2344    3
2365    1
2385    3
2401    0
2425    3
2446    1
Name: FTR, dtype: object
1.9
Barcelona - local
2244    3
2268    3
2287    1
2307    3
2328    3
2347    3
2366    3
2383    3
2403    3
2427    0
Name: FTR, dtype: object
2.5
29
17.4
Las Palmas - visitante
2253    1
2278    0
Name: FTR, dtype: object
0.5
Valencia - local
2245    1
2260    1
2291    1
2311    3
2330    3
2350    3
2371    1
2399    3
2411    3
2432    3
Name: FTR, dtype: object
2.2
17
15.5
Granada - visitante
2247    0
2263    3
2292    3
2313    3
2330    0
2359    0
2372    0
2395    0
2420    0
2445    0
Name: FTR, dtype: object
0.9
Betis - local
2257    3
2273    1
2675    3
2699    0
2714    0
2731    0
2754    0
2779    3
2794    0
2822    3
Name: FTR, dtype: object
1.3
11
14.0
La Coruna - visitante
2250    3
2260    1
2287    1
2308    1
2324    0
2332    1
2351    1
2373    0
2399    0
2418    1
Name: FTR, dtype: object
0.9
Vallecano - local
2250    0
2275    1
2280    0
2300    3
2320    1
2342    3
2363    0
2384    3
2395    3
2415    3
Name: FTR, dtype: object
1.7
16
12.6
Sp Gijon - visitante
2243    3
2265    1
3424    0
3459    3
3478    0
3497    0
3516    1
3538    0
3559    0
3566    1
Name: FTR, dtype: object
0.9
Malaga - local
2251    1
2279    1
2282    0
2312    0
2332    1
2357    1
2376    1
2393    3
2416    3
2437    0
Name: FTR, dtype: object
1.1
12
16.2
Villarreal - visitante
2252    3
2273    1
2288    0
2316    1
2335    1
2352    1
2371    1
2394    1
2413    1
2431    0
Name: FTR, dtype: object
1.0
Levante - local
2259    1
2272    0
2283    1
2302    1
2327    3
2349    1
2367    0
2385    0
2409    3
2420    3
Name: FTR, dtype: object
1.3
12
11.6
Eibar - visitante
2251    1
2270    3
2295    1
2311    0
2334    0
2356    0
2386    1
2409    0
2421    0
2449    0
Name: FTR, dtype: object
0.6
Las Palmas - local
2242    0
2262    1
Name: FTR, dtype: object
0.5
0
12.0
Sevilla - visitante
2259    1
2279    1
2282    3
2303    1
2325    3
2343    1
2367    3
2380    3
2405    3
2422    0
Name: FTR, dtype: object
1.9
Celta - local
2253    1
2267    3
2286    3
2303    1
2326    3
2333    0
2358    3
2374    0
2398    0
2410    1
Name: FTR, dtype: object
1.5
21
14.5
Barcelona - visitante
2258    3
2274    3
2299    3
2317    3
2337    3
2355    1
2374    3
2397    3
2417    3
2444    3
Name: FTR, dtype: object
2.8
Ath Bilbao - local
2254    3
2274    0
2288    3
2308    1
2329    1
2348    3
2362    1
2388    3
2408    3
2424    3
Name: FTR, dtype: object
2.1
18
14.4
Real Madrid - visitante
2256    3
2271    1
2296    3
2315    3
2333    3
2363    3
2383    0
2408    0
2423    3
2448    0
Name: FTR, dtype: object
1.9
Granada - local
2252    0
2270    0
2284    1
2306    3
2321    0
2343    1
2365    1
2386    1
2406    3
2417    0
Name: FTR, dtype: object
1.0
9
11.9
Sociedad - visitante
2257    0
2276    1
2280    3
2307    0
2329    1
2340    0
2369    0
2376    1
2390    3
2411    0
Name: FTR, dtype: object
0.9
Espanol - local
2256    0
2277    3
2296    0
2314    1
2337    0
2353    3
2370    1
2396    1
2419    3
2442    0
Name: FTR, dtype: object
1.2
7
9.0
Valencia - visitante
2255    3
2275    1
2289    3
2305    1
2320    1
2347    0
2362    1
2389    3
2404    1
2426    3
Name: FTR, dtype: object
1.7
Ath Madrid - local
2258    0
2278    3
2299    0
2318    1
2338    3
2369    3
2387    3
2404    1
2428    3
2448    3
Name: FTR, dtype: object
2.0
17
12.4
Getafe - visitante
2254    0
2277    0
2281    0
2300    0
2328    0
2348    0
2361    3
2387    0
2400    3
2416    0
Name: FTR, dtype: object
0.6
Villarreal - local
2269    3
2290    3
2301    3
2322    0
2341    1
2360    0
2380    0
2401    3
2421    3
2445    3
Name: FTR, dtype: object
1.9
13
14.7
Ath Bilbao - visitante
2264    0
2297    3
2318    1
2339    3
2353    0
2375    0
2398    3
2414    3
2438    1
2453    3
Name: FTR, dtype: object
1.7
Sevilla - local
2261    0
2293    3
2315    0
2331    3
2355    1
2375    3
2391    3
2412    1
2435    3
2452    3
Name: FTR, dtype: object
2.0
19
15.5
Celta - visitante
2272    3
2291    1
2310    1
2344    3
2365    1
2385    3
2401    0
2425    3
2446    1
2461    0
Name: FTR, dtype: object
1.6
Las Palmas - local
2262    1
Name: FTR, dtype: object
1.0
0
16.0
Vallecano - visitante
2267    0
2298    3
2314    1
2331    0
2358    0
2379    3
2403    0
2424    0
2440    0
2470    0

Name: FTR, dtype: object
0.7
La Coruna - local
2276    1
2294    3
2316    1
2346    0
2364    1
2382    1
2405    0
2425    0
2449    3
2463    1
Name: FTR, dtype: object
1.1
12
12.2
Sp Gijon - visitante
2265    1
3424    0
3459    3
3478    0
3497    0
3516    1
3538    0
3559    0
3566    1
3583    0
Name: FTR, dtype: object
0.6
Barcelona - local
2268    3
2287    1
2307    3
2328    3
2347    3
2366    3
2383    3
2403    3
2427    0
2434    3
Name: FTR, dtype: object
2.5
30
17.1
Levante - visitante
2262    1
2294    0
2319    0
2336    3
2350    0
2378    3
2392    0
2415    0
2434    0
2466    0
Name: FTR, dtype: object
0.7
Valencia - local
2260    1
2291    1
2311    3
2330    3
2350    3
2371    1
2399    3
2411    3
2432    3
2462    3
Name: FTR, dtype: object
2.4
20
14.6
Betis - visitante
2266    0
2664    0
2685    0
2702    0
2727    0
2741    3
2763    1
2780    1
2802    0
2816    0
Name: FTR, dtype: object
0.5
Sociedad - local
2265    1
2292    0
2319    3
2335    1
2351    1
2381    3
2402    3
2422    3
2446    1
2467    3
Name: FTR, dtype: object
1.9
15
12.2
Espanol - visitante
2269    0
2286    0
2309    3
2321    3
2349    1
2360    3
2382    1
2402    0
2429    0
2437    3
Name: FTR, dtype: object
1.4
Real Madrid - local
2266    3
2281    3
2305    1
2323    3
2345    3
2356    3
2372    3
2392    3
2413    1
2436    3
Name: FTR, dtype: object
2.6
37
21.5
Granada - visitante
2263    3
2292    3
2313    3
2330    0
2359    0
2372    0
2395    0
2420    0
2445    0
2463    1
Name: FTR, dtype: object
1.0
Eibar - local
2264    3
2285    3
2309    0
2325    0
2344    0
2368    3
2379    0
2397    0
2414    0
2430    0
Name: FTR, dtype: object
0.9
8
11.2
Ath Madrid - visitante
2261    3
2284    1
2302    1
2322    3
2346    3
2357    1
2377    3
2396    1
2412    1
2433    0
Name: FTR, dtype: object
1.7
Getafe - local
2263    0
2295    1
2313    0
2336    0
2352    1
2373    3
2390    0
2429    3
2441    3
2461    3
Name: FTR, dtype: object
1.4
12
13.4
Malaga - visitante
2268    0
2290    0
2304    3
2326    0
2345    0
2368    0
2384    0
2406    0
2427    3
2447    0
Name: FTR, dtype: object
0.6
Vallecano - local
2275    1
2280    0
2300    3
2320    1
2342    3
2363    0
2384    3
2395    3
2415    3
2431    3
Name: FTR, dtype: object
2.0
17
13.1
La Coruna - visitante
2260    1
2287    1
2308    1
2324    0
2332    1
2351    1
2373    0
2399    0
2418    1
2436    0
Name: FTR, dtype: object
0.6
Malaga - local
2279    1
2282    0
2312    0
2332    1
2357    1
2376    1
2393    3
2416    3
2437    0
2451    3
Name: FTR, dtype: object
1.3
13
16.5
Eibar - visitante
2270    3
2295    1
2311    0
2334    0
2356    0
2386    1
2409    0
2421    0
2449    0
2467    0
Name: FTR, dtype: object
0.5
Granada - local
2270    0
2284    1
2306    3
2321    0
2343    1
2365    1
2386    1
2406    3
2417    0
2438    1
Name: FTR, dtype: object
1.1
8
11.7
Villarreal - visitante
2273    1
2288    0
2316    1
2335    1
2352    1
2371    1
2394    1
2413    1
2431    0
2454    0
Name: FTR, dtype: object
0.7
Celta - local
2267    3
2286    3
2303    1
2326    3
2333    0
2358    3
2374    0
2398    0
2410    1
2433    3
Name: FTR, dtype: object
1.7
20
13.3
Las Palmas - visitante
2278    0
Name: FTR, dtype: object
0.0
Ath Bilbao - local
2274    0
2288    3
2308    1
2329    1
2348    3
2362    1
2388    3
2408    3
2424    3
2444    0
Name: FTR, dtype: object
1.8
17
14.5
Getafe - visitante
2277    0
2281    0
2300    0
2328    0
2348    0
2361    3
2387    0
2400    3
2416    0
2432    0
Name: FTR, dtype: object
0.6
Sp Gijon - local
2271    1
3432    3
3447    0
3466    3
3484    3
3505    0
3525    0
3546    3
3571    1
3592    1
Name: FTR, dtype: object
1.5
15
15.2
Valencia - visitante
2275    1
2289    3
2305    1
2320    1
2347    0
2362    1
2389    3
2404    1
2426    3
2442    3
Name: FTR, dtype: object
1.7
Espanol - local
2277    3
2296    0
2314    1
2337    0
2353    3
2370    1
2396    1
2419    3
2442    0
2464    3
Name: FTR, dtype: object
1.5
10
9.4
Real Madrid - visitante
2271    1
2296    3
2315    3
2333    3
2363    3
2383    0
2408    0
2423    3
2448    0
2469    3
Name: FTR, dtype: object
1.9
Betis - local
2273    1
2675    3
2699    0
2714    0
2731    0
2754    0
2779    3
2794    0
2822    3
2848    0
Name: FTR, dtype: object
1.0
10
13.8
Sociedad - visitante
2276    1
2280    3
2307    0
2329    1
2340    0
2369    0
2376    1
2390    3
2411    0
2439    1
Name: FTR, dtype: object
1.0
Ath Madrid - local
2278    3
2299    0
2318    1
2338    3
2369    3
2387    3
2404    1
2428    3
2448    3
2470    3
Name: FTR, dtype: object
2.3
19
12.5
Barcelona - visitante
2274    3
2299    3
2317    3
2337    3
2355    1
2374    3
2397    3
2417    3
2444    3
2468    3
Name: FTR, dtype: object
2.8
Levante - local
2272    0
2283    1
2302    1
2327    3
2349    1
2367    0
2385    0
2409    3
2420    3
2447    3
Name: FTR, dtype: object
1.5
15
11.3
Sevilla - visitante
2279    1
2282    3
2303    1
2325    3
2343    1
2367    3
2380    3
2405    3
2422    0
2441    0
Name: FTR, dtype: object
1.8
Valencia - local
2291    1
2311    3
2330    3
2350    3
2371    1
2399    3
2411    3
2432    3
2462    3
2477    3
Name: FTR, dtype: object
2.6
22
14.9
La Coruna - visitante
2287    1
2308    1
2324    0
2332    1
2351    1
2373    0
2399    0
2418    1
2436    0
2460    3
Name: FTR, dtype: object
0.8
Sevilla - local
2293    3
2315    0
2331    3
2355    1
2375    3
2391    3
2412    1
2435    3
2452    3
2471    3
Name: FTR, dtype: object
2.3
21
13.4
Ath Madrid - visitante
2284    1
2302    1
2322    3
2346    3
2357    1
2377    3
2396    1
2412    1
2433    0
2458    3
Name: FTR, dtype: object
1.7
Las Palmas - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Levante - visitante
2294    0
2319    0
2336    3
2350    0
2378    3
2392    0
2415    0
2434    0
2466    0
2474    0
Name: FTR, dtype: object
0.6
Getafe - local
2295    1
2313    0
2336    0
2352    1
2373    3
2390    0
2429    3
2441    3
2461    3
2473    0
Name: FTR, dtype: object
1.4
11
12.4
Granada - visitante
2292    3
2313    3
2330    0
2359    0
2372    0
2395    0
2420    0
2445    0
2463    1
2475    0
Name: FTR, dtype: object
0.7
Eibar - local
2285    3
2309    0
2325    0
2344    0
2368    3
2379    0
2397    0
2414    0
2430    0
2458    0
Name: FTR, dtype: object
0.6
7
11.4
Ath Bilbao - visitante
2297    3
2318    1
2339    3
2353    0
2375    0
2398    3
2414    3
2438    1
2453    3
2476    0
Name: FTR, dtype: object
1.7
Sociedad - local
2292    0
2319    3
2335    1
2351    1
2381    3
2402    3
2422    3
2446    1
2467    3
2478    0
Name: FTR, dtype: object
1.8
15
12.0
Sp Gijon - visitante
3424    0
3459    3
3478    0
3497    0
3516    1
3538    0
3559    0
3566    1
3583    0
3601    0
Name: FTR, dtype: object
0.5
Real Madrid - local
2281    3
2305    1
2323    3
2345    3
2356    3
2372    3
2392    3
2413    1
2436    3
2450    3
Name: FTR, dtype: object
2.6
34
20.8
Betis - visitante
2664    0
2685    0
2702    0
2727    0
2741    3
2763    1
2780    1
2802    0
2816    0
2839    0
Name: FTR, dtype: object
0.5
Celta - local
2286    3
2303    1
2326    3
2333    0
2358    3
2374    0
2398    0
2410    1
2433    3
2459    3
Name: FTR, dtype: object
1.7
18
14.1
Vallecano - visitante
2298    3
2314    1
2331    0
2358    0
2379    3
2403    0
2424    0
2440    0
2470    0
2478    3
Name: FTR, dtype: object
1.0
Barcelona - local
2287    1
2307    3
2328    3
2347    3
2366    3
2383    3
2403    3
2427    0
2434    3
2454    3
Name: FTR, dtype: object
2.5
32
16.8
Malaga - visitante
2290    0
2304    3
2326    0
2345    0
2368    0
2384    0
2406    0
2427    3
2447    0
2465    1
Name: FTR, dtype: object
0.7
Villarreal - local
2290    3
2301    3
2322    0
2341    1
2360    0
2380    0
2401    3
2421    3
2445    3
2466    3
Name: FTR, dtype: object
1.9
11
14.8
Espanol - visitante
2286    0
2309    3
2321    3
2349    1
2360    3
2382    1
2402    0
2429    0
2437    3
2452    0
Name: FTR, dtype: object
1.4
Granada - local
2284    1
2306    3
2321    0
2343    1
2365    1
2386    1
2406    3
2417    0
2438    1
2457    3
Name: FTR, dtype: object
1.4
8
11.9
Eibar - visitante
2295    1
2311    0
2334    0
2356    0
2386    1
2409    0
2421    0
2449    0
2467    0
2480    1
Name: FTR, dtype: object
0.3
Sp Gijon - local
3432    3
3447    0
3466    3
3484    3
3505    0
3525    0
3546    3
3571    1
3592    1
3620    3
Name: FTR, dtype: object
1.7
17
15.7
Real Madrid - visitante
2296    3
2315    3
2333    3
2363    3
2383    0
2408    0
2423    3
2448    0
2469    3
2473    3
Name: FTR, dtype: object
2.1
Levante - local
2283    1
2302    1
2327    3
2349    1
2367    0
2385    0
2409    3
2420    3
2447    3
2453    0
Name: FTR, dtype: object
1.5
14
11.2
Celta - visitante
2291    1
2310    1
2344    3
2365    1
2385    3
2401    0
2425    3
2446    1
2461    0
2479    0
Name: FTR, dtype: object
1.3
Betis - local
2675    3
2699    0
2714    0
2731    0
2754    0
2779    3
2794    0
2822    3
2848    0
2854    0
Name: FTR, dtype: object
0.9
10
13.8
Villarreal - visitante
2288    0
2316    1
2335    1
2352    1
2371    1
2394    1
2413    1
2431    0
2454    0
2487    1
Name: FTR, dtype: object
0.7
Ath Bilbao - local
2288    3
2308    1
2329    1
2348    3
2362    1
2388    3
2408    3
2424    3
2444    0
2465    1
Name: FTR, dtype: object
1.9
18
14.8
Barcelona - visitante
2299    3
2317    3
2337    3
2355    1
2374    3
2397    3
2417    3
2444    3
2468    3
2472    3
Name: FTR, dtype: object
2.8
Vallecano - local
2280    0
2300    3
2320    1
2342    3
2363    0
2384    3
2395    3
2415    3
2431    3
2460    0
Name: FTR, dtype: object
1.9
18
13.4
Valencia - visitante
2289    3
2305    1
2320    1
2347    0
2362    1
2389    3
2404    1
2426    3
2442    3
2451    0
Name: FTR, dtype: object
1.6
La Coruna - local
2294    3
2316    1
2346    0
2364    1
2382    1
2405    0
2425    0
2449    3
2463    1
2472    0
Name: FTR, dtype: object
1.0
12
11.4
Sociedad - visitante
2280    3
2307    0
2329    1
2340    0
2369    0
2376    1
2390    3
2411    0
2439    1
2456    0
Name: FTR, dtype: object
0.9
Espanol - local
2296    0
2314    1
2337    0
2353    3
2370    1
2396    1
2419    3
2442    0
2464    3
2479    3
Name: FTR, dtype: object
1.5
10
10.5
Getafe - visitante
2281    0
2300    0
2328    0
2348    0
2361    3
2387    0
2400    3
2416    0
2432    0
2455    0
Name: FTR, dtype: object
0.6
Ath Madrid - local
2299    0
2318    1
2338    3
2369    3
2387    3
2404    1
2428    3
2448    3
2470    3
2475    3
Name: FTR, dtype: object
2.3
20
12.3
Las Palmas - visitante
Series([], Name: FTR, dtype: object)
0.0
Malaga - local
2282    0
2312    0
2332    1
2357    1
2376    1
2393    3
2416    3
2437    0
2451    3
2487    1

Name: FTR, dtype: object
1.3
14
15.3
Sevilla - visitante
2282    3
2303    1
2325    3
2343    1
2367    3
2380    3
2405    3
2422    0
2441    0
2450    0
Name: FTR, dtype: object
1.7
Vallecano - local
2300    3
2320    1
2342    3
2363    0
2384    3
2395    3
2415    3
2431    3
2460    0
2481    0
Name: FTR, dtype: object
1.9
16
14.2
Sociedad - visitante
2307    0
2329    1
2340    0
2369    0
2376    1
2390    3
2411    0
2439    1
2456    0
2482    1
Name: FTR, dtype: object
0.7
Real Madrid - local
2305    1
2323    3
2345    3
2356    3
2372    3
2392    3
2413    1
2436    3
2450    3
2456    3
Name: FTR, dtype: object
2.6
31
21.6
Getafe - visitante
2300    0
2328    0
2348    0
2361    3
2387    0
2400    3
2416    0
2432    0
2455    0
2488    0
Name: FTR, dtype: object
0.6
Malaga - local
2312    0
2332    1
2357    1
2376    1
2393    3
2416    3
2437    0
2451    3
2487    1
2497    0
Name: FTR, dtype: object
1.3
13
15.1
Sevilla - visitante
2303    1
2325    3
2343    1
2367    3
2380    3
2405    3
2422    0
2441    0
2450    0
2462    0
Name: FTR, dtype: object
1.4
Levante - local
2302    1
2327    3
2349    1
2367    0
2385    0
2409    3
2420    3
2447    3
2453    0
2490    1
Name: FTR, dtype: object
1.5
14
11.3
Elche - visitante
2301    0
2312    3
2338    0
2354    3
2370    1
2391    0
2410    1
2430    3
2457    0
2484    3
Name: FTR, dtype: object
1.4
Granada - local
2306    3
2321    0
2343    1
2365    1
2386    1
2406    3
2417    0
2438    1
2457    3
2482    1
Name: FTR, dtype: object
1.4
9
13.7
Ath Madrid - visitante
2302    1
2322    3
2346    3
2357    1
2377    3
2396    1
2412    1
2433    0
2458    3
2483    0
Name: FTR, dtype: object
1.6
Eibar - local
2309    0
2325    0
2344    0
2368    3
2379    0
2397    0
2414    0
2430    0
2458    0
2488    3
Name: FTR, dtype: object
0.6
6
11.4
Cordoba - visitante
2306    0
2327    0
2341    1
2364    1
2381    0
2393    0
2419    0
2435    0
2459    0
2481    3
Name: FTR, dtype: object
0.5
Celta - local
2303    1
2326    3
2333    0
2358    3
2374    0
2398    0
2410    1
2433    3
2459    3
2489    1
Name: FTR, dtype: object
1.5
16
14.5
Espanol - visitante
2309    3
2321    3
2349    1
2360    3
2382    1
2402    0
2429    0
2437    3
2452    0
2486    0
Name: FTR, dtype: object
1.4
Barcelona - local
2307    3
2328    3
2347    3
2366    3
2383    3
2403    3
2427    0
2434    3
2454    3
2483    3
Name: FTR, dtype: object
2.7
33
16.7
La Coruna - visitante
2308    1
2324    0
2332    1
2351    1
2373    0
2399    0
2418    1
2436    0
2460    3
2490    1
Name: FTR, dtype: object
0.8
Ath Bilbao - local
2308    1
2329    1
2348    3
2362    1
2388    3
2408    3
2424    3
2444    0
2465    1
2484    0
Name: FTR, dtype: object
1.6
15
14.4
Villarreal - visitante
2316    1
2335    1
2352    1
2371    1
2394    1
2413    1
2431    0
2454    0
2487    1
2499    1
Name: FTR, dtype: object
0.8
Almeria - local
2304    0
2310    1
2334    3
2359    3
2378    0
2394    1
2418    1
2439    1
2455    3
2485    0
Name: FTR, dtype: object
1.3
12
11.7
Valencia - visitante
2305    1
2320    1
2347    0
2362    1
2389    3
2404    1
2426    3
2442    3
2451    0
2489    1
Name: FTR, dtype: object
1.4
Villarreal - local
2301    3
2322    0
2341    1
2360    0
2380    0
2401    3
2421    3
2445    3
2466    3
2476    3
Name: FTR, dtype: object
1.9
11
15.9
Malaga - visitante
2304    3
2326    0
2345    0
2368    0
2384    0
2406    0
2427    3
2447    0
2465    1
2471    0
Name: FTR, dtype: object
0.7
Valencia - local
2311    3
2330    3
2350    3
2371    1
2399    3
2411    3
2432    3
2462    3
2477    3
2492    3
Name: FTR, dtype: object
2.8
23
13.9
Celta - visitante
2310    1
2344    3
2365    1
2385    3
2401    0
2425    3
2446    1
2461    0
2479    0
2496    0
Name: FTR, dtype: object
1.2
Sociedad - local
2319    3
2335    1
2351    1
2381    3
2402    3
2422    3
2446    1
2467    3
2478    0
2493    3
Name: FTR, dtype: object
2.1
16
11.9
Granada - visitante
2313    3
2330    0
2359    0
2372    0
2395    0
2420    0
2445    0
2463    1
2475    0
2491    0
Name: FTR, dtype: object
0.4
Sevilla - local
2315    0
2331    3
2355    1
2375    3
2391    3
2412    1
2435    3
2452    3
2471    3
2496    3
Name: FTR, dtype: object
2.3
20
12.9
Almeria - visitante
2323    0
2342    0
2366    0
2388    0
2407    0
2428    0
2443    3
2464    0
2477    0
2497    3
Name: FTR, dtype: object
0.6
La Coruna - local
2316    1
2346    0
2364    1
2382    1
2405    0
2425    0
2449    3
2463    1
2472    0
2498    3
Name: FTR, dtype: object
1.0
11
11.2
Levante - visitante
2319    0
2336    3
2350    0
2378    3
2392    0
2415    0
2434    0
2466    0
2474    0
2500    0
Name: FTR, dtype: object
0.6
Getafe - local
2313    0
2336    0
2352    1
2373    3
2390    0
2429    3
2441    3
2461    3
2473    0
2494    0
Name: FTR, dtype: object
1.3
11
12.3
Eibar - visitante
2311    0
2334    0
2356    0
2386    1
2409    0
2421    0
2449    0
2467    0
2480    1
2495    3
Name: FTR, dtype: object
0.5
Espanol - local
2314    1
2337    0
2353    3
2370    1
2396    1
2419    3
2442    0
2464    3
2479    3
2495    0
Name: FTR, dtype: object
1.5
10
10.5
Real Madrid - visitante
2315    3
2333    3
2363    3
2383    0
2408    0
2423    3
2448    0
2469    3
2473    3
2492    0
Name: FTR, dtype: object
1.8
Elche - local
2324    3
2340    3
2361    0
2389    0
2407    3
2423    0
2440    3
2468    0
2474    3
2499    1
Name: FTR, dtype: object
1.6
11
12.0
Ath Bilbao - visitante
2318    1
2339    3
2353    0
2375    0
2398    3
2414    3
2438    1
2453    3
2476    0
2498    0
Name: FTR, dtype: object
1.4
Cordoba - local
2317    0
2339    0
2354    0
2377    0
2400    0
2426    0
2443    0
2469    0
2480    1
2491    3
Name: FTR, dtype: object
0.4
7
13.0
Vallecano - visitante
2314    1
2331    0
2358    0
2379    3
2403    0
2424    0
2440    0
2470    0
2478    3
2494    3
Name: FTR, dtype: object
1.0
Ath Madrid - local
2318    1
2338    3
2369    3
2387    3
2404    1
2428    3
2448    3
2470    3
2475    3
2500    3
Name: FTR, dtype: object
2.6
23
12.6
Barcelona - visitante
2317    3
2337    3
2355    1
2374    3
2397    3
2417    3
2444    3
2468    3
2472    3
2493    0
Name: FTR, dtype: object
2.5
Vallecano - local
2320    1
2342    3
2363    0
2384    3
2395    3
2415    3
2431    3
2460    0
2481    0
2505    0
Name: FTR, dtype: object
1.6
15
14.3
Getafe - visitante
2328    0
2348    0
2361    3
2387    0
2400    3
2416    0
2432    0
2455    0
2488    0
2502    1
Name: FTR, dtype: object
0.7
Villarreal - local
2322    0
2341    1
2360    0
2380    0
2401    3
2421    3
2445    3
2466    3
2476    3
2501    3
Name: FTR, dtype: object
1.9
13
16.2
Elche - visitante
2312    3
2338    0
2354    3
2370    1
2391    0
2410    1
2430    3
2457    0
2484    3
2510    0
Name: FTR, dtype: object
1.4
Levante - local
2327    3
2349    1
2367    0
2385    0
2409    3
2420    3
2447    3
2453    0
2490    1
2506    1
Name: FTR, dtype: object
1.5
13
11.6
Ath Madrid - visitante
2322    3
2346    3
2357    1
2377    3
2396    1
2412    1
2433    0
2458    3
2483    0
2504    3
Name: FTR, dtype: object
1.8
Celta - local
2326    3
2333    0
2358    3
2374    0
2398    0
2410    1
2433    3
2459    3
2489    1
2509    0
Name: FTR, dtype: object
1.4
15
15.1
Sevilla - visitante
2325    3
2343    1
2367    3
2380    3
2405    3
2422    0
2441    0
2450    0
2462    0
2485    3
Name: FTR, dtype: object
1.6
Almeria - local
2310    1
2334    3
2359    3
2378    0
2394    1
2418    1
2439    1
2455    3
2485    0
2519    0
Name: FTR, dtype: object
1.3
12
12.3
Malaga - visitante
2326    0
2345    0
2368    0
2384    0
2406    0
2427    3
2447    0
2465    1
2471    0
2503    3
Name: FTR, dtype: object
0.7
Real Madrid - local
2323    3
2345    3
2356    3
2372    3
2392    3
2413    1
2436    3
2450    3
2456    3
2486    3
Name: FTR, dtype: object
2.8
32
20.5
Valencia - visitante
2320    1
2347    0
2362    1
2389    3
2404    1
2426    3
2442    3
2451    0
2489    1
2507    3
Name: FTR, dtype: object
1.6
Granada - local
2321    0
2343    1
2365    1
2386    1
2406    3
2417    0
2438    1
2457    3
2482    1
2502    1
Name: FTR, dtype: object
1.2
8
12.9
Cordoba - visitante
2327    0
2341    1
2364    1
2381    0
2393    0
2419    0
2435    0
2459    0
2481    3
2508    0
Name: FTR, dtype: object
0.5
Barcelona - local
2328    3
2347    3
2366    3
2383    3
2403    3
2427    0
2434    3
2454    3
2483    3
2508    3
Name: FTR, dtype: object
2.7
36
16.8
Sociedad - visitante
2329    1
2340    0
2369    0
2376    1
2390    3
2411    0
2439    1
2456    0
2482    1
2506    1
Name: FTR, dtype: object
0.8
Ath Bilbao - local
2329    1
2348    3
2362    1
2388    3
2408    3
2424    3
2444    0
2465    1
2484    0
2504    0
Name: FTR, dtype: object
1.5
15
13.7
La Coruna - visitante
2324    0
2332    1
2351    1
2373    0
2399    0
2418    1
2436    0
2460    3
2490    1
2501    0
Name: FTR, dtype: object
0.7
Eibar - local
2325    0
2344    0
2368    3
2379    0
2397    0
2414    0
2430    0
2458    0
2488    3
2507    0
Name: FTR, dtype: object
0.6
6
11.4
Espanol - visitante
2321    3
2349    1
2360    3
2382    1
2402    0
2429    0
2437    3
2452    0
2486    0
2505    3
Name: FTR, dtype: object
1.4
Almeria - local
2334    3
2359    3
2378    0
2394    1
2418    1
2439    1
2455    3
2485    0
2519    0
2530    0
Name: FTR, dtype: object
1.2
10
12.2
Celta - visitante
2344    3
2365    1
2385    3
2401    0
2425    3
2446    1
2461    0
2479    0
2496    0
2516    0
Name: FTR, dtype: object
1.1
Valencia - local
2330    3
2350    3
2371    1
2399    3
2411    3
2432    3
2462    3
2477    3
2492    3
2515    3
Name: FTR, dtype: object
2.8
23
14.0
Eibar - visitante
2334    0
2356    0
2386    1
2409    0
2421    0
2449    0
2467    0
2480    1
2495    3
2512    1
Name: FTR, dtype: object
0.6
Malaga - local
2332    1
2357    1
2376    1
2393    3
2416    3
2437    0
2451    3
2487    1
2497    0
2516    3
Name: FTR, dtype: object
1.6
13
14.2
Elche - visitante
2338    0
2354    3
2370    1
2391    0
2410    1
2430    3
2457    0
2484    3
2510    0
2539    0
Name: FTR, dtype: object
1.1
Getafe - local
2336    0
2352    1
2373    3
2390    0
2429    3
2441    3
2461    3
2473    0
2494    0
2517    1
Name: FTR, dtype: object
1.4
10
11.0
Granada - visitante
2330    0
2359    0
2372    0
2395    0
2420    0
2445    0
2463    1
2475    0
2491    0
2513    0
Name: FTR, dtype: object
0.1
Espanol - local
2337    0
2353    3
2370    1
2396    1
2419    3
2442    0
2464    3
2479    3
2495    0
2513    3
Name: FTR, dtype: object
1.7
11
10.5
Vallecano - visitante
2331    0
2358    0
2379    3
2403    0
2424    0
2440    0
2470    0
2478    3
2494    3
2515    0
Name: FTR, dtype: object
0.9
Sevilla - local
2331    3
2355    1
2375    3
2391    3
2412    1
2435    3
2452    3
2471    3
2496    3
2512    1

Name: FTR, dtype: object
2.4
18
12.7
Real Madrid - visitante
2333    3
2363    3
2383    0
2408    0
2423    3
2448    0
2469    3
2473    3
2492    0
2519    3
Name: FTR, dtype: object
1.8
La Coruna - local
2346    0
2364    1
2382    1
2405    0
2425    0
2449    3
2463    1
2472    0
2498    3
2510    3
Name: FTR, dtype: object
1.2
11
11.8
Villarreal - visitante
2335    1
2352    1
2371    1
2394    1
2413    1
2431    0
2454    0
2487    1
2499    1
2514    3
Name: FTR, dtype: object
1.0
Cordoba - local
2339    0
2354    0
2377    0
2400    0
2426    0
2443    0
2469    0
2480    1
2491    3
2518    1
Name: FTR, dtype: object
0.5
7
13.8
Barcelona - visitante
2337    3
2355    1
2374    3
2397    3
2417    3
2444    3
2468    3
2472    3
2493    0
2517    1
Name: FTR, dtype: object
2.3
Ath Madrid - local
2338    3
2369    3
2387    3
2404    1
2428    3
2448    3
2470    3
2475    3
2500    3
2514    0
Name: FTR, dtype: object
2.5
23
12.7
Ath Bilbao - visitante
2339    3
2353    0
2375    0
2398    3
2414    3
2438    1
2453    3
2476    0
2498    0
2511    1
Name: FTR, dtype: object
1.4
Sociedad - local
2335    1
2351    1
2381    3
2402    3
2422    3
2446    1
2467    3
2478    0
2493    3
2511    1
Name: FTR, dtype: object
1.9
14
12.4
Levante - visitante
2336    3
2350    0
2378    3
2392    0
2415    0
2434    0
2466    0
2474    0
2500    0
2518    1
Name: FTR, dtype: object
0.7
Vallecano - local
2342    3
2363    0
2384    3
2395    3
2415    3
2431    3
2460    0
2481    0
2505    0
2523    0
Name: FTR, dtype: object
1.5
14
14.5
Valencia - visitante
2347    0
2362    1
2389    3
2404    1
2426    3
2442    3
2451    0
2489    1
2507    3
2524    1
Name: FTR, dtype: object
1.6
Granada - local
2343    1
2365    1
2386    1
2406    3
2417    0
2438    1
2457    3
2482    1
2502    1
2524    1
Name: FTR, dtype: object
1.3
8
12.2
Espanol - visitante
2349    1
2360    3
2382    1
2402    0
2429    0
2437    3
2452    0
2486    0
2505    3
2525    0
Name: FTR, dtype: object
1.1
Villarreal - local
2341    1
2360    0
2380    0
2401    3
2421    3
2445    3
2466    3
2476    3
2501    3
2522    3
Name: FTR, dtype: object
2.2
17
17.3
Ath Madrid - visitante
2346    3
2357    1
2377    3
2396    1
2412    1
2433    0
2458    3
2483    0
2504    3
2528    3
Name: FTR, dtype: object
1.8
Real Madrid - local
2345    3
2356    3
2372    3
2392    3
2413    1
2436    3
2450    3
2456    3
2486    3
2526    3
Name: FTR, dtype: object
2.8
32
20.7
Almeria - visitante
2342    0
2366    0
2388    0
2407    0
2428    0
2443    3
2464    0
2477    0
2497    3
2509    3
Name: FTR, dtype: object
0.9
Elche - local
2340    3
2361    0
2389    0
2407    3
2423    0
2440    3
2468    0
2474    3
2499    1
2503    0
Name: FTR, dtype: object
1.3
8
11.7
La Coruna - visitante
2332    1
2351    1
2373    0
2399    0
2418    1
2436    0
2460    3
2490    1
2501    0
2534    0
Name: FTR, dtype: object
0.7
Eibar - local
2344    0
2368    3
2379    0
2397    0
2414    0
2430    0
2458    0
2488    3
2507    0
2521    3
Name: FTR, dtype: object
0.9
10
11.6
Sevilla - visitante
2343    1
2367    3
2380    3
2405    3
2422    0
2441    0
2450    0
2462    0
2485    3
2523    3
Name: FTR, dtype: object
1.6
Celta - local
2333    0
2358    3
2374    0
2398    0
2410    1
2433    3
2459    3
2489    1
2509    0
2538    0
Name: FTR, dtype: object
1.1
14
16.6
Malaga - visitante
2345    0
2368    0
2384    0
2406    0
2427    3
2447    0
2465    1
2471    0
2503    3
2527    3
Name: FTR, dtype: object
1.0
Levante - local
2349    1
2367    0
2385    0
2409    3
2420    3
2447    3
2453    0
2490    1
2506    1
2520    1
Name: FTR, dtype: object
1.3
13
11.9
Cordoba - visitante
2341    1
2364    1
2381    0
2393    0
2419    0
2435    0
2459    0
2481    3
2508    0
2529    3
Name: FTR, dtype: object
0.8
Barcelona - local
2347    3
2366    3
2383    3
2403    3
2427    0
2434    3
2454    3
2483    3
2508    3
2525    3
Name: FTR, dtype: object
2.7
35
16.2
Getafe - visitante
2348    0
2361    3
2387    0
2400    3
2416    0
2432    0
2455    0
2488    0
2502    1
2520    1
Name: FTR, dtype: object
0.8
Ath Bilbao - local
2348    3
2362    1
2388    3
2408    3
2424    3
2444    0
2465    1
2484    0
2504    0
2529    0
Name: FTR, dtype: object
1.4
14
14.1
Sociedad - visitante
2340    0
2369    0
2376    1
2390    3
2411    0
2439    1
2456    0
2482    1
2506    1
2522    0
Name: FTR, dtype: object
0.7
Valencia - local
2350    3
2371    1
2399    3
2411    3
2432    3
2462    3
2477    3
2492    3
2515    3
2531    0
Name: FTR, dtype: object
2.5
19
13.9
Granada - visitante
2359    0
2372    0
2395    0
2420    0
2445    0
2463    1
2475    0
2491    0
2513    0
2532    0
Name: FTR, dtype: object
0.1
Sevilla - local
2355    1
2375    3
2391    3
2412    1
2435    3
2452    3
2471    3
2496    3
2512    1
2532    3
Name: FTR, dtype: object
2.4
21
12.8
Vallecano - visitante
2358    0
2379    3
2403    0
2424    0
2440    0
2470    0
2478    3
2494    3
2515    0
2530    3
Name: FTR, dtype: object
1.2
Malaga - local
2357    1
2376    1
2393    3
2416    3
2437    0
2451    3
2487    1
2497    0
2516    3
2535    0
Name: FTR, dtype: object
1.5
13
14.0
La Coruna - visitante
2351    1
2373    0
2399    0
2418    1
2436    0
2460    3
2490    1
2501    0
2534    0
2559    1
Name: FTR, dtype: object
0.7
Celta - local
2358    3
2374    0
2398    0
2410    1
2433    3
2459    3
2489    1
2509    0
2538    0
2557    1
Name: FTR, dtype: object
1.2
12
16.3
Real Madrid - visitante
2363    3
2383    0
2408    0
2423    3
2448    0
2469    3
2473    3
2492    0
2519    3
2535    3
Name: FTR, dtype: object
1.8
Almeria - local
2359    3
2378    0
2394    1
2418    1
2439    1
2455    3
2485    0
2519    0
2530    0
2558    0
Name: FTR, dtype: object
0.9
9
11.9
Eibar - visitante
2356    0
2386    1
2409    0
2421    0
2449    0
2467    0
2480    1
2495    3
2512    1
2538    3
Name: FTR, dtype: object
0.9
Sociedad - local
2351    1
2381    3
2402    3
2422    3
2446    1
2467    3
2478    0
2493    3
2511    1
2539    3
Name: FTR, dtype: object
2.1
17
12.3
Villarreal - visitante
2352    1
2371    1
2394    1
2413    1
2431    0
2454    0
2487    1
2499    1
2514    3
2533    3
Name: FTR, dtype: object
1.2
Getafe - local
2352    1
2373    3
2390    0
2429    3
2441    3
2461    3
2473    0
2494    0
2517    1
2536    0
Name: FTR, dtype: object
1.4
11
11.4
Levante - visitante
2350    0
2378    3
2392    0
2415    0
2434    0
2466    0
2474    0
2500    0
2518    1
2537    0
Name: FTR, dtype: object
0.4
Espanol - local
2353    3
2370    1
2396    1
2419    3
2442    0
2464    3
2479    3
2495    0
2513    3
2537    3
Name: FTR, dtype: object
2.0
13
10.8
Barcelona - visitante
2355    1
2374    3
2397    3
2417    3
2444    3
2468    3
2472    3
2493    0
2517    1
2531    3
Name: FTR, dtype: object
2.3
Ath Madrid - local
2369    3
2387    3
2404    1
2428    3
2448    3
2470    3
2475    3
2500    3
2514    0
2534    3
Name: FTR, dtype: object
2.5
22
11.8
Elche - visitante
2354    3
2370    1
2391    0
2410    1
2430    3
2457    0
2484    3
2510    0
2539    0
2556    1
Name: FTR, dtype: object
1.2
Cordoba - local
2354    0
2377    0
2400    0
2426    0
2443    0
2469    0
2480    1
2491    3
2518    1
2533    0
Name: FTR, dtype: object
0.5
7
12.7
Ath Bilbao - visitante
2353    0
2375    0
2398    3
2414    3
2438    1
2453    3
2476    0
2498    0
2511    1
2536    3
Name: FTR, dtype: object
1.4
Elche - local
2361    0
2389    0
2407    3
2423    0
2440    3
2468    0
2474    3
2499    1
2503    0
2528    0
Name: FTR, dtype: object
1.0
7
11.6
Sociedad - visitante
2369    0
2376    1
2390    3
2411    0
2439    1
2456    0
2482    1
2506    1
2522    0
2545    1
Name: FTR, dtype: object
0.8
Villarreal - local
2360    0
2380    0
2401    3
2421    3
2445    3
2466    3
2476    3
2501    3
2522    3
2541    3
Name: FTR, dtype: object
2.4
19
15.5
Cordoba - visitante
2364    1
2381    0
2393    0
2419    0
2435    0
2459    0
2481    3
2508    0
2529    3
2544    1
Name: FTR, dtype: object
0.8
Vallecano - local
2363    0
2384    3
2395    3
2415    3
2431    3
2460    0
2481    0
2505    0
2523    0
2542    3
Name: FTR, dtype: object
1.5
13
14.1
Almeria - visitante
2366    0
2388    0
2407    0
2428    0
2443    3
2464    0
2477    0
2497    3
2509    3
2521    0
Name: FTR, dtype: object
0.9
Granada - local
2365    1
2386    1
2406    3
2417    0
2438    1
2457    3
2482    1
2502    1
2524    1
2540    1
Name: FTR, dtype: object
1.3
7
14.0
Sevilla - visitante
2367    3
2380    3
2405    3
2422    0
2441    0
2450    0
2462    0
2485    3
2523    3
2547    0
Name: FTR, dtype: object
1.5
Eibar - local
2368    3
2379    0
2397    0
2414    0
2430    0
2458    0
2488    3
2507    0
2521    3
2546    0
Name: FTR, dtype: object
0.9
10
11.5
Celta - visitante
2365    1
2385    3
2401    0
2425    3
2446    1
2461    0
2479    0
2496    0
2516    0
2526    0
Name: FTR, dtype: object
0.8
Real Madrid - local
2356    3
2372    3
2392    3
2413    1
2436    3
2450    3
2456    3
2486    3
2526    3
2554    3
Name: FTR, dtype: object
2.8
34
21.1
Malaga - visitante
2368    0
2384    0
2406    0
2427    3
2447    0
2465    1
2471    0
2503    3
2527    3
2548    0
Name: FTR, dtype: object
1.0
La Coruna - local
2364    1
2382    1
2405    0
2425    0
2449    3
2463    1
2472    0
2498    3
2510    3
2527    0
Name: FTR, dtype: object
1.2
10
12.3
Ath Madrid - visitante
2357    1
2377    3
2396    1
2412    1
2433    0
2458    3
2483    0
2504    3
2528    3
2551    0
Name: FTR, dtype: object
1.5
Barcelona - local
2366    3
2383    3
2403    3
2427    0
2434    3
2454    3
2483    3
2508    3
2525    3
2547    3
Name: FTR, dtype: object
2.7
38
16.7
Valencia - visitante
2362    1
2389    3
2404    1
2426    3
2442    3
2451    0
2489    1
2507    3
2524    1
2543    0
Name: FTR, dtype: object
1.6
Ath Bilbao - local
2362    1
2388    3
2408    3
2424    3
2444    0
2465    1
2484    0
2504    0
2529    0
2549    3
Name: FTR, dtype: object
1.4
13
12.3
Getafe - visitante
2361    3
2387    0
2400    3
2416    0
2432    0
2455    0
2488    0
2502    1
2520    1
2541    0
Name: FTR, dtype: object
0.8
Levante - local
2367    0
2385    0
2409    3
2420    3
2447    3
2453    0
2490    1
2506    1
2520    1
2543    3
Name: FTR, dtype: object
1.5
13
11.6
Espanol - visitante
2360    3
2382    1
2402    0
2429    0
2437    3
2452    0
2486    0
2505    3
2525    0
2549    0
Name: FTR, dtype: object
1.0
Valencia - local
2371    1
2399    3
2411    3
2432    3
2462    3
2477    3
2492    3
2515    3
2531    0
2550    1
Name: FTR, dtype: object
2.3
16
13.4

Levante - visitante
2378    3
2392    0
2415    0
2434    0
2466    0
2474    0
2500    0
2518    1
2537    0
2552    1
Name: FTR, dtype: object
0.5
Sociedad - local
2381    3
2402    3
2422    3
2446    1
2467    3
2478    0
2493    3
2511    1
2539    3
2551    3
Name: FTR, dtype: object
2.3
17
12.5
La Coruna - visitante
2373    0
2399    0
2418    1
2436    0
2460    3
2490    1
2501    0
2534    0
2559    1
2573    1
Name: FTR, dtype: object
0.7
Getafe - local
2373    3
2390    0
2429    3
2441    3
2461    3
2473    0
2494    0
2517    1
2536    0
2556    1
Name: FTR, dtype: object
1.4
10
11.8
Villarreal - visitante
2371    1
2394    1
2413    1
2431    0
2454    0
2487    1
2499    1
2514    3
2533    3
2553    1
Name: FTR, dtype: object
1.2
Espanol - local
2370    1
2396    1
2419    3
2442    0
2464    3
2479    3
2495    0
2513    3
2537    3
2553    1
Name: FTR, dtype: object
1.8
13
11.4
Ath Bilbao - visitante
2375    0
2398    3
2414    3
2438    1
2453    3
2476    0
2498    0
2511    1
2536    3
2550    1
Name: FTR, dtype: object
1.5
Cordoba - local
2377    0
2400    0
2426    0
2443    0
2469    0
2480    1
2491    3
2518    1
2533    0
2559    1
Name: FTR, dtype: object
0.6
7
12.7
Elche - visitante
2370    1
2391    0
2410    1
2430    3
2457    0
2484    3
2510    0
2539    0
2556    1
2574    0
Name: FTR, dtype: object
0.9
Sevilla - local
2375    3
2391    3
2412    1
2435    3
2452    3
2471    3
2496    3
2512    1
2532    3
2552    1
Name: FTR, dtype: object
2.4
20
13.2
Barcelona - visitante
2374    3
2397    3
2417    3
2444    3
2468    3
2472    3
2493    0
2517    1
2531    3
2558    3
Name: FTR, dtype: object
2.5
Real Madrid - local
2372    3
2392    3
2413    1
2436    3
2450    3
2456    3
2486    3
2526    3
2554    3
2575    3
Name: FTR, dtype: object
2.8
34
20.5
Eibar - visitante
2386    1
2409    0
2421    0
2449    0
2467    0
2480    1
2495    3
2512    1
2538    3
2555    0
Name: FTR, dtype: object
0.9
Malaga - local
2376    1
2393    3
2416    3
2437    0
2451    3
2487    1
2497    0
2516    3
2535    0
2555    3
Name: FTR, dtype: object
1.7
13
14.4
Ath Madrid - visitante
2377    3
2396    1
2412    1
2433    0
2458    3
2483    0
2504    3
2528    3
2551    0
2572    3
Name: FTR, dtype: object
1.7
Celta - local
2374    0
2398    0
2410    1
2433    3
2459    3
2489    1
2509    0
2538    0
2557    1
2579    3
Name: FTR, dtype: object
1.2
9
15.9
Vallecano - visitante
2379    3
2403    0
2424    0
2440    0
2470    0
2478    3
2494    3
2515    0
2530    3
2554    0
Name: FTR, dtype: object
1.2
Almeria - local
2378    0
2394    1
2418    1
2439    1
2455    3
2485    0
2519    0
2530    0
2558    0
2578    0
Name: FTR, dtype: object
0.6
6
10.9
Granada - visitante
2372    0
2395    0
2420    0
2445    0
2463    1
2475    0
2491    0
2513    0
2532    0
2557    1
Name: FTR, dtype: object
0.2
Villarreal - local
2380    0
2401    3
2421    3
2445    3
2466    3
2476    3
2501    3
2522    3
2541    3
2561    0
Name: FTR, dtype: object
2.4
20
16.2
Espanol - visitante
2382    1
2402    0
2429    0
2437    3
2452    0
2486    0
2505    3
2525    0
2549    0
2563    0
Name: FTR, dtype: object
0.7
Elche - local
2389    0
2407    3
2423    0
2440    3
2468    0
2474    3
2499    1
2503    0
2528    0
2544    1
Name: FTR, dtype: object
1.1
9
11.7
Getafe - visitante
2387    0
2400    3
2416    0
2432    0
2455    0
2488    0
2502    1
2520    1
2541    0
2569    3
Name: FTR, dtype: object
0.8
Ath Bilbao - local
2388    3
2408    3
2424    3
2444    0
2465    1
2484    0
2504    0
2529    0
2549    3
2564    3
Name: FTR, dtype: object
1.6
13
12.0
Valencia - visitante
2389    3
2404    1
2426    3
2442    3
2451    0
2489    1
2507    3
2524    1
2543    0
2561    3
Name: FTR, dtype: object
1.8
Vallecano - local
2384    3
2395    3
2415    3
2431    3
2460    0
2481    0
2505    0
2523    0
2542    3
2560    0
Name: FTR, dtype: object
1.5
15
13.7
Real Madrid - visitante
2383    0
2408    0
2423    3
2448    0
2469    3
2473    3
2492    0
2519    3
2535    3
2546    3
Name: FTR, dtype: object
1.8
La Coruna - local
2382    1
2405    0
2425    0
2449    3
2463    1
2472    0
2498    3
2510    3
2527    0
2545    1
Name: FTR, dtype: object
1.2
9
12.6
Cordoba - visitante
2381    0
2393    0
2419    0
2435    0
2459    0
2481    3
2508    0
2529    3
2544    1
2568    0
Name: FTR, dtype: object
0.7
Granada - local
2386    1
2406    3
2417    0
2438    1
2457    3
2482    1
2502    1
2524    1
2540    1
2566    0
Name: FTR, dtype: object
1.2
6
14.3
Celta - visitante
2385    3
2401    0
2425    3
2446    1
2461    0
2479    0
2496    0
2516    0
2526    0
2542    0
Name: FTR, dtype: object
0.7
Barcelona - local
2383    3
2403    3
2427    0
2434    3
2454    3
2483    3
2508    3
2525    3
2547    3
2567    0
Name: FTR, dtype: object
2.4
34
16.7
Almeria - visitante
2388    0
2407    0
2428    0
2443    3
2464    0
2477    0
2497    3
2509    3
2521    0
2540    1
Name: FTR, dtype: object
1.0
Levante - local
2385    0
2409    3
2420    3
2447    3
2453    0
2490    1
2506    1
2520    1
2543    3
2562    3
Name: FTR, dtype: object
1.8
14
10.8
Sevilla - visitante
2380    3
2405    3
2422    0
2441    0
2450    0
2462    0
2485    3
2523    3
2547    0
2564    0
Name: FTR, dtype: object
1.2
Eibar - local
2379    0
2397    0
2414    0
2430    0
2458    0
2488    3
2507    0
2521    3
2546    0
2576    1
Name: FTR, dtype: object
0.7
10
11.4
Malaga - visitante
2384    0
2406    0
2427    3
2447    0
2465    1
2471    0
2503    3
2527    3
2548    0
2565    3
Name: FTR, dtype: object
1.3
Ath Madrid - local
2387    3
2404    1
2428    3
2448    3
2470    3
2475    3
2500    3
2514    0
2534    3
2548    3
Name: FTR, dtype: object
2.5
23
11.7
Sociedad - visitante
2376    1
2390    3
2411    0
2439    1
2456    0
2482    1
2506    1
2522    0
2545    1
2577    1
Name: FTR, dtype: object
0.9
Espanol - local
2396    1
2419    3
2442    0
2464    3
2479    3
2495    0
2513    3
2537    3
2553    1
2573    1
Name: FTR, dtype: object
1.8
12
12.5
Elche - visitante
2391    0
2410    1
2430    3
2457    0
2484    3
2510    0
2539    0
2556    1
2574    0
2598    1
Name: FTR, dtype: object
0.9
Valencia - local
2399    3
2411    3
2432    3
2462    3
2477    3
2492    3
2515    3
2531    0
2550    1
2574    3
Name: FTR, dtype: object
2.5
19
13.3
Villarreal - visitante
2394    1
2413    1
2431    0
2454    0
2487    1
2499    1
2514    3
2533    3
2553    1
2570    0
Name: FTR, dtype: object
1.1
Real Madrid - local
2392    3
2413    1
2436    3
2450    3
2456    3
2486    3
2526    3
2554    3
2575    3
2591    3
Name: FTR, dtype: object
2.8
30
19.5
Granada - visitante
2395    0
2420    0
2445    0
2463    1
2475    0
2491    0
2513    0
2532    0
2557    1
2576    1
Name: FTR, dtype: object
0.3
Getafe - local
2390    0
2429    3
2441    3
2461    3
2473    0
2494    0
2517    1
2536    0
2556    1
2572    0
Name: FTR, dtype: object
1.1
8
11.8
La Coruna - visitante
2399    0
2418    1
2436    0
2460    3
2490    1
2501    0
2534    0
2559    1
2573    1
2590    0
Name: FTR, dtype: object
0.7
Celta - local
2398    0
2410    1
2433    3
2459    3
2489    1
2509    0
2538    0
2557    1
2579    3
2593    0
Name: FTR, dtype: object
1.2
10
16.7
Barcelona - visitante
2397    3
2417    3
2444    3
2468    3
2472    3
2493    0
2517    1
2531    3
2558    3
2575    0
Name: FTR, dtype: object
2.2
Sevilla - local
2391    3
2412    1
2435    3
2452    3
2471    3
2496    3
2512    1
2532    3
2552    1
2570    3
Name: FTR, dtype: object
2.4
20
13.1
Ath Bilbao - visitante
2398    3
2414    3
2438    1
2453    3
2476    0
2498    0
2511    1
2536    3
2550    1
2578    3
Name: FTR, dtype: object
1.8
Malaga - local
2393    3
2416    3
2437    0
2451    3
2487    1
2497    0
2516    3
2535    0
2555    3
2571    3
Name: FTR, dtype: object
1.9
16
14.9
Sociedad - visitante
2390    3
2411    0
2439    1
2456    0
2482    1
2506    1
2522    0
2545    1
2577    1
2592    0
Name: FTR, dtype: object
0.8
Cordoba - local
2400    0
2426    0
2443    0
2469    0
2480    1
2491    3
2518    1
2533    0
2559    1
2577    1
Name: FTR, dtype: object
0.7
8
12.3
Ath Madrid - visitante
2396    1
2412    1
2433    0
2458    3
2483    0
2504    3
2528    3
2551    0
2572    3
2595    0
Name: FTR, dtype: object
1.4
Almeria - local
2394    1
2418    1
2439    1
2455    3
2485    0
2519    0
2530    0
2558    0
2578    0
2598    1
Name: FTR, dtype: object
0.7
7
11.6
Levante - visitante
2392    0
2415    0
2434    0
2466    0
2474    0
2500    0
2518    1
2537    0
2552    1
2579    0
Name: FTR, dtype: object
0.2
Eibar - local
2397    0
2414    0
2430    0
2458    0
2488    3
2507    0
2521    3
2546    0
2576    1
2597    1
Name: FTR, dtype: object
0.8
12
11.6
Vallecano - visitante
2403    0
2424    0
2440    0
2470    0
2478    3
2494    3
2515    0
2530    3
2554    0
2571    0
Name: FTR, dtype: object
0.9
Villarreal - local
2401    3
2421    3
2445    3
2466    3
2476    3
2501    3
2522    3
2541    3
2561    0
2581    3
Name: FTR, dtype: object
2.7
22
15.6
Sevilla - visitante
2405    3
2422    0
2441    0
2450    0
2462    0
2485    3
2523    3
2547    0
2564    0
2583    3
Name: FTR, dtype: object
1.2
Sociedad - local
2402    3
2422    3
2446    1
2467    3
2478    0
2493    3
2511    1
2539    3
2551    3
2565    0
Name: FTR, dtype: object
2.0
14
11.1
Cordoba - visitante
2393    0
2419    0
2435    0
2459    0
2481    3
2508    0
2529    3
2544    1
2568    0
2599    1
Name: FTR, dtype: object
0.8
La Coruna - local
2405    0
2425    0
2449    3
2463    1
2472    0
2498    3
2510    3
2527    0
2545    1
2569    0
Name: FTR, dtype: object
1.1
10
12.1
Espanol - visitante
2402    0
2429    0
2437    3
2452    0
2486    0
2505    3
2525    0
2549    0
2563    0
2584    0
Name: FTR, dtype: object
0.6
Barcelona - local
2403    3
2427    0
2434    3
2454    3
2483    3
2508    3
2525    3
2547    3
2567    0
2587    3
Name: FTR, dtype: object
2.4
35
17.7
Real Madrid - visitante
2408    0
2423    3
2448    0
2469    3
2473    3
2492    0
2519    3
2535    3
2546    3
2566    3
Name: FTR, dtype: object
2.1
Vallecano - local
2395    3
2415    3
2431    3
2460    0
2481    0
2505    0
2523    0
2542    3
2560    0
2594    0
Name: FTR, dtype: object
1.2
14
14.0
Malaga - visitante
2406    0
2427    3
2447    0
2465    1
2471    0
2503    3
2527    3
2548    0
2565    3
2586    3
Name: FTR, dtype: object
1.6
Levante - local
2409    3
2420    3
2447    3
2453    0
2490    1
2506    1
2520    1
2543    3
2562    3
2585    0
Name: FTR, dtype: object
1.8
14
11.0
Celta - visitante
2401    0
2425    3
2446    1
2461    0
2479    0
2496    0
2516    0
2526    0
2542    0
2567    3
Name: FTR, dtype: object
0.7
Granada - local
2406    3
2417    0
2438    1
2457    3
2482    1
2502    1
2524    1
2540    1
2566    0
2589    0
Name: FTR, dtype: object
1.1
6
13.5
Eibar - visitante
2409    0
2421    0
2449    0
2467    0
2480    1
2495    3
2512    1
2538    3
2555    0
2560    3
Name: FTR, dtype: object
1.1
Ath Madrid - local
2404    1
2428    3
2448    3
2470    3
2475    3
2500    3
2514    0
2534    3
2548    3
2568    3
Name: FTR, dtype: object
2.5
25
11.8
Getafe - visitante
2400    3
2416    0
2432    0
2455    0
2488    0
2502    1
2520    1
2541    0
2569    3
2580    3

Name: FTR, dtype: object
1.1
Ath Bilbao - local
2408    3
2424    3
2444    0
2465    1
2484    0
2504    0
2529    0
2549    3
2564    3
2588    1
Name: FTR, dtype: object
1.4
12
11.4
Almeria - visitante
2407    0
2428    0
2443    3
2464    0
2477    0
2497    3
2509    3
2521    0
2540    1
2562    0
Name: FTR, dtype: object
1.0
Elche - local
2407    3
2423    0
2440    3
2468    0
2474    3
2499    1
2503    0
2528    0
2544    1
2563    3
Name: FTR, dtype: object
1.4
11
12.1
Valencia - visitante
2404    1
2426    3
2442    3
2451    0
2489    1
2507    3
2524    1
2543    0
2561    3
2582    0
Name: FTR, dtype: object
1.5
Getafe - local
2429    3
2441    3
2461    3
2473    0
2494    0
2517    1
2536    0
2556    1
2572    0
2599    1
Name: FTR, dtype: object
1.2
9
12.2
Sociedad - visitante
2411    0
2439    1
2456    0
2482    1
2506    1
2522    0
2545    1
2577    1
2592    0
2613    0
Name: FTR, dtype: object
0.5
Sevilla - local
2412    1
2435    3
2452    3
2471    3
2496    3
2512    1
2532    3
2552    1
2570    3
2590    3
Name: FTR, dtype: object
2.4
21
13.5
Elche - visitante
2410    1
2430    3
2457    0
2484    3
2510    0
2539    0
2556    1
2574    0
2598    1
2618    0
Name: FTR, dtype: object
0.9
Real Madrid - local
2413    1
2436    3
2450    3
2456    3
2486    3
2526    3
2554    3
2575    3
2591    3
2618    3
Name: FTR, dtype: object
2.8
33
19.6
Levante - visitante
2415    0
2434    0
2466    0
2474    0
2500    0
2518    1
2537    0
2552    1
2579    0
2597    1
Name: FTR, dtype: object
0.3
Malaga - local
2416    3
2437    0
2451    3
2487    1
2497    0
2516    3
2535    0
2555    3
2571    3
2596    3
Name: FTR, dtype: object
1.9
16
14.7
Cordoba - visitante
2419    0
2435    0
2459    0
2481    3
2508    0
2529    3
2544    1
2568    0
2599    1
2610    0
Name: FTR, dtype: object
0.8
Almeria - local
2418    1
2439    1
2455    3
2485    0
2519    0
2530    0
2558    0
2578    0
2598    1
2617    0
Name: FTR, dtype: object
0.6
7
11.2
Villarreal - visitante
2413    1
2431    0
2454    0
2487    1
2499    1
2514    3
2533    3
2553    1
2570    0
2593    3
Name: FTR, dtype: object
1.3
Vallecano - local
2415    3
2431    3
2460    0
2481    0
2505    0
2523    0
2542    3
2560    0
2594    0
2612    3
Name: FTR, dtype: object
1.2
13
13.9
Granada - visitante
2420    0
2445    0
2463    1
2475    0
2491    0
2513    0
2532    0
2557    1
2576    1
2596    0
Name: FTR, dtype: object
0.3
Espanol - local
2419    3
2442    0
2464    3
2479    3
2495    0
2513    3
2537    3
2553    1
2573    1
2592    3
Name: FTR, dtype: object
2.0
14
12.8
Ath Madrid - visitante
2412    1
2433    0
2458    3
2483    0
2504    3
2528    3
2551    0
2572    3
2595    0
2617    3
Name: FTR, dtype: object
1.6
Eibar - local
2414    0
2430    0
2458    0
2488    3
2507    0
2521    3
2546    0
2576    1
2597    1
2616    1
Name: FTR, dtype: object
0.9
13
11.0
Barcelona - visitante
2417    3
2444    3
2468    3
2472    3
2493    0
2517    1
2531    3
2558    3
2575    0
2594    3
Name: FTR, dtype: object
2.2
Celta - local
2410    1
2433    3
2459    3
2489    1
2509    0
2538    0
2557    1
2579    3
2593    0
2619    3
Name: FTR, dtype: object
1.5
11
16.2
Ath Bilbao - visitante
2414    3
2438    1
2453    3
2476    0
2498    0
2511    1
2536    3
2550    1
2578    3
2591    0
Name: FTR, dtype: object
1.5
Valencia - local
2411    3
2432    3
2462    3
2477    3
2492    3
2515    3
2531    0
2550    1
2574    3
2595    3
Name: FTR, dtype: object
2.5
20
12.3
La Coruna - visitante
2418    1
2436    0
2460    3
2490    1
2501    0
2534    0
2559    1
2573    1
2590    0
2619    0
Name: FTR, dtype: object
0.7
Cordoba - local
2426    0
2443    0
2469    0
2480    1
2491    3
2518    1
2533    0
2559    1
2577    1
2586    0
Name: FTR, dtype: object
0.7
8
11.3
Getafe - visitante
2416    0
2432    0
2455    0
2488    0
2502    1
2520    1
2541    0
2569    3
2580    3
2611    0
Name: FTR, dtype: object
0.8
Villarreal - local
2421    3
2445    3
2466    3
2476    3
2501    3
2522    3
2541    3
2561    0
2581    3
2604    0
Name: FTR, dtype: object
2.4
18
16.3
Celta - visitante
2425    3
2446    1
2461    0
2479    0
2496    0
2516    0
2526    0
2542    0
2567    3
2588    1
Name: FTR, dtype: object
0.8
Sociedad - local
2422    3
2446    1
2467    3
2478    0
2493    3
2511    1
2539    3
2551    3
2565    0
2580    0
Name: FTR, dtype: object
1.7
14
11.4
Espanol - visitante
2429    0
2437    3
2452    0
2486    0
2505    3
2525    0
2549    0
2563    0
2584    0
2603    1
Name: FTR, dtype: object
0.7
Barcelona - local
2427    0
2434    3
2454    3
2483    3
2508    3
2525    3
2547    3
2567    0
2587    3
2606    3
Name: FTR, dtype: object
2.4
35
17.7
Vallecano - visitante
2424    0
2440    0
2470    0
2478    3
2494    3
2515    0
2530    3
2554    0
2571    0
2589    3
Name: FTR, dtype: object
1.2
Ath Madrid - local
2428    3
2448    3
2470    3
2475    3
2500    3
2514    0
2534    3
2548    3
2568    3
2584    3
Name: FTR, dtype: object
2.7
26
13.0
Valencia - visitante
2426    3
2442    3
2451    0
2489    1
2507    3
2524    1
2543    0
2561    3
2582    0
2600    1
Name: FTR, dtype: object
1.5
La Coruna - local
2425    0
2449    3
2463    1
2472    0
2498    3
2510    3
2527    0
2545    1
2569    0
2582    3
Name: FTR, dtype: object
1.4
10
11.7
Sevilla - visitante
2422    0
2441    0
2450    0
2462    0
2485    3
2523    3
2547    0
2564    0
2583    3
2607    0
Name: FTR, dtype: object
0.9
Granada - local
2417    0
2438    1
2457    3
2482    1
2502    1
2524    1
2540    1
2566    0
2589    0
2615    0
Name: FTR, dtype: object
0.8
5
12.9
Malaga - visitante
2427    3
2447    0
2465    1
2471    0
2503    3
2527    3
2548    0
2565    3
2586    3
2602    0
Name: FTR, dtype: object
1.6
Elche - local
2423    0
2440    3
2468    0
2474    3
2499    1
2503    0
2528    0
2544    1
2563    3
2583    0
Name: FTR, dtype: object
1.1
10
11.8
Almeria - visitante
2428    0
2443    3
2464    0
2477    0
2497    3
2509    3
2521    0
2540    1
2562    0
2581    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
2424    3
2444    0
2465    1
2484    0
2504    0
2529    0
2549    3
2564    3
2588    1
2608    1
Name: FTR, dtype: object
1.2
11
12.1
Real Madrid - visitante
2423    3
2448    0
2469    3
2473    3
2492    0
2519    3
2535    3
2546    3
2566    3
2585    3
Name: FTR, dtype: object
2.4
Levante - local
2420    3
2447    3
2453    0
2490    1
2506    1
2520    1
2543    3
2562    3
2585    0
2605    0
Name: FTR, dtype: object
1.5
12
10.5
Eibar - visitante
2421    0
2449    0
2467    0
2480    1
2495    3
2512    1
2538    3
2555    0
2560    3
2587    0
Name: FTR, dtype: object
1.1
Celta - local
2433    3
2459    3
2489    1
2509    0
2538    0
2557    1
2579    3
2593    0
2619    3
2637    1
Name: FTR, dtype: object
1.5
12
16.4
Elche - visitante
2430    3
2457    0
2484    3
2510    0
2539    0
2556    1
2574    0
2598    1
2618    0
2631    3
Name: FTR, dtype: object
1.1
Valencia - local
2432    3
2462    3
2477    3
2492    3
2515    3
2531    0
2550    1
2574    3
2595    3
2610    3
Name: FTR, dtype: object
2.5
21
12.1
Sociedad - visitante
2439    1
2456    0
2482    1
2506    1
2522    0
2545    1
2577    1
2592    0
2613    0
2637    1
Name: FTR, dtype: object
0.6
Sevilla - local
2435    3
2452    3
2471    3
2496    3
2512    1
2532    3
2552    1
2570    3
2590    3
2613    3
Name: FTR, dtype: object
2.6
22
14.1
Ath Madrid - visitante
2433    0
2458    3
2483    0
2504    3
2528    3
2551    0
2572    3
2595    0
2617    3
2635    3
Name: FTR, dtype: object
1.8
Real Madrid - local
2436    3
2450    3
2456    3
2486    3
2526    3
2554    3
2575    3
2591    3
2618    3
2635    0
Name: FTR, dtype: object
2.7
33
19.2
Villarreal - visitante
2431    0
2454    0
2487    1
2499    1
2514    3
2533    3
2553    1
2570    0
2593    3
2616    1
Name: FTR, dtype: object
1.3
Eibar - local
2430    0
2458    0
2488    3
2507    0
2521    3
2546    0
2576    1
2597    1
2616    1
2630    0
Name: FTR, dtype: object
0.9
13
11.8
Ath Bilbao - visitante
2438    1
2453    3
2476    0
2498    0
2511    1
2536    3
2550    1
2578    3
2591    0
2612    0
Name: FTR, dtype: object
1.2
Vallecano - local
2431    3
2460    0
2481    0
2505    0
2523    0
2542    3
2560    0
2594    0
2612    3
2631    0
Name: FTR, dtype: object
0.9
11
14.0
Levante - visitante
2434    0
2466    0
2474    0
2500    0
2518    1
2537    0
2552    1
2579    0
2597    1
2615    3
Name: FTR, dtype: object
0.6
Malaga - local
2437    0
2451    3
2487    1
2497    0
2516    3
2535    0
2555    3
2571    3
2596    3
2614    1
Name: FTR, dtype: object
1.7
13
13.7
Getafe - visitante
2432    0
2455    0
2488    0
2502    1
2520    1
2541    0
2569    3
2580    3
2611    0
2633    0
Name: FTR, dtype: object
0.8
Granada - local
2438    1
2457    3
2482    1
2502    1
2524    1
2540    1
2566    0
2589    0
2615    0
2634    1
Name: FTR, dtype: object
0.9
4
12.8
Barcelona - visitante
2444    3
2468    3
2472    3
2493    0
2517    1
2531    3
2558    3
2575    0
2594    3
2614    1
Name: FTR, dtype: object
2.0
Almeria - local
2439    1
2455    3
2485    0
2519    0
2530    0
2558    0
2578    0
2598    1
2617    0
2639    1
Name: FTR, dtype: object
0.6
8
11.4
La Coruna - visitante
2436    0
2460    3
2490    1
2501    0
2534    0
2559    1
2573    1
2590    0
2619    0
2630    3
Name: FTR, dtype: object
0.9
Espanol - local
2442    0
2464    3
2479    3
2495    0
2513    3
2537    3
2553    1
2573    1
2592    3
2611    3
Name: FTR, dtype: object
2.0
15
12.6
Cordoba - visitante
2435    0
2459    0
2481    3
2508    0
2529    3
2544    1
2568    0
2599    1
2610    0
2639    1
Name: FTR, dtype: object
0.9
Levante - local
2447    3
2453    0
2490    1
2506    1
2520    1
2543    3
2562    3
2585    0
2605    0
2623    0
Name: FTR, dtype: object
1.2
10
10.5
Granada - visitante
2445    0
2463    1
2475    0
2491    0
2513    0
2532    0
2557    1
2576    1
2596    0
2606    0
Name: FTR, dtype: object
0.3
Villarreal - local
2445    3
2466    3
2476    3
2501    3
2522    3
2541    3
2561    0
2581    3
2604    0
2621    3
Name: FTR, dtype: object
2.4
21
16.1
Eibar - visitante
2449    0
2467    0
2480    1
2495    3
2512    1
2538    3
2555    0
2560    3
2587    0
2608    1
Name: FTR, dtype: object
1.2
Sociedad - local
2446    1
2467    3
2478    0
2493    3
2511    1
2539    3
2551    3
2565    0
2580    0
2600    1
Name: FTR, dtype: object
1.5
11
11.5
Sevilla - visitante
2441    0
2450    0
2462    0
2485    3
2523    3
2547    0
2564    0
2583    3
2607    0
2624    3
Name: FTR, dtype: object
1.2
Elche - local
2440    3
2468    0
2474    3
2499    1
2503    0
2528    0
2544    1
2563    3
2583    0
2609    0

Name: FTR, dtype: object
1.1
10
12.8
Real Madrid - visitante
2448    0
2469    3
2473    3
2492    0
2519    3
2535    3
2546    3
2566    3
2585    3
2604    3
Name: FTR, dtype: object
2.4
Ath Bilbao - local
2444    0
2465    1
2484    0
2504    0
2529    0
2549    3
2564    3
2588    1
2608    1
2628    0
Name: FTR, dtype: object
0.9
10
11.5
Vallecano - visitante
2440    0
2470    0
2478    3
2494    3
2515    0
2530    3
2554    0
2571    0
2589    3
2605    3
Name: FTR, dtype: object
1.5
La Coruna - local
2449    3
2463    1
2472    0
2498    3
2510    3
2527    0
2545    1
2569    0
2582    3
2601    0
Name: FTR, dtype: object
1.4
10
11.1
Celta - visitante
2446    1
2461    0
2479    0
2496    0
2516    0
2526    0
2542    0
2567    3
2588    1
2609    3
Name: FTR, dtype: object
0.8
Cordoba - local
2443    0
2469    0
2480    1
2491    3
2518    1
2533    0
2559    1
2577    1
2586    0
2603    1
Name: FTR, dtype: object
0.8
7
11.2
Valencia - visitante
2442    3
2451    0
2489    1
2507    3
2524    1
2543    0
2561    3
2582    0
2600    1
2620    3
Name: FTR, dtype: object
1.5
Barcelona - local
2434    3
2454    3
2483    3
2508    3
2525    3
2547    3
2567    0
2587    3
2606    3
2638    3
Name: FTR, dtype: object
2.7
37
18.1
Malaga - visitante
2447    0
2465    1
2471    0
2503    3
2527    3
2548    0
2565    3
2586    3
2602    0
2626    1
Name: FTR, dtype: object
1.4
Ath Madrid - local
2448    3
2470    3
2475    3
2500    3
2514    0
2534    3
2548    3
2568    3
2584    3
2607    3
Name: FTR, dtype: object
2.7
27
13.2
Almeria - visitante
2443    3
2464    0
2477    0
2497    3
2509    3
2521    0
2540    1
2562    0
2581    0
2601    3
Name: FTR, dtype: object
1.3
Getafe - local
2441    3
2461    3
2473    0
2494    0
2517    1
2536    0
2556    1
2572    0
2599    1
2602    3
Name: FTR, dtype: object
1.2
8
12.1
Espanol - visitante
2437    3
2452    0
2486    0
2505    3
2525    0
2549    0
2563    0
2584    0
2603    1
2632    0
Name: FTR, dtype: object
0.7
Eibar - local
2458    0
2488    3
2507    0
2521    3
2546    0
2576    1
2597    1
2616    1
2630    0
2653    3
Name: FTR, dtype: object
1.2
14
11.2
Elche - visitante
2457    0
2484    3
2510    0
2539    0
2556    1
2574    0
2598    1
2618    0
2631    3
2655    0
Name: FTR, dtype: object
0.8
Vallecano - local
2460    0
2481    0
2505    0
2523    0
2542    3
2560    0
2594    0
2612    3
2631    0
2650    1
Name: FTR, dtype: object
0.7
9
13.5
Villarreal - visitante
2454    0
2487    1
2499    1
2514    3
2533    3
2553    1
2570    0
2593    3
2616    1
2634    1
Name: FTR, dtype: object
1.4
Valencia - local
2462    3
2477    3
2492    3
2515    3
2531    0
2550    1
2574    3
2595    3
2610    3
2632    3
Name: FTR, dtype: object
2.5
23
11.9
Getafe - visitante
2455    0
2488    0
2502    1
2520    1
2541    0
2569    3
2580    3
2611    0
2633    0
2654    0
Name: FTR, dtype: object
0.8
Celta - local
2459    3
2489    1
2509    0
2538    0
2557    1
2579    3
2593    0
2619    3
2637    1
2654    3
Name: FTR, dtype: object
1.5
13
17.0
Ath Madrid - visitante
2458    3
2483    0
2504    3
2528    3
2551    0
2572    3
2595    0
2617    3
2635    3
2650    1
Name: FTR, dtype: object
1.9
Barcelona - local
2454    3
2483    3
2508    3
2525    3
2547    3
2567    0
2587    3
2606    3
2638    3
2655    3
Name: FTR, dtype: object
2.7
35
17.5
Levante - visitante
2466    0
2474    0
2500    0
2518    1
2537    0
2552    1
2579    0
2597    1
2615    3
2636    1
Name: FTR, dtype: object
0.7
Sevilla - local
2452    3
2471    3
2496    3
2512    1
2532    3
2552    1
2570    3
2590    3
2613    3
2633    3
Name: FTR, dtype: object
2.6
21
13.5
Cordoba - visitante
2459    0
2481    3
2508    0
2529    3
2544    1
2568    0
2599    1
2610    0
2639    1
2651    0
Name: FTR, dtype: object
0.9
Real Madrid - local
2450    3
2456    3
2486    3
2526    3
2554    3
2575    3
2591    3
2618    3
2635    0
2651    3
Name: FTR, dtype: object
2.7
33
18.9
La Coruna - visitante
2460    3
2490    1
2501    0
2534    0
2559    1
2573    1
2590    0
2619    0
2630    3
2658    0
Name: FTR, dtype: object
0.9
Malaga - local
2451    3
2487    1
2497    0
2516    3
2535    0
2555    3
2571    3
2596    3
2614    1
2636    1
Name: FTR, dtype: object
1.8
13
13.8
Espanol - visitante
2452    0
2486    0
2505    3
2525    0
2549    0
2563    0
2584    0
2603    1
2632    0
2659    1
Name: FTR, dtype: object
0.5
Granada - local
2457    3
2482    1
2502    1
2524    1
2540    1
2566    0
2589    0
2615    0
2634    1
2658    3
Name: FTR, dtype: object
1.1
6
12.7
Ath Bilbao - visitante
2453    3
2476    0
2498    0
2511    1
2536    3
2550    1
2578    3
2591    0
2612    0
2638    0
Name: FTR, dtype: object
1.1
Almeria - local
2455    3
2485    0
2519    0
2530    0
2558    0
2578    0
2598    1
2617    0
2639    1
2659    1
Name: FTR, dtype: object
0.6
7
12.4
Sociedad - visitante
2456    0
2482    1
2506    1
2522    0
2545    1
2577    1
2592    0
2613    0
2637    1
2653    0
Name: FTR, dtype: object
0.5
Elche - local
2468    0
2474    3
2499    1
2503    0
2528    0
2544    1
2563    3
2583    0
2609    0
2629    0
Name: FTR, dtype: object
0.8
8
12.5
Vallecano - visitante
2470    0
2478    3
2494    3
2515    0
2530    3
2554    0
2571    0
2589    3
2605    3
2621    0
Name: FTR, dtype: object
1.5
Getafe - local
2461    3
2473    0
2494    0
2517    1
2536    0
2556    1
2572    0
2599    1
2602    3
2620    0
Name: FTR, dtype: object
0.9
6
11.5
Sevilla - visitante
2450    0
2462    0
2485    3
2523    3
2547    0
2564    0
2583    3
2607    0
2624    3
2644    3
Name: FTR, dtype: object
1.5
Espanol - local
2464    3
2479    3
2495    0
2513    3
2537    3
2553    1
2573    1
2592    3
2611    3
2626    1
Name: FTR, dtype: object
2.1
16
13.0
Valencia - visitante
2451    0
2489    1
2507    3
2524    1
2543    0
2561    3
2582    0
2600    1
2620    3
2656    1
Name: FTR, dtype: object
1.3
Cordoba - local
2469    0
2480    1
2491    3
2518    1
2533    0
2559    1
2577    1
2586    0
2603    1
2624    0
Name: FTR, dtype: object
0.8
7
10.7
Almeria - visitante
2464    0
2477    0
2497    3
2509    3
2521    0
2540    1
2562    0
2581    0
2601    3
2622    3
Name: FTR, dtype: object
1.3
Ath Bilbao - local
2465    1
2484    0
2504    0
2529    0
2549    3
2564    3
2588    1
2608    1
2628    0
2647    3
Name: FTR, dtype: object
1.2
11
11.0
Barcelona - visitante
2468    3
2472    3
2493    0
2517    1
2531    3
2558    3
2575    0
2594    3
2614    1
2623    3
Name: FTR, dtype: object
2.0
Villarreal - local
2466    3
2476    3
2501    3
2522    3
2541    3
2561    0
2581    3
2604    0
2621    3
2640    0
Name: FTR, dtype: object
2.1
19
16.1
Granada - visitante
2463    1
2475    0
2491    0
2513    0
2532    0
2557    1
2576    1
2596    0
2606    0
2628    3
Name: FTR, dtype: object
0.6
Sociedad - local
2467    3
2478    0
2493    3
2511    1
2539    3
2551    3
2565    0
2580    0
2600    1
2622    0
Name: FTR, dtype: object
1.4
11
13.0
Celta - visitante
2461    0
2479    0
2496    0
2516    0
2526    0
2542    0
2567    3
2588    1
2609    3
2627    1
Name: FTR, dtype: object
0.8
Levante - local
2453    0
2490    1
2506    1
2520    1
2543    3
2562    3
2585    0
2605    0
2623    0
2652    0
Name: FTR, dtype: object
0.9
6
10.3
Malaga - visitante
2465    1
2471    0
2503    3
2527    3
2548    0
2565    3
2586    3
2602    0
2626    1
2648    0
Name: FTR, dtype: object
1.4
Ath Madrid - local
2470    3
2475    3
2500    3
2514    0
2534    3
2548    3
2568    3
2584    3
2607    3
2627    1
Name: FTR, dtype: object
2.5
25
13.3
Real Madrid - visitante
2469    3
2473    3
2492    0
2519    3
2535    3
2546    3
2566    3
2585    3
2604    3
2625    3
Name: FTR, dtype: object
2.7
La Coruna - local
2463    1
2472    0
2498    3
2510    3
2527    0
2545    1
2569    0
2582    3
2601    0
2625    0
Name: FTR, dtype: object
1.1
10
11.0
Eibar - visitante
2467    0
2480    1
2495    3
2512    1
2538    3
2555    0
2560    3
2587    0
2608    1
2629    3
Name: FTR, dtype: object
1.5
Real Madrid - local
2456    3
2486    3
2526    3
2554    3
2575    3
2591    3
2618    3
2635    0
2651    3
2667    3
Name: FTR, dtype: object
2.7
34
19.2
Sevilla - visitante
2462    0
2485    3
2523    3
2547    0
2564    0
2583    3
2607    0
2624    3
2644    3
2671    0
Name: FTR, dtype: object
1.5
Malaga - local
2487    1
2497    0
2516    3
2535    0
2555    3
2571    3
2596    3
2614    1
2636    1
2657    3
Name: FTR, dtype: object
1.8
13
13.7
Valencia - visitante
2489    1
2507    3
2524    1
2543    0
2561    3
2582    0
2600    1
2620    3
2656    1
2679    0
Name: FTR, dtype: object
1.3
Sevilla - local
2471    3
2496    3
2512    1
2532    3
2552    1
2570    3
2590    3
2613    3
2633    3
2656    1
Name: FTR, dtype: object
2.4
19
12.3
Espanol - visitante
2486    0
2505    3
2525    0
2549    0
2563    0
2584    0
2603    1
2632    0
2659    1
2667    0
Name: FTR, dtype: object
0.5
Levante - local
2490    1
2506    1
2520    1
2543    3
2562    3
2585    0
2605    0
2623    0
2652    0
2679    3
Name: FTR, dtype: object
1.2
8
10.5
Ath Bilbao - visitante
2476    0
2498    0
2511    1
2536    3
2550    1
2578    3
2591    0
2612    0
2638    0
2657    0
Name: FTR, dtype: object
0.8
Barcelona - local
2483    3
2508    3
2525    3
2547    3
2567    0
2587    3
2606    3
2638    3
2655    3
2668    1
Name: FTR, dtype: object
2.5
33
16.7
Villarreal - visitante
2487    1
2499    1
2514    3
2533    3
2553    1
2570    0
2593    3
2616    1
2634    1
2652    3
Name: FTR, dtype: object
1.7
Almeria - local
2485    0
2519    0
2530    0
2558    0
2578    0
2598    1
2617    0
2639    1
2659    1
2665    1
Name: FTR, dtype: object
0.4
6
12.2
Getafe - visitante
2488    0
2502    1
2520    1
2541    0
2569    3
2580    3
2611    0
2633    0
2654    0
2660    3
Name: FTR, dtype: object
1.1
Real Madrid - local
2486    3
2526    3
2554    3
2575    3
2591    3
2618    3
2635    0
2651    3
2667    3
2683    1
Name: FTR, dtype: object
2.5
32
19.8
Sociedad - visitante
2482    1
2506    1
2522    0
2545    1
2577    1
2592    0
2613    0
2637    1
2653    0
2677    1
Name: FTR, dtype: object
0.6
Granada - local
2482    1
2502    1
2524    1
2540    1
2566    0
2589    0
2615    0
2634    1
2658    3
2670    0
Name: FTR, dtype: object
0.8
5
12.9
Elche - visitante
2484    3
2510    0
2539    0
2556    1
2574    0
2598    1
2618    0
2631    3
2655    0
2663    0
Name: FTR, dtype: object
0.8
Eibar - local
2488    3
2507    0
2521    3
2546    0
2576    1
2597    1
2616    1
2630    0
2653    3

Name: FTR, dtype: object
1.3333333333333333
13
11.222222222222221
Ath Madrid - visitante
2483    0
2504    3
2528    3
2551    0
2572    3
2595    0
2617    3
2635    3
2650    1
2668    1
Name: FTR, dtype: object
1.7
Celta - local
2489    1
2509    0
2538    0
2557    1
2579    3
2593    0
2619    3
2637    1
2654    3
2674    3
Name: FTR, dtype: object
1.5
14
16.4
Cordoba - visitante
2481    3
2508    0
2529    3
2544    1
2568    0
2599    1
2610    0
2639    1
2651    0
Name: FTR, dtype: object
1.0
Vallecano - local
2481    0
2505    0
2523    0
2542    3
2560    0
2594    0
2612    3
2631    0
2650    1
2660    0
Name: FTR, dtype: object
0.7
9
14.0
La Coruna - visitante
2490    1
2501    0
2534    0
2559    1
2573    1
2590    0
2619    0
2630    3
2658    0
3054    0
Name: FTR, dtype: object
0.6
Getafe - local
2473    0
2494    0
2517    1
2536    0
2556    1
2572    0
2599    1
2602    3
2620    0
2649    3
Name: FTR, dtype: object
0.9
5
11.4
Celta - visitante
2479    0
2496    0
2516    0
2526    0
2542    0
2567    3
2588    1
2609    3
2627    1
2645    1
Name: FTR, dtype: object
0.9
Valencia - local
2477    3
2492    3
2515    3
2531    0
2550    1
2574    3
2595    3
2610    3
2632    3
2648    3
Name: FTR, dtype: object
2.5
23
12.0
Sevilla - visitante
2485    3
2523    3
2547    0
2564    0
2583    3
2607    0
2624    3
2644    3
2671    0
2695    0
Name: FTR, dtype: object
1.5
La Coruna - local
2472    0
2498    3
2510    3
2527    0
2545    1
2569    0
2582    3
2601    0
2625    0
2642    1
Name: FTR, dtype: object
1.1
10
10.7
Granada - visitante
2475    0
2491    0
2513    0
2532    0
2557    1
2576    1
2596    0
2606    0
2628    3
2643    1
Name: FTR, dtype: object
0.6
Espanol - local
2479    3
2495    0
2513    3
2537    3
2553    1
2573    1
2592    3
2611    3
2626    1
2644    0
Name: FTR, dtype: object
1.8
14
11.6
Almeria - visitante
2477    0
2497    3
2509    3
2521    0
2540    1
2562    0
2581    0
2601    3
2622    3
2649    0
Name: FTR, dtype: object
1.3
Ath Bilbao - local
2484    0
2504    0
2529    0
2549    3
2564    3
2588    1
2608    1
2628    0
2647    3
2677    1
Name: FTR, dtype: object
1.2
11
11.1
Malaga - visitante
2471    0
2503    3
2527    3
2548    0
2565    3
2586    3
2602    0
2626    1
2648    0
2676    1
Name: FTR, dtype: object
1.4
Villarreal - local
2476    3
2501    3
2522    3
2541    3
2561    0
2581    3
2604    0
2621    3
2640    0
2678    3
Name: FTR, dtype: object
2.1
22
16.8
Levante - visitante
2474    0
2500    0
2518    1
2537    0
2552    1
2579    0
2597    1
2615    3
2636    1
2647    0
Name: FTR, dtype: object
0.7
Sociedad - local
2478    0
2493    3
2511    1
2539    3
2551    3
2565    0
2580    0
2600    1
2622    0
2641    3
Name: FTR, dtype: object
1.4
14
12.4
Eibar - visitante
2480    1
2495    3
2512    1
2538    3
2555    0
2560    3
2587    0
2608    1
2629    3
2646    0
Name: FTR, dtype: object
1.5
Elche - local
2474    3
2499    1
2503    0
2528    0
2544    1
2563    3
2583    0
2609    0
2629    0
2643    1
Name: FTR, dtype: object
0.9
9
13.4
Barcelona - visitante
2472    3
2493    0
2517    1
2531    3
2558    3
2575    0
2594    3
2614    1
2623    3
2640    3
Name: FTR, dtype: object
2.0
Cordoba - local
2480    1
2491    3
2518    1
2533    0
2559    1
2577    1
2586    0
2603    1
2624    0
2645    1
Name: FTR, dtype: object
0.9
7
9.7
Real Madrid - visitante
2473    3
2492    0
2519    3
2535    3
2546    3
2566    3
2585    3
2604    3
2625    3
2641    0
Name: FTR, dtype: object
2.4
Ath Madrid - local
2475    3
2500    3
2514    0
2534    3
2548    3
2568    3
2584    3
2607    3
2627    1
2646    3
Name: FTR, dtype: object
2.5
24
13.6
Vallecano - visitante
2478    3
2494    3
2515    0
2530    3
2554    0
2571    0
2589    3
2605    3
2621    0
2642    1
Name: FTR, dtype: object
1.6
Sevilla - local
2496    3
2512    1
2532    3
2552    1
2570    3
2590    3
2613    3
2633    3
2656    1
2663    3
Name: FTR, dtype: object
2.4
20
13.4
Malaga - visitante
2503    3
2527    3
2548    0
2565    3
2586    3
2602    0
2626    1
2648    0
2676    1
2698    0
Name: FTR, dtype: object
1.4
La Coruna - local
2498    3
2510    3
2527    0
2545    1
2569    0
2582    3
2601    0
2625    0
2642    1
3046    0
Name: FTR, dtype: object
1.1
10
12.0
Barcelona - visitante
2493    0
2517    1
2531    3
2558    3
2575    0
2594    3
2614    1
2623    3
2640    3
2673    1
Name: FTR, dtype: object
1.8
Getafe - local
2494    0
2517    1
2536    0
2556    1
2572    0
2599    1
2602    3
2620    0
2649    3
2671    3
Name: FTR, dtype: object
1.2
6
12.2
Real Madrid - visitante
2492    0
2519    3
2535    3
2546    3
2566    3
2585    3
2604    3
2625    3
2641    0
2674    0
Name: FTR, dtype: object
2.1
Elche - local
2499    1
2503    0
2528    0
2544    1
2563    3
2583    0
2609    0
2629    0
2643    1
2673    1
Name: FTR, dtype: object
0.7
8
12.5
Levante - visitante
2500    0
2518    1
2537    0
2552    1
2579    0
2597    1
2615    3
2636    1
2647    0
2669    0
Name: FTR, dtype: object
0.7
Ath Madrid - local
2500    3
2514    0
2534    3
2548    3
2568    3
2584    3
2607    3
2627    1
2646    3
2676    1
Name: FTR, dtype: object
2.3
23
14.1
Granada - visitante
2491    0
2513    0
2532    0
2557    1
2576    1
2596    0
2606    0
2628    3
2643    1
2661    3
Name: FTR, dtype: object
0.9
Villarreal - local
2501    3
2522    3
2541    3
2561    0
2581    3
2604    0
2621    3
2640    0
2678    3
2692    0
Name: FTR, dtype: object
1.8
22
15.4
Ath Bilbao - visitante
2498    0
2511    1
2536    3
2550    1
2578    3
2591    0
2612    0
2638    0
2657    0
2665    1
Name: FTR, dtype: object
0.9
Valencia - local
2492    3
2515    3
2531    0
2550    1
2574    3
2595    3
2610    3
2632    3
2648    3
2666    3
Name: FTR, dtype: object
2.5
22
11.9
Almeria - visitante
2497    3
2509    3
2521    0
2540    1
2562    0
2581    0
2601    3
2622    3
2649    0
2670    3
Name: FTR, dtype: object
1.6
Sociedad - local
2493    3
2511    1
2539    3
2551    3
2565    0
2580    0
2600    1
2622    0
2641    3
2662    0
Name: FTR, dtype: object
1.4
15
12.7
Vallecano - visitante
2494    3
2515    0
2530    3
2554    0
2571    0
2589    3
2605    3
2621    0
2642    1
2678    0
Name: FTR, dtype: object
1.3
Espanol - local
2495    0
2513    3
2537    3
2553    1
2573    1
2592    3
2611    3
2626    1
2644    0
2672    1
Name: FTR, dtype: object
1.6
14
10.8
Celta - visitante
2496    0
2516    0
2526    0
2542    0
2567    3
2588    1
2609    3
2627    1
2645    1
2666    0
Name: FTR, dtype: object
0.9
Cordoba - local
2491    3
2518    1
2533    0
2559    1
2577    1
2586    0
2603    1
2624    0
2645    1
Name: FTR, dtype: object
0.8888888888888888
6
9.222222222222221
Eibar - visitante
2495    3
2512    1
2538    3
2555    0
2560    3
2587    0
2608    1
2629    3
2646    0
Name: FTR, dtype: object
1.5555555555555556
Vallecano - local
2505    0
2523    0
2542    3
2560    0
2594    0
2612    3
2631    0
2650    1
2660    0
2690    0
Name: FTR, dtype: object
0.7
9
13.0
Cordoba - visitante
2508    0
2529    3
2544    1
2568    0
2599    1
2610    0
2639    1
2651    0
Name: FTR, dtype: object
0.75
Granada - local
2502    1
2524    1
2540    1
2566    0
2589    0
2615    0
2634    1
2658    3
2670    0
2697    0
Name: FTR, dtype: object
0.7
4
12.1
Sociedad - visitante
2506    1
2522    0
2545    1
2577    1
2592    0
2613    0
2637    1
2653    0
2677    1
2699    3
Name: FTR, dtype: object
0.8
Barcelona - local
2508    3
2525    3
2547    3
2567    0
2587    3
2606    3
2638    3
2655    3
2668    1
2689    1
Name: FTR, dtype: object
2.3
32
17.1
Ath Madrid - visitante
2504    3
2528    3
2551    0
2572    3
2595    0
2617    3
2635    3
2650    1
2668    1
2684    0
Name: FTR, dtype: object
1.7
Ath Bilbao - local
2504    0
2529    0
2549    3
2564    3
2588    1
2608    1
2628    0
2647    3
2677    1
2695    3
Name: FTR, dtype: object
1.5
13
11.0
Elche - visitante
2510    0
2539    0
2556    1
2574    0
2598    1
2618    0
2631    3
2655    0
2663    0
2688    3
Name: FTR, dtype: object
0.8
Almeria - local
2519    0
2530    0
2558    0
2578    0
2598    1
2617    0
2639    1
2659    1
2665    1
2685    3
Name: FTR, dtype: object
0.7
9
11.5
Sevilla - visitante
2523    3
2547    0
2564    0
2583    3
2607    0
2624    3
2644    3
2671    0
2695    0
2714    3
Name: FTR, dtype: object
1.5
Real Madrid - local
2526    3
2554    3
2575    3
2591    3
2618    3
2635    0
2651    3
2667    3
2683    1
2696    3
Name: FTR, dtype: object
2.5
33
20.0
Espanol - visitante
2505    3
2525    0
2549    0
2563    0
2584    0
2603    1
2632    0
2659    1
2667    0
2686    0
Name: FTR, dtype: object
0.5
Malaga - local
2497    0
2516    3
2535    0
2555    3
2571    3
2596    3
2614    1
2636    1
2657    3
2669    3
Name: FTR, dtype: object
2.0
13
14.9
Villarreal - visitante
2499    1
2514    3
2533    3
2553    1
2570    0
2593    3
2616    1
2634    1
2652    3
2662    3
Name: FTR, dtype: object
1.9
Eibar - local
2507    0
2521    3
2546    0
2576    1
2597    1
2616    1
2630    0
2653    3
Name: FTR, dtype: object
1.125
11
11.125
Getafe - visitante
2502    1
2520    1
2541    0
2569    3
2580    3
2611    0
2633    0
2654    0
2660    3
2689    1
Name: FTR, dtype: object
1.2
Celta - local
2509    0
2538    0
2557    1
2579    3
2593    0
2619    3
2637    1
2654    3
2674    3
2691    3
Name: FTR, dtype: object
1.7
17
16.3
Valencia - visitante
2507    3
2524    1
2543    0
2561    3
2582    0
2600    1
2620    3
2656    1
2679    0
2683    1
Name: FTR, dtype: object
1.3
Levante - local
2506    1
2520    1
2543    3
2562    3
2585    0
2605    0
2623    0
2652    0
2679    3
2684    3
Name: FTR, dtype: object
1.4
10
10.3
La Coruna - visitante
2501    0
2534    0
2559    1
2573    1
2590    0
2619    0
2630    3
2658    0
3054    0
3073    0
Name: FTR, dtype: object
0.5
Cordoba - local
2518    1
2533    0
2559    1
2577    1
2586    0
2603    1
2624    0
2645    1
Name: FTR, dtype: object
0.625
4
9.75
Granada - visitante
2513    0
2532    0
2557    1
2576    1
2596    0
2606    0
2628    3
2643    1
2661    3
2681    1
Name: FTR, dtype: object
1.0
Valencia - local
2515    3
2531    0
2550    1
2574    3
2595    3
2610    3
2632    3
2648    3
2666    3
2693    0
Name: FTR, dtype: object
2.2
20
11.9
Real Madrid - visitante
2519    3
2535    3
2546    3
2566    3
2585    3
2604    3
2625    3
2641    0
2674    0
2680    1
Name: FTR, dtype: object
2.2
Sociedad - local
2511    1
2539    3
2551    3
2565    0
2580    0
2600    1
2622    0
2641    3
2662    0
2681    1
Name: FTR, dtype: object
1.2
15
14.2
Barcelona - visitante
2517    1
2531    3
2558    3
2575    0
2594    3
2614    1
2623    3
2640    3
2673    1
2692    3
Name: FTR, dtype: object
2.1
Getafe - local
2517    1
2536    0
2556    1
2572    0
2599    1
2602    3
2620    0
2649    3
2671    3
2698    3

Name: FTR, dtype: object
1.5
6
11.8
Vallecano - visitante
2515    0
2530    3
2554    0
2571    0
2589    3
2605    3
2621    0
2642    1
2678    0
2697    3
Name: FTR, dtype: object
1.3
Espanol - local
2513    3
2537    3
2553    1
2573    1
2592    3
2611    3
2626    1
2644    0
2672    1
2694    0
Name: FTR, dtype: object
1.6
14
10.2
Eibar - visitante
2512    1
2538    3
2555    0
2560    3
2587    0
2608    1
2629    3
2646    0
Name: FTR, dtype: object
1.375
Sevilla - local
2512    1
2532    3
2552    1
2570    3
2590    3
2613    3
2633    3
2656    1
2663    3
2682    1
Name: FTR, dtype: object
2.2
19
13.5
Celta - visitante
2516    0
2526    0
2542    0
2567    3
2588    1
2609    3
2627    1
2645    1
2666    0
2687    3
Name: FTR, dtype: object
1.2
Malaga - local
2516    3
2535    0
2555    3
2571    3
2596    3
2614    1
2636    1
2657    3
2669    3
2688    0
Name: FTR, dtype: object
2.0
12
14.2
Almeria - visitante
2509    3
2521    0
2540    1
2562    0
2581    0
2601    3
2622    3
2649    0
2670    3
2694    3
Name: FTR, dtype: object
1.6
La Coruna - local
2510    3
2527    0
2545    1
2569    0
2582    3
2601    0
2625    0
2642    1
3046    0
3063    3
Name: FTR, dtype: object
1.1
11
12.9
Ath Bilbao - visitante
2511    1
2536    3
2550    1
2578    3
2591    0
2612    0
2638    0
2657    0
2665    1
2690    3
Name: FTR, dtype: object
1.2
Elche - local
2503    0
2528    0
2544    1
2563    3
2583    0
2609    0
2629    0
2643    1
2673    1
2700    1
Name: FTR, dtype: object
0.7
7
12.9
Villarreal - visitante
2514    3
2533    3
2553    1
2570    0
2593    3
2616    1
2634    1
2652    3
2662    3
2682    1
Name: FTR, dtype: object
1.9
Ath Madrid - local
2514    0
2534    3
2548    3
2568    3
2584    3
2607    3
2627    1
2646    3
2676    1
2709    3
Name: FTR, dtype: object
2.3
22
14.2
Levante - visitante
2518    1
2537    0
2552    1
2579    0
2597    1
2615    3
2636    1
2647    0
2669    0
2700    1
Name: FTR, dtype: object
0.8
Villarreal - local
2522    3
2541    3
2561    0
2581    3
2604    0
2621    3
2640    0
2678    3
2692    0
2715    3
Name: FTR, dtype: object
1.8
20
15.1
La Coruna - visitante
2534    0
2559    1
2573    1
2590    0
2619    0
2630    3
2658    0
3054    0
3073    0
3090    1
Name: FTR, dtype: object
0.6
Granada - local
2524    1
2540    1
2566    0
2589    0
2615    0
2634    1
2658    3
2670    0
2697    0
2717    3
Name: FTR, dtype: object
0.9
4
11.3
Getafe - visitante
2520    1
2541    0
2569    3
2580    3
2611    0
2633    0
2654    0
2660    3
2689    1
2708    1
Name: FTR, dtype: object
1.2
Elche - local
2528    0
2544    1
2563    3
2583    0
2609    0
2629    0
2643    1
2673    1
2700    1
2724    3
Name: FTR, dtype: object
1.0
7
13.6
Malaga - visitante
2527    3
2548    0
2565    3
2586    3
2602    0
2626    1
2648    0
2676    1
2698    0
2710    0
Name: FTR, dtype: object
1.1
Ath Bilbao - local
2529    0
2549    3
2564    3
2588    1
2608    1
2628    0
2647    3
2677    1
2695    3
2710    3
Name: FTR, dtype: object
1.8
15
11.8
Ath Madrid - visitante
2528    3
2551    0
2572    3
2595    0
2617    3
2635    3
2650    1
2668    1
2684    0
2693    3
Name: FTR, dtype: object
1.7
Vallecano - local
2523    0
2542    3
2560    0
2594    0
2612    3
2631    0
2650    1
2660    0
2690    0
2702    3
Name: FTR, dtype: object
1.0
11
13.0
Espanol - visitante
2525    0
2549    0
2563    0
2584    0
2603    1
2632    0
2659    1
2667    0
2686    0
2706    0
Name: FTR, dtype: object
0.2
Levante - local
2520    1
2543    3
2562    3
2585    0
2605    0
2623    0
2652    0
2679    3
2684    3
2708    1
Name: FTR, dtype: object
1.4
9
10.3
Sociedad - visitante
2522    0
2545    1
2577    1
2592    0
2613    0
2637    1
2653    0
2677    1
2699    3
2718    1
Name: FTR, dtype: object
0.8
Eibar - local
2521    3
2546    0
2576    1
2597    1
2616    1
2630    0
2653    3
Name: FTR, dtype: object
1.2857142857142858
11
11.571428571428571
Valencia - visitante
2524    1
2543    0
2561    3
2582    0
2600    1
2620    3
2656    1
2679    0
2683    1
2707    1
Name: FTR, dtype: object
1.1
Barcelona - local
2525    3
2547    3
2567    0
2587    3
2606    3
2638    3
2655    3
2668    1
2689    1
2704    3
Name: FTR, dtype: object
2.3
29
17.2
Cordoba - visitante
2529    3
2544    1
2568    0
2599    1
2610    0
2639    1
2651    0
Name: FTR, dtype: object
0.8571428571428571
Celta - local
2538    0
2557    1
2579    3
2593    0
2619    3
2637    1
2654    3
2674    3
2691    3
2718    1
Name: FTR, dtype: object
1.8
19
15.9
Almeria - visitante
2521    0
2540    1
2562    0
2581    0
2601    3
2622    3
2649    0
2670    3
2694    3
2716    0
Name: FTR, dtype: object
1.3
La Coruna - local
2527    0
2545    1
2569    0
2582    3
2601    0
2625    0
2642    1
3046    0
3063    3
3087    1
Name: FTR, dtype: object
0.9
10
12.4
Elche - visitante
2539    0
2556    1
2574    0
2598    1
2618    0
2631    3
2655    0
2663    0
2688    3
2709    0
Name: FTR, dtype: object
0.8
Sociedad - local
2539    3
2551    3
2565    0
2580    0
2600    1
2622    0
2641    3
2662    0
2681    1
2706    3
Name: FTR, dtype: object
1.4
16
14.7
Ath Bilbao - visitante
2536    3
2550    1
2578    3
2591    0
2612    0
2638    0
2657    0
2665    1
2690    3
2704    0
Name: FTR, dtype: object
1.1
Sevilla - local
2532    3
2552    1
2570    3
2590    3
2613    3
2633    3
2656    1
2663    3
2682    1
2703    3
Name: FTR, dtype: object
2.4
23
12.9
Eibar - visitante
2538    3
2555    0
2560    3
2587    0
2608    1
2629    3
2646    0
Name: FTR, dtype: object
1.4285714285714286
Espanol - local
2537    3
2553    1
2573    1
2592    3
2611    3
2626    1
2644    0
2672    1
2694    0
2713    1
Name: FTR, dtype: object
1.4
14
9.6
Granada - visitante
2532    0
2557    1
2576    1
2596    0
2606    0
2628    3
2643    1
2661    3
2681    1
2703    0
Name: FTR, dtype: object
1.0
Ath Madrid - local
2534    3
2548    3
2568    3
2584    3
2607    3
2627    1
2646    3
2676    1
2709    3
2728    3
Name: FTR, dtype: object
2.6
23
13.7
Villarreal - visitante
2533    3
2553    1
2570    0
2593    3
2616    1
2634    1
2652    3
2662    3
2682    1
2701    0
Name: FTR, dtype: object
1.6
Valencia - local
2531    0
2550    1
2574    3
2595    3
2610    3
2632    3
2648    3
2666    3
2693    0
2711    3
Name: FTR, dtype: object
2.2
19
11.3
Vallecano - visitante
2530    3
2554    0
2571    0
2589    3
2605    3
2621    0
2642    1
2678    0
2697    3
2713    1
Name: FTR, dtype: object
1.4
Malaga - local
2535    0
2555    3
2571    3
2596    3
2614    1
2636    1
2657    3
2669    3
2688    0
2701    3
Name: FTR, dtype: object
2.0
13
14.4
Celta - visitante
2526    0
2542    0
2567    3
2588    1
2609    3
2627    1
2645    1
2666    0
2687    3
2705    3
Name: FTR, dtype: object
1.5
Getafe - local
2536    0
2556    1
2572    0
2599    1
2602    3
2620    0
2649    3
2671    3
2698    3
2712    0
Name: FTR, dtype: object
1.4
6
12.3
Barcelona - visitante
2531    3
2558    3
2575    0
2594    3
2614    1
2623    3
2640    3
2673    1
2692    3
2717    0
Name: FTR, dtype: object
2.0
Cordoba - local
2533    0
2559    1
2577    1
2586    0
2603    1
2624    0
2645    1
Name: FTR, dtype: object
0.5714285714285714
4
9.285714285714286
Levante - visitante
2537    0
2552    1
2579    0
2597    1
2615    3
2636    1
2647    0
2669    0
2700    1
2715    0
Name: FTR, dtype: object
0.7
Almeria - local
2530    0
2558    0
2578    0
2598    1
2617    0
2639    1
2659    1
2665    1
2685    3
2705    0
Name: FTR, dtype: object
0.7
10
11.0
Real Madrid - visitante
2535    3
2546    3
2566    3
2585    3
2604    3
2625    3
2641    0
2674    0
2680    1
2726    3
Name: FTR, dtype: object
2.2
Levante - local
2543    3
2562    3
2585    0
2605    0
2623    0
2652    0
2679    3
2684    3
2708    1
2720    0
Name: FTR, dtype: object
1.3
9
9.8
Getafe - visitante
2541    0
2569    3
2580    3
2611    0
2633    0
2654    0
2660    3
2689    1
2708    1
2724    0
Name: FTR, dtype: object
1.1
Eibar - local
2546    0
2576    1
2597    1
2616    1
2630    0
2653    3
Name: FTR, dtype: object
1.0
6
10.666666666666666
Almeria - visitante
2540    1
2562    0
2581    0
2601    3
2622    3
2649    0
2670    3
2694    3
2716    0
2733    0
Name: FTR, dtype: object
1.3
Villarreal - local
2541    3
2561    0
2581    3
2604    0
2621    3
2640    0
2678    3
2692    0
2715    3
2732    1
Name: FTR, dtype: object
1.6
17
13.7
Sociedad - visitante
2545    1
2577    1
2592    0
2613    0
2637    1
2653    0
2677    1
2699    3
2718    1
2735    1
Name: FTR, dtype: object
0.9
Vallecano - local
2542    3
2560    0
2594    0
2612    3
2631    0
2650    1
2660    0
2690    0
2702    3
2725    3
Name: FTR, dtype: object
1.3
14
13.3
Sevilla - visitante
2547    0
2564    0
2583    3
2607    0
2624    3
2644    3
2671    0
2695    0
2714    3
2738    0
Name: FTR, dtype: object
1.2
Granada - local
2540    1
2566    0
2589    0
2615    0
2634    1
2658    3
2670    0
2697    0
2717    3
2730    0
Name: FTR, dtype: object
0.8
3
11.2
Valencia - visitante
2543    0
2561    3
2582    0
2600    1
2620    3
2656    1
2679    0
2683    1
2707    1
2721    1
Name: FTR, dtype: object
1.1
Barcelona - local
2547    3
2567    0
2587    3
2606    3
2638    3
2655    3
2668    1
2689    1
2704    3
2727    3
Name: FTR, dtype: object
2.3
27
16.9
Espanol - visitante
2549    0
2563    0
2584    0
2603    1
2632    0
2659    1
2667    0
2686    0
2706    0
2722    0
Name: FTR, dtype: object
0.2
Real Madrid - local
2554    3
2575    3
2591    3
2618    3
2635    0
2651    3
2667    3
2683    1
2696    3
2716    3
Name: FTR, dtype: object
2.5
34
20.9
Celta - visitante
2542    0
2567    3
2588    1
2609    3
2627    1
2645    1
2666    0
2687    3
2705    3
2725    0
Name: FTR, dtype: object
1.5
La Coruna - local
2545    1
2569    0
2582    3
2601    0
2625    0
2642    1
3046    0
3063    3
3087    1
3103    1
Name: FTR, dtype: object
1.0
11
12.0
Malaga - visitante
2548    0
2565    3
2586    3
2602    0
2626    1
2648    0
2676    1
2698    0
2710    0
2731    3
Name: FTR, dtype: object
1.1
Elche - local
2544    1
2563    3
2583    0
2609    0
2629    0
2643    1
2673    1
2700    1
2724    3
2749    1
Name: FTR, dtype: object
1.1
7
14.0
Ath Madrid - visitante
2551    0
2572    3
2595    0
2617    3
2635    3
2650    1
2668    1
2684    0
2693    3
2712    3
Name: FTR, dtype: object
1.7
Ath Bilbao - local
2549    3
2564    3
2588    1
2608    1
2628    0
2647    3
2677    1
2695    3
2710    3
2739    0
Name: FTR, dtype: object
1.8
16
11.6
Cordoba - visitante
2544    1
2568    0
2599    1
2610    0
2639    1
2651    0
Name: FTR, dtype: object
0.5
Almeria - local
2558    0
2578    0
2598    1
2617    0
2639    1
2659    1
2665    1
2685    3
2705    0
2729    0

Name: FTR, dtype: object
0.7
11
11.5
Vallecano - visitante
2554    0
2571    0
2589    3
2605    3
2621    0
2642    1
2678    0
2697    3
2713    1
2736    0
Name: FTR, dtype: object
1.1
Valencia - local
2550    1
2574    3
2595    3
2610    3
2632    3
2648    3
2666    3
2693    0
2711    3
2734    0
Name: FTR, dtype: object
2.2
20
12.0
Barcelona - visitante
2558    3
2575    0
2594    3
2614    1
2623    3
2640    3
2673    1
2692    3
2717    0
2737    3
Name: FTR, dtype: object
2.0
Sevilla - local
2552    1
2570    3
2590    3
2613    3
2633    3
2656    1
2663    3
2682    1
2703    3
2722    3
Name: FTR, dtype: object
2.4
22
12.9
Granada - visitante
2557    1
2576    1
2596    0
2606    0
2628    3
2643    1
2661    3
2681    1
2703    0
2723    0
Name: FTR, dtype: object
1.0
Cordoba - local
2559    1
2577    1
2586    0
2603    1
2624    0
2645    1
Name: FTR, dtype: object
0.6666666666666666
4
9.0
Villarreal - visitante
2553    1
2570    0
2593    3
2616    1
2634    1
2652    3
2662    3
2682    1
2701    0
2728    0
Name: FTR, dtype: object
1.3
Ath Madrid - local
2548    3
2568    3
2584    3
2607    3
2627    1
2646    3
2676    1
2709    3
2728    3
2747    3
Name: FTR, dtype: object
2.6
22
14.4
La Coruna - visitante
2559    1
2573    1
2590    0
2619    0
2630    3
2658    0
3054    0
3073    0
3090    1
3117    3
Name: FTR, dtype: object
0.9
Malaga - local
2555    3
2571    3
2596    3
2614    1
2636    1
2657    3
2669    3
2688    0
2701    3
2723    3
Name: FTR, dtype: object
2.3
16
14.3
Real Madrid - visitante
2546    3
2566    3
2585    3
2604    3
2625    3
2641    0
2674    0
2680    1
2726    3
2745    0
Name: FTR, dtype: object
1.9
Getafe - local
2556    1
2572    0
2599    1
2602    3
2620    0
2649    3
2671    3
2698    3
2712    0
2742    0
Name: FTR, dtype: object
1.4
5
12.1
Ath Bilbao - visitante
2550    1
2578    3
2591    0
2612    0
2638    0
2657    0
2665    1
2690    3
2704    0
2720    3
Name: FTR, dtype: object
1.1
Espanol - local
2553    1
2573    1
2592    3
2611    3
2626    1
2644    0
2672    1
2694    0
2713    1
2737    0
Name: FTR, dtype: object
1.1
12
9.4
Levante - visitante
2552    1
2579    0
2597    1
2615    3
2636    1
2647    0
2669    0
2700    1
2715    0
2730    3
Name: FTR, dtype: object
1.0
Celta - local
2557    1
2579    3
2593    0
2619    3
2637    1
2654    3
2674    3
2691    3
2718    1
2738    3
Name: FTR, dtype: object
2.1
20
14.4
Eibar - visitante
2555    0
2560    3
2587    0
2608    1
2629    3
2646    0
Name: FTR, dtype: object
1.1666666666666667
Sociedad - local
2551    3
2565    0
2580    0
2600    1
2622    0
2641    3
2662    0
2681    1
2706    3
2726    0
Name: FTR, dtype: object
1.1
13
14.8
Elche - visitante
2556    1
2574    0
2598    1
2618    0
2631    3
2655    0
2663    0
2688    3
2709    0
2711    0
Name: FTR, dtype: object
0.8
Granada - local
2566    0
2589    0
2615    0
2634    1
2658    3
2670    0
2697    0
2717    3
2730    0
2756    3
Name: FTR, dtype: object
1.0
4
9.7
Almeria - visitante
2562    0
2581    0
2601    3
2622    3
2649    0
2670    3
2694    3
2716    0
2733    0
2765    0
Name: FTR, dtype: object
1.2
Villarreal - local
2561    0
2581    3
2604    0
2621    3
2640    0
2678    3
2692    0
2715    3
2732    1
2760    1
Name: FTR, dtype: object
1.4
16
13.5
Getafe - visitante
2569    3
2580    3
2611    0
2633    0
2654    0
2660    3
2689    1
2708    1
2724    0
2734    3
Name: FTR, dtype: object
1.4
Vallecano - local
2560    0
2594    0
2612    3
2631    0
2650    1
2660    0
2690    0
2702    3
2725    3
2744    3
Name: FTR, dtype: object
1.3
14
13.8
Celta - visitante
2567    3
2588    1
2609    3
2627    1
2645    1
2666    0
2687    3
2705    3
2725    0
2746    0
Name: FTR, dtype: object
1.5
Levante - local
2562    3
2585    0
2605    0
2623    0
2652    0
2679    3
2684    3
2708    1
2720    0
2741    0
Name: FTR, dtype: object
1.0
8
9.7
Valencia - visitante
2561    3
2582    0
2600    1
2620    3
2656    1
2679    0
2683    1
2707    1
2721    1
2743    1
Name: FTR, dtype: object
1.2
Elche - local
2563    3
2583    0
2609    0
2629    0
2643    1
2673    1
2700    1
2724    3
2749    1
2763    1
Name: FTR, dtype: object
1.1
5
13.5
Cordoba - visitante
2568    0
2599    1
2610    0
2639    1
2651    0
Name: FTR, dtype: object
0.4
La Coruna - local
2569    0
2582    3
2601    0
2625    0
2642    1
3046    0
3063    3
3087    1
3103    1
3127    3
Name: FTR, dtype: object
1.2
14
12.1
Sociedad - visitante
2577    1
2592    0
2613    0
2637    1
2653    0
2677    1
2699    3
2718    1
2735    1
2750    0
Name: FTR, dtype: object
0.8
Eibar - local
2576    1
2597    1
2616    1
2630    0
2653    3
Name: FTR, dtype: object
1.2
6
10.8
Real Madrid - visitante
2566    3
2585    3
2604    3
2625    3
2641    0
2674    0
2680    1
2726    3
2745    0
2766    3
Name: FTR, dtype: object
1.9
Barcelona - local
2567    0
2587    3
2606    3
2638    3
2655    3
2668    1
2689    1
2704    3
2727    3
2746    3
Name: FTR, dtype: object
2.3
25
16.7
Sevilla - visitante
2564    0
2583    3
2607    0
2624    3
2644    3
2671    0
2695    0
2714    3
2738    0
2753    3
Name: FTR, dtype: object
1.5
Ath Madrid - local
2568    3
2584    3
2607    3
2627    1
2646    3
2676    1
2709    3
2728    3
2747    3
2768    3
Name: FTR, dtype: object
2.6
20
14.1
Malaga - visitante
2565    3
2586    3
2602    0
2626    1
2648    0
2676    1
2698    0
2710    0
2731    3
2759    3
Name: FTR, dtype: object
1.4
Ath Bilbao - local
2564    3
2588    1
2608    1
2628    0
2647    3
2677    1
2695    3
2710    3
2739    0
2758    3
Name: FTR, dtype: object
1.8
14
12.1
Espanol - visitante
2563    0
2584    0
2603    1
2632    0
2659    1
2667    0
2686    0
2706    0
2722    0
2748    3
Name: FTR, dtype: object
0.5
Valencia - local
2574    3
2595    3
2610    3
2632    3
2648    3
2666    3
2693    0
2711    3
2734    0
2751    3
Name: FTR, dtype: object
2.4
22
12.6
Ath Bilbao - visitante
2578    3
2591    0
2612    0
2638    0
2657    0
2665    1
2690    3
2704    0
2720    3
2749    1
Name: FTR, dtype: object
1.1
Sociedad - local
2565    0
2580    0
2600    1
2622    0
2641    3
2662    0
2681    1
2706    3
2726    0
2740    3
Name: FTR, dtype: object
1.1
12
15.1
Ath Madrid - visitante
2572    3
2595    0
2617    3
2635    3
2650    1
2668    1
2684    0
2693    3
2712    3
2739    3
Name: FTR, dtype: object
2.0
Sevilla - local
2570    3
2590    3
2613    3
2633    3
2656    1
2663    3
2682    1
2703    3
2722    3
2745    3
Name: FTR, dtype: object
2.6
23
12.6
Levante - visitante
2579    0
2597    1
2615    3
2636    1
2647    0
2669    0
2700    1
2715    0
2730    3
2757    1
Name: FTR, dtype: object
1.0
Espanol - local
2573    1
2592    3
2611    3
2626    1
2644    0
2672    1
2694    0
2713    1
2737    0
2757    1
Name: FTR, dtype: object
1.1
11
9.5
Villarreal - visitante
2570    0
2593    3
2616    1
2634    1
2652    3
2662    3
2682    1
2701    0
2728    0
2742    3
Name: FTR, dtype: object
1.5
Real Madrid - local
2575    3
2591    3
2618    3
2635    0
2651    3
2667    3
2683    1
2696    3
2716    3
2736    3
Name: FTR, dtype: object
2.5
34
20.9
Vallecano - visitante
2571    0
2589    3
2605    3
2621    0
2642    1
2678    0
2697    3
2713    1
2736    0
2755    1
Name: FTR, dtype: object
1.2
Malaga - local
2571    3
2596    3
2614    1
2636    1
2657    3
2669    3
2688    0
2701    3
2723    3
2748    0
Name: FTR, dtype: object
2.0
15
14.4
Eibar - visitante
2560    3
2587    0
2608    1
2629    3
2646    0
Name: FTR, dtype: object
1.4
Getafe - local
2572    0
2599    1
2602    3
2620    0
2649    3
2671    3
2698    3
2712    0
2742    0
2769    1
Name: FTR, dtype: object
1.4
8
11.6
Elche - visitante
2574    0
2598    1
2618    0
2631    3
2655    0
2663    0
2688    3
2709    0
2711    0
2732    1
Name: FTR, dtype: object
0.8
Celta - local
2579    3
2593    0
2619    3
2637    1
2654    3
2674    3
2691    3
2718    1
2738    3
2759    0
Name: FTR, dtype: object
2.0
20
13.9
Granada - visitante
2576    1
2596    0
2606    0
2628    3
2643    1
2661    3
2681    1
2703    0
2723    0
2747    0
Name: FTR, dtype: object
0.9
Almeria - local
2578    0
2598    1
2617    0
2639    1
2659    1
2665    1
2685    3
2705    0
2729    0
2743    1
Name: FTR, dtype: object
0.8
12
12.9
Barcelona - visitante
2575    0
2594    3
2614    1
2623    3
2640    3
2673    1
2692    3
2717    0
2737    3
2752    3
Name: FTR, dtype: object
2.0
Cordoba - local
2577    1
2586    0
2603    1
2624    0
2645    1
Name: FTR, dtype: object
0.6
4
8.0
La Coruna - visitante
2573    1
2590    0
2619    0
2630    3
2658    0
3054    0
3073    0
3090    1
3117    3
3133    3
Name: FTR, dtype: object
1.1
Vallecano - local
2594    0
2612    3
2631    0
2650    1
2660    0
2690    0
2702    3
2725    3
2744    3
2765    3
Name: FTR, dtype: object
1.6
15
13.6
Eibar - visitante
2587    0
2608    1
2629    3
2646    0
Name: FTR, dtype: object
1.0
Villarreal - local
2581    3
2604    0
2621    3
2640    0
2678    3
2692    0
2715    3
2732    1
2760    1
2780    1
Name: FTR, dtype: object
1.5
16
12.5
Valencia - visitante
2582    0
2600    1
2620    3
2656    1
2679    0
2683    1
2707    1
2721    1
2743    1
2761    0
Name: FTR, dtype: object
0.9
Levante - local
2585    0
2605    0
2623    0
2652    0
2679    3
2684    3
2708    1
2720    0
2741    0
2767    0
Name: FTR, dtype: object
0.7
6
10.4
Almeria - visitante
2581    0
2601    3
2622    3
2649    0
2670    3
2694    3
2716    0
2733    0
2765    0
2783    0
Name: FTR, dtype: object
1.2
Elche - local
2583    0
2609    0
2629    0
2643    1
2673    1
2700    1
2724    3
2749    1
2763    1
2788    3
Name: FTR, dtype: object
1.1
4
13.3
Espanol - visitante
2584    0
2603    1
2632    0
2659    1
2667    0
2686    0
2706    0
2722    0
2748    3
2768    0
Name: FTR, dtype: object
0.5
Ath Bilbao - local
2588    1
2608    1
2628    0
2647    3
2677    1
2695    3
2710    3
2739    0
2758    3
2789    3
Name: FTR, dtype: object
1.8
17
13.9
Sevilla - visitante
2583    3
2607    0
2624    3
2644    3
2671    0
2695    0
2714    3
2738    0
2753    3
2775    3
Name: FTR, dtype: object
1.8
Sociedad - local
2580    0
2600    1
2622    0
2641    3
2662    0
2681    1
2706    3
2726    0
2740    3
2761    3
Name: FTR, dtype: object
1.4
13
15.5
Malaga - visitante
2586    3
2602    0
2626    1
2648    0
2676    1
2698    0
2710    0
2731    3
2759    3
2771    3
Name: FTR, dtype: object
1.4
Granada - local
2589    0
2615    0
2634    1
2658    3
2670    0
2697    0
2717    3
2730    0
2756    3
2777    3
Name: FTR, dtype: object
1.3
6
9.9
Real Madrid - visitante
2585    3
2604    3
2625    3
2641    0
2674    0
2680    1
2726    3
2745    0
2766    3
2784    1

Name: FTR, dtype: object
1.7
Barcelona - local
2587    3
2606    3
2638    3
2655    3
2668    1
2689    1
2704    3
2727    3
2746    3
2764    3
Name: FTR, dtype: object
2.6
32
16.8
Celta - visitante
2588    1
2609    3
2627    1
2645    1
2666    0
2687    3
2705    3
2725    0
2746    0
2767    3
Name: FTR, dtype: object
1.5
Ath Madrid - local
2584    3
2607    3
2627    1
2646    3
2676    1
2709    3
2728    3
2747    3
2768    3
2784    1
Name: FTR, dtype: object
2.4
18
13.6
Cordoba - visitante
2599    1
2610    0
2639    1
2651    0
Name: FTR, dtype: object
0.5
La Coruna - local
2582    3
2601    0
2625    0
2642    1
3046    0
3063    3
3087    1
3103    1
3127    3
3149    3
Name: FTR, dtype: object
1.5
16
12.9
Getafe - visitante
2580    3
2611    0
2633    0
2654    0
2660    3
2689    1
2708    1
2724    0
2734    3
2758    0
Name: FTR, dtype: object
1.1
Sevilla - local
2590    3
2613    3
2633    3
2656    1
2663    3
2682    1
2703    3
2722    3
2745    3
2762    3
Name: FTR, dtype: object
2.6
25
13.2
Villarreal - visitante
2593    3
2616    1
2634    1
2652    3
2662    3
2682    1
2701    0
2728    0
2742    3
2751    0
Name: FTR, dtype: object
1.5
Malaga - local
2596    3
2614    1
2636    1
2657    3
2669    3
2688    0
2701    3
2723    3
2748    0
2766    0
Name: FTR, dtype: object
1.7
11
13.8
Vallecano - visitante
2589    3
2605    3
2621    0
2642    1
2678    0
2697    3
2713    1
2736    0
2755    1
2770    3
Name: FTR, dtype: object
1.5
Getafe - local
2599    1
2602    3
2620    0
2649    3
2671    3
2698    3
2712    0
2742    0
2769    1
2787    1
Name: FTR, dtype: object
1.5
8
12.0
Ath Madrid - visitante
2595    0
2617    3
2635    3
2650    1
2668    1
2684    0
2693    3
2712    3
2739    3
2754    3
Name: FTR, dtype: object
2.0
Espanol - local
2592    3
2611    3
2626    1
2644    0
2672    1
2694    0
2713    1
2737    0
2757    1
2774    3
Name: FTR, dtype: object
1.3
14
9.1
La Coruna - visitante
2590    0
2619    0
2630    3
2658    0
3054    0
3073    0
3090    1
3117    3
3133    3
3158    0
Name: FTR, dtype: object
1.0
Valencia - local
2595    3
2610    3
2632    3
2648    3
2666    3
2693    0
2711    3
2734    0
2751    3
2772    1
Name: FTR, dtype: object
2.2
20
12.7
Elche - visitante
2598    1
2618    0
2631    3
2655    0
2663    0
2688    3
2709    0
2711    0
2732    1
2756    0
Name: FTR, dtype: object
0.8
Real Madrid - local
2591    3
2618    3
2635    0
2651    3
2667    3
2683    1
2696    3
2716    3
2736    3
2752    0
Name: FTR, dtype: object
2.2
34
20.4
Barcelona - visitante
2594    3
2614    1
2623    3
2640    3
2673    1
2692    3
2717    0
2737    3
2752    3
2776    0
Name: FTR, dtype: object
2.0
Eibar - local
2597    1
2616    1
2630    0
2653    3
Name: FTR, dtype: object
1.25
5
11.75
Granada - visitante
2596    0
2606    0
2628    3
2643    1
2661    3
2681    1
2703    0
2723    0
2747    0
2769    1
Name: FTR, dtype: object
0.9
Cordoba - local
2586    0
2603    1
2624    0
2645    1
Name: FTR, dtype: object
0.5
3
8.25
Sociedad - visitante
2592    0
2613    0
2637    1
2653    0
2677    1
2699    3
2718    1
2735    1
2750    0
2782    0
Name: FTR, dtype: object
0.7
Almeria - local
2598    1
2617    0
2639    1
2659    1
2665    1
2685    3
2705    0
2729    0
2743    1
2750    3
Name: FTR, dtype: object
1.1
16
13.6
Ath Bilbao - visitante
2591    0
2612    0
2638    0
2657    0
2665    1
2690    3
2704    0
2720    3
2749    1
2760    1
Name: FTR, dtype: object
0.9
Celta - local
2593    0
2619    3
2637    1
2654    3
2674    3
2691    3
2718    1
2738    3
2759    0
2778    0
Name: FTR, dtype: object
1.7
17
13.5
Levante - visitante
2597    1
2615    3
2636    1
2647    0
2669    0
2700    1
2715    0
2730    3
2757    1
2773    0
Name: FTR, dtype: object
1.0
Sociedad - local
2600    1
2622    0
2641    3
2662    0
2681    1
2706    3
2726    0
2740    3
2761    3
2770    0
Name: FTR, dtype: object
1.4
14
15.7
Getafe - visitante
2611    0
2633    0
2654    0
2660    3
2689    1
2708    1
2724    0
2734    3
2758    0
2779    0
Name: FTR, dtype: object
0.8
Villarreal - local
2604    0
2621    3
2640    0
2678    3
2692    0
2715    3
2732    1
2760    1
2780    1
2805    0
Name: FTR, dtype: object
1.2
14
12.7
Almeria - visitante
2601    3
2622    3
2649    0
2670    3
2694    3
2716    0
2733    0
2765    0
2783    0
2806    0
Name: FTR, dtype: object
1.2
La Coruna - local
2601    0
2625    0
2642    1
3046    0
3063    3
3087    1
3103    1
3127    3
3149    3
3168    1
Name: FTR, dtype: object
1.3
13
13.1
Valencia - visitante
2600    1
2620    3
2656    1
2679    0
2683    1
2707    1
2721    1
2743    1
2761    0
2781    0
Name: FTR, dtype: object
0.9
Elche - local
2609    0
2629    0
2643    1
2673    1
2700    1
2724    3
2749    1
2763    1
2788    3
2809    1
Name: FTR, dtype: object
1.2
4
13.2
Sevilla - visitante
2607    0
2624    3
2644    3
2671    0
2695    0
2714    3
2738    0
2753    3
2775    3
2791    3
Name: FTR, dtype: object
1.8
Ath Madrid - local
2607    3
2627    1
2646    3
2676    1
2709    3
2728    3
2747    3
2768    3
2784    1
2808    3
Name: FTR, dtype: object
2.4
19
12.9
Espanol - visitante
2603    1
2632    0
2659    1
2667    0
2686    0
2706    0
2722    0
2748    3
2768    0
2787    1
Name: FTR, dtype: object
0.6
Levante - local
2605    0
2623    0
2652    0
2679    3
2684    3
2708    1
2720    0
2741    0
2767    0
2786    3
Name: FTR, dtype: object
1.0
8
10.0
Real Madrid - visitante
2604    3
2625    3
2641    0
2674    0
2680    1
2726    3
2745    0
2766    3
2784    1
2803    3
Name: FTR, dtype: object
1.7
Cordoba - local
2603    1
2624    0
2645    1
Name: FTR, dtype: object
0.6666666666666666
2
8.333333333333334
Malaga - visitante
2602    0
2626    1
2648    0
2676    1
2698    0
2710    0
2731    3
2759    3
2771    3
2798    1
Name: FTR, dtype: object
1.2
Barcelona - local
2606    3
2638    3
2655    3
2668    1
2689    1
2704    3
2727    3
2746    3
2764    3
2783    3
Name: FTR, dtype: object
2.6
33
17.0
Eibar - visitante
2608    1
2629    3
2646    0
Name: FTR, dtype: object
1.3333333333333333
Ath Bilbao - local
2608    1
2628    0
2647    3
2677    1
2695    3
2710    3
2739    0
2758    3
2789    3
2804    0
Name: FTR, dtype: object
1.7
17
13.6
Celta - visitante
2609    3
2627    1
2645    1
2666    0
2687    3
2705    3
2725    0
2746    0
2767    3
2788    0
Name: FTR, dtype: object
1.4
Granada - local
2615    0
2634    1
2658    3
2670    0
2697    0
2717    3
2730    0
2756    3
2777    3
2802    3
Name: FTR, dtype: object
1.6
7
10.3
Vallecano - visitante
2605    3
2621    0
2642    1
2678    0
2697    3
2713    1
2736    0
2755    1
2770    3
2807    0
Name: FTR, dtype: object
1.2
Sevilla - local
2613    3
2633    3
2656    1
2663    3
2682    1
2703    3
2722    3
2745    3
2762    3
2782    3
Name: FTR, dtype: object
2.6
22
12.6
La Coruna - visitante
2619    0
2630    3
2658    0
3054    0
3073    0
3090    1
3117    3
3133    3
3158    0
3189    0
Name: FTR, dtype: object
1.0
Real Madrid - local
2618    3
2635    0
2651    3
2667    3
2683    1
2696    3
2716    3
2736    3
2752    0
2773    3
Name: FTR, dtype: object
2.2
32
21.0
Ath Bilbao - visitante
2612    0
2638    0
2657    0
2665    1
2690    3
2704    0
2720    3
2749    1
2760    1
2772    1
Name: FTR, dtype: object
1.0
Espanol - local
2611    3
2626    1
2644    0
2672    1
2694    0
2713    1
2737    0
2757    1
2774    3
2790    0
Name: FTR, dtype: object
1.0
13
9.4
Sociedad - visitante
2613    0
2637    1
2653    0
2677    1
2699    3
2718    1
2735    1
2750    0
2782    0
2800    3
Name: FTR, dtype: object
1.0
Celta - local
2619    3
2637    1
2654    3
2674    3
2691    3
2718    1
2738    3
2759    0
2778    0
2797    1
Name: FTR, dtype: object
1.8
17
13.9
Villarreal - visitante
2616    1
2634    1
2652    3
2662    3
2682    1
2701    0
2728    0
2742    3
2751    0
2777    0
Name: FTR, dtype: object
1.2
Vallecano - local
2612    3
2631    0
2650    1
2660    0
2690    0
2702    3
2725    3
2744    3
2765    3
2781    3
Name: FTR, dtype: object
1.9
16
13.9
Barcelona - visitante
2614    1
2623    3
2640    3
2673    1
2692    3
2717    0
2737    3
2752    3
2776    0
2795    0
Name: FTR, dtype: object
1.7
Valencia - local
2610    3
2632    3
2648    3
2666    3
2693    0
2711    3
2734    0
2751    3
2772    1
2792    3
Name: FTR, dtype: object
2.2
19
13.8
Ath Madrid - visitante
2617    3
2635    3
2650    1
2668    1
2684    0
2693    3
2712    3
2739    3
2754    3
2778    3
Name: FTR, dtype: object
2.3
Malaga - local
2614    1
2636    1
2657    3
2669    3
2688    0
2701    3
2723    3
2748    0
2766    0
2785    1
Name: FTR, dtype: object
1.5
10
13.8
Granada - visitante
2606    0
2628    3
2643    1
2661    3
2681    1
2703    0
2723    0
2747    0
2769    1
2789    0
Name: FTR, dtype: object
0.9
Eibar - local
2616    1
2630    0
2653    3
Name: FTR, dtype: object
1.3333333333333333
2
11.0
Levante - visitante
2615    3
2636    1
2647    0
2669    0
2700    1
2715    0
2730    3
2757    1
2773    0
2799    1
Name: FTR, dtype: object
1.0
Almeria - local
2617    0
2639    1
2659    1
2665    1
2685    3
2705    0
2729    0
2743    1
2750    3
2775    0
Name: FTR, dtype: object
1.0
15
12.8
Elche - visitante
2618    0
2631    3
2655    0
2663    0
2688    3
2709    0
2711    0
2732    1
2756    0
2774    0
Name: FTR, dtype: object
0.7
Getafe - local
2602    3
2620    0
2649    3
2671    3
2698    3
2712    0
2742    0
2769    1
2787    1
2803    0
Name: FTR, dtype: object
1.4
7
11.1
Cordoba - visitante
2610    0
2639    1
2651    0
Name: FTR, dtype: object
0.3333333333333333
Sociedad - local
2622    0
2641    3
2662    0
2681    1
2706    3
2726    0
2740    3
2761    3
2770    0
2795    3
Name: FTR, dtype: object
1.6
16
15.4
Valencia - visitante
2620    3
2656    1
2679    0
2683    1
2707    1
2721    1
2743    1
2761    0
2781    0
2801    1
Name: FTR, dtype: object
0.9
La Coruna - local
2625    0
2642    1
3046    0
3063    3
3087    1
3103    1
3127    3
3149    3
3168    1
3177    0
Name: FTR, dtype: object
1.3
14
13.8
Almeria - visitante
2622    3
2649    0
2670    3
2694    3
2716    0
2733    0
2765    0
2783    0
2806    0
2821    0
Name: FTR, dtype: object
0.9

Getafe - local
2620    0
2649    3
2671    3
2698    3
2712    0
2742    0
2769    1
2787    1
2803    0
2827    1
Name: FTR, dtype: object
1.2
6
10.9
Malaga - visitante
2626    1
2648    0
2676    1
2698    0
2710    0
2731    3
2759    3
2771    3
2798    1
2815    0
Name: FTR, dtype: object
1.2
Cordoba - local
2624    0
2645    1
Name: FTR, dtype: object
0.5
2
7.5
Espanol - visitante
2632    0
2659    1
2667    0
2686    0
2706    0
2722    0
2748    3
2768    0
2787    1
2804    3
Name: FTR, dtype: object
0.8
Villarreal - local
2621    3
2640    0
2678    3
2692    0
2715    3
2732    1
2760    1
2780    1
2805    0
2820    3
Name: FTR, dtype: object
1.5
17
12.1
Real Madrid - visitante
2625    3
2641    0
2674    0
2680    1
2726    3
2745    0
2766    3
2784    1
2803    3
2824    1
Name: FTR, dtype: object
1.5
Levante - local
2623    0
2652    0
2679    3
2684    3
2708    1
2720    0
2741    0
2767    0
2786    3
2806    3
Name: FTR, dtype: object
1.3
9
10.6
Vallecano - visitante
2621    0
2642    1
2678    0
2697    3
2713    1
2736    0
2755    1
2770    3
2807    0
2826    1
Name: FTR, dtype: object
1.0
Barcelona - local
2638    3
2655    3
2668    1
2689    1
2704    3
2727    3
2746    3
2764    3
2783    3
2807    3
Name: FTR, dtype: object
2.6
33
17.2
Granada - visitante
2628    3
2643    1
2661    3
2681    1
2703    0
2723    0
2747    0
2769    1
2789    0
2792    0
Name: FTR, dtype: object
0.9
Ath Madrid - local
2627    1
2646    3
2676    1
2709    3
2728    3
2747    3
2768    3
2784    1
2808    3
2823    3
Name: FTR, dtype: object
2.4
19
13.0
Sevilla - visitante
2624    3
2644    3
2671    0
2695    0
2714    3
2738    0
2753    3
2775    3
2791    3
2825    0
Name: FTR, dtype: object
1.8
Ath Bilbao - local
2628    0
2647    3
2677    1
2695    3
2710    3
2739    0
2758    3
2789    3
2804    0
2824    1
Name: FTR, dtype: object
1.7
18
13.2
Eibar - visitante
2629    3
2646    0
Name: FTR, dtype: object
1.5
Elche - local
2629    0
2643    1
2673    1
2700    1
2724    3
2749    1
2763    1
2788    3
2809    1
2821    3
Name: FTR, dtype: object
1.5
5
13.1
Celta - visitante
2627    1
2645    1
2666    0
2687    3
2705    3
2725    0
2746    0
2767    3
2788    0
2805    3
Name: FTR, dtype: object
1.4
Valencia - local
2632    3
2648    3
2666    3
2693    0
2711    3
2734    0
2751    3
2772    1
2792    3
2816    3
Name: FTR, dtype: object
2.2
21
13.9
Cordoba - visitante
2639    1
2651    0
Name: FTR, dtype: object
0.5
Espanol - local
2626    1
2644    0
2672    1
2694    0
2713    1
2737    0
2757    1
2774    3
2790    0
2819    3
Name: FTR, dtype: object
1.0
12
9.7
Getafe - visitante
2633    0
2654    0
2660    3
2689    1
2708    1
2724    0
2734    3
2758    0
2779    0
2797    1
Name: FTR, dtype: object
0.9
Vallecano - local
2631    0
2650    1
2660    0
2690    0
2702    3
2725    3
2744    3
2765    3
2781    3
2791    0
Name: FTR, dtype: object
1.6
14
13.3
Ath Bilbao - visitante
2638    0
2657    0
2665    1
2690    3
2704    0
2720    3
2749    1
2760    1
2772    1
2794    3
Name: FTR, dtype: object
1.3
Sevilla - local
2633    3
2656    1
2663    3
2682    1
2703    3
2722    3
2745    3
2762    3
2782    3
2801    1
Name: FTR, dtype: object
2.4
21
12.4
Sociedad - visitante
2637    1
2653    0
2677    1
2699    3
2718    1
2735    1
2750    0
2782    0
2800    3
2823    0
Name: FTR, dtype: object
1.0
Malaga - local
2636    1
2657    3
2669    3
2688    0
2701    3
2723    3
2748    0
2766    0
2785    1
2800    0
Name: FTR, dtype: object
1.4
10
14.6
Barcelona - visitante
2623    3
2640    3
2673    1
2692    3
2717    0
2737    3
2752    3
2776    0
2795    0
2813    3
Name: FTR, dtype: object
1.9
Granada - local
2634    1
2658    3
2670    0
2697    0
2717    3
2730    0
2756    3
2777    3
2802    3
2829    0
Name: FTR, dtype: object
1.6
8
11.1
Levante - visitante
2636    1
2647    0
2669    0
2700    1
2715    0
2730    3
2757    1
2773    0
2799    1
2812    1
Name: FTR, dtype: object
0.8
Eibar - local
2630    0
2653    3
Name: FTR, dtype: object
1.5
1
13.0
Villarreal - visitante
2634    1
2652    3
2662    3
2682    1
2701    0
2728    0
2742    3
2751    0
2777    0
2790    3
Name: FTR, dtype: object
1.4
Almeria - local
2639    1
2659    1
2665    1
2685    3
2705    0
2729    0
2743    1
2750    3
2775    0
2798    1
Name: FTR, dtype: object
1.1
15
12.9
Ath Madrid - visitante
2635    3
2650    1
2668    1
2684    0
2693    3
2712    3
2739    3
2754    3
2778    3
2793    0
Name: FTR, dtype: object
2.0
Real Madrid - local
2635    0
2651    3
2667    3
2683    1
2696    3
2716    3
2736    3
2752    0
2773    3
2796    3
Name: FTR, dtype: object
2.2
30
20.3
Elche - visitante
2631    3
2655    0
2663    0
2688    3
2709    0
2711    0
2732    1
2756    0
2774    0
2796    0
Name: FTR, dtype: object
0.7
Celta - local
2637    1
2654    3
2674    3
2691    3
2718    1
2738    3
2759    0
2778    0
2797    1
2810    1
Name: FTR, dtype: object
1.6
15
14.2
La Coruna - visitante
2630    3
2658    0
3054    0
3073    0
3090    1
3117    3
3133    3
3158    0
3189    0
3207    0
Name: FTR, dtype: object
1.0
Getafe - local
2649    3
2671    3
2698    3
2712    0
2742    0
2769    1
2787    1
2803    0
2827    1
2843    1
Name: FTR, dtype: object
1.3
8
11.3
Valencia - visitante
2656    1
2679    0
2683    1
2707    1
2721    1
2743    1
2761    0
2781    0
2801    1
2828    3
Name: FTR, dtype: object
0.9
Villarreal - local
2640    0
2678    3
2692    0
2715    3
2732    1
2760    1
2780    1
2805    0
2820    3
2841    3
Name: FTR, dtype: object
1.5
15
11.4
Vallecano - visitante
2642    1
2678    0
2697    3
2713    1
2736    0
2755    1
2770    3
2807    0
2826    1
2847    0
Name: FTR, dtype: object
1.0
Sociedad - local
2641    3
2662    0
2681    1
2706    3
2726    0
2740    3
2761    3
2770    0
2795    3
2812    1
Name: FTR, dtype: object
1.7
15
15.0
Almeria - visitante
2649    0
2670    3
2694    3
2716    0
2733    0
2765    0
2783    0
2806    0
2821    0
2841    0
Name: FTR, dtype: object
0.6
Levante - local
2652    0
2679    3
2684    3
2708    1
2720    0
2741    0
2767    0
2786    3
2806    3
2826    1
Name: FTR, dtype: object
1.4
9
10.8
Barcelona - visitante
2640    3
2673    1
2692    3
2717    0
2737    3
2752    3
2776    0
2795    0
2813    3
2842    1
Name: FTR, dtype: object
1.7
Cordoba - local
2645    1
Name: FTR, dtype: object
1.0
1
6.0
Sevilla - visitante
2644    3
2671    0
2695    0
2714    3
2738    0
2753    3
2775    3
2791    3
2825    0
2844    1
Name: FTR, dtype: object
1.6
La Coruna - local
2642    1
3046    0
3063    3
3087    1
3103    1
3127    3
3149    3
3168    1
3177    0
3198    0
Name: FTR, dtype: object
1.3
12
14.0
Real Madrid - visitante
2641    0
2674    0
2680    1
2726    3
2745    0
2766    3
2784    1
2803    3
2824    1
2848    3
Name: FTR, dtype: object
1.5
Espanol - local
2644    0
2672    1
2694    0
2713    1
2737    0
2757    1
2774    3
2790    0
2819    3
2846    3
Name: FTR, dtype: object
1.2
11
9.2
Malaga - visitante
2648    0
2676    1
2698    0
2710    0
2731    3
2759    3
2771    3
2798    1
2815    0
2833    0
Name: FTR, dtype: object
1.1
Ath Madrid - local
2646    3
2676    1
2709    3
2728    3
2747    3
2768    3
2784    1
2808    3
2823    3
2844    1
Name: FTR, dtype: object
2.4
18
12.8
Celta - visitante
2645    1
2666    0
2687    3
2705    3
2725    0
2746    0
2767    3
2788    0
2805    3
2829    3
Name: FTR, dtype: object
1.6
Ath Bilbao - local
2647    3
2677    1
2695    3
2710    3
2739    0
2758    3
2789    3
2804    0
2824    1
2840    3
Name: FTR, dtype: object
2.0
22
14.2
Granada - visitante
2643    1
2661    3
2681    1
2703    0
2723    0
2747    0
2769    1
2789    0
2792    0
2819    0
Name: FTR, dtype: object
0.6
Elche - local
2643    1
2673    1
2700    1
2724    3
2749    1
2763    1
2788    3
2809    1
2821    3
2847    3
Name: FTR, dtype: object
1.8
7
13.1
Eibar - visitante
2646    0
Name: FTR, dtype: object
0.0
Eibar - local
2653    3
Name: FTR, dtype: object
3.0
1
12.0
La Coruna - visitante
2658    0
3054    0
3073    0
3090    1
3117    3
3133    3
3158    0
3189    0
3207    0
3223    0
Name: FTR, dtype: object
0.7
Vallecano - local
2650    1
2660    0
2690    0
2702    3
2725    3
2744    3
2765    3
2781    3
2791    0
2815    3
Name: FTR, dtype: object
1.9
16
13.0
Elche - visitante
2655    0
2663    0
2688    3
2709    0
2711    0
2732    1
2756    0
2774    0
2796    0
2811    1
Name: FTR, dtype: object
0.5
Valencia - local
2648    3
2666    3
2693    0
2711    3
2734    0
2751    3
2772    1
2792    3
2816    3
2836    1
Name: FTR, dtype: object
2.0
20
14.3
Espanol - visitante
2659    1
2667    0
2686    0
2706    0
2722    0
2748    3
2768    0
2787    1
2804    3
2822    0
Name: FTR, dtype: object
0.8
Sevilla - local
2656    1
2663    3
2682    1
2703    3
2722    3
2745    3
2762    3
2782    3
2801    1
2813    0
Name: FTR, dtype: object
2.1
20
12.7
Getafe - visitante
2654    0
2660    3
2689    1
2708    1
2724    0
2734    3
2758    0
2779    0
2797    1
2814    0
Name: FTR, dtype: object
0.9
Granada - local
2658    3
2670    0
2697    0
2717    3
2730    0
2756    3
2777    3
2802    3
2829    0
2845    1
Name: FTR, dtype: object
1.6
8
11.9
Villarreal - visitante
2652    3
2662    3
2682    1
2701    0
2728    0
2742    3
2751    0
2777    0
2790    3
2817    0

Name: FTR, dtype: object
1.3
Real Madrid - local
2651    3
2667    3
2683    1
2696    3
2716    3
2736    3
2752    0
2773    3
2796    3
2817    3
Name: FTR, dtype: object
2.5
33
19.5
Ath Madrid - visitante
2650    1
2668    1
2684    0
2693    3
2712    3
2739    3
2754    3
2778    3
2793    0
2818    0
Name: FTR, dtype: object
1.7
Malaga - local
2657    3
2669    3
2688    0
2701    3
2723    3
2748    0
2766    0
2785    1
2800    0
2825    3
Name: FTR, dtype: object
1.6
13
14.2
Levante - visitante
2647    0
2669    0
2700    1
2715    0
2730    3
2757    1
2773    0
2799    1
2812    1
2837    3
Name: FTR, dtype: object
1.0
Celta - local
2654    3
2674    3
2691    3
2718    1
2738    3
2759    0
2778    0
2797    1
2810    1
2839    3
Name: FTR, dtype: object
1.8
17
13.9
Sociedad - visitante
2653    0
2677    1
2699    3
2718    1
2735    1
2750    0
2782    0
2800    3
2823    0
2843    1
Name: FTR, dtype: object
1.0
Barcelona - local
2655    3
2668    1
2689    1
2704    3
2727    3
2746    3
2764    3
2783    3
2807    3
2828    0
Name: FTR, dtype: object
2.3
33
17.7
Ath Bilbao - visitante
2657    0
2665    1
2690    3
2704    0
2720    3
2749    1
2760    1
2772    1
2794    3
2810    1
Name: FTR, dtype: object
1.4
Almeria - local
2659    1
2665    1
2685    3
2705    0
2729    0
2743    1
2750    3
2775    0
2798    1
2818    3
Name: FTR, dtype: object
1.3
16
12.4
Cordoba - visitante
2651    0
Name: FTR, dtype: object
0.0
Villarreal - local
2678    3
2692    0
2715    3
2732    1
2760    1
2780    1
2805    0
2820    3
2841    3
2850    3
Name: FTR, dtype: object
1.8
20
12.7
Barcelona - visitante
2673    1
2692    3
2717    0
2737    3
2752    3
2776    0
2795    0
2813    3
2842    1
2857    1
Name: FTR, dtype: object
1.5
Sociedad - local
2662    0
2681    1
2706    3
2726    0
2740    3
2761    3
2770    0
2795    3
2812    1
2830    3
Name: FTR, dtype: object
1.7
15
14.4
Real Madrid - visitante
2674    0
2680    1
2726    3
2745    0
2766    3
2784    1
2803    3
2824    1
2848    3
2853    3
Name: FTR, dtype: object
1.8
La Coruna - local
3046    0
3063    3
3087    1
3103    1
3127    3
3149    3
3168    1
3177    0
3198    0
3218    0
Name: FTR, dtype: object
1.2
12
14.1
Vallecano - visitante
2678    0
2697    3
2713    1
2736    0
2755    1
2770    3
2807    0
2826    1
2847    0
2852    3
Name: FTR, dtype: object
1.2
Elche - local
2673    1
2700    1
2724    3
2749    1
2763    1
2788    3
2809    1
2821    3
2847    3
2855    1
Name: FTR, dtype: object
1.8
7
12.6
Granada - visitante
2661    3
2681    1
2703    0
2723    0
2747    0
2769    1
2789    0
2792    0
2819    0
2838    0
Name: FTR, dtype: object
0.5
Espanol - local
2672    1
2694    0
2713    1
2737    0
2757    1
2774    3
2790    0
2819    3
2846    3
2853    0
Name: FTR, dtype: object
1.2
10
9.9
Sevilla - visitante
2671    0
2695    0
2714    3
2738    0
2753    3
2775    3
2791    3
2825    0
2844    1
2855    1
Name: FTR, dtype: object
1.4
Cordoba - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Celta - visitante
2666    0
2687    3
2705    3
2725    0
2746    0
2767    3
2788    0
2805    3
2829    3
2846    0
Name: FTR, dtype: object
1.5
Ath Madrid - local
2676    1
2709    3
2728    3
2747    3
2768    3
2784    1
2808    3
2823    3
2844    1
2857    1
Name: FTR, dtype: object
2.2
16
11.9
Eibar - visitante
Series([], Name: FTR, dtype: object)
0.0
Ath Bilbao - local
2677    1
2695    3
2710    3
2739    0
2758    3
2789    3
2804    0
2824    1
2840    3
2858    3
Name: FTR, dtype: object
2.0
25
14.7
Levante - visitante
2669    0
2700    1
2715    0
2730    3
2757    1
2773    0
2799    1
2812    1
2837    3
2867    0
Name: FTR, dtype: object
1.0
Valencia - local
2666    3
2693    0
2711    3
2734    0
2751    3
2772    1
2792    3
2816    3
2836    1
2867    3
Name: FTR, dtype: object
2.0
19
14.6
Malaga - visitante
2676    1
2698    0
2710    0
2731    3
2759    3
2771    3
2798    1
2815    0
2833    0
2851    0
Name: FTR, dtype: object
1.1
Getafe - local
2671    3
2698    3
2712    0
2742    0
2769    1
2787    1
2803    0
2827    1
2843    1
2852    0
Name: FTR, dtype: object
1.0
7
11.5
Almeria - visitante
2670    3
2694    3
2716    0
2733    0
2765    0
2783    0
2806    0
2821    0
2841    0
2858    0
Name: FTR, dtype: object
0.6
Vallecano - local
2660    0
2690    0
2702    3
2725    3
2744    3
2765    3
2781    3
2791    0
2815    3
2831    0
Name: FTR, dtype: object
1.8
18
13.5
Ath Madrid - visitante
2668    1
2684    0
2693    3
2712    3
2739    3
2754    3
2778    3
2793    0
2818    0
2831    3
Name: FTR, dtype: object
1.9
Real Madrid - local
2667    3
2683    1
2696    3
2716    3
2736    3
2752    0
2773    3
2796    3
2817    3
2838    3
Name: FTR, dtype: object
2.5
33
20.4
Cordoba - visitante
Series([], Name: FTR, dtype: object)
0.0
Levante - local
2679    3
2684    3
2708    1
2720    0
2741    0
2767    0
2786    3
2806    3
2826    1
2842    1
Name: FTR, dtype: object
1.5
10
10.6
Villarreal - visitante
2662    3
2682    1
2701    0
2728    0
2742    3
2751    0
2777    0
2790    3
2817    0
2835    0
Name: FTR, dtype: object
1.0
Eibar - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Sociedad - visitante
2677    1
2699    3
2718    1
2735    1
2750    0
2782    0
2800    3
2823    0
2843    1
2850    0
Name: FTR, dtype: object
1.0
Celta - local
2674    3
2691    3
2718    1
2738    3
2759    0
2778    0
2797    1
2810    1
2839    3
2856    3
Name: FTR, dtype: object
1.8
16
14.0
Getafe - visitante
2660    3
2689    1
2708    1
2724    0
2734    3
2758    0
2779    0
2797    1
2814    0
2834    0
Name: FTR, dtype: object
0.9
Barcelona - local
2668    1
2689    1
2704    3
2727    3
2746    3
2764    3
2783    3
2807    3
2828    0
2833    3
Name: FTR, dtype: object
2.3
33
18.8
Elche - visitante
2663    0
2688    3
2709    0
2711    0
2732    1
2756    0
2774    0
2796    0
2811    1
2830    0
Name: FTR, dtype: object
0.5
Sevilla - local
2663    3
2682    1
2703    3
2722    3
2745    3
2762    3
2782    3
2801    1
2813    0
2837    0
Name: FTR, dtype: object
2.0
21
14.5
Valencia - visitante
2679    0
2683    1
2707    1
2721    1
2743    1
2761    0
2781    0
2801    1
2828    3
2849    1
Name: FTR, dtype: object
0.9
Malaga - local
2669    3
2688    0
2701    3
2723    3
2748    0
2766    0
2785    1
2800    0
2825    3
2849    1
Name: FTR, dtype: object
1.4
12
14.7
Ath Bilbao - visitante
2665    1
2690    3
2704    0
2720    3
2749    1
2760    1
2772    1
2794    3
2810    1
2832    3
Name: FTR, dtype: object
1.7
Granada - local
2670    0
2697    0
2717    3
2730    0
2756    3
2777    3
2802    3
2829    0
2845    1
2859    3
Name: FTR, dtype: object
1.6
10
12.4
La Coruna - visitante
3054    0
3073    0
3090    1
3117    3
3133    3
3158    0
3189    0
3207    0
3223    0
3231    1
Name: FTR, dtype: object
0.8
Almeria - local
2665    1
2685    3
2705    0
2729    0
2743    1
2750    3
2775    0
2798    1
2818    3
2834    3
Name: FTR, dtype: object
1.5
16
11.2
Espanol - visitante
2667    0
2686    0
2706    0
2722    0
2748    3
2768    0
2787    1
2804    3
2822    0
2836    1
Name: FTR, dtype: object
0.8
Vallecano - local
2690    0
2702    3
2725    3
2744    3
2765    3
2781    3
2791    0
2815    3
2831    0
2860    0
Name: FTR, dtype: object
1.8
19
13.8
Getafe - visitante
2689    1
2708    1
2724    0
2734    3
2758    0
2779    0
2797    1
2814    0
2834    0
2863    0
Name: FTR, dtype: object
0.6
Valladolid - local
2680    1
2686    3
2721    1
2733    3
2755    1
2776    3
2799    1
2811    1
2835    3
2866    1
Name: FTR, dtype: object
1.8
9
10.5
Granada - visitante
2681    1
2703    0
2723    0
2747    0
2769    1
2789    0
2792    0
2819    0
2838    0
2869    0
Name: FTR, dtype: object
0.2
Sociedad - local
2681    1
2706    3
2726    0
2740    3
2761    3
2770    0
2795    3
2812    1
2830    3
2862    3
Name: FTR, dtype: object
2.0
16
13.9
Villarreal - visitante
2682    1
2701    0
2728    0
2742    3
2751    0
2777    0
2790    3
2817    0
2835    0
2860    3
Name: FTR, dtype: object
1.0
Sevilla - local
2682    1
2703    3
2722    3
2745    3
2762    3
2782    3
2801    1
2813    0
2837    0
2863    3
Name: FTR, dtype: object
2.0
21
15.0
Elche - visitante
2688    3
2709    0
2711    0
2732    1
2756    0
2774    0
2796    0
2811    1
2830    0
2865    0
Name: FTR, dtype: object
0.5
Osasuna - local
2687    0
2707    1
2719    1
2735    1
2753    0
2771    0
2793    3
2814    3
2832    0
2864    3
Name: FTR, dtype: object
1.2
10
14.5
Betis - visitante
2685    0
2702    0
2727    0
2741    3
2763    1
2780    1
2802    0
2816    0
2839    0
2866    1
Name: FTR, dtype: object
0.6
Almeria - local
2685    3
2705    0
2729    0
2743    1
2750    3
2775    0
2798    1
2818    3
2834    3
2869    3
Name: FTR, dtype: object
1.7
19
12.0
Ath Bilbao - visitante
2690    3
2704    0
2720    3
2749    1
2760    1
2772    1
2794    3
2810    1
2832    3
2862    0
Name: FTR, dtype: object
1.6
Valencia - local
2693    0
2711    3
2734    0
2751    3
2772    1
2792    3
2816    3
2836    1
2867    3
2870    0
Name: FTR, dtype: object
1.7
19
14.4
Celta - visitante
2687    3
2705    3
2725    0
2746    0
2767    3
2788    0
2805    3
2829    3
2846    0
2861    0
Name: FTR, dtype: object
1.5
Real Madrid - local
2683    1
2696    3
2716    3
2736    3
2752    0
2773    3
2796    3
2817    3
2838    3
2861    3
Name: FTR, dtype: object
2.5
33
20.5
Espanol - visitante
2686    0
2706    0
2722    0
2748    3
2768    0
2787    1
2804    3
2822    0
2836    1
2864    0
Name: FTR, dtype: object
0.8
Barcelona - local
2689    1
2704    3
2727    3
2746    3
2764    3
2783    3
2807    3
2828    0
2833    3
2865    3
Name: FTR, dtype: object
2.5
36
19.0
Ath Madrid - visitante
2684    0
2693    3
2712    3
2739    3
2754    3
2778    3
2793    0
2818    0
2831    3
2868    3
Name: FTR, dtype: object
2.1

Malaga - local
2688    0
2701    3
2723    3
2748    0
2766    0
2785    1
2800    0
2825    3
2849    1
2868    0
Name: FTR, dtype: object
1.1
11
13.4
Levante - visitante
2700    1
2715    0
2730    3
2757    1
2773    0
2799    1
2812    1
2837    3
2867    0
2878    0
Name: FTR, dtype: object
1.0
Granada - local
2697    0
2717    3
2730    0
2756    3
2777    3
2802    3
2829    0
2845    1
2859    3
2876    0
Name: FTR, dtype: object
1.6
11
13.1
Almeria - visitante
2694    3
2716    0
2733    0
2765    0
2783    0
2806    0
2821    0
2841    0
2858    0
2877    3
Name: FTR, dtype: object
0.6
Getafe - local
2698    3
2712    0
2742    0
2769    1
2787    1
2803    0
2827    1
2843    1
2852    0
2871    0
Name: FTR, dtype: object
0.7
8
11.3
Sevilla - visitante
2695    0
2714    3
2738    0
2753    3
2775    3
2791    3
2825    0
2844    1
2855    1
2875    3
Name: FTR, dtype: object
1.7
Espanol - local
2694    0
2713    1
2737    0
2757    1
2774    3
2790    0
2819    3
2846    3
2853    0
2872    3
Name: FTR, dtype: object
1.4
13
10.5
Osasuna - visitante
2696    0
2729    3
2744    0
2764    0
2786    0
2809    1
2820    0
2845    1
2854    3
2873    1
Name: FTR, dtype: object
0.9
Elche - local
2700    1
2724    3
2749    1
2763    1
2788    3
2809    1
2821    3
2847    3
2855    1
2879    0
Name: FTR, dtype: object
1.7
7
12.8
Barcelona - visitante
2692    3
2717    0
2737    3
2752    3
2776    0
2795    0
2813    3
2842    1
2857    1
2871    3
Name: FTR, dtype: object
1.7
Celta - local
2691    3
2718    1
2738    3
2759    0
2778    0
2797    1
2810    1
2839    3
2856    3
2873    1
Name: FTR, dtype: object
1.6
15
14.1
Real Madrid - visitante
2680    1
2726    3
2745    0
2766    3
2784    1
2803    3
2824    1
2848    3
2853    3
2870    3
Name: FTR, dtype: object
2.1
Betis - local
2699    0
2714    0
2731    0
2754    0
2779    3
2794    0
2822    3
2848    0
2854    0
2877    0
Name: FTR, dtype: object
0.6
6
14.2
Valladolid - visitante
2691    0
2719    1
2740    0
2762    0
2785    1
2808    0
2827    1
2840    0
2859    0
2872    0
Name: FTR, dtype: object
0.3
Ath Madrid - local
2709    3
2728    3
2747    3
2768    3
2784    1
2808    3
2823    3
2844    1
2857    1
2878    3
Name: FTR, dtype: object
2.4
18
11.8
Malaga - visitante
2698    0
2710    0
2731    3
2759    3
2771    3
2798    1
2815    0
2833    0
2851    0
2879    3
Name: FTR, dtype: object
1.3
Ath Bilbao - local
2695    3
2710    3
2739    0
2758    3
2789    3
2804    0
2824    1
2840    3
2858    3
2874    3
Name: FTR, dtype: object
2.2
26
15.9
Sociedad - visitante
2699    3
2718    1
2735    1
2750    0
2782    0
2800    3
2823    0
2843    1
2850    0
2876    3
Name: FTR, dtype: object
1.2
Villarreal - local
2692    0
2715    3
2732    1
2760    1
2780    1
2805    0
2820    3
2841    3
2850    3
2875    0
Name: FTR, dtype: object
1.5
17
11.8
Vallecano - visitante
2697    3
2713    1
2736    0
2755    1
2770    3
2807    0
2826    1
2847    0
2852    3
2874    0
Name: FTR, dtype: object
1.2
Levante - local
2684    3
2708    1
2720    0
2741    0
2767    0
2786    3
2806    3
2826    1
2842    1
2851    3
Name: FTR, dtype: object
1.5
9
10.2
Valencia - visitante
2683    1
2707    1
2721    1
2743    1
2761    0
2781    0
2801    1
2828    3
2849    1
2856    0
Name: FTR, dtype: object
0.9
Valladolid - local
2686    3
2721    1
2733    3
2755    1
2776    3
2799    1
2811    1
2835    3
2866    1
2880    3
Name: FTR, dtype: object
2.0
11
11.0
Real Madrid - visitante
2726    3
2745    0
2766    3
2784    1
2803    3
2824    1
2848    3
2853    3
2870    3
2886    1
Name: FTR, dtype: object
2.1
Sociedad - local
2706    3
2726    0
2740    3
2761    3
2770    0
2795    3
2812    1
2830    3
2862    3
2881    3
Name: FTR, dtype: object
2.2
20
13.8
Granada - visitante
2703    0
2723    0
2747    0
2769    1
2789    0
2792    0
2819    0
2838    0
2869    0
2885    3
Name: FTR, dtype: object
0.4
Sevilla - local
2703    3
2722    3
2745    3
2762    3
2782    3
2801    1
2813    0
2837    0
2863    3
2882    1
Name: FTR, dtype: object
2.0
22
15.3
Villarreal - visitante
2701    0
2728    0
2742    3
2751    0
2777    0
2790    3
2817    0
2835    0
2860    3
2888    0
Name: FTR, dtype: object
0.9
Real Madrid - local
2696    3
2716    3
2736    3
2752    0
2773    3
2796    3
2817    3
2838    3
2861    3
2894    3
Name: FTR, dtype: object
2.7
35
19.9
Valencia - visitante
2707    1
2721    1
2743    1
2761    0
2781    0
2801    1
2828    3
2849    1
2856    0
2883    0
Name: FTR, dtype: object
0.8
Levante - local
2708    1
2720    0
2741    0
2767    0
2786    3
2806    3
2826    1
2842    1
2851    3
2889    3
Name: FTR, dtype: object
1.5
9
10.4
Ath Madrid - visitante
2693    3
2712    3
2739    3
2754    3
2778    3
2793    0
2818    0
2831    3
2868    3
2896    3
Name: FTR, dtype: object
2.4
Almeria - local
2705    0
2729    0
2743    1
2750    3
2775    0
2798    1
2818    3
2834    3
2869    3
2884    1
Name: FTR, dtype: object
1.5
16
11.8
Betis - visitante
2702    0
2727    0
2741    3
2763    1
2780    1
2802    0
2816    0
2839    0
2866    1
2881    0
Name: FTR, dtype: object
0.6
Valladolid - local
2721    1
2733    3
2755    1
2776    3
2799    1
2811    1
2835    3
2866    1
2880    3
2909    0
Name: FTR, dtype: object
1.7
10
10.7
Espanol - visitante
2706    0
2722    0
2748    3
2768    0
2787    1
2804    3
2822    0
2836    1
2864    0
2884    1
Name: FTR, dtype: object
0.9
Osasuna - local
2707    1
2719    1
2735    1
2753    0
2771    0
2793    3
2814    3
2832    0
2864    3
2886    1
Name: FTR, dtype: object
1.3
12
13.3
Celta - visitante
2705    3
2725    0
2746    0
2767    3
2788    0
2805    3
2829    3
2846    0
2861    0
2880    0
Name: FTR, dtype: object
1.2
Malaga - local
2701    3
2723    3
2748    0
2766    0
2785    1
2800    0
2825    3
2849    1
2868    0
2887    3
Name: FTR, dtype: object
1.4
12
14.8
Elche - visitante
2709    0
2711    0
2732    1
2756    0
2774    0
2796    0
2811    1
2830    0
2865    0
2889    0
Name: FTR, dtype: object
0.2
Barcelona - local
2704    3
2727    3
2746    3
2764    3
2783    3
2807    3
2828    0
2833    3
2865    3
2888    3
Name: FTR, dtype: object
2.7
36
18.2
Getafe - visitante
2708    1
2724    0
2734    3
2758    0
2779    0
2797    1
2814    0
2834    0
2863    0
2887    0
Name: FTR, dtype: object
0.5
Vallecano - local
2702    3
2725    3
2744    3
2765    3
2781    3
2791    0
2815    3
2831    0
2860    0
2885    0
Name: FTR, dtype: object
1.8
19
14.4
Ath Bilbao - visitante
2704    0
2720    3
2749    1
2760    1
2772    1
2794    3
2810    1
2832    3
2862    0
2882    1
Name: FTR, dtype: object
1.4
Celta - local
2718    1
2738    3
2759    0
2778    0
2797    1
2810    1
2839    3
2856    3
2873    1
2897    3
Name: FTR, dtype: object
1.6
14
14.5
Valladolid - visitante
2719    1
2740    0
2762    0
2785    1
2808    0
2827    1
2840    0
2859    0
2872    0
2894    0
Name: FTR, dtype: object
0.3
Villarreal - local
2715    3
2732    1
2760    1
2780    1
2805    0
2820    3
2841    3
2850    3
2875    0
2898    1
Name: FTR, dtype: object
1.6
16
12.0
Barcelona - visitante
2717    0
2737    3
2752    3
2776    0
2795    0
2813    3
2842    1
2857    1
2871    3
2893    0
Name: FTR, dtype: object
1.4
Valencia - local
2711    3
2734    0
2751    3
2772    1
2792    3
2816    3
2836    1
2867    3
2870    0
2890    3
Name: FTR, dtype: object
2.0
22
15.7
Ath Madrid - visitante
2712    3
2739    3
2754    3
2778    3
2793    0
2818    0
2831    3
2868    3
2896    3
2910    1
Name: FTR, dtype: object
2.2
Espanol - local
2713    1
2737    0
2757    1
2774    3
2790    0
2819    3
2846    3
2853    0
2872    3
2895    0
Name: FTR, dtype: object
1.4
13
10.9
Almeria - visitante
2716    0
2733    0
2765    0
2783    0
2806    0
2821    0
2841    0
2858    0
2877    3
2897    0
Name: FTR, dtype: object
0.3
Ath Bilbao - local
2710    3
2739    0
2758    3
2789    3
2804    0
2824    1
2840    3
2858    3
2874    3
2893    3
Name: FTR, dtype: object
2.2
24
16.2
Sevilla - visitante
2714    3
2738    0
2753    3
2775    3
2791    3
2825    0
2844    1
2855    1
2875    3
2891    3
Name: FTR, dtype: object
2.0
Real Madrid - local
2716    3
2736    3
2752    0
2773    3
2796    3
2817    3
2838    3
2861    3
2894    3
2914    3
Name: FTR, dtype: object
2.7
36
19.6
Osasuna - visitante
2729    3
2744    0
2764    0
2786    0
2809    1
2820    0
2845    1
2854    3
2873    1
2890    0
Name: FTR, dtype: object
0.9
Granada - local
2717    3
2730    0
2756    3
2777    3
2802    3
2829    0
2845    1
2859    3
2876    0
2891    0
Name: FTR, dtype: object
1.6
12
13.6
Vallecano - visitante
2713    1
2736    0
2755    1
2770    3
2807    0
2826    1
2847    0
2852    3
2874    0
2892    1
Name: FTR, dtype: object
1.0
Getafe - local
2712    0
2742    0
2769    1
2787    1
2803    0
2827    1
2843    1
2852    0
2871    0
2899    3
Name: FTR, dtype: object
0.7
8
12.0
Malaga - visitante
2710    0
2731    3
2759    3
2771    3
2798    1
2815    0
2833    0
2851    0
2879    3
2898    1
Name: FTR, dtype: object
1.4
Betis - local
2714    0
2731    0
2754    0
2779    3
2794    0
2822    3
2848    0
2854    0
2877    0
2892    1
Name: FTR, dtype: object
0.7
8
14.0
Sociedad - visitante
2718    1
2735    1
2750    0
2782    0
2800    3
2823    0
2843    1
2850    0
2876    3
2895    3
Name: FTR, dtype: object
1.2
Elche - local
2724    3
2749    1
2763    1
2788    3
2809    1
2821    3
2847    3
2855    1
2879    0
2896    0
Name: FTR, dtype: object
1.6
6
11.6
Levante - visitante
2715    0
2730    3
2757    1
2773    0
2799    1
2812    1
2837    3
2867    0
2878    0
2899    0
Name: FTR, dtype: object
0.9
Malaga - local
2723    3
2748    0
2766    0
2785    1
2800    0
2825    3
2849    1
2868    0
2887    3
2900    0

Name: FTR, dtype: object
1.1
11
14.2
Villarreal - visitante
2728    0
2742    3
2751    0
2777    0
2790    3
2817    0
2835    0
2860    3
2888    0
2903    3
Name: FTR, dtype: object
1.2
Vallecano - local
2725    3
2744    3
2765    3
2781    3
2791    0
2815    3
2831    0
2860    0
2885    0
2901    0
Name: FTR, dtype: object
1.5
17
14.4
Betis - visitante
2727    0
2741    3
2763    1
2780    1
2802    0
2816    0
2839    0
2866    1
2881    0
2902    0
Name: FTR, dtype: object
0.6
Sevilla - local
2722    3
2745    3
2762    3
2782    3
2801    1
2813    0
2837    0
2863    3
2882    1
2902    3
Name: FTR, dtype: object
2.0
22
15.9
Granada - visitante
2723    0
2747    0
2769    1
2789    0
2792    0
2819    0
2838    0
2869    0
2885    3
2906    0
Name: FTR, dtype: object
0.4
Barcelona - local
2727    3
2746    3
2764    3
2783    3
2807    3
2828    0
2833    3
2865    3
2888    3
2906    3
Name: FTR, dtype: object
2.7
38
17.8
Ath Bilbao - visitante
2720    3
2749    1
2760    1
2772    1
2794    3
2810    1
2832    3
2862    0
2882    1
2900    3
Name: FTR, dtype: object
1.7
Almeria - local
2729    0
2743    1
2750    3
2775    0
2798    1
2818    3
2834    3
2869    3
2884    1
2908    0
Name: FTR, dtype: object
1.5
14
11.9
Celta - visitante
2725    0
2746    0
2767    3
2788    0
2805    3
2829    3
2846    0
2861    0
2880    0
2905    0
Name: FTR, dtype: object
0.9
Sociedad - local
2726    0
2740    3
2761    3
2770    0
2795    3
2812    1
2830    3
2862    3
2881    3
2905    3
Name: FTR, dtype: object
2.2
22
14.2
Espanol - visitante
2722    0
2748    3
2768    0
2787    1
2804    3
2822    0
2836    1
2864    0
2884    1
2901    3
Name: FTR, dtype: object
1.2
Osasuna - local
2719    1
2735    1
2753    0
2771    0
2793    3
2814    3
2832    0
2864    3
2886    1
2918    0
Name: FTR, dtype: object
1.2
11
14.4
Valencia - visitante
2721    1
2743    1
2761    0
2781    0
2801    1
2828    3
2849    1
2856    0
2883    0
2904    0
Name: FTR, dtype: object
0.7
Levante - local
2720    0
2741    0
2767    0
2786    3
2806    3
2826    1
2842    1
2851    3
2889    3
2903    0
Name: FTR, dtype: object
1.4
9
9.8
Getafe - visitante
2724    0
2734    3
2758    0
2779    0
2797    1
2814    0
2834    0
2863    0
2887    0
2907    0
Name: FTR, dtype: object
0.4
Ath Madrid - local
2728    3
2747    3
2768    3
2784    1
2808    3
2823    3
2844    1
2857    1
2878    3
2883    3
Name: FTR, dtype: object
2.4
19
11.8
Elche - visitante
2711    0
2732    1
2756    0
2774    0
2796    0
2811    1
2830    0
2865    0
2889    0
2915    1
Name: FTR, dtype: object
0.3
Ath Bilbao - local
2739    0
2758    3
2789    3
2804    0
2824    1
2840    3
2858    3
2874    3
2893    3
2917    3
Name: FTR, dtype: object
2.2
23
17.1
Malaga - visitante
2731    3
2759    3
2771    3
2798    1
2815    0
2833    0
2851    0
2879    3
2898    1
2919    0
Name: FTR, dtype: object
1.4
Valencia - local
2734    0
2751    3
2772    1
2792    3
2816    3
2836    1
2867    3
2870    0
2890    3
2911    1
Name: FTR, dtype: object
1.8
22
16.8
Elche - visitante
2732    1
2756    0
2774    0
2796    0
2811    1
2830    0
2865    0
2889    0
2915    1
2933    1
Name: FTR, dtype: object
0.4
Getafe - local
2742    0
2769    1
2787    1
2803    0
2827    1
2843    1
2852    0
2871    0
2899    3
2915    1
Name: FTR, dtype: object
0.8
9
12.1
Ath Madrid - visitante
2739    3
2754    3
2778    3
2793    0
2818    0
2831    3
2868    3
2896    3
2910    1
2931    3
Name: FTR, dtype: object
2.2
Espanol - local
2737    0
2757    1
2774    3
2790    0
2819    3
2846    3
2853    0
2872    3
2895    0
2912    0
Name: FTR, dtype: object
1.3
12
11.8
Vallecano - visitante
2736    0
2755    1
2770    3
2807    0
2826    1
2847    0
2852    3
2874    0
2892    1
2916    3
Name: FTR, dtype: object
1.2
Betis - local
2731    0
2754    0
2779    3
2794    0
2822    3
2848    0
2854    0
2877    0
2892    1
2913    0
Name: FTR, dtype: object
0.7
9
13.9
Sevilla - visitante
2738    0
2753    3
2775    3
2791    3
2825    0
2844    1
2855    1
2875    3
2891    3
2912    3
Name: FTR, dtype: object
2.0
Villarreal - local
2732    1
2760    1
2780    1
2805    0
2820    3
2841    3
2850    3
2875    0
2898    1
2910    1
Name: FTR, dtype: object
1.4
16
12.3
Levante - visitante
2730    3
2757    1
2773    0
2799    1
2812    1
2837    3
2867    0
2878    0
2899    0
2917    0
Name: FTR, dtype: object
0.9
Real Madrid - local
2736    3
2752    0
2773    3
2796    3
2817    3
2838    3
2861    3
2894    3
2914    3
2936    3
Name: FTR, dtype: object
2.7
39
18.5
Almeria - visitante
2733    0
2765    0
2783    0
2806    0
2821    0
2841    0
2858    0
2877    3
2897    0
2918    3
Name: FTR, dtype: object
0.6
Granada - local
2730    0
2756    3
2777    3
2802    3
2829    0
2845    1
2859    3
2876    0
2891    0
2919    3
Name: FTR, dtype: object
1.6
14
14.7
Barcelona - visitante
2737    3
2752    3
2776    0
2795    0
2813    3
2842    1
2857    1
2871    3
2893    0
2913    3
Name: FTR, dtype: object
1.7
Celta - local
2738    3
2759    0
2778    0
2797    1
2810    1
2839    3
2856    3
2873    1
2897    3
2916    0
Name: FTR, dtype: object
1.5
12
14.6
Sociedad - visitante
2735    1
2750    0
2782    0
2800    3
2823    0
2843    1
2850    0
2876    3
2895    3
2914    0
Name: FTR, dtype: object
1.1
Osasuna - local
2735    1
2753    0
2771    0
2793    3
2814    3
2832    0
2864    3
2886    1
2918    0
2937    3
Name: FTR, dtype: object
1.4
14
13.9
Valladolid - visitante
2740    0
2762    0
2785    1
2808    0
2827    1
2840    0
2859    0
2872    0
2894    0
2911    1
Name: FTR, dtype: object
0.3
Levante - local
2741    0
2767    0
2786    3
2806    3
2826    1
2842    1
2851    3
2889    3
2903    0
2922    0
Name: FTR, dtype: object
1.4
8
10.0
Ath Bilbao - visitante
2749    1
2760    1
2772    1
2794    3
2810    1
2832    3
2862    0
2882    1
2900    3
2924    0
Name: FTR, dtype: object
1.4
Valladolid - local
2733    3
2755    1
2776    3
2799    1
2811    1
2835    3
2866    1
2880    3
2909    0
2934    1
Name: FTR, dtype: object
1.7
12
11.4
Valencia - visitante
2743    1
2761    0
2781    0
2801    1
2828    3
2849    1
2856    0
2883    0
2904    0
2923    3
Name: FTR, dtype: object
0.9
Sevilla - local
2745    3
2762    3
2782    3
2801    1
2813    0
2837    0
2863    3
2882    1
2902    3
2927    0
Name: FTR, dtype: object
1.7
18
16.0
Espanol - visitante
2748    3
2768    0
2787    1
2804    3
2822    0
2836    1
2864    0
2884    1
2901    3
2929    0
Name: FTR, dtype: object
1.2
Malaga - local
2748    0
2766    0
2785    1
2800    0
2825    3
2849    1
2868    0
2887    3
2900    0
2921    3
Name: FTR, dtype: object
1.1
10
14.1
Granada - visitante
2747    0
2769    1
2789    0
2792    0
2819    0
2838    0
2869    0
2885    3
2906    0
2922    3
Name: FTR, dtype: object
0.7
Elche - local
2749    1
2763    1
2788    3
2809    1
2821    3
2847    3
2855    1
2879    0
2896    0
2904    3
Name: FTR, dtype: object
1.6
7
10.9
Getafe - visitante
2734    3
2758    0
2779    0
2797    1
2814    0
2834    0
2863    0
2887    0
2907    0
2930    3
Name: FTR, dtype: object
0.7
Vallecano - local
2744    3
2765    3
2781    3
2791    0
2815    3
2831    0
2860    0
2885    0
2901    0
2925    0
Name: FTR, dtype: object
1.2
16
15.3
Celta - visitante
2746    0
2767    3
2788    0
2805    3
2829    3
2846    0
2861    0
2880    0
2905    0
2927    3
Name: FTR, dtype: object
1.2
Sociedad - local
2740    3
2761    3
2770    0
2795    3
2812    1
2830    3
2862    3
2881    3
2905    3
2926    3
Name: FTR, dtype: object
2.5
27
14.6
Real Madrid - visitante
2745    0
2766    3
2784    1
2803    3
2824    1
2848    3
2853    3
2870    3
2886    1
2908    3
Name: FTR, dtype: object
2.1
Barcelona - local
2746    3
2764    3
2783    3
2807    3
2828    0
2833    3
2865    3
2888    3
2906    3
2929    3
Name: FTR, dtype: object
2.7
36
18.5
Betis - visitante
2741    3
2763    1
2780    1
2802    0
2816    0
2839    0
2866    1
2881    0
2902    0
2921    0
Name: FTR, dtype: object
0.6
Ath Madrid - local
2747    3
2768    3
2784    1
2808    3
2823    3
2844    1
2857    1
2878    3
2883    3
2907    3
Name: FTR, dtype: object
2.4
25
13.6
Villarreal - visitante
2742    3
2751    0
2777    0
2790    3
2817    0
2835    0
2860    3
2888    0
2903    3
2920    3
Name: FTR, dtype: object
1.5
Almeria - local
2743    1
2750    3
2775    0
2798    1
2818    3
2834    3
2869    3
2884    1
2908    0
2928    3
Name: FTR, dtype: object
1.8
14
11.7
Osasuna - visitante
2744    0
2764    0
2786    0
2809    1
2820    0
2845    1
2854    3
2873    1
2890    0
2909    3
Name: FTR, dtype: object
0.9
Granada - local
2756    3
2777    3
2802    3
2829    0
2845    1
2859    3
2876    0
2891    0
2919    3
2931    0
Name: FTR, dtype: object
1.6
15
14.9
Levante - visitante
2757    1
2773    0
2799    1
2812    1
2837    3
2867    0
2878    0
2899    0
2917    0
2932    1
Name: FTR, dtype: object
0.7
Betis - local
2754    0
2779    3
2794    0
2822    3
2848    0
2854    0
2877    0
2892    1
2913    0
2932    1
Name: FTR, dtype: object
0.8
8
14.4
Malaga - visitante
2759    3
2771    3
2798    1
2815    0
2833    0
2851    0
2879    3
2898    1
2919    0
2938    1
Name: FTR, dtype: object
1.2
Villarreal - local
2760    1
2780    1
2805    0
2820    3
2841    3
2850    3
2875    0
2898    1
2910    1
2930    0
Name: FTR, dtype: object
1.3
15
12.5
Elche - visitante
2756    0
2774    0
2796    0
2811    1
2830    0
2865    0
2889    0
2915    1
2933    1
2954    3
Name: FTR, dtype: object
0.6
Valladolid - local
2755    1
2776    3
2799    1
2811    1
2835    3
2866    1
2880    3
2909    0
2934    1
2952    1
Name: FTR, dtype: object
1.5
13
10.5
Almeria - visitante
2765    0
2783    0
2806    0
2821    0
2841    0
2858    0
2877    3
2897    0
2918    3
2935    3
Name: FTR, dtype: object
0.9
Valencia - local
2751    3
2772    1
2792    3
2816    3
2836    1
2867    3
2870    0
2890    3
2911    1
2935    0
Name: FTR, dtype: object
1.8
22
16.8
Getafe - visitante
2758    0
2779    0
2797    1
2814    0
2834    0
2863    0
2887    0
2907    0
2930    3
2953    3

Name: FTR, dtype: object
0.7
Osasuna - local
2753    0
2771    0
2793    3
2814    3
2832    0
2864    3
2886    1
2918    0
2937    3
2958    1
Name: FTR, dtype: object
1.4
13
12.8
Sociedad - visitante
2750    0
2782    0
2800    3
2823    0
2843    1
2850    0
2876    3
2895    3
2914    0
2934    1
Name: FTR, dtype: object
1.1
Real Madrid - local
2752    0
2773    3
2796    3
2817    3
2838    3
2861    3
2894    3
2914    3
2936    3
2957    3
Name: FTR, dtype: object
2.7
36
19.1
Vallecano - visitante
2755    1
2770    3
2807    0
2826    1
2847    0
2852    3
2874    0
2892    1
2916    3
2937    0
Name: FTR, dtype: object
1.2
Espanol - local
2757    1
2774    3
2790    0
2819    3
2846    3
2853    0
2872    3
2895    0
2912    0
2938    1
Name: FTR, dtype: object
1.4
12
12.2
Barcelona - visitante
2752    3
2776    0
2795    0
2813    3
2842    1
2857    1
2871    3
2893    0
2913    3
2939    3
Name: FTR, dtype: object
1.7
Celta - local
2759    0
2778    0
2797    1
2810    1
2839    3
2856    3
2873    1
2897    3
2916    0
2939    0
Name: FTR, dtype: object
1.2
11
14.4
Sevilla - visitante
2753    3
2775    3
2791    3
2825    0
2844    1
2855    1
2875    3
2891    3
2912    3
2936    0
Name: FTR, dtype: object
2.0
Ath Bilbao - local
2758    3
2789    3
2804    0
2824    1
2840    3
2858    3
2874    3
2893    3
2917    3
2933    1
Name: FTR, dtype: object
2.3
24
17.5
Ath Madrid - visitante
2754    3
2778    3
2793    0
2818    0
2831    3
2868    3
2896    3
2910    1
2931    3
2959    0
Name: FTR, dtype: object
1.9
Sociedad - local
2761    3
2770    0
2795    3
2812    1
2830    3
2862    3
2881    3
2905    3
2926    3
2942    3
Name: FTR, dtype: object
2.5
29
14.2
Valladolid - visitante
2762    0
2785    1
2808    0
2827    1
2840    0
2859    0
2872    0
2894    0
2911    1
2928    0
Name: FTR, dtype: object
0.3
Levante - local
2767    0
2786    3
2806    3
2826    1
2842    1
2851    3
2889    3
2903    0
2922    0
2946    3
Name: FTR, dtype: object
1.7
10
9.7
Betis - visitante
2763    1
2780    1
2802    0
2816    0
2839    0
2866    1
2881    0
2902    0
2921    0
2944    0
Name: FTR, dtype: object
0.3
Getafe - local
2769    1
2787    1
2803    0
2827    1
2843    1
2852    0
2871    0
2899    3
2915    1
2923    0
Name: FTR, dtype: object
0.8
9
12.3
Villarreal - visitante
2751    0
2777    0
2790    3
2817    0
2835    0
2860    3
2888    0
2903    3
2920    3
2951    0
Name: FTR, dtype: object
1.2
Almeria - local
2750    3
2775    0
2798    1
2818    3
2834    3
2869    3
2884    1
2908    0
2928    3
2955    0
Name: FTR, dtype: object
1.7
12
10.3
Valencia - visitante
2761    0
2781    0
2801    1
2828    3
2849    1
2856    0
2883    0
2904    0
2923    3
2941    0
Name: FTR, dtype: object
0.8
Vallecano - local
2765    3
2781    3
2791    0
2815    3
2831    0
2860    0
2885    0
2901    0
2925    0
2949    0
Name: FTR, dtype: object
0.9
15
15.6
Osasuna - visitante
2764    0
2786    0
2809    1
2820    0
2845    1
2854    3
2873    1
2890    0
2909    3
2926    0
Name: FTR, dtype: object
0.9
Sevilla - local
2762    3
2782    3
2801    1
2813    0
2837    0
2863    3
2882    1
2902    3
2927    0
2943    3
Name: FTR, dtype: object
1.7
18
17.1
Real Madrid - visitante
2766    3
2784    1
2803    3
2824    1
2848    3
2853    3
2870    3
2886    1
2908    3
2925    3
Name: FTR, dtype: object
2.4
Barcelona - local
2764    3
2783    3
2807    3
2828    0
2833    3
2865    3
2888    3
2906    3
2929    3
2948    3
Name: FTR, dtype: object
2.7
35
18.3
Celta - visitante
2767    3
2788    0
2805    3
2829    3
2846    0
2861    0
2880    0
2905    0
2927    3
2945    3
Name: FTR, dtype: object
1.5
Ath Madrid - local
2768    3
2784    1
2808    3
2823    3
2844    1
2857    1
2878    3
2883    3
2907    3
2924    3
Name: FTR, dtype: object
2.4
26
13.5
Granada - visitante
2769    1
2789    0
2792    0
2819    0
2838    0
2869    0
2885    3
2906    0
2922    3
2947    3
Name: FTR, dtype: object
1.0
Malaga - local
2766    0
2785    1
2800    0
2825    3
2849    1
2868    0
2887    3
2900    0
2921    3
2945    0
Name: FTR, dtype: object
1.1
9
13.2
Espanol - visitante
2768    0
2787    1
2804    3
2822    0
2836    1
2864    0
2884    1
2901    3
2929    0
2946    0
Name: FTR, dtype: object
0.9
Elche - local
2763    1
2788    3
2809    1
2821    3
2847    3
2855    1
2879    0
2896    0
2904    3
2920    0
Name: FTR, dtype: object
1.5
7
10.2
Ath Bilbao - visitante
2760    1
2772    1
2794    3
2810    1
2832    3
2862    0
2882    1
2900    3
2924    0
2940    3
Name: FTR, dtype: object
1.6
Almeria - local
2775    0
2798    1
2818    3
2834    3
2869    3
2884    1
2908    0
2928    3
2955    0
2978    0
Name: FTR, dtype: object
1.4
8
9.4
Sociedad - visitante
2782    0
2800    3
2823    0
2843    1
2850    0
2876    3
2895    3
2914    0
2934    1
2956    3
Name: FTR, dtype: object
1.4
Valencia - local
2772    1
2792    3
2816    3
2836    1
2867    3
2870    0
2890    3
2911    1
2935    0
2956    0
Name: FTR, dtype: object
1.5
21
17.0
Villarreal - visitante
2777    0
2790    3
2817    0
2835    0
2860    3
2888    0
2903    3
2920    3
2951    0
2974    0
Name: FTR, dtype: object
1.2
Real Madrid - local
2773    3
2796    3
2817    3
2838    3
2861    3
2894    3
2914    3
2936    3
2957    3
2977    0
Name: FTR, dtype: object
2.7
33
19.8
Barcelona - visitante
2776    0
2795    0
2813    3
2842    1
2857    1
2871    3
2893    0
2913    3
2939    3
2958    1
Name: FTR, dtype: object
1.5
Osasuna - local
2771    0
2793    3
2814    3
2832    0
2864    3
2886    1
2918    0
2937    3
2958    1
2971    0
Name: FTR, dtype: object
1.4
12
13.0
Sevilla - visitante
2775    3
2791    3
2825    0
2844    1
2855    1
2875    3
2891    3
2912    3
2936    0
2952    1
Name: FTR, dtype: object
1.8
Betis - local
2779    3
2794    0
2822    3
2848    0
2854    0
2877    0
2892    1
2913    0
2932    1
2954    0
Name: FTR, dtype: object
0.8
9
15.4
Ath Madrid - visitante
2778    3
2793    0
2818    0
2831    3
2868    3
2896    3
2910    1
2931    3
2959    0
2977    3
Name: FTR, dtype: object
1.9
Valladolid - local
2776    3
2799    1
2811    1
2835    3
2866    1
2880    3
2909    0
2934    1
2952    1
2979    1
Name: FTR, dtype: object
1.5
14
10.9
Vallecano - visitante
2770    3
2807    0
2826    1
2847    0
2852    3
2874    0
2892    1
2916    3
2937    0
2955    3
Name: FTR, dtype: object
1.4
Granada - local
2777    3
2802    3
2829    0
2845    1
2859    3
2876    0
2891    0
2919    3
2931    0
2953    0
Name: FTR, dtype: object
1.3
14
15.2
Elche - visitante
2774    0
2796    0
2811    1
2830    0
2865    0
2889    0
2915    1
2933    1
2954    3
2973    3
Name: FTR, dtype: object
0.9
Espanol - local
2774    3
2790    0
2819    3
2846    3
2853    0
2872    3
2895    0
2912    0
2938    1
2959    3
Name: FTR, dtype: object
1.6
13
11.9
Levante - visitante
2773    0
2799    1
2812    1
2837    3
2867    0
2878    0
2899    0
2917    0
2932    1
2950    3
Name: FTR, dtype: object
0.9
Ath Bilbao - local
2789    3
2804    0
2824    1
2840    3
2858    3
2874    3
2893    3
2917    3
2933    1
2951    3
Name: FTR, dtype: object
2.3
25
18.0
Getafe - visitante
2779    0
2797    1
2814    0
2834    0
2863    0
2887    0
2907    0
2930    3
2953    3
2972    3
Name: FTR, dtype: object
1.0
Celta - local
2778    0
2797    1
2810    1
2839    3
2856    3
2873    1
2897    3
2916    0
2939    0
2950    0
Name: FTR, dtype: object
1.2
11
14.7
Malaga - visitante
2771    3
2798    1
2815    0
2833    0
2851    0
2879    3
2898    1
2919    0
2938    1
2957    0
Name: FTR, dtype: object
0.9
Villarreal - local
2780    1
2805    0
2820    3
2841    3
2850    3
2875    0
2898    1
2910    1
2930    0
2941    3
Name: FTR, dtype: object
1.5
18
13.2
Ath Bilbao - visitante
2772    1
2794    3
2810    1
2832    3
2862    0
2882    1
2900    3
2924    0
2940    3
2970    0
Name: FTR, dtype: object
1.5
Sociedad - local
2770    0
2795    3
2812    1
2830    3
2862    3
2881    3
2905    3
2926    3
2942    3
2976    1
Name: FTR, dtype: object
2.3
29
15.0
Valencia - visitante
2781    0
2801    1
2828    3
2849    1
2856    0
2883    0
2904    0
2923    3
2941    0
2963    1
Name: FTR, dtype: object
0.9
Sevilla - local
2782    3
2801    1
2813    0
2837    0
2863    3
2882    1
2902    3
2927    0
2943    3
2960    3
Name: FTR, dtype: object
1.7
16
17.9
Valladolid - visitante
2785    1
2808    0
2827    1
2840    0
2859    0
2872    0
2894    0
2911    1
2928    0
2949    3
Name: FTR, dtype: object
0.6
Elche - local
2788    3
2809    1
2821    3
2847    3
2855    1
2879    0
2896    0
2904    3
2920    0
2947    0
Name: FTR, dtype: object
1.4
7
9.8
Betis - visitante
2780    1
2802    0
2816    0
2839    0
2866    1
2881    0
2902    0
2921    0
2944    0
2961    0
Name: FTR, dtype: object
0.2
Barcelona - local
2783    3
2807    3
2828    0
2833    3
2865    3
2888    3
2906    3
2929    3
2948    3
2967    3
Name: FTR, dtype: object
2.7
32
18.4
Osasuna - visitante
2786    0
2809    1
2820    0
2845    1
2854    3
2873    1
2890    0
2909    3
2926    0
2943    0
Name: FTR, dtype: object
0.9
Vallecano - local
2781    3
2791    0
2815    3
2831    0
2860    0
2885    0
2901    0
2925    0
2949    0
2964    3
Name: FTR, dtype: object
0.9
13
15.3
Almeria - visitante
2783    0
2806    0
2821    0
2841    0
2858    0
2877    3
2897    0
2918    3
2935    3
2942    0
Name: FTR, dtype: object
0.9
Malaga - local
2785    1
2800    0
2825    3
2849    1
2868    0
2887    3
2900    0
2921    3
2945    0
2969    0

Name: FTR, dtype: object
1.1
9
13.5
Real Madrid - visitante
2784    1
2803    3
2824    1
2848    3
2853    3
2870    3
2886    1
2908    3
2925    3
2948    0
Name: FTR, dtype: object
2.1
Levante - local
2786    3
2806    3
2826    1
2842    1
2851    3
2889    3
2903    0
2922    0
2946    3
2965    0
Name: FTR, dtype: object
1.7
12
9.2
Celta - visitante
2788    0
2805    3
2829    3
2846    0
2861    0
2880    0
2905    0
2927    3
2945    3
2962    0
Name: FTR, dtype: object
1.2
Ath Madrid - local
2784    1
2808    3
2823    3
2844    1
2857    1
2878    3
2883    3
2907    3
2924    3
2944    3
Name: FTR, dtype: object
2.4
30
14.3
Espanol - visitante
2787    1
2804    3
2822    0
2836    1
2864    0
2884    1
2901    3
2929    0
2946    0
2966    0
Name: FTR, dtype: object
0.9
Getafe - local
2787    1
2803    0
2827    1
2843    1
2852    0
2871    0
2899    3
2915    1
2923    0
2940    0
Name: FTR, dtype: object
0.7
6
12.6
Granada - visitante
2789    0
2792    0
2819    0
2838    0
2869    0
2885    3
2906    0
2922    3
2947    3
2968    0
Name: FTR, dtype: object
0.9
Sociedad - local
2795    3
2812    1
2830    3
2862    3
2881    3
2905    3
2926    3
2942    3
2976    1
2997    1
Name: FTR, dtype: object
2.4
27
14.5
Vallecano - visitante
2807    0
2826    1
2847    0
2852    3
2874    0
2892    1
2916    3
2937    0
2955    3
2975    0
Name: FTR, dtype: object
1.1
Osasuna - local
2793    3
2814    3
2832    0
2864    3
2886    1
2918    0
2937    3
2958    1
2971    0
2999    3
Name: FTR, dtype: object
1.7
14
11.9
Malaga - visitante
2798    1
2815    0
2833    0
2851    0
2879    3
2898    1
2919    0
2938    1
2957    0
2979    1
Name: FTR, dtype: object
0.7
Valencia - local
2792    3
2816    3
2836    1
2867    3
2870    0
2890    3
2911    1
2935    0
2956    0
2975    3
Name: FTR, dtype: object
1.7
21
16.2
Ath Bilbao - visitante
2794    3
2810    1
2832    3
2862    0
2882    1
2900    3
2924    0
2940    3
2970    0
2990    0
Name: FTR, dtype: object
1.4
Real Madrid - local
2796    3
2817    3
2838    3
2861    3
2894    3
2914    3
2936    3
2957    3
2977    0
2992    3
Name: FTR, dtype: object
2.7
34
20.2
Levante - visitante
2799    1
2812    1
2837    3
2867    0
2878    0
2899    0
2917    0
2932    1
2950    3
2971    3
Name: FTR, dtype: object
1.2
Espanol - local
2790    0
2819    3
2846    3
2853    0
2872    3
2895    0
2912    0
2938    1
2959    3
2972    0
Name: FTR, dtype: object
1.3
10
12.1
Elche - visitante
2796    0
2811    1
2830    0
2865    0
2889    0
2915    1
2933    1
2954    3
2973    3
2999    0
Name: FTR, dtype: object
0.9
Almeria - local
2798    1
2818    3
2834    3
2869    3
2884    1
2908    0
2928    3
2955    0
2978    0
2998    1
Name: FTR, dtype: object
1.5
9
9.9
Sevilla - visitante
2791    3
2825    0
2844    1
2855    1
2875    3
2891    3
2912    3
2936    0
2952    1
2976    1
Name: FTR, dtype: object
1.6
Valladolid - local
2799    1
2811    1
2835    3
2866    1
2880    3
2909    0
2934    1
2952    1
2979    1
2996    0
Name: FTR, dtype: object
1.2
13
11.4
Barcelona - visitante
2795    0
2813    3
2842    1
2857    1
2871    3
2893    0
2913    3
2939    3
2958    1
2978    3
Name: FTR, dtype: object
1.8
Granada - local
2802    3
2829    0
2845    1
2859    3
2876    0
2891    0
2919    3
2931    0
2953    0
2970    3
Name: FTR, dtype: object
1.3
14
15.2
Villarreal - visitante
2790    3
2817    0
2835    0
2860    3
2888    0
2903    3
2920    3
2951    0
2974    0
2993    1
Name: FTR, dtype: object
1.3
Celta - local
2797    1
2810    1
2839    3
2856    3
2873    1
2897    3
2916    0
2939    0
2950    0
2973    0
Name: FTR, dtype: object
1.2
11
14.5
Ath Madrid - visitante
2793    0
2818    0
2831    3
2868    3
2896    3
2910    1
2931    3
2959    0
2977    3
2996    3
Name: FTR, dtype: object
1.9
Betis - local
2794    0
2822    3
2848    0
2854    0
2877    0
2892    1
2913    0
2932    1
2954    0
2974    3
Name: FTR, dtype: object
0.8
8
14.8
Getafe - visitante
2797    1
2814    0
2834    0
2863    0
2887    0
2907    0
2930    3
2953    3
2972    3
2992    0
Name: FTR, dtype: object
1.0
Villarreal - local
2805    0
2820    3
2841    3
2850    3
2875    0
2898    1
2910    1
2930    0
2941    3
2968    3
Name: FTR, dtype: object
1.7
20
14.4
Betis - visitante
2802    0
2816    0
2839    0
2866    1
2881    0
2902    0
2921    0
2944    0
2961    0
2982    0
Name: FTR, dtype: object
0.1
Vallecano - local
2791    0
2815    3
2831    0
2860    0
2885    0
2901    0
2925    0
2949    0
2964    3
2995    0
Name: FTR, dtype: object
0.6
12
15.0
Valencia - visitante
2801    1
2828    3
2849    1
2856    0
2883    0
2904    0
2923    3
2941    0
2963    1
2984    3
Name: FTR, dtype: object
1.2
Sevilla - local
2801    1
2813    0
2837    0
2863    3
2882    1
2902    3
2927    0
2943    3
2960    3
2983    3
Name: FTR, dtype: object
1.7
19
18.5
Sociedad - visitante
2800    3
2823    0
2843    1
2850    0
2876    3
2895    3
2914    0
2934    1
2956    3
2964    0
Name: FTR, dtype: object
1.4
Barcelona - local
2807    3
2828    0
2833    3
2865    3
2888    3
2906    3
2929    3
2948    3
2967    3
2988    3
Name: FTR, dtype: object
2.7
32
17.8
Almeria - visitante
2806    0
2821    0
2841    0
2858    0
2877    3
2897    0
2918    3
2935    3
2942    0
2960    0
Name: FTR, dtype: object
0.9
Ath Madrid - local
2808    3
2823    3
2844    1
2857    1
2878    3
2883    3
2907    3
2924    3
2944    3
2962    3
Name: FTR, dtype: object
2.6
30
15.5
Real Madrid - visitante
2803    3
2824    1
2848    3
2853    3
2870    3
2886    1
2908    3
2925    3
2948    0
2965    3
Name: FTR, dtype: object
2.3
Malaga - local
2800    0
2825    3
2849    1
2868    0
2887    3
2900    0
2921    3
2945    0
2969    0
2986    3
Name: FTR, dtype: object
1.3
10
13.4
Valladolid - visitante
2808    0
2827    1
2840    0
2859    0
2872    0
2894    0
2911    1
2928    0
2949    3
2967    0
Name: FTR, dtype: object
0.5
Levante - local
2806    3
2826    1
2842    1
2851    3
2889    3
2903    0
2922    0
2946    3
2965    0
2987    1
Name: FTR, dtype: object
1.5
11
10.9
Osasuna - visitante
2809    1
2820    0
2845    1
2854    3
2873    1
2890    0
2909    3
2926    0
2943    0
2969    3
Name: FTR, dtype: object
1.2
Getafe - local
2803    0
2827    1
2843    1
2852    0
2871    0
2899    3
2915    1
2923    0
2940    0
2961    3
Name: FTR, dtype: object
0.9
9
12.2
Espanol - visitante
2804    3
2822    0
2836    1
2864    0
2884    1
2901    3
2929    0
2946    0
2966    0
2980    0
Name: FTR, dtype: object
0.8
Elche - local
2809    1
2821    3
2847    3
2855    1
2879    0
2896    0
2904    3
2920    0
2947    0
2966    3
Name: FTR, dtype: object
1.4
8
10.1
Celta - visitante
2805    3
2829    3
2846    0
2861    0
2880    0
2905    0
2927    3
2945    3
2962    0
2981    0
Name: FTR, dtype: object
1.2
Ath Bilbao - local
2804    0
2824    1
2840    3
2858    3
2874    3
2893    3
2917    3
2933    1
2951    3
2963    1
Name: FTR, dtype: object
2.1
22
17.0
Granada - visitante
2792    0
2819    0
2838    0
2869    0
2885    3
2906    0
2922    3
2947    3
2968    0
2994    1
Name: FTR, dtype: object
1.0
Espanol - local
2819    3
2846    3
2853    0
2872    3
2895    0
2912    0
2938    1
2959    3
2972    0
2990    3
Name: FTR, dtype: object
1.6
12
11.9
Villarreal - visitante
2817    0
2835    0
2860    3
2888    0
2903    3
2920    3
2951    0
2974    0
2993    1
3016    3
Name: FTR, dtype: object
1.3
Vallecano - local
2815    3
2831    0
2860    0
2885    0
2901    0
2925    0
2949    0
2964    3
2995    0
3018    0
Name: FTR, dtype: object
0.6
13
16.4
Sevilla - visitante
2825    0
2844    1
2855    1
2875    3
2891    3
2912    3
2936    0
2952    1
2976    1
2991    0
Name: FTR, dtype: object
1.3
Valencia - local
2816    3
2836    1
2867    3
2870    0
2890    3
2911    1
2935    0
2956    0
2975    3
2991    3
Name: FTR, dtype: object
1.7
22
17.1
Granada - visitante
2819    0
2838    0
2869    0
2885    3
2906    0
2922    3
2947    3
2968    0
2994    1
3017    1
Name: FTR, dtype: object
1.1
Osasuna - local
2814    3
2832    0
2864    3
2886    1
2918    0
2937    3
2958    1
2971    0
2999    3
3016    0
Name: FTR, dtype: object
1.4
11
11.8
Ath Madrid - visitante
2818    0
2831    3
2868    3
2896    3
2910    1
2931    3
2959    0
2977    3
2996    3
3011    3
Name: FTR, dtype: object
2.2
Betis - local
2822    3
2848    0
2854    0
2877    0
2892    1
2913    0
2932    1
2954    0
2974    3
2994    1
Name: FTR, dtype: object
0.9
8
15.6
Ath Bilbao - visitante
2810    1
2832    3
2862    0
2882    1
2900    3
2924    0
2940    3
2970    0
2990    0
3013    0
Name: FTR, dtype: object
1.1
Sociedad - local
2812    1
2830    3
2862    3
2881    3
2905    3
2926    3
2942    3
2976    1
2997    1
3011    0
Name: FTR, dtype: object
2.1
25
14.0
Barcelona - visitante
2813    3
2842    1
2857    1
2871    3
2893    0
2913    3
2939    3
2958    1
2978    3
2995    3
Name: FTR, dtype: object
2.1
Real Madrid - local
2817    3
2838    3
2861    3
2894    3
2914    3
2936    3
2957    3
2977    0
2992    3
3013    3
Name: FTR, dtype: object
2.7
34
20.6
Elche - visitante
2811    1
2830    0
2865    0
2889    0
2915    1
2933    1
2954    3
2973    3
2999    0
3019    1
Name: FTR, dtype: object
1.0
Celta - local
2810    1
2839    3
2856    3
2873    1
2897    3
2916    0
2939    0
2950    0
2973    0
2993    1
Name: FTR, dtype: object
1.2
10
13.1
Getafe - visitante
2814    0
2834    0
2863    0
2887    0
2907    0
2930    3
2953    3
2972    3
2992    0
3015    0
Name: FTR, dtype: object
0.9
Almeria - local
2818    3
2834    3
2869    3
2884    1
2908    0
2928    3
2955    0
2978    0
2998    1
3019    1
Name: FTR, dtype: object
1.5
11
10.1
Malaga - visitante
2815    0
2833    0
2851    0
2879    3
2898    1
2919    0
2938    1
2957    0
2979    1
2997    1
Name: FTR, dtype: object
0.7
Valladolid - local
2811    1
2835    3
2866    1
2880    3
2909    0
2934    1
2952    1
2979    1
2996    0
3015    3

Name: FTR, dtype: object
1.4
13
12.4
Levante - visitante
2812    1
2837    3
2867    0
2878    0
2899    0
2917    0
2932    1
2950    3
2971    3
2998    1
Name: FTR, dtype: object
1.2
Malaga - local
2825    3
2849    1
2868    0
2887    3
2900    0
2921    3
2945    0
2969    0
2986    3
3002    3
Name: FTR, dtype: object
1.6
15
13.7
Sociedad - visitante
2823    0
2843    1
2850    0
2876    3
2895    3
2914    0
2934    1
2956    3
2964    0
2988    0
Name: FTR, dtype: object
1.1
Sevilla - local
2813    0
2837    0
2863    3
2882    1
2902    3
2927    0
2943    3
2960    3
2983    3
3012    1
Name: FTR, dtype: object
1.7
21
18.3
Valencia - visitante
2828    3
2849    1
2856    0
2883    0
2904    0
2923    3
2941    0
2963    1
2984    3
3005    0
Name: FTR, dtype: object
1.1
Granada - local
2829    0
2845    1
2859    3
2876    0
2891    0
2919    3
2931    0
2953    0
2970    3
2984    0
Name: FTR, dtype: object
1.0
13
15.2
Betis - visitante
2816    0
2839    0
2866    1
2881    0
2902    0
2921    0
2944    0
2961    0
2982    0
3014    1
Name: FTR, dtype: object
0.2
Getafe - local
2827    1
2843    1
2852    0
2871    0
2899    3
2915    1
2923    0
2940    0
2961    3
2981    3
Name: FTR, dtype: object
1.2
11
12.7
Real Madrid - visitante
2824    1
2848    3
2853    3
2870    3
2886    1
2908    3
2925    3
2948    0
2965    3
2985    3
Name: FTR, dtype: object
2.3
Ath Bilbao - local
2824    1
2840    3
2858    3
2874    3
2893    3
2917    3
2933    1
2951    3
2963    1
2982    3
Name: FTR, dtype: object
2.4
23
18.0
Espanol - visitante
2822    0
2836    1
2864    0
2884    1
2901    3
2929    0
2946    0
2966    0
2980    0
3003    3
Name: FTR, dtype: object
0.8
Villarreal - local
2820    3
2841    3
2850    3
2875    0
2898    1
2910    1
2930    0
2941    3
2968    3
2980    3
Name: FTR, dtype: object
2.0
22
13.3
Celta - visitante
2829    3
2846    0
2861    0
2880    0
2905    0
2927    3
2945    3
2962    0
2981    0
3001    0
Name: FTR, dtype: object
0.9
Levante - local
2826    1
2842    1
2851    3
2889    3
2903    0
2922    0
2946    3
2965    0
2987    1
3007    1
Name: FTR, dtype: object
1.3
10
10.9
Almeria - visitante
2821    0
2841    0
2858    0
2877    3
2897    0
2918    3
2935    3
2942    0
2960    0
2986    0
Name: FTR, dtype: object
0.9
Barcelona - local
2828    0
2833    3
2865    3
2888    3
2906    3
2929    3
2948    3
2967    3
2988    3
3008    3
Name: FTR, dtype: object
2.7
29
17.6
Vallecano - visitante
2826    1
2847    0
2852    3
2874    0
2892    1
2916    3
2937    0
2955    3
2975    0
2983    0
Name: FTR, dtype: object
1.1
Ath Madrid - local
2823    3
2844    1
2857    1
2878    3
2883    3
2907    3
2924    3
2944    3
2962    3
2989    3
Name: FTR, dtype: object
2.6
29
15.5
Valladolid - visitante
2827    1
2840    0
2859    0
2872    0
2894    0
2911    1
2928    0
2949    3
2967    0
2987    1
Name: FTR, dtype: object
0.6
Elche - local
2821    3
2847    3
2855    1
2879    0
2896    0
2904    3
2920    0
2947    0
2966    3
2985    0
Name: FTR, dtype: object
1.3
9
10.1
Osasuna - visitante
2820    0
2845    1
2854    3
2873    1
2890    0
2909    3
2926    0
2943    0
2969    3
2989    0
Name: FTR, dtype: object
1.1
Celta - local
2839    3
2856    3
2873    1
2897    3
2916    0
2939    0
2950    0
2973    0
2993    1
3017    1
Name: FTR, dtype: object
1.2
11
13.4
Ath Bilbao - visitante
2832    3
2862    0
2882    1
2900    3
2924    0
2940    3
2970    0
2990    0
3013    0
3037    3
Name: FTR, dtype: object
1.3
Valladolid - local
2835    3
2866    1
2880    3
2909    0
2934    1
2952    1
2979    1
2996    0
3015    3
3037    0
Name: FTR, dtype: object
1.3
12
11.9
Elche - visitante
2830    0
2865    0
2889    0
2915    1
2933    1
2954    3
2973    3
2999    0
3019    1
3030    0
Name: FTR, dtype: object
0.9
Sociedad - local
2830    3
2862    3
2881    3
2905    3
2926    3
2942    3
2976    1
2997    1
3011    0
3039    3
Name: FTR, dtype: object
2.3
27
13.8
Levante - visitante
2837    3
2867    0
2878    0
2899    0
2917    0
2932    1
2950    3
2971    3
2998    1
3018    3
Name: FTR, dtype: object
1.4
Sevilla - local
2837    0
2863    3
2882    1
2902    3
2927    0
2943    3
2960    3
2983    3
3012    1
3033    0
Name: FTR, dtype: object
1.7
21
18.2
Barcelona - visitante
2842    1
2857    1
2871    3
2893    0
2913    3
2939    3
2958    1
2978    3
2995    3
3010    3
Name: FTR, dtype: object
2.1
Osasuna - local
2832    0
2864    3
2886    1
2918    0
2937    3
2958    1
2971    0
2999    3
3016    0
3035    0
Name: FTR, dtype: object
1.1
10
11.8
Getafe - visitante
2834    0
2863    0
2887    0
2907    0
2930    3
2953    3
2972    3
2992    0
3015    0
3039    0
Name: FTR, dtype: object
0.9
Vallecano - local
2831    0
2860    0
2885    0
2901    0
2925    0
2949    0
2964    3
2995    0
3018    0
3030    3
Name: FTR, dtype: object
0.6
12
16.4
Malaga - visitante
2833    0
2851    0
2879    3
2898    1
2919    0
2938    1
2957    0
2979    1
2997    1
3012    1
Name: FTR, dtype: object
0.8
Valencia - local
2836    1
2867    3
2870    0
2890    3
2911    1
2935    0
2956    0
2975    3
2991    3
3010    0
Name: FTR, dtype: object
1.4
19
16.9
Betis - visitante
2839    0
2866    1
2881    0
2902    0
2921    0
2944    0
2961    0
2982    0
3014    1
3034    0
Name: FTR, dtype: object
0.2
Real Madrid - local
2838    3
2861    3
2894    3
2914    3
2936    3
2957    3
2977    0
2992    3
3013    3
3034    3
Name: FTR, dtype: object
2.7
32
21.3
Villarreal - visitante
2835    0
2860    3
2888    0
2903    3
2920    3
2951    0
2974    0
2993    1
3016    3
3032    3
Name: FTR, dtype: object
1.6
Almeria - local
2834    3
2869    3
2884    1
2908    0
2928    3
2955    0
2978    0
2998    1
3019    1
3032    0
Name: FTR, dtype: object
1.2
11
10.9
Ath Madrid - visitante
2831    3
2868    3
2896    3
2910    1
2931    3
2959    0
2977    3
2996    3
3011    3
3033    3
Name: FTR, dtype: object
2.5
Espanol - local
2846    3
2853    0
2872    3
2895    0
2912    0
2938    1
2959    3
2972    0
2990    3
3014    1
Name: FTR, dtype: object
1.4
11
11.6
Granada - visitante
2838    0
2869    0
2885    3
2906    0
2922    3
2947    3
2968    0
2994    1
3017    1
3035    3
Name: FTR, dtype: object
1.4
Villarreal - local
2841    3
2850    3
2875    0
2898    1
2910    1
2930    0
2941    3
2968    3
2980    3
3006    1
Name: FTR, dtype: object
1.8
21
13.9
Osasuna - visitante
2845    1
2854    3
2873    1
2890    0
2909    3
2926    0
2943    0
2969    3
2989    0
3004    0
Name: FTR, dtype: object
1.1
Elche - local
2847    3
2855    1
2879    0
2896    0
2904    3
2920    0
2947    0
2966    3
2985    0
3000    1
Name: FTR, dtype: object
1.1
8
9.8
Almeria - visitante
2841    0
2858    0
2877    3
2897    0
2918    3
2935    3
2942    0
2960    0
2986    0
3009    0
Name: FTR, dtype: object
0.9
Betis - local
2848    0
2854    0
2877    0
2892    1
2913    0
2932    1
2954    0
2974    3
2994    1
3005    3
Name: FTR, dtype: object
0.9
9
16.4
Espanol - visitante
2836    1
2864    0
2884    1
2901    3
2929    0
2946    0
2966    0
2980    0
3003    3
3031    1
Name: FTR, dtype: object
0.9
Ath Madrid - local
2844    1
2857    1
2878    3
2883    3
2907    3
2924    3
2944    3
2962    3
2989    3
3009    3
Name: FTR, dtype: object
2.6
29
16.3
Sociedad - visitante
2843    1
2850    0
2876    3
2895    3
2914    0
2934    1
2956    3
2964    0
2988    0
3007    1
Name: FTR, dtype: object
1.2
Ath Bilbao - local
2840    3
2858    3
2874    3
2893    3
2917    3
2933    1
2951    3
2963    1
2982    3
3001    3
Name: FTR, dtype: object
2.6
25
18.7
Real Madrid - visitante
2848    3
2853    3
2870    3
2886    1
2908    3
2925    3
2948    0
2965    3
2985    3
3006    1
Name: FTR, dtype: object
2.3
Malaga - local
2849    1
2868    0
2887    3
2900    0
2921    3
2945    0
2969    0
2986    3
3002    3
3021    0
Name: FTR, dtype: object
1.3
12
13.2
Sevilla - visitante
2844    1
2855    1
2875    3
2891    3
2912    3
2936    0
2952    1
2976    1
2991    0
3008    0
Name: FTR, dtype: object
1.3
Levante - local
2842    1
2851    3
2889    3
2903    0
2922    0
2946    3
2965    0
2987    1
3007    1
3022    1
Name: FTR, dtype: object
1.3
10
10.6
Vallecano - visitante
2847    0
2852    3
2874    0
2892    1
2916    3
2937    0
2955    3
2975    0
2983    0
3002    0
Name: FTR, dtype: object
1.0
Getafe - local
2843    1
2852    0
2871    0
2899    3
2915    1
2923    0
2940    0
2961    3
2981    3
3004    3
Name: FTR, dtype: object
1.4
13
13.4
Valladolid - visitante
2840    0
2859    0
2872    0
2894    0
2911    1
2928    0
2949    3
2967    0
2987    1
3000    1
Name: FTR, dtype: object
0.6
Barcelona - local
2833    3
2865    3
2888    3
2906    3
2929    3
2948    3
2967    3
2988    3
3008    3
3036    3
Name: FTR, dtype: object
3.0
34
17.8
Valencia - visitante
2849    1
2856    0
2883    0
2904    0
2923    3
2941    0
2963    1
2984    3
3005    0
3026    0
Name: FTR, dtype: object
0.8
Granada - local
2845    1
2859    3
2876    0
2891    0
2919    3
2931    0
2953    0
2970    3
2984    0
3003    0
Name: FTR, dtype: object
1.0
12
14.5
Celta - visitante
2846    0
2861    0
2880    0
2905    0
2927    3
2945    3
2962    0
2981    0
3001    0
3023    3
Name: FTR, dtype: object
0.9
Sociedad - local
2862    3
2881    3
2905    3
2926    3
2942    3
2976    1
2997    1
3011    0
3039    3
3052    1
Name: FTR, dtype: object
2.1
26
15.8
Elche - visitante
2865    0
2889    0
2915    1
2933    1
2954    3
2973    3
2999    0
3019    1
3030    0
Name: FTR, dtype: object
1.0

Vallecano - local
2860    0
2885    0
2901    0
2925    0
2949    0
2964    3
2995    0
3018    0
3030    3
3041    1
Name: FTR, dtype: object
0.7
12
17.9
Ath Madrid - visitante
2868    3
2896    3
2910    1
2931    3
2959    0
2977    3
2996    3
3011    3
3033    3
3040    3
Name: FTR, dtype: object
2.5
Osasuna - local
2864    3
2886    1
2918    0
2937    3
2958    1
2971    0
2999    3
3016    0
3035    0
3053    3
Name: FTR, dtype: object
1.4
11
12.5
Ath Bilbao - visitante
2862    0
2882    1
2900    3
2924    0
2940    3
2970    0
2990    0
3013    0
3037    3
3041    1
Name: FTR, dtype: object
1.1
Barcelona - local
2865    3
2888    3
2906    3
2929    3
2948    3
2967    3
2988    3
3008    3
3036    3
3049    3
Name: FTR, dtype: object
3.0
35
16.5
Malaga - visitante
2851    0
2879    3
2898    1
2919    0
2938    1
2957    0
2979    1
2997    1
3012    1
3038    0
Name: FTR, dtype: object
0.8
Almeria - local
2869    3
2884    1
2908    0
2928    3
2955    0
2978    0
2998    1
3019    1
3032    0
Name: FTR, dtype: object
1.0
10
11.333333333333334
Getafe - visitante
2863    0
2887    0
2907    0
2930    3
2953    3
2972    3
2992    0
3015    0
3039    0
3047    0
Name: FTR, dtype: object
0.9
Valladolid - local
2866    1
2880    3
2909    0
2934    1
2952    1
2979    1
2996    0
3015    3
3037    0
3050    0
Name: FTR, dtype: object
1.0
11
12.4
Villarreal - visitante
2860    3
2888    0
2903    3
2920    3
2951    0
2974    0
2993    1
3016    3
3032    3
3431    0
Name: FTR, dtype: object
1.6
Valencia - local
2867    3
2870    0
2890    3
2911    1
2935    0
2956    0
2975    3
2991    3
3010    0
3038    3
Name: FTR, dtype: object
1.6
18
16.3
Espanol - visitante
2864    0
2884    1
2901    3
2929    0
2946    0
2966    0
2980    0
3003    3
3031    1
3048    0
Name: FTR, dtype: object
0.8
Sevilla - local
2863    3
2882    1
2902    3
2927    0
2943    3
2960    3
2983    3
3012    1
3033    0
3042    3
Name: FTR, dtype: object
2.0
23
17.5
Levante - visitante
2867    0
2878    0
2899    0
2917    0
2932    1
2950    3
2971    3
2998    1
3018    3
3036    0
Name: FTR, dtype: object
1.1
Real Madrid - local
2861    3
2894    3
2914    3
2936    3
2957    3
2977    0
2992    3
3013    3
3034    3
3043    3
Name: FTR, dtype: object
2.7
34
20.8
Granada - visitante
2869    0
2885    3
2906    0
2922    3
2947    3
2968    0
2994    1
3017    1
3035    3
3051    0
Name: FTR, dtype: object
1.4
Celta - local
2856    3
2873    1
2897    3
2916    0
2939    0
2950    0
2973    0
2993    1
3017    1
3031    1
Name: FTR, dtype: object
1.0
9
13.9
Betis - visitante
2866    1
2881    0
2902    0
2921    0
2944    0
2961    0
2982    0
3014    1
3034    0
3045    1
Name: FTR, dtype: object
0.3
Ath Bilbao - local
2858    3
2874    3
2893    3
2917    3
2933    1
2951    3
2963    1
2982    3
3001    3
3029    3
Name: FTR, dtype: object
2.6
23
17.2
Valladolid - visitante
2859    0
2872    0
2894    0
2911    1
2928    0
2949    3
2967    0
2987    1
3000    1
3025    0
Name: FTR, dtype: object
0.6
Villarreal - local
2850    3
2875    0
2898    1
2910    1
2930    0
2941    3
2968    3
2980    3
3006    1
3025    3
Name: FTR, dtype: object
1.8
21
14.4
Almeria - visitante
2858    0
2877    3
2897    0
2918    3
2935    3
2942    0
2960    0
2986    0
3009    0
3028    1
Name: FTR, dtype: object
1.0
Levante - local
2851    3
2889    3
2903    0
2922    0
2946    3
2965    0
2987    1
3007    1
3022    1
3045    1
Name: FTR, dtype: object
1.3
10
11.2
Barcelona - visitante
2857    1
2871    3
2893    0
2913    3
2939    3
2958    1
2978    3
2995    3
3010    3
3021    3
Name: FTR, dtype: object
2.3
Getafe - local
2852    0
2871    0
2899    3
2915    1
2923    0
2940    0
2961    3
2981    3
3004    3
3028    1
Name: FTR, dtype: object
1.4
13
13.2
Sociedad - visitante
2850    0
2876    3
2895    3
2914    0
2934    1
2956    3
2964    0
2988    0
3007    1
3027    1
Name: FTR, dtype: object
1.2
Ath Madrid - local
2857    1
2878    3
2883    3
2907    3
2924    3
2944    3
2962    3
2989    3
3009    3
3024    3
Name: FTR, dtype: object
2.8
33
16.1
Sevilla - visitante
2855    1
2875    3
2891    3
2912    3
2936    0
2952    1
2976    1
2991    0
3008    0
3022    1
Name: FTR, dtype: object
1.3
Granada - local
2859    3
2876    0
2891    0
2919    3
2931    0
2953    0
2970    3
2984    0
3003    0
3020    0
Name: FTR, dtype: object
0.9
12
13.6
Osasuna - visitante
2854    3
2873    1
2890    0
2909    3
2926    0
2943    0
2969    3
2989    0
3004    0
3029    0
Name: FTR, dtype: object
1.0
Espanol - local
2853    0
2872    3
2895    0
2912    0
2938    1
2959    3
2972    0
2990    3
3014    1
3026    3
Name: FTR, dtype: object
1.4
13
12.1
Celta - visitante
2861    0
2880    0
2905    0
2927    3
2945    3
2962    0
2981    0
3001    0
3023    3
3050    3
Name: FTR, dtype: object
1.2
Elche - local
2855    1
2879    0
2896    0
2904    3
2920    0
2947    0
2966    3
2985    0
3000    1
3027    1
Name: FTR, dtype: object
0.9
7
9.5
Vallecano - visitante
2852    3
2874    0
2892    1
2916    3
2937    0
2955    3
2975    0
2983    0
3002    0
3024    0
Name: FTR, dtype: object
1.0
Betis - local
2854    0
2877    0
2892    1
2913    0
2932    1
2954    0
2974    3
2994    1
3005    3
3023    0
Name: FTR, dtype: object
0.9
10
17.7
Real Madrid - visitante
2853    3
2870    3
2886    1
2908    3
2925    3
2948    0
2965    3
2985    3
3006    1
3020    3
Name: FTR, dtype: object
2.3
Malaga - local
2868    0
2887    3
2900    0
2921    3
2945    0
2969    0
2986    3
3002    3
3021    0
3054    3
Name: FTR, dtype: object
1.5
15
13.0
Valencia - visitante
2856    0
2883    0
2904    0
2923    3
2941    0
2963    1
2984    3
3005    0
3026    0
3042    0
Name: FTR, dtype: object
0.7
Villarreal - local
2875    0
2898    1
2910    1
2930    0
2941    3
2968    3
2980    3
3006    1
3025    3
3420    0
Name: FTR, dtype: object
1.5
16
13.2
Sociedad - visitante
2876    3
2895    3
2914    0
2934    1
2956    3
2964    0
2988    0
3007    1
3027    1
3046    3
Name: FTR, dtype: object
1.5
Levante - local
2889    3
2903    0
2922    0
2946    3
2965    0
2987    1
3007    1
3022    1
3045    1
3062    0
Name: FTR, dtype: object
1.0
11
11.6
Malaga - visitante
2879    3
2898    1
2919    0
2938    1
2957    0
2979    1
2997    1
3012    1
3038    0
3049    0
Name: FTR, dtype: object
0.8
Getafe - local
2871    0
2899    3
2915    1
2923    0
2940    0
2961    3
2981    3
3004    3
3028    1
3055    0
Name: FTR, dtype: object
1.4
14
13.2
Vallecano - visitante
2874    0
2892    1
2916    3
2937    0
2955    3
2975    0
2983    0
3002    0
3024    0
3055    3
Name: FTR, dtype: object
1.0
Espanol - local
2872    3
2895    0
2912    0
2938    1
2959    3
2972    0
2990    3
3014    1
3026    3
3056    0
Name: FTR, dtype: object
1.4
13
11.6
Real Madrid - visitante
2870    3
2886    1
2908    3
2925    3
2948    0
2965    3
2985    3
3006    1
3020    3
3052    1
Name: FTR, dtype: object
2.1
Betis - local
2877    0
2892    1
2913    0
2932    1
2954    0
2974    3
2994    1
3005    3
3023    0
3057    3
Name: FTR, dtype: object
1.2
13
16.8
Osasuna - visitante
2873    1
2890    0
2909    3
2926    0
2943    0
2969    3
2989    0
3004    0
3029    0
3043    0
Name: FTR, dtype: object
0.7
Elche - local
2879    0
2896    0
2904    3
2920    0
2947    0
2966    3
2985    0
3000    1
3027    1
Name: FTR, dtype: object
0.8888888888888888
6
9.444444444444445
Sevilla - visitante
2875    3
2891    3
2912    3
2936    0
2952    1
2976    1
2991    0
3008    0
3022    1
3053    0
Name: FTR, dtype: object
1.2
Celta - local
2873    1
2897    3
2916    0
2939    0
2950    0
2973    0
2993    1
3017    1
3031    1
3048    3
Name: FTR, dtype: object
1.0
8
13.0
Valencia - visitante
2883    0
2904    0
2923    3
2941    0
2963    1
2984    3
3005    0
3026    0
3042    0
3067    3
Name: FTR, dtype: object
1.0
Ath Madrid - local
2878    3
2883    3
2907    3
2924    3
2944    3
2962    3
2989    3
3009    3
3024    3
3058    1
Name: FTR, dtype: object
2.8
33
16.5
Barcelona - visitante
2871    3
2893    0
2913    3
2939    3
2958    1
2978    3
2995    3
3010    3
3021    3
3056    3
Name: FTR, dtype: object
2.5
Ath Bilbao - local
2874    3
2893    3
2917    3
2933    1
2951    3
2963    1
2982    3
3001    3
3029    3
3059    0
Name: FTR, dtype: object
2.3
17
16.9
Almeria - visitante
2877    3
2897    0
2918    3
2935    3
2942    0
2960    0
2986    0
3009    0
3028    1
Name: FTR, dtype: object
1.1111111111111112
Granada - local
2876    0
2891    0
2919    3
2931    0
2953    0
2970    3
2984    0
3003    0
3020    0
3047    3
Name: FTR, dtype: object
0.9
10
13.7
Valladolid - visitante
2872    0
2894    0
2911    1
2928    0
2949    3
2967    0
2987    1
3000    1
3025    0
3044    0
Name: FTR, dtype: object
0.6
Vallecano - local
2885    0
2901    0
2925    0
2949    0
2964    3
2995    0
3018    0
3030    3
3041    1
3069    0
Name: FTR, dtype: object
0.7
10
17.4
Villarreal - visitante
2888    0
2903    3
2920    3
2951    0
2974    0
2993    1
3016    3
3032    3
3431    0
3447    3
Name: FTR, dtype: object
1.6
Real Madrid - local
2894    3
2914    3
2936    3
2957    3
2977    0
2992    3
3013    3
3034    3
3043    3
3078    3
Name: FTR, dtype: object
2.7
37
21.0
Celta - visitante
2880    0
2905    0
2927    3
2945    3
2962    0
2981    0
3001    0
3023    3
3050    3
3071    0
Name: FTR, dtype: object
1.2
Sociedad - local
2881    3
2905    3
2926    3
2942    3
2976    1
2997    1
3011    0
3039    3
3052    1
3068    1
Name: FTR, dtype: object
1.9
26
16.8
Ath Bilbao - visitante
2882    1
2900    3
2924    0
2940    3
2970    0
2990    0
3013    0
3037    3
3041    1
3061    3
Name: FTR, dtype: object
1.4
Sevilla - local
2882    1
2902    3
2927    0
2943    3
2960    3
2983    3
3012    1
3033    0
3042    3
3065    0
Name: FTR, dtype: object
1.7
21
17.5
Getafe - visitante
2887    0
2907    0
2930    3
2953    3
2972    3
2992    0
3015    0
3039    0
3047    0
3074    0
Name: FTR, dtype: object
0.9
Osasuna - local
2886    1
2918    0
2937    3
2958    1
2971    0
2999    3
3016    0
3035    0
3053    3
3074    3
Name: FTR, dtype: object
1.4
11
13.5
Espanol - visitante
2884    1
2901    3
2929    0
2946    0
2966    0
2980    0
3003    3
3031    1
3048    0
3063    0
Name: FTR, dtype: object
0.8
Barcelona - local
2888    3
2906    3
2929    3
2948    3
2967    3
2988    3
3008    3
3036    3
3049    3
3064    3

Name: FTR, dtype: object
3.0
33
16.8
Elche - visitante
2889    0
2915    1
2933    1
2954    3
2973    3
2999    0
3019    1
3030    0
Name: FTR, dtype: object
1.125
Valladolid - local
2880    3
2909    0
2934    1
2952    1
2979    1
2996    0
3015    3
3037    0
3050    0
3073    3
Name: FTR, dtype: object
1.2
12
12.1
Betis - visitante
2881    0
2902    0
2921    0
2944    0
2961    0
2982    0
3014    1
3034    0
3045    1
3060    0
Name: FTR, dtype: object
0.2
Valencia - local
2870    0
2890    3
2911    1
2935    0
2956    0
2975    3
2991    3
3010    0
3038    3
3051    3
Name: FTR, dtype: object
1.6
17
15.9
Levante - visitante
2878    0
2899    0
2917    0
2932    1
2950    3
2971    3
2998    1
3018    3
3036    0
3059    3
Name: FTR, dtype: object
1.4
Malaga - local
2887    3
2900    0
2921    3
2945    0
2969    0
2986    3
3002    3
3021    0
3054    3
3070    1
Name: FTR, dtype: object
1.6
15
12.7
Ath Madrid - visitante
2896    3
2910    1
2931    3
2959    0
2977    3
2996    3
3011    3
3033    3
3040    3
3079    3
Name: FTR, dtype: object
2.5
Almeria - local
2884    1
2908    0
2928    3
2955    0
2978    0
2998    1
3019    1
3032    0
Name: FTR, dtype: object
0.75
7
10.5
Granada - visitante
2885    3
2906    0
2922    3
2947    3
2968    0
2994    1
3017    1
3035    3
3051    0
3068    1
Name: FTR, dtype: object
1.5
Valencia - local
2890    3
2911    1
2935    0
2956    0
2975    3
2991    3
3010    0
3038    3
3051    3
3085    3
Name: FTR, dtype: object
1.9
19
16.5
Real Madrid - visitante
2886    1
2908    3
2925    3
2948    0
2965    3
2985    3
3006    1
3020    3
3052    1
3075    1
Name: FTR, dtype: object
1.9
Getafe - local
2899    3
2915    1
2923    0
2940    0
2961    3
2981    3
3004    3
3028    1
3055    0
3067    0
Name: FTR, dtype: object
1.4
12
12.4
Barcelona - visitante
2893    0
2913    3
2939    3
2958    1
2978    3
2995    3
3010    3
3021    3
3056    3
3072    3
Name: FTR, dtype: object
2.5
Espanol - local
2895    0
2912    0
2938    1
2959    3
2972    0
2990    3
3014    1
3026    3
3056    0
3075    1
Name: FTR, dtype: object
1.2
10
11.0
Valladolid - visitante
2894    0
2911    1
2928    0
2949    3
2967    0
2987    1
3000    1
3025    0
3044    0
3064    0
Name: FTR, dtype: object
0.6
Celta - local
2897    3
2916    0
2939    0
2950    0
2973    0
2993    1
3017    1
3031    1
3048    3
3079    0
Name: FTR, dtype: object
0.9
8
12.9
Osasuna - visitante
2890    0
2909    3
2926    0
2943    0
2969    3
2989    0
3004    0
3029    0
3043    0
3066    0
Name: FTR, dtype: object
0.6
Ath Bilbao - local
2893    3
2917    3
2933    1
2951    3
2963    1
2982    3
3001    3
3029    3
3059    0
3076    3
Name: FTR, dtype: object
2.3
17
15.4
Vallecano - visitante
2892    1
2916    3
2937    0
2955    3
2975    0
2983    0
3002    0
3024    0
3055    3
3062    3
Name: FTR, dtype: object
1.3
Villarreal - local
2898    1
2910    1
2930    0
2941    3
2968    3
2980    3
3006    1
3025    3
3420    0
3455    1
Name: FTR, dtype: object
1.6
16
13.9
Sevilla - visitante
2891    3
2912    3
2936    0
2952    1
2976    1
2991    0
3008    0
3022    1
3053    0
3070    1
Name: FTR, dtype: object
1.0
Granada - local
2891    0
2919    3
2931    0
2953    0
2970    3
2984    0
3003    0
3020    0
3047    3
3066    3
Name: FTR, dtype: object
1.2
12
12.5
Sociedad - visitante
2895    3
2914    0
2934    1
2956    3
2964    0
2988    0
3007    1
3027    1
3046    3
3065    3
Name: FTR, dtype: object
1.5
Betis - local
2892    1
2913    0
2932    1
2954    0
2974    3
2994    1
3005    3
3023    0
3057    3
3071    3
Name: FTR, dtype: object
1.5
14
15.9
Almeria - visitante
2897    0
2918    3
2935    3
2942    0
2960    0
2986    0
3009    0
3028    1
Name: FTR, dtype: object
0.875
Ath Madrid - local
2883    3
2907    3
2924    3
2944    3
2962    3
2989    3
3009    3
3024    3
3058    1
3072    0
Name: FTR, dtype: object
2.5
31
16.1
Levante - visitante
2899    0
2917    0
2932    1
2950    3
2971    3
2998    1
3018    3
3036    0
3059    3
3083    1
Name: FTR, dtype: object
1.5
Elche - local
2896    0
2904    3
2920    0
2947    0
2966    3
2985    0
3000    1
3027    1
Name: FTR, dtype: object
1.0
6
9.625
Malaga - visitante
2898    1
2919    0
2938    1
2957    0
2979    1
2997    1
3012    1
3038    0
3049    0
3078    0
Name: FTR, dtype: object
0.5
Valladolid - local
2909    0
2934    1
2952    1
2979    1
2996    0
3015    3
3037    0
3050    0
3073    3
3091    1
Name: FTR, dtype: object
1.0
10
12.2
Celta - visitante
2905    0
2927    3
2945    3
2962    0
2981    0
3001    0
3023    3
3050    3
3071    0
3096    3
Name: FTR, dtype: object
1.5
Sociedad - local
2905    3
2926    3
2942    3
2976    1
2997    1
3011    0
3039    3
3052    1
3068    1
3092    3
Name: FTR, dtype: object
1.9
25
16.7
Betis - visitante
2902    0
2921    0
2944    0
2961    0
2982    0
3014    1
3034    0
3045    1
3060    0
3084    0
Name: FTR, dtype: object
0.2
Sevilla - local
2902    3
2927    0
2943    3
2960    3
2983    3
3012    1
3033    0
3042    3
3065    0
3082    3
Name: FTR, dtype: object
1.9
23
17.7
Ath Bilbao - visitante
2900    3
2924    0
2940    3
2970    0
2990    0
3013    0
3037    3
3041    1
3061    3
3089    1
Name: FTR, dtype: object
1.4
Ath Madrid - local
2907    3
2924    3
2944    3
2962    3
2989    3
3009    3
3024    3
3058    1
3072    0
3097    0
Name: FTR, dtype: object
2.2
29
15.8
Valencia - visitante
2904    0
2923    3
2941    0
2963    1
2984    3
3005    0
3026    0
3042    0
3067    3
3069    3
Name: FTR, dtype: object
1.3
Almeria - local
2908    0
2928    3
2955    0
2978    0
2998    1
3019    1
3032    0
Name: FTR, dtype: object
0.7142857142857143
7
10.571428571428571
Espanol - visitante
2901    3
2929    0
2946    0
2966    0
2980    0
3003    3
3031    1
3048    0
3063    0
3082    0
Name: FTR, dtype: object
0.7
Vallecano - local
2901    0
2925    0
2949    0
2964    3
2995    0
3018    0
3030    3
3041    1
3069    0
3099    1
Name: FTR, dtype: object
0.8
12
16.8
Granada - visitante
2906    0
2922    3
2947    3
2968    0
2994    1
3017    1
3035    3
3051    0
3068    1
3094    3
Name: FTR, dtype: object
1.5
Osasuna - local
2918    0
2937    3
2958    1
2971    0
2999    3
3016    0
3035    0
3053    3
3074    3
3102    1
Name: FTR, dtype: object
1.4
9
13.8
Real Madrid - visitante
2908    3
2925    3
2948    0
2965    3
2985    3
3006    1
3020    3
3052    1
3075    1
3097    3
Name: FTR, dtype: object
2.1
Malaga - local
2900    0
2921    3
2945    0
2969    0
2986    3
3002    3
3021    0
3054    3
3070    1
3093    3
Name: FTR, dtype: object
1.6
16
11.8
Getafe - visitante
2907    0
2930    3
2953    3
2972    3
2992    0
3015    0
3039    0
3047    0
3074    0
3093    0
Name: FTR, dtype: object
0.9
Barcelona - local
2906    3
2929    3
2948    3
2967    3
2988    3
3008    3
3036    3
3049    3
3064    3
3084    3
Name: FTR, dtype: object
3.0
35
17.4
Villarreal - visitante
2903    3
2920    3
2951    0
2974    0
2993    1
3016    3
3032    3
3431    0
3447    3
3462    1
Name: FTR, dtype: object
1.7
Levante - local
2903    0
2922    0
2946    3
2965    0
2987    1
3007    1
3022    1
3045    1
3062    0
3077    1
Name: FTR, dtype: object
0.8
9
11.8
Elche - visitante
2915    1
2933    1
2954    3
2973    3
2999    0
3019    1
3030    0
Name: FTR, dtype: object
1.2857142857142858
Valencia - local
2911    1
2935    0
2956    0
2975    3
2991    3
3010    0
3038    3
3051    3
3085    3
3105    3
Name: FTR, dtype: object
1.9
21
15.5
Osasuna - visitante
2909    3
2926    0
2943    0
2969    3
2989    0
3004    0
3029    0
3043    0
3066    0
3085    0
Name: FTR, dtype: object
0.6
Granada - local
2919    3
2931    0
2953    0
2970    3
2984    0
3003    0
3020    0
3047    3
3066    3
3088    3
Name: FTR, dtype: object
1.5
12
12.2
Sevilla - visitante
2912    3
2936    0
2952    1
2976    1
2991    0
3008    0
3022    1
3053    0
3070    1
3091    1
Name: FTR, dtype: object
0.8
Betis - local
2913    0
2932    1
2954    0
2974    3
2994    1
3005    3
3023    0
3057    3
3071    3
3090    1
Name: FTR, dtype: object
1.5
13
16.7
Vallecano - visitante
2916    3
2937    0
2955    3
2975    0
2983    0
3002    0
3024    0
3055    3
3062    3
3081    0
Name: FTR, dtype: object
1.2
Ath Bilbao - local
2917    3
2933    1
2951    3
2963    1
2982    3
3001    3
3029    3
3059    0
3076    3
3098    1
Name: FTR, dtype: object
2.1
18
14.6
Barcelona - visitante
2913    3
2939    3
2958    1
2978    3
2995    3
3010    3
3021    3
3056    3
3072    3
3098    1
Name: FTR, dtype: object
2.6
Real Madrid - local
2914    3
2936    3
2957    3
2977    0
2992    3
3013    3
3034    3
3043    3
3078    3
3086    3
Name: FTR, dtype: object
2.7
37
21.1
Valladolid - visitante
2911    1
2928    0
2949    3
2967    0
2987    1
3000    1
3025    0
3044    0
3064    0
3086    0
Name: FTR, dtype: object
0.6
Espanol - local
2912    0
2938    1
2959    3
2972    0
2990    3
3014    1
3026    3
3056    0
3075    1
3094    0
Name: FTR, dtype: object
1.2
9
10.6
Sociedad - visitante
2914    0
2934    1
2956    3
2964    0
2988    0
3007    1
3027    1
3046    3
3065    3
3080    0
Name: FTR, dtype: object
1.2
Elche - local
2904    3
2920    0
2947    0
2966    3
2985    0
3000    1
3027    1
Name: FTR, dtype: object
1.1428571428571428
6
9.571428571428571
Ath Madrid - visitante
2910    1
2931    3
2959    0
2977    3
2996    3
3011    3
3033    3
3040    3
3079    3
3087    1
Name: FTR, dtype: object
2.3
Celta - local
2916    0
2939    0
2950    0
2973    0
2993    1
3017    1
3031    1
3048    3
3079    0
3089    1
Name: FTR, dtype: object
0.7
6
13.3
Almeria - visitante
2918    3
2935    3
2942    0
2960    0
2986    0
3009    0
3028    1
Name: FTR, dtype: object
1.0
Villarreal - local
2910    1
2930    0
2941    3
2968    3
2980    3
3006    1
3025    3
3420    0
3455    1
3472    1
Name: FTR, dtype: object
1.6
16
15.1
Malaga - visitante
2919    0
2938    1
2957    0
2979    1
2997    1
3012    1
3038    0
3049    0
3078    0
3088    0
Name: FTR, dtype: object
0.4
Getafe - local
2915    1
2923    0
2940    0
2961    3
2981    3
3004    3
3028    1
3055    0
3067    0
3080    3
Name: FTR, dtype: object
1.4
13
12.4
Levante - visitante
2917    0
2932    1
2950    3
2971    3
2998    1
3018    3
3036    0
3059    3
3083    1
3108    0
Name: FTR, dtype: object
1.5
Malaga - local
2921    3
2945    0
2969    0
2986    3
3002    3
3021    0
3054    3
3070    1
3093    3
3116    3

Name: FTR, dtype: object
1.9
16
12.6
Ath Bilbao - visitante
2924    0
2940    3
2970    0
2990    0
3013    0
3037    3
3041    1
3061    3
3089    1
3103    1
Name: FTR, dtype: object
1.2
Vallecano - local
2925    0
2949    0
2964    3
2995    0
3018    0
3030    3
3041    1
3069    0
3099    1
3112    0
Name: FTR, dtype: object
0.8
11
16.3
Espanol - visitante
2929    0
2946    0
2966    0
2980    0
3003    3
3031    1
3048    0
3063    0
3082    0
3104    3
Name: FTR, dtype: object
0.7
Sevilla - local
2927    0
2943    3
2960    3
2983    3
3012    1
3033    0
3042    3
3065    0
3082    3
3101    0
Name: FTR, dtype: object
1.6
19
17.4
Betis - visitante
2921    0
2944    0
2961    0
2982    0
3014    1
3034    0
3045    1
3060    0
3084    0
3106    0
Name: FTR, dtype: object
0.2
Levante - local
2922    0
2946    3
2965    0
2987    1
3007    1
3022    1
3045    1
3062    0
3077    1
3096    0
Name: FTR, dtype: object
0.8
9
12.4
Villarreal - visitante
2920    3
2951    0
2974    0
2993    1
3016    3
3032    3
3431    0
3447    3
3462    1
3499    0
Name: FTR, dtype: object
1.4
Elche - local
2920    0
2947    0
2966    3
2985    0
3000    1
3027    1
Name: FTR, dtype: object
0.8333333333333334
4
9.666666666666666
Valencia - visitante
2923    3
2941    0
2963    1
2984    3
3005    0
3026    0
3042    0
3067    3
3069    3
3092    0
Name: FTR, dtype: object
1.3
Sociedad - local
2926    3
2942    3
2976    1
2997    1
3011    0
3039    3
3052    1
3068    1
3092    3
3125    3
Name: FTR, dtype: object
1.9
25
15.1
Celta - visitante
2927    3
2945    3
2962    0
2981    0
3001    0
3023    3
3050    3
3071    0
3096    3
3110    0
Name: FTR, dtype: object
1.5
Barcelona - local
2929    3
2948    3
2967    3
2988    3
3008    3
3036    3
3049    3
3064    3
3084    3
3108    3
Name: FTR, dtype: object
3.0
32
17.9
Granada - visitante
2922    3
2947    3
2968    0
2994    1
3017    1
3035    3
3051    0
3068    1
3094    3
3113    0
Name: FTR, dtype: object
1.5
Ath Madrid - local
2924    3
2944    3
2962    3
2989    3
3009    3
3024    3
3058    1
3072    0
3097    0
3113    3
Name: FTR, dtype: object
2.2
27
15.0
Getafe - visitante
2930    3
2953    3
2972    3
2992    0
3015    0
3039    0
3047    0
3074    0
3093    0
3115    0
Name: FTR, dtype: object
0.9
Almeria - local
2928    3
2955    0
2978    0
2998    1
3019    1
3032    0
Name: FTR, dtype: object
0.8333333333333334
7
10.333333333333334
Real Madrid - visitante
2925    3
2948    0
2965    3
2985    3
3006    1
3020    3
3052    1
3075    1
3097    3
3114    3
Name: FTR, dtype: object
2.1
Valladolid - local
2934    1
2952    1
2979    1
2996    0
3015    3
3037    0
3050    0
3073    3
3091    1
3115    3
Name: FTR, dtype: object
1.3
12
13.7
Osasuna - visitante
2926    0
2943    0
2969    3
2989    0
3004    0
3029    0
3043    0
3066    0
3085    0
3099    1
Name: FTR, dtype: object
0.4
Villarreal - local
2930    0
2941    3
2968    3
2980    3
3006    1
3025    3
3420    0
3455    1
3472    1
3480    3
Name: FTR, dtype: object
1.8
17
14.5
Ath Madrid - visitante
2931    3
2959    0
2977    3
2996    3
3011    3
3033    3
3040    3
3079    3
3087    1
3101    3
Name: FTR, dtype: object
2.5
Valencia - local
2935    0
2956    0
2975    3
2991    3
3010    0
3038    3
3051    3
3085    3
3105    3
3121    3
Name: FTR, dtype: object
2.1
21
16.3
Valladolid - visitante
2928    0
2949    3
2967    0
2987    1
3000    1
3025    0
3044    0
3064    0
3086    0
3107    1
Name: FTR, dtype: object
0.6
Espanol - local
2938    1
2959    3
2972    0
2990    3
3014    1
3026    3
3056    0
3075    1
3094    0
3118    1
Name: FTR, dtype: object
1.3
11
10.8
Sevilla - visitante
2936    0
2952    1
2976    1
2991    0
3008    0
3022    1
3053    0
3070    1
3091    1
3119    1
Name: FTR, dtype: object
0.6
Betis - local
2932    1
2954    0
2974    3
2994    1
3005    3
3023    0
3057    3
3071    3
3090    1
3119    1
Name: FTR, dtype: object
1.6
15
17.7
Barcelona - visitante
2939    3
2958    1
2978    3
2995    3
3010    3
3021    3
3056    3
3072    3
3098    1
3111    3
Name: FTR, dtype: object
2.6
Real Madrid - local
2936    3
2957    3
2977    0
2992    3
3013    3
3034    3
3043    3
3078    3
3086    3
3106    3
Name: FTR, dtype: object
2.7
35
21.4
Sociedad - visitante
2934    1
2956    3
2964    0
2988    0
3007    1
3027    1
3046    3
3065    3
3080    0
3102    1
Name: FTR, dtype: object
1.3
Getafe - local
2923    0
2940    0
2961    3
2981    3
3004    3
3028    1
3055    0
3067    0
3080    3
3104    0
Name: FTR, dtype: object
1.3
12
12.1
Elche - visitante
2933    1
2954    3
2973    3
2999    0
3019    1
3030    0
Name: FTR, dtype: object
1.3333333333333333
Celta - local
2939    0
2950    0
2973    0
2993    1
3017    1
3031    1
3048    3
3079    0
3089    1
3100    3
Name: FTR, dtype: object
1.0
8
13.3
Vallecano - visitante
2937    0
2955    3
2975    0
2983    0
3002    0
3024    0
3055    3
3062    3
3081    0
3109    1
Name: FTR, dtype: object
1.0
Ath Bilbao - local
2933    1
2951    3
2963    1
2982    3
3001    3
3029    3
3059    0
3076    3
3098    1
3114    0
Name: FTR, dtype: object
1.8
16
13.6
Levante - visitante
2932    1
2950    3
2971    3
2998    1
3018    3
3036    0
3059    3
3083    1
3108    0
3126    0
Name: FTR, dtype: object
1.5
Osasuna - local
2937    3
2958    1
2971    0
2999    3
3016    0
3035    0
3053    3
3074    3
3102    1
3122    0
Name: FTR, dtype: object
1.4
9
13.1
Almeria - visitante
2935    3
2942    0
2960    0
2986    0
3009    0
3028    1
Name: FTR, dtype: object
0.6666666666666666
Granada - local
2931    0
2953    0
2970    3
2984    0
3003    0
3020    0
3047    3
3066    3
3088    3
3107    1
Name: FTR, dtype: object
1.3
10
13.4
Malaga - visitante
2938    1
2957    0
2979    1
2997    1
3012    1
3038    0
3049    0
3078    0
3088    0
3105    0
Name: FTR, dtype: object
0.4
Elche - local
2947    0
2966    3
2985    0
3000    1
3027    1
Name: FTR, dtype: object
1.0
4
10.6
Villarreal - visitante
2951    0
2974    0
2993    1
3016    3
3032    3
3431    0
3447    3
3462    1
3499    0
3512    3
Name: FTR, dtype: object
1.4
Malaga - local
2945    0
2969    0
2986    3
3002    3
3021    0
3054    3
3070    1
3093    3
3116    3
3142    0
Name: FTR, dtype: object
1.6
13
13.1
Betis - visitante
2944    0
2961    0
2982    0
3014    1
3034    0
3045    1
3060    0
3084    0
3106    0
3129    3
Name: FTR, dtype: object
0.5
Levante - local
2946    3
2965    0
2987    1
3007    1
3022    1
3045    1
3062    0
3077    1
3096    0
3117    0
Name: FTR, dtype: object
0.8
9
13.4
Granada - visitante
2947    3
2968    0
2994    1
3017    1
3035    3
3051    0
3068    1
3094    3
3113    0
3131    0
Name: FTR, dtype: object
1.2
Getafe - local
2940    0
2961    3
2981    3
3004    3
3028    1
3055    0
3067    0
3080    3
3104    0
3123    1
Name: FTR, dtype: object
1.4
12
12.4
Valencia - visitante
2941    0
2963    1
2984    3
3005    0
3026    0
3042    0
3067    3
3069    3
3092    0
3118    1
Name: FTR, dtype: object
1.1
Ath Madrid - local
2944    3
2962    3
2989    3
3009    3
3024    3
3058    1
3072    0
3097    0
3113    3
3135    1
Name: FTR, dtype: object
2.0
26
14.4
Ath Bilbao - visitante
2940    3
2970    0
2990    0
3013    0
3037    3
3041    1
3061    3
3089    1
3103    1
3120    0
Name: FTR, dtype: object
1.2
Vallecano - local
2949    0
2964    3
2995    0
3018    0
3030    3
3041    1
3069    0
3099    1
3112    0
3137    0
Name: FTR, dtype: object
0.8
10
15.5
Real Madrid - visitante
2948    0
2965    3
2985    3
3006    1
3020    3
3052    1
3075    1
3097    3
3114    3
3136    1
Name: FTR, dtype: object
1.9
Sociedad - local
2942    3
2976    1
2997    1
3011    0
3039    3
3052    1
3068    1
3092    3
3125    3
3146    3
Name: FTR, dtype: object
1.9
24
15.4
Osasuna - visitante
2943    0
2969    3
2989    0
3004    0
3029    0
3043    0
3066    0
3085    0
3099    1
3116    0
Name: FTR, dtype: object
0.4
Sevilla - local
2943    3
2960    3
2983    3
3012    1
3033    0
3042    3
3065    0
3082    3
3101    0
3120    3
Name: FTR, dtype: object
1.9
21
17.5
Celta - visitante
2945    3
2962    0
2981    0
3001    0
3023    3
3050    3
3071    0
3096    3
3110    0
3149    0
Name: FTR, dtype: object
1.2
Almeria - local
2955    0
2978    0
2998    1
3019    1
3032    0
Name: FTR, dtype: object
0.4
6
9.6
Valladolid - visitante
2949    3
2967    0
2987    1
3000    1
3025    0
3044    0
3064    0
3086    0
3107    1
3121    0
Name: FTR, dtype: object
0.6
Barcelona - local
2948    3
2967    3
2988    3
3008    3
3036    3
3049    3
3064    3
3084    3
3108    3
3128    3
Name: FTR, dtype: object
3.0
36
18.2
Espanol - visitante
2946    0
2966    0
2980    0
3003    3
3031    1
3048    0
3063    0
3082    0
3104    3
3122    3
Name: FTR, dtype: object
1.0
Villarreal - local
2941    3
2968    3
2980    3
3006    1
3025    3
3420    0
3455    1
3472    1
3480    3
3501    1
Name: FTR, dtype: object
1.9
17
14.2
Getafe - visitante
2953    3
2972    3
2992    0
3015    0
3039    0
3047    0
3074    0
3093    0
3115    0
3130    1
Name: FTR, dtype: object
0.7
Granada - local
2953    0
2970    3
2984    0
3003    0
3020    0
3047    3
3066    3
3088    3
3107    1
3129    0
Name: FTR, dtype: object
1.3
10
14.7
Ath Madrid - visitante
2959    0
2977    3
2996    3
3011    3
3033    3
3040    3
3079    3
3087    1
3101    3
3123    1
Name: FTR, dtype: object
2.3
Betis - local
2954    0
2974    3
2994    1
3005    3
3023    0
3057    3
3071    3
3090    1
3119    1
3130    1
Name: FTR, dtype: object
1.6
15
16.9
Levante - visitante
2950    3
2971    3
2998    1
3018    3
3036    0
3059    3
3083    1
3108    0
3126    0
3143    1
Name: FTR, dtype: object
1.5
Ath Bilbao - local
2951    3
2963    1
2982    3
3001    3
3029    3
3059    0
3076    3
3098    1
3114    0
3131    3
Name: FTR, dtype: object
2.0
15
13.3
Elche - visitante
2954    3
2973    3
2999    0
3019    1
3030    0
Name: FTR, dtype: object
1.4
Valladolid - local
2952    1
2979    1
2996    0
3015    3
3037    0
3050    0
3073    3
3091    1
3115    3
3132    0
Name: FTR, dtype: object
1.2
11
12.8
Sociedad - visitante
2956    3
2964    0
2988    0
3007    1
3027    1
3046    3
3065    3
3080    0
3102    1
3112    3
Name: FTR, dtype: object
1.5
Valencia - local
2956    0
2975    3
2991    3
3010    0
3038    3
3051    3
3085    3
3105    3
3121    3
3145    3
Name: FTR, dtype: object
2.4
23
15.9
Almeria - visitante
2942    0
2960    0
2986    0
3009    0
3028    1
Name: FTR, dtype: object
0.2
Real Madrid - local
2957    3
2977    0
2992    3
3013    3
3034    3
3043    3
3078    3
3086    3
3106    3
3126    3

Name: FTR, dtype: object
2.7
33
23.2
Sevilla - visitante
2952    1
2976    1
2991    0
3008    0
3022    1
3053    0
3070    1
3091    1
3119    1
3138    0
Name: FTR, dtype: object
0.6
Osasuna - local
2958    1
2971    0
2999    3
3016    0
3035    0
3053    3
3074    3
3102    1
3122    0
3141    0
Name: FTR, dtype: object
1.1
6
14.0
Vallecano - visitante
2955    3
2975    0
2983    0
3002    0
3024    0
3055    3
3062    3
3081    0
3109    1
3124    3
Name: FTR, dtype: object
1.3
Espanol - local
2959    3
2972    0
2990    3
3014    1
3026    3
3056    0
3075    1
3094    0
3118    1
3134    1
Name: FTR, dtype: object
1.3
13
10.3
Malaga - visitante
2957    0
2979    1
2997    1
3012    1
3038    0
3049    0
3078    0
3088    0
3105    0
3125    0
Name: FTR, dtype: object
0.3
Celta - local
2950    0
2973    0
2993    1
3017    1
3031    1
3048    3
3079    0
3089    1
3100    3
3124    0
Name: FTR, dtype: object
1.0
8
13.5
Barcelona - visitante
2958    1
2978    3
2995    3
3010    3
3021    3
3056    3
3072    3
3098    1
3111    3
3139    1
Name: FTR, dtype: object
2.4
Getafe - local
2961    3
2981    3
3004    3
3028    1
3055    0
3067    0
3080    3
3104    0
3123    1
3148    3
Name: FTR, dtype: object
1.7
13
12.9
Ath Bilbao - visitante
2970    0
2990    0
3013    0
3037    3
3041    1
3061    3
3089    1
3103    1
3120    0
3148    0
Name: FTR, dtype: object
0.9
Villarreal - local
2968    3
2980    3
3006    1
3025    3
3420    0
3455    1
3472    1
3480    3
3501    1
3523    1
Name: FTR, dtype: object
1.7
14
13.7
Valencia - visitante
2963    1
2984    3
3005    0
3026    0
3042    0
3067    3
3069    3
3092    0
3118    1
3135    1
Name: FTR, dtype: object
1.2
Sociedad - local
2976    1
2997    1
3011    0
3039    3
3052    1
3068    1
3092    3
3125    3
3146    3
3161    1
Name: FTR, dtype: object
1.7
24
15.8
Almeria - visitante
2960    0
2986    0
3009    0
3028    1
Name: FTR, dtype: object
0.25
Sevilla - local
2960    3
2983    3
3012    1
3033    0
3042    3
3065    0
3082    3
3101    0
3120    3
3140    3
Name: FTR, dtype: object
1.9
23
16.9
Osasuna - visitante
2969    3
2989    0
3004    0
3029    0
3043    0
3066    0
3085    0
3099    1
3116    0
3132    3
Name: FTR, dtype: object
0.7
Ath Madrid - local
2962    3
2989    3
3009    3
3024    3
3058    1
3072    0
3097    0
3113    3
3135    1
3153    0
Name: FTR, dtype: object
1.7
21
14.9
Betis - visitante
2961    0
2982    0
3014    1
3034    0
3045    1
3060    0
3084    0
3106    0
3129    3
3145    0
Name: FTR, dtype: object
0.5
Malaga - local
2969    0
2986    3
3002    3
3021    0
3054    3
3070    1
3093    3
3116    3
3142    0
3162    1
Name: FTR, dtype: object
1.7
13
13.0
Celta - visitante
2962    0
2981    0
3001    0
3023    3
3050    3
3071    0
3096    3
3110    0
3149    0
3160    0
Name: FTR, dtype: object
0.9
Levante - local
2965    0
2987    1
3007    1
3022    1
3045    1
3062    0
3077    1
3096    0
3117    0
3138    3
Name: FTR, dtype: object
0.8
7
14.5
Espanol - visitante
2966    0
2980    0
3003    3
3031    1
3048    0
3063    0
3082    0
3104    3
3122    3
3142    3
Name: FTR, dtype: object
1.3
Elche - local
2966    3
2985    0
3000    1
3027    1
Name: FTR, dtype: object
1.25
4
11.25
Granada - visitante
2968    0
2994    1
3017    1
3035    3
3051    0
3068    1
3094    3
3113    0
3131    0
3150    1
Name: FTR, dtype: object
1.0
Barcelona - local
2967    3
2988    3
3008    3
3036    3
3049    3
3064    3
3084    3
3108    3
3128    3
3144    3
Name: FTR, dtype: object
3.0
37
18.9
Real Madrid - visitante
2965    3
2985    3
3006    1
3020    3
3052    1
3075    1
3097    3
3114    3
3136    1
3152    3
Name: FTR, dtype: object
2.2
Vallecano - local
2964    3
2995    0
3018    0
3030    3
3041    1
3069    0
3099    1
3112    0
3137    0
3155    3
Name: FTR, dtype: object
1.1
12
15.4
Valladolid - visitante
2967    0
2987    1
3000    1
3025    0
3044    0
3064    0
3086    0
3107    1
3121    0
3146    0
Name: FTR, dtype: object
0.3
Celta - local
2973    0
2993    1
3017    1
3031    1
3048    3
3079    0
3089    1
3100    3
3124    0
3139    1
Name: FTR, dtype: object
1.1
10
12.8
Levante - visitante
2971    3
2998    1
3018    3
3036    0
3059    3
3083    1
3108    0
3126    0
3143    1
3165    1
Name: FTR, dtype: object
1.3
Ath Bilbao - local
2963    1
2982    3
3001    3
3029    3
3059    0
3076    3
3098    1
3114    0
3131    3
3154    3
Name: FTR, dtype: object
2.0
14
12.3
Villarreal - visitante
2974    0
2993    1
3016    3
3032    3
3431    0
3447    3
3462    1
3499    0
3512    3
3533    0
Name: FTR, dtype: object
1.4
Valladolid - local
2979    1
2996    0
3015    3
3037    0
3050    0
3073    3
3091    1
3115    3
3132    0
3156    1
Name: FTR, dtype: object
1.2
10
12.6
Sevilla - visitante
2976    1
2991    0
3008    0
3022    1
3053    0
3070    1
3091    1
3119    1
3138    0
3157    0
Name: FTR, dtype: object
0.5
Granada - local
2970    3
2984    0
3003    0
3020    0
3047    3
3066    3
3088    3
3107    1
3129    0
3143    1
Name: FTR, dtype: object
1.4
11
14.9
Getafe - visitante
2972    3
2992    0
3015    0
3039    0
3047    0
3074    0
3093    0
3115    0
3130    1
3151    1
Name: FTR, dtype: object
0.5
Betis - local
2974    3
2994    1
3005    3
3023    0
3057    3
3071    3
3090    1
3119    1
3130    1
3159    3
Name: FTR, dtype: object
1.9
16
16.3
Elche - visitante
2973    3
2999    0
3019    1
3030    0
Name: FTR, dtype: object
1.0
Almeria - local
2978    0
2998    1
3019    1
3032    0
Name: FTR, dtype: object
0.5
6
10.5
Vallecano - visitante
2975    0
2983    0
3002    0
3024    0
3055    3
3062    3
3081    0
3109    1
3124    3
3144    0
Name: FTR, dtype: object
1.0
Valencia - local
2975    3
2991    3
3010    0
3038    3
3051    3
3085    3
3105    3
3121    3
3145    3
3165    1
Name: FTR, dtype: object
2.5
24
16.2
Sociedad - visitante
2964    0
2988    0
3007    1
3027    1
3046    3
3065    3
3080    0
3102    1
3112    3
3134    1
Name: FTR, dtype: object
1.3
Real Madrid - local
2977    0
2992    3
3013    3
3034    3
3043    3
3078    3
3086    3
3106    3
3126    3
3147    3
Name: FTR, dtype: object
2.7
36
23.4
Malaga - visitante
2979    1
2997    1
3012    1
3038    0
3049    0
3078    0
3088    0
3105    0
3125    0
3137    3
Name: FTR, dtype: object
0.6
Osasuna - local
2971    0
2999    3
3016    0
3035    0
3053    3
3074    3
3102    1
3122    0
3141    0
3167    0
Name: FTR, dtype: object
1.0
6
15.4
Barcelona - visitante
2978    3
2995    3
3010    3
3021    3
3056    3
3072    3
3098    1
3111    3
3139    1
3166    0
Name: FTR, dtype: object
2.3
Espanol - local
2972    0
2990    3
3014    1
3026    3
3056    0
3075    1
3094    0
3118    1
3134    1
3164    1
Name: FTR, dtype: object
1.1
12
10.5
Ath Madrid - visitante
2977    3
2996    3
3011    3
3033    3
3040    3
3079    3
3087    1
3101    3
3123    1
3141    3
Name: FTR, dtype: object
2.6
Sevilla - local
2983    3
3012    1
3033    0
3042    3
3065    0
3082    3
3101    0
3120    3
3140    3
3160    3
Name: FTR, dtype: object
1.9
25
15.9
Almeria - visitante
2986    0
3009    0
3028    1
Name: FTR, dtype: object
0.3333333333333333
Getafe - local
2981    3
3004    3
3028    1
3055    0
3067    0
3080    3
3104    0
3123    1
3148    3
3169    3
Name: FTR, dtype: object
1.7
12
12.6
Betis - visitante
2982    0
3014    1
3034    0
3045    1
3060    0
3084    0
3106    0
3129    3
3145    0
3161    1
Name: FTR, dtype: object
0.6
Ath Madrid - local
2989    3
3009    3
3024    3
3058    1
3072    0
3097    0
3113    3
3135    1
3153    0
3174    3
Name: FTR, dtype: object
1.7
20
13.6
Celta - visitante
2981    0
3001    0
3023    3
3050    3
3071    0
3096    3
3110    0
3149    0
3160    0
3188    0
Name: FTR, dtype: object
0.9
Ath Bilbao - local
2982    3
3001    3
3029    3
3059    0
3076    3
3098    1
3114    0
3131    3
3154    3
3179    0
Name: FTR, dtype: object
1.9
14
12.4
Valencia - visitante
2984    3
3005    0
3026    0
3042    0
3067    3
3069    3
3092    0
3118    1
3135    1
3154    0
Name: FTR, dtype: object
1.1
Vallecano - local
2995    0
3018    0
3030    3
3041    1
3069    0
3099    1
3112    0
3137    0
3155    3
3171    0
Name: FTR, dtype: object
0.8
12
16.1
Sociedad - visitante
2988    0
3007    1
3027    1
3046    3
3065    3
3080    0
3102    1
3112    3
3134    1
3153    3
Name: FTR, dtype: object
1.6
Levante - local
2987    1
3007    1
3022    1
3045    1
3062    0
3077    1
3096    0
3117    0
3138    3
3151    1
Name: FTR, dtype: object
0.9
5
14.8
Real Madrid - visitante
2985    3
3006    1
3020    3
3052    1
3075    1
3097    3
3114    3
3136    1
3152    3
3177    3
Name: FTR, dtype: object
2.2
Elche - local
2985    0
3000    1
3027    1
Name: FTR, dtype: object
0.6666666666666666
2
11.0
Espanol - visitante
2980    0
3003    3
3031    1
3048    0
3063    0
3082    0
3104    3
3122    3
3142    3
3155    0
Name: FTR, dtype: object
1.3
Barcelona - local
2988    3
3008    3
3036    3
3049    3
3064    3
3084    3
3108    3
3128    3
3144    3
3158    3
Name: FTR, dtype: object
3.0
35
18.0
Valladolid - visitante
2987    1
3000    1
3025    0
3044    0
3064    0
3086    0
3107    1
3121    0
3146    0
3164    1
Name: FTR, dtype: object
0.4
Villarreal - local
2980    3
3006    1
3025    3
3420    0
3455    1
3472    1
3480    3
3501    1
3523    1
3540    0
Name: FTR, dtype: object
1.4
12
13.7
Granada - visitante
2994    1
3017    1
3035    3
3051    0
3068    1
3094    3
3113    0
3131    0
3150    1
3172    0
Name: FTR, dtype: object
1.0
Malaga - local
2986    3
3002    3
3021    0
3054    3
3070    1
3093    3
3116    3
3142    0
3162    1
3186    3
Name: FTR, dtype: object
2.0
14
12.7
Osasuna - visitante
2989    0
3004    0
3029    0
3043    0
3066    0
3085    0
3099    1
3116    0
3132    3
3159    0
Name: FTR, dtype: object
0.4
Granada - local
2984    0
3003    0
3020    0
3047    3
3066    3
3088    3
3107    1
3129    0
3143    1
3163    0
Name: FTR, dtype: object
1.1
10
14.6
Ath Bilbao - visitante
2990    0
3013    0
3037    3
3041    1
3061    3
3089    1
3103    1
3120    0
3148    0
3167    3
Name: FTR, dtype: object
1.2
Osasuna - local
2999    3
3016    0
3035    0
3053    3
3074    3
3102    1
3122    0
3141    0
3167    0
3185    3
Name: FTR, dtype: object
1.3
7
14.2
Levante - visitante
2998    1
3018    3
3036    0
3059    3
3083    1
3108    0
3126    0
3143    1
3165    1
3182    1
Name: FTR, dtype: object
1.1
Espanol - local
2990    3
3014    1
3026    3
3056    0
3075    1
3094    0
3118    1
3134    1
3164    1
3184    3

Name: FTR, dtype: object
1.4
13
9.7
Getafe - visitante
2992    0
3015    0
3039    0
3047    0
3074    0
3093    0
3115    0
3130    1
3151    1
3176    3
Name: FTR, dtype: object
0.5
Celta - local
2993    1
3017    1
3031    1
3048    3
3079    0
3089    1
3100    3
3124    0
3139    1
3152    0
Name: FTR, dtype: object
1.1
11
14.0
Elche - visitante
2999    0
3019    1
3030    0
Name: FTR, dtype: object
0.3333333333333333
Betis - local
2994    1
3005    3
3023    0
3057    3
3071    3
3090    1
3119    1
3130    1
3159    3
3173    3
Name: FTR, dtype: object
1.9
18
17.3
Villarreal - visitante
2993    1
3016    3
3032    3
3431    0
3447    3
3462    1
3499    0
3512    3
3533    0
3551    0
Name: FTR, dtype: object
1.4
Valencia - local
2991    3
3010    0
3038    3
3051    3
3085    3
3105    3
3121    3
3145    3
3165    1
3181    3
Name: FTR, dtype: object
2.5
25
16.1
Vallecano - visitante
2983    0
3002    0
3024    0
3055    3
3062    3
3081    0
3109    1
3124    3
3144    0
3168    1
Name: FTR, dtype: object
1.1
Sociedad - local
2997    1
3011    0
3039    3
3052    1
3068    1
3092    3
3125    3
3146    3
3161    1
3182    1
Name: FTR, dtype: object
1.7
24
15.3
Sevilla - visitante
2991    0
3008    0
3022    1
3053    0
3070    1
3091    1
3119    1
3138    0
3157    0
3178    0
Name: FTR, dtype: object
0.4
Real Madrid - local
2992    3
3013    3
3034    3
3043    3
3078    3
3086    3
3106    3
3126    3
3147    3
3166    3
Name: FTR, dtype: object
3.0
38
22.8
Ath Madrid - visitante
2996    3
3011    3
3033    3
3040    3
3079    3
3087    1
3101    3
3123    1
3141    3
3162    1
Name: FTR, dtype: object
2.4
Almeria - local
2998    1
3019    1
3032    0
Name: FTR, dtype: object
0.6666666666666666
6
12.333333333333334
Barcelona - visitante
2995    3
3010    3
3021    3
3056    3
3072    3
3098    1
3111    3
3139    1
3166    0
3187    3
Name: FTR, dtype: object
2.3
Valladolid - local
2996    0
3015    3
3037    0
3050    0
3073    3
3091    1
3115    3
3132    0
3156    1
3180    0
Name: FTR, dtype: object
1.1
8
11.6
Malaga - visitante
2997    1
3012    1
3038    0
3049    0
3078    0
3088    0
3105    0
3125    0
3137    3
3156    1
Name: FTR, dtype: object
0.6
Villarreal - local
3006    1
3025    3
3420    0
3455    1
3472    1
3480    3
3501    1
3523    1
3540    0
3560    1
Name: FTR, dtype: object
1.2
12
15.0
Espanol - visitante
3003    3
3031    1
3048    0
3063    0
3082    0
3104    3
3122    3
3142    3
3155    0
3174    0
Name: FTR, dtype: object
1.3
Getafe - local
3004    3
3028    1
3055    0
3067    0
3080    3
3104    0
3123    1
3148    3
3169    3
3188    3
Name: FTR, dtype: object
1.7
13
12.7
Celta - visitante
3001    0
3023    3
3050    3
3071    0
3096    3
3110    0
3149    0
3160    0
3188    0
3205    0
Name: FTR, dtype: object
0.9
Ath Bilbao - local
3001    3
3029    3
3059    0
3076    3
3098    1
3114    0
3131    3
3154    3
3179    0
3194    0
Name: FTR, dtype: object
1.6
12
12.0
Betis - visitante
3014    1
3034    0
3045    1
3060    0
3084    0
3106    0
3129    3
3145    0
3161    1
3184    0
Name: FTR, dtype: object
0.6
Sevilla - local
3012    1
3033    0
3042    3
3065    0
3082    3
3101    0
3120    3
3140    3
3160    3
3189    3
Name: FTR, dtype: object
1.9
24
16.3
Vallecano - visitante
3002    0
3024    0
3055    3
3062    3
3081    0
3109    1
3124    3
3144    0
3168    1
3183    0
Name: FTR, dtype: object
1.1
Granada - local
3003    0
3020    0
3047    3
3066    3
3088    3
3107    1
3129    0
3143    1
3163    0
3187    0
Name: FTR, dtype: object
1.1
11
13.9
Valencia - visitante
3005    0
3026    0
3042    0
3067    3
3069    3
3092    0
3118    1
3135    1
3154    0
3175    1
Name: FTR, dtype: object
0.9
Elche - local
3000    1
3027    1
Name: FTR, dtype: object
1.0
1
11.0
Real Madrid - visitante
3006    1
3020    3
3052    1
3075    1
3097    3
3114    3
3136    1
3152    3
3177    3
3206    0
Name: FTR, dtype: object
1.9
Malaga - local
3002    3
3021    0
3054    3
3070    1
3093    3
3116    3
3142    0
3162    1
3186    3
3203    1
Name: FTR, dtype: object
1.8
13
11.8
Almeria - visitante
3009    0
3028    1
Name: FTR, dtype: object
0.5
Levante - local
3007    1
3022    1
3045    1
3062    0
3077    1
3096    0
3117    0
3138    3
3151    1
3170    0
Name: FTR, dtype: object
0.8
4
13.2
Valladolid - visitante
3000    1
3025    0
3044    0
3064    0
3086    0
3107    1
3121    0
3146    0
3164    1
3171    3
Name: FTR, dtype: object
0.6
Barcelona - local
3008    3
3036    3
3049    3
3064    3
3084    3
3108    3
3128    3
3144    3
3158    3
3178    3
Name: FTR, dtype: object
3.0
33
17.4
Sociedad - visitante
3007    1
3027    1
3046    3
3065    3
3080    0
3102    1
3112    3
3134    1
3153    3
3179    3
Name: FTR, dtype: object
1.9
Ath Madrid - local
3009    3
3024    3
3058    1
3072    0
3097    0
3113    3
3135    1
3153    0
3174    3
3204    3
Name: FTR, dtype: object
1.7
19
13.7
Osasuna - visitante
3004    0
3029    0
3043    0
3066    0
3085    0
3099    1
3116    0
3132    3
3159    0
3170    3
Name: FTR, dtype: object
0.7
Espanol - local
3014    1
3026    3
3056    0
3075    1
3094    0
3118    1
3134    1
3164    1
3184    3
3208    3
Name: FTR, dtype: object
1.4
13
9.9
Ath Bilbao - visitante
3013    0
3037    3
3041    1
3061    3
3089    1
3103    1
3120    0
3148    0
3167    3
3186    0
Name: FTR, dtype: object
1.2
Valencia - local
3010    0
3038    3
3051    3
3085    3
3105    3
3121    3
3145    3
3165    1
3181    3
3200    1
Name: FTR, dtype: object
2.3
23
15.2
Sevilla - visitante
3008    0
3022    1
3053    0
3070    1
3091    1
3119    1
3138    0
3157    0
3178    0
3195    0
Name: FTR, dtype: object
0.4
Real Madrid - local
3013    3
3034    3
3043    3
3078    3
3086    3
3106    3
3126    3
3147    3
3166    3
3183    3
Name: FTR, dtype: object
3.0
36
20.9
Getafe - visitante
3015    0
3039    0
3047    0
3074    0
3093    0
3115    0
3130    1
3151    1
3176    3
3193    0
Name: FTR, dtype: object
0.5
Celta - local
3017    1
3031    1
3048    3
3079    0
3089    1
3100    3
3124    0
3139    1
3152    0
3172    3
Name: FTR, dtype: object
1.3
13
14.8
Villarreal - visitante
3016    3
3032    3
3431    0
3447    3
3462    1
3499    0
3512    3
3533    0
3551    0
3572    0
Name: FTR, dtype: object
1.3
Betis - local
3005    3
3023    0
3057    3
3071    3
3090    1
3119    1
3130    1
3159    3
3173    3
3190    1
Name: FTR, dtype: object
1.9
18
17.6
Granada - visitante
3017    1
3035    3
3051    0
3068    1
3094    3
3113    0
3131    0
3150    1
3172    0
3198    3
Name: FTR, dtype: object
1.2
Vallecano - local
3018    0
3030    3
3041    1
3069    0
3099    1
3112    0
3137    0
3155    3
3171    0
3192    3
Name: FTR, dtype: object
1.1
14
15.7
Barcelona - visitante
3010    3
3021    3
3056    3
3072    3
3098    1
3111    3
3139    1
3166    0
3187    3
3200    1
Name: FTR, dtype: object
2.1
Valladolid - local
3015    3
3037    0
3050    0
3073    3
3091    1
3115    3
3132    0
3156    1
3180    0
3209    1
Name: FTR, dtype: object
1.2
10
11.4
Ath Madrid - visitante
3011    3
3033    3
3040    3
3079    3
3087    1
3101    3
3123    1
3141    3
3162    1
3180    3
Name: FTR, dtype: object
2.4
Sociedad - local
3011    0
3039    3
3052    1
3068    1
3092    3
3125    3
3146    3
3161    1
3182    1
3201    3
Name: FTR, dtype: object
1.9
27
17.0
Malaga - visitante
3012    1
3038    0
3049    0
3078    0
3088    0
3105    0
3125    0
3137    3
3156    1
3173    0
Name: FTR, dtype: object
0.5
Almeria - local
3019    1
3032    0
Name: FTR, dtype: object
0.5
4
12.0
Levante - visitante
3018    3
3036    0
3059    3
3083    1
3108    0
3126    0
3143    1
3165    1
3182    1
3208    0
Name: FTR, dtype: object
1.0
Osasuna - local
3016    0
3035    0
3053    3
3074    3
3102    1
3122    0
3141    0
3167    0
3185    3
3205    3
Name: FTR, dtype: object
1.3
6
15.1
Elche - visitante
3019    1
3030    0
Name: FTR, dtype: object
0.5
Elche - local
3027    1
Name: FTR, dtype: object
1.0
1
12.0
Valladolid - visitante
3025    0
3044    0
3064    0
3086    0
3107    1
3121    0
3146    0
3164    1
3171    3
3190    1
Name: FTR, dtype: object
0.6
Ath Bilbao - local
3029    3
3059    0
3076    3
3098    1
3114    0
3131    3
3154    3
3179    0
3194    0
3215    3
Name: FTR, dtype: object
1.6
12
12.6
Celta - visitante
3023    3
3050    3
3071    0
3096    3
3110    0
3149    0
3160    0
3188    0
3205    0
3226    1
Name: FTR, dtype: object
1.0
Malaga - local
3021    0
3054    3
3070    1
3093    3
3116    3
3142    0
3162    1
3186    3
3203    1
3226    1
Name: FTR, dtype: object
1.6
9
11.2
Vallecano - visitante
3024    0
3055    3
3062    3
3081    0
3109    1
3124    3
3144    0
3168    1
3183    0
3202    0
Name: FTR, dtype: object
1.1
Granada - local
3020    0
3047    3
3066    3
3088    3
3107    1
3129    0
3143    1
3163    0
3187    0
3206    3
Name: FTR, dtype: object
1.4
12
13.4
Espanol - visitante
3031    1
3048    0
3063    0
3082    0
3104    3
3122    3
3142    3
3155    0
3174    0
3194    3
Name: FTR, dtype: object
1.3
Getafe - local
3028    1
3055    0
3067    0
3080    3
3104    0
3123    1
3148    3
3169    3
3188    3
3207    3
Name: FTR, dtype: object
1.7
14
12.5
Osasuna - visitante
3029    0
3043    0
3066    0
3085    0
3099    1
3116    0
3132    3
3159    0
3170    3
3196    1
Name: FTR, dtype: object
0.8
Betis - local
3023    0
3057    3
3071    3
3090    1
3119    1
3130    1
3159    3
3173    3
3190    1
3220    1
Name: FTR, dtype: object
1.7
16
16.5
Valencia - visitante
3026    0
3042    0
3067    3
3069    3
3092    0
3118    1
3135    1
3154    0
3175    1
3199    3
Name: FTR, dtype: object
1.2
Villarreal - local
3025    3
3420    0
3455    1
3472    1
3480    3
3501    1
3523    1
3540    0
3560    1
3581    3
Name: FTR, dtype: object
1.4
13
14.3
Real Madrid - visitante
3020    3
3052    1
3075    1
3097    3
3114    3
3136    1
3152    3
3177    3
3206    0
3222    3
Name: FTR, dtype: object
2.1
Levante - local
3022    1
3045    1
3062    0
3077    1
3096    0
3117    0
3138    3
3151    1
3170    0
3197    0
Name: FTR, dtype: object
0.7
5
13.1
Sociedad - visitante
3027    1
3046    3
3065    3
3080    0
3102    1
3112    3
3134    1
3153    3
3179    3
3191    3

Name: FTR, dtype: object
2.1
Barcelona - local
3036    3
3049    3
3064    3
3084    3
3108    3
3128    3
3144    3
3158    3
3178    3
3193    3
Name: FTR, dtype: object
3.0
36
17.2
Sevilla - visitante
3022    1
3053    0
3070    1
3091    1
3119    1
3138    0
3157    0
3178    0
3195    0
3228    1
Name: FTR, dtype: object
0.5
Ath Madrid - local
3024    3
3058    1
3072    0
3097    0
3113    3
3135    1
3153    0
3174    3
3204    3
3224    3
Name: FTR, dtype: object
1.7
17
13.0
Almeria - visitante
3028    1
Name: FTR, dtype: object
1.0
Valencia - local
3038    3
3051    3
3085    3
3105    3
3121    3
3145    3
3165    1
3181    3
3200    1
3222    0
Name: FTR, dtype: object
2.3
21
15.6
Barcelona - visitante
3021    3
3056    3
3072    3
3098    1
3111    3
3139    1
3166    0
3187    3
3200    1
3225    0
Name: FTR, dtype: object
1.8
Sociedad - local
3039    3
3052    1
3068    1
3092    3
3125    3
3146    3
3161    1
3182    1
3201    3
3225    3
Name: FTR, dtype: object
2.2
29
17.4
Ath Madrid - visitante
3033    3
3040    3
3079    3
3087    1
3101    3
3123    1
3141    3
3162    1
3180    3
3192    0
Name: FTR, dtype: object
2.1
Sevilla - local
3033    0
3042    3
3065    0
3082    3
3101    0
3120    3
3140    3
3160    3
3189    3
3202    3
Name: FTR, dtype: object
2.1
24
16.4
Malaga - visitante
3038    0
3049    0
3078    0
3088    0
3105    0
3125    0
3137    3
3156    1
3173    0
3197    3
Name: FTR, dtype: object
0.7
Real Madrid - local
3034    3
3043    3
3078    3
3086    3
3106    3
3126    3
3147    3
3166    3
3183    3
3195    3
Name: FTR, dtype: object
3.0
37
20.7
Ath Bilbao - visitante
3037    3
3041    1
3061    3
3089    1
3103    1
3120    0
3148    0
3167    3
3186    0
3209    1
Name: FTR, dtype: object
1.3
Espanol - local
3026    3
3056    0
3075    1
3094    0
3118    1
3134    1
3164    1
3184    3
3208    3
3229    3
Name: FTR, dtype: object
1.6
16
10.7
Betis - visitante
3034    0
3045    1
3060    0
3084    0
3106    0
3129    3
3145    0
3161    1
3184    0
3204    0
Name: FTR, dtype: object
0.5
Valladolid - local
3037    0
3050    0
3073    3
3091    1
3115    3
3132    0
3156    1
3180    0
3209    1
3221    3
Name: FTR, dtype: object
1.2
11
10.6
Getafe - visitante
3039    0
3047    0
3074    0
3093    0
3115    0
3130    1
3151    1
3176    3
3193    0
3212    0
Name: FTR, dtype: object
0.5
Osasuna - local
3035    0
3053    3
3074    3
3102    1
3122    0
3141    0
3167    0
3185    3
3205    3
3223    3
Name: FTR, dtype: object
1.6
8
15.0
Villarreal - visitante
3032    3
3431    0
3447    3
3462    1
3499    0
3512    3
3533    0
3551    0
3572    0
3593    3
Name: FTR, dtype: object
1.3
Celta - local
3031    1
3048    3
3079    0
3089    1
3100    3
3124    0
3139    1
3152    0
3172    3
3199    0
Name: FTR, dtype: object
1.2
12
13.7
Granada - visitante
3035    3
3051    0
3068    1
3094    3
3113    0
3131    0
3150    1
3172    0
3198    3
3210    0
Name: FTR, dtype: object
1.1
Vallecano - local
3030    3
3041    1
3069    0
3099    1
3112    0
3137    0
3155    3
3171    0
3192    3
3211    3
Name: FTR, dtype: object
1.4
16
14.4
Levante - visitante
3036    0
3059    3
3083    1
3108    0
3126    0
3143    1
3165    1
3182    1
3208    0
3224    0
Name: FTR, dtype: object
0.7
Almeria - local
3032    0
Name: FTR, dtype: object
0.0
2
15.0
Elche - visitante
3030    0
Name: FTR, dtype: object
0.0
Granada - local
3047    3
3066    3
3088    3
3107    1
3129    0
3143    1
3163    0
3187    0
3206    3
3227    3
Name: FTR, dtype: object
1.7
14
13.8
Real Madrid - visitante
3052    1
3075    1
3097    3
3114    3
3136    1
3152    3
3177    3
3206    0
3222    3
3237    1
Name: FTR, dtype: object
1.9
Malaga - local
3054    3
3070    1
3093    3
3116    3
3142    0
3162    1
3186    3
3203    1
3226    1
3232    0
Name: FTR, dtype: object
1.6
10
11.0
Barcelona - visitante
3056    3
3072    3
3098    1
3111    3
3139    1
3166    0
3187    3
3200    1
3225    0
3232    3
Name: FTR, dtype: object
1.8
Levante - local
3045    1
3062    0
3077    1
3096    0
3117    0
3138    3
3151    1
3170    0
3197    0
3217    3
Name: FTR, dtype: object
0.9
7
13.9
Sevilla - visitante
3053    0
3070    1
3091    1
3119    1
3138    0
3157    0
3178    0
3195    0
3228    1
3236    0
Name: FTR, dtype: object
0.4
Betis - local
3057    3
3071    3
3090    1
3119    1
3130    1
3159    3
3173    3
3190    1
3220    1
3233    3
Name: FTR, dtype: object
2.0
17
15.8
Celta - visitante
3050    3
3071    0
3096    3
3110    0
3149    0
3160    0
3188    0
3205    0
3226    1
3238    0
Name: FTR, dtype: object
0.7
Ath Madrid - local
3058    1
3072    0
3097    0
3113    3
3135    1
3153    0
3174    3
3204    3
3224    3
3234    3
Name: FTR, dtype: object
1.7
14
13.0
Vallecano - visitante
3055    3
3062    3
3081    0
3109    1
3124    3
3144    0
3168    1
3183    0
3202    0
3227    0
Name: FTR, dtype: object
1.1
Villarreal - local
3420    0
3455    1
3472    1
3480    3
3501    1
3523    1
3540    0
3560    1
3581    3
3606    1
Name: FTR, dtype: object
1.2
11
13.1
Valladolid - visitante
3044    0
3064    0
3086    0
3107    1
3121    0
3146    0
3164    1
3171    3
3190    1
3217    0
Name: FTR, dtype: object
0.6
Espanol - local
3056    0
3075    1
3094    0
3118    1
3134    1
3164    1
3184    3
3208    3
3229    3
3238    3
Name: FTR, dtype: object
1.6
14
10.8
Valencia - visitante
3042    0
3067    3
3069    3
3092    0
3118    1
3135    1
3154    0
3175    1
3199    3
3218    3
Name: FTR, dtype: object
1.5
Elche - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Sociedad - visitante
3046    3
3065    3
3080    0
3102    1
3112    3
3134    1
3153    3
3179    3
3191    3
3219    1
Name: FTR, dtype: object
2.1
Getafe - local
3055    0
3067    0
3080    3
3104    0
3123    1
3148    3
3169    3
3188    3
3207    3
3228    1
Name: FTR, dtype: object
1.7
13
11.9
Almeria - visitante
Series([], Name: FTR, dtype: object)
0.0
Ath Bilbao - local
3059    0
3076    3
3098    1
3114    0
3131    3
3154    3
3179    0
3194    0
3215    3
3239    0
Name: FTR, dtype: object
1.3
11
13.6
Osasuna - visitante
3043    0
3066    0
3085    0
3099    1
3116    0
3132    3
3159    0
3170    3
3196    1
3214    0
Name: FTR, dtype: object
0.8
Vallecano - local
3041    1
3069    0
3099    1
3112    0
3137    0
3155    3
3171    0
3192    3
3211    3
3240    3
Name: FTR, dtype: object
1.4
16
15.7
Elche - visitante
Series([], Name: FTR, dtype: object)
0.0
Celta - local
3048    3
3079    0
3089    1
3100    3
3124    0
3139    1
3152    0
3172    3
3199    0
3219    1
Name: FTR, dtype: object
1.2
11
13.3
Espanol - visitante
3048    0
3063    0
3082    0
3104    3
3122    3
3142    3
3155    0
3174    0
3194    3
3216    1
Name: FTR, dtype: object
1.3
Almeria - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Villarreal - visitante
3431    0
3447    3
3462    1
3499    0
3512    3
3533    0
3551    0
3572    0
3593    3
3623    0
Name: FTR, dtype: object
1.0
Sevilla - local
3042    3
3065    0
3082    3
3101    0
3120    3
3140    3
3160    3
3189    3
3202    3
3210    3
Name: FTR, dtype: object
2.4
26
17.3
Ath Madrid - visitante
3040    3
3079    3
3087    1
3101    3
3123    1
3141    3
3162    1
3180    3
3192    0
3215    0
Name: FTR, dtype: object
1.8
Real Madrid - local
3043    3
3078    3
3086    3
3106    3
3126    3
3147    3
3166    3
3183    3
3195    3
3212    3
Name: FTR, dtype: object
3.0
39
20.9
Betis - visitante
3045    1
3060    0
3084    0
3106    0
3129    3
3145    0
3161    1
3184    0
3204    0
3211    0
Name: FTR, dtype: object
0.5
Osasuna - local
3053    3
3074    3
3102    1
3122    0
3141    0
3167    0
3185    3
3205    3
3223    3
3237    1
Name: FTR, dtype: object
1.7
7
14.9
Granada - visitante
3051    0
3068    1
3094    3
3113    0
3131    0
3150    1
3172    0
3198    3
3210    0
3230    1
Name: FTR, dtype: object
0.9
Barcelona - local
3049    3
3064    3
3084    3
3108    3
3128    3
3144    3
3158    3
3178    3
3193    3
3214    3
Name: FTR, dtype: object
3.0
34
16.9
Levante - visitante
3059    3
3083    1
3108    0
3126    0
3143    1
3165    1
3182    1
3208    0
3224    0
3233    0
Name: FTR, dtype: object
0.7
Valladolid - local
3050    0
3073    3
3091    1
3115    3
3132    0
3156    1
3180    0
3209    1
3221    3
3235    3
Name: FTR, dtype: object
1.5
13
11.2
Ath Bilbao - visitante
3041    1
3061    3
3089    1
3103    1
3120    0
3148    0
3167    3
3186    0
3209    1
3220    1
Name: FTR, dtype: object
1.1
Valencia - local
3051    3
3085    3
3105    3
3121    3
3145    3
3165    1
3181    3
3200    1
3222    0
3236    3
Name: FTR, dtype: object
2.3
22
16.4
Malaga - visitante
3049    0
3078    0
3088    0
3105    0
3125    0
3137    3
3156    1
3173    0
3197    3
3213    3
Name: FTR, dtype: object
1.0
Sociedad - local
3052    1
3068    1
3092    3
3125    3
3146    3
3161    1
3182    1
3201    3
3225    3
3231    1
Name: FTR, dtype: object
2.0
28
16.9
Getafe - visitante
3047    0
3074    0
3093    0
3115    0
3130    1
3151    1
3176    3
3193    0
3212    0
3240    0
Name: FTR, dtype: object
0.5
Zaragoza - local
3061    0
3081    3
3095    3
3111    0
3136    1
3150    1
3175    1
3191    0
3216    1
3249    0
Name: FTR, dtype: object
1.0
12
12.3
Ath Madrid - visitante
3079    3
3087    1
3101    3
3123    1
3141    3
3162    1
3180    3
3192    0
3215    0
3242    1
Name: FTR, dtype: object
1.6
Vallecano - local
3069    0
3099    1
3112    0
3137    0
3155    3
3171    0
3192    3
3211    3
3240    3
3257    3
Name: FTR, dtype: object
1.6
17
14.7
Ath Bilbao - visitante
3061    3
3089    1
3103    1
3120    0
3148    0
3167    3
3186    0
3209    1
3220    1
3246    0
Name: FTR, dtype: object
1.0
Sevilla - local
3065    0
3082    3
3101    0
3120    3
3140    3
3160    3
3189    3
3202    3
3210    3
3245    3

Name: FTR, dtype: object
2.4
23
16.9
Valencia - visitante
3067    3
3069    3
3092    0
3118    1
3135    1
3154    0
3175    1
3199    3
3218    3
3248    3
Name: FTR, dtype: object
1.8
Real Madrid - local
3078    3
3086    3
3106    3
3126    3
3147    3
3166    3
3183    3
3195    3
3212    3
3241    3
Name: FTR, dtype: object
3.0
39
21.6
Osasuna - visitante
3066    0
3085    0
3099    1
3116    0
3132    3
3159    0
3170    3
3196    1
3214    0
3245    0
Name: FTR, dtype: object
0.8
Mallorca - local
3060    3
3083    1
3109    1
3110    3
3133    0
3157    3
3176    0
3196    1
3213    0
3242    1
Name: FTR, dtype: object
1.3
13
14.7
Valladolid - visitante
3064    0
3086    0
3107    1
3121    0
3146    0
3164    1
3171    3
3190    1
3217    0
3243    0
Name: FTR, dtype: object
0.6
Levante - local
3062    0
3077    1
3096    0
3117    0
3138    3
3151    1
3170    0
3197    0
3217    3
3246    3
Name: FTR, dtype: object
1.1
9
13.7
Betis - visitante
3060    0
3084    0
3106    0
3129    3
3145    0
3161    1
3184    0
3204    0
3211    0
3249    3
Name: FTR, dtype: object
0.7
La Coruna - local
3063    3
3087    1
3103    1
3127    3
3149    3
3168    1
3177    0
3198    0
3218    0
3247    3
Name: FTR, dtype: object
1.5
13
13.3
Sociedad - visitante
3065    3
3080    0
3102    1
3112    3
3134    1
3153    3
3179    3
3191    3
3219    1
3241    0
Name: FTR, dtype: object
1.8
Granada - local
3066    3
3088    3
3107    1
3129    0
3143    1
3163    0
3187    0
3206    3
3227    3
3248    0
Name: FTR, dtype: object
1.4
13
12.5
Getafe - visitante
3074    0
3093    0
3115    0
3130    1
3151    1
3176    3
3193    0
3212    0
3240    0
3255    0
Name: FTR, dtype: object
0.5
Celta - local
3079    0
3089    1
3100    3
3124    0
3139    1
3152    0
3172    3
3199    0
3219    1
3243    3
Name: FTR, dtype: object
1.2
13
13.5
Espanol - visitante
3063    0
3082    0
3104    3
3122    3
3142    3
3155    0
3174    0
3194    3
3216    1
3244    0
Name: FTR, dtype: object
1.3
Barcelona - local
3064    3
3084    3
3108    3
3128    3
3144    3
3158    3
3178    3
3193    3
3214    3
3244    3
Name: FTR, dtype: object
3.0
34
17.8
Malaga - visitante
3078    0
3088    0
3105    0
3125    0
3137    3
3156    1
3173    0
3197    3
3213    3
3247    0
Name: FTR, dtype: object
1.0
Valladolid - local
3073    3
3091    1
3115    3
3132    0
3156    1
3180    0
3209    1
3221    3
3235    3
3250    0
Name: FTR, dtype: object
1.5
14
10.4
Celta - visitante
3071    0
3096    3
3110    0
3149    0
3160    0
3188    0
3205    0
3226    1
3238    0
3256    0
Name: FTR, dtype: object
0.4
Valencia - local
3085    3
3105    3
3121    3
3145    3
3165    1
3181    3
3200    1
3222    0
3236    3
3255    3
Name: FTR, dtype: object
2.3
25
17.1
Granada - visitante
3068    1
3094    3
3113    0
3131    0
3150    1
3172    0
3198    3
3210    0
3230    1
3251    3
Name: FTR, dtype: object
1.2
Sociedad - local
3068    1
3092    3
3125    3
3146    3
3161    1
3182    1
3201    3
3225    3
3231    1
3258    3
Name: FTR, dtype: object
2.2
27
15.4
Real Madrid - visitante
3075    1
3097    3
3114    3
3136    1
3152    3
3177    3
3206    0
3222    3
3237    1
3252    0
Name: FTR, dtype: object
1.8
Osasuna - local
3074    3
3102    1
3122    0
3141    0
3167    0
3185    3
3205    3
3223    3
3237    1
3251    0
Name: FTR, dtype: object
1.4
6
14.2
Sevilla - visitante
3070    1
3091    1
3119    1
3138    0
3157    0
3178    0
3195    0
3228    1
3236    0
3258    0
Name: FTR, dtype: object
0.4
Malaga - local
3070    1
3093    3
3116    3
3142    0
3162    1
3186    3
3203    1
3226    1
3232    0
3252    3
Name: FTR, dtype: object
1.6
10
10.6
La Coruna - visitante
3073    0
3090    1
3117    3
3133    3
3158    0
3189    0
3207    0
3223    0
3231    1
3259    0
Name: FTR, dtype: object
0.8
Getafe - local
3067    0
3080    3
3104    0
3123    1
3148    3
3169    3
3188    3
3207    3
3228    1
3230    1
Name: FTR, dtype: object
1.8
14
11.4
Vallecano - visitante
3062    3
3081    0
3109    1
3124    3
3144    0
3168    1
3183    0
3202    0
3227    0
3239    3
Name: FTR, dtype: object
1.1
Espanol - local
3075    1
3094    0
3118    1
3134    1
3164    1
3184    3
3208    3
3229    3
3238    3
3259    3
Name: FTR, dtype: object
1.9
16
11.1
Barcelona - visitante
3072    3
3098    1
3111    3
3139    1
3166    0
3187    3
3200    1
3225    0
3232    3
3250    3
Name: FTR, dtype: object
1.8
Betis - local
3071    3
3090    1
3119    1
3130    1
3159    3
3173    3
3190    1
3220    1
3233    3
3253    0
Name: FTR, dtype: object
1.7
14
16.2
Zaragoza - visitante
3077    1
3100    0
3127    0
3140    0
3169    0
3185    0
3203    1
3221    0
3234    0
3254    3
Name: FTR, dtype: object
0.5
Ath Madrid - local
3072    0
3097    0
3113    3
3135    1
3153    0
3174    3
3204    3
3224    3
3234    3
3256    3
Name: FTR, dtype: object
1.9
15
13.2
Mallorca - visitante
3076    0
3095    0
3128    0
3147    0
3163    3
3181    0
3201    0
3229    0
3235    0
3253    3
Name: FTR, dtype: object
0.6
Ath Bilbao - local
3076    3
3098    1
3114    0
3131    3
3154    3
3179    0
3194    0
3215    3
3239    0
3254    0
Name: FTR, dtype: object
1.3
11
13.6
Levante - visitante
3083    1
3108    0
3126    0
3143    1
3165    1
3182    1
3208    0
3224    0
3233    0
3257    0
Name: FTR, dtype: object
0.4
Mallorca - local
3083    1
3109    1
3110    3
3133    0
3157    3
3176    0
3196    1
3213    0
3242    1
3267    0
Name: FTR, dtype: object
1.0
12
15.0
Betis - visitante
3084    0
3106    0
3129    3
3145    0
3161    1
3184    0
3204    0
3211    0
3249    3
3261    3
Name: FTR, dtype: object
1.0
Zaragoza - local
3081    3
3095    3
3111    0
3136    1
3150    1
3175    1
3191    0
3216    1
3249    0
3262    0
Name: FTR, dtype: object
1.0
11
12.1
Ath Bilbao - visitante
3089    1
3103    1
3120    0
3148    0
3167    3
3186    0
3209    1
3220    1
3246    0
3267    3
Name: FTR, dtype: object
1.0
Levante - local
3077    1
3096    0
3117    0
3138    3
3151    1
3170    0
3197    0
3217    3
3246    3
3271    3
Name: FTR, dtype: object
1.4
11
13.9
Vallecano - visitante
3081    0
3109    1
3124    3
3144    0
3168    1
3183    0
3202    0
3227    0
3239    3
3263    3
Name: FTR, dtype: object
1.1
La Coruna - local
3087    1
3103    1
3127    3
3149    3
3168    1
3177    0
3198    0
3218    0
3247    3
3260    1
Name: FTR, dtype: object
1.3
11
13.4
Espanol - visitante
3082    0
3104    3
3122    3
3142    3
3155    0
3174    0
3194    3
3216    1
3244    0
3264    1
Name: FTR, dtype: object
1.4
Barcelona - local
3084    3
3108    3
3128    3
3144    3
3158    3
3178    3
3193    3
3214    3
3244    3
3265    3
Name: FTR, dtype: object
3.0
36
17.3
Valladolid - visitante
3086    0
3107    1
3121    0
3146    0
3164    1
3171    3
3190    1
3217    0
3243    0
3260    1
Name: FTR, dtype: object
0.7
Sevilla - local
3082    3
3101    0
3120    3
3140    3
3160    3
3189    3
3202    3
3210    3
3245    3
3266    0
Name: FTR, dtype: object
2.4
22
16.4
Sociedad - visitante
3080    0
3102    1
3112    3
3134    1
3153    3
3179    3
3191    3
3219    1
3241    0
3268    1
Name: FTR, dtype: object
1.6
Granada - local
3088    3
3107    1
3129    0
3143    1
3163    0
3187    0
3206    3
3227    3
3248    0
3268    1
Name: FTR, dtype: object
1.2
10
12.4
Osasuna - visitante
3085    0
3099    1
3116    0
3132    3
3159    0
3170    3
3196    1
3214    0
3245    0
3269    1
Name: FTR, dtype: object
0.9
Getafe - local
3080    3
3104    0
3123    1
3148    3
3169    3
3188    3
3207    3
3228    1
3230    1
3269    1
Name: FTR, dtype: object
1.9
15
11.8
Valencia - visitante
3069    3
3092    0
3118    1
3135    1
3154    0
3175    1
3199    3
3218    3
3248    3
3277    3
Name: FTR, dtype: object
1.8
Sociedad - local
3092    3
3125    3
3146    3
3161    1
3182    1
3201    3
3225    3
3231    1
3258    3
3276    1
Name: FTR, dtype: object
2.2
26
14.6
Granada - visitante
3094    3
3113    0
3131    0
3150    1
3172    0
3198    3
3210    0
3230    1
3251    3
3278    0
Name: FTR, dtype: object
1.1
Vallecano - local
3099    1
3112    0
3137    0
3155    3
3171    0
3192    3
3211    3
3240    3
3257    3
3270    0
Name: FTR, dtype: object
1.6
17
14.7
Valencia - visitante
3092    0
3118    1
3135    1
3154    0
3175    1
3199    3
3218    3
3248    3
3277    3
3297    0
Name: FTR, dtype: object
1.5
Malaga - local
3093    3
3116    3
3142    0
3162    1
3186    3
3203    1
3226    1
3232    0
3252    3
3278    3
Name: FTR, dtype: object
1.8
14
11.7
Sevilla - visitante
3091    1
3119    1
3138    0
3157    0
3178    0
3195    0
3228    1
3236    0
3258    0
3279    1
Name: FTR, dtype: object
0.4
Betis - local
3090    1
3119    1
3130    1
3159    3
3173    3
3190    1
3220    1
3233    3
3253    0
3272    0
Name: FTR, dtype: object
1.4
14
15.5
Celta - visitante
3096    3
3110    0
3149    0
3160    0
3188    0
3205    0
3226    1
3238    0
3256    0
3274    0
Name: FTR, dtype: object
0.4
Ath Madrid - local
3097    0
3113    3
3135    1
3153    0
3174    3
3204    3
3224    3
3234    3
3256    3
3273    3
Name: FTR, dtype: object
2.2
20
13.4
Barcelona - visitante
3098    1
3111    3
3139    1
3166    0
3187    3
3200    1
3225    0
3232    3
3250    3
3272    3
Name: FTR, dtype: object
1.8
Valladolid - local
3091    1
3115    3
3132    0
3156    1
3180    0
3209    1
3221    3
3235    3
3250    0
3275    0
Name: FTR, dtype: object
1.2
15
10.7
La Coruna - visitante
3090    1
3117    3
3133    3
3158    0
3189    0
3207    0
3223    0
3231    1
3259    0
3273    0
Name: FTR, dtype: object
0.8
Osasuna - local
3102    1
3122    0
3141    0
3167    0
3185    3
3205    3
3223    3
3237    1
3251    0
3277    0
Name: FTR, dtype: object
1.1
5
13.2
Getafe - visitante
3093    0
3115    0
3130    1
3151    1
3176    3
3193    0
3212    0
3240    0
3255    0
3276    1
Name: FTR, dtype: object
0.6
Espanol - local
3094    0
3118    1
3134    1
3164    1
3184    3
3208    3
3229    3
3238    3
3259    3
3279    1
Name: FTR, dtype: object
1.9
17
11.5
Real Madrid - visitante
3097    3
3114    3
3136    1
3152    3
3177    3
3206    0
3222    3
3237    1
3252    0
3275    3
Name: FTR, dtype: object
2.0
Ath Bilbao - local
3098    1
3114    0
3131    3
3154    3
3179    0
3194    0
3215    3
3239    0
3254    0
3274    3
Name: FTR, dtype: object
1.3
10
13.7
Mallorca - visitante
3095    0
3128    0
3147    0
3163    3
3181    0
3201    0
3229    0
3235    0
3253    3
3271    0
Name: FTR, dtype: object
0.6
Levante - local
3096    0
3117    0
3138    3
3151    1
3170    0
3197    0
3217    3
3246    3
3271    3
3291    0
Name: FTR, dtype: object
1.3
11
13.9
Zaragoza - visitante
3100    0
3127    0
3140    0
3169    0
3185    0
3203    1
3221    0
3234    0
3254    3
3270    3
Name: FTR, dtype: object
0.7

Real Madrid - local
3086    3
3106    3
3126    3
3147    3
3166    3
3183    3
3195    3
3212    3
3241    3
3264    1
Name: FTR, dtype: object
2.8
35
22.5
Malaga - visitante
3088    0
3105    0
3125    0
3137    3
3156    1
3173    0
3197    3
3213    3
3247    0
3266    3
Name: FTR, dtype: object
1.3
Celta - local
3089    1
3100    3
3124    0
3139    1
3152    0
3172    3
3199    0
3219    1
3243    3
3261    0
Name: FTR, dtype: object
1.2
12
13.4
Ath Madrid - visitante
3087    1
3101    3
3123    1
3141    3
3162    1
3180    3
3192    0
3215    0
3242    1
3265    0
Name: FTR, dtype: object
1.3
Getafe - local
3104    0
3123    1
3148    3
3169    3
3188    3
3207    3
3228    1
3230    1
3269    1
3287    3
Name: FTR, dtype: object
1.9
14
11.6
Sociedad - visitante
3102    1
3112    3
3134    1
3153    3
3179    3
3191    3
3219    1
3241    0
3268    1
3285    3
Name: FTR, dtype: object
1.9
Zaragoza - local
3095    3
3111    0
3136    1
3150    1
3175    1
3191    0
3216    1
3249    0
3262    0
3290    0
Name: FTR, dtype: object
0.7
8
11.9
Vallecano - visitante
3109    1
3124    3
3144    0
3168    1
3183    0
3202    0
3227    0
3239    3
3263    3
3289    0
Name: FTR, dtype: object
1.1
Sevilla - local
3101    0
3120    3
3140    3
3160    3
3189    3
3202    3
3210    3
3245    3
3266    0
3280    0
Name: FTR, dtype: object
2.1
20
16.9
Espanol - visitante
3104    3
3122    3
3142    3
3155    0
3174    0
3194    3
3216    1
3244    0
3264    1
3283    1
Name: FTR, dtype: object
1.5
Mallorca - local
3109    1
3110    3
3133    0
3157    3
3176    0
3196    1
3213    0
3242    1
3267    0
3281    1
Name: FTR, dtype: object
1.0
12
14.8
Levante - visitante
3108    0
3126    0
3143    1
3165    1
3182    1
3208    0
3224    0
3233    0
3257    0
3262    3
Name: FTR, dtype: object
0.6
Barcelona - local
3108    3
3128    3
3144    3
3158    3
3178    3
3193    3
3214    3
3244    3
3265    3
3288    3
Name: FTR, dtype: object
3.0
37
17.3
Betis - visitante
3106    0
3129    3
3145    0
3161    1
3184    0
3204    0
3211    0
3249    3
3261    3
3282    3
Name: FTR, dtype: object
1.3
Valencia - local
3105    3
3121    3
3145    3
3165    1
3181    3
3200    1
3222    0
3236    3
3255    3
3263    0
Name: FTR, dtype: object
2.0
21
16.1
Osasuna - visitante
3099    1
3116    0
3132    3
3159    0
3170    3
3196    1
3214    0
3245    0
3269    1
3299    1
Name: FTR, dtype: object
1.0
Real Madrid - local
3106    3
3126    3
3147    3
3166    3
3183    3
3195    3
3212    3
3241    3
3264    1
3286    3
Name: FTR, dtype: object
2.8
33
21.1
Valladolid - visitante
3107    1
3121    0
3146    0
3164    1
3171    3
3190    1
3217    0
3243    0
3260    1
3280    3
Name: FTR, dtype: object
1.0
La Coruna - local
3103    1
3127    3
3149    3
3168    1
3177    0
3198    0
3218    0
3247    3
3260    1
3282    0
Name: FTR, dtype: object
1.2
13
14.1
Ath Madrid - visitante
3101    3
3123    1
3141    3
3162    1
3180    3
3192    0
3215    0
3242    1
3265    0
3286    0
Name: FTR, dtype: object
1.2
Granada - local
3107    1
3129    0
3143    1
3163    0
3187    0
3206    3
3227    3
3248    0
3268    1
3283    1
Name: FTR, dtype: object
1.0
9
13.4
Malaga - visitante
3105    0
3125    0
3137    3
3156    1
3173    0
3197    3
3213    3
3247    0
3266    3
3287    0
Name: FTR, dtype: object
1.3
Celta - local
3100    3
3124    0
3139    1
3152    0
3172    3
3199    0
3219    1
3243    3
3261    0
3284    1
Name: FTR, dtype: object
1.2
12
13.1
Ath Bilbao - visitante
3103    1
3120    0
3148    0
3167    3
3186    0
3209    1
3220    1
3246    0
3267    3
3288    0
Name: FTR, dtype: object
0.9
Betis - local
3119    1
3130    1
3159    3
3173    3
3190    1
3220    1
3233    3
3253    0
3272    0
3298    3
Name: FTR, dtype: object
1.6
14
14.4
La Coruna - visitante
3117    3
3133    3
3158    0
3189    0
3207    0
3223    0
3231    1
3259    0
3273    0
3294    1
Name: FTR, dtype: object
0.8
Valladolid - local
3115    3
3132    0
3156    1
3180    0
3209    1
3221    3
3235    3
3250    0
3275    0
3296    3
Name: FTR, dtype: object
1.4
15
10.5
Sevilla - visitante
3119    1
3138    0
3157    0
3178    0
3195    0
3228    1
3236    0
3258    0
3279    1
3293    0
Name: FTR, dtype: object
0.3
Sociedad - local
3125    3
3146    3
3161    1
3182    1
3201    3
3225    3
3231    1
3258    3
3276    1
3299    1
Name: FTR, dtype: object
2.0
22
14.0
Valencia - visitante
3118    1
3135    1
3154    0
3175    1
3199    3
3218    3
3248    3
3277    3
3297    0
3310    1
Name: FTR, dtype: object
1.6
Malaga - local
3116    3
3142    0
3162    1
3186    3
3203    1
3226    1
3232    0
3252    3
3278    3
3297    3
Name: FTR, dtype: object
1.8
16
12.7
Getafe - visitante
3115    0
3130    1
3151    1
3176    3
3193    0
3212    0
3240    0
3255    0
3276    1
3292    3
Name: FTR, dtype: object
0.9
Espanol - local
3118    1
3134    1
3164    1
3184    3
3208    3
3229    3
3238    3
3259    3
3279    1
3292    0
Name: FTR, dtype: object
1.9
17
11.7
Granada - visitante
3113    0
3131    0
3150    1
3172    0
3198    3
3210    0
3230    1
3251    3
3278    0
3296    0
Name: FTR, dtype: object
0.8
Zaragoza - local
3111    0
3136    1
3150    1
3175    1
3191    0
3216    1
3249    0
3262    0
3290    0
3315    3
Name: FTR, dtype: object
0.7
10
12.9
Mallorca - visitante
3128    0
3147    0
3163    3
3181    0
3201    0
3229    0
3235    0
3253    3
3271    0
3295    0
Name: FTR, dtype: object
0.6
Levante - local
3117    0
3138    3
3151    1
3170    0
3197    0
3217    3
3246    3
3271    3
3291    0
3312    0
Name: FTR, dtype: object
1.3
12
13.9
Celta - visitante
3110    0
3149    0
3160    0
3188    0
3205    0
3226    1
3238    0
3256    0
3274    0
3290    3
Name: FTR, dtype: object
0.4
Ath Madrid - local
3113    3
3135    1
3153    0
3174    3
3204    3
3224    3
3234    3
3256    3
3273    3
3293    3
Name: FTR, dtype: object
2.5
23
14.1
Real Madrid - visitante
3114    3
3136    1
3152    3
3177    3
3206    0
3222    3
3237    1
3252    0
3275    3
3298    0
Name: FTR, dtype: object
1.7
Ath Bilbao - local
3114    0
3131    3
3154    3
3179    0
3194    0
3215    3
3239    0
3254    0
3274    3
3294    1
Name: FTR, dtype: object
1.3
9
15.6
Barcelona - visitante
3111    3
3139    1
3166    0
3187    3
3200    1
3225    0
3232    3
3250    3
3272    3
3291    3
Name: FTR, dtype: object
2.0
Vallecano - local
3112    0
3137    0
3155    3
3171    0
3192    3
3211    3
3240    3
3257    3
3270    0
3295    3
Name: FTR, dtype: object
1.8
17
15.5
Osasuna - visitante
3116    0
3132    3
3159    0
3170    3
3196    1
3214    0
3245    0
3269    1
3299    1
3318    3
Name: FTR, dtype: object
1.2
Celta - local
3124    0
3139    1
3152    0
3172    3
3199    0
3219    1
3243    3
3261    0
3284    1
3305    1
Name: FTR, dtype: object
1.0
11
13.0
Zaragoza - visitante
3127    0
3140    0
3169    0
3185    0
3203    1
3221    0
3234    0
3254    3
3270    3
3281    1
Name: FTR, dtype: object
0.8
Sevilla - local
3120    3
3140    3
3160    3
3189    3
3202    3
3210    3
3245    3
3266    0
3280    0
3301    3
Name: FTR, dtype: object
2.4
25
17.8
Ath Madrid - visitante
3123    1
3141    3
3162    1
3180    3
3192    0
3215    0
3242    1
3265    0
3286    0
3303    3
Name: FTR, dtype: object
1.2
Osasuna - local
3122    0
3141    0
3167    0
3185    3
3205    3
3223    3
3237    1
3251    0
3277    0
3289    3
Name: FTR, dtype: object
1.3
6
13.0
Sociedad - visitante
3112    3
3134    1
3153    3
3179    3
3191    3
3219    1
3241    0
3268    1
3285    3
3317    3
Name: FTR, dtype: object
2.1
La Coruna - local
3127    3
3149    3
3168    1
3177    0
3198    0
3218    0
3247    3
3260    1
3282    0
3302    0
Name: FTR, dtype: object
1.1
12
15.5
Ath Bilbao - visitante
3120    0
3148    0
3167    3
3186    0
3209    1
3220    1
3246    0
3267    3
3288    0
3307    0
Name: FTR, dtype: object
0.8
Getafe - local
3123    1
3148    3
3169    3
3188    3
3207    3
3228    1
3230    1
3269    1
3287    3
3304    3
Name: FTR, dtype: object
2.2
16
12.8
Espanol - visitante
3122    3
3142    3
3155    0
3174    0
3194    3
3216    1
3244    0
3264    1
3283    1
3306    0
Name: FTR, dtype: object
1.2
Valencia - local
3121    3
3145    3
3165    1
3181    3
3200    1
3222    0
3236    3
3255    3
3263    0
3285    0
Name: FTR, dtype: object
1.7
18
15.7
Malaga - visitante
3125    0
3137    3
3156    1
3173    0
3197    3
3213    3
3247    0
3266    3
3287    0
3308    1
Name: FTR, dtype: object
1.4
Real Madrid - local
3126    3
3147    3
3166    3
3183    3
3195    3
3212    3
3241    3
3264    1
3286    3
3307    3
Name: FTR, dtype: object
2.8
35
22.0
Betis - visitante
3129    3
3145    0
3161    1
3184    0
3204    0
3211    0
3249    3
3261    3
3282    3
3301    0
Name: FTR, dtype: object
1.3
Granada - local
3129    0
3143    1
3163    0
3187    0
3206    3
3227    3
3248    0
3268    1
3283    1
3303    0
Name: FTR, dtype: object
0.9
8
11.9
Valladolid - visitante
3121    0
3146    0
3164    1
3171    3
3190    1
3217    0
3243    0
3260    1
3280    3
3304    0
Name: FTR, dtype: object
0.9
Barcelona - local
3128    3
3144    3
3158    3
3178    3
3193    3
3214    3
3244    3
3265    3
3288    3
3309    3
Name: FTR, dtype: object
3.0
39
16.3
Levante - visitante
3126    0
3143    1
3165    1
3182    1
3208    0
3224    0
3233    0
3257    0
3262    3
3284    1
Name: FTR, dtype: object
0.7
Mallorca - local
3110    3
3133    0
3157    3
3176    0
3196    1
3213    0
3242    1
3267    0
3281    1
3311    0
Name: FTR, dtype: object
0.9
13
14.2
Vallecano - visitante
3124    3
3144    0
3168    1
3183    0
3202    0
3227    0
3239    3
3263    3
3289    0
3300    0
Name: FTR, dtype: object
1.0
Mallorca - local
3133    0
3157    3
3176    0
3196    1
3213    0
3242    1
3267    0
3281    1
3311    0
3332    0
Name: FTR, dtype: object
0.6
12
13.3
Celta - visitante
3149    0
3160    0
3188    0
3205    0
3226    1
3238    0
3256    0
3274    0
3290    3
3316    0
Name: FTR, dtype: object
0.4
Zaragoza - local
3136    1
3150    1
3175    1
3191    0
3216    1
3249    0
3262    0
3290    0
3315    3
3331    3
Name: FTR, dtype: object
1.0
12
12.8
Barcelona - visitante
3139    1
3166    0
3187    3
3200    1
3225    0
3232    3
3250    3
3272    3
3291    3
3311    3
Name: FTR, dtype: object
2.0
Vallecano - local
3137    0
3155    3
3171    0
3192    3
3211    3
3240    3
3257    3
3270    0
3295    3
3316    3
Name: FTR, dtype: object
2.1
20
17.3
Sociedad - visitante
3134    1
3153    3
3179    3
3191    3
3219    1
3241    0
3268    1
3285    3
3317    3
3330    1
Name: FTR, dtype: object
1.9
Ath Madrid - local
3135    1
3153    0
3174    3
3204    3
3224    3
3234    3
3256    3
3273    3
3293    3
3313    3
Name: FTR, dtype: object
2.5
20
13.9
Granada - visitante
3131    0
3150    1
3172    0
3198    3
3210    0
3230    1
3251    3
3278    0
3296    0
3319    3

Name: FTR, dtype: object
1.1
Ath Bilbao - local
3131    3
3154    3
3179    0
3194    0
3215    3
3239    0
3254    0
3274    3
3294    1
3314    3
Name: FTR, dtype: object
1.6
11
15.4
Real Madrid - visitante
3136    1
3152    3
3177    3
3206    0
3222    3
3237    1
3252    0
3275    3
3298    0
3312    3
Name: FTR, dtype: object
1.7
Valladolid - local
3132    0
3156    1
3180    0
3209    1
3221    3
3235    3
3250    0
3275    0
3296    3
3310    1
Name: FTR, dtype: object
1.2
14
9.2
Getafe - visitante
3130    1
3151    1
3176    3
3193    0
3212    0
3240    0
3255    0
3276    1
3292    3
3313    0
Name: FTR, dtype: object
0.9
Malaga - local
3142    0
3162    1
3186    3
3203    1
3226    1
3232    0
3252    3
3278    3
3297    3
3317    0
Name: FTR, dtype: object
1.5
16
12.3
Osasuna - visitante
3132    3
3159    0
3170    3
3196    1
3214    0
3245    0
3269    1
3299    1
3318    3
3334    0
Name: FTR, dtype: object
1.2
Levante - local
3138    3
3151    1
3170    0
3197    0
3217    3
3246    3
3271    3
3291    0
3312    0
3333    3
Name: FTR, dtype: object
1.6
15
12.7
La Coruna - visitante
3133    3
3158    0
3189    0
3207    0
3223    0
3231    1
3259    0
3273    0
3294    1
3315    0
Name: FTR, dtype: object
0.5
Espanol - local
3134    1
3164    1
3184    3
3208    3
3229    3
3238    3
3259    3
3279    1
3292    0
3318    0
Name: FTR, dtype: object
1.8
14
11.8
Valencia - visitante
3135    1
3154    0
3175    1
3199    3
3218    3
3248    3
3277    3
3297    0
3310    1
3339    0
Name: FTR, dtype: object
1.5
Betis - local
3130    1
3159    3
3173    3
3190    1
3220    1
3233    3
3253    0
3272    0
3298    3
3319    0
Name: FTR, dtype: object
1.5
12
13.2
Sevilla - visitante
3138    0
3157    0
3178    0
3195    0
3228    1
3236    0
3258    0
3279    1
3293    0
3314    0
Name: FTR, dtype: object
0.2
Sevilla - local
3140    3
3160    3
3189    3
3202    3
3210    3
3245    3
3266    0
3280    0
3301    3
3322    1
Name: FTR, dtype: object
2.2
23
18.3
Ath Bilbao - visitante
3148    0
3167    3
3186    0
3209    1
3220    1
3246    0
3267    3
3288    0
3307    0
3325    3
Name: FTR, dtype: object
1.1
Valencia - local
3145    3
3165    1
3181    3
3200    1
3222    0
3236    3
3255    3
3263    0
3285    0
3306    3
Name: FTR, dtype: object
1.7
18
14.0
Valladolid - visitante
3146    0
3164    1
3171    3
3190    1
3217    0
3243    0
3260    1
3280    3
3304    0
3323    3
Name: FTR, dtype: object
1.2
Osasuna - local
3141    0
3167    0
3185    3
3205    3
3223    3
3237    1
3251    0
3277    0
3289    3
3308    1
Name: FTR, dtype: object
1.4
6
13.6
Espanol - visitante
3142    3
3155    0
3174    0
3194    3
3216    1
3244    0
3264    1
3283    1
3306    0
3321    3
Name: FTR, dtype: object
1.2
Getafe - local
3148    3
3169    3
3188    3
3207    3
3228    1
3230    1
3269    1
3287    3
3304    3
3320    0
Name: FTR, dtype: object
2.1
18
12.9
Ath Madrid - visitante
3141    3
3162    1
3180    3
3192    0
3215    0
3242    1
3265    0
3286    0
3303    3
3326    0
Name: FTR, dtype: object
1.1
Celta - local
3139    1
3152    0
3172    3
3199    0
3219    1
3243    3
3261    0
3284    1
3305    1
3338    1
Name: FTR, dtype: object
1.1
12
12.8
Vallecano - visitante
3144    0
3168    1
3183    0
3202    0
3227    0
3239    3
3263    3
3289    0
3300    0
3328    3
Name: FTR, dtype: object
1.0
Sociedad - local
3146    3
3161    1
3182    1
3201    3
3225    3
3231    1
3258    3
3276    1
3299    1
3300    3
Name: FTR, dtype: object
2.0
22
15.9
Malaga - visitante
3137    3
3156    1
3173    0
3197    3
3213    3
3247    0
3266    3
3287    0
3308    1
3337    1
Name: FTR, dtype: object
1.5
Real Madrid - local
3147    3
3166    3
3183    3
3195    3
3212    3
3241    3
3264    1
3286    3
3307    3
3327    3
Name: FTR, dtype: object
2.8
34
20.4
Levante - visitante
3143    1
3165    1
3182    1
3208    0
3224    0
3233    0
3257    0
3262    3
3284    1
3302    3
Name: FTR, dtype: object
1.0
La Coruna - local
3149    3
3168    1
3177    0
3198    0
3218    0
3247    3
3260    1
3282    0
3302    0
3324    3
Name: FTR, dtype: object
1.1
10
15.6
Zaragoza - visitante
3140    0
3169    0
3185    0
3203    1
3221    0
3234    0
3254    3
3270    3
3281    1
3309    0
Name: FTR, dtype: object
0.8
Barcelona - local
3144    3
3158    3
3178    3
3193    3
3214    3
3244    3
3265    3
3288    3
3309    3
3329    3
Name: FTR, dtype: object
3.0
37
15.4
Mallorca - visitante
3147    0
3163    3
3181    0
3201    0
3229    0
3235    0
3253    3
3271    0
3295    0
3305    1
Name: FTR, dtype: object
0.7
Granada - local
3143    1
3163    0
3187    0
3206    3
3227    3
3248    0
3268    1
3283    1
3303    0
3325    0
Name: FTR, dtype: object
0.9
8
12.0
Betis - visitante
3145    0
3161    1
3184    0
3204    0
3211    0
3249    3
3261    3
3282    3
3301    0
3320    3
Name: FTR, dtype: object
1.3
Betis - local
3159    3
3173    3
3190    1
3220    1
3233    3
3253    0
3272    0
3298    3
3319    0
3339    3
Name: FTR, dtype: object
1.7
13
13.4
Getafe - visitante
3151    1
3176    3
3193    0
3212    0
3240    0
3255    0
3276    1
3292    3
3313    0
3335    3
Name: FTR, dtype: object
1.1
Ath Bilbao - local
3154    3
3179    0
3194    0
3215    3
3239    0
3254    0
3274    3
3294    1
3314    3
3335    0
Name: FTR, dtype: object
1.3
11
16.1
Granada - visitante
3150    1
3172    0
3198    3
3210    0
3230    1
3251    3
3278    0
3296    0
3319    3
3333    0
Name: FTR, dtype: object
1.1
Valladolid - local
3156    1
3180    0
3209    1
3221    3
3235    3
3250    0
3275    0
3296    3
3310    1
3330    1
Name: FTR, dtype: object
1.3
15
9.5
Osasuna - visitante
3159    0
3170    3
3196    1
3214    0
3245    0
3269    1
3299    1
3318    3
3334    0
3354    0
Name: FTR, dtype: object
0.9
Mallorca - local
3157    3
3176    0
3196    1
3213    0
3242    1
3267    0
3281    1
3311    0
3332    0
3350    0
Name: FTR, dtype: object
0.6
11
12.8
La Coruna - visitante
3158    0
3189    0
3207    0
3223    0
3231    1
3259    0
3273    0
3294    1
3315    0
3338    1
Name: FTR, dtype: object
0.3
Espanol - local
3164    1
3184    3
3208    3
3229    3
3238    3
3259    3
3279    1
3292    0
3318    0
3337    1
Name: FTR, dtype: object
1.8
12
12.3
Sociedad - visitante
3153    3
3179    3
3191    3
3219    1
3241    0
3268    1
3285    3
3317    3
3330    1
3358    0
Name: FTR, dtype: object
1.8
Ath Madrid - local
3153    0
3174    3
3204    3
3224    3
3234    3
3256    3
3273    3
3293    3
3313    3
3334    3
Name: FTR, dtype: object
2.7
22
14.9
Valencia - visitante
3154    0
3175    1
3199    3
3218    3
3248    3
3277    3
3297    0
3310    1
3339    0
3351    0
Name: FTR, dtype: object
1.4
Zaragoza - local
3150    1
3175    1
3191    0
3216    1
3249    0
3262    0
3290    0
3315    3
3331    3
3355    0
Name: FTR, dtype: object
0.9
11
12.8
Real Madrid - visitante
3152    3
3177    3
3206    0
3222    3
3237    1
3252    0
3275    3
3298    0
3312    3
3332    3
Name: FTR, dtype: object
1.9
Vallecano - local
3155    3
3171    0
3192    3
3211    3
3240    3
3257    3
3270    0
3295    3
3316    3
3336    0
Name: FTR, dtype: object
2.1
19
17.6
Malaga - visitante
3156    1
3173    0
3197    3
3213    3
3247    0
3266    3
3287    0
3308    1
3337    1
3353    0
Name: FTR, dtype: object
1.2
Levante - local
3151    1
3170    0
3197    0
3217    3
3246    3
3271    3
3291    0
3312    0
3333    3
3351    3
Name: FTR, dtype: object
1.6
15
12.5
Sevilla - visitante
3157    0
3178    0
3195    0
3228    1
3236    0
3258    0
3279    1
3293    0
3314    0
3331    0
Name: FTR, dtype: object
0.2
Celta - local
3152    0
3172    3
3199    0
3219    1
3243    3
3261    0
3284    1
3305    1
3338    1
3359    3
Name: FTR, dtype: object
1.3
12
13.1
Barcelona - visitante
3166    0
3187    3
3200    1
3225    0
3232    3
3250    3
3272    3
3291    3
3311    3
3336    3
Name: FTR, dtype: object
2.2
Sevilla - local
3160    3
3189    3
3202    3
3210    3
3245    3
3266    0
3280    0
3301    3
3322    1
3340    3
Name: FTR, dtype: object
2.2
22
18.8
Zaragoza - visitante
3169    0
3185    0
3203    1
3221    0
3234    0
3254    3
3270    3
3281    1
3309    0
3327    0
Name: FTR, dtype: object
0.8
Osasuna - local
3167    0
3185    3
3205    3
3223    3
3237    1
3251    0
3277    0
3289    3
3308    1
3323    0
Name: FTR, dtype: object
1.4
6
13.4
Ath Madrid - visitante
3162    1
3180    3
3192    0
3215    0
3242    1
3265    0
3286    0
3303    3
3326    0
3341    3
Name: FTR, dtype: object
1.1
Malaga - local
3162    1
3186    3
3203    1
3226    1
3232    0
3252    3
3278    3
3297    3
3317    0
3328    0
Name: FTR, dtype: object
1.5
17
11.9
Espanol - visitante
3155    0
3174    0
3194    3
3216    1
3244    0
3264    1
3283    1
3306    0
3321    3
3357    1
Name: FTR, dtype: object
1.0
Granada - local
3163    0
3187    0
3206    3
3227    3
3248    0
3268    1
3283    1
3303    0
3325    0
3343    0
Name: FTR, dtype: object
0.8
8
11.2
Levante - visitante
3165    1
3182    1
3208    0
3224    0
3233    0
3257    0
3262    3
3284    1
3302    3
3322    1
Name: FTR, dtype: object
1.0
Barcelona - local
3158    3
3178    3
3193    3
3214    3
3244    3
3265    3
3288    3
3309    3
3329    3
3352    1
Name: FTR, dtype: object
2.8
36
14.5
Vallecano - visitante
3168    1
3183    0
3202    0
3227    0
3239    3
3263    3
3289    0
3300    0
3328    3
3345    0
Name: FTR, dtype: object
1.0
Valencia - local
3165    1
3181    3
3200    1
3222    0
3236    3
3255    3
3263    0
3285    0
3306    3
3326    3
Name: FTR, dtype: object
1.7
17
13.1
Betis - visitante
3161    1
3184    0
3204    0
3211    0
3249    3
3261    3
3282    3
3301    0
3320    3
3342    1
Name: FTR, dtype: object
1.4
Sociedad - local
3161    1
3182    1
3201    3
3225    3
3231    1
3258    3
3276    1
3299    1
3300    3
3321    0
Name: FTR, dtype: object
1.7
18
15.5
Valladolid - visitante
3164    1
3171    3
3190    1
3217    0
3243    0
3260    1
3280    3
3304    0
3323    3
3348    0
Name: FTR, dtype: object
1.2
Real Madrid - local
3166    3
3183    3
3195    3
3212    3
3241    3
3264    1
3286    3
3307    3
3327    3
3347    3
Name: FTR, dtype: object
2.8
31
20.4
Mallorca - visitante
3163    3
3181    0
3201    0
3229    0
3235    0
3253    3
3271    0
3295    0
3305    1
3324    0
Name: FTR, dtype: object
0.7
Getafe - local
3169    3
3188    3
3207    3
3228    1
3230    1
3269    1
3287    3
3304    3
3320    0
3344    0
Name: FTR, dtype: object
1.8
17
12.8

Ath Bilbao - visitante
3167    3
3186    0
3209    1
3220    1
3246    0
3267    3
3288    0
3307    0
3325    3
3346    0
Name: FTR, dtype: object
1.1
La Coruna - local
3168    1
3177    0
3198    0
3218    0
3247    3
3260    1
3282    0
3302    0
3324    3
3349    0
Name: FTR, dtype: object
0.8
11
15.2
Celta - visitante
3160    0
3188    0
3205    0
3226    1
3238    0
3256    0
3274    0
3290    3
3316    0
3329    0
Name: FTR, dtype: object
0.4
Zaragoza - local
3175    1
3191    0
3216    1
3249    0
3262    0
3290    0
3315    3
3331    3
3355    0
3377    3
Name: FTR, dtype: object
1.1
14
13.0
Granada - visitante
3172    0
3198    3
3210    0
3230    1
3251    3
3278    0
3296    0
3319    3
3333    0
3350    3
Name: FTR, dtype: object
1.3
Levante - local
3170    0
3197    0
3217    3
3246    3
3271    3
3291    0
3312    0
3333    3
3351    3
3374    3
Name: FTR, dtype: object
1.8
17
12.5
Getafe - visitante
3176    3
3193    0
3212    0
3240    0
3255    0
3276    1
3292    3
3313    0
3335    3
3355    3
Name: FTR, dtype: object
1.3
Celta - local
3172    3
3199    0
3219    1
3243    3
3261    0
3284    1
3305    1
3338    1
3359    3
3378    3
Name: FTR, dtype: object
1.6
13
12.6
Real Madrid - visitante
3177    3
3206    0
3222    3
3237    1
3252    0
3275    3
3298    0
3312    3
3332    3
3352    1
Name: FTR, dtype: object
1.7
Ath Madrid - local
3174    3
3204    3
3224    3
3234    3
3256    3
3273    3
3293    3
3313    3
3334    3
3353    3
Name: FTR, dtype: object
3.0
24
13.7
Sociedad - visitante
3179    3
3191    3
3219    1
3241    0
3268    1
3285    3
3317    3
3330    1
3358    0
3374    0
Name: FTR, dtype: object
1.5
Ath Bilbao - local
3179    0
3194    0
3215    3
3239    0
3254    0
3274    3
3294    1
3314    3
3335    0
3354    3
Name: FTR, dtype: object
1.3
11
17.0
Valencia - visitante
3175    1
3199    3
3218    3
3248    3
3277    3
3297    0
3310    1
3339    0
3351    0
3373    0
Name: FTR, dtype: object
1.4
Vallecano - local
3171    0
3192    3
3211    3
3240    3
3257    3
3270    0
3295    3
3316    3
3336    0
3356    3
Name: FTR, dtype: object
2.1
19
17.4
Espanol - visitante
3174    0
3194    3
3216    1
3244    0
3264    1
3283    1
3306    0
3321    3
3357    1
3379    0
Name: FTR, dtype: object
1.0
Valladolid - local
3180    0
3209    1
3221    3
3235    3
3250    0
3275    0
3296    3
3310    1
3330    1
3357    1
Name: FTR, dtype: object
1.3
15
9.8
Malaga - visitante
3173    0
3197    3
3213    3
3247    0
3266    3
3287    0
3308    1
3337    1
3353    0
3376    1
Name: FTR, dtype: object
1.2
Mallorca - local
3176    0
3196    1
3213    0
3242    1
3267    0
3281    1
3311    0
3332    0
3350    0
3373    3
Name: FTR, dtype: object
0.6
11
12.4
Sevilla - visitante
3178    0
3195    0
3228    1
3236    0
3258    0
3279    1
3293    0
3314    0
3331    0
3359    0
Name: FTR, dtype: object
0.2
Barcelona - local
3178    3
3193    3
3214    3
3244    3
3265    3
3288    3
3309    3
3329    3
3352    1
3380    3
Name: FTR, dtype: object
2.8
36
15.3
La Coruna - visitante
3189    0
3207    0
3223    0
3231    1
3259    0
3273    0
3294    1
3315    0
3338    1
3356    0
Name: FTR, dtype: object
0.3
Betis - local
3173    3
3190    1
3220    1
3233    3
3253    0
3272    0
3298    3
3319    0
3339    3
3358    3
Name: FTR, dtype: object
1.7
13
13.7
Osasuna - visitante
3170    3
3196    1
3214    0
3245    0
3269    1
3299    1
3318    3
3334    0
3354    0
3377    0
Name: FTR, dtype: object
0.9
Sevilla - local
3189    3
3202    3
3210    3
3245    3
3266    0
3280    0
3301    3
3322    1
3340    3
3368    0
Name: FTR, dtype: object
1.9
20
18.4
Celta - visitante
3188    0
3205    0
3226    1
3238    0
3256    0
3274    0
3290    3
3316    0
3329    0
3347    0
Name: FTR, dtype: object
0.4
Sociedad - local
3182    1
3201    3
3225    3
3231    1
3258    3
3276    1
3299    1
3300    3
3321    0
3341    0
Name: FTR, dtype: object
1.6
15
15.6
Betis - visitante
3184    0
3204    0
3211    0
3249    3
3261    3
3282    3
3301    0
3320    3
3342    1
3369    0
Name: FTR, dtype: object
1.3
Malaga - local
3186    3
3203    1
3226    1
3232    0
3252    3
3278    3
3297    3
3317    0
3328    0
3348    3
Name: FTR, dtype: object
1.7
19
12.8
Ath Madrid - visitante
3180    3
3192    0
3215    0
3242    1
3265    0
3286    0
3303    3
3326    0
3341    3
3365    3
Name: FTR, dtype: object
1.3
Granada - local
3187    0
3206    3
3227    3
3248    0
3268    1
3283    1
3303    0
3325    0
3343    0
3364    3
Name: FTR, dtype: object
1.1
9
10.9
Mallorca - visitante
3181    0
3201    0
3229    0
3235    0
3253    3
3271    0
3295    0
3305    1
3324    0
3340    0
Name: FTR, dtype: object
0.4
Espanol - local
3184    3
3208    3
3229    3
3238    3
3259    3
3279    1
3292    0
3318    0
3337    1
3345    3
Name: FTR, dtype: object
2.0
15
12.5
Valladolid - visitante
3171    3
3190    1
3217    0
3243    0
3260    1
3280    3
3304    0
3323    3
3348    0
3375    0
Name: FTR, dtype: object
1.1
Valencia - local
3181    3
3200    1
3222    0
3236    3
3255    3
3263    0
3285    0
3306    3
3326    3
3346    3
Name: FTR, dtype: object
1.9
18
13.9
Levante - visitante
3182    1
3208    0
3224    0
3233    0
3257    0
3262    3
3284    1
3302    3
3322    1
3344    3
Name: FTR, dtype: object
1.2
Real Madrid - local
3183    3
3195    3
3212    3
3241    3
3264    1
3286    3
3307    3
3327    3
3347    3
3362    3
Name: FTR, dtype: object
2.8
34
21.3
Barcelona - visitante
3187    3
3200    1
3225    0
3232    3
3250    3
3272    3
3291    3
3311    3
3336    3
3349    3
Name: FTR, dtype: object
2.5
Osasuna - local
3185    3
3205    3
3223    3
3237    1
3251    0
3277    0
3289    3
3308    1
3323    0
3342    1
Name: FTR, dtype: object
1.5
6
12.7
Ath Bilbao - visitante
3186    0
3209    1
3220    1
3246    0
3267    3
3288    0
3307    0
3325    3
3346    0
3367    0
Name: FTR, dtype: object
0.8
La Coruna - local
3177    0
3198    0
3218    0
3247    3
3260    1
3282    0
3302    0
3324    3
3349    0
3372    0
Name: FTR, dtype: object
0.7
11
15.3
Vallecano - visitante
3183    0
3202    0
3227    0
3239    3
3263    3
3289    0
3300    0
3328    3
3345    0
3361    0
Name: FTR, dtype: object
0.9
Getafe - local
3188    3
3207    3
3228    1
3230    1
3269    1
3287    3
3304    3
3320    0
3344    0
3360    3
Name: FTR, dtype: object
1.8
16
14.6
Zaragoza - visitante
3185    0
3203    1
3221    0
3234    0
3254    3
3270    3
3281    1
3309    0
3327    0
3343    3
Name: FTR, dtype: object
1.1
Levante - local
3197    0
3217    3
3246    3
3271    3
3291    0
3312    0
3333    3
3351    3
3374    3
3393    3
Name: FTR, dtype: object
2.1
20
12.8
Osasuna - visitante
3196    1
3214    0
3245    0
3269    1
3299    1
3318    3
3334    0
3354    0
3377    0
3399    0
Name: FTR, dtype: object
0.6
Vallecano - local
3192    3
3211    3
3240    3
3257    3
3270    0
3295    3
3316    3
3336    0
3356    3
3371    0
Name: FTR, dtype: object
2.1
18
16.9
Valladolid - visitante
3190    1
3217    0
3243    0
3260    1
3280    3
3304    0
3323    3
3348    0
3375    0
3395    0
Name: FTR, dtype: object
0.8
Celta - local
3199    0
3219    1
3243    3
3261    0
3284    1
3305    1
3338    1
3359    3
3378    3
3399    3
Name: FTR, dtype: object
1.6
13
12.5
Granada - visitante
3198    3
3210    0
3230    1
3251    3
3278    0
3296    0
3319    3
3333    0
3350    3
3380    0
Name: FTR, dtype: object
1.3
Betis - local
3190    1
3220    1
3233    3
3253    0
3272    0
3298    3
3319    0
3339    3
3358    3
3370    0
Name: FTR, dtype: object
1.4
12
12.2
Malaga - visitante
3197    3
3213    3
3247    0
3266    3
3287    0
3308    1
3337    1
3353    0
3376    1
3396    3
Name: FTR, dtype: object
1.5
Ath Madrid - local
3204    3
3224    3
3234    3
3256    3
3273    3
3293    3
3313    3
3334    3
3353    3
3375    3
Name: FTR, dtype: object
3.0
25
14.1
Espanol - visitante
3194    3
3216    1
3244    0
3264    1
3283    1
3306    0
3321    3
3357    1
3379    0
3393    0
Name: FTR, dtype: object
1.0
Zaragoza - local
3191    0
3216    1
3249    0
3262    0
3290    0
3315    3
3331    3
3355    0
3377    3
3396    0
Name: FTR, dtype: object
1.0
12
12.7
Valencia - visitante
3199    3
3218    3
3248    3
3277    3
3297    0
3310    1
3339    0
3351    0
3373    0
3394    0
Name: FTR, dtype: object
1.3
Mallorca - local
3196    1
3213    0
3242    1
3267    0
3281    1
3311    0
3332    0
3350    0
3373    3
3397    3
Name: FTR, dtype: object
0.9
11
12.4
Getafe - visitante
3193    0
3212    0
3240    0
3255    0
3276    1
3292    3
3313    0
3335    3
3355    3
3378    0
Name: FTR, dtype: object
1.0
La Coruna - local
3198    0
3218    0
3247    3
3260    1
3282    0
3302    0
3324    3
3349    0
3372    0
3398    1
Name: FTR, dtype: object
0.8
11
14.8
Real Madrid - visitante
3206    0
3222    3
3237    1
3252    0
3275    3
3298    0
3312    3
3332    3
3352    1
3371    3
Name: FTR, dtype: object
1.7
Barcelona - local
3193    3
3214    3
3244    3
3265    3
3288    3
3309    3
3329    3
3352    1
3380    3
3394    3
Name: FTR, dtype: object
2.8
35
14.7
Sevilla - visitante
3195    0
3228    1
3236    0
3258    0
3279    1
3293    0
3314    0
3331    0
3359    0
3372    3
Name: FTR, dtype: object
0.5
Ath Bilbao - local
3194    0
3215    3
3239    0
3254    0
3274    3
3294    1
3314    3
3335    0
3354    3
3376    1
Name: FTR, dtype: object
1.4
10
16.1
Sociedad - visitante
3191    3
3219    1
3241    0
3268    1
3285    3
3317    3
3330    1
3358    0
3374    0
3397    0
Name: FTR, dtype: object
1.2
Valladolid - local
3209    1
3221    3
3235    3
3250    0
3275    0
3296    3
3310    1
3330    1
3357    1
3361    3
Name: FTR, dtype: object
1.6
21
10.9
Ath Madrid - visitante
3192    0
3215    0
3242    1
3265    0
3286    0
3303    3
3326    0
3341    3
3365    3
3370    3
Name: FTR, dtype: object
1.3
Valencia - local
3200    1
3222    0
3236    3
3255    3
3263    0
3285    0
3306    3
3326    3
3346    3
3366    3
Name: FTR, dtype: object
1.9
18
14.8
Mallorca - visitante
3201    0
3229    0
3235    0
3253    3
3271    0
3295    0
3305    1
3324    0
3340    0
3360    0
Name: FTR, dtype: object
0.4
Sociedad - local
3201    3
3225    3
3231    1
3258    3
3276    1
3299    1
3300    3
3321    0
3341    0
3367    3
Name: FTR, dtype: object
1.8
16
16.3
Levante - visitante
3208    0
3224    0
3233    0
3257    0
3262    3
3284    1
3302    3
3322    1
3344    3
3363    0
Name: FTR, dtype: object
1.1
Real Madrid - local
3195    3
3212    3
3241    3
3264    1
3286    3
3307    3
3327    3
3347    3
3362    3
3392    3
Name: FTR, dtype: object
2.8
35
22.5
Vallecano - visitante
3202    0
3227    0
3239    3
3263    3
3289    0
3300    0
3328    3
3345    0
3361    0
3386    0
Name: FTR, dtype: object
0.9
Espanol - local
3208    3
3229    3
3238    3
3259    3
3279    1
3292    0
3318    0
3337    1
3345    3
3365    0

Name: FTR, dtype: object
1.7
14
12.8
Betis - visitante
3204    0
3211    0
3249    3
3261    3
3282    3
3301    0
3320    3
3342    1
3369    0
3381    3
Name: FTR, dtype: object
1.6
Osasuna - local
3205    3
3223    3
3237    1
3251    0
3277    0
3289    3
3308    1
3323    0
3342    1
3363    3
Name: FTR, dtype: object
1.5
9
13.5
Zaragoza - visitante
3203    1
3221    0
3234    0
3254    3
3270    3
3281    1
3309    0
3327    0
3343    3
3366    0
Name: FTR, dtype: object
1.1
Malaga - local
3203    1
3226    1
3232    0
3252    3
3278    3
3297    3
3317    0
3328    0
3348    3
3369    3
Name: FTR, dtype: object
1.7
22
13.7
Ath Bilbao - visitante
3209    1
3220    1
3246    0
3267    3
3288    0
3307    0
3325    3
3346    0
3367    0
3385    1
Name: FTR, dtype: object
0.9
Granada - local
3206    3
3227    3
3248    0
3268    1
3283    1
3303    0
3325    0
3343    0
3364    3
3384    1
Name: FTR, dtype: object
1.2
9
11.6
Barcelona - visitante
3200    1
3225    0
3232    3
3250    3
3272    3
3291    3
3311    3
3336    3
3349    3
3368    3
Name: FTR, dtype: object
2.5
Getafe - local
3207    3
3228    1
3230    1
3269    1
3287    3
3304    3
3320    0
3344    0
3360    3
3390    0
Name: FTR, dtype: object
1.5
14
13.7
Celta - visitante
3205    0
3226    1
3238    0
3256    0
3274    0
3290    3
3316    0
3329    0
3347    0
3364    0
Name: FTR, dtype: object
0.4
Sevilla - local
3202    3
3210    3
3245    3
3266    0
3280    0
3301    3
3322    1
3340    3
3368    0
3388    3
Name: FTR, dtype: object
1.9
18
17.4
La Coruna - visitante
3207    0
3223    0
3231    1
3259    0
3273    0
3294    1
3315    0
3338    1
3356    0
3362    0
Name: FTR, dtype: object
0.3
Betis - local
3220    1
3233    3
3253    0
3272    0
3298    3
3319    0
3339    3
3358    3
3370    0
3379    3
Name: FTR, dtype: object
1.6
13
11.5
Valladolid - visitante
3217    0
3243    0
3260    1
3280    3
3304    0
3323    3
3348    0
3375    0
3395    0
3410    3
Name: FTR, dtype: object
1.0
Zaragoza - local
3216    1
3249    0
3262    0
3290    0
3315    3
3331    3
3355    0
3377    3
3396    0
3410    0
Name: FTR, dtype: object
1.0
11
12.8
Sociedad - visitante
3219    1
3241    0
3268    1
3285    3
3317    3
3330    1
3358    0
3374    0
3397    0
3415    0
Name: FTR, dtype: object
0.9
Vallecano - local
3211    3
3240    3
3257    3
3270    0
3295    3
3316    3
3336    0
3356    3
3371    0
3391    1
Name: FTR, dtype: object
1.9
16
17.2
Ath Madrid - visitante
3215    0
3242    1
3265    0
3286    0
3303    3
3326    0
3341    3
3365    3
3370    3
3414    1
Name: FTR, dtype: object
1.4
Barcelona - local
3214    3
3244    3
3265    3
3288    3
3309    3
3329    3
3352    1
3380    3
3394    3
3415    3
Name: FTR, dtype: object
2.8
34
14.8
Getafe - visitante
3212    0
3240    0
3255    0
3276    1
3292    3
3313    0
3335    3
3355    3
3378    0
3398    1
Name: FTR, dtype: object
1.1
Ath Bilbao - local
3215    3
3239    0
3254    0
3274    3
3294    1
3314    3
3335    0
3354    3
3376    1
3395    3
Name: FTR, dtype: object
1.7
12
16.2
Espanol - visitante
3216    1
3244    0
3264    1
3283    1
3306    0
3321    3
3357    1
3379    0
3393    0
3418    0
Name: FTR, dtype: object
0.7
Real Madrid - local
3212    3
3241    3
3264    1
3286    3
3307    3
3327    3
3347    3
3362    3
3392    3
3413    1
Name: FTR, dtype: object
2.6
32
23.1
Sevilla - visitante
3228    1
3236    0
3258    0
3279    1
3293    0
3314    0
3331    0
3359    0
3372    3
3391    1
Name: FTR, dtype: object
0.6
Mallorca - local
3213    0
3242    1
3267    0
3281    1
3311    0
3332    0
3350    0
3373    3
3397    3
3418    3
Name: FTR, dtype: object
1.1
12
12.9
Osasuna - visitante
3214    0
3245    0
3269    1
3299    1
3318    3
3334    0
3354    0
3377    0
3399    0
3412    0
Name: FTR, dtype: object
0.5
Levante - local
3217    3
3246    3
3271    3
3291    0
3312    0
3333    3
3351    3
3374    3
3393    3
3414    1
Name: FTR, dtype: object
2.2
20
12.2
Malaga - visitante
3213    3
3247    0
3266    3
3287    0
3308    1
3337    1
3353    0
3376    1
3396    3
3419    3
Name: FTR, dtype: object
1.5
La Coruna - local
3218    0
3247    3
3260    1
3282    0
3302    0
3324    3
3349    0
3372    0
3398    1
3412    3
Name: FTR, dtype: object
1.1
13
14.2
Granada - visitante
3210    0
3230    1
3251    3
3278    0
3296    0
3319    3
3333    0
3350    3
3380    0
3392    0
Name: FTR, dtype: object
1.0
Celta - local
3219    1
3243    3
3261    0
3284    1
3305    1
3338    1
3359    3
3378    3
3399    3
3419    0
Name: FTR, dtype: object
1.6
13
13.6
Valencia - visitante
3218    3
3248    3
3277    3
3297    0
3310    1
3339    0
3351    0
3373    0
3394    0
3413    1
Name: FTR, dtype: object
1.1
Valencia - local
3222    0
3236    3
3255    3
3263    0
3285    0
3306    3
3326    3
3346    3
3366    3
3387    3
Name: FTR, dtype: object
2.1
19
14.6
Barcelona - visitante
3225    0
3232    3
3250    3
3272    3
3291    3
3311    3
3336    3
3349    3
3368    3
3390    3
Name: FTR, dtype: object
2.7
Sociedad - local
3225    3
3231    1
3258    3
3276    1
3299    1
3300    3
3321    0
3341    0
3367    3
3382    3
Name: FTR, dtype: object
1.8
15
14.3
Mallorca - visitante
3229    0
3235    0
3253    3
3271    0
3295    0
3305    1
3324    0
3340    0
3360    0
3383    1
Name: FTR, dtype: object
0.5
Sevilla - local
3210    3
3245    3
3266    0
3280    0
3301    3
3322    1
3340    3
3368    0
3388    3
3417    3
Name: FTR, dtype: object
1.9
18
17.4
Vallecano - visitante
3227    0
3239    3
3263    3
3289    0
3300    0
3328    3
3345    0
3361    0
3386    0
3409    3
Name: FTR, dtype: object
1.2
Malaga - local
3226    1
3232    0
3252    3
3278    3
3297    3
3317    0
3328    0
3348    3
3369    3
3389    3
Name: FTR, dtype: object
1.9
24
14.2
Zaragoza - visitante
3221    0
3234    0
3254    3
3270    3
3281    1
3309    0
3327    0
3343    3
3366    0
3382    0
Name: FTR, dtype: object
1.0
Ath Madrid - local
3224    3
3234    3
3256    3
3273    3
3293    3
3313    3
3334    3
3353    3
3375    3
3386    3
Name: FTR, dtype: object
3.0
28
13.9
Betis - visitante
3211    0
3249    3
3261    3
3282    3
3301    0
3320    3
3342    1
3369    0
3381    3
3416    3
Name: FTR, dtype: object
1.9
Osasuna - local
3223    3
3237    1
3251    0
3277    0
3289    3
3308    1
3323    0
3342    1
3363    3
3383    1
Name: FTR, dtype: object
1.3
9
13.8
Celta - visitante
3226    1
3238    0
3256    0
3274    0
3290    3
3316    0
3329    0
3347    0
3364    0
3387    0
Name: FTR, dtype: object
0.4
Granada - local
3227    3
3248    0
3268    1
3283    1
3303    0
3325    0
3343    0
3364    3
3384    1
3404    1
Name: FTR, dtype: object
1.0
9
13.0
Real Madrid - visitante
3222    3
3237    1
3252    0
3275    3
3298    0
3312    3
3332    3
3352    1
3371    3
3388    0
Name: FTR, dtype: object
1.7
Getafe - local
3228    1
3230    1
3269    1
3287    3
3304    3
3320    0
3344    0
3360    3
3390    0
3405    3
Name: FTR, dtype: object
1.5
13
13.6
La Coruna - visitante
3223    0
3231    1
3259    0
3273    0
3294    1
3315    0
3338    1
3356    0
3362    0
3384    1
Name: FTR, dtype: object
0.4
Espanol - local
3229    3
3238    3
3259    3
3279    1
3292    0
3318    0
3337    1
3345    3
3365    0
3385    1
Name: FTR, dtype: object
1.5
14
13.0
Levante - visitante
3224    0
3233    0
3257    0
3262    3
3284    1
3302    3
3322    1
3344    3
3363    0
3389    0
Name: FTR, dtype: object
1.1
Valladolid - local
3221    3
3235    3
3250    0
3275    0
3296    3
3310    1
3330    1
3357    1
3361    3
3381    0
Name: FTR, dtype: object
1.5
19
10.9
Ath Bilbao - visitante
3220    1
3246    0
3267    3
3288    0
3307    0
3325    3
3346    0
3367    0
3385    1
3401    0
Name: FTR, dtype: object
0.8
Sevilla - local
3245    3
3266    0
3280    0
3301    3
3322    1
3340    3
3368    0
3388    3
3417    3
3433    3
Name: FTR, dtype: object
1.9
20
16.6
Granada - visitante
3230    1
3251    3
3278    0
3296    0
3319    3
3333    0
3350    3
3380    0
3392    0
3411    0
Name: FTR, dtype: object
1.0
Vallecano - local
3240    3
3257    3
3270    0
3295    3
3316    3
3336    0
3356    3
3371    0
3391    1
3411    3
Name: FTR, dtype: object
1.9
14
17.8
Betis - visitante
3249    3
3261    3
3282    3
3301    0
3320    3
3342    1
3369    0
3381    3
3416    3
3432    0
Name: FTR, dtype: object
1.9
Real Madrid - local
3241    3
3264    1
3286    3
3307    3
3327    3
3347    3
3362    3
3392    3
3413    1
3423    3
Name: FTR, dtype: object
2.6
32
23.2
Getafe - visitante
3240    0
3255    0
3276    1
3292    3
3313    0
3335    3
3355    3
3378    0
3398    1
3417    0
Name: FTR, dtype: object
1.1
Mallorca - local
3242    1
3267    0
3281    1
3311    0
3332    0
3350    0
3373    3
3397    3
3418    3
3435    3
Name: FTR, dtype: object
1.4
11
11.6
Malaga - visitante
3247    0
3266    3
3287    0
3308    1
3337    1
3353    0
3376    1
3396    3
3419    3
3438    0
Name: FTR, dtype: object
1.2
Barcelona - local
3244    3
3265    3
3288    3
3309    3
3329    3
3352    1
3380    3
3394    3
3415    3
3437    3
Name: FTR, dtype: object
2.8
33
14.3
Osasuna - visitante
3245    0
3269    1
3299    1
3318    3
3334    0
3354    0
3377    0
3399    0
3412    0
3422    3
Name: FTR, dtype: object
0.8
Ath Bilbao - local
3239    0
3254    0
3274    3
3294    1
3314    3
3335    0
3354    3
3376    1
3395    3
3416    0
Name: FTR, dtype: object
1.4
12
15.7
Ath Madrid - visitante
3242    1
3265    0
3286    0
3303    3
3326    0
3341    3
3365    3
3370    3
3414    1
3420    3
Name: FTR, dtype: object
1.7
Zaragoza - local
3249    0
3262    0
3290    0
3315    3
3331    3
3355    0
3377    3
3396    0
3410    0
3430    3
Name: FTR, dtype: object
1.2
13
14.3
Espanol - visitante
3244    0
3264    1
3283    1
3306    0
3321    3
3357    1
3379    0
3393    0
3418    0
3437    0
Name: FTR, dtype: object
0.6
Levante - local
3246    3
3271    3
3291    0
3312    0
3333    3
3351    3
3374    3
3393    3
3414    1
3425    3
Name: FTR, dtype: object
2.2
21
11.8
Valladolid - visitante
3243    0
3260    1
3280    3
3304    0
3323    3
3348    0
3375    0
3395    0
3410    3
Name: FTR, dtype: object
1.1111111111111112
La Coruna - local
3247    3
3260    1
3282    0
3302    0
3324    3
3349    0
3372    0
3398    1
3412    3
Name: FTR, dtype: object
1.2222222222222223
11
14.555555555555555
Valencia - visitante
3248    3
3277    3
3297    0
3310    1
3339    0
3351    0
3373    0
3394    0
3413    1
3428    0
Name: FTR, dtype: object
0.8
Celta - local
3243    3
3261    0
3284    1
3305    1
3338    1
3359    3
3378    3
3399    3
3419    0
Name: FTR, dtype: object
1.6666666666666667
12
13.88888888888889
Sociedad - visitante
3241    0
3268    1
3285    3
3317    3
3330    1
3358    0
3374    0
3397    0
3415    0
3434    0

Name: FTR, dtype: object
0.8
Betis - local
3233    3
3253    0
3272    0
3298    3
3319    0
3339    3
3358    3
3370    0
3379    3
3409    0
Name: FTR, dtype: object
1.5
13
11.9
Ath Bilbao - visitante
3246    0
3267    3
3288    0
3307    0
3325    3
3346    0
3367    0
3385    1
3401    0
3425    0
Name: FTR, dtype: object
0.7
Valladolid - local
3235    3
3250    0
3275    0
3296    3
3310    1
3330    1
3357    1
3361    3
3381    0
3400    3
Name: FTR, dtype: object
1.5
19
11.1
Zaragoza - visitante
3234    0
3254    3
3270    3
3281    1
3309    0
3327    0
3343    3
3366    0
3382    0
3408    3
Name: FTR, dtype: object
1.3
Valencia - local
3236    3
3255    3
3263    0
3285    0
3306    3
3326    3
3346    3
3366    3
3387    3
3402    1
Name: FTR, dtype: object
2.2
22
13.9
Real Madrid - visitante
3237    1
3252    0
3275    3
3298    0
3312    3
3332    3
3352    1
3371    3
3388    0
3405    0
Name: FTR, dtype: object
1.4
Osasuna - local
3237    1
3251    0
3277    0
3289    3
3308    1
3323    0
3342    1
3363    3
3383    1
3403    0
Name: FTR, dtype: object
1.0
8
14.7
La Coruna - visitante
3231    1
3259    0
3273    0
3294    1
3315    0
3338    1
3356    0
3362    0
3384    1
3402    1
Name: FTR, dtype: object
0.5
Ath Madrid - local
3234    3
3256    3
3273    3
3293    3
3313    3
3334    3
3353    3
3375    3
3386    3
3401    3
Name: FTR, dtype: object
3.0
30
14.9
Levante - visitante
3233    0
3257    0
3262    3
3284    1
3302    3
3322    1
3344    3
3363    0
3389    0
3400    0
Name: FTR, dtype: object
1.1
Sociedad - local
3231    1
3258    3
3276    1
3299    1
3300    3
3321    0
3341    0
3367    3
3382    3
3406    3
Name: FTR, dtype: object
1.8
14
14.4
Barcelona - visitante
3232    3
3250    3
3272    3
3291    3
3311    3
3336    3
3349    3
3368    3
3390    3
3403    3
Name: FTR, dtype: object
3.0
Malaga - local
3232    0
3252    3
3278    3
3297    3
3317    0
3328    0
3348    3
3369    3
3389    3
3407    1
Name: FTR, dtype: object
1.9
24
14.9
Celta - visitante
3238    0
3256    0
3274    0
3290    3
3316    0
3329    0
3347    0
3364    0
3387    0
3406    0
Name: FTR, dtype: object
0.3
Granada - local
3248    0
3268    1
3283    1
3303    0
3325    0
3343    0
3364    3
3384    1
3404    1
3436    0
Name: FTR, dtype: object
0.7
8
13.0
Vallecano - visitante
3239    3
3263    3
3289    0
3300    0
3328    3
3345    0
3361    0
3386    0
3409    3
3433    0
Name: FTR, dtype: object
1.2
Getafe - local
3230    1
3269    1
3287    3
3304    3
3320    0
3344    0
3360    3
3390    0
3405    3
3426    0
Name: FTR, dtype: object
1.4
12
13.1
Sevilla - visitante
3236    0
3258    0
3279    1
3293    0
3314    0
3331    0
3359    0
3372    3
3391    1
3404    1
Name: FTR, dtype: object
0.6
Espanol - local
3238    3
3259    3
3279    1
3292    0
3318    0
3337    1
3345    3
3365    0
3385    1
3408    0
Name: FTR, dtype: object
1.2
12
12.1
Mallorca - visitante
3235    0
3253    3
3271    0
3295    0
3305    1
3324    0
3340    0
3360    0
3383    1
3407    1
Name: FTR, dtype: object
0.6
Getafe - local
3269    1
3287    3
3304    3
3320    0
3344    0
3360    3
3390    0
3405    3
3426    0
3449    1
Name: FTR, dtype: object
1.4
11
13.1
Granada - visitante
3251    3
3278    0
3296    0
3319    3
3333    0
3350    3
3380    0
3392    0
3411    0
3421    0
Name: FTR, dtype: object
0.9
Sociedad - local
3258    3
3276    1
3299    1
3300    3
3321    0
3341    0
3367    3
3382    3
3406    3
3428    3
Name: FTR, dtype: object
2.0
14
14.6
La Coruna - visitante
3259    0
3273    0
3294    1
3315    0
3338    1
3356    0
3362    0
3384    1
3402    1
Name: FTR, dtype: object
0.4444444444444444
Malaga - local
3252    3
3278    3
3297    3
3317    0
3328    0
3348    3
3369    3
3389    3
3407    1
3424    3
Name: FTR, dtype: object
2.2
24
16.4
Barcelona - visitante
3250    3
3272    3
3291    3
3311    3
3336    3
3349    3
3368    3
3390    3
3403    3
3429    1
Name: FTR, dtype: object
2.8
Betis - local
3253    0
3272    0
3298    3
3319    0
3339    3
3358    3
3370    0
3379    3
3409    0
3429    1
Name: FTR, dtype: object
1.3
13
11.1
Levante - visitante
3257    0
3262    3
3284    1
3302    3
3322    1
3344    3
3363    0
3389    0
3400    0
3435    0
Name: FTR, dtype: object
1.1
Ath Madrid - local
3256    3
3273    3
3293    3
3313    3
3334    3
3353    3
3375    3
3386    3
3401    3
3438    3
Name: FTR, dtype: object
3.0
30
14.4
Zaragoza - visitante
3254    3
3270    3
3281    1
3309    0
3327    0
3343    3
3366    0
3382    0
3408    3
3426    3
Name: FTR, dtype: object
1.6
Valladolid - local
3250    0
3275    0
3296    3
3310    1
3330    1
3357    1
3361    3
3381    0
3400    3
Name: FTR, dtype: object
1.3333333333333333
16
10.777777777777779
Mallorca - visitante
3253    3
3271    0
3295    0
3305    1
3324    0
3340    0
3360    0
3383    1
3407    1
3423    0
Name: FTR, dtype: object
0.6
Valencia - local
3255    3
3263    0
3285    0
3306    3
3326    3
3346    3
3366    3
3387    3
3402    1
3431    3
Name: FTR, dtype: object
2.2
21
13.9
Sevilla - visitante
3258    0
3279    1
3293    0
3314    0
3331    0
3359    0
3372    3
3391    1
3404    1
3427    1
Name: FTR, dtype: object
0.7
Osasuna - local
3251    0
3277    0
3289    3
3308    1
3323    0
3342    1
3363    3
3383    1
3403    0
3434    3
Name: FTR, dtype: object
1.2
9
15.2
Real Madrid - visitante
3252    0
3275    3
3298    0
3312    3
3332    3
3352    1
3371    3
3388    0
3405    0
3436    3
Name: FTR, dtype: object
1.6
Espanol - local
3259    3
3279    1
3292    0
3318    0
3337    1
3345    3
3365    0
3385    1
3408    0
3427    1
Name: FTR, dtype: object
1.0
12
11.6
Celta - visitante
3256    0
3274    0
3290    3
3316    0
3329    0
3347    0
3364    0
3387    0
3406    0
Name: FTR, dtype: object
0.3333333333333333
Ath Bilbao - local
3254    0
3274    3
3294    1
3314    3
3335    0
3354    3
3376    1
3395    3
3416    0
3439    1
Name: FTR, dtype: object
1.5
11
15.5
Vallecano - visitante
3263    3
3289    0
3300    0
3328    3
3345    0
3361    0
3386    0
3409    3
3433    0
3443    0
Name: FTR, dtype: object
0.9
Vallecano - local
3257    3
3270    0
3295    3
3316    3
3336    0
3356    3
3371    0
3391    1
3411    3
3421    3
Name: FTR, dtype: object
1.9
12
17.2
Getafe - visitante
3255    0
3276    1
3292    3
3313    0
3335    3
3355    3
3378    0
3398    1
3417    0
3439    1
Name: FTR, dtype: object
1.2
Real Madrid - local
3264    1
3286    3
3307    3
3327    3
3347    3
3362    3
3392    3
3413    1
3423    3
3452    3
Name: FTR, dtype: object
2.6
31
22.2
Sociedad - visitante
3268    1
3285    3
3317    3
3330    1
3358    0
3374    0
3397    0
3415    0
3434    0
3445    1
Name: FTR, dtype: object
0.9
Mallorca - local
3267    0
3281    1
3311    0
3332    0
3350    0
3373    3
3397    3
3418    3
3435    3
3443    3
Name: FTR, dtype: object
1.6
11
13.0
Ath Madrid - visitante
3265    0
3286    0
3303    3
3326    0
3341    3
3365    3
3370    3
3414    1
3420    3
3454    1
Name: FTR, dtype: object
1.7
Celta - local
3261    0
3284    1
3305    1
3338    1
3359    3
3378    3
3399    3
3419    0
Name: FTR, dtype: object
1.5
9
13.875
Valladolid - visitante
3260    1
3280    3
3304    0
3323    3
3348    0
3375    0
3395    0
3410    3
Name: FTR, dtype: object
1.25
Barcelona - local
3265    3
3288    3
3309    3
3329    3
3352    1
3380    3
3394    3
3415    3
3437    3
3444    3
Name: FTR, dtype: object
2.8
33
13.5
Espanol - visitante
3264    1
3283    1
3306    0
3321    3
3357    1
3379    0
3393    0
3418    0
3437    0
3448    0
Name: FTR, dtype: object
0.6
Sevilla - local
3266    0
3280    0
3301    3
3322    1
3340    3
3368    0
3388    3
3417    3
3433    3
3442    0
Name: FTR, dtype: object
1.6
20
16.1
Osasuna - visitante
3269    1
3299    1
3318    3
3334    0
3354    0
3377    0
3399    0
3412    0
3422    3
3441    0
Name: FTR, dtype: object
0.8
Levante - local
3271    3
3291    0
3312    0
3333    3
3351    3
3374    3
3393    3
3414    1
3425    3
3457    3
Name: FTR, dtype: object
2.2
21
11.6
Ath Bilbao - visitante
3267    3
3288    0
3307    0
3325    3
3346    0
3367    0
3385    1
3401    0
3425    0
3450    0
Name: FTR, dtype: object
0.7
La Coruna - local
3260    1
3282    0
3302    0
3324    3
3349    0
3372    0
3398    1
3412    3
Name: FTR, dtype: object
1.0
10
14.875
Malaga - visitante
3266    3
3287    0
3308    1
3337    1
3353    0
3376    1
3396    3
3419    3
3438    0
3444    0
Name: FTR, dtype: object
1.2
Granada - local
3268    1
3283    1
3303    0
3325    0
3343    0
3364    3
3384    1
3404    1
3436    0
3448    3
Name: FTR, dtype: object
1.0
9
14.4
Valencia - visitante
3277    3
3297    0
3310    1
3339    0
3351    0
3373    0
3394    0
3413    1
3428    0
3453    0
Name: FTR, dtype: object
0.5
Zaragoza - local
3262    0
3290    0
3315    3
3331    3
3355    0
3377    3
3396    0
3410    0
3430    3
3440    3
Name: FTR, dtype: object
1.5
13
14.5
Betis - visitante
3261    3
3282    3
3301    0
3320    3
3342    1
3369    0
3381    3
3416    3
3432    0
3442    3
Name: FTR, dtype: object
1.9
Valladolid - local
3275    0
3296    3
3310    1
3330    1
3357    1
3361    3
3381    0
3400    3
Name: FTR, dtype: object
1.5
15
11.5
Barcelona - visitante
3272    3
3291    3
3311    3
3336    3
3349    3
3368    3
3390    3
3403    3
3429    1
3451    3
Name: FTR, dtype: object
2.8
Osasuna - local
3277    0
3289    3
3308    1
3323    0
3342    1
3363    3
3383    1
3403    0
3434    3
3460    1
Name: FTR, dtype: object
1.3
9
15.3
Granada - visitante
3278    0
3296    0
3319    3
3333    0
3350    3
3380    0
3392    0
3411    0
3421    0
3457    0
Name: FTR, dtype: object
0.6
Malaga - local
3278    3
3297    3
3317    0
3328    0
3348    3
3369    3
3389    3
3407    1
3424    3
3453    3
Name: FTR, dtype: object
2.2
22
16.9
Real Madrid - visitante
3275    3
3298    0
3312    3
3332    3
3352    1
3371    3
3388    0
3405    0
3436    3
3446    3
Name: FTR, dtype: object
1.9
Betis - local
3272    0
3298    3
3319    0
3339    3
3358    3
3370    0
3379    3
3409    0
3429    1
3454    1

Name: FTR, dtype: object
1.4
14
10.3
Mallorca - visitante
3271    0
3295    0
3305    1
3324    0
3340    0
3360    0
3383    1
3407    1
3423    0
3458    3
Name: FTR, dtype: object
0.6
Ath Bilbao - local
3274    3
3294    1
3314    3
3335    0
3354    3
3376    1
3395    3
3416    0
3439    1
3446    0
Name: FTR, dtype: object
1.5
11
15.4
Zaragoza - visitante
3270    3
3281    1
3309    0
3327    0
3343    3
3366    0
3382    0
3408    3
3426    3
3468    0
Name: FTR, dtype: object
1.3
Valencia - local
3263    0
3285    0
3306    3
3326    3
3346    3
3366    3
3387    3
3402    1
3431    3
3441    3
Name: FTR, dtype: object
2.2
21
14.2
Getafe - visitante
3276    1
3292    3
3313    0
3335    3
3355    3
3378    0
3398    1
3417    0
3439    1
3464    0
Name: FTR, dtype: object
1.2
Ath Madrid - local
3273    3
3293    3
3313    3
3334    3
3353    3
3375    3
3386    3
3401    3
3438    3
3445    1
Name: FTR, dtype: object
2.8
30
14.5
Celta - visitante
3274    0
3290    3
3316    0
3329    0
3347    0
3364    0
3387    0
3406    0
Name: FTR, dtype: object
0.375
Vallecano - local
3270    0
3295    3
3316    3
3336    0
3356    3
3371    0
3391    1
3411    3
3421    3
3451    0
Name: FTR, dtype: object
1.6
9
16.4
Levante - visitante
3262    3
3284    1
3302    3
3322    1
3344    3
3363    0
3389    0
3400    0
3435    0
3440    0
Name: FTR, dtype: object
1.1
Sociedad - local
3276    1
3299    1
3300    3
3321    0
3341    0
3367    3
3382    3
3406    3
3428    3
3456    3
Name: FTR, dtype: object
2.0
15
15.1
Sevilla - visitante
3279    1
3293    0
3314    0
3331    0
3359    0
3372    3
3391    1
3404    1
3427    1
3452    0
Name: FTR, dtype: object
0.7
Espanol - local
3279    1
3292    0
3318    0
3337    1
3345    3
3365    0
3385    1
3408    0
3427    1
3459    0
Name: FTR, dtype: object
0.7
10
12.5
La Coruna - visitante
3273    0
3294    1
3315    0
3338    1
3356    0
3362    0
3384    1
3402    1
Name: FTR, dtype: object
0.5
La Coruna - local
3282    0
3302    0
3324    3
3349    0
3372    0
3398    1
3412    3
Name: FTR, dtype: object
1.0
10
14.428571428571429
Valladolid - visitante
3280    3
3304    0
3323    3
3348    0
3375    0
3395    0
3410    3
Name: FTR, dtype: object
1.2857142857142858
Celta - local
3284    1
3305    1
3338    1
3359    3
3378    3
3399    3
3419    0
Name: FTR, dtype: object
1.7142857142857142
9
14.142857142857142
Betis - visitante
3282    3
3301    0
3320    3
3342    1
3369    0
3381    3
3416    3
3432    0
3442    3
3461    0
Name: FTR, dtype: object
1.6
Zaragoza - local
3290    0
3315    3
3331    3
3355    0
3377    3
3396    0
3410    0
3430    3
3440    3
3450    3
Name: FTR, dtype: object
1.8
15
15.4
Levante - visitante
3284    1
3302    3
3322    1
3344    3
3363    0
3389    0
3400    0
3435    0
3440    0
3467    1
Name: FTR, dtype: object
0.9
Valencia - local
3285    0
3306    3
3326    3
3346    3
3366    3
3387    3
3402    1
3431    3
3441    3
3461    3
Name: FTR, dtype: object
2.5
25
14.8
Vallecano - visitante
3289    0
3300    0
3328    3
3345    0
3361    0
3386    0
3409    3
3433    0
3443    0
3466    0
Name: FTR, dtype: object
0.6
Real Madrid - local
3286    3
3307    3
3327    3
3347    3
3362    3
3392    3
3413    1
3423    3
3452    3
3478    3
Name: FTR, dtype: object
2.8
32
21.7
Espanol - visitante
3283    1
3306    0
3321    3
3357    1
3379    0
3393    0
3418    0
3437    0
3448    0
3465    0
Name: FTR, dtype: object
0.5
Barcelona - local
3288    3
3309    3
3329    3
3352    1
3380    3
3394    3
3415    3
3437    3
3444    3
3469    0
Name: FTR, dtype: object
2.5
30
13.8
Ath Madrid - visitante
3286    0
3303    3
3326    0
3341    3
3365    3
3370    3
3414    1
3420    3
3454    1
3473    3
Name: FTR, dtype: object
2.0
Sevilla - local
3280    0
3301    3
3322    1
3340    3
3368    0
3388    3
3417    3
3433    3
3442    0
3467    1
Name: FTR, dtype: object
1.7
21
16.8
Malaga - visitante
3287    0
3308    1
3337    1
3353    0
3376    1
3396    3
3419    3
3438    0
3444    0
3460    1
Name: FTR, dtype: object
1.0
Mallorca - local
3281    1
3311    0
3332    0
3350    0
3373    3
3397    3
3418    3
3435    3
3443    3
3468    3
Name: FTR, dtype: object
1.9
12
12.4
Ath Bilbao - visitante
3288    0
3307    0
3325    3
3346    0
3367    0
3385    1
3401    0
3425    0
3450    0
3463    3
Name: FTR, dtype: object
0.7
Granada - local
3283    1
3303    0
3325    0
3343    0
3364    3
3384    1
3404    1
3436    0
3448    3
3464    3
Name: FTR, dtype: object
1.2
10
14.5
Sociedad - visitante
3285    3
3317    3
3330    1
3358    0
3374    0
3397    0
3415    0
3434    0
3445    1
3474    1
Name: FTR, dtype: object
0.9
Getafe - local
3287    3
3304    3
3320    0
3344    0
3360    3
3390    0
3405    3
3426    0
3449    1
3458    0
Name: FTR, dtype: object
1.3
11
13.5
Osasuna - visitante
3299    1
3318    3
3334    0
3354    0
3377    0
3399    0
3412    0
3422    3
3441    0
3455    1
Name: FTR, dtype: object
0.8
Vallecano - local
3295    3
3316    3
3336    0
3356    3
3371    0
3391    1
3411    3
3421    3
3451    0
3473    0
Name: FTR, dtype: object
1.6
9
16.2
Zaragoza - visitante
3281    1
3309    0
3327    0
3343    3
3366    0
3382    0
3408    3
3426    3
3468    0
3481    0
Name: FTR, dtype: object
1.0
Levante - local
3291    0
3312    0
3333    3
3351    3
3374    3
3393    3
3414    1
3425    3
3457    3
3479    0
Name: FTR, dtype: object
1.9
18
10.7
Mallorca - visitante
3295    0
3305    1
3324    0
3340    0
3360    0
3383    1
3407    1
3423    0
3458    3
3477    0
Name: FTR, dtype: object
0.6
Betis - local
3298    3
3319    0
3339    3
3358    3
3370    0
3379    3
3409    0
3429    1
3454    1
3476    3
Name: FTR, dtype: object
1.7
14
10.4
Barcelona - visitante
3291    3
3311    3
3336    3
3349    3
3368    3
3390    3
3403    3
3429    1
3451    3
3479    3
Name: FTR, dtype: object
2.8
Ath Madrid - local
3293    3
3313    3
3334    3
3353    3
3375    3
3386    3
3401    3
3438    3
3445    1
3465    3
Name: FTR, dtype: object
2.8
27
14.8
La Coruna - visitante
3294    1
3315    0
3338    1
3356    0
3362    0
3384    1
3402    1
Name: FTR, dtype: object
0.5714285714285714
Ath Bilbao - local
3294    1
3314    3
3335    0
3354    3
3376    1
3395    3
3416    0
3439    1
3446    0
3477    3
Name: FTR, dtype: object
1.5
11
15.7
Celta - visitante
3290    3
3316    0
3329    0
3347    0
3364    0
3387    0
3406    0
Name: FTR, dtype: object
0.42857142857142855
Valladolid - local
3296    3
3310    1
3330    1
3357    1
3361    3
3381    0
3400    3
Name: FTR, dtype: object
1.7142857142857142
13
11.714285714285714
Real Madrid - visitante
3298    0
3312    3
3332    3
3352    1
3371    3
3388    0
3405    0
3436    3
3446    3
3469    3
Name: FTR, dtype: object
1.9
Sociedad - local
3299    1
3300    3
3321    0
3341    0
3367    3
3382    3
3406    3
3428    3
3456    3
3462    1
Name: FTR, dtype: object
2.0
15
15.9
Getafe - visitante
3292    3
3313    0
3335    3
3355    3
3378    0
3398    1
3417    0
3439    1
3464    0
3489    0
Name: FTR, dtype: object
1.1
Osasuna - local
3289    3
3308    1
3323    0
3342    1
3363    3
3383    1
3403    0
3434    3
3460    1
3488    3
Name: FTR, dtype: object
1.6
11
15.6
Valencia - visitante
3297    0
3310    1
3339    0
3351    0
3373    0
3394    0
3413    1
3428    0
3453    0
3475    0
Name: FTR, dtype: object
0.2
Malaga - local
3297    3
3317    0
3328    0
3348    3
3369    3
3389    3
3407    1
3424    3
3453    3
3474    1
Name: FTR, dtype: object
2.0
19
16.8
Granada - visitante
3296    0
3319    3
3333    0
3350    3
3380    0
3392    0
3411    0
3421    0
3457    0
3471    0
Name: FTR, dtype: object
0.6
Espanol - local
3292    0
3318    0
3337    1
3345    3
3365    0
3385    1
3408    0
3427    1
3459    0
3475    3
Name: FTR, dtype: object
0.9
12
13.0
Sevilla - visitante
3293    0
3314    0
3331    0
3359    0
3372    3
3391    1
3404    1
3427    1
3452    0
3470    0
Name: FTR, dtype: object
0.6
Sevilla - local
3301    3
3322    1
3340    3
3368    0
3388    3
3417    3
3433    3
3442    0
3467    1
3481    3
Name: FTR, dtype: object
2.0
23
16.9
Valladolid - visitante
3304    0
3323    3
3348    0
3375    0
3395    0
3410    3
Name: FTR, dtype: object
1.0
Mallorca - local
3311    0
3332    0
3350    0
3373    3
3397    3
3418    3
3435    3
3443    3
3468    3
3492    1
Name: FTR, dtype: object
1.9
11
11.8
Zaragoza - visitante
3309    0
3327    0
3343    3
3366    0
3382    0
3408    3
3426    3
3468    0
3481    0
3505    3
Name: FTR, dtype: object
1.2
La Coruna - local
3302    0
3324    3
3349    0
3372    0
3398    1
3412    3
Name: FTR, dtype: object
1.1666666666666667
8
14.0
Betis - visitante
3301    0
3320    3
3342    1
3369    0
3381    3
3416    3
3432    0
3442    3
3461    0
3487    1
Name: FTR, dtype: object
1.4
Granada - local
3303    0
3325    0
3343    0
3364    3
3384    1
3404    1
3436    0
3448    3
3464    3
3485    1

Name: FTR, dtype: object
1.2
12
13.0
Espanol - visitante
3306    0
3321    3
3357    1
3379    0
3393    0
3418    0
3437    0
3448    0
3465    0
3488    0
Name: FTR, dtype: object
0.4
Celta - local
3305    1
3338    1
3359    3
3378    3
3399    3
3419    0
Name: FTR, dtype: object
1.8333333333333333
8
13.5
Levante - visitante
3302    3
3322    1
3344    3
3363    0
3389    0
3400    0
3435    0
3440    0
3467    1
3484    0
Name: FTR, dtype: object
0.8
Valencia - local
3306    3
3326    3
3346    3
3366    3
3387    3
3402    1
3431    3
3441    3
3461    3
3483    3
Name: FTR, dtype: object
2.8
27
14.8
Sociedad - visitante
3317    3
3330    1
3358    0
3374    0
3397    0
3415    0
3434    0
3445    1
3474    1
3498    1
Name: FTR, dtype: object
0.7
Real Madrid - local
3307    3
3327    3
3347    3
3362    3
3392    3
3413    1
3423    3
3452    3
3478    3
3491    1
Name: FTR, dtype: object
2.6
30
23.7
Ath Madrid - visitante
3303    3
3326    0
3341    3
3365    3
3370    3
3414    1
3420    3
3454    1
3473    3
3493    0
Name: FTR, dtype: object
2.0
Getafe - local
3304    3
3320    0
3344    0
3360    3
3390    0
3405    3
3426    0
3449    1
3458    0
3470    3
Name: FTR, dtype: object
1.3
15
13.4
Malaga - visitante
3308    1
3337    1
3353    0
3376    1
3396    3
3419    3
3438    0
3444    0
3460    1
3480    0
Name: FTR, dtype: object
1.0
Barcelona - local
3309    3
3329    3
3352    1
3380    3
3394    3
3415    3
3437    3
3444    3
3469    0
3489    3
Name: FTR, dtype: object
2.5
29
13.3
Ath Bilbao - visitante
3307    0
3325    3
3346    0
3367    0
3385    1
3401    0
3425    0
3450    0
3463    3
3485    1
Name: FTR, dtype: object
0.8
Osasuna - local
3308    1
3323    0
3342    1
3363    3
3383    1
3403    0
3434    3
3460    1
3488    3
3507    0
Name: FTR, dtype: object
1.3
11
15.7
Vallecano - visitante
3300    0
3328    3
3345    0
3361    0
3386    0
3409    3
3433    0
3443    0
3466    0
3483    0
Name: FTR, dtype: object
0.6
Zaragoza - local
3315    3
3331    3
3355    0
3377    3
3396    0
3410    0
3430    3
3440    3
3450    3
3471    3
Name: FTR, dtype: object
2.1
16
14.8
Celta - visitante
3316    0
3329    0
3347    0
3364    0
3387    0
3406    0
Name: FTR, dtype: object
0.0
Levante - local
3312    0
3333    3
3351    3
3374    3
3393    3
3414    1
3425    3
3457    3
3479    0
3493    3
Name: FTR, dtype: object
2.2
20
10.4
Barcelona - visitante
3311    3
3336    3
3349    3
3368    3
3390    3
3403    3
3429    1
3451    3
3479    3
3495    3
Name: FTR, dtype: object
2.8
Espanol - local
3318    0
3337    1
3345    3
3365    0
3385    1
3408    0
3427    1
3459    0
3475    3
3498    1
Name: FTR, dtype: object
1.0
14
14.6
Getafe - visitante
3313    0
3335    3
3355    3
3378    0
3398    1
3417    0
3439    1
3464    0
3489    0
3504    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
3313    3
3334    3
3353    3
3375    3
3386    3
3401    3
3438    3
3445    1
3465    3
3486    0
Name: FTR, dtype: object
2.5
24
14.1
Sevilla - visitante
3314    0
3331    0
3359    0
3372    3
3391    1
3404    1
3427    1
3452    0
3470    0
3494    0
Name: FTR, dtype: object
0.6
Ath Bilbao - local
3314    3
3335    0
3354    3
3376    1
3395    3
3416    0
3439    1
3446    0
3477    3
3494    3
Name: FTR, dtype: object
1.7
11
14.9
La Coruna - visitante
3315    0
3338    1
3356    0
3362    0
3384    1
3402    1
Name: FTR, dtype: object
0.5
Vallecano - local
3316    3
3336    0
3356    3
3371    0
3391    1
3411    3
3421    3
3451    0
3473    0
3496    3
Name: FTR, dtype: object
1.6
13
16.2
Mallorca - visitante
3305    1
3324    0
3340    0
3360    0
3383    1
3407    1
3423    0
3458    3
3477    0
3482    3
Name: FTR, dtype: object
0.9
Valladolid - local
3310    1
3330    1
3357    1
3361    3
3381    0
3400    3
Name: FTR, dtype: object
1.5
12
12.0
Granada - visitante
3319    3
3333    0
3350    3
3380    0
3392    0
3411    0
3421    0
3457    0
3471    0
3492    1
Name: FTR, dtype: object
0.7
Malaga - local
3317    0
3328    0
3348    3
3369    3
3389    3
3407    1
3424    3
3453    3
3474    1
3490    3
Name: FTR, dtype: object
2.0
18
17.6
Valencia - visitante
3310    1
3339    0
3351    0
3373    0
3394    0
3413    1
3428    0
3453    0
3475    0
3491    1
Name: FTR, dtype: object
0.3
Betis - local
3319    0
3339    3
3358    3
3370    0
3379    3
3409    0
3429    1
3454    1
3476    3
3499    3
Name: FTR, dtype: object
1.7
16
11.1
Real Madrid - visitante
3312    3
3332    3
3352    1
3371    3
3388    0
3405    0
3436    3
3446    3
3469    3
3486    3
Name: FTR, dtype: object
2.2
Sociedad - local
3300    3
3321    0
3341    0
3367    3
3382    3
3406    3
3428    3
3456    3
3462    1
3487    1
Name: FTR, dtype: object
2.0
16
16.3
Osasuna - visitante
3318    3
3334    0
3354    0
3377    0
3399    0
3412    0
3422    3
3441    0
3455    1
3476    0
Name: FTR, dtype: object
0.7
Sociedad - local
3321    0
3341    0
3367    3
3382    3
3406    3
3428    3
3456    3
3462    1
3487    1
3503    3
Name: FTR, dtype: object
2.0
16
15.2
Vallecano - visitante
3328    3
3345    0
3361    0
3386    0
3409    3
3433    0
3443    0
3466    0
3483    0
3503    0
Name: FTR, dtype: object
0.6
Sevilla - local
3322    1
3340    3
3368    0
3388    3
3417    3
3433    3
3442    0
3467    1
3481    3
3500    3
Name: FTR, dtype: object
2.0
21
16.2
Betis - visitante
3320    3
3342    1
3369    0
3381    3
3416    3
3432    0
3442    3
3461    0
3487    1
3508    3
Name: FTR, dtype: object
1.7
La Coruna - local
3324    3
3349    0
3372    0
3398    1
3412    3
Name: FTR, dtype: object
1.4
8
12.0
Levante - visitante
3322    1
3344    3
3363    0
3389    0
3400    0
3435    0
3440    0
3467    1
3484    0
3502    1
Name: FTR, dtype: object
0.6
Granada - local
3325    0
3343    0
3364    3
3384    1
3404    1
3436    0
3448    3
3464    3
3485    1
3510    0
Name: FTR, dtype: object
1.2
12
13.7
Ath Madrid - visitante
3326    0
3341    3
3365    3
3370    3
3414    1
3420    3
3454    1
3473    3
3493    0
3511    0
Name: FTR, dtype: object
1.7
Getafe - local
3320    0
3344    0
3360    3
3390    0
3405    3
3426    0
3449    1
3458    0
3470    3
3497    3
Name: FTR, dtype: object
1.3
15
12.5
Valladolid - visitante
3323    3
3348    0
3375    0
3395    0
3410    3
Name: FTR, dtype: object
1.2
Celta - local
3338    1
3359    3
3378    3
3399    3
3419    0
Name: FTR, dtype: object
2.0
7
13.2
Mallorca - visitante
3324    0
3340    0
3360    0
3383    1
3407    1
3423    0
3458    3
3477    0
3482    3
3500    0
Name: FTR, dtype: object
0.8
Valencia - local
3326    3
3346    3
3366    3
3387    3
3402    1
3431    3
3441    3
3461    3
3483    3
3502    1
Name: FTR, dtype: object
2.6
26
15.0
Espanol - visitante
3321    3
3357    1
3379    0
3393    0
3418    0
3437    0
3448    0
3465    0
3488    0
3501    1
Name: FTR, dtype: object
0.5
Real Madrid - local
3327    3
3347    3
3362    3
3392    3
3413    1
3423    3
3452    3
3478    3
3491    1
3517    3
Name: FTR, dtype: object
2.6
30
22.7
Ath Bilbao - visitante
3325    3
3346    0
3367    0
3385    1
3401    0
3425    0
3450    0
3463    3
3485    1
3509    0
Name: FTR, dtype: object
0.8
Osasuna - local
3323    0
3342    1
3363    3
3383    1
3403    0
3434    3
3460    1
3488    3
3507    0
3528    1
Name: FTR, dtype: object
1.3
11
15.7
Malaga - visitante
3337    1
3353    0
3376    1
3396    3
3419    3
3438    0
3444    0
3460    1
3480    0
3514    3
Name: FTR, dtype: object
1.2
Barcelona - local
3329    3
3352    1
3380    3
3394    3
3415    3
3437    3
3444    3
3469    0
3489    3
3509    3
Name: FTR, dtype: object
2.5
28
14.5
Zaragoza - visitante
3327    0
3343    3
3366    0
3382    0
3408    3
3426    3
3468    0
3481    0
3505    3
3524    3
Name: FTR, dtype: object
1.5
Valladolid - local
3330    1
3357    1
3361    3
3381    0
3400    3
Name: FTR, dtype: object
1.6
11
12.6
Valencia - visitante
3339    0
3351    0
3373    0
3394    0
3413    1
3428    0
3453    0
3475    0
3491    1
3519    0
Name: FTR, dtype: object
0.2
Mallorca - local
3332    0
3350    0
3373    3
3397    3
3418    3
3435    3
3443    3
3468    3
3492    1
3518    0
Name: FTR, dtype: object
1.9
9
12.3
Barcelona - visitante
3336    3
3349    3
3368    3
3390    3
3403    3
3429    1
3451    3
3479    3
3495    3
3518    3
Name: FTR, dtype: object
2.8
Levante - local
3333    3
3351    3
3374    3
3393    3
3414    1
3425    3
3457    3
3479    0
3493    3
3513    0
Name: FTR, dtype: object
2.2
19
11.3
Real Madrid - visitante
3332    3
3352    1
3371    3
3388    0
3405    0
3436    3
3446    3
3469    3
3486    3
3507    3
Name: FTR, dtype: object
2.2
Ath Madrid - local
3334    3
3353    3
3375    3
3386    3
3401    3
3438    3
3445    1
3465    3
3486    0
3504    3
Name: FTR, dtype: object
2.5
25
13.5
Getafe - visitante
3335    3
3355    3
3378    0
3398    1
3417    0
3439    1
3464    0
3489    0
3504    0
3528    1
Name: FTR, dtype: object
0.9
Ath Bilbao - local
3335    0
3354    3
3376    1
3395    3
3416    0
3439    1
3446    0
3477    3
3494    3
3516    1
Name: FTR, dtype: object
1.5
10
15.2
Sevilla - visitante
3331    0
3359    0
3372    3
3391    1
3404    1
3427    1
3452    0
3470    0
3494    0
3510    3
Name: FTR, dtype: object
0.9
Zaragoza - local
3331    3
3355    0
3377    3
3396    0
3410    0
3430    3
3440    3
3450    3
3471    3
3495    0
Name: FTR, dtype: object
1.8
12
13.9
La Coruna - visitante
3338    1
3356    0
3362    0
3384    1
3402    1
Name: FTR, dtype: object
0.6
Vallecano - local
3336    0
3356    3
3371    0
3391    1
3411    3
3421    3
3451    0
3473    0
3496    3
3512    0
Name: FTR, dtype: object
1.3
10
15.2
Celta - visitante
3329    0
3347    0
3364    0
3387    0
3406    0
Name: FTR, dtype: object
0.0
Malaga - local
3328    0
3348    3
3369    3
3389    3
3407    1
3424    3
3453    3
3474    1
3490    3
3508    0
Name: FTR, dtype: object
2.0
17

18.4
Sociedad - visitante
3330    1
3358    0
3374    0
3397    0
3415    0
3434    0
3445    1
3474    1
3498    1
3517    0
Name: FTR, dtype: object
0.4
Espanol - local
3337    1
3345    3
3365    0
3385    1
3408    0
3427    1
3459    0
3475    3
3498    1
3514    0
Name: FTR, dtype: object
1.0
15
13.6
Osasuna - visitante
3334    0
3354    0
3377    0
3399    0
3412    0
3422    3
3441    0
3455    1
3476    0
3496    0
Name: FTR, dtype: object
0.4
Betis - local
3339    3
3358    3
3370    0
3379    3
3409    0
3429    1
3454    1
3476    3
3499    3
3515    1
Name: FTR, dtype: object
1.8
16
11.5
Granada - visitante
3333    0
3350    3
3380    0
3392    0
3411    0
3421    0
3457    0
3471    0
3492    1
3506    3
Name: FTR, dtype: object
0.7
Getafe - local
3344    0
3360    3
3390    0
3405    3
3426    0
3449    1
3458    0
3470    3
3497    3
3519    3
Name: FTR, dtype: object
1.6
16
11.6
Betis - visitante
3342    1
3369    0
3381    3
3416    3
3432    0
3442    3
3461    0
3487    1
3508    3
3536    0
Name: FTR, dtype: object
1.4
Sociedad - local
3341    0
3367    3
3382    3
3406    3
3428    3
3456    3
3462    1
3487    1
3503    3
3526    0
Name: FTR, dtype: object
2.0
17
14.5
Espanol - visitante
3357    1
3379    0
3393    0
3418    0
3437    0
3448    0
3465    0
3488    0
3501    1
3522    1
Name: FTR, dtype: object
0.3
Sevilla - local
3340    3
3368    0
3388    3
3417    3
3433    3
3442    0
3467    1
3481    3
3500    3
3537    0
Name: FTR, dtype: object
1.9
21
15.4
Levante - visitante
3344    3
3363    0
3389    0
3400    0
3435    0
3440    0
3467    1
3484    0
3502    1
3526    3
Name: FTR, dtype: object
0.8
Osasuna - local
3342    1
3363    3
3383    1
3403    0
3434    3
3460    1
3488    3
3507    0
3528    1
3543    3
Name: FTR, dtype: object
1.6
13
15.7
Valladolid - visitante
3348    0
3375    0
3395    0
3410    3
Name: FTR, dtype: object
0.75
La Coruna - local
3349    0
3372    0
3398    1
3412    3
Name: FTR, dtype: object
1.0
7
11.75
Mallorca - visitante
3340    0
3360    0
3383    1
3407    1
3423    0
3458    3
3477    0
3482    3
3500    0
3525    3
Name: FTR, dtype: object
1.1
Granada - local
3343    0
3364    3
3384    1
3404    1
3436    0
3448    3
3464    3
3485    1
3510    0
3538    3
Name: FTR, dtype: object
1.5
13
12.6
Ath Bilbao - visitante
3346    0
3367    0
3385    1
3401    0
3425    0
3450    0
3463    3
3485    1
3509    0
3527    0
Name: FTR, dtype: object
0.5
Valencia - local
3346    3
3366    3
3387    3
3402    1
3431    3
3441    3
3461    3
3483    3
3502    1
3524    0
Name: FTR, dtype: object
2.3
25
17.2
Ath Madrid - visitante
3341    3
3365    3
3370    3
3414    1
3420    3
3454    1
3473    3
3493    0
3511    0
3532    0
Name: FTR, dtype: object
1.7
Real Madrid - local
3347    3
3362    3
3392    3
3413    1
3423    3
3452    3
3478    3
3491    1
3517    3
3531    1
Name: FTR, dtype: object
2.4
27
22.5
Zaragoza - visitante
3343    3
3366    0
3382    0
3408    3
3426    3
3468    0
3481    0
3505    3
3524    3
3547    0
Name: FTR, dtype: object
1.5
Malaga - local
3348    3
3369    3
3389    3
3407    1
3424    3
3453    3
3474    1
3490    3
3508    0
3521    3
Name: FTR, dtype: object
2.3
20
18.8
Vallecano - visitante
3345    0
3361    0
3386    0
3409    3
3433    0
3443    0
3466    0
3483    0
3503    0
3521    0
Name: FTR, dtype: object
0.3
Barcelona - local
3352    1
3380    3
3394    3
3415    3
3437    3
3444    3
3469    0
3489    3
3509    3
3529    3
Name: FTR, dtype: object
2.5
30
15.0
Celta - visitante
3347    0
3364    0
3387    0
3406    0
Name: FTR, dtype: object
0.0
Valladolid - local
3357    1
3361    3
3381    0
3400    3
Name: FTR, dtype: object
1.75
9
12.75
Sociedad - visitante
3358    0
3374    0
3397    0
3415    0
3434    0
3445    1
3474    1
3498    1
3517    0
3539    0
Name: FTR, dtype: object
0.3
Zaragoza - local
3355    0
3377    3
3396    0
3410    0
3430    3
3440    3
3450    3
3471    3
3495    0
3511    3
Name: FTR, dtype: object
1.8
11
14.0
Sevilla - visitante
3359    0
3372    3
3391    1
3404    1
3427    1
3452    0
3470    0
3494    0
3510    3
3520    3
Name: FTR, dtype: object
1.2
Mallorca - local
3350    0
3373    3
3397    3
3418    3
3435    3
3443    3
3468    3
3492    1
3518    0
3532    3
Name: FTR, dtype: object
2.2
11
12.7
Real Madrid - visitante
3352    1
3371    3
3388    0
3405    0
3436    3
3446    3
3469    3
3486    3
3507    3
3523    1
Name: FTR, dtype: object
2.0
Levante - local
3351    3
3374    3
3393    3
3414    1
3425    3
3457    3
3479    0
3493    3
3513    0
3533    3
Name: FTR, dtype: object
2.2
17
11.3
Granada - visitante
3350    3
3380    0
3392    0
3411    0
3421    0
3457    0
3471    0
3492    1
3506    3
3529    0
Name: FTR, dtype: object
0.7
Ath Madrid - local
3353    3
3375    3
3386    3
3401    3
3438    3
3445    1
3465    3
3486    0
3504    3
3527    3
Name: FTR, dtype: object
2.5
24
13.7
Osasuna - visitante
3354    0
3377    0
3399    0
3412    0
3422    3
3441    0
3455    1
3476    0
3496    0
3513    3
Name: FTR, dtype: object
0.7
Ath Bilbao - local
3354    3
3376    1
3395    3
3416    0
3439    1
3446    0
3477    3
3494    3
3516    1
3534    0
Name: FTR, dtype: object
1.5
9
14.2
Getafe - visitante
3355    3
3378    0
3398    1
3417    0
3439    1
3464    0
3489    0
3504    0
3528    1
3540    3
Name: FTR, dtype: object
0.9
Vallecano - local
3356    3
3371    0
3391    1
3411    3
3421    3
3451    0
3473    0
3496    3
3512    0
3536    3
Name: FTR, dtype: object
1.6
13
14.7
Barcelona - visitante
3349    3
3368    3
3390    3
3403    3
3429    1
3451    3
3479    3
3495    3
3518    3
3537    3
Name: FTR, dtype: object
2.8
Espanol - local
3345    3
3365    0
3385    1
3408    0
3427    1
3459    0
3475    3
3498    1
3514    0
3530    3
Name: FTR, dtype: object
1.2
18
13.9
Malaga - visitante
3353    0
3376    1
3396    3
3419    3
3438    0
3444    0
3460    1
3480    0
3514    3
3531    1
Name: FTR, dtype: object
1.2
Celta - local
3359    3
3378    3
3399    3
3419    0
Name: FTR, dtype: object
2.25
6
13.5
La Coruna - visitante
3356    0
3362    0
3384    1
3402    1
Name: FTR, dtype: object
0.5
Betis - local
3358    3
3370    0
3379    3
3409    0
3429    1
3454    1
3476    3
3499    3
3515    1
3522    1
Name: FTR, dtype: object
1.6
16
11.4
Valencia - visitante
3351    0
3373    0
3394    0
3413    1
3428    0
3453    0
3475    0
3491    1
3519    0
3534    3
Name: FTR, dtype: object
0.5
Sevilla - local
3368    0
3388    3
3417    3
3433    3
3442    0
3467    1
3481    3
3500    3
3537    0
3556    1
Name: FTR, dtype: object
1.7
19
15.2
Mallorca - visitante
3360    0
3383    1
3407    1
3423    0
3458    3
3477    0
3482    3
3500    0
3525    3
3541    1
Name: FTR, dtype: object
1.2
Sociedad - local
3367    3
3382    3
3406    3
3428    3
3456    3
3462    1
3487    1
3503    3
3526    0
3547    3
Name: FTR, dtype: object
2.3
20
14.3
Ath Madrid - visitante
3365    3
3370    3
3414    1
3420    3
3454    1
3473    3
3493    0
3511    0
3532    0
3556    1
Name: FTR, dtype: object
1.5
Osasuna - local
3363    3
3383    1
3403    0
3434    3
3460    1
3488    3
3507    0
3528    1
3543    3
3564    3
Name: FTR, dtype: object
1.8
15
16.1
Betis - visitante
3369    0
3381    3
3416    3
3432    0
3442    3
3461    0
3487    1
3508    3
3536    0
3550    0
Name: FTR, dtype: object
1.3
Granada - local
3364    3
3384    1
3404    1
3436    0
3448    3
3464    3
3485    1
3510    0
3538    3
3553    0
Name: FTR, dtype: object
1.5
12
12.8
Zaragoza - visitante
3366    0
3382    0
3408    3
3426    3
3468    0
3481    0
3505    3
3524    3
3547    0
3567    0
Name: FTR, dtype: object
1.2
Getafe - local
3360    3
3390    0
3405    3
3426    0
3449    1
3458    0
3470    3
3497    3
3519    3
3539    3
Name: FTR, dtype: object
1.9
17
10.9
Levante - visitante
3363    0
3389    0
3400    0
3435    0
3440    0
3467    1
3484    0
3502    1
3526    3
3548    0
Name: FTR, dtype: object
0.5
Espanol - local
3365    0
3385    1
3408    0
3427    1
3459    0
3475    3
3498    1
3514    0
3530    3
3544    3
Name: FTR, dtype: object
1.2
20
14.3
Vallecano - visitante
3361    0
3386    0
3409    3
3433    0
3443    0
3466    0
3483    0
3503    0
3521    0
3544    0
Name: FTR, dtype: object
0.3
Valencia - local
3366    3
3387    3
3402    1
3431    3
3441    3
3461    3
3483    3
3502    1
3524    0
3541    1
Name: FTR, dtype: object
2.1
24
16.8
Ath Bilbao - visitante
3367    0
3385    1
3401    0
3425    0
3450    0
3463    3
3485    1
3509    0
3527    0
3543    0
Name: FTR, dtype: object
0.5
Real Madrid - local
3362    3
3392    3
3413    1
3423    3
3452    3
3478    3
3491    1
3517    3
3531    1
3552    3
Name: FTR, dtype: object
2.4
30
22.3
Celta - visitante
3364    0
3387    0
3406    0
Name: FTR, dtype: object
0.0
Malaga - local
3369    3
3389    3
3407    1
3424    3
3453    3
3474    1
3490    3
3508    0
3521    3
3548    3
Name: FTR, dtype: object
2.3
19
19.7
Valladolid - visitante
3375    0
3395    0
3410    3
Name: FTR, dtype: object
1.0
La Coruna - local
3372    0
3398    1
3412    3
Name: FTR, dtype: object
1.3333333333333333
3
11.333333333333334
Barcelona - visitante
3368    3
3390    3
3403    3
3429    1
3451    3
3479    3
3495    3
3518    3
3537    3
3542    3
Name: FTR, dtype: object
2.8
Mallorca - local
3373    3
3397    3
3418    3
3435    3
3443    3
3468    3
3492    1
3518    0
3532    3
3557    1
Name: FTR, dtype: object
2.3
11
12.6
Granada - visitante
3380    0
3392    0
3411    0
3421    0
3457    0
3471    0
3492    1
3506    3
3529    0
3545    0

Name: FTR, dtype: object
0.4
Levante - local
3374    3
3393    3
3414    1
3425    3
3457    3
3479    0
3493    3
3513    0
3533    3
3550    3
Name: FTR, dtype: object
2.2
19
10.5
Valencia - visitante
3373    0
3394    0
3413    1
3428    0
3453    0
3475    0
3491    1
3519    0
3534    3
3553    3
Name: FTR, dtype: object
0.8
Barcelona - local
3380    3
3394    3
3415    3
3437    3
3444    3
3469    0
3489    3
3509    3
3529    3
3559    3
Name: FTR, dtype: object
2.7
31
15.5
Real Madrid - visitante
3371    3
3388    0
3405    0
3436    3
3446    3
3469    3
3486    3
3507    3
3523    1
3549    3
Name: FTR, dtype: object
2.2
Ath Madrid - local
3375    3
3386    3
3401    3
3438    3
3445    1
3465    3
3486    0
3504    3
3527    3
3545    3
Name: FTR, dtype: object
2.5
24
14.2
Malaga - visitante
3376    1
3396    3
3419    3
3438    0
3444    0
3460    1
3480    0
3514    3
3531    1
3558    3
Name: FTR, dtype: object
1.5
Ath Bilbao - local
3376    1
3395    3
3416    0
3439    1
3446    0
3477    3
3494    3
3516    1
3534    0
3554    3
Name: FTR, dtype: object
1.5
10
13.8
Osasuna - visitante
3377    0
3399    0
3412    0
3422    3
3441    0
3455    1
3476    0
3496    0
3513    3
3535    1
Name: FTR, dtype: object
0.8
Zaragoza - local
3377    3
3396    0
3410    0
3430    3
3440    3
3450    3
3471    3
3495    0
3511    3
3535    1
Name: FTR, dtype: object
1.9
12
14.5
Getafe - visitante
3378    0
3398    1
3417    0
3439    1
3464    0
3489    0
3504    0
3528    1
3540    3
3569    1
Name: FTR, dtype: object
0.7
Vallecano - local
3371    0
3391    1
3411    3
3421    3
3451    0
3473    0
3496    3
3512    0
3536    3
3555    3
Name: FTR, dtype: object
1.6
15
15.5
La Coruna - visitante
3362    0
3384    1
3402    1
Name: FTR, dtype: object
0.6666666666666666
Valladolid - local
3361    3
3381    0
3400    3
Name: FTR, dtype: object
2.0
8
13.0
Espanol - visitante
3379    0
3393    0
3418    0
3437    0
3448    0
3465    0
3488    0
3501    1
3522    1
3552    0
Name: FTR, dtype: object
0.2
Betis - local
3370    0
3379    3
3409    0
3429    1
3454    1
3476    3
3499    3
3515    1
3522    1
3549    0
Name: FTR, dtype: object
1.3
16
11.6
Sociedad - visitante
3374    0
3397    0
3415    0
3434    0
3445    1
3474    1
3498    1
3517    0
3539    0
3554    0
Name: FTR, dtype: object
0.3
Celta - local
3378    3
3399    3
3419    0
Name: FTR, dtype: object
2.0
4
14.333333333333334
Sevilla - visitante
3372    3
3391    1
3404    1
3427    1
3452    0
3470    0
3494    0
3510    3
3520    3
3546    0
Name: FTR, dtype: object
1.2
Getafe - local
3390    0
3405    3
3426    0
3449    1
3458    0
3470    3
3497    3
3519    3
3539    3
3558    0
Name: FTR, dtype: object
1.6
17
10.0
Mallorca - visitante
3383    1
3407    1
3423    0
3458    3
3477    0
3482    3
3500    0
3525    3
3541    1
3563    0
Name: FTR, dtype: object
1.2
Valladolid - local
3381    0
3400    3
Name: FTR, dtype: object
1.5
2
12.5
Vallecano - visitante
3386    0
3409    3
3433    0
3443    0
3466    0
3483    0
3503    0
3521    0
3544    0
3573    3
Name: FTR, dtype: object
0.6
Real Madrid - local
3392    3
3413    1
3423    3
3452    3
3478    3
3491    1
3517    3
3531    1
3552    3
3578    3
Name: FTR, dtype: object
2.4
29
22.3
La Coruna - visitante
3384    1
3402    1
Name: FTR, dtype: object
1.0
Osasuna - local
3383    1
3403    0
3434    3
3460    1
3488    3
3507    0
3528    1
3543    3
3564    3
3588    3
Name: FTR, dtype: object
1.8
14
15.2
Levante - visitante
3389    0
3400    0
3435    0
3440    0
3467    1
3484    0
3502    1
3526    3
3548    0
3568    3
Name: FTR, dtype: object
0.8
Granada - local
3384    1
3404    1
3436    0
3448    3
3464    3
3485    1
3510    0
3538    3
3553    0
3574    3
Name: FTR, dtype: object
1.5
14
14.1
Celta - visitante
3387    0
3406    0
Name: FTR, dtype: object
0.0
Espanol - local
3385    1
3408    0
3427    1
3459    0
3475    3
3498    1
3514    0
3530    3
3544    3
3568    0
Name: FTR, dtype: object
1.2
21
14.4
Ath Madrid - visitante
3370    3
3414    1
3420    3
3454    1
3473    3
3493    0
3511    0
3532    0
3556    1
3571    1
Name: FTR, dtype: object
1.3
Valencia - local
3387    3
3402    1
3431    3
3441    3
3461    3
3483    3
3502    1
3524    0
3541    1
3562    0
Name: FTR, dtype: object
1.8
23
16.5
Zaragoza - visitante
3382    0
3408    3
3426    3
3468    0
3481    0
3505    3
3524    3
3547    0
3567    0
3586    3
Name: FTR, dtype: object
1.5
Sociedad - local
3382    3
3406    3
3428    3
3456    3
3462    1
3487    1
3503    3
3526    0
3547    3
3563    3
Name: FTR, dtype: object
2.3
19
13.7
Ath Bilbao - visitante
3385    1
3401    0
3425    0
3450    0
3463    3
3485    1
3509    0
3527    0
3543    0
3560    1
Name: FTR, dtype: object
0.6
Sevilla - local
3388    3
3417    3
3433    3
3442    0
3467    1
3481    3
3500    3
3537    0
3556    1
3577    3
Name: FTR, dtype: object
2.0
19
16.1
Barcelona - visitante
3390    3
3403    3
3429    1
3451    3
3479    3
3495    3
3518    3
3537    3
3542    3
3565    3
Name: FTR, dtype: object
2.8
Malaga - local
3389    3
3407    1
3424    3
3453    3
3474    1
3490    3
3508    0
3521    3
3548    3
3567    3
Name: FTR, dtype: object
2.3
20
19.4
Betis - visitante
3381    3
3416    3
3432    0
3442    3
3461    0
3487    1
3508    3
3536    0
3550    0
3570    3
Name: FTR, dtype: object
1.6
Betis - local
3379    3
3409    0
3429    1
3454    1
3476    3
3499    3
3515    1
3522    1
3549    0
3569    1
Name: FTR, dtype: object
1.4
15
12.3
Ath Madrid - visitante
3414    1
3420    3
3454    1
3473    3
3493    0
3511    0
3532    0
3556    1
3571    1
3587    1
Name: FTR, dtype: object
1.1
Vallecano - local
3391    1
3411    3
3421    3
3451    0
3473    0
3496    3
3512    0
3536    3
3555    3
3561    0
Name: FTR, dtype: object
1.6
15
14.9
Real Madrid - visitante
3388    0
3405    0
3436    3
3446    3
3469    3
3486    3
3507    3
3523    1
3549    3
3561    3
Name: FTR, dtype: object
2.2
La Coruna - local
3398    1
3412    3
Name: FTR, dtype: object
2.0
3
10.0
Sevilla - visitante
3391    1
3404    1
3427    1
3452    0
3470    0
3494    0
3510    3
3520    3
3546    0
3562    3
Name: FTR, dtype: object
1.2
Mallorca - local
3397    3
3418    3
3435    3
3443    3
3468    3
3492    1
3518    0
3532    3
3557    1
3572    3
Name: FTR, dtype: object
2.3
13
13.4
Valencia - visitante
3394    0
3413    1
3428    0
3453    0
3475    0
3491    1
3519    0
3534    3
3553    3
3575    0
Name: FTR, dtype: object
0.8
Levante - local
3393    3
3414    1
3425    3
3457    3
3479    0
3493    3
3513    0
3533    3
3550    3
3573    0
Name: FTR, dtype: object
1.9
20
10.8
Sociedad - visitante
3397    0
3415    0
3434    0
3445    1
3474    1
3498    1
3517    0
3539    0
3554    0
3574    0
Name: FTR, dtype: object
0.3
Ath Madrid - local
3386    3
3401    3
3438    3
3445    1
3465    3
3486    0
3504    3
3527    3
3545    3
3565    0
Name: FTR, dtype: object
2.2
23
13.8
Valladolid - visitante
3395    0
3410    3
Name: FTR, dtype: object
1.5
Ath Bilbao - local
3395    3
3416    0
3439    1
3446    0
3477    3
3494    3
3516    1
3534    0
3554    3
3576    3
Name: FTR, dtype: object
1.7
13
14.2
Malaga - visitante
3396    3
3419    3
3438    0
3444    0
3460    1
3480    0
3514    3
3531    1
3558    3
3576    0
Name: FTR, dtype: object
1.4
Zaragoza - local
3396    0
3410    0
3430    3
3440    3
3450    3
3471    3
3495    0
3511    3
3535    1
3551    3
Name: FTR, dtype: object
1.9
11
14.7
Osasuna - visitante
3399    0
3412    0
3422    3
3441    0
3455    1
3476    0
3496    0
3513    3
3535    1
3557    1
Name: FTR, dtype: object
0.9
Celta - local
3399    3
3419    0
Name: FTR, dtype: object
1.5
2
14.5
Getafe - visitante
3398    1
3417    0
3439    1
3464    0
3489    0
3504    0
3528    1
3540    3
3569    1
3582    0
Name: FTR, dtype: object
0.7
Betis - local
3409    0
3429    1
3454    1
3476    3
3499    3
3515    1
3522    1
3549    0
3569    1
3589    3
Name: FTR, dtype: object
1.4
16
13.3
Espanol - visitante
3393    0
3418    0
3437    0
3448    0
3465    0
3488    0
3501    1
3522    1
3552    0
3579    1
Name: FTR, dtype: object
0.3
Barcelona - local
3394    3
3415    3
3437    3
3444    3
3469    0
3489    3
3509    3
3529    3
3559    3
3575    3
Name: FTR, dtype: object
2.7
34
16.7
Granada - visitante
3392    0
3411    0
3421    0
3457    0
3471    0
3492    1
3506    3
3529    0
3545    0
3564    0
Name: FTR, dtype: object
0.4
Valladolid - local
3400    3
Name: FTR, dtype: object
3.0
2
15.0
Betis - visitante
3416    3
3432    0
3442    3
3461    0
3487    1
3508    3
3536    0
3550    0
3570    3
3595    0
Name: FTR, dtype: object
1.3
Sociedad - local
3406    3
3428    3
3456    3
3462    1
3487    1
3503    3
3526    0
3547    3
3563    3
3580    3
Name: FTR, dtype: object
2.3
19
14.2
Zaragoza - visitante
3408    3
3426    3
3468    0
3481    0
3505    3
3524    3
3547    0
3567    0
3586    3
3608    0
Name: FTR, dtype: object
1.5
Osasuna - local
3403    0
3434    3
3460    1
3488    3
3507    0
3528    1
3543    3
3564    3
3588    3
3600    0
Name: FTR, dtype: object
1.7
13
14.9
Mallorca - visitante
3407    1
3423    0
3458    3
3477    0
3482    3
3500    0
3525    3
3541    1
3563    0
3585    0
Name: FTR, dtype: object
1.1
Granada - local
3404    1
3436    0
3448    3
3464    3
3485    1
3510    0
3538    3
3553    0
3574    3
3590    3
Name: FTR, dtype: object
1.7
15
14.4
La Coruna - visitante
3402    1
Name: FTR, dtype: object
1.0
Espanol - local
3408    0
3427    1
3459    0
3475    3
3498    1
3514    0
3530    3
3544    3
3568    0
3586    0
Name: FTR, dtype: object
1.1
18
14.3
Ath Bilbao - visitante
3401    0
3425    0
3450    0
3463    3
3485    1
3509    0
3527    0
3543    0
3560    1
3589    0
Name: FTR, dtype: object
0.5
Ath Madrid - local
3401    3
3438    3
3445    1
3465    3
3486    0
3504    3
3527    3
3545    3
3565    0
3594    1
Name: FTR, dtype: object
2.0
19
13.5

Vallecano - visitante
3409    3
3433    0
3443    0
3466    0
3483    0
3503    0
3521    0
3544    0
3573    3
3591    3
Name: FTR, dtype: object
0.9
Valencia - local
3402    1
3431    3
3441    3
3461    3
3483    3
3502    1
3524    0
3541    1
3562    0
3583    3
Name: FTR, dtype: object
1.8
25
17.2
Celta - visitante
3406    0
Name: FTR, dtype: object
0.0
Sevilla - local
3417    3
3433    3
3442    0
3467    1
3481    3
3500    3
3537    0
3556    1
3577    3
3593    0
Name: FTR, dtype: object
1.7
19
17.1
Real Madrid - visitante
3405    0
3436    3
3446    3
3469    3
3486    3
3507    3
3523    1
3549    3
3561    3
3597    3
Name: FTR, dtype: object
2.5
Malaga - local
3407    1
3424    3
3453    3
3474    1
3490    3
3508    0
3521    3
3548    3
3567    3
3585    3
Name: FTR, dtype: object
2.3
20
19.9
Levante - visitante
3400    0
3435    0
3440    0
3467    1
3484    0
3502    1
3526    3
3548    0
3568    3
3584    0
Name: FTR, dtype: object
0.8
Getafe - local
3405    3
3426    0
3449    1
3458    0
3470    3
3497    3
3519    3
3539    3
3558    0
3579    1
Name: FTR, dtype: object
1.7
17
11.3
Barcelona - visitante
3403    3
3429    1
3451    3
3479    3
3495    3
3518    3
3537    3
3542    3
3565    3
3588    0
Name: FTR, dtype: object
2.5
Vallecano - local
3411    3
3421    3
3451    0
3473    0
3496    3
3512    0
3536    3
3555    3
3561    0
3582    3
Name: FTR, dtype: object
1.8
17
14.9
Sevilla - visitante
3404    1
3427    1
3452    0
3470    0
3494    0
3510    3
3520    3
3546    0
3562    3
3580    0
Name: FTR, dtype: object
1.1
Real Madrid - local
3413    1
3423    3
3452    3
3478    3
3491    1
3517    3
3531    1
3552    3
3578    3
3584    3
Name: FTR, dtype: object
2.4
30
22.7
Granada - visitante
3411    0
3421    0
3457    0
3471    0
3492    1
3506    3
3529    0
3545    0
3564    0
3581    0
Name: FTR, dtype: object
0.4
Levante - local
3414    1
3425    3
3457    3
3479    0
3493    3
3513    0
3533    3
3550    3
3573    0
3596    1
Name: FTR, dtype: object
1.7
18
11.1
Espanol - visitante
3418    0
3437    0
3448    0
3465    0
3488    0
3501    1
3522    1
3552    0
3579    1
3599    1
Name: FTR, dtype: object
0.4
Barcelona - local
3415    3
3437    3
3444    3
3469    0
3489    3
3509    3
3529    3
3559    3
3575    3
3598    3
Name: FTR, dtype: object
2.7
35
17.4
Valencia - visitante
3413    1
3428    0
3453    0
3475    0
3491    1
3519    0
3534    3
3553    3
3575    0
3594    1
Name: FTR, dtype: object
0.9
Ath Bilbao - local
3416    0
3439    1
3446    0
3477    3
3494    3
3516    1
3534    0
3554    3
3576    3
3599    1
Name: FTR, dtype: object
1.5
14
14.5
Valladolid - visitante
3410    3
Name: FTR, dtype: object
3.0
Zaragoza - local
3410    0
3430    3
3440    3
3450    3
3471    3
3495    0
3511    3
3535    1
3551    3
3570    0
Name: FTR, dtype: object
1.9
11
14.9
Malaga - visitante
3419    3
3438    0
3444    0
3460    1
3480    0
3514    3
3531    1
3558    3
3576    0
3590    0
Name: FTR, dtype: object
1.1
Mallorca - local
3418    3
3435    3
3443    3
3468    3
3492    1
3518    0
3532    3
3557    1
3572    3
3595    3
Name: FTR, dtype: object
2.3
13
13.0
Sociedad - visitante
3415    0
3434    0
3445    1
3474    1
3498    1
3517    0
3539    0
3554    0
3574    0
3598    0
Name: FTR, dtype: object
0.3
La Coruna - local
3412    3
Name: FTR, dtype: object
3.0
2
10.0
Getafe - visitante
3417    0
3439    1
3464    0
3489    0
3504    0
3528    1
3540    3
3569    1
3582    0
3604    3
Name: FTR, dtype: object
0.9
Celta - local
3419    0
Name: FTR, dtype: object
0.0
0
17.0
Osasuna - visitante
3412    0
3422    3
3441    0
3455    1
3476    0
3496    0
3513    3
3535    1
3557    1
3577    0
Name: FTR, dtype: object
0.9
Valladolid - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Levante - visitante
3435    0
3440    0
3467    1
3484    0
3502    1
3526    3
3548    0
3568    3
3584    0
3624    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
3438    3
3445    1
3465    3
3486    0
3504    3
3527    3
3545    3
3565    0
3594    1
3623    3
Name: FTR, dtype: object
2.0
18
13.2
Ath Bilbao - visitante
3425    0
3450    0
3463    3
3485    1
3509    0
3527    0
3543    0
3560    1
3589    0
3607    3
Name: FTR, dtype: object
0.8
Valencia - local
3431    3
3441    3
3461    3
3483    3
3502    1
3524    0
3541    1
3562    0
3583    3
3626    0
Name: FTR, dtype: object
1.7
22
17.1
La Coruna - visitante
Series([], Name: FTR, dtype: object)
0.0
Osasuna - local
3434    3
3460    1
3488    3
3507    0
3528    1
3543    3
3564    3
3588    3
3600    0
3613    1
Name: FTR, dtype: object
1.8
13
14.4
Barcelona - visitante
3429    1
3451    3
3479    3
3495    3
3518    3
3537    3
3542    3
3565    3
3588    0
3606    1
Name: FTR, dtype: object
2.3
Granada - local
3436    0
3448    3
3464    3
3485    1
3510    0
3538    3
3553    0
3574    3
3590    3
3629    0
Name: FTR, dtype: object
1.6
15
14.1
Sevilla - visitante
3427    1
3452    0
3470    0
3494    0
3510    3
3520    3
3546    0
3562    3
3580    0
3603    0
Name: FTR, dtype: object
1.0
Getafe - local
3426    0
3449    1
3458    0
3470    3
3497    3
3519    3
3539    3
3558    0
3579    1
3597    0
Name: FTR, dtype: object
1.4
15
10.7
Real Madrid - visitante
3436    3
3446    3
3469    3
3486    3
3507    3
3523    1
3549    3
3561    3
3597    3
3628    3
Name: FTR, dtype: object
2.8
Sociedad - local
3428    3
3456    3
3462    1
3487    1
3503    3
3526    0
3547    3
3563    3
3580    3
3601    3
Name: FTR, dtype: object
2.3
22
14.1
Celta - visitante
Series([], Name: FTR, dtype: object)
0.0
Malaga - local
3424    3
3453    3
3474    1
3490    3
3508    0
3521    3
3548    3
3567    3
3585    3
3603    3
Name: FTR, dtype: object
2.5
21
19.0
Mallorca - visitante
3423    0
3458    3
3477    0
3482    3
3500    0
3525    3
3541    1
3563    0
3585    0
3609    0
Name: FTR, dtype: object
1.0
Espanol - local
3427    1
3459    0
3475    3
3498    1
3514    0
3530    3
3544    3
3568    0
3586    0
3609    3
Name: FTR, dtype: object
1.4
18
14.6
Zaragoza - visitante
3426    3
3468    0
3481    0
3505    3
3524    3
3547    0
3567    0
3586    3
3608    0
3615    1
Name: FTR, dtype: object
1.3
Betis - local
3429    1
3454    1
3476    3
3499    3
3515    1
3522    1
3549    0
3569    1
3589    3
3605    0
Name: FTR, dtype: object
1.4
16
13.5
Vallecano - visitante
3433    0
3443    0
3466    0
3483    0
3503    0
3521    0
3544    0
3573    3
3591    3
3629    3
Name: FTR, dtype: object
0.9
Zaragoza - local
3430    3
3440    3
3450    3
3471    3
3495    0
3511    3
3535    1
3551    3
3570    0
3591    0
Name: FTR, dtype: object
1.9
12
14.8
Valladolid - visitante
Series([], Name: FTR, dtype: object)
0.0
Vallecano - local
3421    3
3451    0
3473    0
3496    3
3512    0
3536    3
3555    3
3561    0
3582    3
3607    0
Name: FTR, dtype: object
1.5
18
15.2
Granada - visitante
3421    0
3457    0
3471    0
3492    1
3506    3
3529    0
3545    0
3564    0
3581    0
3605    3
Name: FTR, dtype: object
0.7
La Coruna - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Osasuna - visitante
3422    3
3441    0
3455    1
3476    0
3496    0
3513    3
3535    1
3557    1
3577    0
3592    1
Name: FTR, dtype: object
1.0
Real Madrid - local
3423    3
3452    3
3478    3
3491    1
3517    3
3531    1
3552    3
3578    3
3584    3
3608    3
Name: FTR, dtype: object
2.6
32
22.1
Valencia - visitante
3428    0
3453    0
3475    0
3491    1
3519    0
3534    3
3553    3
3575    0
3594    1
3602    1
Name: FTR, dtype: object
0.9
Levante - local
3425    3
3457    3
3479    0
3493    3
3513    0
3533    3
3550    3
3573    0
3596    1
3604    0
Name: FTR, dtype: object
1.6
18
12.3
Ath Madrid - visitante
3420    3
3454    1
3473    3
3493    0
3511    0
3532    0
3556    1
3571    1
3587    1
3600    3
Name: FTR, dtype: object
1.3
Barcelona - local
3437    3
3444    3
3469    0
3489    3
3509    3
3529    3
3559    3
3575    3
3598    3
3622    3
Name: FTR, dtype: object
2.7
34
17.2
Sociedad - visitante
3434    0
3445    1
3474    1
3498    1
3517    0
3539    0
3554    0
3574    0
3598    0
3626    3
Name: FTR, dtype: object
0.6
Ath Bilbao - local
3439    1
3446    0
3477    3
3494    3
3516    1
3534    0
3554    3
3576    3
3599    1
3624    3
Name: FTR, dtype: object
1.8
14
14.5
Betis - visitante
3432    0
3442    3
3461    0
3487    1
3508    3
3536    0
3550    0
3570    3
3595    0
3622    0
Name: FTR, dtype: object
1.0
Sevilla - local
3433    3
3442    0
3467    1
3481    3
3500    3
3537    0
3556    1
3577    3
3593    0
3627    1
Name: FTR, dtype: object
1.5
17
17.4
Getafe - visitante
3439    1
3464    0
3489    0
3504    0
3528    1
3540    3
3569    1
3582    0
3604    3
3617    3
Name: FTR, dtype: object
1.2
Mallorca - local
3435    3
3443    3
3468    3
3492    1
3518    0
3532    3
3557    1
3572    3
3595    3
3628    0
Name: FTR, dtype: object
2.0
12
12.1
Espanol - visitante
3437    0
3448    0
3465    0
3488    0
3501    1
3522    1
3552    0
3579    1
3599    1
3627    1
Name: FTR, dtype: object
0.5
Celta - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Malaga - visitante
3438    0
3444    0
3460    1
3480    0
3514    3
3531    1
3558    3
3576    0
3590    0
3620    0
Name: FTR, dtype: object
0.8
Villarreal - local
3455    1
3472    1
3480    3
3501    1
3523    1
3540    0
3560    1
3581    3
3606    1
3610    3
Name: FTR, dtype: object
1.5
14
13.5
Ath Madrid - visitante
3454    1
3473    3
3493    0
3511    0
3532    0
3556    1
3571    1
3587    1
3600    3
3616    3
Name: FTR, dtype: object
1.3
Vallecano - local
3451    0
3473    0
3496    3
3512    0
3536    3
3555    3
3561    0
3582    3
3607    0
3611    0

Name: FTR, dtype: object
1.2
17
14.6
Granada - visitante
3457    0
3471    0
3492    1
3506    3
3529    0
3545    0
3564    0
3581    0
3605    3
3618    0
Name: FTR, dtype: object
0.7
Santander - local
3463    0
3482    0
3506    0
3520    0
3542    0
3566    1
3587    1
3602    1
3617    0
3636    3
Name: FTR, dtype: object
0.6
5
11.3
Osasuna - visitante
3441    0
3455    1
3476    0
3496    0
3513    3
3535    1
3557    1
3577    0
3592    1
3635    1
Name: FTR, dtype: object
0.8
Real Madrid - local
3452    3
3478    3
3491    1
3517    3
3531    1
3552    3
3578    3
3584    3
3608    3
3612    3
Name: FTR, dtype: object
2.6
32
22.1
Mallorca - visitante
3458    3
3477    0
3482    3
3500    0
3525    3
3541    1
3563    0
3585    0
3609    0
3611    3
Name: FTR, dtype: object
1.3
Malaga - local
3453    3
3474    1
3490    3
3508    0
3521    3
3548    3
3567    3
3585    3
3603    3
3614    0
Name: FTR, dtype: object
2.2
21
17.7
Sp Gijon - visitante
3459    3
3478    0
3497    0
3516    1
3538    0
3559    0
3566    1
3583    0
3601    0
3610    0
Name: FTR, dtype: object
0.5
Levante - local
3457    3
3479    0
3493    3
3513    0
3533    3
3550    3
3573    0
3596    1
3604    0
3615    1
Name: FTR, dtype: object
1.4
15
11.7
Ath Bilbao - visitante
3450    0
3463    3
3485    1
3509    0
3527    0
3543    0
3560    1
3589    0
3607    3
3612    0
Name: FTR, dtype: object
0.8
Getafe - local
3449    1
3458    0
3470    3
3497    3
3519    3
3539    3
3558    0
3579    1
3597    0
3632    1
Name: FTR, dtype: object
1.5
15
12.0
Zaragoza - visitante
3468    0
3481    0
3505    3
3524    3
3547    0
3567    0
3586    3
3608    0
3615    1
3636    0
Name: FTR, dtype: object
1.0
Espanol - local
3459    0
3475    3
3498    1
3514    0
3530    3
3544    3
3568    0
3586    0
3609    3
3618    3
Name: FTR, dtype: object
1.6
20
15.3
Sevilla - visitante
3452    0
3470    0
3494    0
3510    3
3520    3
3546    0
3562    3
3580    0
3603    0
3619    1
Name: FTR, dtype: object
1.0
Sociedad - local
3456    3
3462    1
3487    1
3503    3
3526    0
3547    3
3563    3
3580    3
3601    3
3616    0
Name: FTR, dtype: object
2.0
21
14.4
Valencia - visitante
3453    0
3475    0
3491    1
3519    0
3534    3
3553    3
3575    0
3594    1
3602    1
3613    1
Name: FTR, dtype: object
1.0
Betis - local
3454    1
3476    3
3499    3
3515    1
3522    1
3549    0
3569    1
3589    3
3605    0
3619    1
Name: FTR, dtype: object
1.4
15
14.6
Barcelona - visitante
3451    3
3479    3
3495    3
3518    3
3537    3
3542    3
3565    3
3588    0
3606    1
3614    3
Name: FTR, dtype: object
2.5
Zaragoza - local
3440    3
3450    3
3471    3
3495    0
3511    3
3535    1
3551    3
3570    0
3591    0
3625    1
Name: FTR, dtype: object
1.7
11
13.4
Santander - visitante
3449    1
3456    0
3472    1
3490    0
3515    1
3530    0
3555    0
3578    0
3596    1
3621    3
Name: FTR, dtype: object
0.7
Valencia - local
3441    3
3461    3
3483    3
3502    1
3524    0
3541    1
3562    0
3583    3
3626    0
3640    3
Name: FTR, dtype: object
1.7
23
16.7
Villarreal - visitante
3447    3
3462    1
3499    0
3512    3
3533    0
3551    0
3572    0
3593    3
3623    0
3642    0
Name: FTR, dtype: object
1.0
Sp Gijon - local
3447    0
3466    3
3484    3
3505    0
3525    0
3546    3
3571    1
3592    1
3620    3
3645    0
Name: FTR, dtype: object
1.4
16
15.7
Betis - visitante
3442    3
3461    0
3487    1
3508    3
3536    0
3550    0
3570    3
3595    0
3622    0
3644    3
Name: FTR, dtype: object
1.3
Sevilla - local
3442    0
3467    1
3481    3
3500    3
3537    0
3556    1
3577    3
3593    0
3627    1
3646    0
Name: FTR, dtype: object
1.2
14
17.8
Vallecano - visitante
3443    0
3466    0
3483    0
3503    0
3521    0
3544    0
3573    3
3591    3
3629    3
3665    0
Name: FTR, dtype: object
0.9
Osasuna - local
3460    1
3488    3
3507    0
3528    1
3543    3
3564    3
3588    3
3600    0
3613    1
3621    0
Name: FTR, dtype: object
1.5
12
13.4
Sociedad - visitante
3445    1
3474    1
3498    1
3517    0
3539    0
3554    0
3574    0
3598    0
3626    3
3641    1
Name: FTR, dtype: object
0.7
Mallorca - local
3443    3
3468    3
3492    1
3518    0
3532    3
3557    1
3572    3
3595    3
3628    0
3647    0
Name: FTR, dtype: object
1.7
12
12.3
Levante - visitante
3440    0
3467    1
3484    0
3502    1
3526    3
3548    0
3568    3
3584    0
3624    0
3643    0
Name: FTR, dtype: object
0.8
Granada - local
3448    3
3464    3
3485    1
3510    0
3538    3
3553    0
3574    3
3590    3
3629    0
3643    3
Name: FTR, dtype: object
1.9
16
14.6
Real Madrid - visitante
3446    3
3469    3
3486    3
3507    3
3523    1
3549    3
3561    3
3597    3
3628    3
3646    3
Name: FTR, dtype: object
2.8
Barcelona - local
3444    3
3469    0
3489    3
3509    3
3529    3
3559    3
3575    3
3598    3
3622    3
3669    3
Name: FTR, dtype: object
2.7
35
17.6
Espanol - visitante
3448    0
3465    0
3488    0
3501    1
3522    1
3552    0
3579    1
3599    1
3627    1
3645    3
Name: FTR, dtype: object
0.8
Ath Madrid - local
3445    1
3465    3
3486    0
3504    3
3527    3
3545    3
3565    0
3594    1
3623    3
3644    0
Name: FTR, dtype: object
1.7
16
15.4
Malaga - visitante
3444    0
3460    1
3480    0
3514    3
3531    1
3558    3
3576    0
3590    0
3620    0
3640    0
Name: FTR, dtype: object
0.8
Ath Bilbao - local
3446    0
3477    3
3494    3
3516    1
3534    0
3554    3
3576    3
3599    1
3624    3
3648    3
Name: FTR, dtype: object
2.0
16
14.0
Getafe - visitante
3464    0
3489    0
3504    0
3528    1
3540    3
3569    1
3582    0
3604    3
3617    3
3625    1
Name: FTR, dtype: object
1.2
Zaragoza - local
3450    3
3471    3
3495    0
3511    3
3535    1
3551    3
3570    0
3591    0
3625    1
3649    0
Name: FTR, dtype: object
1.4
10
12.9
Levante - visitante
3467    1
3484    0
3502    1
3526    3
3548    0
3568    3
3584    0
3624    0
3643    0
3669    0
Name: FTR, dtype: object
0.8
Valencia - local
3461    3
3483    3
3502    1
3524    0
3541    1
3562    0
3583    3
3626    0
3640    3
3666    3
Name: FTR, dtype: object
1.7
21
15.2
Osasuna - visitante
3455    1
3476    0
3496    0
3513    3
3535    1
3557    1
3577    0
3592    1
3635    1
3652    1
Name: FTR, dtype: object
0.9
Sevilla - local
3467    1
3481    3
3500    3
3537    0
3556    1
3577    3
3593    0
3627    1
3646    0
3660    3
Name: FTR, dtype: object
1.5
16
18.1
Betis - visitante
3461    0
3487    1
3508    3
3536    0
3550    0
3570    3
3595    0
3622    0
3644    3
3662    0
Name: FTR, dtype: object
1.0
Mallorca - local
3468    3
3492    1
3518    0
3532    3
3557    1
3572    3
3595    3
3628    0
3647    0
3663    1
Name: FTR, dtype: object
1.5
12
11.5
Vallecano - visitante
3466    0
3483    0
3503    0
3521    0
3544    0
3573    3
3591    3
3629    3
3665    0
3670    0
Name: FTR, dtype: object
0.9
Barcelona - local
3469    0
3489    3
3509    3
3529    3
3559    3
3575    3
3598    3
3622    3
3669    3
3670    3
Name: FTR, dtype: object
2.7
35
17.7
Malaga - visitante
3460    1
3480    0
3514    3
3531    1
3558    3
3576    0
3590    0
3620    0
3640    0
3661    0
Name: FTR, dtype: object
0.8
Ath Madrid - local
3465    3
3486    0
3504    3
3527    3
3545    3
3565    0
3594    1
3623    3
3644    0
3665    3
Name: FTR, dtype: object
1.9
18
16.2
Sociedad - visitante
3474    1
3498    1
3517    0
3539    0
3554    0
3574    0
3598    0
3626    3
3641    1
3650    1
Name: FTR, dtype: object
0.7
Ath Bilbao - local
3477    3
3494    3
3516    1
3534    0
3554    3
3576    3
3599    1
3624    3
3648    3
3655    1
Name: FTR, dtype: object
2.1
17
14.5
Real Madrid - visitante
3469    3
3486    3
3507    3
3523    1
3549    3
3561    3
3597    3
3628    3
3646    3
3667    3
Name: FTR, dtype: object
2.8
Sp Gijon - local
3466    3
3484    3
3505    0
3525    0
3546    3
3571    1
3592    1
3620    3
3645    0
3667    0
Name: FTR, dtype: object
1.4
14
14.5
Villarreal - visitante
3462    1
3499    0
3512    3
3533    0
3551    0
3572    0
3593    3
3623    0
3642    0
3668    0
Name: FTR, dtype: object
0.7
Granada - local
3464    3
3485    1
3510    0
3538    3
3553    0
3574    3
3590    3
3629    0
3643    3
3659    1
Name: FTR, dtype: object
1.7
16
14.2
Espanol - visitante
3465    0
3488    0
3501    1
3522    1
3552    0
3579    1
3599    1
3627    1
3645    3
3666    0
Name: FTR, dtype: object
0.8
Getafe - local
3458    0
3470    3
3497    3
3519    3
3539    3
3558    0
3579    1
3597    0
3632    1
3653    3
Name: FTR, dtype: object
1.7
15
13.0
Santander - visitante
3456    0
3472    1
3490    0
3515    1
3530    0
3555    0
3578    0
3596    1
3621    3
3655    1
Name: FTR, dtype: object
0.7
Zaragoza - local
3471    3
3495    0
3511    3
3535    1
3551    3
3570    0
3591    0
3625    1
3649    0
3672    0
Name: FTR, dtype: object
1.1
8
12.1
Ath Bilbao - visitante
3463    3
3485    1
3509    0
3527    0
3543    0
3560    1
3589    0
3607    3
3612    0
3632    1
Name: FTR, dtype: object
0.9
Vallecano - local
3473    0
3496    3
3512    0
3536    3
3555    3
3561    0
3582    3
3607    0
3611    0
3631    3
Name: FTR, dtype: object
1.5
19
14.7
Barcelona - visitante
3479    3
3495    3
3518    3
3537    3
3542    3
3565    3
3588    0
3606    1
3614    3
3633    1
Name: FTR, dtype: object
2.3
Real Madrid - local
3478    3
3491    1
3517    3
3531    1
3552    3
3578    3
3584    3
3608    3
3612    3
3637    3
Name: FTR, dtype: object
2.6
34
24.1
Sevilla - visitante
3470    0
3494    0
3510    3
3520    3
3546    0
3562    3
3580    0
3603    0
3619    1
3631    0
Name: FTR, dtype: object
1.0
Malaga - local
3474    1
3490    3
3508    0
3521    3
3548    3
3567    3
3585    3
3603    3
3614    0
3638    1
Name: FTR, dtype: object
2.0
20
17.2
Valencia - visitante
3475    0
3491    1
3519    0
3534    3
3553    3
3575    0
3594    1
3602    1
3613    1
3630    1
Name: FTR, dtype: object
1.1
Betis - local
3476    3
3499    3
3515    1
3522    1
3549    0
3569    1
3589    3
3605    0
3619    1
3634    3

Name: FTR, dtype: object
1.6
15
15.6
Ath Madrid - visitante
3473    3
3493    0
3511    0
3532    0
3556    1
3571    1
3587    1
3600    3
3616    3
3638    1
Name: FTR, dtype: object
1.3
Villarreal - local
3472    1
3480    3
3501    1
3523    1
3540    0
3560    1
3581    3
3606    1
3610    3
3630    1
Name: FTR, dtype: object
1.5
15
12.8
Osasuna - visitante
3476    0
3496    0
3513    3
3535    1
3557    1
3577    0
3592    1
3635    1
3652    1
3675    3
Name: FTR, dtype: object
1.1
Sociedad - local
3462    1
3487    1
3503    3
3526    0
3547    3
3563    3
3580    3
3601    3
3616    0
3635    1
Name: FTR, dtype: object
1.8
18
14.7
Santander - visitante
3472    1
3490    0
3515    1
3530    0
3555    0
3578    0
3596    1
3621    3
3655    1
3673    0
Name: FTR, dtype: object
0.7
Levante - local
3479    0
3493    3
3513    0
3533    3
3550    3
3573    0
3596    1
3604    0
3615    1
3639    1
Name: FTR, dtype: object
1.2
12
11.6
Granada - visitante
3471    0
3492    1
3506    3
3529    0
3545    0
3564    0
3581    0
3605    3
3618    0
3637    0
Name: FTR, dtype: object
0.7
Getafe - local
3470    3
3497    3
3519    3
3539    3
3558    0
3579    1
3597    0
3632    1
3653    3
3680    3
Name: FTR, dtype: object
2.0
15
12.5
Mallorca - visitante
3477    0
3482    3
3500    0
3525    3
3541    1
3563    0
3585    0
3609    0
3611    3
3639    1
Name: FTR, dtype: object
1.1
Espanol - local
3475    3
3498    1
3514    0
3530    3
3544    3
3568    0
3586    0
3609    3
3618    3
3633    1
Name: FTR, dtype: object
1.7
21
14.9
Sp Gijon - visitante
3478    0
3497    0
3516    1
3538    0
3559    0
3566    1
3583    0
3601    0
3610    0
3634    0
Name: FTR, dtype: object
0.2
Osasuna - local
3488    3
3507    0
3528    1
3543    3
3564    3
3588    3
3600    0
3613    1
3621    0
3642    3
Name: FTR, dtype: object
1.7
13
14.1
Malaga - visitante
3480    0
3514    3
3531    1
3558    3
3576    0
3590    0
3620    0
3640    0
3661    0
3681    3
Name: FTR, dtype: object
1.0
Valencia - local
3483    3
3502    1
3524    0
3541    1
3562    0
3583    3
3626    0
3640    3
3666    3
3688    0
Name: FTR, dtype: object
1.4
19
15.2
Betis - visitante
3487    1
3508    3
3536    0
3550    0
3570    3
3595    0
3622    0
3644    3
3662    0
3687    0
Name: FTR, dtype: object
1.0
Sociedad - local
3487    1
3503    3
3526    0
3547    3
3563    3
3580    3
3601    3
3616    0
3635    1
3661    3
Name: FTR, dtype: object
2.0
20
14.2
Villarreal - visitante
3499    0
3512    3
3533    0
3551    0
3572    0
3593    3
3623    0
3642    0
3668    0
3671    0
Name: FTR, dtype: object
0.6
Santander - local
3482    0
3506    0
3520    0
3542    0
3566    1
3587    1
3602    1
3617    0
3636    3
3641    1
Name: FTR, dtype: object
0.7
5
11.3
Ath Bilbao - visitante
3485    1
3509    0
3527    0
3543    0
3560    1
3589    0
3607    3
3612    0
3632    1
3663    1
Name: FTR, dtype: object
0.7
Granada - local
3485    1
3510    0
3538    3
3553    0
3574    3
3590    3
3629    0
3643    3
3659    1
3664    3
Name: FTR, dtype: object
1.7
16
14.2
Getafe - visitante
3489    0
3504    0
3528    1
3540    3
3569    1
3582    0
3604    3
3617    3
3625    1
3647    3
Name: FTR, dtype: object
1.5
Ath Madrid - local
3486    0
3504    3
3527    3
3545    3
3565    0
3594    1
3623    3
3644    0
3665    3
3686    3
Name: FTR, dtype: object
1.9
18
17.1
Espanol - visitante
3488    0
3501    1
3522    1
3552    0
3579    1
3599    1
3627    1
3645    3
3666    0
3683    1
Name: FTR, dtype: object
0.9
Sp Gijon - local
3484    3
3505    0
3525    0
3546    3
3571    1
3592    1
3620    3
3645    0
3667    0
3682    3
Name: FTR, dtype: object
1.4
14
14.8
Vallecano - visitante
3483    0
3503    0
3521    0
3544    0
3573    3
3591    3
3629    3
3665    0
3670    0
3685    1
Name: FTR, dtype: object
1.0
Sevilla - local
3481    3
3500    3
3537    0
3556    1
3577    3
3593    0
3627    1
3646    0
3660    3
3684    0
Name: FTR, dtype: object
1.4
16
16.7
Levante - visitante
3484    0
3502    1
3526    3
3548    0
3568    3
3584    0
3624    0
3643    0
3669    0
3686    0
Name: FTR, dtype: object
0.7
Mallorca - local
3492    1
3518    0
3532    3
3557    1
3572    3
3595    3
3628    0
3647    0
3663    1
3673    3
Name: FTR, dtype: object
1.5
13
11.5
Zaragoza - visitante
3481    0
3505    3
3524    3
3547    0
3567    0
3586    3
3608    0
3615    1
3636    0
3648    0
Name: FTR, dtype: object
1.0
Barcelona - local
3489    3
3509    3
3529    3
3559    3
3575    3
3598    3
3622    3
3669    3
3670    3
3689    3
Name: FTR, dtype: object
3.0
38
19.0
Real Madrid - visitante
3486    3
3507    3
3523    1
3549    3
3561    3
3597    3
3628    3
3646    3
3667    3
3688    3
Name: FTR, dtype: object
2.8
Getafe - local
3497    3
3519    3
3539    3
3558    0
3579    1
3597    0
3632    1
3653    3
3680    3
3694    3
Name: FTR, dtype: object
2.0
13
12.7
Sevilla - visitante
3494    0
3510    3
3520    3
3546    0
3562    3
3580    0
3603    0
3619    1
3631    0
3657    0
Name: FTR, dtype: object
1.0
Zaragoza - local
3495    0
3511    3
3535    1
3551    3
3570    0
3591    0
3625    1
3649    0
3672    0
3690    1
Name: FTR, dtype: object
0.9
9
12.6
Granada - visitante
3492    1
3506    3
3529    0
3545    0
3564    0
3581    0
3605    3
3618    0
3637    0
3653    0
Name: FTR, dtype: object
0.7
Villarreal - local
3480    3
3501    1
3523    1
3540    0
3560    1
3581    3
3606    1
3610    3
3630    1
3650    1
Name: FTR, dtype: object
1.5
15
12.8
Santander - visitante
3490    0
3515    1
3530    0
3555    0
3578    0
3596    1
3621    3
3655    1
3673    0
3693    1
Name: FTR, dtype: object
0.7
Vallecano - local
3496    3
3512    0
3536    3
3555    3
3561    0
3582    3
3607    0
3611    0
3631    3
3651    0
Name: FTR, dtype: object
1.5
20
15.4
Ath Madrid - visitante
3493    0
3511    0
3532    0
3556    1
3571    1
3587    1
3600    3
3616    3
3638    1
3654    0
Name: FTR, dtype: object
1.0
Malaga - local
3490    3
3508    0
3521    3
3548    3
3567    3
3585    3
3603    3
3614    0
3638    1
3652    1
Name: FTR, dtype: object
2.0
20
17.2
Sociedad - visitante
3498    1
3517    0
3539    0
3554    0
3574    0
3598    0
3626    3
3641    1
3650    1
3676    3
Name: FTR, dtype: object
0.9
Espanol - local
3498    1
3514    0
3530    3
3544    3
3568    0
3586    0
3609    3
3618    3
3633    1
3654    3
Name: FTR, dtype: object
1.7
21
15.1
Valencia - visitante
3491    1
3519    0
3534    3
3553    3
3575    0
3594    1
3602    1
3613    1
3630    1
3658    0
Name: FTR, dtype: object
1.1
Betis - local
3499    3
3515    1
3522    1
3549    0
3569    1
3589    3
3605    0
3619    1
3634    3
3658    3
Name: FTR, dtype: object
1.6
16
16.4
Osasuna - visitante
3496    0
3513    3
3535    1
3557    1
3577    0
3592    1
3635    1
3652    1
3675    3
3692    0
Name: FTR, dtype: object
1.1
Ath Bilbao - local
3494    3
3516    1
3534    0
3554    3
3576    3
3599    1
3624    3
3648    3
3655    1
3677    0
Name: FTR, dtype: object
1.8
16
15.0
Mallorca - visitante
3482    3
3500    0
3525    3
3541    1
3563    0
3585    0
3609    0
3611    3
3639    1
3649    3
Name: FTR, dtype: object
1.4
Real Madrid - local
3491    1
3517    3
3531    1
3552    3
3578    3
3584    3
3608    3
3612    3
3637    3
3656    0
Name: FTR, dtype: object
2.3
32
23.4
Sp Gijon - visitante
3497    0
3516    1
3538    0
3559    0
3566    1
3583    0
3601    0
3610    0
3634    0
3651    3
Name: FTR, dtype: object
0.5
Levante - local
3493    3
3513    0
3533    3
3550    3
3573    0
3596    1
3604    0
3615    1
3639    1
3657    3
Name: FTR, dtype: object
1.5
12
11.8
Barcelona - visitante
3495    3
3518    3
3537    3
3542    3
3565    3
3588    0
3606    1
3614    3
3633    1
3656    3
Name: FTR, dtype: object
2.3
Villarreal - local
3501    1
3523    1
3540    0
3560    1
3581    3
3606    1
3610    3
3630    1
3650    1
3687    3
Name: FTR, dtype: object
1.5
14
13.0
Malaga - visitante
3514    3
3531    1
3558    3
3576    0
3590    0
3620    0
3640    0
3661    0
3681    3
3699    1
Name: FTR, dtype: object
1.1
Sevilla - local
3500    3
3537    0
3556    1
3577    3
3593    0
3627    1
3646    0
3660    3
3684    0
3700    0
Name: FTR, dtype: object
1.1
14
17.6
Zaragoza - visitante
3505    3
3524    3
3547    0
3567    0
3586    3
3608    0
3615    1
3636    0
3648    0
3664    0
Name: FTR, dtype: object
1.0
Santander - local
3506    0
3520    0
3542    0
3566    1
3587    1
3602    1
3617    0
3636    3
3641    1
3668    3
Name: FTR, dtype: object
1.0
6
10.4
Mallorca - visitante
3500    0
3525    3
3541    1
3563    0
3585    0
3609    0
3611    3
3639    1
3649    3
3659    1
Name: FTR, dtype: object
1.2
Valencia - local
3502    1
3524    0
3541    1
3562    0
3583    3
3626    0
3640    3
3666    3
3688    0
3707    3
Name: FTR, dtype: object
1.4
18
15.5
Vallecano - visitante
3503    0
3521    0
3544    0
3573    3
3591    3
3629    3
3665    0
3670    0
3685    1
3706    0
Name: FTR, dtype: object
1.0
Sp Gijon - local
3505    0
3525    0
3546    3
3571    1
3592    1
3620    3
3645    0
3667    0
3682    3
3701    1
Name: FTR, dtype: object
1.2
12
13.5
Levante - visitante
3502    1
3526    3
3548    0
3568    3
3584    0
3624    0
3643    0
3669    0
3686    0
3703    0
Name: FTR, dtype: object
0.7
Granada - local
3510    0
3538    3
3553    0
3574    3
3590    3
3629    0
3643    3
3659    1
3664    3
3693    1
Name: FTR, dtype: object
1.7
14
14.9
Ath Bilbao - visitante
3509    0
3527    0
3543    0
3560    1
3589    0
3607    3
3612    0
3632    1
3663    1
3684    3
Name: FTR, dtype: object
0.9
Ath Madrid - local
3504    3
3527    3
3545    3
3565    0
3594    1
3623    3
3644    0
3665    3
3686    3
3705    3
Name: FTR, dtype: object
2.2
20
17.8
Real Madrid - visitante
3507    3
3523    1
3549    3
3561    3
3597    3
3628    3
3646    3
3667    3
3688    3
3708    3
Name: FTR, dtype: object
2.8
Sociedad - local
3503    3
3526    0
3547    3
3563    3
3580    3
3601    3
3616    0
3635    1
3661    3
3683    1
Name: FTR, dtype: object
2.0
19
13.7
Betis - visitante
3508    3
3536    0
3550    0
3570    3
3595    0
3622    0
3644    3
3662    0
3687    0
3702    0

Name: FTR, dtype: object
0.9
Osasuna - local
3507    0
3528    1
3543    3
3564    3
3588    3
3600    0
3613    1
3621    0
3642    3
3662    3
Name: FTR, dtype: object
1.7
13
13.5
Espanol - visitante
3501    1
3522    1
3552    0
3579    1
3599    1
3627    1
3645    3
3666    0
3683    1
3704    0
Name: FTR, dtype: object
0.9
Barcelona - local
3509    3
3529    3
3559    3
3575    3
3598    3
3622    3
3669    3
3670    3
3689    3
3709    3
Name: FTR, dtype: object
3.0
39
19.4
Getafe - visitante
3504    0
3528    1
3540    3
3569    1
3582    0
3604    3
3617    3
3625    1
3647    3
3660    0
Name: FTR, dtype: object
1.5
Malaga - local
3508    0
3521    3
3548    3
3567    3
3585    3
3603    3
3614    0
3638    1
3652    1
3671    3
Name: FTR, dtype: object
2.0
19
15.2
Santander - visitante
3515    1
3530    0
3555    0
3578    0
3596    1
3621    3
3655    1
3673    0
3693    1
3718    1
Name: FTR, dtype: object
0.8
Real Madrid - local
3517    3
3531    1
3552    3
3578    3
3584    3
3608    3
3612    3
3637    3
3656    0
3679    3
Name: FTR, dtype: object
2.5
36
21.7
Valencia - visitante
3519    0
3534    3
3553    3
3575    0
3594    1
3602    1
3613    1
3630    1
3658    0
3678    3
Name: FTR, dtype: object
1.3
Mallorca - local
3518    0
3532    3
3557    1
3572    3
3595    3
3628    0
3647    0
3663    1
3673    3
3697    1
Name: FTR, dtype: object
1.5
13
11.7
Granada - visitante
3506    3
3529    0
3545    0
3564    0
3581    0
3605    3
3618    0
3637    0
3653    0
3677    3
Name: FTR, dtype: object
0.9
Levante - local
3513    0
3533    3
3550    3
3573    0
3596    1
3604    0
3615    1
3639    1
3657    3
3674    3
Name: FTR, dtype: object
1.5
14
12.0
Ath Madrid - visitante
3511    0
3532    0
3556    1
3571    1
3587    1
3600    3
3616    3
3638    1
3654    0
3679    0
Name: FTR, dtype: object
1.0
Ath Bilbao - local
3516    1
3534    0
3554    3
3576    3
3599    1
3624    3
3648    3
3655    1
3677    0
3696    1
Name: FTR, dtype: object
1.6
17
13.6
Sevilla - visitante
3510    3
3520    3
3546    0
3562    3
3580    0
3603    0
3619    1
3631    0
3657    0
3672    3
Name: FTR, dtype: object
1.3
Zaragoza - local
3511    3
3535    1
3551    3
3570    0
3591    0
3625    1
3649    0
3672    0
3690    1
3712    0
Name: FTR, dtype: object
0.9
8
12.0
Barcelona - visitante
3518    3
3537    3
3542    3
3565    3
3588    0
3606    1
3614    3
3633    1
3656    3
3680    0
Name: FTR, dtype: object
2.0
Vallecano - local
3512    0
3536    3
3555    3
3561    0
3582    3
3607    0
3611    0
3631    3
3651    0
3678    0
Name: FTR, dtype: object
1.2
15
14.7
Osasuna - visitante
3513    3
3535    1
3557    1
3577    0
3592    1
3635    1
3652    1
3675    3
3692    0
3717    1
Name: FTR, dtype: object
1.2
Getafe - local
3519    3
3539    3
3558    0
3579    1
3597    0
3632    1
3653    3
3680    3
3694    3
3717    1
Name: FTR, dtype: object
1.8
13
13.0
Sp Gijon - visitante
3516    1
3538    0
3559    0
3566    1
3583    0
3601    0
3610    0
3634    0
3651    3
3674    0
Name: FTR, dtype: object
0.5
Espanol - local
3514    0
3530    3
3544    3
3568    0
3586    0
3609    3
3618    3
3633    1
3654    3
3675    0
Name: FTR, dtype: object
1.6
20
13.2
Sociedad - visitante
3517    0
3539    0
3554    0
3574    0
3598    0
3626    3
3641    1
3650    1
3676    3
3691    0
Name: FTR, dtype: object
0.8
Betis - local
3515    1
3522    1
3549    0
3569    1
3589    3
3605    0
3619    1
3634    3
3658    3
3676    0
Name: FTR, dtype: object
1.3
15
16.8
Villarreal - visitante
3512    3
3533    0
3551    0
3572    0
3593    3
3623    0
3642    0
3668    0
3671    0
3695    1
Name: FTR, dtype: object
0.7
Sevilla - local
3537    0
3556    1
3577    3
3593    0
3627    1
3646    0
3660    3
3684    0
3700    0
3718    1
Name: FTR, dtype: object
0.9
13
18.3
Mallorca - visitante
3525    3
3541    1
3563    0
3585    0
3609    0
3611    3
3639    1
3649    3
3659    1
3709    0
Name: FTR, dtype: object
1.2
Villarreal - local
3523    1
3540    0
3560    1
3581    3
3606    1
3610    3
3630    1
3650    1
3687    3
3706    3
Name: FTR, dtype: object
1.7
16
13.2
Espanol - visitante
3522    1
3552    0
3579    1
3599    1
3627    1
3645    3
3666    0
3683    1
3704    0
3727    3
Name: FTR, dtype: object
1.1
Valencia - local
3524    0
3541    1
3562    0
3583    3
3626    0
3640    3
3666    3
3688    0
3707    3
3721    1
Name: FTR, dtype: object
1.4
18
16.5
Levante - visitante
3526    3
3548    0
3568    3
3584    0
3624    0
3643    0
3669    0
3686    0
3703    0
3720    3
Name: FTR, dtype: object
0.9
Sociedad - local
3526    0
3547    3
3563    3
3580    3
3601    3
3616    0
3635    1
3661    3
3683    1
3708    0
Name: FTR, dtype: object
1.7
15
12.7
Vallecano - visitante
3521    0
3544    0
3573    3
3591    3
3629    3
3665    0
3670    0
3685    1
3706    0
3724    3
Name: FTR, dtype: object
1.3
Ath Madrid - local
3527    3
3545    3
3565    0
3594    1
3623    3
3644    0
3665    3
3686    3
3705    3
3725    1
Name: FTR, dtype: object
2.0
18
19.0
Getafe - visitante
3528    1
3540    3
3569    1
3582    0
3604    3
3617    3
3625    1
3647    3
3660    0
3682    0
Name: FTR, dtype: object
1.5
Sp Gijon - local
3525    0
3546    3
3571    1
3592    1
3620    3
3645    0
3667    0
3682    3
3701    1
3726    3
Name: FTR, dtype: object
1.5
13
13.7
Zaragoza - visitante
3524    3
3547    0
3567    0
3586    3
3608    0
3615    1
3636    0
3648    0
3664    0
3689    0
Name: FTR, dtype: object
0.7
Santander - local
3520    0
3542    0
3566    1
3587    1
3602    1
3617    0
3636    3
3641    1
3668    3
3681    0
Name: FTR, dtype: object
1.0
7
10.8
Granada - visitante
3529    0
3545    0
3564    0
3581    0
3605    3
3618    0
3637    0
3653    0
3677    3
3700    3
Name: FTR, dtype: object
0.9
Osasuna - local
3528    1
3543    3
3564    3
3588    3
3600    0
3613    1
3621    0
3642    3
3662    3
3685    1
Name: FTR, dtype: object
1.8
12
13.2
Real Madrid - visitante
3523    1
3549    3
3561    3
3597    3
3628    3
3646    3
3667    3
3688    3
3708    3
3728    3
Name: FTR, dtype: object
2.8
Malaga - local
3521    3
3548    3
3567    3
3585    3
3603    3
3614    0
3638    1
3652    1
3671    3
3704    3
Name: FTR, dtype: object
2.3
21
15.1
Betis - visitante
3536    0
3550    0
3570    3
3595    0
3622    0
3644    3
3662    0
3687    0
3702    0
3710    0
Name: FTR, dtype: object
0.6
Barcelona - local
3529    3
3559    3
3575    3
3598    3
3622    3
3669    3
3670    3
3689    3
3709    3
3729    1
Name: FTR, dtype: object
2.8
37
19.5
Ath Bilbao - visitante
3527    0
3543    0
3560    1
3589    0
3607    3
3612    0
3632    1
3663    1
3684    3
3701    1
Name: FTR, dtype: object
1.0
Granada - local
3538    3
3553    0
3574    3
3590    3
3629    0
3643    3
3659    1
3664    3
3693    1
3719    0
Name: FTR, dtype: object
1.7
14
13.1
Sevilla - visitante
3520    3
3546    0
3562    3
3580    0
3603    0
3619    1
3631    0
3657    0
3672    3
3697    1
Name: FTR, dtype: object
1.1
Zaragoza - local
3535    1
3551    3
3570    0
3591    0
3625    1
3649    0
3672    0
3690    1
3712    0
3731    3
Name: FTR, dtype: object
0.9
9
11.6
Ath Madrid - visitante
3532    0
3556    1
3571    1
3587    1
3600    3
3616    3
3638    1
3654    0
3679    0
3694    0
Name: FTR, dtype: object
1.0
Vallecano - local
3536    3
3555    3
3561    0
3582    3
3607    0
3611    0
3631    3
3651    0
3678    0
3691    3
Name: FTR, dtype: object
1.5
19
14.1
Villarreal - visitante
3533    0
3551    0
3572    0
3593    3
3623    0
3642    0
3668    0
3671    0
3695    1
3714    0
Name: FTR, dtype: object
0.4
Levante - local
3533    3
3550    3
3573    0
3596    1
3604    0
3615    1
3639    1
3657    3
3674    3
3698    0
Name: FTR, dtype: object
1.5
14
11.3
Osasuna - visitante
3535    1
3557    1
3577    0
3592    1
3635    1
3652    1
3675    3
3692    0
3717    1
3730    0
Name: FTR, dtype: object
0.9
Espanol - local
3530    3
3544    3
3568    0
3586    0
3609    3
3618    3
3633    1
3654    3
3675    0
3695    1
Name: FTR, dtype: object
1.7
19
14.3
Malaga - visitante
3531    1
3558    3
3576    0
3590    0
3620    0
3640    0
3661    0
3681    3
3699    1
3713    0
Name: FTR, dtype: object
0.8
Betis - local
3522    1
3549    0
3569    1
3589    3
3605    0
3619    1
3634    3
3658    3
3676    0
3699    1
Name: FTR, dtype: object
1.3
14
16.0
Santander - visitante
3530    0
3555    0
3578    0
3596    1
3621    3
3655    1
3673    0
3693    1
3718    1
3739    0
Name: FTR, dtype: object
0.7
Ath Bilbao - local
3534    0
3554    3
3576    3
3599    1
3624    3
3648    3
3655    1
3677    0
3696    1
3711    3
Name: FTR, dtype: object
1.8
19
13.8
Sp Gijon - visitante
3538    0
3559    0
3566    1
3583    0
3601    0
3610    0
3634    0
3651    3
3674    0
3690    1
Name: FTR, dtype: object
0.5
Real Madrid - local
3531    1
3552    3
3578    3
3584    3
3608    3
3612    3
3637    3
3656    0
3679    3
3692    3
Name: FTR, dtype: object
2.5
38
21.6
Sociedad - visitante
3539    0
3554    0
3574    0
3598    0
3626    3
3641    1
3650    1
3676    3
3691    0
3716    0
Name: FTR, dtype: object
0.8
Mallorca - local
3532    3
3557    1
3572    3
3595    3
3628    0
3647    0
3663    1
3673    3
3697    1
3715    0
Name: FTR, dtype: object
1.5
14
12.4
Barcelona - visitante
3537    3
3542    3
3565    3
3588    0
3606    1
3614    3
3633    1
3656    3
3680    0
3696    1
Name: FTR, dtype: object
1.8
Getafe - local
3539    3
3558    0
3579    1
3597    0
3632    1
3653    3
3680    3
3694    3
3717    1
3738    1
Name: FTR, dtype: object
1.6
10
12.9
Valencia - visitante
3534    3
3553    3
3575    0
3594    1
3602    1
3613    1
3630    1
3658    0
3678    3
3698    3
Name: FTR, dtype: object
1.6
Santander - local
3542    0
3566    1
3587    1
3602    1
3617    0
3636    3
3641    1
3668    3
3681    0
3702    3
Name: FTR, dtype: object
1.3
8
10.5
Sevilla - visitante
3546    0
3562    3
3580    0
3603    0
3619    1
3631    0
3657    0
3672    3
3697    1
3729    1
Name: FTR, dtype: object
0.9
Malaga - local
3548    3
3567    3
3585    3
3603    3
3614    0
3638    1
3652    1
3671    3
3704    3
3728    0
Name: FTR, dtype: object
2.0
17
15.7
Vallecano - visitante
3544    0
3573    3
3591    3
3629    3
3665    0
3670    0
3685    1
3706    0
3724    3
3747    1
Name: FTR, dtype: object
1.4
Betis - local
3549    0
3569    1
3589    3
3605    0
3619    1
3634    3
3658    3
3676    0
3699    1
3724    0
Name: FTR, dtype: object
1.2
13
16.9
Espanol - visitante
3552    0
3579    1
3599    1
3627    1
3645    3
3666    0
3683    1
3704    0
3727    3
3732    3
Name: FTR, dtype: object
1.3
Villarreal - local
3540    0
3560    1
3581    3
3606    1
3610    3
3630    1
3650    1
3687    3
3706    3
3720    0

Name: FTR, dtype: object
1.6
15
13.7
Real Madrid - visitante
3549    3
3561    3
3597    3
3628    3
3646    3
3667    3
3688    3
3708    3
3728    3
3742    3
Name: FTR, dtype: object
3.0
Valencia - local
3541    1
3562    0
3583    3
3626    0
3640    3
3666    3
3688    0
3707    3
3721    1
3746    3
Name: FTR, dtype: object
1.7
18
16.0
Zaragoza - visitante
3547    0
3567    0
3586    3
3608    0
3615    1
3636    0
3648    0
3664    0
3689    0
3705    0
Name: FTR, dtype: object
0.4
Sp Gijon - local
3546    3
3571    1
3592    1
3620    3
3645    0
3667    0
3682    3
3701    1
3726    3
3740    0
Name: FTR, dtype: object
1.5
11
11.9
Mallorca - visitante
3541    1
3563    0
3585    0
3609    0
3611    3
3639    1
3649    3
3659    1
3709    0
3725    1
Name: FTR, dtype: object
1.0
Sociedad - local
3547    3
3563    3
3580    3
3601    3
3616    0
3635    1
3661    3
3683    1
3708    0
3722    1
Name: FTR, dtype: object
1.8
14
13.0
Levante - visitante
3548    0
3568    3
3584    0
3624    0
3643    0
3669    0
3686    0
3703    0
3720    3
3743    3
Name: FTR, dtype: object
0.9
Ath Madrid - local
3545    3
3565    0
3594    1
3623    3
3644    0
3665    3
3686    3
3705    3
3725    1
3744    1
Name: FTR, dtype: object
1.8
16
18.4
Ath Bilbao - visitante
3543    0
3560    1
3589    0
3607    3
3612    0
3632    1
3663    1
3684    3
3701    1
3721    1
Name: FTR, dtype: object
1.1
Osasuna - local
3543    3
3564    3
3588    3
3600    0
3613    1
3621    0
3642    3
3662    3
3685    1
3703    3
Name: FTR, dtype: object
2.0
14
12.6
Getafe - visitante
3540    3
3569    1
3582    0
3604    3
3617    3
3625    1
3647    3
3660    0
3682    0
3707    0
Name: FTR, dtype: object
1.4
Barcelona - local
3559    3
3575    3
3598    3
3622    3
3669    3
3670    3
3689    3
3709    3
3729    1
3739    3
Name: FTR, dtype: object
2.8
35
19.6
Granada - visitante
3545    0
3564    0
3581    0
3605    3
3618    0
3637    0
3653    0
3677    3
3700    3
3726    0
Name: FTR, dtype: object
0.9
Espanol - local
3544    3
3568    0
3586    0
3609    3
3618    3
3633    1
3654    3
3675    0
3695    1
3710    3
Name: FTR, dtype: object
1.7
17
14.5
Santander - visitante
3555    0
3578    0
3596    1
3621    3
3655    1
3673    0
3693    1
3718    1
3739    0
3752    1
Name: FTR, dtype: object
0.8
Real Madrid - local
3552    3
3578    3
3584    3
3608    3
3612    3
3637    3
3656    0
3679    3
3692    3
3714    3
Name: FTR, dtype: object
2.7
40
21.1
Malaga - visitante
3558    3
3576    0
3590    0
3620    0
3640    0
3661    0
3681    3
3699    1
3713    0
3734    0
Name: FTR, dtype: object
0.7
Mallorca - local
3557    1
3572    3
3595    3
3628    0
3647    0
3663    1
3673    3
3697    1
3715    0
3736    1
Name: FTR, dtype: object
1.3
13
12.6
Ath Madrid - visitante
3556    1
3571    1
3587    1
3600    3
3616    3
3638    1
3654    0
3679    0
3694    0
3711    0
Name: FTR, dtype: object
1.0
Levante - local
3550    3
3573    0
3596    1
3604    0
3615    1
3639    1
3657    3
3674    3
3698    0
3716    3
Name: FTR, dtype: object
1.5
16
11.2
Villarreal - visitante
3551    0
3572    0
3593    3
3623    0
3642    0
3668    0
3671    0
3695    1
3714    0
3738    1
Name: FTR, dtype: object
0.5
Ath Bilbao - local
3554    3
3576    3
3599    1
3624    3
3648    3
3655    1
3677    0
3696    1
3711    3
3730    3
Name: FTR, dtype: object
2.1
22
14.0
Valencia - visitante
3553    3
3575    0
3594    1
3602    1
3613    1
3630    1
3658    0
3678    3
3698    3
3712    3
Name: FTR, dtype: object
1.6
Zaragoza - local
3551    3
3570    0
3591    0
3625    1
3649    0
3672    0
3690    1
3712    0
3731    3
3751    1
Name: FTR, dtype: object
0.9
8
10.7
Osasuna - visitante
3557    1
3577    0
3592    1
3635    1
3652    1
3675    3
3692    0
3717    1
3730    0
3755    1
Name: FTR, dtype: object
0.9
Vallecano - local
3555    3
3561    0
3582    3
3607    0
3611    0
3631    3
3651    0
3678    0
3691    3
3713    3
Name: FTR, dtype: object
1.5
18
14.3
Betis - visitante
3550    0
3570    3
3595    0
3622    0
3644    3
3662    0
3687    0
3702    0
3710    0
3735    0
Name: FTR, dtype: object
0.6
Sevilla - local
3556    1
3577    3
3593    0
3627    1
3646    0
3660    3
3684    0
3700    0
3718    1
3733    3
Name: FTR, dtype: object
1.2
15
19.1
Barcelona - visitante
3542    3
3565    3
3588    0
3606    1
3614    3
3633    1
3656    3
3680    0
3696    1
3719    3
Name: FTR, dtype: object
1.8
Granada - local
3553    0
3574    3
3590    3
3629    0
3643    3
3659    1
3664    3
3693    1
3719    0
3737    1
Name: FTR, dtype: object
1.5
12
13.6
Sp Gijon - visitante
3559    0
3566    1
3583    0
3601    0
3610    0
3634    0
3651    3
3674    0
3690    1
3715    3
Name: FTR, dtype: object
0.8
Getafe - local
3558    0
3579    1
3597    0
3632    1
3653    3
3680    3
3694    3
3717    1
3738    1
3750    3
Name: FTR, dtype: object
1.6
10
13.0
Sociedad - visitante
3554    0
3574    0
3598    0
3626    3
3641    1
3650    1
3676    3
3691    0
3716    0
3731    0
Name: FTR, dtype: object
0.8
Villarreal - local
3560    1
3581    3
3606    1
3610    3
3630    1
3650    1
3687    3
3706    3
3720    0
3745    1
Name: FTR, dtype: object
1.7
16
14.6
Getafe - visitante
3569    1
3582    0
3604    3
3617    3
3625    1
3647    3
3660    0
3682    0
3707    0
3722    1
Name: FTR, dtype: object
1.2
Valencia - local
3562    0
3583    3
3626    0
3640    3
3666    3
3688    0
3707    3
3721    1
3746    3
3763    1
Name: FTR, dtype: object
1.7
18
14.6
Mallorca - visitante
3563    0
3585    0
3609    0
3611    3
3639    1
3649    3
3659    1
3709    0
3725    1
3748    1
Name: FTR, dtype: object
1.0
Santander - local
3566    1
3587    1
3602    1
3617    0
3636    3
3641    1
3668    3
3681    0
3702    3
3727    0
Name: FTR, dtype: object
1.3
8
12.4
Barcelona - visitante
3565    3
3588    0
3606    1
3614    3
3633    1
3656    3
3680    0
3696    1
3719    3
3740    3
Name: FTR, dtype: object
1.8
Osasuna - local
3564    3
3588    3
3600    0
3613    1
3621    0
3642    3
3662    3
3685    1
3703    3
3723    3
Name: FTR, dtype: object
2.0
15
12.5
Ath Bilbao - visitante
3560    1
3589    0
3607    3
3612    0
3632    1
3663    1
3684    3
3701    1
3721    1
3741    3
Name: FTR, dtype: object
1.4
Espanol - local
3568    0
3586    0
3609    3
3618    3
3633    1
3654    3
3675    0
3695    1
3710    3
3742    0
Name: FTR, dtype: object
1.4
12
14.3
Vallecano - visitante
3573    3
3591    3
3629    3
3665    0
3670    0
3685    1
3706    0
3724    3
3747    1
3757    0
Name: FTR, dtype: object
1.4
Ath Madrid - local
3565    0
3594    1
3623    3
3644    0
3665    3
3686    3
3705    3
3725    1
3744    1
3766    3
Name: FTR, dtype: object
1.8
18
18.9
Granada - visitante
3564    0
3581    0
3605    3
3618    0
3637    0
3653    0
3677    3
3700    3
3726    0
3746    0
Name: FTR, dtype: object
0.9
Sp Gijon - local
3571    1
3592    1
3620    3
3645    0
3667    0
3682    3
3701    1
3726    3
3740    0
3752    1
Name: FTR, dtype: object
1.3
10
12.0
Sevilla - visitante
3562    3
3580    0
3603    0
3619    1
3631    0
3657    0
3672    3
3697    1
3729    1
3744    1
Name: FTR, dtype: object
1.0
Sociedad - local
3563    3
3580    3
3601    3
3616    0
3635    1
3661    3
3683    1
3708    0
3722    1
3741    0
Name: FTR, dtype: object
1.5
12
13.2
Zaragoza - visitante
3567    0
3586    3
3608    0
3615    1
3636    0
3648    0
3664    0
3689    0
3705    0
3723    0
Name: FTR, dtype: object
0.4
Malaga - local
3567    3
3585    3
3603    3
3614    0
3638    1
3652    1
3671    3
3704    3
3728    0
3749    3
Name: FTR, dtype: object
2.0
19
15.2
Levante - visitante
3568    3
3584    0
3624    0
3643    0
3669    0
3686    0
3703    0
3720    3
3743    3
3762    3
Name: FTR, dtype: object
1.2
Betis - local
3569    1
3589    3
3605    0
3619    1
3634    3
3658    3
3676    0
3699    1
3724    0
3743    0
Name: FTR, dtype: object
1.2
11
17.5
Real Madrid - visitante
3561    3
3597    3
3628    3
3646    3
3667    3
3688    3
3708    3
3728    3
3742    3
3764    1
Name: FTR, dtype: object
2.8
Levante - local
3573    0
3596    1
3604    0
3615    1
3639    1
3657    3
3674    3
3698    0
3716    3
3734    3
Name: FTR, dtype: object
1.5
16
11.9
Betis - visitante
3570    3
3595    0
3622    0
3644    3
3662    0
3687    0
3702    0
3710    0
3735    0
3750    0
Name: FTR, dtype: object
0.6
Zaragoza - local
3570    0
3591    0
3625    1
3649    0
3672    0
3690    1
3712    0
3731    3
3751    1
3770    3
Name: FTR, dtype: object
0.9
8
10.7
Villarreal - visitante
3572    0
3593    3
3623    0
3642    0
3668    0
3671    0
3695    1
3714    0
3738    1
3759    1
Name: FTR, dtype: object
0.6
Real Madrid - local
3578    3
3584    3
3608    3
3612    3
3637    3
3656    0
3679    3
3692    3
3714    3
3735    3
Name: FTR, dtype: object
2.7
39
21.1
Espanol - visitante
3579    1
3599    1
3627    1
3645    3
3666    0
3683    1
3704    0
3727    3
3732    3
3754    0
Name: FTR, dtype: object
1.3
Granada - local
3574    3
3590    3
3629    0
3643    3
3659    1
3664    3
3693    1
3719    0
3737    1
3755    1
Name: FTR, dtype: object
1.6
13
13.8
Valencia - visitante
3575    0
3594    1
3602    1
3613    1
3630    1
3658    0
3678    3
3698    3
3712    3
3736    1
Name: FTR, dtype: object
1.4
Ath Bilbao - local
3576    3
3599    1
3624    3
3648    3
3655    1
3677    0
3696    1
3711    3
3730    3
3759    1
Name: FTR, dtype: object
1.9
21
13.6
Sociedad - visitante
3574    0
3598    0
3626    3
3641    1
3650    1
3676    3
3691    0
3716    0
3731    0
3753    0
Name: FTR, dtype: object
0.8
Vallecano - local
3561    0
3582    3
3607    0
3611    0
3631    3
3651    0
3678    0
3691    3
3713    3
3732    0
Name: FTR, dtype: object
1.2
14
12.7
Santander - visitante
3578    0
3596    1
3621    3
3655    1
3673    0
3693    1
3718    1
3739    0
3752    1
3773    0
Name: FTR, dtype: object
0.8
Sevilla - local
3577    3
3593    0
3627    1
3646    0
3660    3
3684    0
3700    0
3718    1
3733    3
3756    3
Name: FTR, dtype: object
1.4
15
18.3
Ath Madrid - visitante
3571    1
3587    1
3600    3
3616    3
3638    1
3654    0
3679    0
3694    0
3711    0
3737    1
Name: FTR, dtype: object
1.0
Mallorca - local
3572    3
3595    3
3628    0
3647    0
3663    1
3673    3
3697    1
3715    0
3736    1
3753    3
Name: FTR, dtype: object
1.5
14
12.8
Osasuna - visitante
3577    0
3592    1
3635    1
3652    1
3675    3
3692    0
3717    1
3730    0
3755    1
3779    0
Name: FTR, dtype: object
0.8
Getafe - local
3579    1
3597    0
3632    1
3653    3
3680    3
3694    3
3717    1
3738    1
3750    3
3772    0

Name: FTR, dtype: object
1.6
9
12.0
Malaga - visitante
3576    0
3590    0
3620    0
3640    0
3661    0
3681    3
3699    1
3713    0
3734    0
3751    1
Name: FTR, dtype: object
0.5
Barcelona - local
3575    3
3598    3
3622    3
3669    3
3670    3
3689    3
3709    3
3729    1
3739    3
3758    3
Name: FTR, dtype: object
2.8
37
19.9
Sp Gijon - visitante
3566    1
3583    0
3601    0
3610    0
3634    0
3651    3
3674    0
3690    1
3715    3
3733    0
Name: FTR, dtype: object
0.8
Villarreal - local
3581    3
3606    1
3610    3
3630    1
3650    1
3687    3
3706    3
3720    0
3745    1
3767    3
Name: FTR, dtype: object
1.9
16
13.8
Ath Bilbao - visitante
3589    0
3607    3
3612    0
3632    1
3663    1
3684    3
3701    1
3721    1
3741    3
3765    0
Name: FTR, dtype: object
1.3
Vallecano - local
3582    3
3607    0
3611    0
3631    3
3651    0
3678    0
3691    3
3713    3
3732    0
3762    0
Name: FTR, dtype: object
1.2
15
13.4
Real Madrid - visitante
3597    3
3628    3
3646    3
3667    3
3688    3
3708    3
3728    3
3742    3
3764    1
3771    0
Name: FTR, dtype: object
2.5
Valencia - local
3583    3
3626    0
3640    3
3666    3
3688    0
3707    3
3721    1
3746    3
3763    1
3787    3
Name: FTR, dtype: object
2.0
18
14.8
Sevilla - visitante
3580    0
3603    0
3619    1
3631    0
3657    0
3672    3
3697    1
3729    1
3744    1
3769    1
Name: FTR, dtype: object
0.8
Sociedad - local
3580    3
3601    3
3616    0
3635    1
3661    3
3683    1
3708    0
3722    1
3741    0
3768    3
Name: FTR, dtype: object
1.5
12
13.3
Mallorca - visitante
3585    0
3609    0
3611    3
3639    1
3649    3
3659    1
3709    0
3725    1
3748    1
3767    0
Name: FTR, dtype: object
1.0
Osasuna - local
3588    3
3600    0
3613    1
3621    0
3642    3
3662    3
3685    1
3703    3
3723    3
3748    1
Name: FTR, dtype: object
1.8
15
12.0
Granada - visitante
3581    0
3605    3
3618    0
3637    0
3653    0
3677    3
3700    3
3726    0
3746    0
3768    0
Name: FTR, dtype: object
0.9
Ath Madrid - local
3594    1
3623    3
3644    0
3665    3
3686    3
3705    3
3725    1
3744    1
3766    3
3773    3
Name: FTR, dtype: object
2.1
21
19.6
Barcelona - visitante
3588    0
3606    1
3614    3
3633    1
3656    3
3680    0
3696    1
3719    3
3740    3
3763    1
Name: FTR, dtype: object
1.6
Santander - local
3587    1
3602    1
3617    0
3636    3
3641    1
3668    3
3681    0
3702    3
3727    0
3747    1
Name: FTR, dtype: object
1.3
8
11.2
Sp Gijon - visitante
3583    0
3601    0
3610    0
3634    0
3651    3
3674    0
3690    1
3715    3
3733    0
3766    0
Name: FTR, dtype: object
0.7
Malaga - local
3585    3
3603    3
3614    0
3638    1
3652    1
3671    3
3704    3
3728    0
3749    3
3765    3
Name: FTR, dtype: object
2.0
15
14.7
Zaragoza - visitante
3586    3
3608    0
3615    1
3636    0
3648    0
3664    0
3689    0
3705    0
3723    0
3745    1
Name: FTR, dtype: object
0.5
Espanol - local
3586    0
3609    3
3618    3
3633    1
3654    3
3675    0
3695    1
3710    3
3742    0
3760    3
Name: FTR, dtype: object
1.7
12
14.9
Levante - visitante
3584    0
3624    0
3643    0
3669    0
3686    0
3703    0
3720    3
3743    3
3762    3
3782    1
Name: FTR, dtype: object
1.0
Betis - local
3589    3
3605    0
3619    1
3634    3
3658    3
3676    0
3699    1
3724    0
3743    0
3761    3
Name: FTR, dtype: object
1.4
14
17.1
Getafe - visitante
3582    0
3604    3
3617    3
3625    1
3647    3
3660    0
3682    0
3707    0
3722    1
3749    0
Name: FTR, dtype: object
1.1
Zaragoza - local
3591    0
3625    1
3649    0
3672    0
3690    1
3712    0
3731    3
3751    1
3770    3
3791    0
Name: FTR, dtype: object
0.9
8
10.2
Betis - visitante
3595    0
3622    0
3644    3
3662    0
3687    0
3702    0
3710    0
3735    0
3750    0
3774    3
Name: FTR, dtype: object
0.6
Sp Gijon - local
3592    1
3620    3
3645    0
3667    0
3682    3
3701    1
3726    3
3740    0
3752    1
3775    0
Name: FTR, dtype: object
1.2
9
12.5
Ath Madrid - visitante
3587    1
3600    3
3616    3
3638    1
3654    0
3679    0
3694    0
3711    0
3737    1
3758    0
Name: FTR, dtype: object
0.9
Mallorca - local
3595    3
3628    0
3647    0
3663    1
3673    3
3697    1
3715    0
3736    1
3753    3
3777    0
Name: FTR, dtype: object
1.2
10
12.0
Villarreal - visitante
3593    3
3623    0
3642    0
3668    0
3671    0
3695    1
3714    0
3738    1
3759    1
3778    0
Name: FTR, dtype: object
0.6
Levante - local
3596    1
3604    0
3615    1
3639    1
3657    3
3674    3
3698    0
3716    3
3734    3
3754    3
Name: FTR, dtype: object
1.8
16
11.2
Vallecano - visitante
3591    3
3629    3
3665    0
3670    0
3685    1
3706    0
3724    3
3747    1
3757    0
3772    3
Name: FTR, dtype: object
1.4
Granada - local
3590    3
3629    0
3643    3
3659    1
3664    3
3693    1
3719    0
3737    1
3755    1
3778    3
Name: FTR, dtype: object
1.6
10
12.6
Sociedad - visitante
3598    0
3626    3
3641    1
3650    1
3676    3
3691    0
3716    0
3731    0
3753    0
3776    0
Name: FTR, dtype: object
0.8
Barcelona - local
3598    3
3622    3
3669    3
3670    3
3689    3
3709    3
3729    1
3739    3
3758    3
3779    3
Name: FTR, dtype: object
2.8
40
18.5
Valencia - visitante
3594    1
3602    1
3613    1
3630    1
3658    0
3678    3
3698    3
3712    3
3736    1
3756    0
Name: FTR, dtype: object
1.4
Ath Bilbao - local
3599    1
3624    3
3648    3
3655    1
3677    0
3696    1
3711    3
3730    3
3759    1
3774    0
Name: FTR, dtype: object
1.6
20
14.1
Malaga - visitante
3590    0
3620    0
3640    0
3661    0
3681    3
3699    1
3713    0
3734    0
3751    1
3777    3
Name: FTR, dtype: object
0.8
Sevilla - local
3593    0
3627    1
3646    0
3660    3
3684    0
3700    0
3718    1
3733    3
3756    3
3776    3
Name: FTR, dtype: object
1.4
14
18.1
Osasuna - visitante
3592    1
3635    1
3652    1
3675    3
3692    0
3717    1
3730    0
3755    1
3779    0
3795    1
Name: FTR, dtype: object
0.9
Real Madrid - local
3584    3
3608    3
3612    3
3637    3
3656    0
3679    3
3692    3
3714    3
3735    3
3757    3
Name: FTR, dtype: object
2.7
41
20.6
Santander - visitante
3596    1
3621    3
3655    1
3673    0
3693    1
3718    1
3739    0
3752    1
3773    0
3797    0
Name: FTR, dtype: object
0.8
Getafe - local
3597    0
3632    1
3653    3
3680    3
3694    3
3717    1
3738    1
3750    3
3772    0
3794    1
Name: FTR, dtype: object
1.6
9
10.9
Espanol - visitante
3599    1
3627    1
3645    3
3666    0
3683    1
3704    0
3727    3
3732    3
3754    0
3770    0
Name: FTR, dtype: object
1.2
Sociedad - local
3601    3
3616    0
3635    1
3661    3
3683    1
3708    0
3722    1
3741    0
3768    3
3788    1
Name: FTR, dtype: object
1.3
12
13.1
Sevilla - visitante
3603    0
3619    1
3631    0
3657    0
3672    3
3697    1
3729    1
3744    1
3769    1
3786    1
Name: FTR, dtype: object
0.9
Villarreal - local
3606    1
3610    3
3630    1
3650    1
3687    3
3706    3
3720    0
3745    1
3767    3
3786    1
Name: FTR, dtype: object
1.7
15
13.7
Granada - visitante
3605    3
3618    0
3637    0
3653    0
3677    3
3700    3
3726    0
3746    0
3768    0
3780    0
Name: FTR, dtype: object
0.9
Vallecano - local
3607    0
3611    0
3631    3
3651    0
3678    0
3691    3
3713    3
3732    0
3762    0
3781    1
Name: FTR, dtype: object
1.0
13
14.1
Getafe - visitante
3604    3
3617    3
3625    1
3647    3
3660    0
3682    0
3707    0
3722    1
3749    0
3760    0
Name: FTR, dtype: object
1.1
Valencia - local
3626    0
3640    3
3666    3
3688    0
3707    3
3721    1
3746    3
3763    1
3787    3
3797    3
Name: FTR, dtype: object
2.0
18
15.2
Sp Gijon - visitante
3601    0
3610    0
3634    0
3651    3
3674    0
3690    1
3715    3
3733    0
3766    0
3783    0
Name: FTR, dtype: object
0.7
Real Madrid - local
3608    3
3612    3
3637    3
3656    0
3679    3
3692    3
3714    3
3735    3
3757    3
3789    3
Name: FTR, dtype: object
2.7
41
20.6
Levante - visitante
3624    0
3643    0
3669    0
3686    0
3703    0
3720    3
3743    3
3762    3
3782    1
3794    1
Name: FTR, dtype: object
1.1
Malaga - local
3603    3
3614    0
3638    1
3652    1
3671    3
3704    3
3728    0
3749    3
3765    3
3780    3
Name: FTR, dtype: object
2.0
16
15.0
Mallorca - visitante
3609    0
3611    3
3639    1
3649    3
3659    1
3709    0
3725    1
3748    1
3767    0
3785    0
Name: FTR, dtype: object
1.0
Espanol - local
3609    3
3618    3
3633    1
3654    3
3675    0
3695    1
3710    3
3742    0
3760    3
3784    3
Name: FTR, dtype: object
2.0
14
14.5
Zaragoza - visitante
3608    0
3615    1
3636    0
3648    0
3664    0
3689    0
3705    0
3723    0
3745    1
3761    0
Name: FTR, dtype: object
0.2
Santander - local
3602    1
3617    0
3636    3
3641    1
3668    3
3681    0
3702    3
3727    0
3747    1
3764    1
Name: FTR, dtype: object
1.3
8
11.1
Ath Madrid - visitante
3600    3
3616    3
3638    1
3654    0
3679    0
3694    0
3711    0
3737    1
3758    0
3787    0
Name: FTR, dtype: object
0.8
Osasuna - local
3600    0
3613    1
3621    0
3642    3
3662    3
3685    1
3703    3
3723    3
3748    1
3769    1
Name: FTR, dtype: object
1.6
12
12.8
Barcelona - visitante
3606    1
3614    3
3633    1
3656    3
3680    0
3696    1
3719    3
3740    3
3763    1
3788    1
Name: FTR, dtype: object
1.7
Betis - local
3605    0
3619    1
3634    3
3658    3
3676    0
3699    1
3724    0
3743    0
3761    3
3785    3
Name: FTR, dtype: object
1.4
13
17.0
Ath Bilbao - visitante
3607    3
3612    0
3632    1
3663    1
3684    3
3701    1
3721    1
3741    3
3765    0
3784    0
Name: FTR, dtype: object
1.3
Granada - local
3629    0
3643    3
3659    1
3664    3
3693    1
3719    0
3737    1
3755    1
3778    3
3799    0
Name: FTR, dtype: object
1.3
8
12.1
Malaga - visitante
3620    0
3640    0
3661    0
3681    3
3699    1
3713    0
3734    0
3751    1
3777    3
3792    0
Name: FTR, dtype: object
0.8
Zaragoza - local
3625    1
3649    0
3672    0
3690    1
3712    0
3731    3
3751    1
3770    3
3791    0
Name: FTR, dtype: object
1.0
7
10.222222222222221
Vallecano - visitante
3629    3
3665    0
3670    0
3685    1
3706    0
3724    3
3747    1
3757    0
3772    3
3796    1
Name: FTR, dtype: object
1.2
Sp Gijon - local
3620    3
3645    0
3667    0
3682    3
3701    1
3726    3
3740    0
3752    1
3775    0
3798    0
Name: FTR, dtype: object
1.1
9
13.1
Osasuna - visitante
3635    1
3652    1
3675    3
3692    0
3717    1
3730    0
3755    1
3779    0
3795    1
Name: FTR, dtype: object
0.8888888888888888
Sevilla - local
3627    1
3646    0
3660    3
3684    0
3700    0
3718    1
3733    3
3756    3
3776    3
3792    3

Name: FTR, dtype: object
1.7
15
17.6
Villarreal - visitante
3623    0
3642    0
3668    0
3671    0
3695    1
3714    0
3738    1
3759    1
3778    0
3790    0
Name: FTR, dtype: object
0.3
Ath Madrid - local
3623    3
3644    0
3665    3
3686    3
3705    3
3725    1
3744    1
3766    3
3773    3
3795    1
Name: FTR, dtype: object
2.1
21
21.5
Valencia - visitante
3602    1
3613    1
3630    1
3658    0
3678    3
3698    3
3712    3
3736    1
3756    0
3775    3
Name: FTR, dtype: object
1.6
Mallorca - local
3628    0
3647    0
3663    1
3673    3
3697    1
3715    0
3736    1
3753    3
3777    0
3793    3
Name: FTR, dtype: object
1.2
10
12.0
Betis - visitante
3622    0
3644    3
3662    0
3687    0
3702    0
3710    0
3735    0
3750    0
3774    3
3799    3
Name: FTR, dtype: object
0.9
Levante - local
3604    0
3615    1
3639    1
3657    3
3674    3
3698    0
3716    3
3734    3
3754    3
3771    3
Name: FTR, dtype: object
2.0
16
10.9
Santander - visitante
3621    3
3655    1
3673    0
3693    1
3718    1
3739    0
3752    1
3773    0
3797    0
Name: FTR, dtype: object
0.7777777777777778
Getafe - local
3632    1
3653    3
3680    3
3694    3
3717    1
3738    1
3750    3
3772    0
3794    1
Name: FTR, dtype: object
1.7777777777777777
9
11.555555555555555
Real Madrid - visitante
3628    3
3646    3
3667    3
3688    3
3708    3
3728    3
3742    3
3764    1
3771    0
3791    3
Name: FTR, dtype: object
2.5
Barcelona - local
3622    3
3669    3
3670    3
3689    3
3709    3
3729    1
3739    3
3758    3
3779    3
3790    3
Name: FTR, dtype: object
2.8
43
18.5
Sociedad - visitante
3626    3
3641    1
3650    1
3676    3
3691    0
3716    0
3731    0
3753    0
3776    0
3798    3
Name: FTR, dtype: object
1.1
Ath Bilbao - local
3624    3
3648    3
3655    1
3677    0
3696    1
3711    3
3730    3
3759    1
3774    0
3796    1
Name: FTR, dtype: object
1.6
18
13.1
Espanol - visitante
3627    1
3645    3
3666    0
3683    1
3704    0
3727    3
3732    3
3754    0
3770    0
3793    0
Name: FTR, dtype: object
1.1
Osasuna - local
3613    1
3621    0
3642    3
3662    3
3685    1
3703    3
3723    3
3748    1
3769    1
3783    3
Name: FTR, dtype: object
1.9
14
13.2
Ath Madrid - visitante
3616    3
3638    1
3654    0
3679    0
3694    0
3711    0
3737    1
3758    0
3787    0
Name: FTR, dtype: object
0.5555555555555556
Sociedad - local
3616    0
3635    1
3661    3
3683    1
3708    0
3722    1
3741    0
3768    3
3788    1
Name: FTR, dtype: object
1.1111111111111112
7
13.0
Sp Gijon - visitante
3610    0
3634    0
3651    3
3674    0
3690    1
3715    3
3733    0
3766    0
3783    0
Name: FTR, dtype: object
0.7777777777777778
Santander - local
3617    0
3636    3
3641    1
3668    3
3681    0
3702    3
3727    0
3747    1
3764    1
3782    1
Name: FTR, dtype: object
1.3
6
10.8
Valencia - visitante
3613    1
3630    1
3658    0
3678    3
3698    3
3712    3
3736    1
3756    0
3775    3
Name: FTR, dtype: object
1.6666666666666667
Malaga - local
3614    0
3638    1
3652    1
3671    3
3704    3
3728    0
3749    3
3765    3
3780    3
Name: FTR, dtype: object
1.8888888888888888
14
15.666666666666666
Sevilla - visitante
3619    1
3631    0
3657    0
3672    3
3697    1
3729    1
3744    1
3769    1
3786    1
Name: FTR, dtype: object
1.0
Levante - local
3615    1
3639    1
3657    3
3674    3
3698    0
3716    3
3734    3
3754    3
3771    3
Name: FTR, dtype: object
2.2222222222222223
15
10.11111111111111
Getafe - visitante
3617    3
3625    1
3647    3
3660    0
3682    0
3707    0
3722    1
3749    0
3760    0
3789    0
Name: FTR, dtype: object
0.8
Betis - local
3619    1
3634    3
3658    3
3676    0
3699    1
3724    0
3743    0
3761    3
3785    3
Name: FTR, dtype: object
1.5555555555555556
12
17.11111111111111
Granada - visitante
3618    0
3637    0
3653    0
3677    3
3700    3
3726    0
3746    0
3768    0
3780    0
Name: FTR, dtype: object
0.6666666666666666
Villarreal - local
3610    3
3630    1
3650    1
3687    3
3706    3
3720    0
3745    1
3767    3
3786    1
Name: FTR, dtype: object
1.7777777777777777
15
14.666666666666666
Barcelona - visitante
3614    3
3633    1
3656    3
3680    0
3696    1
3719    3
3740    3
3763    1
3788    1
Name: FTR, dtype: object
1.7777777777777777
Vallecano - local
3611    0
3631    3
3651    0
3678    0
3691    3
3713    3
3732    0
3762    0
3781    1
Name: FTR, dtype: object
1.1111111111111112
11
13.555555555555555
Ath Bilbao - visitante
3612    0
3632    1
3663    1
3684    3
3701    1
3721    1
3741    3
3765    0
3784    0
Name: FTR, dtype: object
1.1111111111111112
Real Madrid - local
3612    3
3637    3
3656    0
3679    3
3692    3
3714    3
3735    3
3757    3
3789    3
Name: FTR, dtype: object
2.6666666666666665
38
20.88888888888889
Zaragoza - visitante
3615    1
3636    0
3648    0
3664    0
3689    0
3705    0
3723    0
3745    1
3761    0
3781    1
Name: FTR, dtype: object
0.3
Espanol - local
3618    3
3633    1
3654    3
3675    0
3695    1
3710    3
3742    0
3760    3
3784    3
Name: FTR, dtype: object
1.8888888888888888
13
14.777777777777779
Mallorca - visitante
3611    3
3639    1
3649    3
3659    1
3709    0
3725    1
3748    1
3767    0
3785    0
Name: FTR, dtype: object
1.1111111111111112
Villarreal - local
3630    1
3650    1
3687    3
3706    3
3720    0
3745    1
3767    3
3786    1
Name: FTR, dtype: object
1.625
12
14.75
Sp Gijon - visitante
3634    0
3651    3
3674    0
3690    1
3715    3
3733    0
3766    0
3783    0
Name: FTR, dtype: object
0.875
Vallecano - local
3631    3
3651    0
3678    0
3691    3
3713    3
3732    0
3762    0
3781    1
Name: FTR, dtype: object
1.25
11
13.75
Mallorca - visitante
3639    1
3649    3
3659    1
3709    0
3725    1
3748    1
3767    0
3785    0
Name: FTR, dtype: object
0.875
Real Madrid - local
3637    3
3656    0
3679    3
3692    3
3714    3
3735    3
3757    3
3789    3
Name: FTR, dtype: object
2.625
34
20.625
Ath Bilbao - visitante
3632    1
3663    1
3684    3
3701    1
3721    1
3741    3
3765    0
3784    0
Name: FTR, dtype: object
1.25
Osasuna - local
3621    0
3642    3
3662    3
3685    1
3703    3
3723    3
3748    1
3769    1
3783    3
Name: FTR, dtype: object
2.0
13
13.333333333333334
Valencia - visitante
3630    1
3658    0
3678    3
3698    3
3712    3
3736    1
3756    0
3775    3
Name: FTR, dtype: object
1.75
Malaga - local
3638    1
3652    1
3671    3
3704    3
3728    0
3749    3
3765    3
3780    3
Name: FTR, dtype: object
2.125
13
16.5
Barcelona - visitante
3633    1
3656    3
3680    0
3696    1
3719    3
3740    3
3763    1
3788    1
Name: FTR, dtype: object
1.625
Levante - local
3639    1
3657    3
3674    3
3698    0
3716    3
3734    3
3754    3
3771    3
Name: FTR, dtype: object
2.375
15
10.625
Zaragoza - visitante
3636    0
3648    0
3664    0
3689    0
3705    0
3723    0
3745    1
3761    0
3781    1
Name: FTR, dtype: object
0.2222222222222222
Sociedad - local
3635    1
3661    3
3683    1
3708    0
3722    1
3741    0
3768    3
3788    1
Name: FTR, dtype: object
1.25
7
12.625
Ath Madrid - visitante
3638    1
3654    0
3679    0
3694    0
3711    0
3737    1
3758    0
3787    0
Name: FTR, dtype: object
0.25
Santander - local
3636    3
3641    1
3668    3
3681    0
3702    3
3727    0
3747    1
3764    1
3782    1
Name: FTR, dtype: object
1.4444444444444444
5
10.0
Getafe - visitante
3625    1
3647    3
3660    0
3682    0
3707    0
3722    1
3749    0
3760    0
3789    0
Name: FTR, dtype: object
0.5555555555555556
Espanol - local
3633    1
3654    3
3675    0
3695    1
3710    3
3742    0
3760    3
3784    3
Name: FTR, dtype: object
1.75
10
14.625
Granada - visitante
3637    0
3653    0
3677    3
3700    3
3726    0
3746    0
3768    0
3780    0
Name: FTR, dtype: object
0.75
Betis - local
3634    3
3658    3
3676    0
3699    1
3724    0
3743    0
3761    3
3785    3
Name: FTR, dtype: object
1.625
11
17.25
Sevilla - visitante
3631    0
3657    0
3672    3
3697    1
3729    1
3744    1
3769    1
3786    1
Name: FTR, dtype: object
1.0
Sp Gijon - local
3645    0
3667    0
3682    3
3701    1
3726    3
3740    0
3752    1
3775    0
3798    0
Name: FTR, dtype: object
0.8888888888888888
7
13.333333333333334
Malaga - visitante
3640    0
3661    0
3681    3
3699    1
3713    0
3734    0
3751    1
3777    3
3792    0
Name: FTR, dtype: object
0.8888888888888888
Osasuna - local
3642    3
3662    3
3685    1
3703    3
3723    3
3748    1
3769    1
3783    3
Name: FTR, dtype: object
2.25
13
14.0
Santander - visitante
3655    1
3673    0
3693    1
3718    1
3739    0
3752    1
3773    0
3797    0
Name: FTR, dtype: object
0.5
Barcelona - local
3669    3
3670    3
3689    3
3709    3
3729    1
3739    3
3758    3
3779    3
3790    3
Name: FTR, dtype: object
2.7777777777777777
39
18.77777777777778
Betis - visitante
3644    3
3662    0
3687    0
3702    0
3710    0
3735    0
3750    0
3774    3
3799    3
Name: FTR, dtype: object
1.0
Ath Madrid - local
3644    0
3665    3
3686    3
3705    3
3725    1
3744    1
3766    3
3773    3
3795    1
Name: FTR, dtype: object
2.0
18
21.666666666666668
Villarreal - visitante
3642    0
3668    0
3671    0
3695    1
3714    0
3738    1
3759    1
3778    0
3790    0
Name: FTR, dtype: object
0.3333333333333333
Ath Bilbao - local
3648    3
3655    1
3677    0
3696    1
3711    3
3730    3
3759    1
3774    0
3796    1
Name: FTR, dtype: object
1.4444444444444444
15
12.666666666666666
Levante - visitante
3643    0
3669    0
3686    0
3703    0
3720    3
3743    3
3762    3
3782    1
3794    1
Name: FTR, dtype: object
1.2222222222222223
Zaragoza - local
3649    0
3672    0
3690    1
3712    0
3731    3
3751    1
3770    3
3791    0
Name: FTR, dtype: object
1.0
6
9.625
Getafe - visitante
3647    3
3660    0
3682    0
3707    0
3722    1
3749    0
3760    0
3789    0
Name: FTR, dtype: object
0.5
Valencia - local
3640    3
3666    3
3688    0
3707    3
3721    1
3746    3
3763    1
3787    3
3797    3
Name: FTR, dtype: object
2.2222222222222223
18
15.555555555555555
Sociedad - visitante
3641    1
3650    1
3676    3
3691    0
3716    0
3731    0
3753    0
3776    0
3798    3
Name: FTR, dtype: object
0.8888888888888888
Sevilla - local
3646    0
3660    3
3684    0
3700    0
3718    1
3733    3
3756    3
3776    3
3792    3
Name: FTR, dtype: object
1.7777777777777777
15
17.444444444444443
Espanol - visitante
3645    3
3666    0
3683    1
3704    0
3727    3
3732    3
3754    0
3770    0
3793    0
Name: FTR, dtype: object
1.1111111111111112
Mallorca - local
3647    0
3663    1
3673    3
3697    1
3715    0
3736    1
3753    3
3777    0
3793    3
Name: FTR, dtype: object
1.3333333333333333
9
12.444444444444445
Real Madrid - visitante
3646    3
3667    3
3688    3
3708    3
3728    3
3742    3
3764    1
3771    0
3791    3

Name: FTR, dtype: object
2.4444444444444446
Granada - local
3643    3
3659    1
3664    3
3693    1
3719    0
3737    1
3755    1
3778    3
3799    0
Name: FTR, dtype: object
1.4444444444444444
7
11.777777777777779
Vallecano - visitante
3665    0
3670    0
3685    1
3706    0
3724    3
3747    1
3757    0
3772    3
3796    1
Name: FTR, dtype: object
1.0
Villarreal - local
3650    1
3687    3
3706    3
3720    0
3745    1
3767    3
3786    1
Name: FTR, dtype: object
1.7142857142857142
10
15.0
Valencia - visitante
3658    0
3678    3
3698    3
3712    3
3736    1
3756    0
3775    3
Name: FTR, dtype: object
1.8571428571428572
Vallecano - local
3651    0
3678    0
3691    3
3713    3
3732    0
3762    0
3781    1
Name: FTR, dtype: object
1.0
9
14.142857142857142
Sevilla - visitante
3657    0
3672    3
3697    1
3729    1
3744    1
3769    1
3786    1
Name: FTR, dtype: object
1.1428571428571428
Getafe - local
3653    3
3680    3
3694    3
3717    1
3738    1
3750    3
3772    0
3794    1
Name: FTR, dtype: object
1.875
9
11.0
Ath Bilbao - visitante
3663    1
3684    3
3701    1
3721    1
3741    3
3765    0
3784    0
Name: FTR, dtype: object
1.2857142857142858
Espanol - local
3654    3
3675    0
3695    1
3710    3
3742    0
3760    3
3784    3
Name: FTR, dtype: object
1.8571428571428572
9
14.714285714285714
Barcelona - visitante
3656    3
3680    0
3696    1
3719    3
3740    3
3763    1
3788    1
Name: FTR, dtype: object
1.7142857142857142
Betis - local
3658    3
3676    0
3699    1
3724    0
3743    0
3761    3
3785    3
Name: FTR, dtype: object
1.4285714285714286
9
17.0
Sp Gijon - visitante
3651    3
3674    0
3690    1
3715    3
3733    0
3766    0
3783    0
Name: FTR, dtype: object
1.0
Sociedad - local
3661    3
3683    1
3708    0
3722    1
3741    0
3768    3
3788    1
Name: FTR, dtype: object
1.2857142857142858
7
11.571428571428571
Osasuna - visitante
3652    1
3675    3
3692    0
3717    1
3730    0
3755    1
3779    0
3795    1
Name: FTR, dtype: object
0.875
Santander - local
3641    1
3668    3
3681    0
3702    3
3727    0
3747    1
3764    1
3782    1
Name: FTR, dtype: object
1.25
4
9.5
Zaragoza - visitante
3648    0
3664    0
3689    0
3705    0
3723    0
3745    1
3761    0
3781    1
Name: FTR, dtype: object
0.25
Real Madrid - local
3656    0
3679    3
3692    3
3714    3
3735    3
3757    3
3789    3
Name: FTR, dtype: object
2.5714285714285716
29
18.571428571428573
Granada - visitante
3653    0
3677    3
3700    3
3726    0
3746    0
3768    0
3780    0
Name: FTR, dtype: object
0.8571428571428571
Malaga - local
3652    1
3671    3
3704    3
3728    0
3749    3
3765    3
3780    3
Name: FTR, dtype: object
2.2857142857142856
13
17.285714285714285
Ath Madrid - visitante
3654    0
3679    0
3694    0
3711    0
3737    1
3758    0
3787    0
Name: FTR, dtype: object
0.14285714285714285
Levante - local
3657    3
3674    3
3698    0
3716    3
3734    3
3754    3
3771    3
Name: FTR, dtype: object
2.5714285714285716
15
11.0
Mallorca - visitante
3649    3
3659    1
3709    0
3725    1
3748    1
3767    0
3785    0
Name: FTR, dtype: object
0.8571428571428571
Valencia - local
3666    3
3688    0
3707    3
3721    1
3746    3
3763    1
3787    3
3797    3
Name: FTR, dtype: object
2.125
16
15.875
Malaga - visitante
3661    0
3681    3
3699    1
3713    0
3734    0
3751    1
3777    3
3792    0
Name: FTR, dtype: object
1.0
Santander - local
3668    3
3681    0
3702    3
3727    0
3747    1
3764    1
3782    1
Name: FTR, dtype: object
1.2857142857142858
4
9.285714285714286
Sociedad - visitante
3650    1
3676    3
3691    0
3716    0
3731    0
3753    0
3776    0
3798    3
Name: FTR, dtype: object
0.875
Osasuna - local
3662    3
3685    1
3703    3
3723    3
3748    1
3769    1
3783    3
Name: FTR, dtype: object
2.142857142857143
11
13.285714285714286
Villarreal - visitante
3668    0
3671    0
3695    1
3714    0
3738    1
3759    1
3778    0
3790    0
Name: FTR, dtype: object
0.375
Granada - local
3659    1
3664    3
3693    1
3719    0
3737    1
3755    1
3778    3
3799    0
Name: FTR, dtype: object
1.25
5
11.125
Levante - visitante
3669    0
3686    0
3703    0
3720    3
3743    3
3762    3
3782    1
3794    1
Name: FTR, dtype: object
1.375
Ath Madrid - local
3665    3
3686    3
3705    3
3725    1
3744    1
3766    3
3773    3
3795    1
Name: FTR, dtype: object
2.25
18
20.5
Betis - visitante
3662    0
3687    0
3702    0
3710    0
3735    0
3750    0
3774    3
3799    3
Name: FTR, dtype: object
0.75
Sp Gijon - local
3667    0
3682    3
3701    1
3726    3
3740    0
3752    1
3775    0
3798    0
Name: FTR, dtype: object
1.0
6
13.5
Espanol - visitante
3666    0
3683    1
3704    0
3727    3
3732    3
3754    0
3770    0
3793    0
Name: FTR, dtype: object
0.875
Sevilla - local
3660    3
3684    0
3700    0
3718    1
3733    3
3756    3
3776    3
3792    3
Name: FTR, dtype: object
2.0
13
17.25
Real Madrid - visitante
3667    3
3688    3
3708    3
3728    3
3742    3
3764    1
3771    0
3791    3
Name: FTR, dtype: object
2.375
Mallorca - local
3663    1
3673    3
3697    1
3715    0
3736    1
3753    3
3777    0
3793    3
Name: FTR, dtype: object
1.5
8
12.5
Getafe - visitante
3660    0
3682    0
3707    0
3722    1
3749    0
3760    0
3789    0
Name: FTR, dtype: object
0.14285714285714285
Ath Bilbao - local
3655    1
3677    0
3696    1
3711    3
3730    3
3759    1
3774    0
3796    1
Name: FTR, dtype: object
1.25
13
12.875
Zaragoza - visitante
3664    0
3689    0
3705    0
3723    0
3745    1
3761    0
3781    1
Name: FTR, dtype: object
0.2857142857142857
Zaragoza - local
3672    0
3690    1
3712    0
3731    3
3751    1
3770    3
3791    0
Name: FTR, dtype: object
1.1428571428571428
6
10.0
Mallorca - visitante
3659    1
3709    0
3725    1
3748    1
3767    0
3785    0
Name: FTR, dtype: object
0.5
Villarreal - local
3687    3
3706    3
3720    0
3745    1
3767    3
3786    1
Name: FTR, dtype: object
1.8333333333333333
9
14.333333333333334
Sociedad - visitante
3676    3
3691    0
3716    0
3731    0
3753    0
3776    0
3798    3
Name: FTR, dtype: object
0.8571428571428571
Vallecano - local
3678    0
3691    3
3713    3
3732    0
3762    0
3781    1
Name: FTR, dtype: object
1.1666666666666667
8
13.333333333333334
Sp Gijon - visitante
3674    0
3690    1
3715    3
3733    0
3766    0
3783    0
Name: FTR, dtype: object
0.6666666666666666
Malaga - local
3671    3
3704    3
3728    0
3749    3
3765    3
3780    3
Name: FTR, dtype: object
2.5
12
17.0
Osasuna - visitante
3675    3
3692    0
3717    1
3730    0
3755    1
3779    0
3795    1
Name: FTR, dtype: object
0.8571428571428571
Getafe - local
3680    3
3694    3
3717    1
3738    1
3750    3
3772    0
3794    1
Name: FTR, dtype: object
1.7142857142857142
8
9.857142857142858
Granada - visitante
3677    3
3700    3
3726    0
3746    0
3768    0
3780    0
Name: FTR, dtype: object
1.0
Espanol - local
3675    0
3695    1
3710    3
3742    0
3760    3
3784    3
Name: FTR, dtype: object
1.6666666666666667
5
14.166666666666666
Ath Madrid - visitante
3679    0
3694    0
3711    0
3737    1
3758    0
3787    0
Name: FTR, dtype: object
0.16666666666666666
Ath Bilbao - local
3677    0
3696    1
3711    3
3730    3
3759    1
3774    0
3796    1
Name: FTR, dtype: object
1.2857142857142858
12
12.428571428571429
Santander - visitante
3673    0
3693    1
3718    1
3739    0
3752    1
3773    0
3797    0
Name: FTR, dtype: object
0.42857142857142855
Real Madrid - local
3679    3
3692    3
3714    3
3735    3
3757    3
3789    3
Name: FTR, dtype: object
3.0
28
18.833333333333332
Barcelona - visitante
3680    0
3696    1
3719    3
3740    3
3763    1
3788    1
Name: FTR, dtype: object
1.5
Levante - local
3674    3
3698    0
3716    3
3734    3
3754    3
3771    3
Name: FTR, dtype: object
2.5
14
11.666666666666666
Sevilla - visitante
3672    3
3697    1
3729    1
3744    1
3769    1
3786    1
Name: FTR, dtype: object
1.3333333333333333
Betis - local
3676    0
3699    1
3724    0
3743    0
3761    3
3785    3
Name: FTR, dtype: object
1.1666666666666667
7
16.833333333333332
Valencia - visitante
3678    3
3698    3
3712    3
3736    1
3756    0
3775    3
Name: FTR, dtype: object
2.1666666666666665
Granada - local
3664    3
3693    1
3719    0
3737    1
3755    1
3778    3
3799    0
Name: FTR, dtype: object
1.2857142857142858
3
10.857142857142858
Mallorca - visitante
3709    0
3725    1
3748    1
3767    0
3785    0
Name: FTR, dtype: object
0.4
Sevilla - local
3684    0
3700    0
3718    1
3733    3
3756    3
3776    3
3792    3
Name: FTR, dtype: object
1.8571428571428572
10
17.571428571428573
Getafe - visitante
3682    0
3707    0
3722    1
3749    0
3760    0
3789    0
Name: FTR, dtype: object
0.16666666666666666
Sociedad - local
3683    1
3708    0
3722    1
3741    0
3768    3
3788    1
Name: FTR, dtype: object
1.0
4
11.333333333333334
Malaga - visitante
3681    3
3699    1
3713    0
3734    0
3751    1
3777    3
3792    0
Name: FTR, dtype: object
1.1428571428571428
Osasuna - local
3685    1
3703    3
3723    3
3748    1
3769    1
3783    3
Name: FTR, dtype: object
2.0
9
14.166666666666666
Betis - visitante
3687    0
3702    0
3710    0
3735    0
3750    0
3774    3
3799    3
Name: FTR, dtype: object
0.8571428571428571
Mallorca - local
3673    3
3697    1
3715    0
3736    1
3753    3
3777    0
3793    3
Name: FTR, dtype: object
1.5714285714285714
7
12.571428571428571
Ath Bilbao - visitante
3684    3
3701    1
3721    1
3741    3
3765    0
3784    0
Name: FTR, dtype: object
1.3333333333333333
Granada - local

3693    1
3719    0
3737    1
3755    1
3778    3
3799    0
Name: FTR, dtype: object
1.0
2
10.833333333333334
Zaragoza - visitante
3689    0
3705    0
3723    0
3745    1
3761    0
3781    1
Name: FTR, dtype: object
0.3333333333333333
Ath Madrid - local
3686    3
3705    3
3725    1
3744    1
3766    3
3773    3
3795    1
Name: FTR, dtype: object
2.142857142857143
15
20.428571428571427
Vallecano - visitante
3670    0
3685    1
3706    0
3724    3
3747    1
3757    0
3772    3
3796    1
Name: FTR, dtype: object
1.125
Valencia - local
3688    0
3707    3
3721    1
3746    3
3763    1
3787    3
3797    3
Name: FTR, dtype: object
2.0
14
17.0
Espanol - visitante
3683    1
3704    0
3727    3
3732    3
3754    0
3770    0
3793    0
Name: FTR, dtype: object
1.0
Sp Gijon - local
3682    3
3701    1
3726    3
3740    0
3752    1
3775    0
3798    0
Name: FTR, dtype: object
1.1428571428571428
6
14.0
Real Madrid - visitante
3688    3
3708    3
3728    3
3742    3
3764    1
3771    0
3791    3
Name: FTR, dtype: object
2.2857142857142856
Santander - local
3681    0
3702    3
3727    0
3747    1
3764    1
3782    1
Name: FTR, dtype: object
1.0
3
9.5
Villarreal - visitante
3671    0
3695    1
3714    0
3738    1
3759    1
3778    0
3790    0
Name: FTR, dtype: object
0.42857142857142855
Barcelona - local
3670    3
3689    3
3709    3
3729    1
3739    3
3758    3
3779    3
3790    3
Name: FTR, dtype: object
2.75
34
18.875
Levante - visitante
3686    0
3703    0
3720    3
3743    3
3762    3
3782    1
3794    1
Name: FTR, dtype: object
1.5714285714285714
Barcelona - local
3689    3
3709    3
3729    1
3739    3
3758    3
3779    3
3790    3
Name: FTR, dtype: object
2.7142857142857144
30
19.857142857142858
Vallecano - visitante
3685    1
3706    0
3724    3
3747    1
3757    0
3772    3
3796    1
Name: FTR, dtype: object
1.2857142857142858
Malaga - local
3704    3
3728    0
3749    3
3765    3
3780    3
Name: FTR, dtype: object
2.4
10
18.4
Villarreal - visitante
3695    1
3714    0
3738    1
3759    1
3778    0
3790    0
Name: FTR, dtype: object
0.5
Zaragoza - local
3690    1
3712    0
3731    3
3751    1
3770    3
3791    0
Name: FTR, dtype: object
1.3333333333333333
6
9.5
Sevilla - visitante
3697    1
3729    1
3744    1
3769    1
3786    1
Name: FTR, dtype: object
1.0
Mallorca - local
3697    1
3715    0
3736    1
3753    3
3777    0
3793    3
Name: FTR, dtype: object
1.3333333333333333
5
12.666666666666666
Santander - visitante
3693    1
3718    1
3739    0
3752    1
3773    0
3797    0
Name: FTR, dtype: object
0.5
Levante - local
3698    0
3716    3
3734    3
3754    3
3771    3
Name: FTR, dtype: object
2.4
10
12.0
Sp Gijon - visitante
3690    1
3715    3
3733    0
3766    0
3783    0
Name: FTR, dtype: object
0.8
Espanol - local
3695    1
3710    3
3742    0
3760    3
3784    3
Name: FTR, dtype: object
2.0
4
15.4
Osasuna - visitante
3692    0
3717    1
3730    0
3755    1
3779    0
3795    1
Name: FTR, dtype: object
0.5
Betis - local
3699    1
3724    0
3743    0
3761    3
3785    3
Name: FTR, dtype: object
1.4
5
16.2
Sociedad - visitante
3691    0
3716    0
3731    0
3753    0
3776    0
3798    3
Name: FTR, dtype: object
0.5
Ath Bilbao - local
3696    1
3711    3
3730    3
3759    1
3774    0
3796    1
Name: FTR, dtype: object
1.5
12
11.5
Granada - visitante
3700    3
3726    0
3746    0
3768    0
3780    0
Name: FTR, dtype: object
0.6
Vallecano - local
3691    3
3713    3
3732    0
3762    0
3781    1
Name: FTR, dtype: object
1.4
7
13.6
Valencia - visitante
3698    3
3712    3
3736    1
3756    0
3775    3
Name: FTR, dtype: object
2.0
Real Madrid - local
3692    3
3714    3
3735    3
3757    3
3789    3
Name: FTR, dtype: object
3.0
24
19.4
Ath Madrid - visitante
3694    0
3711    0
3737    1
3758    0
3787    0
Name: FTR, dtype: object
0.2
Getafe - local
3694    3
3717    1
3738    1
3750    3
3772    0
3794    1
Name: FTR, dtype: object
1.5
7
10.333333333333334
Barcelona - visitante
3696    1
3719    3
3740    3
3763    1
3788    1
Name: FTR, dtype: object
1.8
Santander - local
3702    3
3727    0
3747    1
3764    1
3782    1
Name: FTR, dtype: object
1.2
2
9.2
Malaga - visitante
3699    1
3713    0
3734    0
3751    1
3777    3
3792    0
Name: FTR, dtype: object
0.8333333333333334
Sp Gijon - local
3701    1
3726    3
3740    0
3752    1
3775    0
3798    0
Name: FTR, dtype: object
0.8333333333333334
4
13.166666666666666
Getafe - visitante
3707    0
3722    1
3749    0
3760    0
3789    0
Name: FTR, dtype: object
0.2
Sociedad - local
3708    0
3722    1
3741    0
3768    3
3788    1
Name: FTR, dtype: object
1.0
4
11.2
Espanol - visitante
3704    0
3727    3
3732    3
3754    0
3770    0
3793    0
Name: FTR, dtype: object
1.0
Sevilla - local
3700    0
3718    1
3733    3
3756    3
3776    3
3792    3
Name: FTR, dtype: object
2.1666666666666665
9
19.166666666666668
Ath Bilbao - visitante
3701    1
3721    1
3741    3
3765    0
3784    0
Name: FTR, dtype: object
1.0
Osasuna - local
3703    3
3723    3
3748    1
3769    1
3783    3
Name: FTR, dtype: object
2.2
9
15.0
Vallecano - visitante
3706    0
3724    3
3747    1
3757    0
3772    3
3796    1
Name: FTR, dtype: object
1.3333333333333333
Ath Madrid - local
3705    3
3725    1
3744    1
3766    3
3773    3
3795    1
Name: FTR, dtype: object
2.0
12
19.5
Levante - visitante
3703    0
3720    3
3743    3
3762    3
3782    1
3794    1
Name: FTR, dtype: object
1.8333333333333333
Villarreal - local
3706    3
3720    0
3745    1
3767    3
3786    1
Name: FTR, dtype: object
1.6
8
15.0
Betis - visitante
3702    0
3710    0
3735    0
3750    0
3774    3
3799    3
Name: FTR, dtype: object
1.0
Valencia - local
3707    3
3721    1
3746    3
3763    1
3787    3
3797    3
Name: FTR, dtype: object
2.3333333333333335
12
17.5
Real Madrid - visitante
3708    3
3728    3
3742    3
3764    1
3771    0
3791    3
Name: FTR, dtype: object
2.1666666666666665
Barcelona - local
3709    3
3729    1
3739    3
3758    3
3779    3
3790    3
Name: FTR, dtype: object
2.6666666666666665
26
18.666666666666668
Zaragoza - visitante
3705    0
3723    0
3745    1
3761    0
3781    1
Name: FTR, dtype: object
0.4
Zaragoza - local
3712    0
3731    3
3751    1
3770    3
3791    0
Name: FTR, dtype: object
1.4
4
8.8
Sp Gijon - visitante
3715    3
3733    0
3766    0
3783    0
Name: FTR, dtype: object
0.75
Vallecano - local
3713    3
3732    0
3762    0
3781    1
Name: FTR, dtype: object
1.0
3
13.75
Sociedad - visitante
3716    0
3731    0
3753    0
3776    0
3798    3
Name: FTR, dtype: object
0.6
Real Madrid - local
3714    3
3735    3
3757    3
3789    3
Name: FTR, dtype: object
3.0
17
19.75
Osasuna - visitante
3717    1
3730    0
3755    1
3779    0
3795    1
Name: FTR, dtype: object
0.6
Granada - local
3719    0
3737    1
3755    1
3778    3
3799    0
Name: FTR, dtype: object
1.0
2
9.8
Santander - visitante
3718    1
3739    0
3752    1
3773    0
3797    0
Name: FTR, dtype: object
0.4
Getafe - local
3717    1
3738    1
3750    3
3772    0
3794    1
Name: FTR, dtype: object
1.2
4
9.6
Ath Madrid - visitante
3711    0
3737    1
3758    0
3787    0
Name: FTR, dtype: object
0.25
Espanol - local
3710    3
3742    0
3760    3
3784    3
Name: FTR, dtype: object
2.25
4
14.5
Villarreal - visitante
3714    0
3738    1
3759    1
3778    0
3790    0
Name: FTR, dtype: object
0.4
Ath Bilbao - local
3711    3
3730    3
3759    1
3774    0
3796    1
Name: FTR, dtype: object
1.6
10
13.0
Barcelona - visitante
3719    3
3740    3
3763    1
3788    1
Name: FTR, dtype: object
2.0
Mallorca - local
3715    0
3736    1
3753    3
3777    0
3793    3
Name: FTR, dtype: object
1.4
5
12.2
Sevilla - visitante
3729    1
3744    1
3769    1
3786    1
Name: FTR, dtype: object
1.0
Levante - local
3716    3
3734    3
3754    3
3771    3
Name: FTR, dtype: object
3.0
10
11.75
Valencia - visitante
3712    3
3736    1
3756    0
3775    3
Name: FTR, dtype: object
1.75
Betis - local
3724    0
3743    0
3761    3
3785    3
Name: FTR, dtype: object
1.5
5
17.75
Malaga - visitante
3713    0
3734    0
3751    1
3777    3
3792    0
Name: FTR, dtype: object
0.8
Sevilla - local
3718    1
3733    3
3756    3
3776    3
3792    3
Name: FTR, dtype: object
2.6
8
16.8
Granada - visitante
3726    0
3746    0
3768    0
3780    0
Name: FTR, dtype: object
0.0
Sp Gijon - local
3726    3
3740    0
3752    1
3775    0
3798    0
Name: FTR, dtype: object
0.8
3
13.6
Ath Bilbao - visitante
3721    1
3741    3
3765    0
3784    0
Name: FTR, dtype: object
1.0
Santander - local
3727    0
3747    1
3764    1
3782    1
Name: FTR, dtype: object
0.75
1
10.0
Betis - visitante
3710    0
3735    0
3750    0
3774    3
3799    3
Name: FTR, dtype: object
1.2
Osasuna - local
3723    3
3748    1
3769    1
3783    3
Name: FTR, dtype: object
2.0
7
15.5
Levante - visitante
3720    3
3743    3
3762    3
3782    1
3794    1
Name: FTR, dtype: object
2.2
Malaga - local
3728    0
3749    3
3765    3
3780    3
Name: FTR, dtype: object
2.25
8
18.25
Espanol - visitante
3727    3
3732    3
3754    0
3770    0
3793    0
Name: FTR, dtype: object
1.2
Ath Madrid - local
3725    1
3744    1
3766    3
3773    3
3795    1
Name: FTR, dtype: object
1.8
9
19.8
Zaragoza - visitante
3723    0
3745    1
3761    0
3781    1
Name: FTR, dtype: object
0.5
Villarreal - local
3720    0
3745    1
3767    3
3786    1
Name: FTR, dtype: object
1.25
6
16.0
Vallecano - visitante
3724    3
3747    1
3757    0
3772    3
3796    1
Name: FTR, dtype: object
1.6
Valencia - local
3721    1
3746    3
3763    1
3787    3
3797    3
Name: FTR, dtype: object
2.2
9
18.4
Getafe - visitante
3722    1
3749    0
3760    0
3789    0
Name: FTR, dtype: object
0.25
Sociedad - local
3722    1
3741    0
3768    3
3788    1
Name: FTR, dtype: object
1.25
4
12.75
Real Madrid - visitante
3728    3
3742    3
3764    1
3771    0
3791    3
Name: FTR, dtype: object
2.0
Barcelona - local
3729    1
3739    3
3758    3
3779    3
3790    3
Name: FTR, dtype: object
2.6
21
18.8
Mallorca - visitante
3725    1
3748    1
3767    0
3785    0
Name: FTR, dtype: object
0.5
Espanol - local
3742    0
3760    3
3784    3
Name: FTR, dtype: object
2.0
3
13.666666666666666
Betis - visitante
3735    0
3750    0
3774    3
3799    3
Name: FTR, dtype: object
1.5
Ath Bilbao - local
3730    3
3759    1
3774    0
3796    1
Name: FTR, dtype: object
1.25
7
12.75
Ath Madrid - visitante
3737    1
3758    0
3787    0
Name: FTR, dtype: object
0.3333333333333333
Zaragoza - local
3731    3
3751    1
3770    3
3791    0
Name: FTR, dtype: object
1.75
4
9.0
Valencia - visitante
3736    1
3756    0
3775    3
Name: FTR, dtype: object
1.3333333333333333
Vallecano - local
3732    0
3762    0
3781    1
Name: FTR, dtype: object
0.3333333333333333
1
13.333333333333334
Malaga - visitante
3734    0
3751    1
3777    3
3792    0
Name: FTR, dtype: object
1.0
Real Madrid - local
3735    3
3757    3
3789    3
Name: FTR, dtype: object
3.0
14
22.0
Villarreal - visitante
3738    1
3759    1
3778    0
3790    0
Name: FTR, dtype: object
0.5
Mallorca - local
3736    1
3753    3
3777    0
3793    3
Name: FTR, dtype: object
1.75
4
11.0
Sp Gijon - visitante
3733    0
3766    0
3783    0
Name: FTR, dtype: object
0.0
Levante - local
3734    3
3754    3
3771    3
Name: FTR, dtype: object
3.0
7
12.333333333333334
Sociedad - visitante
3731    0
3753    0
3776    0
3798    3
Name: FTR, dtype: object
0.75
Getafe - local
3738    1
3750    3
3772    0
3794    1
Name: FTR, dtype: object
1.25
2
8.75
Osasuna - visitante
3730    0
3755    1
3779    0
3795    1
Name: FTR, dtype: object
0.5

Sevilla - local
3733    3
3756    3
3776    3
3792    3
Name: FTR, dtype: object
3.0
6
15.5
Santander - visitante
3739    0
3752    1
3773    0
3797    0
Name: FTR, dtype: object
0.25
Granada - local
3737    1
3755    1
3778    3
3799    0
Name: FTR, dtype: object
1.25
2
11.75
Barcelona - visitante
3740    3
3763    1
3788    1
Name: FTR, dtype: object
1.6666666666666667
Villarreal - local
3745    1
3767    3
3786    1
Name: FTR, dtype: object
1.6666666666666667
6
16.333333333333332
Levante - visitante
3743    3
3762    3
3782    1
3794    1
Name: FTR, dtype: object
2.0
Valencia - local
3746    3
3763    1
3787    3
3797    3
Name: FTR, dtype: object
2.5
8
17.5
Ath Bilbao - visitante
3741    3
3765    0
3784    0
Name: FTR, dtype: object
1.0
Sociedad - local
3741    0
3768    3
3788    1
Name: FTR, dtype: object
1.3333333333333333
4
13.0
Getafe - visitante
3749    0
3760    0
3789    0
Name: FTR, dtype: object
0.0
Osasuna - local
3748    1
3769    1
3783    3
Name: FTR, dtype: object
1.6666666666666667
4
15.333333333333334
Zaragoza - visitante
3745    1
3761    0
3781    1
Name: FTR, dtype: object
0.6666666666666666
Betis - local
3743    0
3761    3
3785    3
Name: FTR, dtype: object
2.0
5
17.666666666666668
Vallecano - visitante
3747    1
3757    0
3772    3
3796    1
Name: FTR, dtype: object
1.25
Ath Madrid - local
3744    1
3766    3
3773    3
3795    1
Name: FTR, dtype: object
2.0
8
19.75
Mallorca - visitante
3748    1
3767    0
3785    0
Name: FTR, dtype: object
0.3333333333333333
Sp Gijon - local
3740    0
3752    1
3775    0
3798    0
Name: FTR, dtype: object
0.25
1
13.0
Granada - visitante
3746    0
3768    0
3780    0
Name: FTR, dtype: object
0.0
Santander - local
3747    1
3764    1
3782    1
Name: FTR, dtype: object
1.0
1
6.666666666666667
Espanol - visitante
3732    3
3754    0
3770    0
3793    0
Name: FTR, dtype: object
0.75
Malaga - local
3749    3
3765    3
3780    3
Name: FTR, dtype: object
3.0
8
17.333333333333332
Real Madrid - visitante
3742    3
3764    1
3771    0
3791    3
Name: FTR, dtype: object
1.75
Barcelona - local
3739    3
3758    3
3779    3
3790    3
Name: FTR, dtype: object
3.0
21
18.25
Sevilla - visitante
3744    1
3769    1
3786    1
Name: FTR, dtype: object
1.0
Ath Bilbao - local
3759    1
3774    0
3796    1
Name: FTR, dtype: object
0.6666666666666666
4
12.666666666666666
Osasuna - visitante
3755    1
3779    0
3795    1
Name: FTR, dtype: object
0.6666666666666666
Zaragoza - local
3751    1
3770    3
3791    0
Name: FTR, dtype: object
1.3333333333333333
2
9.333333333333334
Sociedad - visitante
3753    0
3776    0
3798    3
Name: FTR, dtype: object
1.0
Vallecano - local
3762    0
3781    1
Name: FTR, dtype: object
0.5
1
17.0
Espanol - visitante
3754    0
3770    0
3793    0
Name: FTR, dtype: object
0.0
Sevilla - local
3756    3
3776    3
3792    3
Name: FTR, dtype: object
3.0
4
14.0
Sp Gijon - visitante
3766    0
3783    0
Name: FTR, dtype: object
0.0
Levante - local
3754    3
3771    3
Name: FTR, dtype: object
3.0
4
11.5
Malaga - visitante
3751    1
3777    3
3792    0
Name: FTR, dtype: object
1.3333333333333333
Real Madrid - local
3757    3
3789    3
Name: FTR, dtype: object
3.0
10
22.0
Betis - visitante
3750    0
3774    3
3799    3
Name: FTR, dtype: object
2.0
Mallorca - local
3753    3
3777    0
3793    3
Name: FTR, dtype: object
2.0
3
11.0
Valencia - visitante
3756    0
3775    3
Name: FTR, dtype: object
1.5
Granada - local
3755    1
3778    3
3799    0
Name: FTR, dtype: object
1.3333333333333333
2
9.666666666666666
Ath Madrid - visitante
3758    0
3787    0
Name: FTR, dtype: object
0.0
Getafe - local
3750    3
3772    0
3794    1
Name: FTR, dtype: object
1.3333333333333333
2
9.0
Villarreal - visitante
3759    1
3778    0
3790    0
Name: FTR, dtype: object
0.3333333333333333
Barcelona - local
3758    3
3779    3
3790    3
Name: FTR, dtype: object
3.0
18
18.0
Santander - visitante
3752    1
3773    0
3797    0
Name: FTR, dtype: object
0.3333333333333333
Sp Gijon - local
3752    1
3775    0
3798    0
Name: FTR, dtype: object
0.3333333333333333
1
16.0
Barcelona - visitante
3763    1
3788    1
Name: FTR, dtype: object
1.0
Sociedad - local
3768    3
3788    1
Name: FTR, dtype: object
2.0
3
12.0
Ath Bilbao - visitante
3765    0
3784    0
Name: FTR, dtype: object
0.0
Espanol - local
3760    3
3784    3
Name: FTR, dtype: object
3.0
3
13.0
Real Madrid - visitante
3764    1
3771    0
3791    3
Name: FTR, dtype: object
1.3333333333333333
Betis - local
3761    3
3785    3
Name: FTR, dtype: object
3.0
5
16.5
Levante - visitante
3762    3
3782    1
3794    1
Name: FTR, dtype: object
1.6666666666666667
Ath Madrid - local
3766    3
3773    3
3795    1
Name: FTR, dtype: object
2.3333333333333335
8
21.333333333333332
Sevilla - visitante
3769    1
3786    1
Name: FTR, dtype: object
1.0
Villarreal - local
3767    3
3786    1
Name: FTR, dtype: object
2.0
4
12.0
Zaragoza - visitante
3761    0
3781    1
Name: FTR, dtype: object
0.5
Valencia - local
3763    1
3787    3
3797    3
Name: FTR, dtype: object
2.3333333333333335
7
15.666666666666666
Granada - visitante
3768    0
3780    0
Name: FTR, dtype: object
0.0
Santander - local
3764    1
3782    1
Name: FTR, dtype: object
1.0
0
6.5
Vallecano - visitante
3757    0
3772    3
3796    1
Name: FTR, dtype: object
1.3333333333333333
Osasuna - local
3769    1
3783    3
Name: FTR, dtype: object
2.0
2
18.0
Mallorca - visitante
3767    0
3785    0
Name: FTR, dtype: object
0.0
Malaga - local
3765    3
3780    3
Name: FTR, dtype: object
3.0
5
16.5
Getafe - visitante
3760    0
3789    0
Name: FTR, dtype: object
0.0
Getafe - local
3772    0
3794    1
Name: FTR, dtype: object
0.5
1
7.5
Betis - visitante
3774    3
3799    3
Name: FTR, dtype: object
3.0
Zaragoza - local
3770    3
3791    0
Name: FTR, dtype: object
1.5
2
10.0
Malaga - visitante
3777    3
3792    0
Name: FTR, dtype: object
1.5
Sp Gijon - local
3775    0
3798    0
Name: FTR, dtype: object
0.0
1
16.0
Santander - visitante
3773    0
3797    0
Name: FTR, dtype: object
0.0
Mallorca - local
3777    0
3793    3
Name: FTR, dtype: object
1.5
1
8.5
Sociedad - visitante
3776    0
3798    3
Name: FTR, dtype: object
1.5
Levante - local
3771    3
Name: FTR, dtype: object
3.0
1
11.0
Espanol - visitante
3770    0
3793    0
Name: FTR, dtype: object
0.0
Granada - local
3778    3
3799    0
Name: FTR, dtype: object
1.5
1
9.5
Osasuna - visitante
3779    0
3795    1
Name: FTR, dtype: object
0.5
Sevilla - local
3776    3
3792    3
Name: FTR, dtype: object
3.0
3
15.0
Valencia - visitante
3775    3
Name: FTR, dtype: object
3.0
Real Madrid - local
3789    3
Name: FTR, dtype: object
3.0
4
26.0
Vallecano - visitante
3772    3
3796    1
Name: FTR, dtype: object
2.0
Barcelona - local
3779    3
3790    3
Name: FTR, dtype: object
3.0
13
18.0
Ath Madrid - visitante
3787    0
Name: FTR, dtype: object
0.0
Ath Bilbao - local
3774    0
3796    1
Name: FTR, dtype: object
0.5
3
14.0
Villarreal - visitante
3778    0
3790    0
Name: FTR, dtype: object
0.0
Espanol - local
3784    3
Name: FTR, dtype: object
3.0
2
10.0
Getafe - visitante
3789    0
Name: FTR, dtype: object
0.0
Betis - local
3785    3
Name: FTR, dtype: object
3.0
1
24.0
Zaragoza - visitante
3781    1
Name: FTR, dtype: object
1.0
Vallecano - local
3781    1
Name: FTR, dtype: object
1.0
0
20.0
Levante - visitante
3782    1
3794    1
Name: FTR, dtype: object
1.0
Valencia - local
3787    3
3797    3
Name: FTR, dtype: object
3.0
5
19.0
Barcelona - visitante
3788    1
Name: FTR, dtype: object
1.0
Santander - local
3782    1
Name: FTR, dtype: object
1.0
0
8.0
Real Madrid - visitante
3771    0
3791    3
Name: FTR, dtype: object
1.5
Malaga - local
3780    3
Name: FTR, dtype: object
3.0
4
20.0
Ath Bilbao - visitante
3784    0
Name: FTR, dtype: object
0.0
Ath Madrid - local
3773    3
3795    1
Name: FTR, dtype: object
2.0
4
22.5
Sp Gijon - visitante
3783    0
Name: FTR, dtype: object
0.0
Villarreal - local
3786    1
Name: FTR, dtype: object
1.0
2
11.0
Mallorca - visitante
3785    0
Name: FTR, dtype: object
0.0
Sociedad - local
3788    1
Name: FTR, dtype: object
1.0
2
10.0
Granada - visitante
3780    0
Name: FTR, dtype: object
0.0
Osasuna - local
3783    3
Name: FTR, dtype: object
3.0
2
21.0
Sevilla - visitante
3786    1
Name: FTR, dtype: object
1.0
Zaragoza - local
3791    0
Name: FTR, dtype: object
0.0
0
8.0
Espanol - visitante
3793    0
Name: FTR, dtype: object
0.0
Levante - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Real Madrid - visitante
3791    3
Name: FTR, dtype: object
3.0

Getafe - local
3794    1
Name: FTR, dtype: object
1.0
1
8.0
Vallecano - visitante
3796    1
Name: FTR, dtype: object
1.0
Ath Madrid - local
3795    1
Name: FTR, dtype: object
1.0
0
28.0
Santander - visitante
3797    0
Name: FTR, dtype: object
0.0
Ath Bilbao - local
3796    1
Name: FTR, dtype: object
1.0
1
10.0
Betis - visitante
3799    3
Name: FTR, dtype: object
3.0
Sp Gijon - local
3798    0
Name: FTR, dtype: object
0.0
1
17.0
Valencia - visitante
Series([], Name: FTR, dtype: object)
0.0
Sevilla - local
3792    3
Name: FTR, dtype: object
3.0
2
15.0
Sociedad - visitante
3798    3
Name: FTR, dtype: object
3.0
Mallorca - local
3793    3
Name: FTR, dtype: object
3.0
1
11.0
Malaga - visitante
3792    0
Name: FTR, dtype: object
0.0
Granada - local
3799    0
Name: FTR, dtype: object
0.0
0
11.0
Villarreal - visitante
3790    0
Name: FTR, dtype: object
0.0
Barcelona - local
3790    3
Name: FTR, dtype: object
3.0
5
18.0
Osasuna - visitante
3795    1
Name: FTR, dtype: object
1.0
Malaga - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Granada - visitante
Series([], Name: FTR, dtype: object)
0.0
Vallecano - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Zaragoza - visitante
Series([], Name: FTR, dtype: object)
0.0
Santander - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Levante - visitante
3794    1
Name: FTR, dtype: object
1.0
Osasuna - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Sp Gijon - visitante
Series([], Name: FTR, dtype: object)
0.0
Espanol - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Ath Bilbao - visitante
Series([], Name: FTR, dtype: object)
0.0
Betis - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Mallorca - visitante
Series([], Name: FTR, dtype: object)
0.0
Villarreal - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Sevilla - visitante
Series([], Name: FTR, dtype: object)
0.0
Valencia - local
3797    3
Name: FTR, dtype: object
3.0
4
26.0
Ath Madrid - visitante
Series([], Name: FTR, dtype: object)
0.0
Sociedad - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Barcelona - visitante
Series([], Name: FTR, dtype: object)
0.0
Real Madrid - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Getafe - visitante
Series([], Name: FTR, dtype: object)
0.0
Barcelona - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Villarreal - visitante
Series([], Name: FTR, dtype: object)
0.0
Zaragoza - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Real Madrid - visitante
Series([], Name: FTR, dtype: object)
0.0
Sevilla - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Malaga - visitante
Series([], Name: FTR, dtype: object)
0.0
Mallorca - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Espanol - visitante
Series([], Name: FTR, dtype: object)
0.0
Getafe - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Levante - visitante
Series([], Name: FTR, dtype: object)
0.0
Ath Madrid - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Osasuna - visitante
Series([], Name: FTR, dtype: object)
0.0
Ath Bilbao - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Vallecano - visitante
Series([], Name: FTR, dtype: object)
0.0
Valencia - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Santander - visitante
Series([], Name: FTR, dtype: object)
0.0
Sp Gijon - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Sociedad - visitante
Series([], Name: FTR, dtype: object)
0.0
Granada - local
Series([], Name: FTR, dtype: object)
0.0
0
0.0
Betis - visitante
Series([], Name: FTR, dtype: object)
0.0

In [61]:
data

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA
0,SP1,23/05/2021,20:00,Sevilla,Alaves,1,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,23/05/2021,17:30,Granada,Getafe,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,22/05/2021,17:00,Valladolid,Ath Madrid,1,2,A,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,22/05/2021,17:00,Real Madrid,Villarreal,2,1,H,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,22/05/2021,17:00,Osasuna,Sociedad,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,SP1,28/08/11,NaN,Ath Madrid,Osasuna,0,0,D,0,0,...,6.0,1.55,3.75,6.00,1.57,3.75,5.50,1.50,3.75,6.00
3796,SP1,28/08/11,NaN,Ath Bilbao,Vallecano,1,1,D,0,0,...,5.5,1.57,3.60,6.00,1.62,3.75,5.00,1.53,3.60,6.00
3797,SP1,27/08/11,NaN,Valencia,Santander,4,3,H,1,2,...,7.5,1.45,4.25,6.50,1.44,4.00,7.00,1.44,4.00,6.50
3798,SP1,27/08/11,NaN,Sp Gijon,Sociedad,1,2,A,0,1,...,3.5,2.00,3.20,3.75,2.05,3.30,3.40,2.10,3.20,3.20
3799,SP1,27/08/11,NaN,Granada,Betis,0,1,A,0,0,...,3.0,2.40,3.30,2.80,2.40,3.30,2.75,2.30,3.30,2.75

In [62]:
rend

[[2.4,
  1.3,
  0.7,
  2.1,
  1.8,
  1.4,
  1.2,
  0.9,
  1.5,
  0.8,
  1.1,
  1.9,
  1.8,
  1.0,
  1.4,
  2.1,
  2.1,
  2.3,
  1.5,
  1.1,
  1.6,
  0.8,
  0.7,
  2.3,
  1.1,
  1.5,
  2.4,
  1.0,
  1.3,
  1.6,
  1.9,
  2.3,
  1.2,
  1.6,
  1.1,
  1.7,
  1.2,
  2.1,
  1.3,
  1.5,
  2.7,
  1.7,
  1.9,
  1.0,
  0.9,
  2.3,
  0.9,
  1.4,
  0.6,
  1.5,
  2.4,
  1.6,
  0.7,
  1.6,
  2.5,
  1.5,
  1.1,
  1.2,
  2.5,
  1.6,
  0.9,
  1.1,
  2.4,
  1.3,
  1.7,
  2.3,
  1.2,
  1.1,
  1.1,
  2.1,
  1.3,
  1.3,
  1.6,
  1.0,
  1.4,
  2.1,
  2.3,
  0.9,
  1.4,
  1.0,
  1.8,
  2.0,
  1.2,
  1.8,
  1.4,
  2.5,
  0.7,
  1.5,
  1.1,
  0.9,
  1.6,
  2.4,
  2.2,
  1.1,
  1.1,
  1.0,
  1.0,
  2.2,
  1.7,
  1.9,
  1.9,
  2.3,
  1.4,
  1.6,
  1.0,
  1.1,
  0.9,
  1.8,
  1.7,
  2.0,
  2.2,
  2.4,
  2.2,
  0.8,
  1.5,
  1.7,
  0.9,
  0.9,
  2.2,
  0.9,
  1.7,
  2.3,
  1.7,
  1.7,
  1.9,
  2.5,
  1.0,
  1.2,
  0.9,
  1.1,
  0.8,
  1.3,
  2.1,
  1.7,
  1.5,
  1.0,
  1.6,
  0.9,
  1.2,
  2.2,
  0.7,
  1.7,
  2.1,
  1.5,
  1.9,
  0.8,
  1.6,
  2.1,
  0.9,
  1.1,
  2.6,
  0.9,
  1.4,
  1.7,
  1.0,
  2.0,
  1.7,
  2.1,
  1.2,
  2.1,
  0.6,
  2.2,
  1.8,
  1.6,
  2.1,
  2.8,
  1.7,
  1.2,
  1.8,
  1.4,
  2.2,
  0.8,
  0.8,
  1.9,
  1.0,
  1.4,
  1.8,
  2.0,
  1.0,
  1.4,
  2.0,
  1.1,
  2.4,
  0.7,
  1.0,
  1.5,
  2.6,
  1.5,
  0.8,
  1.0,
  1.0,
  1.4,
  2.2,
  1.0,
  1.8,
  1.0,
  1.3,
  2.2,
  1.4,
  1.1,
  1.0,
  1.2,
  1.0,
  2.6,
  2.0,
  1.0,
  1.1,
  1.2,
  0.75,
  1.6,
  1.2,
  2.0,
  2.2,
  1.6,
  1.5,
  1.5,
  1.3,
  1.3,
  0.8,
  1.1,
  1.2,
  2.4,
  1.1,
  1.3,
  1.9,
  1.2,
  1.5,
  1.3,
  1.4,
  2.6,
  1.8,
  1.6,
  0.7142857142857143,
  2.0,
  2.0,
  1.3,
  0.8,
  2.4,
  1.3,
  1.8,
  1.5,
  1.6,
  1.3,
  1.5,
  1.2,
  0.8,
  0.8333333333333334,
  1.5,
  1.2,
  2.0,
  1.5,
  1.3,
  2.0,
  2.6,
  1.5,
  2.0,
  2.4,
  1.2,
  2.0,
  1.2,
  1.3,
  1.5,
  2.4,
  1.1,
  1.4,
  1.7,
  1.3,
  1.0,
  0.7,
  2.0,
  1.5,
  1.4,
  0.4,
  2.6,
  2.3,
  1.1,
  1.6,
  1.6,
  1.4,
  0.9,
  1.4,
  2.0,
  2.7,
  1.1,
  1.8,
  1.4,
  1.3,
  1.6,
  0.9,
  1.7,
  0.5,
  1.0,
  2.4,
  2.3,
  2.0,
  1.1,
  1.7,
  1.8,
  1.1,
  1.3,
  1.2,
  1.5,
  2.4,
  2.1,
  2.0,
  1.3,
  1.3,
  2.0,
  1.8,
  1.7,
  1.2,
  1.4,
  0.9,
  1.7,
  1.3,
  2.5,
  1.0,
  1.5,
  1.2,
  1.5,
  0.3333333333333333,
  1.1,
  2.4,
  2.2,
  1.4,
  2.3,
  1.3,
  1.4,
  1.2,
  1.2,
  1.7,
  1.0,
  0.9,
  1.5,
  2.8,
  1.5,
  1.7,
  2.5,
  0.0,
  1.5,
  1.2,
  1.4,
  2.1,
  1.2,
  1.2,
  2.4,
  1.4,
  1.6,
  2.2,
  1.1,
  2.8,
  1.2,
  1.7,
  1.4,
  1.5,
  1.5,
  2.5,
  1.4,
  0.0,
  2.4,
  1.3,
  1.5,
  1.7,
  1.5,
  2.3,
  1.1,
  1.7,
  1.7,
  1.4,
  1.4,
  1.4,
  1.2,
  1.7,
  2.3,
  1.6,
  1.3,
  1.2,
  0.0,
  1.7,
  1.5,
  2.0,
  1.4,
  1.5,
  1.5,
  1.4,
  1.0,
  2.6,
  1.6,
  1.1,
  1.3,
  2.1,
  1.6,
  2.6,
  1.3,
  1.5,
  1.5,
  1.7,
  2.8,
  1.2,
  1.5,
  1.7,
  1.7,
  1.2,
  1.7,
  1.2,
  1.5,
  1.0,
  2.3,
  1.2,
  1.2,
  2.6,
  1.7,
  1.5,
  1.3,
  1.4,
  2.6,
  1.8,
  1.7,
  1.5,
  2.1,
  1.7,
  1.7,
  1.7,
  1.1,
  1.1,
  1.8,
  1.7,
  1.0,
  1.4,
  2.3,
  2.6,
  1.7,
  1.4,
  0.9,
  1.7,
  2.4,
  1.5,
  2.8,
  1.2,
  1.1,
  1.6,
  1.1,
  1.7,
  1.5,
  1.7,
  2.3,
  1.1,
  1.3,
  1.8,
  1.7,
  1.7,
  1.1,
  2.4,
  1.8,
  1.6,
  2.8,
  1.1,
  1.7,
  1.4,
  1.7,
  1.8,
  2.2,
  1.3,
  2.1,
  1.8,
  1.6,
  1.1,
  1.9,
  1.3,
  2.0,
  2.4,
  1.6,
  1.4,
  1.3,
  1.3,
  2.8,
  1.7,
  2.0,
  1.7,
  1.7,
  2.0,
  2.4,
  1.5,
  1.6,
  1.4,
  1.4,
  0.8,
  2.4,
  2.0,
  1.9,
  1.3,
  1.7,
  2.0,
  1.7,
  1.4,
  1.4,
  1.9,
  2.8,
  2.1,
  1.6,
  1.8,
  2.4,
  1.6,
  0.7,
  1.5,
  1.9,
  2.2,
  1.4,
  2.2,
  1.6,
  1.7,
  1.9,
  2.2,
  1.2,
  1.5,
  1.5,
  1.7,
  1.7,
  2.8,
  1.1,
  1.7,
  2.6,
  1.8,
  1.3,
  1.8,
  2.2,
  1.8,
  2.8,
  1.4,
  2.2,
  2.0,
  1.1,
  1.6,
  1.7,
  0.4,
  1.9,
  1.2,
  2.0,
  1.7,
  1.3,
  2.8,
  1.6,
  1.8,
  2.1,
  1.5,
  1.0,
  2.2,
  1.4,
  2.4,
  1.9,
  1.2,
  1.7,
  1.8,
  1.0,
  2.1,
  1.8,
  1.6,
  2.0,
  0.3,
  1.4,
  2.8,
  2.3,
  1.9,
  1.7,
  1.4,
  1.3,
  1.6,
  2.1,
  1.8,
  1.0,
  1.0,
  1.8,
  2.0,
  1.6,
  0.5,
  1.9,
  1.9,
  2.0,
  1.7,
  1.4,
  2.3,
  1.8,
  2.0,
  1.7,
  0.7,
  1.6,
  1.7,
  2.8,
  1.7,
  1.3,
  3.0,
  1.9,
  2.0,
  0.7,
  1.2,
  1.9,
  1.9,
  2.3,
  1.9,
  1.6,
  1.7,
  1.7,
  0.5,
  1.6,
  1.8,
  1.3,
  3.0,
  2.1,
  1.3,
  2.3,
  1.9,
  2.2,
  1.7,
  0.8,
  2.3,
  2.0,
  1.9,
  2.0,
  1.7,
  1.7,
  1.4,
  1.6,
  2.0,
  1.6,
  2.0,
  1.0,
  2.3,
  1.2,
  1.5,
  0.5,
  1.9,
  1.8,
  1.9,
  2.2,
  2.3,
  1.8,
  3.0,
  1.6,
  1.9,
  1.5,
  1.9,
  1.2,
  0.6,
  1.7,
  1.7,
  2.2,
  1.4,
  2.5,
  2.2,
  1.7,
  1.1,
  1.9,
  1.8,
  1.6,
  2.5,
  1.5,
  2.3,
  1.9,
  2.0,
  3.0,
  1.5,
  1.5,
  1.9,
  1.8,
  0.9,
  2.0,
  2.2,
  1.1,
  0.6,
  1.9,
  1.9,
  2.3,
  1.1,
  1.7,
  1.2,
  1.8,
  1.6,
  2.4,
  1.7,
  0.6,
  3.0,
  2.0,
  1.0,
  1.7,
  1.5,
  1.2,
  1.9,
  2.2,
  0.6,
  1.4,
  1.6,
  1.7,
  1.0,
  1.7,
  1.4,
  2.6,
  0.6,
  1.9,
  2.6,
  1.9,
  2.0,
  1.6,
  1.7,
  1.9,
  1.9,
  1.8,
  0.8,
  2.8,
  1.2,
  1.0,
  1.7,
  2.4,
  1.9,
  1.5,
  1.9,
  0.6,
  2.5,
  1.6,
  1.7,
  1.1,
  1.4,
  1.2,
  1.9,
  1.1,
  1.8,
  2.8,
  1.8,
  0.9,
  1.9,
  1.7,
  1.7,
  1.8,
  2.5,
  1.9,
  1.4,
  1.4,
  2.1,
  1.1,
  2.4,
  1.9,
  2.8,
  1.2,
  1.8,
  1.3,
  2.3,
  1.6,
  2.1,
  1.0,
  1.4,
  0.9,
  2.5,
  1.4,
  1.8,
  1.0,
  1.6,
  1.3,
  1.5,
  1.9,
  1.6,
  2.4,
  2.1,
  1.8,
  1.2,
  1.7,
  1.4,
  1.4,
  2.2,
  1.8,
  1.6,
  1.0,
  1.4,
  1.5,
  1.9,
  1.8,
  1.6,
  0.6,
  1.2,
  2.8,
  2.7,
  2.2,
  0.9,
  2.1,
  1.5,
  2.2,
  1.6,
  1.1,
  1.5,
  1.6,
  1.1,
  2.0,
  1.4,
  1.3,
  1.5,
  2.0,
  1.5,
  0.4,
  1.6,
  2.8,
  2.7,
  2.4,
  1.5,
  2.0,
  2.4,
  1.1,
  1.7,
  1.4,
  2.5,
  0.6,
  1.2,
  1.2,
  1.3,
  2.1,
  1.0,
  2.1,
  1.7,
  1.5,
  1.9,
  1.3,
  2.5,
  1.4,
  1.9,
  0.6,
  2.0,
  1.7,
  0.5,
  2.2,
  2.0,
  1.2,
  1.1,
  2.5,
  0.7,
  1.2,
  2.1,
  1.3,
  1.5,
  1.6,
  1.2,
  2.1,
  0.8,
  2.5,
  1.5,
  2.0,
  1.7,
  1.7,
  1.2,
  1.9,
  2.0,
  1.3,
  1.3,
  2.5,
  1.2,
  0.9,
  2.3,
  1.8,
  1.4,
  2.1,
  1.0,
  2.5,
  1.9,
  0.8,
  1.1,
  1.7,
  1.6,
  2.0,
  1.5,
  1.6,
  2.0,
  1.2,
  1.7,
  1.5,
  1.2,
  2.3,
  1.4,
  0.8,
  1.1,
  1.8,
  2.3,
  2.5,
  1.9,
  1.6,
  2.0,
  1.5,
  1.5,
  1.7,
  1.8,
  1.1,
  1.9,
  1.0,
  1.6,
  1.2,
  1.0,
  1.2,
  1.5,
  1.9,
  2.5,
  2.3,
  1.6,
  1.4,
  2.1,
  1.8,
  1.0,
  0.9,
  1.5,
  2.2,
  1.8,
  1.3,
  1.3,
  1.2,
  2.1,
  1.9,
  1.9,
  1.5,
  2.3,
  1.7,
  1.4,
  1.0,
  1.6,
  1.8,
  2.6,
  1.1,
  1.3,
  0.8,
  2.2,
  1.9,
  1.8,
  1.0,
  1.4,
  1.2,
  2.3,
  0.7,
  2.2,
  0.8,
  1.2,
  1.1,
  2.1,
  1.4,
  1.3,
  2.3,
  1.9,
  2.6,
  1.6,
  0.7,
  1.2,
  1.4,
  1.5,
  2.3,
  2.2,
  0.7777777777777778,
  1.3,
  1.3,
  1.2,
  1.6,
  2.3,
  2.4,
  1.1,
  0.8,
  1.5,
  1.6,
  1.0,
  1.2,
  1.6,
  2.5,
  2.5,
  1.4,
  1.8,
  0.9,
  0.5,
  1.9,
  1.6,
  1.9,
  1.0,
  0.9,
  1.3,
  1.6,
  1.8,
  2.3,
  2.1,
  1.3,
  1.5,
  0.9,
  1.8,
  2.5,
  1.9,
  0.42857142857142855,
  1.9,
  1.2,
  2.3,
  1.4,
  1.7,
  1.6,
  1.0,
  1.8,
  0.5,
  1.6,
  1.8,
  1.3,
  1.2,
  2.0,
  1.9,
  1.8,
  ...],
 [0.6,
  0.4,
  1.6,
  1.8,
  1.2,
  0.5,
  1.1,
  2.5,
  1.4,
  1.0,
  2.0,
  0.5,
  0.9,
  1.1,
  0.1,
  0.7,
  1.2,
  1.2,
  2.2,
  0.8,
  2.2,
  1.3,
  1.5,
  1.2,
  1.1,
  0.7,
  0.5,
  2.7,
  0.4,
  1.0,
  0.8,
  2.0,
  1.0,
  1.0,
  0.3,
  1.2,
  0.7,
  1.8,
  1.1,
  0.2,
  0.9,
  2.7,
  0.7,
  0.7,
  1.5,
  1.3,
  1.2,
  1.8,
  0.4,
  1.1,
  0.5,
  1.0,
  1.0,
  2.1,
  0.8,
  1.3,
  2.7,
  0.7,
  1.4,
  0.3,
  0.7,
  1.2,
  0.7,
  1.3,
  0.3,
  0.8,
  2.2,
  0.9,
  1.8,
  0.9,
  0.6,
  2.0,
  1.6,
  2.2,
  1.2,
  0.6,
  0.4,
  0.9,
  2.0,
  0.2,
  2.0,
  2.0,
  0.5,
  1.2,
  1.0,
  2.7,
  1.0,
  0.5,
  0.4,
  0.2,
  0.8,
  1.2,
  2.3,
  0.7,
  1.3,
  1.0,
  0.7,
  0.7,
  1.4,
  0.6,
  2.4,
  0.6,
  0.7,
  0.5,
  0.2,
  1.9,
  0.9,
  1.9,
  0.7,
  1.0,
  0.3,
  0.6,
  1.3,
  1.4,
  1.5,
  0.7,
  2.5,
  1.1,
  0.3,
  0.9,
  0.7,
  0.7,
  0.9,
  0.8,
  1.0,
  2.1,
  0.8,
  2.2,
  1.0,
  1.9,
  0.8,
  1.5,
  1.7,
  2.5,
  0.6,
  1.3,
  1.1,
  0.7,
  0.7,
  1.9,
  0.6,
  0.9,
  0.9,
  1.7,
  1.5,
  0.9,
  0.9,
  1.1,
  2.1,
  0.8,
  1.0,
  1.3,
  0.8,
  2.5,
  0.6,
  1.0,
  0.4,
  1.0,
  1.7,
  0.9,
  1.0,
  0.7,
  2.5,
  1.0,
  0.9,
  0.8,
  1.9,
  1.3,
  0.9,
  1.4,
  0.9,
  1.4,
  2.1,
  0.8,
  1.0,
  0.7,
  0.6,
  0.8,
  2.3,
  1.1,
  1.7,
  1.0,
  0.7,
  1.7,
  0.5,
  1.0,
  0.9,
  1.2,
  1.9,
  1.1,
  1.9,
  1.2,
  1.5555555555555556,
  1.3,
  0.9,
  2.1,
  0.9,
  1.3,
  0.9,
  0.5,
  1.5,
  1.2,
  0.9,
  1.8,
  0.9,
  0.9,
  0.8,
  0.6,
  1.1,
  1.5,
  1.9,
  1.9,
  1.8,
  1.3,
  1.9,
  1.625,
  1.7,
  1.1,
  1.6,
  2.1,
  1.2,
  0.9,
  0.6,
  2.0,
  0.9,
  1.0,
  1.8,
  2.1,
  0.6,
  0.8,
  0.7,
  0.9,
  0.6,
  1.4,
  1.6,
  1.8571428571428572,
  1.7,
  1.7,
  0.8,
  0.8,
  1.5,
  2.1,
  0.9,
  1.8,
  1.3,
  2.1,
  0.6,
  1.0,
  1.0,
  0.5,
  1.6,
  1.9,
  0.6,
  1.5,
  0.7,
  1.9,
  1.1,
  2.1666666666666665,
  1.2,
  1.5,
  1.8,
  1.7,
  2.2,
  1.0,
  1.6,
  1.0,
  1.3,
  0.5,
  1.8,
  1.5,
  0.7,
  0.7,
  1.8,
  0.8,
  2.1,
  0.6,
  0.8,
  1.4,
  1.7,
  1.6,
  1.0,
  1.4,
  0.7,
  1.4,
  2.0,
  2.4,
  1.2,
  0.7,
  0.4,
  0.5,
  1.8,
  0.8,
  1.8,
  0.9,
  2.3,
  1.4,
  0.6,
  2.3,
  1.3,
  0.7,
  1.9,
  1.4,
  3.0,
  1.4,
  0.7,
  1.3,
  0.9,
  0.5,
  0.7,
  1.1,
  1.5,
  1.5,
  2.0,
  1.8,
  1.7,
  0.6,
  3.0,
  0.9,
  0.7,
  1.6,
  1.4,
  0.4,
  0.7,
  1.0,
  1.3,
  2.0,
  0.5,
  1.2,
  0.7,
  1.5,
  0.5,
  1.1,
  1.6,
  2.0,
  3.0,
  1.5,
  1.7,
  1.6,
  1.5,
  2.0,
  1.3,
  1.0,
  0.5,
  1.0,
  0.9,
  1.6,
  0.8,
  1.8,
  1.1,
  3.0,
  0.8,
  1.2,
  0.5,
  1.4,
  0.6,
  0.2,
  1.9,
  0.9,
  1.6,
  1.5,
  1.1,
  0.8,
  2.0,
  0.9,
  0.9,
  1.2,
  2.2,
  0.8,
  0.8,
  0.0,
  0.2,
  1.6,
  0.8,
  0.8,
  0.8,
  1.1,
  0.3,
  1.4,
  1.2,
  0.9,
  0.3,
  0.4,
  1.2,
  2.2,
  1.3,
  0.8,
  1.1,
  0.9,
  0.4,
  1.6,
  0.5,
  1.6,
  2.2,
  1.2,
  1.4,
  0.8,
  0.5,
  1.1,
  1.0,
  0.9,
  2.0,
  0.8,
  1.4,
  0.5,
  0.6,
  1.0,
  0.6,
  0.5,
  1.6,
  0.8,
  0.5,
  0.9,
  1.6,
  0.8,
  1.0,
  0.5,
  1.9,
  1.4,
  1.4,
  0.9,
  0.9,
  1.0,
  1.6,
  1.4,
  0.7,
  2.0,
  0.5,
  0.8,
  0.7,
  0.5,
  1.7,
  0.5,
  1.2,
  0.7,
  1.6,
  1.0,
  0.6,
  1.4,
  1.6,
  1.1,
  1.3,
  2.0,
  0.6,
  0.8,
  0.8,
  0.8,
  0.8,
  1.5,
  0.5,
  0.8,
  0.5,
  0.8,
  0.5,
  0.8,
  1.0,
  1.1,
  1.6,
  1.2,
  0.5,
  1.6,
  1.7,
  1.0,
  0.8,
  0.9,
  0.6,
  0.8,
  0.7,
  1.7,
  0.7,
  1.3,
  0.9,
  1.3,
  1.0,
  0.7,
  1.0,
  0.7,
  0.5,
  0.7,
  0.4,
  1.5,
  1.0,
  0.7,
  1.0,
  1.7,
  0.9,
  1.3,
  0.8,
  0.6,
  1.9,
  0.8,
  1.3,
  1.8,
  0.4,
  0.4,
  0.7,
  0.7,
  0.6,
  1.3,
  1.4,
  0.2,
  1.1,
  1.7,
  1.7,
  1.2,
  1.3,
  1.0,
  0.5,
  0.7,
  0.8,
  0.9,
  0.9,
  1.3,
  1.4,
  0.8,
  0.8,
  0.4,
  2.1,
  1.1,
  0.7,
  0.5,
  0.1,
  0.5,
  0.8,
  0.8,
  1.0,
  0.9,
  0.9,
  1.8,
  0.7,
  1.1,
  1.5,
  1.7,
  1.9,
  0.9,
  0.1,
  0.7,
  1.5,
  1.1,
  0.5,
  0.8,
  0.9,
  1.1,
  0.7,
  1.5,
  0.7,
  1.6,
  0.6,
  0.7,
  1.4,
  1.1,
  1.9,
  0.2,
  1.0,
  0.7,
  0.4,
  0.8,
  1.2,
  1.5,
  0.9,
  0.9,
  0.8,
  0.5,
  1.1,
  1.7,
  1.4,
  1.5,
  0.9,
  2.0,
  0.4,
  1.2,
  1.0,
  0.9,
  1.0,
  0.2,
  1.5,
  1.2,
  1.6,
  0.7,
  0.8,
  0.6,
  0.7,
  0.6,
  1.2,
  1.4,
  1.2,
  1.6,
  1.2,
  0.5,
  1.8,
  0.8,
  1.5,
  1.5,
  0.7,
  0.8,
  0.1,
  1.2,
  1.0,
  0.9,
  1.4,
  0.9,
  0.5,
  1.7,
  0.7,
  1.6,
  1.0,
  1.0,
  0.1,
  1.3,
  0.5,
  1.3,
  1.4,
  1.4,
  0.9,
  0.7,
  0.8,
  0.6,
  1.0,
  0.5,
  0.9,
  1.3,
  1.1,
  1.4,
  0.4,
  0.2,
  0.7,
  1.0,
  1.6,
  1.3,
  1.6,
  1.2,
  0.1,
  1.4,
  0.6,
  1.6,
  0.9,
  1.3,
  0.5,
  1.0,
  0.9,
  1.2,
  0.8,
  1.3,
  0.7,
  0.8,
  0.5,
  0.6,
  0.4,
  0.4,
  1.5,
  1.3,
  1.3,
  0.9,
  0.8,
  1.3,
  0.8,
  0.5,
  1.6,
  1.6,
  0.7,
  1.2,
  1.4,
  1.6,
  1.1,
  1.4,
  0.5,
  1.1,
  0.9,
  0.7,
  0.4,
  0.8,
  0.7,
  1.4,
  1.0,
  0.8,
  0.5,
  1.3,
  0.8,
  1.8,
  1.3,
  0.8,
  1.6,
  0.9,
  1.6,
  0.9,
  1.5,
  1.3,
  0.9,
  0.9,
  0.7,
  0.7,
  1.1,
  0.7,
  0.4,
  0.6,
  1.1,
  1.5,
  1.1,
  1.3,
  1.6,
  1.1,
  0.9,
  1.5,
  1.6,
  0.7,
  0.9,
  1.6,
  1.1,
  1.3,
  0.7,
  0.8,
  1.5,
  0.9,
  1.0,
  0.9,
  0.4,
  1.6,
  0.5,
  0.7,
  1.1,
  1.0,
  0.8,
  0.6,
  0.5,
  1.3,
  1.2,
  1.7,
  1.6,
  1.1,
  0.7,
  1.0,
  1.7,
  0.2,
  0.7,
  0.4,
  1.0,
  1.1,
  0.9,
  1.6,
  1.0,
  0.4,
  1.0,
  1.6,
  0.8,
  1.1,
  1.0,
  2.0,
  1.0,
  0.7,
  1.1,
  1.0,
  1.1,
  0.8,
  0.7,
  0.7,
  0.1,
  0.3,
  0.8,
  1.0,
  1.7,
  1.9,
  0.7,
  2.1,
  1.7,
  1.3,
  1.6,
  1.1,
  1.1,
  1.0,
  0.6,
  1.0,
  0.8,
  0.6,
  1.2,
  1.8,
  0.8,
  0.4,
  0.8,
  1.2,
  0.7,
  0.4,
  1.4,
  1.2,
  1.5,
  1.0,
  1.0,
  0.6,
  1.9,
  2.4,
  0.7,
  1.1,
  0.7,
  0.7,
  2.1,
  0.6,
  1.3,
  0.8,
  0.3,
  0.5,
  0.9,
  1.1,
  0.9,
  0.6,
  2.0,
  1.0,
  1.1,
  0.5,
  1.5,
  1.0,
  0.6,
  2.4,
  1.2,
  1.1,
  0.6,
  0.9,
  1.5,
  0.6,
  1.7,
  1.3,
  1.0,
  0.8,
  2.2,
  1.3,
  0.6,
  0.6,
  0.7,
  0.6,
  1.3,
  2.4,
  1.1,
  0.5,
  0.7,
  0.5,
  1.1,
  1.0,
  0.7,
  1.1,
  1.6,
  0.6,
  0.4,
  1.8,
  1.3,
  1.1,
  0.8,
  2.2,
  0.5,
  0.6,
  0.7,
  2.6,
  1.3,
  1.6,
  1.2,
  1.2,
  1.6,
  0.5,
  0.8,
  0.9,
  0.7,
  0.7,
  1.6,
  0.9,
  0.6,
  1.5,
  0.4,
  0.8,
  2.4,
  0.5,
  1.4,
  1.1,
  1.7,
  0.9,
  1.9,
  1.5,
  0.7,
  1.4,
  1.2,
  0.5,
  0.7,
  0.9,
  0.7,
  0.7,
  1.2,
  1.0,
  1.7,
  0.6,
  1.3,
  0.8,
  2.1,
  0.7,
  1.1,
  1.2,
  1.4,
  1.0,
  1.6,
  1.4,
  1.0,
  2.1,
  1.0,
  0.8,
  0.5,
  0.4,
  0.8,
  1.0,
  0.6,
  1.0,
  1.0,
  1.4,
  0.9,
  0.9,
  1.2,
  1.3,
  0.9,
  1.4,
  0.7,
  1.1,
  2.3,
  0.2,
  0.8,
  1.0,
  1.4,
  1.0,
  0.6,
  0.5,
  1.3,
  1.3,
  1.5,
  0.9,
  1.5,
  1.0,
  1.3,
  1.3,
  0.7,
  0.8,
  0.4,
  2.0,
  1.4,
  1.1,
  1.3,
  1.2,
  0.7,
  1.5,
  0.6,
  0.8,
  1.6,
  1.4,
  1.6,
  0.6,
  1.3,
  1.5,
  1.3,
  1.3,
  0.9,
  1.2,
  1.0,
  1.2,
  1.4,
  1.5,
  1.3,
  0.4444444444444444,
  1.2,
  0.8,
  0.5,
  1.7,
  1.3,
  2.0,
  1.2,
  0.4,
  1.1,
  1.3,
  1.6,
  0.6,
  1.1,
  1.5,
  0.5,
  1.3,
  1.0,
  0.8,
  1.2,
  1.2,
  1.2,
  1.7,
  0.5,
  1.9,
  1.8,
  1.2,
  0.9,
  1.4,
  0.5,
  1.3,
  1.3,
  0.5,
  1.9,
  1.0,
  0.9,
  1.7,
  0.5,
  0.6,
  1.3,
  1.6,
  1.5,
  1.9,
  ...],
 [14,
  11,
  9,
  16,
  13,
  12,
  9,
  10,
  14,
  11,
  13,
  17,
  19,
  5,
  12,
  16,
  23,
  20,
  18,
  11,
  12,
  10,
  9,
  19,
  11,
  15,
  16,
  10,
  10,
  11,
  15,
  16,
  12,
  14,
  6,
  17,
  10,
  25,
  11,
  17,
  18,
  14,
  14,
  11,
  11,
  16,
  11,
  12,
  7,
  15,
  26,
  15,
  7,
  15,
  17,
  17,
  11,
  12,
  19,
  13,
  11,
  11,
  22,
  16,
  13,
  20,
  10,
  11,
  9,
  16,
  9,
  14,
  15,
  6,
  12,
  15,
  17,
  10,
  16,
  7,
  17,
  14,
  12,
  15,
  12,
  19,
  7,
  15,
  7,
  9,
  17,
  25,
  16,
  10,
  11,
  10,
  8,
  18,
  14,
  18,
  20,
  17,
  12,
  15,
  7,
  11,
  10,
  17,
  18,
  15,
  18,
  26,
  18,
  6,
  14,
  17,
  7,
  9,
  20,
  9,
  18,
  19,
  12,
  18,
  22,
  20,
  9,
  10,
  9,
  11,
  10,
  13,
  19,
  15,
  13,
  10,
  16,
  5,
  10,
  18,
  5,
  18,
  24,
  12,
  19,
  6,
  18,
  24,
  11,
  12,
  20,
  10,
  13,
  18,
  11,
  16,
  18,
  18,
  8,
  23,
  5,
  18,
  14,
  15,
  18,
  24,
  13,
  11,
  18,
  14,
  16,
  8,
  5,
  17,
  9,
  13,
  22,
  16,
  9,
  9,
  16,
  15,
  19,
  5,
  11,
  13,
  22,
  16,
  10,
  10,
  8,
  12,
  15,
  7,
  16,
  7,
  15,
  18,
  14,
  8,
  7,
  11,
  7,
  21,
  18,
  9,
  13,
  11,
  4,
  15,
  12,
  19,
  13,
  17,
  12,
  16,
  11,
  13,
  5,
  6,
  11,
  18,
  9,
  13,
  17,
  11,
  14,
  13,
  16,
  23,
  19,
  15,
  4,
  22,
  12,
  13,
  4,
  18,
  10,
  17,
  12,
  15,
  10,
  16,
  11,
  4,
  4,
  18,
  16,
  11,
  12,
  13,
  22,
  22,
  13,
  21,
  18,
  18,
  22,
  11,
  14,
  14,
  19,
  12,
  11,
  16,
  9,
  5,
  4,
  19,
  12,
  15,
  2,
  21,
  13,
  11,
  14,
  16,
  14,
  15,
  10,
  19,
  20,
  13,
  17,
  11,
  9,
  11,
  4,
  16,
  2,
  7,
  22,
  12,
  20,
  11,
  12,
  15,
  7,
  11,
  13,
  9,
  21,
  13,
  19,
  14,
  10,
  19,
  15,
  15,
  15,
  16,
  4,
  11,
  9,
  18,
  8,
  12,
  10,
  9,
  2,
  8,
  20,
  14,
  11,
  20,
  10,
  18,
  12,
  6,
  18,
  7,
  9,
  11,
  19,
  17,
  16,
  21,
  1,
  12,
  7,
  11,
  16,
  10,
  10,
  20,
  9,
  17,
  15,
  8,
  20,
  12,
  17,
  16,
  9,
  12,
  18,
  9,
  0,
  16,
  12,
  10,
  19,
  11,
  17,
  8,
  15,
  16,
  18,
  16,
  16,
  8,
  18,
  14,
  18,
  8,
  9,
  0,
  15,
  14,
  15,
  11,
  14,
  10,
  12,
  10,
  17,
  15,
  8,
  10,
  14,
  16,
  18,
  14,
  10,
  16,
  20,
  21,
  8,
  14,
  14,
  14,
  11,
  14,
  10,
  15,
  12,
  16,
  9,
  10,
  18,
  16,
  9,
  15,
  14,
  20,
  13,
  19,
  15,
  14,
  14,
  16,
  14,
  11,
  13,
  11,
  13,
  8,
  14,
  16,
  20,
  18,
  14,
  8,
  20,
  16,
  14,
  23,
  11,
  12,
  11,
  14,
  13,
  12,
  15,
  16,
  13,
  12,
  11,
  14,
  21,
  13,
  18,
  19,
  15,
  26,
  10,
  15,
  12,
  14,
  19,
  15,
  7,
  16,
  13,
  11,
  13,
  16,
  12,
  14,
  20,
  15,
  16,
  12,
  13,
  29,
  18,
  15,
  20,
  15,
  21,
  21,
  10,
  14,
  12,
  8,
  11,
  16,
  13,
  15,
  12,
  21,
  19,
  14,
  11,
  17,
  15,
  32,
  14,
  13,
  16,
  21,
  14,
  11,
  11,
  15,
  14,
  12,
  17,
  13,
  21,
  11,
  19,
  10,
  14,
  17,
  15,
  21,
  29,
  7,
  19,
  22,
  13,
  12,
  13,
  14,
  19,
  32,
  13,
  16,
  19,
  6,
  18,
  21,
  10,
  13,
  10,
  17,
  15,
  12,
  35,
  20,
  13,
  14,
  13,
  10,
  17,
  13,
  22,
  12,
  10,
  21,
  17,
  7,
  14,
  13,
  12,
  16,
  9,
  16,
  36,
  16,
  20,
  17,
  11,
  13,
  18,
  20,
  17,
  10,
  8,
  13,
  22,
  12,
  9,
  13,
  19,
  18,
  12,
  9,
  23,
  18,
  18,
  17,
  8,
  9,
  20,
  33,
  15,
  11,
  35,
  17,
  16,
  10,
  8,
  19,
  12,
  17,
  20,
  11,
  12,
  18,
  5,
  11,
  16,
  11,
  32,
  20,
  8,
  24,
  22,
  15,
  15,
  9,
  18,
  18,
  18,
  15,
  17,
  11,
  10,
  11,
  25,
  13,
  19,
  10,
  23,
  7,
  15,
  4,
  20,
  16,
  18,
  14,
  19,
  13,
  30,
  14,
  18,
  10,
  18,
  7,
  4,
  13,
  16,
  28,
  9,
  26,
  19,
  19,
  10,
  16,
  12,
  13,
  23,
  15,
  18,
  17,
  18,
  28,
  10,
  14,
  17,
  21,
  7,
  16,
  14,
  8,
  4,
  25,
  21,
  18,
  10,
  15,
  8,
  12,
  14,
  14,
  15,
  6,
  25,
  17,
  8,
  15,
  12,
  13,
  17,
  19,
  3,
  15,
  20,
  20,
  7,
  16,
  13,
  16,
  7,
  16,
  19,
  23,
  16,
  15,
  16,
  18,
  14,
  14,
  3,
  25,
  13,
  7,
  22,
  17,
  13,
  13,
  14,
  9,
  17,
  21,
  23,
  14,
  13,
  8,
  16,
  7,
  15,
  23,
  14,
  4,
  18,
  15,
  22,
  15,
  16,
  14,
  14,
  19,
  16,
  13,
  16,
  26,
  21,
  7,
  16,
  9,
  19,
  16,
  19,
  16,
  19,
  10,
  16,
  14,
  17,
  8,
  19,
  9,
  16,
  14,
  16,
  17,
  19,
  14,
  8,
  25,
  19,
  16,
  18,
  16,
  14,
  8,
  20,
  13,
  13,
  14,
  10,
  7,
  13,
  21,
  16,
  15,
  9,
  17,
  16,
  17,
  17,
  15,
  14,
  14,
  8,
  27,
  14,
  21,
  13,
  14,
  12,
  7,
  11,
  22,
  18,
  15,
  13,
  23,
  20,
  14,
  12,
  13,
  16,
  10,
  14,
  9,
  21,
  16,
  13,
  17,
  14,
  15,
  20,
  14,
  23,
  9,
  12,
  8,
  14,
  14,
  7,
  13,
  22,
  16,
  12,
  17,
  9,
  13,
  18,
  15,
  15,
  10,
  15,
  16,
  8,
  26,
  12,
  22,
  12,
  12,
  14,
  20,
  10,
  18,
  12,
  17,
  15,
  9,
  24,
  14,
  13,
  18,
  12,
  28,
  11,
  9,
  16,
  13,
  15,
  20,
  14,
  12,
  13,
  13,
  9,
  11,
  10,
  22,
  15,
  7,
  13,
  16,
  26,
  17,
  11,
  8,
  14,
  12,
  11,
  20,
  14,
  15,
  13,
  12,
  13,
  16,
  10,
  10,
  16,
  13,
  18,
  20,
  14,
  8,
  13,
  13,
  12,
  12,
  13,
  16,
  15,
  18,
  10,
  15,
  27,
  19,
  11,
  13,
  18,
  12,
  10,
  11,
  13,
  13,
  18,
  10,
  18,
  10,
  15,
  18,
  15,
  9,
  17,
  16,
  33,
  8,
  14,
  8,
  12,
  11,
  15,
  11,
  11,
  14,
  13,
  17,
  16,
  10,
  17,
  20,
  12,
  33,
  19,
  8,
  16,
  9,
  12,
  13,
  31,
  18,
  9,
  11,
  12,
  12,
  10,
  16,
  19,
  16,
  21,
  9,
  17,
  9,
  6,
  12,
  20,
  15,
  10,
  16,
  10,
  11,
  14,
  34,
  17,
  10,
  15,
  10,
  13,
  15,
  21,
  4,
  14,
  8,
  21,
  9,
  16,
  20,
  10,
  19,
  4,
  12,
  13,
  12,
  10,
  14,
  14,
  11,

In [63]:
ftr = np.array(data['FTR'])
ftr[ftr!='H'] = 'no'
ftr[ftr=='H'] = 'yes'
ftr

array(['yes', 'no', 'no', ..., 'yes', 'no', 'no'], dtype=object)

In [64]:
for i in rend:
    print(len(i))
    
print(len(rend))

3800
3800
3800
3800
3800
3800
3800
3800
8

In [65]:
# [x-y for x,y in rend[2],rend[4]]
[x-y for (x,y) in zip(rend[2],rend[4])]

[7,
 5,
 -3,
 -6,
 3,
 5,
 -1,
 -18,
 1,
 1,
 -4,
 11,
 11,
 -5,
 7,
 7,
 8,
 12,
 -1,
 -4,
 -6,
 -2,
 -11,
 9,
 0,
 6,
 8,
 -18,
 4,
 3,
 1,
 0,
 0,
 6,
 0,
 10,
 2,
 11,
 2,
 10,
 6,
 -12,
 7,
 2,
 -2,
 7,
 0,
 -3,
 1,
 6,
 14,
 8,
 -3,
 -1,
 5,
 7,
 -16,
 3,
 6,
 8,
 4,
 1,
 15,
 3,
 7,
 9,
 -6,
 5,
 -13,
 3,
 0,
 -2,
 -3,
 -11,
 -3,
 8,
 10,
 -2,
 1,
 0,
 5,
 -1,
 1,
 6,
 4,
 -8,
 -3,
 8,
 1,
 2,
 4,
 16,
 0,
 2,
 -3,
 -3,
 1,
 9,
 -2,
 7,
 -1,
 9,
 5,
 5,
 1,
 -1,
 2,
 2,
 9,
 5,
 11,
 15,
 4,
 -10,
 1,
 4,
 -12,
 0,
 13,
 2,
 9,
 7,
 4,
 8,
 12,
 3,
 -1,
 -10,
 -1,
 0,
 2,
 -2,
 4,
 -4,
 5,
 -5,
 6,
 -5,
 3,
 0,
 -5,
 5,
 15,
 2,
 5,
 -3,
 9,
 17,
 -7,
 2,
 9,
 -2,
 5,
 0,
 2,
 3,
 12,
 7,
 -9,
 14,
 -4,
 7,
 -4,
 7,
 10,
 15,
 -5,
 -1,
 7,
 6,
 8,
 -4,
 -14,
 9,
 0,
 5,
 14,
 7,
 -6,
 -2,
 -1,
 7,
 8,
 -6,
 2,
 6,
 12,
 5,
 -11,
 1,
 -7,
 0,
 7,
 -6,
 8,
 -8,
 6,
 8,
 6,
 -2,
 -2,
 3,
 -5,
 10,
 9,
 -1,
 9,
 2,
 -6,
 3,
 -5,
 1,
 -3,
 5,
 -7,
 9,
 -9,
 3,
 -7,
 -8,
 3,
 9,
 1,
 0,
 6,
 2,
 -3,
 -5,
 6,
 19,
 9,
 8,
 -5,
 11,
 -2,
 6,
 -8,
 6,
 1,
 8,
 -5,
 -2,
 0,
 2,
 2,
 -12,
 1,
 10,
 6,
 3,
 0,
 -4,
 14,
 13,
 3,
 4,
 8,
 11,
 9,
 -2,
 2,
 2,
 1,
 2,
 -3,
 8,
 2,
 -3,
 -13,
 9,
 4,
 6,
 -18,
 11,
 -3,
 7,
 6,
 5,
 3,
 2,
 1,
 11,
 12,
 -2,
 -1,
 5,
 -4,
 3,
 -2,
 9,
 -16,
 2,
 2,
 6,
 3,
 2,
 2,
 -2,
 -5,
 3,
 -3,
 0,
 15,
 3,
 13,
 4,
 5,
 11,
 11,
 3,
 1,
 7,
 -18,
 -6,
 -8,
 8,
 4,
 8,
 0,
 -6,
 -8,
 2,
 13,
 4,
 -2,
 6,
 4,
 6,
 5,
 -2,
 13,
 -6,
 -2,
 -11,
 16,
 2,
 -2,
 3,
 -13,
 -4,
 -7,
 5,
 11,
 4,
 -2,
 8,
 1,
 -4,
 1,
 6,
 13,
 5,
 11,
 1,
 3,
 8,
 4,
 4,
 -17,
 3,
 -1,
 -1,
 5,
 2,
 6,
 -1,
 -2,
 10,
 11,
 16,
 12,
 -4,
 11,
 4,
 8,
 -4,
 4,
 -11,
 1,
 8,
 10,
 5,
 5,
 -5,
 -2,
 3,
 6,
 8,
 2,
 -8,
 7,
 -2,
 3,
 3,
 -5,
 7,
 15,
 12,
 1,
 8,
 0,
 4,
 1,
 6,
 1,
 1,
 6,
 8,
 -9,
 2,
 13,
 8,
 -8,
 6,
 6,
 13,
 0,
 6,
 1,
 9,
 6,
 5,
 -2,
 0,
 6,
 -4,
 5,
 1,
 5,
 6,
 8,
 11,
 3,
 -2,
 8,
 2,
 8,
 10,
 -5,
 2,
 0,
 -4,
 7,
 2,
 8,
 8,
 6,
 -3,
 1,
 9,
 14,
 2,
 8,
 9,
 3,
 12,
 -1,
 2,
 5,
 -1,
 3,
 3,
 -2,
 10,
 7,
 4,
 4,
 -2,
 6,
 2,
 8,
 2,
 7,
 1,
 1,
 23,
 8,
 7,
 13,
 1,
 9,
 16,
 2,
 -2,
 6,
 -4,
 1,
 8,
 1,
 7,
 -2,
 6,
 15,
 7,
 3,
 9,
 4,
 18,
 0,
 5,
 4,
 5,
 0,
 2,
 -2,
 5,
 3,
 3,
 9,
 3,
 15,
 -2,
 7,
 2,
 6,
 11,
 -1,
 7,
 22,
 2,
 12,
 13,
 3,
 4,
 5,
 9,
 9,
 18,
 4,
 9,
 4,
 -6,
 4,
 14,
 3,
 4,
 -5,
 3,
 9,
 6,
 24,
 10,
 4,
 2,
 4,
 -4,
 7,
 8,
 14,
 5,
 -6,
 14,
 6,
 0,
 7,
 0,
 -2,
 1,
 2,
 5,
 22,
 6,
 13,
 2,
 -4,
 3,
 11,
 7,
 8,
 1,
 -1,
 3,
 8,
 4,
 -6,
 1,
 5,
 11,
 6,
 1,
 17,
 9,
 10,
 6,
 0,
 -11,
 10,
 24,
 3,
 -4,
 21,
 4,
 2,
 2,
 0,
 10,
 2,
 9,
 7,
 1,
 4,
 7,
 -3,
 -1,
 11,
 0,
 26,
 2,
 -2,
 14,
 13,
 1,
 4,
 2,
 3,
 9,
 4,
 7,
 10,
 -1,
 1,
 1,
 20,
 5,
 16,
 -1,
 11,
 -1,
 -4,
 -8,
 13,
 6,
 11,
 3,
 7,
 -1,
 23,
 5,
 3,
 -1,
 8,
 -4,
 -2,
 3,
 7,
 25,
 0,
 17,
 8,
 4,
 -7,
 1,
 6,
 -1,
 13,
 9,
 7,
 7,
 7,
 18,
 0,
 -3,
 5,
 10,
 -3,
 5,
 9,
 1,
 -5,
 15,
 10,
 7,
 -5,
 5,
 2,
 -1,
 4,
 -5,
 -1,
 0,
 14,
 5,
 -4,
 10,
 1,
 -3,
 7,
 6,
 -10,
 7,
 9,
 13,
 -2,
 10,
 3,
 1,
 -5,
 1,
 0,
 12,
 6,
 3,
 7,
 11,
 5,
 3,
 -2,
 10,
 1,
 -6,
 5,
 7,
 1,
 5,
 5,
 -10,
 10,
 12,
 13,
 3,
 5,
 2,
 5,
 -1,
 5,
 4,
 3,
 -8,
 8,
 9,
 3,
 7,
 9,
 4,
 3,
 9,
 6,
 -4,
 8,
 19,
 12,
 -6,
 7,
 -3,
 13,
 -5,
 10,
 7,
 8,
 3,
 6,
 6,
 12,
 -2,
 14,
 2,
 6,
 4,
 -2,
 -2,
 11,
 -5,
 -12,
 17,
 7,
 6,
 9,
 6,
 4,
 -3,
 10,
 6,
 3,
 -5,
 0,
 -2,
 3,
 10,
 11,
 7,
 1,
 8,
 1,
 6,
 6,
 6,
 -1,
 -10,
 -1,
 16,
 5,
 12,
 -7,
 4,
 1,
 1,
 3,
 9,
 9,
 6,
 5,
 14,
 0,
 2,
 5,
 3,
 3,
 -1,
 4,
 -17,
 11,
 7,
 5,
 10,
 2,
 5,
 5,
 1,
 12,
 2,
 -11,
 -2,
 0,
 5,
 -2,
 6,
 8,
 -11,
 4,
 6,
 4,
 4,
 9,
 5,
 6,
 1,
 3,
 8,
 1,
 10,
 -1,
 13,
 5,
 -11,
 3,
 13,
 -3,
 -8,
 2,
 3,
 3,
 -3,
 12,
 7,
 4,
 10,
 4,
 19,
 -2,
 1,
 10,
 1,
 9,
 14,
 -9,
 0,
 1,
 6,
 -4,
 -3,
 -9,
 11,
 6,
 -2,
 1,
 10,
 19,
 9,
 3,
 -2,
 -1,
 3,
 -2,
 7,
 3,
 9,
 -10,
 4,
 7,
 5,
 -2,
 0,
 -1,
 3,
 8,
 -1,
 7,
 -1,
 -2,
 6,
 3,
 -2,
 3,
 5,
 5,
 6,
 2,
 3,
 18,
 9,
 -1,
 -1,
 11,
 2,
 -12,
 4,
 -3,
 7,
 3,
 0,
 11,
 1,
 4,
 6,
 2,
 -1,
 5,
 2,
 25,
 -1,
 8,
 -7,
 3,
 -13,
 0,
 -1,
 -3,
 -1,
 6,
 5,
 6,
 0,
 3,
 11,
 0,
 26,
 1,
 -3,
 9,
 -2,
 3,
 -2,
 20,
 1,
 -11,
 0,
 1,
 3,
 0,
 2,
 10,
 5,
 9,
 -17,
 2,
 4,
 -5,
 6,
 9,
 6,
 -5,
 -3,
 2,
 -9,
 4,
 20,
 6,
 -1,
 3,
 -1,
 3,
 2,
 -2,
 -11,
 6,
 0,
 15,
 -3,
 10,
 10,
 -3,
 10,
 -12,
 -6,
 7,
 0,
 -9,
 -7,
 -2,
 0,
 ...]

In [66]:
aux = {}
aux['AHh'] = data['AHh'].fillna(data['BbAHh'])
aux['B365H'] = data['B365H']
aux['RendimientoLocal'] = rend[0]
aux['RendimientoVisit'] = rend[1]
aux['GolesMarcadosLocal'] = rend[2]
aux['GolesEncajadosLocal'] = rend[3]
aux['GolesMarcadosVisit'] = rend[4]
aux['GolesEncajadosVisit'] = rend[5]
aux['DisparosLocal'] = rend[6]
aux['DisparosVisit'] = rend[7]
aux['ftr'] = ftr

In [67]:
data_rend_puntos = pd.DataFrame(aux)
data_rend_puntos

,AHh,B365H,RendimientoLocal,RendimientoVisit,GolesMarcadosLocal,GolesEncajadosLocal,GolesMarcadosVisit,GolesEncajadosVisit,DisparosLocal,DisparosVisit,ftr
0,-1.00,1.50,2.4,0.6,14,4,7,20,12.8,6.6,yes
1,0.00,2.62,1.3,0.4,11,16,6,20,8.6,7.2,no
2,1.50,9.00,0.7,1.6,9,15,12,8,9.5,10.9,no
3,-1.25,1.40,2.1,1.8,16,7,22,9,16.6,10.6,yes
4,1.00,5.00,1.8,1.2,13,9,10,11,10.2,9.3,no
...,...,...,...,...,...,...,...,...,...,...,...
3795,-1.00,1.53,0.0,0.0,0,0,0,0,0.0,0.0,no
3796,-1.00,1.57,0.0,0.0,0,0,0,0,0.0,0.0,no
3797,-1.25,1.40,0.0,0.0,0,0,0,0,0.0,0.0,yes
3798,-0.50,2.05,0.0,0.0,0,0,0,0,0.0,0.0,no
3799,-0.25,2.30,0.0,0.0,0,0,0,0,0.0,0.0,no

In [68]:
data_rend_puntos = data_rend_puntos.sample(frac=1,axis=0,random_state=1)
test_rend_puntos = data_rend_puntos[3000:]
data_rend_puntos = data_rend_puntos[:3000]
test_rend_puntos

,AHh,B365H,RendimientoLocal,RendimientoVisit,GolesMarcadosLocal,GolesEncajadosLocal,GolesMarcadosVisit,GolesEncajadosVisit,DisparosLocal,DisparosVisit,ftr
1567,-3.50,1.02,2.8,0.400000,36,8,7,25,17.9,9.700000,yes
193,0.50,4.33,1.0,1.300000,7,11,13,12,9.5,8.600000,no
646,-0.50,2.00,1.4,0.400000,9,9,9,25,10.3,11.000000,yes
2081,-0.75,1.83,1.8,0.900000,13,9,12,20,12.8,10.800000,yes
360,0.00,3.00,1.3,1.100000,12,10,13,16,10.9,9.600000,no
...,...,...,...,...,...,...,...,...,...,...,...
2763,0.00,2.38,1.4,0.200000,7,7,7,31,9.8,10.500000,no
905,1.00,6.00,1.3,1.400000,18,17,12,9,11.8,11.900000,no
1096,-2.00,1.18,2.6,1.200000,34,10,8,9,19.0,10.900000,yes
235,-0.50,1.90,1.3,1.857143,13,14,7,9,12.3,8.285714,yes
1061,-0.75,1.90,1.5,1.000000,7,6,6,14,11.5,8.000000,yes

In [69]:
[1,2,3,4,5,6,7,8,9,10][3:]

[4, 5, 6, 7, 8, 9, 10]

In [70]:
data_rend_puntos

,AHh,B365H,RendimientoLocal,RendimientoVisit,GolesMarcadosLocal,GolesEncajadosLocal,GolesMarcadosVisit,GolesEncajadosVisit,DisparosLocal,DisparosVisit,ftr
3177,1.50,8.50,0.8,1.700000,11,19,21,10,14.8,15.600000,no
2130,1.00,5.00,2.2,2.300000,16,9,27,11,11.5,17.400000,yes
909,-0.25,2.05,1.9,1.300000,19,10,10,10,19.1,8.800000,no
1010,-0.75,1.85,1.5,0.600000,18,10,11,25,11.9,12.300000,yes
1021,-1.00,1.75,2.1,1.500000,16,10,12,8,16.6,9.900000,yes
...,...,...,...,...,...,...,...,...,...,...,...
2460,-0.75,1.75,0.7,0.600000,9,16,5,16,14.0,8.800000,no
3743,-0.75,1.73,3.0,1.666667,5,3,3,2,16.5,9.666667,no
141,0.25,3.30,1.7,0.900000,18,13,13,14,11.2,10.400000,no
3522,-0.50,1.91,1.2,1.300000,13,14,10,14,16.9,12.200000,no
2439,0.00,2.45,0.6,0.500000,7,15,6,17,12.4,11.700000,no

In [71]:
for i in data_rend_puntos.index:
    for j in test_rend_puntos.index:
        assert i != j

In [73]:
# data_rend_puntos.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_rend_puntos.csv',index=False)
# test_rend_puntos.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\test_rend_puntos.csv',index=False)
data_rend_puntos.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\data_rend_disparos'+ str(partidos) +'.csv',index=False)
test_rend_puntos.to_csv('C:\\Users\\GuillemUPV\\Documents\\Weka datasets\\test_rend_disparos'+ str(partidos) +'.csv',index=False)