In [1]:
import os
import pandas as pd
import regex as re
import utils as ut
import importlib as il
import numpy as np

#### constants and utils

In [2]:
metrics_or_logits = "logits"

r_tabnet_own = re.compile(f"^tabnet_own_.+\{metrics_or_logits}.csv$")
r_own = re.compile(f"^own_original.+\{metrics_or_logits}.csv$")
r_tabnet_paper = re.compile(f"^tabnet_paper_.+\{metrics_or_logits}.csv$")

In [3]:
file_names = {}
file_names["tabnet_own"] = list(filter(r_tabnet_own.match, os.listdir(ut.PATH_LOGS)))
file_names["own_original"] = list(filter(r_own.match, os.listdir(ut.PATH_LOGS)))
file_names["tabnet_paper"] = list(filter(r_tabnet_paper.match, os.listdir(ut.PATH_LOGS)))

file_names

{'tabnet_own': ['tabnet_own_comp_rs_unsup_rps_logits.csv',
  'tabnet_own_simp_ss_sup_rps_logits.csv'],
 'own_original': ['own_original_comp_fac_ss_rps_logits.csv',
  'own_original_simp_fac_ss_rps_logits.csv'],
 'tabnet_paper': []}

## COMPARE EXPERIMENTS

In [14]:
il.reload(ut)
metrics_or_logits = "logits"
experiments = [r'own_top1_comp_fac_ss_(miold|v0\.\d)'+'_logits']

experiments = ['lgbm_top1_rs',
 'own_original_comp_bal_fac_ss',
 'own_original_simp_fac_ss',
 'own_top1_adv_comp_fac_ss_miv2',
 'tabnet_owntop1_comp_ss_sup',
 'tabnet_own_simp_ss_sup',
 'tabnet_paper_ss_unsup',
 'tabnet_own_comp_rs_unsup_rps']

res = ut.compare_experiments(map(lambda x: x+'_logits',experiments),
                    aliases=[],title="deep_analysis",save=1)

res

^lgbm_top1_rs_logits|own_original_comp_bal_fac_ss_logits|own_original_simp_fac_ss_logits|own_top1_adv_comp_fac_ss_miv2_logits|tabnet_owntop1_comp_ss_sup_logits|tabnet_own_simp_ss_sup_logits|tabnet_paper_ss_unsup_logits|tabnet_own_comp_rs_unsup_rps_logits\.csv$
['lgbm_top1_rs_logits', 'own_original_comp_bal_fac_ss_logits', 'own_original_simp_fac_ss_logits', 'own_top1_adv_comp_fac_ss_miv2_logits', 'tabnet_owntop1_comp_ss_sup_logits', 'tabnet_own_comp_rs_unsup_rps_logits', 'tabnet_own_simp_ss_sup_logits', 'tabnet_paper_ss_unsup_logits']
Getting aliases...
^lgbm_top1_rs_logits|own_original_comp_bal_fac_ss_logits|own_original_simp_fac_ss_logits|own_top1_adv_comp_fac_ss_miv2_logits|tabnet_owntop1_comp_ss_sup_logits|tabnet_own_comp_rs_unsup_rps_logits|tabnet_own_simp_ss_sup_logits|tabnet_paper_ss_unsup_logits\.csv$

,match,Date,season,Div,HomeTeam,AwayTeam,FTHG,FTAG,label,prediction_lgbm_top1_rs_logits,...,accurate_flag_own_top1_adv_comp_fac_ss_miv2_logits,rps_own_top1_adv_comp_fac_ss_miv2_logits,accurate_flag_tabnet_owntop1_comp_ss_sup_logits,rps_tabnet_owntop1_comp_ss_sup_logits,accurate_flag_tabnet_own_comp_rs_unsup_rps_logits,rps_tabnet_own_comp_rs_unsup_rps_logits,accurate_flag_tabnet_own_simp_ss_sup_logits,rps_tabnet_own_simp_ss_sup_logits,accurate_flag_tabnet_paper_ss_unsup_logits,rps_tabnet_paper_ss_unsup_logits
0,15969,2020-01-01,T19-20,E0,Brighton,Chelsea,1,1,0.0,2.0,...,0.0,0.434131,0.0,0.454672,0.0,0.465575,0.0,0.388139,0,0.582804
1,15971,2020-01-01,T19-20,E0,Newcastle,Leicester,0,3,2.0,2.0,...,1.0,0.206190,1.0,0.208920,1.0,0.177988,1.0,0.201779,0,0.353059
2,15972,2020-01-01,T19-20,E0,Southampton,Tottenham,1,0,1.0,2.0,...,0.0,0.140483,0.0,0.131028,0.0,0.146577,0.0,0.156329,0,0.139524
3,15973,2020-01-01,T19-20,E0,Watford,Wolves,2,1,1.0,1.0,...,0.0,0.143783,0.0,0.136710,0.0,0.128879,1.0,0.101111,1,0.093010
4,15974,2020-01-01,T19-20,E0,Man City,Everton,2,1,1.0,1.0,...,1.0,0.008832,1.0,0.003266,1.0,0.005951,1.0,0.003882,1,0.025802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,6202,2020-12-05,T20-21,D1,Bielefeld,Mainz,2,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.094864
3239,35366,2020-12-05,T20-21,I1,Spezia,Lazio,1,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.154615
3240,45487,2020-12-06,T20-21,SP1,Villarreal,Elche,0,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.323600
3241,35372,2020-12-06,T20-21,I1,Crotone,Napoli,0,4,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.140351
3242,35370,2020-12-06,T20-21,I1,Parma,Benevento,0,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.287793

In [49]:
ut.compare_experiments([r'own_top1_comp_fac_ss_(v1(.*))_logits'],title="versions_v1",save=True)

['own_top1_comp_fac_ss_v1.3_logits', 'own_top1_comp_fac_ss_v1_logits']
Getting aliases...

,match,Date,season,Div,HomeTeam,AwayTeam,FTHG,FTAG,label,prediction_own_top1_comp_fac_ss_v1.3_logits,...,home_own_top1_comp_fac_ss_v1.3_logits,away_own_top1_comp_fac_ss_v1.3_logits,prediction_own_top1_comp_fac_ss_v1_logits,draw_own_top1_comp_fac_ss_v1_logits,home_own_top1_comp_fac_ss_v1_logits,away_own_top1_comp_fac_ss_v1_logits,accurate_flag_own_top1_comp_fac_ss_v1.3_logits,rps_own_top1_comp_fac_ss_v1.3_logits,accurate_flag_own_top1_comp_fac_ss_v1_logits,rps_own_top1_comp_fac_ss_v1_logits
0,15969,2020-01-01,T19-20,E0,Brighton,Chelsea,1,1,0,1,...,0.3509,0.3123,2.0,0.1860,0.1387,0.6753,0,0.268683,0.0,0.559313
1,15976,2020-01-01,T19-20,E0,West Ham,Bournemouth,4,0,1,1,...,0.7736,0.0138,1.0,0.2929,0.4703,0.2368,1,0.022695,1.0,0.070932
2,15975,2020-01-01,T19-20,E0,Norwich,Crystal Palace,1,1,0,0,...,0.4017,0.1442,2.0,0.2981,0.3125,0.3894,1,0.159469,0.0,0.322148
3,15974,2020-01-01,T19-20,E0,Man City,Everton,2,1,1,1,...,0.7624,0.0209,1.0,0.1014,0.8705,0.0281,1,0.023678,1.0,0.005536
4,15977,2020-01-01,T19-20,E0,Arsenal,Man United,2,0,1,1,...,0.5335,0.1007,2.0,0.2801,0.2821,0.4378,1,0.072002,0.0,0.135062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2277,27051,2021-05-23,T20-21,F1,Reims,Bordeaux,1,2,2,2,...,0.0874,0.6592,1.0,0.3048,0.4093,0.2859,1,0.090178,0.0,0.301421
2278,27052,2021-05-23,T20-21,F1,Rennes,Nimes,2,0,1,1,...,0.6742,0.0471,1.0,0.1987,0.7010,0.1003,1,0.039923,1.0,0.024771
2279,27053,2021-05-23,T20-21,F1,St Etienne,Dijon,0,1,2,1,...,0.7915,0.0368,1.0,0.1898,0.7217,0.0885,0,0.478618,0.0,0.433428
2280,27054,2021-05-23,T20-21,F1,Strasbourg,Lorient,1,1,0,0,...,0.2570,0.1936,1.0,0.2676,0.5404,0.1920,1,0.120261,0.0,0.286637
2281,45756,2021-05-23,T20-21,SP1,Sevilla,Alaves,1,0,1,1,...,0.5341,0.0637,1.0,0.1664,0.7640,0.0696,1,0.082911,1.0,0.016267

In [88]:
res.columns

Index(['match', 'Date', 'season', 'Div', 'HomeTeam', 'AwayTeam', 'FTHG',
       'FTAG', 'label', 'prediction_own_fac', 'draw_own_fac', 'home_own_fac',
       'away_own_fac', 'prediction_tab_own_unsup', 'draw_tab_own_unsup',
       'home_tab_own_unsup', 'away_tab_own_unsup', 'prediction_tab_own_sup',
       'draw_tab_own_sup', 'home_tab_own_sup', 'away_tab_own_sup',
       'accurate_flag_own_fac', 'rps_own_fac', 'accurate_flag_tab_own_unsup',
       'rps_tab_own_unsup', 'accurate_flag_tab_own_sup', 'rps_tab_own_sup'],
      dtype='object')

## RESUME METRICS

- Accuracy absoluto
- Accuracy relativo (haciendo inner join)
- RPS
- bias con empates (min 0.5 para home/away win)

### General accuracy

In [18]:
list(map(lambda x: x.replace('logits','metrics'),experiments))

['own_top1_comp_fac_ss_miold_metrics',
 'own_top1_comp_fac_ss_v0.1_metrics',
 'own_top1_comp_fac_ss_v0.2_metrics',
 'own_top1_comp_fac_ss_v0.3_metrics']

In [21]:
metrics_or_logits = "logits"
# filt_regex = r'(\w+)_metrics'
# filt_regex = list(map(lambda x: x.replace('logits','metrics'),experiments))
filt_regex = r'own_top1_comp_fac_ss_(.+)_metrics'

metricsDFs = ut.read_dataframes([filt_regex])

In [22]:
metrics = { "validation": {},  "abs_test": {}, }
for key in metricsDFs.keys():
    # name = re.match(r'(\w+)_metrics',key).group(1)
    name = ut.filter_group(filt_regex,key)
    test_max = metricsDFs[key].test.round(4).max()
    val_max = metricsDFs[key].validation.round(4).max()
    metrics["abs_test"][name] = test_max
    metrics["validation"][name] = val_max

resume = pd.DataFrame(metrics).sort_values('abs_test',ascending=False)
resume

       validation  abs_test
v0.3       0.7540    0.7188
v1.3       0.6982    0.6525
miold      0.6252    0.5850
v0.1       0.6322    0.5806
v1         0.5363    0.5029
v0.2       0.5347    0.4992

### Relative accuracies

In [6]:
il.reload(ut)
res = ut.compare_experiments(["tabnet_owntop1_comp_ss_sup_logits","lgbm_top1_ss_logits"],title='tabnetowntop1_vs_lgbm',save=False)

^tabnet_owntop1_comp_ss_sup_logits|lgbm_top1_ss_logits\.csv$
[]
Getting aliases...
^\.csv$

AssertionError:

In [20]:
res

,match,Date,season,Div,HomeTeam,AwayTeam,FTHG,FTAG,label,prediction_lgbm_top1_ss_logits,...,home_lgbm_top1_ss_logits,away_lgbm_top1_ss_logits,prediction_tabnet_owntop1_comp_ss_sup_logits,draw_tabnet_owntop1_comp_ss_sup_logits,home_tabnet_owntop1_comp_ss_sup_logits,away_tabnet_owntop1_comp_ss_sup_logits,accurate_flag_lgbm_top1_ss_logits,rps_lgbm_top1_ss_logits,accurate_flag_tabnet_owntop1_comp_ss_sup_logits,rps_tabnet_owntop1_comp_ss_sup_logits
0,15751,2020-01-01,T19-20,E0,Brighton,Chelsea,1,1,0.0,2,...,0.2835,0.4594,0.0,0.5139,0.2421,0.2439,0,0.381474,1.0,0.147915
1,15757,2020-01-01,T19-20,E0,Norwich,Crystal Palace,1,1,0.0,2,...,0.2340,0.4634,0.0,0.6307,0.2160,0.1532,0,0.350553,1.0,0.079942
2,15754,2020-01-01,T19-20,E0,Southampton,Tottenham,1,0,1.0,1,...,0.3702,0.2678,1.0,0.2356,0.7244,0.0400,1,0.101380,1.0,0.028554
3,15753,2020-01-01,T19-20,E0,Newcastle,Leicester,0,3,2.0,2,...,0.1720,0.6137,2.0,0.2081,0.0677,0.7242,1,0.097576,1.0,0.059686
4,15756,2020-01-01,T19-20,E0,Man City,Everton,2,1,1.0,1,...,0.7817,0.0623,1.0,0.2329,0.7463,0.0208,1,0.014109,1.0,0.027338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,26489,2021-05-23,T20-21,F1,St Etienne,Dijon,0,1,2.0,1,...,0.6681,0.0960,1.0,0.2958,0.5845,0.1196,0,0.436432,0.0,0.431213
3239,26490,2021-05-23,T20-21,F1,Strasbourg,Lorient,1,1,0.0,1,...,0.4648,0.2517,2.0,0.3529,0.2875,0.3596,0,0.288363,0.0,0.274025
3240,44888,2021-05-23,T20-21,SP1,Sevilla,Alaves,1,0,1.0,1,...,0.8088,0.0471,1.0,0.2415,0.6932,0.0653,1,0.011492,1.0,0.031293
3241,26481,2021-05-23,T20-21,F1,Angers,Lille,1,2,2.0,2,...,0.2058,0.5717,2.0,0.2813,0.2454,0.4734,1,0.116474,1.0,0.178271
3242,44887,2021-05-23,T20-21,SP1,Granada,Getafe,0,0,0.0,1,...,0.4754,0.2142,2.0,0.3062,0.1773,0.5165,0,0.260715,0.0,0.374065

In [24]:
def read_data(path,dtypes=None):
    return pd.read_csv(path,sep=';',decimal=',',parse_dates=['Date'],
                       date_format="%d/%m/%Y",dtype=dtypes)

dtypes = ut.load_json("F:\\TFG\\" + "datasets/raw_datasets/dtypes.json")
datalake = read_data("F:\TFG\datasets\\raw_datasets\datalake.csv",dtypes)

In [28]:
res

,match,Date,season,Div,HomeTeam,AwayTeam,FTHG,FTAG,label,prediction_lgbm_top1_ss_logits,...,home_lgbm_top1_ss_logits,away_lgbm_top1_ss_logits,prediction_tabnet_owntop1_comp_ss_sup_logits,draw_tabnet_owntop1_comp_ss_sup_logits,home_tabnet_owntop1_comp_ss_sup_logits,away_tabnet_owntop1_comp_ss_sup_logits,accurate_flag_lgbm_top1_ss_logits,rps_lgbm_top1_ss_logits,accurate_flag_tabnet_owntop1_comp_ss_sup_logits,rps_tabnet_owntop1_comp_ss_sup_logits
0,15751,2020-01-01,T19-20,E0,Brighton,Chelsea,1,1,0.0,2,...,0.2835,0.4594,0.0,0.5139,0.2421,0.2439,0,0.381474,1.0,0.147915
1,15757,2020-01-01,T19-20,E0,Norwich,Crystal Palace,1,1,0.0,2,...,0.2340,0.4634,0.0,0.6307,0.2160,0.1532,0,0.350553,1.0,0.079942
2,15754,2020-01-01,T19-20,E0,Southampton,Tottenham,1,0,1.0,1,...,0.3702,0.2678,1.0,0.2356,0.7244,0.0400,1,0.101380,1.0,0.028554
3,15753,2020-01-01,T19-20,E0,Newcastle,Leicester,0,3,2.0,2,...,0.1720,0.6137,2.0,0.2081,0.0677,0.7242,1,0.097576,1.0,0.059686
4,15756,2020-01-01,T19-20,E0,Man City,Everton,2,1,1.0,1,...,0.7817,0.0623,1.0,0.2329,0.7463,0.0208,1,0.014109,1.0,0.027338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,26489,2021-05-23,T20-21,F1,St Etienne,Dijon,0,1,2.0,1,...,0.6681,0.0960,1.0,0.2958,0.5845,0.1196,0,0.436432,0.0,0.431213
3239,26490,2021-05-23,T20-21,F1,Strasbourg,Lorient,1,1,0.0,1,...,0.4648,0.2517,2.0,0.3529,0.2875,0.3596,0,0.288363,0.0,0.274025
3240,44888,2021-05-23,T20-21,SP1,Sevilla,Alaves,1,0,1.0,1,...,0.8088,0.0471,1.0,0.2415,0.6932,0.0653,1,0.011492,1.0,0.031293
3241,26481,2021-05-23,T20-21,F1,Angers,Lille,1,2,2.0,2,...,0.2058,0.5717,2.0,0.2813,0.2454,0.4734,1,0.116474,1.0,0.178271
3242,44887,2021-05-23,T20-21,SP1,Granada,Getafe,0,0,0.0,1,...,0.4754,0.2142,2.0,0.3062,0.1773,0.5165,0,0.260715,0.0,0.374065

In [36]:
res_bets = res.merge(datalake[["matchId","B365H","B365D","B365A"]],left_on="match",right_on="matchId",how="left").drop(columns="matchId")
res_bets["B365H"] = 1 / res_bets["B365H"]
res_bets["B365D"] = 1 / res_bets["B365D"]
res_bets["B365A"] = 1 / res_bets["B365A"]
ut.save_dataframe(res_bets,ut.SAVE_PATH,name_of_file="logits_bets",to_excel=True,sheet_name='logits_bets')
res_bets

,match,Date,season,Div,HomeTeam,AwayTeam,FTHG,FTAG,label,prediction_lgbm_top1_ss_logits,...,draw_tabnet_owntop1_comp_ss_sup_logits,home_tabnet_owntop1_comp_ss_sup_logits,away_tabnet_owntop1_comp_ss_sup_logits,accurate_flag_lgbm_top1_ss_logits,rps_lgbm_top1_ss_logits,accurate_flag_tabnet_owntop1_comp_ss_sup_logits,rps_tabnet_owntop1_comp_ss_sup_logits,B365H,B365D,B365A
0,15751,2020-01-01,T19-20,E0,Brighton,Chelsea,1,1,0.0,2,...,0.5139,0.2421,0.2439,0,0.381474,1.0,0.147915,0.277778,0.277778,0.512821
1,15757,2020-01-01,T19-20,E0,Norwich,Crystal Palace,1,1,0.0,2,...,0.6307,0.2160,0.1532,0,0.350553,1.0,0.079942,0.400000,0.294118,0.363636
2,15754,2020-01-01,T19-20,E0,Southampton,Tottenham,1,0,1.0,1,...,0.2356,0.7244,0.0400,1,0.101380,1.0,0.028554,0.303030,0.285714,0.476190
3,15753,2020-01-01,T19-20,E0,Newcastle,Leicester,0,3,2.0,2,...,0.2081,0.0677,0.7242,1,0.097576,1.0,0.059686,0.200000,0.263158,0.602410
4,15756,2020-01-01,T19-20,E0,Man City,Everton,2,1,1.0,1,...,0.2329,0.7463,0.0208,1,0.014109,1.0,0.027338,0.800000,0.153846,0.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,26489,2021-05-23,T20-21,F1,St Etienne,Dijon,0,1,2.0,1,...,0.2958,0.5845,0.1196,0,0.436432,0.0,0.431213,0.769231,0.181818,0.100000
3239,26490,2021-05-23,T20-21,F1,Strasbourg,Lorient,1,1,0.0,1,...,0.3529,0.2875,0.3596,0,0.288363,0.0,0.274025,0.384615,0.500000,0.230947
3240,44888,2021-05-23,T20-21,SP1,Sevilla,Alaves,1,0,1.0,1,...,0.2415,0.6932,0.0653,1,0.011492,1.0,0.031293,0.666667,0.230947,0.153846
3241,26481,2021-05-23,T20-21,F1,Angers,Lille,1,2,2.0,2,...,0.2813,0.2454,0.4734,1,0.116474,1.0,0.178271,0.100000,0.210526,0.751880
3242,44887,2021-05-23,T20-21,SP1,Granada,Getafe,0,0,0.0,1,...,0.3062,0.1773,0.5165,0,0.260715,0.0,0.374065,0.381679,0.294118,0.384615

In [27]:
res.label.value_counts()

label
1.0    1338
2.0    1049
0.0     856
Name: count, dtype: int64

In [342]:
accurate_flag_cols = ut.filter_list(r"accurate_flag_\w+", ", ".join(res.columns))
res_acc = res[ ut.METADATA + accurate_flag_cols]
names = [ ut.filter_group("accurate_flag_(\w+)",col) for col in res.columns if ut.filter_group("accurate_flag_(\w+)",col)]
rel_test = { name:res_acc[f'accurate_flag_{name}'].mean().round(4) for name in names }

In [343]:
resume["rel_test"] = rel_test
resume.sort_values('rel_test',ascending=False)

                              validation  abs_test  rel_test
tabnet_own_comp_ss                0.5327    0.5021    0.5021
own_original_comp_fac_ss          0.5347    0.4998    0.4998
own_original_simp_fac_ss          0.5312    0.4998    0.4998
tabnet_own_simp_ss_unsup          0.5266    0.4964    0.4964
tabnet_own_comp_ss_sup            0.5314    0.4941    0.4941
tabnet_own_simp_ss_sup            0.5298    0.4941    0.4941
tabnet_own_comp_rs_unsup          0.5220    0.4922    0.4922
own_original_comp_bal_fac_ss      0.4814    0.4623    0.4869
tabnet_paper_ss_unsup             0.5180    0.4857    0.4846
tabnet_paper_rs_unsup             0.5063    0.4807    0.4838

### RPS

In [344]:
res

,match,Date,season,Div,HomeTeam,AwayTeam,FTHG,FTAG,label,prediction_own_original_comp_bal_fac_ss,...,accurate_flag_own_original_comp_bal_fac_ss,accurate_flag_own_original_comp_fac_ss,accurate_flag_own_original_simp_fac_ss,accurate_flag_tabnet_own_comp_rs_unsup,accurate_flag_tabnet_own_comp_ss,accurate_flag_tabnet_own_comp_ss_sup,accurate_flag_tabnet_own_simp_ss_sup,accurate_flag_tabnet_own_simp_ss_unsup,accurate_flag_tabnet_paper_rs_unsup,accurate_flag_tabnet_paper_ss_unsup
0,15751,2020-01-01,T19-20,E0,Brighton,Chelsea,1,1,0,2,...,0,0,0,0,0,0,0,0,0,0
1,15757,2020-01-01,T19-20,E0,Norwich,Crystal Palace,1,1,0,2,...,0,0,0,0,0,0,0,0,0,0
2,15756,2020-01-01,T19-20,E0,Man City,Everton,2,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,15752,2020-01-01,T19-20,E0,Burnley,Aston Villa,1,2,2,0,...,0,0,0,0,0,0,0,0,0,0
4,15755,2020-01-01,T19-20,E0,Watford,Wolves,2,1,1,2,...,0,0,0,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2626,26489,2021-05-23,T20-21,F1,St Etienne,Dijon,0,1,2,1,...,0,0,0,0,0,0,0,0,0,0
2627,26487,2021-05-23,T20-21,F1,Reims,Bordeaux,1,2,2,0,...,0,0,0,0,0,0,0,0,0,1
2628,26486,2021-05-23,T20-21,F1,Nantes,Montpellier,1,2,2,0,...,0,0,0,0,0,0,0,0,0,0
2629,26488,2021-05-23,T20-21,F1,Rennes,Nimes,2,0,1,1,...,1,1,1,1,1,1,1,1,1,1
2630,26490,2021-05-23,T20-21,F1,Strasbourg,Lorient,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [346]:
outcomes = res[['draw_tabnet_own_comp_ss','home_tabnet_own_comp_ss','away_tabnet_own_comp_ss']].values
labels = pd.get_dummies(res.label).astype(float).values

resta = abs(outcomes - labels)
resta

array([[0.7526, 0.3026, 0.45  ],
       [0.725 , 0.3305, 0.3945],
       [0.1584, 0.2485, 0.0901],
       ...,
       [0.2961, 0.4702, 0.7663],
       [0.2763, 0.4394, 0.1631],
       [0.7167, 0.4842, 0.2325]])

In [350]:
rps_dict = { name:ut.compute_rps(res,name)[0] for name in names }
rps_dict
resume['RPS'] = rps_dict
resume.sort_values('RPS')

                              validation  abs_test  rel_test     RPS
tabnet_own_comp_ss                0.5327    0.5021    0.5021  0.1926
own_original_comp_fac_ss          0.5347    0.4998    0.4998  0.1931
tabnet_own_comp_ss_sup            0.5314    0.4941    0.4941  0.1934
tabnet_own_comp_rs_unsup          0.5220    0.4922    0.4922  0.1938
own_original_simp_fac_ss          0.5312    0.4998    0.4998  0.1945
tabnet_own_simp_ss_unsup          0.5266    0.4964    0.4964  0.1947
own_original_comp_bal_fac_ss      0.4814    0.4623    0.4869  0.1949
tabnet_own_simp_ss_sup            0.5298    0.4941    0.4941  0.1956
tabnet_paper_rs_unsup             0.5063    0.4807    0.4838  0.1974
tabnet_paper_ss_unsup             0.5180    0.4857    0.4846  0.1982

### MAKE RESUM

In [15]:
il.reload(ut)

experiments = ['lgbm_top1_rs',
 'own_original_comp_bal_fac_ss',
 'own_original_simp_fac_ss',
 'own_top1_adv_comp_fac_ss_miv2',
 'tabnet_owntop1_comp_ss_sup',
 'tabnet_own_simp_ss_sup',
 'tabnet_paper_ss_unsup',
 'tabnet_own_comp_rs_unsup_rps']

# ut.make_resume([r'(\w+)'],title='resume_v2.2_rps',save=1).columns
ut.make_resume(experiments,title='deep_analysis',save=1).columns

^lgbm_top1_rs_metrics|own_original_comp_bal_fac_ss_metrics|own_original_simp_fac_ss_metrics|own_top1_adv_comp_fac_ss_miv2_metrics|tabnet_owntop1_comp_ss_sup_metrics|tabnet_own_simp_ss_sup_metrics|tabnet_paper_ss_unsup_metrics|tabnet_own_comp_rs_unsup_rps_metrics\.csv$

IndexError: tuple index out of range

In [40]:
il.reload(ut)
ut.make_resume([r'own_top1_comp_fac_ss_(miold|v0\.\d)'],title='versions_v0',save=True)
ut.make_resume([r'own_top1_comp_fac_ss_(v1(.*))'],title='versions_v1',save=True)
# ut.make_resume([r'own_top1_comp_fac_ss_(.+)'],title='versions',save=True)

['own_top1_comp_fac_ss_miold_logits', 'own_top1_comp_fac_ss_v0.1_logits', 'own_top1_comp_fac_ss_v0.2_logits', 'own_top1_comp_fac_ss_v0.3_logits']
Getting aliases...
['own_top1_comp_fac_ss_v1.3_logits', 'own_top1_comp_fac_ss_v1_logits']
Getting aliases...

      validation  abs_test     RPS  rel_test
v1.3      0.6982    0.6525  0.1556    0.6537
v1        0.5363    0.5029  0.1948    0.5029

In [48]:
df = pd.DataFrame({'c1':[1,0,1,0,1,0],'c2':[1,None,0,0,None,1]})
ind = df.c2.dropna().index
df['ceq'] = (df.c1.loc[ind]==df.c2[ind]).astype(int)
df

   c1   c2  ceq
0   1  1.0  1.0
1   0  NaN  NaN
2   1  0.0  0.0
3   0  0.0  1.0
4   1  NaN  NaN
5   0  1.0  0.0

DECIDIR QUE MODELOS LANZAR A ENTRENAR DE NUEVO
1. Preparar modelos con LightGBM
2. Preparar modelo Top1
3. Preparar mis modelos + atributos Top1
4. Investigar Embeddings
5. Investigar Scrapping

### COMPUTE RECALL AND PRECISION

In [10]:
logits = pd.read_excel("F:\TFG\code\\framework\logs\\resume.xlsx",sheet_name='Logits')

In [11]:
logits

,match,Date,season,Div,HomeTeam,AwayTeam,FTHG,FTAG,label,prediction_lgbm_top1_rs,...,accurate_flag_tabnet_own_comp_ss_sup,rps_tabnet_own_comp_ss_sup,accurate_flag_tabnet_own_simp_ss_sup,rps_tabnet_own_simp_ss_sup,accurate_flag_tabnet_own_simp_ss_unsup,rps_tabnet_own_simp_ss_unsup,accurate_flag_tabnet_paper_rs_unsup,rps_tabnet_paper_rs_unsup,accurate_flag_tabnet_paper_ss_unsup,rps_tabnet_paper_ss_unsup
0,15751,2020-01-01,T19-20,E0,Brighton,Chelsea,1,1,0,2,...,0.0,0.4254,0.0,0.3788,0.0,0.3768,0,0.5717,0,0.4356
1,15757,2020-01-01,T19-20,E0,Norwich,Crystal Palace,1,1,0,2,...,0.0,0.2757,0.0,0.3592,0.0,0.3657,0,0.3470,0,0.2870
2,15754,2020-01-01,T19-20,E0,Southampton,Tottenham,1,0,1,1,...,0.0,0.1744,0.0,0.1509,0.0,0.1921,0,0.1137,0,0.1509
3,15753,2020-01-01,T19-20,E0,Newcastle,Leicester,0,3,2,2,...,1.0,0.1856,0.0,0.2650,1.0,0.2524,0,0.3700,0,0.3028
4,15756,2020-01-01,T19-20,E0,Man City,Everton,2,1,1,1,...,1.0,0.0093,1.0,0.0121,1.0,0.0143,1,0.0174,1,0.0183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,26489,2021-05-23,T20-21,F1,St Etienne,Dijon,0,1,2,1,...,0.0,0.2862,0.0,0.2367,0.0,0.3744,0,0.3601,0,0.3777
3239,26490,2021-05-23,T20-21,F1,Strasbourg,Lorient,1,1,0,1,...,0.0,0.2634,0.0,0.3070,0.0,0.2781,0,0.3037,0,0.2749
3240,44888,2021-05-23,T20-21,SP1,Sevilla,Alaves,1,0,1,1,...,1.0,0.0696,1.0,0.0291,1.0,0.0352,1,0.0177,1,0.0271
3241,26481,2021-05-23,T20-21,F1,Angers,Lille,1,2,2,2,...,1.0,0.1676,1.0,0.1552,1.0,0.2206,1,0.1209,1,0.1622
3242,44887,2021-05-23,T20-21,SP1,Granada,Getafe,0,0,0,1,...,0.0,0.2951,0.0,0.3132,0.0,0.2742,0,0.3021,0,0.2809

In [12]:
logits.columns

Index(['match', 'Date', 'season', 'Div', 'HomeTeam', 'AwayTeam', 'FTHG',
       'FTAG', 'label', 'prediction_lgbm_top1_rs', 'draw_lgbm_top1_rs',
       'home_lgbm_top1_rs', 'away_lgbm_top1_rs', 'prediction_lgbm_top1_ss',
       'draw_lgbm_top1_ss', 'home_lgbm_top1_ss', 'away_lgbm_top1_ss',
       'prediction_own_original_comp_bal_fac_ss',
       'draw_own_original_comp_bal_fac_ss',
       'home_own_original_comp_bal_fac_ss',
       'away_own_original_comp_bal_fac_ss',
       'prediction_own_original_comp_fac_ss', 'draw_own_original_comp_fac_ss',
       'home_own_original_comp_fac_ss', 'away_own_original_comp_fac_ss',
       'prediction_own_original_simp_fac_ss', 'draw_own_original_simp_fac_ss',
       'home_own_original_simp_fac_ss', 'away_own_original_simp_fac_ss',
       'prediction_tabnet_own_comp_rs_unsup', 'draw_tabnet_own_comp_rs_unsup',
       'home_tabnet_own_comp_rs_unsup', 'away_tabnet_own_comp_rs_unsup',
       'prediction_tabnet_own_comp_ss', 'draw_tabnet_own_comp_ss',
       'home_tabnet_own_comp_ss', 'away_tabnet_own_comp_ss',
       'prediction_tabnet_own_comp_ss_sup', 'draw_tabnet_own_comp_ss_sup',
       'home_tabnet_own_comp_ss_sup', 'away_tabnet_own_comp_ss_sup',
       'prediction_tabnet_own_simp_ss_sup', 'draw_tabnet_own_simp_ss_sup',
       'home_tabnet_own_simp_ss_sup', 'away_tabnet_own_simp_ss_sup',
       'prediction_tabnet_own_simp_ss_unsup', 'draw_tabnet_own_simp_ss_unsup',
       'home_tabnet_own_simp_ss_unsup', 'away_tabnet_own_simp_ss_unsup',
       'prediction_tabnet_paper_rs_unsup', 'draw_tabnet_paper_rs_unsup',
       'home_tabnet_paper_rs_unsup', 'away_tabnet_paper_rs_unsup',
       'prediction_tabnet_paper_ss_unsup', 'draw_tabnet_paper_ss_unsup',
       'home_tabnet_paper_ss_unsup', 'away_tabnet_paper_ss_unsup',
       'accurate_flag_lgbm_top1_rs', 'rps_lgbm_top1_rs',
       'accurate_flag_lgbm_top1_ss', 'rps_lgbm_top1_ss',
       'accurate_flag_own_original_comp_bal_fac_ss',
       'rps_own_original_comp_bal_fac_ss',
       'accurate_flag_own_original_comp_fac_ss',
       'rps_own_original_comp_fac_ss',
       'accurate_flag_own_original_simp_fac_ss',
       'rps_own_original_simp_fac_ss',
       'accurate_flag_tabnet_own_comp_rs_unsup',
       'rps_tabnet_own_comp_rs_unsup', 'accurate_flag_tabnet_own_comp_ss',
       'rps_tabnet_own_comp_ss', 'accurate_flag_tabnet_own_comp_ss_sup',
       'rps_tabnet_own_comp_ss_sup', 'accurate_flag_tabnet_own_simp_ss_sup',
       'rps_tabnet_own_simp_ss_sup', 'accurate_flag_tabnet_own_simp_ss_unsup',
       'rps_tabnet_own_simp_ss_unsup', 'accurate_flag_tabnet_paper_rs_unsup',
       'rps_tabnet_paper_rs_unsup', 'accurate_flag_tabnet_paper_ss_unsup',
       'rps_tabnet_paper_ss_unsup'],
      dtype='object')

In [18]:
names = [ ut.filter_group("accurate_flag_(.+)",col) for col in logits.columns if ut.filter_group("accurate_flag_(.+)",col)]
names

['lgbm_top1_rs',
 'lgbm_top1_ss',
 'own_original_comp_bal_fac_ss',
 'own_original_comp_fac_ss',
 'own_original_simp_fac_ss',
 'tabnet_own_comp_rs_unsup',
 'tabnet_own_comp_ss',
 'tabnet_own_comp_ss_sup',
 'tabnet_own_simp_ss_sup',
 'tabnet_own_simp_ss_unsup',
 'tabnet_paper_rs_unsup',
 'tabnet_paper_ss_unsup']

In [64]:
aggs = { name:pd.NamedAgg(f'accurate_flag_{name}','mean') for name in names }
aggs

{'lgbm_top1_rs': NamedAgg(column='accurate_flag_lgbm_top1_rs', aggfunc='mean'),
 'lgbm_top1_ss': NamedAgg(column='accurate_flag_lgbm_top1_ss', aggfunc='mean'),
 'own_original_comp_bal_fac_ss': NamedAgg(column='accurate_flag_own_original_comp_bal_fac_ss', aggfunc='mean'),
 'own_original_comp_fac_ss': NamedAgg(column='accurate_flag_own_original_comp_fac_ss', aggfunc='mean'),
 'own_original_simp_fac_ss': NamedAgg(column='accurate_flag_own_original_simp_fac_ss', aggfunc='mean'),
 'tabnet_own_comp_rs_unsup': NamedAgg(column='accurate_flag_tabnet_own_comp_rs_unsup', aggfunc='mean'),
 'tabnet_own_comp_ss': NamedAgg(column='accurate_flag_tabnet_own_comp_ss', aggfunc='mean'),
 'tabnet_own_comp_ss_sup': NamedAgg(column='accurate_flag_tabnet_own_comp_ss_sup', aggfunc='mean'),
 'tabnet_own_simp_ss_sup': NamedAgg(column='accurate_flag_tabnet_own_simp_ss_sup', aggfunc='mean'),
 'tabnet_own_simp_ss_unsup': NamedAgg(column='accurate_flag_tabnet_own_simp_ss_unsup', aggfunc='mean'),
 'tabnet_paper_rs_unsup': NamedAgg(column='accurate_flag_tabnet_paper_rs_unsup', aggfunc='mean'),
 'tabnet_paper_ss_unsup': NamedAgg(column='accurate_flag_tabnet_paper_ss_unsup', aggfunc='mean')}

In [65]:
recall = logits.groupby('label').agg(**aggs)
recall = recall.rename({0:'recall_draw',1:'recall_home',2:'recall_away'})
recall

,lgbm_top1_rs,lgbm_top1_ss,own_original_comp_bal_fac_ss,own_original_comp_fac_ss,own_original_simp_fac_ss,tabnet_own_comp_rs_unsup,tabnet_own_comp_ss,tabnet_own_comp_ss_sup,tabnet_own_simp_ss_sup,tabnet_own_simp_ss_unsup,tabnet_paper_rs_unsup,tabnet_paper_ss_unsup
label,,,,,,,,,,,,
recall_draw,0.108645,0.091121,0.381690,0.000000,0.000000,0.000000,0.007042,0.002817,0.021127,0.000000,0.001168,0.002336
recall_home,0.866218,0.870703,0.563985,0.883912,0.872943,0.890311,0.875686,0.863803,0.869287,0.895795,0.866218,0.877429
recall_away,0.566254,0.559581,0.475212,0.420798,0.435308,0.388150,0.432890,0.426844,0.403869,0.394196,0.380362,0.380362

In [66]:
precision = logits.groupby('prediction_lgbm_top1_rs').agg(**aggs)
precision = precision.rename({0:'precision_draw',1:'precision_home',2:'precision_away'})
precision

,lgbm_top1_rs,lgbm_top1_ss,own_original_comp_bal_fac_ss,own_original_comp_fac_ss,own_original_simp_fac_ss,tabnet_own_comp_rs_unsup,tabnet_own_comp_ss,tabnet_own_comp_ss_sup,tabnet_own_simp_ss_sup,tabnet_own_simp_ss_unsup,tabnet_paper_rs_unsup,tabnet_paper_ss_unsup
prediction_lgbm_top1_rs,,,,,,,,,,,,
precision_draw,0.516667,0.472222,0.438462,0.261538,0.253846,0.246154,0.253846,0.238462,0.261538,0.238462,0.272222,0.294444
precision_home,0.541589,0.542523,0.468025,0.525184,0.518959,0.526316,0.523486,0.521788,0.520656,0.524052,0.519626,0.526636
precision_away,0.643554,0.632719,0.540872,0.480926,0.497275,0.453678,0.494550,0.472752,0.471390,0.475477,0.431203,0.427952

In [68]:
res = pd.concat([recall,precision]).T
res

,recall_draw,recall_home,recall_away,precision_draw,precision_home,precision_away
lgbm_top1_rs,0.108645,0.866218,0.566254,0.516667,0.541589,0.643554
lgbm_top1_ss,0.091121,0.870703,0.559581,0.472222,0.542523,0.632719
own_original_comp_bal_fac_ss,0.381690,0.563985,0.475212,0.438462,0.468025,0.540872
own_original_comp_fac_ss,0.000000,0.883912,0.420798,0.261538,0.525184,0.480926
own_original_simp_fac_ss,0.000000,0.872943,0.435308,0.253846,0.518959,0.497275
tabnet_own_comp_rs_unsup,0.000000,0.890311,0.388150,0.246154,0.526316,0.453678
tabnet_own_comp_ss,0.007042,0.875686,0.432890,0.253846,0.523486,0.494550
tabnet_own_comp_ss_sup,0.002817,0.863803,0.426844,0.238462,0.521788,0.472752
tabnet_own_simp_ss_sup,0.021127,0.869287,0.403869,0.261538,0.520656,0.471390
tabnet_own_simp_ss_unsup,0.000000,0.895795,0.394196,0.238462,0.524052,0.475477
tabnet_paper_rs_unsup,0.001168,0.866218,0.380362,0.272222,0.519626,0.431203
tabnet_paper_ss_unsup,0.002336,0.877429,0.380362,0.294444,0.526636,0.427952

In [71]:
for label in ['draw','home','away']:
    res[f'F1_{label}'] = 2*res[f'precision_{label}']*res[f'recall_{label}'] / (res[f'precision_{label}']+res[f'recall_{label}'])
res

,recall_draw,recall_home,recall_away,precision_draw,precision_home,precision_away,F1_draw,F1_home,F1_away
lgbm_top1_rs,0.108645,0.866218,0.566254,0.516667,0.541589,0.643554,0.179537,0.666475,0.602434
lgbm_top1_ss,0.091121,0.870703,0.559581,0.472222,0.542523,0.632719,0.152765,0.668508,0.593907
own_original_comp_bal_fac_ss,0.381690,0.563985,0.475212,0.438462,0.468025,0.540872,0.408111,0.511544,0.505920
own_original_comp_fac_ss,0.000000,0.883912,0.420798,0.261538,0.525184,0.480926,0.000000,0.658885,0.448858
own_original_simp_fac_ss,0.000000,0.872943,0.435308,0.253846,0.518959,0.497275,0.000000,0.650939,0.464233
tabnet_own_comp_rs_unsup,0.000000,0.890311,0.388150,0.246154,0.526316,0.453678,0.000000,0.661550,0.418364
tabnet_own_comp_ss,0.007042,0.875686,0.432890,0.253846,0.523486,0.494550,0.013704,0.655258,0.461670
tabnet_own_comp_ss_sup,0.002817,0.863803,0.426844,0.238462,0.521788,0.472752,0.005568,0.650585,0.448627
tabnet_own_simp_ss_sup,0.021127,0.869287,0.403869,0.261538,0.520656,0.471390,0.039095,0.651249,0.435025
tabnet_own_simp_ss_unsup,0.000000,0.895795,0.394196,0.238462,0.524052,0.475477,0.000000,0.661259,0.431038
tabnet_paper_rs_unsup,0.001168,0.866218,0.380362,0.272222,0.519626,0.431203,0.002326,0.649582,0.404190
tabnet_paper_ss_unsup,0.002336,0.877429,0.380362,0.294444,0.526636,0.427952,0.004636,0.658211,0.402756

### end